<?php $slug = 'bitcoin-suisse-adgm-abu-dhabi-license'; require __DIR__.'/_header.php'; ?>

  <p class="ko">스위스 크립토 금융사 <strong>비트코인 스위스(Bitcoin Suisse)</strong>는 중동 자회사 BTCS(Middle East) Ltd.가 아부다비글로벌마켓(ADGM) 금융서비스규제청(FSRA)으로부터 금융서비스허가(Financial Services Permission, FSP)를 받았다고 7월 7일 밝혔다. 이번 인가로 BTCS ME는 아랍에미리트(UAE) 내 기관·전문투자자 고객을 대상으로 디지털자산 거래·커스터디·헤징 등 규제 서비스를 정식 제공할 수 있게 됐다고 <strong>비즈니스와이어</strong>와 <strong>CoinDesk</strong>가 전했다. 2013년 스위스 추크에서 설립된 비트코인 스위스는 스위스·리히텐슈타인·UAE·버뮤다에 200명 이상의 인력을 두고 약 37억 달러 규모의 디지털자산을 보관 중이며, 세계 4위 규모의 스테이킹 운영사로 알려져 있다.</p>
  <p class="en"><strong>Bitcoin Suisse</strong>, the Swiss crypto financial firm, said on July 7 that its Middle East subsidiary, BTCS (Middle East) Ltd., received a Financial Services Permission (FSP) from the Financial Services Regulatory Authority (FSRA) of Abu Dhabi Global Market (ADGM). The permission lets BTCS ME formally offer regulated digital-asset services — trading, custody and hedging — to institutional and professional clients in the United Arab Emirates, according to <strong>Businesswire</strong> and <strong>CoinDesk</strong>. Founded in Zug, Switzerland in 2013, Bitcoin Suisse employs more than 200 people across Switzerland, Liechtenstein, the UAE and Bermuda, safeguards roughly $3.7 billion in digital assets, and is reported to be the world's fourth-largest staking operator.</p>
  <p class="ja">スイスの暗号資産金融会社<strong>ビットコイン・スイス(Bitcoin Suisse)</strong>は7月7日、中東子会社BTCS(Middle East) Ltd.がアブダビ・グローバル・マーケット(ADGM)の金融サービス規制庁(FSRA)から金融サービス許可(FSP)を取得したと明らかにした。この認可により、BTCS MEはアラブ首長国連邦(UAE)内の機関・プロ投資家顧客向けに、デジタル資産の取引・カストディ・ヘッジといった規制サービスを正式に提供できるようになったと<strong>ビジネスワイヤ</strong>と<strong>CoinDesk</strong>が伝えた。2013年にスイスのツークで設立されたビットコイン・スイスは、スイス・リヒテンシュタイン・UAE・バミューダに200人超の従業員を抱え、約37億ドル相当のデジタル資産を保管しており、世界第4位規模のステーキング運営会社と報じられている。</p>
  <p class="es">La firma financiera cripto suiza <strong>Bitcoin Suisse</strong> anunció el 7 de julio que su filial en Oriente Medio, BTCS (Middle East) Ltd., recibió un Permiso de Servicios Financieros (FSP) de la Autoridad Regulatoria de Servicios Financieros (FSRA) del Abu Dhabi Global Market (ADGM). El permiso permite a BTCS ME ofrecer formalmente servicios regulados de activos digitales —trading, custodia y cobertura— a clientes institucionales y profesionales en los Emiratos Árabes Unidos (EAU), según <strong>Businesswire</strong> y <strong>CoinDesk</strong>. Fundada en Zug, Suiza, en 2013, Bitcoin Suisse emplea a más de 200 personas en Suiza, Liechtenstein, los EAU y Bermudas, resguarda cerca de 3.700 millones de dólares en activos digitales y se reporta como el cuarto mayor operador de staking del mundo.</p>
  <p class="de">Das Schweizer Krypto-Finanzunternehmen <strong>Bitcoin Suisse</strong> teilte am 7. Juli mit, dass seine Nahost-Tochter BTCS (Middle East) Ltd. eine Finanzdienstleistungserlaubnis (FSP) von der Finanzdienstleistungsaufsicht (FSRA) des Abu Dhabi Global Market (ADGM) erhalten hat. Die Erlaubnis ermöglicht es BTCS ME, institutionellen und professionellen Kunden in den Vereinigten Arabischen Emiraten (VAE) formell regulierte Dienstleistungen für digitale Vermögenswerte anzubieten — Handel, Verwahrung und Hedging —, wie <strong>Businesswire</strong> und <strong>CoinDesk</strong> berichteten. Das 2013 in Zug, Schweiz, gegründete Unternehmen Bitcoin Suisse beschäftigt über 200 Mitarbeiter in der Schweiz, Liechtenstein, den VAE und Bermuda, verwahrt rund 3,7 Milliarden Dollar an digitalen Vermögenswerten und gilt Berichten zufolge als viertgrößter Staking-Betreiber der Welt.</p>
  <p class="fr">La société financière crypto suisse <strong>Bitcoin Suisse</strong> a annoncé le 7 juillet que sa filiale au Moyen-Orient, BTCS (Middle East) Ltd., a reçu une autorisation de services financiers (FSP) de la FSRA (Financial Services Regulatory Authority) de l'Abu Dhabi Global Market (ADGM). Cette autorisation permet à BTCS ME d'offrir officiellement des services réglementés d'actifs numériques — trading, garde et couverture — à des clients institutionnels et professionnels aux Émirats arabes unis (EAU), selon <strong>Businesswire</strong> et <strong>CoinDesk</strong>. Fondée à Zoug, en Suisse, en 2013, Bitcoin Suisse emploie plus de 200 personnes en Suisse, au Liechtenstein, aux EAU et aux Bermudes, conserve environ 3,7 milliards de dollars d'actifs numériques et serait le quatrième plus grand opérateur de staking au monde.</p>
  <p class="pt">A empresa financeira suíça de cripto <strong>Bitcoin Suisse</strong> informou em 7 de julho que sua subsidiária no Oriente Médio, a BTCS (Middle East) Ltd., recebeu uma Permissão de Serviços Financeiros (FSP) da Autoridade Reguladora de Serviços Financeiros (FSRA) do Abu Dhabi Global Market (ADGM). A permissão possibilita que a BTCS ME ofereça formalmente serviços regulados de ativos digitais — negociação, custódia e hedge — a clientes institucionais e profissionais nos Emirados Árabes Unidos (EAU), segundo a <strong>Businesswire</strong> e o <strong>CoinDesk</strong>. Fundada em Zug, na Suíça, em 2013, a Bitcoin Suisse emprega mais de 200 pessoas na Suíça, em Liechtenstein, nos EAU e nas Bermudas, guarda cerca de US$ 3,7 bilhões em ativos digitais e é apontada como a quarta maior operadora de staking do mundo.</p>
  <p class="tr">İsviçreli kripto finans şirketi <strong>Bitcoin Suisse</strong>, 7 Temmuz'da Orta Doğu iştiraki BTCS (Middle East) Ltd.'in Abu Dabi Global Market'in (ADGM) Finansal Hizmetler Düzenleme Otoritesi'nden (FSRA) Finansal Hizmetler İzni (FSP) aldığını duyurdu. Bu izin, BTCS ME'nin Birleşik Arap Emirlikleri'nde (BAE) kurumsal ve profesyonel müşterilere yönelik düzenlenmiş dijital varlık hizmetlerini — alım satım, saklama ve hedge — resmen sunmasına olanak tanıyor; bunu <strong>Businesswire</strong> ve <strong>CoinDesk</strong> bildirdi. 2013'te İsviçre'nin Zug kentinde kurulan Bitcoin Suisse, İsviçre, Liechtenstein, BAE ve Bermuda'da 200'den fazla çalışana sahip, yaklaşık 3,7 milyar dolarlık dijital varlığı koruma altında tutuyor ve dünyanın dördüncü büyük staking operatörü olarak bildiriliyor.</p>
  <p class="vi">Công ty tài chính crypto Thụy Sĩ <strong>Bitcoin Suisse</strong> cho biết ngày 7/7 rằng công ty con tại Trung Đông, BTCS (Middle East) Ltd., đã nhận Giấy Phép Dịch Vụ Tài Chính (FSP) từ Cơ Quan Quản Lý Dịch Vụ Tài Chính (FSRA) của Abu Dhabi Global Market (ADGM). Giấy phép cho phép BTCS ME chính thức cung cấp các dịch vụ tài sản số được quản lý — giao dịch, lưu ký và phòng hộ — cho khách hàng định chế và chuyên nghiệp tại Các Tiểu Vương Quốc Ả Rập Thống Nhất (UAE), theo <strong>Businesswire</strong> và <strong>CoinDesk</strong>. Thành lập tại Zug, Thụy Sĩ năm 2013, Bitcoin Suisse có hơn 200 nhân viên tại Thụy Sĩ, Liechtenstein, UAE và Bermuda, bảo quản khoảng 3,7 tỷ USD tài sản số, và được cho là nhà vận hành staking lớn thứ tư thế giới.</p>

  <div class="box ko">💡 <strong>핵심 요약:</strong> 관건은 '왜 두바이가 아니라 아부다비인가'다. 두바이는 2022년 설립된 가상자산 전담 규제기관 VARA가 관장하며 소매 중심·역내 사업자를 겨냥한다. 반면 ADGM은 2018년부터 영국식 보통법 체계 위에서 암호자산 프레임워크를 운영해온, 기관 등급 규제를 표방하는 관할권이다. 두 체제는 서로 패스포팅(상호인정)되지 않는다 — 기업은 둘 중 하나를 골라야 한다. 비트코인 스위스가 ADGM을 택한 것은 기관 고객을 노린 전략적 선택으로 읽힌다.</div>
  <div class="box en">💡 <strong>Key takeaway:</strong> The real question is why Abu Dhabi and not Dubai. Dubai's crypto activity is overseen by VARA, a dedicated virtual-asset regulator founded in 2022 that targets retail-facing, regionally oriented operators. ADGM, by contrast, has run a crypto-asset framework under English common law since 2018 and markets itself as an institutional-grade jurisdiction. The two regimes do not passport into each other — a firm must pick one. Bitcoin Suisse's choice of ADGM reads as a deliberate bet on institutional clients.</div>
  <div class="box ja">💡 <strong>要点:</strong> 焦点は『なぜドバイではなくアブダビなのか』だ。ドバイの暗号資産活動は2022年設立の専門規制機関VARAが管轄し、小売志向・地域事業者を主な対象とする。対照的にADGMは2018年から英国式コモンローの下で暗号資産フレームワークを運用しており、機関投資家向けの管轄区であることを標榜する。両体制は相互にパスポーティング(相互承認)されない——企業はどちらか一方を選ばねばならない。ビットコイン・スイスがADGMを選んだのは、機関投資家顧客を狙った戦略的選択と読める。</div>
  <div class="box es">💡 <strong>Conclusión clave:</strong> La pregunta real es por qué Abu Dabi y no Dubái. La actividad cripto de Dubái está supervisada por VARA, un regulador dedicado a activos virtuales fundado en 2022 que apunta a operadores minoristas y regionales. El ADGM, en cambio, opera un marco de activos cripto bajo el derecho consuetudinario inglés desde 2018 y se presenta como una jurisdicción de grado institucional. Ambos regímenes no se pasaportan entre sí: una firma debe elegir uno. La elección del ADGM por parte de Bitcoin Suisse se lee como una apuesta deliberada por clientes institucionales.</div>
  <div class="box de">💡 <strong>Kernaussage:</strong> Die eigentliche Frage ist, warum Abu Dhabi und nicht Dubai. Dubais Krypto-Aktivität wird von VARA beaufsichtigt, einer 2022 gegründeten dedizierten Regulierungsbehörde für virtuelle Vermögenswerte, die auf retailorientierte, regionale Betreiber zielt. ADGM dagegen betreibt seit 2018 ein Krypto-Asset-Rahmenwerk nach englischem Common Law und positioniert sich als institutionelle Jurisdiktion. Die beiden Regime lassen sich nicht gegenseitig passporten — eine Firma muss sich für eines entscheiden. Bitcoin Suisses Wahl von ADGM liest sich als bewusste Wette auf institutionelle Kunden.</div>
  <div class="box fr">💡 <strong>À retenir :</strong> La vraie question est pourquoi Abou Dabi et non Dubaï. L'activité crypto de Dubaï est supervisée par VARA, un régulateur dédié aux actifs virtuels fondé en 2022 qui cible des opérateurs orientés vers le grand public et régionaux. L'ADGM, en revanche, exploite depuis 2018 un cadre pour actifs crypto sous le droit commun anglais et se positionne comme une juridiction de niveau institutionnel. Les deux régimes ne se passeportent pas mutuellement — une firme doit en choisir un. Le choix de l'ADGM par Bitcoin Suisse se lit comme un pari délibéré sur la clientèle institutionnelle.</div>
  <div class="box pt">💡 <strong>Ponto principal:</strong> A questão real é por que Abu Dhabi e não Dubai. A atividade cripto de Dubai é supervisionada pela VARA, um regulador dedicado a ativos virtuais fundado em 2022 que mira operadores voltados ao varejo e regionais. Já o ADGM opera desde 2018 um arcabouço para ativos cripto sob o direito consuetudinário inglês e se posiciona como jurisdição de nível institucional. Os dois regimes não têm passaporte mútuo — uma empresa deve escolher um. A escolha do ADGM pela Bitcoin Suisse soa como uma aposta deliberada em clientes institucionais.</div>
  <div class="box tr">💡 <strong>Ana çıkarım:</strong> Asıl soru şu: neden Dubai değil de Abu Dabi? Dubai'nin kripto faaliyeti, 2022'de kurulan ve perakende odaklı, bölgesel operatörleri hedefleyen özel bir sanal varlık düzenleyicisi olan VARA tarafından denetleniyor. ADGM ise 2018'den beri İngiliz common law sistemi altında bir kripto varlık çerçevesi işletiyor ve kendini kurumsal düzeyde bir yargı alanı olarak konumlandırıyor. İki rejim birbirine pasaportlanmıyor — bir şirket ikisinden birini seçmek zorunda. Bitcoin Suisse'in ADGM'yi seçmesi, kurumsal müşterilere yönelik bilinçli bir bahis olarak okunuyor.</div>
  <div class="box vi">💡 <strong>Điểm chính:</strong> Câu hỏi thật sự là tại sao Abu Dhabi mà không phải Dubai. Hoạt động crypto tại Dubai được VARA giám sát — cơ quan quản lý tài sản ảo chuyên trách thành lập năm 2022, nhắm tới các nhà vận hành hướng bán lẻ, mang tính khu vực. Ngược lại, ADGM đã vận hành khung pháp lý tài sản crypto theo thông luật Anh từ năm 2018 và tự định vị là khu vực pháp lý đẳng cấp định chế. Hai chế độ này không "hộ chiếu hóa" lẫn nhau — một công ty phải chọn một trong hai. Việc Bitcoin Suisse chọn ADGM được hiểu như một canh bạc có chủ đích nhắm vào khách hàng định chế.</div>

  <div class="ko">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16.5" font-weight="700" font-family="sans-serif">비트코인 스위스의 규제 라이선스 확장 타임라인</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">2013년 설립 이후 스위스 → 리히텐슈타인 → UAE로 이어진 발자국</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">2013 · 스위스 추크 설립 (FINMA 감독)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">리히텐슈타인 — MiCA 인가 획득</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="14" font-weight="700" font-family="sans-serif">2026.7 · 아부다비 ADGM — FSP 신규 획득</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">기관·전문투자자 대상 거래·커스터디·헤징 서비스</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13.5" font-weight="700" font-family="sans-serif">보관 자산 약 37억 달러</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">회사 전체 커스터디 규모</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13.5" font-weight="700" font-family="sans-serif">세계 4위 규모 스테이킹 운영사로 보도</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">기관 채택의 신뢰 지표로 제시</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">출처: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="en">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16.5" font-weight="700" font-family="sans-serif">Bitcoin Suisse's regulatory license expansion timeline</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">From Switzerland to Liechtenstein to the UAE since its 2013 founding</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">2013 · Founded in Zug, Switzerland (FINMA-supervised)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">Liechtenstein — MiCA license secured</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="14" font-weight="700" font-family="sans-serif">Jul 2026 · Abu Dhabi ADGM — new FSP</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">Trading, custody and hedging for institutional clients</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13.5" font-weight="700" font-family="sans-serif">≈$3.7B in digital assets safeguarded</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Firm-wide custody scale</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13.5" font-weight="700" font-family="sans-serif">Reported as world's 4th-largest staking operator</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Cited as an institutional-trust marker</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">Source: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="ja">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16.5" font-weight="700" font-family="sans-serif">ビットコイン・スイスの規制ライセンス拡大タイムライン</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">2013年の設立以来、スイス→リヒテンシュタイン→UAEへの足跡</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">2013年・スイス ツーク設立(FINMA監督)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">リヒテンシュタイン——MiCA認可取得</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="14" font-weight="700" font-family="sans-serif">2026年7月・アブダビADGM——新規FSP取得</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">機関投資家向け取引・カストディ・ヘッジ</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13.5" font-weight="700" font-family="sans-serif">保管資産 約37億ドル</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">会社全体のカストディ規模</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13.5" font-weight="700" font-family="sans-serif">世界第4位のステーキング運営会社と報道</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">機関採択の信頼指標として提示</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">出典: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="es">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15.5" font-weight="700" font-family="sans-serif">Cronología de expansión de licencias de Bitcoin Suisse</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">De Suiza a Liechtenstein y a los EAU desde su fundación en 2013</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="13.5" font-family="sans-serif">2013 · Fundada en Zug, Suiza (supervisada por FINMA)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">Liechtenstein — licencia MiCA obtenida</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="13.5" font-weight="700" font-family="sans-serif">Jul. 2026 · ADGM de Abu Dabi — nuevo FSP</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">Trading, custodia y cobertura para clientes institucionales</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">≈3.700M$ en activos resguardados</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Escala de custodia de toda la firma</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Reportada como el 4.º operador de staking mundial</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Citado como señal de confianza institucional</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">Fuente: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="de">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Zeitleiste der Lizenzerweiterung von Bitcoin Suisse</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">Von der Schweiz über Liechtenstein bis in die VAE seit 2013</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="13.5" font-family="sans-serif">2013 · Gegründet in Zug, Schweiz (FINMA-beaufsichtigt)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">Liechtenstein — MiCA-Lizenz gesichert</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="13.5" font-weight="700" font-family="sans-serif">Jul. 2026 · Abu Dhabi ADGM — neue FSP</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">Handel, Verwahrung und Hedging für institutionelle Kunden</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">≈3,7 Mrd.$ verwahrte Vermögenswerte</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Firmenweiter Custody-Umfang</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Berichtet als viertgrößter Staking-Betreiber weltweit</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Als institutionelles Vertrauenssignal angeführt</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">Quelle: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="fr">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Chronologie d'expansion des licences de Bitcoin Suisse</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">De la Suisse au Liechtenstein puis aux EAU depuis 2013</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="13.5" font-family="sans-serif">2013 · Fondée à Zoug, Suisse (supervisée par la FINMA)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">Liechtenstein — licence MiCA obtenue</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="13.5" font-weight="700" font-family="sans-serif">Juil. 2026 · ADGM d'Abou Dabi — nouvelle FSP</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">Trading, garde et couverture pour clients institutionnels</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">≈3,7 Md$ d'actifs conservés</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Échelle de garde à l'échelle de la firme</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Rapportée comme 4e opérateur de staking mondial</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Citée comme signal de confiance institutionnelle</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">Source : Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="pt">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Linha do tempo de expansão de licenças da Bitcoin Suisse</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">Da Suíça a Liechtenstein e aos EAU desde 2013</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="13.5" font-family="sans-serif">2013 · Fundada em Zug, Suíça (supervisionada pela FINMA)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">Liechtenstein — licença MiCA obtida</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="13.5" font-weight="700" font-family="sans-serif">Jul. 2026 · ADGM de Abu Dhabi — novo FSP</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">Negociação, custódia e hedge para clientes institucionais</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">≈US$ 3,7 bi em ativos guardados</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Escala de custódia de toda a empresa</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Apontada como a 4ª maior operadora de staking</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Citada como sinal de confiança institucional</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">Fonte: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="tr">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Bitcoin Suisse'in lisans genişleme zaman çizelgesi</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">2013 kuruluşundan bu yana İsviçre'den BAE'ye</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="13.5" font-family="sans-serif">2013 · İsviçre'nin Zug kentinde kuruldu (FINMA denetiminde)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">Liechtenstein — MiCA lisansı alındı</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="13.5" font-weight="700" font-family="sans-serif">Tem. 2026 · Abu Dabi ADGM — yeni FSP</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">Kurumsal müşteriler için alım satım, saklama, hedge</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">≈3,7 milyar $ korunan varlık</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Şirket genelinde saklama ölçeği</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Dünyanın 4. büyük staking operatörü olarak bildiriliyor</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Kurumsal güven göstergesi olarak sunuluyor</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">Kaynak: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>
  <div class="vi">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Dòng thời gian mở rộng giấy phép của Bitcoin Suisse</text>
    <text x="20" y="56" fill="#a1a1aa" font-size="13" font-family="sans-serif">Từ Thụy Sĩ đến Liechtenstein rồi UAE kể từ 2013</text>
    <line x1="40" y1="90" x2="40" y2="255" stroke="#3f3f46" stroke-width="2"/>
    <circle cx="40" cy="100" r="7" fill="#71717a"/>
    <text x="60" y="105" fill="#e4e4e7" font-size="13.5" font-family="sans-serif">2013 · Thành lập tại Zug, Thụy Sĩ (giám sát bởi FINMA)</text>
    <circle cx="40" cy="175" r="7" fill="#71717a"/>
    <text x="60" y="180" fill="#e4e4e7" font-size="14" font-family="sans-serif">Liechtenstein — đã có giấy phép MiCA</text>
    <circle cx="40" cy="250" r="8" fill="#0d9488"/>
    <text x="60" y="248" fill="#5eead4" font-size="13.5" font-weight="700" font-family="sans-serif">T7/2026 · ADGM Abu Dhabi — FSP mới</text>
    <text x="60" y="268" fill="#a1a1aa" font-size="13" font-family="sans-serif">Giao dịch, lưu ký, phòng hộ cho khách hàng định chế</text>
    <rect x="20" y="300" width="300" height="60" rx="8" fill="#1c1c1f"/>
    <text x="35" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">≈3,7 tỷ USD tài sản được bảo quản</text>
    <text x="35" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Quy mô lưu ký toàn công ty</text>
    <rect x="340" y="300" width="340" height="60" rx="8" fill="#1c1c1f"/>
    <text x="355" y="325" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Được cho là nhà vận hành staking lớn thứ 4 thế giới</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="12.5" font-family="sans-serif">Được nêu như tín hiệu tin cậy định chế</text>
    <text x="680" y="388" fill="#52525b" font-size="12" text-anchor="end" font-family="sans-serif">Nguồn: Bitcoin Suisse, CoinDesk, crypto.news, FF News</text>
  </svg>
  </div>

  <h2 class="ko">무엇을 승인받았나 — FSRA 금융서비스허가(FSP)의 의미</h2>
  <h2 class="en">What was approved — what an FSRA Financial Services Permission means</h2>
  <h2 class="ja">何が承認されたか——FSRA金融サービス許可(FSP)の意味</h2>
  <h2 class="es">Qué se aprobó — qué significa un Permiso de Servicios Financieros de la FSRA</h2>
  <h2 class="de">Was genehmigt wurde — was eine FSRA-Finanzdienstleistungserlaubnis bedeutet</h2>
  <h2 class="fr">Ce qui a été approuvé — ce que signifie une autorisation de services financiers de la FSRA</h2>
  <h2 class="pt">O que foi aprovado — o que significa uma Permissão de Serviços Financeiros da FSRA</h2>
  <h2 class="tr">Ne onaylandı — FSRA Finansal Hizmetler İzni ne anlama geliyor</h2>
  <h2 class="vi">Điều gì đã được phê duyệt — Giấy Phép Dịch Vụ Tài Chính FSRA nghĩa là gì</h2>

  <p class="ko">이번 FSP 획득으로 BTCS ME는 다단계 인가 절차를 완료하고, UAE 내 기관·전문투자자 고객에게 디지털자산 거래 중개, 커스터디, 크립토 익스포저 관리·헤징을 포함한 종합 규제 서비스를 제공할 수 있게 됐다고 회사는 밝혔다. 비트코인 스위스는 이미 리히텐슈타인에서 MiCA 인가를 확보한 데 이어 이번 승인으로 유럽과 중동 두 곳에서 동시에 규제 발판을 넓히게 됐다. 회사 측은 이번 인가가 '수개월에 걸친 다단계 심사'를 거쳐 나왔다고 설명했다.</p>
  <p class="ko">FSP는 은행업 허가나 포괄적 크립토 거래소 라이선스와는 다르다. ADGM의 금융서비스·시장 규정(FSMR) 아래에서 기업은 자신이 실제로 수행할 활동(딜링, 거래 주선, 커스터디 등)을 구체적으로 신청해야 하며, FSRA는 그 범위에 맞춰 허가를 내준다. 즉 '크립토 라이선스를 땄다'는 한 문장으로 뭉뚱그려지기 쉽지만, 실제로는 승인된 활동 목록 밖의 서비스는 제공할 수 없는 좁고 구체적인 허가다. 또한 FSP는 대상 고객을 '전문투자자(Professional Client)'로 한정하기 때문에, UAE 일반 소매 이용자를 상대로 한 서비스로 곧바로 확장되는 것은 아니다. 규제가 커버하는 범위와 그렇지 않은 범위를 구분하는 것이 이번 뉴스를 정확히 읽는 핵심이다.</p>
  <p class="en">With the FSP, BTCS ME has completed a multi-stage licensing process and can now offer institutional and professional clients in the UAE a full suite of regulated services — brokering digital-asset trades, custody, and managing and hedging crypto exposure — the company said. Having already secured a MiCA license in Liechtenstein, Bitcoin Suisse now expands its regulatory footprint in Europe and the Middle East at the same time. The firm described the approval as the result of "a thorough, multi-stage licensing process" spanning several months.</p>
  <p class="en">An FSP is not the same as a banking license or a blanket crypto-exchange license. Under ADGM's Financial Services and Markets Regulations (FSMR), a firm must apply for specific regulated activities it actually intends to conduct — dealing, arranging deals, custody and so on — and the FSRA grants permission scoped to that list. In other words, "won a crypto license" is easy shorthand, but in practice this is a narrow, activity-specific permission: BTCS ME cannot offer services outside the approved list. The FSP is also restricted to "Professional Clients," so it does not automatically extend to UAE retail users. Separating what the license actually covers from what it does not is the key to reading this news correctly.</p>
  <p class="ja">今回のFSP取得により、BTCS MEは多段階の審査プロセスを完了し、UAE内の機関・プロ投資家顧客にデジタル資産取引の仲介、カストディ、暗号資産エクスポージャーの管理・ヘッジを含む包括的な規制サービスを提供できるようになったと同社は述べた。ビットコイン・スイスはすでにリヒテンシュタインでMiCA認可を確保しており、今回の承認で欧州と中東の両方で規制上の足場を同時に広げることになる。同社は今回の認可について、数カ月にわたる『徹底した多段階の審査』を経たものだと説明した。</p>
  <p class="ja">FSPは銀行業免許や包括的な暗号資産取引所ライセンスとは異なる。ADGMの金融サービス・市場規則(FSMR)の下では、企業は自らが実際に行う活動(ディーリング、取引の斡旋、カストディなど)を具体的に申請する必要があり、FSRAはその範囲に合わせて許可を出す。つまり『暗号資産ライセンスを取得した』とひとくくりにされがちだが、実際には承認された活動リスト以外のサービスは提供できない、狭く具体的な許可だ。またFSPは対象顧客を『プロフェッショナル・クライアント』に限定しているため、UAEの一般小売利用者向けサービスへ直ちに拡張されるわけではない。規制が対象とする範囲とそうでない範囲を区別することが、今回のニュースを正確に読み解く鍵となる。</p>
  <p class="es">Con el FSP, BTCS ME ha completado un proceso de licenciamiento de varias etapas y ahora puede ofrecer a clientes institucionales y profesionales en los EAU un conjunto completo de servicios regulados —intermediación de operaciones con activos digitales, custodia, y gestión y cobertura de exposición cripto—, dijo la compañía. Habiendo ya asegurado una licencia MiCA en Liechtenstein, Bitcoin Suisse ahora expande su presencia regulatoria en Europa y Oriente Medio al mismo tiempo. La firma describió la aprobación como el resultado de "un proceso de licenciamiento riguroso y de varias etapas" que se extendió por varios meses.</p>
  <p class="es">Un FSP no es lo mismo que una licencia bancaria o una licencia genérica de exchange cripto. Bajo las Regulaciones de Servicios y Mercados Financieros (FSMR) del ADGM, una firma debe solicitar actividades reguladas específicas que realmente pretende realizar —trading, intermediación de operaciones, custodia, etc.— y la FSRA otorga el permiso acotado a esa lista. En otras palabras, "obtuvo una licencia cripto" es un atajo fácil, pero en la práctica se trata de un permiso estrecho y específico por actividad: BTCS ME no puede ofrecer servicios fuera de la lista aprobada. El FSP también está restringido a "clientes profesionales", por lo que no se extiende automáticamente a los usuarios minoristas de los EAU. Separar lo que la licencia realmente cubre de lo que no cubre es la clave para leer correctamente esta noticia.</p>
  <p class="de">Mit der FSP hat BTCS ME einen mehrstufigen Zulassungsprozess abgeschlossen und kann institutionellen und professionellen Kunden in den VAE nun ein vollständiges Angebot regulierter Dienstleistungen bieten — Vermittlung von Geschäften mit digitalen Vermögenswerten, Verwahrung sowie Management und Hedging von Krypto-Exposure —, teilte das Unternehmen mit. Nachdem Bitcoin Suisse bereits eine MiCA-Lizenz in Liechtenstein gesichert hat, erweitert das Unternehmen nun gleichzeitig seinen regulatorischen Fußabdruck in Europa und im Nahen Osten. Die Firma bezeichnete die Genehmigung als Ergebnis eines "gründlichen, mehrstufigen Zulassungsprozesses" über mehrere Monate.</p>
  <p class="de">Eine FSP ist nicht dasselbe wie eine Banklizenz oder eine pauschale Krypto-Börsenlizenz. Unter den Financial Services and Markets Regulations (FSMR) der ADGM muss ein Unternehmen konkrete regulierte Aktivitäten beantragen, die es tatsächlich ausüben will — Handel, Vermittlung von Geschäften, Verwahrung und so weiter —, und die FSRA erteilt die Erlaubnis passend zu dieser Liste. Mit anderen Worten: "hat eine Krypto-Lizenz gewonnen" ist eine bequeme Abkürzung, in der Praxis handelt es sich jedoch um eine enge, aktivitätsspezifische Erlaubnis — BTCS ME darf keine Dienste außerhalb der genehmigten Liste anbieten. Die FSP ist zudem auf "Professional Clients" beschränkt, erstreckt sich also nicht automatisch auf VAE-Privatkunden. Zu trennen, was die Lizenz tatsächlich abdeckt und was nicht, ist der Schlüssel, um diese Nachricht richtig zu lesen.</p>
  <p class="fr">Avec cette FSP, BTCS ME a achevé un processus d'agrément en plusieurs étapes et peut désormais offrir aux clients institutionnels et professionnels aux EAU un ensemble complet de services réglementés — courtage d'opérations sur actifs numériques, garde, et gestion et couverture de l'exposition crypto —, a déclaré l'entreprise. Ayant déjà obtenu une licence MiCA au Liechtenstein, Bitcoin Suisse étend désormais son empreinte réglementaire en Europe et au Moyen-Orient simultanément. La firme a décrit l'approbation comme le résultat d'« un processus d'agrément rigoureux et en plusieurs étapes » s'étalant sur plusieurs mois.</p>
  <p class="fr">Une FSP n'est pas la même chose qu'une licence bancaire ou une licence générique d'échange crypto. Sous les Financial Services and Markets Regulations (FSMR) de l'ADGM, une firme doit demander des activités réglementées précises qu'elle compte réellement exercer — trading, intermédiation d'opérations, garde, etc. — et la FSRA accorde une autorisation calée sur cette liste. Autrement dit, « a obtenu une licence crypto » est un raccourci pratique, mais en réalité il s'agit d'une autorisation étroite et spécifique à l'activité : BTCS ME ne peut pas offrir de services hors de la liste approuvée. La FSP est également restreinte aux « clients professionnels », elle ne s'étend donc pas automatiquement aux utilisateurs particuliers des EAU. Séparer ce que la licence couvre réellement de ce qu'elle ne couvre pas est la clé pour bien lire cette nouvelle.</p>
  <p class="pt">Com o FSP, a BTCS ME concluiu um processo de licenciamento em várias etapas e agora pode oferecer a clientes institucionais e profissionais nos EAU um conjunto completo de serviços regulados — corretagem de operações com ativos digitais, custódia, e gestão e hedge de exposição cripto —, disse a empresa. Já tendo garantido uma licença MiCA em Liechtenstein, a Bitcoin Suisse agora expande sua presença regulatória na Europa e no Oriente Médio ao mesmo tempo. A empresa descreveu a aprovação como resultado de "um processo de licenciamento rigoroso e em várias etapas" ao longo de vários meses.</p>
  <p class="pt">Um FSP não é o mesmo que uma licença bancária ou uma licença genérica de corretora cripto. Sob os Regulamentos de Serviços e Mercados Financeiros (FSMR) do ADGM, uma empresa deve solicitar atividades reguladas específicas que pretende de fato realizar — negociação, intermediação de operações, custódia etc. — e a FSRA concede a permissão restrita a essa lista. Em outras palavras, "conquistou uma licença cripto" é um atalho fácil, mas na prática trata-se de uma permissão estreita e específica por atividade: a BTCS ME não pode oferecer serviços fora da lista aprovada. O FSP também é restrito a "Clientes Profissionais", portanto não se estende automaticamente a usuários de varejo nos EAU. Separar o que a licença realmente cobre do que não cobre é a chave para ler corretamente essa notícia.</p>
  <p class="tr">FSP ile BTCS ME çok aşamalı bir lisanslama sürecini tamamladı ve artık BAE'deki kurumsal ve profesyonel müşterilere dijital varlık işlemlerinde aracılık, saklama ve kripto risklerinin yönetimi/hedge'i dahil kapsamlı düzenlenmiş hizmetler sunabiliyor, dedi şirket. Liechtenstein'da zaten bir MiCA lisansı almış olan Bitcoin Suisse, şimdi Avrupa ve Orta Doğu'da aynı anda düzenleyici ayak izini genişletiyor. Şirket bu onayı, birkaç ay süren "kapsamlı, çok aşamalı bir lisanslama süreci"nin sonucu olarak tanımladı.</p>
  <p class="tr">FSP, bir bankacılık lisansı veya genel bir kripto borsası lisansıyla aynı şey değil. ADGM'nin Finansal Hizmetler ve Piyasalar Düzenlemeleri (FSMR) altında bir şirket, gerçekten yürütmeyi planladığı belirli düzenlenmiş faaliyetler için başvurmalı — alım satım, işlem aracılığı, saklama vb. — ve FSRA izni bu listeyle sınırlı olarak veriyor. Başka bir deyişle, "kripto lisansı kazandı" kolay bir kısaltma, ama pratikte bu dar, faaliyete özgü bir izin: BTCS ME onaylanan listenin dışında hizmet sunamaz. FSP ayrıca "Profesyonel Müşteriler"le sınırlı, dolayısıyla otomatik olarak BAE perakende kullanıcılarına genişlemiyor. Lisansın gerçekte neyi kapsadığını neyi kapsamadığından ayırmak, bu haberi doğru okumanın anahtarı.</p>
  <p class="vi">Với FSP, BTCS ME đã hoàn tất một quy trình cấp phép nhiều giai đoạn và giờ có thể cung cấp cho khách hàng định chế và chuyên nghiệp tại UAE một bộ dịch vụ được quản lý đầy đủ — môi giới giao dịch tài sản số, lưu ký, và quản lý/phòng hộ rủi ro crypto — công ty cho biết. Đã có giấy phép MiCA tại Liechtenstein, Bitcoin Suisse giờ mở rộng dấu chân quản lý ở cả châu Âu và Trung Đông cùng lúc. Công ty mô tả việc phê duyệt là kết quả của "một quy trình cấp phép kỹ lưỡng, nhiều giai đoạn" kéo dài nhiều tháng.</p>
  <p class="vi">FSP không giống với giấy phép ngân hàng hay giấy phép sàn giao dịch crypto toàn diện. Theo Quy Định Dịch Vụ và Thị Trường Tài Chính (FSMR) của ADGM, một công ty phải xin phép cho các hoạt động được quản lý cụ thể mà họ thực sự dự định thực hiện — giao dịch, môi giới giao dịch, lưu ký, v.v. — và FSRA cấp phép giới hạn theo danh sách đó. Nói cách khác, "giành được giấy phép crypto" là cách nói tắt dễ hiểu, nhưng trên thực tế đây là giấy phép hẹp, theo từng hoạt động cụ thể: BTCS ME không thể cung cấp dịch vụ ngoài danh sách đã duyệt. FSP cũng chỉ giới hạn ở "Khách Hàng Chuyên Nghiệp", nên không tự động mở rộng sang người dùng bán lẻ tại UAE. Tách bạch điều giấy phép thực sự bao trùm và điều nó không bao trùm chính là chìa khóa để đọc đúng tin này.</p>

  <h2 class="ko">왜 아부다비인가 — 두바이 VARA와 갈라지는 지점</h2>
  <h2 class="en">Why Abu Dhabi — where it diverges from Dubai's VARA</h2>
  <h2 class="ja">なぜアブダビなのか——ドバイのVARAとの分岐点</h2>
  <h2 class="es">Por qué Abu Dabi — dónde diverge del VARA de Dubái</h2>
  <h2 class="de">Warum Abu Dhabi — wo es sich von Dubais VARA unterscheidet</h2>
  <h2 class="fr">Pourquoi Abou Dabi — où cela diverge du VARA de Dubaï</h2>
  <h2 class="pt">Por que Abu Dhabi — onde diverge da VARA de Dubai</h2>
  <h2 class="tr">Neden Abu Dabi — Dubai'nin VARA'sından ayrıldığı nokta</h2>
  <h2 class="vi">Tại sao Abu Dhabi — điểm khác biệt với VARA của Dubai</h2>

  <p class="ko">ADGM은 2018년 UAE 최초로 포괄적인 암호자산 규제 프레임워크를 도입한 관할권으로, 아부다비글로벌마켓이라는 별도의 자유구역 안에서 영국식 보통법(Common Law)을 기반으로 운영된다. 자본 적정성, 지배구조, AML·KYC, 기술 표준 등에서 전통 금융기관에 준하는 요건을 요구하는 것으로 알려져 있으며, 그 결과 글로벌 기관을 겨냥한 '신뢰의 여권'으로 자리잡았다. 실제로 바이낸스도 ADGM에서 트레이딩·커스터디를 아우르는 복수의 FSRA 인가를 확보했고, 크라켄 역시 아부다비에서 사업 승인을 받은 바 있다. 비트코인 스위스의 이번 인가는 이렇게 형성되고 있는 아부다비 기관 크립토 클러스터에 합류하는 모양새다.</p>
  <p class="ko">반면 두바이의 VARA는 2022년 설립된, 가상자산만을 전담하는 세계 최초의 규제기관으로 DIFC를 제외한 두바이 본토와 대부분의 자유구역 크립토 활동을 관장한다. VARA 체제는 소매 대상 사업과 역내 운영자를 포괄하는 더 폭넓은 범위를 자랑하지만, ADGM만큼 오래된 트랙레코드는 없다. 중요한 것은 두 체제가 상호 패스포팅되지 않는다는 점이다 — ADGM 인가를 받았다고 해서 두바이 VARA나 역내 증권당국(SCA) 아래에서 자동으로 영업할 수 있는 것은 아니다. 이 지점에서 반론도 가능하다. 한 국가 안에 서로 호환되지 않는 최소 세 개의 크립토 규제 체계(ADGM·VARA·SCA)가 병존하는 구조는 기업에는 '관할권 쇼핑'의 여지를, 이용자에게는 '어느 라이선스가 실제로 나를 보호하는가'에 대한 혼란을 남길 수 있다는 비판도 있다.</p>
  <p class="en">ADGM was the UAE's first jurisdiction to introduce a comprehensive crypto-asset regulatory framework, back in 2018, operating under English common law inside its own free-zone financial centre. It is known for requiring capital adequacy, governance, AML/KYC and technology standards comparable to traditional financial institutions, which has made it a "passport of trust" aimed at global institutions. Binance, for one, already holds multiple FSRA authorizations in ADGM spanning trading and custody, and Kraken has also secured approval to operate in Abu Dhabi. Bitcoin Suisse's new license effectively joins this forming institutional crypto cluster in Abu Dhabi.</p>
  <p class="en">Dubai's VARA, by contrast, was founded in 2022 as the world's first regulator dedicated solely to virtual assets, and it oversees crypto activity across mainland Dubai and most of its free zones (excluding DIFC). VARA's regime boasts broader coverage spanning retail-facing business and regional operators, but it lacks ADGM's longer track record. Crucially, the two regimes do not passport into each other — holding an ADGM license does not automatically let a firm operate under Dubai's VARA or the onshore Securities and Commodities Authority (SCA). This is where a counterargument holds too: having at least three mutually incompatible crypto regulatory regimes (ADGM, VARA, SCA) coexist within one country leaves room for firms to shop for the friendliest jurisdiction, and leaves users with genuine confusion over which license actually protects them.</p>
  <p class="ja">ADGMは2018年、UAEで初めて包括的な暗号資産規制フレームワークを導入した管轄区であり、アブダビ・グローバル・マーケットという独自の自由区域内で英国式コモンローに基づいて運営される。資本適正性、ガバナンス、AML・KYC、技術基準などで伝統的金融機関に準じる要件を課すことで知られ、その結果、グローバルな機関投資家を狙った『信頼のパスポート』としての地位を築いた。実際バイナンスもADGMで取引・カストディにまたがる複数のFSRA認可を確保しており、クラケンもアブダビで事業承認を得ている。ビットコイン・スイスの今回の認可は、こうして形成されつつあるアブダビの機関投資家向け暗号資産クラスターに加わる格好だ。</p>
  <p class="ja">対照的にドバイのVARAは、2022年に設立された、仮想資産のみを専任で扱う世界初の規制機関で、DIFCを除くドバイ本土と大半の自由区域の暗号資産活動を管轄する。VARA体制は小売向け事業や地域事業者を包含するより幅広い範囲を誇るが、ADGMほどの長いトラックレコードはない。重要なのは、両体制が相互にパスポーティングされない点だ——ADGM認可を得たからといって、ドバイのVARAや域内証券商品庁(SCA)の下で自動的に営業できるわけではない。ここで反論も成り立つ。一国内に相互互換性のない少なくとも三つの暗号資産規制体系(ADGM・VARA・SCA)が並存する構造は、企業には『管轄区ショッピング』の余地を、利用者には『どのライセンスが実際に自分を守るのか』という混乱を残しかねないという批判もある。</p>
  <p class="es">El ADGM fue la primera jurisdicción de los EAU en introducir un marco regulatorio integral de activos cripto, allá por 2018, operando bajo el derecho consuetudinario inglés dentro de su propio centro financiero de zona franca. Es conocido por exigir requisitos de adecuación de capital, gobernanza, AML/KYC y estándares tecnológicos comparables a los de instituciones financieras tradicionales, lo que lo ha convertido en un "pasaporte de confianza" dirigido a instituciones globales. Binance, por ejemplo, ya posee múltiples autorizaciones de la FSRA en el ADGM que abarcan trading y custodia, y Kraken también ha obtenido aprobación para operar en Abu Dabi. La nueva licencia de Bitcoin Suisse se suma efectivamente a este clúster institucional de cripto que se está formando en Abu Dabi.</p>
  <p class="es">El VARA de Dubái, en cambio, se fundó en 2022 como el primer regulador del mundo dedicado exclusivamente a activos virtuales, y supervisa la actividad cripto en la Dubái continental y la mayoría de sus zonas francas (excluyendo el DIFC). El régimen de VARA presume de una cobertura más amplia que abarca negocios minoristas y operadores regionales, pero carece del historial más largo del ADGM. Fundamentalmente, ambos regímenes no se pasaportan entre sí: tener una licencia del ADGM no permite automáticamente a una firma operar bajo el VARA de Dubái o la Autoridad de Valores y Materias Primas (SCA) local. Aquí también se sostiene un contraargumento: que coexistan al menos tres regímenes regulatorios cripto mutuamente incompatibles (ADGM, VARA, SCA) dentro de un mismo país deja margen para que las firmas busquen la jurisdicción más favorable, y deja a los usuarios con genuina confusión sobre qué licencia realmente los protege.</p>
  <p class="de">Die ADGM war die erste Jurisdiktion der VAE, die 2018 einen umfassenden regulatorischen Rahmen für Krypto-Assets einführte, und operiert unter englischem Common Law innerhalb ihres eigenen Freihandelszonen-Finanzzentrums. Sie ist dafür bekannt, Anforderungen an Kapitaladäquanz, Governance, AML/KYC und Technologiestandards zu stellen, die mit traditionellen Finanzinstituten vergleichbar sind, was sie zu einem "Vertrauenspass" für globale Institutionen gemacht hat. Binance etwa hält bereits mehrere FSRA-Zulassungen in der ADGM für Handel und Verwahrung, und auch Kraken hat eine Genehmigung für den Betrieb in Abu Dhabi gesichert. Bitcoin Suisses neue Lizenz reiht sich damit faktisch in diesen sich formierenden institutionellen Krypto-Cluster in Abu Dhabi ein.</p>
  <p class="de">Dubais VARA hingegen wurde 2022 als weltweit erste ausschließlich für virtuelle Vermögenswerte zuständige Regulierungsbehörde gegründet und beaufsichtigt Krypto-Aktivitäten im Dubai-Festland und den meisten seiner Freihandelszonen (mit Ausnahme des DIFC). Das VARA-Regime bietet eine breitere Abdeckung, die auf Privatkundengeschäft und regionale Betreiber ausgerichtet ist, verfügt aber nicht über die längere Erfolgsbilanz der ADGM. Entscheidend ist, dass sich die beiden Regime nicht gegenseitig passporten — eine ADGM-Lizenz erlaubt es einem Unternehmen nicht automatisch, unter Dubais VARA oder der Onshore-Wertpapier- und Warenbehörde (SCA) zu operieren. Auch hier gilt ein Gegenargument: Dass mindestens drei gegenseitig inkompatible Krypto-Regulierungsregime (ADGM, VARA, SCA) innerhalb eines Landes koexistieren, lässt Raum für "Jurisdiktions-Shopping" durch Unternehmen und echte Verwirrung bei Nutzern darüber, welche Lizenz sie tatsächlich schützt.</p>
  <p class="fr">L'ADGM a été la première juridiction des EAU à introduire un cadre réglementaire complet pour les actifs crypto, dès 2018, opérant sous le droit commun anglais au sein de son propre centre financier de zone franche. Elle est connue pour exiger des normes d'adéquation des fonds propres, de gouvernance, d'AML/KYC et de technologie comparables à celles des institutions financières traditionnelles, ce qui en a fait un « passeport de confiance » destiné aux institutions mondiales. Binance, par exemple, détient déjà plusieurs autorisations FSRA à l'ADGM couvrant le trading et la garde, et Kraken a également obtenu une approbation pour opérer à Abou Dabi. La nouvelle licence de Bitcoin Suisse rejoint effectivement ce cluster crypto institutionnel en formation à Abou Dabi.</p>
  <p class="fr">Le VARA de Dubaï, en revanche, a été fondé en 2022 en tant que premier régulateur au monde dédié exclusivement aux actifs virtuels, et supervise l'activité crypto dans le Dubaï continental et la plupart de ses zones franches (à l'exclusion du DIFC). Le régime du VARA revendique une couverture plus large englobant les entreprises orientées vers le grand public et les opérateurs régionaux, mais il ne dispose pas du plus long historique de l'ADGM. Fait crucial, les deux régimes ne se passeportent pas mutuellement — détenir une licence ADGM ne permet pas automatiquement à une firme d'opérer sous le VARA de Dubaï ou l'Autorité des valeurs et matières premières (SCA) onshore. C'est là qu'un contre-argument tient aussi : la coexistence d'au moins trois régimes réglementaires crypto mutuellement incompatibles (ADGM, VARA, SCA) au sein d'un même pays laisse une marge de « magasinage juridictionnel » aux entreprises, et laisse les utilisateurs dans une confusion réelle quant à la licence qui les protège réellement.</p>
  <p class="pt">O ADGM foi a primeira jurisdição dos EAU a introduzir um arcabouço regulatório abrangente para ativos cripto, já em 2018, operando sob o direito consuetudinário inglês dentro de seu próprio centro financeiro de zona franca. É conhecido por exigir adequação de capital, governança, AML/KYC e padrões tecnológicos comparáveis aos de instituições financeiras tradicionais, o que o tornou um "passaporte de confiança" voltado a instituições globais. A Binance, por exemplo, já detém múltiplas autorizações da FSRA no ADGM abrangendo negociação e custódia, e a Kraken também obteve aprovação para operar em Abu Dhabi. A nova licença da Bitcoin Suisse efetivamente se junta a esse cluster cripto institucional em formação em Abu Dhabi.</p>
  <p class="pt">Já a VARA de Dubai foi fundada em 2022 como o primeiro regulador do mundo dedicado exclusivamente a ativos virtuais, e supervisiona a atividade cripto no Dubai continental e na maioria de suas zonas francas (exceto o DIFC). O regime da VARA ostenta uma cobertura mais ampla, abrangendo negócios voltados ao varejo e operadores regionais, mas carece do histórico mais longo do ADGM. Crucialmente, os dois regimes não têm passaporte mútuo — ter uma licença do ADGM não permite automaticamente que uma empresa opere sob a VARA de Dubai ou a Autoridade de Valores Mobiliários e Commodities (SCA) local. É aqui que um contra-argumento também se sustenta: a coexistência de pelo menos três regimes regulatórios cripto mutuamente incompatíveis (ADGM, VARA, SCA) dentro de um mesmo país deixa espaço para que empresas façam "compras de jurisdição", e deixa os usuários com confusão genuína sobre qual licença realmente os protege.</p>
  <p class="tr">ADGM, 2018'de BAE'de kapsamlı bir kripto varlık düzenleme çerçevesi getiren ilk yargı alanıydı; kendi serbest bölge finans merkezi içinde İngiliz common law'u altında faaliyet gösteriyor. Sermaye yeterliliği, yönetişim, AML/KYC ve teknoloji standartlarında geleneksel finans kurumlarıyla kıyaslanabilir gereklilikler talep etmesiyle biliniyor; bu da onu küresel kurumlara yönelik bir "güven pasaportu" haline getirdi. Örneğin Binance, ADGM'de alım satım ve saklamayı kapsayan birden fazla FSRA yetkisine zaten sahip, Kraken da Abu Dabi'de faaliyet göstermek için onay aldı. Bitcoin Suisse'in yeni lisansı, Abu Dabi'de oluşmakta olan bu kurumsal kripto kümesine fiilen katılıyor.</p>
  <p class="tr">Dubai'nin VARA'sı ise 2022'de dünyanın yalnızca sanal varlıklara adanmış ilk düzenleyicisi olarak kuruldu ve DIFC hariç Dubai anakarası ile serbest bölgelerinin çoğundaki kripto faaliyetini denetliyor. VARA rejimi, perakendeye dönük iş ve bölgesel operatörleri kapsayan daha geniş bir kapsam iddia ediyor, ama ADGM'nin daha uzun geçmişine sahip değil. Kritik olan şu: iki rejim birbirine pasaportlanmıyor — ADGM lisansına sahip olmak bir şirketin otomatik olarak Dubai'nin VARA'sı veya yerel Menkul Kıymetler ve Emtia Otoritesi (SCA) altında faaliyet göstermesine izin vermiyor. Tam burada bir karşı argüman da geçerli: bir ülke içinde birbiriyle uyumsuz en az üç kripto düzenleme rejiminin (ADGM, VARA, SCA) bir arada bulunması, şirketlere "yargı alanı alışverişi" için alan bırakırken, kullanıcılara hangi lisansın onları gerçekten koruduğu konusunda gerçek bir kafa karışıklığı bırakıyor.</p>
  <p class="vi">ADGM là khu vực pháp lý đầu tiên tại UAE giới thiệu khung quản lý tài sản crypto toàn diện, từ năm 2018, vận hành theo thông luật Anh trong trung tâm tài chính khu tự do riêng của mình. Nơi này nổi tiếng vì yêu cầu về đủ vốn, quản trị, AML/KYC và tiêu chuẩn công nghệ tương đương các định chế tài chính truyền thống, khiến nó trở thành một "hộ chiếu niềm tin" nhắm tới các định chế toàn cầu. Chẳng hạn, Binance đã có nhiều giấy phép FSRA tại ADGM bao gồm giao dịch và lưu ký, còn Kraken cũng đã được chấp thuận hoạt động tại Abu Dhabi. Giấy phép mới của Bitcoin Suisse thực chất gia nhập cụm crypto định chế đang hình thành này tại Abu Dhabi.</p>
  <p class="vi">Ngược lại, VARA của Dubai được thành lập năm 2022 với tư cách là cơ quan quản lý đầu tiên trên thế giới chuyên trách riêng tài sản ảo, giám sát hoạt động crypto trên khắp Dubai đại lục và hầu hết các khu tự do (trừ DIFC). Chế độ VARA tự hào có phạm vi rộng hơn, bao gồm cả kinh doanh hướng bán lẻ và nhà vận hành khu vực, nhưng thiếu bề dày lịch sử của ADGM. Điều quan trọng là hai chế độ này không "hộ chiếu hóa" lẫn nhau — có giấy phép ADGM không tự động cho phép một công ty hoạt động theo VARA của Dubai hay Cơ Quan Chứng Khoán và Hàng Hóa (SCA) nội địa. Đây cũng là chỗ một lập luận phản bác có cơ sở: việc ít nhất ba chế độ quản lý crypto không tương thích lẫn nhau (ADGM, VARA, SCA) cùng tồn tại trong một quốc gia để lại dư địa cho các công ty "mua sắm khu vực pháp lý", và để lại sự bối rối thực sự cho người dùng về việc giấy phép nào thực sự bảo vệ họ.</p>

  <h2 class="ko">라이선스 경쟁의 맥락 — 크립토 기업들의 관할권 사냥</h2>
  <h2 class="en">The context — crypto firms' hunt for jurisdictions</h2>
  <h2 class="ja">競争の文脈——暗号資産企業による管轄区の争奪戦</h2>
  <h2 class="es">El contexto — la caza de jurisdicciones de las firmas cripto</h2>
  <h2 class="de">Der Kontext — die Jagd der Krypto-Firmen nach Jurisdiktionen</h2>
  <h2 class="fr">Le contexte — la chasse aux juridictions des sociétés crypto</h2>
  <h2 class="pt">O contexto — a caça por jurisdições das empresas cripto</h2>
  <h2 class="tr">Bağlam — kripto şirketlerinin yargı alanı avı</h2>
  <h2 class="vi">Bối cảnh — cuộc săn tìm khu vực pháp lý của các công ty crypto</h2>

  <p class="ko">이 흐름은 비트코인 스위스만의 이야기가 아니다. <strong>CoinDesk</strong>는 크라켄이 미국 상장을 앞두고 리투아니아에서 완전한 유럽 은행업 인가를 추진 중이라고 7월 7일 보도했다(관련 내용은 <a href="/blog/kraken-lithuania-banking-charter-bid">크라켄의 리투아니아 은행업 인가 도전</a> 참고). 승인되면 크라켄은 은행 허가를 보유한 최초의 크립토 네이티브 거래소가 된다. 두 사례는 같은 패턴을 보여준다 — 크립토 기업들이 전 세계 곳곳에서 전통 금융 등급의 규제 승인을 동시다발적으로 좇고 있다는 것이다. 기관 자본을 유치하려면 특정 관할권 하나의 라이선스만으로는 부족하고, 각 지역 규제기관의 '신뢰 도장'을 하나씩 모아야 하는 국면에 접어들었다.</p>
  <p class="ko">다만 라이선스 취득 자체를 '리스크 해소'와 동일시하는 것은 과도한 해석이다. FSP나 은행 인가는 영업 자격과 준법 감시 체계를 뜻할 뿐, 예금보험이나 최종대부자 기능 같은 전통 금융의 안전망까지 자동으로 제공하지는 않는다. 오히려 이런 라이선스 뉴스는 실질적 위험 축소보다 마케팅적 신뢰도와 시장 접근성 확대 효과가 더 클 수 있다. 앞으로 지켜볼 지표는 두 가지다. 첫째, 이 인가 이후 실제로 UAE로 이전하는 기관 자금·거래량이 늘어나는지. 둘째, 바젤위원회의 은행 자본규제 강화(관련해서는 <a href="/blog/basel-sco60-crypto-capital-review-us-divergence">바젤 SCO60 크립토 자본규제 재검토</a> 참고) 등으로 서구 금융권의 크립토 자본 비용이 오르는 흐름 속에서, 이런 '우호적 관할권 이전'이 다른 대형 커스터디언에서도 이어지는지다. 이 인가의 성패는 결국 규제 승인 그 자체가 아니라, 그 승인이 실제 자본 흐름으로 이어지는지에 달려 있다.</p>
  <p class="en">This trend is not unique to Bitcoin Suisse. <strong>CoinDesk</strong> reported on July 7 that Kraken is pursuing a full European banking license in Lithuania ahead of a planned U.S. IPO (for context, see <a href="/en/blog/kraken-lithuania-banking-charter-bid">Kraken's push for a Lithuanian banking charter</a>). If approved, Kraken would become the first crypto-native exchange to hold a bank charter. The two cases show the same pattern: crypto firms are simultaneously chasing traditional-finance-grade regulatory approvals across multiple jurisdictions worldwide. Attracting institutional capital increasingly requires more than a license in a single jurisdiction — it means collecting a "trust stamp" from each regional regulator, one by one.</p>
  <p class="en">Still, it would be an overreach to equate obtaining a license with eliminating risk. An FSP or a bank charter signals operating eligibility and a compliance framework, but it doesn't automatically come with traditional finance's safety nets, such as deposit insurance or a lender of last resort. If anything, license news like this may deliver more marketing credibility and market access than actual risk reduction. Two metrics are worth watching going forward. First, whether institutional capital and trading volume actually migrate to the UAE following this approval. Second, whether this kind of "friendly-jurisdiction shift" spreads to other major custodians as capital costs for crypto rise in Western finance amid tightening bank capital rules such as the Basel Committee's review (for context, see <a href="/en/blog/basel-sco60-crypto-capital-review-us-divergence">the Basel SCO60 crypto capital review</a>). Ultimately, this license's significance will be decided not by the approval itself but by whether it translates into real capital flows.</p>
  <p class="ja">この流れはビットコイン・スイスだけの話ではない。<strong>CoinDesk</strong>は7月7日、クラケンが米国上場を控えてリトアニアで完全な欧州銀行業免許を追求していると報じた(関連は<a href="/ja/blog/kraken-lithuania-banking-charter-bid">クラケンのリトアニア銀行業免許への挑戦</a>を参照)。承認されれば、クラケンは銀行免許を保有する初の暗号資産ネイティブ取引所となる。二つの事例は同じパターンを示す——暗号資産企業が世界各地で伝統金融級の規制承認を同時多発的に追い求めているということだ。機関資本を呼び込むには特定管轄区一つのライセンスだけでは足りず、各地域規制当局の『信頼の印』を一つずつ集める局面に入っている。</p>
  <p class="ja">ただし、ライセンス取得そのものを『リスク解消』と同一視するのは過度な解釈だ。FSPや銀行免許は営業資格とコンプライアンス体制を意味するにすぎず、預金保険や最後の貸し手機能といった伝統金融のセーフティネットまで自動的に提供するわけではない。むしろこうしたライセンスのニュースは、実質的なリスク低減よりもマーケティング上の信頼性や市場アクセス拡大の効果の方が大きい可能性がある。今後注視すべき指標は二つだ。第一に、この認可の後、実際にUAEへ移る機関資金・取引高が増えるかどうか。第二に、バーゼル委員会の資本規制見直し(関連は<a href="/ja/blog/basel-sco60-crypto-capital-review-us-divergence">バーゼルSCO60暗号資産資本規制の再検討</a>を参照)などで西側金融界の暗号資産資本コストが上がる流れの中で、こうした『友好的管轄区への移行』が他の大手カストディアンにも広がるかどうかだ。この認可の成否は、結局のところ規制承認そのものではなく、それが実際の資本フローにつながるかどうかで決まる。</p>
  <p class="es">Esta tendencia no es exclusiva de Bitcoin Suisse. <strong>CoinDesk</strong> informó el 7 de julio que Kraken busca una licencia bancaria europea completa en Lituania antes de una IPO en EE. UU. planeada (para contexto, véase <a href="/es/blog/kraken-lithuania-banking-charter-bid">el intento de Kraken por una carta bancaria lituana</a>). Si se aprueba, Kraken se convertiría en el primer exchange nativo cripto en tener una carta bancaria. Ambos casos muestran el mismo patrón: las firmas cripto persiguen simultáneamente aprobaciones regulatorias de nivel financiero tradicional en múltiples jurisdicciones de todo el mundo. Atraer capital institucional exige cada vez más que una sola licencia en una jurisdicción; significa acumular un "sello de confianza" de cada regulador regional, uno por uno.</p>
  <p class="es">Aun así, sería exagerado equiparar obtener una licencia con eliminar el riesgo. Un FSP o una carta bancaria señala elegibilidad operativa y un marco de cumplimiento, pero no viene automáticamente con las redes de seguridad de las finanzas tradicionales, como el seguro de depósitos o un prestamista de última instancia. Si acaso, noticias de licencias como esta pueden aportar más credibilidad de marketing y acceso al mercado que una reducción real del riesgo. Dos métricas merecen atención de ahora en adelante. Primera, si el capital institucional y el volumen de trading realmente migran a los EAU tras esta aprobación. Segunda, si este tipo de "cambio a jurisdicción amigable" se extiende a otros grandes custodios a medida que suben los costos de capital cripto en las finanzas occidentales en medio del endurecimiento de reglas de capital bancario como la revisión del Comité de Basilea (para contexto, véase <a href="/es/blog/basel-sco60-crypto-capital-review-us-divergence">la revisión de capital cripto de Basilea SCO60</a>). En última instancia, el significado de esta licencia se decidirá no por la aprobación en sí, sino por si se traduce en flujos de capital reales.</p>
  <p class="de">Dieser Trend ist nicht auf Bitcoin Suisse beschränkt. <strong>CoinDesk</strong> berichtete am 7. Juli, dass Kraken vor einem geplanten US-Börsengang eine volle europäische Banklizenz in Litauen anstrebt (zum Kontext siehe <a href="/de/blog/kraken-lithuania-banking-charter-bid">Krakens Vorstoß für eine litauische Banklizenz</a>). Bei Genehmigung würde Kraken zur ersten krypto-nativen Börse mit Banklizenz. Beide Fälle zeigen dasselbe Muster: Krypto-Firmen jagen gleichzeitig weltweit nach regulatorischen Zulassungen auf Niveau traditioneller Finanzinstitute. Um institutionelles Kapital anzuziehen, reicht zunehmend nicht mehr eine Lizenz in einer einzigen Jurisdiktion — es bedeutet, von jedem regionalen Regulierer einzeln einen "Vertrauensstempel" zu sammeln.</p>
  <p class="de">Dennoch wäre es überzogen, den Erhalt einer Lizenz mit der Beseitigung von Risiko gleichzusetzen. Eine FSP oder eine Banklizenz signalisiert operative Zulässigkeit und ein Compliance-Rahmenwerk, bringt aber nicht automatisch die Sicherheitsnetze traditioneller Finanzen mit sich, etwa Einlagensicherung oder einen Kreditgeber letzter Instanz. Wenn überhaupt, liefern solche Lizenznachrichten eher mehr Marketing-Glaubwürdigkeit und Marktzugang als tatsächliche Risikominderung. Zwei Kennzahlen sind künftig zu beobachten. Erstens, ob institutionelles Kapital und Handelsvolumen nach dieser Genehmigung tatsächlich in die VAE abwandern. Zweitens, ob sich diese Art "Wechsel in eine freundliche Jurisdiktion" auf andere große Verwahrstellen ausweitet, während die Kapitalkosten für Krypto im westlichen Finanzwesen inmitten verschärfter Bankenkapitalregeln wie der Überprüfung durch den Basler Ausschuss steigen (zum Kontext siehe <a href="/de/blog/basel-sco60-crypto-capital-review-us-divergence">die Basel-SCO60-Krypto-Kapitalüberprüfung</a>). Letztlich entscheidet sich die Bedeutung dieser Lizenz nicht an der Genehmigung selbst, sondern daran, ob sie sich in echte Kapitalflüsse übersetzt.</p>
  <p class="fr">Cette tendance ne se limite pas à Bitcoin Suisse. <strong>CoinDesk</strong> a rapporté le 7 juillet que Kraken poursuit une licence bancaire européenne complète en Lituanie avant une introduction en bourse prévue aux États-Unis (pour le contexte, voir <a href="/fr/blog/kraken-lithuania-banking-charter-bid">la démarche de Kraken pour une charte bancaire lituanienne</a>). Si elle est approuvée, Kraken deviendrait la première bourse native crypto à détenir une charte bancaire. Les deux cas montrent le même schéma : les sociétés crypto poursuivent simultanément des approbations réglementaires de niveau financier traditionnel dans de multiples juridictions à travers le monde. Attirer le capital institutionnel exige de plus en plus davantage qu'une licence dans une seule juridiction — cela signifie collecter un « tampon de confiance » de chaque régulateur régional, un par un.</p>
  <p class="fr">Pour autant, il serait excessif d'assimiler l'obtention d'une licence à l'élimination du risque. Une FSP ou une charte bancaire signale une éligibilité opérationnelle et un cadre de conformité, mais ne s'accompagne pas automatiquement des filets de sécurité de la finance traditionnelle, comme l'assurance des dépôts ou un prêteur en dernier ressort. Si tant est que cela compte, ce genre de nouvelle de licence peut apporter davantage de crédibilité marketing et d'accès au marché qu'une réduction réelle du risque. Deux indicateurs méritent d'être surveillés à l'avenir. Premièrement, si le capital institutionnel et le volume de trading migrent réellement vers les EAU après cette approbation. Deuxièmement, si ce type de « bascule vers une juridiction amicale » se propage à d'autres grands dépositaires alors que le coût du capital crypto augmente dans la finance occidentale au milieu du durcissement des règles de capital bancaire telles que l'examen du Comité de Bâle (pour le contexte, voir <a href="/fr/blog/basel-sco60-crypto-capital-review-us-divergence">l'examen du capital crypto de Bâle SCO60</a>). En définitive, la portée de cette licence se décidera non par l'approbation elle-même, mais par sa traduction en flux de capitaux réels.</p>
  <p class="pt">Essa tendência não é exclusiva da Bitcoin Suisse. A <strong>CoinDesk</strong> informou em 7 de julho que a Kraken busca uma licença bancária europeia completa na Lituânia antes de um IPO planejado nos EUA (para contexto, veja <a href="/pt/blog/kraken-lithuania-banking-charter-bid">a busca da Kraken por uma carta bancária lituana</a>). Se aprovada, a Kraken se tornaria a primeira corretora nativa de cripto a possuir uma carta bancária. Os dois casos mostram o mesmo padrão: empresas cripto perseguem simultaneamente aprovações regulatórias de nível financeiro tradicional em múltiplas jurisdições ao redor do mundo. Atrair capital institucional exige cada vez mais do que uma licença em uma única jurisdição — significa acumular um "selo de confiança" de cada regulador regional, um a um.</p>
  <p class="pt">Ainda assim, seria um exagero equiparar obter uma licença a eliminar risco. Um FSP ou uma carta bancária sinaliza elegibilidade operacional e um arcabouço de conformidade, mas não vem automaticamente com as redes de segurança das finanças tradicionais, como seguro de depósitos ou um credor de última instância. Se algo, notícias de licenças como esta podem entregar mais credibilidade de marketing e acesso a mercado do que redução real de risco. Duas métricas merecem atenção daqui em diante. Primeira, se capital institucional e volume de negociação de fato migram para os EAU após essa aprovação. Segunda, se esse tipo de "mudança para jurisdição amigável" se espalha para outros grandes custodiantes à medida que os custos de capital para cripto sobem nas finanças ocidentais em meio ao aperto de regras de capital bancário, como a revisão do Comitê de Basileia (para contexto, veja <a href="/pt/blog/basel-sco60-crypto-capital-review-us-divergence">a revisão de capital cripto de Basileia SCO60</a>). No fim, o significado dessa licença será decidido não pela aprovação em si, mas por ela se traduzir em fluxos de capital reais.</p>
  <p class="tr">Bu eğilim yalnızca Bitcoin Suisse'e özgü değil. <strong>CoinDesk</strong>, 7 Temmuz'da Kraken'in planlanan bir ABD halka arzı öncesinde Litvanya'da tam bir Avrupa bankacılık lisansı peşinde olduğunu bildirdi (bağlam için bkz. <a href="/tr/blog/kraken-lithuania-banking-charter-bid">Kraken'in Litvanya bankacılık ruhsatı girişimi</a>). Onaylanırsa Kraken, bir banka ruhsatına sahip ilk kripto-yerlisi borsa olacak. İki vaka da aynı örüntüyü gösteriyor: kripto şirketleri dünya çapında birden fazla yargı alanında geleneksel finans düzeyinde düzenleyici onayları eşzamanlı olarak kovalıyor. Kurumsal sermayeyi çekmek giderek tek bir yargı alanındaki lisanstan fazlasını gerektiriyor — her bölgesel düzenleyiciden birer birer bir "güven damgası" toplamak anlamına geliyor.</p>
  <p class="tr">Yine de bir lisans elde etmeyi riskin ortadan kalkmasıyla eşitlemek aşırı bir yorum olur. Bir FSP veya banka ruhsatı, faaliyet uygunluğunu ve bir uyum çerçevesini işaret eder, ama otomatik olarak mevduat sigortası veya son kredi mercii gibi geleneksel finansın güvenlik ağlarını beraberinde getirmez. Aksine, bu tür lisans haberleri gerçek risk azaltımından çok pazarlama güvenilirliği ve pazar erişimi sağlayabilir. Bundan sonra izlenmeye değer iki gösterge var. Birincisi, bu onay sonrasında kurumsal sermaye ve işlem hacminin gerçekten BAE'ye kayıp kaymadığı. İkincisi, Basel Komitesi'nin incelemesi gibi banka sermaye kurallarının sıkılaşması ortasında (bağlam için bkz. <a href="/tr/blog/basel-sco60-crypto-capital-review-us-divergence">Basel SCO60 kripto sermaye incelemesi</a>) Batı finansında kripto sermaye maliyeti yükselirken, bu tür "dost yargı alanına kayış"ın diğer büyük saklama kuruluşlarına da yayılıp yayılmadığı. Nihayetinde bu lisansın anlamı, onayın kendisiyle değil, gerçek sermaye akışlarına dönüşüp dönüşmediğiyle belirlenecek.</p>
  <p class="vi">Xu hướng này không chỉ riêng Bitcoin Suisse. <strong>CoinDesk</strong> đưa tin ngày 7/7 rằng Kraken đang theo đuổi giấy phép ngân hàng châu Âu đầy đủ tại Lithuania trước một đợt IPO tại Mỹ đã lên kế hoạch (bối cảnh, xem <a href="/vi/blog/kraken-lithuania-banking-charter-bid">nỗ lực xin giấy phép ngân hàng Lithuania của Kraken</a>). Nếu được duyệt, Kraken sẽ trở thành sàn giao dịch gốc crypto đầu tiên sở hữu giấy phép ngân hàng. Cả hai trường hợp cho thấy cùng một khuôn mẫu: các công ty crypto đang đồng thời theo đuổi các phê duyệt quản lý ở cấp độ tài chính truyền thống tại nhiều khu vực pháp lý trên toàn thế giới. Thu hút vốn định chế ngày càng đòi hỏi nhiều hơn một giấy phép ở một khu vực pháp lý duy nhất — nghĩa là phải gom từng "con dấu tin cậy" từ mỗi cơ quan quản lý khu vực.</p>
  <p class="vi">Tuy vậy, sẽ là quá đà nếu đánh đồng việc có được giấy phép với việc loại bỏ rủi ro. Một FSP hay giấy phép ngân hàng chỉ báo hiệu tư cách hoạt động và một khung tuân thủ, chứ không tự động đi kèm các lưới an toàn của tài chính truyền thống như bảo hiểm tiền gửi hay người cho vay cuối cùng. Nếu có gì đó, tin tức giấy phép kiểu này có thể mang lại uy tín tiếp thị và khả năng tiếp cận thị trường nhiều hơn là giảm rủi ro thực sự. Có hai chỉ số đáng theo dõi sắp tới. Thứ nhất, liệu vốn định chế và khối lượng giao dịch có thực sự dịch chuyển sang UAE sau phê duyệt này hay không. Thứ hai, liệu kiểu "dịch chuyển sang khu vực pháp lý thân thiện" này có lan sang các đơn vị lưu ký lớn khác khi chi phí vốn cho crypto tăng lên trong tài chính phương Tây giữa lúc các quy tắc vốn ngân hàng thắt chặt như đợt rà soát của Ủy Ban Basel (bối cảnh, xem <a href="/vi/blog/basel-sco60-crypto-capital-review-us-divergence">rà soát vốn crypto Basel SCO60</a>). Rốt cuộc, ý nghĩa của giấy phép này sẽ được quyết định không phải bởi bản thân sự phê duyệt, mà bởi việc nó có chuyển thành dòng vốn thực sự hay không.</p>

  <ul class="ko">
    <li><strong><a href="/blog/kraken-lithuania-banking-charter-bid">크라켄의 리투아니아 은행업 인가 도전</a>:</strong> 크립토 기업이 전통 금융 라이선스를 좇는 또 다른 사례</li>
    <li><strong><a href="/blog/basel-sco60-crypto-capital-review-us-divergence">바젤 SCO60 크립토 자본규제 재검토</a>:</strong> 서구 금융권의 크립토 자본 비용이 오르는 배경</li>
  </ul>
  <ul class="en">
    <li><strong><a href="/en/blog/kraken-lithuania-banking-charter-bid">Kraken's push for a Lithuanian banking charter</a>:</strong> Another crypto firm chasing a traditional-finance license</li>
    <li><strong><a href="/en/blog/basel-sco60-crypto-capital-review-us-divergence">The Basel SCO60 crypto capital review</a>:</strong> Why crypto capital costs are rising in Western finance</li>
  </ul>
  <ul class="ja">
    <li><strong><a href="/ja/blog/kraken-lithuania-banking-charter-bid">クラケンのリトアニア銀行業免許への挑戦</a>:</strong> 伝統金融ライセンスを追う暗号資産企業のもう一つの例</li>
    <li><strong><a href="/ja/blog/basel-sco60-crypto-capital-review-us-divergence">バーゼルSCO60暗号資産資本規制の再検討</a>:</strong> 西側金融界で暗号資産の資本コストが上がる背景</li>
  </ul>
  <ul class="es">
    <li><strong><a href="/es/blog/kraken-lithuania-banking-charter-bid">El intento de Kraken por una carta bancaria lituana</a>:</strong> Otra firma cripto persiguiendo una licencia de finanzas tradicionales</li>
    <li><strong><a href="/es/blog/basel-sco60-crypto-capital-review-us-divergence">La revisión de capital cripto de Basilea SCO60</a>:</strong> Por qué suben los costos de capital cripto en las finanzas occidentales</li>
  </ul>
  <ul class="de">
    <li><strong><a href="/de/blog/kraken-lithuania-banking-charter-bid">Krakens Vorstoß für eine litauische Banklizenz</a>:</strong> Eine weitere Krypto-Firma auf der Jagd nach einer traditionellen Finanzlizenz</li>
    <li><strong><a href="/de/blog/basel-sco60-crypto-capital-review-us-divergence">Die Basel-SCO60-Krypto-Kapitalüberprüfung</a>:</strong> Warum die Krypto-Kapitalkosten im westlichen Finanzwesen steigen</li>
  </ul>
  <ul class="fr">
    <li><strong><a href="/fr/blog/kraken-lithuania-banking-charter-bid">La démarche de Kraken pour une charte bancaire lituanienne</a>:</strong> Une autre société crypto en quête d'une licence financière traditionnelle</li>
    <li><strong><a href="/fr/blog/basel-sco60-crypto-capital-review-us-divergence">L'examen du capital crypto de Bâle SCO60</a>:</strong> Pourquoi le coût du capital crypto augmente dans la finance occidentale</li>
  </ul>
  <ul class="pt">
    <li><strong><a href="/pt/blog/kraken-lithuania-banking-charter-bid">A busca da Kraken por uma carta bancária lituana</a>:</strong> Outra empresa cripto perseguindo uma licença financeira tradicional</li>
    <li><strong><a href="/pt/blog/basel-sco60-crypto-capital-review-us-divergence">A revisão de capital cripto de Basileia SCO60</a>:</strong> Por que os custos de capital cripto sobem nas finanças ocidentais</li>
  </ul>
  <ul class="tr">
    <li><strong><a href="/tr/blog/kraken-lithuania-banking-charter-bid">Kraken'in Litvanya bankacılık ruhsatı girişimi</a>:</strong> Geleneksel finans lisansı kovalayan bir başka kripto şirketi</li>
    <li><strong><a href="/tr/blog/basel-sco60-crypto-capital-review-us-divergence">Basel SCO60 kripto sermaye incelemesi</a>:</strong> Batı finansında kripto sermaye maliyetlerinin neden yükseldiği</li>
  </ul>
  <ul class="vi">
    <li><strong><a href="/vi/blog/kraken-lithuania-banking-charter-bid">Nỗ lực xin giấy phép ngân hàng Lithuania của Kraken</a>:</strong> Một công ty crypto khác theo đuổi giấy phép tài chính truyền thống</li>
    <li><strong><a href="/vi/blog/basel-sco60-crypto-capital-review-us-divergence">Rà soát vốn crypto Basel SCO60</a>:</strong> Vì sao chi phí vốn crypto tăng trong tài chính phương Tây</li>
  </ul>

  <p class="ko" style="font-size:.85rem;color:#71717a">출처: Businesswire(비트코인 스위스 공식 발표), CoinDesk(크라켄 리투아니아 은행업 인가 추진, 산업 맥락), crypto.news(ADGM 인가 획득 배경), FF News(FSP 세부 사항), Bitcoin Magazine·Zawya(중동 진출 확대 보도). 보유 자산·순위 수치는 시점에 따라 변동할 수 있으며, 본 글은 투자 조언이 아니다.</p>
  <p class="en" style="font-size:.85rem;color:#71717a">Sources: Businesswire (Bitcoin Suisse's official announcement), CoinDesk (Kraken's Lithuanian banking push, industry context), crypto.news (background on the ADGM approval), FF News (FSP details), Bitcoin Magazine and Zawya (coverage of the Middle East expansion). Holdings and ranking figures may vary over time; this is not investment advice.</p>
  <p class="ja" style="font-size:.85rem;color:#71717a">出典: Businesswire(ビットコイン・スイスの公式発表)、CoinDesk(クラケンのリトアニア銀行業推進、業界の文脈)、crypto.news(ADGM認可取得の背景)、FF News(FSPの詳細)、Bitcoin Magazine・Zawya(中東進出拡大の報道)。保有資産・順位の数値は時点により変動しうるものであり、本記事は投資助言ではない。</p>
  <p class="es" style="font-size:.85rem;color:#71717a">Fuentes: Businesswire (anuncio oficial de Bitcoin Suisse), CoinDesk (el impulso bancario lituano de Kraken, contexto de la industria), crypto.news (antecedentes de la aprobación del ADGM), FF News (detalles del FSP), Bitcoin Magazine y Zawya (cobertura de la expansión en Oriente Medio). Las cifras de activos y clasificación pueden variar con el tiempo; esto no es asesoramiento de inversión.</p>
  <p class="de" style="font-size:.85rem;color:#71717a">Quellen: Businesswire (offizielle Ankündigung von Bitcoin Suisse), CoinDesk (Krakens litauischer Bank-Vorstoß, Branchenkontext), crypto.news (Hintergrund zur ADGM-Genehmigung), FF News (FSP-Details), Bitcoin Magazine und Zawya (Berichterstattung zur Nahost-Expansion). Bestands- und Ranglistenzahlen können sich im Zeitverlauf ändern; dies ist keine Anlageberatung.</p>
  <p class="fr" style="font-size:.85rem;color:#71717a">Sources : Businesswire (annonce officielle de Bitcoin Suisse), CoinDesk (la démarche bancaire lituanienne de Kraken, contexte sectoriel), crypto.news (contexte de l'approbation ADGM), FF News (détails du FSP), Bitcoin Magazine et Zawya (couverture de l'expansion au Moyen-Orient). Les chiffres d'avoirs et de classement peuvent varier dans le temps ; ceci n'est pas un conseil en investissement.</p>
  <p class="pt" style="font-size:.85rem;color:#71717a">Fontes: Businesswire (anúncio oficial da Bitcoin Suisse), CoinDesk (a investida bancária da Kraken na Lituânia, contexto do setor), crypto.news (histórico da aprovação do ADGM), FF News (detalhes do FSP), Bitcoin Magazine e Zawya (cobertura da expansão no Oriente Médio). Os números de ativos e classificação podem variar com o tempo; isto não é aconselhamento de investimento.</p>
  <p class="tr" style="font-size:.85rem;color:#71717a">Kaynaklar: Businesswire (Bitcoin Suisse'in resmi duyurusu), CoinDesk (Kraken'in Litvanya bankacılık girişimi, sektör bağlamı), crypto.news (ADGM onayının arka planı), FF News (FSP detayları), Bitcoin Magazine ve Zawya (Orta Doğu genişlemesinin haberleri). Varlık ve sıralama rakamları zamanla değişebilir; bu bir yatırım tavsiyesi değildir.</p>
  <p class="vi" style="font-size:.85rem;color:#71717a">Nguồn: Businesswire (thông báo chính thức của Bitcoin Suisse), CoinDesk (nỗ lực ngân hàng tại Lithuania của Kraken, bối cảnh ngành), crypto.news (bối cảnh phê duyệt ADGM), FF News (chi tiết FSP), Bitcoin Magazine và Zawya (đưa tin về mở rộng Trung Đông). Các con số tài sản và xếp hạng có thể thay đổi theo thời gian; đây không phải lời khuyên đầu tư.</p>

<?php require __DIR__.'/_footer.php'; ?>
