<?php $slug = 'bitcoin-lth-sth-simultaneous-selling-rally'; require __DIR__.'/_header.php'; ?>

<p class="ko">비트코인이 6월 소비자물가지수(CPI) 둔화에 힘입어 6만5,500달러까지 오르며 이달 최고치를 찍었지만, 이후 이란의 미군 기지 공격 소식과 차익실현 매물이 겹치며 6만4,000달러대로 밀렸다고 코인데스크가 7월16일 보도했다. 같은 기사는 이 반등 국면에서 이례적인 조합이 벌어지고 있다고 짚었다 — 장기 보유자와 단기 보유자, 서로 다른 이유로 시장에 들어온 두 집단이 동시에 물량을 내놓고 있다는 것이다.</p>
<p class="en">Bitcoin climbed to $65,500, its monthly high, on softer June inflation data, then slid back into the $64,000 range as news of Iranian strikes on U.S. bases combined with profit-taking, CoinDesk reported on July 16. The same report flagged an unusual pairing playing out during this bounce — two investor cohorts that entered the market for entirely different reasons are selling into it at the same time.</p>
<p class="ja">ビットコインは6月の消費者物価指数(CPI)鈍化を受けて6万5,500ドルまで上昇し今月の高値を付けたが、その後イランによる米軍基地攻撃の報道と利益確定売りが重なり6万4,000ドル台まで押し戻されたとコインデスクが7月16日に報じた。同記事は、この反発局面で異例の組み合わせが起きていると指摘した——まったく異なる理由で市場に入った長期保有者と短期保有者という二つの集団が、同時に売りを出しているというのだ。</p>
<p class="es">Bitcoin subió a $65,500, su máximo mensual, gracias a datos de inflación de junio más suaves, y luego retrocedió a la banda de $64,000 cuando la noticia de ataques iraníes a bases estadounidenses se sumó a la toma de ganancias, informó CoinDesk el 16 de julio. El mismo informe señaló una combinación inusual durante este repunte — dos grupos de inversores que entraron al mercado por razones completamente distintas están vendiendo al mismo tiempo.</p>
<p class="de">Bitcoin stieg auf 65.500 Dollar, sein Monatshoch, dank schwächerer Inflationsdaten für Juni, und rutschte dann in die Spanne von 64.000 Dollar zurück, als Nachrichten über iranische Angriffe auf US-Stützpunkte mit Gewinnmitnahmen zusammentrafen, berichtete CoinDesk am 16. Juli. Derselbe Bericht wies auf eine ungewöhnliche Kombination während dieser Erholung hin — zwei Anlegergruppen, die aus völlig unterschiedlichen Gründen in den Markt eingestiegen sind, verkaufen gleichzeitig.</p>
<p class="fr">Le bitcoin a grimpé à 65 500 dollars, son plus haut mensuel, porté par des données d'inflation de juin plus faibles, avant de retomber dans la fourchette des 64 000 dollars lorsque des nouvelles de frappes iraniennes contre des bases américaines se sont combinées à des prises de bénéfices, a rapporté CoinDesk le 16 juillet. Le même rapport a relevé une combinaison inhabituelle pendant ce rebond — deux catégories d'investisseurs entrées sur le marché pour des raisons totalement différentes vendent au même moment.</p>
<p class="pt">O bitcoin subiu para US$ 65.500, sua máxima mensal, impulsionado por dados de inflação de junho mais brandos, e depois recuou para a faixa de US$ 64.000 quando notícias de ataques iranianos a bases americanas se somaram à realização de lucros, informou a CoinDesk em 16 de julho. O mesmo relatório apontou uma combinação incomum durante essa recuperação — dois grupos de investidores que entraram no mercado por razões totalmente diferentes estão vendendo ao mesmo tempo.</p>
<p class="tr">Bitcoin, Haziran ayına ait daha yumuşak enflasyon verilerinin etkisiyle aylık zirvesi olan 65.500 dolara yükseldi, ardından İran'ın ABD üslerine yönelik saldırı haberleri kâr satışlarıyla birleşince 64.000 dolar bandına geriledi; CoinDesk 16 Temmuz'da bunu bildirdi. Aynı haber, bu yükselişte sıra dışı bir kombinasyona dikkat çekti — tamamen farklı nedenlerle piyasaya giren iki yatırımcı grubu aynı anda satış yapıyor.</p>
<p class="vi">Bitcoin tăng lên 65.500 đô la, mức cao nhất trong tháng, nhờ dữ liệu lạm phát tháng 6 yếu hơn dự kiến, sau đó lùi về vùng 64.000 đô la khi tin tức về các cuộc tấn công của Iran vào các căn cứ Mỹ cộng hưởng với hoạt động chốt lời, CoinDesk đưa tin ngày 16 tháng 7. Cùng bài báo đó chỉ ra một sự kết hợp bất thường đang diễn ra trong đợt phục hồi này — hai nhóm nhà đầu tư gia nhập thị trường vì những lý do hoàn toàn khác nhau đang cùng lúc bán ra.</p>

<p class="ko">글래스노드 분류 기준으로 장기 보유자(LTH)는 최소 155일(약 5개월) 이상 코인을 옮기지 않은 주소를, 단기 보유자(STH)는 그보다 최근에 코인을 취득한 주소를 가리킨다. 코인데스크에 따르면 STH는 하루 400만달러가 넘는 규모로 이익을 실현하고 있고, LTH 쪽에서는 지난해 고점 근처에서 매수해 여전히 손실 구간에 있는 물량이 반등을 버티는 대신 파는 쪽을 택하고 있다. 두 집단이 서로 다른 동기로 같은 시점에 매도에 나서면서, 시장이 위로 뚫고 올라가려는 바로 그 순간에 물량 부담이 쌓이고 있다는 진단이다.</p>
<p class="en">By Glassnode's classification, long-term holders (LTH) are addresses that haven't moved coins in at least 155 days (roughly five months), while short-term holders (STH) acquired their coins more recently. Per CoinDesk, STH are realizing profits at a pace exceeding $4 million a day, while on the LTH side, coins bought near last year's highs and still sitting at a loss are being sold rather than held through further drawdowns. With both cohorts selling for different reasons at the same moment, the diagnosis is that overhead supply is building right as the market tries to break higher.</p>
<p class="ja">グラスノードの分類基準では、長期保有者(LTH)は少なくとも155日(約5カ月)コインを動かしていないアドレスを、短期保有者(STH)はそれより最近コインを取得したアドレスを指す。コインデスクによれば、STHは1日400万ドルを超える規模で利益を確定しており、LTH側では昨年の高値付近で買って依然として含み損の状態にある玉が、反発に耐えるのではなく売る方を選んでいる。二つの集団が異なる動機で同時に売りに出ることで、市場がまさに上抜けようとするその瞬間に供給圧力が積み上がっているという診断だ。</p>
<p class="es">Según la clasificación de Glassnode, los tenedores a largo plazo (LTH) son direcciones que no han movido sus monedas en al menos 155 días (unos cinco meses), mientras que los tenedores a corto plazo (STH) adquirieron sus monedas más recientemente. Según CoinDesk, los STH están realizando ganancias a un ritmo superior a $4 millones diarios, mientras que del lado de los LTH, monedas compradas cerca de los máximos del año pasado y que aún están en pérdida se están vendiendo en lugar de mantenerse a través de más caídas. Con ambos grupos vendiendo por razones distintas en el mismo momento, el diagnóstico es que se está acumulando oferta excedente justo cuando el mercado intenta romper al alza.</p>
<p class="de">Nach der Klassifikation von Glassnode sind langfristige Halter (LTH) Adressen, die ihre Coins seit mindestens 155 Tagen (etwa fünf Monaten) nicht bewegt haben, während kurzfristige Halter (STH) ihre Coins erst kürzlich erworben haben. Laut CoinDesk realisieren STH Gewinne in einem Tempo von mehr als 4 Millionen Dollar pro Tag, während auf der LTH-Seite Coins, die nahe den Höchstständen des Vorjahres gekauft wurden und noch immer im Minus liegen, verkauft statt durch weitere Rückgänge gehalten werden. Da beide Gruppen zur selben Zeit aus unterschiedlichen Gründen verkaufen, lautet die Diagnose, dass sich genau in dem Moment, in dem der Markt nach oben durchbrechen will, ein Angebotsüberhang aufbaut.</p>
<p class="fr">Selon la classification de Glassnode, les détenteurs de long terme (LTH) sont des adresses qui n'ont pas bougé leurs pièces depuis au moins 155 jours (environ cinq mois), tandis que les détenteurs de court terme (STH) ont acquis leurs pièces plus récemment. Selon CoinDesk, les STH réalisent des profits à un rythme dépassant 4 millions de dollars par jour, tandis que du côté des LTH, des pièces achetées près des sommets de l'an dernier et toujours en perte sont vendues plutôt que conservées à travers de nouvelles baisses. Les deux groupes vendant pour des raisons différentes au même moment, le diagnostic est qu'une offre excédentaire s'accumule précisément au moment où le marché tente de percer vers le haut.</p>
<p class="pt">Segundo a classificação da Glassnode, os detentores de longo prazo (LTH) são endereços que não movimentam suas moedas há pelo menos 155 dias (cerca de cinco meses), enquanto os detentores de curto prazo (STH) adquiriram suas moedas mais recentemente. Segundo a CoinDesk, os STH estão realizando lucros a um ritmo superior a US$ 4 milhões por dia, enquanto do lado dos LTH, moedas compradas perto das máximas do ano passado e ainda em prejuízo estão sendo vendidas em vez de mantidas através de novas quedas. Com os dois grupos vendendo por razões diferentes ao mesmo tempo, o diagnóstico é que uma oferta excedente está se acumulando bem no momento em que o mercado tenta romper para cima.</p>
<p class="tr">Glassnode sınıflandırmasına göre uzun vadeli yatırımcılar (LTH), coinlerini en az 155 gündür (yaklaşık beş ay) hareket ettirmemiş adreslerdir; kısa vadeli yatırımcılar (STH) ise coinlerini daha yakın zamanda edinmiştir. CoinDesk'e göre STH'ler günde 4 milyon doları aşan bir hızla kâr realize ediyor, LTH tarafında ise geçen yılın zirvelerine yakın alınan ve hâlâ zararda olan coinler, daha fazla düşüşe dayanmak yerine satılıyor. İki grup farklı nedenlerle aynı anda satış yaparken, piyasa tam da yukarı kırılmaya çalıştığı anda arz baskısının biriktiği teşhisi yapılıyor.</p>
<p class="vi">Theo phân loại của Glassnode, người nắm giữ dài hạn (LTH) là các địa chỉ chưa di chuyển coin trong ít nhất 155 ngày (khoảng năm tháng), trong khi người nắm giữ ngắn hạn (STH) mua coin gần đây hơn. Theo CoinDesk, STH đang hiện thực hóa lợi nhuận với tốc độ vượt 4 triệu đô la mỗi ngày, trong khi ở phía LTH, số coin mua gần đỉnh năm ngoái và vẫn đang lỗ đang bị bán ra thay vì được giữ qua các đợt giảm tiếp theo. Khi cả hai nhóm cùng bán ra vì những lý do khác nhau tại cùng một thời điểm, chẩn đoán đưa ra là áp lực nguồn cung dư thừa đang tích tụ đúng vào lúc thị trường cố gắng phá vỡ lên trên.</p>

<div class="ko en ja es de fr pt tr vi">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-family="sans-serif" font-size="17" font-weight="700">BTC $62.2K → $65.5K → $64.0K</text>
  <text x="20" y="50" fill="#a1a1aa" font-family="sans-serif" font-size="13">7/9 · 7/15 · 7/16 (KST)</text>
  <polyline points="40,150 260,150 480,80 660,110" fill="none" stroke="#38bdf8" stroke-width="3"/>
  <circle cx="40" cy="150" r="5" fill="#71717a"/>
  <circle cx="480" cy="80" r="5" fill="#4ade80"/>
  <circle cx="660" cy="110" r="5" fill="#f87171"/>
  <text x="20" y="172" fill="#71717a" font-family="sans-serif" font-size="13">$62.2K</text>
  <text x="440" y="66" fill="#4ade80" font-family="sans-serif" font-size="13.5" font-weight="700">$65.5K</text>
  <text x="590" y="128" fill="#f87171" font-family="sans-serif" font-size="13.5" font-weight="700">$64.0K</text>
  <rect x="20" y="220" width="300" height="150" rx="10" fill="#18181b" stroke="#3f3f46"/>
  <text x="40" y="254" fill="#a1a1aa" font-family="sans-serif" font-size="14">LTH</text>
  <text x="40" y="298" fill="#f87171" font-family="sans-serif" font-size="30" font-weight="800">5.58M BTC</text>
  <text x="40" y="324" fill="#71717a" font-family="sans-serif" font-size="13.5">−37%</text>
  <text x="40" y="346" fill="#71717a" font-family="sans-serif" font-size="13.5">≈75% ÷ 20M BTC</text>
  <rect x="360" y="220" width="320" height="150" rx="10" fill="#18181b" stroke="#3f3f46"/>
  <text x="380" y="254" fill="#a1a1aa" font-family="sans-serif" font-size="14">STH</text>
  <text x="380" y="298" fill="#fbbf24" font-family="sans-serif" font-size="30" font-weight="800">≥ $4M</text>
  <text x="380" y="324" fill="#71717a" font-family="sans-serif" font-size="13.5">05/2026 ≈ $82K</text>
  <text x="20" y="386" fill="#71717a" font-family="sans-serif" font-size="12">CoinDesk (7/16/2026) · Glassnode</text>
</svg>
</div>

<h2 class="ko">장기 보유자 매도와 단기 보유자 매도, 왜 같은 '매도'가 아닌가</h2>
<h2 class="en">Why LTH Selling and STH Selling Aren't the Same 'Sell'</h2>
<h2 class="ja">長期保有者の売りと短期保有者の売り、なぜ同じ「売り」ではないのか</h2>
<h2 class="es">Por Qué Vender de un LTH y de un STH No Es la Misma Cosa</h2>
<h2 class="de">Warum LTH-Verkäufe und STH-Verkäufe Nicht Dasselbe Bedeuten</h2>
<h2 class="fr">Pourquoi Vendre pour un LTH et pour un STH N'est Pas la Même Chose</h2>
<h2 class="pt">Por Que Vender de um LTH e de um STH Não é a Mesma Coisa</h2>
<h2 class="tr">LTH Satışı ile STH Satışı Neden Aynı 'Satış' Değil</h2>
<h2 class="vi">Tại Sao Bán Của LTH Và STH Không Phải Là Cùng Một Loại 'Bán'</h2>

<p class="ko">표면적으로는 둘 다 '판다'는 같은 행동이지만 신호는 다르다. STH가 반등장에서 이익을 실현하는 건 통상적인 시장 행태에 가깝다 — 저점 근처에서 사들인 물량을 값이 오르자 정리하는 것이다. 문제는 LTH 쪽이다. 코인데스크에 따르면 현재 558만 BTC가 손실 구간에 있는 장기 보유자 물량이며, 이는 전체 장기 보유자 물량의 37%에 해당한다. 장기 보유자는 전체 유통량의 약 75%를 쥐고 있는 만큼, 이 37%가 향하는 방향은 시장 전체에 작지 않은 무게를 지닌다. 이들이 지금 파는 건 '이익 실현'이 아니라 '반등을 믿지 못해 손실을 확정짓는' 쪽에 가깝다는 게 코인데스크의 해석이다.</p>
<p class="en">On the surface both actions are "selling," but the signal differs. STH taking profit during a bounce is close to ordinary market behavior — clearing out coins bought near the lows once price rises. The LTH side is the problem. Per CoinDesk, 5.58 million BTC of long-term-holder supply currently sits at a loss, which is 37% of all LTH supply. Since long-term holders control roughly 75% of circulating supply, where that 37% goes carries real weight for the market as a whole. What they're selling now looks less like profit-taking and more like locking in a loss because they no longer trust the bounce, CoinDesk's read suggests.</p>
<p class="ja">表面的にはどちらも「売る」という同じ行動だが、そのシグナルは異なる。STHが反発局面で利益を確定するのは、比較的通常の市場行動に近い——安値付近で買った玉を、値が上がったところで整理しているだけだ。問題はLTH側である。コインデスクによれば、現在558万BTCが含み損の状態にある長期保有者の玉であり、これは長期保有者全体の玉の37%に相当する。長期保有者は全流通量の約75%を握っているだけに、この37%が向かう方向は市場全体にとって軽くない重みを持つ。彼らが今売っているのは「利益確定」ではなく「反発を信じられず損失を確定させる」方に近いというのが、コインデスクの解釈だ。</p>
<p class="es">En la superficie ambas acciones son "vender", pero la señal es distinta. Que los STH tomen ganancias durante un repunte es un comportamiento de mercado bastante ordinario — liquidar monedas compradas cerca de los mínimos una vez que el precio sube. El lado de los LTH es el problema. Según CoinDesk, 5.58 millones de BTC de la oferta de tenedores a largo plazo están actualmente en pérdida, lo que equivale al 37% de toda la oferta LTH. Dado que los tenedores a largo plazo controlan cerca del 75% de la oferta circulante, hacia dónde se mueva ese 37% tiene un peso real para el mercado en su conjunto. Lo que están vendiendo ahora se parece menos a tomar ganancias y más a asegurar una pérdida porque ya no confían en el repunte, sugiere la lectura de CoinDesk.</p>
<p class="de">Oberflächlich betrachtet sind beide Aktionen "Verkaufen", doch das Signal unterscheidet sich. Dass STH während einer Erholung Gewinne mitnehmen, ist ziemlich gewöhnliches Marktverhalten — Coins, die nahe den Tiefs gekauft wurden, werden nach einem Preisanstieg abgestoßen. Das Problem liegt bei den LTH. Laut CoinDesk befinden sich derzeit 5,58 Millionen BTC des Long-Term-Holder-Angebots im Minus, das sind 37 % des gesamten LTH-Angebots. Da langfristige Halter rund 75 % des zirkulierenden Angebots kontrollieren, hat die Richtung dieser 37 % echtes Gewicht für den gesamten Markt. Was sie jetzt verkaufen, sieht laut CoinDesks Lesart weniger nach Gewinnmitnahme aus als danach, einen Verlust festzuschreiben, weil sie der Erholung nicht mehr trauen.</p>
<p class="fr">En surface, les deux actions sont des « ventes », mais le signal diffère. Que les STH prennent des bénéfices pendant un rebond est un comportement de marché assez ordinaire — se débarrasser de pièces achetées près des creux une fois le prix remonté. Le côté LTH pose problème. Selon CoinDesk, 5,58 millions de BTC de l'offre des détenteurs de long terme sont actuellement en perte, soit 37 % de toute l'offre LTH. Les détenteurs de long terme contrôlant environ 75 % de l'offre en circulation, la direction que prennent ces 37 % pèse réellement sur l'ensemble du marché. Ce qu'ils vendent maintenant ressemble moins à une prise de bénéfices qu'à l'acceptation d'une perte parce qu'ils ne font plus confiance au rebond, suggère la lecture de CoinDesk.</p>
<p class="pt">Na superfície, ambas as ações são "vender", mas o sinal é diferente. Os STH realizando lucro durante uma recuperação é um comportamento de mercado bastante comum — liquidar moedas compradas perto das mínimas depois que o preço sobe. O lado dos LTH é o problema. Segundo a CoinDesk, 5,58 milhões de BTC da oferta de detentores de longo prazo estão atualmente em prejuízo, o que equivale a 37% de toda a oferta LTH. Como os detentores de longo prazo controlam cerca de 75% da oferta em circulação, para onde esses 37% se movem tem peso real para o mercado como um todo. O que estão vendendo agora se parece menos com realização de lucro e mais com travar um prejuízo porque não confiam mais na recuperação, sugere a leitura da CoinDesk.</p>
<p class="tr">Yüzeyde her iki eylem de "satış" ama sinyal farklı. STH'lerin yükseliş sırasında kâr realize etmesi oldukça sıradan bir piyasa davranışına yakın — dip seviyelere yakın alınan coinlerin fiyat yükseldiğinde elden çıkarılması. Sorun LTH tarafında. CoinDesk'e göre şu anda 5,58 milyon BTC'lik uzun vadeli yatırımcı arzı zararda, bu da tüm LTH arzının %37'sine denk geliyor. Uzun vadeli yatırımcılar dolaşımdaki arzın yaklaşık %75'ini kontrol ettiğinden, bu %37'lik kısmın hangi yöne gittiği tüm piyasa için gerçek bir ağırlık taşıyor. Şu anda sattıkları şey "kâr realizasyonu"ndan çok, yükselişe artık güvenmedikleri için zararı kesinleştirmeye benziyor; CoinDesk'in yorumu bu yönde.</p>
<p class="vi">Bề ngoài cả hai hành động đều là "bán", nhưng tín hiệu lại khác nhau. Việc STH chốt lời trong đợt phục hồi khá giống hành vi thị trường thông thường — thanh lý số coin mua gần đáy sau khi giá tăng. Vấn đề nằm ở phía LTH. Theo CoinDesk, hiện có 5,58 triệu BTC thuộc nguồn cung của người nắm giữ dài hạn đang ở trạng thái lỗ, chiếm 37% tổng nguồn cung LTH. Vì người nắm giữ dài hạn kiểm soát khoảng 75% nguồn cung lưu hành, hướng đi của 37% đó mang trọng lượng thực sự đối với toàn thị trường. Những gì họ đang bán ra hiện nay ít giống với chốt lời hơn mà giống với việc chốt lỗ vì không còn tin vào đợt phục hồi, theo cách diễn giải của CoinDesk.</p>

<p class="ko">이 사이트가 7월6일 짚었던 <a href="/blog/lth-supply-returns-to-accumulation">장기 보유자 순매집 전환 점검</a>에서는 LTH가 과거 대비 4분의 1 규모이긴 해도 다시 사모으는 쪽으로 돌아섰다고 짚은 바 있다. 열흘 만에 그 흐름이 손실 구간 매도로 뒤집혔다면, 이는 일회성 노이즈라기보다 반등의 지속 가능성에 대한 장기 보유자들의 확신이 실제로 흔들렸다는 신호로 읽을 여지가 있다. 다만 이 사이트가 7월13일 확인한 <a href="/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">장기 보유자 공급 사상 최고치 점검</a>이 짚었듯, LTH 관련 지표는 '보유 물량 자체'와 '그 물량의 손익 상태'를 함께 봐야 온전한 그림이 나온다 — 지금은 보유량은 여전히 많은데 그 안의 손익 구성이 나빠지는 국면이다.</p>
<p class="en">This site's July 6 <a href="/en/blog/lth-supply-returns-to-accumulation">check on long-term holders returning to accumulation</a> found LTH had turned back to buying, even at a quarter of the past pace. If that flow flipped to loss-driven selling in just ten days, it's less likely to be one-off noise and more likely a genuine sign that long-term holders' confidence in the bounce's durability has cracked. Still, as this site's July 13 <a href="/en/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">check on record LTH supply</a> pointed out, LTH metrics only give the full picture when you look at both the raw amount held and the profit-and-loss state of that holding — right now the amount held remains high, but the profit/loss mix inside it is deteriorating.</p>
<p class="ja">当サイトが7月6日に取り上げた<a href="/ja/blog/lth-supply-returns-to-accumulation">長期保有者の純買い集め転換点検</a>では、LTHが過去に比べ4分の1の規模とはいえ、再び買い集める方向に転じたと指摘していた。わずか10日でその流れが含み損主導の売りへと反転したのなら、それは一過性のノイズというより、反発の持続性に対する長期保有者の確信が実際に揺らいだサインと読む余地がある。ただし、当サイトが7月13日に確認した<a href="/ja/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">長期保有者供給の史上最高値点検</a>が指摘していたように、LTH関連指標は「保有量そのもの」と「その玉の損益状態」を合わせて見て初めて全体像が見える——今は保有量自体は依然として多いのに、その中身の損益構成が悪化している局面だ。</p>
<p class="es">El <a href="/es/blog/lth-supply-returns-to-accumulation">análisis de este sitio del 6 de julio sobre el retorno de los tenedores a largo plazo a la acumulación</a> encontró que los LTH habían vuelto a comprar, aunque a un cuarto del ritmo pasado. Si ese flujo se invirtió hacia una venta impulsada por pérdidas en apenas diez días, es menos probable que sea ruido puntual y más probable que sea una señal genuina de que la confianza de los tenedores a largo plazo en la durabilidad del repunte se ha resquebrajado. Aun así, como señaló el <a href="/es/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">análisis de este sitio del 13 de julio sobre la oferta récord de LTH</a>, las métricas de LTH solo dan el panorama completo cuando se observan tanto la cantidad bruta en manos como el estado de ganancias y pérdidas de esa tenencia — ahora mismo la cantidad en manos sigue siendo alta, pero la mezcla de ganancias y pérdidas dentro de ella se está deteriorando.</p>
<p class="de">Die <a href="/de/blog/lth-supply-returns-to-accumulation">Prüfung dieser Seite vom 6. Juli zur Rückkehr langfristiger Halter zur Akkumulation</a> ergab, dass LTH wieder zu kaufen begonnen hatten, wenn auch nur mit einem Viertel des früheren Tempos. Wenn dieser Fluss innerhalb von nur zehn Tagen zu verlustgetriebenen Verkäufen umgekippt ist, handelt es sich eher weniger um einmaliges Rauschen als vielmehr um ein echtes Zeichen dafür, dass das Vertrauen langfristiger Halter in die Nachhaltigkeit der Erholung tatsächlich gebrochen ist. Dennoch geben LTH-Kennzahlen, wie die <a href="/de/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">Prüfung dieser Seite vom 13. Juli zum rekordhohen LTH-Angebot</a> feststellte, nur dann das vollständige Bild, wenn man sowohl die reine gehaltene Menge als auch den Gewinn-Verlust-Status dieses Bestands betrachtet — derzeit bleibt die gehaltene Menge hoch, doch die Gewinn-Verlust-Zusammensetzung darin verschlechtert sich.</p>
<p class="fr">L'<a href="/fr/blog/lth-supply-returns-to-accumulation">examen de ce site du 6 juillet sur le retour des détenteurs de long terme à l'accumulation</a> avait constaté que les LTH s'étaient remis à acheter, même à un quart du rythme passé. Si ce flux a basculé vers une vente motivée par les pertes en seulement dix jours, il s'agit probablement moins d'un bruit ponctuel que d'un signe réel que la confiance des détenteurs de long terme dans la durabilité du rebond s'est fissurée. Pourtant, comme l'a souligné l'<a href="/fr/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">examen de ce site du 13 juillet sur l'offre record des LTH</a>, les indicateurs LTH ne donnent une image complète que si l'on observe à la fois la quantité brute détenue et l'état des gains et pertes de cette détention — en ce moment, la quantité détenue reste élevée, mais la composition des gains et pertes en son sein se dégrade.</p>
<p class="pt">A <a href="/pt/blog/lth-supply-returns-to-accumulation">análise deste site de 6 de julho sobre o retorno dos detentores de longo prazo à acumulação</a> constatou que os LTH haviam voltado a comprar, ainda que a um quarto do ritmo passado. Se esse fluxo se inverteu para uma venda motivada por prejuízo em apenas dez dias, é menos provável que seja ruído pontual e mais provável que seja um sinal genuíno de que a confiança dos detentores de longo prazo na durabilidade da recuperação se rompeu. Ainda assim, como apontou a <a href="/pt/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">análise deste site de 13 de julho sobre a oferta recorde de LTH</a>, as métricas de LTH só dão o quadro completo quando se observa tanto a quantidade bruta detida quanto o estado de lucro e prejuízo dessa posição — agora a quantidade detida permanece alta, mas a composição de lucro/prejuízo dentro dela está piorando.</p>
<p class="tr">Bu sitenin 6 Temmuz'daki <a href="/tr/blog/lth-supply-returns-to-accumulation">uzun vadeli yatırımcıların birikime dönüşü incelemesi</a>, LTH'lerin geçmiş hıza göre dörtte biri olsa da yeniden alıma döndüğünü tespit etmişti. Bu akış sadece on gün içinde zarar odaklı satışa dönmüşse, bu tek seferlik bir gürültüden çok, uzun vadeli yatırımcıların yükselişin kalıcılığına olan güveninin gerçekten sarsıldığının bir işareti olabilir. Yine de bu sitenin 13 Temmuz'daki <a href="/tr/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">rekor LTH arzı incelemesi</a>nin belirttiği gibi, LTH göstergeleri ancak hem elde tutulan ham miktara hem de bu miktarın kâr-zarar durumuna birlikte bakıldığında tam resmi verir — şu anda elde tutulan miktar hâlâ yüksek, ama içindeki kâr-zarar bileşimi kötüleşiyor.</p>
<p class="vi">Bài kiểm tra của trang này ngày 6 tháng 7 về <a href="/vi/blog/lth-supply-returns-to-accumulation">việc người nắm giữ dài hạn quay lại tích lũy</a> phát hiện LTH đã quay lại mua vào, dù chỉ bằng một phần tư tốc độ trước đây. Nếu dòng chảy đó đảo chiều sang bán tháo do thua lỗ chỉ trong mười ngày, thì khả năng đây không phải là nhiễu nhất thời mà là dấu hiệu thực sự cho thấy niềm tin của người nắm giữ dài hạn vào độ bền của đợt phục hồi đã lung lay. Tuy nhiên, như bài kiểm tra ngày 13 tháng 7 của trang này về <a href="/vi/blog/lth-supply-buyer-drought-whale-dolphin-stall-gap">nguồn cung LTH đạt kỷ lục</a> đã chỉ ra, các chỉ số LTH chỉ cho bức tranh đầy đủ khi nhìn vào cả lượng nắm giữ thô lẫn trạng thái lãi/lỗ của lượng nắm giữ đó — hiện tại lượng nắm giữ vẫn cao, nhưng cơ cấu lãi/lỗ bên trong đang xấu đi.</p>

<h2 class="ko">5월의 재현인가 — 과거 사례와 비교</h2>
<h2 class="en">A Repeat of May? Comparing It to the Last Time</h2>
<h2 class="ja">5月の再来か——過去の事例との比較</h2>
<h2 class="es">¿Una Repetición de Mayo? Comparando con la Última Vez</h2>
<h2 class="de">Eine Wiederholung des Mai? Ein Vergleich mit dem Letzten Mal</h2>
<h2 class="fr">Une Répétition de Mai ? Comparaison avec la Dernière Fois</h2>
<h2 class="pt">Uma Repetição de Maio? Comparando com a Última Vez</h2>
<h2 class="tr">Mayıs'ın Tekrarı mı? Son Seferle Karşılaştırma</h2>
<h2 class="vi">Liệu Có Lặp Lại Tháng Năm? So Sánh Với Lần Trước</h2>

<p class="ko">코인데스크는 지금의 STH 매도 강도를 5월과 견줬다. 당시 비트코인이 200일 이동평균선을 뚫고 8만2,000달러를 웃돌자 단기 보유자들의 대규모 이익실현이 나타났고, 그 반등은 이어지지 못했다 — 현재 가격은 그보다 20% 이상 낮은 6만4,000달러대다. 저항선 부근에서 STH 매도가 몰리는 패턴이 이번에도 재현된다면, 이번 반등 역시 비슷한 결말을 맞을 수 있다는 우려가 나오는 배경이다.</p>
<p class="en">CoinDesk compared today's STH selling intensity to May, when bitcoin broke above its 200-day moving average past $82,000 and short-term holders took large-scale profits — a bounce that didn't hold; the price today sits more than 20% lower, in the $64,000s. If the pattern of STH selling clustering near resistance repeats here, it's the basis for concern that this bounce could meet a similar fate.</p>
<p class="ja">コインデスクは今回のSTH売りの強度を5月と比較した。当時、ビットコインが200日移動平均線を突破し8万2,000ドルを上回ると、短期保有者による大規模な利益確定が現れ、その反発は続かなかった——現在の価格はそれより20%以上低い6万4,000ドル台だ。抵抗線付近でSTH売りが集中するパターンが今回も再現されるなら、今回の反発も似たような結末を迎えかねないという懸念の背景である。</p>
<p class="es">CoinDesk comparó la intensidad de venta actual de los STH con mayo, cuando bitcoin rompió por encima de su media móvil de 200 días superando los $82,000 y los tenedores a corto plazo tomaron ganancias a gran escala — un repunte que no se sostuvo; el precio hoy está más de un 20% más bajo, en los $64,000. Si el patrón de venta de STH concentrándose cerca de la resistencia se repite aquí, es la base de la preocupación de que este repunte pueda correr una suerte similar.</p>
<p class="de">CoinDesk verglich die heutige STH-Verkaufsintensität mit dem Mai, als Bitcoin über seinen 200-Tage-Durchschnitt hinaus auf über 82.000 Dollar ausbrach und kurzfristige Halter in großem Stil Gewinne mitnahmen — eine Erholung, die sich nicht hielt; der Preis liegt heute mehr als 20 % niedriger, im Bereich von 64.000 Dollar. Wiederholt sich das Muster von STH-Verkäufen, die sich nahe dem Widerstand häufen, hier erneut, ist das der Grund für die Sorge, dass diese Erholung ein ähnliches Schicksal erleiden könnte.</p>
<p class="fr">CoinDesk a comparé l'intensité de vente actuelle des STH à celle de mai, lorsque le bitcoin avait franchi sa moyenne mobile à 200 jours au-delà de 82 000 dollars et que les détenteurs de court terme avaient pris des bénéfices à grande échelle — un rebond qui n'a pas tenu ; le prix se situe aujourd'hui plus de 20 % plus bas, dans les 64 000 dollars. Si le schéma de ventes STH se concentrant près de la résistance se répète ici, c'est la base de la crainte que ce rebond connaisse un sort similaire.</p>
<p class="pt">A CoinDesk comparou a intensidade de venda atual dos STH com maio, quando o bitcoin rompeu acima de sua média móvel de 200 dias superando US$ 82.000 e os detentores de curto prazo realizaram lucros em grande escala — uma recuperação que não se sustentou; o preço hoje está mais de 20% mais baixo, na faixa de US$ 64.000. Se o padrão de vendas de STH se concentrando perto da resistência se repetir aqui, essa é a base da preocupação de que essa recuperação possa ter um destino semelhante.</p>
<p class="tr">CoinDesk, bugünkü STH satış yoğunluğunu, bitcoin'in 200 günlük hareketli ortalamasını aşıp 82.000 doları geçtiği ve kısa vadeli yatırımcıların büyük ölçekli kâr realizasyonu yaptığı Mayıs ayıyla karşılaştırdı — o yükseliş kalıcı olmamıştı; bugün fiyat bundan %20'den fazla düşük olan 64.000 dolar bandında. Direnç seviyeleri yakınında STH satışlarının yoğunlaşması kalıbı burada da tekrarlanırsa, bu yükselişin de benzer bir sona uğrayabileceği endişesinin temeli bu.</p>
<p class="vi">CoinDesk so sánh cường độ bán ra của STH hiện nay với tháng 5, khi bitcoin phá vỡ lên trên đường trung bình động 200 ngày, vượt mốc 82.000 đô la và người nắm giữ ngắn hạn chốt lời trên diện rộng — một đợt phục hồi không trụ được; giá hôm nay thấp hơn hơn 20%, ở mức 64.000 đô la. Nếu mô hình bán ra của STH tập trung gần vùng kháng cự lặp lại lần này, đó là cơ sở cho lo ngại rằng đợt phục hồi này có thể gặp kết cục tương tự.</p>

<p class="ko">다만 5월과 완전히 같은 상황은 아니다. 5월 매도는 STH 단독으로 이뤄졌지만, 이번엔 LTH까지 가세했다는 점이 다르다. 통상 LTH는 시장의 '강한 손'으로 불리며 조정기에도 잘 흔들리지 않는 축으로 여겨진다. 그 축마저 흔들린다는 건 이번 매도 압력이 5월보다 구조적으로 더 넓은 기반에서 나오고 있다는 뜻일 수 있다 — 물론 그 폭이 실제로 5월보다 큰 하락으로 이어질지는 아직 확인되지 않았다.</p>
<p class="en">Still, it isn't quite the same setup as May. May's selling came from STH alone; this time LTH have joined in. LTH are usually called the market's "strong hands," an anchor that tends not to waver even through corrections. That anchor showing cracks could mean this round of selling pressure has a structurally broader base than May's — though whether that translates into a bigger decline than May's hasn't been confirmed yet.</p>
<p class="ja">ただし5月とまったく同じ状況ではない。5月の売りはSTH単独によるものだったが、今回はLTHまで加わっている点が違う。LTHは通常、市場の「強い手」と呼ばれ、調整局面でもあまり揺らがない軸とみなされている。その軸すら揺らいでいるということは、今回の売り圧力が5月より構造的に広い基盤から来ている可能性を意味しうる——もっとも、その広がりが実際に5月より大きな下落につながるかどうかはまだ確認されていない。</p>
<p class="es">Aun así, no es exactamente la misma configuración que mayo. La venta de mayo provino solo de los STH; esta vez se han sumado los LTH. Los LTH suelen llamarse las "manos fuertes" del mercado, un ancla que tiende a no tambalear ni siquiera durante correcciones. Que ese ancla muestre grietas podría significar que esta ronda de presión vendedora tiene una base estructuralmente más amplia que la de mayo — aunque si eso se traduce en una caída mayor que la de mayo todavía no se ha confirmado.</p>
<p class="de">Dennoch ist es nicht ganz dieselbe Ausgangslage wie im Mai. Die Verkäufe im Mai kamen allein von STH; diesmal sind auch LTH mit dabei. LTH werden gewöhnlich als die "starken Hände" des Marktes bezeichnet, ein Anker, der selbst durch Korrekturen hindurch selten wankt. Dass dieser Anker Risse zeigt, könnte bedeuten, dass dieser Verkaufsdruck strukturell auf einer breiteren Basis steht als im Mai — ob sich das jedoch in einen größeren Rückgang als im Mai übersetzt, ist noch nicht bestätigt.</p>
<p class="fr">Pourtant, la configuration n'est pas tout à fait la même qu'en mai. Les ventes de mai provenaient uniquement des STH ; cette fois, les LTH s'y sont joints. Les LTH sont habituellement qualifiés de « mains fortes » du marché, un point d'ancrage qui a tendance à ne pas vaciller même durant les corrections. Que cet ancrage montre des fissures pourrait signifier que cette vague de pression vendeuse repose sur une base structurellement plus large qu'en mai — bien que la question de savoir si cela se traduira par une baisse plus importante qu'en mai reste sans réponse.</p>
<p class="pt">Ainda assim, não é exatamente a mesma configuração de maio. A venda de maio veio apenas dos STH; desta vez os LTH se juntaram. Os LTH costumam ser chamados de "mãos fortes" do mercado, uma âncora que tende a não vacilar nem mesmo durante correções. Essa âncora mostrando rachaduras pode significar que esta rodada de pressão de venda tem uma base estruturalmente mais ampla do que a de maio — embora se isso se traduz em uma queda maior do que a de maio ainda não tenha sido confirmado.</p>
<p class="tr">Yine de bu, Mayıs'takiyle tam olarak aynı kurulum değil. Mayıs'taki satış yalnızca STH'lerden geliyordu; bu sefer LTH'ler de katıldı. LTH'ler genellikle piyasanın "güçlü elleri" olarak adlandırılır, düzeltmeler sırasında bile pek sarsılmayan bir çapa olarak görülür. Bu çapanın çatlaklar göstermesi, bu satış baskısı dalgasının Mayıs'takinden yapısal olarak daha geniş bir tabana sahip olabileceği anlamına gelebilir — ancak bunun Mayıs'takinden daha büyük bir düşüşe dönüşüp dönüşmeyeceği henüz doğrulanmadı.</p>
<p class="vi">Tuy nhiên, đây không hoàn toàn giống tình huống của tháng 5. Đợt bán tháng 5 chỉ đến từ STH; lần này LTH cũng tham gia. LTH thường được gọi là "bàn tay vững" của thị trường, một điểm neo thường không dao động ngay cả trong các đợt điều chỉnh. Việc điểm neo đó xuất hiện vết nứt có thể có nghĩa là đợt áp lực bán này có nền tảng rộng hơn về mặt cấu trúc so với tháng 5 — dù điều đó có dẫn đến một đợt giảm lớn hơn tháng 5 hay không thì vẫn chưa được xác nhận.</p>

<h2 class="ko">다르게 읽을 여지도 있다 — 오버행이 곧 폭락을 뜻하진 않는다</h2>
<h2 class="en">There's Room for a Different Reading — Overhead Supply Isn't the Same as a Crash</h2>
<h2 class="ja">別の読み方の余地もある——オーバーハングは即暴落を意味しない</h2>
<h2 class="es">Hay Espacio para una Lectura Distinta — La Oferta Excedente No es lo Mismo que un Desplome</h2>
<h2 class="de">Es Gibt Raum für eine Andere Lesart — Angebotsüberhang Ist Kein Crash</h2>
<h2 class="fr">Il y a de la Place pour une Lecture Différente — Une Offre Excédentaire N'est Pas un Krach</h2>
<h2 class="pt">Há Espaço para uma Leitura Diferente — Oferta Excedente Não é o Mesmo que um Colapso</h2>
<h2 class="tr">Farklı Bir Okumaya da Yer Var — Arz Baskısı Çöküşle Aynı Şey Değil</h2>
<h2 class="vi">Vẫn Có Chỗ Cho Một Cách Diễn Giải Khác — Dư Cung Không Đồng Nghĩa Với Sụp Đổ</h2>

<p class="ko">코인데스크의 '물량 부담' 진단은 비관적 프레이밍에 가깝다. 하지만 같은 물량 이동을 다르게 읽을 수도 있다. 미국 스팟 비트코인 ETF는 7월14일 약 1억9,110만달러, 7월15일 약 1,000만달러 순유입을 기록하며 최근 며칠간 매수세를 이어갔다. LTH·STH가 내놓는 물량을 ETF를 통한 기관 수요가 흡수하고 있다면, 지금의 매도는 시장을 무너뜨리는 압력이 아니라 '약한 손에서 강한 손으로' 소유권이 넘어가는 정상적인 순환 과정일 수도 있다.</p>
<p class="en">CoinDesk's "overhead supply" framing leans pessimistic. But the same flow of coins can be read differently. U.S. spot bitcoin ETFs logged roughly $191.1 million in net inflows on July 14 and about $10 million on July 15, extending a run of buying over the past several days. If institutional demand flowing through ETFs is absorbing what LTH and STH are putting up for sale, today's selling might not be pressure that breaks the market — it could be an ordinary rotation of ownership from weak hands to strong ones.</p>
<p class="ja">コインデスクの「供給圧力」という枠組みは悲観的な色合いが強い。しかし同じ玉の動きを別様に読むこともできる。米スポットビットコインETFは7月14日に約1億9,110万ドル、7月15日に約1,000万ドルの純流入を記録し、ここ数日買い越しが続いている。LTH・STHが出す玉をETF経由の機関需要が吸収しているのなら、今の売りは市場を崩す圧力ではなく、「弱い手から強い手へ」所有権が移る正常な循環過程である可能性もある。</p>
<p class="es">El encuadre de "oferta excedente" de CoinDesk se inclina hacia lo pesimista. Pero el mismo flujo de monedas puede leerse de otra manera. Los ETF spot de bitcoin en EE.UU. registraron unos $191.1 millones en entradas netas el 14 de julio y unos $10 millones el 15 de julio, extendiendo una racha de compras en los últimos días. Si la demanda institucional que fluye a través de los ETF está absorbiendo lo que los LTH y STH ponen a la venta, la venta de hoy podría no ser presión que rompa el mercado — podría ser una rotación ordinaria de propiedad de manos débiles a manos fuertes.</p>
<p class="de">CoinDesks Framing als "Angebotsüberhang" tendiert zum Pessimismus. Doch derselbe Coin-Fluss lässt sich auch anders lesen. US-Spot-Bitcoin-ETFs verzeichneten am 14. Juli netto rund 191,1 Millionen Dollar und am 15. Juli etwa 10 Millionen Dollar an Zuflüssen und setzten damit eine mehrtägige Kaufserie fort. Wenn institutionelle Nachfrage über ETFs das absorbiert, was LTH und STH zum Verkauf anbieten, ist der heutige Verkauf womöglich kein marktbrechender Druck — er könnte eine gewöhnliche Rotation des Eigentums von schwachen zu starken Händen sein.</p>
<p class="fr">Le cadrage de CoinDesk en « offre excédentaire » penche vers le pessimisme. Mais le même flux de pièces peut se lire différemment. Les ETF spot bitcoin américains ont enregistré environ 191,1 millions de dollars d'entrées nettes le 14 juillet et environ 10 millions le 15 juillet, prolongeant une série d'achats sur plusieurs jours. Si la demande institutionnelle passant par les ETF absorbe ce que les LTH et STH mettent en vente, la vente d'aujourd'hui n'est peut-être pas une pression qui casse le marché — elle pourrait être une rotation ordinaire de propriété des mains faibles vers les mains fortes.</p>
<p class="pt">O enquadramento de "oferta excedente" da CoinDesk tende ao pessimismo. Mas o mesmo fluxo de moedas pode ser lido de outra forma. Os ETFs spot de bitcoin dos EUA registraram cerca de US$ 191,1 milhões em entradas líquidas em 14 de julho e cerca de US$ 10 milhões em 15 de julho, estendendo uma sequência de compras nos últimos dias. Se a demanda institucional fluindo pelos ETFs está absorvendo o que LTH e STH estão colocando à venda, a venda de hoje pode não ser pressão que quebra o mercado — pode ser uma rotação comum de propriedade de mãos fracas para mãos fortes.</p>
<p class="tr">CoinDesk'in "arz baskısı" çerçevelemesi kötümserliğe yakın. Ama aynı coin akışı farklı okunabilir. ABD spot bitcoin ETF'leri 14 Temmuz'da yaklaşık 191,1 milyon dolar, 15 Temmuz'da ise yaklaşık 10 milyon dolar net giriş kaydederek son birkaç günlük alım serisini sürdürdü. LTH ve STH'lerin satışa çıkardığı arzı ETF'ler üzerinden gelen kurumsal talep emiyorsa, bugünkü satış piyasayı kıran bir baskı olmayabilir — zayıf ellerden güçlü ellere geçen sıradan bir mülkiyet rotasyonu olabilir.</p>
<p class="vi">Cách diễn giải "dư cung" của CoinDesk nghiêng về bi quan. Nhưng cùng một dòng chảy coin có thể được đọc khác đi. Các ETF bitcoin giao ngay của Mỹ ghi nhận khoảng 191,1 triệu đô la dòng vào ròng vào ngày 14 tháng 7 và khoảng 10 triệu đô la vào ngày 15 tháng 7, nối dài chuỗi mua vào trong vài ngày qua. Nếu nhu cầu tổ chức chảy qua ETF đang hấp thụ những gì LTH và STH bán ra, thì việc bán ra hôm nay có thể không phải là áp lực phá vỡ thị trường — mà có thể là một vòng quay quyền sở hữu bình thường từ tay yếu sang tay mạnh.</p>

<p class="ko">관건은 그 흡수 속도다. 코인데스크 자체도 최근 ETF 유입이 6월 대규모 순유출(약 45억달러) 이후 아직 '추세 반전'이라 부르기엔 이르다고 짚었다. 매도 물량과 매수 물량 중 어느 쪽이 더 빨리 늘어나는지에 따라 다음 며칠의 방향이 갈릴 것으로 보이며, 이 사이트는 이 균형이 어느 쪽으로 기우는지를 계속 확인할 계획이다.</p>
<p class="en">The question is how fast that absorption happens. CoinDesk itself has noted it's still too early to call the recent ETF inflows a "trend reversal" after June's large net outflows of roughly $4.5 billion. Which side — the coins being sold or the demand buying them — grows faster over the coming days looks set to decide the direction from here, and this site plans to keep checking which way that balance tips.</p>
<p class="ja">問題はその吸収がどれだけ速く進むかだ。コインデスク自身も、6月の大規模な純流出(約45億ドル)の後で最近のETF流入を「トレンド転換」と呼ぶにはまだ早いと指摘している。売られる玉とそれを買う需要のどちらがより速く増えるかによって、これから数日の方向性が決まりそうであり、当サイトはこの均衡がどちらに傾くかを引き続き確認していく方針だ。</p>
<p class="es">La pregunta es qué tan rápido ocurre esa absorción. El propio CoinDesk ha señalado que todavía es pronto para llamar "reversión de tendencia" a las recientes entradas de ETF tras las grandes salidas netas de junio, de unos $4,500 millones. Cuál de los dos lados — las monedas que se venden o la demanda que las compra — crezca más rápido en los próximos días parece que decidirá la dirección desde aquí, y este sitio planea seguir comprobando hacia qué lado se inclina ese equilibrio.</p>
<p class="de">Die Frage ist, wie schnell diese Absorption erfolgt. CoinDesk selbst hat angemerkt, dass es nach den großen Nettoabflüssen im Juni von rund 4,5 Milliarden Dollar noch zu früh ist, die jüngsten ETF-Zuflüsse als "Trendwende" zu bezeichnen. Welche Seite — die verkauften Coins oder die sie kaufende Nachfrage — in den kommenden Tagen schneller wächst, dürfte die Richtung von hier an bestimmen, und diese Seite plant, weiter zu beobachten, in welche Richtung sich dieses Gleichgewicht neigt.</p>
<p class="fr">La question est de savoir à quelle vitesse cette absorption se produit. CoinDesk lui-même a noté qu'il est encore trop tôt pour qualifier les récentes entrées d'ETF de « renversement de tendance » après les importantes sorties nettes de juin, d'environ 4,5 milliards de dollars. Le camp — les pièces vendues ou la demande qui les achète — qui croît le plus vite dans les prochains jours semble devoir décider de la direction à partir d'ici, et ce site prévoit de continuer à vérifier de quel côté penche cet équilibre.</p>
<p class="pt">A questão é a rapidez com que essa absorção acontece. A própria CoinDesk observou que ainda é cedo para chamar as recentes entradas de ETF de "reversão de tendência" após as grandes saídas líquidas de junho, de cerca de US$ 4,5 bilhões. Qual lado — as moedas sendo vendidas ou a demanda que as compra — cresce mais rápido nos próximos dias parece que vai decidir a direção a partir daqui, e este site planeja continuar verificando para qual lado esse equilíbrio pende.</p>
<p class="tr">Soru, bu emilimin ne kadar hızlı gerçekleştiği. CoinDesk'in kendisi de, Haziran'daki yaklaşık 4,5 milyar dolarlık büyük net çıkışların ardından son ETF girişlerini "trend tersine dönüşü" olarak adlandırmanın hâlâ erken olduğunu belirtti. Satılan coinler mi yoksa onları satın alan talep mi önümüzdeki günlerde daha hızlı büyüyecek, buradan sonraki yönü bu belirleyecek gibi görünüyor ve bu site bu dengenin hangi yöne kaydığını takip etmeye devam edecek.</p>
<p class="vi">Câu hỏi là quá trình hấp thụ đó diễn ra nhanh đến mức nào. Bản thân CoinDesk cũng lưu ý rằng vẫn còn quá sớm để gọi dòng vào ETF gần đây là "đảo chiều xu hướng" sau khi tháng 6 chứng kiến dòng ra ròng lớn khoảng 4,5 tỷ đô la. Bên nào — số coin đang bị bán ra hay nhu cầu mua chúng — tăng nhanh hơn trong những ngày tới có vẻ sẽ quyết định hướng đi từ đây, và trang này dự định tiếp tục theo dõi xem cán cân đó nghiêng về phía nào.</p>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <text x="60" y="270" fill="#f4f4f5" font-size="130" font-weight="bold">5.58M</text>
  <text x="60" y="335" fill="#06b6d4" font-size="42" font-weight="bold">LTH BTC · -37%</text>
  <text x="60" y="410" fill="#a1a1aa" font-size="38" font-weight="bold">STH ≥ $4M</text>
  <polygon fill="#ef4444" points="80,470 108,518 52,518"/>
  <text x="130" y="514" fill="#ef4444" font-size="40" font-weight="bold">65.5K → 64.0K</text>
  <image href="/oglogo/BTC.png" x="960" y="40" width="150" height="150"/>
</svg></div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 코인데스크(2026년7월16일, "Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000", 글래스노드 온체인 데이터 인용), 코인데스크(비트코인 현물 ETF 순유입·순유출 수치, 7월14일·15일자 및 6월 월간 집계 보도), 이 사이트 7월6일자 및 7월13일자 장기 보유자 공급 점검. 수치는 각 데이터 제공처 기준 근사치이며 집계 시점에 따라 달라질 수 있다. 본 글은 투자 조언이 아니며 현재 시장 상태를 진단하기 위한 것으로, 가격의 향후 방향을 예측하지 않는다.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinDesk (July 16, 2026, "Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000," citing Glassnode on-chain data), CoinDesk (U.S. spot bitcoin ETF net inflow/outflow figures, July 14-15 and June's monthly total), this site's July 6 and July 13 checks on long-term holder supply. Figures are approximate per each data provider and may shift by measurement time. This is not investment advice — it's meant to diagnose the market's current state, not to predict where price goes next.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: コインデスク(2026年7月16日、「Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000」、グラスノードのオンチェーンデータを引用)、コインデスク(米ビットコイン現物ETFの純流入・純流出数値、7月14日・15日分および6月の月間集計報道)、当サイト7月6日付および7月13日付の長期保有者供給点検。数値は各データ提供元に基づく近似値であり、集計時点により変動する場合がある。本記事は投資助言ではなく、現時点の市場状態を診断することを目的としており、価格の今後の方向を予測するものではない。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinDesk (16 de julio de 2026, "Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000", citando datos on-chain de Glassnode), CoinDesk (cifras de entradas/salidas netas de ETF spot de bitcoin en EE.UU., del 14 y 15 de julio y el total mensual de junio), los análisis de este sitio del 6 y 13 de julio sobre la oferta de tenedores a largo plazo. Las cifras son aproximadas según cada proveedor de datos y pueden variar según el momento de medición. Esto no es asesoramiento de inversión — su propósito es diagnosticar el estado actual del mercado, no predecir hacia dónde va el precio.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinDesk (16. Juli 2026, "Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000", unter Berufung auf On-Chain-Daten von Glassnode), CoinDesk (Nettozufluss-/-abflusszahlen von US-Spot-Bitcoin-ETFs, 14./15. Juli sowie Junis Monatssumme), die Prüfungen dieser Seite vom 6. und 13. Juli zum Angebot langfristiger Halter. Zahlen sind Näherungswerte je nach Datenanbieter und können je nach Erhebungszeitpunkt variieren. Dies ist keine Anlageberatung — sie soll den aktuellen Marktzustand diagnostizieren, nicht die künftige Preisrichtung vorhersagen.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinDesk (16 juillet 2026, « Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000 », citant des données on-chain de Glassnode), CoinDesk (chiffres des entrées/sorties nettes des ETF spot bitcoin américains, 14-15 juillet et total mensuel de juin), les examens de ce site des 6 et 13 juillet sur l'offre des détenteurs de long terme. Les chiffres sont approximatifs selon chaque fournisseur de données et peuvent varier selon le moment de la mesure. Ceci n'est pas un conseil en investissement — il vise à diagnostiquer l'état actuel du marché, pas à prédire la direction future du prix.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinDesk (16 de julho de 2026, "Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000", citando dados on-chain da Glassnode), CoinDesk (números de entradas/saídas líquidas de ETFs spot de bitcoin dos EUA, 14-15 de julho e total mensal de junho), as análises deste site de 6 e 13 de julho sobre a oferta de detentores de longo prazo. Os números são aproximados conforme cada provedor de dados e podem variar conforme o momento da medição. Isto não é aconselhamento de investimento — destina-se a diagnosticar o estado atual do mercado, não a prever para onde o preço vai a seguir.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinDesk (16 Temmuz 2026, "Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000", Glassnode zincir üstü verilerine atıfla), CoinDesk (ABD spot bitcoin ETF net giriş/çıkış rakamları, 14-15 Temmuz ve Haziran ayı toplamı), bu sitenin 6 ve 13 Temmuz tarihli uzun vadeli yatırımcı arzı incelemeleri. Rakamlar her veri sağlayıcısına göre yaklaşık değerlerdir ve ölçüm zamanına göre değişebilir. Bu yatırım tavsiyesi değildir — amacı piyasanın şu anki durumunu teşhis etmektir, fiyatın gelecekteki yönünü tahmin etmek değildir.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinDesk (16 tháng 7 năm 2026, "Two groups of bitcoin investors sell on the rise as U.S. inflation lifts prices to nearly $65,000", trích dẫn dữ liệu on-chain của Glassnode), CoinDesk (số liệu dòng vào/ra ròng của ETF bitcoin giao ngay tại Mỹ, ngày 14-15 tháng 7 và tổng tháng 6), các bài kiểm tra ngày 6 và 13 tháng 7 của trang này về nguồn cung người nắm giữ dài hạn. Các số liệu là giá trị gần đúng theo từng nhà cung cấp dữ liệu và có thể thay đổi tùy theo thời điểm đo lường. Đây không phải là lời khuyên đầu tư — mục đích là chẩn đoán trạng thái hiện tại của thị trường, không dự đoán hướng đi tiếp theo của giá.</p>
<?php require __DIR__.'/_footer.php'; ?>
