<?php $slug = 'btc-gold-decoupling-fear-greed-gap'; require __DIR__.'/_header.php'; ?>

  <p class="ko">비트코인은 6월 30일 $57,900 저점을 찍은 뒤 7월 6~7일 $63,847~$64,330까지 올라서며 주간 기준 +6.27% 반등했다. 저점 대비로는 약 +11%다. 6월 미국 비농업고용이 시장 예상치 11.3만 명의 절반에도 못 미치는 5.7만 명에 그치자 국채금리와 달러가 동시에 밀리면서 위험자산 전반에 완화 기대가 번졌다는 게 표면적인 설명이다. 겉으로 보면 매크로 훈풍을 탄 통상적인 반등처럼 보인다.</p>
  <p class="en">Bitcoin bottomed at $57,900 on June 30 and climbed to $63,847-$64,330 by July 6-7, a weekly gain of 6.27% — roughly +11% off the low. The surface-level explanation is that June's US non-farm payrolls came in at just 57,000, barely half the 113,000 forecast, dragging Treasury yields and the dollar down together and spreading easing hopes across risk assets. On the face of it, this looks like an ordinary macro-driven bounce.</p>
  <p class="ja">ビットコインは6月30日に5万7,900ドルで底を打った後、7月6~7日には6万3,847~6万4,330ドルまで上昇し、週間ベースで+6.27%反発した。安値からは約+11%だ。6月の米非農業部門雇用者数が市場予想11.3万人の半分にも満たない5.7万人にとどまったことで、国債利回りとドルが同時に下落し、リスク資産全般に緩和期待が広がったというのが表面的な説明だ。見た目には、マクロの追い風に乗った通常の反発のように映る。</p>
  <p class="es">Bitcoin tocó fondo en 57.900 $ el 30 de junio y subió a 63.847-64.330 $ hacia el 6-7 de julio, una ganancia semanal del 6,27% — alrededor de +11% desde el mínimo. La explicación superficial es que la nómina no agrícola de EE. UU. de junio llegó a apenas 57.000, poco más de la mitad de los 113.000 previstos, arrastrando a la baja los rendimientos del Tesoro y el dólar a la vez y extendiendo la expectativa de relajación monetaria por los activos de riesgo. A simple vista, parece un rebote macro ordinario.</p>
  <p class="de">Bitcoin markierte am 30. Juni ein Tief bei 57.900 $ und kletterte bis zum 6.-7. Juli auf 63.847-64.330 $ — ein Wochengewinn von 6,27%, rund +11% vom Tief. Die oberflächliche Erklärung: Die US-Beschäftigungszahlen außerhalb der Landwirtschaft für Juni fielen mit nur 57.000 auf kaum die Hälfte der erwarteten 113.000, wodurch Anleiherenditen und Dollar gemeinsam nachgaben und sich Lockerungshoffnungen über die Risikoanlagen ausbreiteten. An der Oberfläche wirkt das wie eine gewöhnliche, makrogetriebene Erholung.</p>
  <p class="fr">Le bitcoin a touché un plancher à 57 900 $ le 30 juin avant de grimper à 63 847-64 330 $ vers le 6-7 juillet, soit un gain hebdomadaire de 6,27% — environ +11% depuis le plus bas. L'explication de surface est que les créations d'emplois non agricoles américaines de juin ne se sont élevées qu'à 57 000, à peine la moitié des 113 000 attendues, entraînant à la baisse à la fois les rendements du Trésor et le dollar et propageant des espoirs d'assouplissement sur l'ensemble des actifs à risque. En apparence, cela ressemble à un rebond macro ordinaire.</p>
  <p class="pt">O bitcoin encontrou fundo em US$ 57.900 em 30 de junho e subiu para US$ 63.847-64.330 por volta de 6-7 de julho, um ganho semanal de 6,27% — cerca de +11% em relação à mínima. A explicação superficial é que a folha de pagamento não agrícola dos EUA em junho veio a apenas 57 mil, pouco mais da metade dos 113 mil esperados, derrubando juntos os rendimentos do Tesouro e o dólar e espalhando expectativas de afrouxamento pelos ativos de risco. À primeira vista, parece uma recuperação macro comum.</p>
  <p class="tr">Bitcoin 30 Haziran'da 57.900 dolardan dip yaptı ve 6-7 Temmuz civarında 63.847-64.330 dolara tırmandı; haftalık %6,27'lik bir kazanç — dipten yaklaşık +%11. Yüzeysel açıklama, haziran ayı ABD tarım dışı istihdamının beklenen 113 bin kişinin ancak yarısı kadar olan 57 bin kişide kalması, bunun da hazine tahvili getirilerini ve doları birlikte aşağı çekerek gevşeme beklentisini risk varlıklarına yaydığı yönünde. Görünüşte bu, sıradan bir makro kaynaklı toparlanmaya benziyor.</p>
  <p class="vi">Bitcoin chạm đáy 57.900 đô la vào ngày 30 tháng 6 rồi leo lên 63.847-64.330 đô la vào khoảng 6-7 tháng 7, mức tăng 6,27% trong tuần — tương đương khoảng +11% từ đáy. Lời giải thích bề mặt là số việc làm phi nông nghiệp tháng 6 của Mỹ chỉ đạt 57.000, chưa bằng một nửa dự báo 113.000, kéo lợi suất trái phiếu kho bạc và đồng đô la cùng giảm, lan tỏa kỳ vọng nới lỏng ra khắp các tài sản rủi ro. Nhìn bề ngoài, đây giống một đợt phục hồi thông thường do vĩ mô dẫn dắt.</p>

  <p class="ko">그런데 같은 기간 시장의 다른 두 축 — 금과의 관계, 그리고 투자심리 지표 — 은 이 반등에 선뜻 동의하지 않는 모습이다. 2026년 들어 여러 트래커가 비트코인-금 30일 롤링 상관계수가 -0.7에서 -0.88까지 떨어졌다고 보도했는데, 이는 2022년 FTX 붕괴 이후 최저 수준이다. 동시에 크립토 공포탐욕지수는 반등이 진행 중인 7월 6~7일에도 23~27 사이, 즉 '극단적 공포' 구간에 머물러 있다. 가격은 오르는데 안전자산으로서의 지위는 흔들리고 심리는 여전히 얼어 있는, 서로 다른 방향을 가리키는 세 개의 바늘을 이 글은 함께 짚는다.</p>
  <p class="en">But two other axes of the market over the same window — bitcoin's relationship with gold, and sentiment gauges — don't readily agree with this bounce. Multiple trackers reported that bitcoin's 30-day rolling correlation with gold fell to between -0.7 and -0.88 at points in 2026, the lowest since the 2022 FTX collapse. At the same time, the crypto Fear & Greed Index sat at 23-27 — squarely in "Extreme Fear" — even as the bounce was underway on July 6-7. This piece walks through three needles pointing in different directions: price climbing, gold-hedge status wobbling, and sentiment still frozen.</p>
  <p class="ja">しかし同じ期間、市場のもう2つの軸——金との関係、そして投資心理指標——はこの反発に素直に同調していない。2026年に入り複数のトラッカーが、ビットコイン-金の30日ローリング相関係数が-0.7から-0.88まで下落したと報じた。これは2022年のFTX破綻以来の最低水準だ。同時にクリプト恐怖強欲指数は、反発が進行中の7月6~7日でも23~27、つまり「極端な恐怖」圏にとどまっている。価格は上がるのに安全資産としての地位は揺らぎ、心理は依然として凍りついたままという、異なる方向を指す3本の針を本稿はまとめて取り上げる。</p>
  <p class="es">Pero otros dos ejes del mercado en la misma ventana —la relación de bitcoin con el oro y los indicadores de sentimiento— no coinciden fácilmente con este repunte. Varios rastreadores informaron que la correlación móvil de 30 días entre bitcoin y oro cayó a entre -0,7 y -0,88 en algunos momentos de 2026, el nivel más bajo desde el colapso de FTX en 2022. Al mismo tiempo, el Índice de Miedo y Codicia cripto se mantuvo en 23-27 —de lleno en "Miedo Extremo"— incluso mientras el repunte estaba en curso el 6-7 de julio. Este artículo recorre tres agujas que apuntan en direcciones distintas: el precio subiendo, el estatus de cobertura del oro tambaleándose y el sentimiento aún congelado.</p>
  <p class="de">Doch zwei andere Achsen des Marktes im selben Zeitraum — Bitcoins Beziehung zu Gold und Stimmungsindikatoren — stimmen dieser Erholung nicht ohne Weiteres zu. Mehrere Tracker berichteten, dass Bitcoins 30-Tage-Rollkorrelation mit Gold 2026 zeitweise auf -0,7 bis -0,88 fiel — der niedrigste Stand seit dem FTX-Kollaps 2022. Gleichzeitig lag der Krypto-Fear-&-Greed-Index bei 23-27 — mitten in "Extreme Angst" — selbst während die Erholung am 6.-7. Juli lief. Dieser Beitrag geht drei Nadeln durch, die in unterschiedliche Richtungen zeigen: steigender Preis, wackelnder Gold-Hedge-Status und weiterhin eingefrorene Stimmung.</p>
  <p class="fr">Mais deux autres axes du marché sur la même période — la relation du bitcoin avec l'or et les indicateurs de sentiment — ne s'accordent pas facilement avec ce rebond. Plusieurs trackers ont rapporté que la corrélation glissante sur 30 jours entre bitcoin et or est tombée entre -0,7 et -0,88 à certains moments de 2026, son niveau le plus bas depuis l'effondrement de FTX en 2022. Dans le même temps, l'indice crypto de Peur et de Cupidité est resté à 23-27 — en pleine "Peur Extrême" — alors même que le rebond était en cours les 6-7 juillet. Cet article passe en revue trois aiguilles pointant dans des directions différentes : le prix qui grimpe, le statut de couverture de l'or qui vacille, et le sentiment encore figé.</p>
  <p class="pt">Mas dois outros eixos do mercado no mesmo período — a relação do bitcoin com o ouro e os indicadores de sentimento — não concordam prontamente com essa recuperação. Vários rastreadores relataram que a correlação móvel de 30 dias entre bitcoin e ouro caiu para entre -0,7 e -0,88 em pontos de 2026, o nível mais baixo desde o colapso da FTX em 2022. Ao mesmo tempo, o Índice de Medo e Ganância cripto ficou em 23-27 — bem no "Medo Extremo" — mesmo com a recuperação em curso em 6-7 de julho. Este texto percorre três agulhas apontando em direções diferentes: o preço subindo, o status de proteção do ouro vacilando e o sentimento ainda congelado.</p>
  <p class="tr">Ancak aynı dönemde piyasanın diğer iki ekseni — bitcoin'in altınla ilişkisi ve duygu durumu göstergeleri — bu yükselişe kolayca katılmıyor. Birçok izleyici, bitcoin'in altınla 30 günlük yuvarlanan korelasyonunun 2026'da bazı noktalarda -0,7 ile -0,88 arasına düştüğünü bildirdi; bu, 2022'deki FTX çöküşünden bu yana en düşük seviye. Aynı zamanda, kripto Korku ve Açgözlülük Endeksi, 6-7 Temmuz'da yükseliş sürerken bile 23-27'de, yani tam olarak "Aşırı Korku" bölgesinde kaldı. Bu yazı, farklı yönleri işaret eden üç ibreyi bir arada ele alıyor: yükselen fiyat, sarsılan altın-koruma statüsü ve hâlâ donmuş duygu durumu.</p>
  <p class="vi">Nhưng hai trục khác của thị trường trong cùng giai đoạn — mối quan hệ của bitcoin với vàng, và các chỉ số tâm lý — lại không dễ dàng đồng tình với đợt phục hồi này. Nhiều trang theo dõi báo cáo rằng tương quan trượt 30 ngày giữa bitcoin và vàng đã giảm xuống còn -0,7 đến -0,88 tại một số thời điểm trong năm 2026, mức thấp nhất kể từ sự sụp đổ của FTX năm 2022. Đồng thời, Chỉ số Sợ hãi và Tham lam của tiền điện tử vẫn ở mức 23-27 — nằm hẳn trong vùng "Sợ hãi Cực độ" — ngay cả khi đợt phục hồi đang diễn ra vào ngày 6-7 tháng 7. Bài viết này xem xét ba chiếc kim chỉ về ba hướng khác nhau: giá đang tăng, vị thế phòng hộ của vàng đang lung lay, và tâm lý vẫn còn đóng băng.</p>

  <div class="box ko">💡 <strong>핵심 요약:</strong> 비트코인은 6월 30일 $57,900에서 7월 6~7일 $63,847~$64,330으로 주간 +6.27%(저점 대비 +11%) 반등했다. 같은 기간 비트코인-금 30일 롤링 상관계수는 -0.7~-0.88까지 떨어져 2022년 FTX 붕괴 이후 최저 수준을 기록했다. 금은 1월 28일 $5,589.38 사상 최고가를 찍은 뒤에도 중앙은행이 1분기에만 244톤(+3% YoY)을 순매수하며 별도의 안전자산 랠리를 이어갔다. 크립토 공포탐욕지수는 7월 6~7일에도 23~27로 '극단적 공포' 구간을 벗어나지 못했고, 펀딩비는 0.0087% 수준의 완만한 플러스에 머물렀다.</div>
  <div class="box en">💡 <strong>Key takeaway:</strong> Bitcoin bounced from $57,900 on June 30 to $63,847-$64,330 by July 6-7, up 6.27% for the week (+11% off the low). Over the same span, bitcoin's 30-day rolling correlation with gold fell to -0.7 to -0.88, the lowest since the 2022 FTX collapse. Gold kept running its own safe-haven rally — hitting an all-time high of $5,589.38 on January 28 and seeing central banks net-buy 244 tonnes in Q1 alone (+3% y/y). The crypto Fear & Greed Index stayed at 23-27, still "Extreme Fear," on July 6-7, while the funding rate held at a mild 0.0087%.</div>
  <div class="box ja">💡 <strong>要点:</strong> ビットコインは6月30日の5万7,900ドルから7月6~7日には6万3,847~6万4,330ドルへと週間+6.27%(安値比+11%)反発した。同じ期間、ビットコイン-金の30日ローリング相関係数は-0.7~-0.88まで下落し、2022年のFTX破綻以来の最低水準を記録した。金は1月28日に5,589.38ドルの史上最高値をつけた後も、中央銀行が第1四半期だけで244トン(前年比+3%)を純購入し、独自の安全資産ラリーを続けた。クリプト恐怖強欲指数は7月6~7日でも23~27と「極端な恐怖」圏を抜け出せず、資金調達率は0.0087%程度の緩やかなプラスにとどまった。</div>
  <div class="box es">💡 <strong>Resumen clave:</strong> Bitcoin rebotó de 57.900 $ el 30 de junio a 63.847-64.330 $ hacia el 6-7 de julio, +6,27% en la semana (+11% desde el mínimo). En el mismo lapso, la correlación móvil de 30 días de bitcoin con el oro cayó a entre -0,7 y -0,88, el nivel más bajo desde el colapso de FTX en 2022. El oro mantuvo su propio rally de refugio seguro —tocando un máximo histórico de 5.589,38 $ el 28 de enero, con bancos centrales comprando netos 244 toneladas solo en el primer trimestre (+3% interanual). El Índice de Miedo y Codicia cripto se mantuvo en 23-27, aún en "Miedo Extremo", el 6-7 de julio, mientras la tasa de financiación se mantuvo en un modesto +0,0087%.</div>
  <div class="box de">💡 <strong>Kernaussage:</strong> Bitcoin erholte sich vom 57.900-$-Tief am 30. Juni auf 63.847-64.330 $ zum 6.-7. Juli, +6,27% in der Woche (+11% vom Tief). Im selben Zeitraum fiel Bitcoins 30-Tage-Rollkorrelation mit Gold auf -0,7 bis -0,88, den niedrigsten Stand seit dem FTX-Kollaps 2022. Gold setzte seine eigene Safe-Haven-Rally fort — mit einem Allzeithoch von 5.589,38 $ am 28. Januar, während Zentralbanken allein im ersten Quartal netto 244 Tonnen kauften (+3% ggü. Vorjahr). Der Krypto-Fear-&-Greed-Index blieb am 6.-7. Juli bei 23-27, weiterhin "Extreme Angst", während die Finanzierungsrate bei moderaten 0,0087% verharrte.</div>
  <div class="box fr">💡 <strong>Résumé clé :</strong> Le bitcoin a rebondi de 57 900 $ le 30 juin à 63 847-64 330 $ vers le 6-7 juillet, soit +6,27% sur la semaine (+11% depuis le plus bas). Sur la même période, la corrélation glissante sur 30 jours du bitcoin avec l'or est tombée à -0,7 à -0,88, son niveau le plus bas depuis l'effondrement de FTX en 2022. L'or a poursuivi son propre rallye de valeur refuge — atteignant un sommet historique de 5 589,38 $ le 28 janvier, les banques centrales achetant net 244 tonnes rien qu'au premier trimestre (+3% sur un an). L'indice crypto de Peur et de Cupidité est resté à 23-27, toujours en "Peur Extrême", les 6-7 juillet, tandis que le taux de financement stagnait à un modeste +0,0087%.</div>
  <div class="box pt">💡 <strong>Resumo:</strong> O bitcoin saltou de US$ 57.900 em 30 de junho para US$ 63.847-64.330 por volta de 6-7 de julho, +6,27% na semana (+11% em relação à mínima). No mesmo período, a correlação móvel de 30 dias do bitcoin com o ouro caiu para -0,7 a -0,88, o nível mais baixo desde o colapso da FTX em 2022. O ouro manteve seu próprio rali de proteção — atingindo uma máxima histórica de US$ 5.589,38 em 28 de janeiro, com bancos centrais comprando líquido 244 toneladas só no primeiro trimestre (+3% na comparação anual). O Índice de Medo e Ganância cripto ficou em 23-27, ainda em "Medo Extremo", em 6-7 de julho, enquanto a taxa de financiamento se manteve em um modesto +0,0087%.</div>
  <div class="box tr">💡 <strong>Öne çıkanlar:</strong> Bitcoin, 30 Haziran'daki 57.900 dolarlık dipten 6-7 Temmuz civarında 63.847-64.330 dolara yükseldi; haftalık +%6,27 (dipten +%11). Aynı dönemde, bitcoin'in altınla 30 günlük yuvarlanan korelasyonu -0,7 ile -0,88 arasına düşerek 2022'deki FTX çöküşünden bu yana en düşük seviyeyi gördü. Altın, kendi güvenli liman rallisini sürdürdü — 28 Ocak'ta 5.589,38 dolarlık tarihi zirveye ulaşırken, merkez bankaları yalnızca ilk çeyrekte net 244 ton aldı (yıllık +%3). Kripto Korku ve Açgözlülük Endeksi 6-7 Temmuz'da hâlâ 23-27'de, yani "Aşırı Korku"da kalırken, fonlama oranı mütevazı +%0,0087'de sabit kaldı.</div>
  <div class="box vi">💡 <strong>Tóm tắt chính:</strong> Bitcoin bật từ 57.900 đô la ngày 30 tháng 6 lên 63.847-64.330 đô la vào khoảng 6-7 tháng 7, tăng 6,27% trong tuần (+11% từ đáy). Trong cùng giai đoạn, tương quan trượt 30 ngày giữa bitcoin và vàng giảm xuống -0,7 đến -0,88, mức thấp nhất kể từ sự sụp đổ của FTX năm 2022. Vàng vẫn tiếp tục đợt tăng trú ẩn an toàn của riêng mình — chạm đỉnh lịch sử 5.589,38 đô la vào ngày 28 tháng 1, khi các ngân hàng trung ương mua ròng 244 tấn chỉ trong quý 1 (+3% so với cùng kỳ năm trước). Chỉ số Sợ hãi và Tham lam tiền điện tử vẫn ở mức 23-27, vẫn trong vùng "Sợ hãi Cực độ", vào ngày 6-7 tháng 7, trong khi phí funding duy trì ở mức nhẹ +0,0087%.</div>

  <h2 class="ko">① 반등의 얼굴 — 안전자산 수요가 아니라 유동성 기대</h2>
  <h2 class="en">① The Face of the Bounce — Liquidity Hopes, Not Safe-Haven Demand</h2>
  <h2 class="ja">① 反発の正体——安全資産需要ではなく流動性期待</h2>
  <h2 class="es">① El Rostro del Rebote — Expectativas de Liquidez, No Demanda de Refugio</h2>
  <h2 class="de">① Das Gesicht der Erholung — Liquiditätshoffnung, keine Safe-Haven-Nachfrage</h2>
  <h2 class="fr">① Le Visage du Rebond — Espoirs de Liquidité, Pas une Demande de Valeur Refuge</h2>
  <h2 class="pt">① O Rosto da Recuperação — Esperança de Liquidez, Não Demanda por Refúgio</h2>
  <h2 class="tr">① Yükselişin Yüzü — Güvenli Liman Talebi Değil, Likidite Umudu</h2>
  <h2 class="vi">① Gương Mặt Của Đợt Phục Hồi — Kỳ Vọng Thanh Khoản, Không Phải Nhu Cầu Trú Ẩn An Toàn</h2>

  <p class="ko">비트코인은 10월 사상 최고가 $126,000에서 6월 30일 $57,900까지 약 54% 밀렸다가 7월 들어 반등을 시작했다. 방아쇠는 6월 미국 고용지표였다 — 비농업 신규고용이 5.7만 명으로 시장 예상(11.3만 명)의 절반에 그치면서 국채금리가 하락하고 달러가 약세를 보였다. 코인글래스·크립토뉴스넷 등의 보도를 종합하면 7월 6일 비트코인은 $64,330까지 올라 20일 지수이동평균선은 넘었지만 50일·200일 이동평균선은 여전히 밑돌았고, 7월 7일에는 $64,033.85 부근에서 거래됐다.</p>
  <p class="en">Bitcoin slid roughly 54% from its October all-time high of $126,000 to the $57,900 low on June 30, then began bouncing in July. The trigger was June's US jobs report: non-farm payrolls came in at 57,000, half the 113,000 forecast, pulling Treasury yields down and weakening the dollar. Pooling CoinGlass and CryptoNews.net reporting, bitcoin climbed to $64,330 on July 6 — clearing its 20-day EMA but still below its 50-day and 200-day EMAs — and traded around $64,033.85 on July 7.</p>
  <p class="ja">ビットコインは10月の史上最高値12万6,000ドルから6月30日の5万7,900ドルまで約54%下落した後、7月に入り反発を始めた。引き金となったのは6月の米雇用統計だ——非農業部門雇用者数が市場予想(11.3万人)の半分の5.7万人にとどまり、国債利回りが低下しドルが弱含んだ。コイングラス・クリプトニュースネットなどの報道を総合すると、7月6日にビットコインは6万4,330ドルまで上昇し20日指数移動平均線は超えたが、50日・200日移動平均線は依然として下回り、7月7日には6万4,033.85ドル前後で取引された。</p>
  <p class="es">Bitcoin cayó cerca de un 54% desde su máximo histórico de octubre de 126.000 $ hasta el mínimo de 57.900 $ del 30 de junio, y luego empezó a rebotar en julio. El detonante fue el informe de empleo de EE. UU. de junio: la nómina no agrícola llegó a 57.000, la mitad de los 113.000 previstos, arrastrando a la baja los rendimientos del Tesoro y debilitando al dólar. Combinando reportes de CoinGlass y CryptoNews.net, bitcoin subió a 64.330 $ el 6 de julio —superando su media móvil exponencial de 20 días pero aún por debajo de las de 50 y 200 días— y cotizó en torno a 64.033,85 $ el 7 de julio.</p>
  <p class="de">Bitcoin fiel von seinem Oktober-Allzeithoch von 126.000 $ um rund 54% auf das Tief von 57.900 $ am 30. Juni, bevor im Juli die Erholung einsetzte. Auslöser war der US-Arbeitsmarktbericht für Juni: Die Beschäftigung außerhalb der Landwirtschaft lag bei nur 57.000, der Hälfte der erwarteten 113.000, was Anleiherenditen drückte und den Dollar schwächte. Kombiniert man Berichte von CoinGlass und CryptoNews.net, kletterte Bitcoin am 6. Juli auf 64.330 $ — über dem 20-Tage-EMA, aber weiterhin unter dem 50- und 200-Tage-EMA — und notierte am 7. Juli bei rund 64.033,85 $.</p>
  <p class="fr">Le bitcoin a chuté d'environ 54% depuis son plus haut historique d'octobre à 126 000 $ jusqu'au plancher de 57 900 $ du 30 juin, avant d'entamer un rebond en juillet. Le déclencheur a été le rapport sur l'emploi américain de juin : les créations d'emplois non agricoles se sont élevées à 57 000, la moitié des 113 000 attendues, tirant vers le bas les rendements du Trésor et affaiblissant le dollar. En combinant les rapports de CoinGlass et CryptoNews.net, le bitcoin a grimpé à 64 330 $ le 6 juillet — franchissant sa moyenne mobile exponentielle à 20 jours mais restant sous celles à 50 et 200 jours — et s'échangeait autour de 64 033,85 $ le 7 juillet.</p>
  <p class="pt">O bitcoin caiu cerca de 54% desde sua máxima histórica de outubro de US$ 126.000 até a mínima de US$ 57.900 em 30 de junho, e então começou a se recuperar em julho. O gatilho foi o relatório de empregos dos EUA de junho: a folha de pagamento não agrícola veio a 57 mil, metade dos 113 mil esperados, derrubando os rendimentos do Tesouro e enfraquecendo o dólar. Combinando reportagens da CoinGlass e CryptoNews.net, o bitcoin subiu para US$ 64.330 em 6 de julho — superando sua média móvel exponencial de 20 dias, mas ainda abaixo das de 50 e 200 dias — e foi negociado perto de US$ 64.033,85 em 7 de julho.</p>
  <p class="tr">Bitcoin, Ekim ayındaki 126.000 dolarlık tarihi zirvesinden 30 Haziran'daki 57.900 dolarlık dibe kadar yaklaşık %54 geriledi, ardından temmuzda toparlanmaya başladı. Tetikleyici, haziran ayı ABD istihdam raporuydu — tarım dışı istihdam, beklenen 113 bininin yarısı kadar olan 57 bin kişide kaldı, bu da hazine tahvili getirilerini aşağı çekti ve doları zayıflattı. CoinGlass ve CryptoNews.net haberlerini birleştirdiğimizde, bitcoin 6 Temmuz'da 64.330 dolara yükseldi — 20 günlük üstel hareketli ortalamasının üzerine çıktı ama 50 ve 200 günlük ortalamalarının hâlâ altındaydı — ve 7 Temmuz'da yaklaşık 64.033,85 dolardan işlem gördü.</p>
  <p class="vi">Bitcoin đã giảm khoảng 54% từ đỉnh lịch sử 126.000 đô la hồi tháng 10 xuống đáy 57.900 đô la vào ngày 30 tháng 6, rồi bắt đầu phục hồi vào tháng 7. Chất xúc tác là báo cáo việc làm tháng 6 của Mỹ — số việc làm phi nông nghiệp chỉ đạt 57.000, bằng một nửa dự báo 113.000, kéo lợi suất trái phiếu kho bạc xuống và làm đồng đô la suy yếu. Tổng hợp báo cáo từ CoinGlass và CryptoNews.net, bitcoin tăng lên 64.330 đô la vào ngày 6 tháng 7 — vượt đường trung bình động hàm mũ 20 ngày nhưng vẫn dưới đường 50 và 200 ngày — và giao dịch quanh mức 64.033,85 đô la vào ngày 7 tháng 7.</p>

  <p class="ko">이 흐름은 '금리 인하 기대 → 달러 약세 → 위험자산 선호'라는 익숙한 매크로 경로를 따른다. 즉 이번 반등의 동력은 비트코인 자체의 온체인 수요 개선이 아니라, 연준의 통화정책 완화 기대라는 외부 변수에 가깝다. 이 지점이 중요한 이유는, 같은 매크로 국면에서 전통적인 안전자산인 금은 정반대 이유로 오르고 있기 때문이다 — 다음 장에서 보듯, 지정학적 긴장과 중앙은행 수요라는 완전히 다른 동력이다.</p>
  <p class="en">This follows a familiar macro pathway: rate-cut hopes, a weaker dollar, then a tilt toward risk assets. In other words, the bounce's fuel looks less like an improvement in bitcoin's own on-chain demand and more like an external variable — expectations that the Fed will ease. That matters because, in the same macro window, gold — the traditional safe haven — is rising for the opposite reason, as the next section shows: geopolitical tension and central-bank demand, an entirely different engine.</p>
  <p class="ja">この流れは「利下げ期待→ドル安→リスク資産選好」という馴染みのマクロ経路をたどっている。つまり今回の反発の動力は、ビットコイン自体のオンチェーン需要の改善ではなく、FRBの金融緩和期待という外部変数に近い。この点が重要なのは、同じマクロ局面で伝統的な安全資産である金が正反対の理由で上昇しているからだ——次章で見るように、地政学的緊張と中央銀行需要というまったく別の動力である。</p>
  <p class="es">Esto sigue una vía macro familiar: expectativas de recorte de tipos, un dólar más débil y luego una inclinación hacia los activos de riesgo. En otras palabras, el combustible del rebote se parece menos a una mejora en la propia demanda on-chain de bitcoin y más a una variable externa: la expectativa de que la Fed relaje su política. Esto importa porque, en la misma ventana macro, el oro —el refugio tradicional— sube por la razón opuesta, como muestra la siguiente sección: tensión geopolítica y demanda de bancos centrales, un motor completamente distinto.</p>
  <p class="de">Das folgt einem vertrauten Makro-Pfad: Zinssenkungshoffnungen, ein schwächerer Dollar, dann eine Neigung zu Risikoanlagen. Anders gesagt: Der Treibstoff der Erholung wirkt weniger wie eine Verbesserung von Bitcoins eigener On-Chain-Nachfrage und mehr wie eine externe Variable — die Erwartung einer Fed-Lockerung. Das ist wichtig, denn im selben Makro-Fenster steigt Gold — der traditionelle sichere Hafen — aus dem entgegengesetzten Grund, wie der nächste Abschnitt zeigt: geopolitische Spannungen und Zentralbanknachfrage, ein völlig anderer Motor.</p>
  <p class="fr">Cela suit un chemin macro familier : espoirs de baisse des taux, dollar plus faible, puis inclination vers les actifs à risque. Autrement dit, le carburant du rebond ressemble moins à une amélioration de la demande on-chain propre au bitcoin qu'à une variable externe — l'anticipation d'un assouplissement de la Fed. C'est important car, dans la même fenêtre macro, l'or — le refuge traditionnel — monte pour la raison opposée, comme le montre la section suivante : tensions géopolitiques et demande des banques centrales, un moteur entièrement différent.</p>
  <p class="pt">Isso segue um caminho macro familiar: expectativas de corte de juros, dólar mais fraco, depois uma inclinação para ativos de risco. Em outras palavras, o combustível da recuperação parece menos uma melhora na própria demanda on-chain do bitcoin e mais uma variável externa — a expectativa de que o Fed vá afrouxar. Isso importa porque, na mesma janela macro, o ouro — o refúgio tradicional — sobe pelo motivo oposto, como mostra a próxima seção: tensão geopolítica e demanda de bancos centrais, um motor totalmente diferente.</p>
  <p class="tr">Bu, tanıdık bir makro yol izliyor: faiz indirimi umutları, zayıflayan dolar, ardından risk varlıklarına yöneliş. Başka bir deyişle, bu yükselişin yakıtı bitcoin'in kendi zincir üstü talebindeki bir iyileşmeden çok, Fed'in gevşeyeceği beklentisi gibi dışsal bir değişkene benziyor. Bu önemli çünkü aynı makro dönemde geleneksel güvenli liman olan altın, tam tersi bir nedenle yükseliyor — bir sonraki bölümde görüleceği gibi, jeopolitik gerilim ve merkez bankası talebi, tamamen farklı bir motor.</p>
  <p class="vi">Điều này đi theo một con đường vĩ mô quen thuộc: kỳ vọng cắt giảm lãi suất, đồng đô la yếu hơn, rồi nghiêng về tài sản rủi ro. Nói cách khác, động lực của đợt phục hồi này trông giống một biến số bên ngoài — kỳ vọng Fed sẽ nới lỏng — hơn là sự cải thiện trong chính nhu cầu on-chain của bitcoin. Điều này quan trọng vì trong cùng giai đoạn vĩ mô đó, vàng — nơi trú ẩn an toàn truyền thống — lại tăng vì lý do ngược lại, như phần tiếp theo sẽ cho thấy: căng thẳng địa chính trị và nhu cầu từ ngân hàng trung ương, một động cơ hoàn toàn khác.</p>

  <h2 class="ko">② 금과의 디커플링 — '디지털 골드' 서사가 작동하지 않는 국면</h2>
  <h2 class="en">② Decoupling From Gold — Where the "Digital Gold" Narrative Stops Working</h2>
  <h2 class="ja">② 金とのデカップリング——「デジタルゴールド」神話が機能しない局面</h2>
  <h2 class="es">② Desacoplamiento del Oro — Donde Deja de Funcionar el Relato del "Oro Digital"</h2>
  <h2 class="de">② Entkopplung von Gold — Wo die "Digitales Gold"-Erzählung nicht mehr funktioniert</h2>
  <h2 class="fr">② Découplage de l'Or — Là où le Récit de l'« Or Numérique » Cesse de Fonctionner</h2>
  <h2 class="pt">② Desacoplamento do Ouro — Onde a Narrativa do "Ouro Digital" Para de Funcionar</h2>
  <h2 class="tr">② Altından Kopuş — "Dijital Altın" Anlatısının İşlemediği Nokta</h2>
  <h2 class="vi">② Sự Tách Rời Khỏi Vàng — Nơi Câu Chuyện "Vàng Kỹ Thuật Số" Không Còn Đúng</h2>

  <p class="ko">금은 2026년 1월 28일 온스당 $5,589.38로 사상 최고가를 찍었고 2025년 초 대비로는 약 80% 올랐다. 세계금협회(WGC) 집계에 따르면 각국 중앙은행은 1분기에만 244톤(전년 동기 대비 +3%)을 순매수했고, 연간으로는 700~900톤 매수가 예상돼 2022년 이전 평균을 크게 웃돈다. 폴란드·중국·인도·카자흐스탄·브라질 등이 주요 매수국으로 꼽히는데, 서구 커스터디에 대한 신뢰 저하와 지정학적 리스크 분산이라는 주권적 동기에서 나온 수요다 — 즉 금의 상승은 '위험 회피'라는 전통적 안전자산 논리를 그대로 따르고 있다.</p>
  <p class="en">Gold hit an all-time high of $5,589.38 an ounce on January 28, 2026, up roughly 80% from the start of 2025. Per World Gold Council figures, central banks net-bought 244 tonnes in Q1 alone (+3% year over year), with the full-year pace tracking toward 700-900 tonnes — well above pre-2022 averages. Poland, China, India, Kazakhstan and Brazil rank among the top buyers, demand rooted in sovereign motives: reduced trust in Western-held custody and a push to diversify away from geopolitical risk. In short, gold's rise follows the traditional safe-haven logic of risk aversion to the letter.</p>
  <p class="ja">金は2026年1月28日にオンス当たり5,589.38ドルで史上最高値をつけ、2025年初来では約80%上昇した。世界金協会(WGC)の集計によると、各国中央銀行は第1四半期だけで244トン(前年同期比+3%)を純購入し、通期では700~900トンの購入が見込まれ、2022年以前の平均を大きく上回る。ポーランド・中国・インド・カザフスタン・ブラジルなどが主要な買い手で、西側カストディへの信頼低下と地政学的リスク分散という主権的動機に基づく需要だ——つまり金の上昇は「リスク回避」という伝統的な安全資産の論理をそのままなぞっている。</p>
  <p class="es">El oro alcanzó un máximo histórico de 5.589,38 $ la onza el 28 de enero de 2026, un 80% más que a comienzos de 2025. Según cifras del Consejo Mundial del Oro, los bancos centrales compraron netos 244 toneladas solo en el primer trimestre (+3% interanual), con un ritmo anual que apunta a 700-900 toneladas, muy por encima de los promedios previos a 2022. Polonia, China, India, Kazajistán y Brasil figuran entre los principales compradores, una demanda arraigada en motivos soberanos: menor confianza en la custodia occidental y un impulso por diversificar frente al riesgo geopolítico. En resumen, el alza del oro sigue al pie de la letra la lógica tradicional de refugio ante la aversión al riesgo.</p>
  <p class="de">Gold erreichte am 28. Januar 2026 ein Allzeithoch von 5.589,38 $ je Unze, rund 80% über dem Stand von Anfang 2025. Laut Zahlen des World Gold Council kauften Zentralbanken allein im ersten Quartal netto 244 Tonnen (+3% im Jahresvergleich), wobei das Jahrestempo auf 700-900 Tonnen zusteuert — deutlich über den Durchschnittswerten vor 2022. Polen, China, Indien, Kasachstan und Brasilien zählen zu den größten Käufern; die Nachfrage wurzelt in souveränen Motiven: geringeres Vertrauen in westliche Verwahrung und der Drang, sich von geopolitischem Risiko zu diversifizieren. Kurz gesagt folgt Golds Anstieg buchstabengetreu der traditionellen Safe-Haven-Logik der Risikoaversion.</p>
  <p class="fr">L'or a atteint un sommet historique de 5 589,38 $ l'once le 28 janvier 2026, en hausse d'environ 80% depuis le début de 2025. Selon les chiffres du World Gold Council, les banques centrales ont acheté net 244 tonnes rien qu'au premier trimestre (+3% sur un an), le rythme annuel visant 700-900 tonnes — bien au-dessus des moyennes d'avant 2022. La Pologne, la Chine, l'Inde, le Kazakhstan et le Brésil figurent parmi les principaux acheteurs, une demande enracinée dans des motifs souverains : une confiance réduite envers la conservation occidentale et une volonté de diversification face au risque géopolitique. En somme, la hausse de l'or suit à la lettre la logique traditionnelle de refuge face à l'aversion au risque.</p>
  <p class="pt">O ouro atingiu uma máxima histórica de US$ 5.589,38 a onça em 28 de janeiro de 2026, alta de cerca de 80% desde o início de 2025. Segundo dados do World Gold Council, os bancos centrais compraram líquido 244 toneladas só no primeiro trimestre (+3% na comparação anual), com o ritmo anual apontando para 700-900 toneladas — bem acima das médias pré-2022. Polônia, China, Índia, Cazaquistão e Brasil estão entre os maiores compradores, uma demanda enraizada em motivos soberanos: menor confiança na custódia ocidental e um esforço de diversificação frente ao risco geopolítico. Em suma, a alta do ouro segue à risca a lógica tradicional de refúgio por aversão ao risco.</p>
  <p class="tr">Altın, 28 Ocak 2026'da ons başına 5.589,38 dolarla tarihi zirveye ulaştı; 2025 başından bu yana yaklaşık %80 yükseldi. Dünya Altın Konseyi verilerine göre, merkez bankaları yalnızca ilk çeyrekte net 244 ton aldı (yıllık +%3), yıllık tempo ise 2022 öncesi ortalamaların çok üzerinde olan 700-900 tona işaret ediyor. Polonya, Çin, Hindistan, Kazakistan ve Brezilya en büyük alıcılar arasında; bu talep, Batı'daki saklamaya olan güvenin azalması ve jeopolitik riskten çeşitlendirme gibi egemen gerekçelere dayanıyor — kısacası altının yükselişi, risk kaçınmasının geleneksel güvenli liman mantığını harfiyen izliyor.</p>
  <p class="vi">Vàng chạm đỉnh lịch sử 5.589,38 đô la/ounce vào ngày 28 tháng 1 năm 2026, tăng khoảng 80% so với đầu năm 2025. Theo số liệu của Hội đồng Vàng Thế giới, các ngân hàng trung ương đã mua ròng 244 tấn chỉ trong quý 1 (+3% so với cùng kỳ năm trước), với tốc độ cả năm hướng tới 700-900 tấn — cao hơn nhiều so với mức trung bình trước năm 2022. Ba Lan, Trung Quốc, Ấn Độ, Kazakhstan và Brazil nằm trong số những nước mua nhiều nhất, nhu cầu bắt nguồn từ động cơ chủ quyền: niềm tin giảm sút vào việc lưu ký ở phương Tây và mong muốn đa dạng hóa khỏi rủi ro địa chính trị. Nói ngắn gọn, đà tăng của vàng tuân theo đúng logic trú ẩn an toàn truyền thống của việc né tránh rủi ro.</p>

  <p class="ko">반면 비트코인은 같은 기간 정반대로 움직였다. 10월 $126,000 고점에서 6월 30일 $57,900까지 약 54% 급락한 뒤에야 반등이 나왔다. 옐로우닷컴·크립토뉴스넷 등의 보도에 따르면 두 자산의 30일 롤링 상관계수는 2026년 들어 -0.7에서 -0.88 사이까지 떨어진 시점들이 관측됐으며, 이는 2022년 11월 FTX 붕괴 이후 가장 낮은 수준이다(트래커·측정 구간에 따라 절대값 차이는 있다). JP모건·반에크 계열의 분석은 이를 두고 비트코인이 이제 금 같은 가치저장 수단이 아니라 글로벌 M2 유동성과 위험선호를 반영하는 자산으로 재편됐다고 해석한다.</p>
  <p class="en">Bitcoin, over the same window, moved in the opposite direction. It fell about 54% from its October peak of $126,000 to the $57,900 low on June 30 before any bounce appeared. Per reporting from Yellow.com and CryptoNews.net, the two assets' 30-day rolling correlation was observed dropping to between -0.7 and -0.88 at points in 2026 — the lowest since the November 2022 FTX collapse (absolute figures vary by tracker and measurement window). Analysis in the vein of JPMorgan and VanEck reads this as bitcoin having been reclassified: no longer a gold-like store of value, but an asset that tracks global M2 liquidity and risk appetite instead.</p>
  <p class="ja">一方ビットコインは同じ期間、正反対の動きをした。10月の高値12万6,000ドルから6月30日の5万7,900ドルまで約54%急落した後にようやく反発が来た。イエロー・ドット・コムやクリプトニュースネットなどの報道によれば、両資産の30日ローリング相関係数は2026年に入り-0.7から-0.88の間まで下落した時点が観測されており、これは2022年11月のFTX破綻以来最も低い水準だ(トラッカーや測定期間によって絶対値は異なる)。JPモルガンやヴァンエック系の分析はこれを、ビットコインがもはや金のような価値保存手段ではなく、グローバルM2流動性とリスク選好を反映する資産に再編されたと解釈している。</p>
  <p class="es">Bitcoin, en la misma ventana, se movió en dirección opuesta. Cayó cerca de un 54% desde su pico de octubre de 126.000 $ hasta el mínimo de 57.900 $ del 30 de junio antes de que apareciera cualquier rebote. Según reportes de Yellow.com y CryptoNews.net, se observó que la correlación móvil de 30 días de ambos activos caía a entre -0,7 y -0,88 en algunos momentos de 2026 —el nivel más bajo desde el colapso de FTX en noviembre de 2022 (las cifras absolutas varían según el rastreador y la ventana de medición). Análisis en la línea de JPMorgan y VanEck interpretan esto como una reclasificación de bitcoin: ya no una reserva de valor tipo oro, sino un activo que sigue la liquidez global M2 y el apetito por el riesgo.</p>
  <p class="de">Bitcoin bewegte sich im selben Zeitraum in die entgegengesetzte Richtung. Es fiel um rund 54% von seinem Oktoberhoch von 126.000 $ auf das Tief von 57.900 $ am 30. Juni, bevor überhaupt eine Erholung einsetzte. Laut Berichten von Yellow.com und CryptoNews.net wurde beobachtet, dass die 30-Tage-Rollkorrelation beider Assets 2026 zeitweise auf -0,7 bis -0,88 fiel — der niedrigste Stand seit dem FTX-Kollaps im November 2022 (absolute Werte variieren je nach Tracker und Messfenster). Analysen im Stil von JPMorgan und VanEck deuten dies als Neueinordnung von Bitcoin: kein goldähnlicher Wertspeicher mehr, sondern ein Asset, das globale M2-Liquidität und Risikoappetit widerspiegelt.</p>
  <p class="fr">Le bitcoin, sur la même période, a évolué dans la direction opposée. Il a chuté d'environ 54% depuis son sommet d'octobre à 126 000 $ jusqu'au plancher de 57 900 $ du 30 juin avant qu'un quelconque rebond n'apparaisse. Selon des rapports de Yellow.com et CryptoNews.net, la corrélation glissante sur 30 jours des deux actifs a été observée tombant entre -0,7 et -0,88 à certains moments de 2026 — le niveau le plus bas depuis l'effondrement de FTX en novembre 2022 (les chiffres absolus varient selon le tracker et la fenêtre de mesure). Des analyses dans la lignée de JPMorgan et VanEck y voient une reclassification du bitcoin : non plus une réserve de valeur façon or, mais un actif qui suit la liquidité mondiale M2 et l'appétit pour le risque.</p>
  <p class="pt">O bitcoin, no mesmo período, moveu-se na direção oposta. Caiu cerca de 54% de seu pico de outubro de US$ 126.000 até a mínima de US$ 57.900 em 30 de junho antes que qualquer recuperação aparecesse. Segundo reportagens da Yellow.com e CryptoNews.net, observou-se a correlação móvel de 30 dias dos dois ativos caindo para entre -0,7 e -0,88 em pontos de 2026 — o nível mais baixo desde o colapso da FTX em novembro de 2022 (os números absolutos variam conforme o rastreador e a janela de medição). Análises na linha do JPMorgan e da VanEck interpretam isso como uma reclassificação do bitcoin: não mais uma reserva de valor tipo ouro, mas um ativo que acompanha a liquidez global M2 e o apetite por risco.</p>
  <p class="tr">Bitcoin ise aynı dönemde tam tersi yönde hareket etti. Herhangi bir toparlanma görülmeden önce, Ekim'deki 126.000 dolarlık zirveden 30 Haziran'daki 57.900 dolarlık dibe kadar yaklaşık %54 geriledi. Yellow.com ve CryptoNews.net haberlerine göre, iki varlığın 30 günlük yuvarlanan korelasyonunun 2026'da bazı noktalarda -0,7 ile -0,88 arasına düştüğü gözlemlendi — bu, Kasım 2022'deki FTX çöküşünden bu yana en düşük seviye (mutlak rakamlar izleyiciye ve ölçüm penceresine göre değişiyor). JPMorgan ve VanEck tarzı analizler bunu, bitcoin'in artık altın gibi bir değer saklama aracı değil, küresel M2 likiditesini ve risk iştahını yansıtan bir varlık olarak yeniden sınıflandırıldığı şeklinde yorumluyor.</p>
  <p class="vi">Trong cùng giai đoạn, bitcoin lại di chuyển theo hướng ngược lại. Nó giảm khoảng 54% từ đỉnh 126.000 đô la hồi tháng 10 xuống đáy 57.900 đô la vào ngày 30 tháng 6 trước khi có bất kỳ đợt phục hồi nào xuất hiện. Theo báo cáo từ Yellow.com và CryptoNews.net, tương quan trượt 30 ngày giữa hai tài sản được ghi nhận giảm xuống còn -0,7 đến -0,88 tại một số thời điểm trong năm 2026 — mức thấp nhất kể từ sự sụp đổ của FTX vào tháng 11 năm 2022 (các con số tuyệt đối khác nhau tùy theo trang theo dõi và khung đo lường). Các phân tích theo hướng của JPMorgan và VanEck diễn giải điều này là bitcoin đã được phân loại lại: không còn là công cụ lưu trữ giá trị giống vàng nữa, mà là tài sản phản ánh thanh khoản M2 toàn cầu và khẩu vị rủi ro.</p>

  <div class="ko">
  <svg viewBox="0 0 700 640" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">가격 · 금 상관관계 · 심리 — 세 바늘이 다른 곳을 가리키다</text>
    <g font-family="sans-serif">
      <text x="20" y="55" fill="#a1a1aa" font-size="13" font-weight="700">① 저점 대비 +11% 반등</text>
      <line x1="40" y1="190" x2="670" y2="190" stroke="rgba(255,255,255,.15)" stroke-width="1"/>
      <rect x="100" y="92" width="140" height="98" fill="rgba(161,161,170,.22)" stroke="#a1a1aa"/>
      <text x="170" y="82" fill="#d4d4d8" font-size="14" font-weight="800" text-anchor="middle">$57,900</text>
      <text x="170" y="207" fill="#a1a1aa" font-size="13" text-anchor="middle">6/30 저점</text>
      <rect x="460" y="81" width="140" height="109" fill="rgba(74,222,128,.28)" stroke="#4ade80" stroke-width="1.8"/>
      <text x="530" y="71" fill="#4ade80" font-size="14" font-weight="800" text-anchor="middle">$64,330</text>
      <text x="530" y="207" fill="#a1a1aa" font-size="13" text-anchor="middle">7/6~7</text>
      <text x="350" y="140" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle">주간 +6.27% · 저점 대비 +11%</text>
      <text x="350" y="226" fill="#a1a1aa" font-size="13" text-anchor="middle">동력: 6월 고용 5.7만&lt;예상 11.3만 → 금리·달러 하락 (안전자산 수요 아님)</text>

      <text x="20" y="264" fill="#a1a1aa" font-size="13" font-weight="700">② 비트코인-금 30일 롤링 상관계수</text>
      <line x1="60" y1="340" x2="640" y2="340" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
      <line x1="60" y1="334" x2="60" y2="346" stroke="#71717a"/>
      <line x1="350" y1="334" x2="350" y2="346" stroke="#71717a"/>
      <line x1="640" y1="334" x2="640" y2="346" stroke="#71717a"/>
      <text x="60" y="362" fill="#71717a" font-size="12" text-anchor="middle">-1</text>
      <text x="350" y="362" fill="#71717a" font-size="12" text-anchor="middle">0</text>
      <text x="640" y="362" fill="#71717a" font-size="12" text-anchor="middle">+1</text>
      <circle cx="121" cy="340" r="6" fill="#f87171"/>
      <line x1="121" y1="340" x2="121" y2="303" stroke="#f87171" stroke-width="1.5"/>
      <text x="121" y="293" fill="#f87171" font-size="13" font-weight="800" text-anchor="middle">−0.7~−0.88</text>
      <text x="121" y="380" fill="#a1a1aa" font-size="12" text-anchor="middle">2022년 이후 최저</text>
      <circle cx="452" cy="340" r="5" fill="#a1a1aa"/>
      <line x1="452" y1="340" x2="452" y2="303" stroke="#a1a1aa" stroke-width="1.5"/>
      <text x="452" y="293" fill="#a1a1aa" font-size="13" font-weight="700" text-anchor="middle">+0.2~+0.5</text>
      <text x="452" y="380" fill="#71717a" font-size="12" text-anchor="middle">평상시 범위</text>

      <rect x="70" y="400" width="270" height="72" rx="6" fill="rgba(251,191,36,.12)" stroke="#fbbf24"/>
      <text x="85" y="423" fill="#fbbf24" font-size="13" font-weight="700">금: 1/28 사상 최고가 $5,589.38</text>
      <text x="85" y="447" fill="#d4d4d8" font-size="12.5">중앙은행 1분기 순매수 244t (+3% YoY)</text>
      <rect x="360" y="400" width="270" height="72" rx="6" fill="rgba(248,113,113,.12)" stroke="#f87171"/>
      <text x="375" y="423" fill="#f87171" font-size="13" font-weight="700">BTC: 10월 사상 최고가 $126,000</text>
      <text x="375" y="447" fill="#d4d4d8" font-size="12.5">→ 6/30 저점 $57,900 (−54%)</text>

      <text x="20" y="506" fill="#a1a1aa" font-size="13" font-weight="700">③ 공포탐욕지수 — 반등에도 '극단적 공포'</text>
      <rect x="60" y="530" width="145" height="30" fill="#f87171" opacity=".55"/>
      <rect x="205" y="530" width="116" height="30" fill="#fbbf24" opacity=".55"/>
      <rect x="321" y="530" width="58" height="30" fill="#a1a1aa" opacity=".4"/>
      <rect x="379" y="530" width="261" height="30" fill="#4ade80" opacity=".45"/>
      <polygon points="197,514 213,514 205,528" fill="#fafafa"/>
      <text x="205" y="506" fill="#fafafa" font-size="13" font-weight="800" text-anchor="middle">현재 23~27</text>
      <text x="132" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">극단적 공포</text>
      <text x="263" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">공포</text>
      <text x="350" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">중립</text>
      <text x="509" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">탐욕+</text>
      <text x="350" y="612" fill="#fbbf24" font-size="13" text-anchor="middle">저점 대비 +11% 반등에도 지수는 '극단적 공포~공포' 경계에 머묾</text>
    </g>
  </svg>
  </div>
  <div class="ja">
  <svg viewBox="0 0 700 640" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">価格・金相関・心理——3本の針が別々の方向を指す</text>
    <g font-family="sans-serif">
      <text x="20" y="55" fill="#a1a1aa" font-size="13" font-weight="700">①安値比+11%の反発</text>
      <line x1="40" y1="190" x2="670" y2="190" stroke="rgba(255,255,255,.15)" stroke-width="1"/>
      <rect x="100" y="92" width="140" height="98" fill="rgba(161,161,170,.22)" stroke="#a1a1aa"/>
      <text x="170" y="82" fill="#d4d4d8" font-size="14" font-weight="800" text-anchor="middle">$57,900</text>
      <text x="170" y="207" fill="#a1a1aa" font-size="13" text-anchor="middle">6/30安値</text>
      <rect x="460" y="81" width="140" height="109" fill="rgba(74,222,128,.28)" stroke="#4ade80" stroke-width="1.8"/>
      <text x="530" y="71" fill="#4ade80" font-size="14" font-weight="800" text-anchor="middle">$64,330</text>
      <text x="530" y="207" fill="#a1a1aa" font-size="13" text-anchor="middle">7/6~7</text>
      <text x="350" y="140" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle">週間+6.27%・安値比+11%</text>
      <text x="350" y="226" fill="#a1a1aa" font-size="13" text-anchor="middle">動力:6月雇用5.7万&lt;予想11.3万→金利・ドル下落(安全資産需要ではない)</text>

      <text x="20" y="264" fill="#a1a1aa" font-size="13" font-weight="700">②ビットコイン-金30日ローリング相関係数</text>
      <line x1="60" y1="340" x2="640" y2="340" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
      <line x1="60" y1="334" x2="60" y2="346" stroke="#71717a"/>
      <line x1="350" y1="334" x2="350" y2="346" stroke="#71717a"/>
      <line x1="640" y1="334" x2="640" y2="346" stroke="#71717a"/>
      <text x="60" y="362" fill="#71717a" font-size="12" text-anchor="middle">-1</text>
      <text x="350" y="362" fill="#71717a" font-size="12" text-anchor="middle">0</text>
      <text x="640" y="362" fill="#71717a" font-size="12" text-anchor="middle">+1</text>
      <circle cx="121" cy="340" r="6" fill="#f87171"/>
      <line x1="121" y1="340" x2="121" y2="303" stroke="#f87171" stroke-width="1.5"/>
      <text x="121" y="293" fill="#f87171" font-size="13" font-weight="800" text-anchor="middle">−0.7~−0.88</text>
      <text x="121" y="380" fill="#a1a1aa" font-size="12" text-anchor="middle">2022年以来最低</text>
      <circle cx="452" cy="340" r="5" fill="#a1a1aa"/>
      <line x1="452" y1="340" x2="452" y2="303" stroke="#a1a1aa" stroke-width="1.5"/>
      <text x="452" y="293" fill="#a1a1aa" font-size="13" font-weight="700" text-anchor="middle">+0.2~+0.5</text>
      <text x="452" y="380" fill="#71717a" font-size="12" text-anchor="middle">通常時の範囲</text>

      <rect x="70" y="400" width="270" height="72" rx="6" fill="rgba(251,191,36,.12)" stroke="#fbbf24"/>
      <text x="85" y="423" fill="#fbbf24" font-size="13" font-weight="700">金:1/28 史上最高値$5,589.38</text>
      <text x="85" y="447" fill="#d4d4d8" font-size="12.5">中央銀行第1四半期純購入244t(+3%YoY)</text>
      <rect x="360" y="400" width="270" height="72" rx="6" fill="rgba(248,113,113,.12)" stroke="#f87171"/>
      <text x="375" y="423" fill="#f87171" font-size="13" font-weight="700">BTC:10月史上最高値$126,000</text>
      <text x="375" y="447" fill="#d4d4d8" font-size="12.5">→6/30安値$57,900(−54%)</text>

      <text x="20" y="506" fill="#a1a1aa" font-size="13" font-weight="700">③恐怖強欲指数——反発中も「極端な恐怖」</text>
      <rect x="60" y="530" width="145" height="30" fill="#f87171" opacity=".55"/>
      <rect x="205" y="530" width="116" height="30" fill="#fbbf24" opacity=".55"/>
      <rect x="321" y="530" width="58" height="30" fill="#a1a1aa" opacity=".4"/>
      <rect x="379" y="530" width="261" height="30" fill="#4ade80" opacity=".45"/>
      <polygon points="197,514 213,514 205,528" fill="#fafafa"/>
      <text x="205" y="506" fill="#fafafa" font-size="13" font-weight="800" text-anchor="middle">現在23~27</text>
      <text x="132" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">極端な恐怖</text>
      <text x="263" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">恐怖</text>
      <text x="350" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">中立</text>
      <text x="509" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">強欲+</text>
      <text x="350" y="612" fill="#fbbf24" font-size="13" text-anchor="middle">安値比+11%反発でも指数は「極端な恐怖~恐怖」の境界にとどまる</text>
    </g>
  </svg>
  </div>
  <div class="en es de fr pt tr vi">
  <svg viewBox="0 0 700 640" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">Price · Gold Correlation · Sentiment — Three Needles, Three Directions</text>
    <g font-family="sans-serif">
      <text x="20" y="55" fill="#a1a1aa" font-size="13" font-weight="700">① +11% Off the Low</text>
      <line x1="40" y1="190" x2="670" y2="190" stroke="rgba(255,255,255,.15)" stroke-width="1"/>
      <rect x="100" y="92" width="140" height="98" fill="rgba(161,161,170,.22)" stroke="#a1a1aa"/>
      <text x="170" y="82" fill="#d4d4d8" font-size="14" font-weight="800" text-anchor="middle">$57,900</text>
      <text x="170" y="207" fill="#a1a1aa" font-size="13" text-anchor="middle">Low, 6/30</text>
      <rect x="460" y="81" width="140" height="109" fill="rgba(74,222,128,.28)" stroke="#4ade80" stroke-width="1.8"/>
      <text x="530" y="71" fill="#4ade80" font-size="14" font-weight="800" text-anchor="middle">$64,330</text>
      <text x="530" y="207" fill="#a1a1aa" font-size="13" text-anchor="middle">7/6-7</text>
      <text x="350" y="140" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle">+6.27%/week · +11% off low</text>
      <text x="350" y="226" fill="#a1a1aa" font-size="13" text-anchor="middle">Driver: June jobs 57K &lt; 113K forecast → yields, dollar down (not safe-haven demand)</text>

      <text x="20" y="264" fill="#a1a1aa" font-size="13" font-weight="700">② BTC-Gold 30-Day Rolling Correlation</text>
      <line x1="60" y1="340" x2="640" y2="340" stroke="rgba(255,255,255,.2)" stroke-width="1.5"/>
      <line x1="60" y1="334" x2="60" y2="346" stroke="#71717a"/>
      <line x1="350" y1="334" x2="350" y2="346" stroke="#71717a"/>
      <line x1="640" y1="334" x2="640" y2="346" stroke="#71717a"/>
      <text x="60" y="362" fill="#71717a" font-size="12" text-anchor="middle">-1</text>
      <text x="350" y="362" fill="#71717a" font-size="12" text-anchor="middle">0</text>
      <text x="640" y="362" fill="#71717a" font-size="12" text-anchor="middle">+1</text>
      <circle cx="121" cy="340" r="6" fill="#f87171"/>
      <line x1="121" y1="340" x2="121" y2="303" stroke="#f87171" stroke-width="1.5"/>
      <text x="121" y="293" fill="#f87171" font-size="13" font-weight="800" text-anchor="middle">−0.7 to −0.88</text>
      <text x="121" y="380" fill="#a1a1aa" font-size="12" text-anchor="middle">lowest since 2022</text>
      <circle cx="452" cy="340" r="5" fill="#a1a1aa"/>
      <line x1="452" y1="340" x2="452" y2="303" stroke="#a1a1aa" stroke-width="1.5"/>
      <text x="452" y="293" fill="#a1a1aa" font-size="13" font-weight="700" text-anchor="middle">+0.2 to +0.5</text>
      <text x="452" y="380" fill="#71717a" font-size="12" text-anchor="middle">typical range</text>

      <rect x="70" y="400" width="270" height="72" rx="6" fill="rgba(251,191,36,.12)" stroke="#fbbf24"/>
      <text x="85" y="423" fill="#fbbf24" font-size="13" font-weight="700">Gold: ATH $5,589.38 (Jan 28)</text>
      <text x="85" y="447" fill="#d4d4d8" font-size="12.5">Central banks +244t net in Q1 (+3% y/y)</text>
      <rect x="360" y="400" width="270" height="72" rx="6" fill="rgba(248,113,113,.12)" stroke="#f87171"/>
      <text x="375" y="423" fill="#f87171" font-size="13" font-weight="700">BTC: ATH $126,000 (October)</text>
      <text x="375" y="447" fill="#d4d4d8" font-size="12.5">→ $57,900 low, 6/30 (−54%)</text>

      <text x="20" y="506" fill="#a1a1aa" font-size="13" font-weight="700">③ Fear &amp; Greed — Still "Extreme Fear" Amid the Bounce</text>
      <rect x="60" y="530" width="145" height="30" fill="#f87171" opacity=".55"/>
      <rect x="205" y="530" width="116" height="30" fill="#fbbf24" opacity=".55"/>
      <rect x="321" y="530" width="58" height="30" fill="#a1a1aa" opacity=".4"/>
      <rect x="379" y="530" width="261" height="30" fill="#4ade80" opacity=".45"/>
      <polygon points="197,514 213,514 205,528" fill="#fafafa"/>
      <text x="205" y="506" fill="#fafafa" font-size="13" font-weight="800" text-anchor="middle">now 23-27</text>
      <text x="132" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">Extreme Fear</text>
      <text x="263" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">Fear</text>
      <text x="350" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">Neutral</text>
      <text x="509" y="582" fill="#d4d4d8" font-size="12.5" text-anchor="middle">Greed+</text>
      <text x="350" y="612" fill="#fbbf24" font-size="13" text-anchor="middle">Even up 11% off the low, the index stays at the Extreme Fear / Fear line</text>
    </g>
  </svg>
  </div>

  <p class="ko">상관관계가 마이너스로 갈라졌다는 것은, 투자자들이 '안전'이 필요할 때 비트코인 대신 금을 선택하고 있다는 뜻이다. 이번 주 반등도 이 구도를 벗어나지 않는다 — 비트코인은 금리 인하 기대라는 유동성 재료에 반응해 오른 것이지, 지정학적 불안에 대한 헤지 수요로 오른 게 아니다. 두 자산이 서로 다른 이유로 움직이는 지금, 비트코인을 '디지털 골드'로 부르는 서사는 적어도 가격 동학 차원에서는 근거를 잃고 있다.</p>
  <p class="en">A correlation that's split into negative territory means investors are choosing gold over bitcoin when they need "safety." This week's bounce doesn't break that pattern — bitcoin rallied on the liquidity trigger of rate-cut hopes, not on hedge demand against geopolitical unease. With the two assets moving for entirely different reasons right now, the narrative of bitcoin as "digital gold" is losing its footing, at least at the level of price dynamics.</p>
  <p class="ja">相関係数がマイナスに割れているということは、投資家が「安全」を必要とするとき、ビットコインではなく金を選んでいるということだ。今週の反発もこの構図を外れていない——ビットコインは利下げ期待という流動性材料に反応して上昇したのであり、地政学的不安に対するヘッジ需要で上がったのではない。両資産がまったく異なる理由で動いている今、ビットコインを「デジタルゴールド」と呼ぶ物語は、少なくとも価格の動きという次元では根拠を失いつつある。</p>
  <p class="es">Una correlación que se ha partido hacia territorio negativo significa que los inversores eligen el oro en lugar de bitcoin cuando necesitan "seguridad". El rebote de esta semana no rompe ese patrón: bitcoin repuntó por el disparador de liquidez de las expectativas de recorte de tipos, no por demanda de cobertura contra la inquietud geopolítica. Con los dos activos moviéndose ahora mismo por razones completamente distintas, el relato de bitcoin como "oro digital" está perdiendo sustento, al menos en el plano de la dinámica de precios.</p>
  <p class="de">Eine ins Negative gedrehte Korrelation bedeutet, dass Anleger Gold statt Bitcoin wählen, wenn sie "Sicherheit" brauchen. Die Erholung dieser Woche durchbricht dieses Muster nicht — Bitcoin legte wegen des Liquiditätsauslösers Zinssenkungshoffnung zu, nicht wegen Absicherungsnachfrage gegen geopolitische Unruhe. Da sich die beiden Assets derzeit aus völlig unterschiedlichen Gründen bewegen, verliert die Erzählung von Bitcoin als "digitalem Gold" zumindest auf der Ebene der Preisdynamik an Boden.</p>
  <p class="fr">Une corrélation qui a basculé en territoire négatif signifie que les investisseurs choisissent l'or plutôt que le bitcoin quand ils ont besoin de « sécurité ». Le rebond de cette semaine ne rompt pas ce schéma — le bitcoin a rebondi sur le déclencheur de liquidité que représentent les espoirs de baisse des taux, pas sur une demande de couverture contre l'inquiétude géopolitique. Avec les deux actifs évoluant en ce moment pour des raisons entièrement différentes, le récit du bitcoin comme « or numérique » perd pied, du moins au niveau de la dynamique des prix.</p>
  <p class="pt">Uma correlação que se dividiu para o território negativo significa que os investidores estão escolhendo ouro em vez de bitcoin quando precisam de "segurança". A recuperação desta semana não quebra esse padrão — o bitcoin subiu pelo gatilho de liquidez das expectativas de corte de juros, não por demanda de proteção contra a inquietação geopolítica. Com os dois ativos se movendo agora por razões totalmente diferentes, a narrativa do bitcoin como "ouro digital" está perdendo terreno, ao menos no nível da dinâmica de preços.</p>
  <p class="tr">Negatif bölgeye ayrılan bir korelasyon, yatırımcıların "güvenlik" ihtiyacı duyduklarında bitcoin yerine altını seçtiği anlamına gelir. Bu haftaki yükseliş de bu örüntüyü bozmuyor — bitcoin, jeopolitik tedirginliğe karşı bir koruma talebiyle değil, faiz indirimi umutlarının likidite tetikleyicisiyle yükseldi. İki varlık şu anda tamamen farklı nedenlerle hareket ederken, bitcoin'i "dijital altın" olarak adlandıran anlatı, en azından fiyat dinamikleri düzeyinde dayanağını yitiriyor.</p>
  <p class="vi">Tương quan chuyển sang vùng âm có nghĩa là các nhà đầu tư đang chọn vàng thay vì bitcoin khi họ cần "sự an toàn". Đợt phục hồi tuần này không phá vỡ khuôn mẫu đó — bitcoin tăng nhờ chất xúc tác thanh khoản là kỳ vọng cắt giảm lãi suất, chứ không phải nhu cầu phòng hộ trước bất ổn địa chính trị. Khi hai tài sản này đang di chuyển vì những lý do hoàn toàn khác nhau, câu chuyện coi bitcoin là "vàng kỹ thuật số" đang mất chỗ đứng, ít nhất là ở cấp độ động lực giá.</p>

  <h2 class="ko">③ 반등에도 웃지 않는 공포탐욕지수, 조용한 펀딩비</h2>
  <h2 class="en">③ A Fear & Greed Index That Won't Smile — and a Quiet Funding Rate</h2>
  <h2 class="ja">③反発でも笑わない恐怖強欲指数、静かな資金調達率</h2>
  <h2 class="es">③ Un Índice de Miedo y Codicia Que No Sonríe — y una Tasa de Financiación Silenciosa</h2>
  <h2 class="de">③ Ein Fear-&-Greed-Index, der nicht lächelt — und eine ruhige Finanzierungsrate</h2>
  <h2 class="fr">③ Un Indice de Peur et de Cupidité Qui Ne Sourit Pas — et un Taux de Financement Discret</h2>
  <h2 class="pt">③ Um Índice de Medo e Ganância Que Não Sorri — e uma Taxa de Financiamento Silenciosa</h2>
  <h2 class="tr">③ Gülümsemeyen Korku ve Açgözlülük Endeksi — ve Sessiz Fonlama Oranı</h2>
  <h2 class="vi">③ Chỉ Số Sợ Hãi và Tham Lam Không Chịu Mỉm Cười — và Phí Funding Lặng Lẽ</h2>

  <p class="ko">가격이 저점 대비 11% 오르는 동안 심리 지표는 거의 움직이지 않았다. 얼터너티브미·밀크로드·코인마켓캡 등의 크립토 공포탐욕지수는 7월 5일 전후로 '극단적 공포'에서 '공포'로 한 단계 개선되는 조짐을 보였지만, 7월 6~7일에도 23~27 사이에 머물렀다. 통상 가격이 저점 대비 두 자릿수 %로 반등하면 지수는 최소 '중립' 근처까지 따라 올라가는 경우가 많은데, 이번엔 그 정도의 동조가 나타나지 않았다.</p>
  <p class="en">While price climbed 11% off its low, sentiment barely moved. The crypto Fear & Greed Index, per Alternative.me, Milkroad and CoinMarketCap, showed hints of easing from "Extreme Fear" to "Fear" around July 5, but stayed at 23-27 through July 6-7. A double-digit percentage bounce off a low usually pulls the index up toward "Neutral" at minimum — that degree of co-movement hasn't shown up this time.</p>
  <p class="ja">価格が安値比11%上昇する間、心理指標はほとんど動かなかった。オルタナティブミー・ミルクロード・コインマーケットキャップなどのクリプト恐怖強欲指数は7月5日前後に「極端な恐怖」から「恐怖」へ一段改善する兆しを見せたが、7月6~7日でも23~27の間にとどまった。通常、価格が安値比で二桁%反発すれば指数も最低「中立」近くまで追随することが多いが、今回はその程度の連動は見られていない。</p>
  <p class="es">Mientras el precio subía un 11% desde su mínimo, el sentimiento apenas se movió. El Índice de Miedo y Codicia cripto, según Alternative.me, Milkroad y CoinMarketCap, mostró indicios de pasar de "Miedo Extremo" a "Miedo" alrededor del 5 de julio, pero se mantuvo en 23-27 durante el 6-7 de julio. Un rebote de dos dígitos porcentuales desde un mínimo suele llevar al índice al menos cerca de "Neutral" — ese grado de correlación no ha aparecido esta vez.</p>
  <p class="de">Während der Preis 11% vom Tief kletterte, bewegte sich die Stimmung kaum. Der Krypto-Fear-&-Greed-Index zeigte laut Alternative.me, Milkroad und CoinMarketCap um den 5. Juli Anzeichen einer Aufhellung von "Extreme Angst" zu "Angst", blieb aber am 6.-7. Juli bei 23-27. Eine zweistellige prozentuale Erholung vom Tief zieht den Index normalerweise mindestens in Richtung "Neutral" — dieses Ausmaß an Gleichlauf ist diesmal ausgeblieben.</p>
  <p class="fr">Alors que le prix grimpait de 11% depuis son plus bas, le sentiment a à peine bougé. L'indice crypto de Peur et de Cupidité, selon Alternative.me, Milkroad et CoinMarketCap, a montré des signes d'amélioration de "Peur Extrême" vers "Peur" autour du 5 juillet, mais est resté à 23-27 les 6-7 juillet. Un rebond à deux chiffres depuis un plus bas tire habituellement l'indice au moins vers "Neutre" — ce degré de co-mouvement ne s'est pas produit cette fois.</p>
  <p class="pt">Enquanto o preço subia 11% em relação à mínima, o sentimento mal se mexeu. O Índice de Medo e Ganância cripto, segundo Alternative.me, Milkroad e CoinMarketCap, mostrou indícios de melhora de "Medo Extremo" para "Medo" por volta de 5 de julho, mas ficou em 23-27 em 6-7 de julho. Uma recuperação de dois dígitos percentuais a partir de uma mínima costuma puxar o índice pelo menos perto de "Neutro" — esse grau de comovimento não apareceu desta vez.</p>
  <p class="tr">Fiyat dipten %11 yükselirken duygu durumu neredeyse hiç kıpırdamadı. Alternative.me, Milkroad ve CoinMarketCap'e göre kripto Korku ve Açgözlülük Endeksi, 5 Temmuz civarında "Aşırı Korku"dan "Korku"ya hafif bir iyileşme belirtisi gösterdi ama 6-7 Temmuz'da 23-27'de kaldı. Dipten çift haneli yüzdelik bir yükseliş genellikle endeksi en azından "Nötr"e yaklaştırır — bu kez bu derece bir eş hareket görülmedi.</p>
  <p class="vi">Trong khi giá tăng 11% từ đáy, tâm lý hầu như không nhúc nhích. Chỉ số Sợ hãi và Tham lam tiền điện tử, theo Alternative.me, Milkroad và CoinMarketCap, cho thấy dấu hiệu cải thiện từ "Sợ hãi Cực độ" sang "Sợ hãi" quanh ngày 5 tháng 7, nhưng vẫn ở mức 23-27 trong ngày 6-7 tháng 7. Một đợt phục hồi hai chữ số phần trăm từ đáy thường kéo chỉ số lên ít nhất gần mức "Trung lập" — mức độ đồng biến đó chưa xuất hiện lần này.</p>

  <p class="ko">파생상품 쪽도 조용하다. 코인스탯츠 AI의 7월 7일 집계에 따르면 펀딩비는 0.0087% 수준으로, 신규 롱 포지션이 붙고는 있지만 과열이라 부를 수준은 아니다. 미결제약정(OI) 역시 한 트래커 기준 $47.71B로 30일 새 +6.11% 늘었지만, 다른 집계는 $109.07B(-0.56%)를 제시해 집계 방식에 따라 절대값 차이가 크다 — 다만 방향성만 보면 극단적인 레버리지 쏠림은 아직 관측되지 않는다. 가격은 오르는데 심리도, 레버리지도 뒤따르지 않는 조합은 이번 반등이 아직 '확신에 찬 신규 매수'보다는 숏커버링과 매크로 재료에 의한 조심스러운 되돌림에 가깝다는 것을 시사한다.</p>
  <p class="en">Derivatives are quiet too. Per CoinStats AI's July 7 read, the funding rate sat around 0.0087% — fresh longs are being added, but not at a level anyone would call overheated. Open interest tells a similarly cautious story: one tracker puts it at $47.71B, up 6.11% over 30 days, while another puts it at $109.07B (-0.56%) — the absolute figures diverge sharply by methodology, but directionally, no extreme leverage buildup shows up in either. Price rising without sentiment or leverage following suggests this bounce still looks more like cautious short-covering and a reaction to macro headlines than conviction-driven new buying.</p>
  <p class="ja">デリバティブ側も静かだ。コインスタッツAIの7月7日集計によれば資金調達率は0.0087%程度で、新規ロングは付いているが過熱と呼べる水準ではない。オープンインタレスト(OI)も同様に慎重な様子を示す——あるトラッカーでは30日間で+6.11%増の477.1億ドルだが、別の集計では1,090.7億ドル(-0.56%)と、集計方法により絶対値の差が大きい。ただし方向性だけ見れば、極端なレバレッジの偏りはどちらでも観測されていない。価格が上がるのに心理もレバレッジも追随しない組み合わせは、今回の反発がまだ「確信を持った新規買い」というより、ショートカバーとマクロ材料による慎重な戻しに近いことを示唆する。</p>
  <p class="es">Los derivados también están tranquilos. Según la lectura de CoinStats AI del 7 de julio, la tasa de financiación se situó en torno al 0,0087% — se suman nuevas posiciones largas, pero no a un nivel que nadie llamaría sobrecalentado. El interés abierto (OI) cuenta una historia igualmente cautelosa: un rastreador lo sitúa en 47.710 M$, un +6,11% en 30 días, mientras otro lo sitúa en 109.070 M$ (-0,56%) — las cifras absolutas divergen mucho según la metodología, pero direccionalmente no aparece una acumulación extrema de apalancamiento en ninguno de los dos. Que el precio suba sin que el sentimiento ni el apalancamiento le sigan sugiere que este repunte todavía se parece más a un cauteloso cierre de cortos y una reacción a titulares macro que a una compra nueva con convicción.</p>
  <p class="de">Auch die Derivate sind ruhig. Laut dem Stand von CoinStats AI vom 7. Juli lag die Finanzierungsrate bei rund 0,0087% — frische Longs kommen hinzu, aber nicht in einem Ausmaß, das jemand als überhitzt bezeichnen würde. Das Open Interest (OI) erzählt eine ähnlich vorsichtige Geschichte: Ein Tracker beziffert es auf 47,71 Mrd. $, ein Plus von 6,11% über 30 Tage, ein anderer auf 109,07 Mrd. $ (-0,56%) — die absoluten Zahlen weichen je nach Methodik stark voneinander ab, doch richtungsmäßig zeigt sich in keinem der beiden ein extremer Hebelaufbau. Dass der Preis steigt, ohne dass Stimmung oder Hebel folgen, deutet darauf hin, dass diese Erholung noch eher nach vorsichtigem Short-Covering und einer Reaktion auf Makro-Schlagzeilen aussieht als nach überzeugungsgetriebenen Neukäufen.</p>
  <p class="fr">Les dérivés sont également calmes. Selon la lecture de CoinStats AI du 7 juillet, le taux de financement se situait autour de 0,0087% — de nouvelles positions longues s'ajoutent, mais pas à un niveau que quiconque qualifierait de surchauffe. L'open interest (OI) raconte une histoire tout aussi prudente : un tracker le situe à 47,71 Md$, en hausse de 6,11% sur 30 jours, tandis qu'un autre le situe à 109,07 Md$ (-0,56%) — les chiffres absolus divergent fortement selon la méthodologie, mais sur le plan directionnel, aucune accumulation extrême de levier n'apparaît dans l'un ou l'autre cas. Un prix qui monte sans que le sentiment ni le levier ne suivent suggère que ce rebond ressemble encore davantage à un dénouement prudent de positions courtes et à une réaction aux nouvelles macro qu'à des achats nouveaux portés par la conviction.</p>
  <p class="pt">Os derivativos também estão quietos. Segundo a leitura da CoinStats AI de 7 de julho, a taxa de financiamento ficou em torno de 0,0087% — novas posições compradas estão sendo adicionadas, mas não em um nível que alguém chamaria de superaquecido. O interesse em aberto (OI) conta uma história igualmente cautelosa: um rastreador o situa em US$ 47,71 bi, alta de 6,11% em 30 dias, enquanto outro o situa em US$ 109,07 bi (-0,56%) — os números absolutos divergem bastante conforme a metodologia, mas direcionalmente não aparece um acúmulo extremo de alavancagem em nenhum dos dois. Um preço subindo sem que sentimento ou alavancagem acompanhem sugere que essa recuperação ainda se parece mais com um fechamento cauteloso de posições vendidas e uma reação a manchetes macro do que com compras novas guiadas por convicção.</p>
  <p class="tr">Türev tarafı da sessiz. CoinStats AI'nin 7 Temmuz verilerine göre fonlama oranı yaklaşık %0,0087 seviyesinde — yeni long pozisyonlar ekleniyor ama kimsenin aşırı ısınma diyeceği bir düzeyde değil. Açık pozisyon (OI) da benzer şekilde temkinli bir tablo çiziyor: bir izleyici bunu 30 günde %6,11 artışla 47,71 milyar dolar olarak gösterirken, başka bir kaynak 109,07 milyar dolar (-%0,56) veriyor — metodolojiye göre mutlak rakamlar büyük ölçüde ayrışıyor, ama yön olarak her ikisinde de aşırı bir kaldıraç birikimi görülmüyor. Fiyatın yükselirken duygu durumunun ve kaldıracın buna eşlik etmemesi, bu yükselişin hâlâ inançla yapılan yeni alımlardan çok, temkinli kısa pozisyon kapatmalarına ve makro haberlere verilen bir tepkiye benzediğini düşündürüyor.</p>
  <p class="vi">Phái sinh cũng im ắng. Theo số liệu ngày 7 tháng 7 của CoinStats AI, phí funding ở mức khoảng 0,0087% — các vị thế long mới đang được thêm vào, nhưng chưa đến mức có thể gọi là quá nóng. Hợp đồng mở (OI) cũng kể một câu chuyện thận trọng tương tự: một trang theo dõi đưa ra con số 47,71 tỷ đô la, tăng 6,11% trong 30 ngày, trong khi trang khác đưa ra 109,07 tỷ đô la (giảm 0,56%) — các con số tuyệt đối chênh lệch lớn tùy theo phương pháp, nhưng xét về hướng thì cả hai đều chưa cho thấy sự tích lũy đòn bẩy cực đoan. Giá tăng mà tâm lý lẫn đòn bẩy đều không theo sau cho thấy đợt phục hồi này vẫn giống việc đóng vị thế bán khống một cách thận trọng và phản ứng trước tin tức vĩ mô hơn là hoạt động mua mới đầy tự tin.</p>

  <h2 class="ko">지금 국면에서 지켜봐야 할 지점</h2>
  <h2 class="en">What to Watch From Here</h2>
  <h2 class="ja">今の局面で注視すべき点</h2>
  <h2 class="es">Qué Observar a Partir de Ahora</h2>
  <h2 class="de">Worauf von Hier an zu Achten Ist</h2>
  <h2 class="fr">Ce Qu'il Faut Surveiller à Partir de Maintenant</h2>
  <h2 class="pt">O Que Observar Daqui em Diante</h2>
  <h2 class="tr">Bundan Sonra İzlenmesi Gerekenler</h2>
  <h2 class="vi">Những Điều Cần Theo Dõi Từ Đây</h2>

  <p class="ko">세 지표는 서로 다른 이야기를 하는 것처럼 보이지만, 실은 같은 그림의 세 조각일 수 있다 — 비트코인은 지금 안전자산이 아니라 유동성에 베팅하는 위험자산으로 거래되고 있고, 시장 참여자들도 아직 그 베팅에 확신을 갖지 못했다. 금이 안전자산 수요를 흡수하는 동안 비트코인은 그 자리를 비워주고 있고, 정작 그 자리를 채워야 할 위험선호 심리(공포탐욕지수)와 레버리지(펀딩비·OI)는 아직 뒤따라오지 않은 상태다.</p>
  <p class="en">The three indicators look like they're telling different stories, but they may really be three pieces of the same picture — bitcoin is trading right now as a risk asset betting on liquidity, not as a safe haven, and market participants haven't yet committed to that bet. While gold soaks up safe-haven demand, bitcoin is vacating that role, and the risk appetite (Fear & Greed) and leverage (funding rate, OI) that would need to fill the gap haven't caught up yet.</p>
  <p class="ja">3つの指標は別々の話をしているように見えるが、実は同じ絵の3つの断片かもしれない——ビットコインは今、安全資産ではなく流動性に賭けるリスク資産として取引されており、市場参加者もまだその賭けに確信を持てていない。金が安全資産需要を吸収する間、ビットコインはその座を明け渡しつつあり、本来その隙間を埋めるべきリスク選好心理(恐怖強欲指数)とレバレッジ(資金調達率・OI)はまだ追いついていない。</p>
  <p class="es">Los tres indicadores parecen contar historias distintas, pero en realidad pueden ser tres piezas del mismo cuadro: bitcoin cotiza ahora mismo como un activo de riesgo que apuesta por la liquidez, no como un refugio seguro, y los participantes del mercado aún no se han comprometido con esa apuesta. Mientras el oro absorbe la demanda de refugio, bitcoin está cediendo ese papel, y el apetito de riesgo (Miedo y Codicia) y el apalancamiento (tasa de financiación, OI) que deberían llenar ese hueco todavía no le han seguido el ritmo.</p>
  <p class="de">Die drei Indikatoren scheinen unterschiedliche Geschichten zu erzählen, könnten aber tatsächlich drei Teile desselben Bildes sein — Bitcoin wird derzeit als Risikoanlage gehandelt, die auf Liquidität setzt, nicht als sicherer Hafen, und Marktteilnehmer haben sich dieser Wette noch nicht verschrieben. Während Gold die Safe-Haven-Nachfrage aufsaugt, räumt Bitcoin diese Rolle, und die Risikobereitschaft (Fear & Greed) sowie der Hebel (Finanzierungsrate, OI), die diese Lücke füllen müssten, sind noch nicht nachgezogen.</p>
  <p class="fr">Les trois indicateurs semblent raconter des histoires différentes, mais ils pourraient en réalité être trois morceaux du même tableau — le bitcoin se négocie actuellement comme un actif à risque pariant sur la liquidité, pas comme une valeur refuge, et les acteurs du marché ne se sont pas encore engagés dans ce pari. Pendant que l'or absorbe la demande de refuge, le bitcoin cède ce rôle, et l'appétit pour le risque (Peur et Cupidité) ainsi que le levier (taux de financement, OI) censés combler cet écart n'ont pas encore suivi.</p>
  <p class="pt">Os três indicadores parecem contar histórias diferentes, mas podem ser, na verdade, três peças do mesmo quadro — o bitcoin está sendo negociado agora como um ativo de risco apostando em liquidez, não como um refúgio seguro, e os participantes do mercado ainda não se comprometeram com essa aposta. Enquanto o ouro absorve a demanda por refúgio, o bitcoin está cedendo esse papel, e o apetite por risco (Medo e Ganância) e a alavancagem (taxa de financiamento, OI) que deveriam preencher essa lacuna ainda não acompanharam.</p>
  <p class="tr">Üç gösterge farklı hikayeler anlatıyor gibi görünse de, aslında aynı resmin üç parçası olabilir — bitcoin şu anda güvenli liman değil, likiditeye bahis oynayan bir risk varlığı olarak işlem görüyor ve piyasa katılımcıları henüz bu bahse tam olarak inanmış değil. Altın güvenli liman talebini emerken bitcoin bu rolü bırakıyor ve o boşluğu doldurması gereken risk iştahı (Korku ve Açgözlülük) ile kaldıraç (fonlama oranı, OI) henüz buna yetişmedi.</p>
  <p class="vi">Ba chỉ số dường như kể những câu chuyện khác nhau, nhưng thực ra có thể là ba mảnh ghép của cùng một bức tranh — bitcoin hiện đang giao dịch như một tài sản rủi ro đặt cược vào thanh khoản, không phải nơi trú ẩn an toàn, và những người tham gia thị trường vẫn chưa thực sự tin vào canh bạc đó. Trong khi vàng hút hết nhu cầu trú ẩn an toàn, bitcoin đang nhường lại vai trò đó, còn khẩu vị rủi ro (Sợ hãi và Tham lam) và đòn bẩy (phí funding, OI) — những thứ lẽ ra phải lấp đầy khoảng trống đó — vẫn chưa bắt kịp.</p>

  <p class="ko">이 조합이 반등의 실패를 의미하지는 않는다. 오히려 심리와 레버리지가 가격을 따라잡는 국면이 온다면 반등에 힘이 더 실릴 수 있다. 관건은 순서와 속도다 — 공포탐욕지수가 '공포'를 넘어 '중립' 이상으로 올라서는지, 펀딩비가 과열권(예: 0.03% 이상)으로 튀어 오르는지, 그리고 비트코인-금 상관계수가 다시 플러스 영역으로 돌아오는지. 이 세 가지가 함께 확인되기 전까지는, 지금의 반등을 '심리적 전환'이 아니라 '매크로 재료에 대한 국지적 반응'으로 보는 게 더 정확하다.</p>
  <p class="en">This combination doesn't mean the bounce is doomed to fail. If anything, a phase where sentiment and leverage catch up to price could give the rally more fuel. The question is sequence and speed — whether the Fear & Greed Index climbs past "Fear" toward "Neutral" or higher, whether the funding rate spikes into overheated territory (say, above 0.03%), and whether the bitcoin-gold correlation swings back into positive territory. Until all three are confirmed together, it's more accurate to read the current bounce as a localized reaction to macro headlines rather than a psychological turning point.</p>
  <p class="ja">この組み合わせは反発の失敗を意味しない。むしろ心理とレバレッジが価格に追いつく局面が来れば、反発にさらに勢いがつく可能性もある。焦点は順序と速度だ——恐怖強欲指数が「恐怖」を超えて「中立」以上に上がるか、資金調達率が過熱圏(例えば0.03%超)へ跳ね上がるか、そしてビットコイン-金の相関係数が再びプラス圏に戻るか。この3つが揃って確認されるまでは、今の反発を「心理的転換」ではなく「マクロ材料への局所的反応」と見るほうが正確だ。</p>
  <p class="es">Esta combinación no significa que el rebote esté condenado a fracasar. Al contrario, una fase en la que el sentimiento y el apalancamiento alcancen al precio podría dar más combustible al repunte. La cuestión es el orden y la velocidad: si el Índice de Miedo y Codicia sube más allá de "Miedo" hacia "Neutral" o más, si la tasa de financiación se dispara a territorio de sobrecalentamiento (digamos, por encima del 0,03%), y si la correlación bitcoin-oro vuelve a territorio positivo. Hasta que se confirmen los tres juntos, es más preciso leer el repunte actual como una reacción localizada a titulares macro que como un punto de inflexión psicológico.</p>
  <p class="de">Diese Kombination bedeutet nicht, dass die Erholung zum Scheitern verurteilt ist. Im Gegenteil: Eine Phase, in der Stimmung und Hebel den Preis einholen, könnte der Rally mehr Treibstoff geben. Die Frage ist Reihenfolge und Tempo — ob der Fear-&-Greed-Index über "Angst" hinaus Richtung "Neutral" oder höher klettert, ob die Finanzierungsrate in überhitztes Terrain schießt (etwa über 0,03%) und ob die Bitcoin-Gold-Korrelation wieder ins Positive dreht. Bis alle drei gemeinsam bestätigt sind, ist es genauer, die aktuelle Erholung als lokalisierte Reaktion auf Makro-Schlagzeilen zu lesen statt als psychologischen Wendepunkt.</p>
  <p class="fr">Cette combinaison ne signifie pas que le rebond est voué à l'échec. Au contraire, une phase où le sentiment et le levier rattrapent le prix pourrait donner plus de carburant à la hausse. La question est l'ordre et la vitesse — si l'indice de Peur et de Cupidité dépasse "Peur" vers "Neutre" ou plus haut, si le taux de financement s'envole en territoire de surchauffe (disons, au-delà de 0,03%), et si la corrélation bitcoin-or revient en territoire positif. Tant que ces trois éléments ne sont pas confirmés ensemble, il est plus juste de lire le rebond actuel comme une réaction localisée aux nouvelles macro plutôt que comme un tournant psychologique.</p>
  <p class="pt">Essa combinação não significa que a recuperação esteja fadada ao fracasso. Pelo contrário, uma fase em que sentimento e alavancagem alcancem o preço poderia dar mais combustível à alta. A questão é a ordem e a velocidade — se o Índice de Medo e Ganância sobe além de "Medo" rumo a "Neutro" ou mais, se a taxa de financiamento dispara para território de superaquecimento (digamos, acima de 0,03%), e se a correlação bitcoin-ouro volta ao território positivo. Até que os três sejam confirmados juntos, é mais preciso ler a recuperação atual como uma reação localizada a manchetes macro, não como uma virada psicológica.</p>
  <p class="tr">Bu kombinasyon, yükselişin başarısızlığa mahkûm olduğu anlamına gelmiyor. Aksine, duygu durumu ve kaldıracın fiyata yetiştiği bir aşama gelirse, yükseliş daha da güç kazanabilir. Kilit nokta sıra ve hız — Korku ve Açgözlülük Endeksi'nin "Korku"yu aşıp "Nötr" veya üzerine çıkıp çıkmayacağı, fonlama oranının aşırı ısınma bölgesine (örneğin %0,03 üzerine) sıçrayıp sıçramayacağı ve bitcoin-altın korelasyonunun yeniden pozitif bölgeye dönüp dönmeyeceği. Bu üçü birlikte doğrulanana kadar, mevcut yükselişi bir psikolojik dönüm noktası değil, makro haberlere verilen yerel bir tepki olarak okumak daha doğru.</p>
  <p class="vi">Sự kết hợp này không có nghĩa là đợt phục hồi chắc chắn thất bại. Ngược lại, nếu tâm lý và đòn bẩy bắt kịp giá, đợt tăng có thể nhận thêm động lực. Vấn đề nằm ở thứ tự và tốc độ — liệu Chỉ số Sợ hãi và Tham lam có vượt qua "Sợ hãi" để tiến lên "Trung lập" trở lên hay không, liệu phí funding có tăng vọt vào vùng quá nóng (chẳng hạn trên 0,03%) hay không, và liệu tương quan bitcoin-vàng có quay trở lại vùng dương hay không. Cho đến khi cả ba điều này được xác nhận cùng nhau, sẽ chính xác hơn nếu coi đợt phục hồi hiện tại là phản ứng cục bộ trước tin tức vĩ mô hơn là một bước ngoặt tâm lý.</p>

  <div class="box ko">🎯 <strong>지켜볼 지점:</strong> ① 공포탐욕지수가 '공포'를 넘어 '중립' 이상으로 진입하는지 ② 펀딩비가 과열권(0.03%+)으로 튀는지 ③ 비트코인-금 30일 상관계수가 다시 플러스로 돌아서는지 — 세 가지가 함께 확인돼야 이번 반등이 유동성 베팅을 넘어 심리적 전환까지 동반했다고 볼 수 있다.</div>
  <div class="box en">🎯 <strong>What to watch:</strong> ① Whether the Fear & Greed Index climbs past "Fear" into "Neutral" or higher. ② Whether the funding rate spikes into overheated territory (0.03%+). ③ Whether the bitcoin-gold 30-day correlation swings back positive. All three together would be needed to read this bounce as a psychological turn rather than just a liquidity bet.</div>
  <div class="box ja">🎯 <strong>注視点:</strong> ①恐怖強欲指数が「恐怖」を超えて「中立」以上に入るか ②資金調達率が過熱圏(0.03%以上)へ跳ねるか ③ビットコイン-金の30日相関係数が再びプラスに転じるか——この3つが揃って初めて、今回の反発が流動性への賭けを超えた心理的転換を伴ったと言える。</div>
  <div class="box es">🎯 <strong>Qué observar:</strong> ① Si el Índice de Miedo y Codicia supera "Miedo" hacia "Neutral" o más. ② Si la tasa de financiación se dispara a territorio de sobrecalentamiento (0,03%+). ③ Si la correlación bitcoin-oro a 30 días vuelve a ser positiva. Las tres juntas serían necesarias para leer este rebote como un giro psicológico y no solo una apuesta de liquidez.</div>
  <div class="box de">🎯 <strong>Worauf zu achten ist:</strong> ① Ob der Fear-&-Greed-Index über "Angst" hinaus Richtung "Neutral" oder höher steigt. ② Ob die Finanzierungsrate in überhitztes Terrain springt (0,03%+). ③ Ob die 30-Tage-Korrelation Bitcoin-Gold wieder positiv wird. Erst alle drei zusammen würden diesen Bounce als psychologische Wende statt bloße Liquiditätswette lesen lassen.</div>
  <div class="box fr">🎯 <strong>À surveiller :</strong> ① Si l'indice de Peur et de Cupidité dépasse "Peur" vers "Neutre" ou plus. ② Si le taux de financement s'envole en territoire de surchauffe (0,03%+). ③ Si la corrélation bitcoin-or sur 30 jours redevient positive. Les trois ensemble seraient nécessaires pour lire ce rebond comme un tournant psychologique plutôt qu'un simple pari sur la liquidité.</div>
  <div class="box pt">🎯 <strong>O que observar:</strong> ① Se o Índice de Medo e Ganância supera "Medo" rumo a "Neutro" ou mais. ② Se a taxa de financiamento dispara para território de superaquecimento (0,03%+). ③ Se a correlação bitcoin-ouro de 30 dias volta a ser positiva. As três juntas seriam necessárias para ler esse repique como uma virada psicológica, e não apenas uma aposta de liquidez.</div>
  <div class="box tr">🎯 <strong>İzlenecekler:</strong> ① Korku ve Açgözlülük Endeksi'nin "Korku"yu aşıp "Nötr" veya üzerine çıkıp çıkmayacağı. ② Fonlama oranının aşırı ısınma bölgesine (%0,03+) sıçrayıp sıçramayacağı. ③ Bitcoin-altın 30 günlük korelasyonunun yeniden pozitife dönüp dönmeyeceği. Bu üçünün birlikte gerçekleşmesi, bu yükselişi sadece bir likidite bahsi değil, psikolojik bir dönüş olarak okumak için gerekli olurdu.</div>
  <div class="box vi">🎯 <strong>Những điều cần theo dõi:</strong> ① Liệu Chỉ số Sợ hãi và Tham lam có vượt qua "Sợ hãi" để vào vùng "Trung lập" trở lên hay không. ② Liệu phí funding có tăng vọt vào vùng quá nóng (0,03%+) hay không. ③ Liệu tương quan 30 ngày giữa bitcoin và vàng có quay lại vùng dương hay không. Cả ba điều này cùng xảy ra mới đủ để đọc đợt phục hồi này là một bước ngoặt tâm lý chứ không chỉ là canh bạc thanh khoản.</div>

  <h2 class="ko">함께 보면 좋은 지표</h2>
  <h2 class="en">Best Combined With</h2>
  <h2 class="ja">併せて見るべき指標</h2>
  <h2 class="es">Mejor Combinado Con</h2>
  <h2 class="de">Am besten kombiniert mit</h2>
  <h2 class="fr">À Combiner Avec</h2>
  <h2 class="pt">Melhor Combinado Com</h2>
  <h2 class="tr">En İyi Şununla Birlikte Kullanılır</h2>
  <h2 class="vi">Kết Hợp Tốt Nhất Với</h2>
  <ul class="ko">
    <li><strong><a href="/blog/correlation-breakdown-gold-bitcoin">금-비트코인 상관관계 붕괴</a>:</strong> 이 디커플링을 처음 짚은 원조 분석</li>
    <li><strong><a href="/blog/dxy-bitcoin-relationship">달러 인덱스와 비트코인의 관계</a>:</strong> 이번 반등을 이끈 달러 약세 경로에 대한 배경 지식</li>
    <li><strong><a href="/blog/fear-greed-extreme-fear-duration-signal">극단적 공포 지속 기간이 갖는 신호</a>:</strong> 공포 국면이 얼마나 오래가면 신호가 되는지</li>
    <li><strong><a href="/blog/fear-greed-whiplash-btc-range-intact">공포탐욕지수 급변과 박스권 유지</a>:</strong> 심리 급변이 실제 가격 레인지에 미치는 영향</li>
    <li><strong><a href="/blog/funding-rate-futures-gap">펀딩비·선물 갭 가이드</a>:</strong> 펀딩비로 레버리지 쏠림을 읽는 기본기</li>
    <li><strong><a href="/blog/btc-correlation-guide">비트코인 상관관계 읽는 법</a>:</strong> 다른 자산과의 관계를 해석하는 기초</li>
  </ul>
  <ul class="en">
    <li><strong><a href="/en/blog/correlation-breakdown-gold-bitcoin">Gold-Bitcoin Correlation Breakdown</a>:</strong> The original analysis that first flagged this decoupling</li>
    <li><strong><a href="/en/blog/dxy-bitcoin-relationship">The Dollar Index and Bitcoin's Relationship</a>:</strong> Background on the weak-dollar pathway driving this bounce</li>
    <li><strong><a href="/en/blog/fear-greed-extreme-fear-duration-signal">What Extreme Fear's Duration Signals</a>:</strong> How long a fear phase has to run before it becomes a signal</li>
    <li><strong><a href="/en/blog/fear-greed-whiplash-btc-range-intact">Fear & Greed Whiplash, Range Still Intact</a>:</strong> How sudden sentiment swings actually feed through to price ranges</li>
    <li><strong><a href="/en/blog/funding-rate-futures-gap">Funding Rate & Futures Gap Guide</a>:</strong> The basics of reading leverage crowding from funding rates</li>
    <li><strong><a href="/en/blog/btc-correlation-guide">How to Read Bitcoin's Correlations</a>:</strong> The fundamentals of interpreting bitcoin's relationship with other assets</li>
  </ul>
  <ul class="ja">
    <li><strong><a href="/ja/blog/correlation-breakdown-gold-bitcoin">金-ビットコイン相関関係の崩壊</a>:</strong> このデカップリングを最初に指摘した元祖分析</li>
    <li><strong><a href="/ja/blog/dxy-bitcoin-relationship">ドルインデックスとビットコインの関係</a>:</strong> 今回の反発を導いたドル安経路の背景知識</li>
    <li><strong><a href="/ja/blog/fear-greed-extreme-fear-duration-signal">極端な恐怖の持続期間が持つシグナル</a>:</strong> 恐怖局面がどれだけ続けばシグナルになるか</li>
    <li><strong><a href="/ja/blog/fear-greed-whiplash-btc-range-intact">恐怖強欲指数の急変とレンジ維持</a>:</strong> 心理急変が実際の価格レンジに与える影響</li>
    <li><strong><a href="/ja/blog/funding-rate-futures-gap">資金調達率・先物ギャップガイド</a>:</strong> 資金調達率でレバレッジの偏りを読む基本</li>
    <li><strong><a href="/ja/blog/btc-correlation-guide">ビットコインの相関関係の読み方</a>:</strong> 他資産との関係を解釈する基礎</li>
  </ul>
  <ul class="es">
    <li><strong><a href="/es/blog/correlation-breakdown-gold-bitcoin">Ruptura de la Correlación Oro-Bitcoin</a>:</strong> El análisis original que señaló primero este desacoplamiento</li>
    <li><strong><a href="/es/blog/dxy-bitcoin-relationship">La Relación entre el Índice Dólar y Bitcoin</a>:</strong> Contexto sobre la vía de dólar débil que impulsa este rebote</li>
    <li><strong><a href="/es/blog/fear-greed-extreme-fear-duration-signal">Lo Que Señala la Duración del Miedo Extremo</a>:</strong> Cuánto debe durar una fase de miedo para convertirse en señal</li>
    <li><strong><a href="/es/blog/fear-greed-whiplash-btc-range-intact">Vaivén del Miedo y Codicia, el Rango Sigue Intacto</a>:</strong> Cómo los giros bruscos de sentimiento repercuten en los rangos de precio</li>
    <li><strong><a href="/es/blog/funding-rate-futures-gap">Guía de Tasa de Financiación y Brecha de Futuros</a>:</strong> Lo básico para leer el apalancamiento a través de la tasa de financiación</li>
    <li><strong><a href="/es/blog/btc-correlation-guide">Cómo Leer las Correlaciones de Bitcoin</a>:</strong> Fundamentos para interpretar la relación de bitcoin con otros activos</li>
  </ul>
  <ul class="de">
    <li><strong><a href="/de/blog/correlation-breakdown-gold-bitcoin">Der Zusammenbruch der Gold-Bitcoin-Korrelation</a>:</strong> Die ursprüngliche Analyse, die diese Entkopplung erstmals aufzeigte</li>
    <li><strong><a href="/de/blog/dxy-bitcoin-relationship">Die Beziehung zwischen Dollarindex und Bitcoin</a>:</strong> Hintergrund zum schwachen Dollar als Treiber dieser Erholung</li>
    <li><strong><a href="/de/blog/fear-greed-extreme-fear-duration-signal">Was die Dauer Extremer Angst Signalisiert</a>:</strong> Wie lange eine Angstphase anhalten muss, um zum Signal zu werden</li>
    <li><strong><a href="/de/blog/fear-greed-whiplash-btc-range-intact">Fear-&-Greed-Peitscheneffekt, Range Bleibt Intakt</a>:</strong> Wie plötzliche Stimmungsschwankungen tatsächlich auf Preisspannen durchschlagen</li>
    <li><strong><a href="/de/blog/funding-rate-futures-gap">Finanzierungsrate & Futures-Gap-Leitfaden</a>:</strong> Die Grundlagen, um Hebel-Crowding aus Finanzierungsraten zu lesen</li>
    <li><strong><a href="/de/blog/btc-correlation-guide">Wie Man Bitcoins Korrelationen Liest</a>:</strong> Die Grundlagen zur Interpretation von Bitcoins Beziehung zu anderen Assets</li>
  </ul>
  <ul class="fr">
    <li><strong><a href="/fr/blog/correlation-breakdown-gold-bitcoin">L'Effondrement de la Corrélation Or-Bitcoin</a>:</strong> L'analyse originale qui a signalé la première ce découplage</li>
    <li><strong><a href="/fr/blog/dxy-bitcoin-relationship">La Relation entre l'Indice Dollar et le Bitcoin</a>:</strong> Contexte sur la voie du dollar faible qui alimente ce rebond</li>
    <li><strong><a href="/fr/blog/fear-greed-extreme-fear-duration-signal">Ce Que Signale la Durée de la Peur Extrême</a>:</strong> Combien de temps une phase de peur doit-elle durer pour devenir un signal</li>
    <li><strong><a href="/fr/blog/fear-greed-whiplash-btc-range-intact">Coup de Fouet de Peur et Cupidité, le Range Tient Toujours</a>:</strong> Comment les revirements soudains de sentiment se répercutent réellement sur les fourchettes de prix</li>
    <li><strong><a href="/fr/blog/funding-rate-futures-gap">Guide du Taux de Financement et de l'Écart Futures</a>:</strong> Les bases pour lire l'encombrement du levier via le taux de financement</li>
    <li><strong><a href="/fr/blog/btc-correlation-guide">Comment Lire les Corrélations du Bitcoin</a>:</strong> Les fondamentaux pour interpréter la relation du bitcoin avec d'autres actifs</li>
  </ul>
  <ul class="pt">
    <li><strong><a href="/pt/blog/correlation-breakdown-gold-bitcoin">O Colapso da Correlação Ouro-Bitcoin</a>:</strong> A análise original que apontou primeiro esse desacoplamento</li>
    <li><strong><a href="/pt/blog/dxy-bitcoin-relationship">A Relação entre o Índice do Dólar e o Bitcoin</a>:</strong> Contexto sobre a via do dólar fraco que impulsiona essa recuperação</li>
    <li><strong><a href="/pt/blog/fear-greed-extreme-fear-duration-signal">O Que a Duração do Medo Extremo Sinaliza</a>:</strong> Quanto tempo uma fase de medo precisa durar para virar sinal</li>
    <li><strong><a href="/pt/blog/fear-greed-whiplash-btc-range-intact">Chicote de Medo e Ganância, o Range Segue Intacto</a>:</strong> Como oscilações súbitas de sentimento realmente afetam as faixas de preço</li>
    <li><strong><a href="/pt/blog/funding-rate-futures-gap">Guia de Taxa de Financiamento e Gap de Futuros</a>:</strong> O básico para ler o acúmulo de alavancagem pela taxa de financiamento</li>
    <li><strong><a href="/pt/blog/btc-correlation-guide">Como Ler as Correlações do Bitcoin</a>:</strong> Os fundamentos para interpretar a relação do bitcoin com outros ativos</li>
  </ul>
  <ul class="tr">
    <li><strong><a href="/tr/blog/correlation-breakdown-gold-bitcoin">Altın-Bitcoin Korelasyonunun Çöküşü</a>:</strong> Bu kopuşu ilk işaret eden orijinal analiz</li>
    <li><strong><a href="/tr/blog/dxy-bitcoin-relationship">Dolar Endeksi ve Bitcoin İlişkisi</a>:</strong> Bu yükselişi tetikleyen zayıf dolar yolu hakkında arka plan bilgisi</li>
    <li><strong><a href="/tr/blog/fear-greed-extreme-fear-duration-signal">Aşırı Korkunun Süresi Ne Anlatıyor</a>:</strong> Bir korku evresinin sinyale dönüşmesi için ne kadar sürmesi gerektiği</li>
    <li><strong><a href="/tr/blog/fear-greed-whiplash-btc-range-intact">Korku ve Açgözlülükte Ani Dönüş, Aralık Hâlâ Sağlam</a>:</strong> Ani duygu durumu değişimlerinin fiyat aralıklarına gerçekte nasıl yansıdığı</li>
    <li><strong><a href="/tr/blog/funding-rate-futures-gap">Fonlama Oranı ve Vadeli İşlem Farkı Rehberi</a>:</strong> Fonlama oranından kaldıraç yığılmasını okumanın temelleri</li>
    <li><strong><a href="/tr/blog/btc-correlation-guide">Bitcoin Korelasyonları Nasıl Okunur</a>:</strong> Bitcoin'in diğer varlıklarla ilişkisini yorumlamanın temelleri</li>
  </ul>
  <ul class="vi">
    <li><strong><a href="/vi/blog/correlation-breakdown-gold-bitcoin">Sự Sụp Đổ Của Tương Quan Vàng-Bitcoin</a>:</strong> Phân tích gốc đầu tiên chỉ ra sự tách rời này</li>
    <li><strong><a href="/vi/blog/dxy-bitcoin-relationship">Mối Quan Hệ Giữa Chỉ Số Đô La và Bitcoin</a>:</strong> Kiến thức nền về con đường đồng đô la yếu dẫn dắt đợt phục hồi này</li>
    <li><strong><a href="/vi/blog/fear-greed-extreme-fear-duration-signal">Thời Gian Sợ Hãi Cực Độ Báo Hiệu Điều Gì</a>:</strong> Một giai đoạn sợ hãi cần kéo dài bao lâu để trở thành tín hiệu</li>
    <li><strong><a href="/vi/blog/fear-greed-whiplash-btc-range-intact">Sợ Hãi và Tham Lam Đảo Chiều Đột Ngột, Vùng Giá Vẫn Nguyên Vẹn</a>:</strong> Những biến động tâm lý đột ngột thực sự ảnh hưởng thế nào đến vùng giá</li>
    <li><strong><a href="/vi/blog/funding-rate-futures-gap">Hướng Dẫn Phí Funding và Khoảng Cách Hợp Đồng Tương Lai</a>:</strong> Kiến thức cơ bản để đọc sự tích tụ đòn bẩy từ phí funding</li>
    <li><strong><a href="/vi/blog/btc-correlation-guide">Cách Đọc Các Tương Quan Của Bitcoin</a>:</strong> Kiến thức nền tảng để diễn giải mối quan hệ của bitcoin với các tài sản khác</li>
  </ul>

  <p class="ko" style="font-size:.85rem;color:#71717a">출처: CoinGlass·크립토뉴스넷·크립토노미스트(비트코인 가격·이동평균), 코인스탯츠 AI(펀딩비·OI 7월 7일 집계), 코인얼라이즈(OI 대체 집계), 얼터너티브미·밀크로드·코인마켓캡·비트디그리·더모틀리풀(크립토 공포탐욕지수), 옐로우닷컴·크립토뉴스넷(비트코인-금 상관계수), 세계금협회(WGC, 중앙은행 금 순매수·금 가격), JP모건·반에크 계열 분석(유동성-비트코인 관계 해석), BTCtiming.com 자체 분석. 수치는 인용 시점 기준이며 트래커별 집계 방법론 차이로 절대값은 다를 수 있다. 본 글은 투자 조언이 아니다.</p>
  <p class="en" style="font-size:.85rem;color:#71717a">Sources: CoinGlass, CryptoNews.net & Cryptonomist (bitcoin price, moving averages), CoinStats AI (funding rate & OI, July 7 read), Coinalyze (alternate OI figures), Alternative.me, Milkroad, CoinMarketCap, BitDegree & The Motley Fool (crypto Fear & Greed Index), Yellow.com & CryptoNews.net (bitcoin-gold correlation), World Gold Council (central bank gold buying, gold price), analysis in the vein of JPMorgan & VanEck (liquidity-bitcoin relationship), BTCtiming.com's own analysis. Figures are as of the time cited and absolute values may differ by tracker methodology. This is not investment advice.</p>
  <p class="ja" style="font-size:.85rem;color:#71717a">出典: CoinGlass・クリプトニュースネット・クリプトノミスト(ビットコイン価格・移動平均)、コインスタッツAI(資金調達率・OI 7月7日集計)、コインアライズ(OI代替集計)、オルタナティブミー・ミルクロード・コインマーケットキャップ・ビットディグリー・ザ・モトリーフール(クリプト恐怖強欲指数)、イエロー・ドット・コム・クリプトニュースネット(ビットコイン-金相関係数)、世界金協会(WGC、中央銀行金純購入・金価格)、JPモルガン・ヴァンエック系分析(流動性-ビットコイン関係の解釈)、BTCtiming.com自社分析。数値は引用時点のものであり、集計方法の違いによりトラッカーごとに絶対値は異なる場合がある。本記事は投資助言ではない。</p>
  <p class="es" style="font-size:.85rem;color:#71717a">Fuentes: CoinGlass, CryptoNews.net y Cryptonomist (precio de bitcoin, medias móviles), CoinStats AI (tasa de financiación y OI, lectura del 7 de julio), Coinalyze (cifras alternativas de OI), Alternative.me, Milkroad, CoinMarketCap, BitDegree y The Motley Fool (Índice de Miedo y Codicia cripto), Yellow.com y CryptoNews.net (correlación bitcoin-oro), Consejo Mundial del Oro (compras de oro de bancos centrales, precio del oro), análisis en la línea de JPMorgan y VanEck (interpretación de la relación liquidez-bitcoin), análisis propio de BTCtiming.com. Las cifras son de la fecha citada y los valores absolutos pueden diferir según la metodología del rastreador. Esto no es asesoramiento de inversión.</p>
  <p class="de" style="font-size:.85rem;color:#71717a">Quellen: CoinGlass, CryptoNews.net und Cryptonomist (Bitcoin-Preis, gleitende Durchschnitte), CoinStats AI (Finanzierungsrate & OI, Stand 7. Juli), Coinalyze (alternative OI-Zahlen), Alternative.me, Milkroad, CoinMarketCap, BitDegree und The Motley Fool (Krypto-Fear-&-Greed-Index), Yellow.com und CryptoNews.net (Bitcoin-Gold-Korrelation), World Gold Council (Zentralbank-Goldkäufe, Goldpreis), Analysen im Stil von JPMorgan & VanEck (Interpretation der Liquiditäts-Bitcoin-Beziehung), BTCtiming.coms eigene Analyse. Zahlen beziehen sich auf den zitierten Zeitpunkt; absolute Werte können je nach Tracker-Methodik abweichen. Dies ist keine Anlageberatung.</p>
  <p class="fr" style="font-size:.85rem;color:#71717a">Sources : CoinGlass, CryptoNews.net et Cryptonomist (prix du bitcoin, moyennes mobiles), CoinStats AI (taux de financement et OI, relevé du 7 juillet), Coinalyze (chiffres alternatifs d'OI), Alternative.me, Milkroad, CoinMarketCap, BitDegree et The Motley Fool (indice crypto de Peur et de Cupidité), Yellow.com et CryptoNews.net (corrélation bitcoin-or), World Gold Council (achats d'or des banques centrales, prix de l'or), analyses dans la lignée de JPMorgan et VanEck (interprétation de la relation liquidité-bitcoin), analyse propre de BTCtiming.com. Les chiffres sont datés de leur citation et les valeurs absolues peuvent varier selon la méthodologie du tracker. Ceci n'est pas un conseil en investissement.</p>
  <p class="pt" style="font-size:.85rem;color:#71717a">Fontes: CoinGlass, CryptoNews.net e Cryptonomist (preço do bitcoin, médias móveis), CoinStats AI (taxa de financiamento e OI, leitura de 7 de julho), Coinalyze (números alternativos de OI), Alternative.me, Milkroad, CoinMarketCap, BitDegree e The Motley Fool (Índice de Medo e Ganância cripto), Yellow.com e CryptoNews.net (correlação bitcoin-ouro), World Gold Council (compras de ouro por bancos centrais, preço do ouro), análises na linha do JPMorgan e da VanEck (interpretação da relação liquidez-bitcoin), análise própria da BTCtiming.com. Os números são referentes à data citada e os valores absolutos podem diferir conforme a metodologia do rastreador. Isto não é aconselhamento de investimento.</p>
  <p class="tr" style="font-size:.85rem;color:#71717a">Kaynaklar: CoinGlass, CryptoNews.net ve Cryptonomist (bitcoin fiyatı, hareketli ortalamalar), CoinStats AI (fonlama oranı ve OI, 7 Temmuz verisi), Coinalyze (alternatif OI rakamları), Alternative.me, Milkroad, CoinMarketCap, BitDegree ve The Motley Fool (kripto Korku ve Açgözlülük Endeksi), Yellow.com ve CryptoNews.net (bitcoin-altın korelasyonu), Dünya Altın Konseyi (merkez bankası altın alımları, altın fiyatı), JPMorgan ve VanEck tarzı analizler (likidite-bitcoin ilişkisinin yorumu), BTCtiming.com'un kendi analizi. Rakamlar alıntı tarihine aittir ve mutlak değerler izleyici metodolojisine göre farklılık gösterebilir. Bu yatırım tavsiyesi değildir.</p>
  <p class="vi" style="font-size:.85rem;color:#71717a">Nguồn: CoinGlass, CryptoNews.net và Cryptonomist (giá bitcoin, các đường trung bình động), CoinStats AI (phí funding và OI, số liệu ngày 7 tháng 7), Coinalyze (số liệu OI thay thế), Alternative.me, Milkroad, CoinMarketCap, BitDegree và The Motley Fool (Chỉ số Sợ hãi và Tham lam tiền điện tử), Yellow.com và CryptoNews.net (tương quan bitcoin-vàng), Hội đồng Vàng Thế giới (mua vàng của ngân hàng trung ương, giá vàng), các phân tích theo hướng của JPMorgan và VanEck (diễn giải mối quan hệ thanh khoản-bitcoin), phân tích riêng của BTCtiming.com. Các con số tính theo thời điểm được trích dẫn và giá trị tuyệt đối có thể khác nhau tùy phương pháp của từng nguồn theo dõi. Đây không phải là lời khuyên đầu tư.</p>

<?php require __DIR__.'/_footer.php'; ?>
