<?php $slug = 'citadel-securities-crypto-com-400m-investment'; require __DIR__.'/_header.php'; ?>

<p class="ko">월가 최대 규모의 마켓메이커로 꼽히는 시타델 증권(Citadel Securities)이 크립토 거래소 크립토닷컴(Crypto.com)에 4억달러를 투자했다고 로이터·코인데스크가 7월16일 보도했다. 이번 투자로 크립토닷컴의 밸류에이션은 200억달러로 확정됐다. 크립토닷컴 공동창업자 겸 CEO 크리스 마르잘렉은 "시타델 증권과 함께 크립토 업계를 기관화의 새 시대로 밀어붙이게 되어 기쁘다"고 밝혔다. 이번 거래는 시타델이 지난해 2월 블룸버그 보도를 통해 알려진 코인베이스·바이낸스·크립토닷컴 대상 마켓메이킹 서비스 진출 계획을, 서비스 제공을 넘어 실제 지분 투자로 구체화한 첫 사례라는 점에서 주목받고 있다.</p>
<p class="en">Citadel Securities, widely regarded as Wall Street's largest market maker, invested $400 million in crypto exchange Crypto.com, Reuters and CoinDesk reported July 16. The investment confirmed a $20 billion valuation for Crypto.com. Co-founder and CEO Kris Marszalek said he was "excited to work with Citadel Securities to push the crypto sector toward a new era of institutionalization." The deal stands out because it turns plans first reported by Bloomberg in February 2025 - for Citadel to provide market-making services to Coinbase, Binance and Crypto.com - into something more concrete than a vendor relationship: an actual equity stake.</p>
<p class="ja">ウォール街最大のマーケットメイカーとされるシタデル証券(Citadel Securities)が、暗号資産取引所クリプトドットコム(Crypto.com)に4億ドルを投資したと、ロイターとコインデスクが7月16日に報じた。この投資によりクリプトドットコムの評価額は200億ドルで確定した。共同創業者兼CEOのクリス・マルザレク氏は「シタデル証券とともに、暗号資産業界を機関化の新時代へと押し進めることができて嬉しい」と述べた。今回の取引は、2025年2月にブルームバーグが報じたコインベース・バイナンス・クリプトドットコム向けマーケットメイキングサービス進出計画を、単なるサービス提供関係を超えて実際の株式投資として具体化した初の事例である点が注目される。</p>
<p class="es">Citadel Securities, ampliamente considerado el mayor creador de mercado de Wall Street, invirtió 400 millones de dólares en el exchange de criptomonedas Crypto.com, informaron Reuters y CoinDesk el 16 de julio. La inversión confirmó una valoración de 20.000 millones de dólares para Crypto.com. El cofundador y CEO Kris Marszalek dijo que estaba "encantado de trabajar con Citadel Securities para impulsar al sector cripto hacia una nueva era de institucionalización". El acuerdo destaca porque convierte en algo más concreto que una relación de proveedor los planes reportados por primera vez por Bloomberg en febrero de 2025, según los cuales Citadel ofrecería servicios de creación de mercado a Coinbase, Binance y Crypto.com: ahora se trata de una participación accionaria real.</p>
<p class="de">Citadel Securities, weithin als größter Market Maker der Wall Street angesehen, hat 400 Millionen Dollar in die Krypto-Börse Crypto.com investiert, wie Reuters und CoinDesk am 16. Juli berichteten. Die Investition bestätigte eine Bewertung von Crypto.com in Höhe von 20 Milliarden Dollar. Mitgründer und CEO Kris Marszalek sagte, er freue sich, „gemeinsam mit Citadel Securities den Kryptosektor in eine neue Ära der Institutionalisierung zu treiben." Der Deal sticht hervor, weil er die im Februar 2025 von Bloomberg erstmals gemeldeten Pläne - wonach Citadel Market-Making-Dienste für Coinbase, Binance und Crypto.com anbieten wollte - über eine reine Dienstleisterbeziehung hinaus zu etwas Konkreterem macht: einer tatsächlichen Kapitalbeteiligung.</p>
<p class="fr">Citadel Securities, largement considéré comme le plus grand teneur de marché de Wall Street, a investi 400 millions de dollars dans la plateforme d'échange de cryptomonnaies Crypto.com, ont rapporté Reuters et CoinDesk le 16 juillet. Cet investissement confirme une valorisation de 20 milliards de dollars pour Crypto.com. Le cofondateur et PDG Kris Marszalek a déclaré être « ravi de travailler avec Citadel Securities pour propulser le secteur crypto vers une nouvelle ère d'institutionnalisation ». L'accord se démarque car il transforme en quelque chose de plus concret qu'une simple relation de prestataire les plans rapportés pour la première fois par Bloomberg en février 2025 - selon lesquels Citadel fournirait des services de tenue de marché à Coinbase, Binance et Crypto.com - à savoir une véritable participation au capital.</p>
<p class="pt">A Citadel Securities, amplamente considerada a maior formadora de mercado de Wall Street, investiu US$ 400 milhões na exchange de criptomoedas Crypto.com, informaram Reuters e CoinDesk em 16 de julho. O investimento confirmou uma avaliação de US$ 20 bilhões para a Crypto.com. O cofundador e CEO Kris Marszalek disse estar "animado em trabalhar com a Citadel Securities para impulsionar o setor cripto rumo a uma nova era de institucionalização". O acordo se destaca por transformar em algo mais concreto que uma relação de fornecedor os planos noticiados pela primeira vez pela Bloomberg em fevereiro de 2025 - segundo os quais a Citadel forneceria serviços de formação de mercado à Coinbase, Binance e Crypto.com - agora uma participação acionária real.</p>
<p class="tr">Wall Street'in en büyük piyasa yapıcısı olarak kabul edilen Citadel Securities, kripto para borsası Crypto.com'a 400 milyon dolar yatırım yaptı; bu gelişme Reuters ve CoinDesk tarafından 16 Temmuz'da bildirildi. Yatırım, Crypto.com'un değerlemesini 20 milyar dolar olarak onayladı. Kurucu ortak ve CEO Kris Marszalek, "Citadel Securities ile birlikte kripto sektörünü kurumsallaşmanın yeni bir çağına taşımaktan heyecan duyduğunu" söyledi. Anlaşma, Bloomberg'in Şubat 2025'te ilk kez haberleştirdiği - Citadel'in Coinbase, Binance ve Crypto.com'a piyasa yapıcılığı hizmeti sunma planlarını - salt bir tedarikçi ilişkisinin ötesine taşıyarak gerçek bir hisse yatırımına dönüştürmesiyle dikkat çekiyor.</p>
<p class="vi">Citadel Securities, được xem là nhà tạo lập thị trường lớn nhất Phố Wall, đã đầu tư 400 triệu đô la vào sàn giao dịch tiền mã hóa Crypto.com, theo Reuters và CoinDesk đưa tin ngày 16/7. Khoản đầu tư này xác nhận mức định giá 20 tỷ đô la cho Crypto.com. Đồng sáng lập kiêm CEO Kris Marszalek cho biết ông "hào hứng khi hợp tác với Citadel Securities để đẩy ngành công nghiệp tiền mã hóa tiến vào một kỷ nguyên thể chế hóa mới." Thương vụ này nổi bật vì đã biến kế hoạch được Bloomberg đưa tin lần đầu vào tháng 2/2025 - rằng Citadel sẽ cung cấp dịch vụ tạo lập thị trường cho Coinbase, Binance và Crypto.com - thành thứ gì đó cụ thể hơn một quan hệ nhà cung cấp thông thường: một khoản đầu tư cổ phần thực sự.</p>
<p class="id">Citadel Securities, yang secara luas dianggap sebagai pembuat pasar terbesar di Wall Street, menginvestasikan 400 juta dolar AS ke bursa kripto Crypto.com, menurut laporan Reuters dan CoinDesk pada 16 Juli. Investasi ini mengonfirmasi valuasi sebesar 20 miliar dolar AS untuk Crypto.com. Co-founder sekaligus CEO Kris Marszalek mengatakan ia "senang bisa bekerja sama dengan Citadel Securities untuk mendorong sektor kripto menuju era baru institusionalisasi." Kesepakatan ini menonjol karena mengubah rencana yang pertama kali dilaporkan Bloomberg pada Februari 2025 - bahwa Citadel akan menyediakan layanan market-making untuk Coinbase, Binance, dan Crypto.com - menjadi sesuatu yang lebih konkret daripada sekadar hubungan vendor: sebuah kepemilikan saham yang nyata.</p>
<p class="pl">Citadel Securities, powszechnie uznawany za największego animatora rynku na Wall Street, zainwestował 400 milionów dolarów w giełdę kryptowalut Crypto.com - poinformowały Reuters i CoinDesk 16 lipca. Inwestycja potwierdziła wycenę Crypto.com na poziomie 20 miliardów dolarów. Współzałożyciel i dyrektor generalny Kris Marszalek powiedział, że jest „podekscytowany współpracą z Citadel Securities, by pchnąć sektor kryptowalut w stronę nowej ery instytucjonalizacji”. Transakcja wyróżnia się tym, że zamienia plany po raz pierwszy ujawnione przez Bloomberg w lutym 2025 roku - zgodnie z którymi Citadel miał świadczyć usługi animowania rynku dla Coinbase, Binance i Crypto.com - w coś bardziej konkretnego niż relacja z dostawcą usług: rzeczywisty udział kapitałowy.</p>
<p class="it">Citadel Securities, ampiamente considerata il più grande market maker di Wall Street, ha investito 400 milioni di dollari nell'exchange di criptovalute Crypto.com, secondo quanto riportato da Reuters e CoinDesk il 16 luglio. L'investimento ha confermato una valutazione di 20 miliardi di dollari per Crypto.com. Il co-fondatore e CEO Kris Marszalek ha dichiarato di essere «entusiasta di collaborare con Citadel Securities per spingere il settore cripto verso una nuova era di istituzionalizzazione». L'accordo si distingue perché trasforma i piani riportati per la prima volta da Bloomberg nel febbraio 2025 - secondo cui Citadel avrebbe fornito servizi di market making a Coinbase, Binance e Crypto.com - in qualcosa di più concreto di un semplice rapporto con un fornitore: una vera e propria partecipazione azionaria.</p>
<p class="ru">Citadel Securities, широко считающаяся крупнейшим маркет-мейкером Уолл-стрит, инвестировала 400 миллионов долларов в криптобиржу Crypto.com, сообщили Reuters и CoinDesk 16 июля. Инвестиция подтвердила оценку Crypto.com в 20 миллиардов долларов. Сооснователь и генеральный директор Крис Маршалек заявил, что рад «работать с Citadel Securities, чтобы подтолкнуть криптоотрасль к новой эре институционализации». Сделка выделяется тем, что превращает планы, впервые раскрытые Bloomberg в феврале 2025 года, - по которым Citadel должна была предоставлять услуги маркет-мейкинга для Coinbase, Binance и Crypto.com, - из простых отношений с поставщиком услуг в нечто более конкретное: реальную долю в капитале.</p>
<p class="zh">據路透社與CoinDesk於7月16日報導,被廣泛視為華爾街最大做市商的Citadel Securities向加密貨幣交易所Crypto.com投資4億美元。該投資確認了Crypto.com 200億美元的估值。共同創辦人兼執行長克里斯·馬扎萊克(Kris Marszalek)表示,他「很高興能與Citadel Securities合作,推動加密產業邁向機構化的新時代」。這筆交易之所以引人注目,是因為它將彭博社於2025年2月首次報導的計畫——即Citadel將為Coinbase、Binance與Crypto.com提供做市服務——轉化為比單純供應商關係更具體的東西:一筆真正的股權投資。</p>

<h2 class="ko">서비스 검토에서 지분 투자로 — 시타델 크립토 전략의 전환점</h2>
<h2 class="en">From Exploring Services to Taking Equity - A Turning Point in Citadel's Crypto Strategy</h2>
<h2 class="ja">サービス検討から株式投資へ — シタデルの暗号資産戦略の転換点</h2>
<h2 class="es">De explorar servicios a tomar participación — un punto de inflexión en la estrategia cripto de Citadel</h2>
<h2 class="de">Von der Prüfung von Dienstleistungen zur Beteiligung — ein Wendepunkt in Citadels Kryptostrategie</h2>
<h2 class="fr">D'une exploration de services à une prise de participation — un tournant dans la stratégie crypto de Citadel</h2>
<h2 class="pt">De explorar serviços a tomar participação — um ponto de virada na estratégia cripto da Citadel</h2>
<h2 class="tr">Hizmet Değerlendirmesinden Hisse Yatırımına — Citadel'in Kripto Stratejisinde Dönüm Noktası</h2>
<h2 class="vi">Từ Cân Nhắc Dịch Vụ Đến Đầu Tư Cổ Phần — Bước Ngoặt Trong Chiến Lược Crypto Của Citadel</h2>
<h2 class="id">Dari Eksplorasi Layanan ke Kepemilikan Saham - Titik Balik dalam Strategi Kripto Citadel</h2>
<h2 class="pl">Od badania usług do objęcia udziałów - punkt zwrotny w strategii kryptowalutowej Citadel</h2>
<h2 class="it">Dall'esplorazione dei servizi alla partecipazione azionaria - Un punto di svolta nella strategia crypto di Citadel</h2>
<h2 class="ru">От изучения услуг к покупке доли - поворотный момент в криптостратегии Citadel</h2>
<h2 class="zh">從評估服務到持股——Citadel加密貨幣策略的轉捩點</h2>

<p class="ko">2025년 2월 블룸버그는 익명의 소식통을 인용해 시타델 증권이 코인베이스·바이낸스·크립토닷컴 등 주요 크립토 거래소에 유동성을 공급하는 마켓메이킹 사업을 검토하고 있다고 보도했다. 당시 보도에 따르면 시타델은 이 신사업을 미국 규제 밖에 두기 위해 역외 팀을 꾸리고 있었으며, 이는 도널드 트럼프 행정부의 친크립토 규제 기조 전환에 대한 반응으로 해석됐다. 시타델은 기관간 크립토 거래 플랫폼 EDX마켓츠에 지분을 보유하는 등 업계 주변부에는 발을 걸쳐왔지만, 정작 핵심 사업인 마켓메이킹 자체를 크립토에 들여오는 데는 그동안 신중한 태도를 유지해왔다. 17개월이 지난 지금, 4억달러 규모의 실제 지분 투자가 성사되며 '검토 중'이라는 수사가 처음으로 자본 집행이라는 구체적 실행으로 옮겨간 것이다.</p>
<p class="en">In February 2025, Bloomberg reported, citing anonymous sources, that Citadel Securities was exploring a market-making business that would supply liquidity to major crypto exchanges including Coinbase, Binance and Crypto.com. According to that report, Citadel was setting up offshore teams to keep the new line outside U.S. regulatory reach, a move read as a response to the Trump administration's shift toward friendlier crypto rules. Citadel had touched the industry's edges before - holding a stake in the institutional crypto trading venue EDX Markets - but had remained cautious about bringing its core market-making business into crypto itself. Seventeen months later, the $400 million equity investment turns that "exploring" rhetoric into concrete capital deployment for the first time.</p>
<p class="ja">2025年2月、ブルームバーグは匿名の情報筋を引用し、シタデル証券がコインベース・バイナンス・クリプトドットコムなど主要暗号資産取引所に流動性を供給するマーケットメイキング事業を検討していると報じた。当時の報道によれば、シタデルはこの新規事業を米国の規制の外に置くため域外チームを編成しており、これはドナルド・トランプ政権の親暗号資産的な規制姿勢への転換への反応と解釈された。シタデルは機関間暗号資産取引プラットフォームであるEDXマーケッツに出資するなど業界の周辺には関わってきたが、中核事業であるマーケットメイキング自体を暗号資産に持ち込むことにはこれまで慎重な姿勢を保ってきた。17カ月が経過した今、4億ドル規模の実際の株式投資が成立し、「検討中」という言葉が初めて具体的な資本執行へと移行したことになる。</p>
<p class="es">En febrero de 2025, Bloomberg informó, citando fuentes anónimas, que Citadel Securities estaba explorando un negocio de creación de mercado que suministraría liquidez a los principales exchanges de criptomonedas, incluidos Coinbase, Binance y Crypto.com. Según ese reporte, Citadel estaba organizando equipos offshore para mantener esta nueva línea fuera del alcance regulatorio estadounidense, un movimiento interpretado como respuesta al giro de la administración Trump hacia normas más favorables para el sector cripto. Citadel ya había rozado los márgenes de la industria —posee una participación en la plataforma de trading institucional EDX Markets— pero se había mantenido cauteloso respecto a traer su negocio central de creación de mercado directamente al mundo cripto. Diecisiete meses después, la inversión accionaria de 400 millones de dólares convierte por primera vez esa retórica de "exploración" en un despliegue de capital concreto.</p>
<p class="de">Im Februar 2025 berichtete Bloomberg unter Berufung auf anonyme Quellen, Citadel Securities prüfe ein Market-Making-Geschäft, das großen Krypto-Börsen wie Coinbase, Binance und Crypto.com Liquidität zuführen würde. Laut jenem Bericht baute Citadel Offshore-Teams auf, um die neue Sparte außerhalb der US-Regulierung zu halten - ein Schritt, der als Reaktion auf den Kurswechsel der Trump-Regierung hin zu kryptofreundlicheren Regeln gedeutet wurde. Citadel hatte die Ränder der Branche zuvor schon berührt, etwa mit einer Beteiligung an der institutionellen Krypto-Handelsplattform EDX Markets, war aber vorsichtig geblieben, sein Kerngeschäft Market Making direkt in den Kryptobereich zu bringen. Siebzehn Monate später verwandelt die 400-Millionen-Dollar-Kapitalbeteiligung diese "Prüfungs"-Rhetorik erstmals in einen konkreten Kapitaleinsatz.</p>
<p class="fr">En février 2025, Bloomberg a rapporté, citant des sources anonymes, que Citadel Securities explorait une activité de tenue de marché qui fournirait de la liquidité aux grandes plateformes crypto, dont Coinbase, Binance et Crypto.com. Selon ce rapport, Citadel mettait en place des équipes offshore pour maintenir cette nouvelle activité hors de portée de la réglementation américaine, un geste interprété comme une réponse au virage de l'administration Trump vers des règles plus favorables à la crypto. Citadel avait déjà effleuré les marges du secteur - détenant une participation dans la plateforme de trading institutionnel EDX Markets - mais restait prudent quant à l'introduction de son cœur de métier, la tenue de marché, directement dans la crypto. Dix-sept mois plus tard, l'investissement en capital de 400 millions de dollars transforme pour la première fois cette rhétorique d'« exploration » en un déploiement de capital concret.</p>
<p class="pt">Em fevereiro de 2025, a Bloomberg noticiou, citando fontes anônimas, que a Citadel Securities estava explorando um negócio de formação de mercado que forneceria liquidez a grandes exchanges de criptomoedas, incluindo Coinbase, Binance e Crypto.com. Segundo aquele relato, a Citadel estava montando equipes offshore para manter essa nova linha fora do alcance regulatório dos EUA, um movimento interpretado como resposta à guinada da administração Trump rumo a regras mais favoráveis às criptomoedas. A Citadel já havia tocado as bordas do setor - detendo participação na plataforma de negociação institucional de cripto EDX Markets - mas se mantinha cautelosa quanto a trazer seu negócio central de formação de mercado diretamente para as criptomoedas. Dezessete meses depois, o investimento acionário de US$ 400 milhões transforma pela primeira vez essa retórica de "exploração" em uma alocação concreta de capital.</p>
<p class="tr">Şubat 2025'te Bloomberg, isimsiz kaynaklara dayanarak Citadel Securities'in Coinbase, Binance ve Crypto.com dahil büyük kripto borsalarına likidite sağlayacak bir piyasa yapıcılığı işi değerlendirdiğini bildirmişti. O habere göre Citadel, bu yeni iş kolunu ABD düzenleyici erişiminin dışında tutmak için offshore ekipler kuruyordu; bu adım Trump yönetiminin kripto dostu düzenlemelere yönelik dönüşümüne bir yanıt olarak okundu. Citadel, kurumlar arası kripto ticaret platformu EDX Markets'te pay sahibi olmak gibi sektörün kenarlarına daha önce de dokunmuştu, ancak temel işi olan piyasa yapıcılığını doğrudan kriptoya taşıma konusunda temkinli kalmıştı. On yedi ay sonra, 400 milyon dolarlık hisse yatırımı bu "değerlendirme" söylemini ilk kez somut bir sermaye tahsisine dönüştürüyor.</p>
<p class="vi">Vào tháng 2/2025, Bloomberg đưa tin, dẫn nguồn ẩn danh, rằng Citadel Securities đang cân nhắc một mảng kinh doanh tạo lập thị trường nhằm cung cấp thanh khoản cho các sàn giao dịch tiền mã hóa lớn bao gồm Coinbase, Binance và Crypto.com. Theo báo cáo đó, Citadel đang thành lập các đội ngũ ở nước ngoài để giữ mảng kinh doanh mới này nằm ngoài tầm với của cơ quan quản lý Mỹ, một động thái được hiểu là phản ứng trước sự chuyển hướng của chính quyền Trump sang các quy định thân thiện hơn với tiền mã hóa. Citadel trước đó đã chạm đến rìa ngoài của ngành - nắm giữ cổ phần tại nền tảng giao dịch tiền mã hóa dành cho tổ chức EDX Markets - nhưng vẫn thận trọng trong việc đưa mảng kinh doanh cốt lõi là tạo lập thị trường trực tiếp vào tiền mã hóa. Mười bảy tháng sau, khoản đầu tư cổ phần 400 triệu đô la lần đầu tiên biến lời lẽ "cân nhắc" thành việc triển khai vốn cụ thể.</p>
<p class="id">Pada Februari 2025, Bloomberg melaporkan, mengutip sumber anonim, bahwa Citadel Securities sedang mengeksplorasi bisnis market-making yang akan memasok likuiditas ke bursa kripto besar termasuk Coinbase, Binance, dan Crypto.com. Menurut laporan itu, Citadel sedang membentuk tim offshore untuk menjaga lini bisnis baru ini tetap di luar jangkauan regulasi AS, sebuah langkah yang dibaca sebagai respons terhadap pergeseran pemerintahan Trump menuju aturan kripto yang lebih ramah. Citadel sebelumnya sudah menyentuh pinggiran industri ini - dengan memegang saham di platform perdagangan kripto institusional EDX Markets - tetapi tetap berhati-hati untuk membawa bisnis inti market-making-nya langsung ke dunia kripto. Tujuh belas bulan kemudian, investasi saham senilai 400 juta dolar AS ini untuk pertama kalinya mengubah retorika "eksplorasi" tersebut menjadi penempatan modal yang konkret.</p>
<p class="pl">W lutym 2025 roku Bloomberg poinformował, powołując się na anonimowe źródła, że Citadel Securities rozważa działalność animatora rynku, która miałaby dostarczać płynność głównym giełdom kryptowalut, w tym Coinbase, Binance i Crypto.com. Według tego raportu Citadel tworzył zespoły offshore, aby utrzymać nową działalność poza zasięgiem amerykańskich regulatorów - co odczytano jako reakcję na zwrot administracji Trumpa w stronę bardziej przyjaznych kryptowalutom przepisów. Citadel wcześniej już dotykał peryferii branży - posiadając udziały w instytucjonalnej platformie handlu kryptowalutami EDX Markets - ale pozostawał ostrożny wobec wprowadzenia swojej podstawowej działalności animowania rynku bezpośrednio do świata kryptowalut. Siedemnaście miesięcy później inwestycja kapitałowa o wartości 400 milionów dolarów po raz pierwszy zamienia tę retorykę „rozważania” w konkretne wdrożenie kapitału.</p>
<p class="it">Nel febbraio 2025, Bloomberg riportò, citando fonti anonime, che Citadel Securities stava valutando un'attività di market making che avrebbe fornito liquidità ai principali exchange di criptovalute, tra cui Coinbase, Binance e Crypto.com. Secondo quel resoconto, Citadel stava creando team offshore per mantenere la nuova attività fuori dalla portata della regolamentazione statunitense, una mossa interpretata come risposta al passaggio dell'amministrazione Trump verso regole più favorevoli alle criptovalute. Citadel aveva già sfiorato i margini del settore in passato - detenendo una quota nella piattaforma di trading istituzionale EDX Markets - ma era rimasta cauta riguardo all'introduzione della sua attività principale di market making direttamente nel mondo crypto. Diciassette mesi dopo, l'investimento azionario da 400 milioni di dollari trasforma per la prima volta quella retorica di "valutazione" in un concreto impiego di capitale.</p>
<p class="ru">В феврале 2025 года Bloomberg сообщил со ссылкой на анонимные источники, что Citadel Securities изучает возможность создания маркет-мейкингового бизнеса, который будет обеспечивать ликвидность крупным криптобиржам, включая Coinbase, Binance и Crypto.com. Согласно этому сообщению, Citadel формировала офшорные команды, чтобы держать новое направление вне досягаемости американских регуляторов - шаг, расцененный как реакция на разворот администрации Трампа в сторону более дружественных крипторынку правил. Citadel и раньше соприкасалась с периферией отрасли - владея долей в институциональной криптоплатформе EDX Markets, - но оставалась осторожной в вопросе переноса своего основного маркет-мейкингового бизнеса непосредственно в крипту. Семнадцать месяцев спустя инвестиция в капитал на 400 миллионов долларов впервые превращает эту риторику «изучения» в конкретное размещение капитала.</p>
<p class="zh">2025年2月,彭博社援引匿名消息來源報導,Citadel Securities正在評估一項做市業務,將為包括Coinbase、Binance與Crypto.com在內的主要加密貨幣交易所提供流動性。根據該報導,Citadel正在組建境外團隊,以將這項新業務置於美國監管範圍之外,此舉被解讀為對川普政府轉向更友善加密貨幣法規的回應。Citadel此前已觸及該產業邊緣——持有機構加密貨幣交易平台EDX Markets的股權——但對於將其核心做市業務直接引入加密貨幣領域,一直保持謹慎態度。十七個月後,這筆4億美元的股權投資首次將「評估中」的說法轉化為具體的資本部署。</p>

<p class="ko">마켓메이커는 매수·매도 양방향 호가를 동시에 제시해 스프레드를 수익원으로 삼고, 여러 거래소에 걸쳐 유동성을 공급하며 가격 효율성을 유지하는 역할을 한다. 단순한 서비스 제공 관계라면 시타델의 수익은 거래 수수료나 스프레드에 그치지만, 지분을 보유하면 크립토닷컴 플랫폼 전체의 거래량·수익 성장에 시타델의 손익이 직접 연동된다 — 이는 시타델이 자사가 유동성을 공급하는 거래소 자체의 성장에 인센티브를 갖게 됨을 뜻한다. 이 구조는 시타델이 미국 주식시장에서 로빈후드 등과 맺어온 주문흐름대가지급(PFOF) 관계를 둘러싼 논란을 떠올리게 한다 — 마켓메이커가 특정 플랫폼과 경제적 이해관계를 공유할 때 최선집행 의무와 이해상충이 어떻게 충돌하는지가 미국 증권시장에서 수년간 SEC의 감독 대상이 되어 왔다. 크립토 시장에는 아직 이에 상응하는 명확한 규제 체계가 없다는 점에서, 이번 지분투자가 유사한 논쟁을 새로운 무대로 옮겨올지가 관전 포인트다.</p>
<p class="en">Market makers post continuous two-sided quotes, earning the bid-ask spread while supplying liquidity across venues and keeping prices efficient. In a pure vendor relationship, Citadel's revenue would be limited to trading fees or spreads; holding equity ties Citadel's own profit and loss directly to the growth of Crypto.com's overall trading volume and revenue - meaning Citadel now has a stake in the growth of the very exchange whose liquidity it may supply. That structure echoes the controversy around Citadel's payment-for-order-flow arrangements with platforms like Robinhood in U.S. equities, where the SEC has spent years scrutinizing how a market maker's economic ties to a specific platform can collide with best-execution duties. Crypto markets have no equivalent regulatory framework yet, which is exactly what makes it worth watching whether this equity stake imports a similar debate into a new arena.</p>
<p class="ja">マーケットメイカーは売買両方向の気配値を同時に提示してスプレッドを収益源とし、複数の取引所にまたがって流動性を供給しながら価格効率性を維持する役割を担う。単なるサービス提供関係であればシタデルの収益は取引手数料やスプレッドにとどまるが、株式を保有すればクリプトドットコムのプラットフォーム全体の取引高・収益成長にシタデルの損益が直接連動する — これはシタデルが自らが流動性を供給する取引所自体の成長に対してインセンティブを持つことを意味する。この構造は、シタデルが米国株式市場でロビンフッドなどと結んできた注文フロー対価支払い(PFOF)関係をめぐる論争を想起させる — マーケットメイカーが特定のプラットフォームと経済的利害を共有する際、最善執行義務と利益相反がどう衝突するかは、米国証券市場で長年SECの監視対象となってきた。暗号資産市場にはまだこれに相当する明確な規制枠組みが存在しないため、今回の株式投資が同様の論争を新たな舞台に持ち込むかどうかが注目点だ。</p>
<p class="es">Los creadores de mercado publican cotizaciones continuas en ambos sentidos, ganando con el diferencial entre compra y venta mientras suministran liquidez en distintas plazas y mantienen la eficiencia de precios. En una relación de proveedor puro, los ingresos de Citadel se limitarían a comisiones o diferenciales; al poseer participación accionaria, las ganancias y pérdidas de Citadel quedan directamente ligadas al crecimiento del volumen de negociación e ingresos de toda la plataforma de Crypto.com, lo que significa que Citadel ahora tiene un interés en el crecimiento del propio exchange al que podría suministrar liquidez. Esa estructura recuerda la controversia en torno a los acuerdos de pago por flujo de órdenes (PFOF) de Citadel con plataformas como Robinhood en el mercado de acciones estadounidense, donde la SEC ha pasado años examinando cómo los vínculos económicos de un creador de mercado con una plataforma específica pueden chocar con el deber de mejor ejecución. Los mercados cripto aún no cuentan con un marco regulatorio equivalente, lo que hace que valga la pena observar si esta participación accionaria traslada un debate similar a un nuevo escenario.</p>
<p class="de">Market Maker stellen fortlaufend beidseitige Kurse und verdienen an der Geld-Brief-Spanne, während sie über mehrere Handelsplätze hinweg Liquidität bereitstellen und die Preiseffizienz erhalten. Bei einer reinen Dienstleisterbeziehung wäre Citadels Erlös auf Handelsgebühren oder Spreads begrenzt; mit einer Beteiligung ist Citadels eigenes Gewinn-und-Verlust-Ergebnis direkt an das Wachstum von Handelsvolumen und Umsatz der gesamten Crypto.com-Plattform gekoppelt — Citadel hat damit ein Interesse am Wachstum genau jener Börse, der es möglicherweise Liquidität zuführt. Diese Struktur erinnert an die Kontroverse um Citadels Payment-for-Order-Flow-Vereinbarungen mit Plattformen wie Robinhood im US-Aktienmarkt, wo die SEC seit Jahren untersucht, wie wirtschaftliche Bindungen eines Market Makers an eine bestimmte Plattform mit der Best-Execution-Pflicht kollidieren können. Kryptomärkte verfügen noch über keinen vergleichbaren Regulierungsrahmen, weshalb sich beobachten lässt, ob diese Beteiligung eine ähnliche Debatte in ein neues Umfeld trägt.</p>
<p class="fr">Les teneurs de marché affichent en continu des cotations dans les deux sens, gagnant sur l'écart entre l'offre et la demande tout en fournissant de la liquidité sur plusieurs plateformes et en maintenant l'efficience des prix. Dans une relation de prestataire pure, les revenus de Citadel se limiteraient aux frais de transaction ou aux écarts ; en détenant une participation, les profits et pertes propres de Citadel sont directement liés à la croissance du volume de transactions et des revenus de l'ensemble de la plateforme Crypto.com - ce qui signifie que Citadel a désormais un intérêt dans la croissance de la bourse même à laquelle elle pourrait fournir de la liquidité. Cette structure rappelle la controverse autour des accords de paiement pour flux d'ordres (PFOF) de Citadel avec des plateformes comme Robinhood sur le marché actions américain, où la SEC scrute depuis des années comment les liens économiques d'un teneur de marché avec une plateforme donnée peuvent entrer en conflit avec le devoir de meilleure exécution. Les marchés crypto ne disposent pas encore d'un cadre réglementaire équivalent, ce qui rend intéressant de voir si cette participation importe un débat similaire dans une nouvelle arène.</p>
<p class="pt">Formadores de mercado publicam cotações contínuas nos dois sentidos, lucrando com o spread entre compra e venda enquanto fornecem liquidez em várias praças e mantêm a eficiência de preços. Em uma relação puramente de fornecedor, a receita da Citadel se limitaria a taxas de negociação ou spreads; ao deter participação acionária, os lucros e perdas da própria Citadel ficam diretamente atrelados ao crescimento do volume de negociação e da receita de toda a plataforma da Crypto.com - o que significa que a Citadel agora tem interesse no crescimento da própria exchange à qual pode fornecer liquidez. Essa estrutura remete à controvérsia em torno dos acordos de pagamento por fluxo de ordens (PFOF) da Citadel com plataformas como a Robinhood no mercado acionário americano, em que a SEC vem examinando há anos como os vínculos econômicos de um formador de mercado com uma plataforma específica podem colidir com o dever de melhor execução. Os mercados de criptomoedas ainda não têm um arcabouço regulatório equivalente, o que torna relevante observar se essa participação acionária importa um debate semelhante para uma nova arena.</p>
<p class="tr">Piyasa yapıcılar sürekli olarak iki yönlü kotasyonlar sunar, alış-satış farkından kazanç sağlarken çeşitli platformlarda likidite tedarik eder ve fiyat verimliliğini korur. Salt bir tedarikçi ilişkisinde Citadel'in geliri işlem ücretleri veya spread'lerle sınırlı kalırdı; hisse sahibi olmak, Citadel'in kendi kâr-zarar durumunu Crypto.com platformunun genel işlem hacmi ve gelir büyümesine doğrudan bağlıyor — bu da Citadel'in, likidite sağlayabileceği borsanın büyümesinde artık doğrudan bir çıkarı olduğu anlamına geliyor. Bu yapı, Citadel'in ABD hisse senedi piyasasında Robinhood gibi platformlarla yaptığı emir akışı karşılığı ödeme (PFOF) anlaşmaları etrafındaki tartışmayı hatırlatıyor; SEC yıllardır bir piyasa yapıcının belirli bir platformla ekonomik bağlarının en iyi uygulama yükümlülüğüyle nasıl çatışabileceğini inceliyor. Kripto piyasalarının henüz buna denk bir düzenleyici çerçevesi yok; bu da söz konusu hisse yatırımının benzer bir tartışmayı yeni bir alana taşıyıp taşımayacağını izlemeye değer kılıyor.</p>
<p class="vi">Các nhà tạo lập thị trường liên tục niêm yết giá chào mua và chào bán hai chiều, kiếm lời từ chênh lệch giá trong khi cung cấp thanh khoản trên nhiều sàn và duy trì hiệu quả giá cả. Trong một quan hệ nhà cung cấp thuần túy, doanh thu của Citadel sẽ chỉ giới hạn ở phí giao dịch hoặc chênh lệch giá; khi nắm giữ cổ phần, lãi lỗ của chính Citadel gắn trực tiếp với sự tăng trưởng khối lượng giao dịch và doanh thu của toàn bộ nền tảng Crypto.com - nghĩa là Citadel giờ đây có lợi ích trong sự tăng trưởng của chính sàn giao dịch mà họ có thể cung cấp thanh khoản. Cấu trúc này gợi nhớ đến tranh cãi xung quanh các thỏa thuận thanh toán cho luồng lệnh (PFOF) của Citadel với các nền tảng như Robinhood trên thị trường cổ phiếu Mỹ, nơi Ủy ban Chứng khoán Mỹ (SEC) đã dành nhiều năm xem xét cách các mối liên hệ kinh tế của một nhà tạo lập thị trường với một nền tảng cụ thể có thể xung đột với nghĩa vụ thực thi tốt nhất. Thị trường tiền mã hóa vẫn chưa có khung pháp lý tương đương, điều này khiến việc theo dõi xem khoản đầu tư cổ phần này có mang một cuộc tranh luận tương tự vào một đấu trường mới hay không trở nên đáng chú ý.</p>
<p class="id">Pembuat pasar memasang kuotasi dua arah secara terus-menerus, memperoleh keuntungan dari selisih bid-ask sambil memasok likuiditas di berbagai platform dan menjaga efisiensi harga. Dalam hubungan vendor murni, pendapatan Citadel akan terbatas pada biaya transaksi atau spread; kepemilikan saham mengaitkan laba-rugi Citadel sendiri secara langsung dengan pertumbuhan volume perdagangan dan pendapatan keseluruhan platform Crypto.com - artinya Citadel kini memiliki kepentingan dalam pertumbuhan bursa yang justru likuiditasnya mungkin ia pasok sendiri. Struktur ini mengingatkan pada kontroversi seputar kesepakatan payment-for-order-flow Citadel dengan platform seperti Robinhood di pasar saham AS, di mana SEC telah bertahun-tahun mengawasi bagaimana keterkaitan ekonomi seorang pembuat pasar dengan platform tertentu dapat berbenturan dengan kewajiban eksekusi terbaik. Pasar kripto belum memiliki kerangka regulasi yang setara, yang justru membuat menarik untuk diamati apakah kepemilikan saham ini membawa perdebatan serupa ke arena baru.</p>
<p class="pl">Animatorzy rynku stale wystawiają dwustronne kwotowania, zarabiając na spreadzie kupna-sprzedaży, jednocześnie dostarczając płynność na różnych platformach i utrzymując efektywność cenową. W czysto usługowej relacji przychody Citadel byłyby ograniczone do opłat transakcyjnych lub spreadów; posiadanie udziałów wiąże własne zyski i straty Citadel bezpośrednio ze wzrostem wolumenu obrotu i przychodów całej platformy Crypto.com - co oznacza, że Citadel ma teraz interes we wzroście tej samej giełdy, której płynność może dostarczać. Ta struktura przypomina kontrowersje wokół umów Citadel dotyczących płatności za przepływ zleceń (PFOF) z platformami takimi jak Robinhood na amerykańskim rynku akcji, gdzie SEC od lat bada, jak ekonomiczne powiązania animatora rynku z konkretną platformą mogą kolidować z obowiązkiem najlepszego wykonania zleceń. Rynki kryptowalut nie mają jeszcze równoważnych ram regulacyjnych, co sprawia, że warto obserwować, czy ten udział kapitałowy przeniesie podobną debatę na nową arenę.</p>
<p class="it">I market maker pubblicano continuamente quotazioni bidirezionali, guadagnando sullo spread denaro-lettera mentre forniscono liquidità su più sedi di negoziazione e mantengono l'efficienza dei prezzi. In un rapporto puramente da fornitore, i ricavi di Citadel sarebbero limitati alle commissioni di negoziazione o agli spread; detenere una partecipazione azionaria lega direttamente il conto economico di Citadel alla crescita del volume di scambi e dei ricavi complessivi della piattaforma Crypto.com - il che significa che Citadel ha ora un interesse nella crescita proprio dell'exchange a cui potrebbe fornire liquidità. Questa struttura richiama la controversia legata agli accordi di payment-for-order-flow di Citadel con piattaforme come Robinhood nel mercato azionario statunitense, dove la SEC ha passato anni a esaminare come i legami economici di un market maker con una piattaforma specifica possano entrare in conflitto con gli obblighi di best execution. I mercati crypto non hanno ancora un quadro normativo equivalente, il che è esattamente ciò che rende interessante osservare se questa partecipazione azionaria importi un dibattito simile in una nuova arena.</p>
<p class="ru">Маркет-мейкеры непрерывно выставляют двусторонние котировки, зарабатывая на спреде между ценой покупки и продажи, одновременно обеспечивая ликвидность на разных площадках и поддерживая эффективность цен. При чисто поставщических отношениях доход Citadel ограничивался бы торговыми комиссиями или спредами; владение долей напрямую связывает собственную прибыль и убытки Citadel с ростом общего торгового объёма и выручки платформы Crypto.com - а значит, теперь Citadel заинтересована в росте той самой биржи, ликвидность которой она может обеспечивать. Эта структура перекликается со спорами вокруг соглашений Citadel о платежах за поток ордеров (PFOF) с такими платформами, как Robinhood, на рынке акций США, где SEC годами изучает, как экономические связи маркет-мейкера с конкретной платформой могут вступать в конфликт с обязанностями по наилучшему исполнению. У крипторынков пока нет аналогичной регуляторной базы, и именно поэтому стоит следить, перенесёт ли эта доля в капитале похожую дискуссию на новую площадку.</p>
<p class="zh">做市商持續掛出雙向報價,透過買賣價差獲利,同時在多個交易場所提供流動性並維持價格效率。在單純的供應商關係下,Citadel的收入僅限於交易手續費或價差;而持有股權則使Citadel自身的損益直接與Crypto.com整體交易量及營收的成長掛鉤——這意味著Citadel如今對自己可能提供流動性的這家交易所的成長本身也有了利益關係。這種結構讓人聯想到Citadel與Robinhood等平台在美國股市中的訂單流付費(PFOF)安排所引發的爭議——多年來,美國證券交易委員會(SEC)一直在審視做市商與特定平台之間的經濟聯繫,如何與最佳執行義務產生衝突。加密貨幣市場尚無對應的監管框架,這正是為何值得關注這筆股權投資是否會將類似的爭論帶入新的舞台。</p>

<h2 class="ko">크립토닷컴이 얻는 것 — 기관화 신호탄인가, 상장 전 밸류에이션 방어인가</h2>
<h2 class="en">What Crypto.com Gets - A Signal of Institutionalization, or a Pre-IPO Valuation Defense?</h2>
<h2 class="ja">クリプトドットコムが得るもの — 機関化のシグナルか、上場前の評価額防衛か</h2>
<h2 class="es">Qué gana Crypto.com — ¿señal de institucionalización o defensa de la valoración antes de una salida a bolsa?</h2>
<h2 class="de">Was Crypto.com gewinnt — Signal der Institutionalisierung oder Verteidigung der Bewertung vor einem Börsengang?</h2>
<h2 class="fr">Ce que gagne Crypto.com — signal d'institutionnalisation ou défense de la valorisation avant une IPO ?</h2>
<h2 class="pt">O que a Crypto.com ganha — sinal de institucionalização ou defesa da avaliação antes de um IPO?</h2>
<h2 class="tr">Crypto.com Ne Kazanıyor — Kurumsallaşma Sinyali mi, Halka Arz Öncesi Değerleme Savunması mı?</h2>
<h2 class="vi">Crypto.com Nhận Được Gì — Tín Hiệu Thể Chế Hóa, Hay Phòng Thủ Định Giá Trước Thềm IPO?</h2>
<h2 class="id">Apa yang Didapat Crypto.com - Sinyal Institusionalisasi, atau Pertahanan Valuasi Pra-IPO?</h2>
<h2 class="pl">Co zyskuje Crypto.com - sygnał instytucjonalizacji czy obrona wyceny przed IPO?</h2>
<h2 class="it">Cosa ottiene Crypto.com - Un segnale di istituzionalizzazione o una difesa della valutazione pre-IPO?</h2>
<h2 class="ru">Что получает Crypto.com - сигнал институционализации или защита оценки перед IPO?</h2>
<h2 class="zh">Crypto.com獲得了什麼——機構化的訊號,還是IPO前的估值防禦?</h2>

<p class="ko">크립토닷컴은 100여개국에서 규제 라이선스를 보유하고 있으며 이 중 미국 내 40여개 주의 자금이체업(MTL) 라이선스가 포함된다. 2024년 매출은 약 15억달러로 전년(약 12억달러) 대비 25% 늘었고, 이용자 수는 2021년초 1,000만명에서 2024년 중반 1억명을 넘어선 것으로 추정된다. 크립토닷컴은 지난해 10월 상장 전 사전 주문을 받는 'IPO 얼리버드' 프로그램을 시작하며 상장 의지를 내비쳤고, 올해 1분기에는 통화감독청(OCC)으로부터 연방 인가 수탁은행 설립 승인을 받았다. 7월7일에는 계열 선물중개업체(FCM) 'OG브로커'의 인프라를 <a href="/blog/prospect-markets-cryptocom-cftc-prediction-entry">상장사 프로스펙트에 빌려주는 방식으로 미국 예측시장 진출을 지원</a>하는 등, 자체 거래소를 넘어 규제 인프라를 임대하는 사업모델로도 영역을 넓혀왔다. 이번 시타델의 지분 투자는 이런 다각화된 기관화 행보에 월가 최대 마켓메이커의 이름값을 더하는 모양새다.</p>
<p class="en">Crypto.com holds regulatory licenses across more than 100 jurisdictions, including money transmitter licenses in more than 40 U.S. states. Its 2024 revenue was roughly $1.5 billion, up 25% from about $1.2 billion the prior year, and its user base is estimated to have grown from 10 million in early 2021 to more than 100 million by mid-2024. The company signaled IPO ambitions by launching an "IPO Early Bird" pre-listing order program last October, and in the first quarter of this year won approval from the Office of the Comptroller of the Currency to establish a federally chartered trust bank. On July 7, it lent the infrastructure of its affiliated futures commission merchant, OG Broker, to help publicly traded <a href="/en/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets enter the U.S. prediction-market business</a> - part of a broader push to rent out regulated infrastructure beyond its own exchange. Citadel's equity stake adds Wall Street's biggest market-making name to that pattern of diversified institutionalization.</p>
<p class="ja">クリプトドットコムは100以上の法域で規制ライセンスを保有しており、その中には米国内40以上の州の資金移動業(MTL)ライセンスが含まれる。2024年の売上高は約15億ドルで前年(約12億ドル)比25%増加し、利用者数は2021年初の1,000万人から2024年半ばには1億人を超えたと推定されている。クリプトドットコムは昨年10月、上場前の事前注文を受け付ける「IPOアーリーバード」プログラムを開始し上場意欲を示した。また今年第1四半期には、通貨監督庁(OCC)から連邦認可信託銀行設立の承認を得た。7月7日には、系列先物取次業者(FCM)「OGブローカー」のインフラを<a href="/ja/blog/prospect-markets-cryptocom-cftc-prediction-entry">上場企業プロスペクトに貸し出し米国予測市場への進出を支援する</a>など、自社取引所を超えて規制インフラを賃貸する事業モデルへも領域を広げてきた。今回のシタデルの株式投資は、こうした多角的な機関化の歩みにウォール街最大のマーケットメイカーの名を加える形となった。</p>
<p class="es">Crypto.com posee licencias regulatorias en más de 100 jurisdicciones, incluidas licencias de transmisor de dinero en más de 40 estados de EE. UU. Sus ingresos de 2024 fueron de aproximadamente 1.500 millones de dólares, un 25% más que los cerca de 1.200 millones del año anterior, y se estima que su base de usuarios creció de 10 millones a principios de 2021 a más de 100 millones a mediados de 2024. La compañía dejó entrever ambiciones de salida a bolsa al lanzar en octubre pasado un programa de pedidos previos llamado "IPO Early Bird", y en el primer trimestre de este año obtuvo la aprobación de la Oficina del Contralor de la Moneda (OCC) para establecer un banco fiduciario con licencia federal. El 7 de julio prestó la infraestructura de su comisionista de futuros afiliado, OG Broker, para ayudar a la cotizada <a href="/es/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets a entrar en el negocio de mercados de predicción en EE. UU.</a>, parte de un impulso más amplio por alquilar infraestructura regulada más allá de su propio exchange. La participación de Citadel añade el nombre del mayor creador de mercado de Wall Street a ese patrón de institucionalización diversificada.</p>
<p class="de">Crypto.com hält regulatorische Lizenzen in mehr als 100 Rechtsräumen, darunter Geldtransferlizenzen in mehr als 40 US-Bundesstaaten. Der Umsatz 2024 lag bei rund 1,5 Milliarden Dollar, ein Plus von 25% gegenüber rund 1,2 Milliarden Dollar im Vorjahr; die Nutzerbasis soll von 10 Millionen Anfang 2021 auf über 100 Millionen Mitte 2024 gewachsen sein. Das Unternehmen signalisierte Börsenambitionen mit dem im Oktober gestarteten Vorbestellprogramm "IPO Early Bird" und erhielt im ersten Quartal dieses Jahres von der US-Bankenaufsicht OCC die Genehmigung zur Gründung einer bundeslizenzierten Treuhandbank. Am 7. Juli lieh es die Infrastruktur seines verbundenen Terminkommissionärs OG Broker aus, um dem börsennotierten <a href="/de/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets den Einstieg ins US-Prognosemarkt-Geschäft zu ermöglichen</a> — Teil eines breiteren Vorstoßes, regulierte Infrastruktur über die eigene Börse hinaus zu vermieten. Citadels Beteiligung fügt diesem Muster diversifizierter Institutionalisierung den Namen des größten Market Makers der Wall Street hinzu.</p>
<p class="fr">Crypto.com détient des licences réglementaires dans plus de 100 juridictions, dont des licences de transmetteur de fonds dans plus de 40 États américains. Son chiffre d'affaires 2024 s'est élevé à environ 1,5 milliard de dollars, en hausse de 25% par rapport à environ 1,2 milliard l'année précédente, et sa base d'utilisateurs serait passée de 10 millions début 2021 à plus de 100 millions mi-2024. L'entreprise a laissé entrevoir des ambitions de cotation en lançant en octobre dernier un programme de précommande baptisé « IPO Early Bird », et a obtenu au premier trimestre de cette année l'approbation du Bureau du contrôleur de la monnaie (OCC) pour créer une banque fiduciaire à charte fédérale. Le 7 juillet, elle a prêté l'infrastructure de son courtier en contrats à terme affilié, OG Broker, pour aider la société cotée <a href="/fr/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets à entrer sur le marché américain des marchés de prédiction</a> - un élément d'une stratégie plus large consistant à louer une infrastructure réglementée au-delà de sa propre bourse. La participation de Citadel ajoute le nom du plus grand teneur de marché de Wall Street à ce schéma d'institutionnalisation diversifiée.</p>
<p class="pt">A Crypto.com detém licenças regulatórias em mais de 100 jurisdições, incluindo licenças de transmissão de dinheiro em mais de 40 estados dos EUA. Sua receita em 2024 foi de cerca de US$ 1,5 bilhão, alta de 25% frente a cerca de US$ 1,2 bilhão no ano anterior, e sua base de usuários teria crescido de 10 milhões no início de 2021 para mais de 100 milhões em meados de 2024. A empresa sinalizou ambições de IPO ao lançar em outubro passado um programa de pedidos antecipados chamado "IPO Early Bird", e no primeiro trimestre deste ano obteve aprovação do Escritório do Controlador da Moeda (OCC) para estabelecer um banco fiduciário com carta federal. Em 7 de julho, emprestou a infraestrutura de sua corretora de futuros afiliada, a OG Broker, para ajudar a companhia aberta <a href="/pt/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets a entrar no negócio de mercados de previsão nos EUA</a> - parte de um esforço mais amplo de alugar infraestrutura regulada além de sua própria exchange. A participação da Citadel soma o nome da maior formadora de mercado de Wall Street a esse padrão de institucionalização diversificada.</p>
<p class="tr">Crypto.com, 40'tan fazla ABD eyaletinde para transferi lisansları dahil olmak üzere 100'den fazla yargı bölgesinde düzenleyici lisanslara sahip. 2024 geliri yaklaşık 1,5 milyar dolar olup önceki yıla (yaklaşık 1,2 milyar dolar) göre %25 arttı; kullanıcı tabanının 2021 başındaki 10 milyondan 2024 ortasında 100 milyonun üzerine çıktığı tahmin ediliyor. Şirket, geçen Ekim ayında başlattığı "IPO Early Bird" ön sipariş programıyla halka arz niyetini işaret etti ve bu yılın ilk çeyreğinde ABD Para Denetleme Ofisi'nden (OCC) federal lisanslı bir güven bankası kurma onayı aldı. 7 Temmuz'da, halka açık <a href="/tr/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets'in ABD tahmin piyasası işine girmesine yardımcı olmak için</a> bağlı vadeli işlemler komisyoncusu OG Broker'ın altyapısını ödünç verdi — bu da kendi borsasının ötesinde düzenlenmiş altyapıyı kiralamaya yönelik daha geniş bir çabanın parçası. Citadel'in hisse yatırımı, bu çeşitlendirilmiş kurumsallaşma örüntüsüne Wall Street'in en büyük piyasa yapıcısının adını ekliyor.</p>
<p class="vi">Crypto.com nắm giữ giấy phép quản lý tại hơn 100 khu vực pháp lý, bao gồm giấy phép chuyển tiền tại hơn 40 bang của Mỹ. Doanh thu năm 2024 của công ty vào khoảng 1,5 tỷ đô la, tăng 25% so với khoảng 1,2 tỷ đô la năm trước đó, và cơ sở người dùng được ước tính đã tăng từ 10 triệu vào đầu năm 2021 lên hơn 100 triệu vào giữa năm 2024. Công ty đã thể hiện tham vọng IPO khi ra mắt chương trình đặt lệnh trước mang tên "IPO Early Bird" vào tháng 10 năm ngoái, và trong quý 1 năm nay đã nhận được sự chấp thuận từ Văn phòng Kiểm soát Tiền tệ (OCC) để thành lập một ngân hàng ủy thác được cấp phép liên bang. Vào ngày 7/7, công ty đã cho <a href="/vi/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets, một công ty đại chúng, mượn hạ tầng của công ty môi giới hợp đồng tương lai liên kết OG Broker để hỗ trợ Prospect gia nhập thị trường dự đoán tại Mỹ</a> - một phần trong nỗ lực rộng hơn nhằm cho thuê hạ tầng được quản lý ngoài phạm vi sàn giao dịch của chính mình. Khoản đầu tư cổ phần của Citadel bổ sung tên tuổi của nhà tạo lập thị trường lớn nhất Phố Wall vào mô hình thể chế hóa đa dạng đó.</p>
<p class="id">Crypto.com memegang lisensi regulasi di lebih dari 100 yurisdiksi, termasuk lisensi money transmitter di lebih dari 40 negara bagian AS. Pendapatannya pada 2024 sekitar 1,5 miliar dolar AS, naik 25% dari sekitar 1,2 miliar dolar AS pada tahun sebelumnya, dan basis penggunanya diperkirakan tumbuh dari 10 juta pada awal 2021 menjadi lebih dari 100 juta pada pertengahan 2024. Perusahaan ini menandakan ambisi IPO dengan meluncurkan program pemesanan pra-listing "IPO Early Bird" pada Oktober lalu, dan pada kuartal pertama tahun ini memperoleh persetujuan dari Office of the Comptroller of the Currency untuk mendirikan trust bank berpiagam federal. Pada 7 Juli, perusahaan ini meminjamkan infrastruktur pialang komisi futures afiliasinya, OG Broker, untuk membantu <a href="/id/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets, perusahaan publik, memasuki bisnis pasar prediksi AS</a> - bagian dari dorongan yang lebih luas untuk menyewakan infrastruktur teregulasi di luar bursanya sendiri. Kepemilikan saham Citadel menambahkan nama pembuat pasar terbesar Wall Street ke pola institusionalisasi yang terdiversifikasi ini.</p>
<p class="pl">Crypto.com posiada licencje regulacyjne w ponad 100 jurysdykcjach, w tym licencje money transmitter w ponad 40 stanach USA. Jej przychody w 2024 roku wyniosły około 1,5 miliarda dolarów, wzrost o 25% w porównaniu do około 1,2 miliarda dolarów rok wcześniej, a baza użytkowników wzrosła szacunkowo z 10 milionów na początku 2021 roku do ponad 100 milionów w połowie 2024 roku. Firma zasygnalizowała ambicje związane z IPO, uruchamiając w październiku ubiegłego roku program przedsprzedaży zamówień „IPO Early Bird”, a w pierwszym kwartale tego roku uzyskała zgodę Biura Kontrolera Waluty (OCC) na utworzenie federalnie licencjonowanego banku powierniczego. 7 lipca firma udostępniła infrastrukturę powiązanego domu maklerskiego kontraktów terminowych OG Broker, aby pomóc notowanej na giełdzie <a href="/pl/blog/prospect-markets-cryptocom-cftc-prediction-entry">spółce Prospect Markets wejść na amerykański rynek rynków predykcyjnych</a> - część szerszej strategii wynajmowania regulowanej infrastruktury poza własną giełdą. Udział kapitałowy Citadel dodaje nazwę największego animatora rynku Wall Street do tego wzorca zdywersyfikowanej instytucjonalizacji.</p>
<p class="it">Crypto.com detiene licenze regolamentari in oltre 100 giurisdizioni, incluse licenze di money transmitter in più di 40 stati americani. I suoi ricavi nel 2024 sono stati di circa 1,5 miliardi di dollari, in aumento del 25% rispetto a circa 1,2 miliardi di dollari dell'anno precedente, e la sua base di utenti si stima sia cresciuta da 10 milioni all'inizio del 2021 a oltre 100 milioni a metà 2024. L'azienda ha segnalato ambizioni di IPO lanciando lo scorso ottobre un programma di preordine pre-quotazione chiamato "IPO Early Bird", e nel primo trimestre di quest'anno ha ottenuto l'approvazione dell'Office of the Comptroller of the Currency per istituire una trust bank a statuto federale. Il 7 luglio ha prestato l'infrastruttura del suo futures commission merchant affiliato, OG Broker, per aiutare la società quotata in borsa <a href="/it/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets a entrare nel settore dei mercati predittivi statunitensi</a> - parte di una spinta più ampia a dare in affitto infrastrutture regolamentate al di là del proprio exchange. La partecipazione azionaria di Citadel aggiunge il nome del più grande market maker di Wall Street a questo schema di istituzionalizzazione diversificata.</p>
<p class="ru">Crypto.com имеет регуляторные лицензии более чем в 100 юрисдикциях, включая лицензии оператора денежных переводов в более чем 40 штатах США. Выручка компании в 2024 году составила около 1,5 млрд долларов, увеличившись на 25% по сравнению примерно с 1,2 млрд долларов годом ранее, а её пользовательская база, по оценкам, выросла с 10 миллионов в начале 2021 года до более чем 100 миллионов к середине 2024 года. Компания дала понять о своих амбициях на IPO, запустив в октябре прошлого года программу предварительных заказов «IPO Early Bird», а в первом квартале этого года получила одобрение Управления контролёра денежного обращения (OCC) на создание траст-банка с федеральной лицензией. 7 июля компания предоставила инфраструктуру своего аффилированного брокера фьючерсных комиссий OG Broker, чтобы помочь публичной <a href="/ru/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets выйти на американский рынок рынков прогнозов</a> - часть более широкой стратегии сдачи в аренду регулируемой инфраструктуры за пределами собственной биржи. Доля Citadel добавляет имя крупнейшего маркет-мейкера Уолл-стрит к этой модели диверсифицированной институционализации.</p>
<p class="zh">Crypto.com在超過100個司法管轄區持有監管牌照,包括美國40多個州的匯款業務牌照。其2024年營收約為15億美元,較前一年約12億美元成長25%,用戶數估計已從2021年初的1,000萬成長至2024年中的逾1億。該公司去年10月推出「IPO Early Bird」預售訂單計畫,顯示出上市意圖,並於今年第一季獲得美國貨幣監理署(OCC)批准設立聯邦特許信託銀行。7月7日,該公司出借其關聯期貨佣金商OG Broker的基礎設施,協助上市公司<a href="/zh/blog/prospect-markets-cryptocom-cftc-prediction-entry">Prospect Markets進軍美國預測市場業務</a>——這是其在自身交易所之外出租受監管基礎設施這一更廣泛策略的一部分。Citadel的股權投資,為這種多元化機構化模式增添了華爾街最大做市商的名號。</p>

<p class="ko">다만 200억달러라는 밸류에이션이 실적에 부합하는지는 별개의 문제다. 경쟁사 코인베이스의 시가총액이 크립토 시장 상황에 따라 크게 출렁여온 전례를 감안하면, 비상장사인 크립토닷컴의 밸류에이션을 검증할 공개 지표는 마땅치 않다. 크립토닷컴의 자체 발행 토큰 CRO를 둘러싼 거버넌스 논란도 변수다 — 2025년초 크립토닷컴은 2021년 소각했던 CRO 700억개를 재발행하겠다고 제안했는데, 거버넌스 투표에서 커뮤니티의 87%가 반대했음에도 재발행을 강행한 바 있다. 이 때문에 일각에서는 이번 투자를 실질적인 사업 협력보다는, 향후 상장을 염두에 두고 200억달러 밸류에이션에 월가의 신용을 입히려는 상장 전 포석으로 해석한다. 두 해석 모두 아직 검증되지 않았으며, 마켓메이킹 사업이 실제로 가동되는지와 밸류에이션이 상장 국면에서도 유지되는지가 이를 가를 것이다.</p>
<p class="en">Whether a $20 billion valuation matches the underlying business is a separate question. Given how sharply publicly traded rival Coinbase's market cap has swung with crypto market conditions, there's little public benchmark to validate a private company's valuation like Crypto.com's. Governance controversy around its native token, CRO, is another variable: in early 2025 Crypto.com proposed reissuing 70 billion CRO tokens it had burned in 2021, and pushed ahead with the reissuance even after 87% of the community voted against it in governance. That history feeds a reading in which this deal is less about operational collaboration and more a pre-IPO move - borrowing Wall Street's credibility to defend a $20 billion mark ahead of any future listing. Neither interpretation is confirmed; what settles it will be whether the market-making business actually launches and whether the valuation holds once IPO talks turn concrete.</p>
<p class="ja">ただし、200億ドルという評価額が実績に見合うかは別問題だ。競合のコインベースの時価総額が暗号資産市場の状況に応じて大きく変動してきた前例を踏まえると、非上場企業であるクリプトドットコムの評価額を検証できる公開指標は乏しい。自社発行トークンCROをめぐるガバナンス論争も変数となる — 2025年初め、クリプトドットコムは2021年に焼却した700億枚のCROを再発行すると提案し、ガバナンス投票でコミュニティの87%が反対したにもかかわらず再発行を強行した。このため一部では、今回の投資を実質的な事業協力というより、将来の上場を見据えて200億ドルの評価額にウォール街の信用を付与しようとする上場前の布石と解釈する。両方の解釈とも未検証であり、マーケットメイキング事業が実際に稼働するか、そして上場局面でも評価額が維持されるかが分かれ目となるだろう。</p>
<p class="es">Si una valoración de 20.000 millones de dólares corresponde al negocio subyacente es una cuestión distinta. Dado lo bruscamente que ha oscilado la capitalización bursátil de su rival cotizado Coinbase según las condiciones del mercado cripto, hay poco referente público para validar la valoración de una empresa privada como Crypto.com. La controversia de gobernanza en torno a su token nativo, CRO, es otra variable: a principios de 2025 Crypto.com propuso reemitir 70.000 millones de tokens CRO que había quemado en 2021, y siguió adelante con la reemisión incluso después de que el 87% de la comunidad votara en contra en la gobernanza. Ese antecedente alimenta una lectura según la cual este acuerdo tiene menos que ver con colaboración operativa y más con una jugada previa a la salida a bolsa: tomar prestada la credibilidad de Wall Street para defender la marca de 20.000 millones de dólares antes de cualquier futura cotización. Ninguna interpretación está confirmada; lo que lo definirá será si el negocio de creación de mercado realmente se pone en marcha y si la valoración se sostiene cuando las conversaciones sobre la salida a bolsa se vuelvan concretas.</p>
<p class="de">Ob eine Bewertung von 20 Milliarden Dollar zum zugrunde liegenden Geschäft passt, ist eine andere Frage. Angesichts dessen, wie stark die Marktkapitalisierung des börsennotierten Konkurrenten Coinbase mit den Kryptomarktbedingungen geschwankt hat, gibt es kaum einen öffentlichen Maßstab, um die Bewertung eines privaten Unternehmens wie Crypto.com zu überprüfen. Die Governance-Kontroverse um den eigenen Token CRO ist eine weitere Variable: Anfang 2025 schlug Crypto.com vor, 70 Milliarden 2021 verbrannte CRO-Token wieder auszugeben, und setzte die Wiederausgabe durch, obwohl 87% der Community in einer Governance-Abstimmung dagegen votiert hatten. Diese Vorgeschichte nährt eine Lesart, wonach es bei diesem Deal weniger um operative Zusammenarbeit als um einen Schachzug vor dem Börsengang geht — die Glaubwürdigkeit der Wall Street zu leihen, um die Marke von 20 Milliarden Dollar vor einer künftigen Notierung zu verteidigen. Keine der Lesarten ist bestätigt; entscheiden wird sich das daran, ob das Market-Making-Geschäft tatsächlich anläuft und ob die Bewertung hält, sobald Börsengangsgespräche konkret werden.</p>
<p class="fr">Reste à savoir si une valorisation de 20 milliards de dollars correspond à l'activité sous-jacente. Étant donné à quel point la capitalisation boursière du rival coté Coinbase a fluctué au gré des conditions du marché crypto, il existe peu de référence publique pour valider la valorisation d'une entreprise privée comme Crypto.com. La controverse de gouvernance autour de son jeton natif, le CRO, est une autre variable : début 2025, Crypto.com a proposé de réémettre 70 milliards de jetons CRO qu'elle avait brûlés en 2021, et est allée de l'avant malgré un vote de gouvernance où 87% de la communauté s'y était opposée. Cet antécédent alimente une lecture selon laquelle cet accord relèverait moins d'une collaboration opérationnelle que d'un geste pré-IPO - emprunter la crédibilité de Wall Street pour défendre la barre des 20 milliards de dollars avant une éventuelle future cotation. Aucune des deux lectures n'est confirmée ; ce qui tranchera sera de savoir si l'activité de tenue de marché se concrétise réellement et si la valorisation tient une fois les discussions d'introduction en bourse devenues concrètes.</p>
<p class="pt">Se uma avaliação de US$ 20 bilhões condiz com o negócio subjacente é outra questão. Dado o quanto o valor de mercado da rival de capital aberto Coinbase tem oscilado conforme as condições do mercado cripto, há pouco parâmetro público para validar a avaliação de uma empresa privada como a Crypto.com. A controvérsia de governança em torno de seu token nativo, o CRO, é outra variável: no início de 2025, a Crypto.com propôs reemitir 70 bilhões de tokens CRO que havia queimado em 2021, e seguiu em frente com a reemissão mesmo depois que 87% da comunidade votou contra em uma votação de governança. Esse histórico alimenta uma leitura em que este acordo teria menos a ver com colaboração operacional e mais com uma jogada pré-IPO - tomar emprestada a credibilidade de Wall Street para defender a marca de US$ 20 bilhões antes de uma eventual listagem futura. Nenhuma das interpretações está confirmada; o que vai decidir é se o negócio de formação de mercado realmente entra em operação e se a avaliação se sustenta quando as conversas sobre IPO se tornarem concretas.</p>
<p class="tr">Ancak 20 milyar dolarlık değerlemenin altta yatan işle örtüşüp örtüşmediği ayrı bir soru. Halka açık rakip Coinbase'in piyasa değerinin kripto piyasası koşullarına göre ne kadar keskin dalgalandığı düşünüldüğünde, Crypto.com gibi özel bir şirketin değerlemesini doğrulayacak kamuya açık bir ölçüt neredeyse yok. Kendi yerel token'ı CRO etrafındaki yönetişim tartışması bir başka değişken: 2025 başında Crypto.com, 2021'de yaktığı 70 milyar CRO token'ını yeniden ihraç etmeyi önerdi ve yönetişim oylamasında topluluğun %87'si karşı çıkmasına rağmen yeniden ihracı gerçekleştirdi. Bu geçmiş, anlaşmanın operasyonel iş birliğinden çok, gelecekteki olası bir halka arz öncesinde 20 milyar dolarlık değeri Wall Street'in güvenilirliğiyle savunmaya yönelik bir hamle olduğu yönündeki bir okumayı besliyor. Hiçbir yorum doğrulanmış değil; belirleyici olan, piyasa yapıcılığı işinin gerçekten hayata geçip geçmeyeceği ve halka arz görüşmeleri somutlaştığında değerlemenin korunup korunmayacağı olacak.</p>
<p class="vi">Tuy nhiên, liệu mức định giá 20 tỷ đô la có tương xứng với hoạt động kinh doanh nền tảng hay không lại là một câu hỏi khác. Xét đến việc vốn hóa thị trường của đối thủ niêm yết công khai Coinbase đã dao động mạnh mẽ ra sao theo điều kiện thị trường tiền mã hóa, gần như không có thước đo công khai nào để xác thực định giá của một công ty tư nhân như Crypto.com. Tranh cãi về quản trị xung quanh token bản địa CRO của công ty là một biến số khác: đầu năm 2025, Crypto.com đề xuất phát hành lại 70 tỷ token CRO mà họ đã đốt vào năm 2021, và vẫn tiến hành việc phát hành lại này ngay cả sau khi 87% cộng đồng bỏ phiếu phản đối trong một cuộc bỏ phiếu quản trị. Tiền lệ đó nuôi dưỡng một cách diễn giải rằng thương vụ này ít liên quan đến hợp tác vận hành hơn mà thiên về một nước đi trước thềm IPO - mượn uy tín của Phố Wall để bảo vệ mốc định giá 20 tỷ đô la trước bất kỳ đợt niêm yết nào trong tương lai. Không cách diễn giải nào được xác nhận; điều quyết định sẽ là liệu mảng kinh doanh tạo lập thị trường có thực sự đi vào hoạt động hay không, và liệu định giá có được duy trì khi các cuộc thảo luận về IPO trở nên cụ thể hay không.</p>
<p class="id">Apakah valuasi 20 miliar dolar AS ini sesuai dengan bisnis yang mendasarinya adalah pertanyaan lain. Mengingat betapa tajamnya kapitalisasi pasar rival yang telah melantai di bursa, Coinbase, berayun mengikuti kondisi pasar kripto, hanya ada sedikit tolok ukur publik untuk memvalidasi valuasi perusahaan swasta seperti Crypto.com. Kontroversi tata kelola seputar token asli perusahaan, CRO, adalah variabel lain: pada awal 2025 Crypto.com mengusulkan penerbitan ulang 70 miliar token CRO yang telah dibakarnya pada 2021, dan tetap melanjutkan penerbitan ulang tersebut meski 87% komunitas memberikan suara menolak dalam pemungutan suara tata kelola. Riwayat itu memperkuat tafsir bahwa kesepakatan ini kurang berkaitan dengan kolaborasi operasional dan lebih merupakan langkah pra-IPO - meminjam kredibilitas Wall Street untuk mempertahankan angka 20 miliar dolar AS menjelang kemungkinan pencatatan di masa depan. Tak satu pun tafsir ini terkonfirmasi; yang akan menentukannya adalah apakah bisnis market-making ini benar-benar diluncurkan dan apakah valuasi tersebut bertahan begitu pembicaraan IPO menjadi konkret.</p>
<p class="pl">To, czy wycena na poziomie 20 miliardów dolarów odpowiada rzeczywistej działalności, to osobna kwestia. Biorąc pod uwagę, jak gwałtownie kapitalizacja rynkowa notowanego na giełdzie rywala Coinbase wahała się wraz z warunkami rynku kryptowalut, istnieje niewiele publicznych punktów odniesienia do zweryfikowania wyceny prywatnej firmy takiej jak Crypto.com. Kontrowersje wokół zarządzania natywnym tokenem CRO to kolejna zmienna: na początku 2025 roku Crypto.com zaproponowało ponowną emisję 70 miliardów tokenów CRO, które spaliło w 2021 roku, i kontynuowało tę emisję nawet po tym, jak 87% społeczności zagłosowało przeciwko temu w głosowaniu zarządczym. Ta historia karmi interpretację, według której ta transakcja ma mniej wspólnego ze współpracą operacyjną, a bardziej jest ruchem przed IPO - pożyczaniem wiarygodności Wall Street w celu obrony poziomu 20 miliardów dolarów przed ewentualnym przyszłym debiutem giełdowym. Żadna z interpretacji nie jest potwierdzona; rozstrzygnie o tym, czy działalność animatora rynku faktycznie ruszy i czy wycena utrzyma się, gdy rozmowy o IPO staną się konkretne.</p>
<p class="it">Se una valutazione di 20 miliardi di dollari corrisponda all'attività sottostante è una questione a parte. Considerando quanto bruscamente la capitalizzazione di mercato della rivale quotata in borsa Coinbase abbia oscillato con le condizioni del mercato crypto, esiste ben poco benchmark pubblico per convalidare la valutazione di una società privata come Crypto.com. La controversia di governance attorno al suo token nativo, CRO, è un'altra variabile: all'inizio del 2025 Crypto.com ha proposto di riemettere 70 miliardi di token CRO che aveva bruciato nel 2021, e ha proseguito con la riemissione anche dopo che l'87% della community aveva votato contro in una votazione di governance. Questa storia alimenta una lettura secondo cui l'accordo riguarda meno una collaborazione operativa e più una mossa pre-IPO - prendendo in prestito la credibilità di Wall Street per difendere la soglia dei 20 miliardi di dollari in vista di un'eventuale futura quotazione. Nessuna delle due interpretazioni è confermata; a deciderlo sarà se l'attività di market making verrà effettivamente avviata e se la valutazione reggerà quando le discussioni sull'IPO diventeranno concrete.</p>
<p class="ru">Соответствует ли оценка в 20 миллиардов долларов реальному бизнесу - отдельный вопрос. Учитывая, насколько резко колебалась рыночная капитализация публичного конкурента Coinbase вслед за условиями крипторынка, практически нет публичного ориентира для проверки оценки частной компании вроде Crypto.com. Ещё одна переменная - спор вокруг управления собственным токеном компании, CRO: в начале 2025 года Crypto.com предложила повторно выпустить 70 миллиардов токенов CRO, сожжённых в 2021 году, и продолжила эмиссию даже после того, как 87% сообщества проголосовали против на голосовании по управлению. Эта история подпитывает трактовку, согласно которой сделка меньше связана с операционным сотрудничеством и больше является шагом перед IPO - заимствованием репутации Уолл-стрит для защиты отметки в 20 миллиардов долларов перед возможным будущим листингом. Ни одна из трактовок не подтверждена; решающим станет то, действительно ли запустится маркет-мейкинговый бизнес и удержится ли оценка, когда переговоры об IPO станут конкретными.</p>
<p class="zh">200億美元的估值是否與其實際業務相符,是另一個問題。鑑於上市競爭對手Coinbase的市值曾隨加密貨幣市場狀況劇烈波動,幾乎沒有公開的基準可用來驗證像Crypto.com這樣一家私人公司的估值。圍繞其原生代幣CRO的治理爭議是另一個變數:2025年初,Crypto.com提議重新發行其於2021年銷毀的700億枚CRO代幣,並在社群治理投票中87%反對的情況下,仍強行推進了這次重新發行。這段歷史助長了一種解讀,即此次交易與其說是業務合作,不如說更像是一步上市前的棋——借用華爾街的信譽,為未來可能的上市預先捍衛200億美元這個估值。這兩種解讀目前皆未獲證實;真正的分水嶺將是做市業務是否真的啟動,以及一旦上市討論轉為具體,估值能否維持。</p>

<div class="ko">
<svg viewBox="0 0 700 380" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">시타델의 크립토 진출: 검토에서 지분투자까지</text>
  <g font-family="sans-serif">
    <rect x="20" y="60" width="320" height="150" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
    <text x="36" y="90" fill="#e4e4e7" font-size="15" font-weight="700">2025년 2월 (블룸버그 보도)</text>
    <text x="36" y="120" fill="#a1a1aa" font-size="13">방식: 유동성 서비스 검토</text>
    <text x="36" y="146" fill="#a1a1aa" font-size="13">지분: 없음</text>
    <text x="36" y="172" fill="#a1a1aa" font-size="13">유인구조: 수수료 기반</text>
    <rect x="360" y="60" width="320" height="150" rx="10" fill="#1a1005" stroke="#f7931a" stroke-width="1.6"/>
    <text x="376" y="90" fill="#fbbf24" font-size="15" font-weight="700">2026년 7월16일 (로이터·코인데스크)</text>
    <text x="376" y="120" fill="#e4e4e7" font-size="13">방식: $400M 지분 투자</text>
    <text x="376" y="146" fill="#e4e4e7" font-size="13">밸류에이션: $20B 확정</text>
    <text x="376" y="172" fill="#fbbf24" font-size="13">유인구조: 플랫폼 성장과 연동</text>
    <line x1="20" y1="234" x2="680" y2="234" stroke="#27272a" stroke-width="1"/>
    <text x="20" y="262" fill="#e4e4e7" font-size="14" font-weight="700">4억달러</text>
    <text x="20" y="284" fill="#a1a1aa" font-size="13">시타델의 크립토닷컴 지분 투자액</text>
    <text x="240" y="262" fill="#e4e4e7" font-size="14" font-weight="700">200억달러</text>
    <text x="240" y="284" fill="#a1a1aa" font-size="13">크립토닷컴 확정 밸류에이션</text>
    <text x="470" y="262" fill="#e4e4e7" font-size="14" font-weight="700">17개월</text>
    <text x="470" y="284" fill="#a1a1aa" font-size="13">검토 보도 후 실투자까지 소요기간</text>
    <text x="20" y="360" fill="#52525b" font-size="12">출처: Bloomberg(2025.2), Reuters·CoinDesk(2026.7.16)</text>
  </g>
</svg>
</div>
<div class="en es de fr pt tr id pl it ru zh">
<svg viewBox="0 0 700 380" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Citadel's Crypto Push: From Exploring to Equity</text>
  <g font-family="sans-serif">
    <rect x="20" y="60" width="320" height="150" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
    <text x="36" y="90" fill="#e4e4e7" font-size="15" font-weight="700">Feb 2025 (Bloomberg report)</text>
    <text x="36" y="120" fill="#a1a1aa" font-size="13">Approach: exploring liquidity services</text>
    <text x="36" y="146" fill="#a1a1aa" font-size="13">Equity: none</text>
    <text x="36" y="172" fill="#a1a1aa" font-size="13">Incentive: fee-based</text>
    <rect x="360" y="60" width="320" height="150" rx="10" fill="#1a1005" stroke="#f7931a" stroke-width="1.6"/>
    <text x="376" y="90" fill="#fbbf24" font-size="15" font-weight="700">Jul 16, 2026 (Reuters, CoinDesk)</text>
    <text x="376" y="120" fill="#e4e4e7" font-size="13">Approach: $400M equity investment</text>
    <text x="376" y="146" fill="#e4e4e7" font-size="13">Valuation: $20B confirmed</text>
    <text x="376" y="172" fill="#fbbf24" font-size="13">Incentive: tied to platform growth</text>
    <line x1="20" y1="234" x2="680" y2="234" stroke="#27272a" stroke-width="1"/>
    <text x="20" y="262" fill="#e4e4e7" font-size="14" font-weight="700">$400M</text>
    <text x="20" y="284" fill="#a1a1aa" font-size="13">Citadel's equity stake in Crypto.com</text>
    <text x="240" y="262" fill="#e4e4e7" font-size="14" font-weight="700">$20B</text>
    <text x="240" y="284" fill="#a1a1aa" font-size="13">Crypto.com's confirmed valuation</text>
    <text x="470" y="262" fill="#e4e4e7" font-size="14" font-weight="700">17 months</text>
    <text x="470" y="284" fill="#a1a1aa" font-size="13">From report to actual investment</text>
    <text x="20" y="360" fill="#52525b" font-size="12">Source: Bloomberg (2/2025), Reuters, CoinDesk (7/16/2026)</text>
  </g>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 380" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">シタデルの暗号資産進出:検討から株式投資まで</text>
  <g font-family="sans-serif">
    <rect x="20" y="60" width="320" height="150" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
    <text x="36" y="90" fill="#e4e4e7" font-size="15" font-weight="700">2025年2月(ブルームバーグ報道)</text>
    <text x="36" y="120" fill="#a1a1aa" font-size="13">方式:流動性サービス検討</text>
    <text x="36" y="146" fill="#a1a1aa" font-size="13">持分:なし</text>
    <text x="36" y="172" fill="#a1a1aa" font-size="13">誘因構造:手数料ベース</text>
    <rect x="360" y="60" width="320" height="150" rx="10" fill="#1a1005" stroke="#f7931a" stroke-width="1.6"/>
    <text x="376" y="90" fill="#fbbf24" font-size="15" font-weight="700">2026年7月16日(ロイター・コインデスク)</text>
    <text x="376" y="120" fill="#e4e4e7" font-size="13">方式:4億ドル株式投資</text>
    <text x="376" y="146" fill="#e4e4e7" font-size="13">評価額:200億ドル確定</text>
    <text x="376" y="172" fill="#fbbf24" font-size="13">誘因構造:プラットフォーム成長に連動</text>
    <line x1="20" y1="234" x2="680" y2="234" stroke="#27272a" stroke-width="1"/>
    <text x="20" y="262" fill="#e4e4e7" font-size="14" font-weight="700">4億ドル</text>
    <text x="20" y="284" fill="#a1a1aa" font-size="13">シタデルのクリプトドットコム出資額</text>
    <text x="240" y="262" fill="#e4e4e7" font-size="14" font-weight="700">200億ドル</text>
    <text x="240" y="284" fill="#a1a1aa" font-size="13">クリプトドットコムの確定評価額</text>
    <text x="470" y="262" fill="#e4e4e7" font-size="14" font-weight="700">17カ月</text>
    <text x="470" y="284" fill="#a1a1aa" font-size="13">検討報道から実投資までの期間</text>
    <text x="20" y="360" fill="#52525b" font-size="12">出典:ブルームバーグ(2025年2月)、ロイター・コインデスク(2026年7月16日)</text>
  </g>
</svg>
</div>
<div class="vi">
<svg viewBox="0 0 700 380" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Bước Tiến Crypto Của Citadel: Từ Cân Nhắc Đến Đầu Tư Cổ Phần</text>
  <g font-family="sans-serif">
    <rect x="20" y="60" width="320" height="150" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
    <text x="36" y="90" fill="#e4e4e7" font-size="15" font-weight="700">Tháng 2/2025 (Bloomberg)</text>
    <text x="36" y="120" fill="#a1a1aa" font-size="13">Cách tiếp cận: cân nhắc dịch vụ</text>
    <text x="36" y="146" fill="#a1a1aa" font-size="13">Cổ phần: không có</text>
    <text x="36" y="172" fill="#a1a1aa" font-size="13">Động lực: dựa trên phí</text>
    <rect x="360" y="60" width="320" height="150" rx="10" fill="#1a1005" stroke="#f7931a" stroke-width="1.6"/>
    <text x="376" y="90" fill="#fbbf24" font-size="15" font-weight="700">16/7/2026 (Reuters, CoinDesk)</text>
    <text x="376" y="120" fill="#e4e4e7" font-size="13">Cách tiếp cận: đầu tư 400 triệu $</text>
    <text x="376" y="146" fill="#e4e4e7" font-size="13">Định giá: xác nhận 20 tỷ $</text>
    <text x="376" y="172" fill="#fbbf24" font-size="13">Động lực: gắn với tăng trưởng</text>
    <line x1="20" y1="234" x2="680" y2="234" stroke="#27272a" stroke-width="1"/>
    <text x="20" y="262" fill="#e4e4e7" font-size="14" font-weight="700">400 triệu $</text>
    <text x="20" y="284" fill="#a1a1aa" font-size="13">Cổ phần Citadel tại Crypto.com</text>
    <text x="240" y="262" fill="#e4e4e7" font-size="14" font-weight="700">20 tỷ $</text>
    <text x="240" y="284" fill="#a1a1aa" font-size="13">Định giá xác nhận của Crypto.com</text>
    <text x="470" y="262" fill="#e4e4e7" font-size="14" font-weight="700">17 tháng</text>
    <text x="470" y="284" fill="#a1a1aa" font-size="13">Từ báo cáo đến đầu tư thực tế</text>
    <text x="20" y="360" fill="#52525b" font-size="12">Nguồn: Bloomberg (2/2025), Reuters, CoinDesk (16/7/2026)</text>
  </g>
</svg>
</div>

<div class="box ko">💡 <strong>시사점:</strong> 관전포인트 세 가지 — (1) 시타델이 실제로 크립토닷컴 등 거래소에서 마켓메이킹을 개시하는지, (2) 200억달러 밸류에이션이 상장 논의가 본격화될 때도 유지되는지, (3) 마켓메이커의 거래소 지분 보유가 주식시장의 PFOF 논쟁처럼 이해상충 규제 이슈로 번지는지.</div>
<div class="box en">💡 <strong>Takeaway:</strong> Three things worth watching: (1) whether Citadel actually begins market-making at Crypto.com and other exchanges; (2) whether the $20 billion valuation holds once IPO discussions turn concrete; (3) whether a market maker holding equity in an exchange draws the same conflict-of-interest scrutiny as the PFOF debate in equities.</div>
<div class="box ja">💡 <strong>示唆:</strong> 注目点は3つ — (1)シタデルが実際にクリプトドットコムなど取引所でマーケットメイキングを開始するか、(2)200億ドルの評価額が上場議論が本格化した際にも維持されるか、(3)マーケットメイカーによる取引所の株式保有が、株式市場のPFOF論争のような利益相反規制の問題に発展するか。</div>
<div class="box es">💡 <strong>Conclusión:</strong> tres cosas a vigilar: (1) si Citadel realmente comienza a hacer creación de mercado en Crypto.com y otros exchanges; (2) si la valoración de 20.000 millones de dólares se sostiene cuando las conversaciones de salida a bolsa se vuelvan concretas; (3) si que un creador de mercado posea participación en un exchange atrae el mismo escrutinio por conflicto de interés que el debate del PFOF en acciones.</div>
<div class="box de">💡 <strong>Fazit:</strong> Drei Dinge sind zu beobachten: (1) ob Citadel tatsächlich mit Market Making bei Crypto.com und anderen Börsen beginnt; (2) ob die 20-Milliarden-Dollar-Bewertung hält, sobald Börsengangsgespräche konkret werden; (3) ob ein Market Maker mit Beteiligung an einer Börse dieselbe Interessenkonflikt-Prüfung auf sich zieht wie die PFOF-Debatte bei Aktien.</div>
<div class="box fr">💡 <strong>À retenir :</strong> trois choses à surveiller : (1) si Citadel commence réellement à faire de la tenue de marché chez Crypto.com et d'autres bourses ; (2) si la valorisation de 20 milliards de dollars tient une fois les discussions d'IPO devenues concrètes ; (3) si le fait qu'un teneur de marché détienne une participation dans une bourse attire le même examen pour conflit d'intérêts que le débat sur le PFOF dans les actions.</div>
<div class="box pt">💡 <strong>Conclusão:</strong> três pontos merecem atenção: (1) se a Citadel realmente começa a atuar como formadora de mercado na Crypto.com e em outras exchanges; (2) se a avaliação de US$ 20 bilhões se sustenta quando as conversas de IPO se tornarem concretas; (3) se o fato de uma formadora de mercado deter participação em uma exchange atrai o mesmo escrutínio de conflito de interesses do debate sobre PFOF no mercado acionário.</div>
<div class="box tr">💡 <strong>Sonuç:</strong> İzlenmesi gereken üç şey var: (1) Citadel'in Crypto.com ve diğer borsalarda gerçekten piyasa yapıcılığına başlayıp başlamayacağı; (2) halka arz görüşmeleri somutlaştığında 20 milyar dolarlık değerlemenin korunup korunmayacağı; (3) bir piyasa yapıcının bir borsada hisseye sahip olmasının, hisse senetlerindeki PFOF tartışmasına benzer bir çıkar çatışması incelemesi çekip çekmeyeceği.</div>
<div class="box vi">💡 <strong>Điểm mấu chốt:</strong> Có ba điều cần theo dõi: (1) liệu Citadel có thực sự bắt đầu tạo lập thị trường tại Crypto.com và các sàn khác hay không; (2) liệu mức định giá 20 tỷ đô la có được duy trì khi các cuộc thảo luận IPO trở nên cụ thể hay không; (3) liệu việc một nhà tạo lập thị trường nắm giữ cổ phần tại một sàn giao dịch có thu hút sự giám sát về xung đột lợi ích tương tự cuộc tranh luận PFOF trong thị trường cổ phiếu hay không.</div>
<div class="box id">💡 <strong>Kesimpulan:</strong> Tiga hal yang layak diperhatikan: (1) apakah Citadel benar-benar mulai melakukan market-making di Crypto.com dan bursa lain; (2) apakah valuasi 20 miliar dolar AS bertahan begitu pembicaraan IPO menjadi konkret; (3) apakah kepemilikan saham pembuat pasar di sebuah bursa menarik pengawasan konflik kepentingan yang sama seperti perdebatan PFOF di pasar saham.</div>
<div class="box pl">💡 <strong>Wniosek:</strong> Trzy rzeczy warte obserwacji: (1) czy Citadel faktycznie zacznie działać jako animator rynku na Crypto.com i innych giełdach; (2) czy wycena 20 miliardów dolarów utrzyma się, gdy rozmowy o IPO staną się konkretne; (3) czy posiadanie przez animatora rynku udziałów w giełdzie wywoła taką samą kontrolę pod kątem konfliktu interesów, jak debata o PFOF na rynku akcji.</div>
<div class="box it">💡 <strong>Conclusione:</strong> Tre cose da osservare: (1) se Citadel inizierà davvero a fare market making su Crypto.com e altri exchange; (2) se la valutazione da 20 miliardi di dollari reggerà quando le discussioni sull'IPO diventeranno concrete; (3) se il fatto che un market maker detenga una partecipazione in un exchange attirerà lo stesso controllo per conflitto di interessi del dibattito sul PFOF nel mercato azionario.</div>
<div class="box ru">💡 <strong>Вывод:</strong> Три момента, за которыми стоит следить: (1) действительно ли Citadel начнёт маркет-мейкинг на Crypto.com и других биржах; (2) удержится ли оценка в 20 миллиардов долларов, когда переговоры об IPO станут конкретными; (3) вызовет ли владение маркет-мейкером долей в бирже такой же надзор за конфликтом интересов, как дебаты о PFOF на рынке акций.</div>
<div class="box zh">💡 <strong>重點:</strong> 有三件事值得關注:(1) Citadel是否真的會在Crypto.com及其他交易所開始做市;(2) 一旦上市討論轉為具體,200億美元的估值能否維持;(3) 做市商持有交易所股權,是否會招致與股票市場PFOF爭議相同程度的利益衝突審查。</div>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <text x="60" y="260" fill="#f4f4f5" font-size="160" font-weight="bold">$400M</text>
  <text x="60" y="330" fill="#06b6d4" font-size="44" font-weight="bold">CRYPTO.COM</text>
  <text x="60" y="470" fill="#f4f4f5" font-size="130" font-weight="bold">$20B</text>
  <text x="60" y="522" fill="#06b6d4" font-size="40" font-weight="bold">VALUATION</text>
</svg></div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 로이터(Reuters), 코인데스크(CoinDesk), 블룸버그(Bloomberg), 트레이딩뷰(TradingView), 포춘(Fortune), 파이먼츠(PYMNTS), 크립토노미스트(Cryptonomist), 코인로(CoinLaw), 크런치베이스(Crunchbase)</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: ロイター(Reuters)、コインデスク(CoinDesk)、ブルームバーグ(Bloomberg)、トレーディングビュー(TradingView)、フォーチュン(Fortune)、ピメンツ(PYMNTS)、クリプトノミスト(Cryptonomist)、コインロー(CoinLaw)、クランチベース(Crunchbase)</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="id" style="font-size:12px;color:#52525b;margin-top:24px">Sumber: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="pl" style="font-size:12px;color:#52525b;margin-top:24px">Źródła: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="it" style="font-size:12px;color:#52525b;margin-top:24px">Fonti: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="ru" style="font-size:12px;color:#52525b;margin-top:24px">Источники: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>
<p class="zh" style="font-size:12px;color:#52525b;margin-top:24px">資料來源: Reuters, CoinDesk, Bloomberg, TradingView, Fortune, PYMNTS, Cryptonomist, CoinLaw, Crunchbase</p>

<?php require __DIR__.'/_footer.php'; ?>
