<?php $slug = 'false-consensus-effect-crypto-twitter-echo-chamber'; require __DIR__.'/_header.php'; ?>

<p class="ko">1977년 스탠퍼드대 사회심리학자 리 로스와 데이비드 그린, 파멜라 하우스는 학생들에게 "Eat at Joe's"라고 적힌 샌드위치보드를 걸치고 캠퍼스를 30분간 돌아달라고 부탁했다. 절반은 승낙했고 절반은 거절했다. 두 집단 모두에게 같은 질문을 던졌다 — 다른 학생 중 몇 퍼센트가 당신과 같은 선택을 할 것 같은가. 승낙한 학생도, 거절한 학생도 하나같이 자신의 선택이 다수라고 답했다. 이 실험은 '허위 합의 효과(false consensus effect)'라는 이름으로 학계에 자리 잡았고, 발표 이후 10년 동안 이 현상 하나만 다룬 논문이 50편 가까이 쏟아졌다.</p>
<p class="en">In 1977, Stanford social psychologists Lee Ross, David Greene, and Pamela House asked students to wear a sandwich board reading "Eat at Joe's" and walk around campus for thirty minutes. About half agreed; half refused. The researchers then asked both groups the same question — what percentage of other students did they think would make the same choice they had? Both the ones who agreed and the ones who refused overwhelmingly believed their own choice was the majority one. The experiment became the foundation of what's now called the "false consensus effect," and in the decade after it was published, nearly fifty papers appeared studying this phenomenon alone.</p>
<p class="ja">1977年、スタンフォード大学の社会心理学者リー・ロス、デイヴィッド・グリーン、パメラ・ハウスは、学生たちに「Eat at Joe's」と書かれたサンドイッチボードを身につけてキャンパスを30分間歩き回るよう依頼した。約半数が承諾し、半数が拒否した。研究者らは両グループに同じ質問をした――他の学生のうち何パーセントが自分と同じ選択をすると思うか。承諾した学生も拒否した学生も、口を揃えて自分の選択が多数派だと答えた。この実験は「偽の合意効果(false consensus effect)」と呼ばれる現象の土台となり、発表後10年間でこの現象だけを扱った論文が50本近く発表された。</p>
<p class="es">En 1977, los psicólogos sociales de Stanford Lee Ross, David Greene y Pamela House pidieron a un grupo de estudiantes que se pusieran un cartel de sándwich con la leyenda "Eat at Joe's" y caminaran por el campus durante treinta minutos. Cerca de la mitad aceptó; la otra mitad se negó. Luego preguntaron lo mismo a ambos grupos: ¿qué porcentaje de otros estudiantes creían que haría la misma elección que ellos? Tanto los que aceptaron como los que se negaron creyeron, de forma abrumadora, que su propia elección era la mayoritaria. El experimento se convirtió en la base de lo que hoy se llama 'efecto de falso consenso' (false consensus effect), y en la década posterior a su publicación se produjeron casi cincuenta artículos dedicados solo a este fenómeno.</p>
<p class="de">1977 baten die Stanford-Sozialpsychologen Lee Ross, David Greene und Pamela House Studierende, ein Werbeschild mit der Aufschrift „Eat at Joe's" umzuhängen und dreißig Minuten lang über den Campus zu laufen. Etwa die Hälfte willigte ein, die andere Hälfte lehnte ab. Anschließend stellten die Forscher beiden Gruppen dieselbe Frage: Wie viel Prozent der anderen Studierenden würden ihrer Meinung nach dieselbe Wahl treffen wie sie selbst? Sowohl diejenigen, die zugestimmt hatten, als auch diejenigen, die abgelehnt hatten, glaubten überwältigend, ihre eigene Wahl sei die der Mehrheit. Das Experiment wurde zur Grundlage dessen, was heute als „falscher Konsens-Effekt" (false consensus effect) bezeichnet wird, und in dem Jahrzehnt nach seiner Veröffentlichung erschienen fast fünfzig Fachartikel, die sich allein mit diesem Phänomen befassten.</p>
<p class="fr">En 1977, les psychologues sociaux de Stanford Lee Ross, David Greene et Pamela House ont demandé à des étudiants de porter un panneau publicitaire portant l'inscription « Eat at Joe's » et de marcher sur le campus pendant trente minutes. Environ la moitié a accepté, l'autre moitié a refusé. Les chercheurs ont ensuite posé la même question aux deux groupes : quel pourcentage des autres étudiants pensaient-ils feraient le même choix qu'eux ? Aussi bien ceux qui avaient accepté que ceux qui avaient refusé ont massivement estimé que leur propre choix était majoritaire. L'expérience est devenue le fondement de ce qu'on appelle aujourd'hui « l'effet de faux consensus » (false consensus effect), et dans la décennie suivant sa publication, près de cinquante articles ont été consacrés à ce seul phénomène.</p>
<p class="pt">Em 1977, os psicólogos sociais de Stanford Lee Ross, David Greene e Pamela House pediram a estudantes que vestissem um cartaz do tipo sanduíche com os dizeres "Eat at Joe's" e caminhassem pelo campus durante trinta minutos. Cerca de metade aceitou; a outra metade recusou. Os pesquisadores então fizeram a mesma pergunta aos dois grupos: que porcentagem dos outros estudantes eles achavam que faria a mesma escolha que eles? Tanto os que aceitaram quanto os que recusaram acreditavam, de forma esmagadora, que sua própria escolha era a majoritária. O experimento se tornou a base do que hoje se chama 'efeito do falso consenso' (false consensus effect), e na década seguinte à publicação, quase cinquenta artigos foram dedicados apenas a esse fenômeno.</p>
<p class="tr">1977'de Stanford'lı sosyal psikologlar Lee Ross, David Greene ve Pamela House, öğrencilerden üzerinde "Eat at Joe's" yazan bir tabela taşıyarak kampüste otuz dakika yürümelerini istedi. Yaklaşık yarısı kabul etti, yarısı reddetti. Araştırmacılar ardından her iki gruba da aynı soruyu sordu: diğer öğrencilerin yüzde kaçının kendileriyle aynı seçimi yapacağını düşünüyorlardı? Hem kabul edenler hem de reddedenler, ezici bir çoğunlukla kendi seçimlerinin çoğunluğun tercihi olduğuna inandı. Bu deney, bugün "yanlış fikir birliği etkisi" (false consensus effect) olarak adlandırılan olgunun temelini oluşturdu ve yayımlanmasının ardından geçen on yıl içinde yalnızca bu olguyu ele alan neredeyse elli makale yayımlandı.</p>
<p class="vi">Năm 1977, các nhà tâm lý học xã hội tại Stanford là Lee Ross, David Greene và Pamela House đã yêu cầu sinh viên đeo một tấm biển quảng cáo ghi dòng chữ "Eat at Joe's" và đi bộ quanh khuôn viên trường trong ba mươi phút. Khoảng một nửa đồng ý, một nửa từ chối. Sau đó, các nhà nghiên cứu hỏi cả hai nhóm cùng một câu hỏi — họ nghĩ bao nhiêu phần trăm sinh viên khác sẽ đưa ra lựa chọn giống mình. Cả nhóm đồng ý lẫn nhóm từ chối đều áp đảo tin rằng lựa chọn của chính mình là lựa chọn của số đông. Thí nghiệm này trở thành nền tảng cho hiện tượng ngày nay được gọi là "hiệu ứng đồng thuận giả" (false consensus effect), và trong thập kỷ sau khi công bố, gần năm mươi bài báo đã được xuất bản chỉ để nghiên cứu hiện tượng này.</p>

<p class="ko">이 편향이 비트코인 트레이더에게 특히 위험한 이유는, 확신을 확인하는 창구가 거의 예외 없이 하나이기 때문이다 — 소셜미디어 타임라인이다. 타임라인의 목소리가 강세 일색이면 트레이더는 '시장이 강세'라고 느끼고, 그 느낌은 실제 시장 참여자의 분포나 포지셔닝 데이터를 확인하지 않은 채로 확신으로 굳어진다. 이 칼럼의 주장은 하나다 — 크립토 트위터에서 느끼는 '모두가 동의한다'는 감각은 시장의 합의가 아니라 자기선택된 소수와 봇이 만들어낸 착시이며, 그 착시가 레버리지로 전환되는 지점에서 사이클의 정점과 바닥이 만들어진다.</p>
<p class="en">This bias is especially dangerous for Bitcoin traders because there's essentially one window through which they check their own conviction — the social media timeline. When the voices on that timeline lean uniformly bullish, a trader feels that "the market is bullish," and that feeling hardens into certainty without ever being checked against the actual distribution of market participants or real positioning data. This column makes one argument: the sense that "everyone agrees" on crypto Twitter isn't market consensus at all. It's an illusion manufactured by a self-selected minority and by bots — and it's at the point where that illusion converts into leverage that cycle tops and bottoms get made.</p>
<p class="ja">このバイアスがビットコイントレーダーにとって特に危険なのは、自分の確信を確かめる窓口がほぼ例外なく一つしかないからだ――ソーシャルメディアのタイムラインである。タイムラインの声が強気一色であれば、トレーダーは「市場は強気だ」と感じ、その感覚は実際の市場参加者の分布やポジショニングデータを確認しないまま確信へと固まっていく。本コラムの主張は一つだ――クリプトツイッターで感じる「みんなが同意している」という感覚は市場の合意ではなく、自己選択された少数派とボットが作り出した錯覚であり、その錯覚がレバレッジへと転換される地点でサイクルの天井と底が作られる。</p>
<p class="es">Este sesgo es especialmente peligroso para los operadores de Bitcoin porque existe, prácticamente sin excepción, una única ventana desde la cual comprueban su propia convicción: la línea de tiempo de las redes sociales. Cuando las voces de esa línea de tiempo se inclinan de forma uniforme hacia lo alcista, el operador siente que 'el mercado es alcista', y esa sensación se endurece hasta convertirse en certeza sin haber sido contrastada nunca con la distribución real de los participantes del mercado ni con datos reales de posicionamiento. El argumento de esta columna es uno solo: la sensación de que 'todos están de acuerdo' en crypto Twitter no es en absoluto el consenso del mercado. Es una ilusión fabricada por una minoría autoseleccionada y por bots — y es en el punto donde esa ilusión se convierte en apalancamiento donde se forman los techos y los suelos del ciclo.</p>
<p class="de">Dieser Bias ist für Bitcoin-Trader besonders gefährlich, weil es praktisch nur ein einziges Fenster gibt, durch das sie ihre eigene Überzeugung prüfen — die Social-Media-Timeline. Wenn die Stimmen in dieser Timeline durchweg bullisch klingen, hat der Trader das Gefühl, „der Markt ist bullisch", und dieses Gefühl verfestigt sich zur Gewissheit, ohne je an der tatsächlichen Verteilung der Marktteilnehmer oder an echten Positionierungsdaten überprüft zu werden. Diese Kolumne vertritt genau eine These: Das Gefühl, dass auf Crypto-Twitter „alle einer Meinung sind", ist überhaupt kein Marktkonsens. Es ist eine Illusion, erzeugt von einer selbstselektierten Minderheit und von Bots — und genau an dem Punkt, an dem sich diese Illusion in Hebelwirkung verwandelt, entstehen die Höchst- und Tiefststände eines Zyklus.</p>
<p class="fr">Ce biais est particulièrement dangereux pour les traders de Bitcoin car il existe, presque sans exception, une seule fenêtre par laquelle ils vérifient leur propre conviction : le fil d'actualité des réseaux sociaux. Quand les voix de ce fil penchent uniformément vers le haussier, le trader ressent que « le marché est haussier », et ce sentiment se durcit en certitude sans jamais être confronté à la distribution réelle des participants du marché ni aux données réelles de positionnement. Cette chronique défend une seule idée : le sentiment que « tout le monde est d'accord » sur crypto Twitter n'est en rien un consensus de marché. C'est une illusion fabriquée par une minorité autosélectionnée et par des bots — et c'est au moment où cette illusion se convertit en levier que se forment les sommets et les creux du cycle.</p>
<p class="pt">Esse viés é especialmente perigoso para traders de Bitcoin porque existe, praticamente sem exceção, uma única janela pela qual eles verificam sua própria convicção — a timeline das redes sociais. Quando as vozes dessa timeline se inclinam uniformemente para o lado altista, o trader sente que "o mercado está altista", e essa sensação se transforma em certeza sem nunca ser confrontada com a distribuição real dos participantes do mercado ou com dados reais de posicionamento. Esta coluna defende um único argumento: a sensação de que "todo mundo concorda" no crypto Twitter não é, de forma alguma, o consenso do mercado. É uma ilusão fabricada por uma minoria autosselecionada e por bots — e é no ponto em que essa ilusão se converte em alavancagem que se formam os topos e fundos do ciclo.</p>
<p class="tr">Bu yanlılık Bitcoin trader'ları için özellikle tehlikelidir, çünkü kanaatlerini doğruladıkları pencere neredeyse istisnasız tektir — sosyal medya zaman akışı. Bu akıştaki sesler tek tip biçimde yükselişçi olduğunda, trader "piyasa yükselişte" hissine kapılır ve bu his, gerçek piyasa katılımcı dağılımı veya gerçek pozisyon verileriyle hiç karşılaştırılmadan kesinliğe dönüşür. Bu yazının tek bir savı var: kripto Twitter'da hissedilen "herkes hemfikir" duygusu piyasa fikir birliği değildir. Bu, kendi kendini seçmiş bir azınlık ve botlar tarafından üretilen bir yanılsamadır — ve döngünün tepe ve dip noktaları, tam da bu yanılsamanın kaldıraca dönüştüğü noktada oluşur.</p>
<p class="vi">Thiên kiến này đặc biệt nguy hiểm đối với các trader Bitcoin vì gần như không có ngoại lệ, họ chỉ có một cửa sổ duy nhất để kiểm chứng niềm tin của chính mình — dòng thời gian mạng xã hội. Khi các tiếng nói trên dòng thời gian đó đồng loạt nghiêng về phía tăng giá, trader cảm thấy "thị trường đang tăng giá", và cảm giác đó cứng lại thành niềm tin chắc chắn mà chưa bao giờ được đối chiếu với phân bố thực tế của những người tham gia thị trường hay dữ liệu vị thế thực sự. Bài viết này chỉ đưa ra một luận điểm: cảm giác "mọi người đều đồng ý" trên crypto Twitter hoàn toàn không phải là sự đồng thuận của thị trường. Đó là một ảo giác được tạo ra bởi một nhóm thiểu số tự chọn và các bot — và chính tại điểm ảo giác đó chuyển hóa thành đòn bẩy, đỉnh và đáy của chu kỳ được hình thành.</p>

<h2 class="ko">표본이 아니라 반향실이다</h2>
<h2 class="en">A Sample of One, Mistaken for the Room</h2>
<h2 class="ja">標本ではなく反響室だ</h2>
<h2 class="es">Una Muestra de Uno, Confundida con la Sala Entera</h2>
<h2 class="de">Keine Stichprobe, sondern ein Echoraum</h2>
<h2 class="fr">Un Échantillon d'Un Seul, Pris pour la Salle Entière</h2>
<h2 class="pt">Uma Amostra de Um, Confundida com a Sala Inteira</h2>
<h2 class="tr">Bir Kişilik Örneklem, Odanın Tamamı Sanılıyor</h2>
<h2 class="vi">Một Mẫu Duy Nhất Bị Nhầm Là Cả Căn Phòng</h2>

<p class="ko">미국 성인 중 실제로 비트코인이나 다른 암호화폐를 보유한 비율을 묻는 설문은 조사 기관마다 결과가 크게 갈린다. 2025년 말 기준 미 연방준비제도 설문은 10%, 갤럽은 2025년 7월 조사에서 14%, 퓨리서치센터는 2021년 조사에서 16%, 모틀리풀은 2026년 조사에서 22%, 시큐리티닷오알지는 2025년 조사에서 30%라는 숫자를 내놨다 — 같은 질문에 대한 답이 조사마다 최대 3배 가까이 벌어진다는 뜻이다. 직접 보유만 셀지, ETF 보유까지 포함할지, 표본을 어떻게 뽑을지에 따라 이 정도 격차가 벌어진다는 사실 자체가 '얼마나 많은 사람이 동의하는가'라는 질문에 정밀하게 답하기가 애초에 얼마나 어려운지를 보여준다.</p>
<p class="en">Surveys asking what share of American adults actually own Bitcoin or other cryptocurrency diverge sharply depending on who's asking. The U.S. Federal Reserve's late-2025 survey put the figure at 10%; Gallup's July 2025 poll put it at 14%; Pew Research Center's 2021 survey put it at 16%; The Motley Fool's 2026 survey put it at 22%; Security.org's 2025 report put it at 30% — meaning the same question, asked by different pollsters, produces answers that differ by nearly threefold. The fact that methodology alone — whether to count direct holdings only or include ETF exposure, how the sample is drawn — can swing the number this much shows just how hard "how many people agree" is to answer precisely in the first place.</p>
<p class="ja">米国成人のうち実際にビットコインや他の暗号資産を保有している割合を尋ねる調査は、調査機関によって結果が大きく分かれる。2025年末時点の米連邦準備制度の調査では10%、ギャラップの2025年7月調査では14%、ピュー・リサーチ・センターの2021年調査では16%、モトリーフールの2026年調査では22%、セキュリティ・オルグの2025年調査では30%という数字が出た――同じ質問への答えが調査によって最大3倍近く開くということだ。直接保有だけを数えるかETF保有まで含めるか、標本をどう抽出するかによってこれほどの差が出るという事実自体が、「どれだけの人が同意しているか」という問いに正確に答えることがそもそもいかに難しいかを物語っている。</p>
<p class="es">Las encuestas que preguntan qué porcentaje de adultos estadounidenses posee realmente bitcoin u otra criptomoneda divergen enormemente según quién pregunte. La encuesta de la Reserva Federal de EE.UU. a finales de 2025 situó la cifra en 10%; la de Gallup de julio de 2025 la situó en 14%; la del Pew Research Center de 2021 la situó en 16%; la de The Motley Fool de 2026 la situó en 22%; el informe de Security.org de 2025 la situó en 30% — es decir, la misma pregunta, formulada por distintas encuestadoras, produce respuestas que difieren en casi el triple. El solo hecho de que la metodología — si se cuentan solo las tenencias directas o también la exposición vía ETF, cómo se extrae la muestra — pueda hacer variar tanto la cifra demuestra lo difícil que resulta, de entrada, responder con precisión a la pregunta de cuánta gente está de acuerdo.</p>
<p class="de">Umfragen zu der Frage, wie viele US-Erwachsene tatsächlich Bitcoin oder andere Kryptowährungen besitzen, gehen je nach Anbieter stark auseinander. Die Umfrage der US-Notenbank Fed von Ende 2025 nannte 10%, Gallup im Juli 2025 14%, das Pew Research Center 2021 16%, The Motley Fool 2026 22%, Security.org 2025 30% — dieselbe Frage liefert je nach Erhebung Antworten, die sich um fast das Dreifache unterscheiden. Allein die Tatsache, dass Methodik — ob nur direkte Bestände gezählt werden oder auch ETF-Exposure, wie die Stichprobe gezogen wird — eine derart große Spanne erzeugen kann, zeigt, wie schwer die Frage, wie viele Menschen zustimmen, überhaupt präzise zu beantworten ist.</p>
<p class="fr">Les sondages mesurant la part des adultes américains détenant réellement du bitcoin ou une autre cryptomonnaie divergent fortement selon qui les mène. L'enquête de la Réserve fédérale américaine fin 2025 avançait le chiffre de 10% ; celle de Gallup en juillet 2025, 14% ; celle du Pew Research Center en 2021, 16% ; celle de The Motley Fool en 2026, 22% ; le rapport de Security.org en 2025, 30% — soit une même question qui, posée par des sondeurs différents, produit des réponses qui varient presque du simple au triple. Le simple fait que la méthodologie — compter seulement les détentions directes ou aussi l'exposition via ETF, la manière dont l'échantillon est constitué — puisse faire varier le chiffre à ce point montre à quel point il est difficile, en soi, de répondre précisément à la question de savoir combien de personnes sont d'accord.</p>
<p class="pt">As pesquisas que perguntam qual a porcentagem de adultos americanos que realmente possui bitcoin ou outra criptomoeda divergem muito dependendo de quem pergunta. A pesquisa do Federal Reserve dos EUA no fim de 2025 apontou 10%; a da Gallup, em julho de 2025, apontou 14%; a do Pew Research Center, em 2021, apontou 16%; a da Motley Fool, em 2026, apontou 22%; o relatório da Security.org, em 2025, apontou 30% — ou seja, a mesma pergunta, feita por institutos diferentes, produz respostas que diferem em quase o triplo. O simples fato de que a metodologia — contar apenas posses diretas ou incluir também exposição via ETF, como a amostra é selecionada — possa fazer o número variar tanto mostra o quão difícil é, de saída, responder com precisão à pergunta de quantas pessoas concordam.</p>
<p class="tr">Amerikalı yetişkinlerin ne kadarının gerçekten bitcoin veya başka bir kripto para birimine sahip olduğunu soran anketler, kimin sorduğuna bağlı olarak büyük ölçüde farklılık gösteriyor. ABD Merkez Bankası'nın 2025 sonu anketi bu oranı %10 olarak verdi; Gallup'ın Temmuz 2025 anketi %14; Pew Araştırma Merkezi'nin 2021 anketi %16; The Motley Fool'un 2026 anketi %22; Security.org'un 2025 raporu %30 — yani aynı soru, farklı anket şirketleri tarafından sorulduğunda, neredeyse üç kata varan farklı yanıtlar üretiyor. Yalnızca metodolojinin — yalnızca doğrudan sahipliği mi yoksa ETF maruziyetini de mi sayacağı, örneklemin nasıl seçildiği — sayıyı bu kadar değiştirebilmesi bile, "kaç kişi hemfikir" sorusunun baştan itibaren ne kadar zor cevaplanan bir soru olduğunu gösteriyor.</p>
<p class="vi">Các cuộc khảo sát hỏi bao nhiêu phần trăm người trưởng thành ở Mỹ thực sự sở hữu bitcoin hoặc tiền mã hóa khác cho ra kết quả rất khác nhau tùy vào ai thực hiện khảo sát. Khảo sát của Cục Dự trữ Liên bang Mỹ cuối năm 2025 đưa ra con số 10%; khảo sát của Gallup tháng 7/2025 là 14%; khảo sát của Trung tâm Nghiên cứu Pew năm 2021 là 16%; khảo sát của Motley Fool năm 2026 là 22%; báo cáo của Security.org năm 2025 là 30% — nghĩa là cùng một câu hỏi, do các đơn vị khảo sát khác nhau thực hiện, cho ra kết quả chênh lệch gần gấp ba lần. Chỉ riêng việc phương pháp luận — có tính cả sở hữu trực tiếp hay bao gồm cả nắm giữ qua ETF, cách chọn mẫu ra sao — có thể khiến con số dao động lớn đến vậy đã cho thấy câu hỏi "bao nhiêu người đồng ý" vốn dĩ khó trả lời chính xác đến mức nào.</p>

<p class="ko">그런데 크립토 트위터의 타임라인에는 이런 불확실성이 전혀 남아있지 않다. 소셜미디어의 선택적 노출과 동질적 연결(homophily)을 다루는 연구들은 이용자가 자신과 비슷한 생각을 가진 계정을 팔로우하고, 알고리즘이 그 관계를 다시 강화하면서 극단적으로 동질적인 정보 환경이 만들어진다는 걸 반복적으로 확인했다. 트레이더가 매일 들여다보는 타임라인은 시장 참여자 전체에서 무작위로 뽑은 표본이 아니라, 자기 자신과 비슷한 소수를 스스로 큐레이션한 반향실이다. 이는 <a href="/blog/herding-information-cascade">타인의 행동을 그대로 따라 하는 군집 행동(herding)</a>과는 다른 문제다 — 허위 합의 효과는 행동을 모방하는 게 아니라, 이 반향실 안에서 형성된 '전원 일치'가 실제로는 미국 성인의 10~30%, 그중에서도 적극적으로 게시하는 극소수의 의견일 뿐인데 로스의 1977년 실험이 예측한 그대로 그 소수가 스스로를 다수라고 확신하는 지각의 오류다.</p>
<p class="en">None of that uncertainty survives on the crypto Twitter timeline. Research on selective exposure and homophily in social media has repeatedly found that users follow accounts that think like they do, and that recommendation algorithms then reinforce those connections, producing an extremely homogeneous information environment. The timeline a trader scrolls every day isn't a random sample of the entire market — it's a self-curated echo chamber of people who already resemble the trader. This is a different problem from <a href="/en/blog/herding-information-cascade">herding, where people copy other people's actions</a> — the false consensus effect isn't about copying behavior. It's a perceptual error in which the "unanimity" formed inside that echo chamber — which, in reality, represents at most 10% to 30% of American adults, and within that, only the small vocal minority who post — gets mistaken by that same minority for the majority view, exactly as Ross's 1977 experiment predicted.</p>
<p class="ja">ところがクリプトツイッターのタイムラインには、こうした不確実性がまったく残っていない。ソーシャルメディアにおける選択的接触と同質結合(homophily)を扱う研究は、利用者が自分と似た考えを持つアカウントをフォローし、アルゴリズムがその関係をさらに強化することで極端に同質的な情報環境が作られることを繰り返し確認してきた。トレーダーが毎日眺めるタイムラインは市場参加者全体からランダムに抽出された標本ではなく、自分自身と似た少数派を自ら選び取った反響室なのだ。これは<a href="/ja/blog/herding-information-cascade">他人の行動をそのまま真似る群集行動(herding)</a>とは異なる問題だ――偽の合意効果は行動を模倣することではなく、この反響室の中で形成された「全員一致」が実際には米国成人の10~30%、その中でも積極的に投稿する極少数の意見にすぎないにもかかわらず、ロスの1977年の実験が予測した通り、その少数派が自分たちこそ多数派だと確信してしまう知覚の誤りである。</p>
<p class="es">Nada de esa incertidumbre sobrevive en la línea de tiempo de crypto Twitter. La investigación sobre exposición selectiva y homofilia en redes sociales ha comprobado repetidamente que los usuarios siguen cuentas que piensan como ellos, y que los algoritmos de recomendación luego refuerzan esas conexiones, produciendo un entorno informativo extremadamente homogéneo. La línea de tiempo que un operador recorre a diario no es una muestra aleatoria de todo el mercado — es una cámara de eco autocurada de personas que ya se parecen al propio operador. Esto es un problema distinto del <a href="/es/blog/herding-information-cascade">efecto rebaño, donde la gente copia las acciones de otros</a> — el efecto de falso consenso no consiste en copiar comportamiento. Es un error de percepción en el que la 'unanimidad' formada dentro de esa cámara de eco — que en realidad representa, como mucho, entre el 10% y el 30% de los adultos estadounidenses, y dentro de eso, solo a la pequeña minoría vocal que publica — es confundida por esa misma minoría con la opinión mayoritaria, exactamente como predijo el experimento de Ross en 1977.</p>
<p class="de">Von dieser Unsicherheit bleibt auf der Crypto-Twitter-Timeline nichts übrig. Forschung zu selektiver Informationsaufnahme und Homophilie in sozialen Medien hat wiederholt gezeigt, dass Nutzer Accounts folgen, die ähnlich denken wie sie selbst, und dass Empfehlungsalgorithmen diese Verbindungen weiter verstärken — es entsteht ein extrem homogenes Informationsumfeld. Die Timeline, die ein Trader täglich scrollt, ist keine Zufallsstichprobe aus dem gesamten Markt — sie ist ein selbst kuratierter Echoraum von Menschen, die dem Trader bereits ähneln. Das ist ein anderes Problem als <a href="/de/blog/herding-information-cascade">Herdenverhalten, bei dem Menschen die Handlungen anderer kopieren</a> — der falsche Konsens-Effekt bedeutet nicht, Verhalten zu kopieren. Es ist ein Wahrnehmungsfehler, bei dem die in diesem Echoraum entstandene „Einstimmigkeit" — die in Wirklichkeit höchstens 10% bis 30% der US-Erwachsenen repräsentiert, und davon nur die kleine, lautstarke Minderheit, die überhaupt postet — von genau dieser Minderheit für die Mehrheitsmeinung gehalten wird, exakt so, wie Ross' Experiment von 1977 es vorhersagte.</p>
<p class="fr">Rien de cette incertitude ne survit sur le fil d'actualité de crypto Twitter. Les recherches sur l'exposition sélective et l'homophilie dans les réseaux sociaux ont montré à maintes reprises que les utilisateurs suivent des comptes qui pensent comme eux, et que les algorithmes de recommandation renforcent ensuite ces connexions, produisant un environnement informationnel extrêmement homogène. Le fil qu'un trader parcourt chaque jour n'est pas un échantillon aléatoire de l'ensemble du marché — c'est une chambre d'écho auto-organisée composée de gens qui lui ressemblent déjà. C'est un problème différent de <a href="/fr/blog/herding-information-cascade">l'effet de troupeau, où l'on copie les actions des autres</a> — l'effet de faux consensus ne consiste pas à copier un comportement. C'est une erreur de perception dans laquelle « l'unanimité » formée à l'intérieur de cette chambre d'écho — qui, en réalité, représente au plus 10 à 30% des adultes américains, et parmi eux, seulement la petite minorité vocale qui publie — est prise par cette même minorité pour l'opinion majoritaire, exactement comme l'expérience de Ross de 1977 l'avait prédit.</p>
<p class="pt">Nada dessa incerteza sobrevive na timeline do crypto Twitter. Pesquisas sobre exposição seletiva e homofilia nas redes sociais confirmaram repetidamente que os usuários seguem contas que pensam como eles, e que os algoritmos de recomendação depois reforçam essas conexões, produzindo um ambiente informacional extremamente homogêneo. A timeline que um trader percorre todos os dias não é uma amostra aleatória de todo o mercado — é uma câmara de eco autocurada, formada por pessoas que já se parecem com o próprio trader. Esse é um problema diferente do <a href="/pt/blog/herding-information-cascade">efeito manada, em que as pessoas copiam as ações de outras</a> — o efeito do falso consenso não é sobre copiar comportamento. É um erro de percepção no qual a "unanimidade" formada dentro dessa câmara de eco — que, na realidade, representa no máximo entre 10% e 30% dos adultos americanos, e dentro disso, apenas a pequena minoria vocal que publica — é confundida por essa mesma minoria com a opinião majoritária, exatamente como o experimento de Ross de 1977 previu.</p>
<p class="tr">Ama kripto Twitter zaman akışında bu belirsizlikten eser kalmıyor. Sosyal medyada seçici maruziyet ve homofili üzerine yapılan araştırmalar, kullanıcıların kendileriyle benzer düşünen hesapları takip ettiğini ve öneri algoritmalarının bu bağlantıları daha da güçlendirerek son derece homojen bir bilgi ortamı yarattığını defalarca doğruladı. Bir trader'ın her gün kaydırdığı zaman akışı, piyasanın tamamından rastgele seçilmiş bir örneklem değildir — bu, trader'a zaten benzeyen kişilerden oluşan, kendi kendine seçilmiş bir yankı odasıdır. Bu, <a href="/tr/blog/herding-information-cascade">insanların başkalarının eylemlerini kopyaladığı sürü davranışından (herding)</a> farklı bir sorundur — yanlış fikir birliği etkisi davranış kopyalamakla ilgili değildir. Bu yankı odasının içinde oluşan "oy birliği" — ki gerçekte Amerikalı yetişkinlerin en fazla %10 ila %30'unu, bunun da yalnızca aktif paylaşım yapan küçük, gürültücü azınlığını temsil eder — Ross'un 1977 deneyinin öngördüğü gibi tam olarak bu azınlık tarafından çoğunluk görüşü sanılan bir algı hatasıdır.</p>
<p class="vi">Nhưng trên dòng thời gian crypto Twitter, không còn dấu vết nào của sự bất định đó. Các nghiên cứu về tiếp xúc chọn lọc và tính đồng dạng (homophily) trên mạng xã hội đã nhiều lần xác nhận rằng người dùng theo dõi những tài khoản suy nghĩ giống mình, và thuật toán đề xuất sau đó lại càng củng cố các mối liên kết đó, tạo ra một môi trường thông tin cực kỳ đồng nhất. Dòng thời gian mà một trader lướt qua mỗi ngày không phải là một mẫu ngẫu nhiên từ toàn bộ thị trường — đó là một căn phòng vọng âm được tự mình biên tập, gồm những người vốn đã giống với chính trader đó. Đây là một vấn đề khác với <a href="/vi/blog/herding-information-cascade">hành vi bầy đàn (herding), nơi người ta sao chép hành động của người khác</a> — hiệu ứng đồng thuận giả không phải là sao chép hành vi. Đó là một lỗi nhận thức, trong đó "sự nhất trí tuyệt đối" được hình thành bên trong căn phòng vọng âm đó — thực chất chỉ đại diện cho nhiều nhất 10% đến 30% người trưởng thành ở Mỹ, và trong số đó, chỉ là nhóm thiểu số nhỏ, hay lên tiếng, thường xuyên đăng bài — lại bị chính nhóm thiểu số đó nhầm tưởng là ý kiến của đa số, đúng như thí nghiệm năm 1977 của Ross đã dự đoán.</p>

<div class="ko">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">미국 성인 실제 코인 보유율 — 조사마다 최대 3배 차이</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">같은 질문, 다른 답 — 크립토 트위터의 '전원 일치'는 이 중 어디에도 없다</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">실제 보유율(%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="en">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Actual U.S. Adult Crypto Ownership — Up to 3x Apart by Survey</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Same question, different answers — 'unanimous' crypto Twitter isn't reflected in any of these</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">Actual ownership (%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">米国成人の実際の暗号資産保有率 — 調査によって最大3倍の差</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">同じ質問、異なる答え——クリプトツイッターの「全員一致」はこのどれにも当てはまらない</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">実際の保有率(%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="es">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Tenencia Real de Cripto en Adultos de EE.UU. — Hasta 3 Veces de Diferencia Según la Encuesta</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Misma pregunta, respuestas distintas — la 'unanimidad' de crypto Twitter no aparece en ninguna de ellas</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">Tenencia real (%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="de">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Tatsächlicher Krypto-Besitz bei US-Erwachsenen — bis zu 3-fache Abweichung je Umfrage</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Gleiche Frage, unterschiedliche Antworten — die „Einstimmigkeit" von Crypto-Twitter findet sich in keiner davon</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">Tatsächlicher Besitz (%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="fr">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Détention Réelle de Crypto chez les Adultes Américains — Jusqu'à 3 Fois d'Écart Selon le Sondage</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Même question, réponses différentes — « l'unanimité » de crypto Twitter ne figure dans aucune d'elles</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">Détention réelle (%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="pt">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Posse Real de Cripto entre Adultos dos EUA — Até 3x de Diferença Conforme a Pesquisa</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Mesma pergunta, respostas diferentes — a "unanimidade" do crypto Twitter não aparece em nenhuma delas</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">Posse real (%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="tr">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">ABD'li Yetişkinlerin Gerçek Kripto Sahipliği — Ankete Göre 3 Kata Varan Fark</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Aynı soru, farklı cevaplar — kripto Twitter'daki "oy birliği" bunların hiçbirinde yok</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">Gerçek sahiplik (%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>
<div class="vi">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Tỷ Lệ Sở Hữu Tiền Mã Hóa Thực Tế Ở Người Trưởng Thành Mỹ — Chênh Lệch Tới 3 Lần</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Cùng một câu hỏi, câu trả lời khác nhau — sự nhất trí tuyệt đối trên crypto Twitter không có ở đây</text>
  <text x="18" y="220" fill="#71717a" font-size="13" font-family="sans-serif" transform="rotate(-90 18 220)" text-anchor="middle">Tỷ lệ sở hữu thực tế (%)</text>
  <line x1="50" y1="360" x2="660" y2="360" stroke="#3f3f46" stroke-width="1"/>
  <rect x="70" y="273" width="90" height="87" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="115" y="261" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">10%</text>
  <text x="115" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Fed 2025</text>
  <rect x="190" y="239" width="90" height="121" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="235" y="227" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">14%</text>
  <text x="235" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Gallup 2025</text>
  <rect x="310" y="221" width="90" height="139" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="355" y="209" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">16%</text>
  <text x="355" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Pew 2021</text>
  <rect x="430" y="169" width="90" height="191" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="475" y="157" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">22%</text>
  <text x="475" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Motley Fool 2026</text>
  <rect x="550" y="100" width="90" height="260" rx="4" fill="#38bdf8" fill-opacity="0.85" stroke="#7dd3fc"/>
  <text x="595" y="88" fill="#fafafa" font-size="20" font-weight="700" text-anchor="middle" font-family="sans-serif">30%</text>
  <text x="595" y="384" fill="#d4d4d8" font-size="13" text-anchor="middle" font-family="sans-serif">Security.org 2025</text>
</svg>
</div>

<h2 class="ko">합의를 파는 봇들</h2>
<h2 class="en">The Bots That Sell Consensus</h2>
<h2 class="ja">合意を売るボットたち</h2>
<h2 class="es">Los Bots Que Venden Consenso</h2>
<h2 class="de">Die Bots, die Konsens verkaufen</h2>
<h2 class="fr">Les Bots Qui Vendent du Consensus</h2>
<h2 class="pt">Os Bots Que Vendem Consenso</h2>
<h2 class="tr">Fikir Birliği Satan Botlar</h2>
<h2 class="vi">Những Con Bot Bán Sự Đồng Thuận</h2>

<p class="ko">이 반향실을 한 단계 더 왜곡하는 요인은 그 안의 목소리 중 상당수가 애초에 사람이 아니라는 사실이다. 암호화폐 관련 트윗을 대상으로 한 여러 연구에서 봇으로 분류된 계정의 비중은 표본과 탐지 방법에 따라 1%에서 14% 사이로 나타났고, 더 넓게 잡은 연구에서는 25%까지 올라갔다. 암호화폐 초대 링크를 퍼뜨리는 계정만 따로 분석한 연구에서는 그 비율이 36.4%까지 치솟았다 — 일반적인 트위터 봇 추정치를 훨씬 웃도는 수준이다.</p>
<p class="en">What distorts this echo chamber further is that a meaningful share of the voices inside it aren't human to begin with. Multiple studies of cryptocurrency-related tweets have found bot-classified accounts making up anywhere from 1% to 14% of the sample, depending on the dataset and detection method, with broader studies putting the figure as high as 25%. A study that isolated accounts specifically spreading cryptocurrency invite links found bot rates as high as 36.4% — far above typical Twitter-wide bot estimates.</p>
<p class="ja">この反響室をさらに歪める要因は、その中の声のかなりの部分がそもそも人間ではないという事実だ。暗号資産関連ツイートを対象とした複数の研究では、ボットに分類されたアカウントの割合はサンプルと検出方法によって1%から14%の間とされ、より広く取った研究では25%まで上がった。暗号資産の招待リンクを拡散するアカウントだけを分析した研究では、その割合は36.4%まで跳ね上がった――一般的なツイッターのボット推定値をはるかに上回る水準だ。</p>
<p class="es">Lo que distorsiona aún más esta cámara de eco es que buena parte de las voces que hay dentro no son humanas en absoluto. Varios estudios sobre tuits relacionados con criptomonedas han hallado que las cuentas clasificadas como bots representan entre el 1% y el 14% de la muestra, según el conjunto de datos y el método de detección, y estudios con criterios más amplios elevan la cifra hasta el 25%. Un estudio que aisló específicamente cuentas que difundían enlaces de invitación a criptomonedas encontró tasas de bots de hasta el 36,4% — muy por encima de las estimaciones típicas de bots en Twitter en general.</p>
<p class="de">Was diesen Echoraum weiter verzerrt, ist die Tatsache, dass ein erheblicher Teil der Stimmen darin von vornherein nicht menschlich ist. Mehrere Studien zu kryptobezogenen Tweets fanden, dass als Bots klassifizierte Accounts je nach Datensatz und Erkennungsmethode zwischen 1% und 14% der Stichprobe ausmachten, wobei breiter angelegte Studien den Wert auf bis zu 25% bezifferten. Eine Studie, die gezielt Accounts untersuchte, die Krypto-Einladungslinks verbreiteten, fand Bot-Anteile von bis zu 36,4% — weit über den üblichen Bot-Schätzungen für Twitter insgesamt.</p>
<p class="fr">Ce qui déforme encore davantage cette chambre d'écho, c'est qu'une part significative des voix qui s'y trouvent ne sont pas humaines au départ. Plusieurs études sur les tweets liés aux cryptomonnaies ont trouvé que les comptes classés comme bots représentaient entre 1% et 14% de l'échantillon, selon le jeu de données et la méthode de détection, des études plus larges portant ce chiffre jusqu'à 25%. Une étude isolant spécifiquement les comptes diffusant des liens d'invitation crypto a trouvé des taux de bots atteignant 36,4% — bien au-delà des estimations habituelles de bots sur l'ensemble de Twitter.</p>
<p class="pt">O que distorce ainda mais essa câmara de eco é o fato de que boa parte das vozes ali dentro não são humanas, para começar. Vários estudos sobre tweets relacionados a criptomoedas descobriram que contas classificadas como bots representam entre 1% e 14% da amostra, dependendo do conjunto de dados e do método de detecção, com estudos mais amplos elevando esse número até 25%. Um estudo que isolou especificamente contas que disseminavam links de convite para criptomoedas encontrou taxas de bots de até 36,4% — muito acima das estimativas típicas de bots no Twitter em geral.</p>
<p class="tr">Bu yankı odasını daha da çarpıtan şey, içindeki seslerin önemli bir kısmının baştan itibaren insan olmamasıdır. Kripto para birimiyle ilgili tweetler üzerine yapılan birçok çalışma, veri setine ve tespit yöntemine bağlı olarak bot olarak sınıflandırılan hesapların örneklemin %1 ila %14'ünü oluşturduğunu, daha geniş kapsamlı çalışmaların ise bu oranı %25'e kadar çıkardığını buldu. Özellikle kripto davet bağlantıları yayan hesapları inceleyen bir çalışma, bot oranının %36,4'e kadar yükseldiğini tespit etti — Twitter genelindeki tipik bot tahminlerinin çok üzerinde bir seviye.</p>
<p class="vi">Yếu tố làm méo mó thêm căn phòng vọng âm này là một phần đáng kể tiếng nói bên trong đó ngay từ đầu không phải con người. Nhiều nghiên cứu về các tweet liên quan đến tiền mã hóa phát hiện rằng các tài khoản được phân loại là bot chiếm từ 1% đến 14% mẫu nghiên cứu, tùy vào bộ dữ liệu và phương pháp phát hiện, trong khi các nghiên cứu có phạm vi rộng hơn đưa con số này lên tới 25%. Một nghiên cứu tách riêng các tài khoản chuyên phát tán liên kết mời tham gia tiền mã hóa phát hiện tỷ lệ bot lên tới 36,4% — cao hơn nhiều so với ước tính tỷ lệ bot thông thường trên toàn bộ Twitter.</p>

<p class="ko">이게 추상적인 위험이 아니라는 걸 보여준 사례가 FTX다. FTX 붕괴를 전후한 시기를 조사한 연구자들은 봇형 계정들이 BOBA, GALA, IMX, RNDR, SPELL 등 FTX 상장 토큰 6종의 시장 심리를 인위적으로 부풀리는 데 동원됐다는 걸 확인했다 — 연구진의 표현을 빌리면 '비authentic(inauthentic)한 잡음'이 해당 코인들의 가격 변화에 영향을 주도록 의도적으로 배치됐다. 트레이더가 '시장의 합의'라고 느끼는 신호 중 일부는 애초에 합의가 아니라 허위 합의 효과를 노리고 설계된 조작이다. 인간의 인지 편향과 봇 네트워크가 같은 방향으로 힘을 합치면, 착시는 단순한 심리적 오류를 넘어 실제로 가격을 움직이는 무기가 된다.</p>
<p class="en">FTX shows this isn't an abstract risk. Researchers who examined the period around FTX's collapse found that bot-like accounts were deployed to artificially inflate market sentiment around six FTX-listed tokens — BOBA, GALA, IMX, RNDR, and SPELL. In the researchers' words, "inauthentic chatter" was deliberately engineered to move those tokens' prices. Some of what a trader reads as "market consensus" was never consensus at all — it was manipulation designed specifically to exploit the false consensus effect. When human cognitive bias and bot networks pull in the same direction, the illusion stops being a mere psychological error and becomes a weapon that actually moves price.</p>
<p class="ja">これが抽象的なリスクではないことを示した事例がFTXだ。FTX破綻前後の時期を調査した研究者たちは、ボット型アカウントがBOBA、GALA、IMX、RNDR、SPELLなどFTX上場トークン6種の市場心理を人為的に膨らませるために動員されたことを確認した――研究者の言葉を借りれば「非authentic(inauthentic)な雑音」がこれらのコインの価格変動に影響を与えるよう意図的に配置された。トレーダーが「市場の合意」だと感じる信号の一部は、そもそも合意ではなく、偽の合意効果を狙って設計された操作なのだ。人間の認知バイアスとボットネットワークが同じ方向に力を合わせると、錯覚は単なる心理的誤りを超え、実際に価格を動かす武器となる。</p>
<p class="es">FTX demuestra que esto no es un riesgo abstracto. Investigadores que examinaron el período en torno al colapso de FTX descubrieron que cuentas de tipo bot fueron desplegadas para inflar artificialmente el sentimiento de mercado en torno a seis tokens listados en FTX — BOBA, GALA, IMX, RNDR y SPELL. En palabras de los propios investigadores, se diseñó deliberadamente 'chatter inauténtico' para mover el precio de esos tokens. Parte de lo que un operador lee como 'consenso de mercado' nunca fue consenso en absoluto — fue manipulación diseñada específicamente para explotar el efecto de falso consenso. Cuando el sesgo cognitivo humano y las redes de bots tiran en la misma dirección, la ilusión deja de ser un mero error psicológico y se convierte en un arma que efectivamente mueve el precio.</p>
<p class="de">FTX zeigt, dass dies kein abstraktes Risiko ist. Forscher, die den Zeitraum um den Zusammenbruch von FTX untersuchten, stellten fest, dass botartige Accounts eingesetzt wurden, um die Marktstimmung rund um sechs bei FTX gelistete Token — BOBA, GALA, IMX, RNDR und SPELL — künstlich aufzublähen. In den Worten der Forscher wurde „inauthentisches Rauschen" gezielt so platziert, dass es die Preisentwicklung dieser Token beeinflusste. Ein Teil dessen, was ein Trader als „Marktkonsens" liest, war nie Konsens — es war Manipulation, gezielt darauf ausgelegt, den falschen Konsens-Effekt auszunutzen. Wenn menschlicher kognitiver Bias und Bot-Netzwerke in dieselbe Richtung ziehen, hört die Illusion auf, ein bloßer psychologischer Fehler zu sein, und wird zur Waffe, die tatsächlich den Preis bewegt.</p>
<p class="fr">FTX démontre qu'il ne s'agit pas d'un risque abstrait. Des chercheurs ayant examiné la période entourant l'effondrement de FTX ont découvert que des comptes de type bot avaient été déployés pour gonfler artificiellement le sentiment de marché autour de six jetons cotés sur FTX — BOBA, GALA, IMX, RNDR et SPELL. Selon les termes mêmes des chercheurs, un « bruit inauthentique » avait été délibérément mis en place pour influencer le cours de ces jetons. Une partie de ce qu'un trader lit comme un « consensus de marché » n'a jamais été un consensus — c'était une manipulation spécifiquement conçue pour exploiter l'effet de faux consensus. Quand le biais cognitif humain et les réseaux de bots tirent dans la même direction, l'illusion cesse d'être une simple erreur psychologique et devient une arme qui déplace réellement les prix.</p>
<p class="pt">A FTX mostra que isso não é um risco abstrato. Pesquisadores que examinaram o período em torno do colapso da FTX descobriram que contas do tipo bot foram usadas para inflar artificialmente o sentimento de mercado em torno de seis tokens listados na FTX — BOBA, GALA, IMX, RNDR e SPELL. Nas palavras dos próprios pesquisadores, um "burburinho inautêntico" foi deliberadamente projetado para mover o preço desses tokens. Parte do que um trader lê como "consenso de mercado" nunca foi consenso algum — foi manipulação desenhada especificamente para explorar o efeito do falso consenso. Quando o viés cognitivo humano e as redes de bots puxam na mesma direção, a ilusão deixa de ser um mero erro psicológico e se torna uma arma que efetivamente move o preço.</p>
<p class="tr">Bunun soyut bir risk olmadığını gösteren örnek FTX'tir. FTX'in çöküşünün öncesini ve sonrasını inceleyen araştırmacılar, bot benzeri hesapların BOBA, GALA, IMX, RNDR ve SPELL gibi FTX'te listelenen altı token'ın piyasa duyarlılığını yapay olarak şişirmek için kullanıldığını doğruladı — araştırmacıların ifadesiyle, "sahici olmayan gürültü" bu coinlerin fiyat hareketlerini etkilemesi için kasıtlı olarak yerleştirildi. Bir trader'ın "piyasa fikir birliği" olarak okuduğu sinyallerin bir kısmı baştan itibaren fikir birliği değildi — yanlış fikir birliği etkisini istismar etmek için özel olarak tasarlanmış bir manipülasyondu. İnsan bilişsel yanlılığı ile bot ağları aynı yönde birleştiğinde, yanılsama sıradan bir psikolojik hatanın ötesine geçip fiyatı gerçekten hareket ettiren bir silaha dönüşür.</p>
<p class="vi">FTX là ví dụ cho thấy đây không phải là rủi ro trừu tượng. Các nhà nghiên cứu xem xét giai đoạn quanh thời điểm FTX sụp đổ phát hiện rằng các tài khoản dạng bot đã được triển khai để thổi phồng một cách nhân tạo tâm lý thị trường quanh sáu token niêm yết trên FTX — BOBA, GALA, IMX, RNDR và SPELL. Theo lời các nhà nghiên cứu, "tiếng ồn không xác thực" đã được cố tình dàn dựng để tác động đến biến động giá của các token này. Một phần những gì trader đọc được như là "sự đồng thuận của thị trường" chưa bao giờ thực sự là đồng thuận — đó là hành vi thao túng được thiết kế riêng để khai thác hiệu ứng đồng thuận giả. Khi thiên kiến nhận thức của con người và mạng lưới bot cùng kéo về một hướng, ảo giác không còn là một sai lầm tâm lý đơn thuần nữa mà trở thành vũ khí thực sự làm biến động giá.</p>

<h2 class="ko">슈퍼사이클이 무너진 방식</h2>
<h2 class="en">How the Supercycle Collapsed</h2>
<h2 class="ja">スーパーサイクルはこうして崩れた</h2>
<h2 class="es">Cómo Colapsó el Supercycle</h2>
<h2 class="de">Wie der Supercycle zusammenbrach</h2>
<h2 class="fr">Comment le Supercycle s'est Effondré</h2>
<h2 class="pt">Como o Supercycle Desmoronou</h2>
<h2 class="tr">Süper Döngü Nasıl Çöktü</h2>
<h2 class="vi">Siêu Chu Kỳ Đã Sụp Đổ Như Thế Nào</h2>

<p class="ko">2020년 비트코인 교육자 댄 헬드가 제시한 '슈퍼사이클' 이론은 2021년 내내 크립토 트위터를 지배했다. 반감기에 따른 공급 감소, 기관 자금의 유입, 매크로 환경의 변화가 겹치면서 이번엔 통상적인 4년 주기의 조정 국면 없이 '계속 우상향'한다는 주장이었고, 주요 계정들이 앞다퉈 이 서사를 반복하면서 타임라인은 사실상 이견 없는 하나의 목소리처럼 보였다. 6만9천 달러까지 오른 비트코인을 보며 슈퍼사이클을 의심하는 목소리를 타임라인에서 찾기는 점점 더 어려워졌다.</p>
<p class="en">The "supercycle" theory, floated in 2020 by Bitcoin educator Dan Held, dominated crypto Twitter throughout 2021. The argument was that the combination of halving-driven supply reduction, institutional capital inflows, and a shifting macro backdrop meant this time Bitcoin would keep grinding upward without the usual four-year correction — and as prominent accounts raced to repeat the narrative, the timeline came to look like a single voice with no dissent. As Bitcoin climbed to $69,000, it became harder and harder to find a skeptical voice about the supercycle anywhere on the timeline.</p>
<p class="ja">2020年にビットコイン教育者のダン・ヘルドが提示した「スーパーサイクル」理論は、2021年を通してクリプトツイッターを支配した。半減期による供給減少、機関投資家資金の流入、マクロ環境の変化が重なり、今回は通常の4年周期の調整局面なしに「上昇を続ける」という主張であり、主要アカウントが競うようにこの物語を繰り返す中、タイムラインは事実上異論のない一つの声のように見えた。6万9千ドルまで上昇したビットコインを前に、スーパーサイクルを疑う声をタイムラインで見つけるのはますます難しくなった。</p>
<p class="es">La teoría del 'supercycle', propuesta en 2020 por el educador de Bitcoin Dan Held, dominó crypto Twitter durante todo 2021. El argumento era que la combinación de la reducción de la oferta impulsada por el halving, las entradas de capital institucional y un contexto macro cambiante significaba que, esta vez, Bitcoin seguiría subiendo sin la habitual corrección de cuatro años — y, a medida que las cuentas más prominentes competían por repetir esa narrativa, la línea de tiempo llegó a parecer una sola voz sin disidencia. A medida que Bitcoin subía hasta los 69.000 dólares, se volvía cada vez más difícil encontrar una voz escéptica sobre el supercycle en cualquier parte de la línea de tiempo.</p>
<p class="de">Die 2020 vom Bitcoin-Bildungsvermittler Dan Held aufgebrachte „Supercycle"-Theorie beherrschte 2021 durchgängig Crypto-Twitter. Das Argument lautete, die Kombination aus halving-bedingter Angebotsverknappung, institutionellen Kapitalzuflüssen und einem sich wandelnden Makroumfeld bedeute, dass Bitcoin diesmal ohne die übliche vierjährige Korrekturphase weiter steigen würde — und während prominente Accounts wetteiferten, diese Erzählung zu wiederholen, wirkte die Timeline wie eine einzige Stimme ohne Widerspruch. Während Bitcoin auf 69.000 Dollar kletterte, wurde es immer schwerer, irgendwo auf der Timeline eine skeptische Stimme zum Supercycle zu finden.</p>
<p class="fr">La théorie du « supercycle », lancée en 2020 par l'éducateur Bitcoin Dan Held, a dominé crypto Twitter tout au long de 2021. L'argument était que la combinaison de la réduction de l'offre liée au halving, des afflux de capitaux institutionnels et d'un contexte macroéconomique changeant signifiait que, cette fois, le Bitcoin continuerait de grimper sans la correction habituelle de quatre ans — et à mesure que les comptes les plus en vue rivalisaient pour répéter ce récit, le fil d'actualité a fini par ressembler à une voix unique, sans aucune contestation. Alors que le Bitcoin grimpait jusqu'à 69 000 dollars, il devenait de plus en plus difficile de trouver une voix sceptique sur le supercycle où que ce soit sur le fil.</p>
<p class="pt">A teoria do "supercycle", lançada em 2020 pelo educador de Bitcoin Dan Held, dominou o crypto Twitter ao longo de 2021. O argumento era que a combinação entre a redução da oferta provocada pelo halving, os fluxos de capital institucional e um cenário macro em mudança significava que, dessa vez, o Bitcoin continuaria subindo sem a habitual correção de quatro anos — e, à medida que contas de destaque disputavam para repetir essa narrativa, a timeline passou a parecer uma única voz, sem dissidência. Enquanto o Bitcoin subia até 69 mil dólares, ficava cada vez mais difícil encontrar uma voz cética sobre o supercycle em qualquer lugar da timeline.</p>
<p class="tr">2020'de Bitcoin eğitimcisi Dan Held'in ortaya attığı "süper döngü" teorisi, 2021 boyunca kripto Twitter'a hakim oldu. Argümana göre, halving kaynaklı arz azalması, kurumsal sermaye girişleri ve değişen makro ortamın birleşimi, bu kez Bitcoin'in olağan dört yıllık düzeltme olmadan yükselmeye devam edeceği anlamına geliyordu — ve önde gelen hesaplar bu anlatıyı tekrarlamak için yarışırken, zaman akışı adeta itirazsız tek bir ses gibi görünmeye başladı. Bitcoin 69 bin dolara tırmanırken, zaman akışında herhangi bir yerde süper döngüye şüpheyle yaklaşan bir ses bulmak giderek zorlaştı.</p>
<p class="vi">Lý thuyết "siêu chu kỳ" (supercycle), được nhà giáo dục Bitcoin Dan Held đưa ra năm 2020, đã thống trị crypto Twitter suốt năm 2021. Lập luận cho rằng sự kết hợp giữa việc giảm nguồn cung do halving, dòng vốn tổ chức đổ vào, và bối cảnh vĩ mô thay đổi có nghĩa là lần này Bitcoin sẽ tiếp tục tăng mà không trải qua đợt điều chỉnh bốn năm thông thường — và khi các tài khoản nổi bật đua nhau lặp lại câu chuyện này, dòng thời gian gần như trở thành một tiếng nói duy nhất, không có bất đồng. Khi Bitcoin leo lên mức 69.000 đô la, việc tìm thấy một tiếng nói hoài nghi về siêu chu kỳ ở bất cứ đâu trên dòng thời gian ngày càng trở nên khó khăn.</p>

<p class="ko">그러나 그 '전원 일치'는 시장 전체의 포지셔닝을 반영한 게 아니었다. 2022년 5월 루나·테라USD 붕괴, 6월 스리 애로우즈 캐피털의 청산, 11월 FTX의 파산이 연쇄적으로 터지면서 비트코인은 고점 대비 거의 80% 하락했다. 슈퍼사이클을 믿는 목소리가 컸던 만큼, 그 반대편에 쌓이던 위험 — 과도한 레버리지, 자기순환 담보구조, 거래소의 고객자산 유용 — 은 타임라인에서 거의 체감되지 않았다. 허위 합의 효과가 위험한 건 틀린 예측을 하게 만들어서가 아니라, 반대 의견의 존재 자체를 지워버려 그 반대편에 쌓이고 있는 리스크의 규모를 가늠할 수 없게 만들기 때문이다.</p>
<p class="en">But that "unanimity" never reflected the positioning of the market as a whole. The collapse of Luna and TerraUSD in May 2022, the liquidation of Three Arrows Capital in June, and FTX's bankruptcy in November hit in sequence, and Bitcoin fell nearly 80% from its high. Because the voices believing in the supercycle were so loud, the risk building on the other side — excessive leverage, circularly collateralized structures, exchanges misusing customer assets — barely registered on the timeline at all. The danger of the false consensus effect isn't that it makes you predict wrong. It's that it erases the very existence of dissent, making it impossible to gauge how much risk is accumulating on the other side of your position.</p>
<p class="ja">しかしその「全員一致」は市場全体のポジショニングを反映したものではなかった。2022年5月のルナ・テラUSD崩壊、6月のスリー・アローズ・キャピタルの清算、11月のFTX破綻が連鎖的に起こり、ビットコインは高値から約80%下落した。スーパーサイクルを信じる声が大きかった分、その裏側で積み上がっていたリスク――過剰なレバレッジ、自己循環的な担保構造、取引所による顧客資産の流用――はタイムライン上でほとんど体感されなかった。偽の合意効果が危険なのは、誤った予測をさせるからではなく、反対意見の存在そのものを消し去り、その裏側に積み上がっているリスクの規模を測れなくしてしまうからだ。</p>
<p class="es">Pero esa 'unanimidad' nunca reflejó el posicionamiento del mercado en su conjunto. El colapso de Luna y TerraUSD en mayo de 2022, la liquidación de Three Arrows Capital en junio y la bancarrota de FTX en noviembre golpearon en secuencia, y Bitcoin cayó casi un 80% desde su máximo. Precisamente porque las voces que creían en el supercycle eran tan ruidosas, el riesgo que se acumulaba en el otro lado — apalancamiento excesivo, estructuras de garantías circulares, uso indebido de activos de clientes por parte de los exchanges — apenas se percibía en la línea de tiempo. El peligro del efecto de falso consenso no es que te haga predecir mal. Es que borra la existencia misma de la disidencia, haciendo imposible calibrar cuánto riesgo se está acumulando al otro lado de tu posición.</p>
<p class="de">Doch diese „Einstimmigkeit" spiegelte nie die Positionierung des Gesamtmarktes wider. Der Zusammenbruch von Luna und TerraUSD im Mai 2022, die Liquidation von Three Arrows Capital im Juni und die FTX-Insolvenz im November trafen nacheinander ein, und Bitcoin fiel um fast 80% von seinem Höchststand. Gerade weil die Stimmen, die an den Supercycle glaubten, so laut waren, war das Risiko, das sich auf der anderen Seite aufbaute — exzessive Hebelwirkung, zirkulär besicherte Strukturen, Missbrauch von Kundenvermögen durch Börsen — auf der Timeline kaum spürbar. Der falsche Konsens-Effekt ist nicht deshalb gefährlich, weil er zu falschen Vorhersagen führt. Er ist gefährlich, weil er die Existenz abweichender Meinungen komplett auslöscht und es damit unmöglich macht abzuschätzen, wie viel Risiko sich auf der anderen Seite der eigenen Position aufbaut.</p>
<p class="fr">Mais cette « unanimité » n'a jamais reflété le positionnement de l'ensemble du marché. L'effondrement de Luna et de TerraUSD en mai 2022, la liquidation de Three Arrows Capital en juin, puis la faillite de FTX en novembre se sont enchaînés, et le Bitcoin a chuté de près de 80% depuis son sommet. Précisément parce que les voix croyant au supercycle étaient si bruyantes, le risque qui s'accumulait de l'autre côté — effet de levier excessif, structures de garanties circulaires, détournement des actifs clients par les plateformes — se faisait à peine sentir sur le fil d'actualité. Le danger de l'effet de faux consensus n'est pas qu'il vous fasse mal prédire. C'est qu'il efface l'existence même de la dissidence, rendant impossible d'évaluer l'ampleur du risque qui s'accumule de l'autre côté de sa position.</p>
<p class="pt">Mas essa "unanimidade" nunca refletiu o posicionamento do mercado como um todo. O colapso da Luna e da TerraUSD em maio de 2022, a liquidação da Three Arrows Capital em junho e a falência da FTX em novembro se sucederam, e o Bitcoin caiu quase 80% em relação à máxima. Justamente porque as vozes que acreditavam no supercycle eram tão altas, o risco que se acumulava do outro lado — alavancagem excessiva, estruturas de garantia circulares, uso indevido de ativos de clientes por corretoras — mal era percebido na timeline. O perigo do efeito do falso consenso não é fazer você prever errado. É apagar a própria existência da discordância, tornando impossível avaliar quanto risco está se acumulando do outro lado da sua posição.</p>
<p class="tr">Ama o "oy birliği" hiçbir zaman piyasanın bütününün pozisyonunu yansıtmadı. Mayıs 2022'de Luna ve TerraUSD'nin çöküşü, Haziran'da Three Arrows Capital'in tasfiyesi ve Kasım'da FTX'in iflası art arda gerçekleşti ve Bitcoin zirvesinden neredeyse %80 düştü. Süper döngüye inanan sesler bu kadar yüksek olduğu için, diğer tarafta biriken risk — aşırı kaldıraç, döngüsel olarak teminatlandırılmış yapılar, borsaların müşteri varlıklarını kötüye kullanması — zaman akışında neredeyse hiç hissedilmedi. Yanlış fikir birliği etkisinin tehlikesi, sizi yanlış tahmin yapmaya itmesi değildir. Muhalif görüşün varlığını tamamen silerek, pozisyonunuzun karşı tarafında ne kadar risk biriktiğini ölçmenizi imkansız hale getirmesidir.</p>
<p class="vi">Nhưng sự "nhất trí tuyệt đối" đó chưa bao giờ phản ánh vị thế của toàn bộ thị trường. Sự sụp đổ của Luna và TerraUSD vào tháng 5/2022, việc thanh lý Three Arrows Capital vào tháng 6, và vụ phá sản của FTX vào tháng 11 lần lượt xảy ra, khiến Bitcoin giảm gần 80% so với đỉnh. Chính vì tiếng nói tin vào siêu chu kỳ quá lớn, rủi ro đang tích tụ ở phía đối lập — đòn bẩy quá mức, các cấu trúc thế chấp vòng tròn lẫn nhau, việc các sàn giao dịch lạm dụng tài sản khách hàng — gần như không được cảm nhận trên dòng thời gian. Sự nguy hiểm của hiệu ứng đồng thuận giả không nằm ở việc khiến bạn dự đoán sai. Nó nằm ở chỗ nó xóa bỏ hoàn toàn sự tồn tại của ý kiến trái chiều, khiến bạn không thể ước lượng được rủi ro đang tích tụ lớn đến đâu ở phía đối lập với vị thế của mình.</p>

<h2 class="ko">체감 합의와 실제 포지셔닝 사이</h2>
<h2 class="en">Between Felt Consensus and Actual Positioning</h2>
<h2 class="ja">体感される合意と実際のポジショニングの間</h2>
<h2 class="es">Entre el Consenso Percibido y el Posicionamiento Real</h2>
<h2 class="de">Zwischen gefühltem Konsens und tatsächlicher Positionierung</h2>
<h2 class="fr">Entre Consensus Ressenti et Positionnement Réel</h2>
<h2 class="pt">Entre o Consenso Percebido e o Posicionamento Real</h2>
<h2 class="tr">Hissedilen Fikir Birliği ile Gerçek Pozisyonlama Arasında</h2>
<h2 class="vi">Giữa Sự Đồng Thuận Cảm Nhận Và Vị Thế Thực Tế</h2>

<p class="ko">이 편향을 완전히 없앨 방법은 없다 — 로스의 연구가 보여줬듯 허위 합의 효과는 의식적인 판단이 아니라 사회적 지각의 기본 작동 방식이기 때문이다. 대신 할 수 있는 건 체감한 합의를 곧바로 확신으로 옮기지 않고, 그 사이에 검증 가능한 데이터를 하나 끼워 넣는 것이다. 펀딩비율이 지속적으로 한쪽으로 쏠려 있는지, 옵션 시장의 풋/콜 비율이 실제로 편향돼 있는지, 거래소 순유출입이 타임라인의 '방향'과 같은 쪽을 가리키는지 — 이런 지표들은 감정이 아니라 실제로 자금을 걸어야 만들어지는 데이터라는 점에서, 타임라인의 텍스트보다 조작하기가 훨씬 좁고 비용도 크다.</p>
<p class="en">There's no way to eliminate this bias entirely — as Ross's research showed, the false consensus effect isn't a conscious judgment but a basic feature of how social perception works. What you can do instead is refuse to let felt consensus convert directly into conviction, and insert one piece of verifiable data in between. Is the funding rate persistently skewed in one direction? Is the options market's put/call ratio actually lopsided? Does exchange net flow point the same way the timeline "feels" it should? These are figures that require real capital to be staked to exist at all, not just sentiment — which makes them far harder, and far more expensive, to fake than a timeline full of text.</p>
<p class="ja">このバイアスを完全になくす方法はない――ロスの研究が示した通り、偽の合意効果は意識的な判断ではなく社会的知覚の基本的な作動様式だからだ。代わりにできるのは、体感した合意をそのまま確信へと移さず、その間に検証可能なデータを一つ挟み込むことだ。ファンディングレートが持続的に一方向に偏っているか、オプション市場のプット/コール比率が実際に偏っているか、取引所の純流出入がタイムラインの「方向」と同じ側を指しているか――こうした指標は感情ではなく実際に資金を賭けなければ生まれないデータであるという点で、タイムラインの文章よりも操作の余地がはるかに狭く、コストも大きい。</p>
<p class="es">No hay forma de eliminar por completo este sesgo — como demostró la investigación de Ross, el efecto de falso consenso no es un juicio consciente, sino una característica básica de cómo funciona la percepción social. Lo que sí se puede hacer es negarse a dejar que el consenso percibido se convierta directamente en convicción, e insertar en el medio un dato verificable. ¿Está la tasa de financiación (funding rate) sesgada de forma persistente hacia un lado? ¿Está el ratio put/call del mercado de opciones realmente desequilibrado? ¿El flujo neto de los exchanges apunta en la misma dirección que la línea de tiempo 'siente' que debería? Estas son cifras que requieren capital real comprometido para siquiera existir, no solo sentimiento — lo que las hace mucho más difíciles, y mucho más costosas, de falsificar que una línea de tiempo llena de texto.</p>
<p class="de">Diesen Bias vollständig zu beseitigen ist unmöglich — wie Ross' Forschung zeigte, ist der falsche Konsens-Effekt kein bewusstes Urteil, sondern eine grundlegende Eigenschaft der sozialen Wahrnehmung selbst. Was man stattdessen tun kann: sich weigern, gefühlten Konsens direkt in Überzeugung umzuwandeln, und stattdessen einen überprüfbaren Datenpunkt dazwischenschalten. Ist die Funding Rate anhaltend in eine Richtung verzerrt? Ist das Put/Call-Verhältnis am Optionsmarkt tatsächlich einseitig? Zeigt der Netto-Fluss der Börsen in dieselbe Richtung, in die sich die Timeline „anfühlt"? Solche Zahlen entstehen nur, wenn tatsächlich Kapital eingesetzt wird, nicht durch bloße Stimmung — was sie weit schwerer und weit teurer zu fälschen macht als eine Timeline voller Text.</p>
<p class="fr">Il n'existe aucun moyen d'éliminer entièrement ce biais — comme l'a montré la recherche de Ross, l'effet de faux consensus n'est pas un jugement conscient mais une caractéristique fondamentale du fonctionnement de la perception sociale. Ce que l'on peut faire, en revanche, c'est refuser de laisser le consensus ressenti se transformer directement en conviction, et insérer entre les deux une donnée vérifiable. Le taux de financement (funding rate) est-il durablement biaisé dans une direction ? Le ratio put/call du marché des options est-il réellement déséquilibré ? Le flux net des plateformes pointe-t-il dans la même direction que celle « ressentie » sur le fil ? Ce sont des chiffres qui exigent l'engagement de capitaux réels pour exister, pas seulement un sentiment — ce qui les rend bien plus difficiles, et bien plus coûteux, à falsifier qu'un fil rempli de texte.</p>
<p class="pt">Não há como eliminar esse viés por completo — como a pesquisa de Ross mostrou, o efeito do falso consenso não é um julgamento consciente, mas uma característica básica de como funciona a percepção social. O que se pode fazer, em vez disso, é se recusar a deixar que o consenso percebido se converta diretamente em convicção, inserindo entre os dois um dado verificável. A taxa de financiamento (funding rate) está persistentemente inclinada para um lado? O índice put/call do mercado de opções está realmente desequilibrado? O fluxo líquido das corretoras aponta na mesma direção que a timeline "sente" que deveria apontar? Esses são números que exigem capital real em jogo para sequer existir, não apenas sentimento — o que os torna muito mais difíceis, e muito mais caros, de falsificar do que uma timeline cheia de texto.</p>
<p class="tr">Bu yanlılığı tamamen ortadan kaldırmanın bir yolu yok — Ross'un araştırması gösterdiği gibi, yanlış fikir birliği etkisi bilinçli bir yargı değil, sosyal algının temel bir işleyiş biçimidir. Bunun yerine yapılabilecek şey, hissedilen fikir birliğinin doğrudan kanaate dönüşmesine izin vermemek ve ikisinin arasına doğrulanabilir bir veri yerleştirmektir. Fonlama oranı sürekli olarak bir yöne mi eğik? Opsiyon piyasasının put/call oranı gerçekten dengesiz mi? Borsaların net akışı, zaman akışının "hissettirdiği" yönle aynı yöne mi işaret ediyor? Bu rakamlar, salt duygudan değil, gerçekten sermaye taahhüt edilmesinden doğar — bu da onları metinle dolu bir zaman akışından çok daha zor ve çok daha maliyetli hale getirir.</p>
<p class="vi">Không có cách nào loại bỏ hoàn toàn thiên kiến này — như nghiên cứu của Ross đã chỉ ra, hiệu ứng đồng thuận giả không phải là một phán đoán có ý thức mà là một đặc điểm cơ bản trong cách nhận thức xã hội vận hành. Điều có thể làm thay vào đó là từ chối để sự đồng thuận cảm nhận chuyển hóa trực tiếp thành niềm tin chắc chắn, và chèn vào giữa một dữ liệu có thể kiểm chứng. Tỷ lệ funding có liên tục nghiêng về một phía không? Tỷ lệ put/call trên thị trường quyền chọn có thực sự lệch không? Dòng chảy ròng của sàn giao dịch có chỉ cùng hướng với "cảm giác" mà dòng thời gian đang tạo ra không? Đây là những con số chỉ tồn tại khi có vốn thực sự được đặt cược, chứ không chỉ là cảm tính — điều này khiến chúng khó, và tốn kém hơn nhiều để giả mạo so với một dòng thời gian đầy chữ.</p>

<p class="ko">관건은 이 확인 절차를 게을리하지 않는 습관이다. 타임라인이 온통 한 방향으로 기운 것처럼 느껴지는 순간이야말로 그 확신의 근거가 시장 전체의 표본인지, 아니면 스스로 큐레이션한 반향실의 메아리인지 물어야 하는 순간이다. 이는 <a href="/blog/choice-supportive-bias-bitcoin-thesis-creep">선택 지지 편향</a>처럼 스스로 그 왜곡을 인식하지 못한다는 점에서 더 위험하다. 1977년 로스의 학생들이 자신의 선택을 다수라고 믿었던 것처럼, 2021년의 슈퍼사이클 신봉자들도, 오늘 타임라인을 스크롤하는 트레이더도 같은 착시에 노출돼 있다. 다만 이번엔 그 착시를 만드는 게 대학 캠퍼스가 아니라 알고리즘과 봇, 그리고 자기선택이라는 세 겹의 필터라는 점이 다를 뿐이다.</p>
<p class="en">The real work is the habit of never skipping that check. The moment the timeline feels like it's leaning entirely one way is precisely the moment to ask whether that conviction rests on a sample of the whole market or on the echo of a chamber you curated yourself. This is more dangerous than an ordinary mistake because, like <a href="/en/blog/choice-supportive-bias-bitcoin-thesis-creep">choice-supportive bias</a>, you never notice the distortion happening. Just as Ross's students in 1977 believed their choice was the majority one, the supercycle believers of 2021 — and the trader scrolling the timeline today — are exposed to the same illusion. The only thing that's changed is that the illusion is no longer manufactured on a college campus. It's manufactured by a triple filter of algorithms, bots, and self-selection.</p>
<p class="ja">肝心なのは、この確認作業を怠らない習慣だ。タイムラインが完全に一方向に傾いているように感じられる瞬間こそ、その確信の根拠が市場全体の標本なのか、それとも自ら選び取った反響室のこだまなのかを問うべき瞬間である。これは<a href="/ja/blog/choice-supportive-bias-bitcoin-thesis-creep">選択支持バイアス</a>と同様、自分ではその歪みに気づけないという点でより危険だ。1977年のロスの学生たちが自分の選択を多数派だと信じたように、2021年のスーパーサイクル信奉者も、今日タイムラインをスクロールするトレーダーも、同じ錯覚にさらされている。違うのはただ一つ、その錯覚を作り出しているのが大学のキャンパスではなく、アルゴリズムとボット、そして自己選択という三重のフィルターだという点だけだ。</p>
<p class="es">Lo que realmente cuenta es el hábito de no saltarse nunca esa comprobación. El momento en que la línea de tiempo se siente completamente inclinada hacia un solo lado es precisamente el momento de preguntarse si esa convicción se apoya en una muestra de todo el mercado o en el eco de una cámara que uno mismo curó. Esto es más peligroso que un error corriente porque, igual que el <a href="/es/blog/choice-supportive-bias-bitcoin-thesis-creep">sesgo de apoyo a la elección</a>, uno nunca nota que la distorsión está ocurriendo. Igual que los estudiantes de Ross en 1977 creyeron que su elección era la mayoritaria, tanto los creyentes del supercycle de 2021 como el operador que hoy recorre la línea de tiempo están expuestos a la misma ilusión. Lo único que ha cambiado es que esa ilusión ya no se fabrica en un campus universitario. Se fabrica mediante un triple filtro de algoritmos, bots y autoselección.</p>
<p class="de">Entscheidend ist die Gewohnheit, diese Überprüfung niemals auszulassen. Genau der Moment, in dem sich die Timeline vollständig auf eine Seite geneigt anfühlt, ist der Moment, in dem man fragen sollte, ob diese Überzeugung auf einer Stichprobe des gesamten Marktes beruht oder auf dem Echo eines selbst kuratierten Raums. Das ist gefährlicher als ein gewöhnlicher Fehler, weil man — wie beim <a href="/de/blog/choice-supportive-bias-bitcoin-thesis-creep">Choice-Supportive Bias</a> — die Verzerrung selbst nie bemerkt. Genau wie Ross' Studierende 1977 glaubten, ihre Wahl sei die der Mehrheit, sind sowohl die Supercycle-Gläubigen von 2021 als auch der Trader, der heute die Timeline scrollt, derselben Illusion ausgesetzt. Der einzige Unterschied: Diese Illusion entsteht nicht mehr auf einem Universitätscampus. Sie entsteht durch einen dreifachen Filter aus Algorithmen, Bots und Selbstselektion.</p>
<p class="fr">Ce qui compte vraiment, c'est l'habitude de ne jamais sauter cette vérification. Le moment où le fil semble entièrement penché d'un seul côté est précisément le moment où il faut se demander si cette conviction repose sur un échantillon de l'ensemble du marché ou sur l'écho d'une chambre que l'on a soi-même organisée. C'est plus dangereux qu'une erreur ordinaire car, comme le <a href="/fr/blog/choice-supportive-bias-bitcoin-thesis-creep">biais de soutien au choix</a>, on ne remarque jamais que la distorsion est en train de se produire. Tout comme les étudiants de Ross en 1977 croyaient que leur choix était majoritaire, les adeptes du supercycle de 2021 comme le trader qui parcourt aujourd'hui son fil d'actualité sont exposés à la même illusion. La seule chose qui a changé, c'est que cette illusion n'est plus fabriquée sur un campus universitaire. Elle est fabriquée par un triple filtre : algorithmes, bots et autosélection.</p>
<p class="pt">O que realmente importa é o hábito de nunca pular essa verificação. O momento em que a timeline parece completamente inclinada para um só lado é exatamente o momento de perguntar se essa convicção se apoia em uma amostra de todo o mercado ou no eco de uma câmara que você mesmo organizou. Isso é mais perigoso do que um erro comum porque, assim como o <a href="/pt/blog/choice-supportive-bias-bitcoin-thesis-creep">viés de apoio à escolha</a>, você nunca percebe a distorção acontecendo. Assim como os estudantes de Ross em 1977 acreditavam que sua escolha era majoritária, tanto os crentes do supercycle de 2021 quanto o trader que hoje rola a timeline estão expostos à mesma ilusão. A única coisa que mudou é que essa ilusão não é mais fabricada em um campus universitário. Ela é fabricada por um filtro triplo de algoritmos, bots e autosseleção.</p>
<p class="tr">Asıl mesele, bu kontrolü asla atlamama alışkanlığıdır. Zaman akışının tamamen tek yöne eğilmiş gibi hissedildiği an, tam olarak bu kanaatin piyasanın tamamından alınmış bir örnekleme mi yoksa kendi oluşturduğunuz bir yankı odasının yankısına mı dayandığını sorgulamanız gereken andır. Bu, <a href="/tr/blog/choice-supportive-bias-bitcoin-thesis-creep">seçim destekleyici yanlılıkta olduğu gibi</a>, çarpıklığın gerçekleştiğini asla fark etmemeniz nedeniyle sıradan bir hatadan daha tehlikelidir. Ross'un 1977'deki öğrencileri seçimlerinin çoğunluğun tercihi olduğuna inandığı gibi, 2021'in süper döngü inananları da, bugün zaman akışını kaydıran trader da aynı yanılsamaya maruz kalıyor. Tek değişen şey, bu yanılsamanın artık bir üniversite kampüsünde değil, algoritmalar, botlar ve kendi kendini seçme olmak üzere üç katmanlı bir filtre tarafından üretiliyor olması.</p>
<p class="vi">Điều thực sự quan trọng là thói quen không bao giờ bỏ qua bước kiểm chứng này. Khoảnh khắc dòng thời gian có cảm giác nghiêng hoàn toàn về một phía chính là khoảnh khắc cần tự hỏi liệu niềm tin đó dựa trên một mẫu đại diện cho toàn thị trường hay chỉ là tiếng vọng của một căn phòng do chính mình biên tập. Điều này nguy hiểm hơn một sai lầm thông thường vì, giống như <a href="/vi/blog/choice-supportive-bias-bitcoin-thesis-creep">thiên kiến ủng hộ lựa chọn</a>, bạn không bao giờ nhận ra sự bóp méo đang diễn ra. Giống như các sinh viên của Ross năm 1977 tin rằng lựa chọn của họ là của số đông, những người tin vào siêu chu kỳ năm 2021, cũng như trader đang lướt dòng thời gian hôm nay, đều đang phơi bày trước cùng một ảo giác. Điều duy nhất đã thay đổi là ảo giác đó không còn được tạo ra trên một khuôn viên đại học nữa. Nó được tạo ra bởi ba lớp bộ lọc: thuật toán, bot, và sự tự chọn lọc.</p>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: Ross, L., Greene, D. &amp; House, P. (1977), "The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes", Journal of Experimental Social Psychology, 13(3). Gallup, "Cryptocurrency Still Has Limited Main Street Appeal" (2025.7). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, "16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (2021.11.11). The Motley Fool, "2026 Cryptocurrency Investor Trends Survey". Security.org, "2026 Cryptocurrency Adoption and Sentiment Report". CNBC, "Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (2023.8.2). Held, D., "The Bitcoin Supercycle Theory" (2020).</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Ross, L., Greene, D. &amp; House, P. (1977), "The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes," Journal of Experimental Social Psychology, 13(3). Gallup, "Cryptocurrency Still Has Limited Main Street Appeal" (Jul. 2025). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, "16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (Nov. 11, 2021). The Motley Fool, "2026 Cryptocurrency Investor Trends Survey." Security.org, "2026 Cryptocurrency Adoption and Sentiment Report." CNBC, "Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (Aug. 2, 2023). Held, D., "The Bitcoin Supercycle Theory" (2020).</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: Ross, L., Greene, D. &amp; House, P. (1977), "The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes", Journal of Experimental Social Psychology, 13(3). Gallup, "Cryptocurrency Still Has Limited Main Street Appeal" (2025年7月). 米連邦準備制度理事会, Survey of Household Economics and Decisionmaking (2025年). Pew Research Center, "16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (2021年11月11日). The Motley Fool, "2026 Cryptocurrency Investor Trends Survey". Security.org, "2026 Cryptocurrency Adoption and Sentiment Report". CNBC, "Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (2023年8月2日). Held, D., "The Bitcoin Supercycle Theory" (2020年).</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: Ross, L., Greene, D. &amp; House, P. (1977), "The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes", Journal of Experimental Social Psychology, 13(3). Gallup, "Cryptocurrency Still Has Limited Main Street Appeal" (jul. 2025). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, "16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (11 nov. 2021). The Motley Fool, "2026 Cryptocurrency Investor Trends Survey". Security.org, "2026 Cryptocurrency Adoption and Sentiment Report". CNBC, "Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (2 ago. 2023). Held, D., "The Bitcoin Supercycle Theory" (2020).</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: Ross, L., Greene, D. &amp; House, P. (1977), „The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes", Journal of Experimental Social Psychology, 13(3). Gallup, „Cryptocurrency Still Has Limited Main Street Appeal" (Jul. 2025). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, „16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (11. Nov. 2021). The Motley Fool, „2026 Cryptocurrency Investor Trends Survey". Security.org, „2026 Cryptocurrency Adoption and Sentiment Report". CNBC, „Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (2. Aug. 2023). Held, D., „The Bitcoin Supercycle Theory" (2020).</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : Ross, L., Greene, D. &amp; House, P. (1977), « The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes », Journal of Experimental Social Psychology, 13(3). Gallup, « Cryptocurrency Still Has Limited Main Street Appeal » (juil. 2025). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, « 16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency » (11 nov. 2021). The Motley Fool, « 2026 Cryptocurrency Investor Trends Survey ». Security.org, « 2026 Cryptocurrency Adoption and Sentiment Report ». CNBC, « Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers » (2 août 2023). Held, D., « The Bitcoin Supercycle Theory » (2020).</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: Ross, L., Greene, D. &amp; House, P. (1977), "The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes", Journal of Experimental Social Psychology, 13(3). Gallup, "Cryptocurrency Still Has Limited Main Street Appeal" (jul. 2025). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, "16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (11 nov. 2021). The Motley Fool, "2026 Cryptocurrency Investor Trends Survey". Security.org, "2026 Cryptocurrency Adoption and Sentiment Report". CNBC, "Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (2 ago. 2023). Held, D., "The Bitcoin Supercycle Theory" (2020).</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: Ross, L., Greene, D. &amp; House, P. (1977), "The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes", Journal of Experimental Social Psychology, 13(3). Gallup, "Cryptocurrency Still Has Limited Main Street Appeal" (Tem. 2025). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, "16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (11 Kas. 2021). The Motley Fool, "2026 Cryptocurrency Investor Trends Survey". Security.org, "2026 Cryptocurrency Adoption and Sentiment Report". CNBC, "Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (2 Ağu. 2023). Held, D., "The Bitcoin Supercycle Theory" (2020).</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: Ross, L., Greene, D. &amp; House, P. (1977), "The False Consensus Effect: An Egocentric Bias in Social Perception and Attribution Processes", Journal of Experimental Social Psychology, 13(3). Gallup, "Cryptocurrency Still Has Limited Main Street Appeal" (7/2025). Federal Reserve Board, Survey of Household Economics and Decisionmaking (2025). Pew Research Center, "16% of Americans Say They Have Ever Invested in, Traded or Used Cryptocurrency" (11/11/2021). The Motley Fool, "2026 Cryptocurrency Investor Trends Survey". Security.org, "2026 Cryptocurrency Adoption and Sentiment Report". CNBC, "Elon Musk tweets, Twitter bots boosted FTX-listed crypto: researchers" (2/8/2023). Held, D., "The Bitcoin Supercycle Theory" (2020).</p>

<?php require __DIR__.'/_footer.php'; ?>
