<?php $slug = 'fca-crypto-etn-ucits-10-percent-retail-funds'; require __DIR__.'/_header.php'; ?>

<p class="ko">영국 금융행위감독청(FCA)이 UCITS(양도성증권 집합투자기구)와 일부 비UCITS 소매펀드(NURS)에 대해 암호자산 상장지수채권(cETN)을 신탁재산의 최대 10%까지 편입할 수 있도록 허용하는 방안을 내놨다. FCA는 지난 6월 5일 발표한 제52차 분기 협의문서(CP26/17)에서 이 같은 제안을 공개했으며, 코인데스크(CoinDesk)·더블록(The Block) 등에 따르면 관련 의견 수렴 기한은 7월 13일로 하루 앞으로 다가왔다. FCA는 협의문서에서 "이 펀드들이 일반 소비자에게 판매될 수 있도록 허용하는 대가로, 펀드가 노출될 수 있는 자산에 보수적인 제한을 두는 것"이라고 10% 상한의 취지를 설명했다. 이는 지난 2월 룩셈부르크 금융감독청(CSSF)이 UCITS의 간접 크립토 익스포저를 순자산가치(NAV)의 10%까지 허용한 것과 같은 구조다.</p>
<p class="en">The UK's Financial Conduct Authority has proposed letting UCITS (Undertakings for Collective Investment in Transferable Securities) schemes and certain non-UCITS retail schemes (NURS) hold cryptoasset exchange-traded notes (cETNs) up to 10% of scheme property. The FCA unveiled the plan in Consultation Paper 26/17, its 52nd quarterly consultation paper, published June 5; according to CoinDesk and The Block, the comment period closes July 13 — tomorrow. The FCA said the cap would "set conservative restrictions on the assets to which a fund can be exposed, in exchange for allowing these funds to be marketed to retail consumers." It mirrors a structure Luxembourg's financial regulator, the CSSF, adopted in February, when it allowed UCITS funds indirect crypto exposure up to 10% of net asset value.</p>
<p class="ja">英金融行為監督機構(FCA)が、UCITS(譲渡性証券集団投資事業)および一部の非UCITS小口投資家向けスキーム(NURS)に対し、暗号資産上場投資証券(cETN)を信託財産の最大10%まで組み入れることを認める案を打ち出した。FCAは6月5日発表の第52回四半期協議文書(CP26/17)でこの提案を公表しており、コインデスク(CoinDesk)やザ・ブロック(The Block)によれば、意見募集の締め切りは7月13日と明日に迫っている。FCAは協議文書で、この10%上限の狙いについて「これらのファンドが一般消費者向けに販売されることを認める代わりに、ファンドがさらされうる資産に保守的な制限を設けるもの」と説明した。これは2月にルクセンブルク金融監督委員会(CSSF)がUCITSの間接的な暗号資産エクスポージャーを純資産価値(NAV)の10%まで認めたのと同じ構造だ。</p>
<p class="es">La Autoridad de Conducta Financiera del Reino Unido (FCA) ha propuesto que los fondos UCITS (Organismos de Inversión Colectiva en Valores Mobiliarios) y ciertos esquemas minoristas no UCITS (NURS) puedan mantener notas cotizadas en bolsa sobre criptoactivos (cETN) hasta un 10% del patrimonio del fondo. La FCA presentó el plan en el Documento de Consulta 26/17, su 52ª consulta trimestral, publicado el 5 de junio; según CoinDesk y The Block, el plazo para comentarios cierra el 13 de julio, es decir, mañana. La FCA dijo que el límite establecería "restricciones conservadoras sobre los activos a los que un fondo puede estar expuesto, a cambio de permitir que estos fondos se comercialicen a consumidores minoristas". Esto refleja la estructura que el regulador financiero de Luxemburgo, la CSSF, adoptó en febrero, cuando permitió a los fondos UCITS una exposición cripto indirecta de hasta el 10% del valor liquidativo.</p>
<p class="de">Die britische Finanzaufsicht FCA hat vorgeschlagen, dass UCITS-Fonds (Organismen für gemeinsame Anlagen in Wertpapieren) und bestimmte Nicht-UCITS-Retailfonds (NURS) Krypto-Exchange-Traded-Notes (cETNs) bis zu 10 % des Fondsvermögens halten dürfen. Die FCA stellte den Plan in ihrem Konsultationspapier 26/17, dem 52. Quartalskonsultationspapier, vor, veröffentlicht am 5. Juni; laut CoinDesk und The Block endet die Kommentierungsfrist am 13. Juli — morgen. Die FCA erklärte, die Obergrenze würde "konservative Beschränkungen für die Vermögenswerte festlegen, denen ein Fonds ausgesetzt sein kann, im Gegenzug dafür, dass diese Fonds an Kleinanleger vermarktet werden dürfen". Das entspricht einer Struktur, die Luxemburgs Finanzaufsicht CSSF im Februar einführte, als sie UCITS-Fonds eine indirekte Krypto-Exponierung von bis zu 10 % des Nettoinventarwerts gestattete.</p>
<p class="fr">L'Autorité britannique de conduite financière (FCA) a proposé d'autoriser les fonds UCITS (organismes de placement collectif en valeurs mobilières) et certains schémas de détail non-UCITS (NURS) à détenir des billets cotés adossés à des cryptoactifs (cETN) à hauteur de 10 % maximum du patrimoine du fonds. La FCA a dévoilé ce projet dans le document de consultation 26/17, sa 52e consultation trimestrielle, publié le 5 juin ; selon CoinDesk et The Block, la période de commentaires se termine le 13 juillet, soit demain. La FCA a indiqué que ce plafond visait à « fixer des restrictions prudentes sur les actifs auxquels un fonds peut être exposé, en contrepartie de l'autorisation de commercialiser ces fonds auprès des consommateurs de détail ». Cela reprend une structure adoptée en février par le régulateur financier luxembourgeois, la CSSF, qui avait alors autorisé les fonds UCITS à une exposition crypto indirecte allant jusqu'à 10 % de la valeur liquidative.</p>
<p class="pt">A Autoridade de Conduta Financeira do Reino Unido (FCA) propôs permitir que fundos UCITS (Organismos de Investimento Coletivo em Valores Mobiliários) e certos esquemas de varejo não-UCITS (NURS) mantenham notas negociadas em bolsa sobre criptoativos (cETN) em até 10% do patrimônio do fundo. A FCA revelou o plano no Documento de Consulta 26/17, sua 52ª consulta trimestral, publicado em 5 de junho; segundo a CoinDesk e a The Block, o prazo para comentários se encerra em 13 de julho — amanhã. A FCA disse que o teto estabeleceria "restrições conservadoras sobre os ativos aos quais um fundo pode se expor, em troca de permitir que esses fundos sejam comercializados para consumidores de varejo". Isso reflete uma estrutura adotada em fevereiro pelo regulador financeiro de Luxemburgo, a CSSF, que permitiu aos fundos UCITS exposição cripto indireta de até 10% do valor líquido dos ativos.</p>
<p class="tr">Birleşik Krallık Finansal Davranış Otoritesi (FCA), UCITS (Devredilebilir Menkul Kıymetlere Yapılan Kolektif Yatırım Kuruluşları) fonlarının ve bazı UCITS dışı perakende fonlarının (NURS) kripto varlık borsada işlem gören senetlerini (cETN) fon varlığının en fazla yüzde 10'u kadar tutmasına izin verilmesini önerdi. FCA planı, 5 Haziranda yayınlanan 52. üç aylık danışma belgesi olan CP26/17'de açıkladı; CoinDesk ve The Block'a göre, görüş bildirme süresi 13 Temmuz'da, yani yarın sona eriyor. FCA, bu üst sınırın "bu fonların perakende tüketicilere pazarlanmasına izin verilmesi karşılığında, bir fonun maruz kalabileceği varlıklara muhafazakar kısıtlamalar getireceğini" belirtti. Bu, Lüksemburg finansal düzenleyicisi CSSF'nin Şubat ayında UCITS fonlarına net varlık değerinin yüzde 10'una kadar dolaylı kripto maruziyetine izin verdiğinde benimsediği yapıyla aynı.</p>
<p class="vi">Cơ quan Quản lý Tài chính Anh (FCA) đã đề xuất cho phép các quỹ UCITS (Tổ chức Đầu tư Tập thể vào Chứng khoán Chuyển nhượng) và một số chương trình bán lẻ ngoài UCITS (NURS) nắm giữ trái phiếu giao dịch trao đổi tài sản crypto (cETN) tối đa 10% tài sản của quỹ. FCA công bố kế hoạch này trong Tài liệu Tham vấn 26/17, tài liệu tham vấn hàng quý thứ 52, được công bố ngày 5/6; theo CoinDesk và The Block, thời hạn góp ý kết thúc vào ngày 13/7 — tức ngày mai. FCA cho biết mức trần này sẽ "đặt ra các hạn chế thận trọng đối với tài sản mà một quỹ có thể tiếp xúc, đổi lại việc cho phép các quỹ này được tiếp thị đến người tiêu dùng bán lẻ". Điều này phản ánh cấu trúc mà cơ quan quản lý tài chính Luxembourg, CSSF, đã áp dụng vào tháng 2, khi cho phép các quỹ UCITS tiếp xúc gián tiếp với crypto tối đa 10% giá trị tài sản ròng.</p>

<h2 class="ko">직접 매수에서 펀드 편입으로 — 5년에 걸쳐 세 단계로 풀린 빗장</h2>
<h2 class="en">From direct purchase to fund inclusion — five years, three stages of loosening</h2>
<h2 class="ja">直接購入からファンド組み入れへ — 5年かけて3段階で緩んだ規制</h2>
<h2 class="es">De la compra directa a la inclusión en fondos: cinco años, tres etapas de flexibilización</h2>
<h2 class="de">Vom Direktkauf zur Fondsaufnahme — fünf Jahre, drei Lockerungsstufen</h2>
<h2 class="fr">De l'achat direct à l'intégration dans les fonds : cinq ans, trois étapes d'assouplissement</h2>
<h2 class="pt">Da compra direta à inclusão em fundos — cinco anos, três etapas de flexibilização</h2>
<h2 class="tr">Doğrudan alımdan fon dahil edilmesine — beş yılda üç aşamalı gevşeme</h2>
<h2 class="vi">Từ mua trực tiếp đến đưa vào quỹ — năm năm, ba giai đoạn nới lỏng</h2>

<p class="ko">이번 제안은 하루아침에 나온 것이 아니라, 2021년 1월 전면 금지 이후 5년에 걸쳐 단계적으로 풀려온 흐름의 세 번째 단계다. FCA는 2021년 규제되지 않은 암호자산을 기초로 한 파생상품·ETN의 소매 판매·마케팅·유통을 전면 금지하며 "극심한 변동성"과 "시장남용 만연", "기초자산의 신뢰할 만한 가치평가 근거 부재"를 이유로 들었다. 2024년 3월에는 첫 완화가 있었다 — 런던증권거래소(LSE)나 시카고옵션거래소(Cboe) 같은 공인투자거래소(RIE)가 전문투자자 전용 cETN 상장 시장을 개설하겠다고 요청하면 이의를 제기하지 않기로 한 것이다. 이어 2025년 10월 8일에는 전면적인 소매 접근 금지 자체가 풀려, 개인 투자자도 RIE에 상장된 cETN을 금융판촉 규정상 위험고지를 받는 조건으로 직접 매수할 수 있게 됐다.</p>
<p class="en">This proposal didn't appear overnight — it's the third stage of a five-year loosening process that began with an outright ban in January 2021. Back then, the FCA banned the sale, marketing, and distribution to retail clients of derivatives and ETNs referencing unregulated cryptoassets, citing "extreme volatility," "the prevalence of market abuse," and "a lack of a reliable basis for valuation" of the underlying assets. The first relaxation came in March 2024, when the FCA said it would not object to recognised investment exchanges (RIEs) like the London Stock Exchange or Cboe creating a listed market segment for cETNs restricted to professional investors. Then on October 8, 2025, the blanket retail-access ban itself was lifted, letting individual investors directly buy RIE-listed cETNs, subject to financial-promotion risk-warning rules.</p>
<p class="ja">今回の提案は一夜にして出てきたものではなく、2021年1月の全面禁止以降、5年をかけて段階的に緩和されてきた流れの3段目にあたる。FCAは2021年、規制されていない暗号資産を裏付けとするデリバティブ・ETNの小口投資家向け販売・マーケティング・流通を全面禁止し、その理由として「極度のボラティリティ」「市場濫用の蔓延」「基礎資産に信頼できる評価根拠がないこと」を挙げた。2024年3月には最初の緩和があった — ロンドン証券取引所(LSE)やシカゴ・オプション取引所(Cboe)のような公認投資取引所(RIE)が、プロ投資家専用のcETN上場市場を開設したいと申請すれば異議を唱えないとしたのだ。続いて2025年10月8日には全面的な小口投資家向けアクセス禁止そのものが解除され、個人投資家もRIEに上場されたcETNを、金融プロモーション規則上のリスク告知を受けることを条件に直接購入できるようになった。</p>
<p class="es">Esta propuesta no surgió de la noche a la mañana: es la tercera etapa de un proceso de flexibilización de cinco años que comenzó con una prohibición total en enero de 2021. En aquel momento, la FCA prohibió la venta, comercialización y distribución a clientes minoristas de derivados y ETN referenciados a criptoactivos no regulados, citando "extrema volatilidad", "la prevalencia del abuso de mercado" y "la falta de una base fiable de valoración" de los activos subyacentes. La primera relajación llegó en marzo de 2024, cuando la FCA dijo que no se opondría a que bolsas de inversión reconocidas (RIE) como la Bolsa de Londres o Cboe crearan un segmento de mercado cotizado para cETN restringido a inversores profesionales. Luego, el 8 de octubre de 2025, se levantó la prohibición general de acceso minorista en sí, permitiendo a los inversores individuales comprar directamente cETN cotizados en RIE, sujeto a normas de advertencia de riesgo en promociones financieras.</p>
<p class="de">Dieser Vorschlag kam nicht über Nacht — er ist die dritte Stufe eines fünfjährigen Lockerungsprozesses, der im Januar 2021 mit einem vollständigen Verbot begann. Damals verbot die FCA den Verkauf, das Marketing und den Vertrieb von Derivaten und ETNs auf unregulierte Kryptoassets an Kleinanleger und verwies auf "extreme Volatilität", "die Verbreitung von Marktmissbrauch" und "das Fehlen einer verlässlichen Bewertungsgrundlage" der zugrunde liegenden Vermögenswerte. Die erste Lockerung kam im März 2024, als die FCA erklärte, sie werde nicht widersprechen, wenn anerkannte Investmentbörsen (RIEs) wie die London Stock Exchange oder Cboe ein börsennotiertes Marktsegment für cETNs schaffen, das auf professionelle Anleger beschränkt ist. Am 8. Oktober 2025 wurde dann das pauschale Verbot des Retail-Zugangs selbst aufgehoben, sodass Privatanleger RIE-notierte cETNs direkt kaufen konnten, vorbehaltlich der Risikohinweispflichten bei Finanzwerbung.</p>
<p class="fr">Cette proposition n'est pas apparue du jour au lendemain — elle constitue la troisième étape d'un processus d'assouplissement de cinq ans, qui a débuté par une interdiction totale en janvier 2021. À l'époque, la FCA avait interdit la vente, la commercialisation et la distribution aux clients de détail de produits dérivés et d'ETN référencés à des cryptoactifs non réglementés, invoquant une « volatilité extrême », « la prévalence des abus de marché » et « l'absence de base fiable d'évaluation » des actifs sous-jacents. Le premier assouplissement est intervenu en mars 2024, lorsque la FCA a indiqué qu'elle ne s'opposerait pas à ce que des bourses d'investissement reconnues (RIE) comme le London Stock Exchange ou Cboe créent un segment de marché coté pour les cETN, réservé aux investisseurs professionnels. Puis, le 8 octobre 2025, l'interdiction générale d'accès au détail elle-même a été levée, permettant aux investisseurs individuels d'acheter directement des cETN cotés sur les RIE, sous réserve des règles d'avertissement sur les risques en matière de promotion financière.</p>
<p class="pt">Esta proposta não surgiu do dia para a noite — é a terceira etapa de um processo de flexibilização de cinco anos que começou com uma proibição total em janeiro de 2021. Naquela ocasião, a FCA proibiu a venda, comercialização e distribuição a clientes de varejo de derivativos e ETNs referenciados a criptoativos não regulamentados, citando "volatilidade extrema", "a prevalência de abuso de mercado" e "a falta de uma base confiável de avaliação" dos ativos subjacentes. A primeira flexibilização veio em março de 2024, quando a FCA disse que não se oporia a que bolsas de investimento reconhecidas (RIEs), como a Bolsa de Londres ou a Cboe, criassem um segmento de mercado listado para cETNs restrito a investidores profissionais. Depois, em 8 de outubro de 2025, a proibição geral de acesso de varejo foi levantada, permitindo que investidores individuais comprassem diretamente cETNs listados em RIEs, sujeitos às regras de aviso de risco em promoções financeiras.</p>
<p class="tr">Bu öneri bir gecede ortaya çıkmadı — Ocak 2021'deki tam yasakla başlayan beş yıllık bir gevşeme sürecinin üçüncü aşaması bu. O dönemde FCA, düzenlenmemiş kripto varlıklara dayalı türev ürünlerin ve ETN'lerin perakende müşterilere satışını, pazarlamasını ve dağıtımını, dayanak varlıkların "aşırı oynaklığı", "piyasa suistimalinin yaygınlığı" ve "güvenilir bir değerleme temelinin bulunmaması" gerekçesiyle yasaklamıştı. İlk gevşeme Mart 2024'te geldi; FCA, Londra Menkul Kıymetler Borsası veya Cboe gibi tanınmış yatırım borsalarının (RIE) yalnızca profesyonel yatırımcılara yönelik bir cETN listeleme pazarı oluşturmasına itiraz etmeyeceğini açıkladı. Ardından 8 Ekim 2025'te perakende erişimine yönelik genel yasağın kendisi kaldırıldı ve bireysel yatırımcılar, finansal tanıtım risk uyarısı kurallarına tabi olarak RIE'de listelenen cETN'leri doğrudan satın alabilir hale geldi.</p>
<p class="vi">Đề xuất này không xuất hiện chỉ sau một đêm — đây là giai đoạn thứ ba của một quá trình nới lỏng kéo dài năm năm, bắt đầu bằng lệnh cấm hoàn toàn vào tháng 1/2021. Khi đó, FCA đã cấm việc bán, tiếp thị và phân phối cho khách hàng bán lẻ các sản phẩm phái sinh và ETN tham chiếu đến tài sản crypto không được quản lý, viện dẫn "sự biến động cực đoan", "tình trạng lạm dụng thị trường phổ biến" và "thiếu cơ sở định giá đáng tin cậy" của tài sản cơ sở. Sự nới lỏng đầu tiên đến vào tháng 3/2024, khi FCA cho biết sẽ không phản đối nếu các sàn giao dịch đầu tư được công nhận (RIE) như Sở Giao dịch Chứng khoán London hay Cboe tạo ra một phân khúc thị trường niêm yết cho cETN chỉ dành cho nhà đầu tư chuyên nghiệp. Sau đó, vào ngày 8/10/2025, chính lệnh cấm tiếp cận bán lẻ toàn diện đã được dỡ bỏ, cho phép nhà đầu tư cá nhân trực tiếp mua cETN niêm yết trên RIE, tuân theo các quy tắc cảnh báo rủi ro trong quảng cáo tài chính.</p>

<p class="ko">이번 CP26/17 제안은 여기서 한 걸음 더 나아간다. 지금까지는 개인이 스스로 판단해 cETN을 사는 '직접 매수'였다면, 이번에는 연금이나 개인저축계좌(ISA)에 흔히 담기는 UCITS·NURS 같은 소매펀드 자체가 그 펀드를 산 투자자 대신 cETN을 편입할 수 있게 된다. 즉 투자자가 "나는 크립토에 투자하겠다"고 능동적으로 선택하지 않아도, 이미 보유한 다각화 펀드 안에 최대 10%까지 크립토 익스포저가 '기본값'으로 섞여 들어올 수 있다는 의미다. 이는 자산운용사 입장에서는 상품 차별화의 기회지만, 소비자보호 관점에서는 위험고지 체계 자체가 달라져야 한다는 뜻이기도 하다.</p>
<p class="en">CP26/17 goes a step further still. Until now, buying a cETN meant an individual making an active, deliberate choice to do so directly. This proposal would instead let retail funds themselves — UCITS and NURS vehicles commonly held inside pensions or Individual Savings Accounts — embed cETNs on behalf of investors who bought the fund. In other words, an investor who never actively decided "I want crypto exposure" could still end up with up to 10% crypto exposure baked into a diversified fund they already hold, as a default. For asset managers, that's an opportunity to differentiate products; for consumer protection, it means the entire risk-disclosure framework has to work differently.</p>
<p class="ja">今回のCP26/17提案はここからさらに一歩踏み込む。これまでは個人が自ら能動的に判断してcETNを購入する「直接購入」だった。今回は年金や個人貯蓄口座(ISA)によく組み込まれるUCITS・NURSのような小口投資家向けファンド自体が、そのファンドを買った投資家に代わってcETNを組み入れられるようになる。つまり投資家が「自分は暗号資産に投資する」と能動的に選択しなくても、すでに保有している分散型ファンドの中に最大10%まで暗号資産エクスポージャーが「デフォルト」で混入しうるということだ。これは資産運用会社にとっては商品差別化の機会だが、消費者保護の観点からはリスク告知の枠組み自体が変わらねばならないことを意味する。</p>
<p class="es">CP26/17 va aún más lejos. Hasta ahora, comprar un cETN significaba que un individuo tomaba una decisión activa y deliberada de hacerlo directamente. Esta propuesta permitiría en cambio que los propios fondos minoristas —vehículos UCITS y NURS que suelen mantenerse dentro de pensiones o cuentas de ahorro individuales (ISA)— incorporen cETN en nombre de los inversores que compraron el fondo. En otras palabras, un inversor que nunca decidió activamente "quiero exposición a cripto" podría acabar teniendo hasta un 10% de exposición cripto integrada por defecto en un fondo diversificado que ya posee. Para los gestores de activos, eso es una oportunidad de diferenciar productos; para la protección del consumidor, significa que todo el marco de divulgación de riesgos debe funcionar de otra manera.</p>
<p class="de">CP26/17 geht noch einen Schritt weiter. Bisher bedeutete der Kauf eines cETN, dass eine Einzelperson aktiv und bewusst entschied, dies direkt zu tun. Dieser Vorschlag würde stattdessen den Retailfonds selbst — UCITS- und NURS-Vehikel, die häufig innerhalb von Renten oder individuellen Sparkonten (ISAs) gehalten werden — erlauben, cETNs im Namen von Anlegern einzubetten, die den Fonds gekauft haben. Mit anderen Worten: Ein Anleger, der nie aktiv entschieden hat "ich will Krypto-Exponierung", könnte trotzdem am Ende bis zu 10 % Krypto-Exponierung standardmäßig in einem bereits gehaltenen diversifizierten Fonds eingebettet finden. Für Vermögensverwalter ist das eine Chance zur Produktdifferenzierung; für den Verbraucherschutz bedeutet es, dass der gesamte Rahmen der Risikoaufklärung anders funktionieren muss.</p>
<p class="fr">Le CP26/17 va encore plus loin. Jusqu'à présent, acheter un cETN signifiait qu'un particulier faisait un choix actif et délibéré de le faire directement. Cette proposition permettrait plutôt aux fonds de détail eux-mêmes — véhicules UCITS et NURS couramment détenus au sein de pensions ou de comptes d'épargne individuels (ISA) — d'intégrer des cETN pour le compte des investisseurs ayant acheté le fonds. Autrement dit, un investisseur n'ayant jamais activement décidé « je veux une exposition crypto » pourrait tout de même se retrouver avec jusqu'à 10 % d'exposition crypto intégrée par défaut dans un fonds diversifié qu'il détient déjà. Pour les gestionnaires d'actifs, c'est une occasion de différencier leurs produits ; pour la protection des consommateurs, cela signifie que tout le cadre de divulgation des risques doit fonctionner différemment.</p>
<p class="pt">O CP26/17 vai ainda mais longe. Até agora, comprar um cETN significava que um indivíduo tomava uma decisão ativa e deliberada de fazê-lo diretamente. Esta proposta permitiria, em vez disso, que os próprios fundos de varejo — veículos UCITS e NURS comumente mantidos dentro de previdências ou contas de poupança individuais (ISA) — incorporassem cETNs em nome dos investidores que compraram o fundo. Em outras palavras, um investidor que nunca decidiu ativamente "quero exposição a cripto" poderia, ainda assim, acabar com até 10% de exposição cripto embutida por padrão em um fundo diversificado que já possui. Para os gestores de ativos, isso é uma oportunidade de diferenciar produtos; para a proteção do consumidor, significa que todo o arcabouço de divulgação de riscos precisa funcionar de forma diferente.</p>
<p class="tr">CP26/17 daha da ileri gidiyor. Şimdiye kadar bir cETN satın almak, bir bireyin bunu doğrudan yapmaya yönelik aktif, bilinçli bir seçim yapması anlamına geliyordu. Bu öneri ise, emeklilik veya Bireysel Tasarruf Hesapları (ISA) içinde yaygın olarak tutulan UCITS ve NURS araçları olan perakende fonların kendilerinin, fonu satın alan yatırımcılar adına cETN'leri gömmesine izin verecek. Başka bir deyişle, hiçbir zaman aktif olarak "kripto maruziyeti istiyorum" diye karar vermemiş bir yatırımcı, zaten sahip olduğu çeşitlendirilmiş bir fonun içine varsayılan olarak yüzde 10'a kadar kripto maruziyeti gömülmüş halde bulabilir. Varlık yöneticileri için bu, ürün farklılaştırma fırsatıdır; tüketici koruması açısından ise tüm risk açıklama çerçevesinin farklı işlemesi gerektiği anlamına gelir.</p>
<p class="vi">CP26/17 còn tiến xa hơn nữa. Cho đến nay, việc mua cETN có nghĩa là một cá nhân chủ động, có chủ đích quyết định làm điều đó trực tiếp. Đề xuất này thay vào đó sẽ cho phép chính các quỹ bán lẻ — các phương tiện UCITS và NURS thường được nắm giữ trong lương hưu hoặc Tài khoản Tiết kiệm Cá nhân (ISA) — đưa cETN vào thay mặt cho các nhà đầu tư đã mua quỹ đó. Nói cách khác, một nhà đầu tư chưa bao giờ chủ động quyết định "tôi muốn tiếp xúc với crypto" vẫn có thể có tới 10% mức độ tiếp xúc với crypto được tích hợp mặc định trong một quỹ đa dạng hóa mà họ đã nắm giữ. Đối với các công ty quản lý tài sản, đây là cơ hội để khác biệt hóa sản phẩm; đối với bảo vệ người tiêu dùng, điều đó có nghĩa là toàn bộ khung công bố rủi ro phải hoạt động theo cách khác.</p>

<h2 class="ko">'쓰레기 비율'이라는 뒷문 — ETN이 어떻게 크립토를 우회해 펀드에 들어가는가</h2>
<h2 class="en">The "trash ratio" backdoor — how ETNs let crypto slip into a fund</h2>
<h2 class="ja">「トラッシュ・レシオ」という裏口 — ETNはどうやって暗号資産をファンドに滑り込ませるのか</h2>
<h2 class="es">La puerta trasera del "trash ratio": cómo los ETN dejan que las criptomonedas se cuelen en un fondo</h2>
<h2 class="de">Die Hintertür namens "Trash Ratio" — wie ETNs Krypto in einen Fonds einschleusen</h2>
<h2 class="fr">La porte dérobée du « trash ratio » — comment les ETN font entrer la crypto dans un fonds</h2>
<h2 class="pt">A porta dos fundos do "trash ratio" — como os ETNs deixam a cripto entrar em um fundo</h2>
<h2 class="tr">"Çöp oranı" arka kapısı — ETN'ler kriptonun bir fona nasıl sızmasına izin veriyor</h2>
<h2 class="vi">Cửa hậu "tỷ lệ rác" — cách ETN để crypto lọt vào một quỹ</h2>

<p class="ko">UCITS 규정은 원래 암호자산 자체를 적격 자산으로 인정하지 않는다. 그런데도 이번 제안이 가능한 이유는 ETN이 법적으로 암호자산이 아니라 '양도성증권(transferable security)'으로 분류되는 채무증권이기 때문이다. cETN은 발행사가 비트코인 등 기초자산을 담보로 보유하며 그 가치를 추종하도록 설계된 채권 형태 상품으로, 증권거래소에 상장돼 거래된다는 형식만 갖추면 UCITS가 편입 가능한 '적격 양도성증권' 요건을 충족한다. 여기에 활용되는 장치가 이른바 '쓰레기 비율(trash ratio)'이다. UCITS 펀드는 원칙적으로 정해진 적격자산 목록 안에서만 투자해야 하지만, 이 목록에 딱 들어맞지 않는 자산도 분산 목적으로 신탁재산의 최대 10%까지는 예외적으로 담을 수 있도록 허용돼 왔다. 이번 FCA 제안은 바로 이 기존의 '10% 예외 바구니'를 cETN에 명시적으로 적용하겠다는 것이다.</p>
<p class="en">UCITS rules don't recognize cryptoassets themselves as eligible assets. Yet this proposal works because a cETN is legally classified not as a cryptoasset but as a debt security — a "transferable security." A cETN is a bond-like instrument, issued and backed by an issuer holding the underlying asset (such as bitcoin) to track its value, and as long as it's listed and traded on an exchange, it satisfies the formal requirements for an "eligible transferable security" that UCITS funds can hold. The mechanism enabling this is what's informally called the "trash ratio." UCITS funds are, in principle, required to invest only within a defined list of eligible assets, but they've long been permitted an exception: up to 10% of scheme property can go toward assets that don't neatly fit that list, for diversification purposes. This FCA proposal simply applies that pre-existing 10% exception basket explicitly to cETNs.</p>
<p class="ja">UCITS規則はもともと暗号資産そのものを適格資産として認めていない。それでも今回の提案が可能なのは、cETNが法的には暗号資産ではなく「譲渡性証券(transferable security)」に分類される債務証券だからだ。cETNは発行体がビットコインなどの原資産を担保として保有し、その価値を追随するよう設計された債券型商品であり、証券取引所に上場・取引されるという形式さえ整えば、UCITSが組み入れ可能な「適格譲渡性証券」の要件を満たす。ここで活用される仕組みがいわゆる「トラッシュ・レシオ(trash ratio)」だ。UCITSファンドは原則として定められた適格資産リストの範囲内でのみ投資すべきだが、このリストに正確には当てはまらない資産についても、分散目的で信託財産の最大10%までは例外的に組み入れることが従来から認められてきた。今回のFCA提案は、まさにこの既存の「10%例外バスケット」をcETNに明示的に適用しようとするものだ。</p>
<p class="es">Las normas UCITS no reconocen a los criptoactivos en sí mismos como activos elegibles. Sin embargo, esta propuesta funciona porque un cETN se clasifica legalmente no como un criptoactivo, sino como un valor de deuda: un "valor mobiliario". Un cETN es un instrumento similar a un bono, emitido y respaldado por un emisor que posee el activo subyacente (como bitcoin) para seguir su valor, y siempre que cotice y se negocie en una bolsa, cumple los requisitos formales de "valor mobiliario elegible" que los fondos UCITS pueden mantener. El mecanismo que lo permite es lo que informalmente se llama el "trash ratio". En principio, los fondos UCITS deben invertir solo dentro de una lista definida de activos elegibles, pero desde hace tiempo se les permite una excepción: hasta un 10% del patrimonio del fondo puede destinarse a activos que no encajan perfectamente en esa lista, con fines de diversificación. Esta propuesta de la FCA simplemente aplica esa cesta de excepción del 10% ya existente, de forma explícita, a los cETN.</p>
<p class="de">UCITS-Regeln erkennen Kryptoassets selbst nicht als zulässige Vermögenswerte an. Dennoch funktioniert dieser Vorschlag, weil ein cETN rechtlich nicht als Kryptoasset, sondern als Schuldtitel — ein "übertragbares Wertpapier" — eingestuft wird. Ein cETN ist ein anleiheähnliches Instrument, das von einem Emittenten ausgegeben und besichert wird, der den zugrunde liegenden Vermögenswert (etwa Bitcoin) hält, um dessen Wert nachzubilden, und solange es an einer Börse notiert und gehandelt wird, erfüllt es die formalen Anforderungen an ein "zulässiges übertragbares Wertpapier", das UCITS-Fonds halten dürfen. Der Mechanismus, der dies ermöglicht, wird inoffiziell "Trash Ratio" genannt. UCITS-Fonds müssen grundsätzlich nur innerhalb einer definierten Liste zulässiger Vermögenswerte investieren, doch es wurde ihnen seit Langem eine Ausnahme gestattet: Bis zu 10 % des Fondsvermögens können zu Diversifizierungszwecken in Vermögenswerte fließen, die nicht sauber in diese Liste passen. Dieser FCA-Vorschlag wendet lediglich diesen bereits bestehenden 10-%-Ausnahmekorb explizit auf cETNs an.</p>
<p class="fr">Les règles UCITS ne reconnaissent pas les cryptoactifs eux-mêmes comme des actifs éligibles. Pourtant, cette proposition fonctionne parce qu'un cETN est classé juridiquement non pas comme un cryptoactif, mais comme un titre de créance — une « valeur mobilière ». Un cETN est un instrument s'apparentant à une obligation, émis et adossé par un émetteur détenant l'actif sous-jacent (comme le bitcoin) pour en suivre la valeur, et tant qu'il est coté et négocié en bourse, il satisfait aux exigences formelles de « valeur mobilière éligible » que les fonds UCITS peuvent détenir. Le mécanisme qui le permet est ce qu'on appelle familièrement le « trash ratio ». Les fonds UCITS doivent en principe investir uniquement dans une liste définie d'actifs éligibles, mais une exception leur est accordée de longue date : jusqu'à 10 % du patrimoine du fonds peut être alloué à des actifs qui ne correspondent pas exactement à cette liste, à des fins de diversification. Cette proposition de la FCA ne fait qu'appliquer explicitement ce panier d'exception de 10 % préexistant aux cETN.</p>
<p class="pt">As regras UCITS não reconhecem os próprios criptoativos como ativos elegíveis. Ainda assim, esta proposta funciona porque um cETN é classificado juridicamente não como um criptoativo, mas como um título de dívida — um "valor mobiliário". Um cETN é um instrumento semelhante a um título, emitido e lastreado por um emissor que detém o ativo subjacente (como o bitcoin) para acompanhar seu valor, e, desde que seja listado e negociado em bolsa, atende aos requisitos formais de "valor mobiliário elegível" que os fundos UCITS podem manter. O mecanismo que possibilita isso é o chamado informalmente "trash ratio". Os fundos UCITS devem, em princípio, investir apenas dentro de uma lista definida de ativos elegíveis, mas há muito lhes é permitida uma exceção: até 10% do patrimônio do fundo pode ser destinado a ativos que não se encaixam perfeitamente nessa lista, para fins de diversificação. Esta proposta da FCA simplesmente aplica essa cesta de exceção de 10% já existente, de forma explícita, aos cETNs.</p>
<p class="tr">UCITS kuralları, kripto varlıkların kendisini uygun varlık olarak tanımıyor. Yine de bu öneri işe yarıyor çünkü bir cETN yasal olarak bir kripto varlık değil, bir borç senedi — bir "devredilebilir menkul kıymet" olarak sınıflandırılıyor. Bir cETN, değerini takip etmek için dayanak varlığı (bitcoin gibi) elinde tutan bir ihraççı tarafından çıkarılan ve teminat altına alınan tahvil benzeri bir araçtır ve bir borsada listelendiği ve işlem gördüğü sürece, UCITS fonlarının tutabileceği "uygun devredilebilir menkul kıymet" için resmi gereklilikleri karşılar. Bunu mümkün kılan mekanizma gayri resmi olarak "çöp oranı" olarak adlandırılan şeydir. UCITS fonları, ilke olarak, yalnızca tanımlanmış bir uygun varlıklar listesi içinde yatırım yapmak zorundadır, ancak uzun süredir bir istisnaya izin verilmektedir: fon varlığının yüzde 10'una kadarı, çeşitlendirme amacıyla bu listeye tam olarak uymayan varlıklara ayrılabilir. Bu FCA önerisi, mevcut bu yüzde 10 istisna sepetini basitçe açıkça cETN'lere uyguluyor.</p>
<p class="vi">Các quy tắc UCITS không công nhận bản thân tài sản crypto là tài sản đủ điều kiện. Tuy nhiên, đề xuất này vẫn hoạt động được vì một cETN được phân loại về mặt pháp lý không phải là tài sản crypto mà là chứng khoán nợ — một "chứng khoán chuyển nhượng". cETN là một công cụ giống trái phiếu, được phát hành và bảo đảm bởi một tổ chức phát hành nắm giữ tài sản cơ sở (như bitcoin) để theo dõi giá trị của nó, và miễn là nó được niêm yết và giao dịch trên một sàn giao dịch, nó đáp ứng các yêu cầu chính thức của một "chứng khoán chuyển nhượng đủ điều kiện" mà các quỹ UCITS có thể nắm giữ. Cơ chế cho phép điều này được gọi không chính thức là "tỷ lệ rác". Về nguyên tắc, các quỹ UCITS chỉ được đầu tư trong một danh sách tài sản đủ điều kiện xác định, nhưng từ lâu đã được phép có một ngoại lệ: tối đa 10% tài sản của quỹ có thể dành cho các tài sản không khớp hoàn toàn với danh sách đó, vì mục đích đa dạng hóa. Đề xuất này của FCA đơn giản là áp dụng rõ ràng giỏ ngoại lệ 10% đã tồn tại từ trước đó cho cETN.</p>

<p class="ko">공교롭게도 룩셈부르크 금융감독청(CSSF)이 지난 2월 4일 채택한 방식도 거의 동일하다. CSSF는 UCITS·대체투자펀드(AIF)에 관한 크립토자산 FAQ를 개정하며, cETN이 파생상품이 내재되지 않은 양도성증권에 해당한다는 전제 아래 UCITS의 간접 크립토 익스포저를 순자산가치의 10%까지 허용했다. 다만 이 익스포저를 담으려면 사전에 투자설명서(prospectus)에 명시해야 하고, 이는 사실상 CSSF의 사전 승인을 거쳐야 한다는 뜻이다. 즉 영국과 룩셈부르크가 서로 다른 감독기구임에도 거의 같은 시기에 같은 10%라는 숫자, 같은 법적 우회로(ETN을 통한 간접 편입)를 택한 셈이다. 이는 우연이라기보다는, 유럽 자산운용업계에서 이미 통용되던 '쓰레기 비율' 규정을 크립토에 적용하는 것이 가장 마찰이 적은 실무적 해법으로 자리 잡았음을 보여준다.</p>
<p class="en">Coincidentally, the approach Luxembourg's CSSF adopted on February 4 is nearly identical. In revising its crypto-asset FAQ for UCITS and alternative investment funds (AIFs), the CSSF allowed UCITS indirect crypto exposure up to 10% of net asset value, on the premise that a cETN qualifies as a transferable security without an embedded derivative. To include that exposure, though, a fund must disclose it in advance in its prospectus — which effectively means securing the CSSF's prior sign-off. In other words, two separate regulators in the UK and Luxembourg landed on nearly the same number — 10% — and the same legal workaround (indirect inclusion via ETNs) at nearly the same time. That looks less like coincidence than confirmation that applying the pre-existing "trash ratio" rule to crypto has become the path of least resistance across Europe's fund management industry.</p>
<p class="ja">奇しくも、ルクセンブルク金融監督委員会(CSSF)が2月4日に採用した方式もほぼ同一だ。CSSFはUCITS・オルタナティブ投資ファンド(AIF)向け暗号資産FAQを改定し、cETNが組み込みデリバティブのない譲渡性証券に該当するとの前提のもと、UCITSの間接的な暗号資産エクスポージャーを純資産価値の10%まで認めた。ただしこのエクスポージャーを組み入れるには事前に投資説明書(目論見書)へ明記する必要があり、これは事実上CSSFの事前承認を経る必要があることを意味する。つまり英国とルクセンブルクという別々の監督機関が、ほぼ同時期に同じ10%という数字、同じ法的迂回路(ETNを通じた間接組み入れ)を選んだことになる。これは偶然というより、欧州の資産運用業界ですでに通用していた「トラッシュ・レシオ」規定を暗号資産に適用することが、最も摩擦の少ない実務的解決策として定着したことを示している。</p>
<p class="es">Casualmente, el enfoque que adoptó la CSSF de Luxemburgo el 4 de febrero es casi idéntico. Al revisar sus preguntas frecuentes sobre criptoactivos para fondos UCITS y fondos de inversión alternativa (AIF), la CSSF permitió a los UCITS una exposición cripto indirecta de hasta el 10% del valor liquidativo, bajo la premisa de que un cETN califica como un valor mobiliario sin derivado incorporado. Sin embargo, para incluir esa exposición, un fondo debe declararla previamente en su folleto, lo que equivale en la práctica a obtener la aprobación previa de la CSSF. En otras palabras, dos reguladores distintos, en el Reino Unido y Luxemburgo, llegaron casi al mismo número —10%— y al mismo rodeo legal (inclusión indirecta vía ETN) casi al mismo tiempo. Eso parece menos una coincidencia que la confirmación de que aplicar la norma preexistente del "trash ratio" a las criptomonedas se ha convertido en el camino de menor resistencia en la industria europea de gestión de fondos.</p>
<p class="de">Zufälligerweise ist der Ansatz, den Luxemburgs CSSF am 4. Februar verabschiedete, nahezu identisch. Bei der Überarbeitung ihrer Krypto-Asset-FAQ für UCITS- und alternative Investmentfonds (AIFs) erlaubte die CSSF UCITS eine indirekte Krypto-Exponierung von bis zu 10 % des Nettoinventarwerts, unter der Voraussetzung, dass ein cETN als übertragbares Wertpapier ohne eingebettetes Derivat gilt. Um diese Exponierung aufzunehmen, muss ein Fonds sie jedoch vorab im Prospekt offenlegen — was faktisch bedeutet, die vorherige Zustimmung der CSSF einzuholen. Mit anderen Worten: Zwei getrennte Aufsichtsbehörden in Großbritannien und Luxemburg landeten fast zur gleichen Zeit bei nahezu derselben Zahl — 10 % — und demselben rechtlichen Umweg (indirekte Aufnahme über ETNs). Das wirkt weniger wie Zufall als wie eine Bestätigung, dass die Anwendung der bereits bestehenden "Trash Ratio"-Regel auf Krypto zum Weg des geringsten Widerstands in der europäischen Fondsbranche geworden ist.</p>
<p class="fr">Par coïncidence, l'approche adoptée par la CSSF luxembourgeoise le 4 février est presque identique. En révisant sa FAQ sur les cryptoactifs pour les fonds UCITS et les fonds d'investissement alternatifs (FIA), la CSSF a autorisé les UCITS à une exposition crypto indirecte allant jusqu'à 10 % de la valeur liquidative, sur la base du principe qu'un cETN est qualifié de valeur mobilière sans dérivé intégré. Toutefois, pour intégrer cette exposition, un fonds doit la déclarer au préalable dans son prospectus, ce qui revient en pratique à obtenir l'accord préalable de la CSSF. Autrement dit, deux régulateurs distincts, au Royaume-Uni et au Luxembourg, sont arrivés presque au même chiffre — 10 % — et au même contournement juridique (intégration indirecte via des ETN) à peu près au même moment. Cela ressemble moins à une coïncidence qu'à la confirmation que l'application de la règle préexistante du « trash ratio » à la crypto est devenue la voie de moindre résistance dans le secteur européen de la gestion de fonds.</p>
<p class="pt">Coincidentemente, a abordagem que a CSSF de Luxemburgo adotou em 4 de fevereiro é quase idêntica. Ao revisar suas perguntas frequentes sobre criptoativos para fundos UCITS e fundos de investimento alternativo (AIFs), a CSSF permitiu aos UCITS exposição cripto indireta de até 10% do valor líquido dos ativos, sob a premissa de que um cETN se qualifica como valor mobiliário sem derivativo embutido. Porém, para incluir essa exposição, um fundo deve declará-la previamente em seu prospecto — o que, na prática, significa obter a aprovação prévia da CSSF. Em outras palavras, dois reguladores distintos, no Reino Unido e em Luxemburgo, chegaram quase ao mesmo número — 10% — e ao mesmo desvio legal (inclusão indireta via ETNs) quase ao mesmo tempo. Isso parece menos uma coincidência do que a confirmação de que aplicar a regra pré-existente do "trash ratio" à cripto se tornou o caminho de menor resistência na indústria europeia de gestão de fundos.</p>
<p class="tr">Tesadüfen, Lüksemburg CSSF'nin 4 Şubat'ta benimsediği yaklaşım neredeyse aynı. UCITS ve alternatif yatırım fonları (AIF) için kripto varlık SSS'sini gözden geçirirken CSSF, bir cETN'in gömülü türev içermeyen bir devredilebilir menkul kıymet olarak nitelendirilmesi önkoşuluyla UCITS'lere net varlık değerinin yüzde 10'una kadar dolaylı kripto maruziyetine izin verdi. Ancak bu maruziyeti dahil etmek için bir fonun bunu önceden izahnamesinde açıklaması gerekir — bu da fiilen CSSF'nin ön onayını almak anlamına gelir. Başka bir deyişle, Birleşik Krallık ve Lüksemburg'daki iki ayrı düzenleyici, neredeyse aynı zamanda neredeyse aynı sayıya — yüzde 10 — ve aynı yasal çözüme (ETN'ler aracılığıyla dolaylı dahil etme) ulaştı. Bu, bir tesadüften çok, kriptoya önceden var olan "çöp oranı" kuralını uygulamanın Avrupa fon yönetimi sektöründe en az direnç gösteren yol haline geldiğinin bir onayı gibi görünüyor.</p>
<p class="vi">Tình cờ thay, cách tiếp cận mà CSSF Luxembourg áp dụng vào ngày 4/2 gần như giống hệt. Khi sửa đổi FAQ về tài sản crypto cho các quỹ UCITS và quỹ đầu tư thay thế (AIF), CSSF đã cho phép UCITS tiếp xúc gián tiếp với crypto tối đa 10% giá trị tài sản ròng, với tiền đề rằng cETN đủ điều kiện là chứng khoán chuyển nhượng không có phái sinh nhúng. Tuy nhiên, để đưa mức tiếp xúc đó vào, một quỹ phải công bố trước trong bản cáo bạch — điều này về cơ bản có nghĩa là phải có sự chấp thuận trước của CSSF. Nói cách khác, hai cơ quan quản lý riêng biệt ở Anh và Luxembourg đã đi đến gần như cùng một con số — 10% — và cùng một cách lách luật (đưa vào gián tiếp qua ETN) gần như cùng một thời điểm. Điều đó trông ít giống sự trùng hợp hơn là sự xác nhận rằng việc áp dụng quy tắc "tỷ lệ rác" đã tồn tại từ trước cho crypto đã trở thành con đường ít trở ngại nhất trong ngành quản lý quỹ châu Âu.</p>

<h2 class="ko">직접 매수와는 다른 무게 — 그리고 지금 지켜봐야 할 것</h2>
<h2 class="en">A different kind of weight than direct purchase — and what to watch now</h2>
<h2 class="ja">直接購入とは異なる重み — そして今後注視すべきこと</h2>
<h2 class="es">Un peso distinto al de la compra directa: qué vigilar ahora</h2>
<h2 class="de">Ein anderes Gewicht als der Direktkauf — und worauf jetzt zu achten ist</h2>
<h2 class="fr">Un poids différent de l'achat direct — et ce qu'il faut surveiller maintenant</h2>
<h2 class="pt">Um peso diferente da compra direta — e o que observar agora</h2>
<h2 class="tr">Doğrudan alımdan farklı bir ağırlık — ve şimdi izlenmesi gerekenler</h2>
<h2 class="vi">Một trọng lượng khác so với mua trực tiếp — và điều cần theo dõi lúc này</h2>

<p class="ko">회의론도 만만치 않다. 2024년 3월 전문투자자 전용 상장이 허용된 이후에도 실제로 RIE에 상장된 cETN 종목 수는 많지 않았고, 자산운용사들이 규제 허용과 별개로 상품을 실제로 내놓기까지는 시간이 걸렸다. 이번 10% 상한 역시 법적으로 가능해졌다고 해서 UCITS·NURS 펀드매니저들이 곧바로 편입에 나선다는 보장은 없다 — 개별 펀드가 크립토를 편입하려면 자체 이사회 승인과 투자설명서 개정, 위험고지 재설계를 거쳐야 하고, 변동성 관리·유동성 조건 등 실사도 필요하다. 미국에서는 이와 대조적으로 1940년법(Investment Company Act) 적용을 받는 뮤추얼펀드가 여전히 비슷한 분산투자 한도 규정 아래 놓여 있어, 개별 상장지수펀드(ETF)로 크립토에 투자하는 것과 뮤추얼펀드 자체에 크립토를 담는 것 사이에 큰 간극이 남아 있다. 영국·룩셈부르크의 이번 움직임은 그 간극을 유럽이 먼저 좁히려는 시도로 읽힌다.</p>
<p class="en">Skepticism is warranted, too. Even after professional-only listings were permitted in March 2024, relatively few cETNs actually got listed on RIEs, and asset managers took time to bring products to market even once the regulatory door was open. Legal permission for the 10% cap doesn't guarantee UCITS and NURS fund managers will rush to add crypto exposure — an individual fund still needs board approval, a revised prospectus, redesigned risk disclosures, and due diligence on volatility management and liquidity conditions before it can include a cETN. In the US, by contrast, mutual funds governed by the Investment Company Act of 1940 remain subject to similar diversification limits, leaving a wide gap between investing in crypto via a standalone ETF and embedding crypto inside a mutual fund itself. This UK and Luxembourg move reads as an attempt by Europe to close that gap first.</p>
<p class="ja">懐疑論も根強い。2024年3月にプロ投資家専用の上場が認められた後も、実際にRIEに上場されたcETN銘柄数は多くなく、規制上の許可とは別に、資産運用会社が実際に商品を投入するまでには時間がかかった。今回の10%上限についても、法的に可能になったからといってUCITS・NURSのファンドマネージャーがすぐさま組み入れに動くとは限らない — 個別ファンドが暗号資産を組み入れるには自社の取締役会承認、目論見書の改定、リスク告知の再設計を経る必要があり、ボラティリティ管理や流動性条件などのデューデリジェンスも必要になる。米国では対照的に、1940年法(投資会社法)の適用を受けるミューチュアルファンドが依然として同様の分散投資限度規定の下に置かれており、単体の上場投資信託(ETF)で暗号資産に投資することと、ミューチュアルファンド自体に暗号資産を組み入れることの間には大きな隔たりが残っている。英国・ルクセンブルクの今回の動きは、その隔たりを欧州が先に縮めようとする試みと読める。</p>
<p class="es">También hay razones para el escepticismo. Incluso después de que se permitieran las cotizaciones exclusivas para profesionales en marzo de 2024, relativamente pocos cETN llegaron a cotizar en RIE, y los gestores de activos tardaron en llevar productos al mercado incluso una vez abierta la puerta regulatoria. El permiso legal para el límite del 10% no garantiza que los gestores de fondos UCITS y NURS se apresuren a añadir exposición cripto: un fondo individual todavía necesita la aprobación de su junta, un folleto revisado, divulgaciones de riesgo rediseñadas y una debida diligencia sobre la gestión de la volatilidad y las condiciones de liquidez antes de poder incluir un cETN. En EE. UU., en cambio, los fondos mutuos regidos por la Ley de Sociedades de Inversión de 1940 siguen sujetos a límites de diversificación similares, dejando una brecha amplia entre invertir en cripto mediante un ETF independiente e incorporar cripto dentro de un fondo mutuo en sí. Este movimiento de Reino Unido y Luxemburgo se lee como un intento de Europa de cerrar primero esa brecha.</p>
<p class="de">Skepsis ist ebenfalls angebracht. Selbst nachdem im März 2024 rein professionelle Notierungen zugelassen wurden, kamen relativ wenige cETNs tatsächlich an RIEs zur Notierung, und Vermögensverwalter brauchten Zeit, um Produkte auf den Markt zu bringen, selbst als die regulatorische Tür bereits offen stand. Die rechtliche Zulassung der 10-%-Obergrenze garantiert nicht, dass UCITS- und NURS-Fondsmanager sich beeilen werden, Krypto-Exponierung hinzuzufügen — ein einzelner Fonds benötigt weiterhin eine Vorstandsgenehmigung, einen überarbeiteten Prospekt, neu gestaltete Risikoaufklärungen und eine Due-Diligence-Prüfung zu Volatilitätsmanagement und Liquiditätsbedingungen, bevor er einen cETN aufnehmen kann. In den USA hingegen unterliegen Investmentfonds, die dem Investment Company Act von 1940 unterliegen, weiterhin ähnlichen Diversifizierungsgrenzen, sodass eine große Lücke bleibt zwischen einer Krypto-Investition über einen eigenständigen ETF und der Einbettung von Krypto in einen Investmentfonds selbst. Dieser Schritt von Großbritannien und Luxemburg liest sich als Versuch Europas, diese Lücke als Erstes zu schließen.</p>
<p class="fr">Le scepticisme est également justifié. Même après l'autorisation des cotations réservées aux professionnels en mars 2024, relativement peu de cETN ont réellement été cotés sur les RIE, et les gestionnaires d'actifs ont mis du temps à lancer des produits, même une fois la porte réglementaire ouverte. L'autorisation légale du plafond de 10 % ne garantit pas que les gestionnaires de fonds UCITS et NURS se précipiteront pour ajouter une exposition crypto — un fonds individuel a toujours besoin de l'approbation de son conseil d'administration, d'un prospectus révisé, de divulgations de risques repensées et d'une diligence raisonnable sur la gestion de la volatilité et les conditions de liquidité avant de pouvoir inclure un cETN. Aux États-Unis, en revanche, les fonds communs de placement régis par l'Investment Company Act de 1940 restent soumis à des limites de diversification similaires, laissant un écart important entre investir dans la crypto via un ETF autonome et intégrer la crypto dans un fonds commun de placement lui-même. Ce mouvement du Royaume-Uni et du Luxembourg se lit comme une tentative de l'Europe de combler cet écart en premier.</p>
<p class="pt">O ceticismo também é justificado. Mesmo depois que as listagens exclusivas para profissionais foram permitidas em março de 2024, relativamente poucos cETNs chegaram a ser listados em RIEs, e os gestores de ativos levaram tempo para trazer produtos ao mercado mesmo depois que a porta regulatória foi aberta. A permissão legal para o teto de 10% não garante que os gestores de fundos UCITS e NURS vão se apressar em adicionar exposição cripto — um fundo individual ainda precisa de aprovação do conselho, de um prospecto revisado, de divulgações de risco redesenhadas e de due diligence sobre gestão de volatilidade e condições de liquidez antes de poder incluir um cETN. Nos EUA, em contraste, os fundos mútuos regidos pela Lei das Sociedades de Investimento de 1940 permanecem sujeitos a limites de diversificação semelhantes, deixando uma grande lacuna entre investir em cripto por meio de um ETF independente e incorporar cripto dentro de um fundo mútuo em si. Esse movimento do Reino Unido e de Luxemburgo se lê como uma tentativa da Europa de fechar essa lacuna primeiro.</p>
<p class="tr">Şüphecilik de haklı. Mart 2024'te yalnızca profesyonellere yönelik listelemelere izin verilmesinden sonra bile, RIE'lerde nispeten az sayıda cETN fiilen listelendi ve düzenleyici kapı açıldıktan sonra bile varlık yöneticilerinin ürünleri piyasaya sürmesi zaman aldı. Yüzde 10 üst sınır için yasal izin, UCITS ve NURS fon yöneticilerinin kripto maruziyeti eklemek için hemen harekete geçeceğinin garantisi değil — bireysel bir fonun bir cETN'i dahil edebilmesi için hâlâ yönetim kurulu onayı, revize edilmiş bir izahname, yeniden tasarlanmış risk açıklamaları ve oynaklık yönetimi ile likidite koşulları üzerine durum tespiti gerekiyor. Buna karşılık ABD'de, 1940 Yatırım Şirketi Yasası'na tabi yatırım fonları benzer çeşitlendirme sınırlarına tabi olmaya devam ediyor ve bağımsız bir ETF aracılığıyla kriptoya yatırım yapmak ile kriptoyu bir yatırım fonunun kendisine gömmek arasında geniş bir boşluk bırakıyor. Birleşik Krallık ve Lüksemburg'un bu hamlesi, Avrupa'nın bu boşluğu ilk kapatma girişimi olarak okunuyor.</p>
<p class="vi">Sự hoài nghi cũng có cơ sở. Ngay cả sau khi việc niêm yết chỉ dành cho chuyên nghiệp được cho phép vào tháng 3/2024, tương đối ít cETN thực sự được niêm yết trên các RIE, và các công ty quản lý tài sản đã mất thời gian để đưa sản phẩm ra thị trường ngay cả khi cánh cửa quản lý đã mở. Việc được phép hợp pháp đối với mức trần 10% không đảm bảo rằng các nhà quản lý quỹ UCITS và NURS sẽ vội vàng thêm mức tiếp xúc với crypto — một quỹ riêng lẻ vẫn cần sự chấp thuận của hội đồng quản trị, bản cáo bạch sửa đổi, công bố rủi ro được thiết kế lại, và thẩm định về quản lý biến động cùng điều kiện thanh khoản trước khi có thể đưa cETN vào. Ngược lại, ở Mỹ, các quỹ tương hỗ chịu sự điều chỉnh của Đạo luật Công ty Đầu tư năm 1940 vẫn phải tuân theo các giới hạn đa dạng hóa tương tự, để lại một khoảng cách lớn giữa việc đầu tư vào crypto qua một ETF độc lập và việc đưa crypto vào chính một quỹ tương hỗ. Động thái này của Anh và Luxembourg được hiểu là nỗ lực của châu Âu nhằm thu hẹp khoảng cách đó trước tiên.</p>

<p class="ko">지금 지켜봐야 할 지점은 세 가지로 좁혀진다. 첫째, 7월 13일 협의 마감 이후 FCA가 실제 최종 규칙을 언제 확정하고 시행일을 언제로 잡는지다. 둘째, 규칙이 확정된 뒤 실제로 몇 개의 UCITS·NURS 펀드가 cETN 편입을 투자설명서에 반영하고 나서는지 — 이는 법적 허용과 실제 상품화 사이의 간극이 이번에도 반복되는지를 가늠하는 척도가 된다. 셋째, 21셰어스(21Shares)·위즈덤트리(WisdomTree)·반에크(VanEck) 등 앞서 전문투자자용 상장을 준비했던 발행사들이 이 소매펀드 채널을 겨냥한 신규 상품을 얼마나 빨리 내놓는지다. 10%라는 숫자 자체는 작아 보이지만, 영국·룩셈부르크의 UCITS 시장 규모를 감안하면 실제 자금 유입 통로로서는 결코 작지 않은 잠재력을 지닌다.</p>
<p class="en">Three things narrow down what to watch now. First, once the July 13 consultation closes, when the FCA actually finalizes the rule and sets an effective date. Second, once the rule is final, how many UCITS and NURS funds actually update their prospectuses to include cETN exposure — a gauge of whether the gap between legal permission and real product launches repeats itself once again. Third, how quickly issuers such as 21Shares, WisdomTree, and VanEck, which had already prepared professional-only listings, roll out new products aimed at this retail-fund channel. The 10% figure itself may look modest, but given the sheer size of the UK and Luxembourg UCITS markets, its potential as an actual channel for fund inflows is far from trivial.</p>
<p class="ja">今後注視すべき点は3つに絞られる。第一に、7月13日の協議締め切り後、FCAが実際にいつ最終規則を確定し、施行日をいつに定めるかだ。第二に、規則確定後、実際に何本のUCITS・NURSファンドが目論見書にcETN組み入れを反映して発売に踏み切るか — これは法的許可と実際の商品化との間隙が今回も繰り返されるかを測る尺度になる。第三に、21シェアーズ(21Shares)、ウィズダムツリー(WisdomTree)、バンエック(VanEck)など先にプロ投資家向け上場を準備していた発行体が、この小口投資家向けファンドチャネルを狙った新商品をどれほど早く投入するかだ。10%という数字自体は小さく見えるが、英国・ルクセンブルクのUCITS市場規模を勘案すれば、実際の資金流入経路としては決して小さくない潜在力を持つ。</p>
<p class="es">Tres cosas acotan lo que hay que vigilar ahora. Primero, tras el cierre de la consulta el 13 de julio, cuándo finaliza realmente la FCA la norma y qué fecha de entrada en vigor fija. Segundo, una vez finalizada la norma, cuántos fondos UCITS y NURS actualizan realmente sus folletos para incluir exposición a cETN, un indicador de si la brecha entre la autorización legal y el lanzamiento real de productos se repite una vez más. Tercero, con qué rapidez emisores como 21Shares, WisdomTree y VanEck, que ya habían preparado cotizaciones exclusivas para profesionales, sacan al mercado nuevos productos dirigidos a este canal de fondos minoristas. La cifra del 10% en sí puede parecer modesta, pero dado el enorme tamaño de los mercados UCITS del Reino Unido y Luxemburgo, su potencial como canal real de entrada de fondos dista de ser trivial.</p>
<p class="de">Drei Dinge grenzen ein, worauf jetzt zu achten ist. Erstens, wann die FCA nach Abschluss der Konsultation am 13. Juli die Regel tatsächlich finalisiert und ein Inkrafttretensdatum festlegt. Zweitens, wie viele UCITS- und NURS-Fonds nach der endgültigen Regel tatsächlich ihre Prospekte aktualisieren, um cETN-Exponierung einzubeziehen — ein Gradmesser dafür, ob sich die Lücke zwischen rechtlicher Zulassung und tatsächlicher Produkteinführung erneut wiederholt. Drittens, wie schnell Emittenten wie 21Shares, WisdomTree und VanEck, die bereits rein professionelle Notierungen vorbereitet hatten, neue Produkte für diesen Retailfonds-Kanal auf den Markt bringen. Die Zahl 10 % selbst mag bescheiden wirken, aber angesichts der schieren Größe der UCITS-Märkte in Großbritannien und Luxemburg ist ihr Potenzial als tatsächlicher Kanal für Fondszuflüsse alles andere als trivial.</p>
<p class="fr">Trois éléments précisent ce qu'il faut surveiller maintenant. Premièrement, une fois la consultation close le 13 juillet, quand la FCA finalisera réellement la règle et fixera une date d'entrée en vigueur. Deuxièmement, une fois la règle finalisée, combien de fonds UCITS et NURS mettent réellement à jour leurs prospectus pour inclure une exposition aux cETN — une jauge permettant de voir si l'écart entre l'autorisation légale et le lancement réel de produits se répète une nouvelle fois. Troisièmement, la rapidité avec laquelle des émetteurs comme 21Shares, WisdomTree et VanEck, qui avaient déjà préparé des cotations réservées aux professionnels, lancent de nouveaux produits visant ce canal de fonds de détail. Le chiffre de 10 % en lui-même peut paraître modeste, mais compte tenu de la taille considérable des marchés UCITS britannique et luxembourgeois, son potentiel en tant que canal réel d'afflux de fonds est loin d'être négligeable.</p>
<p class="pt">Três coisas delimitam o que observar agora. Primeiro, depois que a consulta se encerrar em 13 de julho, quando a FCA realmente finalizará a regra e definirá uma data de vigência. Segundo, uma vez finalizada a regra, quantos fundos UCITS e NURS realmente atualizam seus prospectos para incluir exposição a cETN — um indicador de se a lacuna entre a permissão legal e o lançamento real de produtos se repete mais uma vez. Terceiro, com que rapidez emissores como 21Shares, WisdomTree e VanEck, que já haviam preparado listagens exclusivas para profissionais, lançam novos produtos voltados a esse canal de fundos de varejo. O número de 10% em si pode parecer modesto, mas, dado o tamanho considerável dos mercados UCITS do Reino Unido e de Luxemburgo, seu potencial como um canal real de entrada de recursos está longe de ser trivial.</p>
<p class="tr">Şimdi izlenmesi gerekenler üç noktaya indirgeniyor. Birincisi, 13 Temmuz'da danışma süreci kapandıktan sonra FCA'nın kuralı fiilen ne zaman kesinleştireceği ve bir yürürlük tarihi belirleyeceği. İkincisi, kural kesinleştikten sonra kaç UCITS ve NURS fonunun izahnamelerini cETN maruziyetini içerecek şekilde fiilen güncellediği — bu, yasal izin ile fiili ürün lansmanları arasındaki boşluğun bir kez daha tekrarlanıp tekrarlanmadığını ölçen bir gösterge. Üçüncüsü, daha önce yalnızca profesyonellere yönelik listelemeler hazırlamış olan 21Shares, WisdomTree ve VanEck gibi ihraççıların bu perakende fon kanalına yönelik yeni ürünleri ne kadar hızlı piyasaya süreceği. Yüzde 10 rakamının kendisi mütevazı görünebilir, ancak Birleşik Krallık ve Lüksemburg UCITS piyasalarının büyüklüğü göz önüne alındığında, gerçek bir fon girişi kanalı olarak potansiyeli hiç de küçük değil.</p>
<p class="vi">Ba điều thu hẹp lại những gì cần theo dõi lúc này. Thứ nhất, sau khi việc tham vấn kết thúc vào ngày 13/7, khi nào FCA thực sự hoàn thiện quy định và ấn định ngày có hiệu lực. Thứ hai, sau khi quy định được hoàn thiện, có bao nhiêu quỹ UCITS và NURS thực sự cập nhật bản cáo bạch để đưa vào mức tiếp xúc với cETN — một thước đo cho việc liệu khoảng cách giữa sự cho phép hợp pháp và việc ra mắt sản phẩm thực tế có lặp lại một lần nữa hay không. Thứ ba, các tổ chức phát hành như 21Shares, WisdomTree và VanEck, vốn đã chuẩn bị niêm yết chỉ dành cho nhà đầu tư chuyên nghiệp, sẽ tung ra sản phẩm mới nhắm vào kênh quỹ bán lẻ này nhanh đến mức nào. Bản thân con số 10% có thể trông khiêm tốn, nhưng xét đến quy mô khổng lồ của thị trường UCITS ở Anh và Luxembourg, tiềm năng của nó như một kênh thực sự để dòng vốn chảy vào không hề nhỏ.</p>

<div class="ko">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">영국 FCA 크립토 ETN 규제 완화 타임라인</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">2021.1</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">소매 전면금지</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">2024.3</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">전문투자자 RIE 상장</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">2025.10.8</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">소매 직접매수 허용</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">2026.6.5</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17: 펀드 10% 편입 제안</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">협의마감 7.13</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">UCITS/NURS 소매펀드, cETN 최대 10% 편입 가능</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">룩셈부르크 CSSF도 2026.2.4 동일한 10% NAV 한도 채택</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">FCA, CoinDesk, The Block, CSSF 발표 기준 재구성.</p>
</div>
<div class="en">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">UK FCA crypto ETN loosening timeline</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">Jan 2021</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Full retail ban</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">Mar 2024</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Professional-only RIE listing</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">Oct 8, 2025</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Retail direct purchase allowed</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">Jun 5, 2026</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17: 10% fund inclusion proposed</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">Consultation closes Jul 13</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">UCITS/NURS retail funds could hold up to 10% cETNs</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">Luxembourg's CSSF adopted the same 10% NAV cap on Feb 4, 2026</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Reconstructed from FCA, CoinDesk, The Block, and CSSF publications.</p>
</div>
<div class="ja">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">英FCA暗号資産ETN規制緩和タイムライン</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">2021.1</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">小口全面禁止</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">2024.3</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">プロ専用RIE上場</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">2025.10.8</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">小口直接購入許可</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">2026.6.5</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17:ファンド10%組入提案</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">協議締切7.13</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">UCITS/NURS小口ファンド、cETNを最大10%組入可能に</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">ルクセンブルクCSSFも2026.2.4に同じ10%NAV上限を採用</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">FCA、CoinDesk、The Block、CSSF発表をもとに再構成。</p>
</div>
<div class="es">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Cronología de flexibilización de ETN cripto de la FCA británica</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">Ene 2021</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Prohibición total</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">Mar 2024</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Cotización solo profesional</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">8 oct 2025</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Compra directa minorista</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">5 jun 2026</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17: 10% en fondos</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">Consulta cierra 13 jul</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">Fondos minoristas UCITS/NURS podrían tener hasta 10% en cETN</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">La CSSF de Luxemburgo adoptó el mismo tope del 10% del NAV el 4 feb 2026</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Reconstruido a partir de publicaciones de la FCA, CoinDesk, The Block y la CSSF.</p>
</div>
<div class="de">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Zeitleiste der Lockerung bei Krypto-ETNs der britischen FCA</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">Jan 2021</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Volles Retail-Verbot</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">Mär 2024</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Nur professionelle RIE-Notierung</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">8. Okt 2025</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Retail-Direktkauf erlaubt</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">5. Jun 2026</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17: 10% Fondsaufnahme</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">Konsultation endet 13. Jul</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">UCITS/NURS-Retailfonds könnten bis zu 10% cETNs halten</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">Luxemburgs CSSF übernahm dieselbe 10%-NAV-Grenze am 4. Feb 2026</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Rekonstruiert aus Veröffentlichungen von FCA, CoinDesk, The Block und CSSF.</p>
</div>
<div class="fr">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Chronologie de l'assouplissement des ETN crypto de la FCA</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">Jan 2021</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Interdiction totale</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">Mar 2024</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Cotation pro uniquement</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">8 oct 2025</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Achat direct retail permis</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">5 juin 2026</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17 : 10% dans les fonds</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">Consultation close le 13 juil.</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">Les fonds UCITS/NURS pourraient détenir jusqu'à 10% de cETN</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">La CSSF luxembourgeoise a adopté le même plafond de 10% de la VL le 4 fév 2026</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Reconstitué à partir des publications de la FCA, CoinDesk, The Block et la CSSF.</p>
</div>
<div class="pt">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Linha do tempo da flexibilização de ETNs cripto da FCA</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">Jan 2021</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Proibição total varejo</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">Mar 2024</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Listagem só profissional</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">8 out 2025</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Compra direta de varejo</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">5 jun 2026</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17: 10% em fundos</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">Consulta encerra 13 jul</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">Fundos de varejo UCITS/NURS poderiam ter até 10% em cETN</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">A CSSF de Luxemburgo adotou o mesmo teto de 10% do NAV em 4 fev 2026</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Reconstruído a partir de publicações da FCA, CoinDesk, The Block e CSSF.</p>
</div>
<div class="tr">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">İngiltere FCA kripto ETN gevşeme zaman çizelgesi</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">Oca 2021</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Tam perakende yasağı</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">Mar 2024</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Yalnızca profesyonel RIE listesi</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">8 Eki 2025</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Perakende doğrudan alım</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">5 Haz 2026</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17: Fonlarda %10 önerisi</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">Danışma 13 Tem'de kapanıyor</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">UCITS/NURS perakende fonları cETN'lerin %10'una kadar tutabilir</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">Lüksemburg CSSF de 4 Şub 2026'da aynı %10 NAV sınırını benimsedi</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">FCA, CoinDesk, The Block ve CSSF yayınlarından yeniden oluşturulmuştur.</p>
</div>
<div class="vi">
<svg viewBox="0 0 700 420" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Dòng thời gian nới lỏng cETN của FCA Anh</text>
  <g font-family="sans-serif">
    <line x1="60" y1="210" x2="650" y2="210" stroke="#3f3f46" stroke-width="3"/>
    <circle cx="100" cy="210" r="9" fill="#f87171"/>
    <text x="100" y="180" fill="#f87171" font-size="14" font-weight="700" text-anchor="middle">T1/2021</text>
    <text x="100" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Cấm hoàn toàn bán lẻ</text>
    <circle cx="260" cy="210" r="9" fill="#fbbf24"/>
    <text x="260" y="180" fill="#fbbf24" font-size="14" font-weight="700" text-anchor="middle">T3/2024</text>
    <text x="260" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Niêm yết chỉ chuyên nghiệp</text>
    <circle cx="420" cy="210" r="9" fill="#38bdf8"/>
    <text x="420" y="180" fill="#38bdf8" font-size="14" font-weight="700" text-anchor="middle">8/10/2025</text>
    <text x="420" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">Cho phép mua trực tiếp bán lẻ</text>
    <circle cx="580" cy="210" r="10" fill="#4ade80"/>
    <text x="580" y="180" fill="#4ade80" font-size="14" font-weight="700" text-anchor="middle">5/6/2026</text>
    <text x="580" y="160" fill="#a1a1aa" font-size="13" text-anchor="middle">CP26/17: đề xuất 10% trong quỹ</text>
    <text x="580" y="240" fill="#fbbf24" font-size="13" text-anchor="middle">Tham vấn kết thúc 13/7</text>
    <rect x="60" y="300" width="590" height="60" rx="8" fill="#1c1c1e" stroke="#3f3f46"/>
    <text x="355" y="325" fill="#d4d4d8" font-size="14" text-anchor="middle" font-weight="700">Quỹ bán lẻ UCITS/NURS có thể nắm giữ tới 10% cETN</text>
    <text x="355" y="347" fill="#a1a1aa" font-size="13" text-anchor="middle">CSSF Luxembourg cũng áp dụng cùng mức trần 10% NAV vào 4/2/2026</text>
  </g>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Được dựng lại từ các công bố của FCA, CoinDesk, The Block và CSSF.</p>
</div>

<div class="box ko">💡 <strong>지금 지켜봐야 할 것:</strong> (1) 7월13일 협의 마감 이후 FCA의 최종규칙 확정 시점과 시행일, (2) 실제로 cETN 편입을 투자설명서에 반영하는 UCITS·NURS 펀드 수, (3) 21셰어스·위즈덤트리·반에크 등 발행사의 소매펀드 채널 신상품 출시 속도. 법적 허용과 실제 자금 유입 사이에는 여전히 간극이 있을 수 있다.</div>
<div class="box en">💡 <strong>What to watch now:</strong> (1) when the FCA finalizes the rule and sets an effective date after the July 13 consultation closes; (2) how many UCITS and NURS funds actually update prospectuses to include cETN exposure; (3) how quickly issuers like 21Shares, WisdomTree, and VanEck roll out new retail-fund-channel products. A gap between legal permission and actual fund inflows may still remain.</div>
<div class="box ja">💡 <strong>今後注視すべきこと:</strong> (1) 7月13日の協議締め切り後、FCAが最終規則をいつ確定し施行日をいつに定めるか、(2) 実際にcETN組み入れを目論見書に反映するUCITS・NURSファンドの数、(3) 21シェアーズ・ウィズダムツリー・バンエックなど発行体の小口ファンドチャネル向け新商品の投入速度である。法的許可と実際の資金流入の間には依然として間隙が残る可能性がある。</div>
<div class="box es">💡 <strong>Qué vigilar ahora:</strong> (1) cuándo finaliza la FCA la norma y fija una fecha de entrada en vigor tras el cierre de la consulta el 13 de julio; (2) cuántos fondos UCITS y NURS actualizan realmente sus folletos para incluir exposición a cETN; (3) con qué rapidez emisores como 21Shares, WisdomTree y VanEck lanzan nuevos productos para este canal de fondos minoristas. Aún podría quedar una brecha entre la autorización legal y la entrada real de fondos.</div>
<div class="box de">💡 <strong>Worauf jetzt zu achten ist:</strong> (1) wann die FCA die Regel nach Abschluss der Konsultation am 13. Juli finalisiert und ein Inkrafttretensdatum festlegt; (2) wie viele UCITS- und NURS-Fonds tatsächlich ihre Prospekte aktualisieren, um cETN-Exponierung einzubeziehen; (3) wie schnell Emittenten wie 21Shares, WisdomTree und VanEck neue Produkte für diesen Retailfonds-Kanal auf den Markt bringen. Eine Lücke zwischen rechtlicher Zulassung und tatsächlichen Fondszuflüssen könnte weiterhin bestehen bleiben.</div>
<div class="box fr">💡 <strong>À surveiller maintenant :</strong> (1) quand la FCA finalisera la règle et fixera une date d'entrée en vigueur après la clôture de la consultation le 13 juillet ; (2) combien de fonds UCITS et NURS mettent réellement à jour leurs prospectus pour inclure une exposition aux cETN ; (3) la rapidité avec laquelle des émetteurs comme 21Shares, WisdomTree et VanEck lancent de nouveaux produits pour ce canal de fonds de détail. Un écart entre l'autorisation légale et les afflux de fonds réels pourrait subsister.</div>
<div class="box pt">💡 <strong>O que observar agora:</strong> (1) quando a FCA finalizará a regra e definirá uma data de vigência após o encerramento da consulta em 13 de julho; (2) quantos fundos UCITS e NURS realmente atualizam prospectos para incluir exposição a cETN; (3) com que rapidez emissores como 21Shares, WisdomTree e VanEck lançam novos produtos para esse canal de fundos de varejo. Uma lacuna entre a permissão legal e as entradas reais de recursos ainda pode persistir.</div>
<div class="box tr">💡 <strong>Şimdi izlenmesi gerekenler:</strong> (1) FCA'nın 13 Temmuz'daki danışma sürecinin kapanmasının ardından kuralı ne zaman kesinleştireceği ve bir yürürlük tarihi belirleyeceği; (2) kaç UCITS ve NURS fonunun cETN maruziyetini içerecek şekilde fiilen izahnamelerini güncellediği; (3) 21Shares, WisdomTree ve VanEck gibi ihraççıların bu perakende fon kanalına yönelik yeni ürünleri ne kadar hızlı piyasaya süreceği. Yasal izin ile fiili fon girişleri arasında hâlâ bir boşluk kalabilir.</div>
<div class="box vi">💡 <strong>Điều cần theo dõi lúc này:</strong> (1) khi nào FCA hoàn thiện quy định và ấn định ngày có hiệu lực sau khi tham vấn kết thúc vào ngày 13/7; (2) có bao nhiêu quỹ UCITS và NURS thực sự cập nhật bản cáo bạch để đưa vào mức tiếp xúc cETN; (3) các tổ chức phát hành như 21Shares, WisdomTree và VanEck sẽ tung ra sản phẩm mới cho kênh quỹ bán lẻ này nhanh đến mức nào. Khoảng cách giữa sự cho phép hợp pháp và dòng vốn thực tế vẫn có thể còn tồn tại.</div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 영국 금융행위감독청(FCA) CP26/17, 코인데스크(CoinDesk), 더블록(The Block), 룩셈부르크 금융감독청(CSSF) 크립토자산 FAQ, 데커트(Dechert)·EY 룩셈부르크 법률분석.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: UK Financial Conduct Authority CP26/17, CoinDesk, The Block, Luxembourg CSSF crypto-asset FAQ, and legal analysis from Dechert and EY Luxembourg.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: 英金融行為監督機構(FCA)CP26/17、コインデスク(CoinDesk)、ザ・ブロック(The Block)、ルクセンブルク金融監督委員会(CSSF)暗号資産FAQ、デカート(Dechert)・EYルクセンブルクの法律分析。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: FCA del Reino Unido CP26/17, CoinDesk, The Block, FAQ de criptoactivos de la CSSF de Luxemburgo, y análisis legal de Dechert y EY Luxemburgo.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: britische FCA CP26/17, CoinDesk, The Block, Krypto-Asset-FAQ der luxemburgischen CSSF sowie Rechtsanalysen von Dechert und EY Luxemburg.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : FCA britannique CP26/17, CoinDesk, The Block, FAQ crypto-actifs de la CSSF luxembourgeoise, et analyses juridiques de Dechert et EY Luxembourg.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: FCA do Reino Unido CP26/17, CoinDesk, The Block, FAQ de criptoativos da CSSF de Luxemburgo, e análises jurídicas da Dechert e EY Luxemburgo.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: İngiltere FCA CP26/17, CoinDesk, The Block, Lüksemburg CSSF kripto varlık SSS'si ve Dechert ile EY Luxembourg'un hukuki analizleri.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: FCA Vương quốc Anh CP26/17, CoinDesk, The Block, FAQ tài sản crypto của CSSF Luxembourg, và phân tích pháp lý từ Dechert và EY Luxembourg.</p>
<?php require __DIR__.'/_footer.php'; ?>
