<?php $slug = 'france-anj-polymarket-isp-block'; require __DIR__.'/_header.php'; ?>

<p class="ko">프랑스 도박감독기구인 국가도박청(ANJ)이 지난 16일 자국 인터넷서비스제공업체(ISP)들에 예측시장 플랫폼 폴리마켓(Polymarket) 접속을 차단하라고 명령했다. 코인데스크 등에 따르면 ANJ는 폴리마켓을 금융 거래 플랫폼이 아니라 무허가 불법 도박·베팅 사업자로 규정했으며, 프랑스 도박 규정을 준수할 때까지 차단을 유지하겠다고 밝혔다.</p>
<p class="en">France's national gambling regulator, the Autorité Nationale des Jeux (ANJ), ordered the country's internet service providers on July 16 to block access to the prediction-market platform Polymarket. According to CoinDesk and other outlets, the ANJ classified Polymarket not as a financial trading venue but as an unlicensed, illegal gambling and betting operator, and said the block would remain in place until the platform complies with French gambling rules.</p>
<p class="ja">フランスの国家賭博監督機関である国家賭博庁(ANJ)は7月16日、自国のインターネットサービスプロバイダー(ISP)各社に対し、予測市場プラットフォームのポリマーケット(Polymarket)へのアクセスを遮断するよう命じた。コインデスクなど複数の媒体によると、ANJはポリマーケットを金融取引の場ではなく、無許可の違法な賭博・ベッティング事業者と分類し、フランスの賭博規制に従うまで遮断を維持すると述べた。</p>
<p class="es">El regulador nacional de juego de apuestas de Francia, la Autorité Nationale des Jeux (ANJ), ordenó el 16 de julio a los proveedores de servicios de internet del país que bloquearan el acceso a la plataforma de mercados de predicción Polymarket. Según CoinDesk y otros medios, la ANJ clasificó a Polymarket no como una plataforma de negociación financiera, sino como un operador de apuestas y juego ilegal sin licencia, y afirmó que el bloqueo se mantendría hasta que la plataforma cumpliera con la normativa francesa de juego.</p>
<p class="de">Frankreichs nationale Glücksspielaufsicht, die Autorité Nationale des Jeux (ANJ), wies die Internetdienstanbieter des Landes am 16. Juli an, den Zugang zur Prognosemarkt-Plattform Polymarket zu sperren. Laut CoinDesk und anderen Medien stufte die ANJ Polymarket nicht als Finanzhandelsplattform, sondern als unlizenzierten, illegalen Glücksspiel- und Wettanbieter ein und erklärte, die Sperre bleibe bestehen, bis die Plattform die französischen Glücksspielregeln einhalte.</p>
<p class="fr">L'Autorité Nationale des Jeux (ANJ), le régulateur français des jeux d'argent, a ordonné le 16 juillet aux fournisseurs d'accès à internet du pays de bloquer l'accès à la plateforme de marchés prédictifs Polymarket. Selon CoinDesk et d'autres médias, l'ANJ a classé Polymarket non pas comme une plateforme de négociation financière, mais comme un opérateur de jeux d'argent et de paris illégal et non agréé, précisant que le blocage resterait en vigueur tant que la plateforme ne se conformerait pas à la réglementation française sur les jeux d'argent.</p>
<p class="pt">O regulador nacional de jogos de azar da França, a Autorité Nationale des Jeux (ANJ), ordenou em 16 de julho que os provedores de internet do país bloqueassem o acesso à plataforma de mercados de previsão Polymarket. Segundo a CoinDesk e outros veículos, a ANJ classificou a Polymarket não como uma plataforma de negociação financeira, mas como um operador de apostas e jogos de azar ilegal e sem licença, afirmando que o bloqueio permaneceria em vigor até que a plataforma cumprisse as regras francesas de jogo.</p>
<p class="tr">Fransa'nın ulusal kumar düzenleyicisi Autorité Nationale des Jeux (ANJ), 16 Temmuz'da ülkedeki internet servis sağlayıcılarına tahmin piyasası platformu Polymarket'e erişimi engelleme talimatı verdi. CoinDesk ve diğer kaynaklara göre ANJ, Polymarket'i bir finansal işlem platformu değil, lisanssız, yasa dışı bir kumar ve bahis operatörü olarak sınıflandırdı ve platform Fransız kumar kurallarına uyana kadar engellemenin devam edeceğini belirtti.</p>
<p class="vi">Cơ quan quản lý cờ bạc quốc gia của Pháp, Autorité Nationale des Jeux (ANJ), đã ra lệnh cho các nhà cung cấp dịch vụ internet trong nước vào ngày 16/7 chặn quyền truy cập vào nền tảng thị trường dự đoán Polymarket. Theo CoinDesk và các hãng tin khác, ANJ phân loại Polymarket không phải là một nền tảng giao dịch tài chính mà là một đơn vị vận hành cờ bạc và cá cược bất hợp pháp, không có giấy phép, và cho biết lệnh chặn sẽ được duy trì cho đến khi nền tảng này tuân thủ các quy định cờ bạc của Pháp.</p>
<p class="id">Regulator perjudian nasional Prancis, Autorité Nationale des Jeux (ANJ), memerintahkan penyedia layanan internet negara itu pada 16 Juli untuk memblokir akses ke platform pasar prediksi Polymarket. Menurut CoinDesk dan media lain, ANJ mengklasifikasikan Polymarket bukan sebagai platform perdagangan keuangan, melainkan sebagai operator perjudian dan taruhan ilegal tanpa izin, dan menyatakan pemblokiran akan tetap berlaku hingga platform tersebut mematuhi aturan perjudian Prancis.</p>
<p class="pl">Francuski krajowy regulator hazardu, Autorité Nationale des Jeux (ANJ), nakazał 16 lipca krajowym dostawcom usług internetowych zablokowanie dostępu do platformy rynków predykcyjnych Polymarket. Według CoinDesk i innych mediów ANJ zaklasyfikował Polymarket nie jako platformę obrotu finansowego, lecz jako nielicencjonowanego, nielegalnego operatora hazardu i zakładów, stwierdzając, że blokada pozostanie w mocy, dopóki platforma nie zastosuje się do francuskich przepisów hazardowych.</p>
<p class="it">Il regolatore nazionale del gioco d'azzardo francese, l'Autorité Nationale des Jeux (ANJ), ha ordinato il 16 luglio ai fornitori di servizi internet del paese di bloccare l'accesso alla piattaforma di mercati predittivi Polymarket. Secondo CoinDesk e altre testate, l'ANJ ha classificato Polymarket non come una piattaforma di negoziazione finanziaria, ma come un operatore di scommesse e gioco d'azzardo illegale e privo di licenza, affermando che il blocco sarebbe rimasto in vigore finché la piattaforma non si fosse conformata alle norme francesi sul gioco d'azzardo.</p>
<p class="ru">Национальный регулятор азартных игр Франции, Autorité Nationale des Jeux (ANJ), 16 июля предписал интернет-провайдерам страны заблокировать доступ к платформе рынков предсказаний Polymarket. По данным CoinDesk и других изданий, ANJ классифицировал Polymarket не как площадку для финансовой торговли, а как нелицензированного, незаконного оператора азартных игр и ставок, заявив, что блокировка сохранится до тех пор, пока платформа не будет соответствовать французским правилам азартных игр.</p>
<p class="zh">法國國家博彩監管機構「國家博彩局」(ANJ)於7月16日下令該國網路服務供應商封鎖預測市場平台Polymarket的存取。根據CoinDesk等多家媒體報導,ANJ將Polymarket定性為未經授權的非法博彩與投注業者,而非金融交易平台,並表示在該平台符合法國博彩規定之前,封鎖將持續有效。</p>

<p class="ko">이번 조치는 지난해 11월부터 시행 중이던 금융거래 금지 조치가 사실상 효과가 없었다는 판단에서 나왔다. ANJ에 따르면 6월 한 달간 프랑스에서만 20만5057명의 순방문자가 폴리마켓에 57만8751회 접속했다 — 금융거래는 막혔지만 사이트 접속과 예측 베팅 자체는 계속됐다는 뜻이다. ANJ는 이번엔 아예 ISP 단에서 접속 자체를 차단하는 더 강한 조치로 전환했다.</p>
<p class="en">The move follows a finding that a ban on financial transactions in place since November had proven largely ineffective. According to the ANJ, Polymarket drew 578,751 visits from 205,057 unique visitors in France in June alone — meaning the transaction ban had stopped payments but not access to the site or the placing of prediction bets themselves. This time, the regulator escalated to a stronger measure: blocking access at the ISP level entirely.</p>
<p class="ja">今回の措置は、昨年11月から実施していた金融取引禁止措置がほぼ効果を上げていなかったという判断に基づく。ANJによれば、6月だけでフランス国内から20万5057人の重複しない訪問者がポリマーケットに57万8751回アクセスした——取引禁止は決済を止めたが、サイトへのアクセスや予測ベット自体は止められなかったということだ。そこで規制当局は、ISP段階でアクセス自体を丸ごと遮断するというより強い措置に踏み切った。</p>
<p class="es">La medida llega tras constatar que la prohibición de transacciones financieras vigente desde noviembre había resultado en gran medida ineficaz. Según la ANJ, Polymarket registró 578.751 visitas de 205.057 visitantes únicos en Francia solo en junio, lo que significa que la prohibición de transacciones detuvo los pagos pero no el acceso al sitio ni la realización de apuestas de predicción en sí. Esta vez, el regulador escaló a una medida más contundente: bloquear el acceso por completo a nivel de proveedor de internet.</p>
<p class="de">Der Schritt folgt auf die Feststellung, dass ein seit November geltendes Verbot von Finanztransaktionen weitgehend wirkungslos geblieben war. Laut ANJ verzeichnete Polymarket allein im Juni 578.751 Besuche von 205.057 eindeutigen Besuchern in Frankreich — das Transaktionsverbot hatte also Zahlungen gestoppt, nicht aber den Zugang zur Seite oder das Platzieren von Prognosewetten selbst. Diesmal griff die Aufsichtsbehörde zu einer schärferen Maßnahme: der vollständigen Sperrung des Zugangs auf ISP-Ebene.</p>
<p class="fr">Cette mesure fait suite au constat qu'une interdiction des transactions financières en vigueur depuis novembre s'était révélée largement inefficace. Selon l'ANJ, Polymarket a enregistré 578 751 visites de la part de 205 057 visiteurs uniques en France rien qu'au mois de juin — ce qui signifie que l'interdiction des transactions avait stoppé les paiements, mais pas l'accès au site ni le placement de paris prédictifs en tant que tel. Cette fois, le régulateur a opté pour une mesure plus forte : le blocage complet de l'accès au niveau des fournisseurs d'accès.</p>
<p class="pt">A medida segue a constatação de que a proibição de transações financeiras em vigor desde novembro havia se mostrado, em grande parte, ineficaz. Segundo a ANJ, a Polymarket registrou 578.751 visitas de 205.057 visitantes únicos na França somente em junho — o que significa que a proibição de transações havia bloqueado os pagamentos, mas não o acesso ao site nem a realização das próprias apostas de previsão. Desta vez, o regulador escalou para uma medida mais forte: bloquear o acesso inteiramente no nível dos provedores de internet.</p>
<p class="tr">Bu adım, Kasım ayından bu yana yürürlükte olan finansal işlem yasağının büyük ölçüde etkisiz kaldığının tespit edilmesinin ardından geldi. ANJ'ye göre Polymarket, sadece Haziran ayında Fransa'da 205.057 tekil ziyaretçiden 578.751 ziyaret aldı — bu da işlem yasağının ödemeleri durdurduğunu ancak siteye erişimi veya tahmin bahislerinin yapılmasını durdurmadığını gösteriyor. Bu kez düzenleyici, erişimi doğrudan ISS seviyesinde tamamen engelleyen daha güçlü bir önleme geçti.</p>
<p class="vi">Động thái này được đưa ra sau khi phát hiện lệnh cấm giao dịch tài chính có hiệu lực từ tháng 11 phần lớn không hiệu quả. Theo ANJ, chỉ riêng trong tháng 6, Polymarket đã ghi nhận 578.751 lượt truy cập từ 205.057 khách truy cập duy nhất tại Pháp — nghĩa là lệnh cấm giao dịch đã ngăn được thanh toán nhưng không ngăn được việc truy cập trang web hay việc đặt cược dự đoán. Lần này, cơ quan quản lý đã leo thang sang một biện pháp mạnh hơn: chặn hoàn toàn quyền truy cập ở cấp nhà cung cấp dịch vụ internet.</p>
<p class="id">Langkah ini menyusul temuan bahwa larangan transaksi keuangan yang berlaku sejak November sebagian besar tidak efektif. Menurut ANJ, Polymarket menarik 578.751 kunjungan dari 205.057 pengunjung unik di Prancis hanya dalam bulan Juni — artinya larangan transaksi berhasil menghentikan pembayaran tetapi tidak menghentikan akses ke situs atau pemasangan taruhan prediksi itu sendiri. Kali ini, regulator meningkatkan langkahnya menjadi lebih tegas: memblokir akses sepenuhnya di level penyedia layanan internet.</p>
<p class="pl">Ten krok następuje po stwierdzeniu, że obowiązujący od listopada zakaz transakcji finansowych okazał się w dużej mierze nieskuteczny. Według ANJ Polymarket zanotował 578 751 wizyt od 205 057 unikalnych odwiedzających we Francji tylko w czerwcu — co oznacza, że zakaz transakcji zatrzymał płatności, ale nie dostęp do witryny ani samo obstawianie zakładów predykcyjnych. Tym razem regulator sięgnął po ostrzejszy środek: całkowite zablokowanie dostępu na poziomie dostawców internetu.</p>
<p class="it">La mossa segue la constatazione che un divieto sulle transazioni finanziarie in vigore da novembre si era rivelato in gran parte inefficace. Secondo l'ANJ, Polymarket ha registrato 578.751 visite da 205.057 visitatori unici in Francia nel solo mese di giugno — il che significa che il divieto sulle transazioni aveva fermato i pagamenti ma non l'accesso al sito né il piazzamento delle scommesse predittive stesse. Questa volta il regolatore è passato a una misura più severa: il blocco completo dell'accesso a livello di fornitore di servizi internet.</p>
<p class="ru">Этот шаг последовал за выводом о том, что запрет на финансовые транзакции, действующий с ноября, оказался в значительной степени неэффективным. По данным ANJ, только в июне Polymarket зафиксировал 578 751 посещение от 205 057 уникальных посетителей во Франции — то есть запрет на транзакции остановил платежи, но не доступ к сайту и не размещение ставок на предсказания как таковых. На этот раз регулятор перешёл к более жёсткой мере: полной блокировке доступа на уровне интернет-провайдеров.</p>
<p class="zh">此舉是在發現自去年11月起實施的金融交易禁令基本上未見成效之後採取的。根據ANJ數據,僅6月一個月,Polymarket在法國就吸引了20萬5057名不重複訪客,累計造訪57萬8751次——這意味著交易禁令雖然阻止了金流,卻未能阻止民眾造訪網站或實際下注預測。這一次,監管機構升級為更強硬的手段:直接在網路服務供應商層級全面封鎖存取。</p>

<h2 class="ko">샤를드골 공항 기상 센서, 그리고 2만1398달러의 수익</h2>
<h2 class="en">A Weather Sensor at Charles de Gaulle — and a $21,398 Payout</h2>
<h2 class="ja">シャルル・ド・ゴール空港の気象センサーと2万1398ドルの利益</h2>
<h2 class="es">Un Sensor Meteorológico en Charles de Gaulle — y un Pago de 21.398 Dólares</h2>
<h2 class="de">Ein Wettersensor am Charles-de-Gaulle-Flughafen — und eine Auszahlung von 21.398 Dollar</h2>
<h2 class="fr">Un Capteur Météo à Charles-de-Gaulle — et un Gain de 21 398 Dollars</h2>
<h2 class="pt">Um Sensor Meteorológico em Charles de Gaulle — e um Pagamento de US$ 21.398</h2>
<h2 class="tr">Charles de Gaulle'de Bir Hava Durumu Sensörü — ve 21.398 Dolarlık Bir Ödeme</h2>
<h2 class="vi">Một Cảm Biến Thời Tiết Tại Charles de Gaulle — Và Khoản Thanh Toán 21.398 Đô La</h2>
<h2 class="id">Sensor Cuaca di Charles de Gaulle — dan Pembayaran $21.398</h2>
<h2 class="pl">Czujnik Pogody na Lotnisku Charles de Gaulle — i Wypłata 21 398 Dolarów</h2>
<h2 class="it">Un Sensore Meteo a Charles de Gaulle — e un Guadagno di 21.398 Dollari</h2>
<h2 class="ru">Метеодатчик в Аэропорту Шарль-де-Голль — и Выплата в 21 398 Долларов</h2>
<h2 class="zh">戴高樂機場的氣象感測器,與2萬1398美元的獲利</h2>

<p class="ko">이번 차단 결정의 도화선이 된 사건은 지난 4월 파리 샤를드골 공항의 기상 관측 장비를 둘러싼 논란이었다. 'xX25Xx'라는 익명 이용자는 4월15일 파리 기온이 화씨 64도(섭씨 약 17.8도) 상당을 넘어설 것이라는 폴리마켓 계약에 119달러를 걸었는데, 실제로 그 직후 기온 급등이 관측 장비에 기록되면서 2만1398달러를 벌었다. 비슷한 시기 다른 이용자 두 명도 4월6일과 4월15일 각각 관측치가 급등한 직후 1만4000달러, 2만 달러를 챙겼다. 프랑스 기상청(메테오프랑스)은 "샤를드골 공항에 설치된 자동관측장비의 데이터 처리 시스템이 조작됐다"며 공식 고발장을 냈고, 파리 검찰 사이버범죄수사팀이 5월4일 수사에 착수했다.</p>
<p class="en">The spark for this escalation was a controversy in April involving a weather-monitoring device at Paris's Charles de Gaulle Airport. An anonymous user known as "xX25Xx" wagered $119 on a Polymarket contract that Paris temperatures would exceed roughly 64°F (about 17.8°C) on April 15 — and netted $21,398 in profit after a sudden spike was logged on the monitoring equipment shortly afterward. Around the same time, two other users pocketed $14,000 and $20,000 respectively after similar readings spiked on April 6 and April 15. France's national weather service, Météo-France, filed a formal complaint alleging "tampering with an automated data-processing system" at the airport, and the Paris prosecutor's cybercrime unit opened an investigation on May 4.</p>
<p class="ja">今回の措置強化の引き金となったのは、4月にパリのシャルル・ド・ゴール空港の気象観測装置をめぐって浮上した疑惑だった。「xX25Xx」という匿名ユーザーは、4月15日にパリの気温が華氏64度(摂氏約17.8度)相当を超えるというポリマーケットの契約に119ドルを賭け、その直後に観測装置で急激な気温上昇が記録されたことで2万1398ドルの利益を得た。ほぼ同時期に、別の2人のユーザーもそれぞれ4月6日と4月15日の観測値急騰の直後に1万4000ドル、2万ドルを得ていた。フランス気象庁(メテオフランス)は、同空港に設置された自動データ処理システムが「改ざんされた」として正式に告発状を提出し、パリ検察のサイバー犯罪捜査班が5月4日に捜査を開始した。</p>
<p class="es">La chispa de esta escalada fue una controversia surgida en abril en torno a un dispositivo de monitoreo meteorológico en el aeropuerto Charles de Gaulle de París. Un usuario anónimo conocido como "xX25Xx" apostó 119 dólares en un contrato de Polymarket que preveía que la temperatura de París superaría los 64°F (unos 17,8°C) el 15 de abril, y obtuvo una ganancia neta de 21.398 dólares después de que se registrara un repunte repentino en el equipo de monitoreo poco después. Casi al mismo tiempo, otros dos usuarios se embolsaron 14.000 y 20.000 dólares, respectivamente, tras registrarse repuntes similares el 6 y el 15 de abril. El servicio meteorológico nacional de Francia, Météo-France, presentó una denuncia formal alegando "manipulación de un sistema automatizado de procesamiento de datos" en el aeropuerto, y la unidad de delitos cibernéticos de la fiscalía de París abrió una investigación el 4 de mayo.</p>
<p class="de">Auslöser dieser Verschärfung war eine Kontroverse im April rund um ein Wettermessgerät am Pariser Flughafen Charles de Gaulle. Ein anonymer Nutzer namens "xX25Xx" setzte 119 Dollar auf einen Polymarket-Kontrakt, wonach die Temperatur in Paris am 15. April etwa 64°F (rund 17,8°C) überschreiten würde — und erzielte einen Gewinn von 21.398 Dollar, nachdem kurz darauf ein plötzlicher Anstieg vom Messgerät erfasst wurde. Etwa zur gleichen Zeit strichen zwei weitere Nutzer 14.000 bzw. 20.000 Dollar ein, nachdem ähnliche Messwerte am 6. und 15. April in die Höhe schossen. Frankreichs nationaler Wetterdienst Météo-France erstattete förmlich Anzeige wegen "Manipulation eines automatisierten Datenverarbeitungssystems" am Flughafen, und die Cyberkriminalitätseinheit der Pariser Staatsanwaltschaft leitete am 4. Mai Ermittlungen ein.</p>
<p class="fr">L'étincelle de cette escalade fut une controverse survenue en avril autour d'un dispositif de mesure météorologique à l'aéroport Charles-de-Gaulle de Paris. Un utilisateur anonyme connu sous le nom de « xX25Xx » a parié 119 dollars sur un contrat Polymarket selon lequel la température parisienne dépasserait environ 64°F (environ 17,8°C) le 15 avril — empochant un gain net de 21 398 dollars après qu'un pic soudain eut été enregistré par l'équipement de mesure peu après. À peu près à la même période, deux autres utilisateurs ont empoché respectivement 14 000 et 20 000 dollars après des relevés similaires en flèche les 6 et 15 avril. Météo-France, le service météorologique national, a déposé une plainte formelle pour « altération d'un système de traitement automatisé de données » à l'aéroport, et la brigade de lutte contre la cybercriminalité du parquet de Paris a ouvert une enquête le 4 mai.</p>
<p class="pt">A faísca dessa escalada foi uma controvérsia em abril envolvendo um dispositivo de monitoramento meteorológico no Aeroporto Charles de Gaulle, em Paris. Um usuário anônimo conhecido como "xX25Xx" apostou US$ 119 em um contrato da Polymarket que previa que a temperatura de Paris ultrapassaria cerca de 64°F (aproximadamente 17,8°C) em 15 de abril — e lucrou US$ 21.398 depois que um pico repentino foi registrado pelo equipamento de monitoramento pouco depois. Quase ao mesmo tempo, outros dois usuários embolsaram US$ 14.000 e US$ 20.000, respectivamente, após leituras semelhantes dispararem em 6 e 15 de abril. O serviço meteorológico nacional da França, Météo-France, apresentou uma queixa formal alegando "adulteração de um sistema automatizado de processamento de dados" no aeroporto, e a unidade de crimes cibernéticos do Ministério Público de Paris abriu uma investigação em 4 de maio.</p>
<p class="tr">Bu tırmanışın kıvılcımı, Nisan ayında Paris Charles de Gaulle Havalimanı'ndaki bir hava durumu izleme cihazı etrafında yaşanan bir tartışmaydı. "xX25Xx" adlı anonim bir kullanıcı, 15 Nisan'da Paris sıcaklığının yaklaşık 64°F'yi (yaklaşık 17,8°C) aşacağına dair bir Polymarket sözleşmesine 119 dolar yatırdı ve kısa süre sonra izleme ekipmanında ani bir yükseliş kaydedilince 21.398 dolar net kâr elde etti. Aynı dönemde, iki kullanıcı daha 6 ve 15 Nisan'da benzer okumaların sıçramasının ardından sırasıyla 14.000 ve 20.000 dolar cebe indirdi. Fransa'nın ulusal meteoroloji kurumu Météo-France, havalimanındaki "otomatik veri işleme sisteminin kurcalanması" iddiasıyla resmi şikayette bulundu ve Paris savcılığının siber suçlar birimi 4 Mayıs'ta soruşturma başlattı.</p>
<p class="vi">Ngòi nổ cho bước leo thang này là một vụ tranh cãi hồi tháng 4 liên quan đến một thiết bị quan trắc thời tiết tại Sân bay Charles de Gaulle của Paris. Một người dùng ẩn danh có tên "xX25Xx" đã đặt cược 119 đô la vào một hợp đồng Polymarket dự đoán nhiệt độ Paris sẽ vượt khoảng 64°F (khoảng 17,8°C) vào ngày 15/4 — và thu về khoản lãi ròng 21.398 đô la sau khi thiết bị quan trắc ghi nhận mức tăng đột biến ngay sau đó. Gần như cùng thời điểm, hai người dùng khác lần lượt bỏ túi 14.000 và 20.000 đô la sau khi các chỉ số tương tự tăng vọt vào ngày 6/4 và 15/4. Cơ quan khí tượng quốc gia Pháp, Météo-France, đã nộp đơn khiếu nại chính thức cáo buộc "can thiệp vào hệ thống xử lý dữ liệu tự động" tại sân bay, và đơn vị tội phạm mạng thuộc Viện công tố Paris đã mở cuộc điều tra vào ngày 4/5.</p>
<p class="id">Percikan bagi eskalasi ini adalah kontroversi pada April yang melibatkan perangkat pemantau cuaca di Bandara Charles de Gaulle Paris. Pengguna anonim bernama "xX25Xx" memasang taruhan $119 pada kontrak Polymarket bahwa suhu Paris akan melampaui sekitar 64°F (sekitar 17,8°C) pada 15 April — dan meraup untung bersih $21.398 setelah lonjakan mendadak tercatat pada peralatan pemantau tak lama kemudian. Sekitar waktu yang sama, dua pengguna lain masing-masing mengantongi $14.000 dan $20.000 setelah pembacaan serupa melonjak pada 6 dan 15 April. Badan meteorologi nasional Prancis, Météo-France, mengajukan pengaduan resmi yang menuduh "pengubahan sistem pemrosesan data otomatis" di bandara tersebut, dan unit kejahatan siber kejaksaan Paris membuka penyelidikan pada 4 Mei.</p>
<p class="pl">Iskrą, która wywołała tę eskalację, była kwietniowa kontrowersja związana z urządzeniem do pomiaru pogody na lotnisku Charles de Gaulle w Paryżu. Anonimowy użytkownik znany jako „xX25Xx" postawił 119 dolarów na kontrakt Polymarket zakładający, że temperatura w Paryżu przekroczy około 64°F (ok. 17,8°C) 15 kwietnia — i zarobił netto 21 398 dolarów, gdy krótko potem sprzęt pomiarowy odnotował nagły skok. Mniej więcej w tym samym czasie dwóch innych użytkowników zainkasowało odpowiednio 14 000 i 20 000 dolarów po podobnych skokach odczytów 6 i 15 kwietnia. Francuska narodowa służba meteorologiczna, Météo-France, złożyła formalne zawiadomienie, zarzucając „manipulację zautomatyzowanym systemem przetwarzania danych" na lotnisku, a jednostka ds. cyberprzestępczości prokuratury paryskiej wszczęła śledztwo 4 maja.</p>
<p class="it">La scintilla di questa escalation fu una controversia di aprile riguardante un dispositivo di monitoraggio meteorologico all'aeroporto Charles de Gaulle di Parigi. Un utente anonimo noto come "xX25Xx" ha scommesso 119 dollari su un contratto Polymarket secondo cui la temperatura di Parigi avrebbe superato circa 64°F (circa 17,8°C) il 15 aprile — incassando un profitto netto di 21.398 dollari dopo che poco dopo l'apparecchiatura di monitoraggio registrò un'improvvisa impennata. Più o meno nello stesso periodo, altri due utenti hanno intascato rispettivamente 14.000 e 20.000 dollari dopo letture simili impennate il 6 e il 15 aprile. Il servizio meteorologico nazionale francese, Météo-France, ha presentato una denuncia formale accusando una "manomissione di un sistema automatizzato di elaborazione dati" presso l'aeroporto, e l'unità cybercrime della procura di Parigi ha aperto un'indagine il 4 maggio.</p>
<p class="ru">Искрой для этой эскалации стал апрельский скандал вокруг метеорологического датчика в парижском аэропорту Шарль-де-Голль. Анонимный пользователь под ником «xX25Xx» поставил 119 долларов на контракт Polymarket о том, что температура в Париже 15 апреля превысит примерно 64°F (около 17,8°C), и заработал чистыми 21 398 долларов после того, как вскоре после этого измерительное оборудование зафиксировало резкий скачок. Примерно в то же время двое других пользователей получили 14 000 и 20 000 долларов соответственно после аналогичных скачков показаний 6 и 15 апреля. Национальная метеослужба Франции, Météo-France, подала официальную жалобу, утверждая о «вмешательстве в автоматизированную систему обработки данных» в аэропорту, а отдел по киберпреступлениям прокуратуры Парижа начал расследование 4 мая.</p>
<p class="zh">引爆此次升級的導火線,是4月間發生在巴黎戴高樂機場一具氣象監測裝置上的爭議事件。一名代號「xX25Xx」的匿名用戶,以119美元押注一份Polymarket合約,賭巴黎氣溫將於4月15日突破約華氏64度(約攝氏17.8度)——結果監測設備隨後記錄到氣溫驟升,該用戶淨賺2萬1398美元。差不多同一時期,另外兩名用戶也分別在4月6日與4月15日類似讀數飆升後,各自進帳1萬4000美元與2萬美元。法國國家氣象局(Météo-France)正式提出申訴,指控機場「自動數據處理系統遭到竄改」,巴黎檢方網路犯罪小組於5月4日展開調查。</p>

<p class="ko">이 사건이 문제적인 이유는 예측시장 특유의 구조적 약점을 드러내기 때문이다. 폴리마켓 같은 이벤트 기반 예측시장은 다수 참여자의 실시간 매매로 가격이 형성되는 일반 금융시장과 달리, 계약 만기 시점에 '단 하나의 공개된 데이터 포인트'(이 경우 공항 기상 관측치)로 정산된다. 즉 그 데이터 포인트를 만들어내는 물리적 장비나 소스에 접근해 조작할 수 있는 사람이 있다면, 매매 물량이나 시장 흐름과 무관하게 확정적인 수익을 낼 수 있다. 이는 디파이(DeFi)에서 반복적으로 문제가 됐던 '온체인 가격 오라클 조작' 공격과 개념적으로 같은 취약점이 오프라인 데이터에서도 그대로 재현될 수 있음을 보여준 사례다.</p>
<p class="en">The episode is instructive because it exposes a structural weakness specific to prediction markets. Unlike ordinary financial markets, where prices form continuously from many participants' trades, an event-based market like Polymarket settles on a single publicly reported data point at expiry — in this case, an airport's temperature reading. Anyone with physical access to tamper with the device or source generating that data point can lock in a guaranteed profit, regardless of trading volume or market sentiment. Conceptually, it's the same vulnerability class as the on-chain price-oracle manipulation attacks that have repeatedly hit DeFi protocols — except here the "oracle" being manipulated sits in the physical world rather than on a blockchain.</p>
<p class="ja">この事案が示唆に富むのは、予測市場特有の構造的な弱点を露呈したからだ。多数の参加者の取引で価格が継続的に形成される通常の金融市場と異なり、ポリマーケットのようなイベント型市場は満期時点で「唯一の公開されたデータポイント」——このケースでは空港の気温観測値——で決済される。つまり、そのデータポイントを生み出す物理的な装置やソースに手を加えられる人物がいれば、取引量や市況とは無関係に確定的な利益を得られてしまう。これは概念的には、DeFiで繰り返し問題となってきたオンチェーン価格オラクル操作攻撃と同じ脆弱性の系統であり、違いは操作対象の「オラクル」がブロックチェーン上ではなく物理世界に存在する点だけだ。</p>
<p class="es">El episodio resulta instructivo porque expone una debilidad estructural específica de los mercados de predicción. A diferencia de los mercados financieros ordinarios, donde los precios se forman continuamente a partir de las operaciones de muchos participantes, un mercado basado en eventos como Polymarket se liquida con un único dato publicado al vencimiento —en este caso, una lectura de temperatura de un aeropuerto—. Cualquiera con acceso físico para manipular el dispositivo o la fuente que genera ese dato puede asegurarse una ganancia garantizada, sin importar el volumen de operaciones o el sentimiento del mercado. Conceptualmente, es la misma clase de vulnerabilidad que los ataques de manipulación de oráculos de precios on-chain que han golpeado repetidamente a los protocolos DeFi, solo que aquí el "oráculo" manipulado reside en el mundo físico y no en una cadena de bloques.</p>
<p class="de">Der Vorfall ist aufschlussreich, weil er eine strukturelle Schwäche offenlegt, die für Prognosemärkte spezifisch ist. Anders als auf normalen Finanzmärkten, wo sich Preise fortlaufend aus den Geschäften vieler Teilnehmer bilden, wird ein ereignisbasierter Markt wie Polymarket bei Fälligkeit anhand eines einzigen öffentlich gemeldeten Datenpunkts abgerechnet — in diesem Fall eine Temperaturmessung am Flughafen. Wer physischen Zugang hat, um das Gerät oder die Quelle dieses Datenpunkts zu manipulieren, kann sich unabhängig von Handelsvolumen oder Marktstimmung einen garantierten Gewinn sichern. Konzeptionell ist das dieselbe Verwundbarkeitsklasse wie die On-Chain-Preisorakel-Manipulationsangriffe, die DeFi-Protokolle immer wieder getroffen haben — nur befindet sich das manipulierte "Orakel" hier in der physischen Welt statt auf einer Blockchain.</p>
<p class="fr">Cet épisode est instructif car il expose une faiblesse structurelle propre aux marchés prédictifs. Contrairement aux marchés financiers ordinaires, où les prix se forment en continu à partir des transactions de nombreux participants, un marché basé sur un événement comme Polymarket se règle à l'échéance sur un unique point de donnée rendu public — ici, un relevé de température aéroportuaire. Quiconque a un accès physique permettant de trafiquer l'appareil ou la source produisant ce point de donnée peut s'assurer un gain garanti, indépendamment du volume d'échanges ou du sentiment de marché. Conceptuellement, il s'agit de la même classe de vulnérabilité que les attaques par manipulation d'oracles de prix on-chain qui ont frappé à répétition les protocoles DeFi — sauf qu'ici, l'« oracle » manipulé se trouve dans le monde physique plutôt que sur une blockchain.</p>
<p class="pt">O episódio é instrutivo porque expõe uma fragilidade estrutural específica dos mercados de previsão. Diferentemente dos mercados financeiros comuns, em que os preços se formam continuamente a partir das negociações de muitos participantes, um mercado baseado em eventos como a Polymarket se liquida, no vencimento, com base em um único ponto de dado divulgado publicamente — neste caso, uma leitura de temperatura de aeroporto. Qualquer pessoa com acesso físico para adulterar o dispositivo ou a fonte que gera esse dado pode garantir um lucro certo, independentemente do volume de negociação ou do sentimento de mercado. Conceitualmente, é a mesma classe de vulnerabilidade dos ataques de manipulação de oráculos de preços on-chain que atingiram repetidamente protocolos DeFi — só que aqui o "oráculo" manipulado está no mundo físico, não em uma blockchain.</p>
<p class="tr">Bu olay öğretici çünkü tahmin piyasalarına özgü yapısal bir zayıflığı gözler önüne seriyor. Fiyatların birçok katılımcının işlemlerinden sürekli olarak oluştuğu sıradan finansal piyasaların aksine, Polymarket gibi olay tabanlı bir piyasa, vade sonunda kamuya açıklanan tek bir veri noktasına -bu durumda bir havalimanı sıcaklık okumasına- göre sonuçlanıyor. O veri noktasını üreten cihaza veya kaynağa fiziksel erişimle müdahale edebilecek herkes, işlem hacmi veya piyasa duyarlılığından bağımsız olarak garantili bir kâr elde edebilir. Kavramsal olarak bu, DeFi protokollerini defalarca vuran zincir üstü fiyat oracle'ı manipülasyon saldırılarıyla aynı zafiyet sınıfıdır -tek fark, burada manipüle edilen "oracle"ın bir blok zinciri üzerinde değil, fiziksel dünyada bulunmasıdır.</p>
<p class="vi">Sự việc này mang tính chỉ dấu bởi nó phơi bày một điểm yếu cấu trúc đặc thù của các thị trường dự đoán. Khác với thị trường tài chính thông thường, nơi giá được hình thành liên tục từ giao dịch của nhiều bên tham gia, một thị trường dựa trên sự kiện như Polymarket sẽ tất toán dựa trên một điểm dữ liệu công khai duy nhất tại thời điểm đáo hạn — trong trường hợp này là chỉ số nhiệt độ của sân bay. Bất kỳ ai có quyền tiếp cận vật lý để can thiệp vào thiết bị hoặc nguồn tạo ra điểm dữ liệu đó đều có thể chốt được khoản lợi nhuận chắc chắn, bất kể khối lượng giao dịch hay tâm lý thị trường. Về mặt khái niệm, đây là cùng một loại lỗ hổng như các cuộc tấn công thao túng oracle giá trên chuỗi từng nhiều lần tấn công các giao thức DeFi — chỉ khác là "oracle" bị thao túng ở đây nằm trong thế giới vật lý chứ không phải trên blockchain.</p>
<p class="id">Episode ini bersifat instruktif karena mengungkap kelemahan struktural yang khas pada pasar prediksi. Berbeda dari pasar keuangan biasa, di mana harga terbentuk secara berkelanjutan dari transaksi banyak peserta, pasar berbasis peristiwa seperti Polymarket diselesaikan berdasarkan satu titik data yang dilaporkan secara publik saat jatuh tempo — dalam kasus ini, pembacaan suhu bandara. Siapa pun yang memiliki akses fisik untuk mengutak-atik perangkat atau sumber yang menghasilkan titik data tersebut dapat mengunci keuntungan yang terjamin, terlepas dari volume perdagangan atau sentimen pasar. Secara konseptual, ini adalah kelas kerentanan yang sama dengan serangan manipulasi oracle harga on-chain yang berulang kali menghantam protokol DeFi — hanya saja "oracle" yang dimanipulasi di sini berada di dunia fisik, bukan di blockchain.</p>
<p class="pl">Ten epizod jest pouczający, ponieważ obnaża słabość strukturalną specyficzną dla rynków predykcyjnych. W przeciwieństwie do zwykłych rynków finansowych, gdzie ceny kształtują się w sposób ciągły na podstawie transakcji wielu uczestników, rynek oparty na zdarzeniach, taki jak Polymarket, rozlicza się w momencie wygaśnięcia na podstawie jednego, publicznie podanego punktu danych — w tym przypadku odczytu temperatury z lotniska. Każdy, kto ma fizyczny dostęp umożliwiający manipulację urządzeniem lub źródłem generującym ten punkt danych, może zapewnić sobie gwarantowany zysk, niezależnie od wolumenu obrotu czy nastrojów rynkowych. Koncepcyjnie jest to ta sama klasa podatności co ataki polegające na manipulacji onchainowymi wyroczniami cenowymi, które wielokrotnie uderzały w protokoły DeFi — z tą różnicą, że manipulowana tu „wyrocznia" znajduje się w świecie fizycznym, a nie na blockchainie.</p>
<p class="it">L'episodio è istruttivo perché espone una debolezza strutturale specifica dei mercati predittivi. A differenza dei normali mercati finanziari, dove i prezzi si formano continuamente dalle transazioni di molti partecipanti, un mercato basato su eventi come Polymarket si regola alla scadenza su un singolo dato reso pubblico — in questo caso una lettura della temperatura aeroportuale. Chiunque abbia accesso fisico per manomettere il dispositivo o la fonte che genera quel dato può assicurarsi un profitto garantito, indipendentemente dal volume di scambi o dal sentiment di mercato. Concettualmente, si tratta della stessa classe di vulnerabilità degli attacchi di manipolazione degli oracoli di prezzo on-chain che hanno colpito ripetutamente i protocolli DeFi — solo che qui l'"oracolo" manipolato si trova nel mondo fisico anziché su una blockchain.</p>
<p class="ru">Этот эпизод показателен, поскольку раскрывает структурную слабость, характерную именно для рынков предсказаний. В отличие от обычных финансовых рынков, где цены формируются непрерывно на основе сделок множества участников, рынок на основе событий, такой как Polymarket, рассчитывается при истечении срока по единственной публично сообщённой точке данных — в данном случае показанию температуры в аэропорту. Любой, у кого есть физический доступ для вмешательства в устройство или источник, генерирующий эту точку данных, может гарантированно зафиксировать прибыль независимо от объёма торгов или настроений рынка. Концептуально это тот же класс уязвимости, что и атаки с манипуляцией ончейн-оракулами цен, неоднократно поражавшие DeFi-протоколы, — с той разницей, что манипулируемый здесь «оракул» находится в физическом мире, а не в блокчейне.</p>
<p class="zh">這起事件之所以具有啟示意義,在於它暴露出預測市場特有的結構性弱點。與價格由眾多參與者持續交易形成的一般金融市場不同,像Polymarket這類事件型市場,是在到期時依據「單一公開數據點」——本案中即機場的氣溫讀數——來結算。也就是說,任何有實體管道竄改該數據點所依賴設備或來源的人,都能無視交易量或市場情緒,鎖定確定的獲利。從概念上看,這與DeFi協議屢屢遭遇的鏈上價格預言機操縱攻擊屬於同一類漏洞——差別只在於,這裡被操縱的「預言機」存在於實體世界,而非區塊鏈上。</p>

<div class="ko">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">샤를드골 공항 기상 베팅, 수상한 수익</text>
  <text x="20" y="55" fill="#a1a1aa" font-size="13" font-family="sans-serif">4월 관측치 급등 직후 발생한 세 건의 고배당 베팅</text>
  <rect x="90" y="270" width="90" height="80" fill="#71717a" opacity="0.85" rx="4"/>
  <text x="135" y="262" fill="#d4d4d8" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$14,000</text>
  <text x="135" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/6</text>
  <rect x="320" y="238" width="90" height="112" fill="#f59e0b" opacity="0.85" rx="4"/>
  <text x="365" y="230" fill="#fcd34d" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$20,000</text>
  <text x="365" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/15</text>
  <rect x="550" y="230" width="90" height="120" fill="#ef4444" opacity="0.9" rx="4"/>
  <text x="595" y="222" fill="#fca5a5" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$21,398</text>
  <text x="595" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/15 (xX25Xx)</text>
  <line x1="60" y1="350" x2="650" y2="350" stroke="#52525b" stroke-width="1.5"/>
  <text x="20" y="392" fill="#71717a" font-size="12" font-family="sans-serif">※ xX25Xx는 119달러를 걸어 2만1398달러 획득(약 180배). 수치는 본문 출처 기준.</text>
</svg>
</div>
<div class="en es de fr pt tr vi id pl it">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Suspicious Payouts From Weather Bets at Charles de Gaulle</text>
  <text x="20" y="55" fill="#a1a1aa" font-size="13" font-family="sans-serif">Three high-payout bets placed right after April temperature spikes</text>
  <rect x="90" y="270" width="90" height="80" fill="#71717a" opacity="0.85" rx="4"/>
  <text x="135" y="262" fill="#d4d4d8" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$14,000</text>
  <text x="135" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">Apr 6</text>
  <rect x="320" y="238" width="90" height="112" fill="#f59e0b" opacity="0.85" rx="4"/>
  <text x="365" y="230" fill="#fcd34d" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$20,000</text>
  <text x="365" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">Apr 15</text>
  <rect x="550" y="230" width="90" height="120" fill="#ef4444" opacity="0.9" rx="4"/>
  <text x="595" y="222" fill="#fca5a5" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$21,398</text>
  <text x="595" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">Apr 15 (xX25Xx)</text>
  <line x1="60" y1="350" x2="650" y2="350" stroke="#52525b" stroke-width="1.5"/>
  <text x="20" y="392" fill="#71717a" font-size="12" font-family="sans-serif">* xX25Xx staked $119 and won $21,398 (~180x). Figures per sources cited in the article.</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">シャルル・ド・ゴール空港の気象ベット、不審な利益</text>
  <text x="20" y="55" fill="#a1a1aa" font-size="13" font-family="sans-serif">4月の観測値急騰直後に発生した3件の高配当ベット</text>
  <rect x="90" y="270" width="90" height="80" fill="#71717a" opacity="0.85" rx="4"/>
  <text x="135" y="262" fill="#d4d4d8" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$14,000</text>
  <text x="135" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/6</text>
  <rect x="320" y="238" width="90" height="112" fill="#f59e0b" opacity="0.85" rx="4"/>
  <text x="365" y="230" fill="#fcd34d" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$20,000</text>
  <text x="365" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/15</text>
  <rect x="550" y="230" width="90" height="120" fill="#ef4444" opacity="0.9" rx="4"/>
  <text x="595" y="222" fill="#fca5a5" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$21,398</text>
  <text x="595" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/15(xX25Xx)</text>
  <line x1="60" y1="350" x2="650" y2="350" stroke="#52525b" stroke-width="1.5"/>
  <text x="20" y="392" fill="#71717a" font-size="12" font-family="sans-serif">※ xX25Xxは119ドルを賭け2万1398ドルを獲得(約180倍)。数値は本文出典に基づく。</text>
</svg>
</div>
<div class="ru">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Подозрительные выплаты по погодным ставкам в Шарль-де-Голль</text>
  <text x="20" y="55" fill="#a1a1aa" font-size="13" font-family="sans-serif">Три ставки с крупной выплатой сразу после скачков температуры в апреле</text>
  <rect x="90" y="270" width="90" height="80" fill="#71717a" opacity="0.85" rx="4"/>
  <text x="135" y="262" fill="#d4d4d8" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$14,000</text>
  <text x="135" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">6 апр.</text>
  <rect x="320" y="238" width="90" height="112" fill="#f59e0b" opacity="0.85" rx="4"/>
  <text x="365" y="230" fill="#fcd34d" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$20,000</text>
  <text x="365" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">15 апр.</text>
  <rect x="550" y="230" width="90" height="120" fill="#ef4444" opacity="0.9" rx="4"/>
  <text x="595" y="222" fill="#fca5a5" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$21,398</text>
  <text x="595" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">15 апр. (xX25Xx)</text>
  <line x1="60" y1="350" x2="650" y2="350" stroke="#52525b" stroke-width="1.5"/>
  <text x="20" y="392" fill="#71717a" font-size="12" font-family="sans-serif">* xX25Xx поставил $119 и выиграл $21 398 (~180x). Цифры — по источникам в статье.</text>
</svg>
</div>
<div class="zh">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">戴高樂機場氣象投注,可疑的獲利</text>
  <text x="20" y="55" fill="#a1a1aa" font-size="13" font-family="sans-serif">4月觀測值飆升後緊接發生的三筆高賠率投注</text>
  <rect x="90" y="270" width="90" height="80" fill="#71717a" opacity="0.85" rx="4"/>
  <text x="135" y="262" fill="#d4d4d8" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$14,000</text>
  <text x="135" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/6</text>
  <rect x="320" y="238" width="90" height="112" fill="#f59e0b" opacity="0.85" rx="4"/>
  <text x="365" y="230" fill="#fcd34d" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$20,000</text>
  <text x="365" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/15</text>
  <rect x="550" y="230" width="90" height="120" fill="#ef4444" opacity="0.9" rx="4"/>
  <text x="595" y="222" fill="#fca5a5" font-size="14" text-anchor="middle" font-family="sans-serif" font-weight="700">$21,398</text>
  <text x="595" y="368" fill="#e4e4e7" font-size="12" text-anchor="middle" font-family="sans-serif">4/15(xX25Xx)</text>
  <line x1="60" y1="350" x2="650" y2="350" stroke="#52525b" stroke-width="1.5"/>
  <text x="20" y="392" fill="#71717a" font-size="12" font-family="sans-serif">※ xX25Xx以119美元下注,贏得2萬1398美元(約180倍)。數字依本文出處。</text>
</svg>
</div>

<h2 class="ko">도박이냐 금융상품이냐, 나라마다 다른 답</h2>
<h2 class="en">Gambling or Financial Instrument? The Answer Differs by Country</h2>
<h2 class="ja">賭博か金融商品か、国によって異なる答え</h2>
<h2 class="es">¿Apuesta o Instrumento Financiero? La Respuesta Varía Según el País</h2>
<h2 class="de">Glücksspiel oder Finanzinstrument? Die Antwort Ist Von Land zu Land Verschieden</h2>
<h2 class="fr">Pari ou Instrument Financier ? La Réponse Varie Selon les Pays</h2>
<h2 class="pt">Aposta ou Instrumento Financeiro? A Resposta Varia Conforme o País</h2>
<h2 class="tr">Kumar mı, Finansal Araç mı? Cevap Ülkeden Ülkeye Değişiyor</h2>
<h2 class="vi">Cờ Bạc Hay Công Cụ Tài Chính? Câu Trả Lời Khác Nhau Theo Từng Quốc Gia</h2>
<h2 class="id">Judi atau Instrumen Keuangan? Jawabannya Berbeda di Setiap Negara</h2>
<h2 class="pl">Hazard czy Instrument Finansowy? Odpowiedź Różni Się w Zależności od Kraju</h2>
<h2 class="it">Scommessa o Strumento Finanziario? La Risposta Cambia da Paese a Paese</h2>
<h2 class="ru">Азартная Игра или Финансовый Инструмент? Ответ Разнится от Страны к Стране</h2>
<h2 class="zh">究竟是賭博還是金融商品?各國答案大不相同</h2>

<p class="ko">ANJ는 폴리마켓을 금융상품이 아니라 '무허가 도박·베팅 사업자'로 규정했는데, 이는 프랑스가 오랫동안 온라인 스포츠 베팅·포커 사이트를 상대로 써온 것과 같은 규제 틀이다. 반면 미국에서는 캘시(Kalshi) 같은 이벤트 계약 플랫폼이 상품선물거래위원회(CFTC) 감독을 받는 '지정계약시장(DCM)'으로 인정받아 합법적인 파생상품으로 거래된다. 같은 '특정 사건의 결과에 베팅한다'는 메커니즘이 어느 나라에서는 도박으로, 어느 나라에서는 규제된 금융상품으로 갈리는 셈이다.</p>
<p class="en">The ANJ classified Polymarket not as a financial product but as an "unlicensed gambling and betting operator" — the same regulatory framework France has long applied to unlicensed online sports-betting and poker sites. In the United States, by contrast, event-contract platforms like Kalshi are recognized as CFTC-regulated Designated Contract Markets and trade as legal derivatives. The same underlying mechanism — betting on the outcome of a specific event — ends up classified as gambling in one country and as a regulated financial product in another.</p>
<p class="ja">ANJはポリマーケットを金融商品ではなく「無許可の賭博・ベッティング事業者」と分類した。これはフランスが長年、無許可のオンラインスポーツベッティングやポーカーサイトに適用してきたのと同じ規制枠組みだ。一方米国では、キャルシー(Kalshi)のようなイベント契約プラットフォームがCFTC規制下の「指定契約市場(DCM)」として認められ、合法なデリバティブとして取引されている。同じ「特定イベントの結果に賭ける」というメカニズムが、ある国では賭博に、別の国では規制された金融商品に分類されるわけだ。</p>
<p class="es">La ANJ clasificó a Polymarket no como un producto financiero, sino como un "operador de apuestas y juego de azar sin licencia" — el mismo marco regulatorio que Francia ha aplicado durante mucho tiempo a los sitios de apuestas deportivas y póquer en línea no autorizados. En Estados Unidos, en cambio, plataformas de contratos por eventos como Kalshi son reconocidas como Mercados de Contratos Designados regulados por la CFTC y operan como derivados legales. El mismo mecanismo subyacente —apostar sobre el resultado de un evento específico— termina clasificado como juego de azar en un país y como producto financiero regulado en otro.</p>
<p class="de">Die ANJ stufte Polymarket nicht als Finanzprodukt, sondern als "unlizenzierten Glücksspiel- und Wettanbieter" ein — derselbe regulatorische Rahmen, den Frankreich seit Langem auf unlizenzierte Online-Sportwetten- und Pokerseiten anwendet. In den USA hingegen gelten Event-Contract-Plattformen wie Kalshi als von der CFTC regulierte Designated Contract Markets und werden als legale Derivate gehandelt. Derselbe zugrunde liegende Mechanismus — das Wetten auf den Ausgang eines bestimmten Ereignisses — wird im einen Land als Glücksspiel eingestuft, im anderen als reguliertes Finanzprodukt.</p>
<p class="fr">L'ANJ a classé Polymarket non pas comme un produit financier, mais comme un « opérateur de jeux d'argent et de paris non agréé » — le même cadre réglementaire que la France applique de longue date aux sites de paris sportifs et de poker en ligne non autorisés. Aux États-Unis, en revanche, des plateformes de contrats événementiels comme Kalshi sont reconnues comme des Designated Contract Markets régulés par la CFTC et négociées comme des produits dérivés légaux. Le même mécanisme sous-jacent — parier sur l'issue d'un événement précis — se retrouve ainsi classé comme jeu d'argent dans un pays et comme produit financier régulé dans un autre.</p>
<p class="pt">A ANJ classificou a Polymarket não como um produto financeiro, mas como um "operador de apostas e jogos de azar sem licença" — o mesmo arcabouço regulatório que a França há muito aplica a sites de apostas esportivas e pôquer online não autorizados. Nos Estados Unidos, por outro lado, plataformas de contratos de eventos como a Kalshi são reconhecidas como Designated Contract Markets regulados pela CFTC e negociadas como derivativos legais. O mesmo mecanismo subjacente — apostar no resultado de um evento específico — acaba classificado como jogo de azar em um país e como produto financeiro regulado em outro.</p>
<p class="tr">ANJ, Polymarket'i bir finansal ürün değil, "lisanssız bir kumar ve bahis operatörü" olarak sınıflandırdı - Fransa'nın lisanssız çevrimiçi spor bahisleri ve poker sitelerine uzun süredir uyguladığı düzenleyici çerçevenin aynısı. Buna karşılık ABD'de Kalshi gibi olay sözleşmesi platformları, CFTC tarafından düzenlenen Belirlenmiş Sözleşme Piyasaları olarak tanınıyor ve yasal türev ürünler olarak işlem görüyor. Belirli bir olayın sonucuna bahis oynamaktan ibaret olan aynı mekanizma, bir ülkede kumar, başka bir ülkede ise düzenlenmiş bir finansal ürün olarak sınıflandırılıyor.</p>
<p class="vi">ANJ phân loại Polymarket không phải là một sản phẩm tài chính mà là "đơn vị vận hành cờ bạc và cá cược không có giấy phép" — cùng khung pháp lý mà Pháp từ lâu đã áp dụng cho các trang cá cược thể thao trực tuyến và poker không được cấp phép. Ngược lại, tại Hoa Kỳ, các nền tảng hợp đồng sự kiện như Kalshi được công nhận là Thị Trường Hợp Đồng Được Chỉ Định do CFTC quản lý và giao dịch như các sản phẩm phái sinh hợp pháp. Cùng một cơ chế cơ bản — cá cược vào kết quả của một sự kiện cụ thể — lại bị phân loại là cờ bạc ở nước này nhưng lại là sản phẩm tài chính được quản lý ở nước khác.</p>
<p class="id">ANJ mengklasifikasikan Polymarket bukan sebagai produk keuangan, melainkan sebagai "operator perjudian dan taruhan tanpa izin" — kerangka regulasi yang sama yang telah lama diterapkan Prancis pada situs taruhan olahraga online dan poker tanpa izin. Sebaliknya, di Amerika Serikat, platform kontrak peristiwa seperti Kalshi diakui sebagai Designated Contract Market yang diatur CFTC dan diperdagangkan sebagai derivatif yang sah. Mekanisme dasar yang sama — bertaruh pada hasil suatu peristiwa tertentu — akhirnya diklasifikasikan sebagai perjudian di satu negara dan sebagai produk keuangan yang diatur di negara lain.</p>
<p class="pl">ANJ zaklasyfikował Polymarket nie jako produkt finansowy, lecz jako „nielicencjonowanego operatora hazardu i zakładów" — te same ramy regulacyjne, które Francja od dawna stosuje wobec nielicencjonowanych stron z zakładami sportowymi online i pokerem. W Stanach Zjednoczonych natomiast platformy kontraktów na zdarzenia, takie jak Kalshi, są uznawane za regulowane przez CFTC Designated Contract Markets i notowane jako legalne instrumenty pochodne. Ten sam podstawowy mechanizm — obstawianie wyniku konkretnego zdarzenia — w jednym kraju kończy się jako hazard, a w innym jako regulowany produkt finansowy.</p>
<p class="it">L'ANJ ha classificato Polymarket non come un prodotto finanziario, ma come un "operatore di gioco d'azzardo e scommesse senza licenza" — lo stesso quadro normativo che la Francia applica da tempo ai siti di scommesse sportive online e poker non autorizzati. Negli Stati Uniti, al contrario, piattaforme di contratti su eventi come Kalshi sono riconosciute come Designated Contract Market regolamentati dalla CFTC e negoziate come derivati legali. Lo stesso meccanismo di fondo — scommettere sull'esito di un evento specifico — finisce classificato come gioco d'azzardo in un paese e come prodotto finanziario regolamentato in un altro.</p>
<p class="ru">ANJ классифицировал Polymarket не как финансовый продукт, а как «нелицензированного оператора азартных игр и ставок» — ту же регуляторную схему, которую Франция давно применяет к нелицензированным сайтам онлайн-ставок на спорт и покера. В США же, напротив, платформы событийных контрактов, такие как Kalshi, признаны регулируемыми CFTC Designated Contract Markets и торгуются как законные деривативы. Один и тот же базовый механизм — ставка на исход конкретного события — в одной стране классифицируется как азартная игра, а в другой — как регулируемый финансовый продукт.</p>
<p class="zh">ANJ將Polymarket歸類為並非金融商品,而是「未經授權的博彩與投注業者」——這正是法國長期以來用於打擊未授權線上體育博彩與撲克網站的同一套監管框架。相較之下,在美國,像Kalshi這類事件合約平台則被認可為受商品期貨交易委員會(CFTC)監管的「指定合約市場」(DCM),以合法衍生性商品的身分交易。同樣是「押注特定事件結果」這種底層機制,在某些國家被歸類為賭博,在另一些國家卻是受監管的金融商品。</p>

<p class="ko">이런 분류 차이는 우연이 아니다. 도박으로 규정되면 규제 기관이 라이선스 없는 운영자를 이용자 보호·중독 예방 명분으로 손쉽게 차단할 수 있는 반면, 금융상품으로 인정되면 증권·상품 규제 체계 안에서 운영이 허용되고 오히려 제도권 편입의 길이 열린다. <a href="/blog/italy-polymarket-second-block-lazio-sponsorship">이탈리아 등 이미 30여개국이 폴리마켓 접속을 제한한 상태</a>이며, 이번 프랑스의 결정은 유럽에서 예측시장을 '규제된 금융 혁신'이 아니라 '온라인 도박의 변종'으로 보는 시각이 굳어지고 있다는 신호로 읽힌다.</p>
<p class="en">That classification gap is not accidental. Labeling a platform as gambling lets regulators block an unlicensed operator relatively easily, in the name of consumer protection and addiction prevention; recognition as a financial product, by contrast, opens a path into the securities and commodities regulatory system — and, potentially, mainstream legitimacy. With <a href="/en/blog/italy-polymarket-second-block-lazio-sponsorship">more than 30 countries, including Italy, already restricting access to Polymarket</a>, France's decision reads as another signal that European regulators are settling on a view of prediction markets as a variant of online gambling rather than a form of regulated financial innovation.</p>
<p class="ja">この分類の違いは偶然ではない。賭博と位置づければ、規制当局は消費者保護や依存症予防を名目に、無許可事業者を比較的容易に遮断できる。一方、金融商品として認められれば証券・商品規制の枠組み内での運営が許され、むしろ制度への編入の道が開ける。<a href="/ja/blog/italy-polymarket-second-block-lazio-sponsorship">イタリアを含む30カ国以上がすでにポリマーケットへのアクセスを制限している</a>状況を踏まえると、今回のフランスの決定は、欧州の規制当局が予測市場を「規制された金融イノベーション」ではなく「オンライン賭博の一形態」とみなす方向へ収斂しつつあるもう一つのシグナルとして読み取れる。</p>
<p class="es">Esa brecha de clasificación no es accidental. Etiquetar una plataforma como juego de azar permite a los reguladores bloquear a un operador sin licencia con relativa facilidad, en nombre de la protección al consumidor y la prevención de la adicción; el reconocimiento como producto financiero, en cambio, abre una vía hacia el sistema regulatorio de valores y materias primas y, potencialmente, hacia la legitimidad convencional. Con <a href="/es/blog/italy-polymarket-second-block-lazio-sponsorship">más de 30 países, incluida Italia, que ya restringen el acceso a Polymarket</a>, la decisión de Francia se lee como otra señal de que los reguladores europeos se están inclinando por considerar los mercados de predicción una variante del juego de azar en línea en lugar de una forma de innovación financiera regulada.</p>
<p class="de">Diese Klassifizierungslücke ist kein Zufall. Wird eine Plattform als Glücksspiel eingestuft, können Regulierer einen unlizenzierten Betreiber im Namen von Verbraucherschutz und Suchtprävention relativ leicht sperren; die Anerkennung als Finanzprodukt hingegen eröffnet einen Weg in das Wertpapier- und Warenregulierungssystem — und potenziell zu Mainstream-Legitimität. Da <a href="/de/blog/italy-polymarket-second-block-lazio-sponsorship">bereits mehr als 30 Länder, darunter Italien, den Zugang zu Polymarket einschränken</a>, liest sich Frankreichs Entscheidung als weiteres Signal dafür, dass sich europäische Regulierer zunehmend auf eine Sicht von Prognosemärkten als Variante des Online-Glücksspiels statt als Form regulierter Finanzinnovation festlegen.</p>
<p class="fr">Cet écart de classification n'a rien d'accidentel. Qualifier une plateforme de jeu d'argent permet aux régulateurs de bloquer relativement facilement un opérateur non agréé, au nom de la protection des consommateurs et de la prévention de l'addiction ; la reconnaissance comme produit financier, à l'inverse, ouvre une voie vers le système réglementaire des valeurs mobilières et des matières premières — et potentiellement vers une légitimité grand public. Avec <a href="/fr/blog/italy-polymarket-second-block-lazio-sponsorship">plus de 30 pays, dont l'Italie, restreignant déjà l'accès à Polymarket</a>, la décision de la France apparaît comme un signal supplémentaire que les régulateurs européens tendent à considérer les marchés prédictifs comme une variante du jeu d'argent en ligne plutôt que comme une forme d'innovation financière régulée.</p>
<p class="pt">Essa diferença de classificação não é acidental. Rotular uma plataforma como jogo de azar permite que os reguladores bloqueiem um operador sem licença com relativa facilidade, em nome da proteção ao consumidor e da prevenção de vícios; o reconhecimento como produto financeiro, por outro lado, abre um caminho para o sistema regulatório de valores mobiliários e commodities — e, potencialmente, para a legitimidade dominante. Com <a href="/pt/blog/italy-polymarket-second-block-lazio-sponsorship">mais de 30 países, incluindo a Itália, já restringindo o acesso à Polymarket</a>, a decisão da França soa como mais um sinal de que os reguladores europeus estão se consolidando em torno da visão de que mercados de previsão são uma variante do jogo de azar online, e não uma forma de inovação financeira regulada.</p>
<p class="tr">Bu sınıflandırma farkı tesadüf değil. Bir platformu kumar olarak etiketlemek, düzenleyicilerin tüketici koruması ve bağımlılığı önleme adı altında lisanssız bir operatörü nispeten kolayca engellemesine olanak tanıyor; finansal ürün olarak tanınmak ise menkul kıymetler ve emtia düzenleme sistemine, hatta potansiyel olarak ana akım meşruiyete giden bir yol açıyor. <a href="/tr/blog/italy-polymarket-second-block-lazio-sponsorship">İtalya dahil 30'dan fazla ülke zaten Polymarket'e erişimi kısıtlamışken</a>, Fransa'nın kararı, Avrupalı düzenleyicilerin tahmin piyasalarını düzenlenmiş bir finansal yenilik biçiminden ziyade çevrimiçi kumarın bir türü olarak görmeye doğru yerleştiğinin bir başka işareti gibi okunuyor.</p>
<p class="vi">Khoảng cách phân loại đó không phải ngẫu nhiên. Gắn nhãn một nền tảng là cờ bạc cho phép các cơ quan quản lý chặn một đơn vị không có giấy phép tương đối dễ dàng, nhân danh bảo vệ người tiêu dùng và phòng ngừa nghiện; ngược lại, được công nhận là sản phẩm tài chính lại mở ra con đường đi vào hệ thống quản lý chứng khoán và hàng hóa — và tiềm năng là tính chính danh trong dòng chảy chính thống. Với <a href="/vi/blog/italy-polymarket-second-block-lazio-sponsorship">hơn 30 quốc gia, bao gồm Ý, đã hạn chế quyền truy cập vào Polymarket</a>, quyết định của Pháp được xem như một tín hiệu nữa cho thấy các cơ quan quản lý châu Âu đang ngả về quan điểm coi thị trường dự đoán là một biến thể của cờ bạc trực tuyến hơn là một hình thức đổi mới tài chính được quản lý.</p>
<p class="id">Kesenjangan klasifikasi itu bukan kebetulan. Melabeli sebuah platform sebagai perjudian memungkinkan regulator memblokir operator tanpa izin dengan relatif mudah, atas nama perlindungan konsumen dan pencegahan kecanduan; sebaliknya, pengakuan sebagai produk keuangan membuka jalan menuju sistem regulasi sekuritas dan komoditas — dan berpotensi menuju legitimasi arus utama. Dengan <a href="/id/blog/italy-polymarket-second-block-lazio-sponsorship">lebih dari 30 negara, termasuk Italia, yang sudah membatasi akses ke Polymarket</a>, keputusan Prancis ini terbaca sebagai sinyal lain bahwa regulator Eropa semakin condong memandang pasar prediksi sebagai varian perjudian online, bukan bentuk inovasi keuangan yang diatur.</p>
<p class="pl">Ta różnica w klasyfikacji nie jest przypadkowa. Określenie platformy jako hazardu pozwala regulatorom stosunkowo łatwo zablokować nielicencjonowanego operatora w imię ochrony konsumentów i zapobiegania uzależnieniom; uznanie za produkt finansowy otwiera natomiast drogę do systemu regulacji papierów wartościowych i towarów — a potencjalnie do głównego nurtu legalności. Skoro <a href="/pl/blog/italy-polymarket-second-block-lazio-sponsorship">ponad 30 krajów, w tym Włochy, już ogranicza dostęp do Polymarket</a>, decyzja Francji odczytywana jest jako kolejny sygnał, że europejscy regulatorzy skłaniają się ku postrzeganiu rynków predykcyjnych jako wariantu hazardu online, a nie formy regulowanej innowacji finansowej.</p>
<p class="it">Questo divario di classificazione non è casuale. Etichettare una piattaforma come gioco d'azzardo consente ai regolatori di bloccare relativamente facilmente un operatore senza licenza, in nome della tutela dei consumatori e della prevenzione delle dipendenze; il riconoscimento come prodotto finanziario, al contrario, apre una via verso il sistema normativo dei titoli e delle materie prime — e potenzialmente verso una legittimità mainstream. Con <a href="/it/blog/italy-polymarket-second-block-lazio-sponsorship">oltre 30 paesi, tra cui l'Italia, che già limitano l'accesso a Polymarket</a>, la decisione della Francia si legge come un ulteriore segnale che i regolatori europei si stanno orientando verso una visione dei mercati predittivi come variante del gioco d'azzardo online piuttosto che come forma di innovazione finanziaria regolamentata.</p>
<p class="ru">Этот разрыв в классификации не случаен. Обозначение платформы как азартной игры позволяет регуляторам относительно легко заблокировать нелицензированного оператора во имя защиты потребителей и профилактики зависимости; признание же финансовым продуктом, напротив, открывает путь в систему регулирования ценных бумаг и товаров — и потенциально к легитимности в основном русле. На фоне того, что <a href="/ru/blog/italy-polymarket-second-block-lazio-sponsorship">более 30 стран, включая Италию, уже ограничивают доступ к Polymarket</a>, решение Франции читается как ещё один сигнал того, что европейские регуляторы всё больше склоняются к взгляду на рынки предсказаний как на разновидность онлайн-азартных игр, а не как на форму регулируемых финансовых инноваций.</p>
<p class="zh">這種分類上的差異並非偶然。將平台貼上博彩標籤,能讓監管機構以保護消費者、預防成癮為由,相對輕鬆地封鎖未授權業者;反之,若被認定為金融商品,則能打開通往證券與商品監管體系的大門,甚至有機會進入主流合法性的行列。<a href="/zh/blog/italy-polymarket-second-block-lazio-sponsorship">目前包括義大利在內,已有超過30個國家限制Polymarket的存取</a>,法國此次的決定,可視為又一個訊號,顯示歐洲監管機構正逐漸傾向將預測市場視為線上博彩的變種,而非受監管的金融創新形式。</p>

<h2 class="ko">차단이 실제로 통할까</h2>
<h2 class="en">Will the Block Actually Work?</h2>
<h2 class="ja">遮断は実際に効果を発揮するか</h2>
<h2 class="es">¿Funcionará Realmente el Bloqueo?</h2>
<h2 class="de">Wird die Sperre Tatsächlich Wirken?</h2>
<h2 class="fr">Le Blocage Fonctionnera-t-il Vraiment ?</h2>
<h2 class="pt">O Bloqueio Vai Realmente Funcionar?</h2>
<h2 class="tr">Engelleme Gerçekten İşe Yarayacak mı?</h2>
<h2 class="vi">Liệu Việc Chặn Có Thực Sự Hiệu Quả?</h2>
<h2 class="id">Apakah Pemblokiran Ini Benar-Benar Akan Berhasil?</h2>
<h2 class="pl">Czy Blokada Rzeczywiście Zadziała?</h2>
<h2 class="it">Il Blocco Funzionerà Davvero?</h2>
<h2 class="ru">Действительно ли Сработает Блокировка?</h2>
<h2 class="zh">封鎖真能奏效嗎?</h2>

<p class="ko">관건은 실효성이다. 지난해 11월 시행된 금융거래 금지 조치가 6월 한 달에만 20만 명 넘는 순방문자를 막지 못했다는 사실은, 이번 ISP 차단 역시 완전한 해법이 되기 어렵다는 점을 시사한다. ISP 단의 접속 차단은 대개 도메인네임시스템(DNS) 차단 방식으로 이뤄지는데, 이는 가상사설망(VPN)이나 대체 DNS 서버로 우회하기가 비교적 쉬워 기술적으로 정교한 이용자에게는 사실상 무력화되는 경우가 많다.</p>
<p class="en">The key question is effectiveness. The fact that the financial-transaction ban imposed last November failed to stop more than 200,000 unique visitors from accessing the site in June alone suggests this ISP-level block is unlikely to be a complete solution either. Access blocks at the ISP level are typically implemented through domain name system (DNS) filtering, which can often be circumvented relatively easily using a VPN or an alternative DNS server — meaning it can be largely defeated by technically sophisticated users.</p>
<p class="ja">焦点は実効性だ。昨年11月に課された金融取引禁止措置が、6月だけでも20万人を超える純訪問者のサイトアクセスを止められなかったという事実は、今回のISP段階での遮断もまた完全な解決策にはなりにくいことを示唆している。ISP段階での遮断は通常、ドメインネームシステム(DNS)によるフィルタリングで実施されるが、VPNや代替DNSサーバーによって比較的容易に回避できることが多く、技術に精通した利用者に対してはほぼ無力化される。</p>
<p class="es">La pregunta clave es la eficacia. El hecho de que la prohibición de transacciones financieras impuesta en noviembre pasado no lograra impedir que más de 200.000 visitantes únicos accedieran al sitio solo en junio sugiere que este bloqueo a nivel de ISP tampoco será probablemente una solución completa. Los bloqueos de acceso a nivel de ISP suelen implementarse mediante filtrado del sistema de nombres de dominio (DNS), que a menudo puede eludirse con relativa facilidad usando una VPN o un servidor DNS alternativo, lo que significa que puede quedar en gran medida neutralizado para usuarios técnicamente sofisticados.</p>
<p class="de">Die zentrale Frage ist die Wirksamkeit. Die Tatsache, dass das im vergangenen November verhängte Verbot von Finanztransaktionen allein im Juni nicht verhindern konnte, dass über 200.000 eindeutige Besucher auf die Seite zugriffen, legt nahe, dass auch diese Sperre auf ISP-Ebene keine vollständige Lösung sein dürfte. Zugangssperren auf ISP-Ebene werden typischerweise durch DNS-Filterung (Domain Name System) umgesetzt, die sich oft relativ leicht mit einem VPN oder einem alternativen DNS-Server umgehen lässt — technisch versierte Nutzer können sie damit weitgehend aushebeln.</p>
<p class="fr">La question clé est celle de l'efficacité. Le fait que l'interdiction des transactions financières imposée en novembre dernier n'ait pas empêché plus de 200 000 visiteurs uniques d'accéder au site rien qu'en juin laisse penser que ce blocage au niveau des FAI ne sera probablement pas non plus une solution complète. Les blocages d'accès au niveau des FAI sont généralement mis en œuvre via un filtrage du système de noms de domaine (DNS), qui peut souvent être contourné assez facilement à l'aide d'un VPN ou d'un serveur DNS alternatif — ce qui signifie qu'il peut être largement neutralisé par des utilisateurs techniquement avertis.</p>
<p class="pt">A questão central é a eficácia. O fato de a proibição de transações financeiras imposta em novembro passado não ter impedido mais de 200 mil visitantes únicos de acessar o site somente em junho sugere que esse bloqueio em nível de provedor também dificilmente será uma solução completa. Bloqueios de acesso em nível de ISP normalmente são implementados por meio de filtragem do sistema de nomes de domínio (DNS), que muitas vezes pode ser contornada com relativa facilidade usando uma VPN ou um servidor DNS alternativo — o que significa que pode ser amplamente neutralizada por usuários tecnicamente sofisticados.</p>
<p class="tr">Kilit soru etkinlik. Geçen Kasım ayında uygulanan finansal işlem yasağının, yalnızca Haziran ayında 200.000'den fazla tekil ziyaretçinin siteye erişmesini engelleyememiş olması, bu ISS düzeyindeki engellemenin de tam bir çözüm olma ihtimalinin düşük olduğunu düşündürüyor. ISS düzeyindeki erişim engellemeleri genellikle alan adı sistemi (DNS) filtrelemesi yoluyla uygulanır ve bu genellikle bir VPN veya alternatif bir DNS sunucusu kullanılarak nispeten kolayca aşılabilir - bu da teknik açıdan bilgili kullanıcılar tarafından büyük ölçüde etkisiz hale getirilebileceği anlamına gelir.</p>
<p class="vi">Câu hỏi then chốt là tính hiệu quả. Việc lệnh cấm giao dịch tài chính áp dụng từ tháng 11 năm ngoái không ngăn được hơn 200.000 khách truy cập duy nhất tiếp cận trang web chỉ trong tháng 6 cho thấy lệnh chặn ở cấp nhà cung cấp dịch vụ internet này cũng khó có thể là giải pháp trọn vẹn. Việc chặn truy cập ở cấp ISP thường được thực hiện thông qua lọc hệ thống tên miền (DNS), vốn thường có thể bị vượt qua tương đối dễ dàng bằng VPN hoặc máy chủ DNS thay thế — nghĩa là nó có thể phần lớn bị vô hiệu hóa bởi những người dùng am hiểu kỹ thuật.</p>
<p class="id">Pertanyaan kuncinya adalah efektivitas. Fakta bahwa larangan transaksi keuangan yang diberlakukan November lalu gagal mencegah lebih dari 200.000 pengunjung unik mengakses situs tersebut hanya dalam bulan Juni menunjukkan bahwa pemblokiran di level ISP ini pun kemungkinan bukan solusi yang lengkap. Pemblokiran akses di level ISP biasanya diterapkan melalui penyaringan sistem nama domain (DNS), yang sering kali dapat dielakkan dengan relatif mudah menggunakan VPN atau server DNS alternatif — artinya dapat sebagian besar dikalahkan oleh pengguna yang paham secara teknis.</p>
<p class="pl">Kluczowe pytanie dotyczy skuteczności. Fakt, że zakaz transakcji finansowych wprowadzony w listopadzie ubiegłego roku nie powstrzymał ponad 200 tysięcy unikalnych odwiedzających przed dostępem do witryny tylko w czerwcu, sugeruje, że ta blokada na poziomie dostawców internetu również raczej nie będzie kompletnym rozwiązaniem. Blokady dostępu na poziomie ISP są zazwyczaj wdrażane poprzez filtrowanie systemu nazw domen (DNS), które często można stosunkowo łatwo obejść za pomocą VPN lub alternatywnego serwera DNS — co oznacza, że może zostać w dużej mierze zneutralizowana przez technicznie zaawansowanych użytkowników.</p>
<p class="it">La domanda chiave riguarda l'efficacia. Il fatto che il divieto sulle transazioni finanziarie imposto lo scorso novembre non sia riuscito a impedire a oltre 200.000 visitatori unici di accedere al sito nel solo mese di giugno suggerisce che anche questo blocco a livello di ISP difficilmente sarà una soluzione completa. I blocchi di accesso a livello di ISP vengono tipicamente implementati tramite il filtraggio del sistema dei nomi di dominio (DNS), che spesso può essere aggirato con relativa facilità utilizzando una VPN o un server DNS alternativo — il che significa che può essere in gran parte neutralizzato dagli utenti tecnicamente esperti.</p>
<p class="ru">Ключевой вопрос — эффективность. Тот факт, что запрет на финансовые транзакции, введённый в ноябре прошлого года, не смог помешать более чем 200 000 уникальных посетителей получить доступ к сайту только в июне, наводит на мысль, что и эта блокировка на уровне интернет-провайдеров вряд ли станет полным решением. Блокировки доступа на уровне провайдеров обычно реализуются через фильтрацию системы доменных имён (DNS), которую зачастую можно относительно легко обойти с помощью VPN или альтернативного DNS-сервера, а значит, технически подкованные пользователи способны во многом её нейтрализовать.</p>
<p class="zh">關鍵問題在於實效性。去年11月實施的金融交易禁令,光是6月一個月就未能阻止超過20萬名不重複訪客造訪該網站,這一事實顯示,此次網路服務供應商層級的封鎖恐怕同樣難以成為完整解方。ISP層級的存取封鎖通常透過網域名稱系統(DNS)過濾實現,而這種方式往往可以透過VPN或替代DNS伺服器相對輕易地繞過——也就是說,對技術嫻熟的使用者而言,這道封鎖在很大程度上形同虛設。</p>

<p class="ko">그런 만큼 이번 조치를 순수한 소비자 보호 대책으로만 보기는 어렵다는 해석도 나온다. 프랑스 국가 기관인 기상청의 관측 장비가 조작 의혹의 대상이 됐고, 검찰까지 나서 수사 중인 상황은 규제 당국 입장에서 단순한 '도박 중독 우려'를 넘어선 제도적 자존심의 문제이기도 하다. 접속 차단이 실제로 국내 트래픽을 얼마나 줄이는지는 앞으로 몇 달간의 방문자 수 추이로 확인될 전망이며, 이는 유럽 다른 규제 당국이 비슷한 조치를 검토할지 가늠하는 시금석이 될 것이다.</p>
<p class="en">That's why some read this move as more than a pure consumer-protection measure. With a French state institution's own weather-monitoring equipment at the center of a tampering allegation now under criminal investigation, this is, for regulators, as much a matter of institutional credibility as it is a concern about gambling addiction. How much the block actually reduces domestic traffic will become clear only over the coming months of visitor data — and that outcome is likely to serve as a test case for whether other European regulators pursue similar measures.</p>
<p class="ja">だからこそ、今回の措置を純粋な消費者保護策とだけ見るのは難しいという見方もある。フランスの国家機関である気象庁自身の観測装置が改ざん疑惑の中心となり、刑事捜査の対象になっている状況は、規制当局にとって単なる賭博依存への懸念を超えた、制度的な信頼の問題でもある。遮断が実際に国内トラフィックをどれだけ減らせるかは、今後数カ月の訪問者データの推移で明らかになる見込みで、その結果は他の欧州規制当局が同様の措置を取るかどうかを占う試金石となるだろう。</p>
<p class="es">Por eso algunos interpretan esta medida como algo más que una simple herramienta de protección al consumidor. Con el propio equipo de monitoreo meteorológico de una institución estatal francesa en el centro de una acusación de manipulación ahora bajo investigación penal, para los reguladores esto es tanto una cuestión de credibilidad institucional como una preocupación por la adicción al juego. Cuánto reduzca realmente el bloqueo el tráfico nacional solo quedará claro con los datos de visitantes de los próximos meses, y ese resultado probablemente servirá de caso de prueba para saber si otros reguladores europeos adoptan medidas similares.</p>
<p class="de">Deshalb lesen manche diesen Schritt als mehr als eine reine Verbraucherschutzmaßnahme. Da das eigene Wettermessgerät einer französischen Staatsinstitution im Zentrum eines Manipulationsvorwurfs steht, der nun strafrechtlich untersucht wird, ist dies für die Regulierungsbehörden ebenso eine Frage der institutionellen Glaubwürdigkeit wie der Sorge um Spielsucht. Wie stark die Sperre den inländischen Traffic tatsächlich senkt, wird sich erst in den kommenden Monaten anhand der Besucherdaten zeigen — und dieses Ergebnis dürfte als Testfall dafür dienen, ob andere europäische Regulierungsbehörden ähnliche Maßnahmen ergreifen.</p>
<p class="fr">C'est pourquoi certains voient dans cette mesure plus qu'un simple dispositif de protection des consommateurs. Avec l'équipement de mesure météorologique d'une institution étatique française elle-même au cœur d'une accusation de manipulation désormais sous enquête pénale, il s'agit pour les régulateurs autant d'une question de crédibilité institutionnelle que d'une préoccupation liée à l'addiction au jeu. L'ampleur réelle de la réduction du trafic national par ce blocage ne se précisera que dans les données de fréquentation des prochains mois — un résultat qui devrait servir de test pour savoir si d'autres régulateurs européens adoptent des mesures similaires.</p>
<p class="pt">É por isso que alguns interpretam essa medida como algo além de uma mera proteção ao consumidor. Com o próprio equipamento de monitoramento meteorológico de uma instituição estatal francesa no centro de uma alegação de adulteração agora sob investigação criminal, isso é, para os reguladores, tanto uma questão de credibilidade institucional quanto uma preocupação com vício em jogos. O quanto o bloqueio realmente reduzirá o tráfego doméstico só ficará claro com os dados de visitantes dos próximos meses — e esse resultado deve servir de teste para saber se outros reguladores europeus adotarão medidas semelhantes.</p>
<p class="tr">Bu yüzden bazıları bu adımı salt bir tüketici koruma önlemi olmanın ötesinde okuyor. Bir Fransız devlet kurumunun kendi hava durumu izleme ekipmanının, artık cezai soruşturma altındaki bir kurcalama iddiasının merkezinde olması, düzenleyiciler için bu meseleyi kumar bağımlılığı endişesi kadar kurumsal güvenilirlik meselesi haline getiriyor. Engellemenin yurt içi trafiği gerçekte ne kadar azalttığı ancak önümüzdeki aylardaki ziyaretçi verileriyle netleşecek ve bu sonuç, diğer Avrupalı düzenleyicilerin benzer önlemler alıp almayacağının bir turnusol testi olacak gibi görünüyor.</p>
<p class="vi">Đó là lý do một số ý kiến cho rằng động thái này không chỉ đơn thuần là biện pháp bảo vệ người tiêu dùng. Khi thiết bị quan trắc thời tiết của chính một cơ quan nhà nước Pháp trở thành trung tâm của cáo buộc can thiệp đang bị điều tra hình sự, đối với các nhà quản lý, đây vừa là vấn đề uy tín thể chế, vừa là mối lo ngại về nghiện cờ bạc. Việc lệnh chặn thực sự làm giảm lưu lượng truy cập trong nước đến mức nào chỉ có thể được xác nhận qua dữ liệu khách truy cập trong những tháng tới — và kết quả đó nhiều khả năng sẽ trở thành phép thử cho việc liệu các cơ quan quản lý châu Âu khác có áp dụng biện pháp tương tự hay không.</p>
<p class="id">Itulah sebabnya sebagian pihak membaca langkah ini sebagai lebih dari sekadar tindakan perlindungan konsumen murni. Dengan peralatan pemantau cuaca milik institusi negara Prancis sendiri kini menjadi pusat tuduhan pengubahan data yang sedang diselidiki secara pidana, bagi regulator ini sama pentingnya sebagai masalah kredibilitas institusional seperti halnya kekhawatiran soal kecanduan judi. Seberapa besar pemblokiran ini benar-benar mengurangi lalu lintas domestik baru akan terlihat jelas dari data pengunjung dalam beberapa bulan mendatang — dan hasilnya kemungkinan akan menjadi uji kasus bagi apakah regulator Eropa lain akan mengambil langkah serupa.</p>
<p class="pl">Dlatego niektórzy odczytują ten krok jako coś więcej niż czysty środek ochrony konsumentów. Skoro własny sprzęt meteorologiczny francuskiej instytucji państwowej znalazł się w centrum zarzutu manipulacji, obecnie objętego dochodzeniem karnym, dla regulatorów jest to w równym stopniu kwestia wiarygodności instytucjonalnej, co obawa o uzależnienie od hazardu. To, na ile blokada rzeczywiście ograniczy ruch krajowy, stanie się jasne dopiero po analizie danych o odwiedzających w kolejnych miesiącach — a ten wynik prawdopodobnie posłuży za sprawdzian tego, czy inni europejscy regulatorzy sięgną po podobne środki.</p>
<p class="it">Per questo motivo alcuni interpretano questa mossa come qualcosa di più di una semplice misura di tutela dei consumatori. Con l'apparecchiatura di monitoraggio meteorologico di un'istituzione statale francese al centro di un'accusa di manomissione ora oggetto di indagine penale, per i regolatori questa è tanto una questione di credibilità istituzionale quanto una preoccupazione legata alla dipendenza dal gioco. Quanto il blocco riduca effettivamente il traffico nazionale diventerà chiaro solo con i dati sui visitatori dei prossimi mesi — e quell'esito servirà probabilmente da caso di prova per capire se altri regolatori europei adotteranno misure simili.</p>
<p class="ru">Именно поэтому некоторые расценивают этот шаг как нечто большее, чем чистая мера защиты потребителей. Поскольку собственное метеорологическое оборудование французского государственного учреждения оказалось в центре обвинения во вмешательстве, которое сейчас расследуется в уголовном порядке, для регуляторов это в такой же мере вопрос институционального доверия, как и озабоченность игровой зависимостью. Насколько блокировка реально снизит внутренний трафик, станет ясно лишь по данным о посетителях за ближайшие месяцы, и этот результат, вероятно, послужит проверочным случаем для того, пойдут ли другие европейские регуляторы на аналогичные меры.</p>
<p class="zh">正因如此,也有人將此舉解讀為不僅僅是單純的消費者保護措施。法國一個國家機構自身的氣象監測設備,竟成為遭竄改指控、目前正接受刑事調查的核心,對監管機構而言,這既是對賭博成癮的憂慮,也同樣攸關體制公信力的問題。封鎖究竟能在多大程度上減少國內流量,唯有透過未來數月的訪客數據才能見分曉,而這一結果很可能將成為檢驗歐洲其他監管機構是否會採取類似措施的試金石。</p>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <text x="60" y="200" fill="#71717a" font-size="52" font-weight="bold">$119</text>
  <polygon fill="#ef4444" points="230,175 230,225 285,200"/>
  <text x="320" y="220" fill="#f4f4f5" font-size="110" font-weight="bold">$21,398</text>
  <text x="60" y="420" fill="#ef4444" font-size="60" font-weight="bold">180×</text>
  <text x="60" y="500" fill="#71717a" font-size="40" font-weight="bold">578,751</text>
</svg></div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 코인데스크(CoinDesk), 비트코인닷컴 뉴스(Bitcoin.com News), 프랑스24(France 24), NPR, CNN, 블룸버그(Bloomberg), 코인피디아(CoinPedia), 스타트업포천(Startup Fortune), 프랑스 국가도박청(ANJ) 공식 발표, 프랑스 기상청(메테오프랑스) 고발장.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, official statements from France's Autorité Nationale des Jeux (ANJ), and Météo-France's formal complaint.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: コインデスク(CoinDesk)、ビットコイン・ドット・コム・ニュース(Bitcoin.com News)、フランス24(France 24)、NPR、CNN、ブルームバーグ(Bloomberg)、コインピディア(CoinPedia)、スタートアップフォーチュン(Startup Fortune)、フランス国家賭博庁(ANJ)公式発表、フランス気象庁(メテオフランス)の告発状。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, declaraciones oficiales de la Autorité Nationale des Jeux (ANJ) de Francia, y la denuncia formal de Météo-France.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, offizielle Erklärungen der französischen Autorité Nationale des Jeux (ANJ) und die förmliche Anzeige von Météo-France.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, déclarations officielles de l'Autorité Nationale des Jeux (ANJ) française, et la plainte formelle de Météo-France.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, declarações oficiais da Autorité Nationale des Jeux (ANJ) da França, e a queixa formal da Météo-France.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, Fransa Autorité Nationale des Jeux (ANJ) resmi açıklamaları ve Météo-France'ın resmi şikayeti.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, tuyên bố chính thức từ Autorité Nationale des Jeux (ANJ) của Pháp, và đơn khiếu nại chính thức của Météo-France.</p>
<p class="id" style="font-size:12px;color:#52525b;margin-top:24px">Sumber: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, pernyataan resmi Autorité Nationale des Jeux (ANJ) Prancis, dan pengaduan resmi Météo-France.</p>
<p class="pl" style="font-size:12px;color:#52525b;margin-top:24px">Źródła: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, oficjalne oświadczenia francuskiego Autorité Nationale des Jeux (ANJ) oraz formalne zawiadomienie Météo-France.</p>
<p class="it" style="font-size:12px;color:#52525b;margin-top:24px">Fonti: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, dichiarazioni ufficiali dell'Autorité Nationale des Jeux (ANJ) francese e la denuncia formale di Météo-France.</p>
<p class="ru" style="font-size:12px;color:#52525b;margin-top:24px">Источники: CoinDesk, Bitcoin.com News, France 24, NPR, CNN, Bloomberg, CoinPedia, Startup Fortune, официальные заявления французского Autorité Nationale des Jeux (ANJ) и официальная жалоба Météo-France.</p>
<p class="zh" style="font-size:12px;color:#52525b;margin-top:24px">資料來源:CoinDesk、Bitcoin.com News、France 24、NPR、CNN、彭博社(Bloomberg)、CoinPedia、Startup Fortune、法國國家博彩局(ANJ)官方聲明、法國國家氣象局(Météo-France)正式申訴文件。</p>

<?php require __DIR__.'/_footer.php'; ?>
