<?php $slug = 'ftx-july-31-payout-disputed-claims-reserve-cut'; require __DIR__.'/_header.php'; ?>

<p class="ko">FTX 리커버리 트러스트가 7월31일을 다섯 번째 채권자 배분일로 정하고, 델라웨어 파산법원에 분쟁채권 준비금을 24억달러에서 18억달러로 6억달러 삭감하는 내용의 수정 통지서를 제출했다고 PR뉴스와이어와 크립토브리핑이 전했다. 이미 확정된(allowed) 채권 보유자들에게 돌아갈 현금을 추가로 풀어주는 조치다. 이번 라운드의 기준일은 6월16일로 정해졌으며, 대상 채권자는 자금을 받기 전에 신원확인(KYC), 세금서류 제출, 그리고 빗고(BitGo)·크라켄(Kraken)·페이오니어(Payoneer) 등 승인된 배분 대행사 등록을 완료해야 한다. 확정된 NFT 고객 청구권 보유자들에게는 6월30일부터 별도의 배분 절차가 시작된다는 안내가 나갔다.</p>
<p class="en">FTX's recovery trust set July 31, 2026 as the date for its fifth round of creditor distributions and filed an amended notice with the Delaware bankruptcy court proposing to cut its disputed-claims reserve by $600 million, from $2.4 billion to $1.8 billion, according to PR Newswire and CryptoBriefing. The move would free additional cash for holders of already-allowed claims. The record date for the new round was set for June 16, and eligible creditors must complete KYC verification, tax paperwork and onboarding with one of FTX's approved distribution providers — BitGo, Kraken or Payoneer — before they can receive funds. Holders of allowed NFT Customer Entitlement Claims were told a separate distribution track opened June 30.</p>
<p class="ja">FTXのリカバリー・トラストは7月31日を5回目の債権者配当日と定め、係争債権準備金を24億ドルから18億ドルへ6億ドル削減する修正通知書をデラウェア破産裁判所に提出したと、PRニュースワイヤーとクリプトブリーフィングが報じた。これはすでに確定(allowed)された債権保有者に追加の現金を振り向ける措置だ。今回のラウンドの基準日は6月16日と定められ、対象となる債権者は資金を受け取る前に本人確認(KYC)、税務書類の提出、そしてビットゴー(BitGo)・クラーケン(Kraken)・ペイオニア(Payoneer)など承認された配当代行業者への登録を完了しなければならない。確定したNFT顧客請求権の保有者には、6月30日から別途の配当手続きが開始されるとの案内があった。</p>
<p class="es">El fondo de recuperación de FTX fijó el 31 de julio de 2026 como fecha de su quinta ronda de distribución a acreedores y presentó un aviso enmendado ante el tribunal de quiebras de Delaware proponiendo recortar en 600 millones de dólares su reserva de reclamos en disputa, de 2.400 millones a 1.800 millones de dólares, según PR Newswire y CryptoBriefing. La medida liberaría efectivo adicional para los titulares de reclamos ya permitidos. La fecha de registro de esta nueva ronda se fijó para el 16 de junio, y los acreedores elegibles deben completar la verificación KYC, la documentación fiscal y el registro con uno de los proveedores de distribución aprobados por FTX —BitGo, Kraken o Payoneer— antes de recibir los fondos. A los titulares de reclamos de derechos de NFT ya permitidos se les informó que un proceso de distribución separado comenzó el 30 de junio.</p>
<p class="de">Der FTX Recovery Trust hat den 31. Juli 2026 als Termin für seine fünfte Runde von Gläubigerausschüttungen festgelegt und beim Insolvenzgericht in Delaware eine geänderte Mitteilung eingereicht, in der eine Kürzung der Rückstellung für strittige Forderungen um 600 Millionen Dollar vorgeschlagen wird — von 2,4 Milliarden auf 1,8 Milliarden Dollar, wie PR Newswire und CryptoBriefing berichten. Die Maßnahme würde zusätzliches Bargeld für Inhaber bereits zugelassener Forderungen freisetzen. Der Stichtag für die neue Runde wurde auf den 16. Juni festgelegt; berechtigte Gläubiger müssen vor Erhalt der Mittel eine KYC-Verifizierung, Steuerunterlagen und die Registrierung bei einem der zugelassenen Auszahlungsdienstleister — BitGo, Kraken oder Payoneer — abschließen. Inhabern zugelassener NFT-Kundenansprüche wurde mitgeteilt, dass ein separates Ausschüttungsverfahren am 30. Juni begonnen hat.</p>
<p class="fr">Le fonds de recouvrement de FTX a fixé au 31 juillet 2026 la date de son cinquième cycle de distribution aux créanciers et a déposé un avis modifié auprès du tribunal des faillites du Delaware proposant de réduire de 600 millions de dollars sa réserve pour créances contestées, la faisant passer de 2,4 milliards à 1,8 milliard de dollars, selon PR Newswire et CryptoBriefing. Cette mesure libérerait des liquidités supplémentaires pour les détenteurs de créances déjà admises. La date de référence de ce nouveau cycle a été fixée au 16 juin, et les créanciers éligibles doivent achever la vérification KYC, les documents fiscaux et l'inscription auprès de l'un des prestataires de distribution agréés par FTX — BitGo, Kraken ou Payoneer — avant de recevoir les fonds. Les détenteurs de créances NFT admises ont été informés qu'un processus de distribution distinct a débuté le 30 juin.</p>
<p class="pt">O fundo de recuperação da FTX definiu 31 de julho de 2026 como a data de sua quinta rodada de distribuição a credores e protocolou um aviso emendado no tribunal de falências de Delaware propondo cortar em US$ 600 milhões sua reserva para reclamações contestadas, de US$ 2,4 bilhões para US$ 1,8 bilhão, segundo a PR Newswire e a CryptoBriefing. A medida liberaria caixa adicional para titulares de reclamações já permitidas. A data-base desta nova rodada foi fixada para 16 de junho, e os credores elegíveis devem concluir a verificação KYC, a documentação fiscal e o cadastro junto a um dos provedores de distribuição aprovados pela FTX — BitGo, Kraken ou Payoneer — antes de receber os fundos. Titulares de reclamações de NFT já permitidas foram informados de que um processo de distribuição separado começou em 30 de junho.</p>
<p class="tr">FTX'in tahsilat fonu (recovery trust), alacaklılara yönelik beşinci dağıtım turunun tarihini 31 Temmuz 2026 olarak belirledi ve Delaware iflas mahkemesine, itirazlı alacaklar rezervini 600 milyon dolar azaltarak 2,4 milyar dolardan 1,8 milyar dolara indirmeyi öneren tadil edilmiş bir bildirim sundu; bunu PR Newswire ve CryptoBriefing bildirdi. Bu adım, zaten kabul edilmiş alacak sahipleri için ek nakit serbest bırakacak. Yeni turun kayıt tarihi 16 Haziran olarak belirlendi; uygun alacaklıların fon almadan önce KYC doğrulamasını, vergi belgelerini ve FTX'in onaylı dağıtım sağlayıcılarından biri olan BitGo, Kraken veya Payoneer'e kayıt işlemini tamamlaması gerekiyor. Onaylı NFT Müşteri Hak Talebi sahiplerine, 30 Haziran'da ayrı bir dağıtım sürecinin başladığı bildirildi.</p>
<p class="vi">Quỹ thu hồi tài sản của FTX đã ấn định ngày 31 tháng 7 năm 2026 là ngày phân phối đợt thứ năm cho các chủ nợ và đã nộp thông báo sửa đổi lên tòa án phá sản Delaware, đề xuất cắt giảm 600 triệu đô la quỹ dự phòng cho các khoản yêu cầu bồi thường đang tranh chấp, từ 2,4 tỷ đô la xuống còn 1,8 tỷ đô la, theo PR Newswire và CryptoBriefing. Động thái này sẽ giải phóng thêm tiền mặt cho những người nắm giữ các khoản yêu cầu đã được chấp thuận. Ngày chốt danh sách cho đợt mới được ấn định là 16 tháng 6, và các chủ nợ đủ điều kiện phải hoàn tất xác minh KYC, giấy tờ thuế và đăng ký với một trong các nhà cung cấp dịch vụ phân phối được FTX phê duyệt — BitGo, Kraken hoặc Payoneer — trước khi nhận được tiền. Những người nắm giữ các khoản yêu cầu bồi thường NFT đã được chấp thuận được thông báo rằng một quy trình phân phối riêng đã bắt đầu từ ngày 30 tháng 6.</p>

<p class="ko">이번 조치는 2025년2월 첫 배분 이후 몇 달 간격으로 반복돼 온 패턴의 연장선이다. 당시 소액 '편의클래스(Convenience Class)' 청구권자들에게 청구액 명목가치의 약 120%에 해당하는 약 12억달러가 현금으로 지급됐다. 지난 9월 3차 배분에서는 약 16억달러가 지급됐고, 지난 1월 준비금이 46억달러에서 24억달러로 삭감되면서 재원을 마련한 4차 배분이 3월31일 시작됐다. 샘 뱅크먼프리드의 거래소가 챕터11 파산으로 무너진 지 3년 넘게 지난 지금, 누적 배분액은 100억달러를 넘어섰다.</p>
<p class="en">The filing continues a pattern that has repeated roughly every few months since February 2025, when FTX paid out its first round, about $1.2 billion to small Convenience Class claimants recovering around 120% of their claim's nominal value in cash. A third round paid roughly $1.6 billion last September, and a fourth began March 31 after an earlier reserve cut — from $4.6 billion to $2.4 billion — released funds in January. Cumulative distributions now exceed $10 billion, more than three years after Sam Bankman-Fried's exchange collapsed into Chapter 11.</p>
<p class="ja">この措置は、2025年2月の第1回配当以来、数カ月おきに繰り返されてきたパターンの延長線上にある。当時、少額の「コンビニエンス・クラス」請求権者には、請求額の名目価値の約120%にあたる約12億ドルが現金で支払われた。昨年9月の第3回配当では約16億ドルが支払われ、1月に準備金が46億ドルから24億ドルへ削減されたことで財源が確保された第4回配当が3月31日に開始された。サム・バンクマン・フリード被告の取引所がチャプター11破産で崩壊してから3年余りが経った今、累積配当額は100億ドルを超えた。</p>
<p class="es">La medida continúa un patrón que se ha repetido cada pocos meses desde febrero de 2025, cuando FTX pagó su primera ronda, unos 1.200 millones de dólares a pequeños reclamantes de la Clase de Conveniencia, que recuperaron cerca del 120% del valor nominal de su reclamo en efectivo. Una tercera ronda pagó unos 1.600 millones de dólares en septiembre pasado, y una cuarta comenzó el 31 de marzo tras un recorte anterior de la reserva —de 4.600 a 2.400 millones de dólares— que liberó fondos en enero. Las distribuciones acumuladas superan ahora los 10.000 millones de dólares, más de tres años después de que el exchange de Sam Bankman-Fried colapsara bajo el Capítulo 11.</p>
<p class="de">Die Maßnahme setzt ein Muster fort, das sich seit Februar 2025 alle paar Monate wiederholt hat, als FTX seine erste Runde auszahlte — rund 1,2 Milliarden Dollar an kleine Gläubiger der Convenience Class, die etwa 120 % des Nominalwerts ihrer Forderung in bar zurückerhielten. Eine dritte Runde zahlte im vergangenen September rund 1,6 Milliarden Dollar aus, und eine vierte begann am 31. März, nachdem eine frühere Rückstellungskürzung — von 4,6 auf 2,4 Milliarden Dollar — im Januar Mittel freigesetzt hatte. Die kumulierten Ausschüttungen übersteigen mittlerweile 10 Milliarden Dollar, mehr als drei Jahre nachdem die Börse von Sam Bankman-Fried im Rahmen von Chapter 11 zusammengebrochen ist.</p>
<p class="fr">Cette mesure poursuit un schéma qui se répète tous les quelques mois depuis février 2025, lorsque FTX a versé son premier cycle, environ 1,2 milliard de dollars à de petits créanciers de la Convenience Class, récupérant environ 120 % de la valeur nominale de leur créance en espèces. Un troisième cycle a versé environ 1,6 milliard de dollars en septembre dernier, et un quatrième a débuté le 31 mars après qu'une réduction antérieure de la réserve — de 4,6 à 2,4 milliards de dollars — a libéré des fonds en janvier. Les distributions cumulées dépassent désormais 10 milliards de dollars, plus de trois ans après l'effondrement de la plateforme de Sam Bankman-Fried sous le chapitre 11.</p>
<p class="pt">A medida dá continuidade a um padrão que se repete a cada poucos meses desde fevereiro de 2025, quando a FTX pagou sua primeira rodada, cerca de US$ 1,2 bilhão a pequenos reclamantes da Convenience Class, recuperando cerca de 120% do valor nominal de sua reclamação em dinheiro. Uma terceira rodada pagou aproximadamente US$ 1,6 bilhão em setembro passado, e uma quarta começou em 31 de março após um corte anterior na reserva — de US$ 4,6 bilhões para US$ 2,4 bilhões — que liberou fundos em janeiro. As distribuições acumuladas agora superam US$ 10 bilhões, mais de três anos depois que a corretora de Sam Bankman-Fried entrou em colapso sob o Capítulo 11.</p>
<p class="tr">Bu adım, FTX'in ilk turu ödediği Şubat 2025'ten bu yana birkaç ayda bir tekrarlanan bir örüntüyü sürdürüyor; o zaman küçük Convenience Class alacaklılarına, alacaklarının nominal değerinin yaklaşık %120'sine denk gelen yaklaşık 1,2 milyar dolar nakit olarak ödendi. Geçen Eylül'de üçüncü tur yaklaşık 1,6 milyar dolar ödedi ve Ocak ayında rezervin 4,6 milyar dolardan 2,4 milyar dolara indirilmesiyle serbest kalan fonla dördüncü tur 31 Mart'ta başladı. Sam Bankman-Fried'in borsası Chapter 11 iflasıyla çöktükten üç yıldan fazla bir süre sonra, kümülatif dağıtımlar artık 10 milyar doları aşıyor.</p>
<p class="vi">Động thái này tiếp nối một khuôn mẫu đã lặp lại vài tháng một lần kể từ tháng 2 năm 2025, khi FTX chi trả đợt đầu tiên, khoảng 1,2 tỷ đô la cho các chủ nợ nhỏ thuộc Convenience Class, thu hồi khoảng 120% giá trị danh nghĩa của khoản yêu cầu bằng tiền mặt. Đợt thứ ba đã chi trả khoảng 1,6 tỷ đô la vào tháng 9 năm ngoái, và đợt thứ tư bắt đầu vào ngày 31 tháng 3 sau khi một đợt cắt giảm quỹ dự phòng trước đó — từ 4,6 tỷ xuống 2,4 tỷ đô la — giải phóng tiền vào tháng 1. Tổng số tiền phân phối lũy kế hiện đã vượt 10 tỷ đô la, hơn ba năm sau khi sàn giao dịch của Sam Bankman-Fried sụp đổ theo Chương 11.</p>

<h2 class="ko">오늘의 삭감이 실제로 하는 일</h2>
<h2 class="en">What the Reserve Cut Actually Does</h2>
<h2 class="ja">今回の削減が実際に意味すること</h2>
<h2 class="es">Lo Que Realmente Hace el Recorte de Reserva</h2>
<h2 class="de">Was die Rückstellungskürzung Tatsächlich Bewirkt</h2>
<h2 class="fr">Ce Que la Réduction de Réserve Change Réellement</h2>
<h2 class="pt">O Que o Corte de Reserva Realmente Faz</h2>
<h2 class="tr">Rezerv Kesintisi Aslında Neyi Değiştiriyor</h2>
<h2 class="vi">Việc Cắt Giảm Quỹ Dự Phòng Thực Sự Thay Đổi Điều Gì</h2>

<p class="ko">분쟁채권 준비금이 존재하는 이유는, 미국 파산 절차가 누구에게든 돈을 지급하기 전에 다투고 있는 모든 청구권의 소송이 끝나기를 기다릴 수 없기 때문이다. 트러스트는 — 잔액 규모를 다투는 고객이든, 계열사 간 이체를 되찾으려는 다른 파산재단이든 — 여전히 다투는 중인 모든 청구권의 최대 가능 가치에 해당하는 현금을 따로 떼어 두고, 나머지를 이미 확정(allowed)된 청구권에 배분한다. 준비금을 24억달러에서 18억달러로 줄인다는 것은, 트러스트 측 변호인단이 이제 6억달러어치의 분쟁이 해소됐거나 합의됐거나, 혹은 상한이 충분히 낮아져 그 돈을 계속 묶어둘 필요가 없다고 판단했다는 뜻이며, 그 돈은 이미 절차를 통과한 사람들에게 갈 수 있다.</p>
<p class="en">A disputed-claims reserve exists because U.S. bankruptcy plans can't wait for every contested claim to be litigated before paying anyone; the trust sets aside cash equal to the maximum possible value of all claims still being fought over — whether that's a customer disputing the size of their balance or a rival estate clawing back an intercompany transfer — and distributes the rest to claims already allowed. Cutting the reserve from $2.4 billion to $1.8 billion means the trust's lawyers now judge $600 million of those disputes to be resolved, settled, or capped low enough that holding the money idle is no longer necessary, and it can instead reach people who have already cleared the process.</p>
<p class="ja">係争債権準備金が存在する理由は、米国の破産手続きが、誰かに支払いをする前にすべての係争中の請求権の訴訟が終わるのを待つことができないからだ。トラストは — 残高の規模を争う顧客であれ、関連会社間の送金を取り戻そうとする別の破産財団であれ — 依然として争われているすべての請求権の最大可能価値に相当する現金を取り分けておき、残りをすでに確定(allowed)された請求権に配当する。準備金を24億ドルから18億ドルに減らすということは、トラスト側の弁護団が、6億ドル分の争いがすでに解決・和解したか、上限が十分低く抑えられ、その資金を塩漬けにしておく必要がなくなったと判断したことを意味し、その資金はすでに手続きを通過した人々に届けられる。</p>
<p class="es">Una reserva de reclamos en disputa existe porque los planes de quiebra en EE.UU. no pueden esperar a que se litigue cada reclamo impugnado antes de pagarle a nadie; el fondo aparta efectivo equivalente al valor máximo posible de todos los reclamos que aún se disputan —ya sea un cliente que discute el tamaño de su saldo o un patrimonio rival reclamando una transferencia entre empresas— y distribuye el resto a los reclamos ya permitidos. Recortar la reserva de 2.400 a 1.800 millones de dólares significa que los abogados del fondo ahora consideran que 600 millones de dólares de esas disputas están resueltas, acordadas, o limitadas lo suficientemente bajo como para que ya no sea necesario mantener ese dinero inactivo, y en su lugar puede llegar a quienes ya superaron el proceso.</p>
<p class="de">Eine Rückstellung für strittige Forderungen existiert, weil US-Insolvenzpläne nicht warten können, bis jede angefochtene Forderung ausgestritten ist, bevor irgendjemand bezahlt wird; der Trust legt Bargeld in Höhe des maximal möglichen Werts aller noch strittigen Forderungen zurück — sei es ein Kunde, der die Höhe seines Guthabens anficht, oder ein konkurrierender Insolvenzverwalter, der eine konzerninterne Überweisung zurückfordert — und verteilt den Rest an bereits zugelassene Forderungen. Die Kürzung der Rückstellung von 2,4 auf 1,8 Milliarden Dollar bedeutet, dass die Anwälte des Trusts nun 600 Millionen Dollar dieser Streitfälle als gelöst, verglichen oder ausreichend niedrig gedeckelt einschätzen, sodass es nicht mehr nötig ist, dieses Geld brachliegen zu lassen — es kann stattdessen an jene gehen, die das Verfahren bereits durchlaufen haben.</p>
<p class="fr">Une réserve pour créances contestées existe parce que les plans de faillite américains ne peuvent pas attendre que chaque créance contestée soit tranchée en justice avant de payer qui que ce soit ; le fonds met de côté des liquidités équivalant à la valeur maximale possible de toutes les créances encore disputées — qu'il s'agisse d'un client contestant le montant de son solde ou d'un patrimoine concurrent réclamant un transfert intersociétés — et distribue le reste aux créances déjà admises. Réduire la réserve de 2,4 à 1,8 milliard de dollars signifie que les avocats du fonds jugent désormais que 600 millions de dollars de ces litiges sont résolus, réglés à l'amiable, ou plafonnés à un niveau suffisamment bas pour qu'il ne soit plus nécessaire de laisser cet argent inutilisé, et qu'il peut au contraire atteindre les personnes ayant déjà franchi le processus.</p>
<p class="pt">Uma reserva para reclamações contestadas existe porque os planos de falência nos EUA não podem esperar que cada reclamação contestada seja litigada antes de pagar a alguém; o fundo separa caixa equivalente ao valor máximo possível de todas as reclamações ainda em disputa — seja um cliente contestando o tamanho de seu saldo, seja uma massa falida rival tentando recuperar uma transferência entre empresas — e distribui o restante às reclamações já permitidas. Cortar a reserva de US$ 2,4 bilhões para US$ 1,8 bilhão significa que os advogados do fundo agora julgam que US$ 600 milhões dessas disputas estão resolvidas, acordadas, ou limitadas a um teto baixo o suficiente para que não seja mais necessário manter esse dinheiro parado, podendo em vez disso chegar a quem já concluiu o processo.</p>
<p class="tr">İtirazlı alacaklar rezervi var, çünkü ABD iflas planları kimseye ödeme yapmadan önce itiraz edilen her alacağın dava sürecinin bitmesini bekleyemez; fon — bakiyesinin büyüklüğüne itiraz eden bir müşteri olsun, şirketler arası bir transferi geri almaya çalışan rakip bir tasfiye kütlesi olsun — hâlâ tartışmalı olan tüm alacakların olası en yüksek değerine eşit nakdi ayırır ve geri kalanını zaten kabul edilmiş alacaklara dağıtır. Rezervi 2,4 milyar dolardan 1,8 milyar dolara indirmek, fonun avukatlarının artık bu anlaşmazlıkların 600 milyon dolarlık kısmının çözüldüğünü, uzlaşıldığını veya yeterince düşük bir tavana bağlandığını ve bu parayı artık atıl tutmaya gerek olmadığını değerlendirdiği anlamına gelir; bu para bunun yerine süreci zaten tamamlamış olanlara ulaşabilir.</p>
<p class="vi">Quỹ dự phòng cho các khoản yêu cầu tranh chấp tồn tại vì các kế hoạch phá sản của Mỹ không thể chờ mọi khoản yêu cầu bị tranh chấp được tranh tụng xong xuôi trước khi trả tiền cho bất kỳ ai; quỹ dành riêng một khoản tiền mặt tương đương giá trị tối đa có thể có của tất cả các khoản yêu cầu vẫn đang tranh chấp — dù đó là một khách hàng tranh cãi về quy mô số dư của mình hay một khối tài sản phá sản đối thủ đòi lại một khoản chuyển tiền nội bộ giữa các công ty — và phân phối phần còn lại cho các khoản yêu cầu đã được chấp thuận. Cắt giảm quỹ dự phòng từ 2,4 tỷ xuống 1,8 tỷ đô la có nghĩa là các luật sư của quỹ giờ đây đánh giá rằng 600 triệu đô la trong số các tranh chấp đó đã được giải quyết, dàn xếp, hoặc bị giới hạn ở mức đủ thấp để không còn cần giữ số tiền đó nhàn rỗi nữa, và thay vào đó nó có thể đến tay những người đã hoàn tất quy trình.</p>

<p class="ko">이는 6개월 사이 두 번째 삭감이다 — 지난 1월 46억달러에서 24억달러로의 삭감이 같은 방식으로 3월 배분의 재원이 됐다. 각 삭감은 파산법원의 승인을 필요로 하며, 통상 극적인 단일 사건이라기보다는 가장 규모가 큰 분쟁 청구권 묶음을 한꺼번에 해소하는 협상 합의나 법원 판결을 뒤따른다. 이 메커니즘은 인내심에 보상을 준다 — KYC와 서류 제출을 일찍 마친 채권자는 라운드가 열리자마자 지급받는 반면, 해소되지 않은 분쟁은 파산재단이 절차를 마칠 때까지 라운드를 거듭할수록 준비금 풀을 계속 줄여나간다.</p>
<p class="en">This is the second such cut in six months — the January reduction, from $4.6 billion to $2.4 billion, funded the March round the same way. Each cut requires the bankruptcy court's approval and typically follows negotiated settlements or court rulings that resolve a batch of the largest disputed claims at once, rather than a single dramatic event. The mechanism rewards patience: creditors who complete KYC and documentation early get paid as soon as a round opens, while unresolved disputes continue to shrink the reserve pool round by round until the estate can close.</p>
<p class="ja">これは6カ月間で2度目の削減だ——1月の46億ドルから24億ドルへの削減も同じ方式で3月の配当の財源となった。それぞれの削減は破産裁判所の承認を必要とし、通常は劇的な単発の出来事というより、最大規模の係争請求権のまとまりを一度に解決する交渉合意や裁判所の判断に続くものだ。この仕組みは忍耐に報いる——KYCと書類提出を早く済ませた債権者はラウンドが開かれ次第支払いを受ける一方、未解決の争いは破産財団が手続きを終えるまで、ラウンドを重ねるごとに準備金プールを縮小させ続ける。</p>
<p class="es">Este es el segundo recorte de este tipo en seis meses —la reducción de enero, de 4.600 a 2.400 millones de dólares, financió la ronda de marzo de la misma manera. Cada recorte requiere la aprobación del tribunal de quiebras y normalmente sigue a acuerdos negociados o fallos judiciales que resuelven de golpe un lote de los mayores reclamos disputados, en lugar de un evento dramático único. El mecanismo recompensa la paciencia: los acreedores que completan el KYC y la documentación temprano cobran tan pronto se abre una ronda, mientras que las disputas no resueltas siguen reduciendo la reserva ronda tras ronda hasta que el patrimonio pueda cerrarse.</p>
<p class="de">Dies ist die zweite derartige Kürzung innerhalb von sechs Monaten — die Reduzierung im Januar, von 4,6 auf 2,4 Milliarden Dollar, finanzierte auf dieselbe Weise die Runde im März. Jede Kürzung erfordert die Zustimmung des Insolvenzgerichts und folgt in der Regel ausgehandelten Vergleichen oder Gerichtsentscheidungen, die ein Bündel der größten strittigen Forderungen auf einmal lösen, statt einem einzelnen dramatischen Ereignis. Der Mechanismus belohnt Geduld: Gläubiger, die KYC und Unterlagen frühzeitig abschließen, werden ausgezahlt, sobald eine Runde eröffnet wird, während ungelöste Streitfälle den Rückstellungspool von Runde zu Runde weiter schrumpfen lassen, bis der Nachlass abgeschlossen werden kann.</p>
<p class="fr">Il s'agit de la deuxième réduction de ce type en six mois — la baisse de janvier, de 4,6 à 2,4 milliards de dollars, avait financé le cycle de mars de la même manière. Chaque réduction nécessite l'approbation du tribunal des faillites et suit généralement des accords négociés ou des décisions de justice qui résolvent d'un coup un lot des plus grandes créances contestées, plutôt qu'un événement spectaculaire isolé. Ce mécanisme récompense la patience : les créanciers qui complètent le KYC et les documents tôt sont payés dès l'ouverture d'un cycle, tandis que les litiges non résolus continuent de réduire la réserve cycle après cycle jusqu'à ce que le patrimoine puisse être clôturé.</p>
<p class="pt">Este é o segundo corte desse tipo em seis meses — a redução de janeiro, de US$ 4,6 bilhões para US$ 2,4 bilhões, financiou a rodada de março da mesma forma. Cada corte requer aprovação do tribunal de falências e normalmente segue acordos negociados ou decisões judiciais que resolvem de uma vez um lote das maiores reclamações contestadas, em vez de um evento dramático único. O mecanismo recompensa a paciência: credores que completam o KYC e a documentação cedo recebem assim que uma rodada abre, enquanto disputas não resolvidas continuam encolhendo o pool de reserva rodada após rodada até que a massa falida possa ser encerrada.</p>
<p class="tr">Bu, altı ay içindeki ikinci kesinti — Ocak ayındaki 4,6 milyar dolardan 2,4 milyar dolara indirim de aynı şekilde Mart turunu finanse etmişti. Her kesinti iflas mahkemesinin onayını gerektirir ve genellikle tek bir dramatik olaydan çok, en büyük itirazlı alacak grubunu bir kerede çözen müzakere edilmiş anlaşmaları veya mahkeme kararlarını takip eder. Bu mekanizma sabrı ödüllendirir: KYC ve belgelerini erken tamamlayan alacaklılar bir tur açılır açılmaz ödeme alırken, çözülmemiş anlaşmazlıklar tasfiye kütlesi kapanana kadar tur be tur rezerv havuzunu küçültmeye devam eder.</p>
<p class="vi">Đây là lần cắt giảm thứ hai như vậy trong sáu tháng — đợt giảm hồi tháng 1, từ 4,6 tỷ xuống 2,4 tỷ đô la, đã tài trợ cho đợt phân phối tháng 3 theo cách tương tự. Mỗi lần cắt giảm đều cần sự chấp thuận của tòa án phá sản và thường theo sau các thỏa thuận đã thương lượng hoặc phán quyết của tòa giải quyết một loạt các khoản yêu cầu tranh chấp lớn nhất cùng một lúc, thay vì một sự kiện kịch tính đơn lẻ. Cơ chế này thưởng cho sự kiên nhẫn: các chủ nợ hoàn tất KYC và giấy tờ sớm sẽ được trả tiền ngay khi một đợt mở ra, trong khi các tranh chấp chưa được giải quyết tiếp tục làm co lại quỹ dự phòng qua từng đợt cho đến khi khối tài sản phá sản có thể khép lại.</p>

<h2 class="ko">왜 여전히 2022년11월 가격인가</h2>
<h2 class="en">Why November 2022 Still Sets the Price</h2>
<h2 class="ja">なぜ今も2022年11月の価格なのか</h2>
<h2 class="es">Por Qué Noviembre de 2022 Sigue Fijando el Precio</h2>
<h2 class="de">Warum Immer Noch der Preis von November 2022 Gilt</h2>
<h2 class="fr">Pourquoi Novembre 2022 Fixe Toujours le Prix</h2>
<h2 class="pt">Por Que Novembro de 2022 Ainda Define o Preço</h2>
<h2 class="tr">Kasım 2022 Neden Hâlâ Fiyatı Belirliyor</h2>
<h2 class="vi">Vì Sao Giá Tháng 11 Năm 2022 Vẫn Là Mốc Cố Định</h2>

<p class="ko">모든 FTX 청구권에 찍힌 숫자는 회사가 챕터11을 신청한 날 — 비트코인이 17,036달러 부근에서 거래되던 2022년11월11일 — 에 고정됐다. 미국 파산법이 일반적으로 청구권을 파산신청일(petition date) 기준으로 평가해, 고객이 보유했던 어떤 암호화폐든 그날의 가격으로 단일한 달러 표시 무담보 청구권으로 환산하기 때문이다. 델라웨어 법원은 2024년 이례적으로 파산신청일 시장가격을 이용해 이 청구권들을 공식 추산하는 절차를 밟았고, 확정된 회생계획은 그 고정된 달러 액수 대비 약 118%~142%의 회수율을 현금으로 전액 지급하는 것으로 설계됐다.</p>
<p class="en">The number printed on every FTX claim was fixed the day the company filed for Chapter 11 — November 11, 2022, when bitcoin traded near $17,036 — because U.S. bankruptcy law generally values claims as of the petition date, converting whatever crypto a customer held into a single dollar-denominated unsecured claim at that day's price. A Delaware court took the unusual step in 2024 of formally estimating those claims using petition-date market prices, and the confirmed reorganization plan projected recoveries of roughly 118% to 142% of that fixed dollar figure, paid entirely in cash.</p>
<p class="ja">すべてのFTX請求権に刻まれた数字は、同社がチャプター11を申請した日——ビットコインが17,036ドル前後で取引されていた2022年11月11日——に固定された。米国破産法は一般に、請求権を破産申請日(petition date)基準で評価し、顧客が保有していたどの暗号資産も、その日の価格で単一のドル建て無担保請求権に換算するためだ。デラウェア裁判所は2024年、異例にも破産申請日の市場価格を用いてこれらの請求権を正式に見積もる手続きを取り、確定した再建計画は、その固定されたドル額に対して約118%〜142%の回収率を全額現金で支払うよう設計された。</p>
<p class="es">La cifra impresa en cada reclamo de FTX quedó fijada el día en que la empresa se acogió al Capítulo 11 —el 11 de noviembre de 2022, cuando el bitcoin cotizaba cerca de 17.036 dólares— porque la ley de quiebras estadounidense generalmente valora los reclamos a la fecha de la petición, convirtiendo cualquier cripto que un cliente tuviera en un único reclamo no garantizado denominado en dólares al precio de ese día. Un tribunal de Delaware dio el paso inusual en 2024 de estimar formalmente esos reclamos usando los precios de mercado de la fecha de petición, y el plan de reorganización confirmado proyectó recuperaciones de aproximadamente el 118% al 142% de esa cifra fija en dólares, pagada enteramente en efectivo.</p>
<p class="de">Die Zahl, die auf jeder FTX-Forderung steht, wurde an dem Tag fixiert, an dem das Unternehmen Chapter 11 beantragte — am 11. November 2022, als Bitcoin bei etwa 17.036 Dollar gehandelt wurde —, weil US-Insolvenzrecht Forderungen in der Regel zum Stichtag des Antrags bewertet und dabei jede von einem Kunden gehaltene Kryptowährung in eine einzige, auf Dollar lautende ungesicherte Forderung zum Kurs jenes Tages umwandelt. Ein Gericht in Delaware ging 2024 den ungewöhnlichen Schritt, diese Forderungen förmlich anhand der Marktpreise zum Antragsstichtag zu schätzen, und der bestätigte Reorganisationsplan sah Rückflüsse von etwa 118 % bis 142 % dieser fixen Dollarsumme vor, vollständig in bar ausgezahlt.</p>
<p class="fr">Le chiffre inscrit sur chaque créance FTX a été fixé le jour où l'entreprise a déposé le bilan sous le chapitre 11 — le 11 novembre 2022, lorsque le bitcoin s'échangeait autour de 17 036 dollars — car le droit américain des faillites évalue généralement les créances à la date de la pétition, convertissant toute cryptomonnaie détenue par un client en une créance chirographaire unique libellée en dollars au prix de ce jour-là. Un tribunal du Delaware a pris l'initiative inhabituelle en 2024 d'estimer formellement ces créances en utilisant les prix du marché à la date de la pétition, et le plan de réorganisation confirmé prévoyait des recouvrements d'environ 118 % à 142 % de ce montant fixe en dollars, versés entièrement en espèces.</p>
<p class="pt">O número impresso em cada reclamação da FTX foi fixado no dia em que a empresa entrou com o Capítulo 11 — 11 de novembro de 2022, quando o bitcoin era negociado perto de US$ 17.036 — porque a lei de falências dos EUA geralmente avalia reclamações na data do pedido, convertendo qualquer cripto que um cliente detivesse em uma única reclamação não garantida denominada em dólares ao preço daquele dia. Um tribunal de Delaware deu o passo incomum em 2024 de estimar formalmente essas reclamações usando preços de mercado da data do pedido, e o plano de reorganização confirmado projetou recuperações de aproximadamente 118% a 142% desse valor fixo em dólares, pago inteiramente em dinheiro.</p>
<p class="tr">Her FTX alacağına yazılan rakam, şirketin Chapter 11'e başvurduğu gün — bitcoin'in yaklaşık 17.036 dolardan işlem gördüğü 11 Kasım 2022 — sabitlendi, çünkü ABD iflas hukuku genellikle alacakları başvuru tarihi (petition date) itibarıyla değerlendirir ve bir müşterinin elinde bulunan her kriptoyu o günün fiyatından tek bir dolar cinsinden teminatsız alacağa çevirir. Delaware'deki bir mahkeme 2024'te bu alacakları başvuru tarihindeki piyasa fiyatlarını kullanarak resmi olarak tahmin etme gibi alışılmadık bir adım attı ve onaylanan yeniden yapılanma planı, bu sabit dolar rakamının yaklaşık %118 ila %142'sinin tamamen nakit olarak geri kazanılmasını öngördü.</p>
<p class="vi">Con số ghi trên mỗi khoản yêu cầu bồi thường của FTX đã được ấn định vào ngày công ty nộp đơn theo Chương 11 — ngày 11 tháng 11 năm 2022, khi bitcoin giao dịch quanh mức 17.036 đô la — bởi vì luật phá sản Mỹ nói chung định giá các khoản yêu cầu theo ngày nộp đơn, chuyển đổi bất kỳ loại tiền mã hóa nào mà khách hàng nắm giữ thành một khoản yêu cầu không có bảo đảm duy nhất tính bằng đô la theo giá của ngày hôm đó. Một tòa án ở Delaware đã thực hiện bước đi bất thường vào năm 2024 là chính thức ước tính các khoản yêu cầu này bằng cách sử dụng giá thị trường tại ngày nộp đơn, và kế hoạch tái cơ cấu đã được xác nhận dự kiến mức thu hồi khoảng 118% đến 142% con số đô la cố định đó, được trả toàn bộ bằng tiền mặt.</p>

<p class="ko">문제는 비트코인이 그 이후 2022년11월 수준보다 몇 배나 높은 가격에서 거래돼 왔다는 점이다. 그래서 2022년 달러 기준 '142% 회수'라 해도, 붕괴 당시 실제 비트코인을 보유하고 있던 고객 입장에서는 거래소가 자산을 현물 그대로 돌려줬을 경우보다 훨씬 적은 구매력의 코인을 손에 쥐게 될 수 있다. 이 방식을 옹호하는 쪽은 파산신청일 평가가 암호화폐 보유자를 홀대하기 위해 고안된 규칙이 아니라 모든 자산군에 공평하게 적용되는 표준적인 파산 관행이라고 지적한다 — 대안으로, 수년에 걸친 소송 기간 내내 변동성 자산 가치를 추적해 청구권을 매긴다면 어떤 회생계획도 확정 짓기 불가능해질 것이라는 논리다.</p>
<p class="en">The catch is that bitcoin has since traded several times higher than its November 2022 level, so a "142% recovery" measured against 2022 dollars can still leave a customer who held actual bitcoin through the collapse with far less purchasing power in coins than if the exchange had simply returned their assets in kind. Defenders of the approach note petition-date valuation is standard bankruptcy practice applied evenhandedly across all asset classes, not a rule invented to shortchange crypto holders — the alternative, tracking a claim's value against a volatile asset for years of litigation, would make every plan impossible to finalize.</p>
<p class="ja">問題は、ビットコインがその後2022年11月の水準の数倍で取引されてきたことだ。そのため2022年ドル基準での「142%回収」であっても、崩壊当時に実際にビットコインを保有していた顧客からすれば、取引所が資産をそのまま現物で返還した場合よりもはるかに少ない購買力のコインしか手にできないことになりかねない。この方式を擁護する側は、破産申請日評価は暗号資産保有者を冷遇するために考案された規則ではなく、あらゆる資産クラスに公平に適用される標準的な破産実務だと指摘する——代替案として、数年にわたる訴訟期間中ずっとボラティリティの高い資産の価値を追跡して請求権を算定するとしたら、どの再建計画も確定させることは不可能になるだろうという論理だ。</p>
<p class="es">El problema es que el bitcoin desde entonces ha cotizado varias veces por encima de su nivel de noviembre de 2022, por lo que una "recuperación del 142%" medida en dólares de 2022 aún puede dejar a un cliente que mantuvo bitcoin real durante el colapso con mucho menos poder adquisitivo en monedas del que habría tenido si el exchange simplemente hubiera devuelto sus activos en especie. Los defensores del enfoque señalan que la valoración a la fecha de petición es una práctica estándar de quiebras aplicada equitativamente a todas las clases de activos, no una regla inventada para perjudicar a los tenedores de cripto —la alternativa, rastrear el valor de un reclamo frente a un activo volátil durante años de litigio, haría imposible finalizar cualquier plan.</p>
<p class="de">Der Haken ist, dass Bitcoin seitdem mehrfach über seinem Niveau von November 2022 gehandelt wurde, sodass eine „Rückzahlungsquote von 142 %", gemessen in Dollar von 2022, einen Kunden, der tatsächlich Bitcoin während des Zusammenbruchs hielt, immer noch mit weit weniger Kaufkraft in Coins zurücklassen kann, als wenn die Börse seine Vermögenswerte einfach in Natura zurückgegeben hätte. Befürworter des Ansatzes weisen darauf hin, dass die Bewertung zum Antragsstichtag gängige, gleichmäßig auf alle Anlageklassen angewandte Insolvenzpraxis ist und keine Regel, die erfunden wurde, um Krypto-Inhaber zu benachteiligen — die Alternative, den Wert einer Forderung über Jahre des Rechtsstreits hinweg gegen ein volatiles Asset zu verfolgen, würde es unmöglich machen, überhaupt einen Plan abzuschließen.</p>
<p class="fr">Le hic, c'est que le bitcoin s'est depuis échangé à plusieurs fois son niveau de novembre 2022, de sorte qu'un « recouvrement de 142 % » mesuré en dollars de 2022 peut encore laisser un client ayant réellement détenu du bitcoin pendant l'effondrement avec un pouvoir d'achat en pièces bien inférieur à ce qu'il aurait eu si la plateforme avait simplement restitué ses actifs en nature. Les défenseurs de cette approche soulignent que l'évaluation à la date de la pétition est une pratique standard des faillites appliquée équitablement à toutes les classes d'actifs, et non une règle inventée pour léser les détenteurs de cryptomonnaies — l'alternative, suivre la valeur d'une créance par rapport à un actif volatil pendant des années de litige, rendrait impossible la finalisation de tout plan.</p>
<p class="pt">O problema é que o bitcoin desde então tem sido negociado a várias vezes seu nível de novembro de 2022, então uma "recuperação de 142%" medida em dólares de 2022 ainda pode deixar um cliente que detinha bitcoin real durante o colapso com um poder de compra em moedas muito menor do que se a corretora simplesmente tivesse devolvido seus ativos in natura. Defensores da abordagem apontam que a avaliação na data do pedido é uma prática padrão de falência aplicada de forma equânime a todas as classes de ativos, não uma regra inventada para prejudicar detentores de cripto — a alternativa, acompanhar o valor de uma reclamação contra um ativo volátil ao longo de anos de litígio, tornaria impossível finalizar qualquer plano.</p>
<p class="tr">Sorun şu ki, bitcoin o zamandan beri Kasım 2022 seviyesinin birkaç katı fiyattan işlem gördü, bu yüzden 2022 dolarlarına göre ölçülen bir "%142 geri kazanım", çöküş sırasında gerçekten bitcoin tutan bir müşteriyi, borsa varlıklarını aynen (in kind) iade etmiş olsaydı elde edeceğinden çok daha az satın alma gücüne sahip coinlerle baş başa bırakabilir. Bu yaklaşımı savunanlar, başvuru tarihi değerlemesinin kripto sahiplerini mağdur etmek için icat edilmiş bir kural değil, tüm varlık sınıflarına eşit şekilde uygulanan standart bir iflas uygulaması olduğunu belirtiyor — alternatif olarak, bir alacağın değerini yıllar süren dava boyunca oynak bir varlığa karşı takip etmek, herhangi bir planın sonuçlandırılmasını imkânsız hale getirirdi.</p>
<p class="vi">Vấn đề là bitcoin kể từ đó đã giao dịch cao hơn nhiều lần so với mức tháng 11 năm 2022, vì vậy mức "thu hồi 142%" tính theo đô la năm 2022 vẫn có thể khiến một khách hàng thực sự nắm giữ bitcoin trong thời gian sụp đổ nhận được sức mua bằng coin thấp hơn nhiều so với việc sàn giao dịch đơn giản trả lại tài sản của họ theo đúng hiện vật. Những người ủng hộ cách tiếp cận này chỉ ra rằng việc định giá theo ngày nộp đơn là thông lệ phá sản tiêu chuẩn được áp dụng công bằng cho mọi loại tài sản, không phải một quy tắc được đặt ra để thiệt hại cho người nắm giữ tiền mã hóa — giải pháp thay thế, theo dõi giá trị của một khoản yêu cầu so với một tài sản biến động qua nhiều năm tranh tụng, sẽ khiến bất kỳ kế hoạch nào cũng không thể hoàn tất được.</p>

<h2 class="ko">므트곡스가 보여주는 거울상</h2>
<h2 class="en">A Mirror Image in Mt. Gox</h2>
<h2 class="ja">マウントゴックスが映す鏡像</h2>
<h2 class="es">Una Imagen Especular en Mt. Gox</h2>
<h2 class="de">Ein Spiegelbild bei Mt. Gox</h2>
<h2 class="fr">Une Image en Miroir chez Mt. Gox</h2>
<h2 class="pt">Uma Imagem Espelhada na Mt. Gox</h2>
<h2 class="tr">Mt. Gox'ta Ayna Görüntüsü</h2>
<h2 class="vi">Hình Ảnh Phản Chiếu Ở Mt. Gox</h2>

<p class="ko">'2022년 가격으로 현금 지급'이라는 FTX의 모델은, 2014년 무너진 도쿄 거래소 므트곡스(Mt. Gox)가 10년 넘게 끌어온 자체 사건을 정리하는 방식과 거의 정반대다. 므트곡스의 민사재생계획은 고정된 달러 금액이 아니라 비트코인과 비트코인캐시를 채권자에게 직접 돌려준다 — 이는 이미 배상을 받은 약 1만9,500명의 채권자가, 청구권 가치를 붕괴 당시 가격에 묶어두는 대신 2014년 수준 이후 통화의 가격 상승분을 그대로 포착했다는 의미다. 반면 므트곡스 자체의 배상 마감기한은 이제까지 세 차례 미뤄져 최근에는 2026년10월31일로 재조정됐고, 약 3만4,689 BTC가 여전히 지갑에 그대로 남아있다.</p>
<p class="en">FTX's cash-at-2022-prices model is close to the opposite of how Mt. Gox, the Tokyo exchange that collapsed in 2014, is unwinding its own decade-old case. Mt. Gox's civil rehabilitation plan returns creditors bitcoin and bitcoin cash directly rather than a fixed dollar sum, meaning the roughly 19,500 creditors already repaid captured the currency's appreciation from 2014 levels instead of having it capped at collapse-day prices — even as Mt. Gox's own repayment deadline has now been pushed back three times, most recently to October 31, 2026, with about 34,689 BTC still sitting unmoved in its wallets.</p>
<p class="ja">「2022年価格で現金支払い」というFTXのモデルは、2014年に破綻した東京の取引所マウントゴックス(Mt. Gox)が10年以上かけて自らの案件を清算している方式とほぼ正反対だ。マウントゴックスの民事再生計画は、固定されたドル額ではなくビットコインとビットコインキャッシュを債権者に直接返還する——これは、すでに弁済を受けた約1万9,500人の債権者が、請求権の価値を破綻当時の価格に固定される代わりに、2014年水準からの通貨の値上がり分をそのまま享受したことを意味する。一方でマウントゴックス自体の弁済期限はこれまで3度延期され、直近では2026年10月31日に再調整され、約3万4,689BTCが今なおウォレットに残ったままだ。</p>
<p class="es">El modelo de FTX de "efectivo a precios de 2022" es casi lo opuesto a cómo Mt. Gox, el exchange de Tokio que colapsó en 2014, está liquidando su propio caso de más de una década. El plan de rehabilitación civil de Mt. Gox devuelve a los acreedores bitcoin y bitcoin cash directamente en lugar de una suma fija en dólares, lo que significa que los aproximadamente 19.500 acreedores ya reembolsados capturaron la apreciación de la moneda desde los niveles de 2014 en vez de tenerla limitada a los precios del día del colapso —incluso cuando el propio plazo de reembolso de Mt. Gox se ha pospuesto ya tres veces, más recientemente hasta el 31 de octubre de 2026, con unos 34.689 BTC todavía sin moverse en sus billeteras.</p>
<p class="de">FTXs Modell „Bargeld zu Preisen von 2022" ist fast das Gegenteil davon, wie Mt. Gox, die 2014 zusammengebrochene Tokioter Börse, ihren eigenen, jahrzehntealten Fall abwickelt. Mt. Gox' zivilrechtlicher Sanierungsplan gibt Gläubigern Bitcoin und Bitcoin Cash direkt zurück, statt einer fixen Dollarsumme — das bedeutet, dass die bereits rund 19.500 entschädigten Gläubiger die Wertsteigerung der Währung seit dem Niveau von 2014 mitnahmen, statt sie auf die Preise am Tag des Zusammenbruchs gedeckelt zu bekommen — selbst während Mt. Gox' eigene Rückzahlungsfrist inzwischen dreimal verschoben wurde, zuletzt auf den 31. Oktober 2026, wobei noch rund 34.689 BTC unbewegt in seinen Wallets liegen.</p>
<p class="fr">Le modèle de FTX, « espèces aux prix de 2022 », est presque l'inverse de la manière dont Mt. Gox, la plateforme tokyoïte qui s'est effondrée en 2014, liquide sa propre affaire vieille de plus d'une décennie. Le plan de réhabilitation civile de Mt. Gox reverse directement aux créanciers du bitcoin et du bitcoin cash plutôt qu'une somme fixe en dollars, ce qui signifie que les quelque 19 500 créanciers déjà remboursés ont capté l'appréciation de la monnaie depuis les niveaux de 2014 au lieu de la voir plafonnée aux prix du jour de l'effondrement — alors même que l'échéance de remboursement de Mt. Gox a désormais été repoussée trois fois, la plus récente au 31 octobre 2026, avec environ 34 689 BTC toujours immobiles dans ses portefeuilles.</p>
<p class="pt">O modelo da FTX de "dinheiro a preços de 2022" é quase o oposto de como a Mt. Gox, a corretora de Tóquio que colapsou em 2014, está encerrando seu próprio caso de mais de uma década. O plano de reabilitação civil da Mt. Gox devolve bitcoin e bitcoin cash diretamente aos credores, em vez de uma soma fixa em dólares — o que significa que os cerca de 19.500 credores já reembolsados capturaram a valorização da moeda desde os níveis de 2014, em vez de tê-la limitada aos preços do dia do colapso — mesmo com o próprio prazo de reembolso da Mt. Gox já tendo sido adiado três vezes, mais recentemente para 31 de outubro de 2026, com cerca de 34.689 BTC ainda parados em suas carteiras.</p>
<p class="tr">FTX'in "2022 fiyatlarından nakit" modeli, 2014'te çöken Tokyo borsası Mt. Gox'un on yılı aşkın süredir devam eden kendi davasını tasfiye etme biçiminin neredeyse tam tersidir. Mt. Gox'un medeni yeniden yapılanma planı, alacaklılara sabit bir dolar tutarı yerine doğrudan bitcoin ve bitcoin cash iade ediyor — bu, zaten geri ödemesi yapılan yaklaşık 19.500 alacaklının, alacak değerinin çöküş günü fiyatlarına sabitlenmesi yerine, para biriminin 2014 seviyelerinden bu yana değer artışını yakaladığı anlamına geliyor — Mt. Gox'un kendi geri ödeme süresi şimdiye kadar üç kez ertelenip en son 31 Ekim 2026'ya çekilmiş ve yaklaşık 34.689 BTC hâlâ cüzdanlarında hareketsiz dururken bile.</p>
<p class="vi">Mô hình "tiền mặt theo giá năm 2022" của FTX gần như trái ngược với cách Mt. Gox, sàn giao dịch Tokyo sụp đổ năm 2014, đang giải quyết vụ việc kéo dài hơn một thập kỷ của chính mình. Kế hoạch phục hồi dân sự của Mt. Gox trả lại trực tiếp cho các chủ nợ bằng bitcoin và bitcoin cash thay vì một khoản tiền đô la cố định — nghĩa là khoảng 19.500 chủ nợ đã được hoàn trả đã thu được mức tăng giá của đồng tiền kể từ mức năm 2014, thay vì bị giới hạn ở mức giá vào ngày sụp đổ — ngay cả khi thời hạn hoàn trả của chính Mt. Gox giờ đây đã bị lùi ba lần, gần đây nhất là đến ngày 31 tháng 10 năm 2026, với khoảng 34.689 BTC vẫn nằm yên trong ví của họ.</p>

<p class="ko">이 대조는 암호화폐 파산에서 '채권자 회수'가 하나의 표준화된 개념이 아님을 보여준다 — 계획이 기초자산 그대로 지급하느냐, 아니면 과거 특정 시점 가격에 고정된 현금으로 지급하느냐는 전적으로, 오늘 발표되는 그 어떤 헤드라인 숫자보다 몇 년 앞서 정해지는 설계상의 선택이다. 이는 또한 FTX의 법원 서류가 왜 계속 100%를 넘는 회수율을 강조하는지도 설명해준다 — 2022년 가격 대비로는 후한 수치로 읽히지만, 그 코인들이 오늘 실제로 얼마의 가치가 있는지를 기준으로 재면 전혀 다른 이야기가 된다.</p>
<p class="en">The contrast is a reminder that "creditor recovery" in crypto bankruptcies is not one standardized concept — it depends entirely on whether a plan pays in the underlying asset or in cash pegged to a historical price, a design choice made years before any of today's headline numbers are announced. It also suggests why FTX's court filings keep emphasizing recovery percentages above 100%, a framing that reads generously against 2022 prices but tells a different story once measured against what those same coins are worth today.</p>
<p class="ja">この対比は、暗号資産破産における「債権者回収」がひとつの標準化された概念ではないことを示している——計画が原資産そのもので支払うのか、それとも過去の特定時点の価格に固定された現金で支払うのかは、今日発表されるどんな見出しの数字よりも何年も前に決まる設計上の選択にすぎない。これはまた、FTXの裁判所提出書類がなぜ100%を超える回収率を強調し続けるのかも説明する——2022年価格基準では気前の良い数字に見えるが、そのコインが今日実際にいくらの価値があるかを基準に測れば、まったく違う話になる。</p>
<p class="es">El contraste es un recordatorio de que la "recuperación de acreedores" en las quiebras cripto no es un concepto único y estandarizado —depende enteramente de si un plan paga en el activo subyacente o en efectivo anclado a un precio histórico, una decisión de diseño tomada años antes de que se anuncie cualquiera de las cifras destacadas de hoy. También sugiere por qué los documentos judiciales de FTX siguen resaltando porcentajes de recuperación superiores al 100%, un marco que se lee generoso frente a los precios de 2022 pero cuenta una historia distinta al medirse frente a lo que esas mismas monedas valen hoy.</p>
<p class="de">Der Kontrast erinnert daran, dass „Gläubiger-Recovery" bei Krypto-Insolvenzen kein einheitliches Konzept ist — es hängt vollständig davon ab, ob ein Plan im zugrunde liegenden Asset oder in Bargeld zahlt, das an einen historischen Preis gekoppelt ist, eine Designentscheidung, die Jahre getroffen wird, bevor irgendeine der heutigen Schlagzeilenzahlen verkündet wird. Es legt auch nahe, warum FTX' Gerichtsunterlagen immer wieder Rückzahlungsquoten über 100 % betonen — eine Darstellung, die gemessen an Preisen von 2022 großzügig wirkt, aber eine andere Geschichte erzählt, sobald man sie daran misst, was dieselben Coins heute tatsächlich wert sind.</p>
<p class="fr">Ce contraste rappelle que le « recouvrement des créanciers » dans les faillites crypto n'est pas un concept unique et standardisé — cela dépend entièrement de savoir si un plan paie dans l'actif sous-jacent ou en espèces indexées sur un prix historique, un choix de conception fait des années avant que l'un des chiffres phares d'aujourd'hui ne soit annoncé. Cela suggère aussi pourquoi les documents judiciaires de FTX continuent de mettre en avant des taux de recouvrement supérieurs à 100 %, un cadrage qui paraît généreux au regard des prix de 2022 mais raconte une tout autre histoire une fois mesuré par rapport à ce que valent réellement ces mêmes pièces aujourd'hui.</p>
<p class="pt">O contraste é um lembrete de que a "recuperação de credores" em falências cripto não é um conceito único e padronizado — depende inteiramente de o plano pagar no ativo subjacente ou em dinheiro atrelado a um preço histórico, uma escolha de design feita anos antes de qualquer um dos números de destaque de hoje serem anunciados. Isso também sugere por que os documentos judiciais da FTX continuam enfatizando percentuais de recuperação acima de 100%, um enquadramento que parece generoso frente aos preços de 2022, mas conta uma história diferente quando medido pelo que essas mesmas moedas valem hoje.</p>
<p class="tr">Bu karşıtlık, kripto iflaslarında "alacaklı geri kazanımının" tek, standartlaştırılmış bir kavram olmadığının bir hatırlatıcısıdır — bu tamamen bir planın dayanak varlıkta mı yoksa tarihsel bir fiyata sabitlenmiş nakitte mi ödeme yaptığına bağlıdır; bu, bugünün manşet rakamlarından yıllar önce yapılan bir tasarım tercihidir. Bu aynı zamanda FTX'in mahkeme dosyalarının neden %100'ün üzerindeki geri kazanım oranlarını vurgulamaya devam ettiğini de açıklıyor — 2022 fiyatlarına göre cömert okunan bir çerçeveleme, ama aynı coinlerin bugün gerçekte ne kadar değerli olduğuna göre ölçüldüğünde bambaşka bir hikâye anlatıyor.</p>
<p class="vi">Sự tương phản này là lời nhắc nhở rằng "thu hồi cho chủ nợ" trong các vụ phá sản tiền mã hóa không phải là một khái niệm chuẩn hóa duy nhất — nó hoàn toàn phụ thuộc vào việc một kế hoạch trả bằng tài sản cơ sở hay bằng tiền mặt neo theo một mức giá lịch sử, một lựa chọn thiết kế được đưa ra nhiều năm trước khi bất kỳ con số nổi bật nào của ngày hôm nay được công bố. Điều này cũng gợi ý lý do vì sao các hồ sơ tòa án của FTX tiếp tục nhấn mạnh tỷ lệ thu hồi trên 100% — một cách trình bày có vẻ hào phóng khi so với giá năm 2022 nhưng lại kể một câu chuyện khác khi đo theo giá trị thực tế của chính những đồng coin đó ngày hôm nay.</p>

<div class="ko">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">FTX 배분·준비금 타임라인 (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">파산 신청부터 다섯 번째 배분까지</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — 파산 신청, BTC $17,036에 청구권 고정</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 1차 배분 약 $12억 (편의클래스, 120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 3차 배분 약 $16억</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — 준비금 $46억→$24억 삭감</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — 5차 배분 기준일 확정</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 5차 배분, 준비금 $24억→$18억,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">누적 $100억+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">모든 청구권은 2022년11월 파산신청일 비트코인 가격에</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">고정돼 현금으로만 지급된다 — 이후의 가격 상승분은</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">채권자가 아니라 준비금 반환분에만 반영된다.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">수치는 각 매체 보도 기준 근사치. 출처: PR뉴스와이어, 크립토브리핑</text>
</svg>
</div>
<div class="en">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">FTX Distribution &amp; Reserve Timeline (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">From bankruptcy filing to the fifth payout round</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — Chapter 11 filed, claims locked at BTC $17,036</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 1st payout ~$1.2B (Convenience Class, 120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 3rd payout ~$1.6B</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — Reserve cut $4.6B→$2.4B</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — 5th round record date set</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 5th payout, reserve $2.4B→$1.8B,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">cumulative $10B+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">Every claim stays fixed to bitcoin's November 2022</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">petition-date price, paid entirely in cash — later price</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">gains show up in reserve givebacks, not in creditor payouts.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">Figures are approximate per each outlet. Source: PR Newswire, CryptoBriefing</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">FTX 配当・準備金タイムライン(2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">破産申請から第5回配当まで</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — チャプター11申請、BTC $17,036で請求権固定</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 第1回配当 約12億ドル(コンビニエンス・クラス、120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 第3回配当 約16億ドル</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — 準備金46億→24億ドルに削減</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — 第5回配当基準日確定</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 第5回配当、準備金24億→18億ドル、</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">累積100億ドル超</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">すべての請求権は2022年11月の破産申請日の</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">ビットコイン価格に固定され全額現金で支払われる——</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">その後の値上がり分は準備金の払い戻しに反映されるだけだ。</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">数値は各媒体報道の近似値。出典: PRニュースワイヤー、クリプトブリーフィング</text>
</svg>
</div>
<div class="es">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Cronología de Distribución y Reserva de FTX (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Desde la quiebra hasta la quinta ronda de pago</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — Cap. 11, reclamos fijados a BTC $17.036</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 1ª ronda ~$1.200M (Clase Conveniencia, 120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 3ª ronda ~$1.600M</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — Reserva $4.600M→$2.400M</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — Fecha de registro de 5ª ronda</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 5ª ronda, reserva $2.400M→$1.800M,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">acumulado $10.000M+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">Cada reclamo permanece fijado al precio del bitcoin</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">en la fecha de petición de noviembre de 2022, pagado en</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">efectivo — las ganancias posteriores solo reducen la reserva.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">Cifras aproximadas según cada medio. Fuente: PR Newswire, CryptoBriefing</text>
</svg>
</div>
<div class="de">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">FTX Ausschüttungs- und Rückstellungs-Zeitleiste (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Vom Insolvenzantrag bis zur fünften Auszahlungsrunde</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — Chapter 11, Forderungen fixiert bei BTC $17.036</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 1. Runde ~$1,2 Mrd. (Convenience Class, 120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 3. Runde ~$1,6 Mrd.</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — Rückstellung $4,6 Mrd.→$2,4 Mrd.</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — Stichtag 5. Runde festgelegt</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 5. Runde, Rückstellung $2,4 Mrd.→$1,8 Mrd.,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">kumuliert $10 Mrd.+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">Jede Forderung bleibt am Bitcoin-Preis vom Antragsstichtag</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">November 2022 fixiert, vollständig bar ausgezahlt — spätere</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">Kursgewinne zeigen sich nur in Rückstellungskürzungen.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">Zahlen sind Näherungswerte je nach Medium. Quelle: PR Newswire, CryptoBriefing</text>
</svg>
</div>
<div class="fr">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Chronologie des Distributions et Réserves de FTX (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">De la faillite au cinquième cycle de paiement</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — Chapitre 11, créances fixées à BTC $17 036</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 1er cycle ~1,2 Md$ (Convenience Class, 120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 3e cycle ~1,6 Md$</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — Réserve 4,6 Md$→2,4 Md$</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — Date de référence du 5e cycle</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 5e cycle, réserve 2,4 Md$→1,8 Md$,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">cumul 10 Md$+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">Chaque créance reste fixée au prix du bitcoin à la date</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">de la pétition de novembre 2022, payée en espèces — les</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">gains ultérieurs ne réduisent que la réserve, pas les créances.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">Chiffres approximatifs selon chaque média. Source : PR Newswire, CryptoBriefing</text>
</svg>
</div>
<div class="pt">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Linha do Tempo de Distribuição e Reserva da FTX (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Da falência até a quinta rodada de pagamento</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — Cap. 11, reclamações fixadas em BTC $17.036</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 1ª rodada ~US$1,2 bi (Convenience Class, 120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 3ª rodada ~US$1,6 bi</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — Reserva US$4,6 bi→US$2,4 bi</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — Data-base da 5ª rodada definida</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 5ª rodada, reserva US$2,4 bi→US$1,8 bi,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">acumulado US$10 bi+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">Toda reclamação permanece fixada ao preço do bitcoin</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">na data do pedido de novembro de 2022, paga em dinheiro —</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">ganhos posteriores só aparecem nos cortes de reserva.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">Números aproximados conforme cada veículo. Fonte: PR Newswire, CryptoBriefing</text>
</svg>
</div>
<div class="tr">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">FTX Dağıtım ve Rezerv Zaman Çizelgesi (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">İflas başvurusundan beşinci ödeme turuna</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — Chapter 11, alacaklar BTC $17.036'da sabitlendi</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — 1. tur ~1,2 milyar$ (Convenience Class, %120)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — 3. tur ~1,6 milyar$</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — Rezerv 4,6 milyar$→2,4 milyar$</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — 5. tur kayıt tarihi belirlendi</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — 5. tur, rezerv 2,4 milyar$→1,8 milyar$,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">toplam 10 milyar$+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">Her alacak Kasım 2022 başvuru tarihi bitcoin fiyatına</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">sabitlenmiş şekilde tamamen nakit ödenir — sonraki fiyat</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">artışları yalnızca rezerv kesintilerine yansır.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">Rakamlar kaynağa göre yaklaşık değerlerdir. Kaynak: PR Newswire, CryptoBriefing</text>
</svg>
</div>
<div class="vi">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Dòng Thời Gian Phân Phối &amp; Quỹ Dự Phòng FTX (2022–2026)</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Từ khi nộp đơn phá sản đến đợt chi trả thứ năm</text>
  <rect x="20" y="70" width="660" height="40" rx="6" fill="#27272a"/>
  <text x="34" y="95" fill="#d4d4d8" font-family="sans-serif" font-size="14" font-weight="700">2022.11.11 — Nộp Chương 11, yêu cầu cố định ở BTC $17.036</text>
  <rect x="20" y="114" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="139" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.02 — Đợt 1 ~1,2 tỷ$ (Convenience Class, 120%)</text>
  <rect x="20" y="158" width="660" height="40" rx="6" fill="#1e3a5f"/>
  <text x="34" y="183" fill="#bfdbfe" font-family="sans-serif" font-size="14" font-weight="700">2025.09 — Đợt 3 ~1,6 tỷ$</text>
  <rect x="20" y="202" width="660" height="40" rx="6" fill="#164e63"/>
  <text x="34" y="227" fill="#a5f3fc" font-family="sans-serif" font-size="14" font-weight="700">2026.01 — Quỹ dự phòng $4,6 tỷ→$2,4 tỷ</text>
  <rect x="20" y="246" width="660" height="40" rx="6" fill="#3f2d54"/>
  <text x="34" y="271" fill="#e9d5ff" font-family="sans-serif" font-size="14" font-weight="700">2026.06.16 — Chốt ngày đợt 5</text>
  <rect x="20" y="290" width="660" height="52" rx="6" fill="#422006"/>
  <text x="34" y="313" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">2026.07.31 — Đợt 5, quỹ dự phòng $2,4 tỷ→$1,8 tỷ,</text>
  <text x="34" y="333" fill="#fde68a" font-family="sans-serif" font-size="14" font-weight="700">lũy kế $10 tỷ+</text>
  <line x1="20" y1="368" x2="680" y2="368" stroke="#3f3f46"/>
  <text x="20" y="392" fill="#a1a1aa" font-family="sans-serif" font-size="13">Mọi khoản yêu cầu vẫn cố định theo giá bitcoin tại ngày</text>
  <text x="20" y="412" fill="#a1a1aa" font-family="sans-serif" font-size="13">nộp đơn tháng 11/2022, trả toàn bộ bằng tiền mặt — mức</text>
  <text x="20" y="432" fill="#a1a1aa" font-family="sans-serif" font-size="13">tăng giá sau đó chỉ thể hiện ở phần cắt giảm quỹ dự phòng.</text>
  <text x="20" y="450" fill="#52525b" font-family="sans-serif" font-size="12">Số liệu gần đúng theo từng nguồn. Nguồn: PR Newswire, CryptoBriefing</text>
</svg>
</div>

<h2 class="ko">다음에 지켜볼 것</h2>
<h2 class="en">What to Watch Next</h2>
<h2 class="ja">次に注視すべきこと</h2>
<h2 class="es">Qué Observar a Continuación</h2>
<h2 class="de">Worauf als Nächstes zu Achten Ist</h2>
<h2 class="fr">Ce Qu'il Faut Surveiller Ensuite</h2>
<h2 class="pt">O Que Observar a Seguir</h2>
<h2 class="tr">Sırada İzlenecekler</h2>
<h2 class="vi">Điều Cần Theo Dõi Tiếp Theo</h2>

<p class="ko">당장의 관전 포인트는 델라웨어 법원이 7월31일 전에 18억달러 준비금 액수를 승인할지, 그리고 이번 라운드가 실제로 예정대로 지급되는지다 — FTX의 이전 라운드들은 대체로 발표된 일정을 지켜왔지만, 매번 아직 등록을 마치지 않은, 점점 줄어드는 청구권자 풀을 상대로 막판 KYC 절차가 필요했다. 그 다음으로는, 언제가 됐든 다음 준비금 삭감의 규모가 트러스트가 남은 가장 큰 분쟁들 — 경쟁 파산재단의 청구권과, 일반 고객에게 돌아갈 전체 재원 풀을 여전히 줄이거나 늘일 수 있는 부인권(clawback) 소송을 포함해서 — 을 얼마나 빨리 해소하고 있는지를 보여줄 것이다.</p>
<p class="en">The immediate marker is whether the Delaware court approves the $1.8 billion reserve figure before July 31 and whether the round actually disburses on schedule — FTX's prior rounds have generally hit their announced dates, but each has required last-minute KYC compliance from a shrinking pool of still-unregistered claimants. Beyond that, the size of the next reserve cut, whenever it comes, will show how quickly the trust is resolving its largest remaining disputes, which include claims from rival estates and clawback litigation that could still shrink or grow the total pool available to ordinary customers.</p>
<p class="ja">当面の焦点は、デラウェア裁判所が7月31日までに18億ドルの準備金額を承認するかどうか、そしてこのラウンドが実際に予定通り支払われるかどうかだ——FTXの過去のラウンドは概ね発表された日程を守ってきたが、そのたびに、まだ登録を終えていない、縮小し続ける請求権者プールを相手にした土壇場でのKYC対応が必要だった。その先では、いつになるにせよ次の準備金削減の規模が、トラストが残る最大の争い——ライバル破産財団からの請求権や、一般顧客に届く財源プール全体を依然として縮小・拡大しうる否認権(クローバック)訴訟を含む——をどれだけ早く解決しているかを示すことになる。</p>
<p class="es">El indicador inmediato es si el tribunal de Delaware aprueba la cifra de reserva de 1.800 millones de dólares antes del 31 de julio y si la ronda realmente se desembolsa según lo programado —las rondas anteriores de FTX generalmente han cumplido sus fechas anunciadas, pero cada una ha requerido cumplimiento de KYC de último momento de un grupo cada vez más reducido de reclamantes aún no registrados. Más allá de eso, el tamaño del próximo recorte de reserva, cuando llegue, mostrará qué tan rápido está resolviendo el fondo sus mayores disputas restantes, que incluyen reclamos de patrimonios rivales y litigios de recuperación (clawback) que aún podrían reducir o aumentar el fondo total disponible para los clientes comunes.</p>
<p class="de">Der unmittelbare Indikator ist, ob das Gericht in Delaware die Rückstellungssumme von 1,8 Milliarden Dollar vor dem 31. Juli genehmigt und ob die Runde tatsächlich planmäßig ausgezahlt wird — FTX' frühere Runden haben ihre angekündigten Termine im Allgemeinen eingehalten, aber jede erforderte in letzter Minute KYC-Compliance von einem schrumpfenden Pool noch nicht registrierter Anspruchsteller. Darüber hinaus wird die Größe der nächsten Rückstellungskürzung, wann immer sie kommt, zeigen, wie schnell der Trust seine größten verbleibenden Streitfälle löst — darunter Forderungen konkurrierender Insolvenzverwalter und Rückforderungsklagen (Clawback), die den gesamten für normale Kunden verfügbaren Mittelpool noch schrumpfen oder wachsen lassen könnten.</p>
<p class="fr">L'indicateur immédiat est de savoir si le tribunal du Delaware approuve le montant de réserve de 1,8 milliard de dollars avant le 31 juillet et si le cycle est effectivement décaissé comme prévu — les cycles précédents de FTX ont généralement respecté les dates annoncées, mais chacun a nécessité une mise en conformité KYC de dernière minute de la part d'un bassin toujours plus restreint de créanciers encore non enregistrés. Au-delà, la taille de la prochaine réduction de réserve, quand elle arrivera, montrera à quelle vitesse le fonds résout ses plus grands litiges restants, notamment les créances de patrimoines concurrents et les litiges en récupération (clawback) qui pourraient encore réduire ou augmenter le total du bassin disponible pour les clients ordinaires.</p>
<p class="pt">O marcador imediato é se o tribunal de Delaware aprova o valor de reserva de US$ 1,8 bilhão antes de 31 de julho e se a rodada realmente é desembolsada conforme programado — as rodadas anteriores da FTX geralmente cumpriram as datas anunciadas, mas cada uma exigiu conformidade KYC de última hora de um grupo cada vez menor de reclamantes ainda não registrados. Além disso, o tamanho do próximo corte de reserva, sempre que ocorrer, mostrará com que rapidez o fundo está resolvendo suas maiores disputas remanescentes, que incluem reclamações de massas falidas rivais e litígios de recuperação (clawback) que ainda podem encolher ou aumentar o total do pool disponível para clientes comuns.</p>
<p class="tr">Anlık gösterge, Delaware mahkemesinin 31 Temmuz'dan önce 1,8 milyar dolarlık rezerv rakamını onaylayıp onaylamayacağı ve turun gerçekten programa uygun şekilde dağıtılıp dağıtılmayacağıdır — FTX'in önceki turları genellikle ilan edilen tarihlere uymuştur, ancak her biri hâlâ kayıt olmamış, giderek küçülen bir alacaklı havuzundan son dakika KYC uyumu gerektirmiştir. Bunun ötesinde, ne zaman gelirse gelsin bir sonraki rezerv kesintisinin büyüklüğü, fonun — rakip tasfiye kütlelerinden gelen alacaklar ve sıradan müşterilere ulaşacak toplam havuzu hâlâ küçültebilecek veya büyütebilecek geri alım (clawback) davaları da dahil olmak üzere — kalan en büyük anlaşmazlıklarını ne kadar hızlı çözdüğünü gösterecektir.</p>
<p class="vi">Dấu hiệu trước mắt là liệu tòa án Delaware có phê duyệt con số quỹ dự phòng 1,8 tỷ đô la trước ngày 31 tháng 7 hay không, và liệu đợt phân phối này có thực sự được giải ngân đúng lịch trình hay không — các đợt trước của FTX nhìn chung đã đúng theo ngày đã công bố, nhưng mỗi đợt đều cần sự tuân thủ KYC vào phút chót từ một nhóm người yêu cầu bồi thường ngày càng thu hẹp vẫn chưa đăng ký. Xa hơn nữa, quy mô của đợt cắt giảm quỹ dự phòng tiếp theo, bất kể khi nào nó đến, sẽ cho thấy quỹ đang giải quyết nhanh đến mức nào các tranh chấp lớn còn lại của mình, bao gồm các khoản yêu cầu từ các khối tài sản phá sản đối thủ và các vụ kiện đòi lại (clawback) vẫn có thể làm co lại hoặc mở rộng tổng quỹ dành cho khách hàng thông thường.</p>

<p class="ko">더 길게 보면, FTX의 파산신청일 평가 다툼은 다음 암호화폐 거래소 붕괴가 어떻게 정리될지의 방향을 만들고 있다 — 앞으로 파산을 신청하는 모든 기업과 모든 파산판사에게는, 좋든 나쁘든 이제 완전히 소송을 거친 선례가 하나 생긴 셈이다. 이 선례가 업계의 기본값이 될지, 아니면 미래의 어떤 사건이 대신 므트곡스식 현물 지급 모델을 따를지는, FTX에 아직 돈을 받아야 할 사람보다 다음 세대의 거래소 고객들에게 더 중요한 문제가 될 것이다.</p>
<p class="en">Longer term, FTX's petition-date valuation fight is shaping how the next crypto-exchange collapse gets unwound — every future filer and every future bankruptcy judge now has a fully litigated precedent to point to, for better or worse. Whether that precedent becomes the industry default, or whether a future case follows Mt. Gox's in-kind model instead, will matter more to the next generation of exchange customers than to anyone still owed money by FTX.</p>
<p class="ja">より長い目で見れば、FTXの破産申請日評価をめぐる争いは、次の暗号資産取引所の破綻がどう清算されるかの方向性を形作りつつある——今後破産を申請するすべての企業と、すべての破産判事にとって、良くも悪くも、完全に訴訟を経た先例がひとつ存在することになる。この先例が業界の既定路線になるのか、それとも将来のどこかの案件がマウントゴックス式の現物支払いモデルに従うのかは、FTXからまだ支払いを受けていない人々よりも、次世代の取引所顧客にとってより重要な問題になるだろう。</p>
<p class="es">A más largo plazo, la disputa de FTX sobre la valoración a la fecha de petición está moldeando cómo se liquidará el próximo colapso de un exchange cripto —cada futuro solicitante y cada futuro juez de quiebras tiene ahora un precedente totalmente litigado al que recurrir, para bien o para mal. Si ese precedente se convierte en el estándar de la industria, o si un caso futuro sigue en cambio el modelo en especie de Mt. Gox, importará más a la próxima generación de clientes de exchanges que a cualquiera a quien FTX todavía le deba dinero.</p>
<p class="de">Langfristig prägt FTX' Streit um die Bewertung zum Antragsstichtag, wie der nächste Zusammenbruch einer Krypto-Börse abgewickelt wird — jeder künftige Antragsteller und jeder künftige Insolvenzrichter hat nun einen vollständig gerichtlich geprüften Präzedenzfall, auf den er sich berufen kann, im Guten wie im Schlechten. Ob dieser Präzedenzfall zum Branchenstandard wird oder ob ein künftiger Fall stattdessen Mt. Gox' Sachleistungsmodell folgt, wird für die nächste Generation von Börsenkunden wichtiger sein als für alle, denen FTX noch Geld schuldet.</p>
<p class="fr">À plus long terme, la bataille de FTX sur l'évaluation à la date de la pétition façonne la manière dont le prochain effondrement d'une plateforme crypto sera liquidé — chaque futur débiteur et chaque futur juge des faillites dispose désormais d'un précédent entièrement plaidé auquel se référer, pour le meilleur ou pour le pire. Que ce précédent devienne la norme du secteur, ou qu'une future affaire suive plutôt le modèle en nature de Mt. Gox, comptera davantage pour la prochaine génération de clients de plateformes que pour quiconque à qui FTX doit encore de l'argent.</p>
<p class="pt">No longo prazo, a disputa da FTX sobre a avaliação na data do pedido está moldando como o próximo colapso de uma corretora cripto será liquidado — todo futuro requerente e todo futuro juiz de falências agora tem um precedente totalmente litigado ao qual recorrer, para o bem ou para o mal. Se esse precedente se tornará o padrão da indústria, ou se um caso futuro seguirá em vez disso o modelo in natura da Mt. Gox, importará mais para a próxima geração de clientes de corretoras do que para quem ainda tem dinheiro a receber da FTX.</p>
<p class="tr">Daha uzun vadede, FTX'in başvuru tarihi değerlemesi üzerindeki mücadelesi, bir sonraki kripto borsası çöküşünün nasıl tasfiye edileceğini şekillendiriyor — bundan sonra başvuruda bulunacak her şirket ve her iflas hakimi artık, iyi ya da kötü, başvurabileceği tamamen dava edilmiş bir emsale sahip. Bu emsalin sektörün varsayılanı haline gelip gelmeyeceği, ya da gelecekteki bir davanın bunun yerine Mt. Gox'un ayni ödeme modelini izleyip izlemeyeceği, FTX'ten hâlâ para alacaklı olanlardan çok, bir sonraki nesil borsa müşterileri için daha önemli olacak.</p>
<p class="vi">Về lâu dài, cuộc chiến của FTX về định giá theo ngày nộp đơn đang định hình cách mà sự sụp đổ tiếp theo của một sàn giao dịch tiền mã hóa sẽ được giải quyết — mọi bên nộp đơn phá sản trong tương lai và mọi thẩm phán phá sản trong tương lai giờ đây đều có một tiền lệ đã được tranh tụng đầy đủ để tham chiếu, dù tốt hay xấu. Việc tiền lệ này có trở thành chuẩn mực của ngành hay không, hay liệu một vụ việc trong tương lai có thay vào đó đi theo mô hình trả bằng hiện vật của Mt. Gox hay không, sẽ quan trọng hơn đối với thế hệ khách hàng sàn giao dịch tiếp theo hơn là đối với bất kỳ ai vẫn còn được FTX nợ tiền.</p>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: PR뉴스와이어(PR Newswire, "FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction"), 크립토브리핑(CryptoBriefing, "FTX recovery trust targets July 31 for next round of creditor payments"), 로이터(Reuters) via 트레이딩뷰(TradingView), 코인페이퍼(CoinPaper), 비트코인월드(BitcoinWorld), 코인가바(CoinGabbar), 코인텔레그래프(Cointelegraph, "FTX debtors assess value of crypto assets based on petition date market prices"), 코인데스크(CoinDesk, "Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears"), 뉴스BTC(NewsBTC), 야후파이낸스(Yahoo Finance, "Mt. Gox Pushes Back Bitcoin Repayments to October 2026"). 수치는 각 매체 보도 기준 근사치이며 보도 시점에 따라 달라질 수 있다.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: PR Newswire ("FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction"), CryptoBriefing ("FTX recovery trust targets July 31 for next round of creditor payments"), Reuters via TradingView, CoinPaper, BitcoinWorld, CoinGabbar, Cointelegraph ("FTX debtors assess value of crypto assets based on petition date market prices"), CoinDesk ("Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears"), NewsBTC, Yahoo Finance ("Mt. Gox Pushes Back Bitcoin Repayments to October 2026"). Figures are approximate per each outlet and may vary by reporting time.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: PRニュースワイヤー(PR Newswire、「FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction」)、クリプトブリーフィング(CryptoBriefing、「FTX recovery trust targets July 31 for next round of creditor payments」)、ロイター(Reuters) via トレーディングビュー(TradingView)、コインペーパー(CoinPaper)、ビットコインワールド(BitcoinWorld)、コインガバー(CoinGabbar)、コインテレグラフ(Cointelegraph、「FTX debtors assess value of crypto assets based on petition date market prices」)、コインデスク(CoinDesk、「Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears」)、ニュースBTC(NewsBTC)、ヤフーファイナンス(Yahoo Finance、「Mt. Gox Pushes Back Bitcoin Repayments to October 2026」)。数値は各媒体報道時点の近似値であり、報道時期により変動し得る。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: PR Newswire ("FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction"), CryptoBriefing ("FTX recovery trust targets July 31 for next round of creditor payments"), Reuters vía TradingView, CoinPaper, BitcoinWorld, CoinGabbar, Cointelegraph ("FTX debtors assess value of crypto assets based on petition date market prices"), CoinDesk ("Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears"), NewsBTC, Yahoo Finance ("Mt. Gox Pushes Back Bitcoin Repayments to October 2026"). Las cifras son aproximadas según cada medio y pueden variar según el momento del reporte.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: PR Newswire („FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction"), CryptoBriefing („FTX recovery trust targets July 31 for next round of creditor payments"), Reuters via TradingView, CoinPaper, BitcoinWorld, CoinGabbar, Cointelegraph („FTX debtors assess value of crypto assets based on petition date market prices"), CoinDesk („Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears"), NewsBTC, Yahoo Finance („Mt. Gox Pushes Back Bitcoin Repayments to October 2026"). Zahlen sind Näherungswerte je nach Medium und können je nach Berichtszeitpunkt variieren.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : PR Newswire (« FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction »), CryptoBriefing (« FTX recovery trust targets July 31 for next round of creditor payments »), Reuters via TradingView, CoinPaper, BitcoinWorld, CoinGabbar, Cointelegraph (« FTX debtors assess value of crypto assets based on petition date market prices »), CoinDesk (« Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears »), NewsBTC, Yahoo Finance (« Mt. Gox Pushes Back Bitcoin Repayments to October 2026 »). Les chiffres sont approximatifs selon chaque média et peuvent varier selon le moment du reportage.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: PR Newswire ("FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction"), CryptoBriefing ("FTX recovery trust targets July 31 for next round of creditor payments"), Reuters via TradingView, CoinPaper, BitcoinWorld, CoinGabbar, Cointelegraph ("FTX debtors assess value of crypto assets based on petition date market prices"), CoinDesk ("Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears"), NewsBTC, Yahoo Finance ("Mt. Gox Pushes Back Bitcoin Repayments to October 2026"). Os números são aproximados conforme cada veículo e podem variar conforme o momento da reportagem.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: PR Newswire ("FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction"), CryptoBriefing ("FTX recovery trust targets July 31 for next round of creditor payments"), TradingView üzerinden Reuters, CoinPaper, BitcoinWorld, CoinGabbar, Cointelegraph ("FTX debtors assess value of crypto assets based on petition date market prices"), CoinDesk ("Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears"), NewsBTC, Yahoo Finance ("Mt. Gox Pushes Back Bitcoin Repayments to October 2026"). Rakamlar her kaynağa göre yaklaşık değerlerdir ve haber zamanına göre değişebilir.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: PR Newswire ("FTX Sets Next Distribution Date and Amends Proposed Disputed Claims Reserve Reduction"), CryptoBriefing ("FTX recovery trust targets July 31 for next round of creditor payments"), Reuters qua TradingView, CoinPaper, BitcoinWorld, CoinGabbar, Cointelegraph ("FTX debtors assess value of crypto assets based on petition date market prices"), CoinDesk ("Mt. Gox moves 10,422 bitcoin worth $739 million to a new wallet as deadline nears"), NewsBTC, Yahoo Finance ("Mt. Gox Pushes Back Bitcoin Repayments to October 2026"). Các số liệu là giá trị gần đúng theo từng nguồn và có thể thay đổi tùy thời điểm đưa tin.</p>
<?php require __DIR__.'/_footer.php'; ?>
