<?php $slug = 'funding-rate-turns-positive-exchange-outflow-gap'; require __DIR__.'/_header.php'; ?>

<p class="ko">비트코인은 7월 1일 저점 $57,950에서 반등한 뒤 지금은 $63,180 부근에서 거래되고 있다. 24시간 기준으로는 +0.48%로 사실상 제자리걸음이고, 72시간 전인 7월 3일의 $61,920과 비교해도 +2.03%에 그친다. 가격이 조용한 사이 조용히 방향을 바꾼 지표가 하나 있다 — 무기한선물 펀딩비다. 코인글래스 집계 기준 바이낸스·OKX·바이빗 가중평균 펀딩비(8시간)는 6월 25일 이후 줄곧 0.005~0.015% 사이의 중립 구간에 머물러 있었는데, 지금은 0.056%까지 올라와 11일 만에 처음으로 0.05%를 넘어섰다.</p>
  <p class="en">Bitcoin bounced off its July 1 low of $57,950 and is now trading around $63,180 — essentially flat, up just 0.48% on the day and only 2.03% above the $61,920 it printed 72 hours ago on July 3. While price has gone quiet, one indicator just moved: the perpetual funding rate. Per CoinGlass, the volume-weighted 8-hour funding rate across Binance, OKX, and Bybit had sat in a neutral 0.005%–0.015% band since June 25 — until now. It just climbed to 0.056%, clearing 0.05% for the first time in 11 days.</p>
  <p class="ja">ビットコインは7月1日の安値5万7,950ドルから反発し、現在は6万3,180ドル前後で取引されている。24時間ベースでは+0.48%とほぼ横ばいで、72時間前の7月3日の6万1,920ドルと比べても+2.03%にとどまる。価格が静かな間に、静かに方向を変えた指標が一つある — 無期限先物のファンディングレートだ。コインググラス集計によるバイナンス・OKX・バイビットの加重平均ファンディングレート(8時間)は6月25日以降ずっと0.005~0.015%の中立圏にとどまっていたが、今は0.056%まで上昇し、11日ぶりに0.05%を突破した。</p>
  <p class="es">Bitcoin rebotó desde su mínimo del 1 de julio de $57,950 y ahora cotiza en torno a los $63,180 — prácticamente plano, apenas +0.48% en el día y solo un 2.03% por encima de los $61,920 que marcó hace 72 horas, el 3 de julio. Mientras el precio guarda silencio, un indicador acaba de moverse: la tasa de financiación de los perpetuos. Según CoinGlass, la tasa de financiación promedio ponderada a 8 horas en Binance, OKX y Bybit se había mantenido en una banda neutral de 0.005%–0.015% desde el 25 de junio — hasta ahora. Acaba de subir a 0.056%, superando el 0.05% por primera vez en 11 días.</p>
  <p class="de">Bitcoin erholte sich von seinem Tief vom 1. Juli bei 57.950 $ und notiert jetzt bei rund 63.180 $ — praktisch unverändert, nur +0,48% auf Tagesbasis und lediglich 2,03% über den 61.920 $, die vor 72 Stunden am 3. Juli erreicht wurden. Während der Preis stillsteht, hat sich ein Indikator gerade bewegt — die Funding Rate der Perpetuals. Laut CoinGlass lag die volumengewichtete 8-Stunden-Funding-Rate über Binance, OKX und Bybit seit dem 25. Juni in einer neutralen Bandbreite von 0,005–0,015% — bis jetzt. Sie kletterte auf 0,056% und überschritt damit erstmals seit 11 Tagen die Marke von 0,05%.</p>
  <p class="fr">Bitcoin a rebondi après son creux du 1er juillet à 57 950 $ et se négocie désormais autour de 63 180 $ — pratiquement stable, en hausse de seulement 0,48% sur la journée et de seulement 2,03% au-dessus des 61 920 $ atteints il y a 72 heures, le 3 juillet. Alors que le prix est resté silencieux, un indicateur vient de bouger : le taux de financement des perpétuels. Selon CoinGlass, le taux de financement moyen pondéré sur 8 heures sur Binance, OKX et Bybit se situait dans une bande neutre de 0,005%–0,015% depuis le 25 juin — jusqu'à présent. Il vient de grimper à 0,056%, dépassant 0,05% pour la première fois en 11 jours.</p>
  <p class="pt">O Bitcoin recuou de sua mínima de 1º de julho, em $57.950, e agora é negociado perto de $63.180 — praticamente estável, com alta de apenas 0,48% no dia e apenas 2,03% acima dos $61.920 registrados há 72 horas, em 3 de julho. Enquanto o preço permanece silencioso, um indicador acabou de se mover: a taxa de financiamento dos perpétuos. Segundo a CoinGlass, a taxa de financiamento média ponderada de 8 horas em Binance, OKX e Bybit permanecia em uma faixa neutra de 0,005%–0,015% desde 25 de junho — até agora. Ela acabou de subir para 0,056%, superando 0,05% pela primeira vez em 11 dias.</p>
  <p class="tr">Bitcoin, 1 Temmuz'daki 57.950 dolarlık dip seviyesinden toparlanarak şu anda 63.180 dolar civarında işlem görüyor — günlük bazda yalnızca %0,48 artışla ve 72 saat önce, 3 Temmuz'da görülen 61.920 doların yalnızca %2,03 üzerinde, esasen yatay bir seyir. Fiyat sessizleşirken bir gösterge hareket etti: sürekli vadeli işlem fonlama oranı. CoinGlass verilerine göre Binance, OKX ve Bybit'teki hacim ağırlıklı 8 saatlik fonlama oranı, 25 Haziran'dan bu yana %0,005–%0,015 aralığında nötr seyrediyordu — şimdiye kadar. Oran şimdi %0,056'ya yükselerek 11 gün sonra ilk kez %0,05 seviyesini aştı.</p>
  <p class="vi">Bitcoin đã bật lên từ mức đáy 57.950 USD ngày 1 tháng 7 và hiện đang giao dịch quanh mức 63.180 USD — về cơ bản đi ngang, chỉ tăng 0,48% trong ngày và chỉ cao hơn 2,03% so với mức 61.920 USD ghi nhận cách đây 72 giờ vào ngày 3 tháng 7. Trong khi giá im ắng, một chỉ báo vừa dịch chuyển: tỷ lệ tài trợ (funding rate) của hợp đồng vĩnh viễn. Theo CoinGlass, tỷ lệ tài trợ 8 giờ theo trọng số khối lượng trên Binance, OKX và Bybit đã nằm trong vùng trung lập 0,005%–0,015% kể từ ngày 25 tháng 6 — cho đến bây giờ. Tỷ lệ này vừa tăng lên 0,056%, vượt mốc 0,05% lần đầu tiên sau 11 ngày.</p>

  <div class="ko">
  <svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">비트코인 무기한선물 펀딩비(8H) — 11일 만의 이탈</text>
    <text x="20" y="46" fill="#fbbf24" font-size="11" font-weight="700" font-family="sans-serif">코인글래스 집계, 바이낸스·OKX·바이빗 가중평균</text>
    <line x1="45" y1="102" x2="655" y2="102" stroke="#3f3f46" stroke-width="1.3" stroke-dasharray="5,4"/>
    <text x="650" y="96" fill="#38bdf8" font-size="10" font-weight="700" text-anchor="end" font-family="sans-serif">0.05% 기준선</text>
    <rect x="90" y="232" width="110" height="20" rx="3" fill="#94a3b8"/>
    <text x="145" y="225" fill="#94a3b8" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.008%</text>
    <text x="145" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">6/25</text>
    <rect x="300" y="227" width="110" height="25" rx="3" fill="#94a3b8"/>
    <text x="355" y="220" fill="#94a3b8" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.010%</text>
    <text x="355" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">7/5 14시</text>
    <rect x="510" y="112" width="110" height="140" rx="3" fill="#fbbf24"/>
    <text x="565" y="105" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.056%</text>
    <text x="565" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">7/6 지금</text>
    <text x="640" y="288" fill="#52525b" font-size="9" text-anchor="end" font-family="sans-serif">출처: CoinGlass</text>
  </svg>
  </div>
  <div class="en es de fr pt tr vi">
  <svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">Bitcoin Perpetual Funding Rate (8H) — Breaking Out After 11 Days</text>
    <text x="20" y="46" fill="#fbbf24" font-size="11" font-weight="700" font-family="sans-serif">CoinGlass data, Binance+OKX+Bybit weighted average</text>
    <line x1="45" y1="102" x2="655" y2="102" stroke="#3f3f46" stroke-width="1.3" stroke-dasharray="5,4"/>
    <text x="650" y="96" fill="#38bdf8" font-size="10" font-weight="700" text-anchor="end" font-family="sans-serif">0.05% line</text>
    <rect x="90" y="232" width="110" height="20" rx="3" fill="#94a3b8"/>
    <text x="145" y="225" fill="#94a3b8" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.008%</text>
    <text x="145" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">Jun 25</text>
    <rect x="300" y="227" width="110" height="25" rx="3" fill="#94a3b8"/>
    <text x="355" y="220" fill="#94a3b8" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.010%</text>
    <text x="355" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">Jul 5, 14:00</text>
    <rect x="510" y="112" width="110" height="140" rx="3" fill="#fbbf24"/>
    <text x="565" y="105" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.056%</text>
    <text x="565" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">Jul 6, now</text>
    <text x="640" y="288" fill="#52525b" font-size="9" text-anchor="end" font-family="sans-serif">Source: CoinGlass</text>
  </svg>
  </div>
  <div class="ja">
  <svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">ビットコイン無期限先物ファンディングレート(8H) — 11日ぶりの離脱</text>
    <text x="20" y="46" fill="#fbbf24" font-size="11" font-weight="700" font-family="sans-serif">コインググラス集計、バイナンス・OKX・バイビット加重平均</text>
    <line x1="45" y1="102" x2="655" y2="102" stroke="#3f3f46" stroke-width="1.3" stroke-dasharray="5,4"/>
    <text x="650" y="96" fill="#38bdf8" font-size="10" font-weight="700" text-anchor="end" font-family="sans-serif">0.05%ライン</text>
    <rect x="90" y="232" width="110" height="20" rx="3" fill="#94a3b8"/>
    <text x="145" y="225" fill="#94a3b8" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.008%</text>
    <text x="145" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">6/25</text>
    <rect x="300" y="227" width="110" height="25" rx="3" fill="#94a3b8"/>
    <text x="355" y="220" fill="#94a3b8" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.010%</text>
    <text x="355" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">7/5 14時</text>
    <rect x="510" y="112" width="110" height="140" rx="3" fill="#fbbf24"/>
    <text x="565" y="105" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">0.056%</text>
    <text x="565" y="266" fill="#a1a1aa" font-size="10" text-anchor="middle" font-family="sans-serif">7/6 現在</text>
    <text x="640" y="288" fill="#52525b" font-size="9" text-anchor="end" font-family="sans-serif">出典: CoinGlass</text>
  </svg>
  </div>

  <div class="cc">
    <h3><span class="ko">📊 오늘의 지표 스냅샷</span><span class="en">📊 Today's Indicator Snapshot</span><span class="ja">📊 本日の指標スナップショット</span><span class="es">📊 Instantánea de Indicadores de Hoy</span><span class="de">📊 Heutige Indikatoren-Momentaufnahme</span><span class="fr">📊 Instantané des Indicateurs du Jour</span><span class="pt">📊 Instantâneo dos Indicadores de Hoje</span><span class="tr">📊 Bugünün Gösterge Anlık Görüntüsü</span><span class="vi">📊 Ảnh Chụp Nhanh Chỉ Báo Hôm Nay</span></h3>
    <div class="stats">
      <div class="si"><div class="sl"><span class="ko">펀딩비(8H)</span><span class="en">Funding Rate (8H)</span><span class="ja">ファンディングレート(8H)</span><span class="es">Tasa de Financiación (8H)</span><span class="de">Funding Rate (8H)</span><span class="fr">Taux de Financement (8H)</span><span class="pt">Taxa de Financiamento (8H)</span><span class="tr">Fonlama Oranı (8H)</span><span class="vi">Tỷ Lệ Tài Trợ (8H)</span></div><div class="sv">0.056%</div><div class="ss"><span class="ko">6/25 이후 첫 0.05% 돌파</span><span class="en">First break above 0.05% since Jun 25</span><span class="ja">6/25以来初の0.05%突破</span><span class="es">Primer quiebre sobre 0.05% desde el 25 jun</span><span class="de">Erster Ausbruch über 0,05% seit 25. Juni</span><span class="fr">Premier dépassement de 0,05% depuis le 25 juin</span><span class="pt">Primeira ruptura acima de 0,05% desde 25 de junho</span><span class="tr">25 Haziran'dan bu yana ilk kez %0,05 üzerine çıkış</span><span class="vi">Lần đầu vượt 0,05% kể từ 25/6</span></div></div>
      <div class="si"><div class="sl"><span class="ko">거래소 순유출(7일)</span><span class="en">Exchange Net Outflow (7d)</span><span class="ja">取引所純流出(7日)</span><span class="es">Salida Neta de Exchanges (7d)</span><span class="de">Netto-Börsenabfluss (7T)</span><span class="fr">Sortie Nette des Exchanges (7j)</span><span class="pt">Saída Líquida de Exchanges (7d)</span><span class="tr">Borsa Net Çıkışı (7g)</span><span class="vi">Dòng Rút Ròng Khỏi Sàn (7 Ngày)</span></div><div class="sv">-21,400 BTC</div><div class="ss"><span class="ko">약 13억 5천만 달러, 10주 만의 최대</span><span class="en">~$1.35B, largest in 10 weeks</span><span class="ja">約13.5億ドル、10週ぶり最大</span><span class="es">~$1,350M, la mayor en 10 semanas</span><span class="de">~1,35 Mrd. $, größter Wert seit 10 Wochen</span><span class="fr">~1,35 Md $, la plus importante en 10 semaines</span><span class="pt">~US$ 1,35 bi, a maior em 10 semanas</span><span class="tr">~1,35 milyar $, 10 haftanın en büyüğü</span><span class="vi">~1,35 tỷ USD, lớn nhất trong 10 tuần</span></div></div>
      <div class="si"><div class="sl"><span class="ko">롱숏비율(24H)</span><span class="en">Long/Short Ratio (24h)</span><span class="ja">ロングショート比率(24H)</span><span class="es">Ratio Long/Short (24H)</span><span class="de">Long/Short-Verhältnis (24H)</span><span class="fr">Ratio Long/Short (24H)</span><span class="pt">Índice Long/Short (24H)</span><span class="tr">Long/Short Oranı (24S)</span><span class="vi">Tỷ Lệ Long/Short (24H)</span></div><div class="sv">51.36% / 48.64%</div><div class="ss"><span class="ko">7/5 기준, 아직 펀딩비를 안 따라감</span><span class="en">As of Jul 5, hasn't followed funding yet</span><span class="ja">7/5時点、ファンディングにまだ追随せず</span><span class="es">Al 5 jul, aún no sigue a la financiación</span><span class="de">Stand 5. Juli, folgt Funding noch nicht</span><span class="fr">Au 5 juillet, n'a pas encore suivi le financement</span><span class="pt">Em 5 de julho, ainda não acompanhou o financiamento</span><span class="tr">5 Temmuz itibarıyla henüz fonlamayı takip etmedi</span><span class="vi">Tính đến 5/7, vẫn chưa theo kịp biến động của tỷ lệ tài trợ</span></div></div>
      <div class="si"><div class="sl"><span class="ko">BTC 가격</span><span class="en">BTC Price</span><span class="ja">BTC価格</span><span class="es">Precio BTC</span><span class="de">BTC-Preis</span><span class="fr">Prix du BTC</span><span class="pt">Preço do BTC</span><span class="tr">BTC Fiyatı</span><span class="vi">Giá BTC</span></div><div class="sv">$63,180</div><div class="ss"><span class="ko">24H +0.48%, 72H +2.03%</span><span class="en">+0.48% 24h, +2.03% 72h</span><span class="ja">24H +0.48%、72H +2.03%</span><span class="es">+0.48% 24h, +2.03% 72h</span><span class="de">+0,48% 24h, +2,03% 72h</span><span class="fr">+0,48% 24h, +2,03% 72h</span><span class="pt">+0,48% 24h, +2,03% 72h</span><span class="tr">+0,48% 24h, +2,03% 72h</span><span class="vi">+0,48% 24h, +2,03% 72h</span></div></div>
    </div>
  </div>

  <h2 class="ko">펀딩비, 6월 25일 이후 처음 0.05%를 넘었다</h2>
  <h2 class="en">Funding Rate Clears 0.05% for the First Time Since June 25</h2>
  <h2 class="ja">ファンディングレート、6月25日以来初めて0.05%を超えた</h2>
  <h2 class="es">La Tasa de Financiación Supera el 0.05% por Primera Vez Desde el 25 de Junio</h2>
  <h2 class="de">Funding Rate übersteigt erstmals seit dem 25. Juni die Marke von 0,05%</h2>
  <h2 class="fr">Le Taux de Financement Dépasse 0,05% pour la Première Fois Depuis le 25 Juin</h2>
  <h2 class="pt">Taxa de Financiamento Ultrapassa 0,05% pela Primeira Vez Desde 25 de Junho</h2>
  <h2 class="tr">Fonlama Oranı 25 Haziran'dan Bu Yana İlk Kez %0,05'i Aştı</h2>
  <h2 class="vi">Tỷ Lệ Tài Trợ Vượt Mốc 0,05% Lần Đầu Tiên Kể Từ Ngày 25 Tháng 6</h2>

  <p class="ko">본지는 지난 7월 5일 <a href="/blog/oi-rebuild-balanced-positioning">선물 오픈 인터레스트가 저점에서 빠르게 반등하는 동안 롱숏비율과 펀딩비는 아직 쏠리지 않았다</a>고 짚으면서, 앞으로 지켜볼 지점 중 하나로 "펀딩비가 중립(0.01% 안팎)을 벗어나 뚜렷하게 플러스로 돌아서는지"를 꼽았다. 반나절 만에 그 질문에 답이 나왔다. 코인글래스 기준 펀딩비는 0.056%까지 올라와, 6월 25일 이후 11일 연속 이어지던 0.005~0.015% 중립 구간을 벗어났다. 8시간 단위 요율을 연율로 환산하면 약 61%에 해당하는 수준으로, 절대적으로 극단적인 수치는 아니지만 최근 열흘간의 baseline과 비교하면 분명한 방향 전환이다.</p>
  <p class="en">On July 5, this site noted that <a href="/en/blog/oi-rebuild-balanced-positioning">while futures open interest was rebuilding fast off its low, the long/short ratio and funding rate hadn't tilted yet</a>, and flagged one thing worth watching from there: whether funding would break decisively out of neutral (around 0.01%) into clearly positive territory. Half a day later, there's an answer. Per CoinGlass, funding has climbed to 0.056%, breaking out of the 0.005%–0.015% neutral band that had held for 11 straight days since June 25. Annualized, the 8-hour rate works out to roughly 61% — not extreme in absolute terms, but a clear directional shift from the recent baseline.</p>
  <p class="ja">本紙は7月5日、<a href="/ja/blog/oi-rebuild-balanced-positioning">先物オープンインタレストが底値から急速に反発する一方でロングショート比率とファンディングレートはまだ偏っていない</a>と指摘し、今後の注視点の一つとして「ファンディングレートが中立(0.01%前後)を脱し明確にプラスへ転じるか」を挙げた。半日後、その問いへの答えが出た。コインググラス基準でファンディングレートは0.056%まで上昇し、6月25日以来11日間続いていた0.005~0.015%の中立圏を脱した。8時間レートを年率換算すると約61%相当で、絶対値としては極端ではないが、直近10日間のベースラインと比べれば明確な方向転換だ。</p>
  <p class="es">El 5 de julio, este sitio señaló que <a href="/es/blog/oi-rebuild-balanced-positioning">mientras el interés abierto en futuros se reconstruía rápido desde su mínimo, el ratio long/short y la tasa de financiación aún no se habían inclinado</a>, y marcó como algo a vigilar si la financiación rompería decisivamente la neutralidad (en torno al 0.01%) hacia territorio claramente positivo. Medio día después, hay una respuesta. Según CoinGlass, la financiación subió a 0.056%, saliendo de la banda neutral de 0.005%–0.015% que se había mantenido durante 11 días seguidos desde el 25 de junio. Anualizada, la tasa de 8 horas equivale a aproximadamente 61% — no extrema en términos absolutos, pero un giro direccional claro respecto a la referencia reciente.</p>
  <p class="de">Am 5. Juli stellte diese Seite fest, dass <a href="/de/blog/oi-rebuild-balanced-positioning">das Long/Short-Verhältnis und die Funding Rate noch nicht getiltet hatten, während sich das Futures-Open-Interest schnell vom Tief erholte</a>, und nannte als einen der Beobachtungspunkte, ob die Funding Rate entschieden aus der Neutralität (rund 0,01%) in eindeutig positives Terrain ausbricht. Ein halber Tag später gibt es eine Antwort. Laut CoinGlass stieg die Funding Rate auf 0,056% und verließ damit die neutrale Bandbreite von 0,005–0,015%, die seit dem 25. Juni 11 Tage lang gehalten hatte. Auf das Jahr hochgerechnet entspricht der 8-Stunden-Satz etwa 61% — absolut betrachtet nicht extrem, aber gegenüber der jüngsten Basislinie ein klarer Richtungswechsel.</p>
  <p class="fr">Le 5 juillet, ce site notait que <a href="/fr/blog/oi-rebuild-balanced-positioning">tandis que l'intérêt ouvert sur les contrats à terme se reconstituait rapidement depuis son creux, le ratio long/short et le taux de financement n'avaient pas encore basculé</a>, et signalait un point à surveiller à partir de là : si le financement allait franchir de manière décisive la neutralité (autour de 0,01%) pour entrer en territoire clairement positif. Une demi-journée plus tard, une réponse est arrivée. Selon CoinGlass, le financement a grimpé à 0,056%, sortant de la bande neutre de 0,005%–0,015% qui avait tenu pendant 11 jours consécutifs depuis le 25 juin. Annualisé, le taux sur 8 heures équivaut à environ 61% — pas extrême en termes absolus, mais un changement de direction net par rapport à la référence récente.</p>
  <p class="pt">Em 5 de julho, este site observou que <a href="/pt/blog/oi-rebuild-balanced-positioning">enquanto o interesse em aberto de futuros se reconstruía rapidamente após sua mínima, o índice long/short e a taxa de financiamento ainda não haviam se inclinado</a>, e apontou algo a observar a partir daí: se o financiamento romperia de forma decisiva a neutralidade (em torno de 0,01%) para um território claramente positivo. Meio dia depois, há uma resposta. Segundo a CoinGlass, o financiamento subiu para 0,056%, rompendo a faixa neutra de 0,005%–0,015% que havia se mantido por 11 dias seguidos desde 25 de junho. Anualizada, a taxa de 8 horas equivale a cerca de 61% — não extrema em termos absolutos, mas uma mudança direcional clara em relação à referência recente.</p>
  <p class="tr">5 Temmuz'da bu site, <a href="/tr/blog/oi-rebuild-balanced-positioning">vadeli işlem açık pozisyonu dip seviyesinden hızla toparlanırken long/short oranının ve fonlama oranının henüz yönelmediğini</a> belirtmiş ve buradan itibaren izlenmeye değer bir noktaya işaret etmişti: fonlamanın nötr seviyeden (yaklaşık %0,01) kararlı bir şekilde çıkıp net olarak pozitif bölgeye geçip geçmeyeceği. Yarım gün sonra bir yanıt geldi. CoinGlass'a göre fonlama %0,056'ya yükselerek, 25 Haziran'dan bu yana 11 gün boyunca süren %0,005–%0,015 nötr bandından çıktı. Yıllıklandırıldığında 8 saatlik oran yaklaşık %61'e denk geliyor — mutlak anlamda aşırı değil, ancak son dönemdeki taban seviyeye göre net bir yön değişikliği.</p>
  <p class="vi">Vào ngày 5 tháng 7, trang này đã lưu ý rằng <a href="/vi/blog/oi-rebuild-balanced-positioning">trong khi hợp đồng mở của futures đang phục hồi nhanh từ đáy, tỷ lệ long/short và tỷ lệ tài trợ vẫn chưa nghiêng hẳn về một phía</a>, và đã chỉ ra một điểm đáng theo dõi từ đó: liệu tỷ lệ tài trợ có bứt phá dứt khoát khỏi vùng trung lập (khoảng 0,01%) để bước vào vùng dương rõ rệt hay không. Nửa ngày sau, đã có câu trả lời. Theo CoinGlass, tỷ lệ tài trợ đã tăng lên 0,056%, phá vỡ vùng trung lập 0,005%–0,015% vốn đã duy trì suốt 11 ngày liên tiếp kể từ 25 tháng 6. Quy đổi theo năm, tỷ lệ 8 giờ này tương đương khoảng 61% — không phải là mức cực đoan xét về giá trị tuyệt đối, nhưng là một sự chuyển hướng rõ ràng so với nền tảng gần đây.</p>

  <p class="ko"><a href="/blog/metric-that-breaks-first">사이클마다 가장 먼저 깨지는 지표가 펀딩비라는 분석</a>이 짚었듯, 4월에는 정반대 그림이 있었다 — 4월 15일까지 46일 연속 마이너스 펀딩비가 이어지는 동안 오픈 인터레스트는 오히려 늘어나는 "혼잡한 숏" 구도였고, 이는 몇 주 후 $75,000 부근까지 밀어올리는 급등으로 청산됐다. 지금은 거울상에 가깝다. 펀딩비는 플러스로 확실히 돌아섰는데 가격은 지난 24시간 +0.48%에 그쳐 거의 움직이지 않았다. 레버리지 쪽의 확신이 가격보다 먼저 커지고 있는 셈인데, 이 간극이 유지된 채 펀딩비가 계속 오르면 "가격은 안 가는데 롱 포지션만 쌓이는" 구도가 되고, 이는 작은 되돌림에도 청산이 몰리는 취약한 상태로 이어질 수 있다.</p>
  <p class="en">As <a href="/en/blog/metric-that-breaks-first">the analysis of the metric that breaks first each cycle</a> covered, April looked like the mirror image — funding stayed negative for 46 straight days through April 15 while open interest kept rising, a "crowded short" setup that unwound weeks later in a sharp rally toward $75,000. Right now looks close to the opposite mirror. Funding has clearly turned positive, but price has barely moved, up just 0.48% over the past 24 hours. Conviction on the leveraged side is growing faster than conviction in price itself. If that gap holds while funding keeps climbing, it becomes a setup where longs keep piling up without price cooperating — a fragile state where even a small pullback can trigger a cluster of liquidations.</p>
  <p class="ja"><a href="/ja/blog/metric-that-breaks-first">サイクルごとに最初に崩れる指標がファンディングレートだという分析</a>で指摘した通り、4月は正反対の構図だった — 4月15日まで46日連続でマイナスファンディングが続く間、オープンインタレストはむしろ増加する「混雑したショート」の構図で、これは数週間後、7万5,000ドル付近まで押し上げる急騰で解消された。今はほぼ鏡像に近い。ファンディングレートは確実にプラスへ転じたが、価格は直近24時間で+0.48%とほとんど動いていない。レバレッジ側の確信が価格そのものより先に膨らんでいる形だ。この乖離が続いたままファンディングレートが上昇し続ければ、「価格は動かないのにロングポジションだけ積み上がる」構図となり、小さな押し目でも清算が集中する脆弱な状態につながりかねない。</p>
  <p class="es">Como cubrió <a href="/es/blog/metric-that-breaks-first">el análisis sobre el indicador que se rompe primero en cada ciclo</a>, abril lucía como la imagen especular — la financiación se mantuvo negativa durante 46 días seguidos hasta el 15 de abril mientras el interés abierto seguía subiendo, un montaje de "cortos apiñados" que se deshizo semanas después en un repunte brusco hacia los $75,000. Ahora mismo parece casi lo opuesto. La financiación se volvió claramente positiva, pero el precio apenas se ha movido, solo +0.48% en las últimas 24 horas. La convicción del lado apalancado crece más rápido que la convicción en el precio mismo. Si esa brecha se mantiene mientras la financiación sigue subiendo, se convierte en un escenario donde los longs siguen acumulándose sin que el precio coopere — un estado frágil donde incluso un pequeño retroceso puede disparar un cúmulo de liquidaciones.</p>
  <p class="de">Wie <a href="/de/blog/metric-that-breaks-first">die Analyse zur Kennzahl, die in jedem Zyklus zuerst bricht</a> beschrieb, sah der April wie das Spiegelbild aus — die Funding Rate blieb bis zum 15. April 46 Tage in Folge negativ, während das Open Interest weiter stieg, ein "Crowded-Short"-Szenario, das sich Wochen später in einer scharfen Rally Richtung 75.000 $ auflöste. Jetzt sieht es fast wie das Gegenteil aus. Die Funding Rate ist eindeutig ins Positive gedreht, doch der Preis hat sich kaum bewegt — in den letzten 24 Stunden nur +0,48%. Die Überzeugung auf der gehebelten Seite wächst schneller als die Überzeugung im Preis selbst. Hält sich diese Lücke, während die Funding Rate weiter steigt, entsteht ein Szenario, in dem sich Longs weiter aufbauen, ohne dass der Preis mitzieht — ein fragiler Zustand, in dem schon ein kleiner Rücksetzer eine Liquidationswelle auslösen kann.</p>
  <p class="fr">Comme l'a montré <a href="/fr/blog/metric-that-breaks-first">l'analyse de l'indicateur qui cède le premier à chaque cycle</a>, avril ressemblait à l'image inversée — le financement est resté négatif pendant 46 jours consécutifs jusqu'au 15 avril tandis que l'intérêt ouvert continuait de croître, un montage de « shorts surpeuplés » qui s'est dénoué quelques semaines plus tard lors d'un rallye brutal vers 75 000 $. En ce moment, on est proche du miroir opposé. Le financement est clairement devenu positif, mais le prix a à peine bougé, en hausse de seulement 0,48% sur les dernières 24 heures. La conviction du côté du levier croît plus vite que la conviction sur le prix lui-même. Si cet écart persiste tandis que le financement continue de grimper, cela devient un montage où les positions longues continuent de s'accumuler sans que le prix ne coopère — un état fragile où même un petit repli peut déclencher une vague de liquidations.</p>
  <p class="pt">Como abordou <a href="/pt/blog/metric-that-breaks-first">a análise sobre o indicador que quebra primeiro em cada ciclo</a>, abril parecia a imagem espelhada — o financiamento permaneceu negativo por 46 dias seguidos até 15 de abril, enquanto o interesse em aberto continuava subindo, uma configuração de "shorts lotados" que se desfez semanas depois em um rali forte rumo a $75.000. Agora, o cenário parece próximo do espelho oposto. O financiamento claramente se tornou positivo, mas o preço mal se mexeu, subindo apenas 0,48% nas últimas 24 horas. A convicção do lado alavancado está crescendo mais rápido do que a convicção no próprio preço. Se essa diferença persistir enquanto o financiamento continua subindo, isso se transforma em uma configuração em que as posições compradas continuam se acumulando sem que o preço colabore — um estado frágil em que até um pequeno recuo pode disparar uma onda de liquidações.</p>
  <p class="tr"><a href="/tr/blog/metric-that-breaks-first">Her döngüde ilk kırılan göstergeye ilişkin analizin</a> ele aldığı gibi, Nisan ayı ayna görüntüsü gibiydi — 15 Nisan'a kadar 46 gün boyunca fonlama negatif kalırken açık pozisyon artmaya devam etti; bu, haftalar sonra 75.000 dolara doğru sert bir yükselişle çözülen bir "kalabalık short" kurgusuydu. Şu anda ise tam tersi bir aynaya yakın görünüyor. Fonlama net biçimde pozitife döndü, ancak fiyat neredeyse hiç hareket etmedi; son 24 saatte yalnızca %0,48 arttı. Kaldıraçlı taraftaki güven, fiyattaki güvenden daha hızlı büyüyor. Bu fark, fonlama yükselmeye devam ederken sürerse, fiyat işbirliği yapmadan long pozisyonların birikmeye devam ettiği bir kurguya dönüşür — küçük bir geri çekilmenin bile bir tasfiye dalgasını tetikleyebileceği kırılgan bir durum.</p>
  <p class="vi">Như <a href="/vi/blog/metric-that-breaks-first">phân tích về chỉ báo bị phá vỡ đầu tiên trong mỗi chu kỳ</a> đã đề cập, tháng 4 trông giống như hình ảnh phản chiếu ngược lại — tỷ lệ tài trợ duy trì âm suốt 46 ngày liên tiếp cho đến 15 tháng 4 trong khi hợp đồng mở tiếp tục tăng, một thế "short quá đông" đã được giải tỏa vài tuần sau đó bằng một đợt tăng mạnh hướng tới 75.000 USD. Hiện tại trông gần như hình ảnh đối lập. Tỷ lệ tài trợ đã chuyển sang dương rõ rệt, nhưng giá gần như không nhúc nhích, chỉ tăng 0,48% trong 24 giờ qua. Niềm tin ở phía đòn bẩy đang tăng nhanh hơn niềm tin vào chính giá. Nếu khoảng cách đó vẫn duy trì trong khi tỷ lệ tài trợ tiếp tục leo thang, nó sẽ trở thành một thế mà các vị thế long tiếp tục chất chồng mà không có giá hợp tác — một trạng thái mong manh nơi chỉ một đợt điều chỉnh nhỏ cũng có thể kích hoạt một loạt thanh lý.</p>

  <h2 class="ko">그런데 거래소에서는 정반대 이야기가 나온다 — 7일간 2만 1,400 BTC 순유출</h2>
  <h2 class="en">But Exchanges Tell the Opposite Story — 21,400 BTC Net Outflow in 7 Days</h2>
  <h2 class="ja">だが取引所では正反対の話が出ている — 7日間で2万1,400BTC純流出</h2>
  <h2 class="es">Pero los Exchanges Cuentan la Historia Opuesta — 21,400 BTC de Salida Neta en 7 Días</h2>
  <h2 class="de">Doch die Börsen erzählen das Gegenteil — 21.400 BTC Nettoabfluss in 7 Tagen</h2>
  <h2 class="fr">Mais les Exchanges Racontent l'Histoire Inverse — 21 400 BTC de Sortie Nette en 7 Jours</h2>
  <h2 class="pt">Mas os Exchanges Contam a História Oposta — 21.400 BTC de Saída Líquida em 7 Dias</h2>
  <h2 class="tr">Ama Borsalar Tam Tersini Anlatıyor — 7 Günde 21.400 BTC Net Çıkış</h2>
  <h2 class="vi">Nhưng Các Sàn Giao Dịch Lại Kể Câu Chuyện Ngược Lại — 21.400 BTC Rút Ròng Trong 7 Ngày</h2>

  <p class="ko">파생상품 레버리지가 방향을 트는 동안, 현물 쪽 지표는 별개로 움직이고 있다. 거래소 전체 비트코인 잔고는 현재 약 231만 BTC로 유통량(약 1,994만 BTC)의 11.6% 수준까지 줄었고, 최근 7일간 순유출 규모는 2만 1,400 BTC(현재가 기준 약 13억 5천만 달러)로 10주 만에 가장 큰 주간 유출이다. 본지는 지난 7월 4일 <a href="/blog/exchange-reserve-decline-trend">거래소 잔고 감소분의 상당수가 개인 셀프 커스터디보다는 ETF 발행사의 자체 커스터디 이전일 수 있다</a>고 짚은 바 있는데, 이번 유출이 같은 성격인지 다른 성격인지는 아직 단정하기 이르다.</p>
  <p class="en">While derivatives leverage is changing direction, the spot-side data is moving on its own track. Total exchange bitcoin reserves now sit around 2.31 million BTC, down to about 11.6% of circulating supply (roughly 19.94 million BTC), and the past 7 days saw a net outflow of 21,400 BTC — worth about $1.35 billion at current prices, the largest weekly outflow in 10 weeks. On July 4, this site noted that <a href="/en/blog/exchange-reserve-decline-trend">much of the recent reserve decline may reflect ETF issuers moving supply into their own custody rather than retail self-custody</a>. Whether this latest leg of outflow follows the same pattern or a different one is still too early to say.</p>
  <p class="ja">デリバティブのレバレッジが方向を変える一方で、現物側のデータは別軌道で動いている。取引所全体のビットコイン残高は現在約231万BTCで、流通量(約1,994万BTC)の11.6%まで減少しており、直近7日間の純流出額は2万1,400BTC(現在価格で約13.5億ドル)と10週間ぶりの最大の週間流出となった。本紙は7月4日、<a href="/ja/blog/exchange-reserve-decline-trend">最近の残高減少の多くが個人のセルフカストディよりもETF発行体の自社カストディへの移動である可能性がある</a>と指摘したが、今回の流出が同じ性質なのか異なる性質なのかを断定するのはまだ早い。</p>
  <p class="es">Mientras el apalancamiento en derivados cambia de dirección, los datos del lado spot se mueven por su propia vía. Las reservas totales de bitcoin en exchanges ahora rondan los 2.31 millones de BTC, cayendo a cerca del 11.6% del suministro circulante (unos 19.94 millones de BTC), y los últimos 7 días registraron una salida neta de 21,400 BTC — unos $1,350 millones a precios actuales, la mayor salida semanal en 10 semanas. El 4 de julio, este sitio señaló que <a href="/es/blog/exchange-reserve-decline-trend">buena parte del reciente descenso de reservas podría reflejar a emisores de ETF moviendo suministro a su propia custodia más que autocustodia minorista</a>. Si este último tramo de salidas sigue el mismo patrón o uno distinto, aún es pronto para saberlo.</p>
  <p class="de">Während sich der Hebel bei Derivaten dreht, bewegen sich die Spot-Daten auf einer eigenen Spur. Die gesamten Bitcoin-Bestände auf Börsen liegen derzeit bei rund 2,31 Millionen BTC, das entspricht etwa 11,6% des Umlaufangebots (rund 19,94 Millionen BTC), und in den vergangenen 7 Tagen gab es einen Nettoabfluss von 21.400 BTC — beim aktuellen Kurs rund 1,35 Milliarden Dollar, der größte Wochenabfluss seit 10 Wochen. Am 4. Juli stellte diese Seite fest, dass <a href="/de/blog/exchange-reserve-decline-trend">ein Großteil des jüngsten Rückgangs der Börsenreserven eher auf die Verlagerung von Beständen durch ETF-Emittenten in eigene Verwahrung als auf Retail-Selbstverwahrung zurückgehen könnte</a>. Ob dieser neue Abfluss demselben Muster folgt oder einem anderen, lässt sich noch nicht sicher sagen.</p>
  <p class="fr">Alors que le levier des produits dérivés change de direction, les données du côté spot suivent leur propre trajectoire. Les réserves totales de bitcoin sur les exchanges se situent désormais autour de 2,31 millions de BTC, soit environ 11,6% de l'offre en circulation (environ 19,94 millions de BTC), et les 7 derniers jours ont vu une sortie nette de 21 400 BTC — soit environ 1,35 milliard de dollars aux prix actuels, la plus grande sortie hebdomadaire en 10 semaines. Le 4 juillet, ce site notait que <a href="/fr/blog/exchange-reserve-decline-trend">une grande partie du récent déclin des réserves pourrait refléter le déplacement de l'offre par les émetteurs d'ETF vers leur propre garde plutôt qu'une auto-garde de détail</a>. Il est encore trop tôt pour dire si ce dernier volet de sorties suit le même schéma ou un schéma différent.</p>
  <p class="pt">Enquanto a alavancagem de derivativos muda de direção, os dados do lado spot seguem seu próprio caminho. As reservas totais de bitcoin em exchanges agora estão em torno de 2,31 milhões de BTC, cerca de 11,6% da oferta em circulação (aproximadamente 19,94 milhões de BTC), e os últimos 7 dias registraram uma saída líquida de 21.400 BTC — cerca de US$ 1,35 bilhão aos preços atuais, a maior saída semanal em 10 semanas. Em 4 de julho, este site observou que <a href="/pt/blog/exchange-reserve-decline-trend">boa parte da recente queda nas reservas pode refletir emissores de ETF transferindo oferta para sua própria custódia, em vez de autocustódia de varejo</a>. Ainda é cedo para saber se essa última leva de saídas segue o mesmo padrão ou um diferente.</p>
  <p class="tr">Türev kaldıracı yön değiştirirken, spot taraftaki veriler kendi seyrinde ilerliyor. Toplam borsa bitcoin rezervleri şu anda dolaşımdaki arzın (yaklaşık 19,94 milyon BTC) yaklaşık %11,6'sına karşılık gelen 2,31 milyon BTC civarında ve son 7 günde 21.400 BTC net çıkış yaşandı — güncel fiyatlarla yaklaşık 1,35 milyar dolar değerinde, 10 haftanın en büyük haftalık çıkışı. 4 Temmuz'da bu site, <a href="/tr/blog/exchange-reserve-decline-trend">son rezerv düşüşünün büyük bölümünün, perakende self-custody'den ziyade ETF ihraççılarının arzı kendi saklama hizmetlerine taşımasını yansıtabileceğini</a> belirtmişti. Bu son çıkış dalgasının aynı örüntüyü mü yoksa farklı bir örüntüyü mü izlediğini söylemek için henüz erken.</p>
  <p class="vi">Trong khi đòn bẩy phái sinh đang đổi hướng, dữ liệu phía giao ngay lại di chuyển theo hướng riêng của nó. Tổng dự trữ bitcoin trên các sàn hiện ở mức khoảng 2,31 triệu BTC, giảm còn khoảng 11,6% nguồn cung lưu hành (khoảng 19,94 triệu BTC), và 7 ngày qua ghi nhận dòng rút ròng 21.400 BTC — trị giá khoảng 1,35 tỷ USD theo giá hiện tại, mức rút ròng theo tuần lớn nhất trong 10 tuần. Vào ngày 4 tháng 7, trang này đã lưu ý rằng <a href="/vi/blog/exchange-reserve-decline-trend">phần lớn sự sụt giảm dự trữ gần đây có thể phản ánh việc các tổ chức phát hành ETF chuyển nguồn cung sang lưu ký riêng của họ hơn là tự lưu ký ở cấp độ nhà đầu tư cá nhân</a>. Việc đợt rút vốn mới nhất này theo cùng một khuôn mẫu hay một khuôn mẫu khác thì vẫn còn quá sớm để khẳng định.</p>

  <p class="ko">분명한 것은 두 지표가 서로 다른 참가자 집단, 다른 시간축을 대표한다는 점이다. 펀딩비는 지금 이 순간의 레버리지 트레이더 심리를 반영하는 반면, 거래소 잔고는 주 단위로 쌓이는 현물·커스터디 자금의 흐름을 보여준다. 본지가 지난 7월 4일 <a href="/blog/whale-wallet-accumulation-pattern">가격이 조용한 동안에도 대형 지갑이 조용히 매집을 이어갔다</a>고 짚은 흐름과 이번 거래소 순유출이 겹치는지도 지켜볼 대목이다. 두 지표가 원래 항상 같은 방향으로 움직여야 하는 관계는 아니지만, 지금처럼 레버리지 쪽에서 처음으로 확신이 생기는 시점에 현물 쪽 자금까지 같은 방향을 가리키는지, 아니면 계속 따로 노는지가 이번 반등의 성격을 가늠하는 단서가 된다.</p>
  <p class="en">What's clear is that the two indicators represent different participants on different timescales. Funding rate reflects leveraged traders' sentiment in this exact moment, while exchange reserves track spot and custody flows accumulating over weeks. It's worth watching whether this outflow overlaps with the pattern this site flagged on July 4, when <a href="/en/blog/whale-wallet-accumulation-pattern">large wallets kept quietly accumulating even while price stayed quiet</a>. The two indicators were never required to move in lockstep, but whether spot-side flows start pointing the same way as leverage — right as leverage shows its first real conviction — or keep drifting apart is a useful clue to what kind of bounce this actually is.</p>
  <p class="ja">明らかなのは、この二つの指標が異なる参加者層、異なる時間軸を代表しているという点だ。ファンディングレートはまさに今この瞬間のレバレッジトレーダーの心理を反映する一方、取引所残高は週単位で積み上がる現物・カストディ資金の流れを示す。本紙が7月4日に<a href="/ja/blog/whale-wallet-accumulation-pattern">価格が静かな間も大型ウォレットが静かに買い集めを続けていた</a>と指摘した流れと、今回の取引所純流出が重なるかどうかも注視すべき点だ。二つの指標がもともと常に同じ方向に動くべき関係ではないが、レバレッジ側で初めて確信が生まれたこのタイミングで現物側の資金も同じ方向を示すのか、それとも別々に動き続けるのかが、今回の反発の性格を見極める手がかりになる。</p>
  <p class="es">Lo que está claro es que ambos indicadores representan a participantes distintos en escalas de tiempo distintas. La tasa de financiación refleja el sentimiento de los traders apalancados en este momento exacto, mientras que las reservas de exchanges siguen los flujos spot y de custodia que se acumulan durante semanas. Vale la pena observar si esta salida coincide con el patrón que este sitio señaló el 4 de julio, cuando <a href="/es/blog/whale-wallet-accumulation-pattern">las billeteras grandes siguieron acumulando silenciosamente incluso mientras el precio permanecía tranquilo</a>. Los dos indicadores nunca tuvieron que moverse al unísono, pero que el flujo spot empiece a apuntar en la misma dirección que el apalancamiento —justo cuando el apalancamiento muestra su primera convicción real— o que sigan separándose es una pista útil sobre qué tipo de rebote es este realmente.</p>
  <p class="de">Klar ist, dass die beiden Indikatoren unterschiedliche Teilnehmer auf unterschiedlichen Zeitskalen abbilden. Die Funding Rate spiegelt die Stimmung gehebelter Trader in genau diesem Moment wider, während die Börsenreserven Spot- und Verwahrungsflüsse zeigen, die sich über Wochen aufbauen. Es lohnt sich zu beobachten, ob dieser Abfluss mit dem Muster übereinstimmt, das diese Seite am 4. Juli feststellte, als <a href="/de/blog/whale-wallet-accumulation-pattern">große Wallets weiter still akkumulierten, während der Preis ruhig blieb</a>. Die beiden Indikatoren mussten nie im Gleichschritt laufen, aber ob die Spot-Flüsse jetzt, wo der Hebel zum ersten Mal echte Überzeugung zeigt, in dieselbe Richtung zeigen oder weiter auseinanderdriften, ist ein nützlicher Hinweis darauf, was für eine Art Erholung das hier eigentlich ist.</p>
  <p class="fr">Ce qui est clair, c'est que les deux indicateurs représentent des participants différents sur des échelles de temps différentes. Le taux de financement reflète le sentiment des traders sous levier à cet instant précis, tandis que les réserves des exchanges suivent les flux spot et de garde qui s'accumulent sur plusieurs semaines. Il vaut la peine d'observer si cette sortie recoupe le schéma que ce site a signalé le 4 juillet, lorsque <a href="/fr/blog/whale-wallet-accumulation-pattern">les grands portefeuilles ont continué d'accumuler discrètement même pendant que le prix restait silencieux</a>. Les deux indicateurs n'ont jamais été tenus de bouger au même rythme, mais le fait que les flux du côté spot commencent à pointer dans la même direction que le levier — juste au moment où le levier montre sa première véritable conviction — ou continuent de diverger est un indice utile sur la nature réelle de ce rebond.</p>
  <p class="pt">O que fica claro é que os dois indicadores representam participantes diferentes em escalas de tempo diferentes. A taxa de financiamento reflete o sentimento dos traders alavancados neste exato momento, enquanto as reservas de exchanges acompanham fluxos de spot e custódia que se acumulam ao longo de semanas. Vale a pena observar se essa saída coincide com o padrão que este site apontou em 4 de julho, quando <a href="/pt/blog/whale-wallet-accumulation-pattern">grandes carteiras continuaram acumulando silenciosamente mesmo enquanto o preço permanecia parado</a>. Os dois indicadores nunca precisaram se mover em sincronia, mas se os fluxos do lado spot começam a apontar na mesma direção que a alavancagem — bem no momento em que a alavancagem mostra sua primeira convicção real — ou continuam se distanciando é uma pista útil sobre que tipo de recuperação esta realmente é.</p>
  <p class="tr">Açık olan şey, bu iki göstergenin farklı zaman ölçeklerinde farklı katılımcıları temsil ettiğidir. Fonlama oranı tam da bu anda kaldıraçlı yatırımcıların duyarlılığını yansıtırken, borsa rezervleri haftalar içinde birikimli olarak oluşan spot ve saklama akışlarını izler. Bu çıkışın, <a href="/tr/blog/whale-wallet-accumulation-pattern">büyük cüzdanların fiyat sessizken bile sessizce birikim yapmaya devam ettiği</a> ve bu sitenin 4 Temmuz'da işaret ettiği örüntüyle örtüşüp örtüşmediğini izlemekte fayda var. Bu iki gösterge hiçbir zaman aynı adımda hareket etmek zorunda olmadı, ancak spot taraftaki akışların kaldıraçla aynı yönü göstermeye başlaması — tam olarak kaldıracın ilk gerçek güvenini gösterdiği anda — ya da birbirinden uzaklaşmaya devam etmesi, bunun gerçekte ne tür bir toparlanma olduğuna dair yararlı bir ipucudur.</p>
  <p class="vi">Điều rõ ràng là hai chỉ báo này đại diện cho các nhóm tham gia khác nhau trên các khung thời gian khác nhau. Tỷ lệ tài trợ phản ánh tâm lý của các nhà giao dịch đòn bẩy ngay tại thời điểm này, trong khi dự trữ trên sàn theo dõi dòng chảy giao ngay và lưu ký tích lũy qua nhiều tuần. Đáng để theo dõi xem dòng rút này có trùng khớp với khuôn mẫu mà trang này đã chỉ ra vào ngày 4 tháng 7 hay không, khi <a href="/vi/blog/whale-wallet-accumulation-pattern">các ví lớn vẫn âm thầm tích lũy ngay cả khi giá im ắng</a>. Hai chỉ báo này chưa bao giờ bắt buộc phải di chuyển đồng bộ, nhưng việc dòng vốn phía giao ngay có bắt đầu chỉ cùng hướng với đòn bẩy hay không — ngay khi đòn bẩy thể hiện niềm tin thực sự đầu tiên của nó — hay tiếp tục trôi dạt xa nhau là một manh mối hữu ích cho biết đây thực sự là loại đợt phục hồi nào.</p>

  <h2 class="ko">네 지표가 같은 곳을 보지 않는다 — 지금 지켜봐야 할 세 가지</h2>
  <h2 class="en">Four Indicators, Not One Story — Three Things to Watch From Here</h2>
  <h2 class="ja">四つの指標が同じ方向を見ていない — 今後注視すべき3点</h2>
  <h2 class="es">Cuatro Indicadores, No Una Sola Historia — Tres Cosas a Vigilar Desde Aquí</h2>
  <h2 class="de">Vier Indikatoren, keine einheitliche Geschichte — Drei Dinge, die es zu beobachten gilt</h2>
  <h2 class="fr">Quatre Indicateurs, Pas une Seule Histoire — Trois Choses à Surveiller à Partir d'Ici</h2>
  <h2 class="pt">Quatro Indicadores, Não Uma Só História — Três Coisas a Observar a Partir de Agora</h2>
  <h2 class="tr">Dört Gösterge, Tek Bir Hikaye Değil — Buradan İtibaren İzlenmesi Gereken Üç Şey</h2>
  <h2 class="vi">Bốn Chỉ Báo, Không Phải Một Câu Chuyện — Ba Điều Cần Theo Dõi Từ Đây</h2>

  <p class="ko">지금 국면을 한 화면에 모아보면 이렇다. 가격은 24시간 +0.48%로 거의 정지해 있고, 펀딩비는 11일 만에 처음 뚜렷한 플러스(0.056%)로 돌아섰으며, 롱숏비율은 7월 5일 기준 51.36%/48.64%로 아직 펀딩비의 변화를 따라가지 않았고, 거래소 잔고는 7일간 2만 1,400 BTC가 순유출됐다. 넷 중 어느 것도 그 자체로 극단적인 신호는 아니지만, 넷이 하나의 일관된 서사로 묶이지도 않는다. <a href="/blog/rebound-not-yet-confirmed-2026">가격·심리·자금·레버리지의 괴리를 다룬 분석</a>이 짚었듯 이번 반등은 여러 층위에서 아직 완전히 확인되지 않은 상태인데, 오늘은 그 층위 중 하나(파생상품 레버리지 심리)가 처음으로 움직였다는 점 자체가 새로운 정보다.</p>
  <p class="en">Put on one screen, the current picture looks like this: price is essentially frozen at +0.48% over 24 hours, funding rate has turned clearly positive (0.056%) for the first time in 11 days, the long/short ratio still read 51.36%/48.64% as of July 5 and hasn't followed funding's move, and exchange reserves posted a 21,400 BTC net outflow over 7 days. None of the four is extreme on its own, but they don't add up to one consistent story either. As <a href="/en/blog/rebound-not-yet-confirmed-2026">the analysis of the gap between price, sentiment, flows, and leverage</a> covered, this bounce remains unconfirmed across multiple layers — and today, the fact that one of those layers, derivatives leverage sentiment, just moved for the first time is itself new information.</p>
  <p class="ja">一つの画面にまとめるとこうなる。価格は24時間+0.48%とほぼ静止しており、ファンディングレートは11日ぶりに明確なプラス(0.056%)へ転じ、ロングショート比率は7月5日時点で51.36%/48.64%とファンディングの変化にまだ追随していない。そして取引所残高は7日間で2万1,400BTCの純流出を記録した。四つのうちどれ一つとして単独では極端なシグナルではないが、四つがひとつの一貫した物語にまとまるわけでもない。<a href="/ja/blog/rebound-not-yet-confirmed-2026">価格・心理・資金・レバレッジの乖離を扱った分析</a>が指摘した通り、今回の反発は複数の層でまだ完全には確認されていない状態だが、今日はその層の一つ(デリバティブレバレッジ心理)が初めて動いたこと自体が新しい情報だ。</p>
  <p class="es">Reunido en una sola pantalla, el panorama actual luce así: el precio está prácticamente congelado en +0.48% en 24 horas, la tasa de financiación se volvió claramente positiva (0.056%) por primera vez en 11 días, el ratio long/short seguía en 51.36%/48.64% al 5 de julio y no ha seguido el movimiento de la financiación, y las reservas de exchanges registraron una salida neta de 21,400 BTC en 7 días. Ninguno de los cuatro es extremo por sí solo, pero tampoco se suman a una sola historia coherente. Como cubrió <a href="/es/blog/rebound-not-yet-confirmed-2026">el análisis de la brecha entre precio, sentimiento, flujos y apalancamiento</a>, este rebote sigue sin confirmarse en varias capas — y hoy, el hecho de que una de esas capas, el sentimiento de apalancamiento en derivados, se haya movido por primera vez es en sí mismo información nueva.</p>
  <p class="de">Auf einen Blick sieht die aktuelle Lage so aus: Der Preis ist mit +0,48% über 24 Stunden praktisch eingefroren, die Funding Rate ist erstmals seit 11 Tagen deutlich ins Positive gedreht (0,056%), das Long/Short-Verhältnis lag zum 5. Juli noch bei 51,36%/48,64% und ist der Bewegung der Funding Rate nicht gefolgt, und die Börsenreserven verzeichneten über 7 Tage einen Nettoabfluss von 21.400 BTC. Keiner der vier Werte ist für sich genommen extrem, aber sie ergeben auch keine einheitliche Geschichte. Wie <a href="/de/blog/rebound-not-yet-confirmed-2026">die Analyse der Lücke zwischen Preis, Sentiment, Flüssen und Hebel</a> beschrieb, bleibt diese Erholung auf mehreren Ebenen unbestätigt — und dass sich heute eine dieser Ebenen, das Derivate-Hebel-Sentiment, zum ersten Mal bewegt hat, ist selbst schon eine neue Information.</p>
  <p class="fr">Réunie sur un seul écran, la situation actuelle se présente ainsi : le prix est essentiellement figé à +0,48% sur 24 heures, le taux de financement est clairement devenu positif (0,056%) pour la première fois en 11 jours, le ratio long/short affichait encore 51,36%/48,64% au 5 juillet et n'a pas suivi le mouvement du financement, et les réserves des exchanges ont enregistré une sortie nette de 21 400 BTC sur 7 jours. Aucun des quatre n'est extrême en soi, mais ils ne forment pas non plus une histoire cohérente. Comme l'a montré <a href="/fr/blog/rebound-not-yet-confirmed-2026">l'analyse de l'écart entre le prix, le sentiment, les flux et le levier</a>, ce rebond reste non confirmé à plusieurs niveaux — et aujourd'hui, le fait que l'un de ces niveaux, le sentiment de levier des produits dérivés, vienne de bouger pour la première fois constitue en soi une information nouvelle.</p>
  <p class="pt">Reunido em uma única tela, o quadro atual é assim: o preço está essencialmente congelado em +0,48% em 24 horas, a taxa de financiamento se tornou claramente positiva (0,056%) pela primeira vez em 11 dias, o índice long/short ainda marcava 51,36%/48,64% em 5 de julho e não seguiu o movimento do financiamento, e as reservas de exchanges registraram uma saída líquida de 21.400 BTC em 7 dias. Nenhum dos quatro é extremo isoladamente, mas também não se somam a uma única história coerente. Como abordou <a href="/pt/blog/rebound-not-yet-confirmed-2026">a análise da diferença entre preço, sentimento, fluxos e alavancagem</a>, essa recuperação permanece não confirmada em várias camadas — e hoje, o fato de uma dessas camadas, o sentimento de alavancagem em derivativos, ter se movido pela primeira vez já é, por si só, uma informação nova.</p>
  <p class="tr">Tek ekranda toplandığında mevcut tablo şöyle görünüyor: fiyat 24 saatte %0,48 ile hemen hemen donmuş durumda, fonlama oranı 11 gün içinde ilk kez net biçimde pozitife döndü (%0,056), long/short oranı 5 Temmuz itibarıyla hâlâ %51,36/%48,64 okundu ve fonlamanın hareketini takip etmedi, borsa rezervleri ise 7 günde 21.400 BTC net çıkış kaydetti. Dördünden hiçbiri tek başına aşırı değil, ancak tutarlı tek bir hikaye de oluşturmuyorlar. <a href="/tr/blog/rebound-not-yet-confirmed-2026">Fiyat, duyarlılık, akışlar ve kaldıraç arasındaki farkı ele alan analizin</a> belirttiği gibi, bu toparlanma birden fazla katmanda hâlâ doğrulanmış değil — ve bugün, bu katmanlardan birinin, türev kaldıraç duyarlılığının, ilk kez hareket etmiş olması başlı başına yeni bir bilgi.</p>
  <p class="vi">Gộp lại trên một màn hình, bức tranh hiện tại trông như sau: giá gần như đóng băng ở mức +0,48% trong 24 giờ, tỷ lệ tài trợ đã chuyển sang dương rõ rệt (0,056%) lần đầu tiên sau 11 ngày, tỷ lệ long/short tính đến ngày 5 tháng 7 vẫn ở mức 51,36%/48,64% và chưa theo kịp diễn biến của tỷ lệ tài trợ, còn dự trữ trên sàn ghi nhận mức rút ròng 21.400 BTC trong 7 ngày. Không chỉ báo nào trong bốn chỉ báo này là cực đoan khi xét riêng lẻ, nhưng chúng cũng không cộng lại thành một câu chuyện nhất quán. Như <a href="/vi/blog/rebound-not-yet-confirmed-2026">phân tích về khoảng cách giữa giá, tâm lý, dòng vốn và đòn bẩy</a> đã đề cập, đợt phục hồi này vẫn chưa được xác nhận trên nhiều tầng lớp — và hôm nay, việc một trong những tầng lớp đó, tâm lý đòn bẩy phái sinh, vừa dịch chuyển lần đầu tiên tự bản thân nó đã là một thông tin mới.</p>

  <p class="ko">앞으로 좁혀볼 지점은 세 가지다. 첫째, 롱숏비율이 펀딩비를 뒤따라 쏠리기 시작하는지—레버리지 심리와 실제 포지션 쏠림이 함께 움직이기 시작하면, 그때부터가 진짜 방향성 베팅이 쌓이는 국면이다. 둘째, 펀딩비가 다시 중립으로 식더라도 거래소 순유출이 계속 이어지는지—그렇다면 이번 유출이 파생상품 심리와 무관하게 굴러가는 구조적 흐름이라는 뜻이 된다. 셋째, 가격이 결국 레버리지가 베팅하는 방향으로 따라가는지, 아니면 펀딩비만 오르고 가격은 안 가는 상태가 계속되며 작은 되돌림에도 청산이 몰리는 "펀딩비 에어포켓"으로 이어지는지. 셋 중 무엇이 먼저 움직이는지가 오르내림을 미리 맞히는 문제가 아니라, 지금 쌓이고 있는 포지셔닝이 얼마나 튼튼한지를 가늠하는 기준이 된다.</p>
  <p class="en">Three things narrow down what's worth watching from here. First, whether the long/short ratio starts tilting in the direction funding is already leaning — once leverage sentiment and actual position skew move together, that's when a real directional bet starts building. Second, whether exchange outflows keep going even if funding cools back toward neutral — if so, this outflow is a structural flow running independent of derivatives sentiment. Third, whether price eventually follows the direction leverage is now betting on, or whether funding keeps climbing while price goes nowhere, turning into a "funding air pocket" where even a small pullback triggers a cluster of liquidations. Which of these three moves first isn't about calling the next move — it's the gauge for how sturdy the positioning building up right now actually is.</p>
  <p class="ja">今後注視すべき点は三つに絞られる。第一に、ロングショート比率がファンディングレートに追随して偏り始めるかどうか—レバレッジ心理と実際のポジションの偏りが共に動き始めた時が、本当の方向性ベットが積み上がる局面だ。第二に、ファンディングレートが再び中立へ冷えても取引所純流出が続くかどうか—そうであれば、この流出はデリバティブ心理と無関係に進む構造的な流れだということになる。第三に、価格が最終的にレバレッジが賭けている方向へついていくのか、それともファンディングレートだけが上昇し価格が動かない状態が続き、小さな押し目でも清算が集中する「ファンディングレート・エアポケット」につながるのか。この三つのうちどれが先に動くかは、次の値動きを当てる問題ではなく、今積み上がりつつあるポジショニングがどれだけ堅牢かを測る基準になる。</p>
  <p class="es">Tres cosas acotan lo que vale la pena vigilar desde aquí. Primero, si el ratio long/short empieza a inclinarse en la dirección hacia la que ya se inclina la financiación — una vez que el sentimiento de apalancamiento y el sesgo real de posiciones se mueven juntos, ahí es cuando empieza a construirse una apuesta direccional real. Segundo, si las salidas de exchanges continúan incluso si la financiación se enfría de vuelta hacia neutral — de ser así, esta salida es un flujo estructural que corre independiente del sentimiento en derivados. Tercero, si el precio finalmente sigue la dirección en la que el apalancamiento está apostando ahora, o si la financiación sigue subiendo mientras el precio no va a ninguna parte, convirtiéndose en un "bolsillo de aire de financiación" donde incluso un pequeño retroceso dispara un cúmulo de liquidaciones. Cuál de estas tres cosas se mueve primero no se trata de predecir el próximo movimiento — es el indicador de cuán sólido es realmente el posicionamiento que se está acumulando ahora.</p>
  <p class="de">Drei Dinge grenzen ein, was sich von hier aus zu beobachten lohnt. Erstens, ob sich das Long/Short-Verhältnis in die Richtung neigt, in die die Funding Rate bereits zeigt — sobald sich Hebel-Sentiment und tatsächliche Positionsschieflage gemeinsam bewegen, beginnt sich eine echte Richtungswette aufzubauen. Zweitens, ob die Börsenabflüsse weitergehen, selbst wenn sich die Funding Rate wieder Richtung neutral abkühlt — falls ja, ist dieser Abfluss ein struktureller Fluss, der unabhängig vom Derivate-Sentiment läuft. Drittens, ob der Preis der Richtung, auf die der Hebel jetzt wettet, letztlich folgt, oder ob die Funding Rate weiter steigt, während der Preis nicht vom Fleck kommt — was in ein "Funding-Luftloch" münden würde, in dem schon ein kleiner Rücksetzer eine Liquidationswelle auslöst. Welcher dieser drei Punkte sich zuerst bewegt, geht nicht darum, die nächste Bewegung vorherzusagen — es ist der Maßstab dafür, wie stabil die sich gerade aufbauende Positionierung tatsächlich ist.</p>
  <p class="fr">Trois éléments permettent de cerner ce qui vaut la peine d'être surveillé à partir d'ici. Premièrement, si le ratio long/short commence à s'incliner dans la direction que le financement indique déjà — une fois que le sentiment de levier et le déséquilibre réel des positions bougent ensemble, c'est à ce moment qu'un véritable pari directionnel commence à se construire. Deuxièmement, si les sorties des exchanges continuent même si le financement refroidit vers la neutralité — si c'est le cas, cette sortie est un flux structurel indépendant du sentiment des produits dérivés. Troisièmement, si le prix finit par suivre la direction sur laquelle le levier parie désormais, ou si le financement continue de grimper pendant que le prix ne bouge nulle part, se transformant en une « poche d'air du financement » où même un petit repli déclenche une vague de liquidations. Lequel de ces trois éléments bouge en premier n'est pas une question de prédire le prochain mouvement — c'est la jauge de la solidité réelle du positionnement en train de se constituer en ce moment.</p>
  <p class="pt">Três coisas delimitam o que vale a pena observar a partir daqui. Primeiro, se o índice long/short começa a se inclinar na direção que o financiamento já sugere — uma vez que o sentimento de alavancagem e o desvio real de posições se movem juntos, é quando uma aposta direcional real começa a se formar. Segundo, se as saídas de exchanges continuam mesmo que o financiamento esfrie de volta para neutro — se assim for, essa saída é um fluxo estrutural que corre independente do sentimento de derivativos. Terceiro, se o preço eventualmente segue a direção na qual a alavancagem está apostando agora, ou se o financiamento continua subindo enquanto o preço não vai a lugar nenhum, transformando-se em um "bolsão de ar do financiamento" onde até um pequeno recuo dispara uma onda de liquidações. Qual dessas três coisas se move primeiro não é sobre prever o próximo movimento — é o indicador de quão sólido é, na verdade, o posicionamento que está se acumulando agora.</p>
  <p class="tr">Buradan itibaren neyin izlenmeye değer olduğunu üç şey belirliyor. Birincisi, long/short oranının fonlamanın zaten yöneldiği yöne doğru eğilmeye başlayıp başlamayacağı — kaldıraç duyarlılığı ile gerçek pozisyon eğilimi birlikte hareket etmeye başladığında, gerçek bir yönlü bahis birikmeye başlar. İkincisi, fonlama tekrar nötre soğusa bile borsa çıkışlarının devam edip etmeyeceği — eğer öyleyse, bu çıkış türev duyarlılığından bağımsız işleyen yapısal bir akıştır. Üçüncüsü, fiyatın sonunda kaldıracın şu anda bahis oynadığı yönü izleyip izlemeyeceği, ya da fonlama yükselmeye devam ederken fiyatın hiçbir yere gitmeyip küçük bir geri çekilmenin bile bir tasfiye dalgasını tetiklediği bir "fonlama hava cebine" dönüşüp dönüşmeyeceği. Bu üçünden hangisinin önce hareket ettiği bir sonraki hareketi tahmin etmekle ilgili değildir — şu anda birikmekte olan pozisyonlanmanın aslında ne kadar sağlam olduğunun ölçüsüdür.</p>
  <p class="vi">Ba điều sẽ thu hẹp lại những gì đáng theo dõi từ đây. Thứ nhất, liệu tỷ lệ long/short có bắt đầu nghiêng theo hướng mà tỷ lệ tài trợ đã nghiêng sẵn hay không — một khi tâm lý đòn bẩy và độ lệch vị thế thực tế di chuyển cùng nhau, đó là lúc một cược định hướng thực sự bắt đầu hình thành. Thứ hai, liệu dòng rút khỏi sàn có tiếp tục ngay cả khi tỷ lệ tài trợ nguội trở lại mức trung lập hay không — nếu vậy, dòng rút này là một dòng chảy mang tính cấu trúc, vận hành độc lập với tâm lý phái sinh. Thứ ba, liệu giá cuối cùng có đi theo hướng mà đòn bẩy đang đặt cược hay không, hay tỷ lệ tài trợ tiếp tục leo thang trong khi giá không đi đến đâu, biến thành một "túi khí tài trợ" nơi chỉ một đợt điều chỉnh nhỏ cũng kích hoạt một loạt thanh lý. Điều nào trong ba điều này di chuyển trước không phải là để đoán biến động tiếp theo — đó là thước đo cho việc vị thế đang tích lũy ngay lúc này thực sự vững chắc đến đâu.</p>

  <div class="box ko">💡 <strong>정리:</strong> 비트코인은 $63,180 부근에서 사실상 정체(24H +0.48%)된 사이, 펀딩비는 6월 25일 이후 처음으로 0.05%를 넘어(0.056%) 뚜렷한 플러스로 돌아섰다. 그런데 같은 시각 거래소 잔고는 7일간 2만 1,400 BTC 순유출됐고, 롱숏비율(51.36%/48.64%)은 아직 펀딩비를 따라가지 않았다. 네 지표가 하나의 방향을 가리키지 않는 지금은 예측이 아니라, 롱숏비율·거래소 유출·가격 중 무엇이 먼저 움직이는지를 지켜봐야 할 시점이다.</div>
  <div class="box en">💡 <strong>Bottom line:</strong> While bitcoin sits essentially frozen around $63,180 (+0.48% on the day), funding rate has cleared 0.05% (0.056%) for the first time since June 25, turning clearly positive. Yet exchange reserves posted a 21,400 BTC net outflow over 7 days, and the long/short ratio (51.36%/48.64%) hasn't followed funding's move. With four indicators not pointing one direction, this is a moment to watch which moves first — the long/short ratio, exchange outflows, or price — rather than a moment to forecast.</div>
  <div class="box ja">💡 <strong>まとめ:</strong> ビットコインが$63,180付近でほぼ停滞(24H +0.48%)する間、ファンディングレートは6月25日以来初めて0.05%を超え(0.056%)、明確にプラスへ転じた。しかし同じ時間帯に取引所残高は7日間で2万1,400BTCの純流出を記録し、ロングショート比率(51.36%/48.64%)はまだファンディングの動きに追随していない。四つの指標が一つの方向を示さない今は、予測ではなく、ロングショート比率・取引所流出・価格のうちどれが先に動くかを見守るべき時点だ。</div>
  <div class="box es">💡 <strong>En resumen:</strong> Mientras bitcoin permanece prácticamente congelado en torno a $63,180 (+0.48% en el día), la tasa de financiación superó el 0.05% (0.056%) por primera vez desde el 25 de junio, volviéndose claramente positiva. Sin embargo, las reservas de exchanges registraron una salida neta de 21,400 BTC en 7 días, y el ratio long/short (51.36%/48.64%) no ha seguido el movimiento de la financiación. Con cuatro indicadores que no apuntan en una sola dirección, este es un momento para observar qué se mueve primero — el ratio long/short, las salidas de exchanges o el precio — más que para predecir.</div>
  <div class="box de">💡 <strong>Fazit:</strong> Während Bitcoin bei rund 63.180 $ praktisch eingefroren bleibt (+0,48% auf Tagesbasis), hat die Funding Rate erstmals seit dem 25. Juni die Marke von 0,05% (0,056%) überschritten und ist klar ins Positive gedreht. Doch die Börsenreserven verzeichneten über 7 Tage einen Nettoabfluss von 21.400 BTC, und das Long/Short-Verhältnis (51,36%/48,64%) ist der Bewegung der Funding Rate nicht gefolgt. Da vier Indikatoren nicht in eine Richtung zeigen, ist dies ein Moment zum Beobachten, was sich zuerst bewegt — das Long/Short-Verhältnis, die Börsenabflüsse oder der Preis — und keiner für Prognosen.</div>
  <div class="box fr">💡 <strong>En résumé :</strong> Alors que le bitcoin reste essentiellement figé autour de 63 180 $ (+0,48% sur la journée), le taux de financement a dépassé 0,05% (0,056%) pour la première fois depuis le 25 juin, devenant clairement positif. Pourtant, les réserves des exchanges ont enregistré une sortie nette de 21 400 BTC sur 7 jours, et le ratio long/short (51,36%/48,64%) n'a pas suivi le mouvement du financement. Avec quatre indicateurs qui ne pointent pas dans une seule direction, c'est un moment pour observer ce qui bouge en premier — le ratio long/short, les sorties des exchanges ou le prix — plutôt qu'un moment pour faire des prévisions.</div>
  <div class="box pt">💡 <strong>Conclusão:</strong> Enquanto o bitcoin permanece essencialmente congelado em torno de $63.180 (+0,48% no dia), a taxa de financiamento ultrapassou 0,05% (0,056%) pela primeira vez desde 25 de junho, tornando-se claramente positiva. No entanto, as reservas de exchanges registraram uma saída líquida de 21.400 BTC em 7 dias, e o índice long/short (51,36%/48,64%) não seguiu o movimento do financiamento. Com quatro indicadores não apontando em uma única direção, este é um momento para observar o que se move primeiro — o índice long/short, as saídas de exchanges ou o preço — em vez de um momento para prever.</div>
  <div class="box tr">💡 <strong>Sonuç:</strong> Bitcoin 63.180 dolar civarında hemen hemen donmuş durumda kalırken (günlük +%0,48), fonlama oranı 25 Haziran'dan bu yana ilk kez %0,05'i (%0,056) aşarak net biçimde pozitife döndü. Ancak borsa rezervleri 7 günde 21.400 BTC net çıkış kaydetti ve long/short oranı (%51,36/%48,64) fonlamanın hareketini takip etmedi. Dört gösterge tek bir yöne işaret etmezken, bu an bir tahmin anı değil, long/short oranı, borsa çıkışları veya fiyattan hangisinin önce hareket edeceğini izleme anıdır.</div>
  <div class="box vi">💡 <strong>Tóm lại:</strong> Trong khi bitcoin gần như đóng băng quanh mức 63.180 USD (+0,48% trong ngày), tỷ lệ tài trợ đã vượt mốc 0,05% (0,056%) lần đầu tiên kể từ 25 tháng 6, chuyển sang dương rõ rệt. Tuy nhiên, dự trữ trên sàn ghi nhận mức rút ròng 21.400 BTC trong 7 ngày, và tỷ lệ long/short (51,36%/48,64%) vẫn chưa theo kịp diễn biến của tỷ lệ tài trợ. Với bốn chỉ báo không cùng chỉ về một hướng, đây là thời điểm để theo dõi xem điều gì di chuyển trước — tỷ lệ long/short, dòng rút khỏi sàn, hay giá — hơn là thời điểm để dự đoán.</div>

  <p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: CoinGlass(펀딩비·롱숏비율), CryptoQuant(거래소 잔고·순유출입 추정), BTCtiming.com 자체 분석("선물 오픈 인터레스트 빠르게 복귀 — 그런데 롱숏비율은 아직 안 쏠렸다", "거래소 잔고 감소, 셀프 커스터디가 아니라 기관 이동일 수도", "가격은 조용한데 대형 지갑은 조용히 매집 중", "사이클마다 가장 먼저 깨지는 지표는 펀딩비다"). 수치는 인용 시점 기준이며 실시간으로 변동할 수 있다. 이 글은 투자 조언이 아니다.</p>
  <p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinGlass (funding rate, long/short ratio), CryptoQuant (exchange reserve and net flow estimates), BTCtiming.com's own analysis ("Futures Open Interest Is Rebuilding Fast — But Long/Short Positioning Isn't Yet," "Exchange Reserves Are Falling, but It Might Be Institutional Custody Moves, Not Self-Custody," "Price Is Quiet, but Big Wallets Are Quietly Accumulating," "The Metric That Breaks First Each Cycle Is Funding Rate"). Figures are as of the time cited and may change in real time. This article is not investment advice.</p>
  <p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: CoinGlass(ファンディングレート・ロングショート比率)、CryptoQuant(取引所残高・純流出入の推定)、BTCtiming.com自社分析(「先物オープンインタレスト、急速に回復——だがロングショート比率はまだ偏っていない」「取引所残高の減少、セルフカストディではなく機関の移動かもしれない」「価格は静かでも大型ウォレットは静かに買い集め中」「サイクルごとに最初に崩れる指標はファンディングレートだ」)。数値は引用時点のものであり、リアルタイムで変動しうる。本記事は投資助言ではない。</p>
  <p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinGlass (tasa de financiación, ratio long/short), CryptoQuant (estimaciones de reservas y flujo neto de exchanges), análisis propio de BTCtiming.com ("El Interés Abierto en Futuros Se Reconstruye Rápido — Pero el Ratio Long/Short Aún No", "Las Reservas de Exchanges Caen, pero Podría Ser Movimiento de Custodia Institucional, No Autocustodia", "El Precio Está Tranquilo, pero las Grandes Billeteras Acumulan en Silencio", "El Indicador que Se Rompe Primero en Cada Ciclo Es la Tasa de Financiación"). Las cifras corresponden al momento citado y pueden cambiar en tiempo real. Este artículo no es asesoramiento de inversión.</p>
  <p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinGlass (Funding Rate, Long/Short-Verhältnis), CryptoQuant (Schätzungen zu Börsenreserven und Nettoflüssen), BTCtiming.com-Eigenanalyse ("Futures Open Interest baut sich schnell wieder auf — das Long/Short-Verhältnis aber noch nicht", "Börsenreserven fallen, aber es könnte institutionelle Verwahrungsverlagerung statt Selbstverwahrung sein", "Der Preis ist ruhig, aber große Wallets akkumulieren still", "Die Kennzahl, die in jedem Zyklus zuerst bricht, ist die Funding Rate"). Die Zahlen entsprechen dem zitierten Zeitpunkt und können sich in Echtzeit ändern. Dieser Artikel ist keine Anlageberatung.</p>
  <p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinGlass (taux de financement, ratio long/short), CryptoQuant (estimations des réserves et flux nets des exchanges), analyse propre de BTCtiming.com (« L'Intérêt Ouvert sur les Contrats à Terme se Reconstitue Rapidement — Mais Pas Encore le Positionnement Long/Short », « Les Réserves des Exchanges Baissent, mais Cela Pourrait Être des Mouvements de Garde Institutionnelle, pas de l'Auto-Garde », « Le Prix est Calme, mais les Grands Portefeuilles Accumulent Discrètement », « L'Indicateur qui Cède le Premier à Chaque Cycle est le Taux de Financement »). Les chiffres correspondent au moment cité et peuvent évoluer en temps réel. Cet article ne constitue pas un conseil en investissement.</p>
  <p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinGlass (taxa de financiamento, índice long/short), CryptoQuant (estimativas de reservas e fluxo líquido de exchanges), análise própria do BTCtiming.com ("O Interesse em Aberto de Futuros Está se Reconstruindo Rápido — Mas o Posicionamento Long/Short Ainda Não", "As Reservas de Exchanges Estão Caindo, mas Pode Ser Movimento de Custódia Institucional, Não Autocustódia", "O Preço Está Calmo, mas Grandes Carteiras Estão Acumulando em Silêncio", "O Indicador que Quebra Primeiro em Cada Ciclo é a Taxa de Financiamento"). Os números correspondem ao momento citado e podem mudar em tempo real. Este artigo não é aconselhamento de investimento.</p>
  <p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinGlass (fonlama oranı, long/short oranı), CryptoQuant (borsa rezervi ve net akış tahminleri), BTCtiming.com'un kendi analizi ("Vadeli İşlem Açık Pozisyonu Hızla Toparlanıyor — Ama Long/Short Konumlanması Henüz Değil", "Borsa Rezervleri Düşüyor, Ancak Bu Self-Custody Değil, Kurumsal Saklama Hareketleri Olabilir", "Fiyat Sessiz, Ama Büyük Cüzdanlar Sessizce Birikim Yapıyor", "Her Döngüde İlk Kırılan Gösterge Fonlama Oranıdır"). Rakamlar belirtilen zamana aittir ve gerçek zamanlı olarak değişebilir. Bu makale yatırım tavsiyesi değildir.</p>
  <p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinGlass (tỷ lệ tài trợ, tỷ lệ long/short), CryptoQuant (ước tính dự trữ và dòng chảy ròng của sàn), phân tích riêng của BTCtiming.com ("Hợp Đồng Mở Futures Đang Phục Hồi Nhanh — Nhưng Vị Thế Long/Short Thì Chưa", "Dự Trữ Sàn Đang Giảm, Nhưng Có Thể Là Do Dịch Chuyển Lưu Ký Tổ Chức, Không Phải Tự Lưu Ký", "Giá Đang Im Ắng, Nhưng Các Ví Lớn Đang Âm Thầm Tích Lũy", "Chỉ Báo Bị Phá Vỡ Đầu Tiên Trong Mỗi Chu Kỳ Là Tỷ Lệ Tài Trợ"). Các số liệu tính đến thời điểm được trích dẫn và có thể thay đổi theo thời gian thực. Bài viết này không phải là lời khuyên đầu tư.</p>
<?php require __DIR__.'/_footer.php'; ?>
