<?php $slug = 'hyperliquid-hype-unlock-assistance-fund-absorption'; require __DIR__.'/_header.php'; ?>

  <p class="ko">파생상품 거래소 하이퍼리퀴드가 7월 6일 코어 기여자 몫으로 HYPE 토큰 992만 개를 새로 잠금 해제했다. DEXTools와 온체인 데이터 기준으로 시가 약 6억4500만 달러에 해당하는 물량이다. 그러나 시장이 이 물량을 어떻게 소화할지를 좌우하는 더 큰 숫자는 따로 있다. 거래 수수료를 HYPE로 바꿔 사들이는 프로토콜의 '어시스턴스 펀드(Assistance Fund)'가 이미 약 4565만 개의 HYPE를 보유하고 있으며, 현재가 기준 약 31억9000만 달러로 이번 언락 물량의 약 4.6배에 달한다고 온체인 집계는 밝혔다.</p>
  <p class="en">The derivatives exchange Hyperliquid unlocked 9.92 million HYPE tokens for its core contributors on July 6, a tranche worth roughly $645 million based on DEXTools and on-chain data. But the larger number that governs how the market absorbs the supply lies elsewhere: the protocol's Assistance Fund — the address that converts trading fees into HYPE purchases — already holds about 45.65 million HYPE, worth roughly $3.19 billion at current prices, or about 4.6 times the size of this unlock, according to on-chain tallies.</p>
  <p class="ja">デリバティブ取引所ハイパーリキッドが7月6日、コア貢献者向けにHYPEトークン992万枚を新たにアンロックした。DEXToolsとオンチェーンデータに基づくと時価およそ6億4500万ドルに相当する。しかし、市場がこの供給をどう消化するかを左右するより大きな数字は別にある。取引手数料をHYPEに換えて買い上げるプロトコルの「アシスタンスファンド(Assistance Fund)」がすでに約4565万枚のHYPEを保有しており、現在値換算で約31億9000万ドル、今回のアンロック量の約4.6倍に達するとオンチェーン集計は示した。</p>
  <p class="es">El exchange de derivados Hyperliquid desbloqueó 9,92 millones de tokens HYPE para sus contribuyentes principales el 6 de julio, un tramo valorado en unos 645 millones de dólares según DEXTools y datos on-chain. Pero el número mayor que determina cómo absorbe el mercado esa oferta está en otro lugar: el Fondo de Asistencia del protocolo —la dirección que convierte las comisiones de trading en compras de HYPE— ya posee cerca de 45,65 millones de HYPE, con un valor aproximado de 3.190 millones de dólares a precios actuales, unas 4,6 veces el tamaño de este desbloqueo, según los recuentos on-chain.</p>
  <p class="de">Die Derivatebörse Hyperliquid gab am 6. Juli 9,92 Millionen HYPE-Token für ihre Kernbeitragenden frei — eine Tranche im Wert von rund 645 Millionen Dollar auf Basis von DEXTools- und On-Chain-Daten. Doch die größere Zahl, die darüber entscheidet, wie der Markt das Angebot aufnimmt, liegt anderswo: Der Assistance Fund des Protokolls — die Adresse, die Handelsgebühren in HYPE-Käufe umwandelt — hält bereits etwa 45,65 Millionen HYPE im Wert von rund 3,19 Milliarden Dollar zu aktuellen Preisen, also etwa das 4,6-Fache dieser Freigabe, so die On-Chain-Auswertungen.</p>
  <p class="fr">La plateforme de dérivés Hyperliquid a débloqué 9,92 millions de tokens HYPE pour ses contributeurs principaux le 6 juillet, une tranche évaluée à environ 645 millions de dollars selon DEXTools et les données on-chain. Mais le chiffre plus important qui détermine comment le marché absorbe cette offre se situe ailleurs : le Fonds d'assistance du protocole — l'adresse qui convertit les frais de trading en achats de HYPE — détient déjà environ 45,65 millions de HYPE, soit près de 3,19 milliards de dollars aux prix actuels, environ 4,6 fois la taille de ce déblocage, selon les décomptes on-chain.</p>
  <p class="pt">A corretora de derivativos Hyperliquid desbloqueou 9,92 milhões de tokens HYPE para seus contribuidores principais em 6 de julho, um lote avaliado em cerca de 645 milhões de dólares segundo a DEXTools e dados on-chain. Mas o número maior que determina como o mercado absorve essa oferta está em outro lugar: o Fundo de Assistência do protocolo — o endereço que converte as taxas de negociação em compras de HYPE — já detém cerca de 45,65 milhões de HYPE, no valor aproximado de 3,19 bilhões de dólares a preços atuais, cerca de 4,6 vezes o tamanho deste desbloqueio, de acordo com as contagens on-chain.</p>
  <p class="tr">Türev borsası Hyperliquid, 6 Temmuz'da çekirdek katkı sağlayıcıları için 9,92 milyon HYPE token'ının kilidini açtı; DEXTools ve zincir üstü verilere göre yaklaşık 645 milyon dolar değerinde bir dilim. Ancak piyasanın bu arzı nasıl emeceğini belirleyen daha büyük sayı başka yerde: protokolün işlem ücretlerini HYPE alımlarına dönüştüren adresi olan Yardım Fonu (Assistance Fund), zincir üstü sayımlara göre halihazırda yaklaşık 45,65 milyon HYPE tutuyor; bu, güncel fiyatlarla yaklaşık 3,19 milyar dolar, yani bu kilit açılışının yaklaşık 4,6 katı ediyor.</p>
  <p class="vi">Sàn giao dịch phái sinh Hyperliquid đã mở khóa 9,92 triệu token HYPE cho các nhà đóng góp cốt lõi vào ngày 6 tháng 7, một đợt trị giá khoảng 645 triệu USD dựa trên dữ liệu của DEXTools và on-chain. Nhưng con số lớn hơn chi phối cách thị trường hấp thụ nguồn cung này lại nằm ở nơi khác: Quỹ Hỗ trợ (Assistance Fund) của giao thức — địa chỉ chuyển phí giao dịch thành các giao dịch mua HYPE — đã nắm giữ khoảng 45,65 triệu HYPE, trị giá khoảng 3,19 tỷ USD theo giá hiện tại, tức khoảng 4,6 lần quy mô đợt mở khóa này, theo các thống kê on-chain.</p>

  <div class="box ko">💡 <strong>핵심 요약:</strong> 7월 6일 언락은 992만 HYPE(약 6억4500만 달러)로, 전체 최대 공급량 약 9억5300만~10억 개의 약 1%에 해당한다. 이는 2026년 내내 이어지는 코어 기여자 대상 월간 언락 시리즈 중 한 회차이며, 각 회차 규모는 992만 개로 동일하다. 팀 배분은 전체의 23.8%로, 1년 클리프 뒤 24개월에 걸쳐 선형으로 풀린다. 이론상 매도 압력을 키우는 사건이지만, 프로토콜이 수수료의 97~99%를 자동으로 HYPE 매수에 투입해 온 구조가 반대편에 서 있다.</div>
  <div class="box en">💡 <strong>Key takeaway:</strong> The July 6 unlock is 9.92 million HYPE (about $645 million), roughly 1% of the estimated 953 million to 1 billion max supply. It is one installment in a series of monthly unlocks to core contributors that runs throughout 2026, each tranche the same 9.92 million size. The team allocation is 23.8% of the total, released over 24 months of linear vesting after a one-year cliff. In theory the event adds sell pressure, but the protocol's structure — routing 97% to 99% of fees into automatic HYPE buybacks — sits on the other side of the ledger.</div>
  <div class="box ja">💡 <strong>要点:</strong> 7月6日のアンロックは992万HYPE(約6億4500万ドル)で、最大供給量約9億5300万~10億枚の約1%に相当する。これは2026年を通じて続くコア貢献者向け月次アンロックの1回分であり、各回の規模は992万枚で同じだ。チーム配分は全体の23.8%で、1年のクリフの後24か月かけて線形に解放される。理論上は売り圧力を高める事象だが、プロトコルが手数料の97~99%を自動でHYPE買いに投入してきた構造が反対側に立つ。</div>
  <div class="box es">💡 <strong>Resumen clave:</strong> El desbloqueo del 6 de julio es de 9,92 millones de HYPE (unos 645 millones de dólares), cerca del 1% de la oferta máxima estimada de 953 millones a 1.000 millones. Es una cuota de una serie de desbloqueos mensuales para contribuyentes principales que se extiende durante todo 2026, cada tramo del mismo tamaño de 9,92 millones. La asignación del equipo es el 23,8% del total, liberada en 24 meses de vesting lineal tras un periodo de bloqueo (cliff) de un año. En teoría el evento añade presión vendedora, pero la estructura del protocolo —que canaliza del 97% al 99% de las comisiones hacia recompras automáticas de HYPE— está del otro lado.</div>
  <div class="box de">💡 <strong>Kernaussage:</strong> Die Freigabe vom 6. Juli umfasst 9,92 Millionen HYPE (rund 645 Millionen Dollar), etwa 1% des geschätzten maximalen Angebots von 953 Millionen bis 1 Milliarde. Sie ist eine Rate in einer Serie monatlicher Freigaben an Kernbeitragende, die sich über das gesamte Jahr 2026 zieht, jede Tranche mit denselben 9,92 Millionen. Die Team-Zuteilung beträgt 23,8% des Gesamten und wird über 24 Monate lineares Vesting nach einer einjährigen Cliff-Phase freigesetzt. Theoretisch erhöht das Ereignis den Verkaufsdruck, doch die Struktur des Protokolls — 97% bis 99% der Gebühren fließen in automatische HYPE-Rückkäufe — steht auf der anderen Seite.</div>
  <div class="box fr">💡 <strong>À retenir :</strong> Le déblocage du 6 juillet porte sur 9,92 millions de HYPE (environ 645 millions de dollars), soit près de 1% de l'offre maximale estimée entre 953 millions et 1 milliard. Il s'agit d'une tranche d'une série de déblocages mensuels destinés aux contributeurs principaux qui court sur toute l'année 2026, chaque tranche affichant la même taille de 9,92 millions. L'allocation de l'équipe représente 23,8% du total, libérée sur 24 mois de vesting linéaire après une période de blocage (cliff) d'un an. En théorie, l'événement ajoute une pression vendeuse, mais la structure du protocole — qui dirige 97% à 99% des frais vers des rachats automatiques de HYPE — se tient de l'autre côté.</div>
  <div class="box pt">💡 <strong>Resumo:</strong> O desbloqueio de 6 de julho é de 9,92 milhões de HYPE (cerca de 645 milhões de dólares), aproximadamente 1% da oferta máxima estimada de 953 milhões a 1 bilhão. É uma parcela de uma série de desbloqueios mensais para contribuidores principais que se estende por todo o ano de 2026, cada lote com o mesmo tamanho de 9,92 milhões. A alocação da equipe é de 23,8% do total, liberada ao longo de 24 meses de vesting linear após um período de carência (cliff) de um ano. Em teoria, o evento adiciona pressão vendedora, mas a estrutura do protocolo — que direciona de 97% a 99% das taxas para recompras automáticas de HYPE — está do outro lado.</div>
  <div class="box tr">💡 <strong>Öne çıkanlar:</strong> 6 Temmuz kilidi 9,92 milyon HYPE (yaklaşık 645 milyon dolar) olup, tahmini 953 milyon–1 milyar azami arzın yaklaşık %1'ine denk gelir. Bu, 2026 boyunca süren çekirdek katkı sağlayıcılarına yönelik aylık kilit açılışları serisinin bir taksitidir ve her dilim aynı 9,92 milyon büyüklüğündedir. Ekip tahsisi toplamın %23,8'idir ve bir yıllık cliff süresinin ardından 24 ay boyunca doğrusal olarak serbest bırakılır. Teoride bu olay satış baskısını artırır, ancak ücretlerin %97–99'unu otomatik HYPE geri alımlarına yönlendiren protokol yapısı defterin diğer tarafında durur.</div>
  <div class="box vi">💡 <strong>Điểm chính:</strong> Đợt mở khóa ngày 6 tháng 7 là 9,92 triệu HYPE (khoảng 645 triệu USD), tương đương khoảng 1% nguồn cung tối đa ước tính từ 953 triệu đến 1 tỷ. Đây là một phần trong chuỗi các đợt mở khóa hàng tháng cho các nhà đóng góp cốt lõi kéo dài suốt năm 2026, mỗi đợt đều cùng quy mô 9,92 triệu. Phần phân bổ cho đội ngũ là 23,8% tổng cung, được giải phóng trong 24 tháng vesting tuyến tính sau thời gian khóa (cliff) một năm. Về lý thuyết, sự kiện này làm tăng áp lực bán, nhưng cấu trúc của giao thức — chuyển 97% đến 99% phí vào việc mua lại HYPE tự động — lại đứng ở phía bên kia.</div>

  <div class="ko">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">7월 언락 vs 어시스턴스 펀드의 흡수 여력 (달러)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">7/6 언락 (992만 HYPE)</text>
      <rect x="230" y="60" width="91" height="24" rx="3" fill="#f87171"/>
      <text x="331" y="77" fill="#fca5a5" font-size="13" font-weight="700">6.45억 달러</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">어시스턴스 펀드 보유 (4565만 HYPE)</text>
      <rect x="230" y="108" width="450" height="24" rx="3" fill="#34d399"/>
      <text x="230" y="125" fill="#052e16" font-size="13" font-weight="700" text-anchor="start" dx="6">31.9억 달러 (언락의 약 4.6배)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">분기별 HYPE 매입 규모 (수수료 재투입)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">2025년 3분기</text>
      <rect x="200" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="525" y="234" fill="#7dd3fc" font-size="13" font-weight="700">3.17억 달러</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">2025년 4분기</text>
      <rect x="200" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="463" y="272" fill="#7dd3fc" font-size="13" font-weight="700">2.55억 달러</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">2026년 1분기</text>
      <rect x="200" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="400" y="310" fill="#7dd3fc" font-size="13" font-weight="700">1.92억 달러</text>
      <text x="20" y="352" fill="#71717a" font-size="12">막대 길이는 달러 금액에 비례. 매입 규모는 거래량에 연동돼 분기마다 감소해 왔다.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">출처: DEXTools 온체인 데이터, 하이퍼리퀴드 어시스턴스 펀드 주소.</text>
    </g>
  </svg>
  </div>
  <div class="en">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">July unlock vs. the Assistance Fund's absorption capacity (USD)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">Jul 6 unlock (9.92M HYPE)</text>
      <rect x="250" y="60" width="91" height="24" rx="3" fill="#f87171"/>
      <text x="351" y="77" fill="#fca5a5" font-size="13" font-weight="700">$645M</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">Assistance Fund holdings (45.65M HYPE)</text>
      <rect x="250" y="108" width="430" height="24" rx="3" fill="#34d399"/>
      <text x="256" y="125" fill="#052e16" font-size="13" font-weight="700">$3.19B (~4.6x the unlock)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">Quarterly HYPE buybacks (fees recycled)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">Q3 2025</text>
      <rect x="150" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="475" y="234" fill="#7dd3fc" font-size="13" font-weight="700">$317M</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">Q4 2025</text>
      <rect x="150" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="413" y="272" fill="#7dd3fc" font-size="13" font-weight="700">$255M</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">Q1 2026</text>
      <rect x="150" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="350" y="310" fill="#7dd3fc" font-size="13" font-weight="700">$192M</text>
      <text x="20" y="352" fill="#71717a" font-size="12">Bar length is proportional to dollar amount. Buybacks track volume and have fallen each quarter.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">Source: DEXTools on-chain data; Hyperliquid Assistance Fund address.</text>
    </g>
  </svg>
  </div>
  <div class="ja">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">7月アンロック vs アシスタンスファンドの吸収余力 (ドル)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">7/6 アンロック (992万HYPE)</text>
      <rect x="250" y="60" width="91" height="24" rx="3" fill="#f87171"/>
      <text x="351" y="77" fill="#fca5a5" font-size="13" font-weight="700">6.45億ドル</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">ファンド保有 (4565万HYPE)</text>
      <rect x="250" y="108" width="430" height="24" rx="3" fill="#34d399"/>
      <text x="256" y="125" fill="#052e16" font-size="13" font-weight="700">31.9億ドル (約4.6倍)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">四半期別HYPE買い(手数料の再投入)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">2025年 第3四半期</text>
      <rect x="200" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="525" y="234" fill="#7dd3fc" font-size="13" font-weight="700">3.17億ドル</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">2025年 第4四半期</text>
      <rect x="200" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="463" y="272" fill="#7dd3fc" font-size="13" font-weight="700">2.55億ドル</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">2026年 第1四半期</text>
      <rect x="200" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="400" y="310" fill="#7dd3fc" font-size="13" font-weight="700">1.92億ドル</text>
      <text x="20" y="352" fill="#71717a" font-size="12">棒の長さはドル額に比例。買い規模は取引量に連動し四半期ごとに減少してきた。</text>
      <text x="20" y="374" fill="#71717a" font-size="12">出典: DEXToolsオンチェーンデータ、ハイパーリキッドのアシスタンスファンドアドレス。</text>
    </g>
  </svg>
  </div>
  <div class="es">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Desbloqueo de julio vs. capacidad de absorción del fondo (USD)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">Desbloqueo 6 jul (9,92M HYPE)</text>
      <rect x="270" y="60" width="82" height="24" rx="3" fill="#f87171"/>
      <text x="362" y="77" fill="#fca5a5" font-size="13" font-weight="700">645M $</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">Fondo de Asistencia (45,65M HYPE)</text>
      <rect x="270" y="108" width="410" height="24" rx="3" fill="#34d399"/>
      <text x="276" y="125" fill="#052e16" font-size="13" font-weight="700">3.190M $ (~4,6x)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">Recompras trimestrales de HYPE (comisiones)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">3T 2025</text>
      <rect x="160" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="485" y="234" fill="#7dd3fc" font-size="13" font-weight="700">317M $</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">4T 2025</text>
      <rect x="160" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="423" y="272" fill="#7dd3fc" font-size="13" font-weight="700">255M $</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">1T 2026</text>
      <rect x="160" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="360" y="310" fill="#7dd3fc" font-size="13" font-weight="700">192M $</text>
      <text x="20" y="352" fill="#71717a" font-size="12">La longitud es proporcional al monto en dólares. Las recompras siguen al volumen y han caído cada trimestre.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">Fuente: datos on-chain de DEXTools; dirección del Fondo de Asistencia de Hyperliquid.</text>
    </g>
  </svg>
  </div>
  <div class="de">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Juli-Freigabe vs. Absorptionskapazität des Fonds (USD)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">Freigabe 6. Juli (9,92 Mio. HYPE)</text>
      <rect x="290" y="60" width="82" height="24" rx="3" fill="#f87171"/>
      <text x="382" y="77" fill="#fca5a5" font-size="13" font-weight="700">645 Mio. $</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">Assistance Fund (45,65 Mio. HYPE)</text>
      <rect x="290" y="108" width="390" height="24" rx="3" fill="#34d399"/>
      <text x="296" y="125" fill="#052e16" font-size="13" font-weight="700">3,19 Mrd. $ (~4,6x)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">Quartals-Rückkäufe von HYPE (Gebühren)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">Q3 2025</text>
      <rect x="150" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="475" y="234" fill="#7dd3fc" font-size="13" font-weight="700">317 Mio. $</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">Q4 2025</text>
      <rect x="150" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="413" y="272" fill="#7dd3fc" font-size="13" font-weight="700">255 Mio. $</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">Q1 2026</text>
      <rect x="150" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="350" y="310" fill="#7dd3fc" font-size="13" font-weight="700">192 Mio. $</text>
      <text x="20" y="352" fill="#71717a" font-size="12">Balkenlänge proportional zum Dollarbetrag. Rückkäufe folgen dem Volumen und sanken je Quartal.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">Quelle: On-Chain-Daten von DEXTools; Assistance-Fund-Adresse von Hyperliquid.</text>
    </g>
  </svg>
  </div>
  <div class="fr">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Déblocage de juillet vs. capacité d'absorption du fonds (USD)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">Déblocage 6 juil. (9,92M HYPE)</text>
      <rect x="290" y="60" width="82" height="24" rx="3" fill="#f87171"/>
      <text x="382" y="77" fill="#fca5a5" font-size="13" font-weight="700">645M $</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">Fonds d'assistance (45,65M HYPE)</text>
      <rect x="290" y="108" width="390" height="24" rx="3" fill="#34d399"/>
      <text x="296" y="125" fill="#052e16" font-size="13" font-weight="700">3,19 Mrd $ (~4,6x)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">Rachats trimestriels de HYPE (frais)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">T3 2025</text>
      <rect x="150" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="475" y="234" fill="#7dd3fc" font-size="13" font-weight="700">317M $</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">T4 2025</text>
      <rect x="150" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="413" y="272" fill="#7dd3fc" font-size="13" font-weight="700">255M $</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">T1 2026</text>
      <rect x="150" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="350" y="310" fill="#7dd3fc" font-size="13" font-weight="700">192M $</text>
      <text x="20" y="352" fill="#71717a" font-size="12">La longueur est proportionnelle au montant en dollars. Les rachats suivent le volume et baissent chaque trimestre.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">Source : données on-chain de DEXTools ; adresse du Fonds d'assistance de Hyperliquid.</text>
    </g>
  </svg>
  </div>
  <div class="pt">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Desbloqueio de julho vs. capacidade de absorção do fundo (USD)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">Desbloqueio 6 jul (9,92M HYPE)</text>
      <rect x="290" y="60" width="82" height="24" rx="3" fill="#f87171"/>
      <text x="382" y="77" fill="#fca5a5" font-size="13" font-weight="700">645M $</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">Fundo de Assistência (45,65M HYPE)</text>
      <rect x="290" y="108" width="390" height="24" rx="3" fill="#34d399"/>
      <text x="296" y="125" fill="#052e16" font-size="13" font-weight="700">3,19 bi $ (~4,6x)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">Recompras trimestrais de HYPE (taxas)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">3T 2025</text>
      <rect x="150" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="475" y="234" fill="#7dd3fc" font-size="13" font-weight="700">317M $</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">4T 2025</text>
      <rect x="150" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="413" y="272" fill="#7dd3fc" font-size="13" font-weight="700">255M $</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">1T 2026</text>
      <rect x="150" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="350" y="310" fill="#7dd3fc" font-size="13" font-weight="700">192M $</text>
      <text x="20" y="352" fill="#71717a" font-size="12">O comprimento é proporcional ao valor em dólares. As recompras acompanham o volume e caíram a cada trimestre.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">Fonte: dados on-chain da DEXTools; endereço do Fundo de Assistência da Hyperliquid.</text>
    </g>
  </svg>
  </div>
  <div class="tr">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Temmuz kilidi vs. fonun emme kapasitesi (USD)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">6 Tem kilidi (9,92M HYPE)</text>
      <rect x="270" y="60" width="82" height="24" rx="3" fill="#f87171"/>
      <text x="362" y="77" fill="#fca5a5" font-size="13" font-weight="700">645M $</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">Yardım Fonu (45,65M HYPE)</text>
      <rect x="270" y="108" width="410" height="24" rx="3" fill="#34d399"/>
      <text x="276" y="125" fill="#052e16" font-size="13" font-weight="700">3,19 milyar $ (~4,6x)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">Üç aylık HYPE geri alımları (ücretler)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">2025 3Ç</text>
      <rect x="150" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="475" y="234" fill="#7dd3fc" font-size="13" font-weight="700">317M $</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">2025 4Ç</text>
      <rect x="150" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="413" y="272" fill="#7dd3fc" font-size="13" font-weight="700">255M $</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">2026 1Ç</text>
      <rect x="150" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="350" y="310" fill="#7dd3fc" font-size="13" font-weight="700">192M $</text>
      <text x="20" y="352" fill="#71717a" font-size="12">Çubuk uzunluğu dolar tutarıyla orantılıdır. Geri alımlar hacme bağlıdır ve her çeyrek düşmüştür.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">Kaynak: DEXTools zincir üstü verileri; Hyperliquid Yardım Fonu adresi.</text>
    </g>
  </svg>
  </div>
  <div class="vi">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Đợt mở khóa tháng 7 vs. khả năng hấp thụ của quỹ (USD)</text>
    <g font-family="sans-serif">
      <text x="20" y="72" fill="#a1a1aa" font-size="13">Mở khóa 6/7 (9,92 triệu HYPE)</text>
      <rect x="290" y="60" width="82" height="24" rx="3" fill="#f87171"/>
      <text x="382" y="77" fill="#fca5a5" font-size="13" font-weight="700">645 triệu $</text>
      <text x="20" y="120" fill="#a1a1aa" font-size="13">Quỹ Hỗ trợ (45,65 triệu HYPE)</text>
      <rect x="290" y="108" width="390" height="24" rx="3" fill="#34d399"/>
      <text x="296" y="125" fill="#052e16" font-size="13" font-weight="700">3,19 tỷ $ (~4,6 lần)</text>
      <line x1="20" y1="156" x2="680" y2="156" stroke="rgba(255,255,255,.1)"/>
      <text x="20" y="188" fill="#e4e4e7" font-size="14" font-weight="700">Mua lại HYPE theo quý (tái đầu tư phí)</text>
      <text x="20" y="230" fill="#a1a1aa" font-size="13">Q3 2025</text>
      <rect x="150" y="218" width="317" height="20" rx="3" fill="#38bdf8"/>
      <text x="475" y="234" fill="#7dd3fc" font-size="13" font-weight="700">317 triệu $</text>
      <text x="20" y="268" fill="#a1a1aa" font-size="13">Q4 2025</text>
      <rect x="150" y="256" width="255" height="20" rx="3" fill="#38bdf8"/>
      <text x="413" y="272" fill="#7dd3fc" font-size="13" font-weight="700">255 triệu $</text>
      <text x="20" y="306" fill="#a1a1aa" font-size="13">Q1 2026</text>
      <rect x="150" y="294" width="192" height="20" rx="3" fill="#38bdf8"/>
      <text x="350" y="310" fill="#7dd3fc" font-size="13" font-weight="700">192 triệu $</text>
      <text x="20" y="352" fill="#71717a" font-size="12">Độ dài thanh tỷ lệ với số tiền USD. Việc mua lại bám theo khối lượng và đã giảm mỗi quý.</text>
      <text x="20" y="374" fill="#71717a" font-size="12">Nguồn: dữ liệu on-chain của DEXTools; địa chỉ Quỹ Hỗ trợ của Hyperliquid.</text>
    </g>
  </svg>
  </div>

  <h2 class="ko">언락으로 무엇이, 얼마나 풀렸나</h2>
  <h2 class="en">What Unlocked, and How Much</h2>
  <h2 class="ja">アンロックで何が、どれだけ解放されたか</h2>
  <h2 class="es">Qué se Desbloqueó y Cuánto</h2>
  <h2 class="de">Was Freigegeben Wurde und Wie Viel</h2>
  <h2 class="fr">Ce Qui a Été Débloqué, et Combien</h2>
  <h2 class="pt">O Que Foi Desbloqueado, e Quanto</h2>
  <h2 class="tr">Kilit Neyi ve Ne Kadar Açtı</h2>
  <h2 class="vi">Đợt Mở Khóa Đã Giải Phóng Gì, Bao Nhiêu</h2>

  <p class="ko">7월 6일 풀린 992만 HYPE는 하이퍼리퀴드가 초기부터 예고해온 코어 기여자 배분 일정의 한 회차다. tokenomist·DefiLlama 등 베스팅 추적 사이트에 따르면, 이 배분은 발행 당시 정해진 1년 클리프(cliff)를 지난 뒤 24개월에 걸쳐 매달 같은 크기로 선형 해제되며, 각 회차 규모는 992만 개로 고정돼 2027년까지 이어진다. 팀·코어 기여자 몫은 총공급의 23.8%에 해당한다. 즉 이번 물량은 갑작스러운 이벤트가 아니라, 시장이 몇 달 전부터 날짜와 수량을 알고 있던 예정된 공급이다.</p>
  <p class="en">The 9.92 million HYPE released on July 6 is one installment in the core-contributor allocation schedule Hyperliquid has flagged since its launch. According to vesting trackers such as tokenomist and DefiLlama, the allocation unlocks linearly in equal monthly amounts over 24 months after a one-year cliff set at issuance, with each tranche fixed at 9.92 million and the schedule running into 2027. The team and core-contributor share amounts to 23.8% of total supply. In other words, this is not a sudden event but scheduled supply whose date and size the market has known for months.</p>
  <p class="ja">7月6日に解放された992万HYPEは、ハイパーリキッドが立ち上げ当初から示してきたコア貢献者向け配分スケジュールの1回分だ。tokenomistやDefiLlamaなどのベスティング追跡サイトによれば、この配分は発行時に定められた1年のクリフを過ぎた後、24か月にわたり毎月同じ規模で線形に解放され、各回の規模は992万枚に固定され、スケジュールは2027年まで続く。チーム・コア貢献者の取り分は総供給の23.8%に当たる。つまり今回の量は突発的なイベントではなく、市場が数か月前から日付と数量を把握していた予定された供給だ。</p>
  <p class="es">Los 9,92 millones de HYPE liberados el 6 de julio son una cuota del calendario de asignación a contribuyentes principales que Hyperliquid ha señalado desde su lanzamiento. Según rastreadores de vesting como tokenomist y DefiLlama, la asignación se desbloquea de forma lineal en montos mensuales iguales durante 24 meses tras un cliff de un año fijado en la emisión, con cada tramo fijado en 9,92 millones y el calendario extendiéndose hasta 2027. La parte del equipo y los contribuyentes principales equivale al 23,8% de la oferta total. Es decir, esto no es un evento repentino sino oferta programada cuya fecha y tamaño el mercado conocía desde hacía meses.</p>
  <p class="de">Die am 6. Juli freigegebenen 9,92 Millionen HYPE sind eine Rate im Zuteilungsplan für Kernbeitragende, den Hyperliquid seit dem Start angekündigt hat. Laut Vesting-Trackern wie tokenomist und DefiLlama wird die Zuteilung nach einer bei der Ausgabe festgelegten einjährigen Cliff-Phase über 24 Monate linear in gleichen monatlichen Beträgen freigesetzt, jede Tranche fixiert auf 9,92 Millionen, und der Plan reicht bis 2027. Der Anteil von Team und Kernbeitragenden beläuft sich auf 23,8% des Gesamtangebots. Mit anderen Worten: Dies ist kein plötzliches Ereignis, sondern geplantes Angebot, dessen Datum und Umfang der Markt seit Monaten kannte.</p>
  <p class="fr">Les 9,92 millions de HYPE libérés le 6 juillet constituent une tranche du calendrier d'allocation aux contributeurs principaux que Hyperliquid a annoncé depuis son lancement. Selon des traqueurs de vesting comme tokenomist et DefiLlama, l'allocation se débloque de manière linéaire en montants mensuels égaux sur 24 mois après un cliff d'un an fixé à l'émission, chaque tranche étant fixée à 9,92 millions et le calendrier s'étendant jusqu'en 2027. La part de l'équipe et des contributeurs principaux représente 23,8% de l'offre totale. Autrement dit, il ne s'agit pas d'un événement soudain mais d'une offre programmée dont le marché connaît la date et la taille depuis des mois.</p>
  <p class="pt">Os 9,92 milhões de HYPE liberados em 6 de julho são uma parcela do cronograma de alocação a contribuidores principais que a Hyperliquid vem sinalizando desde o lançamento. Segundo rastreadores de vesting como tokenomist e DefiLlama, a alocação é desbloqueada de forma linear em montantes mensais iguais ao longo de 24 meses após um cliff de um ano fixado na emissão, com cada lote fixado em 9,92 milhões e o cronograma se estendendo até 2027. A parcela da equipe e dos contribuidores principais equivale a 23,8% da oferta total. Ou seja, isto não é um evento repentino, mas oferta programada cuja data e tamanho o mercado conhecia havia meses.</p>
  <p class="tr">6 Temmuz'da serbest bırakılan 9,92 milyon HYPE, Hyperliquid'in lansmanından bu yana işaret ettiği çekirdek katkı sağlayıcı tahsis takviminin bir taksitidir. tokenomist ve DefiLlama gibi vesting takip sitelerine göre bu tahsis, ihraç sırasında belirlenen bir yıllık cliff sonrasında 24 ay boyunca eşit aylık miktarlarla doğrusal olarak açılır; her dilim 9,92 milyon olarak sabittir ve takvim 2027'ye kadar uzanır. Ekip ve çekirdek katkı sağlayıcı payı toplam arzın %23,8'ine denk gelir. Başka bir deyişle bu ani bir olay değil, piyasanın tarihini ve büyüklüğünü aylardır bildiği planlı bir arzdır.</p>
  <p class="vi">9,92 triệu HYPE được giải phóng vào ngày 6 tháng 7 là một phần trong lịch phân bổ cho nhà đóng góp cốt lõi mà Hyperliquid đã báo hiệu kể từ khi ra mắt. Theo các trang theo dõi vesting như tokenomist và DefiLlama, phần phân bổ này mở khóa tuyến tính theo các khoản bằng nhau hằng tháng trong 24 tháng sau thời gian cliff một năm được ấn định lúc phát hành, mỗi đợt cố định 9,92 triệu và lịch trình kéo dài đến năm 2027. Phần của đội ngũ và nhà đóng góp cốt lõi chiếm 23,8% tổng cung. Nói cách khác, đây không phải là một sự kiện đột ngột mà là nguồn cung theo kế hoạch mà thị trường đã biết ngày tháng và quy mô từ nhiều tháng trước.</p>

  <p class="ko">규모를 가늠하려면 두 가지 기준선을 봐야 한다. 첫째, 이번 992만 개는 최대 공급량(약 9억5300만~10억 개)의 약 1%에 불과하다. 둘째, 그러나 이는 시장에 실제로 유통되는 물량이 아니라 '수령자에게 잠금이 풀린' 물량이라는 점이다. 잠금이 풀렸다고 곧바로 매도되는 것은 아니며, 코어 기여자들이 실제로 얼마를 언제 파는지는 온체인에서 사후적으로만 확인된다. 실제로 하이퍼리퀴드 팀은 2026년 초까지 자신들 몫의 99%를 팔지 않고 보유해 왔다는 것이 온체인 데이터로 확인되는데, 이는 장기 정렬(alignment)의 신호로 읽히는 동시에, 언젠가 풀릴 수 있는 잠재적 매도 물량이 계속 쌓여 있다는 뜻이기도 하다.</p>
  <p class="en">Gauging the size requires two reference points. First, these 9.92 million are only about 1% of the max supply (roughly 953 million to 1 billion). Second — and more important — this is not supply that actually circulates but supply that has been unlocked to recipients. An unlock is not an immediate sale, and how much core contributors actually sell, and when, can only be confirmed after the fact on-chain. In practice, on-chain data shows the Hyperliquid team held about 99% of its allocation unsold through early 2026, which reads as a signal of long-term alignment while also meaning that a potential overhang of sellable tokens keeps accumulating.</p>
  <p class="ja">規模を測るには2つの基準線が要る。第一に、今回の992万枚は最大供給量(約9億5300万~10億枚)のわずか約1%にすぎない。第二に、しかしこれは実際に市場に流通する量ではなく「受領者に対してロックが解除された」量だという点だ。ロック解除が即座の売却を意味するわけではなく、コア貢献者が実際にいくらをいつ売るかはオンチェーンで事後的にしか確認できない。実際、ハイパーリキッドのチームは2026年初頭まで自らの取り分の99%を売らずに保有してきたことがオンチェーンデータで確認されており、これは長期的な整合(アライメント)の signal と読める一方、いずれ放出されうる潜在的な売り物量が積み上がり続けていることも意味する。</p>
  <p class="es">Calibrar el tamaño exige dos puntos de referencia. Primero, estos 9,92 millones son solo cerca del 1% de la oferta máxima (unos 953 millones a 1.000 millones). Segundo —y más importante—, no es oferta que circula realmente sino oferta que se ha desbloqueado a los receptores. Un desbloqueo no es una venta inmediata, y cuánto venden realmente los contribuyentes principales, y cuándo, solo puede confirmarse a posteriori on-chain. En la práctica, los datos on-chain muestran que el equipo de Hyperliquid mantuvo sin vender cerca del 99% de su asignación hasta principios de 2026, lo que se lee como señal de alineación a largo plazo y a la vez significa que un posible excedente de tokens vendibles sigue acumulándose.</p>
  <p class="de">Um die Größe einzuschätzen, braucht es zwei Bezugspunkte. Erstens sind diese 9,92 Millionen nur etwa 1% des maximalen Angebots (rund 953 Millionen bis 1 Milliarde). Zweitens — und wichtiger — handelt es sich nicht um tatsächlich zirkulierendes Angebot, sondern um Angebot, das an Empfänger freigegeben wurde. Eine Freigabe ist kein sofortiger Verkauf, und wie viel Kernbeitragende tatsächlich verkaufen und wann, lässt sich erst im Nachhinein on-chain bestätigen. In der Praxis zeigen On-Chain-Daten, dass das Hyperliquid-Team bis Anfang 2026 etwa 99% seiner Zuteilung unverkauft hielt, was als Signal langfristiger Ausrichtung gelesen wird, zugleich aber bedeutet, dass sich ein potenzieller Überhang verkaufbarer Token weiter anhäuft.</p>
  <p class="fr">Évaluer la taille exige deux points de référence. Premièrement, ces 9,92 millions ne représentent qu'environ 1% de l'offre maximale (soit 953 millions à 1 milliard). Deuxièmement — et c'est plus important — il ne s'agit pas d'offre qui circule réellement mais d'offre débloquée au profit des bénéficiaires. Un déblocage n'est pas une vente immédiate, et combien les contributeurs principaux vendent réellement, et quand, ne peut être confirmé qu'a posteriori on-chain. En pratique, les données on-chain montrent que l'équipe de Hyperliquid a conservé sans les vendre environ 99% de son allocation jusqu'au début 2026, ce qui se lit comme un signal d'alignement à long terme tout en signifiant qu'un excédent potentiel de tokens vendables continue de s'accumuler.</p>
  <p class="pt">Avaliar o tamanho exige dois pontos de referência. Primeiro, esses 9,92 milhões são apenas cerca de 1% da oferta máxima (aproximadamente 953 milhões a 1 bilhão). Segundo — e mais importante —, não é oferta que de fato circula, mas oferta que foi desbloqueada aos beneficiários. Um desbloqueio não é uma venda imediata, e quanto os contribuidores principais realmente vendem, e quando, só pode ser confirmado a posteriori on-chain. Na prática, os dados on-chain mostram que a equipe da Hyperliquid manteve sem vender cerca de 99% de sua alocação até o início de 2026, o que se lê como sinal de alinhamento de longo prazo e, ao mesmo tempo, significa que um potencial excedente de tokens vendáveis continua se acumulando.</p>
  <p class="tr">Büyüklüğü ölçmek iki referans noktası gerektirir. Birincisi, bu 9,92 milyon, azami arzın (yaklaşık 953 milyon–1 milyar) yalnızca yaklaşık %1'idir. İkincisi — ve daha önemlisi — bu, gerçekten dolaşımdaki arz değil, alıcılara kilidi açılmış arzdır. Kilit açılışı anında satış anlamına gelmez ve çekirdek katkı sağlayıcıların gerçekte ne kadar ve ne zaman sattığı ancak sonradan zincir üstünde doğrulanabilir. Uygulamada zincir üstü veriler, Hyperliquid ekibinin 2026 başına kadar tahsisinin yaklaşık %99'unu satmadan tuttuğunu gösteriyor; bu, uzun vadeli hizalanmanın işareti olarak okunurken aynı zamanda ileride serbest kalabilecek potansiyel bir satılabilir token fazlasının birikmeye devam ettiği anlamına gelir.</p>
  <p class="vi">Để đánh giá quy mô cần hai điểm tham chiếu. Thứ nhất, 9,92 triệu này chỉ khoảng 1% nguồn cung tối đa (khoảng 953 triệu đến 1 tỷ). Thứ hai — và quan trọng hơn — đây không phải nguồn cung thực sự lưu thông mà là nguồn cung đã được mở khóa cho người nhận. Mở khóa không phải là bán ngay, và các nhà đóng góp cốt lõi thực sự bán bao nhiêu, khi nào, chỉ có thể xác nhận sau đó trên chuỗi. Trên thực tế, dữ liệu on-chain cho thấy đội ngũ Hyperliquid đã giữ khoảng 99% phần phân bổ của mình không bán cho đến đầu năm 2026, điều này được đọc như tín hiệu về sự gắn kết dài hạn, đồng thời cũng có nghĩa là một lượng token có thể bán tiềm ẩn vẫn tiếp tục tích lũy.</p>

  <h2 class="ko">어시스턴스 펀드라는 매수 엔진은 어떻게 작동하는가</h2>
  <h2 class="en">How the Assistance Fund Buyback Engine Works</h2>
  <h2 class="ja">アシスタンスファンドという買いエンジンはどう機能するか</h2>
  <h2 class="es">Cómo Funciona el Motor de Recompra del Fondo de Asistencia</h2>
  <h2 class="de">Wie die Rückkauf-Maschine des Assistance Fund Funktioniert</h2>
  <h2 class="fr">Comment Fonctionne le Moteur de Rachat du Fonds d'Assistance</h2>
  <h2 class="pt">Como Funciona o Motor de Recompra do Fundo de Assistência</h2>
  <h2 class="tr">Yardım Fonu Geri Alım Motoru Nasıl Çalışır</h2>
  <h2 class="vi">Động Cơ Mua Lại của Quỹ Hỗ Trợ Hoạt Động Ra Sao</h2>

  <p class="ko">언락의 반대편을 이해하려면 하이퍼리퀴드의 수익 구조를 한 단계 더 파고들 필요가 있다. 하이퍼리퀴드는 자체 레이어1 위에서 무기한 선물(perpetual futures)을 거래하는 탈중앙화 거래소이며, 거기서 발생하는 거래 수수료를 대부분 외부 투자자에게 배당하지 않고 '어시스턴스 펀드'라는 온체인 주소로 보낸다. 이 주소는 받은 수수료로 공개 시장에서 HYPE를 사들이고, 매입한 토큰은 유통에서 제거된 것으로 간주된다. DEXTools의 온체인 집계에 따르면 이 방식으로 펀드가 축적한 HYPE는 약 4565만 개, 약 31억9000만 달러에 이르며, 하이퍼리퀴드는 수수료의 약 97~99%를 이 매입에 투입해 온 것으로 보고됐다. 구조적으로 이는 거래가 일어날 때마다 자동으로 발동되는 상시 매수 주문에 가깝다.</p>
  <p class="en">Understanding the other side of the unlock requires digging one level deeper into how Hyperliquid makes money. Hyperliquid is a decentralized exchange for perpetual futures running on its own layer-1, and rather than paying most of the resulting trading fees out to outside investors, it sends them to an on-chain address called the Assistance Fund. That address uses the fees to buy HYPE on the open market, and the purchased tokens are treated as removed from circulation. By DEXTools' on-chain count, the fund has accumulated about 45.65 million HYPE, worth roughly $3.19 billion, and Hyperliquid is reported to route about 97% to 99% of fees into these purchases. Structurally, this behaves like a standing buy order that fires automatically every time a trade occurs.</p>
  <p class="ja">アンロックの反対側を理解するには、ハイパーリキッドの収益構造をもう一段掘り下げる必要がある。ハイパーリキッドは独自のレイヤー1上で無期限先物(パーペチュアル)を取引する分散型取引所であり、そこで生じる取引手数料の大半を外部投資家に配当せず、「アシスタンスファンド」というオンチェーンアドレスに送る。このアドレスは受け取った手数料で公開市場からHYPEを買い、購入したトークンは流通から除外されたとみなされる。DEXToolsのオンチェーン集計によれば、この方式でファンドが蓄積したHYPEは約4565万枚、約31億9000万ドルに達し、ハイパーリキッドは手数料の約97~99%をこの買いに投入してきたと報告される。構造的には、取引が起きるたびに自動的に発動する常設の買い注文に近い。</p>
  <p class="es">Entender el otro lado del desbloqueo exige profundizar un nivel más en cómo gana dinero Hyperliquid. Hyperliquid es un exchange descentralizado de futuros perpetuos que corre sobre su propia layer-1 y, en lugar de repartir la mayor parte de las comisiones de trading resultantes a inversores externos, las envía a una dirección on-chain llamada Fondo de Asistencia. Esa dirección usa las comisiones para comprar HYPE en el mercado abierto, y los tokens comprados se consideran retirados de la circulación. Según el recuento on-chain de DEXTools, el fondo ha acumulado cerca de 45,65 millones de HYPE, por un valor aproximado de 3.190 millones de dólares, y se informa que Hyperliquid canaliza cerca del 97% al 99% de las comisiones hacia estas compras. Estructuralmente, esto se comporta como una orden de compra permanente que se dispara automáticamente cada vez que ocurre una operación.</p>
  <p class="de">Um die andere Seite der Freigabe zu verstehen, muss man eine Ebene tiefer betrachten, wie Hyperliquid Geld verdient. Hyperliquid ist eine dezentrale Börse für unbefristete Futures (Perpetuals) auf einer eigenen Layer-1, und statt die meisten der daraus entstehenden Handelsgebühren an externe Investoren auszuschütten, sendet es sie an eine On-Chain-Adresse namens Assistance Fund. Diese Adresse nutzt die Gebühren, um HYPE am offenen Markt zu kaufen, und die gekauften Token gelten als aus dem Umlauf entfernt. Nach der On-Chain-Zählung von DEXTools hat der Fonds etwa 45,65 Millionen HYPE im Wert von rund 3,19 Milliarden Dollar angesammelt, und Hyperliquid soll etwa 97% bis 99% der Gebühren in diese Käufe leiten. Strukturell verhält sich das wie eine ständige Kauforder, die automatisch bei jedem Handel ausgelöst wird.</p>
  <p class="fr">Comprendre l'autre côté du déblocage exige de creuser d'un niveau la façon dont Hyperliquid gagne de l'argent. Hyperliquid est une bourse décentralisée de contrats à terme perpétuels fonctionnant sur sa propre layer-1 et, plutôt que de reverser la majeure partie des frais de trading à des investisseurs externes, elle les envoie à une adresse on-chain appelée Fonds d'assistance. Cette adresse utilise les frais pour acheter du HYPE sur le marché libre, et les tokens achetés sont considérés comme retirés de la circulation. Selon le décompte on-chain de DEXTools, le fonds a accumulé environ 45,65 millions de HYPE, d'une valeur d'environ 3,19 milliards de dollars, et Hyperliquid dirigerait environ 97% à 99% des frais vers ces achats. Structurellement, cela se comporte comme un ordre d'achat permanent qui se déclenche automatiquement à chaque transaction.</p>
  <p class="pt">Entender o outro lado do desbloqueio exige aprofundar um nível em como a Hyperliquid ganha dinheiro. A Hyperliquid é uma corretora descentralizada de futuros perpétuos que roda sobre sua própria layer-1 e, em vez de distribuir a maior parte das taxas de negociação resultantes a investidores externos, as envia para um endereço on-chain chamado Fundo de Assistência. Esse endereço usa as taxas para comprar HYPE no mercado aberto, e os tokens comprados são considerados retirados de circulação. Pela contagem on-chain da DEXTools, o fundo acumulou cerca de 45,65 milhões de HYPE, no valor aproximado de 3,19 bilhões de dólares, e relata-se que a Hyperliquid direciona cerca de 97% a 99% das taxas para essas compras. Estruturalmente, isso se comporta como uma ordem de compra permanente que dispara automaticamente cada vez que ocorre uma negociação.</p>
  <p class="tr">Kilit açılışının diğer tarafını anlamak, Hyperliquid'in nasıl para kazandığını bir kademe daha derine inerek incelemeyi gerektirir. Hyperliquid, kendi layer-1'i üzerinde çalışan, süresiz vadeli işlemler (perpetual) için bir merkeziyetsiz borsadır ve ortaya çıkan işlem ücretlerinin çoğunu dış yatırımcılara dağıtmak yerine, Yardım Fonu adlı bir zincir üstü adrese gönderir. Bu adres, ücretleri açık piyasada HYPE almak için kullanır ve satın alınan token'lar dolaşımdan çıkarılmış sayılır. DEXTools'un zincir üstü sayımına göre fon yaklaşık 45,65 milyon HYPE biriktirmiş olup değeri yaklaşık 3,19 milyar dolardır ve Hyperliquid'in ücretlerin yaklaşık %97–99'unu bu alımlara yönlendirdiği bildirilmektedir. Yapısal olarak bu, her işlem gerçekleştiğinde otomatik olarak tetiklenen kalıcı bir alım emri gibi davranır.</p>
  <p class="vi">Để hiểu phía bên kia của đợt mở khóa cần đào sâu thêm một cấp về cách Hyperliquid kiếm tiền. Hyperliquid là một sàn giao dịch phi tập trung cho hợp đồng tương lai vĩnh cửu (perpetual) chạy trên layer-1 riêng của mình, và thay vì trả phần lớn phí giao dịch phát sinh cho các nhà đầu tư bên ngoài, nó gửi chúng đến một địa chỉ on-chain gọi là Quỹ Hỗ trợ. Địa chỉ này dùng phí để mua HYPE trên thị trường mở, và các token đã mua được coi là đã rút khỏi lưu thông. Theo thống kê on-chain của DEXTools, quỹ đã tích lũy khoảng 45,65 triệu HYPE, trị giá khoảng 3,19 tỷ USD, và Hyperliquid được cho là chuyển khoảng 97% đến 99% phí vào các giao dịch mua này. Về mặt cấu trúc, điều này hoạt động như một lệnh mua thường trực tự động kích hoạt mỗi khi có giao dịch.</p>

  <p class="ko">여기서 반드시 짚어야 할 반론이 있다. 이 매수 엔진의 연료는 어디까지나 거래 수수료이고, 수수료는 거래량에 연동된다. 실제 분기별 매입 규모를 보면 2025년 3분기 약 3억1700만 달러에서 4분기 약 2억5500만 달러, 2026년 1분기 약 1억9200만 달러로 세 분기 연속 감소했다. 즉 어시스턴스 펀드가 쌓아둔 잔고는 크지만, 앞으로 매달 시장에서 실제로 사들일 수 있는 신규 매수력은 거래 활황 여부에 따라 흔들린다. 언락은 매달 992만 개로 고정돼 있는 반면, 이를 흡수할 매수 흐름은 변동적이라는 비대칭이 존재하는 셈이다. 축적된 잔고 4565만 개는 든든한 완충재지만, 그것을 실제 매도 방어에 쓰려면 프로토콜이 보유분을 시장에 되파는 것이 아니라 계속 사 모으는 현재 정책을 유지해야만 성립한다.</p>
  <p class="en">A counterpoint must be stated plainly here. The fuel for this buyback engine is trading fees, and fees track volume. Looking at the actual quarterly buybacks, they fell for three straight quarters — from about $317 million in Q3 2025 to roughly $255 million in Q4 and about $192 million in Q1 2026. So while the Assistance Fund's accumulated balance is large, the fresh buying power it can actually deploy each month swings with how active trading is. There is an asymmetry: the unlock is fixed at 9.92 million per month, while the buy flow meant to absorb it is variable. The accumulated 45.65 million balance is a solid cushion, but using it as genuine sell-side defense holds only as long as the protocol keeps its current policy of accumulating rather than selling those holdings back into the market.</p>
  <p class="ja">ここで明確に述べるべき反論がある。この買いエンジンの燃料はあくまで取引手数料であり、手数料は取引量に連動する。実際の四半期買い規模を見ると、2025年第3四半期の約3億1700万ドルから第4四半期の約2億5500万ドル、2026年第1四半期の約1億9200万ドルへと3四半期連続で減少した。つまりアシスタンスファンドの積み上げた残高は大きいが、今後毎月市場で実際に買える新規の買い余力は取引の活況次第で揺れる。アンロックが毎月992万枚で固定されている一方、それを吸収する買いの流れは変動的だという非対称が存在する。積み上がった残高4565万枚は頼れる緩衝材だが、それを実際の売り防御に使うには、プロトコルが保有分を市場に売り戻すのではなく買い集め続ける現行方針を維持することが前提になる。</p>
  <p class="es">Aquí debe enunciarse un contrapunto con claridad. El combustible de este motor de recompra son las comisiones de trading, y las comisiones siguen al volumen. Mirando las recompras trimestrales reales, cayeron durante tres trimestres seguidos: de unos 317 millones de dólares en el 3T de 2025 a unos 255 millones en el 4T y unos 192 millones en el 1T de 2026. Así que aunque el saldo acumulado del Fondo de Asistencia es grande, el poder de compra nuevo que realmente puede desplegar cada mes oscila según lo activo que esté el trading. Existe una asimetría: el desbloqueo es fijo en 9,92 millones al mes, mientras que el flujo de compra destinado a absorberlo es variable. El saldo acumulado de 45,65 millones es un colchón sólido, pero usarlo como defensa real del lado vendedor solo se sostiene mientras el protocolo mantenga su política actual de acumular en lugar de revender esas tenencias al mercado.</p>
  <p class="de">Hier muss ein Gegenargument klar benannt werden. Der Treibstoff dieser Rückkauf-Maschine sind Handelsgebühren, und Gebühren folgen dem Volumen. Betrachtet man die tatsächlichen Quartals-Rückkäufe, fielen sie drei Quartale in Folge — von rund 317 Millionen Dollar im Q3 2025 auf etwa 255 Millionen im Q4 und rund 192 Millionen im Q1 2026. Der akkumulierte Bestand des Assistance Fund ist also groß, doch die frische Kaufkraft, die er jeden Monat tatsächlich einsetzen kann, schwankt damit, wie aktiv gehandelt wird. Es besteht eine Asymmetrie: Die Freigabe ist fix auf 9,92 Millionen pro Monat, während der Kaufstrom, der sie aufnehmen soll, variabel ist. Der angesammelte Bestand von 45,65 Millionen ist ein solides Polster, doch ihn als echte Verkaufsseiten-Verteidigung zu nutzen, gilt nur, solange das Protokoll seine aktuelle Politik beibehält, diese Bestände anzuhäufen, statt sie an den Markt zurückzuverkaufen.</p>
  <p class="fr">Il faut ici énoncer clairement un contre-argument. Le carburant de ce moteur de rachat, ce sont les frais de trading, et les frais suivent le volume. En regardant les rachats trimestriels réels, ils ont baissé trois trimestres d'affilée — d'environ 317 millions de dollars au T3 2025 à quelque 255 millions au T4 et environ 192 millions au T1 2026. Ainsi, si le solde accumulé du Fonds d'assistance est important, le pouvoir d'achat frais qu'il peut réellement déployer chaque mois varie selon l'activité du trading. Il existe une asymétrie : le déblocage est fixe à 9,92 millions par mois, tandis que le flux d'achat censé l'absorber est variable. Le solde accumulé de 45,65 millions est un coussin solide, mais l'utiliser comme véritable défense côté vendeur ne tient que tant que le protocole conserve sa politique actuelle d'accumulation plutôt que de revendre ces avoirs sur le marché.</p>
  <p class="pt">Aqui é preciso enunciar um contraponto com clareza. O combustível deste motor de recompra são as taxas de negociação, e as taxas acompanham o volume. Olhando as recompras trimestrais reais, elas caíram por três trimestres seguidos — de cerca de 317 milhões de dólares no 3T de 2025 para aproximadamente 255 milhões no 4T e cerca de 192 milhões no 1T de 2026. Assim, embora o saldo acumulado do Fundo de Assistência seja grande, o poder de compra novo que ele pode de fato empregar a cada mês oscila conforme o quão ativa está a negociação. Há uma assimetria: o desbloqueio é fixo em 9,92 milhões por mês, enquanto o fluxo de compra destinado a absorvê-lo é variável. O saldo acumulado de 45,65 milhões é um colchão sólido, mas usá-lo como defesa real do lado vendedor só se sustenta enquanto o protocolo mantiver sua política atual de acumular em vez de revender essas posições ao mercado.</p>
  <p class="tr">Burada açıkça belirtilmesi gereken bir karşı görüş var. Bu geri alım motorunun yakıtı işlem ücretleridir ve ücretler hacme bağlıdır. Gerçek üç aylık geri alımlara bakıldığında, üç çeyrek üst üste düştüler — 2025 3Ç'deki yaklaşık 317 milyon dolardan 4Ç'de yaklaşık 255 milyona ve 2026 1Ç'de yaklaşık 192 milyona. Dolayısıyla Yardım Fonu'nun biriken bakiyesi büyük olsa da, her ay piyasada gerçekten kullanabileceği taze alım gücü, işlemlerin ne kadar aktif olduğuna göre dalgalanır. Bir asimetri vardır: kilit açılışı ayda 9,92 milyon olarak sabittir, oysa onu emmesi beklenen alım akışı değişkendir. Biriken 45,65 milyonluk bakiye sağlam bir tampondur, ancak bunu gerçek bir satış tarafı savunması olarak kullanmak, yalnızca protokol bu varlıkları piyasaya geri satmak yerine biriktirme yönündeki mevcut politikasını sürdürdüğü sürece geçerlidir.</p>
  <p class="vi">Ở đây cần nêu rõ một luận điểm phản biện. Nhiên liệu cho động cơ mua lại này là phí giao dịch, và phí bám theo khối lượng. Nhìn vào các đợt mua lại theo quý thực tế, chúng đã giảm ba quý liên tiếp — từ khoảng 317 triệu USD trong Q3 2025 xuống khoảng 255 triệu trong Q4 và khoảng 192 triệu trong Q1 2026. Vì vậy, dù số dư tích lũy của Quỹ Hỗ trợ lớn, sức mua mới mà nó thực sự có thể triển khai mỗi tháng lại dao động theo mức độ sôi động của giao dịch. Có một sự bất đối xứng: đợt mở khóa cố định ở 9,92 triệu mỗi tháng, trong khi dòng mua nhằm hấp thụ nó lại biến động. Số dư tích lũy 45,65 triệu là tấm đệm vững chắc, nhưng dùng nó làm phòng thủ thực sự ở phía bán chỉ đứng vững chừng nào giao thức duy trì chính sách hiện tại là tích lũy thay vì bán lại lượng nắm giữ đó ra thị trường.</p>

  <h2 class="ko">다른 언락은 왜 무너졌고, 이번엔 무엇이 다른가</h2>
  <h2 class="en">Why Other Unlocks Broke, and What Is Different Here</h2>
  <h2 class="ja">他のアンロックはなぜ崩れ、今回は何が違うのか</h2>
  <h2 class="es">Por Qué Otros Desbloqueos se Hundieron y Qué es Diferente Aquí</h2>
  <h2 class="de">Warum Andere Freigaben Einbrachen und Was Hier Anders Ist</h2>
  <h2 class="fr">Pourquoi D'autres Déblocages Ont Chuté, et Ce Qui Diffère Ici</h2>
  <h2 class="pt">Por Que Outros Desbloqueios Desabaram e o Que é Diferente Aqui</h2>
  <h2 class="tr">Diğer Kilit Açılışları Neden Çöktü ve Burada Ne Farklı</h2>
  <h2 class="vi">Vì Sao Các Đợt Mở Khóa Khác Sụp Đổ, Và Ở Đây Khác Gì</h2>

  <p class="ko">토큰 언락이 가격에 부담을 준 사례는 2021~2024년 사이 반복적으로 나타났다. 대형 클리프가 한꺼번에 풀리는 프로젝트들에서, 초기 투자자와 팀이 유동성 낮은 시장에 물량을 쏟아내며 언락 전후로 하락 압력이 집중되는 패턴이 관찰됐다. 이런 사례들의 공통점은 두 가지였다. 첫째, 벤처캐피털·초기 투자자 배분 비중이 커서 매도 유인이 강했고, 둘째, 프로토콜 자체가 그 물량을 흡수할 수요 엔진을 갖추지 못했다는 점이다. 새 토큰이 시장에 나오는 속도가 그 토큰을 원하는 신규 수요보다 빠르면, 가격은 구조적으로 눌린다.</p>
  <p class="en">Cases where token unlocks weighed on price recurred throughout 2021–2024. In projects where large cliffs unlocked all at once, early investors and teams dumped supply into thin markets, concentrating downward pressure around the unlock dates. These cases shared two traits. First, venture-capital and early-investor allocations were large, so the incentive to sell was strong; second, the protocol itself had no demand engine to absorb that supply. When new tokens hit the market faster than fresh demand for them appears, price is structurally suppressed.</p>
  <p class="ja">トークンアンロックが価格に重しとなった事例は2021~2024年にかけて繰り返し現れた。大型クリフが一度に解放されるプロジェクトで、初期投資家やチームが流動性の低い市場に物量を放出し、アンロック前後に下落圧力が集中するパターンが観察された。これらの事例の共通点は二つだった。第一にベンチャーキャピタル・初期投資家の配分比率が大きく売却誘因が強かったこと、第二にプロトコル自体がその物量を吸収する需要エンジンを持たなかったことだ。新規トークンが市場に出る速度が、その トークンを求める新規需要より速ければ、価格は構造的に抑えられる。</p>
  <p class="es">Los casos en que los desbloqueos de tokens pesaron sobre el precio se repitieron a lo largo de 2021–2024. En proyectos donde grandes cliffs se desbloqueaban de golpe, los inversores iniciales y los equipos volcaban oferta en mercados poco líquidos, concentrando la presión bajista en torno a las fechas de desbloqueo. Estos casos compartían dos rasgos. Primero, las asignaciones a capital de riesgo e inversores tempranos eran grandes, por lo que el incentivo para vender era fuerte; segundo, el propio protocolo carecía de un motor de demanda para absorber esa oferta. Cuando los nuevos tokens llegan al mercado más rápido de lo que aparece demanda nueva por ellos, el precio queda estructuralmente reprimido.</p>
  <p class="de">Fälle, in denen Token-Freigaben auf den Preis drückten, wiederholten sich über 2021–2024 hinweg. Bei Projekten, in denen große Cliffs auf einmal freigegeben wurden, warfen frühe Investoren und Teams Angebot in dünne Märkte und konzentrierten den Abwärtsdruck rund um die Freigabetermine. Diese Fälle teilten zwei Merkmale. Erstens waren die Zuteilungen an Wagniskapital und Frühinvestoren groß, sodass der Verkaufsanreiz stark war; zweitens hatte das Protokoll selbst keine Nachfrage-Maschine, um dieses Angebot aufzunehmen. Wenn neue Token schneller auf den Markt kommen, als frische Nachfrage nach ihnen entsteht, wird der Preis strukturell gedrückt.</p>
  <p class="fr">Les cas où les déblocages de tokens ont pesé sur le prix se sont répétés tout au long de 2021–2024. Dans les projets où de gros cliffs se débloquaient d'un coup, les premiers investisseurs et les équipes déversaient de l'offre sur des marchés peu liquides, concentrant la pression baissière autour des dates de déblocage. Ces cas partageaient deux traits. Premièrement, les allocations au capital-risque et aux premiers investisseurs étaient importantes, si bien que l'incitation à vendre était forte ; deuxièmement, le protocole lui-même n'avait pas de moteur de demande pour absorber cette offre. Quand de nouveaux tokens arrivent sur le marché plus vite que la demande nouvelle qui les réclame, le prix est structurellement comprimé.</p>
  <p class="pt">Casos em que desbloqueios de tokens pesaram sobre o preço se repetiram ao longo de 2021–2024. Em projetos onde grandes cliffs se desbloqueavam de uma só vez, investidores iniciais e equipes despejavam oferta em mercados rasos, concentrando a pressão de baixa em torno das datas de desbloqueio. Esses casos compartilhavam dois traços. Primeiro, as alocações a capital de risco e investidores iniciais eram grandes, então o incentivo para vender era forte; segundo, o próprio protocolo não tinha um motor de demanda para absorver essa oferta. Quando novos tokens chegam ao mercado mais rápido do que surge demanda nova por eles, o preço fica estruturalmente reprimido.</p>
  <p class="tr">Token kilit açılışlarının fiyata yük bindirdiği örnekler 2021–2024 boyunca tekrarlandı. Büyük cliff'lerin bir anda açıldığı projelerde, erken yatırımcılar ve ekipler ince piyasalara arz boşaltarak kilit açılış tarihleri etrafında aşağı yönlü baskıyı yoğunlaştırdı. Bu örnekler iki ortak özelliği paylaşıyordu. Birincisi, risk sermayesi ve erken yatırımcı tahsisleri büyüktü, dolayısıyla satış güdüsü güçlüydü; ikincisi, protokolün kendisi bu arzı emecek bir talep motoruna sahip değildi. Yeni token'lar, kendilerine yönelik taze talebin oluşmasından daha hızlı piyasaya çıktığında, fiyat yapısal olarak baskılanır.</p>
  <p class="vi">Những trường hợp mở khóa token gây áp lực lên giá đã lặp lại suốt giai đoạn 2021–2024. Ở các dự án nơi những đợt cliff lớn mở khóa cùng lúc, nhà đầu tư ban đầu và đội ngũ đổ nguồn cung vào thị trường mỏng, dồn áp lực giảm quanh các ngày mở khóa. Những trường hợp này có hai đặc điểm chung. Thứ nhất, phần phân bổ cho quỹ đầu tư mạo hiểm và nhà đầu tư sớm lớn, nên động cơ bán mạnh; thứ hai, bản thân giao thức không có động cơ nhu cầu để hấp thụ nguồn cung đó. Khi token mới ra thị trường nhanh hơn nhu cầu mới xuất hiện, giá bị đè nén một cách có cấu trúc.</p>

  <p class="ko">하이퍼리퀴드가 다른 점은 바로 이 두 번째 조건에 정면으로 대응하는 설계라는 데 있다. 하이퍼리퀴드는 초기 자금 조달에서 벤처캐피털 배분을 거의 두지 않고 커뮤니티 에어드롭 중심으로 토큰을 분배했고, 수수료를 배당이 아니라 자사 토큰 매입에 쓰는 순환 구조를 만들었다. 이 때문에 언락 물량과 매수 엔진이 같은 프로토콜 안에서 맞물린다. 다만 이것을 '언락이 무해하다'는 뜻으로 읽으면 안 된다. 이 모델의 아킬레스건은 명확하다—거래량이 꺾이면 매수 연료가 줄고, 매수 연료가 줄면 완충 능력도 줄어든다. 즉 하이퍼리퀴드의 언락 방어는 거래소로서의 성공에 반사적으로(reflexively) 묶여 있으며, 이는 강점인 동시에 단일 실패 지점이 될 수 있다. 지켜봐야 할 것은 언락 그 자체가 아니라, 언락을 흡수하는 거래량과 수수료 흐름이 앞으로도 유지되느냐다.</p>
  <p class="en">What is different about Hyperliquid is that its design confronts precisely this second condition head-on. Hyperliquid held almost no venture-capital allocation in its early funding, distributing tokens mainly through a community airdrop, and it built a circular structure that spends fees on buying its own token rather than on dividends. Because of that, the unlock supply and the buyback engine are geared together inside the same protocol. But this should not be read as "the unlock is harmless." The model's Achilles' heel is clear: if volume rolls over, the buying fuel shrinks, and if the buying fuel shrinks, so does the cushioning. In other words, Hyperliquid's unlock defense is reflexively tied to its success as an exchange — a strength and a single point of failure at once. What to watch is not the unlock itself but whether the trading volume and fee flow that absorb it hold up over time.</p>
  <p class="ja">ハイパーリキッドが異なるのは、まさにこの第二の条件に正面から対応する設計だという点にある。ハイパーリキッドは初期の資金調達でベンチャーキャピタル配分をほとんど置かず、コミュニティのエアドロップ中心にトークンを分配し、手数料を配当ではなく自社トークンの買いに充てる循環構造を作った。そのため、アンロック物量と買いエンジンが同じプロトコル内でかみ合う。ただしこれを「アンロックは無害だ」と読んではならない。このモデルのアキレス腱は明確だ——取引量が鈍れば買いの燃料が減り、買いの燃料が減れば緩衝力も減る。つまりハイパーリキッドのアンロック防御は取引所としての成功に反射的(リフレクシブ)に結びついており、これは強みであると同時に単一障害点になりうる。注視すべきはアンロックそのものではなく、それを吸収する取引量と手数料の流れが今後も維持されるかだ。</p>
  <p class="es">Lo que diferencia a Hyperliquid es que su diseño aborda precisamente esta segunda condición de frente. Hyperliquid apenas tuvo asignación de capital de riesgo en su financiación inicial, distribuyendo tokens sobre todo mediante un airdrop comunitario, y construyó una estructura circular que gasta las comisiones en comprar su propio token en lugar de en dividendos. Por eso, la oferta del desbloqueo y el motor de recompra están engranados dentro del mismo protocolo. Pero esto no debe leerse como que "el desbloqueo es inofensivo". El talón de Aquiles del modelo es claro: si el volumen cae, el combustible de compra se reduce, y si el combustible de compra se reduce, también lo hace el amortiguamiento. En otras palabras, la defensa del desbloqueo de Hyperliquid está reflexivamente atada a su éxito como exchange: una fortaleza y un único punto de fallo a la vez. Lo que hay que vigilar no es el desbloqueo en sí, sino si el volumen de trading y el flujo de comisiones que lo absorben se sostienen con el tiempo.</p>
  <p class="de">Das Besondere an Hyperliquid ist, dass sein Design genau dieser zweiten Bedingung direkt begegnet. Hyperliquid hatte in seiner frühen Finanzierung fast keine Wagniskapital-Zuteilung, verteilte Token vor allem über einen Community-Airdrop und baute eine zirkuläre Struktur, die Gebühren für den Kauf des eigenen Tokens statt für Dividenden ausgibt. Deshalb greifen Freigabe-Angebot und Rückkauf-Maschine innerhalb desselben Protokolls ineinander. Doch das sollte nicht als „die Freigabe ist harmlos" gelesen werden. Die Achillesferse des Modells ist klar: Kippt das Volumen, schrumpft der Kauf-Treibstoff, und schrumpft der Kauf-Treibstoff, schrumpft auch die Pufferung. Mit anderen Worten: Hyperliquids Freigabe-Verteidigung ist reflexiv an seinen Erfolg als Börse gebunden — zugleich Stärke und einzelner Ausfallpunkt. Zu beobachten ist nicht die Freigabe selbst, sondern ob das Handelsvolumen und der Gebührenfluss, die sie aufnehmen, dauerhaft Bestand haben.</p>
  <p class="fr">Ce qui distingue Hyperliquid, c'est que sa conception affronte précisément cette deuxième condition de front. Hyperliquid n'a presque pas eu d'allocation de capital-risque lors de son financement initial, distribuant les tokens surtout via un airdrop communautaire, et a bâti une structure circulaire qui dépense les frais à racheter son propre token plutôt qu'en dividendes. De ce fait, l'offre du déblocage et le moteur de rachat sont engrenés au sein du même protocole. Mais cela ne doit pas se lire comme « le déblocage est inoffensif ». Le talon d'Achille du modèle est clair : si le volume se retourne, le carburant d'achat se réduit, et si le carburant d'achat se réduit, l'amortissement aussi. Autrement dit, la défense du déblocage de Hyperliquid est réflexivement liée à son succès en tant que bourse — une force et un point de défaillance unique à la fois. Ce qu'il faut surveiller n'est pas le déblocage lui-même, mais si le volume de trading et le flux de frais qui l'absorbent tiennent dans le temps.</p>
  <p class="pt">O que diferencia a Hyperliquid é que seu design enfrenta precisamente esta segunda condição de frente. A Hyperliquid quase não teve alocação de capital de risco em seu financiamento inicial, distribuindo tokens sobretudo por um airdrop comunitário, e construiu uma estrutura circular que gasta as taxas comprando seu próprio token em vez de pagar dividendos. Por isso, a oferta do desbloqueio e o motor de recompra estão engrenados dentro do mesmo protocolo. Mas isto não deve ser lido como "o desbloqueio é inofensivo". O calcanhar de Aquiles do modelo é claro: se o volume vira, o combustível de compra encolhe, e se o combustível de compra encolhe, o amortecimento também. Em outras palavras, a defesa do desbloqueio da Hyperliquid está reflexivamente atada ao seu sucesso como corretora — uma força e um ponto único de falha ao mesmo tempo. O que se deve observar não é o desbloqueio em si, mas se o volume de negociação e o fluxo de taxas que o absorvem se sustentam ao longo do tempo.</p>
  <p class="tr">Hyperliquid'i farklı kılan, tasarımının tam da bu ikinci koşulla doğrudan yüzleşmesidir. Hyperliquid erken finansmanında neredeyse hiç risk sermayesi tahsisi bulundurmadı, token'ları çoğunlukla bir topluluk airdrop'u yoluyla dağıttı ve ücretleri temettü yerine kendi token'ını almaya harcayan döngüsel bir yapı kurdu. Bu nedenle kilit açılış arzı ile geri alım motoru aynı protokol içinde birbirine geçmiştir. Ancak bu, "kilit açılışı zararsızdır" biçiminde okunmamalı. Modelin Aşil topuğu net: hacim düşerse alım yakıtı azalır ve alım yakıtı azalırsa tamponlama da azalır. Başka bir deyişle, Hyperliquid'in kilit açılış savunması, borsa olarak başarısına refleksif biçimde bağlıdır — hem bir güç hem de tek bir başarısızlık noktasıdır. İzlenmesi gereken şey kilit açılışının kendisi değil, onu emen işlem hacminin ve ücret akışının zamanla sürüp sürmeyeceğidir.</p>
  <p class="vi">Điều khác biệt ở Hyperliquid là thiết kế của nó đối mặt trực diện với chính điều kiện thứ hai này. Hyperliquid gần như không có phần phân bổ cho quỹ đầu tư mạo hiểm trong vòng gọi vốn ban đầu, phân phối token chủ yếu qua một đợt airdrop cộng đồng, và xây dựng một cấu trúc tuần hoàn dùng phí để mua chính token của mình thay vì trả cổ tức. Nhờ đó, nguồn cung mở khóa và động cơ mua lại ăn khớp với nhau trong cùng một giao thức. Nhưng không nên đọc điều này thành "đợt mở khóa là vô hại". Gót chân Achilles của mô hình rất rõ: nếu khối lượng suy giảm, nhiên liệu mua giảm, và nếu nhiên liệu mua giảm thì khả năng đệm cũng giảm. Nói cách khác, hàng phòng thủ mở khóa của Hyperliquid gắn một cách phản xạ với thành công của nó với tư cách một sàn giao dịch — vừa là điểm mạnh vừa là điểm hỏng duy nhất. Điều cần theo dõi không phải bản thân đợt mở khóa, mà là liệu khối lượng giao dịch và dòng phí hấp thụ nó có duy trì theo thời gian hay không.</p>

  <h2 class="ko">무엇을 지켜봐야 하는가</h2>
  <h2 class="en">What to Watch</h2>
  <h2 class="ja">何を注視すべきか</h2>
  <h2 class="es">Qué Vigilar</h2>
  <h2 class="de">Worauf Zu Achten Ist</h2>
  <h2 class="fr">Ce Qu'il Faut Surveiller</h2>
  <h2 class="pt">O Que Observar</h2>
  <h2 class="tr">Neye Dikkat Edilmeli</h2>
  <h2 class="vi">Cần Theo Dõi Điều Gì</h2>

  <p class="ko">이번 언락은 단발 이벤트가 아니라 2027년까지 매달 반복되는 시리즈의 한 회차이므로, 관전 포인트는 '이번 달 가격'이 아니라 두 개의 온체인 흐름이 계속 균형을 유지하는지다. 첫째, 어시스턴스 펀드의 HYPE 잔고가 계속 순증하는지—즉 매입이 언락을 앞지르는지—를 온체인 주소에서 직접 확인할 수 있다. 잔고 증가세가 꺾이는 순간은 매수 엔진이 공급 속도를 따라잡지 못하기 시작했다는 첫 신호가 된다. 둘째, 코어 기여자 지갑들이 풀린 물량을 실제로 거래소로 옮기는지다. 잠금 해제와 실제 매도는 다른 사건이며, 팀이 지금까지 보여온 99% 보유 행태가 유지되는지 여부가 이 물량의 실제 무게를 결정한다.</p>
  <p class="en">Because this unlock is not a one-off but one installment in a series that repeats every month into 2027, the thing to watch is not "this month's price" but whether two on-chain flows stay in balance. First, whether the Assistance Fund's HYPE balance keeps rising net — that is, whether buying outpaces the unlocks — is directly verifiable at the on-chain address. The moment that balance stops growing would be the first signal that the buy engine has begun to fall behind the pace of supply. Second, whether core-contributor wallets actually move unlocked tokens onto exchanges. Unlocking and selling are different events, and whether the team's 99%-held behavior to date persists will determine the real weight of this supply.</p>
  <p class="ja">今回のアンロックは単発イベントではなく2027年まで毎月繰り返されるシリーズの1回分であるため、注視点は「今月の価格」ではなく、二つのオンチェーンの流れが均衡を保ち続けるかだ。第一に、アシスタンスファンドのHYPE残高が純増し続けるか——つまり買いがアンロックを上回るか——はオンチェーンアドレスで直接確認できる。残高の増加が止まる瞬間は、買いエンジンが供給速度に追いつけなくなり始めたという最初の signal となる。第二に、コア貢献者のウォレットが解放された物量を実際に取引所へ移すかだ。ロック解除と実際の売却は別の事象であり、チームがこれまで示してきた99%保有の行動が維持されるか否かが、この物量の実際の重みを決める。</p>
  <p class="es">Como este desbloqueo no es puntual sino una cuota de una serie que se repite cada mes hasta 2027, lo que hay que vigilar no es "el precio de este mes" sino si dos flujos on-chain se mantienen en equilibrio. Primero, si el saldo de HYPE del Fondo de Asistencia sigue creciendo en neto —es decir, si las compras superan a los desbloqueos— es verificable directamente en la dirección on-chain. El momento en que ese saldo deje de crecer sería la primera señal de que el motor de compra ha empezado a quedarse por detrás del ritmo de la oferta. Segundo, si las billeteras de contribuyentes principales realmente mueven los tokens desbloqueados a los exchanges. Desbloquear y vender son eventos distintos, y que persista el comportamiento del equipo de retener el 99% hasta ahora determinará el peso real de esta oferta.</p>
  <p class="de">Da diese Freigabe kein einmaliges Ereignis ist, sondern eine Rate in einer Serie, die sich bis 2027 jeden Monat wiederholt, ist das zu Beobachtende nicht „der Preis dieses Monats", sondern ob zwei On-Chain-Ströme im Gleichgewicht bleiben. Erstens ist an der On-Chain-Adresse direkt überprüfbar, ob der HYPE-Bestand des Assistance Fund netto weiter steigt — also ob die Käufe die Freigaben übertreffen. Der Moment, in dem dieser Bestand aufhört zu wachsen, wäre das erste Signal, dass die Kauf-Maschine begonnen hat, hinter das Tempo des Angebots zurückzufallen. Zweitens, ob die Wallets der Kernbeitragenden freigegebene Token tatsächlich auf Börsen bewegen. Freigeben und Verkaufen sind verschiedene Ereignisse, und ob das bisherige 99%-Halteverhalten des Teams bestehen bleibt, wird das reale Gewicht dieses Angebots bestimmen.</p>
  <p class="fr">Comme ce déblocage n'est pas ponctuel mais une tranche d'une série qui se répète chaque mois jusqu'en 2027, ce qu'il faut surveiller n'est pas « le prix de ce mois-ci » mais si deux flux on-chain restent en équilibre. Premièrement, savoir si le solde de HYPE du Fonds d'assistance continue d'augmenter en net — c'est-à-dire si les achats dépassent les déblocages — est directement vérifiable à l'adresse on-chain. Le moment où ce solde cesse de croître serait le premier signal que le moteur d'achat commence à prendre du retard sur le rythme de l'offre. Deuxièmement, si les portefeuilles des contributeurs principaux déplacent réellement les tokens débloqués vers les exchanges. Débloquer et vendre sont des événements distincts, et le maintien du comportement de l'équipe qui a conservé 99% jusqu'ici déterminera le poids réel de cette offre.</p>
  <p class="pt">Como este desbloqueio não é pontual, mas uma parcela de uma série que se repete todo mês até 2027, o que se deve observar não é "o preço deste mês", mas se dois fluxos on-chain permanecem em equilíbrio. Primeiro, se o saldo de HYPE do Fundo de Assistência continua crescendo em termos líquidos — ou seja, se as compras superam os desbloqueios — é verificável diretamente no endereço on-chain. O momento em que esse saldo parar de crescer seria o primeiro sinal de que o motor de compra começou a ficar atrás do ritmo da oferta. Segundo, se as carteiras dos contribuidores principais de fato movem os tokens desbloqueados para as corretoras. Desbloquear e vender são eventos distintos, e se o comportamento da equipe de reter 99% até agora persistir determinará o peso real dessa oferta.</p>
  <p class="tr">Bu kilit açılışı tek seferlik bir olay değil, 2027'ye kadar her ay tekrarlanan bir serinin bir taksidi olduğundan, izlenmesi gereken şey "bu ayın fiyatı" değil, iki zincir üstü akışın dengede kalıp kalmadığıdır. Birincisi, Yardım Fonu'nun HYPE bakiyesinin net olarak artmaya devam edip etmediği — yani alımların kilit açılışlarını geçip geçmediği — zincir üstü adreste doğrudan doğrulanabilir. Bu bakiyenin büyümeyi durdurduğu an, alım motorunun arz hızının gerisine düşmeye başladığının ilk işareti olur. İkincisi, çekirdek katkı sağlayıcı cüzdanların kilidi açılan token'ları gerçekten borsalara taşıyıp taşımadığıdır. Kilit açmak ile satmak farklı olaylardır ve ekibin şimdiye dek sergilediği %99 tutma davranışının sürüp sürmemesi, bu arzın gerçek ağırlığını belirleyecektir.</p>
  <p class="vi">Vì đợt mở khóa này không phải sự kiện đơn lẻ mà là một phần trong chuỗi lặp lại hằng tháng đến năm 2027, điều cần theo dõi không phải "giá tháng này" mà là liệu hai dòng chảy on-chain có giữ được cân bằng hay không. Thứ nhất, việc số dư HYPE của Quỹ Hỗ trợ có tiếp tục tăng ròng hay không — tức là việc mua có vượt các đợt mở khóa hay không — có thể kiểm chứng trực tiếp tại địa chỉ on-chain. Thời điểm số dư đó ngừng tăng sẽ là tín hiệu đầu tiên cho thấy động cơ mua đã bắt đầu tụt lại sau nhịp cung. Thứ hai, liệu ví của các nhà đóng góp cốt lõi có thực sự chuyển token đã mở khóa lên các sàn hay không. Mở khóa và bán là hai sự kiện khác nhau, và việc hành vi giữ 99% của đội ngũ đến nay có tiếp tục hay không sẽ quyết định trọng lượng thực sự của nguồn cung này.</p>

  <p class="ko">이 글은 특정 자산의 매수·매도를 권유하지 않으며, 가격 방향을 예측하지 않는다. 여기서 다룬 것은 공개된 베스팅 일정과 온체인 주소에서 검증 가능한 수급 데이터일 뿐이다. 토큰 매입형 구조는 프로토콜이 수수료 수익을 자사 토큰에 재투입하는 여러 설계 중 하나이며, 매입한 토큰을 소각하지 않고 펀드에 쌓아두는 방식은 향후 정책 변경 시 다시 유통될 수 있다는 점에서 '영구 소각'과는 성격이 다르다는 점도 함께 기억할 필요가 있다.</p>
  <p class="en">This article does not recommend buying or selling any asset and does not predict price direction. What it covers is only the published vesting schedule and supply-demand data verifiable at on-chain addresses. A token-buyback structure is one of several designs by which a protocol recycles fee revenue into its own token, and it is worth remembering that holding bought-back tokens in a fund rather than burning them differs in character from a permanent burn, since they could re-enter circulation under a future policy change.</p>
  <p class="ja">本記事は特定資産の売買を推奨せず、価格の方向も予測しない。ここで扱ったのは公開されたベスティング日程と、オンチェーンアドレスで検証可能な需給データにすぎない。トークン買い入れ型の構造は、プロトコルが手数料収益を自社トークンに再投入する複数の設計の一つであり、買い入れたトークンを焼却せずファンドに積み上げる方式は、将来の政策変更時に再び流通しうるという点で「恒久的な焼却」とは性質が異なることも併せて記憶しておく必要がある。</p>
  <p class="es">Este artículo no recomienda comprar ni vender ningún activo y no predice la dirección del precio. Lo que aquí se cubre es solo el calendario de vesting publicado y datos de oferta y demanda verificables en direcciones on-chain. Una estructura de recompra de tokens es uno de varios diseños por los que un protocolo recicla los ingresos por comisiones en su propio token, y conviene recordar que mantener los tokens recomprados en un fondo en lugar de quemarlos difiere en naturaleza de una quema permanente, ya que podrían volver a circular ante un cambio futuro de política.</p>
  <p class="de">Dieser Artikel empfiehlt weder den Kauf noch den Verkauf eines Vermögenswerts und sagt keine Preisrichtung voraus. Behandelt wird nur der veröffentlichte Vesting-Plan und an On-Chain-Adressen überprüfbare Angebots-Nachfrage-Daten. Eine Token-Rückkauf-Struktur ist eines von mehreren Designs, mit denen ein Protokoll Gebühreneinnahmen in den eigenen Token zurückführt, und es ist zu bedenken, dass das Halten zurückgekaufter Token in einem Fonds statt sie zu verbrennen sich vom Charakter her von einem dauerhaften Burn unterscheidet, da sie bei einer künftigen Politikänderung wieder in Umlauf gelangen könnten.</p>
  <p class="fr">Cet article ne recommande d'acheter ni de vendre aucun actif et ne prédit pas la direction du prix. Ce qu'il couvre n'est que le calendrier de vesting publié et des données d'offre et de demande vérifiables aux adresses on-chain. Une structure de rachat de tokens est l'un des divers modèles par lesquels un protocole réinjecte ses revenus de frais dans son propre token, et il convient de rappeler que conserver les tokens rachetés dans un fonds plutôt que de les brûler diffère par nature d'un burn permanent, car ils pourraient revenir en circulation lors d'un changement futur de politique.</p>
  <p class="pt">Este artigo não recomenda comprar ou vender qualquer ativo e não prevê a direção do preço. O que ele cobre é apenas o cronograma de vesting publicado e dados de oferta e demanda verificáveis em endereços on-chain. Uma estrutura de recompra de tokens é um dos vários desenhos pelos quais um protocolo recicla a receita de taxas em seu próprio token, e vale lembrar que manter os tokens recomprados em um fundo em vez de queimá-los difere em natureza de uma queima permanente, pois eles poderiam voltar a circular diante de uma futura mudança de política.</p>
  <p class="tr">Bu makale herhangi bir varlığın alınmasını veya satılmasını önermez ve fiyat yönü tahmininde bulunmaz. Burada ele alınan yalnızca yayımlanmış vesting takvimi ve zincir üstü adreslerde doğrulanabilir arz-talep verileridir. Token geri alım yapısı, bir protokolün ücret gelirini kendi token'ına geri yatırdığı çeşitli tasarımlardan biridir ve geri alınan token'ları yakmak yerine bir fonda biriktirmenin, gelecekteki bir politika değişikliğinde yeniden dolaşıma girebilecekleri için kalıcı bir yakımdan nitelik olarak farklı olduğunu hatırlamakta fayda vardır.</p>
  <p class="vi">Bài viết này không khuyến nghị mua hay bán bất kỳ tài sản nào và không dự đoán hướng giá. Những gì nó đề cập chỉ là lịch vesting đã công bố và dữ liệu cung-cầu có thể kiểm chứng tại các địa chỉ on-chain. Cấu trúc mua lại token là một trong nhiều thiết kế mà một giao thức tái đầu tư doanh thu phí vào chính token của mình, và cần nhớ rằng việc giữ token đã mua lại trong một quỹ thay vì đốt chúng khác về bản chất so với việc đốt vĩnh viễn, vì chúng có thể quay lại lưu thông khi có thay đổi chính sách trong tương lai.</p>

  <h2 class="ko">함께 보면 좋은 글</h2>
  <h2 class="en">Best Read Alongside</h2>
  <h2 class="ja">あわせて読みたい</h2>
  <h2 class="es">Mejor Leído Junto Con</h2>
  <h2 class="de">Am Besten Zusammen Lesen</h2>
  <h2 class="fr">À Lire En Complément</h2>
  <h2 class="pt">Melhor Lido Em Conjunto</h2>
  <h2 class="tr">Birlikte Okunması Önerilir</h2>
  <h2 class="vi">Nên Đọc Cùng Với</h2>
  <ul class="ko">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">칼시의 CFTC 승인 온쇼어 무기한 선물</a>:</strong> 하이퍼리퀴드가 지배해온 무기한 선물 시장에 규제권 경쟁자가 진입하는 맥락</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">ESMA의 무기한 선물·CFD 레버리지 규제</a>:</strong> 무기한 선물이라는 상품 자체를 둘러싼 규제 환경</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">스테이블코인 드라이파우더 고갈과 거래소 준비금 격차</a>:</strong> 신규 물량을 흡수할 시장 유동성의 현주소</li>
  </ul>
  <ul class="en">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">Kalshi's CFTC-Approved Onshore Perpetuals</a>:</strong> The context of a regulated rival entering the perpetuals market Hyperliquid has dominated</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">ESMA on Perpetual Futures and CFD Leverage</a>:</strong> The regulatory environment around the perpetuals product itself</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">Stablecoin Dry-Powder Drought and the Exchange Reserve Gap</a>:</strong> The current state of the market liquidity that absorbs new supply</li>
  </ul>
  <ul class="ja">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">カルシのCFTC承認オンショア無期限先物</a>:</strong> ハイパーリキッドが支配してきた無期限先物市場に規制圏の競合が参入する文脈</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">ESMAの無期限先物・CFDレバレッジ規制</a>:</strong> 無期限先物という商品自体を巡る規制環境</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">ステーブルコインのドライパウダー枯渇と取引所準備金の格差</a>:</strong> 新規物量を吸収する市場流動性の現状</li>
  </ul>
  <ul class="es">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">Los Perpetuos Onshore de Kalshi Aprobados por la CFTC</a>:</strong> El contexto de un rival regulado entrando en el mercado de perpetuos que Hyperliquid ha dominado</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">La ESMA sobre Futuros Perpetuos y Apalancamiento CFD</a>:</strong> El entorno regulatorio en torno al propio producto de perpetuos</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">La Sequía de Pólvora Seca en Stablecoins y la Brecha de Reservas de los Exchanges</a>:</strong> El estado actual de la liquidez de mercado que absorbe la nueva oferta</li>
  </ul>
  <ul class="de">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">Kalshis CFTC-Genehmigte Onshore-Perpetuals</a>:</strong> Der Kontext eines regulierten Rivalen, der in den von Hyperliquid dominierten Perpetuals-Markt eintritt</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">ESMA zu Perpetual Futures und CFD-Hebel</a>:</strong> Das regulatorische Umfeld rund um das Perpetuals-Produkt selbst</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">Stablecoin-Dry-Powder-Dürre und die Reservelücke der Börsen</a>:</strong> Der aktuelle Stand der Marktliquidität, die neues Angebot aufnimmt</li>
  </ul>
  <ul class="fr">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">Les Perpétuels Onshore de Kalshi Approuvés par la CFTC</a>:</strong> Le contexte d'un rival régulé entrant sur le marché des perpétuels que Hyperliquid a dominé</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">L'ESMA sur les Futures Perpétuels et l'Effet de Levier des CFD</a>:</strong> L'environnement réglementaire autour du produit perpétuel lui-même</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">La Sécheresse de Poudre Sèche des Stablecoins et l'Écart de Réserves des Exchanges</a>:</strong> L'état actuel de la liquidité de marché qui absorbe la nouvelle offre</li>
  </ul>
  <ul class="pt">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">Os Perpétuos Onshore da Kalshi Aprovados pela CFTC</a>:</strong> O contexto de um rival regulado entrando no mercado de perpétuos que a Hyperliquid dominou</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">A ESMA sobre Futuros Perpétuos e Alavancagem de CFD</a>:</strong> O ambiente regulatório em torno do próprio produto de perpétuos</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">A Seca de Pólvora Seca das Stablecoins e a Lacuna de Reservas das Corretoras</a>:</strong> O estado atual da liquidez de mercado que absorve a nova oferta</li>
  </ul>
  <ul class="tr">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">Kalshi'nin CFTC Onaylı Yurt İçi Süresiz İşlemleri</a>:</strong> Hyperliquid'in hâkim olduğu süresiz işlemler pazarına düzenlemeye tabi bir rakibin girmesi bağlamı</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">ESMA'nın Süresiz Vadeli İşlemler ve CFD Kaldıraç Düzenlemesi</a>:</strong> Süresiz işlemler ürününün kendisini çevreleyen düzenleyici ortam</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">Stabil Para Kuru Barut Kıtlığı ve Borsa Rezerv Açığı</a>:</strong> Yeni arzı emen piyasa likiditesinin mevcut durumu</li>
  </ul>
  <ul class="vi">
    <li><strong><a href="/blog/kalshi-btcperp-cftc-onshore-perpetuals.php">Hợp Đồng Vĩnh Cửu Nội Địa Được CFTC Phê Duyệt của Kalshi</a>:</strong> Bối cảnh một đối thủ được quản lý gia nhập thị trường perpetual mà Hyperliquid từng thống trị</li>
    <li><strong><a href="/blog/esma-perpetual-futures-cfd-leverage.php">ESMA về Hợp Đồng Tương Lai Vĩnh Cửu và Đòn Bẩy CFD</a>:</strong> Môi trường pháp lý xung quanh chính sản phẩm perpetual</li>
    <li><strong><a href="/blog/stablecoin-dry-powder-drought-exchange-reserve-gap.php">Cạn Kiệt Vốn Chờ của Stablecoin và Khoảng Trống Dự Trữ Sàn</a>:</strong> Hiện trạng thanh khoản thị trường hấp thụ nguồn cung mới</li>
  </ul>

  <p class="ko" style="font-size:.85rem;color:#71717a">출처: DEXTools(어시스턴스 펀드 온체인 보유량·분기별 매입 데이터), 코인마켓캡·코인스탯(HYPE 언락 규모·가격), tokenomist·DefiLlama(HYPE 베스팅 일정·최대 공급량·팀 배분), 하이퍼리퀴드 온체인 주소(수수료 재투입 구조). 온체인 수치는 조회 시점에 따라 달라질 수 있으며, 본 글은 투자 조언이 아니다.</p>
  <p class="en" style="font-size:.85rem;color:#71717a">Sources: DEXTools (Assistance Fund on-chain holdings and quarterly buyback data), CoinMarketCap and CoinStats (HYPE unlock size and price), tokenomist and DefiLlama (HYPE vesting schedule, max supply, team allocation), Hyperliquid on-chain addresses (fee-recycling structure). On-chain figures may vary by the time of query; this is not investment advice.</p>
  <p class="ja" style="font-size:.85rem;color:#71717a">出典: DEXTools(アシスタンスファンドのオンチェーン保有量・四半期買い入れデータ)、コインマーケットキャップ・コインスタット(HYPEアンロック規模・価格)、tokenomist・DefiLlama(HYPEベスティング日程・最大供給量・チーム配分)、ハイパーリキッドのオンチェーンアドレス(手数料再投入構造)。オンチェーン数値は照会時点により異なる場合があり、本記事は投資助言ではない。</p>
  <p class="es" style="font-size:.85rem;color:#71717a">Fuentes: DEXTools (tenencias on-chain del Fondo de Asistencia y datos de recompras trimestrales), CoinMarketCap y CoinStats (tamaño del desbloqueo de HYPE y precio), tokenomist y DefiLlama (calendario de vesting de HYPE, oferta máxima, asignación del equipo), direcciones on-chain de Hyperliquid (estructura de reciclaje de comisiones). Las cifras on-chain pueden variar según el momento de la consulta; esto no es asesoramiento de inversión.</p>
  <p class="de" style="font-size:.85rem;color:#71717a">Quellen: DEXTools (On-Chain-Bestände des Assistance Fund und Quartals-Rückkaufdaten), CoinMarketCap und CoinStats (Umfang der HYPE-Freigabe und Preis), tokenomist und DefiLlama (HYPE-Vesting-Plan, maximales Angebot, Team-Zuteilung), On-Chain-Adressen von Hyperliquid (Gebühren-Recycling-Struktur). On-Chain-Zahlen können je nach Abfragezeitpunkt variieren; dies ist keine Anlageberatung.</p>
  <p class="fr" style="font-size:.85rem;color:#71717a">Sources : DEXTools (avoirs on-chain du Fonds d'assistance et données de rachats trimestriels), CoinMarketCap et CoinStats (taille du déblocage de HYPE et prix), tokenomist et DefiLlama (calendrier de vesting de HYPE, offre maximale, allocation de l'équipe), adresses on-chain de Hyperliquid (structure de recyclage des frais). Les chiffres on-chain peuvent varier selon le moment de la consultation ; ceci n'est pas un conseil en investissement.</p>
  <p class="pt" style="font-size:.85rem;color:#71717a">Fontes: DEXTools (participações on-chain do Fundo de Assistência e dados de recompras trimestrais), CoinMarketCap e CoinStats (tamanho do desbloqueio de HYPE e preço), tokenomist e DefiLlama (cronograma de vesting do HYPE, oferta máxima, alocação da equipe), endereços on-chain da Hyperliquid (estrutura de reciclagem de taxas). Os números on-chain podem variar conforme o momento da consulta; isto não é aconselhamento de investimento.</p>
  <p class="tr" style="font-size:.85rem;color:#71717a">Kaynaklar: DEXTools (Yardım Fonu zincir üstü varlıkları ve üç aylık geri alım verileri), CoinMarketCap ve CoinStats (HYPE kilit açılış büyüklüğü ve fiyatı), tokenomist ve DefiLlama (HYPE vesting takvimi, azami arz, ekip tahsisi), Hyperliquid zincir üstü adresleri (ücret geri dönüşüm yapısı). Zincir üstü rakamlar sorgulama zamanına göre değişebilir; bu bir yatırım tavsiyesi değildir.</p>
  <p class="vi" style="font-size:.85rem;color:#71717a">Nguồn: DEXTools (lượng nắm giữ on-chain của Quỹ Hỗ trợ và dữ liệu mua lại theo quý), CoinMarketCap và CoinStats (quy mô mở khóa HYPE và giá), tokenomist và DefiLlama (lịch vesting HYPE, nguồn cung tối đa, phân bổ đội ngũ), các địa chỉ on-chain của Hyperliquid (cấu trúc tái đầu tư phí). Các con số on-chain có thể thay đổi tùy thời điểm truy vấn; đây không phải là lời khuyên đầu tư.</p>

<?php require __DIR__.'/_footer.php'; ?>
