<?php $slug = 'keyrock-blockfills-institutional-acquisition-3-25m'; require __DIR__.'/_header.php'; ?>

<p class="ko">벨기에 브뤼셀에 본사를 둔 디지털자산 마켓메이커 키록(Keyrock)이 파산 절차를 밟고 있던 미국 기관용 크립토 브로커리지 블록필스(BlockFills)의 트레이딩·브로커리지 사업 자산을 325만달러에 인수했다고 코인데스크가 7월 16일 보도했다. 이번 인수로 키록은 블록필스의 기관 고객 관계, 트레이딩 기술, 파생상품 전문인력을 함께 확보했으며, 거래는 델라웨어 파산법원의 승인을 거쳐 완료됐다.</p>
<p class="en">Keyrock, a Brussels-based digital-asset market maker, has acquired the trading and brokerage assets of bankrupt U.S. institutional crypto broker BlockFills for $3.25 million, CoinDesk reported on July 16. The deal, completed with approval from a Delaware bankruptcy court, gives Keyrock BlockFills' institutional client relationships, trading technology and derivatives talent in one transaction.</p>
<p class="ja">ベルギー・ブリュッセルに本社を置くデジタル資産マーケットメイカーのキーロック(Keyrock)が、破産手続き中だった米国の機関投資家向け暗号資産ブローカレッジ、ブロックフィルズ(BlockFills)のトレーディング・ブローカレッジ事業資産を325万ドルで買収したと、コインデスクが7月16日に報じた。この買収によりキーロックは、ブロックフィルズの機関投資家との関係、取引技術、デリバティブ専門人材を一括で獲得した。取引はデラウェア州破産裁判所の承認を経て完了した。</p>
<p class="es">Keyrock, un creador de mercado de activos digitales con sede en Bruselas, adquirió los activos de trading y correduría del bróker cripto institucional estadounidense en quiebra BlockFills por 3,25 millones de dólares, informó CoinDesk el 16 de julio. El acuerdo, completado con la aprobación de un tribunal de quiebras de Delaware, le da a Keyrock las relaciones con clientes institucionales de BlockFills, su tecnología de trading y su talento en derivados en una sola transacción.</p>
<p class="de">Keyrock, ein in Brüssel ansässiger Market Maker für digitale Vermögenswerte, hat die Handels- und Brokerage-Vermögenswerte des insolventen US-amerikanischen institutionellen Krypto-Brokers BlockFills für 3,25 Millionen Dollar übernommen, berichtete CoinDesk am 16. Juli. Der mit Genehmigung eines Insolvenzgerichts in Delaware abgeschlossene Deal verschafft Keyrock die institutionellen Kundenbeziehungen, die Handelstechnologie und das Derivate-Talent von BlockFills in einer einzigen Transaktion.</p>
<p class="fr">Keyrock, un teneur de marché d'actifs numériques basé à Bruxelles, a acquis les actifs de trading et de courtage du courtier crypto institutionnel américain en faillite BlockFills pour 3,25 millions de dollars, a rapporté CoinDesk le 16 juillet. L'accord, finalisé avec l'approbation d'un tribunal des faillites du Delaware, donne à Keyrock les relations avec les clients institutionnels de BlockFills, sa technologie de trading et ses talents en dérivés en une seule transaction.</p>
<p class="pt">A Keyrock, uma formadora de mercado de ativos digitais sediada em Bruxelas, adquiriu os ativos de negociação e corretagem da corretora cripto institucional americana falida BlockFills por US$ 3,25 milhões, informou a CoinDesk em 16 de julho. O acordo, concluído com aprovação de um tribunal de falências de Delaware, dá à Keyrock os relacionamentos com clientes institucionais da BlockFills, sua tecnologia de negociação e seu talento em derivativos em uma única transação.</p>
<p class="tr">Brüksel merkezli dijital varlık piyasa yapıcısı Keyrock, iflas sürecindeki ABD merkezli kurumsal kripto brokerı BlockFills'in trading ve brokerlik varlıklarını 3,25 milyon dolara satın aldı; haberi 16 Temmuz'da CoinDesk duyurdu. Delaware iflas mahkemesinin onayıyla tamamlanan anlaşma, Keyrock'a BlockFills'in kurumsal müşteri ilişkilerini, trading teknolojisini ve türev ürün uzmanlığını tek bir işlemde kazandırdı.</p>
<p class="vi">Keyrock, nhà tạo lập thị trường tài sản số có trụ sở tại Brussels, đã mua lại các tài sản giao dịch và môi giới của công ty môi giới tiền mã hóa tổ chức Mỹ đang phá sản BlockFills với giá 3,25 triệu USD, CoinDesk đưa tin ngày 16/7. Thương vụ được hoàn tất với sự chấp thuận của tòa án phá sản Delaware, mang lại cho Keyrock các mối quan hệ khách hàng tổ chức, công nghệ giao dịch và nhân tài phái sinh của BlockFills trong một giao dịch duy nhất.</p>

<p class="ko">인수 대상에는 골드만삭스·도이체방크 출신으로 블록필스의 기관용 옵션 사업을 이끌었던 페리 파커, 리스크·트레이딩 운영을 총괄했던 댄 샤크 등 핵심 인력도 포함됐다. 키록은 이번 거래로 약 2,000곳의 기관 고객 관계를 즉시 확보하게 됐으며, 회사 측은 이를 통해 마켓메이킹·OTC트레이딩·옵션·신용·온체인서비스·자산관리로 이뤄진 기존 사업 포트폴리오 중 특히 빠르게 성장하던 디지털자산 파생상품 부문을 강화하게 됐다고 밝혔다. 지난 3월 스탠다드차타드 산하 SC벤처스가 주도한 시리즈C 라운드에서 기업가치 11억달러를 인정받은 키록은 220명 규모의 팀을 두고 37개국, 85개 거래소·플랫폼에서 활동해왔다.</p>
<p class="en">The acquisition brought in key personnel, including Perry Parker, a former Goldman Sachs and Deutsche Bank derivatives executive who led BlockFills' institutional options business, and Dan Schak, who oversaw its risk and trading operations. The deal gives Keyrock instant access to roughly 2,000 institutional client relationships, and the company said it strengthens its digital-asset derivatives business — one of its fastest-growing lines within an existing portfolio spanning market making, OTC trading, options, credit, onchain services and asset management. Keyrock, valued at $1.1 billion in a March Series C round led by Standard Chartered's SC Ventures, employs roughly 220 people and operates across 37 countries and 85 trading venues.</p>
<p class="ja">今回の買収では、ゴールドマン・サックスとドイツ銀行出身でブロックフィルズの機関投資家向けオプション事業を率いていたペリー・パーカー氏、リスク・トレーディング運営を統括していたダン・シャック氏ら主要人材も獲得した。この取引によりキーロックは約2,000の機関投資家との顧客関係を即座に確保することになり、同社はマーケットメイキング・OTCトレーディング・オプション・信用・オンチェーンサービス・資産運用からなる既存事業ポートフォリオの中でも特に急成長中だったデジタル資産デリバティブ部門を強化することになると述べた。3月にスタンダードチャータード傘下のSCベンチャーズ主導のシリーズCラウンドで企業価値11億ドルと評価されたキーロックは、220人規模のチームを擁し、37カ国、85の取引所・プラットフォームで活動してきた。</p>
<p class="es">La adquisición incorporó personal clave, incluido Perry Parker, exejecutivo de derivados de Goldman Sachs y Deutsche Bank que dirigía el negocio de opciones institucionales de BlockFills, y Dan Schak, quien supervisaba sus operaciones de riesgo y trading. El acuerdo le da a Keyrock acceso instantáneo a unas 2.000 relaciones con clientes institucionales, y la compañía dijo que fortalece su negocio de derivados de activos digitales, una de sus líneas de más rápido crecimiento dentro de un portafolio existente que abarca creación de mercado, trading OTC, opciones, crédito, servicios onchain y gestión de activos. Keyrock, valorada en 1.100 millones de dólares en una ronda Serie C en marzo liderada por SC Ventures de Standard Chartered, emplea a unas 220 personas y opera en 37 países y 85 plataformas de trading.</p>
<p class="de">Die Übernahme brachte auch Schlüsselpersonal mit, darunter Perry Parker, ein ehemaliger Derivate-Manager von Goldman Sachs und Deutsche Bank, der BlockFills' institutionelles Optionsgeschäft leitete, sowie Dan Schak, der für Risiko- und Handelsoperationen zuständig war. Der Deal verschafft Keyrock sofortigen Zugang zu rund 2.000 institutionellen Kundenbeziehungen, und das Unternehmen erklärte, dies stärke sein Digital-Asset-Derivategeschäft — eine der am schnellsten wachsenden Sparten innerhalb eines bestehenden Portfolios aus Market Making, OTC-Handel, Optionen, Krediten, Onchain-Diensten und Vermögensverwaltung. Keyrock, im März in einer von SC Ventures (Standard Chartered) geführten Series-C-Runde mit 1,1 Milliarden Dollar bewertet, beschäftigt rund 220 Mitarbeiter und ist in 37 Ländern und auf 85 Handelsplätzen aktiv.</p>
<p class="fr">L'acquisition a intégré du personnel clé, dont Perry Parker, ancien cadre dérivés chez Goldman Sachs et Deutsche Bank qui dirigeait l'activité d'options institutionnelles de BlockFills, et Dan Schak, qui supervisait ses opérations de risque et de trading. L'accord donne à Keyrock un accès instantané à environ 2 000 relations avec des clients institutionnels, et l'entreprise a déclaré que cela renforce son activité de dérivés d'actifs numériques, l'une de ses lignes à la croissance la plus rapide au sein d'un portefeuille existant couvrant la tenue de marché, le trading OTC, les options, le crédit, les services onchain et la gestion d'actifs. Keyrock, valorisée à 1,1 milliard de dollars lors d'un tour de série C en mars mené par SC Ventures de Standard Chartered, emploie environ 220 personnes et opère dans 37 pays et 85 plateformes de trading.</p>
<p class="pt">A aquisição trouxe pessoal-chave, incluindo Perry Parker, ex-executivo de derivativos do Goldman Sachs e do Deutsche Bank que liderava o negócio de opções institucionais da BlockFills, e Dan Schak, que supervisionava suas operações de risco e negociação. O acordo dá à Keyrock acesso instantâneo a cerca de 2.000 relacionamentos com clientes institucionais, e a empresa disse que isso fortalece seu negócio de derivativos de ativos digitais — uma de suas linhas de crescimento mais rápido dentro de um portfólio existente que abrange formação de mercado, negociação OTC, opções, crédito, serviços onchain e gestão de ativos. A Keyrock, avaliada em US$ 1,1 bilhão em uma rodada Série C em março liderada pela SC Ventures do Standard Chartered, emprega cerca de 220 pessoas e opera em 37 países e 85 plataformas de negociação.</p>
<p class="tr">Satın alma, BlockFills'in kurumsal opsiyon işini yöneten eski Goldman Sachs ve Deutsche Bank türev ürünler yöneticisi Perry Parker ile risk ve trading operasyonlarını denetleyen Dan Schak dahil kilit personeli de beraberinde getirdi. Anlaşma, Keyrock'a yaklaşık 2.000 kurumsal müşteri ilişkisine anında erişim sağlıyor; şirket bunun, piyasa yapıcılığı, OTC trading, opsiyonlar, kredi, zincir üstü hizmetler ve varlık yönetiminden oluşan mevcut portföyü içinde en hızlı büyüyen hatlarından biri olan dijital varlık türev ürünleri işini güçlendirdiğini belirtti. Mart ayında Standard Chartered'ın SC Ventures'ının liderliğindeki Seri C turunda 1,1 milyar dolar değerlemesi alan Keyrock, yaklaşık 220 kişi istihdam ediyor ve 37 ülkede, 85 işlem platformunda faaliyet gösteriyor.</p>
<p class="vi">Thương vụ mua lại đã mang về nhân sự chủ chốt, bao gồm Perry Parker, cựu giám đốc phái sinh của Goldman Sachs và Deutsche Bank, người từng dẫn dắt mảng quyền chọn tổ chức của BlockFills, và Dan Schak, người giám sát hoạt động rủi ro và giao dịch. Thương vụ mang lại cho Keyrock quyền tiếp cận ngay lập tức với khoảng 2.000 mối quan hệ khách hàng tổ chức, và công ty cho biết điều này củng cố mảng phái sinh tài sản số của họ — một trong những mảng tăng trưởng nhanh nhất trong danh mục hiện có gồm tạo lập thị trường, giao dịch OTC, quyền chọn, tín dụng, dịch vụ onchain và quản lý tài sản. Keyrock, được định giá 1,1 tỷ USD trong vòng gọi vốn Series C hồi tháng 3 do SC Ventures thuộc Standard Chartered dẫn dắt, có khoảng 220 nhân viên và hoạt động tại 37 quốc gia, trên 85 nền tảng giao dịch.</p>

<h2 class="ko">610억달러를 처리하던 회사가 325만달러에 팔린 경로</h2>
<h2 class="en">How a Firm That Processed $61 Billion Ended Up Sold for $3.25 Million</h2>
<h2 class="ja">610億ドルを処理していた企業が325万ドルで売却された経緯</h2>
<h2 class="es">Cómo una firma que procesó 61.000 millones de dólares terminó vendida por 3,25 millones</h2>
<h2 class="de">Wie eine Firma, die 61 Milliarden Dollar abwickelte, für 3,25 Millionen Dollar verkauft wurde</h2>
<h2 class="fr">Comment une société qui traitait 61 milliards de dollars a fini vendue pour 3,25 millions</h2>
<h2 class="pt">Como uma empresa que processou US$ 61 bilhões acabou vendida por US$ 3,25 milhões</h2>
<h2 class="tr">61 Milyar Dolar İşleyen Bir Şirket Nasıl 3,25 Milyon Dolara Satıldı</h2>
<h2 class="vi">Một Công Ty Từng Xử Lý 61 Tỷ USD Đã Bị Bán Với Giá 3,25 Triệu USD Như Thế Nào</h2>

<p class="ko">블록필스는 한때 누적 610억달러 이상의 거래량을 처리했던 기관용 크립토 유동성 공급업체였다. 그러나 지난 2월 인출 요청이 몰리면서 유동성 관리에 실패해 입출금을 전면 중단했고, 이후 고객 자금 유용·전환·계약위반을 주장하는 소송이 뉴욕남부지법(2월 27일)과 일리노이북부지법(3월 5일)에 잇따라 제기됐다. 결국 모회사인 렐리즈테크놀로지그룹홀딩스와 계열사 3곳이 3월 15일 델라웨어주 파산법원에 챕터11(회생) 신청을 했다. 법원 문서에 따르면 자산은 5,000만~1억달러 수준인 반면 부채는 최대 5억달러에 달해, 회수 가능한 자산 대비 부채가 최대 10배에 이르는 심각한 자본잠식 상태였던 것으로 나타났다.</p>
<p class="en">BlockFills was once an institutional crypto liquidity provider that had processed more than $61 billion in cumulative trading volume. But in February, a surge of withdrawal requests overwhelmed its liquidity management, forcing the firm to halt deposits and withdrawals entirely. Lawsuits alleging misappropriation of customer funds, conversion and breach of contract followed in quick succession — one filed in the Southern District of New York on Feb. 27, another in the Northern District of Illinois on March 5. The parent, Reliz Technology Group Holdings, and three affiliates then filed for Chapter 11 in Delaware bankruptcy court on March 15. Court filings showed assets of just $50 million to $100 million against liabilities as high as $500 million — a capital shortfall of up to 10-to-1 relative to recoverable assets.</p>
<p class="ja">ブロックフィルズはかつて累計610億ドル以上の取引量を処理していた機関投資家向け暗号資産流動性プロバイダーだった。しかし2月、出金要請が殺到したことで流動性管理が破綻し、入出金を全面停止せざるを得なくなった。その後、顧客資金の流用・転換・契約違反を主張する訴訟が相次いで提起された。2月27日にニューヨーク南部地区連邦地裁、3月5日にイリノイ北部地区連邦地裁でそれぞれ提訴された。最終的に親会社のレリズ・テクノロジー・グループ・ホールディングスと関連会社3社が3月15日、デラウェア州破産裁判所にチャプター11(会社更生)を申請した。裁判所文書によれば、資産はわずか5,000万~1億ドルにとどまる一方、負債は最大5億ドルに達しており、回収可能な資産に対して最大10倍の深刻な資本毀損状態にあったことが明らかになった。</p>
<p class="es">BlockFills fue en su momento un proveedor institucional de liquidez cripto que había procesado más de 61.000 millones de dólares en volumen de trading acumulado. Pero en febrero, una oleada de solicitudes de retiro desbordó su gestión de liquidez, obligando a la firma a suspender por completo depósitos y retiros. A eso siguieron rápidamente demandas que alegaban malversación de fondos de clientes, conversión y incumplimiento de contrato: una presentada en el Distrito Sur de Nueva York el 27 de febrero, otra en el Distrito Norte de Illinois el 5 de marzo. La matriz, Reliz Technology Group Holdings, y tres filiales se acogieron al Capítulo 11 en un tribunal de quiebras de Delaware el 15 de marzo. Los documentos judiciales mostraron activos de apenas 50 a 100 millones de dólares frente a pasivos de hasta 500 millones, un déficit de capital de hasta 10 a 1 respecto a los activos recuperables.</p>
<p class="de">BlockFills war einst ein institutioneller Krypto-Liquiditätsanbieter, der ein kumuliertes Handelsvolumen von über 61 Milliarden Dollar abgewickelt hatte. Doch im Februar überforderte eine Welle von Auszahlungsanträgen das Liquiditätsmanagement, sodass die Firma Einzahlungen und Auszahlungen vollständig einstellen musste. Es folgten rasch Klagen wegen mutmaßlicher Veruntreuung von Kundengeldern, widerrechtlicher Aneignung und Vertragsbruchs — eine eingereicht im südlichen Bezirk von New York am 27. Februar, eine weitere im nördlichen Bezirk von Illinois am 5. März. Die Muttergesellschaft Reliz Technology Group Holdings und drei verbundene Unternehmen meldeten am 15. März Chapter-11-Insolvenz beim Insolvenzgericht in Delaware an. Gerichtsunterlagen zeigten Vermögenswerte von nur 50 bis 100 Millionen Dollar gegenüber Verbindlichkeiten von bis zu 500 Millionen Dollar — eine Kapitallücke von bis zu 10 zu 1 gegenüber den verwertbaren Vermögenswerten.</p>
<p class="fr">BlockFills était autrefois un fournisseur institutionnel de liquidité crypto ayant traité plus de 61 milliards de dollars de volume de trading cumulé. Mais en février, une vague de demandes de retrait a submergé sa gestion de liquidité, forçant l'entreprise à suspendre entièrement dépôts et retraits. Des poursuites alléguant détournement de fonds clients, conversion et rupture de contrat ont rapidement suivi — l'une déposée dans le district sud de New York le 27 février, une autre dans le district nord de l'Illinois le 5 mars. La société mère, Reliz Technology Group Holdings, et trois filiales ont ensuite déposé le bilan sous le régime du Chapitre 11 auprès du tribunal des faillites du Delaware le 15 mars. Les documents judiciaires ont révélé des actifs de seulement 50 à 100 millions de dollars face à des passifs allant jusqu'à 500 millions de dollars — un déficit de capital allant jusqu'à 10 contre 1 par rapport aux actifs récupérables.</p>
<p class="pt">A BlockFills foi outrora uma provedora institucional de liquidez cripto que processou mais de US$ 61 bilhões em volume acumulado de negociação. Mas em fevereiro, uma onda de pedidos de saque sobrecarregou sua gestão de liquidez, forçando a empresa a suspender totalmente depósitos e saques. Processos alegando desvio de fundos de clientes, conversão indevida e quebra de contrato vieram na sequência — um protocolado no Distrito Sul de Nova York em 27 de fevereiro, outro no Distrito Norte de Illinois em 5 de março. A controladora, Reliz Technology Group Holdings, e três afiliadas então entraram com pedido de recuperação judicial (Chapter 11) no tribunal de falências de Delaware em 15 de março. Documentos judiciais mostraram ativos de apenas US$ 50 milhões a US$ 100 milhões contra passivos de até US$ 500 milhões — um déficit de capital de até 10 para 1 em relação aos ativos recuperáveis.</p>
<p class="tr">BlockFills bir zamanlar toplam 61 milyar dolardan fazla işlem hacmi işlemiş kurumsal bir kripto likidite sağlayıcısıydı. Ancak şubat ayında, çekim taleplerindeki ani artış likidite yönetimini altüst etti ve şirketi mevduat ile çekimleri tamamen durdurmaya zorladı. Ardından müşteri fonlarının kötüye kullanımını, haksız el koymayı ve sözleşme ihlalini iddia eden davalar art arda geldi — biri 27 Şubat'ta New York Güney Bölgesi'nde, diğeri 5 Mart'ta Illinois Kuzey Bölgesi'nde açıldı. Ana şirket Reliz Technology Group Holdings ve üç bağlı kuruluş, 15 Mart'ta Delaware iflas mahkemesinde Chapter 11 başvurusunda bulundu. Mahkeme belgeleri, varlıkların yalnızca 50-100 milyon dolar olduğunu, buna karşılık yükümlülüklerin 500 milyon dolara kadar çıktığını gösterdi — kurtarılabilir varlıklara göre 10 kata varan bir sermaye açığı.</p>
<p class="vi">BlockFills từng là nhà cung cấp thanh khoản tiền mã hóa cho tổ chức, đã xử lý hơn 61 tỷ USD khối lượng giao dịch lũy kế. Nhưng vào tháng 2, làn sóng yêu cầu rút tiền đã áp đảo khả năng quản lý thanh khoản, buộc công ty phải ngừng hoàn toàn việc gửi và rút tiền. Các vụ kiện cáo buộc chiếm dụng tiền của khách hàng, chuyển đổi trái phép và vi phạm hợp đồng nhanh chóng theo sau — một vụ nộp tại Tòa án Quận Nam New York ngày 27/2, vụ khác tại Tòa án Quận Bắc Illinois ngày 5/3. Công ty mẹ Reliz Technology Group Holdings cùng ba công ty liên kết sau đó đã nộp đơn xin bảo hộ phá sản theo Chapter 11 tại tòa án phá sản Delaware vào ngày 15/3. Hồ sơ tòa án cho thấy tài sản chỉ từ 50 đến 100 triệu USD trong khi nợ phải trả lên tới 500 triệu USD — thiếu hụt vốn lên tới 10 lần so với tài sản có thể thu hồi.</p>

<p class="ko">이 붕괴 경로는 2022년 셀시우스·보이저·제네시스 등 크립토 대출업체들이 무너졌던 패턴과 본질적으로 같다. 고객 자산을 자체 트레이딩·대출·채굴 사업에 재투자해 수익을 내는 구조였던 업체가, 시장이 흔들리며 대규모 인출 요청이 몰리자 유동성이 없어 지급불능에 빠지는 '뱅크런형' 붕괴다. 다만 2022년 사례들과 달리 이번 블록필스 파산은 특정 코인 폭락이나 연쇄 디폴트가 아니라 개별 기업의 리스크 관리 실패로 촉발됐다는 점에서, 시장 전반의 전염 위험보다는 기관 크립토 브로커리지 업종 안에 여전히 존재하는 구조적 취약점을 보여준 사례로 읽는 편이 더 정확하다. 즉 크립토 시장이 성숙해졌다고 해도, 고객자산과 자기자본을 뒤섞어 운용하는 사업모델 자체의 위험은 줄어들지 않았다는 뜻이다.</p>
<p class="en">This collapse pattern is fundamentally the same as what took down crypto lenders Celsius, Voyager and Genesis in 2022: a firm that reinvests customer assets into its own trading, lending or mining operations to generate yield, then becomes insolvent once a surge of withdrawal requests hits and there isn't enough liquidity to meet them — a bank-run-style failure. Unlike 2022, though, BlockFills' bankruptcy wasn't triggered by a specific token crash or a chain of cross-defaults; it stemmed from one firm's own risk-management failure, which makes it more accurate to read as evidence of a structural vulnerability that still exists within institutional crypto brokerage as an industry, rather than a sign of market-wide contagion risk. In other words, even as crypto markets have matured, the underlying risk of business models that commingle customer assets with proprietary capital hasn't gone away.</p>
<p class="ja">この崩壊パターンは、2022年にセルシウス・ボイジャー・ジェネシスといった暗号資産貸出業者を沈めたものと本質的に同じだ。顧客資産を自社のトレーディング・貸出・マイニング事業に再投資して収益を上げる構造の企業が、市場が揺らぎ大規模な出金要請が殺到した際に十分な流動性がなく支払不能に陥る、いわば「取り付け騒ぎ型」の崩壊である。ただし2022年の事例とは異なり、今回のブロックフィルズの破産は特定コインの暴落や連鎖的デフォルトではなく、個別企業のリスク管理の失敗によって引き起こされた。この点で、市場全体への伝染リスクというより、機関投資家向け暗号資産ブローカレッジ業界に依然として存在する構造的な脆弱性を示す事例として読むほうがより正確だろう。つまり暗号資産市場が成熟したとしても、顧客資産と自己資本を混在させて運用するビジネスモデル自体のリスクは減っていないということだ。</p>
<p class="es">Este patrón de colapso es fundamentalmente el mismo que derribó a los prestamistas cripto Celsius, Voyager y Genesis en 2022: una firma que reinvierte activos de clientes en sus propias operaciones de trading, préstamos o minería para generar rendimiento, y luego se vuelve insolvente cuando una oleada de solicitudes de retiro la golpea y no hay suficiente liquidez para atenderlas —un colapso al estilo corrida bancaria. Sin embargo, a diferencia de 2022, la quiebra de BlockFills no fue provocada por el desplome de un token específico ni por una cadena de impagos cruzados; se originó en el propio fallo de gestión de riesgo de la firma, lo que hace más preciso leerla como evidencia de una vulnerabilidad estructural que aún persiste en la industria de la correduría cripto institucional, más que como señal de riesgo de contagio a todo el mercado. En otras palabras, aunque los mercados cripto hayan madurado, el riesgo subyacente de los modelos de negocio que mezclan activos de clientes con capital propio no ha desaparecido.</p>
<p class="de">Dieses Zusammenbruchsmuster gleicht im Kern dem, das 2022 die Krypto-Kreditgeber Celsius, Voyager und Genesis zu Fall brachte: Eine Firma reinvestiert Kundengelder in ihre eigenen Handels-, Kredit- oder Mining-Geschäfte, um Rendite zu erzielen, und wird dann zahlungsunfähig, sobald eine Welle von Auszahlungsanträgen eintrifft und nicht genug Liquidität vorhanden ist, um sie zu bedienen — ein Zusammenbruch im Stil eines Bank-Runs. Anders als 2022 wurde die Insolvenz von BlockFills jedoch nicht durch den Absturz eines bestimmten Tokens oder eine Kette von Kreuzausfällen ausgelöst; sie entstand aus dem eigenen Risikomanagement-Versagen einer einzelnen Firma, was es treffender macht, sie als Beleg für eine strukturelle Schwachstelle zu lesen, die in der institutionellen Krypto-Brokerage-Branche als Ganzes weiterhin besteht, statt als Zeichen eines marktweiten Ansteckungsrisikos. Mit anderen Worten: Auch wenn die Kryptomärkte gereift sind, ist das zugrundeliegende Risiko von Geschäftsmodellen, die Kundengelder mit Eigenkapital vermischen, nicht verschwunden.</p>
<p class="fr">Ce schéma d'effondrement est fondamentalement le même que celui qui a fait tomber les prêteurs crypto Celsius, Voyager et Genesis en 2022 : une entreprise réinvestit les actifs des clients dans ses propres opérations de trading, de prêt ou de minage pour générer du rendement, puis devient insolvable lorsqu'une vague de demandes de retrait survient sans liquidité suffisante pour y répondre — un effondrement de type ruée bancaire. Contrairement à 2022, cependant, la faillite de BlockFills n'a pas été déclenchée par l'effondrement d'un token spécifique ou une chaîne de défauts croisés ; elle découle de l'échec de gestion des risques propre à cette entreprise, ce qui rend plus juste d'y voir la preuve d'une vulnérabilité structurelle qui persiste dans le secteur du courtage crypto institutionnel, plutôt qu'un signe de risque de contagion à l'ensemble du marché. Autrement dit, même si les marchés crypto ont mûri, le risque sous-jacent des modèles économiques mêlant actifs clients et capital propre n'a pas disparu.</p>
<p class="pt">Esse padrão de colapso é fundamentalmente o mesmo que derrubou as credoras cripto Celsius, Voyager e Genesis em 2022: uma empresa reinveste ativos de clientes em suas próprias operações de negociação, empréstimo ou mineração para gerar rendimento, e depois se torna insolvente quando uma onda de pedidos de saque chega e não há liquidez suficiente para atendê-los — um colapso no estilo corrida bancária. Diferentemente de 2022, porém, a falência da BlockFills não foi desencadeada pelo colapso de um token específico ou por uma cadeia de inadimplências cruzadas; ela decorreu da própria falha de gestão de risco da empresa, o que torna mais preciso interpretá-la como evidência de uma vulnerabilidade estrutural que ainda persiste no setor de corretagem cripto institucional, e não como sinal de risco de contágio para todo o mercado. Em outras palavras, mesmo com a maturidade dos mercados cripto, o risco subjacente de modelos de negócio que misturam ativos de clientes com capital próprio não desapareceu.</p>
<p class="tr">Bu çöküş kalıbı, 2022'de kripto kredi kuruluşları Celsius, Voyager ve Genesis'i çökerten kalıpla temelde aynıdır: Müşteri varlıklarını getiri elde etmek için kendi trading, kredi veya madencilik operasyonlarına yeniden yatıran bir şirket, piyasa sarsıldığında ve büyük bir çekim talebi dalgası geldiğinde, bunları karşılayacak yeterli likidite olmadığı için ödeme güçlüğüne düşer — banka hücumu tarzı bir çöküş. Ancak 2022'deki örneklerden farklı olarak, BlockFills'in iflası belirli bir token çöküşü veya zincirleme temerrütler tarafından değil, şirketin kendi risk yönetimi başarısızlığı tarafından tetiklendi. Bu da olayı, piyasa çapında bir bulaşma riski işaretinden ziyade, kurumsal kripto brokerlik sektöründe hâlâ var olan yapısal bir zayıflığın kanıtı olarak okumayı daha doğru kılıyor. Başka bir deyişle, kripto piyasaları olgunlaşmış olsa da, müşteri varlıklarını özkaynakla harmanlayan iş modellerinin taşıdığı temel risk ortadan kalkmadı.</p>
<p class="vi">Mô hình sụp đổ này về bản chất giống với những gì đã hạ gục các bên cho vay tiền mã hóa Celsius, Voyager và Genesis vào năm 2022: một công ty tái đầu tư tài sản khách hàng vào các hoạt động giao dịch, cho vay hoặc khai thác của chính mình để tạo lợi suất, rồi mất khả năng thanh toán khi làn sóng yêu cầu rút tiền ập đến mà không đủ thanh khoản để đáp ứng — một kiểu sụp đổ giống rút tiền hàng loạt ngân hàng. Tuy nhiên, khác với năm 2022, vụ phá sản của BlockFills không phải do sự sụp đổ của một token cụ thể hay chuỗi vỡ nợ chéo gây ra; nó bắt nguồn từ chính sự thất bại trong quản lý rủi ro của công ty, điều này khiến việc coi đây là bằng chứng cho một điểm yếu mang tính cấu trúc vẫn tồn tại trong ngành môi giới tiền mã hóa tổ chức, thay vì là dấu hiệu của rủi ro lây lan toàn thị trường, trở nên chính xác hơn. Nói cách khác, dù thị trường tiền mã hóa đã trưởng thành hơn, rủi ro nền tảng của các mô hình kinh doanh trộn lẫn tài sản khách hàng với vốn tự có vẫn chưa biến mất.</p>

<h2 class="ko">헐값 인수의 경제학 — 왜 마켓메이커들이 파산 자산을 사들이나</h2>
<h2 class="en">The Economics of a Fire Sale — Why Market Makers Buy Bankrupt Assets</h2>
<h2 class="ja">投げ売り買収の経済学 — なぜマーケットメイカーは破産資産を買うのか</h2>
<h2 class="es">La economía de una liquidación forzosa: por qué los creadores de mercado compran activos en quiebra</h2>
<h2 class="de">Die Ökonomie eines Notverkaufs — warum Market Maker insolvente Vermögenswerte kaufen</h2>
<h2 class="fr">L'économie d'une vente de détresse — pourquoi les teneurs de marché achètent des actifs en faillite</h2>
<h2 class="pt">A economia de uma liquidação forçada — por que formadores de mercado compram ativos falidos</h2>
<h2 class="tr">Zorunlu Satışın Ekonomisi — Piyasa Yapıcılar Neden İflas Etmiş Varlıkları Satın Alıyor</h2>
<h2 class="vi">Kinh Tế Học Của Một Vụ Bán Tháo — Vì Sao Các Nhà Tạo Lập Thị Trường Mua Tài Sản Phá Sản</h2>

<p class="ko">한때 610억달러 규모의 거래량을 처리하던 회사가 325만달러, 즉 매출 규모 대비 1만분의 1 수준의 헐값에 팔린 것은 파산 매각 특유의 가격 구조를 보여준다. 챕터11 매각에서 인수자는 부채·소송 리스크·고객 신뢰 훼손이라는 짐을 떠안지 않고 원하는 자산(고객 관계·기술·인력)만 선별해 가져갈 수 있다. 키록 입장에서 325만달러는 2,000개 기관 고객을 처음부터 영업으로 유치하는 데 드는 시간과 비용, 그리고 파커·샤크 같은 전문인력을 스카우트하는 비용과 비교하면 매우 저렴한 지름길이다. 실제로 키록은 지난 6월 1일 이미 인수 의사를 밝혔고, 이번 발표는 파산법원 절차를 마치고 거래를 공식 완료했다는 확인에 해당한다.</p>
<p class="en">A firm that once processed $61 billion in trading volume selling for $3.25 million — roughly one ten-thousandth of that figure — illustrates the peculiar pricing dynamics of a bankruptcy sale. In a Chapter 11 sale, a buyer can cherry-pick the assets it wants (client relationships, technology, personnel) without inheriting the liabilities, litigation exposure or reputational damage that came with the seller. For Keyrock, $3.25 million is a bargain shortcut compared with the time and cost of organically winning 2,000 institutional clients from scratch, or recruiting specialists like Parker and Schak individually. Keyrock first signaled its intent to acquire BlockFills on June 1; this week's announcement confirms the deal formally closed after clearing the bankruptcy court process.</p>
<p class="ja">かつて610億ドル規模の取引量を処理していた企業が、その1万分の1程度にすぎない325万ドルという安値で売却されたことは、破産売却特有の価格構造を示している。チャプター11売却では、買収者は負債・訴訟リスク・顧客信頼の毀損という重荷を引き継ぐことなく、欲しい資産(顧客関係・技術・人材)だけを選んで取得できる。キーロックにとって325万ドルは、2,000の機関顧客をゼロから営業で獲得するのにかかる時間とコスト、あるいはパーカーやシャックのような専門人材を個別にスカウトするコストと比べれば、非常に安い近道だ。実際キーロックは既に6月1日の時点で買収意向を表明しており、今回の発表は破産裁判所の手続きを経て取引を正式に完了したことの確認にあたる。</p>
<p class="es">Una firma que alguna vez procesó 61.000 millones de dólares en volumen de trading, vendida por 3,25 millones —aproximadamente una diezmilésima parte de esa cifra—, ilustra la peculiar dinámica de precios de una venta por quiebra. En una venta bajo el Capítulo 11, un comprador puede seleccionar solo los activos que desea (relaciones con clientes, tecnología, personal) sin heredar los pasivos, la exposición a litigios ni el daño reputacional que arrastraba el vendedor. Para Keyrock, 3,25 millones es un atajo de ganga comparado con el tiempo y el costo de conquistar orgánicamente 2.000 clientes institucionales desde cero, o de reclutar individualmente a especialistas como Parker y Schak. Keyrock señaló por primera vez su intención de adquirir BlockFills el 1 de junio; el anuncio de esta semana confirma que el acuerdo se cerró formalmente tras superar el proceso del tribunal de quiebras.</p>
<p class="de">Eine Firma, die einst 61 Milliarden Dollar an Handelsvolumen abwickelte und für 3,25 Millionen Dollar verkauft wird — etwa ein Zehntausendstel dieser Summe —, veranschaulicht die eigentümliche Preisdynamik eines Insolvenzverkaufs. Bei einem Chapter-11-Verkauf kann ein Käufer sich gezielt die gewünschten Vermögenswerte (Kundenbeziehungen, Technologie, Personal) herauspicken, ohne die Verbindlichkeiten, das Prozessrisiko oder den Reputationsschaden des Verkäufers zu übernehmen. Für Keyrock sind 3,25 Millionen Dollar eine günstige Abkürzung im Vergleich zu Zeit und Kosten, 2.000 institutionelle Kunden organisch von Grund auf zu gewinnen oder Spezialisten wie Parker und Schak einzeln abzuwerben. Keyrock signalisierte seine Übernahmeabsicht erstmals am 1. Juni; die Ankündigung dieser Woche bestätigt, dass der Deal nach Abschluss des Insolvenzgerichtsverfahrens formell besiegelt wurde.</p>
<p class="fr">Une entreprise qui traitait autrefois 61 milliards de dollars de volume de trading vendue pour 3,25 millions de dollars — environ un dix-millième de ce chiffre — illustre la dynamique de prix particulière d'une vente en faillite. Dans une vente sous Chapitre 11, un acheteur peut sélectionner uniquement les actifs qu'il souhaite (relations clients, technologie, personnel) sans hériter des passifs, de l'exposition aux litiges ni des dommages réputationnels du vendeur. Pour Keyrock, 3,25 millions de dollars représentent un raccourci avantageux comparé au temps et au coût nécessaires pour conquérir organiquement 2 000 clients institutionnels à partir de zéro, ou pour recruter individuellement des spécialistes comme Parker et Schak. Keyrock avait déjà signalé son intention d'acquérir BlockFills le 1er juin ; l'annonce de cette semaine confirme que l'accord a été formellement conclu après la procédure du tribunal des faillites.</p>
<p class="pt">Uma empresa que já processou US$ 61 bilhões em volume de negociação sendo vendida por US$ 3,25 milhões — cerca de um décimo de milésimo desse valor — ilustra a dinâmica peculiar de preços de uma venda por falência. Em uma venda sob o Chapter 11, um comprador pode escolher apenas os ativos que deseja (relacionamentos com clientes, tecnologia, pessoal) sem herdar os passivos, a exposição a litígios ou os danos reputacionais que acompanhavam o vendedor. Para a Keyrock, US$ 3,25 milhões é um atalho vantajoso comparado ao tempo e custo de conquistar organicamente 2.000 clientes institucionais do zero, ou de recrutar individualmente especialistas como Parker e Schak. A Keyrock já havia sinalizado sua intenção de adquirir a BlockFills em 1º de junho; o anúncio desta semana confirma que o negócio foi formalmente fechado após o processo no tribunal de falências.</p>
<p class="tr">Bir zamanlar 61 milyar dolarlık işlem hacmi işleyen bir şirketin bu rakamın yaklaşık on binde biri olan 3,25 milyon dolara satılması, bir iflas satışının kendine özgü fiyatlama dinamiğini gösteriyor. Chapter 11 satışında alıcı, satıcının yükümlülüklerini, dava risklerini veya itibar zedelenmesini devralmadan istediği varlıkları (müşteri ilişkileri, teknoloji, personel) seçerek alabilir. Keyrock açısından 3,25 milyon dolar, 2.000 kurumsal müşteriyi sıfırdan organik olarak kazanmanın ya da Parker ve Schak gibi uzmanları tek tek transfer etmenin zaman ve maliyetiyle kıyaslandığında ucuz bir kısayoldur. Keyrock, satın alma niyetini ilk kez 1 Haziran'da açıklamıştı; bu haftaki duyuru, anlaşmanın iflas mahkemesi sürecini tamamladıktan sonra resmen kapandığını doğruluyor.</p>
<p class="vi">Một công ty từng xử lý 61 tỷ USD khối lượng giao dịch được bán với giá 3,25 triệu USD — chỉ bằng khoảng một phần vạn con số đó — minh họa cho động lực định giá đặc thù của một thương vụ bán tài sản phá sản. Trong một thương vụ bán theo Chapter 11, bên mua có thể chọn lọc chỉ những tài sản mình muốn (quan hệ khách hàng, công nghệ, nhân sự) mà không phải gánh các khoản nợ, rủi ro kiện tụng hay tổn hại danh tiếng đi kèm với bên bán. Đối với Keyrock, 3,25 triệu USD là một lối tắt hời so với thời gian và chi phí để chinh phục 2.000 khách hàng tổ chức từ đầu một cách hữu cơ, hoặc tuyển dụng riêng lẻ các chuyên gia như Parker và Schak. Keyrock lần đầu phát tín hiệu ý định mua lại BlockFills vào ngày 1/6; thông báo tuần này xác nhận thương vụ đã chính thức hoàn tất sau khi vượt qua thủ tục tòa án phá sản.</p>

<p class="ko">이런 패턴은 새로운 것이 아니다. 2022~2023년 FTX·셀시우스·보이저·제네시스가 잇따라 파산했을 때도, 바이낸스US·크라켄·갤럭시디지털을 비롯한 생존 기업들이 파산 자산과 고객 명부를 헐값에 인수하며 시장 구조를 재편했다. 다만 이번 사례가 시사하는 바는 조금 다르다. 2022년 인수전이 '살아남은 대형 거래소가 무너진 대형 거래소를 흡수'하는 구도였다면, 이번 키록-블록필스 거래는 상대적으로 신생 기업에 가까운 마켓메이커가 파생상품 전문성이라는 특정 역량을 목표로 기관 브로커리지 자산을 인수한 사례다. 이는 크립토 기관화가 진행되면서 파산이 나더라도 그 자산이 시장 밖으로 사라지지 않고, 곧바로 다른 사업자의 손에 넘어가 서비스가 연속되는 구조로 업계가 재편되고 있음을 보여준다. 다만 이 재편이 곧 리스크 관리 수준의 향상을 의미하는 것은 아니라는 점은 유의할 필요가 있다 — 자산을 인수한 새 주인이 같은 실수를 반복하지 않으리라는 보장은 없기 때문이다.</p>
<p class="en">This pattern isn't new. When FTX, Celsius, Voyager and Genesis collapsed in succession during 2022-2023, survivors including Binance.US, Kraken and Galaxy Digital snapped up bankrupt assets and customer books at fire-sale prices, reshaping the market's structure. What's slightly different here is the shape of the deal: the 2022 wave was largely "surviving mega-exchanges absorbing fallen mega-exchanges," while Keyrock-BlockFills is a relatively young market maker acquiring institutional brokerage assets to target one specific capability — derivatives expertise. That points to crypto's institutionalization proceeding in a way where, even when a firm fails, its assets don't disappear from the market; they get absorbed almost immediately by another operator, keeping service continuity intact. It's worth noting, though, that this consolidation doesn't automatically mean better risk management going forward — there's no guarantee the new owner of these assets won't repeat the same mistakes.</p>
<p class="ja">このパターンは新しいものではない。2022~2023年にFTX・セルシウス・ボイジャー・ジェネシスが相次いで破産した際も、バイナンスUS・クラーケン・ギャラクシーデジタルといった生き残った企業が破産資産や顧客リストを安値で買収し、市場構造を再編した。ただし今回のケースが示唆する点はやや異なる。2022年の買収劇が「生き残った大手取引所が倒れた大手取引所を吸収する」構図だったのに対し、今回のキーロック・ブロックフィルズの取引は、比較的新興に近いマーケットメイカーがデリバティブ専門性という特定の能力を狙って機関投資家向けブローカレッジ資産を買収した事例だ。これは、暗号資産の機関投資家化が進む中で、たとえ破産が起きても資産が市場から消えることなく、すぐに別の事業者の手に渡りサービスの連続性が保たれる構造へと業界が再編されつつあることを示している。ただし、この再編が直ちにリスク管理水準の向上を意味するわけではない点には留意が必要だ — 資産を取得した新たな所有者が同じ過ちを繰り返さない保証はないからだ。</p>
<p class="es">Este patrón no es nuevo. Cuando FTX, Celsius, Voyager y Genesis colapsaron sucesivamente en 2022-2023, sobrevivientes como Binance.US, Kraken y Galaxy Digital arrasaron con activos en quiebra y carteras de clientes a precios de liquidación, remodelando la estructura del mercado. Lo que es ligeramente diferente aquí es la forma del acuerdo: la ola de 2022 fue en gran medida "megabolsas sobrevivientes absorbiendo megabolsas caídas", mientras que Keyrock-BlockFills es un creador de mercado relativamente joven adquiriendo activos de correduría institucional para apuntar a una capacidad específica: experiencia en derivados. Eso apunta a que la institucionalización cripto avanza de manera que, incluso cuando una firma fracasa, sus activos no desaparecen del mercado; son absorbidos casi de inmediato por otro operador, manteniendo intacta la continuidad del servicio. Vale la pena señalar, sin embargo, que esta consolidación no significa automáticamente una mejor gestión de riesgos de ahí en adelante: no hay garantía de que el nuevo propietario de estos activos no repita los mismos errores.</p>
<p class="de">Dieses Muster ist nicht neu. Als FTX, Celsius, Voyager und Genesis 2022-2023 nacheinander zusammenbrachen, griffen Überlebende wie Binance.US, Kraken und Galaxy Digital zu Ausverkaufspreisen nach insolventen Vermögenswerten und Kundenlisten und formten damit die Marktstruktur neu. Etwas anders ist hier die Form des Deals: Die Welle von 2022 bestand größtenteils aus „überlebende Mega-Börsen absorbieren gefallene Mega-Börsen", während Keyrock-BlockFills ein relativ junger Market Maker ist, der institutionelle Brokerage-Vermögenswerte erwirbt, um gezielt eine bestimmte Fähigkeit anzugehen — Derivate-Expertise. Das deutet darauf hin, dass sich die Institutionalisierung von Krypto so entwickelt, dass selbst beim Scheitern einer Firma deren Vermögenswerte nicht vom Markt verschwinden; sie werden fast sofort von einem anderen Akteur absorbiert, wodurch die Servicekontinuität erhalten bleibt. Es lohnt sich jedoch festzuhalten, dass diese Konsolidierung nicht automatisch besseres Risikomanagement für die Zukunft bedeutet — es gibt keine Garantie, dass der neue Eigentümer dieser Vermögenswerte nicht dieselben Fehler wiederholt.</p>
<p class="fr">Ce schéma n'est pas nouveau. Lorsque FTX, Celsius, Voyager et Genesis se sont effondrés successivement en 2022-2023, des survivants comme Binance.US, Kraken et Galaxy Digital ont raflé des actifs en faillite et des portefeuilles clients à prix cassés, remodelant la structure du marché. Ce qui diffère légèrement ici, c'est la forme de l'accord : la vague de 2022 relevait largement de « méga-bourses survivantes absorbant des méga-bourses déchues », tandis que Keyrock-BlockFills est un teneur de marché relativement jeune acquérant des actifs de courtage institutionnel pour viser une capacité spécifique — l'expertise en dérivés. Cela suggère que l'institutionnalisation de la crypto progresse de telle manière que, même lorsqu'une entreprise échoue, ses actifs ne disparaissent pas du marché ; ils sont absorbés presque immédiatement par un autre opérateur, préservant la continuité du service. Il convient toutefois de noter que cette consolidation ne signifie pas automatiquement une meilleure gestion des risques à l'avenir — rien ne garantit que le nouveau propriétaire de ces actifs ne répétera pas les mêmes erreurs.</p>
<p class="pt">Esse padrão não é novo. Quando FTX, Celsius, Voyager e Genesis colapsaram em sucessão em 2022-2023, sobreviventes como Binance.US, Kraken e Galaxy Digital arrebataram ativos falidos e carteiras de clientes a preços de liquidação, remodelando a estrutura do mercado. O que é ligeiramente diferente aqui é o formato do negócio: a onda de 2022 foi majoritariamente "mega-exchanges sobreviventes absorvendo mega-exchanges caídas", enquanto Keyrock-BlockFills é uma formadora de mercado relativamente jovem adquirindo ativos de corretagem institucional para mirar uma capacidade específica — expertise em derivativos. Isso aponta para uma institucionalização cripto avançando de modo que, mesmo quando uma empresa fracassa, seus ativos não desaparecem do mercado; eles são absorvidos quase imediatamente por outro operador, mantendo intacta a continuidade do serviço. Vale notar, porém, que essa consolidação não significa automaticamente uma gestão de risco melhor daqui em diante — não há garantia de que o novo dono desses ativos não repita os mesmos erros.</p>
<p class="tr">Bu kalıp yeni değil. 2022-2023'te FTX, Celsius, Voyager ve Genesis art arda çöktüğünde, Binance.US, Kraken ve Galaxy Digital gibi hayatta kalanlar iflas etmiş varlıkları ve müşteri defterlerini zorunlu satış fiyatlarından kapıp piyasa yapısını yeniden şekillendirdi. Burada biraz farklı olan, anlaşmanın şekli: 2022 dalgası büyük ölçüde "hayatta kalan dev borsaların çökmüş dev borsaları yutması" şeklindeydi; Keyrock-BlockFills ise nispeten genç bir piyasa yapıcının belirli bir yeteneği — türev ürün uzmanlığını — hedefleyerek kurumsal brokerlik varlıklarını satın alması. Bu, kripto kurumsallaşmasının, bir şirket başarısız olsa bile varlıklarının piyasadan kaybolmadığı, neredeyse anında başka bir operatör tarafından devralınarak hizmet sürekliliğinin korunduğu bir yapıya doğru ilerlediğine işaret ediyor. Ancak bu konsolidasyonun otomatik olarak daha iyi risk yönetimi anlamına gelmediğini not etmekte fayda var — bu varlıkların yeni sahibinin aynı hataları tekrarlamayacağının garantisi yok.</p>
<p class="vi">Mô hình này không mới. Khi FTX, Celsius, Voyager và Genesis lần lượt sụp đổ trong giai đoạn 2022-2023, những công ty sống sót như Binance.US, Kraken và Galaxy Digital đã vơ vét các tài sản phá sản và danh sách khách hàng với giá bán tháo, định hình lại cấu trúc thị trường. Điều hơi khác ở đây là hình thức thương vụ: làn sóng năm 2022 phần lớn là "các sàn giao dịch khổng lồ còn sống hấp thụ các sàn giao dịch khổng lồ đã sụp đổ", trong khi Keyrock-BlockFills là một nhà tạo lập thị trường tương đối trẻ mua lại tài sản môi giới tổ chức nhắm vào một năng lực cụ thể — chuyên môn phái sinh. Điều đó cho thấy quá trình thể chế hóa tiền mã hóa đang diễn ra theo hướng ngay cả khi một công ty thất bại, tài sản của nó cũng không biến mất khỏi thị trường; chúng gần như ngay lập tức được một nhà vận hành khác hấp thụ, giữ cho tính liên tục của dịch vụ không bị gián đoạn. Tuy nhiên, cần lưu ý rằng sự hợp nhất này không tự động đồng nghĩa với việc quản lý rủi ro tốt hơn về sau — không có gì đảm bảo chủ sở hữu mới của các tài sản này sẽ không lặp lại chính những sai lầm đó.</p>

<div class="ko en ja es de fr pt tr vi">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">BlockFills — From Peak to Bankruptcy Sale</text>
  <g font-family="sans-serif">
    <text x="20" y="80" fill="#a1a1aa" font-size="13" font-weight="700">Cumulative volume processed</text>
    <rect x="20" y="90" width="640" height="34" fill="#06b6d4"/>
    <text x="640" y="114" fill="#f4f4f5" font-size="15" font-weight="700" text-anchor="end">$61B</text>

    <text x="20" y="165" fill="#a1a1aa" font-size="13" font-weight="700">Reported assets (bankruptcy filing)</text>
    <rect x="20" y="175" width="64" height="34" fill="#71717a"/>
    <text x="94" y="199" fill="#d4d4d8" font-size="14" font-weight="700">$50–100M</text>

    <text x="20" y="245" fill="#a1a1aa" font-size="13" font-weight="700">Reported liabilities (bankruptcy filing)</text>
    <rect x="20" y="255" width="320" height="34" fill="#ef4444"/>
    <text x="330" y="279" fill="#f4f4f5" font-size="14" font-weight="700">up to $500M</text>

    <text x="20" y="325" fill="#a1a1aa" font-size="13" font-weight="700">Keyrock acquisition price</text>
    <rect x="20" y="335" width="6" height="34" fill="#22c55e"/>
    <text x="34" y="359" fill="#22c55e" font-size="14" font-weight="700">$3.25M</text>
  </g>
  <text x="20" y="392" fill="#52525b" font-size="11" font-family="sans-serif">Source: Delaware bankruptcy court filings; CoinDesk, July 2026.</text>
</svg>
</div>

<div class="box ko">💡 <strong>지금 지켜봐야 할 것:</strong> (1) 키록이 확보한 2,000곳 기관 고객이 실제로 얼마나 유지되며 거래를 재개하는지, (2) 블록필스 채권자들이 파산 절차에서 얼마나 회수하는지, (3) 파산법원이 소송 중인 고객 자금 유용 의혹을 어떻게 처리하는지, (4) 다른 마켓메이커·브로커리지들도 비슷한 방식으로 파산 자산 쇼핑에 나서는지다.</div>
<div class="box en">💡 <strong>What to watch now:</strong> (1) how many of the 2,000 institutional clients Keyrock acquired actually stay and resume trading; (2) how much BlockFills' creditors ultimately recover through the bankruptcy process; (3) how the court resolves the pending customer-fund misappropriation lawsuits; (4) whether other market makers and brokerages follow with similar distressed-asset shopping.</div>
<div class="box ja">💡 <strong>今後注視すべきこと:</strong> (1)キーロックが獲得した2,000の機関顧客のうち実際にどれだけが継続し取引を再開するか、(2)ブロックフィルズの債権者が破産手続きで最終的にどれだけ回収できるか、(3)裁判所が係争中の顧客資金流用疑惑をどう処理するか、(4)他のマーケットメイカーやブローカレッジも同様に破産資産の買い漁りに乗り出すか。</div>
<div class="box es">💡 <strong>Qué vigilar ahora:</strong> (1) cuántos de los 2.000 clientes institucionales adquiridos por Keyrock realmente permanecen y reanudan el trading; (2) cuánto recuperan finalmente los acreedores de BlockFills a través del proceso de quiebra; (3) cómo resuelve el tribunal las demandas pendientes por malversación de fondos de clientes; (4) si otros creadores de mercado y correduras siguen con compras similares de activos en dificultades.</div>
<div class="box de">💡 <strong>Worauf jetzt zu achten ist:</strong> (1) wie viele der 2.000 von Keyrock übernommenen institutionellen Kunden tatsächlich bleiben und den Handel wiederaufnehmen; (2) wie viel BlockFills' Gläubiger letztlich im Insolvenzverfahren zurückerhalten; (3) wie das Gericht die anhängigen Klagen wegen Veruntreuung von Kundengeldern löst; (4) ob weitere Market Maker und Broker mit ähnlichen Käufen notleidender Vermögenswerte folgen.</div>
<div class="box fr">💡 <strong>Ce qu'il faut surveiller maintenant :</strong> (1) combien des 2 000 clients institutionnels acquis par Keyrock restent réellement et reprennent le trading ; (2) combien les créanciers de BlockFills récupèrent finalement via la procédure de faillite ; (3) comment le tribunal résout les poursuites en cours pour détournement de fonds clients ; (4) si d'autres teneurs de marché et courtiers suivent avec des achats similaires d'actifs en difficulté.</div>
<div class="box pt">💡 <strong>O que observar agora:</strong> (1) quantos dos 2.000 clientes institucionais adquiridos pela Keyrock realmente permanecem e retomam a negociação; (2) quanto os credores da BlockFills acabam recuperando no processo de falência; (3) como o tribunal resolve os processos pendentes de desvio de fundos de clientes; (4) se outros formadores de mercado e corretoras seguem com compras semelhantes de ativos em dificuldades.</div>
<div class="box tr">💡 <strong>Şimdi izlenmesi gerekenler:</strong> (1) Keyrock'un edindiği 2.000 kurumsal müşteriden kaçının gerçekten kalıp trading'e devam ettiği; (2) BlockFills alacaklılarının iflas sürecinde nihayetinde ne kadar tahsilat yapabildiği; (3) mahkemenin devam eden müşteri fonu kötüye kullanımı davalarını nasıl sonuçlandırdığı; (4) diğer piyasa yapıcıların ve brokerların benzer sıkıntılı varlık alımlarına girişip girişmediği.</div>
<div class="box vi">💡 <strong>Những điều cần theo dõi ngay bây giờ:</strong> (1) bao nhiêu trong số 2.000 khách hàng tổ chức mà Keyrock có được thực sự ở lại và tiếp tục giao dịch; (2) chủ nợ của BlockFills cuối cùng thu hồi được bao nhiêu qua thủ tục phá sản; (3) tòa án giải quyết các vụ kiện chiếm dụng tiền khách hàng đang chờ xử lý ra sao; (4) liệu các nhà tạo lập thị trường và môi giới khác có tiếp bước mua tài sản gặp khó khăn tương tự hay không.</div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 코인데스크(CoinDesk), 블룸버그(Bloomberg), 포브스(Forbes/BitcoinWorld), 포크로그(ForkLog), 디스럽션뱅킹(Disruption Banking), 블록필스 공식 발표.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinDesk, Bloomberg, BitcoinWorld, ForkLog, Disruption Banking, BlockFills official statement.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: コインデスク(CoinDesk)、ブルームバーグ(Bloomberg)、ビットコインワールド(BitcoinWorld)、フォークログ(ForkLog)、ディスラプションバンキング(Disruption Banking)、ブロックフィルズ公式発表。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinDesk, Bloomberg, BitcoinWorld, ForkLog, Disruption Banking, comunicado oficial de BlockFills.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinDesk, Bloomberg, BitcoinWorld, ForkLog, Disruption Banking, offizielle Mitteilung von BlockFills.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinDesk, Bloomberg, BitcoinWorld, ForkLog, Disruption Banking, communiqué officiel de BlockFills.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinDesk, Bloomberg, BitcoinWorld, ForkLog, Disruption Banking, comunicado oficial da BlockFills.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinDesk, Bloomberg, BitcoinWorld, ForkLog, Disruption Banking, BlockFills resmi açıklaması.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinDesk, Bloomberg, BitcoinWorld, ForkLog, Disruption Banking, thông báo chính thức của BlockFills.</p>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
    <text x="60" y="270" fill="#f4f4f5" font-size="130" font-weight="bold">$3.25M</text>
    <text x="60" y="335" fill="#06b6d4" font-size="40" font-weight="bold">KEYROCK ACQUISITION</text>
    <text x="60" y="405" fill="#a1a1aa" font-size="34" font-weight="bold">BLOCKFILLS CH.11</text>
    <text x="60" y="470" fill="#71717a" font-size="30" font-weight="bold">61B</text>
    <polygon fill="#71717a" points="200,455 240,470 200,485"/>
    <text x="270" y="470" fill="#71717a" font-size="30" font-weight="bold">3.25M</text>
  </svg></div>

<?php require __DIR__.'/_footer.php'; ?>
