<?php $slug = 'miner-selling-record-price-rebound-gap'; require __DIR__.'/_header.php'; ?>

<p class="ko">비트코인은 6월 30일 5만 7,950달러 저점에서 반등해 지금은 6만 3,000달러대 초반에서 거래되고 있다. 저점 대비로는 약 9% 오른 셈이다. 그런데 같은 기간 채굴 업계의 숫자는 정반대 이야기를 하고 있다. 테마이너매그(TheMinerMag) 집계에 따르면 마라·클린스파크·라이엇·캉고·코어사이언티픽·비트디어 등 상장 채굴사들은 2026년 1분기에만 3만 2,000 BTC 이상을 팔아 2025년 한 해 전체 매도량을 통째로 넘어섰다. 가격은 반등 신호를 냈는데, 채굴 업계는 사상 최대 규모로 코인을 시장에 내놓고 있는 셈이다. 이 글은 두 흐름이 왜 같은 방향을 보지 않는지, 그리고 지금 국면에서 어느 쪽이 먼저 방향을 바꿀지를 짚는다.</p>
<p class="en">Bitcoin bounced off its June 30 low of $57,950 and is now trading in the low $63,000s — up roughly 9% from the bottom. Over the same stretch, though, the mining industry's numbers are telling the opposite story. Per TheMinerMag's tally, publicly traded miners including MARA, CleanSpark, Riot, Cango, Core Scientific, and Bitdeer sold more than 32,000 BTC in Q1 2026 alone, already exceeding their combined sales for all of 2025. Price sent a recovery signal; the mining industry is putting coins on the market at a record pace. This piece looks at why the two aren't pointing the same way, and which one is more likely to turn first from here.</p>
<p class="ja">ビットコインは6月30日の安値5万7,950ドルから反発し、現在は6万3千ドル台前半で取引されている。安値からは約9%の上昇だ。だが同じ期間、採掘業界の数字はまったく逆の話をしている。TheMinerMagの集計によると、マラ・クリーンスパーク・ライオット・カンゴ・コアサイエンティフィック・ビットディアなど上場採掘企業は2026年第1四半期だけで3万2,000BTC以上を売却し、2025年通年の売却量をまるごと超えた。価格は反発の兆しを見せたが、採掘業界は過去最大規模でコインを市場に出している格好だ。本稿は、この二つの流れがなぜ同じ方向を向いていないのか、そして今の局面でどちらが先に方向を変えるのかを掘り下げる。</p>
<p class="es">Bitcoin rebotó desde su mínimo del 30 de junio de $57,950 y ahora cotiza en la zona baja de los $63,000 — un alza de casi 9% desde el suelo. Sin embargo, en ese mismo tramo, los números de la industria minera cuentan la historia contraria. Según el recuento de TheMinerMag, mineros que cotizan en bolsa como MARA, CleanSpark, Riot, Cango, Core Scientific y Bitdeer vendieron más de 32,000 BTC solo en el primer trimestre de 2026, superando ya sus ventas combinadas de todo 2025. El precio envió una señal de recuperación; la industria minera está poniendo monedas en el mercado a un ritmo récord. Este artículo analiza por qué ambas corrientes no apuntan en la misma dirección, y cuál de las dos tiene más probabilidades de girar primero desde aquí.</p>
<p class="de">Bitcoin erholte sich von seinem Tief vom 30. Juni bei 57.950 $ und notiert nun in der unteren 63.000-Dollar-Zone — ein Anstieg von rund 9% vom Tiefpunkt. Im selben Zeitraum erzählen die Zahlen der Mining-Branche jedoch die gegenteilige Geschichte. Laut der Auswertung von TheMinerMag verkauften börsennotierte Miner wie MARA, CleanSpark, Riot, Cango, Core Scientific und Bitdeer allein im ersten Quartal 2026 mehr als 32.000 BTC — schon mehr als ihre gesamten Verkäufe im Jahr 2025 zusammen. Der Preis sandte ein Erholungssignal; die Mining-Branche bringt Coins in Rekordtempo auf den Markt. Dieser Beitrag untersucht, warum die beiden Trends nicht in dieselbe Richtung zeigen und welcher von beiden von hier aus eher zuerst dreht.</p>
<p class="fr">Le bitcoin a rebondi depuis son plus bas du 30 juin à 57 950 $ et se négocie désormais dans la zone basse des 63 000 $ — soit une hausse d'environ 9% depuis le creux. Sur la même période, pourtant, les chiffres de l'industrie minière racontent l'histoire inverse. Selon le décompte de TheMinerMag, des mineurs cotés en bourse comme MARA, CleanSpark, Riot, Cango, Core Scientific et Bitdeer ont vendu plus de 32 000 BTC au seul premier trimestre 2026, dépassant déjà leurs ventes cumulées de toute l'année 2025. Le prix a envoyé un signal de reprise ; l'industrie minière met des coins sur le marché à un rythme record. Cet article examine pourquoi ces deux tendances ne pointent pas dans la même direction, et laquelle des deux est la plus susceptible de s'inverser en premier à partir d'ici.</p>
<p class="pt">O bitcoin recuou do seu mínimo de 30 de junho, em 57.950 $, e agora é negociado na faixa baixa dos 63.000 $ — uma alta de cerca de 9% desde o fundo. No mesmo período, porém, os números da indústria de mineração contam a história oposta. Segundo o levantamento da TheMinerMag, mineradoras de capital aberto como MARA, CleanSpark, Riot, Cango, Core Scientific e Bitdeer venderam mais de 32.000 BTC somente no primeiro trimestre de 2026, já superando suas vendas combinadas de todo o ano de 2025. O preço enviou um sinal de recuperação; a indústria de mineração está colocando moedas no mercado em ritmo recorde. Este texto analisa por que as duas tendências não apontam na mesma direção, e qual delas tem mais chances de reverter primeiro a partir daqui.</p>
<p class="tr">Bitcoin, 30 Haziran'daki 57.950 dolarlık dibinden toparlanarak şu anda 63.000 doların altında işlem görüyor — dipten bu yana yaklaşık %9 yükseldi. Ancak aynı dönemde madencilik sektörünün rakamları tam tersini anlatıyor. TheMinerMag'in derlemesine göre MARA, CleanSpark, Riot, Cango, Core Scientific ve Bitdeer gibi halka açık madenciler yalnızca 2026'nın ilk çeyreğinde 32.000 BTC'nin üzerinde satış yaptı; bu rakam 2025'in tamamındaki toplam satışları çoktan geçti. Fiyat bir toparlanma sinyali verdi; madencilik sektörü ise coinleri rekor hızda piyasaya sürüyor. Bu yazı, bu iki eğilimin neden aynı yönü göstermediğini ve buradan itibaren hangisinin önce yön değiştirmesinin daha muhtemel olduğunu inceliyor.</p>
<p class="vi">Bitcoin đã bật lên từ đáy 57.950 đô la ngày 30 tháng 6 và hiện đang giao dịch quanh mức thấp của vùng 63.000 đô la — tăng khoảng 9% so với đáy. Tuy nhiên, trong cùng giai đoạn đó, các con số của ngành khai thác lại kể một câu chuyện ngược lại. Theo thống kê của TheMinerMag, các công ty khai thác niêm yết công khai như MARA, CleanSpark, Riot, Cango, Core Scientific và Bitdeer đã bán hơn 32.000 BTC chỉ riêng trong quý 1 năm 2026, đã vượt qua tổng doanh số bán ra của cả năm 2025 cộng lại. Giá phát đi tín hiệu phục hồi; trong khi đó ngành khai thác lại đang tung coin ra thị trường với tốc độ kỷ lục. Bài viết này xem xét vì sao hai xu hướng này không cùng hướng, và bên nào có khả năng đổi chiều trước từ đây.</p>

<div class="cc">
  <h3><span class="ko">📊 오늘의 지표 스냅샷</span><span class="en">📊 Today's Indicator Snapshot</span><span class="ja">📊 本日の指標スナップショット</span><span class="es">📊 Instantánea de Indicadores de Hoy</span><span class="de">📊 Heutige Indikatoren-Momentaufnahme</span><span class="fr">📊 Instantané des Indicateurs du Jour</span><span class="pt">📊 Instantâneo dos Indicadores de Hoje</span><span class="tr">📊 Bugünün Gösterge Görünümü</span><span class="vi">📊 Ảnh Chụp Nhanh Chỉ Số Hôm Nay</span></h3>
  <div class="stats">
    <div class="si"><div class="sl"><span class="ko">BTC 가격</span><span class="en">BTC Price</span><span class="ja">BTC価格</span><span class="es">Precio BTC</span><span class="de">BTC-Preis</span><span class="fr">Prix du BTC</span><span class="pt">Preço do BTC</span><span class="tr">BTC Fiyatı</span><span class="vi">Giá BTC</span></div><div class="sv">$63,050</div><div class="ss"><span class="ko">6/30 저점 대비 +8.8%</span><span class="en">+8.8% off Jun 30 low</span><span class="ja">6/30安値比+8.8%</span><span class="es">+8.8% desde el mínimo del 30 jun</span><span class="de">+8,8% seit Tief vom 30. Juni</span><span class="fr">+8,8% depuis le creux du 30 juin</span><span class="pt">+8,8% acima do mínimo de 30/jun</span><span class="tr">30 Haziran dibinden +%8,8</span><span class="vi">+8,8% so với đáy 30/6</span></div></div>
    <div class="si"><div class="sl"><span class="ko">해시프라이스</span><span class="en">Hashprice</span><span class="ja">ハッシュプライス</span><span class="es">Hashprice</span><span class="de">Hashprice</span><span class="fr">Hashprice</span><span class="pt">Hashprice</span><span class="tr">Hashprice</span><span class="vi">Hashprice</span></div><div class="sv">~$33.7/PH/s</div><div class="ss"><span class="ko">손익분기선(~$35) 아래</span><span class="en">Below ~$35 breakeven</span><span class="ja">損益分岐点(~$35)以下</span><span class="es">Bajo el equilibrio (~$35)</span><span class="de">Unter Gewinnschwelle (~35$)</span><span class="fr">Sous le seuil de rentabilité (~35 $)</span><span class="pt">Abaixo do ponto de equilíbrio (~US$ 35)</span><span class="tr">~35$ başabaş noktasının altında</span><span class="vi">Dưới điểm hòa vốn (~35 đô la)</span></div></div>
    <div class="si"><div class="sl"><span class="ko">1분기 채굴사 매도</span><span class="en">Q1 Miner Sales</span><span class="ja">第1四半期採掘者売却</span><span class="es">Ventas Mineras T1</span><span class="de">Miner-Verkäufe Q1</span><span class="fr">Ventes des Mineurs au T1</span><span class="pt">Vendas de Mineradoras no T1</span><span class="tr">1Ç Madenci Satışları</span><span class="vi">Doanh Số Bán Của Thợ Đào Q1</span></div><div class="sv">32,000+ BTC</div><div class="ss"><span class="ko">2025년 연간치 초과</span><span class="en">Already tops all of 2025</span><span class="ja">2025年通年を超過</span><span class="es">Ya supera todo 2025</span><span class="de">Übertrifft bereits 2025 gesamt</span><span class="fr">Dépasse déjà toute l'année 2025</span><span class="pt">Já supera todo o ano de 2025</span><span class="tr">2025'in tamamını şimdiden geçti</span><span class="vi">Đã vượt cả năm 2025</span></div></div>
    <div class="si"><div class="sl"><span class="ko">채굴자 보유잔고</span><span class="en">Miner Reserve</span><span class="ja">採掘者保有残高</span><span class="es">Reserva de Mineros</span><span class="de">Miner-Reserve</span><span class="fr">Réserve des Mineurs</span><span class="pt">Reserva das Mineradoras</span><span class="tr">Madenci Rezervi</span><span class="vi">Dự Trữ Của Thợ Đào</span></div><div class="sv">~1.8M BTC</div><div class="ss"><span class="ko">'23년 말 1.86M에서 감소</span><span class="en">Down from 1.86M end-2023</span><span class="ja">'23年末186万から減少</span><span class="es">Baja desde 1.86M fin-2023</span><span class="de">Von 1,86 Mio. Ende 2023</span><span class="fr">En baisse depuis 1,86 M fin 2023</span><span class="pt">Em queda ante 1,86 M no fim de 2023</span><span class="tr">2023 sonundaki 1,86M'den düştü</span><span class="vi">Giảm từ 1,86 triệu cuối 2023</span></div></div>
  </div>
</div>

<h2 class="ko">채굴자는 2025년 전체보다 더 많이, 단 3개월 만에 팔았다</h2>
<h2 class="en">Miners Sold More in Three Months Than in All of 2025</h2>
<h2 class="ja">採掘者は2025年通年より多くを、わずか3カ月で売った</h2>
<h2 class="es">Los Mineros Vendieron Más en Tres Meses Que en Todo 2025</h2>
<h2 class="de">Miner Verkauften in Drei Monaten Mehr als im Gesamten Jahr 2025</h2>
<h2 class="fr">Les Mineurs Ont Vendu Plus en Trois Mois Qu'en Toute l'Année 2025</h2>
<h2 class="pt">Mineradoras Venderam Mais em Três Meses Do Que em Todo o Ano de 2025</h2>
<h2 class="tr">Madenciler Üç Ayda 2025'in Tamamından Daha Fazlasını Sattı</h2>
<h2 class="vi">Thợ Đào Bán Nhiều Hơn Trong Ba Tháng So Với Cả Năm 2025</h2>

<p class="ko">코인셰어즈와 테마이너매그 집계를 종합하면, <a href="/blog/public-miners-record-btc-sale-q1-2026.html">상장 채굴사들의 2026년 1분기 매도량(3만 2,000 BTC 이상)</a>은 2025년 연간 매도량을 넘어선 단일 분기 최대 기록이다. 개별적으로 보면 성격이 뚜렷하다. 비트디어는 2월에 보유 물량을 사실상 0으로 줄였고, 코어사이언티픽은 1월 한 달에만 약 1,900 BTC(약 1억 7,500만 달러)를 팔면서 남은 보유분 대부분을 청산할 계획이라고 밝혔다. 이는 가격 상승을 노린 차익 실현이 아니라, 운영비를 대기 위한 강제 매도에 가깝다. 채굴 업계 전반이 부채 상환과 전력비 지출을 감당하기 위해 보유 코인을 헐어 쓰는 국면에 들어섰다는 뜻이다.</p>
<p class="en">Combining CoinShares' and TheMinerMag's tallies, <a href="/blog/public-miners-record-btc-sale-q1-2026.html">public miners' Q1 2026 sales of over 32,000 BTC</a> already form a single-quarter record that exceeds all of 2025's sales. Look at individual miners and the character of the selling becomes clear. Bitdeer cut its treasury to effectively zero in February, and Core Scientific sold roughly 1,900 BTC (about $175 million) in January alone while saying it planned to liquidate substantially all of its remaining holdings. This isn't profit-taking timed to a price rally — it looks far more like forced selling to cover operating costs. The mining industry broadly has entered a phase where it's drawing down its own coin holdings to service debt and pay power bills.</p>
<p class="ja">コインシェアーズとTheMinerMagの集計を合わせると、<a href="/blog/public-miners-record-btc-sale-q1-2026.html">上場採掘企業の2026年第1四半期の売却量(3万2,000BTC超)</a>は2025年通年の売却量を上回る単一四半期としての最大記録だ。個別に見るとその性格ははっきりしている。ビットディアは2月に保有量を実質ゼロまで減らし、コアサイエンティフィックは1月だけで約1,900BTC(約1億7,500万ドル)を売却し、残る保有分の大半を清算する計画だと明らかにした。これは価格上昇を狙った利益確定ではなく、運営費を賄うための強制売却に近い。採掘業界全体が、負債返済と電力費支出を賄うために保有コインを取り崩す局面に入ったことを意味する。</p>
<p class="es">Combinando los recuentos de CoinShares y TheMinerMag, <a href="/blog/public-miners-record-btc-sale-q1-2026.html">las ventas de más de 32,000 BTC de mineros públicos en el T1 de 2026</a> ya constituyen un récord trimestral que supera todas las ventas de 2025. Al mirar mineros individuales, el carácter de las ventas queda claro. Bitdeer redujo su tesorería a prácticamente cero en febrero, y Core Scientific vendió cerca de 1,900 BTC (unos $175 millones) solo en enero, mientras afirmaba que planeaba liquidar sustancialmente todas sus tenencias restantes. Esto no es toma de ganancias cronometrada con un repunte del precio — se parece mucho más a una venta forzada para cubrir costos operativos. La industria minera en general ha entrado en una fase en la que reduce sus propias tenencias de monedas para pagar deuda y facturas de electricidad.</p>
<p class="de">Kombiniert man die Auswertungen von CoinShares und TheMinerMag, bilden <a href="/blog/public-miners-record-btc-sale-q1-2026.html">die Q1-2026-Verkäufe börsennotierter Miner von über 32.000 BTC</a> bereits einen Rekord für ein einzelnes Quartal, der die gesamten Verkäufe von 2025 übertrifft. Betrachtet man einzelne Miner, wird der Charakter der Verkäufe deutlich. Bitdeer reduzierte seine Treasury im Februar auf praktisch null, und Core Scientific verkaufte allein im Januar rund 1.900 BTC (etwa 175 Millionen $) und erklärte, im Wesentlichen alle verbleibenden Bestände liquidieren zu wollen. Das ist keine an einer Preisrally ausgerichtete Gewinnmitnahme — es sieht viel mehr nach Zwangsverkäufen zur Deckung der Betriebskosten aus. Die Mining-Branche insgesamt ist in eine Phase eingetreten, in der sie die eigenen Coin-Bestände abbaut, um Schulden zu bedienen und Stromrechnungen zu bezahlen.</p>
<p class="fr">En combinant les décomptes de CoinShares et de TheMinerMag, <a href="/blog/public-miners-record-btc-sale-q1-2026.html">les ventes de plus de 32 000 BTC des mineurs cotés au T1 2026</a> constituent déjà un record trimestriel qui dépasse l'ensemble des ventes de 2025. En examinant les mineurs individuellement, le caractère de ces ventes devient clair. Bitdeer a réduit sa trésorerie à pratiquement zéro en février, et Core Scientific a vendu environ 1 900 BTC (environ 175 millions de dollars) au seul mois de janvier tout en indiquant qu'elle prévoyait de liquider la quasi-totalité de ses avoirs restants. Il ne s'agit pas de prises de bénéfices calées sur un rallye de prix — cela ressemble bien davantage à des ventes forcées destinées à couvrir les coûts opérationnels. L'industrie minière dans son ensemble est entrée dans une phase où elle puise dans ses propres réserves de coins pour rembourser sa dette et payer ses factures d'électricité.</p>
<p class="pt">Combinando os levantamentos da CoinShares e da TheMinerMag, <a href="/blog/public-miners-record-btc-sale-q1-2026.html">as vendas de mais de 32.000 BTC das mineradoras públicas no T1 de 2026</a> já formam um recorde trimestral que supera todas as vendas de 2025. Olhando para as mineradoras individualmente, o caráter dessas vendas fica claro. A Bitdeer reduziu seu tesouro a praticamente zero em fevereiro, e a Core Scientific vendeu cerca de 1.900 BTC (cerca de US$ 175 milhões) somente em janeiro, ao mesmo tempo em que afirmou planejar liquidar substancialmente todas as suas participações remanescentes. Isso não é realização de lucro cronometrada com um rali de preço — parece muito mais uma venda forçada para cobrir custos operacionais. A indústria de mineração como um todo entrou em uma fase em que reduz suas próprias reservas de moedas para pagar dívidas e contas de energia.</p>
<p class="tr">CoinShares ve TheMinerMag'in verilerini birleştirdiğimizde, <a href="/blog/public-miners-record-btc-sale-q1-2026.html">halka açık madencilerin 2026'nın ilk çeyreğinde yaptığı 32.000 BTC'yi aşan satışlar</a>, 2025'in tamamındaki satışları geride bırakan tek çeyreklik bir rekor oluşturuyor. Madencileri tek tek incelediğinizde satışın niteliği netleşiyor. Bitdeer, Şubat ayında hazinesini fiilen sıfıra indirdi ve Core Scientific yalnızca Ocak ayında yaklaşık 1.900 BTC (yaklaşık 175 milyon dolar) sattı; şirket kalan varlıklarının neredeyse tamamını tasfiye etmeyi planladığını açıkladı. Bu, bir fiyat rallisine zamanlanmış kâr realizasyonu değil — çok daha çok işletme maliyetlerini karşılamak için yapılan zorunlu satışa benziyor. Madencilik sektörünün genelinde, borç ödemek ve elektrik faturalarını karşılamak için kendi coin rezervlerini eritme aşamasına girildi.</p>
<p class="vi">Kết hợp số liệu của CoinShares và TheMinerMag, <a href="/blog/public-miners-record-btc-sale-q1-2026.html">doanh số bán ra hơn 32.000 BTC của các thợ đào niêm yết công khai trong quý 1 năm 2026</a> đã tạo thành kỷ lục theo quý, vượt qua toàn bộ doanh số bán của năm 2025. Nhìn vào từng thợ đào riêng lẻ, bản chất của đợt bán tháo này trở nên rõ ràng. Bitdeer đã cắt giảm kho dự trữ xuống gần như bằng không vào tháng 2, còn Core Scientific đã bán khoảng 1.900 BTC (khoảng 175 triệu đô la) chỉ riêng trong tháng 1, đồng thời cho biết có kế hoạch thanh lý gần như toàn bộ số lượng nắm giữ còn lại. Đây không phải là hành động chốt lời theo đà tăng giá — mà giống với việc bán bắt buộc để trang trải chi phí vận hành hơn nhiều. Ngành khai thác nói chung đã bước vào giai đoạn phải rút bớt lượng coin nắm giữ của chính mình để trả nợ và thanh toán tiền điện.</p>

<p class="ko">이 매도 압력은 크립토퀀트가 집계하는 채굴자 보유잔고(Miner Reserve)에도 그대로 반영된다. 2023년 말 약 186만 BTC였던 채굴자 보유잔고는 올해 들어 약 180만 BTC까지 줄었고, 이 감소분의 상당수가 최근 몇 달 사이에 집중됐다. 이런 흐름의 핵심은 방향성이 아니라 강제성이다. ETF 자금이나 고래 지갑의 매수·매도는 투자 판단에 따라 언제든 방향을 바꿀 수 있지만, 채굴자의 매도는 해시프라이스가 손익분기선을 회복하기 전까지는 가격이 오르든 내리든 계속될 가능성이 높은 구조적 흐름이다.</p>
<p class="en">This selling pressure shows up directly in CryptoQuant's Miner Reserve figure too. Total miner-held bitcoin, roughly 1.86 million BTC at the end of 2023, has fallen to around 1.8 million BTC this year, with much of that decline concentrated in recent months. What matters here isn't direction so much as compulsion. ETF flows and whale wallets can reverse course whenever conviction changes, but miner selling is likely to keep running regardless of which way price moves, for as long as hashprice stays under breakeven.</p>
<p class="ja">この売却圧力は、クリプトクアントが集計する採掘者保有残高(Miner Reserve)にもそのまま表れている。2023年末に約186万BTCだった採掘者保有残高は今年に入り約180万BTCまで減少し、この減少分の相当部分が直近数カ月に集中している。この流れの核心は方向性ではなく強制性にある。ETF資金やクジラウォレットの売買は投資判断次第でいつでも方向を変えられるが、採掘者の売却はハッシュプライスが損益分岐点を回復するまで、価格が上がろうと下がろうと続く可能性が高い構造的な流れだ。</p>
<p class="es">Esta presión de venta también se refleja directamente en la cifra de Reserva de Mineros de CryptoQuant. El total de bitcoin en poder de mineros, cerca de 1.86 millones de BTC a fines de 2023, ha caído a unos 1.8 millones de BTC este año, con buena parte de ese descenso concentrado en los últimos meses. Lo que importa aquí no es tanto la dirección como la compulsión. Los flujos de ETF y las billeteras ballena pueden revertir el rumbo cuando cambia la convicción, pero es probable que la venta de mineros siga corriendo sin importar hacia dónde se mueva el precio, mientras el hashprice permanezca bajo el punto de equilibrio.</p>
<p class="de">Dieser Verkaufsdruck zeigt sich auch direkt in der von CryptoQuant erfassten Miner-Reserve. Der gesamte von Minern gehaltene Bitcoin-Bestand, Ende 2023 noch rund 1,86 Millionen BTC, ist dieses Jahr auf etwa 1,8 Millionen BTC gefallen, wobei sich ein Großteil dieses Rückgangs auf die jüngsten Monate konzentriert. Entscheidend ist hier weniger die Richtung als der Zwang. ETF-Flüsse und Whale-Wallets können die Richtung wechseln, sobald sich die Überzeugung ändert, doch Miner-Verkäufe dürften unabhängig von der Preisrichtung weiterlaufen, solange der Hashprice unter der Gewinnschwelle bleibt.</p>
<p class="fr">Cette pression vendeuse se reflète aussi directement dans la Réserve des Mineurs relevée par CryptoQuant. Le total de bitcoin détenu par les mineurs, environ 1,86 million de BTC fin 2023, est tombé à environ 1,8 million de BTC cette année, une bonne partie de ce déclin étant concentrée ces derniers mois. Ce qui compte ici, ce n'est pas tant la direction que la contrainte. Les flux des ETF et les portefeuilles de baleines peuvent s'inverser dès que la conviction change, mais les ventes des mineurs devraient probablement se poursuivre quel que soit le sens dans lequel le prix évolue, tant que le hashprice restera sous le seuil de rentabilité.</p>
<p class="pt">Essa pressão de venda também aparece diretamente na Reserva de Mineradoras apurada pela CryptoQuant. O total de bitcoin em poder das mineradoras, cerca de 1,86 milhão de BTC no fim de 2023, caiu para cerca de 1,8 milhão de BTC neste ano, com boa parte dessa queda concentrada nos últimos meses. O que importa aqui não é tanto a direção, mas a compulsão. Os fluxos de ETFs e as carteiras de baleias podem reverter de rumo quando a convicção muda, mas é provável que a venda das mineradoras continue independentemente de para onde o preço se mova, enquanto o hashprice permanecer abaixo do ponto de equilíbrio.</p>
<p class="tr">Bu satış baskısı, CryptoQuant'ın izlediği Madenci Rezervi rakamında da doğrudan görülüyor. 2023 sonunda yaklaşık 1,86 milyon BTC olan toplam madenci bitcoin varlığı, bu yıl yaklaşık 1,8 milyon BTC'ye geriledi; bu düşüşün büyük bölümü son aylarda yoğunlaştı. Burada önemli olan yön değil, zorunluluktur. ETF akışları ve balina cüzdanları, kanaat değiştiğinde yön değiştirebilir; ancak hashprice başabaş noktasının altında kaldığı sürece madenci satışlarının fiyatın yönünden bağımsız olarak sürmesi muhtemeldir.</p>
<p class="vi">Áp lực bán này cũng thể hiện trực tiếp trong chỉ số Dự Trữ Của Thợ Đào mà CryptoQuant theo dõi. Tổng lượng bitcoin do thợ đào nắm giữ, khoảng 1,86 triệu BTC vào cuối năm 2023, đã giảm xuống còn khoảng 1,8 triệu BTC trong năm nay, với phần lớn mức giảm tập trung trong vài tháng gần đây. Điều quan trọng ở đây không phải là chiều hướng mà là tính bắt buộc. Dòng tiền ETF và ví cá voi có thể đảo chiều bất cứ khi nào niềm tin thay đổi, nhưng việc bán ra của thợ đào nhiều khả năng sẽ tiếp tục bất kể giá di chuyển theo hướng nào, chừng nào hashprice còn ở dưới điểm hòa vốn.</p>

<h2 class="ko">해시프라이스는 반등했지만, 손익분기선까지는 아직이다</h2>
<h2 class="en">Hashprice Has Bounced — But Not Up to Breakeven</h2>
<h2 class="ja">ハッシュプライスは反発したが、損益分岐点にはまだ届かない</h2>
<h2 class="es">El Hashprice Rebotó — Pero Todavía No Llega al Equilibrio</h2>
<h2 class="de">Der Hashprice Hat Sich Erholt — Aber Noch Nicht Bis zur Gewinnschwelle</h2>
<h2 class="fr">Le Hashprice a Rebondi — Mais Pas Jusqu'au Seuil de Rentabilité</h2>
<h2 class="pt">O Hashprice Se Recuperou — Mas Não Até o Ponto de Equilíbrio</h2>
<h2 class="tr">Hashprice Toparlandı — Ama Başabaş Noktasına Ulaşamadı</h2>
<h2 class="vi">Hashprice Đã Bật Tăng — Nhưng Chưa Đạt Điểm Hòa Vốn</h2>

<p class="ko">채굴자 한 단위 연산력이 하루에 벌어들이는 돈을 뜻하는 해시프라이스는 지표 제공처마다 다소 다르게 집계된다. 해시레이트인덱스 기준으로는 PH/s당 하루 약 33.68달러, <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">야후파이낸스가 인용한 다른 집계</a> 기준으로는 37.5달러 안팎이다. 두 수치 모두 코인셰어즈가 추정하는 구형 채굴장비 손익분기선(PH/s당 하루 약 35달러) 근방이거나 그 아래에 있다. 코인셰어즈는 1분기 평균 해시프라이스를 약 33달러로 집계하면서, 이 수준에서 채굴 업계의 15~20%가 여전히 적자 구간에 머물러 있다고 추산했다. 3월 초에는 한때 28~30달러대까지 밀리며 2024년 반감기 이후 최저치를 기록하기도 했다.</p>
<p class="en">Hashprice — what a miner earns per unit of computing power per day — is tallied somewhat differently across data providers. Per Hashrate Index it's around $33.68 per PH/s per day; per <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">a separate tally cited by Yahoo Finance</a>, it's closer to $37.5. Both figures sit at or below the roughly $35 per PH/s per day breakeven line CoinShares estimates for older-generation mining hardware. CoinShares put the Q1 average hashprice at about $33 and estimated that at that level, 15–20% of the industry remained in the red. It briefly sank into the $28–30 range in early March, a post-2024-halving low.</p>
<p class="ja">採掘者が単位演算力あたり1日に稼ぐ金額を示すハッシュプライスは、データ提供元によって集計がやや異なる。ハッシュレートインデックス基準ではPH/sあたり1日約33.68ドル、<a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">ヤフーファイナンスが引用した別集計</a>基準では37.5ドル前後だ。いずれの数値も、コインシェアーズが推定する旧世代採掘機材の損益分岐点(PH/sあたり1日約35ドル)付近かそれ以下にある。コインシェアーズは第1四半期の平均ハッシュプライスを約33ドルと集計し、この水準では採掘業界の15~20%が依然として赤字圏にとどまっていると推定した。3月初旬には一時28~30ドル台まで下落し、2024年の半減期以降の最低値を記録した。</p>
<p class="es">El hashprice —lo que un minero gana por unidad de potencia de cómputo al día— se contabiliza de forma algo distinta según el proveedor de datos. Según Hashrate Index ronda los $33.68 por PH/s al día; según <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">otro recuento citado por Yahoo Finance</a>, es más cercano a $37.5. Ambas cifras están en o por debajo del punto de equilibrio de unos $35 por PH/s al día que CoinShares estima para el hardware minero de generación antigua. CoinShares situó el hashprice promedio del T1 en unos $33 y estimó que, a ese nivel, entre el 15% y el 20% de la industria seguía en números rojos. A principios de marzo llegó a hundirse en el rango de $28–30, un mínimo posterior al halving de 2024.</p>
<p class="de">Der Hashprice — was ein Miner pro Einheit Rechenleistung und Tag verdient — wird je nach Datenanbieter etwas unterschiedlich erfasst. Laut Hashrate Index liegt er bei rund 33,68 $ pro PH/s und Tag; laut <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">einer separaten, von Yahoo Finance zitierten Erhebung</a> eher bei 37,5 $. Beide Werte liegen auf oder unter der Gewinnschwelle von etwa 35 $ pro PH/s und Tag, die CoinShares für Mining-Hardware älterer Generation schätzt. CoinShares bezifferte den durchschnittlichen Hashprice im ersten Quartal auf etwa 33 $ und schätzte, dass auf diesem Niveau 15–20% der Branche weiterhin rote Zahlen schrieben. Anfang März sackte er zeitweise in die Spanne von 28–30 $ ab, ein Tief nach dem Halving von 2024.</p>
<p class="fr">Le hashprice — ce qu'un mineur gagne par unité de puissance de calcul et par jour — est calculé de façon légèrement différente selon les fournisseurs de données. Selon Hashrate Index, il s'élève à environ 33,68 $ par PH/s et par jour ; selon <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">un autre décompte cité par Yahoo Finance</a>, il est plus proche de 37,5 $. Les deux chiffres se situent au niveau ou en dessous du seuil de rentabilité d'environ 35 $ par PH/s et par jour que CoinShares estime pour le matériel minier de génération plus ancienne. CoinShares a établi le hashprice moyen du T1 à environ 33 $ et a estimé qu'à ce niveau, 15 à 20% du secteur restait dans le rouge. Il est brièvement tombé dans la fourchette de 28 à 30 $ début mars, un plus bas depuis le halving de 2024.</p>
<p class="pt">O hashprice — o que uma mineradora ganha por unidade de poder computacional por dia — é calculado de forma um pouco diferente entre os provedores de dados. Segundo a Hashrate Index, fica em torno de US$ 33,68 por PH/s por dia; segundo <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">outro levantamento citado pela Yahoo Finance</a>, fica mais próximo de US$ 37,5. Ambos os números estão no nível ou abaixo do ponto de equilíbrio de cerca de US$ 35 por PH/s por dia que a CoinShares estima para equipamentos de mineração de geração mais antiga. A CoinShares situou o hashprice médio do T1 em cerca de US$ 33 e estimou que, nesse nível, 15% a 20% do setor permanecia no vermelho. Ele chegou a cair brevemente para a faixa de US$ 28-30 no início de março, uma mínima pós-halving de 2024.</p>
<p class="tr">Hashprice — bir madencinin birim işlem gücü başına günlük kazandığı miktar — veri sağlayıcılarına göre biraz farklı şekilde hesaplanıyor. Hashrate Index'e göre PH/s başına günde yaklaşık 33,68 dolar; <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">Yahoo Finance'in aktardığı ayrı bir veriye</a> göre ise 37,5 dolara daha yakın. Her iki rakam da CoinShares'in eski nesil madencilik donanımı için tahmin ettiği PH/s başına günlük yaklaşık 35 dolarlık başabaş çizgisinde veya altında. CoinShares, 1Ç ortalama hashprice'ı yaklaşık 33 dolar olarak belirledi ve bu seviyede sektörün %15-20'sinin hâlâ zararda olduğunu tahmin etti. Mart başında kısa süreliğine 28-30 dolar aralığına geriledi; bu, 2024 yarılanması sonrası en düşük seviyeydi.</p>
<p class="vi">Hashprice — số tiền một thợ đào kiếm được trên mỗi đơn vị công suất tính toán mỗi ngày — được các nhà cung cấp dữ liệu tính toán có phần khác nhau. Theo Hashrate Index, con số này vào khoảng 33,68 đô la trên mỗi PH/s mỗi ngày; theo <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">một thống kê riêng được Yahoo Finance trích dẫn</a>, con số gần với 37,5 đô la hơn. Cả hai con số đều bằng hoặc thấp hơn ngưỡng hòa vốn khoảng 35 đô la trên mỗi PH/s mỗi ngày mà CoinShares ước tính cho các thiết bị khai thác thế hệ cũ. CoinShares đưa ra mức hashprice trung bình quý 1 là khoảng 33 đô la và ước tính rằng ở mức này, 15-20% ngành vẫn đang thua lỗ. Con số này từng giảm xuống mức 28-30 đô la vào đầu tháng 3, mức thấp nhất kể từ sau halving 2024.</p>

<p class="ko">해시프라이스가 최근 살짝 반등한 것도 가격 상승보다는 채굴 난이도 하락 덕이 크다. <a href="/blog/mining-difficulty-adjustment-analysis.html">본지가 앞서 짚었듯</a> 6월 채굴 난이도는 138.9T에서 124.9T로 10.09% 급락해 2026년 두 번째로 큰 하락 폭을 기록했고, 이 덕에 해시프라이스가 잠시 숨통을 텄다. 그런데 7월 5일 기준 난이도는 이미 133.87T까지 되돌아왔고, 네트워크 해시레이트는 사상 첫 1제타해시(ZH/s) 문턱을 향해 약 935EH/s까지 올라섰다. 난이도 하락으로 얻은 여유가 벌써 대부분 반납된 셈이다. 해시레이트인덱스의 초기 추정으로는 7월 11일 예정된 다음 난이도 조정도 약 -0.8%에 그쳐, 채굴 경제에 별다른 추가 여유를 주지 않을 전망이다.</p>
<p class="en">The recent uptick in hashprice owes more to a difficulty drop than to the price rally. <a href="/blog/mining-difficulty-adjustment-analysis.html">As this site has covered before</a>, June's mining difficulty fell 10.09%, from 138.9T to 124.9T, the second-largest downward adjustment of 2026 — and that gave hashprice some brief breathing room. But as of July 5, difficulty has already climbed back to 133.87T, and network hashrate has risen to about 935 EH/s, closing in on the historic 1-zettahash (ZH/s) threshold for the first time. Most of the relief the difficulty drop provided has already been given back. Hashrate Index's early estimate puts the next retarget, due around July 11, at roughly -0.8% — not enough to hand mining economics any real additional room.</p>
<p class="ja">最近のハッシュプライスのわずかな反発も、価格上昇よりむしろ採掘難易度の低下によるところが大きい。<a href="/blog/mining-difficulty-adjustment-analysis.html">本紙が以前指摘した通り</a>、6月の採掘難易度は138.9Tから124.9Tへ10.09%急落し、2026年で2番目に大きな下方調整を記録した。これがハッシュプライスに一時的な余裕を与えた。だが7月5日時点で難易度はすでに133.87Tまで戻り、ネットワークハッシュレートは史上初の1ゼタハッシュ(ZH/s)の大台に向けて約935EH/sまで上昇した。難易度低下で得られた余裕はすでに大半が失われた格好だ。ハッシュレートインデックスの初期推定では、7月11日前後に予定される次回の難易度調整も約-0.8%にとどまり、採掘経済にさらなる余裕を与えることはなさそうだ。</p>
<p class="es">El repunte reciente del hashprice se debe más a una caída de la dificultad que al repunte del precio. <a href="/blog/mining-difficulty-adjustment-analysis.html">Como este sitio ha cubierto antes</a>, la dificultad de minería de junio cayó 10.09%, de 138.9T a 124.9T, el segundo mayor ajuste a la baja de 2026, lo que dio al hashprice un respiro breve. Pero al 5 de julio, la dificultad ya ha vuelto a subir a 133.87T, y el hashrate de la red ha subido a unos 935 EH/s, acercándose por primera vez al histórico umbral de 1 zettahash (ZH/s). Buena parte del alivio que dio la caída de dificultad ya se ha devuelto. La estimación temprana de Hashrate Index sitúa el próximo reajuste, previsto hacia el 11 de julio, en apenas -0.8% — no lo suficiente para dar a la economía minera un respiro adicional real.</p>
<p class="de">Der jüngste Anstieg des Hashprice ist eher einem Rückgang der Difficulty als der Preisrally zu verdanken. <a href="/blog/mining-difficulty-adjustment-analysis.html">Wie diese Seite bereits berichtete</a>, fiel die Mining-Difficulty im Juni um 10,09% von 138,9 T auf 124,9 T — die zweitgrößte Abwärtsanpassung 2026 — und verschaffte dem Hashprice damit kurz etwas Luft. Doch zum 5. Juli ist die Difficulty bereits wieder auf 133,87 T gestiegen, und die Netzwerk-Hashrate ist auf rund 935 EH/s geklettert und nähert sich damit erstmals der historischen Schwelle von 1 Zettahash (ZH/s). Der Großteil der durch den Difficulty-Rückgang gewonnenen Entlastung ist damit bereits wieder aufgebraucht. Die frühe Schätzung von Hashrate Index für das nächste Retarget um den 11. Juli liegt bei nur etwa -0,8% — nicht genug, um der Mining-Ökonomie nennenswert zusätzlichen Spielraum zu geben.</p>
<p class="fr">La récente légère hausse du hashprice tient davantage à une baisse de la difficulté qu'au rallye du prix. <a href="/blog/mining-difficulty-adjustment-analysis.html">Comme ce site l'a déjà relevé</a>, la difficulté minière de juin a chuté de 10,09%, passant de 138,9 T à 124,9 T, le deuxième ajustement à la baisse le plus important de 2026 — ce qui a donné au hashprice un bref répit. Mais au 5 juillet, la difficulté est déjà remontée à 133,87 T, et le hashrate du réseau a grimpé à environ 935 EH/s, se rapprochant pour la première fois du seuil historique de 1 zettahash (ZH/s). La majeure partie du soulagement apporté par la baisse de la difficulté a déjà été reprise. La première estimation de Hashrate Index situe le prochain ajustement, attendu vers le 11 juillet, à environ -0,8% — insuffisant pour offrir une réelle marge supplémentaire à l'économie minière.</p>
<p class="pt">A recente leve alta do hashprice deve-se mais a uma queda na dificuldade do que ao rali do preço. <a href="/blog/mining-difficulty-adjustment-analysis.html">Como este site já cobriu antes</a>, a dificuldade de mineração de junho caiu 10,09%, de 138,9 T para 124,9 T, o segundo maior ajuste para baixo de 2026 — o que deu ao hashprice um breve alívio. Mas, em 5 de julho, a dificuldade já voltou a subir para 133,87 T, e o hashrate da rede subiu para cerca de 935 EH/s, aproximando-se pela primeira vez do histórico limiar de 1 zettahash (ZH/s). A maior parte do alívio proporcionado pela queda na dificuldade já foi devolvida. A estimativa inicial da Hashrate Index para o próximo reajuste, previsto para cerca de 11 de julho, é de aproximadamente -0,8% — insuficiente para dar à economia da mineração qualquer folga adicional real.</p>
<p class="tr">Hashprice'taki son artış, fiyat rallisinden çok zorluk düşüşüne bağlı. <a href="/blog/mining-difficulty-adjustment-analysis.html">Bu sitenin daha önce ele aldığı gibi</a>, Haziran ayı madencilik zorluğu 138,9T'den 124,9T'ye %10,09 düşerek 2026'nın ikinci en büyük aşağı yönlü ayarlamasını oluşturdu ve bu da hashprice'a kısa süreli bir nefes alanı sağladı. Ancak 5 Temmuz itibarıyla zorluk zaten 133,87T'ye geri tırmandı ve ağ hash oranı yaklaşık 935 EH/s'ye yükselerek ilk kez tarihi 1 zettahash (ZH/s) eşiğine yaklaştı. Zorluk düşüşünün sağladığı rahatlamanın büyük bölümü zaten geri alındı. Hashrate Index'in erken tahmini, 11 Temmuz civarında beklenen bir sonraki ayarlamayı yaklaşık %-0,8 olarak öngörüyor — bu da madencilik ekonomisine gerçek anlamda ek bir alan sağlamaya yetmiyor.</p>
<p class="vi">Mức tăng nhẹ gần đây của hashprice là nhờ độ khó giảm nhiều hơn là nhờ đà tăng giá. <a href="/blog/mining-difficulty-adjustment-analysis.html">Như trang này đã đề cập trước đây</a>, độ khó khai thác tháng 6 đã giảm 10,09%, từ 138,9T xuống 124,9T, mức điều chỉnh giảm lớn thứ hai của năm 2026 — điều này đã cho hashprice một khoảng thở ngắn ngủi. Nhưng tính đến ngày 5 tháng 7, độ khó đã tăng trở lại lên 133,87T, và hashrate mạng lưới đã tăng lên khoảng 935 EH/s, lần đầu tiên tiến sát ngưỡng lịch sử 1 zettahash (ZH/s). Phần lớn sự nhẹ nhõm mà đợt giảm độ khó mang lại đã bị lấy lại. Ước tính sớm của Hashrate Index cho lần điều chỉnh tiếp theo, dự kiến vào khoảng ngày 11 tháng 7, chỉ vào khoảng -0,8% — không đủ để mang lại thêm không gian thực sự nào cho kinh tế khai thác.</p>

<div class="ko">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">해시프라이스 vs 손익분기선 — 반등에도 여전히 아래</text>
  <text x="20" y="48" fill="#fb923c" font-size="13" font-weight="700" font-family="sans-serif">단위: PH/s당 하루 미국달러, 해시레이트인덱스·코인셰어즈 집계</text>
  <line x1="60" y1="102.5" x2="650" y2="102.5" stroke="#38bdf8" stroke-width="1.5" stroke-dasharray="6,5"/>
  <text x="645" y="94" fill="#38bdf8" font-size="13" font-weight="700" text-anchor="end" font-family="sans-serif">손익분기선 ≈$35 (코인셰어즈 추정)</text>
  <line x1="60" y1="330" x2="650" y2="330" stroke="#3f3f46" stroke-width="1"/>
  <text x="45" y="334" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$0</text>
  <text x="45" y="205" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$20</text>
  <text x="45" y="75" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$40</text>
  <polyline points="90,141.5 220,115.5 350,148 480,118.75 610,110.95" fill="none" stroke="#fb923c" stroke-width="2.5"/>
  <circle cx="90" cy="141.5" r="5" fill="#fb923c"/>
  <text x="90" y="127" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$29</text>
  <text x="90" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">1분기 저점(3월초)</text>
  <circle cx="220" cy="115.5" r="5" fill="#fb923c"/>
  <text x="220" y="101" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$33</text>
  <text x="220" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">1분기 평균</text>
  <circle cx="350" cy="148" r="5" fill="#fb923c"/>
  <text x="350" y="163" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$28</text>
  <text x="350" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">6월 중순(난이도컷 전)</text>
  <circle cx="480" cy="118.75" r="5" fill="#fb923c"/>
  <text x="480" y="104" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$32.5</text>
  <text x="480" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">6월 말(컷 후)</text>
  <circle cx="610" cy="110.95" r="6" fill="#fbbf24"/>
  <text x="610" y="96" fill="#fbbf24" font-size="15" font-weight="700" text-anchor="middle" font-family="sans-serif">$33.7</text>
  <text x="610" y="352" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">7월 초(지금)</text>
  <text x="650" y="378" fill="#52525b" font-size="13" text-anchor="end" font-family="sans-serif">출처: Hashrate Index, CoinShares</text>
</svg>
</div>
<div class="en es de fr pt tr vi">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">Hashprice vs Breakeven — Still Below, Even After the Bounce</text>
  <text x="20" y="48" fill="#fb923c" font-size="13" font-weight="700" font-family="sans-serif">USD per PH/s per day, per Hashrate Index &amp; CoinShares</text>
  <line x1="60" y1="102.5" x2="650" y2="102.5" stroke="#38bdf8" stroke-width="1.5" stroke-dasharray="6,5"/>
  <text x="645" y="94" fill="#38bdf8" font-size="13" font-weight="700" text-anchor="end" font-family="sans-serif">Breakeven ≈$35 (CoinShares est.)</text>
  <line x1="60" y1="330" x2="650" y2="330" stroke="#3f3f46" stroke-width="1"/>
  <text x="45" y="334" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$0</text>
  <text x="45" y="205" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$20</text>
  <text x="45" y="75" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$40</text>
  <polyline points="90,141.5 220,115.5 350,148 480,118.75 610,110.95" fill="none" stroke="#fb923c" stroke-width="2.5"/>
  <circle cx="90" cy="141.5" r="5" fill="#fb923c"/>
  <text x="90" y="127" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$29</text>
  <text x="90" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">Q1 low (early Mar)</text>
  <circle cx="220" cy="115.5" r="5" fill="#fb923c"/>
  <text x="220" y="101" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$33</text>
  <text x="220" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">Q1 average</text>
  <circle cx="350" cy="148" r="5" fill="#fb923c"/>
  <text x="350" y="163" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$28</text>
  <text x="350" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">Mid-Jun (pre-cut)</text>
  <circle cx="480" cy="118.75" r="5" fill="#fb923c"/>
  <text x="480" y="104" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$32.5</text>
  <text x="480" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">Late Jun (post-cut)</text>
  <circle cx="610" cy="110.95" r="6" fill="#fbbf24"/>
  <text x="610" y="96" fill="#fbbf24" font-size="15" font-weight="700" text-anchor="middle" font-family="sans-serif">$33.7</text>
  <text x="610" y="352" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">Now (early Jul)</text>
  <text x="650" y="378" fill="#52525b" font-size="13" text-anchor="end" font-family="sans-serif">Source: Hashrate Index, CoinShares</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">ハッシュプライス vs 損益分岐点 — 反発後もなお下回る</text>
  <text x="20" y="48" fill="#fb923c" font-size="13" font-weight="700" font-family="sans-serif">単位: PH/sあたり1日の米ドル、ハッシュレートインデックス・コインシェアーズ集計</text>
  <line x1="60" y1="102.5" x2="650" y2="102.5" stroke="#38bdf8" stroke-width="1.5" stroke-dasharray="6,5"/>
  <text x="645" y="94" fill="#38bdf8" font-size="13" font-weight="700" text-anchor="end" font-family="sans-serif">損益分岐点 ≈$35(コインシェアーズ推定)</text>
  <line x1="60" y1="330" x2="650" y2="330" stroke="#3f3f46" stroke-width="1"/>
  <text x="45" y="334" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$0</text>
  <text x="45" y="205" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$20</text>
  <text x="45" y="75" fill="#71717a" font-size="13" text-anchor="end" font-family="sans-serif">$40</text>
  <polyline points="90,141.5 220,115.5 350,148 480,118.75 610,110.95" fill="none" stroke="#fb923c" stroke-width="2.5"/>
  <circle cx="90" cy="141.5" r="5" fill="#fb923c"/>
  <text x="90" y="127" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$29</text>
  <text x="90" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">第1四半期安値(3月初)</text>
  <circle cx="220" cy="115.5" r="5" fill="#fb923c"/>
  <text x="220" y="101" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$33</text>
  <text x="220" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">第1四半期平均</text>
  <circle cx="350" cy="148" r="5" fill="#fb923c"/>
  <text x="350" y="163" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$28</text>
  <text x="350" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">6月中旬(難易度低下前)</text>
  <circle cx="480" cy="118.75" r="5" fill="#fb923c"/>
  <text x="480" y="104" fill="#fafafa" font-size="14" font-weight="700" text-anchor="middle" font-family="sans-serif">$32.5</text>
  <text x="480" y="352" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">6月末(低下後)</text>
  <circle cx="610" cy="110.95" r="6" fill="#fbbf24"/>
  <text x="610" y="96" fill="#fbbf24" font-size="15" font-weight="700" text-anchor="middle" font-family="sans-serif">$33.7</text>
  <text x="610" y="352" fill="#fbbf24" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">現在(7月初)</text>
  <text x="650" y="378" fill="#52525b" font-size="13" text-anchor="end" font-family="sans-serif">出典: Hashrate Index, CoinShares</text>
</svg>
</div>

<h2 class="ko">가격은 올랐는데 채굴 경제는 안 풀렸다 — 지금 지켜봐야 할 지점</h2>
<h2 class="en">Price Rose, Mining Economics Didn't — What to Watch From Here</h2>
<h2 class="ja">価格は上がったが採掘経済は好転していない — 今後注視すべき点</h2>
<h2 class="es">El Precio Subió, la Economía Minera No — Qué Vigilar Desde Aquí</h2>
<h2 class="de">Der Preis Stieg, die Mining-Ökonomie Nicht — Was Es Jetzt zu Beobachten Gilt</h2>
<h2 class="fr">Le Prix a Grimpé, Pas l'Économie Minière — Ce Qu'il Faut Surveiller Désormais</h2>
<h2 class="pt">O Preço Subiu, a Economia da Mineração Não — O Que Observar a Partir de Agora</h2>
<h2 class="tr">Fiyat Yükseldi, Madencilik Ekonomisi Yükselmedi — Buradan İtibaren İzlenmesi Gerekenler</h2>
<h2 class="vi">Giá Tăng, Kinh Tế Khai Thác Thì Không — Những Gì Cần Theo Dõi Từ Đây</h2>

<p class="ko">지금 국면을 나란히 놓으면 이렇다. 가격은 저점 대비 약 9% 올라 회복 국면에 들어섰다는 신호를 냈다. 그런데 그 신호를 만든 건 숏스퀴즈와 매크로 재료(연준 발언, 고용지표)였지, 채굴 경제의 개선이 아니다. 해시프라이스는 손익분기선 근방에서 오르내릴 뿐 뚜렷하게 위로 뚫지 못했고, 난이도는 오히려 그 반등분을 갉아먹는 방향으로 되돌아왔다. 결과적으로 가격을 밀어올린 수요 쪽 힘과, 채굴자의 원가 구조를 결정하는 공급 쪽 압박이 서로 다른 속도로 움직이고 있다.</p>
<p class="en">Laid side by side, the current picture looks like this: price is up about 9% from its low, sending a recovery signal. But that signal was built by a short squeeze and macro catalysts — Fed commentary, a soft jobs report — not by an improvement in mining economics. Hashprice has only drifted around the breakeven line without decisively clearing it, and difficulty has already climbed back in a way that eats into whatever relief the bounce provided. The result is that the demand-side force pushing price up and the supply-side pressure shaping miners' cost structure are moving at different speeds.</p>
<p class="ja">今の局面を並べてみるとこうなる。価格は安値から約9%上昇し、回復局面入りを示すシグナルを出した。だがそのシグナルを作ったのはショートスクイーズとマクロ材料(FRB発言、雇用統計)であり、採掘経済の改善ではない。ハッシュプライスは損益分岐点付近を行き来するだけで明確に上抜けできておらず、難易度はむしろその反発分を食いつぶす方向へ戻ってきた。結果として、価格を押し上げた需要側の力と、採掘者のコスト構造を決める供給側の圧力が、異なる速度で動いている。</p>
<p class="es">Puestos uno junto al otro, el panorama actual luce así: el precio subió cerca de 9% desde su mínimo, enviando una señal de recuperación. Pero esa señal la construyeron un short squeeze y catalizadores macro —comentarios de la Fed, un informe de empleo suave— no una mejora en la economía minera. El hashprice solo ha oscilado en torno al punto de equilibrio sin superarlo decisivamente, y la dificultad ya ha vuelto a subir de una forma que se come buena parte del alivio que dio el rebote. El resultado es que la fuerza de demanda que empujó el precio hacia arriba y la presión de oferta que moldea la estructura de costos de los mineros se mueven a velocidades distintas.</p>
<p class="de">Nebeneinandergelegt sieht die aktuelle Lage so aus: Der Preis ist rund 9% von seinem Tief gestiegen und sendet ein Erholungssignal. Doch dieses Signal wurde durch einen Short Squeeze und Makro-Katalysatoren — Fed-Kommentare, ein schwacher Arbeitsmarktbericht — erzeugt, nicht durch eine Verbesserung der Mining-Ökonomie. Der Hashprice ist nur um die Gewinnschwelle herum gependelt, ohne sie klar zu durchbrechen, und die Difficulty ist bereits wieder so gestiegen, dass sie einen Großteil der durch die Erholung gewonnenen Entlastung auffrisst. Das Ergebnis: Die Nachfragekraft, die den Preis nach oben trieb, und der Angebotsdruck, der die Kostenstruktur der Miner bestimmt, bewegen sich mit unterschiedlicher Geschwindigkeit.</p>
<p class="fr">Mis côte à côte, le tableau actuel se présente ainsi : le prix a augmenté d'environ 9% depuis son plus bas, envoyant un signal de reprise. Mais ce signal a été construit par un short squeeze et des catalyseurs macroéconomiques — des commentaires de la Fed, un rapport sur l'emploi décevant — et non par une amélioration de l'économie minière. Le hashprice n'a fait qu'osciller autour du seuil de rentabilité sans le dépasser nettement, et la difficulté est déjà remontée d'une manière qui grignote une bonne partie du répit apporté par le rebond. Résultat : la force de la demande qui pousse le prix vers le haut et la pression de l'offre qui façonne la structure de coûts des mineurs évoluent à des vitesses différentes.</p>
<p class="pt">Colocado lado a lado, o quadro atual é assim: o preço subiu cerca de 9% em relação ao seu mínimo, enviando um sinal de recuperação. Mas esse sinal foi construído por um short squeeze e por catalisadores macro — comentários do Fed, um relatório de emprego fraco — não por uma melhora na economia da mineração. O hashprice apenas oscilou em torno da linha de equilíbrio sem superá-la de forma decisiva, e a dificuldade já voltou a subir de um jeito que consome boa parte do alívio proporcionado pela recuperação. O resultado é que a força de demanda que empurra o preço para cima e a pressão de oferta que molda a estrutura de custos das mineradoras estão se movendo em velocidades diferentes.</p>
<p class="tr">Yan yana koyulduğunda, mevcut tablo şöyle görünüyor: fiyat, dibinden yaklaşık %9 yükselerek bir toparlanma sinyali verdi. Ancak bu sinyal, madencilik ekonomisindeki bir iyileşmeyle değil, bir short squeeze ve makro katalizörlerle — Fed açıklamaları, zayıf bir istihdam raporu — oluşturuldu. Hashprice yalnızca başabaş çizgisi etrafında dolaştı ve onu kesin olarak aşamadı; zorluk ise zaten sıçramanın sağladığı rahatlamanın büyük bölümünü yiyip bitirecek şekilde geri tırmandı. Sonuç olarak, fiyatı yukarı iten talep tarafındaki güç ile madencilerin maliyet yapısını belirleyen arz tarafındaki baskı farklı hızlarda hareket ediyor.</p>
<p class="vi">Đặt cạnh nhau, bức tranh hiện tại trông như thế này: giá đã tăng khoảng 9% so với đáy, phát đi tín hiệu phục hồi. Nhưng tín hiệu đó được tạo nên bởi một đợt short squeeze và các yếu tố vĩ mô — phát biểu của Fed, báo cáo việc làm yếu — chứ không phải nhờ sự cải thiện của kinh tế khai thác. Hashprice chỉ dao động quanh ngưỡng hòa vốn mà không vượt qua một cách dứt khoát, còn độ khó thì đã leo trở lại theo cách ăn mòn hầu hết phần nhẹ nhõm mà đợt bật tăng mang lại. Kết quả là lực từ phía cầu đẩy giá lên và áp lực từ phía cung định hình cơ cấu chi phí của thợ đào đang di chuyển với tốc độ khác nhau.</p>

<p class="ko">이 괴리가 중요한 이유는 채굴자의 매도가 ETF나 고래의 자금 흐름과 성격이 다르기 때문이다. ETF 자금은 투자 판단에 따라 유입과 유출을 오갈 수 있고, 고래의 매집도 심리에 따라 방향을 바꿀 수 있다. 그러나 해시프라이스가 손익분기선 아래에 머무는 한, 특히 구형 장비를 운용하는 한계 채굴자들의 매도는 가격이 오르든 내리든 계속될 공산이 크다. 앞으로 좁혀볼 지점은 세 가지다. 첫째, 해시프라이스가 35달러 손익분기선을 뚜렷하게 넘어서는지—난이도가 계속 사상 최고권을 유지하는 한 이 문턱을 넘기는 쉽지 않다. 둘째, 다음 분기(2분기) 상장 채굴사 매도 집계가 나올 때 매도 속도가 둔화됐는지, 아니면 1분기 기록을 다시 넘어서는지. 셋째, 채굴자 보유잔고(약 180만 BTC)가 바닥을 다지는지, 아니면 계속 줄어드는지—이 잔고는 무한정 줄어들 수 있는 게 아니라서, 다 팔고 나면 남는 건 서서히 판매가 아니라 한계 채굴사의 파산·인수합병이라는 더 급격한 형태로 나타날 수 있다.</p>
<p class="en">This gap matters because miner selling is a different animal from ETF or whale flows. ETF money can flow in or out depending on investor conviction, and whale accumulation can flip with sentiment. But as long as hashprice stays below breakeven, selling by marginal miners running older hardware is likely to keep going regardless of which way price moves. Three things narrow down what's worth watching from here. First, whether hashprice decisively clears the $35 breakeven line — not an easy bar while difficulty keeps sitting near record highs. Second, whether next quarter's public miner sales tally shows the pace slowing, or breaking Q1's record again. Third, whether the miner reserve (around 1.8 million BTC) finds a floor or keeps shrinking — that pool can't decline indefinitely, and once it's mostly gone, what replaces gradual selling could be a sharper event: bankruptcies and consolidation among the weakest miners.</p>
<p class="ja">この乖離が重要なのは、採掘者の売却がETFやクジラの資金フローとは性格が異なるからだ。ETF資金は投資判断次第で流入・流出を行き来でき、クジラの買い集めも心理次第で方向を変えられる。しかしハッシュプライスが損益分岐点を下回り続ける限り、特に旧世代機材を稼働させる限界採掘者の売却は、価格が上がろうと下がろうと続く公算が大きい。今後絞り込むべき点は三つだ。第一に、ハッシュプライスが35ドルの損益分岐点を明確に上抜けるかどうか—難易度が史上最高圏にとどまり続ける限り、この壁を越えるのは容易ではない。第二に、次の四半期(第2四半期)の上場採掘企業売却集計が出た際、売却ペースが鈍化しているか、それとも第1四半期の記録を再び上回るか。第三に、採掘者保有残高(約180万BTC)が底を固めるか、それとも減り続けるか—この残高は無限に減り続けられるわけではなく、大半を使い果たした後に残るのは緩やかな売却ではなく、限界採掘企業の破産・買収合併というより急激な形で現れる可能性がある。</p>
<p class="es">Esta brecha importa porque la venta de mineros es un animal distinto de los flujos de ETF o de ballenas. El dinero de los ETF puede entrar o salir según la convicción del inversor, y la acumulación de ballenas puede girar con el sentimiento. Pero mientras el hashprice se mantenga bajo el equilibrio, es probable que la venta de mineros marginales que operan hardware antiguo continúe sin importar hacia dónde se mueva el precio. Tres cosas acotan lo que vale la pena vigilar desde aquí. Primero, si el hashprice supera decisivamente el punto de equilibrio de $35 — no es un listón fácil mientras la dificultad se mantenga cerca de máximos históricos. Segundo, si el recuento de ventas de mineros públicos del próximo trimestre muestra que el ritmo se desacelera, o que vuelve a romper el récord del T1. Tercero, si la reserva de mineros (unos 1.8 millones de BTC) encuentra un piso o sigue reduciéndose — ese fondo no puede caer indefinidamente, y una vez que se agote en su mayoría, lo que reemplace a la venta gradual podría ser un evento más abrupto: quiebras y consolidación entre los mineros más débiles.</p>
<p class="de">Diese Lücke ist wichtig, weil Miner-Verkäufe ein anderes Tier sind als ETF- oder Whale-Flüsse. ETF-Gelder können je nach Anlegerüberzeugung ein- oder ausströmen, und die Akkumulation von Whales kann mit der Stimmung kippen. Doch solange der Hashprice unter der Gewinnschwelle bleibt, dürften Verkäufe marginaler Miner mit älterer Hardware unabhängig von der Preisrichtung weitergehen. Drei Dinge grenzen ein, was sich von hier aus zu beobachten lohnt. Erstens, ob der Hashprice die Gewinnschwelle von 35 $ entschieden überwindet — keine leichte Hürde, solange die Difficulty nahe Rekordhochs verharrt. Zweitens, ob die Verkaufszahlen börsennotierter Miner im nächsten Quartal ein langsameres Tempo zeigen oder erneut den Q1-Rekord brechen. Drittens, ob die Miner-Reserve (rund 1,8 Millionen BTC) einen Boden findet oder weiter schrumpft — dieser Pool kann nicht unbegrenzt sinken, und sobald er größtenteils aufgebraucht ist, könnte an die Stelle des allmählichen Verkaufs ein schärferes Ereignis treten: Insolvenzen und Konsolidierung unter den schwächsten Minern.</p>
<p class="fr">Cet écart importe parce que les ventes des mineurs sont d'une nature différente des flux d'ETF ou de baleines. L'argent des ETF peut entrer ou sortir selon la conviction des investisseurs, et l'accumulation des baleines peut s'inverser avec le sentiment. Mais tant que le hashprice reste sous le seuil de rentabilité, les ventes des mineurs marginaux exploitant du matériel plus ancien devraient probablement se poursuivre quel que soit le sens dans lequel le prix évolue. Trois éléments permettent de cerner ce qu'il vaut la peine de surveiller à partir de maintenant. Premièrement, si le hashprice franchit nettement le seuil de rentabilité de 35 $ — une barre difficile à atteindre tant que la difficulté reste proche de ses sommets historiques. Deuxièmement, si le décompte des ventes des mineurs cotés du prochain trimestre montre un ralentissement du rythme, ou bat de nouveau le record du T1. Troisièmement, si la réserve des mineurs (environ 1,8 million de BTC) trouve un plancher ou continue de rétrécir — ce stock ne peut pas décliner indéfiniment, et une fois qu'il sera en grande partie épuisé, ce qui remplacera les ventes progressives pourrait être un événement plus brutal : faillites et consolidation parmi les mineurs les plus faibles.</p>
<p class="pt">Essa lacuna importa porque a venda das mineradoras é um animal diferente dos fluxos de ETFs ou de baleias. O dinheiro dos ETFs pode entrar ou sair dependendo da convicção dos investidores, e o acúmulo de baleias pode se inverter conforme o sentimento. Mas enquanto o hashprice permanecer abaixo do ponto de equilíbrio, é provável que a venda por mineradoras marginais que operam equipamentos mais antigos continue independentemente do rumo do preço. Três coisas ajudam a delimitar o que vale a pena observar a partir daqui. Primeiro, se o hashprice supera decisivamente a linha de equilíbrio de US$ 35 — uma barra nada fácil enquanto a dificuldade permanece perto de máximas recordes. Segundo, se o levantamento de vendas das mineradoras públicas do próximo trimestre mostra o ritmo desacelerando, ou batendo o recorde do T1 novamente. Terceiro, se a reserva das mineradoras (cerca de 1,8 milhão de BTC) encontra um piso ou continua encolhendo — esse estoque não pode cair indefinidamente, e, uma vez que estiver majoritariamente esgotado, o que substituirá a venda gradual pode ser um evento mais abrupto: falências e consolidação entre as mineradoras mais fracas.</p>
<p class="tr">Bu fark önemli çünkü madenci satışları, ETF veya balina akışlarından farklı bir olgu. ETF parası, yatırımcı kanaatine bağlı olarak içeri veya dışarı akabilir ve balina birikimi duyarlılıkla birlikte tersine dönebilir. Ancak hashprice başabaş noktasının altında kaldığı sürece, eski donanımla çalışan marjinal madencilerin satışlarının fiyatın yönünden bağımsız olarak sürmesi muhtemel. Buradan itibaren neyin izlenmeye değer olduğunu üç şey belirliyor. Birincisi, hashprice'ın 35 dolarlık başabaş çizgisini kesin olarak aşıp aşmayacağı — zorluk rekor seviyelere yakın kaldığı sürece bu kolay bir eşik değil. İkincisi, gelecek çeyreğin halka açık madenci satış verilerinin hızın yavaşladığını mı yoksa 1Ç rekorunu yeniden mi kırdığını göstereceği. Üçüncüsü, madenci rezervinin (yaklaşık 1,8 milyon BTC) bir taban bulup bulmayacağı ya da küçülmeye devam edip etmeyeceği — bu havuz sonsuza dek küçülemez ve büyük ölçüde tükendiğinde, kademeli satışın yerini daha keskin bir olay alabilir: en zayıf madenciler arasında iflaslar ve konsolidasyon.</p>
<p class="vi">Khoảng cách này quan trọng vì việc bán ra của thợ đào là một hiện tượng khác hẳn so với dòng vốn ETF hay dòng tiền cá voi. Tiền ETF có thể chảy vào hoặc ra tùy theo niềm tin của nhà đầu tư, và việc gom hàng của cá voi có thể đảo chiều theo tâm lý thị trường. Nhưng chừng nào hashprice còn ở dưới điểm hòa vốn, việc bán ra của các thợ đào cận biên vận hành thiết bị cũ nhiều khả năng sẽ tiếp tục bất kể giá di chuyển theo hướng nào. Có ba điều đáng theo dõi từ đây. Thứ nhất, liệu hashprice có vượt qua ngưỡng hòa vốn 35 đô la một cách dứt khoát hay không — đây không phải là mức dễ đạt được khi độ khó vẫn duy trì gần mức cao kỷ lục. Thứ hai, liệu số liệu bán ra của các thợ đào niêm yết công khai trong quý tới có cho thấy tốc độ chậm lại, hay lại phá vỡ kỷ lục của quý 1. Thứ ba, liệu dự trữ của thợ đào (khoảng 1,8 triệu BTC) có tìm được đáy hay tiếp tục thu hẹp — lượng dự trữ này không thể giảm mãi mãi, và một khi phần lớn đã cạn, điều thay thế cho việc bán dần có thể là một sự kiện gay gắt hơn: phá sản và hợp nhất giữa các thợ đào yếu nhất.</p>

<div class="box ko">💡 <strong>정리:</strong> 비트코인이 6월 30일 저점(5만 7,950달러) 대비 약 9% 반등해 6만 3,000달러대에 들어선 사이, 상장 채굴사들은 2026년 1분기에만 3만 2,000 BTC 넘게 팔아 2025년 연간 매도량을 넘어섰고, 채굴자 보유잔고는 약 180만 BTC까지 줄었다. 해시프라이스는 33~38달러 사이(집계처에 따라 상이)로 코인셰어즈가 추정한 손익분기선(약 35달러) 근방이거나 그 아래이며, 채굴 난이도는 6월 급락분을 대부분 반납하며 다시 사상 최고권으로 향하고 있다. 가격은 회복 신호를 냈지만 채굴 경제의 압박은 그대로라는 괴리가, 지금 국면에서 지켜봐야 할 지점이다.</div>
<div class="box en">💡 <strong>Bottom line:</strong> While bitcoin rebounded roughly 9% off its June 30 low ($57,950) into the low $63,000s, public miners sold more than 32,000 BTC in Q1 2026 alone — already exceeding all of 2025's sales — and miner reserves fell to about 1.8 million BTC. Hashprice sits between $33 and $38 depending on the data source, at or below CoinShares' roughly $35 breakeven estimate, and mining difficulty has already given back most of June's plunge on its way back toward record highs. Price sent a recovery signal, but the pressure on mining economics hasn't lifted — that gap is what's worth watching from here.</div>
<div class="box ja">💡 <strong>まとめ:</strong> ビットコインが6月30日の安値(5万7,950ドル)から約9%反発して6万3,000ドル台に入る一方、上場採掘企業は2026年第1四半期だけで3万2,000BTC超を売却し2025年通年の売却量を超え、採掘者保有残高は約180万BTCまで減少した。ハッシュプライスは集計元によって33~38ドルの間にあり、コインシェアーズが推定する損益分岐点(約35ドル)付近かそれ以下で、採掘難易度は6月の急落分の大半を取り戻し再び史上最高圏へ向かっている。価格は回復シグナルを出したが、採掘経済への圧力は解消されていない——この乖離こそ、今の局面で注視すべき点だ。</div>
<div class="box es">💡 <strong>En resumen:</strong> Mientras bitcoin rebotó cerca de 9% desde su mínimo del 30 de junio ($57,950) hasta la zona baja de los $63,000, los mineros públicos vendieron más de 32,000 BTC solo en el T1 de 2026 —superando ya todas las ventas de 2025— y las reservas de mineros cayeron a unos 1.8 millones de BTC. El hashprice se ubica entre $33 y $38 según la fuente de datos, en o por debajo del punto de equilibrio de unos $35 que estima CoinShares, y la dificultad de minería ya ha devuelto la mayor parte de la caída de junio en su camino de vuelta hacia máximos históricos. El precio envió una señal de recuperación, pero la presión sobre la economía minera no ha cedido — esa brecha es lo que vale la pena vigilar desde aquí.</div>
<div class="box de">💡 <strong>Fazit:</strong> Während Bitcoin von seinem Tief vom 30. Juni (57.950 $) um rund 9% in die untere 63.000-Dollar-Zone stieg, verkauften börsennotierte Miner allein im ersten Quartal 2026 über 32.000 BTC — schon mehr als im gesamten Jahr 2025 — und die Miner-Reserven fielen auf etwa 1,8 Millionen BTC. Der Hashprice liegt je nach Datenquelle zwischen 33 und 38 $, auf oder unter der von CoinShares geschätzten Gewinnschwelle von etwa 35 $, und die Mining-Difficulty hat den Großteil des Juni-Einbruchs bereits wieder aufgeholt und steuert erneut auf Rekordhochs zu. Der Preis sandte ein Erholungssignal, doch der Druck auf die Mining-Ökonomie ist nicht gewichen — diese Lücke ist es, was sich von hier aus zu beobachten lohnt.</div>
<div class="box fr">💡 <strong>En résumé :</strong> alors que le bitcoin a rebondi d'environ 9% depuis son plus bas du 30 juin (57 950 $) vers la zone basse des 63 000 $, les mineurs cotés en bourse ont vendu plus de 32 000 BTC au seul T1 2026 — dépassant déjà l'ensemble des ventes de 2025 — et les réserves des mineurs sont tombées à environ 1,8 million de BTC. Le hashprice se situe entre 33 $ et 38 $ selon la source de données, au niveau ou en dessous de l'estimation du seuil de rentabilité de CoinShares d'environ 35 $, et la difficulté minière a déjà repris la majeure partie de la chute de juin en remontant vers des sommets records. Le prix a envoyé un signal de reprise, mais la pression sur l'économie minière ne s'est pas relâchée — cet écart est ce qu'il vaut la peine de surveiller à partir de maintenant.</div>
<div class="box pt">💡 <strong>Resumo:</strong> Enquanto o bitcoin recuperou cerca de 9% em relação ao seu mínimo de 30 de junho (US$ 57.950), chegando à faixa baixa dos US$ 63.000, as mineradoras públicas venderam mais de 32.000 BTC somente no T1 de 2026 — já superando todas as vendas de 2025 — e as reservas das mineradoras caíram para cerca de 1,8 milhão de BTC. O hashprice está entre US$ 33 e US$ 38, dependendo da fonte de dados, no nível ou abaixo da estimativa de ponto de equilíbrio de cerca de US$ 35 da CoinShares, e a dificuldade de mineração já devolveu a maior parte da queda de junho a caminho de novas máximas recordes. O preço enviou um sinal de recuperação, mas a pressão sobre a economia da mineração não diminuiu — essa lacuna é o que vale a pena observar a partir daqui.</div>
<div class="box tr">💡 <strong>Özet:</strong> Bitcoin, 30 Haziran dibinden (57.950 $) yaklaşık %9 toparlanarak 63.000 doların altına yükselirken, halka açık madenciler yalnızca 2026'nın ilk çeyreğinde 32.000 BTC'nin üzerinde satış yaptı — 2025'in tamamındaki satışları şimdiden geride bıraktı — ve madenci rezervleri yaklaşık 1,8 milyon BTC'ye geriledi. Hashprice, veri kaynağına bağlı olarak 33 ile 38 dolar arasında seyrediyor; bu, CoinShares'in yaklaşık 35 dolarlık başabaş tahmininde veya altında. Madencilik zorluğu ise Haziran ayındaki düşüşün büyük bölümünü geri alarak yeniden rekor seviyelere doğru ilerliyor. Fiyat bir toparlanma sinyali verdi, ancak madencilik ekonomisi üzerindeki baskı hafiflemedi — buradan itibaren izlenmeye değer olan da bu fark.</div>
<div class="box vi">💡 <strong>Tóm lại:</strong> Trong khi bitcoin đã phục hồi khoảng 9% từ đáy 57.950 đô la ngày 30 tháng 6 lên mức thấp của vùng 63.000 đô la, các thợ đào niêm yết công khai đã bán hơn 32.000 BTC chỉ riêng trong quý 1 năm 2026 — đã vượt qua toàn bộ doanh số bán của năm 2025 — và dự trữ của thợ đào đã giảm xuống còn khoảng 1,8 triệu BTC. Hashprice dao động từ 33 đến 38 đô la tùy nguồn dữ liệu, bằng hoặc thấp hơn mức ước tính điểm hòa vốn khoảng 35 đô la của CoinShares, và độ khó khai thác đã lấy lại phần lớn mức giảm của tháng 6 trên đường trở lại các mức cao kỷ lục. Giá đã phát đi tín hiệu phục hồi, nhưng áp lực lên kinh tế khai thác vẫn chưa giảm bớt — đó là khoảng cách đáng theo dõi từ đây.</div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: CoinShares(1분기 채굴 리포트, 손익분기선·해시프라이스 추정), TheMinerMag(상장 채굴사 매도량 집계), CryptoQuant(채굴자 보유잔고), Hashrate Index·CoinWarz·blockchaincenter(해시프라이스·난이도·해시레이트), Yahoo Finance, BTCtiming.com 자체 분석("해시레이트는 1제타해시로, 채굴 수익은 사상 최저로", "상장 채굴사, 1분기에만 3만 2천 BTC 매도", "난이도 조정 급등, 해시레이트는 후행 지표라는 걸 기억하세요"). 수치는 인용 시점 기준이며 실시간으로 변동할 수 있다. 이 글은 투자 조언이 아니다.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinShares (Q1 mining report, breakeven and hashprice estimates), TheMinerMag (public miner sales tally), CryptoQuant (Miner Reserve), Hashrate Index, CoinWarz, and blockchaincenter (hashprice, difficulty, hashrate), Yahoo Finance, BTCtiming.com's own analysis ("Hashrate Toward 1 Zettahash, Mining Revenue Toward Record Lows," "Public Miners Sold Over 32,000 BTC in Q1 Alone," "Difficulty Adjustment Spikes — Remember Hashrate Is a Lagging Indicator"). Figures are as of the time cited and may change in real time. This article is not investment advice.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: CoinShares(第1四半期採掘レポート、損益分岐点・ハッシュプライス推定)、TheMinerMag(上場採掘企業売却量集計)、CryptoQuant(採掘者保有残高)、Hashrate Index・CoinWarz・blockchaincenter(ハッシュプライス・難易度・ハッシュレート)、Yahoo Finance、BTCtiming.com自社分析(「ハッシュレートは1ゼタハッシュへ、採掘収益は史上最低へ」「上場採掘企業、第1四半期だけで3万2千BTC売却」「難易度調整急騰、ハッシュレートは遅行指標だと忘れずに」)。数値は引用時点のものであり、リアルタイムで変動しうる。本記事は投資助言ではない。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinShares (informe minero del T1, estimaciones de equilibrio y hashprice), TheMinerMag (recuento de ventas de mineros públicos), CryptoQuant (Reserva de Mineros), Hashrate Index, CoinWarz y blockchaincenter (hashprice, dificultad, hashrate), Yahoo Finance, análisis propio de BTCtiming.com ("El Hashrate Hacia 1 Zettahash, los Ingresos Mineros Hacia Mínimos Récord", "Mineros Públicos Vendieron Más de 32,000 BTC Solo en el T1", "La Dificultad Se Dispara — Recuerda que el Hashrate Es un Indicador Rezagado"). Las cifras corresponden al momento citado y pueden cambiar en tiempo real. Este artículo no es asesoramiento de inversión.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinShares (Q1-Mining-Report, Schätzungen zu Gewinnschwelle und Hashprice), TheMinerMag (Verkaufszahlen börsennotierter Miner), CryptoQuant (Miner-Reserve), Hashrate Index, CoinWarz und blockchaincenter (Hashprice, Difficulty, Hashrate), Yahoo Finance, BTCtiming.com-Eigenanalyse ("Hashrate Richtung 1 Zettahash, Mining-Erlöse Richtung Rekordtief", "Börsennotierte Miner Verkauften Allein in Q1 Über 32.000 BTC", "Difficulty-Anpassung Schnellt Hoch — Hashrate Bleibt Ein Nachlaufender Indikator"). Die Zahlen entsprechen dem zitierten Zeitpunkt und können sich in Echtzeit ändern. Dieser Artikel ist keine Anlageberatung.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinShares (rapport minier du T1, estimations du seuil de rentabilité et du hashprice), TheMinerMag (décompte des ventes des mineurs cotés), CryptoQuant (Réserve des Mineurs), Hashrate Index, CoinWarz et blockchaincenter (hashprice, difficulté, hashrate), Yahoo Finance, analyse propre de BTCtiming.com (« Le Hashrate Vers 1 Zettahash, les Revenus Miniers Vers des Plus Bas Records », « Les Mineurs Cotés Ont Vendu Plus de 32 000 BTC au Seul T1 », « La Difficulté S'Envole — Rappelez-Vous que le Hashrate Est un Indicateur Retardé »). Les chiffres correspondent au moment cité et peuvent évoluer en temps réel. Cet article ne constitue pas un conseil en investissement.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinShares (relatório de mineração do T1, estimativas de ponto de equilíbrio e hashprice), TheMinerMag (levantamento de vendas de mineradoras públicas), CryptoQuant (Reserva de Mineradoras), Hashrate Index, CoinWarz e blockchaincenter (hashprice, dificuldade, hashrate), Yahoo Finance, análise própria da BTCtiming.com ("O Hashrate Rumo a 1 Zettahash, a Receita de Mineração Rumo a Mínimas Recordes", "Mineradoras Públicas Venderam Mais de 32.000 BTC Só no T1", "Ajuste de Dificuldade Dispara — Lembre-se de que o Hashrate É um Indicador Defasado"). Os números correspondem ao momento citado e podem mudar em tempo real. Este artigo não é aconselhamento de investimento.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinShares (1Ç madencilik raporu, başabaş ve hashprice tahminleri), TheMinerMag (halka açık madenci satış verileri), CryptoQuant (Madenci Rezervi), Hashrate Index, CoinWarz ve blockchaincenter (hashprice, zorluk, hash oranı), Yahoo Finance, BTCtiming.com'un kendi analizi ("Hashrate 1 Zettahash'e Doğru, Madencilik Geliri Rekor Düşüklere Doğru", "Halka Açık Madenciler Yalnızca 1Ç'de 32.000 BTC'nin Üzerinde Sattı", "Zorluk Ayarlaması Sıçradı — Hash Oranının Gecikmeli Bir Gösterge Olduğunu Unutmayın"). Rakamlar belirtilen zamana aittir ve gerçek zamanlı olarak değişebilir. Bu yazı yatırım tavsiyesi değildir.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinShares (báo cáo khai thác quý 1, ước tính điểm hòa vốn và hashprice), TheMinerMag (thống kê doanh số bán của thợ đào niêm yết công khai), CryptoQuant (Dự Trữ Của Thợ Đào), Hashrate Index, CoinWarz và blockchaincenter (hashprice, độ khó, hashrate), Yahoo Finance, phân tích riêng của BTCtiming.com ("Hashrate Hướng Tới 1 Zettahash, Doanh Thu Khai Thác Hướng Tới Mức Thấp Kỷ Lục", "Thợ Đào Niêm Yết Công Khai Bán Hơn 32.000 BTC Chỉ Trong Quý 1", "Điều Chỉnh Độ Khó Tăng Vọt — Hãy Nhớ Rằng Hashrate Là Chỉ Báo Trễ"). Các số liệu tính đến thời điểm được trích dẫn và có thể thay đổi theo thời gian thực. Bài viết này không phải là lời khuyên đầu tư.</p>
<?php require __DIR__.'/_footer.php'; ?>
