<?php $slug = 'mtgox-bitstamp-repayment-supply-overhang'; require __DIR__.'/_header.php'; ?>

<p class="ko">2014년 파산한 일본 거래소 마운트곡스(Mt. Gox)의 관재인 지갑에서 7월 6일 4만7228 비트코인(BTC)이 비트스탬프(Bitstamp) 연계 주소로 이동한 것으로 온체인 데이터에서 확인됐다고 크립토뉴스넷과 인베즈(Invezz)가 전했다. 이는 십수 년을 끌어온 채권자 상환 절차가 서류 단계를 넘어 실제 코인 이동으로 접어들었다는 신호로, 비트스탬프가 오는 7월 25일부터 마운트곡스 채권자에게 암호화폐 분배를 개시한다고 밝힌 일정과 맞물린다고 코인텔레그래프가 보도했다. 관재인의 최종 상환 기한은 지난해 절차 지연을 이유로 2026년 10월 31일까지 연장된 상태다.</p>
  <p class="en">A wallet controlled by the trustee of Mt. Gox, the Japanese exchange that collapsed in 2014, moved 47,228 bitcoin (BTC) to addresses linked to Bitstamp on July 6, according to on-chain data cited by Cryptonews.net and Invezz. It is a signal that a creditor-repayment process dragging on for more than a decade has moved past paperwork into actual coin movement — dovetailing, Cointelegraph reported, with Bitstamp's stated plan to begin distributing crypto to Mt. Gox creditors on July 25. The trustee's final repayment deadline was extended last year, citing procedural delays, to October 31, 2026.</p>
  <p class="ja">2014年に破綻した日本の取引所マウントゴックス(Mt. Gox)の管財人ウォレットから7月6日、4万7228ビットコイン(BTC)がビットスタンプ(Bitstamp)関連アドレスへ移動したことがオンチェーンデータで確認されたと、Cryptonews.netとInvezzが伝えた。これは十数年を引きずってきた債権者返済手続きが書類段階を越え実際のコイン移動に入った signal であり、ビットスタンプが7月25日からマウントゴックス債権者への暗号資産分配を開始すると表明した日程とかみ合うと、コインテレグラフが報じた。管財人の最終返済期限は昨年、手続き遅延を理由に2026年10月31日まで延長されている。</p>

  <p class="es">Una billetera controlada por el administrador judicial de Mt. Gox, la casa de cambio japonesa que colapsó en 2014, movió 47.228 bitcoines (BTC) a direcciones vinculadas a Bitstamp el 6 de julio, según datos on-chain citados por Cryptonews.net e Invezz. Es una señal de que un proceso de reembolso a acreedores que se ha prolongado durante más de una década ha pasado del papeleo al movimiento real de monedas, encajando —según informó Cointelegraph— con el plan declarado de Bitstamp de comenzar a distribuir cripto a los acreedores de Mt. Gox el 25 de julio. El plazo final de reembolso del administrador se amplió el año pasado, alegando demoras procesales, hasta el 31 de octubre de 2026.</p>
  <p class="de">Eine vom Treuhänder von Mt. Gox — der 2014 zusammengebrochenen japanischen Börse — kontrollierte Wallet bewegte am 6. Juli 47.228 Bitcoin (BTC) an mit Bitstamp verknüpfte Adressen, wie On-Chain-Daten laut Cryptonews.net und Invezz zeigen. Es ist ein Signal, dass ein seit über einem Jahrzehnt schleppender Gläubiger-Rückzahlungsprozess vom Papierkram zur tatsächlichen Coin-Bewegung übergegangen ist — passend, wie Cointelegraph berichtete, zu Bitstamps erklärtem Plan, ab dem 25. Juli mit der Verteilung von Krypto an Mt.-Gox-Gläubiger zu beginnen. Die endgültige Rückzahlungsfrist des Treuhänders wurde letztes Jahr wegen Verfahrensverzögerungen bis zum 31. Oktober 2026 verlängert.</p>
  <p class="fr">Un portefeuille contrôlé par l'administrateur judiciaire de Mt. Gox, la plateforme japonaise qui s'est effondrée en 2014, a transféré 47 228 bitcoins (BTC) vers des adresses liées à Bitstamp le 6 juillet, selon des données on-chain citées par Cryptonews.net et Invezz. Il s'agit d'un signal indiquant qu'un processus de remboursement des créanciers qui traîne depuis plus d'une décennie est passé du stade administratif à un mouvement de coins bien réel — coïncidant, selon Cointelegraph, avec le plan annoncé par Bitstamp de commencer à distribuer des cryptomonnaies aux créanciers de Mt. Gox le 25 juillet. Le délai final de remboursement de l'administrateur a été prolongé l'an dernier, en raison de retards de procédure, jusqu'au 31 octobre 2026.</p>
  <p class="pt">Uma carteira controlada pelo administrador judicial da Mt. Gox, a corretora japonesa que colapsou em 2014, transferiu 47.228 bitcoins (BTC) para endereços vinculados à Bitstamp em 6 de julho, segundo dados on-chain citados pela Cryptonews.net e pela Invezz. É um sinal de que um processo de reembolso de credores que se arrasta há mais de uma década avançou da fase burocrática para a movimentação real de moedas — coincidindo, segundo a Cointelegraph, com o plano declarado da Bitstamp de começar a distribuir criptomoedas aos credores da Mt. Gox em 25 de julho. O prazo final de reembolso do administrador foi prorrogado no ano passado, devido a atrasos processuais, até 31 de outubro de 2026.</p>
  <p class="tr">2014 yılında çöken Japon borsası Mt. Gox'un yediemin cüzdanı, 6 Temmuz'da Cryptonews.net ve Invezz tarafından aktarılan zincir üstü verilere göre 47.228 bitcoin'i (BTC) Bitstamp ile bağlantılı adreslere aktardı. Bu, on yılı aşkın süredir uzayan alacaklı geri ödeme sürecinin evrak aşamasını geride bırakıp gerçek coin hareketine geçtiğinin bir işareti; Cointelegraph'ın bildirdiğine göre bu durum, Bitstamp'in Mt. Gox alacaklılarına 25 Temmuz'da kripto para dağıtmaya başlayacağını açıkladığı planla da örtüşüyor. Yedieminin nihai geri ödeme süresi, geçen yıl usul gecikmeleri gerekçesiyle 31 Ekim 2026'ya kadar uzatılmıştı.</p>
  <p class="vi">Một ví do người quản lý tài sản phá sản của Mt. Gox, sàn giao dịch Nhật Bản sụp đổ năm 2014, kiểm soát đã chuyển 47.228 bitcoin (BTC) đến các địa chỉ liên kết với Bitstamp vào ngày 6 tháng 7, theo dữ liệu on-chain được Cryptonews.net và Invezz trích dẫn. Đây là tín hiệu cho thấy quá trình hoàn trả cho chủ nợ kéo dài hơn một thập kỷ đã vượt qua giai đoạn giấy tờ để bước vào việc di chuyển coin thực sự — trùng khớp, theo Cointelegraph đưa tin, với kế hoạch đã công bố của Bitstamp về việc bắt đầu phân phối tiền mã hóa cho các chủ nợ của Mt. Gox vào ngày 25 tháng 7. Thời hạn hoàn trả cuối cùng của người quản lý tài sản đã được gia hạn vào năm ngoái, với lý do chậm trễ thủ tục, đến ngày 31 tháng 10 năm 2026.</p>

  <h2 class="ko">채권자 상환은 어떻게 굴러가는가 — 온체인에 찍힌 신호</h2>
  <h2 class="en">How the repayment machine works — a signal etched on-chain</h2>
  <h2 class="ja">債権者返済はどう回るのか — オンチェーンに刻まれた signal</h2>
  <h2 class="es">Cómo funciona la maquinaria de reembolso — una señal grabada on-chain</h2>
  <h2 class="de">Wie die Rückzahlungsmaschinerie funktioniert — ein On-Chain-Signal</h2>
  <h2 class="fr">Comment fonctionne la machine de remboursement — un signal gravé on-chain</h2>
  <h2 class="pt">Como funciona a máquina de reembolso — um sinal gravado on-chain</h2>
  <h2 class="tr">Geri ödeme makinesi nasıl işliyor — zincir üzerine kazınan bir sinyal</h2>
  <h2 class="vi">Cỗ máy hoàn trả vận hành ra sao — một tín hiệu khắc trên chuỗi</h2>
  <p class="ko">마운트곡스 상환은 관재인이 직접 채권자 수만 명의 지갑으로 코인을 뿌리는 방식이 아니라, 크라켄(Kraken)·비트스탬프 같은 지정 거래소를 경유하는 구조다. 관재인이 대량의 BTC를 거래소 연계 지갑으로 옮기면, 거래소가 이를 개별 채권자 계정에 배분한다. 따라서 이번 4만7228 BTC의 거래소 유입은 곧바로 시장 매도로 해석해서는 안 된다. 온체인 분석가들이 이런 이동을 예민하게 지켜보는 이유는, 거래소 지갑에 쌓인 코인이 '매도 가능 상태'로 한 단계 가까워졌다는 점 때문이지, 이동 자체가 매도는 아니기 때문이다.</p>
  <p class="en">Mt. Gox repayments do not work by the trustee spraying coins directly into tens of thousands of creditor wallets; they route through designated exchanges such as Kraken and Bitstamp. The trustee moves a large tranche of BTC to an exchange-linked wallet, and the exchange then allocates it to individual creditor accounts. This 47,228-BTC inflow to an exchange should therefore not be read as an immediate market sale. On-chain analysts watch such moves closely because coins piling up in an exchange wallet have stepped one notch closer to a "sellable state" — not because the movement itself is a sale.</p>
  <p class="ja">マウントゴックスの返済は、管財人が数万人の債権者ウォレットへ直接コインを撒く方式ではなく、クラーケン(Kraken)・ビットスタンプなど指定取引所を経由する構造だ。管財人が大量のBTCを取引所関連ウォレットへ移すと、取引所がそれを個々の債権者口座に配分する。したがって今回の4万7228 BTCの取引所流入を、ただちに市場売却と解釈してはならない。オンチェーン分析家がこうした移動を敏感に見るのは、取引所ウォレットに積み上がったコインが「売却可能な状態」へ一段近づいたためであり、移動そのものが売却だからではない。</p>

  <p class="es">Los reembolsos de Mt. Gox no funcionan con el administrador rociando monedas directamente en decenas de miles de billeteras de acreedores; se canalizan a través de casas de cambio designadas como Kraken y Bitstamp. El administrador mueve un gran tramo de BTC a una billetera vinculada a la casa de cambio, y esta lo asigna luego a las cuentas individuales de los acreedores. Por tanto, esta entrada de 47.228 BTC a una casa de cambio no debe leerse como una venta inmediata en el mercado. Los analistas on-chain vigilan de cerca estos movimientos porque las monedas que se acumulan en una billetera de exchange han dado un paso más hacia un "estado vendible" — no porque el movimiento en sí sea una venta.</p>
  <p class="de">Mt.-Gox-Rückzahlungen funktionieren nicht so, dass der Treuhänder Coins direkt in Zehntausende Gläubiger-Wallets streut; sie laufen über benannte Börsen wie Kraken und Bitstamp. Der Treuhänder bewegt eine große BTC-Tranche in eine börsenverknüpfte Wallet, und die Börse verteilt sie dann auf einzelne Gläubigerkonten. Dieser Zufluss von 47.228 BTC an eine Börse ist daher nicht als sofortiger Marktverkauf zu lesen. On-Chain-Analysten beobachten solche Bewegungen genau, weil in einer Börsen-Wallet aufgetürmte Coins dem „verkaufsfähigen Zustand" eine Stufe nähergekommen sind — nicht weil die Bewegung selbst ein Verkauf ist.</p>
  <p class="fr">Les remboursements de Mt. Gox ne fonctionnent pas en dispersant directement des coins dans les portefeuilles de dizaines de milliers de créanciers ; ils transitent par des plateformes désignées telles que Kraken et Bitstamp. L'administrateur transfère une importante tranche de BTC vers un portefeuille lié à une plateforme, laquelle la répartit ensuite sur les comptes individuels des créanciers. Cet afflux de 47 228 BTC vers une plateforme ne doit donc pas être interprété comme une vente immédiate sur le marché. Les analystes on-chain surveillent de près ces mouvements car les coins qui s'accumulent dans le portefeuille d'une plateforme se rapprochent d'un cran d'un « état vendable » — non parce que le mouvement lui-même constitue une vente.</p>
  <p class="pt">Os reembolsos da Mt. Gox não funcionam com o administrador espalhando moedas diretamente em dezenas de milhares de carteiras de credores; eles passam por corretoras designadas como a Kraken e a Bitstamp. O administrador transfere um grande lote de BTC para uma carteira vinculada a uma corretora, que então o distribui às contas individuais dos credores. Esse influxo de 47.228 BTC para uma corretora, portanto, não deve ser interpretado como uma venda imediata no mercado. Analistas on-chain observam atentamente esses movimentos porque as moedas acumuladas na carteira de uma corretora avançaram um passo mais perto de um "estado vendável" — não porque o movimento em si seja uma venda.</p>
  <p class="tr">Mt. Gox geri ödemeleri, yediminin coinleri doğrudan on binlerce alacaklı cüzdanına saçması şeklinde işlemez; bunlar Kraken ve Bitstamp gibi belirlenmiş borsalar üzerinden yönlendirilir. Yediemin büyük bir BTC dilimini borsayla bağlantılı bir cüzdana taşır, borsa da bunu bireysel alacaklı hesaplarına dağıtır. Bu nedenle borsaya giren 47.228 BTC'lik bu akış, ani bir piyasa satışı olarak okunmamalıdır. Zincir üstü analistler bu tür hareketleri yakından izler; çünkü bir borsa cüzdanında biriken coinler "satılabilir duruma" bir adım daha yaklaşmıştır — hareketin kendisi bir satış olduğu için değil.</p>
  <p class="vi">Việc hoàn trả của Mt. Gox không diễn ra theo cách người quản lý tài sản rải coin trực tiếp vào hàng chục nghìn ví của chủ nợ; chúng được định tuyến qua các sàn giao dịch được chỉ định như Kraken và Bitstamp. Người quản lý tài sản chuyển một lượng lớn BTC đến ví liên kết với sàn giao dịch, sau đó sàn giao dịch phân bổ số đó cho từng tài khoản chủ nợ. Do đó, dòng vào 47.228 BTC này vào một sàn giao dịch không nên được hiểu là một đợt bán ra thị trường ngay lập tức. Các nhà phân tích on-chain theo dõi sát những động thái như vậy vì lượng coin chất đống trong ví của sàn giao dịch đã tiến thêm một bước gần hơn tới "trạng thái có thể bán" — chứ không phải vì bản thân việc di chuyển đó là một đợt bán.</p>

  <p class="ko">규모의 맥락도 중요하다. 마운트곡스 관재단은 파산 절차 과정에서 약 14만 BTC를 회수해 채권자 상환 재원으로 삼아 왔고, 2024년 7월부터 크라켄·비트스탬프를 통해 실제 분배를 시작했다. 이후 약 1만9500명의 채권자가 분배를 받았으며, 여전히 약 3만4500 BTC가 회생신탁에 남아 있는 것으로 전해진다. 이번 이동분은 남은 신탁 물량의 상당 부분을 한 번에 거래소로 옮긴 것으로, 10월 말 기한을 앞두고 상환 절차가 최종 국면에 진입했음을 시사한다.</p>
  <p class="en">Scale matters for context. Through the bankruptcy process the Mt. Gox estate recovered roughly 140,000 BTC to fund creditor repayments, and it began actual distributions via Kraken and Bitstamp in July 2024. Since then some 19,500 creditors have received distributions, and roughly 34,500 BTC is reported still to sit in the rehabilitation trust. This transfer moved a substantial share of the remaining trust holdings to an exchange in a single stroke, suggesting that — with the end-of-October deadline ahead — the repayment process has entered its final phase.</p>
  <p class="ja">規模の文脈も重要だ。マウントゴックス管財団は破産手続きの過程で約14万BTCを回収して債権者返済の原資とし、2024年7月からクラーケン・ビットスタンプを通じて実際の分配を始めた。以降、約1万9500人の債権者が分配を受け、なお約3万4500 BTCが再生信託に残っていると伝えられる。今回の移動分は残る信託物量の相当部分を一度に取引所へ移したもので、10月末の期限を前に返済手続きが最終局面に入ったことを示唆する。</p>

  <p class="es">La escala importa para el contexto. A través del proceso de quiebra, la masa de Mt. Gox recuperó unos 140.000 BTC para financiar los reembolsos a acreedores, y comenzó las distribuciones reales vía Kraken y Bitstamp en julio de 2024. Desde entonces, unos 19.500 acreedores han recibido distribuciones, y se informa que aún quedan unos 34.500 BTC en el fideicomiso de rehabilitación. Esta transferencia movió una parte sustancial de las tenencias restantes del fideicomiso a una casa de cambio de una sola vez, lo que sugiere que —con el plazo de fin de octubre por delante— el proceso de reembolso ha entrado en su fase final.</p>
  <p class="de">Der Maßstab ist für den Kontext wichtig. Im Insolvenzverfahren trieb die Mt.-Gox-Masse rund 140.000 BTC ein, um die Gläubigerrückzahlungen zu finanzieren, und begann im Juli 2024 mit tatsächlichen Verteilungen über Kraken und Bitstamp. Seither haben rund 19.500 Gläubiger Auszahlungen erhalten, und rund 34.500 BTC sollen noch im Sanierungstreuhandvermögen liegen. Diese Überweisung bewegte einen erheblichen Teil der verbliebenen Treuhandbestände auf einen Schlag an eine Börse, was darauf hindeutet, dass der Rückzahlungsprozess — mit der Frist Ende Oktober vor Augen — in seine Endphase eingetreten ist.</p>
  <p class="fr">L'échelle compte pour la mise en contexte. Au cours de la procédure de faillite, la masse de Mt. Gox a récupéré environ 140 000 BTC pour financer les remboursements aux créanciers, et a entamé les distributions effectives via Kraken et Bitstamp en juillet 2024. Depuis lors, quelque 19 500 créanciers ont reçu des distributions, et environ 34 500 BTC seraient encore détenus dans la fiducie de réhabilitation. Ce transfert a déplacé d'un seul coup une part substantielle des avoirs restants de la fiducie vers une plateforme, suggérant que — à l'approche de l'échéance de fin octobre — le processus de remboursement est entré dans sa phase finale.</p>
  <p class="pt">A escala importa para o contexto. Ao longo do processo de falência, a massa falida da Mt. Gox recuperou cerca de 140.000 BTC para financiar os reembolsos aos credores, e começou as distribuições efetivas via Kraken e Bitstamp em julho de 2024. Desde então, cerca de 19.500 credores receberam distribuições, e cerca de 34.500 BTC ainda estariam no fundo de recuperação. Essa transferência moveu, de uma só vez, uma parcela substancial das participações remanescentes do fundo para uma corretora, sugerindo que — com o prazo final de outubro se aproximando — o processo de reembolso entrou em sua fase final.</p>
  <p class="tr">Bağlam için ölçek önemlidir. İflas süreci boyunca Mt. Gox tasfiye kurumu, alacaklı geri ödemelerini finanse etmek üzere yaklaşık 140.000 BTC geri kazandı ve Temmuz 2024'te Kraken ve Bitstamp üzerinden fiili dağıtımlara başladı. O zamandan bu yana yaklaşık 19.500 alacaklı dağıtım aldı ve yaklaşık 34.500 BTC'nin hâlâ iyileştirme tröstünde durduğu bildiriliyor. Bu transfer, kalan tröst varlıklarının önemli bir kısmını tek seferde bir borsaya taşıyarak, Ekim sonundaki son tarih yaklaşırken geri ödeme sürecinin son aşamasına girdiğini düşündürüyor.</p>
  <p class="vi">Quy mô đóng vai trò quan trọng để đặt trong bối cảnh. Trong quá trình phá sản, tài sản của Mt. Gox đã thu hồi khoảng 140.000 BTC để tài trợ cho việc hoàn trả chủ nợ, và bắt đầu phân phối thực tế qua Kraken và Bitstamp vào tháng 7 năm 2024. Kể từ đó, khoảng 19.500 chủ nợ đã nhận được phân phối, và khoảng 34.500 BTC được cho là vẫn còn nằm trong quỹ tín thác phục hồi. Đợt chuyển này đã dịch chuyển một phần đáng kể lượng nắm giữ còn lại của quỹ tín thác sang một sàn giao dịch chỉ trong một lần, cho thấy rằng — trước thời hạn cuối tháng 10 — quá trình hoàn trả đã bước vào giai đoạn cuối cùng.</p>

  <div class="ko">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">마운트곡스 회생신탁: 회수 → 분배 → 잔여 (BTC)</text>
    <g font-family="sans-serif">
      <text x="20" y="70" fill="#a1a1aa" font-size="13">2024년 7월 분배 개시 이후 남은 신탁 물량이 거래소로 이동하는 국면</text>
      <!-- bars -->
      <rect x="120" y="95" width="480" height="46" rx="6" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
      <text x="130" y="123" fill="#38bdf8" font-size="14" font-weight="700">회수 총량 약 140,000</text>
      <text x="20" y="123" fill="#e4e4e7" font-size="13">회수</text>

      <rect x="120" y="160" width="118" height="46" rx="6" fill="#1c1c1f" stroke="#4ade80" stroke-width="1.5"/>
      <text x="130" y="188" fill="#4ade80" font-size="14" font-weight="700">잔여 약 34,500</text>
      <text x="20" y="188" fill="#e4e4e7" font-size="13">신탁 잔여</text>

      <rect x="120" y="225" width="162" height="46" rx="6" fill="#1c1c1f" stroke="#fbbf24" stroke-width="1.5"/>
      <text x="130" y="253" fill="#fbbf24" font-size="14" font-weight="700">이번 이동 47,228 → 비트스탬프</text>
      <text x="20" y="253" fill="#e4e4e7" font-size="13">최근 이동</text>

      <line x1="120" y1="300" x2="600" y2="300" stroke="#3f3f46" stroke-width="1"/>
      <text x="120" y="325" fill="#71717a" font-size="13">2024.7 분배 개시</text>
      <text x="330" y="325" fill="#71717a" font-size="13">채권자 약 19,500명 수령</text>
      <text x="120" y="352" fill="#71717a" font-size="13">비트스탬프 분배 개시: 7.25</text>
      <text x="380" y="352" fill="#71717a" font-size="13">상환 기한: 2026.10.31</text>
      <text x="120" y="382" fill="#52525b" font-size="12">※ 수치는 크립토뉴스넷·인베즈·코인텔레그래프 보도 기준 근사치. 막대 길이는 개념적 비교.</text>
    </g>
  </svg>
  </div>
  <div class="en fr pt tr vi">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Mt. Gox rehabilitation trust: recovered → distributed → remaining (BTC)</text>
    <g font-family="sans-serif">
      <text x="20" y="70" fill="#a1a1aa" font-size="13">Post-July-2024 phase: remaining trust holdings moving to an exchange</text>
      <rect x="150" y="95" width="450" height="46" rx="6" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
      <text x="160" y="123" fill="#38bdf8" font-size="14" font-weight="700">Total recovered ~140,000</text>
      <text x="20" y="123" fill="#e4e4e7" font-size="13">Recovered</text>

      <rect x="150" y="160" width="111" height="46" rx="6" fill="#1c1c1f" stroke="#4ade80" stroke-width="1.5"/>
      <text x="160" y="188" fill="#4ade80" font-size="14" font-weight="700">~34,500 left</text>
      <text x="20" y="188" fill="#e4e4e7" font-size="13">In trust</text>

      <rect x="150" y="225" width="152" height="46" rx="6" fill="#1c1c1f" stroke="#fbbf24" stroke-width="1.5"/>
      <text x="160" y="253" fill="#fbbf24" font-size="14" font-weight="700">47,228 moved → Bitstamp</text>
      <text x="20" y="253" fill="#e4e4e7" font-size="13">Recent move</text>

      <line x1="150" y1="300" x2="600" y2="300" stroke="#3f3f46" stroke-width="1"/>
      <text x="150" y="325" fill="#71717a" font-size="13">Jul 2024: distributions begin</text>
      <text x="400" y="325" fill="#71717a" font-size="13">~19,500 creditors paid</text>
      <text x="150" y="352" fill="#71717a" font-size="13">Bitstamp payouts start: Jul 25</text>
      <text x="410" y="352" fill="#71717a" font-size="13">Deadline: Oct 31, 2026</text>
      <text x="150" y="382" fill="#52525b" font-size="12">Figures approximate per Cryptonews.net, Invezz, Cointelegraph. Bar lengths conceptual.</text>
    </g>
  </svg>
  </div>
  <div class="ja">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">マウントゴックス再生信託: 回収 → 分配 → 残余 (BTC)</text>
    <g font-family="sans-serif">
      <text x="20" y="70" fill="#a1a1aa" font-size="13">2024年7月の分配開始後、残る信託物量が取引所へ移動する局面</text>
      <rect x="130" y="95" width="470" height="46" rx="6" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
      <text x="140" y="123" fill="#38bdf8" font-size="14" font-weight="700">回収総量 約140,000</text>
      <text x="20" y="123" fill="#e4e4e7" font-size="13">回収</text>

      <rect x="130" y="160" width="116" height="46" rx="6" fill="#1c1c1f" stroke="#4ade80" stroke-width="1.5"/>
      <text x="140" y="188" fill="#4ade80" font-size="14" font-weight="700">残余 約34,500</text>
      <text x="20" y="188" fill="#e4e4e7" font-size="13">信託残余</text>

      <rect x="130" y="225" width="160" height="46" rx="6" fill="#1c1c1f" stroke="#fbbf24" stroke-width="1.5"/>
      <text x="140" y="253" fill="#fbbf24" font-size="14" font-weight="700">今回移動 47,228 → Bitstamp</text>
      <text x="20" y="253" fill="#e4e4e7" font-size="13">直近移動</text>

      <line x1="130" y1="300" x2="600" y2="300" stroke="#3f3f46" stroke-width="1"/>
      <text x="130" y="325" fill="#71717a" font-size="13">2024.7 分配開始</text>
      <text x="360" y="325" fill="#71717a" font-size="13">債権者 約19,500人が受領</text>
      <text x="130" y="352" fill="#71717a" font-size="13">Bitstamp分配開始: 7.25</text>
      <text x="390" y="352" fill="#71717a" font-size="13">返済期限: 2026.10.31</text>
      <text x="130" y="382" fill="#52525b" font-size="12">※ 数値はCryptonews.net・Invezz・Cointelegraph報道の近似値。棒の長さは概念的比較。</text>
    </g>
  </svg>
  </div>
  <div class="es">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Fideicomiso Mt. Gox: recuperado → distribuido → restante (BTC)</text>
    <g font-family="sans-serif">
      <text x="20" y="70" fill="#a1a1aa" font-size="13">Fase posterior a julio de 2024: el saldo del fideicomiso se mueve a un exchange</text>
      <rect x="150" y="95" width="450" height="46" rx="6" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
      <text x="160" y="123" fill="#38bdf8" font-size="14" font-weight="700">Recuperado ~140,000</text>
      <text x="20" y="123" fill="#e4e4e7" font-size="13">Recuper.</text>

      <rect x="150" y="160" width="111" height="46" rx="6" fill="#1c1c1f" stroke="#4ade80" stroke-width="1.5"/>
      <text x="160" y="188" fill="#4ade80" font-size="14" font-weight="700">~34,500 restan</text>
      <text x="20" y="188" fill="#e4e4e7" font-size="13">En fideic.</text>

      <rect x="150" y="225" width="152" height="46" rx="6" fill="#1c1c1f" stroke="#fbbf24" stroke-width="1.5"/>
      <text x="160" y="253" fill="#fbbf24" font-size="14" font-weight="700">47,228 movidos → Bitstamp</text>
      <text x="20" y="253" fill="#e4e4e7" font-size="13">Mov. reciente</text>

      <line x1="150" y1="300" x2="600" y2="300" stroke="#3f3f46" stroke-width="1"/>
      <text x="150" y="325" fill="#71717a" font-size="13">Jul 2024: inician distribuciones</text>
      <text x="150" y="352" fill="#71717a" font-size="13">Bitstamp inicia pagos: 25 jul</text>
      <text x="410" y="352" fill="#71717a" font-size="13">Plazo: 31 oct 2026</text>
      <text x="150" y="382" fill="#52525b" font-size="12">Cifras aproximadas según Cryptonews.net, Invezz, Cointelegraph. Barras conceptuales.</text>
    </g>
  </svg>
  </div>
  <div class="de">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Mt.-Gox-Sanierungstreuhand: eingetrieben → verteilt → verbleibend (BTC)</text>
    <g font-family="sans-serif">
      <text x="20" y="70" fill="#a1a1aa" font-size="13">Phase nach Juli 2024: verbleibende Treuhandbestände wandern an eine Börse</text>
      <rect x="150" y="95" width="450" height="46" rx="6" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
      <text x="160" y="123" fill="#38bdf8" font-size="14" font-weight="700">Eingetrieben ~140,000</text>
      <text x="20" y="123" fill="#e4e4e7" font-size="13">Eingetr.</text>

      <rect x="150" y="160" width="111" height="46" rx="6" fill="#1c1c1f" stroke="#4ade80" stroke-width="1.5"/>
      <text x="160" y="188" fill="#4ade80" font-size="14" font-weight="700">~34,500 übrig</text>
      <text x="20" y="188" fill="#e4e4e7" font-size="13">Im Trust</text>

      <rect x="150" y="225" width="152" height="46" rx="6" fill="#1c1c1f" stroke="#fbbf24" stroke-width="1.5"/>
      <text x="160" y="253" fill="#fbbf24" font-size="14" font-weight="700">47,228 bewegt → Bitstamp</text>
      <text x="20" y="253" fill="#e4e4e7" font-size="13">Jüngst</text>

      <line x1="150" y1="300" x2="600" y2="300" stroke="#3f3f46" stroke-width="1"/>
      <text x="150" y="325" fill="#71717a" font-size="13">Juli 2024: Verteilungen starten</text>
      <text x="150" y="352" fill="#71717a" font-size="13">Bitstamp-Auszahlung: 25. Juli</text>
      <text x="410" y="352" fill="#71717a" font-size="13">Frist: 31. Okt. 2026</text>
      <text x="150" y="382" fill="#52525b" font-size="12">Zahlen ungefähr laut Cryptonews.net, Invezz, Cointelegraph. Balken konzeptionell.</text>
    </g>
  </svg>
  </div>

  <h2 class="ko">'공급 오버행'이라는 오래된 공포, 그리고 2024년의 교훈</h2>
  <h2 class="en">The old fear of a 'supply overhang' — and the lesson of 2024</h2>
  <h2 class="ja">「供給オーバーハング」という古い恐怖、そして2024年の教訓</h2>
  <h2 class="es">El viejo temor a un 'exceso de oferta' — y la lección de 2024</h2>
  <h2 class="de">Die alte Angst vor einem 'Angebotsüberhang' — und die Lektion von 2024</h2>
  <h2 class="fr">La vieille peur d'un « excédent d'offre » — et la leçon de 2024</h2>
  <h2 class="pt">O velho temor de um 'excesso de oferta' — e a lição de 2024</h2>
  <h2 class="tr">Eski 'arz fazlası' korkusu — ve 2024'ün dersi</h2>
  <h2 class="vi">Nỗi sợ cũ về 'tình trạng dư cung' — và bài học năm 2024</h2>
  <p class="ko">마운트곡스 물량이 시장에 부담이라는 우려, 이른바 '공급 오버행(supply overhang)'은 십 년 넘게 반복돼 온 서사다. 논리는 단순하다. 채권자 다수가 비트코인을 2013~2014년 낮은 가격에 사들여 파산에 휘말렸고, 지금 돌려받으면 수십 배 차익을 실현하려 매도할 것이라는 가정이다. 4만7228 BTC는 결코 작은 숫자가 아니다. 그러나 이 서사는 2024년 실전에서 이미 한 차례 시험대에 올랐다. 그해 7월 마운트곡스가 첫 분배를 시작했을 때 시장은 대규모 투매를 우려하며 급락했지만, 실제 매도 압력은 예상보다 훨씬 온건했고 몇 주 만에 낙폭을 대부분 회복했다.</p>
  <p class="en">The worry that Mt. Gox coins weigh on the market — the so-called "supply overhang" — is a narrative repeated for more than a decade. The logic is simple: many creditors bought bitcoin cheaply in 2013–2014, got caught in the bankruptcy, and, on being repaid now, would sell to realize gains of dozens of times over. 47,228 BTC is by no means a small number. But this narrative was already put to the test in practice in 2024. When Mt. Gox began its first distributions that July, the market plunged on fears of mass dumping — yet the actual selling pressure proved far milder than expected, and most of the drop was recovered within a few weeks.</p>
  <p class="ja">マウントゴックス物量が市場の重しだという懸念、いわゆる「供給オーバーハング(supply overhang)」は十年以上繰り返されてきた物語だ。論理は単純だ。債権者の多くはビットコインを2013〜2014年の低価格で買って破綻に巻き込まれ、いま返還されれば数十倍の差益を実現しようと売る、という仮定である。4万7228 BTCは決して小さな数字ではない。しかしこの物語は2024年の実戦ですでに一度試された。同年7月にマウントゴックスが初の分配を始めたとき、市場は大規模投げ売りを懸念して急落したが、実際の売り圧力は予想よりはるかに穏当で、数週間で下げ幅の大半を回復した。</p>

  <p class="es">La preocupación de que las monedas de Mt. Gox pesen sobre el mercado —el llamado "exceso de oferta" (supply overhang)— es una narrativa repetida durante más de una década. La lógica es simple: muchos acreedores compraron bitcoin barato en 2013-2014, quedaron atrapados en la quiebra y, al ser reembolsados ahora, venderían para realizar ganancias de decenas de veces. 47.228 BTC no es en absoluto una cifra pequeña. Pero esta narrativa ya se puso a prueba en la práctica en 2024. Cuando Mt. Gox comenzó sus primeras distribuciones aquel julio, el mercado se desplomó por temor a una venta masiva — pero la presión vendedora real resultó mucho más suave de lo esperado, y la mayor parte de la caída se recuperó en pocas semanas.</p>
  <p class="de">Die Sorge, dass Mt.-Gox-Coins auf dem Markt lasten — der sogenannte „Angebotsüberhang" — ist ein seit über einem Jahrzehnt wiederholtes Narrativ. Die Logik ist einfach: Viele Gläubiger kauften Bitcoin 2013–2014 billig, gerieten in die Insolvenz und würden bei der jetzigen Rückzahlung verkaufen, um Gewinne des Dutzendfachen zu realisieren. 47.228 BTC ist keineswegs eine kleine Zahl. Doch dieses Narrativ wurde 2024 bereits in der Praxis getestet. Als Mt. Gox in jenem Juli mit den ersten Verteilungen begann, stürzte der Markt aus Angst vor Massenabverkäufen ab — doch der tatsächliche Verkaufsdruck erwies sich als weit milder als erwartet, und der Großteil des Rückgangs war binnen weniger Wochen aufgeholt.</p>
  <p class="fr">La crainte que les coins de Mt. Gox ne pèsent sur le marché — le fameux « excédent d'offre » — est un récit répété depuis plus d'une décennie. La logique est simple : de nombreux créanciers ont acheté du bitcoin à bas prix en 2013-2014, se sont retrouvés pris au piège de la faillite et, une fois remboursés aujourd'hui, vendraient pour réaliser des gains de plusieurs dizaines de fois leur mise. 47 228 BTC n'est en aucun cas un chiffre négligeable. Mais ce récit a déjà été mis à l'épreuve en 2024. Lorsque Mt. Gox a entamé ses premières distributions en juillet de cette année-là, le marché a chuté par crainte d'un déversement massif — pourtant, la pression vendeuse réelle s'est révélée bien plus modérée que prévu, et l'essentiel de la baisse a été effacé en quelques semaines.</p>
  <p class="pt">A preocupação de que as moedas da Mt. Gox pesem sobre o mercado — o chamado "excesso de oferta" — é uma narrativa repetida há mais de uma década. A lógica é simples: muitos credores compraram bitcoin barato em 2013-2014, ficaram presos na falência e, ao serem reembolsados agora, venderiam para realizar ganhos de dezenas de vezes o valor investido. 47.228 BTC não é, de forma alguma, um número pequeno. Mas essa narrativa já foi posta à prova na prática em 2024. Quando a Mt. Gox iniciou suas primeiras distribuições naquele julho, o mercado despencou por temores de uma venda maciça — mas a pressão vendedora real mostrou-se muito mais branda do que o esperado, e a maior parte da queda foi recuperada em poucas semanas.</p>
  <p class="tr">Mt. Gox coinlerinin piyasa üzerinde baskı oluşturacağı endişesi — sözde "arz fazlası" — on yılı aşkın süredir tekrarlanan bir anlatı. Mantık basit: birçok alacaklı bitcoin'i 2013-2014'te ucuza satın aldı, iflasa yakalandı ve şimdi geri ödeme yapıldığında onlarca kat kâr elde etmek için satacak. 47.228 BTC kesinlikle küçük bir rakam değil. Ancak bu anlatı 2024'te pratikte zaten bir kez sınandı. Mt. Gox o yılın Temmuz ayında ilk dağıtımlarına başladığında piyasa kitlesel satış korkusuyla sert düştü — ama gerçek satış baskısı beklenenden çok daha ılımlı çıktı ve düşüşün büyük kısmı birkaç hafta içinde telafi edildi.</p>
  <p class="vi">Mối lo ngại rằng số coin của Mt. Gox sẽ đè nặng lên thị trường — cái gọi là "tình trạng dư cung" — là một luận điểm được lặp lại suốt hơn một thập kỷ. Logic rất đơn giản: nhiều chủ nợ đã mua bitcoin với giá rẻ vào năm 2013-2014, bị mắc kẹt trong vụ phá sản, và khi được hoàn trả bây giờ sẽ bán ra để hiện thực hóa khoản lãi gấp hàng chục lần. 47.228 BTC hoàn toàn không phải là một con số nhỏ. Nhưng luận điểm này đã từng được kiểm chứng trong thực tế vào năm 2024. Khi Mt. Gox bắt đầu đợt phân phối đầu tiên vào tháng 7 năm đó, thị trường đã lao dốc vì lo sợ bị bán tháo ồ ạt — nhưng áp lực bán thực tế lại nhẹ hơn nhiều so với dự đoán, và phần lớn mức giảm đã được phục hồi chỉ trong vài tuần.</p>

  <p class="ko">2024년의 교훈은 두 가지 반론을 낳는다. 첫째, 십 년을 기다린 채권자는 정의상 극단적 장기 보유자다. 파산 절차 내내 팔 수 없었던 이들이 반드시 즉시 매도할 것이라 단정하기 어렵고, 상당수 청구권은 이미 펀드에 매각돼 매수자 손에 넘어가 있다. 둘째, 같은 2024년 독일 연방수사청(BKA)이 압류 비트코인 약 5만 개를 몇 주에 걸쳐 시장에 직접 매도했을 때는 실제로 뚜렷한 하방 압력이 나타났다. 두 사건의 차이는 '누가, 어떤 동기로, 얼마나 급하게 파느냐'에 있다. 관재인을 통한 채권자 분배는 매도 시점과 주체가 수만 갈래로 분산되는 반면, 정부의 일괄 매각은 단일 주체가 시한을 두고 쏟아내는 구조다. 이번 이동을 해석할 때도 이 구분이 핵심이다.</p>
  <p class="en">The lesson of 2024 yields two counterarguments. First, creditors who waited a decade are, by definition, extreme long-term holders. Those who could not sell throughout the bankruptcy cannot be assumed to dump immediately, and a substantial share of claims has already been sold to funds and passed into buyers' hands. Second, that same year, when Germany's Federal Criminal Police (BKA) sold roughly 50,000 seized bitcoin directly into the market over a few weeks, distinct downward pressure did appear. The difference between the two events lies in "who sells, with what motive, and how urgently." Creditor distribution through a trustee scatters the timing and the sellers into tens of thousands of strands, whereas a government's bulk sale is a single actor pouring out against a clock. That distinction is again the key to reading this transfer.</p>
  <p class="ja">2024年の教訓は二つの反論を生む。第一に、十年待った債権者は定義上、極端な長期保有者だ。破綻手続きの間ずっと売れなかった彼らが必ず即時売却するとは断じがたく、相当数の請求権はすでにファンドへ売却され買い手の手に渡っている。第二に、同じ2024年、ドイツ連邦刑事庁(BKA)が押収ビットコイン約5万個を数週間にわたり市場へ直接売却したときは、実際に明確な下押し圧力が現れた。二つの事件の違いは「誰が、どんな動機で、どれほど急いで売るか」にある。管財人を通じた債権者分配は売却時点と主体が数万に分散する一方、政府の一括売却は単一主体が期限を切って吐き出す構造だ。今回の移動を解釈する際も、この区分が核心である。</p>

  <p class="es">La lección de 2024 produce dos contraargumentos. Primero, los acreedores que esperaron una década son, por definición, tenedores de larguísimo plazo. No puede asumirse que quienes no pudieron vender durante toda la quiebra vendan de inmediato, y una parte sustancial de las reclamaciones ya se vendió a fondos y pasó a manos de compradores. Segundo, ese mismo año, cuando la Policía Criminal Federal de Alemania (BKA) vendió unos 50.000 bitcoines incautados directamente al mercado en pocas semanas, sí apareció una presión bajista clara. La diferencia entre ambos eventos está en "quién vende, con qué motivo y con qué urgencia". La distribución a acreedores a través de un administrador dispersa el momento y los vendedores en decenas de miles de hilos, mientras que la venta masiva de un gobierno es un único actor vaciando contra un reloj. Esa distinción es de nuevo la clave para leer esta transferencia.</p>
  <p class="de">Die Lektion von 2024 liefert zwei Gegenargumente. Erstens sind Gläubiger, die ein Jahrzehnt gewartet haben, per Definition extreme Langfristhalter. Von denen, die während der gesamten Insolvenz nicht verkaufen konnten, kann man keinen sofortigen Abverkauf annehmen, und ein erheblicher Teil der Forderungen wurde bereits an Fonds verkauft und ging in Käuferhände über. Zweitens trat, als Deutschlands Bundeskriminalamt (BKA) im selben Jahr rund 50.000 beschlagnahmte Bitcoin über einige Wochen direkt in den Markt verkaufte, tatsächlich deutlicher Abwärtsdruck auf. Der Unterschied zwischen beiden Ereignissen liegt darin, „wer mit welchem Motiv und wie dringend verkauft". Die Gläubigerverteilung über einen Treuhänder streut Zeitpunkt und Verkäufer in Zehntausende Stränge, während der Massenverkauf einer Regierung ein einzelner Akteur ist, der gegen eine Uhr ausschüttet. Diese Unterscheidung ist erneut der Schlüssel zum Verständnis dieser Überweisung.</p>
  <p class="fr">La leçon de 2024 fait naître deux contre-arguments. Premièrement, les créanciers qui ont attendu une décennie sont, par définition, des détenteurs de très long terme extrêmes. On ne peut supposer que ceux qui n'ont pas pu vendre pendant toute la durée de la faillite se débarrasseront immédiatement de leurs avoirs, et une part substantielle des créances a déjà été vendue à des fonds et est passée entre les mains d'acheteurs. Deuxièmement, cette même année, lorsque la police criminelle fédérale allemande (BKA) a vendu directement sur le marché environ 50 000 bitcoins saisis sur quelques semaines, une pression baissière nette est bel et bien apparue. La différence entre ces deux événements tient à « qui vend, avec quelle motivation, et avec quelle urgence ». La distribution aux créanciers via un administrateur disperse le calendrier et les vendeurs en dizaines de milliers de fils distincts, tandis que la vente en bloc d'un gouvernement est le fait d'un acteur unique qui écoule ses avoirs contre une échéance. Cette distinction demeure la clé de lecture de ce transfert.</p>
  <p class="pt">A lição de 2024 gera dois contra-argumentos. Primeiro, credores que esperaram uma década são, por definição, detentores de longuíssimo prazo. Não se pode presumir que aqueles que não puderam vender durante toda a falência despejem suas moedas imediatamente, e uma parcela substancial das reivindicações já foi vendida a fundos e passou para as mãos de compradores. Segundo, naquele mesmo ano, quando a Polícia Criminal Federal da Alemanha (BKA) vendeu cerca de 50.000 bitcoins apreendidos diretamente no mercado ao longo de algumas semanas, surgiu de fato uma pressão baixista nítida. A diferença entre os dois eventos está em "quem vende, com que motivação e com que urgência". A distribuição a credores por meio de um administrador dispersa o momento e os vendedores em dezenas de milhares de fios, ao passo que a venda em bloco de um governo é um único agente despejando moedas contra um prazo. Essa distinção é, novamente, a chave para interpretar essa transferência.</p>
  <p class="tr">2024'ün dersi iki karşı argüman doğuruyor. Birincisi, on yıl bekleyen alacaklılar tanım gereği aşırı uzun vadeli yatırımcılardır. İflas boyunca satamayanların hemen ellerindekini boşaltacağı varsayılamaz ve alacakların önemli bir kısmı zaten fonlara satılmış ve alıcıların eline geçmiştir. İkincisi, aynı yıl Almanya Federal Kriminal Polisi (BKA) yaklaşık 50.000 el konulmuş bitcoin'i birkaç hafta boyunca doğrudan piyasaya sattığında, belirgin bir aşağı yönlü baskı gerçekten ortaya çıktı. Bu iki olay arasındaki fark, "kimin, hangi güdüyle ve ne kadar aceleyle sattığında" yatmaktadır. Yediemin aracılığıyla yapılan alacaklı dağıtımı, zamanlamayı ve satıcıları on binlerce farklı kanala dağıtırken, bir hükümetin toplu satışı tek bir aktörün bir son tarihe karşı boşaltma yapmasıdır. Bu ayrım, yine bu transferi yorumlamanın anahtarıdır.</p>
  <p class="vi">Bài học năm 2024 đưa ra hai lập luận phản biện. Thứ nhất, những chủ nợ đã chờ đợi suốt một thập kỷ, theo định nghĩa, là những người nắm giữ cực kỳ dài hạn. Không thể mặc định rằng những người không thể bán trong suốt quá trình phá sản sẽ ngay lập tức bán tháo, và một phần đáng kể các khoản yêu cầu bồi thường đã được bán cho các quỹ và chuyển sang tay người mua. Thứ hai, cũng trong năm đó, khi Cảnh sát Hình sự Liên bang Đức (BKA) bán trực tiếp ra thị trường khoảng 50.000 bitcoin bị tịch thu trong vài tuần, áp lực giảm giá rõ rệt đã thực sự xuất hiện. Sự khác biệt giữa hai sự kiện này nằm ở "ai bán, với động cơ gì và khẩn cấp đến mức nào." Việc phân phối cho chủ nợ thông qua người quản lý tài sản phân tán thời điểm và người bán thành hàng chục nghìn nhánh nhỏ, trong khi việc bán số lượng lớn của chính phủ là một chủ thể duy nhất xả hàng theo một thời hạn. Sự khác biệt đó một lần nữa là chìa khóa để giải mã đợt chuyển này.</p>

  <h2 class="ko">지켜볼 지점 — 비트스탬프 지갑과 10월 31일</h2>
  <h2 class="en">What to watch — the Bitstamp wallet and October 31</h2>
  <h2 class="ja">注視すべき点 — Bitstampウォレットと10月31日</h2>
  <h2 class="es">Qué vigilar — la billetera de Bitstamp y el 31 de octubre</h2>
  <h2 class="de">Worauf zu achten ist — die Bitstamp-Wallet und der 31. Oktober</h2>
  <h2 class="fr">Ce qu'il faut surveiller — le portefeuille Bitstamp et le 31 octobre</h2>
  <h2 class="pt">O que observar — a carteira da Bitstamp e o dia 31 de outubro</h2>
  <h2 class="tr">Nelere dikkat edilmeli — Bitstamp cüzdanı ve 31 Ekim</h2>
  <h2 class="vi">Những điều cần theo dõi — ví Bitstamp và ngày 31 tháng 10</h2>
  <p class="ko">투자자가 실질적으로 주시해야 할 것은 가격 자체가 아니라 흐름의 다음 단계다. 첫째, 비트스탬프 연계 지갑에 들어간 코인이 실제 채권자 계정으로 분배된 뒤 얼마나 매도로 이어지는지다. 온체인에서 거래소 유입 자체는 이미 관찰됐으므로, 다음 신호는 '거래소 잔고 증가 → 실제 출금·매도 전환' 여부다. 둘째, 7월 25일 분배 개시와 10월 31일 최종 기한이라는 두 날짜다. 남은 약 3만4500 BTC가 이 기간에 집중 분배될 경우, 시장은 단일 사건이 아니라 수 주에 걸친 완만한 물량으로 흡수할 가능성이 크다.</p>
  <p class="en">What investors should really monitor is not price itself but the next stage of the flow. First, once the coins that entered the Bitstamp-linked wallet are distributed to actual creditor accounts, how much of it converts into selling. The exchange inflow itself has already been observed on-chain, so the next signal is whether "rising exchange balances turn into actual withdrawals and sales." Second, the two dates: the July 25 start of distributions and the October 31 final deadline. If the remaining roughly 34,500 BTC is distributed intensively over this window, the market is more likely to absorb it as a gentle supply spread over weeks rather than a single event.</p>
  <p class="ja">投資家が実質的に注視すべきは価格そのものではなく、フローの次の段階だ。第一に、Bitstamp関連ウォレットに入ったコインが実際の債権者口座へ分配された後、どれほど売却につながるかである。オンチェーンで取引所流入自体はすでに観察されたので、次の signal は「取引所残高の増加 → 実際の出金・売却への転換」の有無だ。第二に、7月25日の分配開始と10月31日の最終期限という二つの日付だ。残る約3万4500 BTCがこの期間に集中分配される場合、市場は単一事件ではなく数週間にわたる緩やかな物量として吸収する公算が大きい。</p>

  <p class="es">Lo que los inversores realmente deben monitorear no es el precio en sí, sino la siguiente etapa del flujo. Primero, una vez que las monedas que entraron en la billetera vinculada a Bitstamp se distribuyan a las cuentas reales de los acreedores, cuánto de ello se convierte en ventas. La entrada al exchange en sí ya se observó on-chain, así que la próxima señal es si "el aumento de saldos del exchange se convierte en retiros y ventas reales". Segundo, las dos fechas: el inicio de distribuciones el 25 de julio y el plazo final del 31 de octubre. Si los aproximadamente 34.500 BTC restantes se distribuyen intensivamente en esta ventana, es más probable que el mercado lo absorba como una oferta suave repartida durante semanas y no como un evento único.</p>
  <p class="de">Was Investoren wirklich beobachten sollten, ist nicht der Preis selbst, sondern die nächste Stufe des Flusses. Erstens: Wie viel davon in Verkäufe umschlägt, sobald die Coins, die in die Bitstamp-verknüpfte Wallet gelangten, an tatsächliche Gläubigerkonten verteilt sind. Der Börsenzufluss selbst wurde bereits on-chain beobachtet, das nächste Signal ist also, ob „steigende Börsenbestände in tatsächliche Abhebungen und Verkäufe umschlagen". Zweitens die beiden Daten: der Verteilungsbeginn am 25. Juli und die Endfrist am 31. Oktober. Werden die verbleibenden rund 34.500 BTC in diesem Fenster intensiv verteilt, dürfte der Markt sie eher als sanftes, über Wochen verteiltes Angebot aufnehmen als in einem einzelnen Ereignis.</p>
  <p class="fr">Ce que les investisseurs devraient réellement surveiller n'est pas le prix lui-même mais la prochaine étape du flux. Premièrement, une fois que les coins entrés dans le portefeuille lié à Bitstamp sont distribués aux comptes réels des créanciers, quelle part se transforme en ventes. L'afflux vers la plateforme a déjà été observé on-chain ; le prochain signal est donc de savoir si « la hausse des soldes de la plateforme se traduit par des retraits et des ventes effectifs ». Deuxièmement, les deux dates : le début des distributions le 25 juillet et l'échéance finale du 31 octobre. Si les quelque 34 500 BTC restants sont distribués intensivement durant cette fenêtre, le marché est plus susceptible de les absorber comme une offre douce étalée sur plusieurs semaines plutôt que comme un événement unique.</p>
  <p class="pt">O que os investidores realmente devem monitorar não é o preço em si, mas a próxima etapa do fluxo. Primeiro, uma vez que as moedas que entraram na carteira vinculada à Bitstamp sejam distribuídas às contas reais dos credores, quanto disso se converte em vendas. A entrada na corretora em si já foi observada on-chain, então o próximo sinal é se "o aumento dos saldos da corretora se transforma em saques e vendas efetivos". Segundo, as duas datas: o início das distribuições em 25 de julho e o prazo final em 31 de outubro. Se os cerca de 34.500 BTC restantes forem distribuídos intensamente nessa janela, é mais provável que o mercado os absorva como uma oferta suave espalhada ao longo de semanas, em vez de um evento único.</p>
  <p class="tr">Yatırımcıların gerçekten izlemesi gereken şey fiyatın kendisi değil, akışın bir sonraki aşamasıdır. Birincisi, Bitstamp bağlantılı cüzdana giren coinler gerçek alacaklı hesaplarına dağıtıldıktan sonra bunun ne kadarının satışa dönüştüğüdür. Borsaya giriş zaten zincir üzerinde gözlemlenmiştir, dolayısıyla bir sonraki sinyal "artan borsa bakiyelerinin gerçek çekim ve satışlara dönüşüp dönüşmediği"dir. İkincisi, iki tarih önemlidir: 25 Temmuz'daki dağıtım başlangıcı ve 31 Ekim'deki son tarih. Kalan yaklaşık 34.500 BTC bu pencerede yoğun biçimde dağıtılırsa, piyasanın bunu tek bir olay olarak değil, haftalara yayılan yumuşak bir arz olarak özümsemesi daha olasıdır.</p>
  <p class="vi">Điều mà nhà đầu tư thực sự nên theo dõi không phải là giá cả mà là giai đoạn tiếp theo của dòng chảy. Thứ nhất, một khi số coin đã vào ví liên kết với Bitstamp được phân phối đến các tài khoản chủ nợ thực sự, bao nhiêu phần trong số đó sẽ chuyển thành hoạt động bán ra. Bản thân dòng vào sàn giao dịch đã được quan sát trên chuỗi, vì vậy tín hiệu tiếp theo là liệu "số dư sàn giao dịch tăng lên có chuyển thành các đợt rút tiền và bán ra thực sự hay không." Thứ hai là hai mốc thời gian: ngày bắt đầu phân phối 25 tháng 7 và thời hạn cuối cùng 31 tháng 10. Nếu khoảng 34.500 BTC còn lại được phân phối dồn dập trong khoảng thời gian này, thị trường nhiều khả năng sẽ hấp thụ nó như một nguồn cung nhẹ nhàng trải dài qua nhiều tuần thay vì một sự kiện đơn lẻ.</p>

  <p class="ko">더 넓게 보면, 마운트곡스 상환의 종결은 비트코인 시장에서 십 년 묵은 구조적 불확실성 하나가 소멸한다는 의미이기도 하다. 그동안 '언젠가 마운트곡스 물량이 쏟아진다'는 막연한 공포는 약세 논리로 상시 인용돼 왔다. 상환이 실제로 마무리되면 이 잠재적 매물 압력은 시장 가격에 이미 반영된 채 사라지며, 남는 것은 실체가 확인된 소화 과정뿐이다. 물론 반대 해석도 가능하다. 회수 물량 전량이 여전히 신탁에 남아 있었다면 그 자체가 잠재적 매물벽이었던 만큼, 최종 분배가 단기적으로는 심리적 부담으로 작용할 수 있다. 결국 관건은 코인의 이동이 아니라, 십 년을 기다린 손들이 실제로 어떤 선택을 하느냐다.</p>
  <p class="en">More broadly, the conclusion of Mt. Gox repayments also means that one decade-old structural uncertainty in the bitcoin market dissolves. For years the vague fear that "someday the Mt. Gox coins will flood in" was routinely cited as bearish logic. Once repayment actually wraps up, this latent supply pressure vanishes — already priced in — leaving only a digestion process whose substance is now known. The opposite reading is possible too: precisely because the entire recovered stash still sat in trust as a potential wall of supply, the final distribution can act as a psychological weight in the short term. In the end, the crux is not the movement of coins but what the hands that waited a decade actually choose to do.</p>
  <p class="ja">より広く見れば、マウントゴックス返済の終結は、ビットコイン市場で十年来の構造的不確実性が一つ消滅することも意味する。その間「いつかマウントゴックス物量が溢れ出す」という漠然とした恐怖は弱気の論理として常時引用されてきた。返済が実際に片づけば、この潜在的な売り圧力はすでに織り込まれたまま消え、残るのは実体の確認された消化過程だけだ。むろん反対の解釈も可能だ。回収物量の全量がなお信託に残っていた以上それ自体が潜在的な売り板だったわけで、最終分配は短期的には心理的重しとして作用しうる。結局、鍵はコインの移動ではなく、十年待った手が実際にどんな選択をするかである。</p>

  <p class="es">En un sentido más amplio, la conclusión de los reembolsos de Mt. Gox también significa que se disuelve una incertidumbre estructural de una década en el mercado de bitcoin. Durante años, el vago temor de que "algún día las monedas de Mt. Gox inundarán el mercado" se citó rutinariamente como lógica bajista. Una vez que el reembolso realmente concluye, esta presión de oferta latente se desvanece —ya descontada—, dejando solo un proceso de digestión cuya sustancia ahora se conoce. También es posible la lectura opuesta: precisamente porque todo el botín recuperado aún estaba en fideicomiso como un muro potencial de oferta, la distribución final puede actuar como un peso psicológico a corto plazo. Al final, el quid no es el movimiento de las monedas, sino lo que las manos que esperaron una década realmente eligen hacer.</p>
  <p class="de">Weiter gefasst bedeutet der Abschluss der Mt.-Gox-Rückzahlungen auch, dass eine jahrzehntealte strukturelle Unsicherheit im Bitcoin-Markt verschwindet. Jahrelang wurde die vage Angst, dass „eines Tages die Mt.-Gox-Coins hereinfluten", routinemäßig als Bärenlogik zitiert. Ist die Rückzahlung tatsächlich abgeschlossen, verschwindet dieser latente Angebotsdruck — bereits eingepreist — und übrig bleibt nur ein Verdauungsprozess, dessen Substanz nun bekannt ist. Auch die gegenteilige Lesart ist möglich: Gerade weil der gesamte eingetriebene Bestand noch als potenzielle Angebotswand im Trust lag, kann die finale Verteilung kurzfristig als psychische Last wirken. Letztlich ist der Kern nicht die Bewegung der Coins, sondern was die Hände, die ein Jahrzehnt warteten, tatsächlich zu tun wählen.</p>
  <p class="fr">Plus largement, l'achèvement des remboursements de Mt. Gox signifie aussi la dissolution d'une incertitude structurelle vieille d'une décennie sur le marché du bitcoin. Pendant des années, la crainte vague qu'« un jour les coins de Mt. Gox déferlent » a été invoquée systématiquement comme argument baissier. Une fois le remboursement effectivement achevé, cette pression d'offre latente s'évanouit — déjà intégrée dans les prix — ne laissant qu'un processus de digestion dont la substance est désormais connue. La lecture inverse est également possible : précisément parce que la totalité du magot récupéré reposait encore en fiducie comme un mur d'offre potentiel, la distribution finale peut peser psychologiquement à court terme. En fin de compte, l'essentiel n'est pas le mouvement des coins, mais ce que choisissent réellement de faire les mains qui ont attendu une décennie.</p>
  <p class="pt">De forma mais ampla, a conclusão dos reembolsos da Mt. Gox também significa que uma incerteza estrutural de uma década se dissolve no mercado de bitcoin. Durante anos, o temor vago de que "algum dia as moedas da Mt. Gox vão inundar o mercado" foi rotineiramente citado como lógica baixista. Uma vez que o reembolso realmente se conclua, essa pressão de oferta latente se dissipa — já precificada — deixando apenas um processo de digestão cuja substância agora é conhecida. A leitura oposta também é possível: precisamente porque todo o montante recuperado ainda estava em fideicomisso como um potencial muro de oferta, a distribuição final pode atuar como um peso psicológico no curto prazo. No fim das contas, o cerne da questão não é a movimentação das moedas, mas o que as mãos que esperaram uma década realmente escolhem fazer.</p>
  <p class="tr">Daha geniş açıdan bakıldığında, Mt. Gox geri ödemelerinin tamamlanması, bitcoin piyasasındaki on yıllık yapısal belirsizliğin de ortadan kalkması anlamına gelir. Yıllarca "bir gün Mt. Gox coinleri piyasaya akacak" şeklindeki belirsiz korku, düşüş yönlü bir mantık olarak rutin biçimde dile getirildi. Geri ödeme fiilen tamamlandığında, bu gizli arz baskısı — zaten fiyatlanmış olarak — ortadan kalkar ve geriye yalnızca içeriği artık bilinen bir sindirim süreci kalır. Tam tersi bir yorum da mümkün: geri kazanılan tüm birikimin hâlâ trüstte, potansiyel bir arz duvarı olarak durması nedeniyle, nihai dağıtım kısa vadede psikolojik bir yük olarak da işlev görebilir. Sonuçta önemli olan coinlerin hareketi değil, on yıl bekleyen ellerin fiilen ne yapmayı seçtiğidir.</p>
  <p class="vi">Nhìn rộng hơn, việc hoàn tất các khoản hoàn trả của Mt. Gox cũng đồng nghĩa với việc một sự bất định mang tính cấu trúc kéo dài cả thập kỷ trên thị trường bitcoin sẽ tan biến. Trong nhiều năm, nỗi lo mơ hồ rằng "một ngày nào đó số coin của Mt. Gox sẽ tràn vào thị trường" đã thường xuyên được viện dẫn như một luận điểm giảm giá. Khi việc hoàn trả thực sự hoàn tất, áp lực nguồn cung tiềm ẩn này sẽ biến mất — vốn đã được phản ánh vào giá — chỉ còn lại một quá trình hấp thụ mà bản chất giờ đây đã được biết rõ. Cách hiểu ngược lại cũng có thể xảy ra: chính vì toàn bộ số tiền thu hồi vẫn nằm trong quỹ tín thác như một bức tường cung tiềm năng, đợt phân phối cuối cùng có thể đóng vai trò như một gánh nặng tâm lý trong ngắn hạn. Suy cho cùng, mấu chốt không nằm ở việc di chuyển coin mà ở việc những bàn tay đã chờ đợi suốt một thập kỷ thực sự sẽ chọn làm gì.</p>

  <div class="box ko">💡 <strong>지금 지켜봐야 할 것:</strong> 4만7228 BTC의 거래소 이동은 매도가 아니라 상환 절차의 진전이다. 핵심 관전 포인트는 (1) 비트스탬프 유입분이 채권자 계정 분배 후 실제 매도로 전환되는지, (2) 7월 25일 분배 개시와 10월 31일 최종 기한 사이의 물량 소화 속도, (3) 십 년 대기 채권자의 매도 성향 대 청구권을 매입한 펀드의 보유 성향이다. 2024년 첫 분배와 독일 BKA의 일괄 매각이 정반대 결과를 낸 사실이 '누가 어떻게 파느냐'가 관건임을 보여준다.</div>
  <div class="box en">💡 <strong>What to watch now:</strong> The 47,228-BTC move to an exchange is progress in the repayment process, not a sale. The key vantage points are (1) whether the Bitstamp inflow converts into actual selling after distribution to creditor accounts, (2) the pace of absorption between the July 25 start and the October 31 deadline, and (3) the selling propensity of decade-waiting creditors versus the holding propensity of funds that bought their claims. That the 2024 first distribution and Germany's BKA bulk sale produced opposite outcomes shows that "who sells, and how" is what matters.</div>
  <div class="box ja">💡 <strong>今後注視すべきこと:</strong> 4万7228 BTCの取引所移動は売却ではなく返済手続きの進展だ。核心的な観点は、(1) Bitstamp流入分が債権者口座への分配後に実際の売却へ転換するか、(2) 7月25日の分配開始と10月31日の最終期限の間の物量消化速度、(3) 十年待った債権者の売却性向 対 請求権を買ったファンドの保有性向だ。2024年の初分配とドイツBKAの一括売却が正反対の結果を出した事実が、「誰がどう売るか」が鍵であることを示す。</div>
  <div class="box es">💡 <strong>Qué vigilar ahora:</strong> El movimiento de 47.228 BTC a un exchange es un avance del proceso de reembolso, no una venta. Los puntos clave son (1) si la entrada a Bitstamp se convierte en ventas reales tras la distribución a las cuentas de acreedores, (2) el ritmo de absorción entre el inicio del 25 de julio y el plazo del 31 de octubre, y (3) la propensión vendedora de los acreedores que esperaron una década frente a la propensión a retener de los fondos que compraron sus reclamaciones. Que la primera distribución de 2024 y la venta masiva de la BKA alemana dieran resultados opuestos muestra que lo que importa es "quién vende y cómo".</div>
  <div class="box de">💡 <strong>Worauf jetzt zu achten ist:</strong> Die Bewegung von 47.228 BTC an eine Börse ist Fortschritt im Rückzahlungsprozess, kein Verkauf. Die zentralen Beobachtungspunkte sind (1) ob der Bitstamp-Zufluss nach der Verteilung an Gläubigerkonten in tatsächliche Verkäufe umschlägt, (2) das Absorptionstempo zwischen dem Start am 25. Juli und der Frist am 31. Oktober, und (3) die Verkaufsneigung der ein Jahrzehnt wartenden Gläubiger gegenüber der Halteneigung der Fonds, die deren Forderungen kauften. Dass die erste Verteilung 2024 und der Massenverkauf des deutschen BKA gegenteilige Ergebnisse brachten, zeigt: Entscheidend ist, „wer wie verkauft".</div>
  <div class="box fr">💡 <strong>Ce qu'il faut surveiller maintenant :</strong> Le transfert de 47 228 BTC vers une plateforme est une avancée du processus de remboursement, pas une vente. Les points de vue clés sont (1) si l'afflux vers Bitstamp se convertit en vente réelle après distribution aux comptes des créanciers, (2) le rythme d'absorption entre le début du 25 juillet et l'échéance du 31 octobre, et (3) la propension à vendre des créanciers ayant attendu une décennie face à la propension à conserver des fonds ayant racheté leurs créances. Le fait que la première distribution de 2024 et la vente en bloc du BKA allemand aient produit des résultats opposés montre que ce qui compte, c'est « qui vend, et comment ».</div>
  <div class="box pt">💡 <strong>O que observar agora:</strong> A transferência de 47.228 BTC para uma corretora é um avanço no processo de reembolso, não uma venda. Os pontos-chave são (1) se o influxo para a Bitstamp se converte em vendas reais após a distribuição às contas dos credores, (2) o ritmo de absorção entre o início em 25 de julho e o prazo de 31 de outubro, e (3) a propensão a vender dos credores que esperaram uma década em comparação com a propensão a reter dos fundos que compraram suas reivindicações. O fato de a primeira distribuição de 2024 e a venda em bloco da BKA alemã terem produzido resultados opostos mostra que o que importa é "quem vende, e como".</div>
  <div class="box tr">💡 <strong>Şimdi izlenmesi gerekenler:</strong> 47.228 BTC'lik borsa transferi bir satış değil, geri ödeme sürecindeki bir ilerlemedir. Kilit bakış açıları şunlardır: (1) Bitstamp'e giren akışın, alacaklı hesaplarına dağıtımdan sonra gerçek satışa dönüşüp dönüşmediği, (2) 25 Temmuz başlangıcı ile 31 Ekim son tarihi arasındaki özümseme hızı ve (3) on yıl bekleyen alacaklıların satış eğilimi ile alacaklarını satın alan fonların elde tutma eğilimi arasındaki denge. 2024'teki ilk dağıtım ile Almanya BKA'sının toplu satışının zıt sonuçlar doğurması, önemli olanın "kimin nasıl sattığı" olduğunu gösteriyor.</div>
  <div class="box vi">💡 <strong>Những điều cần theo dõi lúc này:</strong> Việc chuyển 47.228 BTC đến một sàn giao dịch là bước tiến trong quá trình hoàn trả, không phải một đợt bán ra. Các điểm quan sát then chốt là (1) liệu dòng vào Bitstamp có chuyển thành hoạt động bán ra thực sự sau khi phân phối cho các tài khoản chủ nợ hay không, (2) tốc độ hấp thụ trong khoảng thời gian từ khi bắt đầu ngày 25 tháng 7 đến thời hạn 31 tháng 10, và (3) xu hướng bán ra của các chủ nợ đã chờ đợi một thập kỷ so với xu hướng nắm giữ của các quỹ đã mua lại các khoản yêu cầu bồi thường của họ. Việc đợt phân phối đầu tiên năm 2024 và đợt bán số lượng lớn của BKA Đức mang lại kết quả trái ngược nhau cho thấy điều quan trọng chính là "ai bán, và bán như thế nào".</div>

  <p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: Cryptonews.net('Mt. Gox Wallet Sends 47,228 BTC To Bitstamp'), Invezz·TradingView News, Cointelegraph('Bitstamp will begin Mt. Gox creditor repayments on July 25' 및 test transaction 보도), CoinMarketCap Academy(상환 기한 2026년 10월 31일 연장), Yahoo Finance. 회수·잔여·수령 채권자 수치는 각 매체 보도 기준 근사치이며, 지갑 귀속은 온체인 추적에 기반한 추정이다.</p>
  <p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Cryptonews.net ("Mt. Gox Wallet Sends 47,228 BTC To Bitstamp"), Invezz / TradingView News, Cointelegraph ("Bitstamp will begin Mt. Gox creditor repayments on July 25" and test-transaction reporting), CoinMarketCap Academy (deadline extended to October 31, 2026), and Yahoo Finance. Figures for recovery, remainder and creditors paid are approximate per each outlet; wallet attribution rests on on-chain tracing estimates.</p>
  <p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: Cryptonews.net(「Mt. Gox Wallet Sends 47,228 BTC To Bitstamp」)、Invezz・TradingView News、Cointelegraph(「Bitstamp will begin Mt. Gox creditor repayments on July 25」およびテスト取引の報道)、CoinMarketCap Academy(返済期限2026年10月31日への延長)、Yahoo Finance。回収・残余・受領債権者の数値は各媒体報道の近似値であり、ウォレット帰属はオンチェーン追跡に基づく推定である。</p>
  <p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: Cryptonews.net ("Mt. Gox Wallet Sends 47,228 BTC To Bitstamp"), Invezz / TradingView News, Cointelegraph ("Bitstamp will begin Mt. Gox creditor repayments on July 25" y la cobertura de transacciones de prueba), CoinMarketCap Academy (plazo ampliado al 31 de octubre de 2026) y Yahoo Finance. Las cifras de recuperación, saldo y acreedores pagados son aproximadas según cada medio; la atribución de billeteras se basa en estimaciones de rastreo on-chain.</p>
  <p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: Cryptonews.net („Mt. Gox Wallet Sends 47,228 BTC To Bitstamp"), Invezz / TradingView News, Cointelegraph („Bitstamp will begin Mt. Gox creditor repayments on July 25" sowie Berichterstattung über Testtransaktionen), CoinMarketCap Academy (Frist verlängert bis 31. Oktober 2026) und Yahoo Finance. Zahlen zu Eintreibung, Rest und ausgezahlten Gläubigern sind laut den jeweiligen Medien ungefähr; die Wallet-Zuordnung beruht auf On-Chain-Tracing-Schätzungen.</p>
  <p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : Cryptonews.net (« Mt. Gox Wallet Sends 47,228 BTC To Bitstamp »), Invezz / TradingView News, Cointelegraph (« Bitstamp will begin Mt. Gox creditor repayments on July 25 » et reportages sur les transactions de test), CoinMarketCap Academy (délai prolongé au 31 octobre 2026) et Yahoo Finance. Les chiffres relatifs au recouvrement, au solde restant et aux créanciers payés sont approximatifs selon chaque source ; l'attribution des portefeuilles repose sur des estimations de traçage on-chain.</p>
  <p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: Cryptonews.net ("Mt. Gox Wallet Sends 47,228 BTC To Bitstamp"), Invezz / TradingView News, Cointelegraph ("Bitstamp will begin Mt. Gox creditor repayments on July 25" e reportagens sobre transações de teste), CoinMarketCap Academy (prazo prorrogado para 31 de outubro de 2026) e Yahoo Finance. Os números de recuperação, saldo remanescente e credores pagos são aproximados conforme cada veículo; a atribuição das carteiras baseia-se em estimativas de rastreamento on-chain.</p>
  <p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: Cryptonews.net ("Mt. Gox Wallet Sends 47,228 BTC To Bitstamp"), Invezz / TradingView News, Cointelegraph ("Bitstamp will begin Mt. Gox creditor repayments on July 25" ve test işlemi haberleri), CoinMarketCap Academy (son tarihin 31 Ekim 2026'ya uzatılması) ve Yahoo Finance. Geri kazanım, kalan miktar ve ödeme yapılan alacaklı sayılarına ilişkin rakamlar her bir kaynağa göre yaklaşık değerlerdir; cüzdan atfı zincir üstü izleme tahminlerine dayanmaktadır.</p>
  <p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: Cryptonews.net ("Mt. Gox Wallet Sends 47,228 BTC To Bitstamp"), Invezz / TradingView News, Cointelegraph ("Bitstamp will begin Mt. Gox creditor repayments on July 25" và các bài đưa tin về giao dịch thử nghiệm), CoinMarketCap Academy (thời hạn được gia hạn đến ngày 31 tháng 10 năm 2026), và Yahoo Finance. Các con số về lượng thu hồi, số dư còn lại và số chủ nợ đã được thanh toán là ước tính gần đúng theo từng nguồn tin; việc xác định chủ sở hữu ví dựa trên các ước tính truy vết on-chain.</p>
<?php require __DIR__.'/_footer.php'; ?>
