<?php $slug = 'present-bias-bitcoin-holding-discipline'; require __DIR__.'/_header.php'; ?>

<p class="ko">장기 보유 계획은 대체로 냉정한 순간에 세워진다. 가격이 안정적이고 감정이 잔잔할 때, 투자자는 "사이클이 끝날 때까지 팔지 않겠다"거나 "20% 하락해도 추가 매수만 하겠다"는 규칙을 노트에 적는다. 그런데 정확히 그 규칙이 시험대에 오르는 순간 — 하루 만에 15% 빠지거나, 반대로 하루 만에 20% 뛰는 순간 — 그 규칙은 거의 예외 없이 무너진다. 이 붕괴를 흔히 "의지력 부족"이나 "공포에 굴복했다"는 말로 설명하지만, 행동경제학이 반세기 가까이 축적해온 증거는 다른 그림을 그린다.</p>
<p class="en">Long-term holding plans are usually drafted in calm moments. When the price is stable and emotions are quiet, an investor writes down a rule — "I won't sell until the cycle ends," or "I'll only add on a 20% drop." Then, at precisely the moment that rule is tested — a 15% drop in a single day, or a 20% spike in a single day — it collapses almost without exception. This collapse is usually explained away as "lack of willpower" or "giving in to fear." Nearly fifty years of behavioral economics evidence points to a different picture.</p>
<p class="ja">長期保有計画は、たいてい冷静な瞬間に立てられる。価格が安定し感情が静かなとき、投資家は「サイクルが終わるまで売らない」「20%下落しても買い増しだけする」というルールをノートに書き込む。ところが、まさにそのルールが試される瞬間——一日で15%下落する、あるいは逆に一日で20%急騰する瞬間——にこのルールはほぼ例外なく崩れる。この崩壊はよく「意志力不足」や「恐怖に屈した」という言葉で説明されるが、行動経済学が半世紀近く積み重ねてきた証拠は別の図を描く。</p>
<p class="es">Los planes de mantenimiento a largo plazo suelen redactarse en momentos de calma. Cuando el precio es estable y las emociones están tranquilas, el inversor anota una regla — "no venderé hasta que termine el ciclo" o "solo compraré más si cae un 20%". Entonces, precisamente en el momento en que esa regla se pone a prueba — una caída del 15% en un solo día, o un salto del 20% en un solo día — se derrumba casi sin excepción. Este derrumbe suele explicarse como "falta de fuerza de voluntad" o "ceder ante el miedo". Casi cincuenta años de evidencia de la economía conductual dibujan un panorama distinto.</p>
<p class="de">Pläne für eine langfristige Haltedauer entstehen meist in ruhigen Momenten. Wenn der Preis stabil ist und die Emotionen ruhig sind, schreibt ein Anleger eine Regel auf — „Ich verkaufe nicht, bis der Zyklus endet" oder „Ich kaufe nur bei einem Rückgang von 20% nach." Doch genau in dem Moment, in dem diese Regel auf die Probe gestellt wird — ein Rückgang von 15% an einem einzigen Tag oder ein Anstieg von 20% an einem einzigen Tag — bricht sie fast ausnahmslos zusammen. Dieser Zusammenbruch wird gewöhnlich mit „mangelnder Willenskraft" oder „dem Nachgeben gegenüber der Angst" erklärt. Fast fünfzig Jahre an verhaltensökonomischer Evidenz zeichnen ein anderes Bild.</p>
<p class="fr">Les plans de détention à long terme sont généralement rédigés dans des moments de calme. Lorsque le prix est stable et les émotions apaisées, l'investisseur note une règle — « je ne vendrai pas avant la fin du cycle » ou « je n'achèterai davantage qu'en cas de baisse de 20 % ». Puis, précisément au moment où cette règle est mise à l'épreuve — une chute de 15 % en une seule journée, ou une envolée de 20 % en une seule journée — elle s'effondre presque sans exception. Cet effondrement est généralement attribué à un « manque de volonté » ou à une « capitulation face à la peur ». Près de cinquante ans de preuves en économie comportementale dressent un tableau différent.</p>
<p class="pt">Planos de manutenção de longo prazo costumam ser feitos em momentos de calma. Quando o preço está estável e as emoções estão tranquilas, o investidor anota uma regra — "não vou vender até o ciclo terminar" ou "só vou comprar mais se cair 20%". Então, exatamente no momento em que essa regra é testada — uma queda de 15% em um único dia, ou uma alta de 20% em um único dia — ela desmorona quase sem exceção. Esse colapso costuma ser explicado como "falta de força de vontade" ou "ceder ao medo". Quase cinquenta anos de evidências da economia comportamental desenham um quadro diferente.</p>
<p class="tr">Uzun vadeli tutma planları genellikle sakin anlarda yazılır. Fiyat istikrarlıyken ve duygular durgunken, yatırımcı bir kural yazar — "döngü bitene kadar satmayacağım" ya da "yalnızca %20 düşerse ekleme yapacağım". Ama tam olarak o kural sınandığı anda — tek bir günde %15 düşüş ya da tam tersine tek bir günde %20 sıçrama anında — bu kural neredeyse istisnasız çöker. Bu çöküş genellikle "irade eksikliği" ya da "korkuya teslim olma" olarak açıklanır. Ancak davranışsal ekonominin neredeyse elli yıldır biriktirdiği kanıtlar farklı bir tablo çiziyor.</p>
<p class="vi">Các kế hoạch nắm giữ dài hạn thường được lập ra vào những thời điểm bình tĩnh. Khi giá ổn định và cảm xúc lắng dịu, nhà đầu tư viết ra một quy tắc — "tôi sẽ không bán cho đến khi chu kỳ kết thúc" hoặc "tôi chỉ mua thêm nếu giảm 20%". Nhưng chính xác vào khoảnh khắc quy tắc đó bị thử thách — một cú giảm 15% chỉ trong một ngày, hoặc ngược lại một cú tăng 20% chỉ trong một ngày — quy tắc đó sụp đổ gần như không có ngoại lệ. Sự sụp đổ này thường được giải thích là "thiếu ý chí" hoặc "khuất phục trước nỗi sợ". Nhưng gần năm mươi năm bằng chứng từ kinh tế học hành vi lại vẽ nên một bức tranh khác.</p>

<p class="ko">문제의 핵심은 감정이 아니라 시간을 계산하는 방식 그 자체에 있다. 인간은 미래의 보상과 손실을 지수함수적으로 할인하지 않는다 — 대신 가까운 미래에는 유난히 가파르게, 먼 미래에는 상대적으로 평평하게 할인한다. 이 비대칭이 바로 "쌍곡선 할인(hyperbolic discounting)"이며, 계획을 세운 그때의 나와 그 계획을 실행해야 하는 지금의 나 사이에 벌어지는 간극의 정체다. 이 글은 그 간극이 왜 생기고, 왜 하필 실행의 순간에만 폭발적으로 커지며, 의지력 강화가 아니라 어떤 구조적 장치만이 실제로 이 간극을 좁혀왔는지를 순서대로 짚는다.</p>
<p class="en">The core of the problem isn't emotion — it's the way humans calculate time itself. People don't discount future gains and losses exponentially. Instead, they discount unusually steeply for the near future and comparatively flatly for the distant future. That asymmetry is "hyperbolic discounting," and it is the actual identity of the gap between the self who made the plan and the self who now has to execute it. This piece walks through why that gap forms, why it explodes specifically at the moment of execution, and why only a structural device — not more willpower — has ever actually closed it.</p>
<p class="ja">問題の核心は感情ではなく、時間を計算する方法そのものにある。人間は未来の報酬や損失を指数関数的に割り引かない——代わりに、近い未来には異常に急勾配で、遠い未来には相対的に平坦に割り引く。この非対称性こそが「双曲割引(hyperbolic discounting)」であり、計画を立てたときの自分と、その計画を実行しなければならない今の自分との間に生じる乖離の正体だ。本稿では、その乖離がなぜ生まれるのか、なぜよりによって実行の瞬間にだけ爆発的に大きくなるのか、そして意志力の強化ではなくどんな構造的な仕掛けだけが実際にこの乖離を狭めてきたのかを順に見ていく。</p>
<p class="es">El núcleo del problema no es la emoción, sino la forma misma en que los humanos calculamos el tiempo. Las personas no descuentan las ganancias y pérdidas futuras de forma exponencial. En cambio, descuentan de forma inusualmente pronunciada para el futuro cercano y relativamente plana para el futuro lejano. Esa asimetría es el "descuento hiperbólico", y es la identidad real de la brecha entre el yo que hizo el plan y el yo que ahora debe ejecutarlo. Este artículo recorre por qué se forma esa brecha, por qué estalla precisamente en el momento de la ejecución, y por qué solo un dispositivo estructural —no más fuerza de voluntad— la ha cerrado realmente alguna vez.</p>
<p class="de">Der Kern des Problems liegt nicht in der Emotion, sondern in der Art und Weise, wie Menschen Zeit überhaupt berechnen. Menschen diskontieren zukünftige Gewinne und Verluste nicht exponentiell. Stattdessen diskontieren sie für die nahe Zukunft ungewöhnlich steil und für die ferne Zukunft vergleichsweise flach. Diese Asymmetrie ist das „hyperbolische Diskontieren", und sie ist die eigentliche Identität der Kluft zwischen dem Ich, das den Plan gemacht hat, und dem Ich, das ihn jetzt ausführen muss. Dieser Beitrag geht der Reihe nach durch, warum diese Kluft entsteht, warum sie ausgerechnet im Moment der Ausführung explosionsartig wächst, und warum allein eine strukturelle Vorrichtung — nicht mehr Willenskraft — sie je tatsächlich verkleinert hat.</p>
<p class="fr">Le cœur du problème n'est pas l'émotion, mais la manière même dont les humains calculent le temps. Les gens n'actualisent pas les gains et pertes futurs de façon exponentielle. Ils actualisent au contraire de façon anormalement abrupte pour l'avenir proche et relativement plate pour l'avenir lointain. Cette asymétrie est « l'actualisation hyperbolique », et c'est la véritable identité de l'écart entre le moi qui a fait le plan et le moi qui doit maintenant l'exécuter. Cet article détaille pourquoi cet écart se forme, pourquoi il explose précisément au moment de l'exécution, et pourquoi seul un dispositif structurel — pas davantage de volonté — l'a jamais véritablement réduit.</p>
<p class="pt">O cerne do problema não é a emoção, mas a própria forma como os humanos calculam o tempo. As pessoas não descontam ganhos e perdas futuros de forma exponencial. Em vez disso, descontam de modo anormalmente acentuado para o futuro próximo e relativamente plano para o futuro distante. Essa assimetria é o "desconto hiperbólico", e é a verdadeira identidade da lacuna entre o eu que fez o plano e o eu que agora precisa executá-lo. Este artigo percorre por que essa lacuna se forma, por que ela explode justamente no momento da execução, e por que somente um dispositivo estrutural — não mais força de vontade — de fato já a reduziu.</p>
<p class="tr">Sorunun özü duygu değil, insanların zamanı hesaplama biçiminin ta kendisidir. İnsanlar gelecekteki kazanç ve kayıpları üstel biçimde iskonto etmez. Bunun yerine, yakın gelecek için alışılmadık derecede dik, uzak gelecek için ise nispeten düz bir şekilde iskonto ederler. Bu asimetri "hiperbolik iskonto"dur ve planı yapan ben ile şimdi onu uygulaması gereken ben arasındaki farkın gerçek kimliğidir. Bu yazı, bu farkın neden oluştuğunu, neden tam olarak uygulama anında patlarcasına büyüdüğünü ve neden yalnızca yapısal bir düzeneğin — daha fazla iradenin değil — bu farkı gerçekten daraltabildiğini sırasıyla ele alıyor.</p>
<p class="vi">Cốt lõi của vấn đề không phải là cảm xúc, mà là chính cách con người tính toán thời gian. Con người không chiết khấu lợi ích và tổn thất tương lai theo hàm mũ. Thay vào đó, họ chiết khấu dốc một cách bất thường cho tương lai gần và tương đối phẳng cho tương lai xa. Sự bất đối xứng đó chính là "chiết khấu hyperbol", và đó là bản chất thực sự của khoảng cách giữa cái tôi đã lập kế hoạch và cái tôi giờ đây phải thực hiện nó. Bài viết này lần lượt xem xét vì sao khoảng cách đó hình thành, vì sao nó bùng nổ đúng vào thời điểm thực hiện, và vì sao chỉ một cơ chế mang tính cấu trúc — chứ không phải ý chí mạnh hơn — mới thực sự thu hẹp được khoảng cách này.</p>

<h2 class="ko">왜 "다음 달의 나"는 사실상 남이나 마찬가지인가</h2>
<h2 class="en">Why "Next Month's Me" Is Practically a Stranger</h2>
<h2 class="ja">なぜ「来月の自分」は事実上、他人同然なのか</h2>
<h2 class="es">Por Qué el "Yo del Mes Que Viene" Es Prácticamente un Desconocido</h2>
<h2 class="de">Warum das „Ich im nächsten Monat" praktisch ein Fremder ist</h2>
<h2 class="fr">Pourquoi le « Moi du Mois Prochain » Est Pratiquement un Étranger</h2>
<h2 class="pt">Por Que o "Eu do Próximo Mês" É Praticamente um Estranho</h2>
<h2 class="tr">"Gelecek Ayki Ben" Neden Aslında Bir Yabancı Gibidir</h2>
<h2 class="vi">Vì Sao "Tôi Của Tháng Sau" Gần Như Là Một Người Xa Lạ</h2>

<p class="ko">1981년 리처드 탈러(Richard Thaler)는 이코노믹스 레터스(Economics Letters)에 발표한 논문 "동태적 비일관성에 관한 실증적 증거(Some Empirical Evidence on Dynamic Inconsistency)"에서, 사람들이 암묵적으로 적용하는 할인율이 시점에 따라 달라진다는 사실을 실증적으로 보여줬다. 동일한 사람이 가까운 시점 사이의 트레이드오프에는 훨씬 높은 할인율을, 먼 시점 사이의 트레이드오프에는 훨씬 낮은 할인율을 적용한다. 다시 말해 "오늘과 내일"의 차이는 참을 수 없을 만큼 크게 느껴지는데, "1년 후와 1년하고 하루 후"의 차이는 사실상 없는 것처럼 느껴진다. 이 비일관성은 계산 실수가 아니라, 인간의 시간 선호가 원래 이런 모양으로 설계되어 있다는 뜻이다.</p>
<p class="en">In 1981, Richard Thaler published "Some Empirical Evidence on Dynamic Inconsistency" in Economics Letters, empirically showing that the discount rate people implicitly apply changes depending on the time horizon. The same person applies a much higher discount rate to trade-offs between near points in time, and a much lower one to trade-offs between distant points in time. In other words, the difference between "today and tomorrow" feels unbearably large, while the difference between "one year from now and one year and one day from now" feels like nothing at all. This inconsistency isn't a calculation error — it reflects the actual shape that human time preference is built with.</p>
<p class="ja">1981年、リチャード・タラー(Richard Thaler)はエコノミクス・レターズ誌に発表した論文「動学的不整合に関する実証的証拠(Some Empirical Evidence on Dynamic Inconsistency)」で、人々が暗黙のうちに適用する割引率が時点によって変わるという事実を実証的に示した。同一人物が近い時点間のトレードオフにははるかに高い割引率を、遠い時点間のトレードオフにははるかに低い割引率を適用する。言い換えれば、「今日と明日」の差は耐えがたいほど大きく感じられるのに、「1年後と1年と1日後」の差は事実上ないもののように感じられる。この不整合は計算ミスではなく、人間の時間選好がもともとこのような形に設計されているということを意味する。</p>
<p class="es">En 1981, Richard Thaler publicó "Some Empirical Evidence on Dynamic Inconsistency" en Economics Letters, mostrando empíricamente que la tasa de descuento que las personas aplican implícitamente cambia según el horizonte temporal. La misma persona aplica una tasa de descuento mucho más alta a las disyuntivas entre puntos cercanos en el tiempo, y mucho más baja a las disyuntivas entre puntos lejanos en el tiempo. Dicho de otro modo, la diferencia entre "hoy y mañana" se siente insoportablemente grande, mientras que la diferencia entre "dentro de un año y dentro de un año y un día" se siente prácticamente nula. Esta inconsistencia no es un error de cálculo: refleja la forma real con la que está construida la preferencia temporal humana.</p>
<p class="de">1981 veröffentlichte Richard Thaler in Economics Letters den Aufsatz „Some Empirical Evidence on Dynamic Inconsistency" und zeigte empirisch, dass der Abzinsungssatz, den Menschen implizit anwenden, je nach Zeithorizont variiert. Dieselbe Person wendet auf Abwägungen zwischen nahen Zeitpunkten einen viel höheren Abzinsungssatz an als auf Abwägungen zwischen entfernten Zeitpunkten. Anders gesagt: Der Unterschied zwischen „heute und morgen" fühlt sich unerträglich groß an, während der Unterschied zwischen „in einem Jahr und in einem Jahr und einem Tag" sich praktisch nach nichts anfühlt. Diese Inkonsistenz ist kein Rechenfehler — sie spiegelt die tatsächliche Form wider, in der die menschliche Zeitpräferenz gebaut ist.</p>
<p class="fr">En 1981, Richard Thaler a publié « Some Empirical Evidence on Dynamic Inconsistency » dans Economics Letters, montrant empiriquement que le taux d'actualisation implicitement appliqué par les gens varie selon l'horizon temporel. Une même personne applique un taux d'actualisation bien plus élevé aux arbitrages entre points proches dans le temps, et bien plus faible aux arbitrages entre points éloignés. Autrement dit, la différence entre « aujourd'hui et demain » paraît insupportablement grande, tandis que celle entre « dans un an et dans un an et un jour » paraît quasiment nulle. Cette incohérence n'est pas une erreur de calcul — elle reflète la forme réelle dont est bâtie la préférence temporelle humaine.</p>
<p class="pt">Em 1981, Richard Thaler publicou "Some Empirical Evidence on Dynamic Inconsistency" na Economics Letters, mostrando empiricamente que a taxa de desconto que as pessoas aplicam implicitamente muda conforme o horizonte de tempo. A mesma pessoa aplica uma taxa de desconto muito mais alta às trocas entre pontos próximos no tempo, e muito mais baixa às trocas entre pontos distantes. Em outras palavras, a diferença entre "hoje e amanhã" parece insuportavelmente grande, enquanto a diferença entre "daqui a um ano e daqui a um ano e um dia" parece praticamente nula. Essa inconsistência não é um erro de cálculo — reflete a forma real com que a preferência temporal humana é construída.</p>
<p class="tr">1981'de Richard Thaler, Economics Letters'ta yayımlanan "Some Empirical Evidence on Dynamic Inconsistency" (Dinamik Tutarsızlığa İlişkin Ampirik Kanıtlar) makalesinde, insanların zımnen uyguladığı iskonto oranının zaman ufkuna göre değiştiğini ampirik olarak gösterdi. Aynı kişi, yakın zaman noktaları arasındaki değiş tokuşlara çok daha yüksek, uzak zaman noktaları arasındakilere ise çok daha düşük bir iskonto oranı uygular. Başka bir deyişle, "bugün ile yarın" arasındaki fark dayanılmaz derecede büyük hissettirirken, "bir yıl sonra ile bir yıl bir gün sonra" arasındaki fark neredeyse yokmuş gibi hissettirir. Bu tutarsızlık bir hesaplama hatası değildir — insanın zaman tercihinin gerçekte bu biçimde inşa edildiğini gösterir.</p>
<p class="vi">Năm 1981, Richard Thaler công bố "Some Empirical Evidence on Dynamic Inconsistency" trên tạp chí Economics Letters, chứng minh bằng thực nghiệm rằng tỷ lệ chiết khấu mà con người ngầm áp dụng thay đổi tùy theo khoảng thời gian. Cùng một người áp dụng tỷ lệ chiết khấu cao hơn nhiều cho những đánh đổi giữa các thời điểm gần nhau, và thấp hơn nhiều cho những đánh đổi giữa các thời điểm xa nhau. Nói cách khác, sự khác biệt giữa "hôm nay và ngày mai" cảm thấy lớn đến mức không chịu nổi, trong khi sự khác biệt giữa "một năm nữa và một năm lẻ một ngày nữa" lại cảm thấy gần như không tồn tại. Sự bất nhất quán này không phải là lỗi tính toán — nó phản ánh hình dạng thực sự mà sở thích thời gian của con người được xây dựng nên.</p>

<p class="ko">1997년 데이비드 레입슨(David Laibson)은 저널 오브 이코노믹스(Quarterly Journal of Economics)에 발표한 "황금알과 쌍곡선 할인(Golden Eggs and Hyperbolic Discounting)"에서 이를 하나의 수식으로 정식화했다 — 이른바 준쌍곡선(quasi-hyperbolic) β-δ 모델이다. 미래의 모든 보상에는 표준적인 할인 계수 δ가 적용되지만, "지금 당장"과 "조금이라도 미래" 사이에는 한 번 더 β라는 별도의 할인 계수가 곱해진다. 이 β가 1보다 훨씬 작을수록 — 실증 연구에서 흔히 인용되는 값은 0.7 안팎이다 — 현재의 유혹이 계획을 짓누르는 힘이 커진다. 비트코인 투자자가 "사이클 끝까지 홀드"라는 계획을 세울 때, 그 계획은 δ만 적용되는 먼 미래의 트레이드오프로 계산된다. 그런데 정작 매도 버튼 앞에 섰을 때는 β까지 곱해진 전혀 다른 계산이 작동한다 — 계획을 세운 자아와 실행하는 자아가 같은 수학을 쓰고 있지 않은 셈이다.</p>
<p class="en">In 1997, David Laibson formalized this into a single equation in "Golden Eggs and Hyperbolic Discounting," published in the Quarterly Journal of Economics — the so-called quasi-hyperbolic β-δ model. A standard discount factor, δ, applies to all future rewards, but between "right now" and "even slightly in the future," one additional discount factor, β, gets multiplied in. The smaller β is relative to 1 — empirical studies commonly cite a value around 0.7 — the more crushing the pull of present temptation becomes on any plan. When a Bitcoin investor sets a plan to "hold until the cycle ends," that plan is computed as a distant trade-off governed only by δ. But standing in front of the sell button, an entirely different calculation kicks in — one multiplied by β as well. The self who made the plan and the self executing it are, in effect, not running the same math.</p>
<p class="ja">1997年、デイビッド・レイブソン(David Laibson)はクォータリー・ジャーナル・オブ・エコノミクス誌に発表した「黄金の卵と双曲割引(Golden Eggs and Hyperbolic Discounting)」でこれを一つの数式に定式化した——いわゆる準双曲(quasi-hyperbolic)β-δモデルである。未来のすべての報酬には標準的な割引係数δが適用されるが、「今すぐ」と「わずかでも未来」の間には、もう一度βという別の割引係数が乗じられる。このβが1よりはるかに小さいほど——実証研究でよく引用される値はおよそ0.7前後だ——現在の誘惑が計画を押しつぶす力は大きくなる。ビットコイン投資家が「サイクルの終わりまでホールドする」という計画を立てるとき、その計画はδのみが適用される遠い未来のトレードオフとして計算される。ところがいざ売却ボタンの前に立ったとき、βまで乗じられたまったく別の計算が働く——計画を立てた自我と実行する自我は、同じ数学を使っていないというわけだ。</p>
<p class="es">En 1997, David Laibson formalizó esto en una sola ecuación en "Golden Eggs and Hyperbolic Discounting", publicado en el Quarterly Journal of Economics — el llamado modelo cuasi-hiperbólico β-δ. Un factor de descuento estándar, δ, se aplica a todas las recompensas futuras, pero entre "ahora mismo" e "incluso un poco en el futuro", se multiplica un factor de descuento adicional, β. Cuanto más pequeño sea β en relación con 1 —los estudios empíricos suelen citar un valor cercano a 0.7—, mayor es la fuerza con que la tentación presente aplasta cualquier plan. Cuando un inversor de Bitcoin traza un plan de "mantener hasta que termine el ciclo", ese plan se calcula como una disyuntiva lejana gobernada solo por δ. Pero al pararse frente al botón de venta, entra en juego un cálculo totalmente distinto —uno multiplicado también por β. El yo que hizo el plan y el yo que lo ejecuta, en efecto, no están usando las mismas matemáticas.</p>
<p class="de">1997 formalisierte David Laibson dies in einer einzigen Gleichung in „Golden Eggs and Hyperbolic Discounting", veröffentlicht im Quarterly Journal of Economics — dem sogenannten quasi-hyperbolischen β-δ-Modell. Ein Standard-Diskontfaktor δ gilt für alle zukünftigen Belohnungen, aber zwischen „genau jetzt" und „auch nur ein wenig in der Zukunft" wird ein zusätzlicher Diskontfaktor β eingerechnet. Je kleiner β im Verhältnis zu 1 ist — empirische Studien nennen häufig einen Wert um 0,7 —, desto erdrückender wird die Kraft der gegenwärtigen Versuchung gegenüber jedem Plan. Wenn ein Bitcoin-Anleger den Plan fasst, „bis zum Ende des Zyklus zu halten", wird dieser Plan als ferne Abwägung berechnet, die nur von δ bestimmt wird. Doch steht er tatsächlich vor dem Verkaufsknopf, greift eine völlig andere Rechnung — eine, die zusätzlich mit β multipliziert wird. Das Ich, das den Plan gemacht hat, und das Ich, das ihn ausführt, rechnen faktisch nicht mit derselben Mathematik.</p>
<p class="fr">En 1997, David Laibson a formalisé cela en une seule équation dans « Golden Eggs and Hyperbolic Discounting », publié dans le Quarterly Journal of Economics — le modèle dit quasi-hyperbolique β-δ. Un facteur d'actualisation standard, δ, s'applique à toutes les récompenses futures, mais entre « maintenant » et « même un peu plus tard », un facteur d'actualisation supplémentaire, β, vient se multiplier. Plus β est petit par rapport à 1 — les études empiriques citent couramment une valeur d'environ 0,7 —, plus la force de la tentation présente écrase n'importe quel plan. Lorsqu'un investisseur en Bitcoin élabore un plan « tenir jusqu'à la fin du cycle », ce plan est calculé comme un arbitrage lointain régi uniquement par δ. Mais debout devant le bouton de vente, un calcul entièrement différent entre en jeu — un calcul multiplié aussi par β. Le moi qui a fait le plan et le moi qui l'exécute n'utilisent, en pratique, pas les mêmes mathématiques.</p>
<p class="pt">Em 1997, David Laibson formalizou isso em uma única equação em "Golden Eggs and Hyperbolic Discounting", publicado no Quarterly Journal of Economics — o chamado modelo quase-hiperbólico β-δ. Um fator de desconto padrão, δ, aplica-se a todas as recompensas futuras, mas entre "agora mesmo" e "mesmo que um pouco no futuro", um fator de desconto adicional, β, é multiplicado. Quanto menor for β em relação a 1 — estudos empíricos costumam citar um valor próximo de 0,7 —, maior é a força com que a tentação presente esmaga qualquer plano. Quando um investidor de Bitcoin traça um plano de "manter até o fim do ciclo", esse plano é calculado como uma troca distante governada apenas por δ. Mas, diante do botão de venda, entra em ação um cálculo totalmente diferente — um também multiplicado por β. O eu que fez o plano e o eu que o executa, na prática, não estão usando a mesma matemática.</p>
<p class="tr">1997'de David Laibson, Quarterly Journal of Economics'te yayımlanan "Golden Eggs and Hyperbolic Discounting" (Altın Yumurtalar ve Hiperbolik İskonto) makalesinde bunu tek bir denklemle biçimlendirdi — sözde yarı-hiperbolik β-δ modeli. Standart bir iskonto katsayısı olan δ, tüm gelecekteki ödüllere uygulanır, ama "tam şimdi" ile "biraz bile olsa gelecek" arasında bir kez daha β adında ayrı bir iskonto katsayısı çarpılır. Bu β, 1'e göre ne kadar küçükse — ampirik çalışmalarda sıklıkla 0,7 civarında bir değer anılır — şimdiki zamanın cazibesinin planı ezme gücü o kadar büyür. Bir Bitcoin yatırımcısı "döngü bitene kadar tut" planını yaparken, bu plan yalnızca δ'nın yönettiği uzak bir değiş tokuş olarak hesaplanır. Ama satış düğmesinin önünde durduğunda, β ile de çarpılmış tamamen farklı bir hesap devreye girer — planı yapan ben ile onu uygulayan ben, aslında aynı matematiği kullanmıyordur.</p>
<p class="vi">Năm 1997, David Laibson đã hình thức hóa điều này thành một phương trình duy nhất trong "Golden Eggs and Hyperbolic Discounting", đăng trên Quarterly Journal of Economics — mô hình gần-hyperbol β-δ. Một hệ số chiết khấu chuẩn, δ, áp dụng cho mọi phần thưởng tương lai, nhưng giữa "ngay bây giờ" và "dù chỉ một chút trong tương lai", một hệ số chiết khấu bổ sung, β, được nhân thêm vào. β càng nhỏ so với 1 — các nghiên cứu thực nghiệm thường trích dẫn giá trị khoảng 0,7 — thì lực kéo của cám dỗ hiện tại càng đè bẹp mọi kế hoạch. Khi một nhà đầu tư Bitcoin lập kế hoạch "giữ đến khi chu kỳ kết thúc", kế hoạch đó được tính toán như một sự đánh đổi xa xôi chỉ chịu chi phối bởi δ. Nhưng khi đứng trước nút bán, một phép tính hoàn toàn khác vận hành — một phép tính cũng được nhân với β. Cái tôi đã lập kế hoạch và cái tôi đang thực hiện nó, trên thực tế, không dùng cùng một phép toán.</p>

<h2 class="ko">계획하는 자아와 실행하는 자아는 서로를 믿지 않는다</h2>
<h2 class="en">The Planning Self and the Doing Self Don't Trust Each Other</h2>
<h2 class="ja">計画する自我と実行する自我は、互いを信用していない</h2>
<h2 class="es">El Yo Planificador y el Yo Ejecutor No Confían el Uno en el Otro</h2>
<h2 class="de">Das planende und das handelnde Ich vertrauen einander nicht</h2>
<h2 class="fr">Le Moi Planificateur et le Moi Exécutant Ne se Font Pas Confiance</h2>
<h2 class="pt">O Eu Planejador e o Eu Executor Não Confiam Um no Outro</h2>
<h2 class="tr">Planlayan Ben ile Uygulayan Ben Birbirine Güvenmez</h2>
<h2 class="vi">Cái Tôi Lập Kế Hoạch và Cái Tôi Hành Động Không Tin Tưởng Lẫn Nhau</h2>

<p class="ko">리처드 탈러와 허쉬 셰프린(Hersh Shefrin)은 1981년 저널 오브 폴리티컬 이코노미(Journal of Political Economy)에 실린 "자기통제의 경제학 이론(An Economic Theory of Self-Control)"에서 한 사람 안에 "플래너(planner)"와 "두어(doer)"라는 두 자아가 공존한다고 제안했다. 플래너는 장기적 효용을 극대화하려 하고, 두어는 그 순간의 만족을 극대화하려 한다. 문제는 이 두 자아가 협상 테이블에 함께 앉아있지 않다는 데 있다 — 플래너가 규칙을 세울 수는 있지만, 그 규칙을 실제로 지킬지는 나중에 등장할 두어의 몫이고, 두어는 플래너의 약속에 구속되지 않는다.</p>
<p class="en">Richard Thaler and Hersh Shefrin, in "An Economic Theory of Self-Control," published in the Journal of Political Economy in 1981, proposed that a single person houses two coexisting selves — a "planner" and a "doer." The planner tries to maximize long-term utility; the doer tries to maximize satisfaction in the moment. The problem is that these two selves never sit at the same negotiating table. The planner can set a rule, but whether that rule actually gets kept is up to the doer who shows up later — and the doer isn't bound by the planner's promise.</p>
<p class="ja">リチャード・タラーとハーシュ・シェフリン(Hersh Shefrin)は1981年、ジャーナル・オブ・ポリティカル・エコノミー誌に掲載された「自己統制の経済学理論(An Economic Theory of Self-Control)」で、一人の人間の中に「プランナー(planner)」と「ドゥアー(doer)」という二つの自我が共存すると提案した。プランナーは長期的効用を最大化しようとし、ドゥアーはその瞬間の満足を最大化しようとする。問題は、この二つの自我が交渉のテーブルに一緒に座っていないという点にある——プランナーがルールを立てることはできても、そのルールを実際に守るかどうかは後から現れるドゥアーの領分であり、ドゥアーはプランナーの約束に縛られない。</p>
<p class="es">Richard Thaler y Hersh Shefrin, en "An Economic Theory of Self-Control", publicado en el Journal of Political Economy en 1981, propusieron que una sola persona alberga dos yoes coexistentes — un "planificador" y un "ejecutor". El planificador intenta maximizar la utilidad a largo plazo; el ejecutor intenta maximizar la satisfacción del momento. El problema es que estos dos yoes nunca se sientan en la misma mesa de negociación — el planificador puede fijar una regla, pero que esa regla se cumpla realmente depende del ejecutor que aparecerá después, y el ejecutor no está obligado por la promesa del planificador.</p>
<p class="de">Richard Thaler und Hersh Shefrin schlugen 1981 in „An Economic Theory of Self-Control", veröffentlicht im Journal of Political Economy, vor, dass eine einzige Person zwei koexistierende Ichs beherbergt — einen „Planer" und einen „Handelnden". Der Planer versucht, den langfristigen Nutzen zu maximieren; der Handelnde versucht, die Zufriedenheit im Moment zu maximieren. Das Problem ist, dass diese beiden Ichs niemals am selben Verhandlungstisch sitzen — der Planer kann eine Regel aufstellen, aber ob diese Regel tatsächlich eingehalten wird, liegt beim später auftretenden Handelnden, und der Handelnde ist nicht an das Versprechen des Planers gebunden.</p>
<p class="fr">Richard Thaler et Hersh Shefrin, dans « An Economic Theory of Self-Control », publié dans le Journal of Political Economy en 1981, ont proposé qu'une seule personne héberge deux moi coexistants — un « planificateur » et un « exécutant ». Le planificateur cherche à maximiser l'utilité à long terme ; l'exécutant cherche à maximiser la satisfaction du moment. Le problème est que ces deux moi ne s'assoient jamais à la même table de négociation — le planificateur peut fixer une règle, mais que cette règle soit réellement respectée dépend de l'exécutant qui apparaîtra plus tard, et celui-ci n'est pas lié par la promesse du planificateur.</p>
<p class="pt">Richard Thaler e Hersh Shefrin, em "An Economic Theory of Self-Control", publicado no Journal of Political Economy em 1981, propuseram que uma única pessoa abriga dois eus coexistentes — um "planejador" e um "executor". O planejador tenta maximizar a utilidade de longo prazo; o executor tenta maximizar a satisfação do momento. O problema é que esses dois eus nunca se sentam à mesma mesa de negociação — o planejador pode estabelecer uma regra, mas se essa regra é realmente cumprida depende do executor que aparecerá depois, e o executor não está vinculado à promessa do planejador.</p>
<p class="tr">Richard Thaler ve Hersh Shefrin, 1981'de Journal of Political Economy'de yayımlanan "An Economic Theory of Self-Control" (Öz-Denetimin Ekonomik Teorisi) makalesinde, tek bir kişinin içinde "planlayıcı" ve "uygulayıcı" adında iki bir arada var olan benlik olduğunu öne sürdü. Planlayıcı uzun vadeli faydayı en üst düzeye çıkarmaya çalışırken, uygulayıcı o anki tatmini en üst düzeye çıkarmaya çalışır. Sorun şu ki bu iki benlik aynı müzakere masasında hiç oturmaz — planlayıcı bir kural koyabilir, ama o kuralın gerçekten tutulup tutulmayacağı sonradan ortaya çıkan uygulayıcının elindedir ve uygulayıcı planlayıcının verdiği sözle bağlı değildir.</p>
<p class="vi">Richard Thaler và Hersh Shefrin, trong bài "An Economic Theory of Self-Control" (Một Lý Thuyết Kinh Tế về Tự Kiểm Soát), đăng trên Journal of Political Economy năm 1981, đề xuất rằng một người chứa đựng hai cái tôi cùng tồn tại — một "người lập kế hoạch" và một "người thực hiện". Người lập kế hoạch cố gắng tối đa hóa lợi ích dài hạn; người thực hiện cố gắng tối đa hóa sự thỏa mãn trong khoảnh khắc. Vấn đề là hai cái tôi này không bao giờ ngồi cùng bàn đàm phán — người lập kế hoạch có thể đặt ra quy tắc, nhưng việc quy tắc đó có thực sự được tuân thủ hay không lại tùy thuộc vào người thực hiện xuất hiện sau đó, và người thực hiện không bị ràng buộc bởi lời hứa của người lập kế hoạch.</p>

<p class="ko">1999년 테드 오도너휴(Ted O'Donoghue)와 매튜 라빈(Matthew Rabin)은 아메리칸 이코노믹 리뷰(American Economic Review)에 발표한 "지금 할 것인가, 나중에 할 것인가(Doing It Now or Later)"에서 이 간극을 한 단계 더 파고들었다. 이들은 투자자를 두 부류로 나눈다 — 자신의 미래 자기통제 실패를 과소평가하는 "나이브(naive)" 유형과, 그 실패 가능성을 어느 정도 인정하고 미리 대비하는 "소피스티케이트(sophisticated)" 유형이다. 나이브 유형은 "이번엔 다르게 할 것"이라고 매번 진심으로 믿으면서 매번 같은 실수를 반복한다 — 애초에 미래의 자신이 유혹 앞에서 무너질 가능성 자체를 계산에 넣지 않았기 때문이다. 반면 소피스티케이트 유형은 자신을 완전히 신뢰하지 않는다는 바로 그 이유로, 유혹이 오기 전에 스스로의 선택지를 미리 제한해 둔다.</p>
<p class="en">In 1999, Ted O'Donoghue and Matthew Rabin dug one level deeper into this gap in "Doing It Now or Later," published in the American Economic Review. They split investors into two types — "naive" ones who underestimate their own future self-control failure, and "sophisticated" ones who acknowledge that possibility to some degree and prepare for it in advance. Naive types genuinely believe "this time will be different" every single time, and repeat the same mistake every single time — because they never priced in the possibility that their future self would cave to temptation in the first place. Sophisticated types, precisely because they don't fully trust themselves, restrict their own options in advance, before temptation arrives.</p>
<p class="ja">1999年、テッド・オドノヒュー(Ted O'Donoghue)とマシュー・ラビン(Matthew Rabin)はアメリカン・エコノミック・レビュー誌に発表した「今やるか、後でやるか(Doing It Now or Later)」で、この乖離をもう一段深く掘り下げた。彼らは投資家を二種類に分ける——自らの将来の自己統制の失敗を過小評価する「ナイーブ(naive)」タイプと、その失敗の可能性をある程度認め、あらかじめ備える「ソフィスティケート(sophisticated)」タイプだ。ナイーブタイプは「今回は違うやり方をする」と毎回本気で信じながら、毎回同じ過ちを繰り返す——そもそも未来の自分が誘惑の前で崩れる可能性そのものを計算に入れていないからだ。一方、ソフィスティケートタイプは自分を完全には信用していないというまさにその理由から、誘惑が来る前にあらかじめ自らの選択肢を制限しておく。</p>
<p class="es">En 1999, Ted O'Donoghue y Matthew Rabin profundizaron un nivel más en esta brecha en "Doing It Now or Later", publicado en el American Economic Review. Dividen a los inversores en dos tipos — los "ingenuos" (naive), que subestiman su propio fracaso futuro de autocontrol, y los "sofisticados" (sophisticated), que reconocen esa posibilidad en cierta medida y se preparan de antemano. Los tipos ingenuos creen genuinamente cada vez que "esta vez será diferente" y repiten el mismo error cada vez —porque nunca contemplaron desde el principio la posibilidad de que su yo futuro cediera ante la tentación. Los tipos sofisticados, precisamente porque no confían del todo en sí mismos, restringen sus propias opciones de antemano, antes de que llegue la tentación.</p>
<p class="de">1999 gruben Ted O'Donoghue und Matthew Rabin in „Doing It Now or Later", veröffentlicht im American Economic Review, eine Ebene tiefer in diese Kluft. Sie teilen Anleger in zwei Typen ein — „naive", die ihr eigenes zukünftiges Versagen der Selbstkontrolle unterschätzen, und „raffinierte" (sophisticated), die diese Möglichkeit in gewissem Maße anerkennen und sich im Voraus darauf vorbereiten. Naive Typen glauben jedes Mal aufrichtig, „dieses Mal wird es anders", und wiederholen jedes Mal denselben Fehler — weil sie von vornherein nie einkalkuliert haben, dass ihr zukünftiges Ich der Versuchung erliegen könnte. Raffinierte Typen hingegen schränken, gerade weil sie sich selbst nicht vollständig vertrauen, ihre eigenen Optionen im Voraus ein, bevor die Versuchung überhaupt eintrifft.</p>
<p class="fr">En 1999, Ted O'Donoghue et Matthew Rabin ont creusé un cran plus loin cet écart dans « Doing It Now or Later », publié dans l'American Economic Review. Ils répartissent les investisseurs en deux types — les « naïfs », qui sous-estiment leur propre futur échec de maîtrise de soi, et les « sophistiqués », qui reconnaissent cette possibilité dans une certaine mesure et s'y préparent à l'avance. Les naïfs croient sincèrement, chaque fois, que « cette fois sera différente », et répètent chaque fois la même erreur — parce qu'ils n'ont jamais intégré, dès le départ, la possibilité que leur futur moi cède à la tentation. Les sophistiqués, précisément parce qu'ils ne se font pas entièrement confiance, restreignent d'avance leurs propres options, avant même que la tentation n'arrive.</p>
<p class="pt">Em 1999, Ted O'Donoghue e Matthew Rabin se aprofundaram um nível mais nessa lacuna em "Doing It Now or Later", publicado na American Economic Review. Eles dividem os investidores em dois tipos — os "ingênuos" (naive), que subestimam sua própria falha futura de autocontrole, e os "sofisticados", que reconhecem essa possibilidade em certa medida e se preparam com antecedência. Os tipos ingênuos acreditam genuinamente, toda vez, que "desta vez será diferente", e repetem o mesmo erro toda vez — porque nunca consideraram, desde o início, a possibilidade de que seu eu futuro cederia à tentação. Já os sofisticados, justamente por não confiarem plenamente em si mesmos, restringem antecipadamente suas próprias opções, antes que a tentação chegue.</p>
<p class="tr">1999'da Ted O'Donoghue ve Matthew Rabin, American Economic Review'da yayımlanan "Doing It Now or Later" (Şimdi mi Sonra mı Yapmalı) makalesinde bu farkı bir kademe daha derinleştirdi. Yatırımcıları iki türe ayırıyorlar — kendi gelecekteki öz-denetim başarısızlığını hafife alan "naif" türler ve bu olasılığı bir ölçüde kabul edip önceden hazırlanan "sofistike" türler. Naif türler her seferinde "bu sefer farklı olacak" diye içtenlikle inanır ve her seferinde aynı hatayı tekrarlar — çünkü gelecekteki benliklerinin cazibe karşısında çökebileceği olasılığını baştan hesaba katmamışlardır. Sofistike türler ise tam olarak kendilerine tamamen güvenmedikleri için, cazibe gelmeden önce kendi seçeneklerini önceden kısıtlarlar.</p>
<p class="vi">Năm 1999, Ted O'Donoghue và Matthew Rabin đào sâu thêm một tầng nữa vào khoảng cách này trong bài "Doing It Now or Later" (Làm Ngay Bây Giờ hay Để Sau), đăng trên American Economic Review. Họ chia nhà đầu tư thành hai loại — loại "ngây thơ" đánh giá thấp khả năng thất bại tự kiểm soát trong tương lai của chính mình, và loại "tinh khôn" thừa nhận khả năng đó ở một mức độ nào đó và chuẩn bị trước. Loại ngây thơ thực lòng tin rằng "lần này sẽ khác" mỗi lần, và lặp lại cùng một sai lầm mỗi lần — vì ngay từ đầu họ chưa bao giờ tính đến khả năng bản thân tương lai sẽ gục ngã trước cám dỗ. Ngược lại, loại tinh khôn, chính vì không hoàn toàn tin tưởng bản thân, nên đã giới hạn trước các lựa chọn của chính mình, trước khi cám dỗ ập đến.</p>

<div class="ko">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">계획 자아와 실행 자아, 시간을 다르게 계산한다</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">지수형 할인 vs 준쌍곡선 할인 — 지연에 따른 주관적 가치</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">가치</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">지연 시간 →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">지금</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← β 갭</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">지수형 할인 (계획)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">준쌍곡선 할인 (실행)</text>
</svg>
<p class="ko" style="font-size:12px;color:#71717a;margin-top:-10px">※ 레입슨(Laibson, 1997)의 준쌍곡선 β-δ 모델을 단순화한 개념도이며, 실제 계산값이 아닙니다(β=0.7, δ=0.85 가정). 지연이 0에서 1로 늘어나는 순간에만 β만큼 추가로 할인되고, 그 이후 구간은 지수형 할인과 동일한 비율로 움직인다 — "지금 당장"과 "조금 뒤"의 격차만 유독 크게 느껴지는 이유다.</p>
</div>
<div class="en">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">The Planning Self and the Doing Self Compute Time Differently</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Exponential vs. Quasi-Hyperbolic Discounting — Subjective Value by Delay</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Value</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Delay →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">Now</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← β gap</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">Exponential (Planning Self)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">Quasi-Hyperbolic (Doing Self)</text>
</svg>
<p class="en" style="font-size:12px;color:#71717a;margin-top:-10px">※ A simplified conceptual illustration of Laibson's (1997) quasi-hyperbolic β-δ model, not a plot of real computed values (β=0.7, δ=0.85 assumed here). The extra β discount applies only once, at the jump from delay 0 to delay 1 — every step after that moves at the same rate as exponential discounting. That's why only the gap between "right now" and "a little later" feels disproportionately large.</p>
</div>
<div class="ja">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">計画する自我と実行する自我は、時間の計算が違う</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">指数割引 対 準双曲割引——遅延に対する主観的価値</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">価値</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">遅延時間→</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">今</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← βギャップ</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">指数割引(計画自我)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">準双曲割引(実行自我)</text>
</svg>
<p class="ja" style="font-size:12px;color:#71717a;margin-top:-10px">※ レイブソン(Laibson, 1997)の準双曲β-δモデルを単純化した概念図であり、実際の計算値ではありません(β=0.7、δ=0.85と仮定)。遅延が0から1に増える瞬間にのみβ分だけ追加で割り引かれ、それ以降の区間は指数割引と同じ比率で動く——「今すぐ」と「少し後」の差だけが際立って大きく感じられる理由だ。</p>
</div>
<div class="es">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">El Yo que Planea y el Yo que Actúa Calculan el Tiempo de Forma Distinta</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Descuento Exponencial vs. Cuasi-Hiperbólico — Valor Subjetivo Según la Demora</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Valor</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Demora →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">Ahora</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← brecha β</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">Exponencial (Yo Planificador)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">Cuasi-Hiperbólico (Yo Ejecutor)</text>
</svg>
<p class="es" style="font-size:12px;color:#71717a;margin-top:-10px">※ Ilustración conceptual simplificada del modelo cuasi-hiperbólico β-δ de Laibson (1997), no un gráfico de valores reales calculados (β=0.7, δ=0.85 asumidos aquí). El descuento extra de β se aplica solo una vez, en el salto de demora 0 a demora 1 — cada paso posterior se mueve al mismo ritmo que el descuento exponencial. Por eso solo la brecha entre "ahora mismo" y "un poco después" se siente desproporcionadamente grande.</p>
</div>
<div class="de">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Das planende und das handelnde Ich berechnen Zeit unterschiedlich</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Exponentielles vs. Quasi-Hyperbolisches Diskontieren — Subjektiver Wert nach Verzögerung</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Wert</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Verzögerung →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">Jetzt</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← β-Lücke</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">Exponentiell (Planendes Ich)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">Quasi-Hyperbolisch (Handelndes Ich)</text>
</svg>
<p class="de" style="font-size:12px;color:#71717a;margin-top:-10px">※ Eine vereinfachte konzeptionelle Darstellung von Laibsons (1997) quasi-hyperbolischem β-δ-Modell, keine Darstellung realer berechneter Werte (hier β=0,7, δ=0,85 angenommen). Der zusätzliche β-Abschlag gilt nur einmal, beim Sprung von Verzögerung 0 zu Verzögerung 1 — jeder Schritt danach bewegt sich im gleichen Tempo wie beim exponentiellen Diskontieren. Deshalb fühlt sich nur die Lücke zwischen „jetzt sofort" und „etwas später" unverhältnismäßig groß an.</p>
</div>
<div class="fr">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Le Moi qui Planifie et le Moi qui Agit Calculent le Temps Différemment</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Actualisation Exponentielle vs Quasi-Hyperbolique — Valeur Subjective Selon le Délai</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Valeur</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Délai →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">Maintenant</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← écart β</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">Exponentiel (Moi Planificateur)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">Quasi-Hyperbolique (Moi Exécutant)</text>
</svg>
<p class="fr" style="font-size:12px;color:#71717a;margin-top:-10px">※ Illustration conceptuelle simplifiée du modèle quasi-hyperbolique β-δ de Laibson (1997), non un graphique de valeurs réellement calculées (β=0,7, δ=0,85 supposés ici). L'escompte supplémentaire de β ne s'applique qu'une seule fois, au passage du délai 0 au délai 1 — chaque étape suivante évolue au même rythme que l'actualisation exponentielle. C'est pourquoi seul l'écart entre « maintenant » et « un peu plus tard » paraît disproportionnellement grand.</p>
</div>
<div class="pt">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">O Eu que Planeja e o Eu que Age Calculam o Tempo de Forma Diferente</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Desconto Exponencial vs. Quase-Hiperbólico — Valor Subjetivo pelo Atraso</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Valor</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Atraso →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">Agora</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← lacuna β</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">Exponencial (Eu Planejador)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">Quase-Hiperbólico (Eu Executor)</text>
</svg>
<p class="pt" style="font-size:12px;color:#71717a;margin-top:-10px">※ Ilustração conceitual simplificada do modelo quase-hiperbólico β-δ de Laibson (1997), não um gráfico de valores reais calculados (aqui β=0,7, δ=0,85). O desconto extra de β se aplica apenas uma vez, no salto do atraso 0 para o atraso 1 — cada etapa seguinte se move no mesmo ritmo do desconto exponencial. É por isso que só a lacuna entre "agora mesmo" e "um pouco depois" parece desproporcionalmente grande.</p>
</div>
<div class="tr">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Planlayan Ben ile Uygulayan Ben Zamanı Farklı Hesaplar</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Üstel ve Yarı-Hiperbolik İskonto — Gecikmeye Göre Öznel Değer</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Değer</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Gecikme →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">Şimdi</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← β farkı</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">Üstel (Planlayan Ben)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">Yarı-Hiperbolik (Uygulayan Ben)</text>
</svg>
<p class="tr" style="font-size:12px;color:#71717a;margin-top:-10px">※ Laibson'ın (1997) yarı-hiperbolik β-δ modelinin basitleştirilmiş kavramsal bir gösterimidir, gerçek hesaplanmış değerlerin grafiği değildir (burada β=0,7, δ=0,85 varsayılmıştır). Ekstra β iskontosu yalnızca bir kez, gecikme 0'dan gecikme 1'e sıçrarken uygulanır — sonrasındaki her adım üstel iskontoyla aynı hızda ilerler. Bu yüzden yalnızca "şimdi" ile "biraz sonra" arasındaki fark orantısız derecede büyük hissettirir.</p>
</div>
<div class="vi">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Cái Tôi Lập Kế Hoạch và Cái Tôi Hành Động Tính Thời Gian Khác Nhau</text>
  <text x="20" y="48" fill="#a1a1aa" font-size="13" font-family="sans-serif">Chiết Khấu Theo Hàm Mũ so với Gần-Hyperbol — Giá Trị Chủ Quan Theo Độ Trễ</text>
  <line x1="80" y1="70" x2="80" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <line x1="80" y1="320" x2="650" y2="320" stroke="#52525b" stroke-width="1.5"/>
  <text x="60" y="80" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Giá trị</text>
  <text x="650" y="345" fill="#a1a1aa" font-size="13" text-anchor="end" font-family="sans-serif">Độ trễ →</text>
  <polyline points="80,70 137,107.5 194,139.4 251,166.5 308,189.5 365,209.1 422,225.7 479,239.8 536,251.9 593,262.1 650,270.8" fill="none" stroke="#4ade80" stroke-width="3"/>
  <polyline points="80,70 137,171.25 194,193.55 251,212.52 308,228.65 365,242.35 422,254.0 479,263.9 536,272.32 593,279.47 650,285.55" fill="none" stroke="#f87171" stroke-width="3"/>
  <line x1="137" y1="107.5" x2="137" y2="171.25" stroke="#fbbf24" stroke-width="2" stroke-dasharray="3,3"/>
  <circle cx="80" cy="70" r="5" fill="#fbbf24"/>
  <text x="90" y="65" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">Bây giờ</text>
  <text x="150" y="145" fill="#fbbf24" font-size="13" font-family="sans-serif" font-weight="700">← khoảng cách β</text>
  <rect x="90" y="365" width="28" height="4" fill="#4ade80"/>
  <text x="126" y="371" fill="#e4e4e7" font-size="13" font-family="sans-serif">Hàm Mũ (Cái Tôi Lập Kế Hoạch)</text>
  <rect x="90" y="392" width="28" height="4" fill="#f87171"/>
  <text x="126" y="398" fill="#e4e4e7" font-size="13" font-family="sans-serif">Gần-Hyperbol (Cái Tôi Hành Động)</text>
</svg>
<p class="vi" style="font-size:12px;color:#71717a;margin-top:-10px">※ Minh họa khái niệm đơn giản hóa của mô hình gần-hyperbol β-δ của Laibson (1997), không phải đồ thị giá trị tính toán thực tế (ở đây giả định β=0,7, δ=0,85). Mức chiết khấu β bổ sung chỉ áp dụng một lần duy nhất, ở bước nhảy từ độ trễ 0 sang độ trễ 1 — mỗi bước sau đó di chuyển với cùng tốc độ như chiết khấu theo hàm mũ. Đó là lý do tại sao chỉ có khoảng cách giữa "ngay bây giờ" và "một lát sau" mới cảm thấy lớn một cách bất cân xứng.</p>
</div>

<h2 class="ko">온체인 데이터가 보여주는 계획과 실행의 간극</h2>
<h2 class="en">What On-Chain Data Shows About the Gap Between Plan and Execution</h2>
<h2 class="ja">オンチェーンデータが示す計画と実行の乖離</h2>
<h2 class="es">Lo Que los Datos On-Chain Muestran Sobre la Brecha Entre el Plan y la Ejecución</h2>
<h2 class="de">Was On-Chain-Daten über die Kluft zwischen Plan und Ausführung zeigen</h2>
<h2 class="fr">Ce Que les Données On-Chain Montrent Sur l'Écart Entre le Plan et l'Exécution</h2>
<h2 class="pt">O Que os Dados On-Chain Mostram Sobre a Lacuna Entre o Plano e a Execução</h2>
<h2 class="tr">Zincir Üstü Veriler Plan ile Uygulama Arasındaki Farkı Nasıl Gösteriyor</h2>
<h2 class="vi">Dữ Liệu On-Chain Cho Thấy Gì Về Khoảng Cách Giữa Kế Hoạch và Thực Hiện</h2>

<p class="ko">이 간극은 추상적인 이론에 머물지 않는다. <a href="/blog/long-term-holder-supply.php">장기 보유자(LTH) 공급량</a> 지표는 사이클마다 거의 동일한 패턴을 반복해왔다 — 2017년, 2021년, 2023~24년 회복기 모두에서 이 지표는 하락장의 가장 어두운 구간에 정점을 찍은 뒤, 회복이 무르익을수록 서서히 줄어드는 곡선을 그렸다. 다시 말해 "가장 견디기 힘든 구간을 버텨낸" 바로 그 코호트가, "가장 보상이 큰 구간"까지 자동으로 버텨내지는 못한다는 뜻이다. 공포의 구간을 통과하는 데는 성공한 계획이, 정확히 반대 방향의 유혹 — 눈앞의 수익을 실현하고 싶은 충동 — 앞에서는 다시 무너지는 것이다.</p>
<p class="en">This gap doesn't stay confined to abstract theory. The <a href="/blog/long-term-holder-supply.php">long-term holder (LTH) supply</a> metric has repeated nearly the same pattern across cycles — in the 2017, 2021, and 2023–24 recoveries alike, it peaked in the darkest stretch of the bear market and then gradually declined as the recovery matured. In other words, the very cohort that endured "the hardest stretch to sit through" doesn't automatically endure through "the stretch with the largest reward." A plan that succeeded at surviving the fear phase collapses again in front of the exact opposite temptation — the urge to lock in gains that are now sitting right in front of you.</p>
<p class="ja">この乖離は抽象的な理論にとどまらない。<a href="/blog/long-term-holder-supply.php">長期保有者(LTH)供給量</a>指標は、サイクルごとにほぼ同じパターンを繰り返してきた——2017年、2021年、2023~24年の回復期のいずれも、この指標は弱気相場の最も暗い局面でピークをつけた後、回復が熟すにつれて徐々に減少する曲線を描いた。言い換えれば、「最も耐えがたい局面を耐え抜いた」まさにそのコホートが、「最も報酬の大きい局面」まで自動的に耐え抜くわけではないということだ。恐怖の局面を通過することには成功した計画が、まさに正反対の誘惑——目の前の利益を確定させたいという衝動——の前では再び崩れるのである。</p>
<p class="es">Esta brecha no se queda confinada a la teoría abstracta. El indicador de <a href="/blog/long-term-holder-supply.php">suministro de tenedores a largo plazo (LTH)</a> ha repetido casi el mismo patrón en cada ciclo — en las recuperaciones de 2017, 2021 y 2023-24 por igual, alcanzó su pico en el tramo más oscuro del mercado bajista y luego disminuyó gradualmente a medida que la recuperación maduraba. Dicho de otro modo, la misma cohorte que soportó "el tramo más difícil de aguantar" no aguanta automáticamente hasta "el tramo de mayor recompensa". Un plan que tuvo éxito sobreviviendo a la fase de miedo vuelve a derrumbarse frente a la tentación exactamente opuesta —el impulso de asegurar unas ganancias que ahora están justo delante.</p>
<p class="de">Diese Kluft bleibt nicht auf abstrakte Theorie beschränkt. Die Kennzahl der <a href="/blog/long-term-holder-supply.php">langfristigen Halter (LTH)</a> hat über die Zyklen hinweg fast dasselbe Muster wiederholt — in den Erholungen von 2017, 2021 und 2023-24 gleichermaßen erreichte sie ihren Höhepunkt in der dunkelsten Phase des Bärenmarktes und ging dann allmählich zurück, während die Erholung reifte. Anders gesagt: Dieselbe Kohorte, die „die härteste Phase durchzustehen" schaffte, hält nicht automatisch bis zur „Phase mit der größten Belohnung" durch. Ein Plan, der erfolgreich die Angstphase überstand, bricht erneut zusammen — angesichts genau der entgegengesetzten Versuchung: dem Drang, jetzt greifbare Gewinne zu sichern.</p>
<p class="fr">Cet écart ne reste pas confiné à la théorie abstraite. L'indicateur de l'<a href="/blog/long-term-holder-supply.php">offre des détenteurs de long terme (LTH)</a> a répété presque le même schéma à chaque cycle — dans les reprises de 2017, 2021 et 2023-24 tout autant, il a atteint son sommet dans la phase la plus sombre du marché baissier, puis a progressivement diminué à mesure que la reprise mûrissait. Autrement dit, la cohorte même qui a supporté « la phase la plus dure à traverser » ne tient pas automatiquement jusqu'à « la phase la plus rémunératrice ». Un plan qui a réussi à survivre à la phase de peur s'effondre de nouveau face à la tentation exactement inverse — l'envie de sécuriser des gains désormais bien visibles.</p>
<p class="pt">Essa lacuna não fica confinada à teoria abstrata. O indicador de <a href="/blog/long-term-holder-supply.php">oferta de detentores de longo prazo (LTH)</a> repetiu quase o mesmo padrão em cada ciclo — nas recuperações de 2017, 2021 e 2023-24 igualmente, ele atingiu o pico no trecho mais sombrio do mercado em baixa e depois diminuiu gradualmente à medida que a recuperação amadurecia. Em outras palavras, a mesma coorte que aguentou "o trecho mais difícil de suportar" não aguenta automaticamente até "o trecho de maior recompensa". Um plano que teve sucesso em sobreviver à fase do medo desmorona novamente diante da tentação exatamente oposta — o impulso de garantir ganhos que agora estão bem diante dos olhos.</p>
<p class="tr">Bu fark soyut teoriyle sınırlı kalmıyor. <a href="/blog/long-term-holder-supply.php">Uzun vadeli sahip (LTH) arzı</a> göstergesi, döngüler boyunca neredeyse aynı deseni tekrarladı — 2017, 2021 ve 2023-24 toparlanmalarının hepsinde bu gösterge, ayı piyasasının en karanlık kesitinde zirve yaptı ve ardından toparlanma olgunlaştıkça yavaş yavaş azaldı. Başka bir deyişle, "en dayanılması zor kesiti" atlatan aynı kohort, otomatik olarak "en büyük ödülün olduğu kesiti" de atlatmuyor. Korku evresinden geçmeyi başaran bir plan, tam olarak tersi bir cazibe karşısında — şu an gözünün önünde duran kazancı kesinleştirme dürtüsü — yeniden çöküyor.</p>
<p class="vi">Khoảng cách này không chỉ nằm trong lý thuyết trừu tượng. Chỉ số <a href="/blog/long-term-holder-supply.php">nguồn cung của người nắm giữ dài hạn (LTH)</a> đã lặp lại gần như cùng một khuôn mẫu qua các chu kỳ — trong các đợt phục hồi năm 2017, 2021 và 2023-24 đều như vậy, chỉ số này đạt đỉnh ở giai đoạn tăm tối nhất của thị trường giá xuống rồi giảm dần khi sự phục hồi chín muồi. Nói cách khác, chính nhóm đã "chịu đựng được giai đoạn khó chịu đựng nhất" lại không tự động chịu đựng được đến "giai đoạn có phần thưởng lớn nhất". Một kế hoạch đã thành công vượt qua giai đoạn sợ hãi lại sụp đổ lần nữa trước cám dỗ hoàn toàn ngược lại — sự thôi thúc muốn chốt lời ngay trước mắt.</p>

<p class="ko">이 패턴이 흥미로운 건, 두 유혹이 겉보기엔 정반대 감정처럼 보인다는 데 있다. 하락장에서 계획을 깨는 유혹은 공포에서 오고, 상승장에서 계획을 깨는 유혹은 탐욕에서 온다. 그런데 쌍곡선 할인의 관점에서 보면 이 둘은 같은 메커니즘의 서로 다른 얼굴일 뿐이다 — 두 경우 모두 "지금 당장의 확실한 결과"가 "미래의 더 나은 기대값"을 압도한다. 하락장에서는 "지금 팔아서 확실히 손실을 멈추는 것"이, 상승장에서는 "지금 팔아서 확실히 수익을 챙기는 것"이 똑같은 방식으로 β라는 할인 계수의 지배를 받는다. 그래서 손실 회피만으로는 이 붕괴의 절반밖에 설명하지 못한다 — 나머지 절반은 손실과 무관하게, 그저 지금 이 순간이 미래보다 압도적으로 크게 느껴지기 때문에 일어난다.</p>
<p class="en">What makes this pattern interesting is that the two temptations look, on the surface, like opposite emotions. In a downturn, the temptation to break a plan comes from fear; in an uptrend, it comes from greed. But from the standpoint of hyperbolic discounting, these are just two faces of the same mechanism — in both cases, "a certain outcome right now" overwhelms "a better expected value in the future." In a downturn, "selling now to definitely stop the loss," and in an uptrend, "selling now to definitely lock in the gain," are governed the exact same way by the discount factor β. That's why loss aversion alone explains only half of this collapse — the other half happens independent of loss or gain, simply because this exact moment feels overwhelmingly larger than the future does.</p>
<p class="ja">このパターンが興味深いのは、二つの誘惑が表面上は正反対の感情のように見えるという点にある。弱気相場で計画を破る誘惑は恐怖から来て、強気相場で計画を破る誘惑は貪欲から来る。しかし双曲割引の観点から見れば、この二つは同じメカニズムの異なる顔にすぎない——どちらの場合も「今すぐの確実な結果」が「未来のより良い期待値」を圧倒する。弱気相場では「今売って確実に損失を止めること」が、強気相場では「今売って確実に利益を確保すること」が、まったく同じ方法でβという割引係数に支配される。だから損失回避だけではこの崩壊の半分しか説明できない——残りの半分は、損失とは無関係に、ただ今この瞬間が未来よりも圧倒的に大きく感じられるために起こる。</p>
<p class="es">Lo que hace interesante este patrón es que las dos tentaciones parecen, en la superficie, emociones opuestas. En una caída, la tentación de romper un plan viene del miedo; en una subida, viene de la codicia. Pero desde la perspectiva del descuento hiperbólico, ambas son solo dos caras del mismo mecanismo —en ambos casos, "un resultado seguro ahora mismo" abruma a "un mejor valor esperado en el futuro". En una caída, "vender ahora para detener con certeza la pérdida", y en una subida, "vender ahora para asegurar con certeza la ganancia", se rigen exactamente de la misma manera por el factor de descuento β. Por eso la aversión a la pérdida por sí sola solo explica la mitad de este derrumbe —la otra mitad ocurre independientemente de la pérdida o ganancia, simplemente porque este momento exacto se siente abrumadoramente más grande que el futuro.</p>
<p class="de">Was dieses Muster interessant macht, ist, dass die beiden Versuchungen an der Oberfläche wie entgegengesetzte Emotionen wirken. In einem Abschwung kommt die Versuchung, einen Plan zu brechen, aus Angst; in einem Aufschwung kommt sie aus Gier. Aus Sicht des hyperbolischen Diskontierens sind dies jedoch nur zwei Gesichter desselben Mechanismus — in beiden Fällen überwältigt „ein sicheres Ergebnis genau jetzt" den „besseren erwarteten Wert in der Zukunft". Im Abschwung wird „jetzt verkaufen, um den Verlust sicher zu stoppen", im Aufschwung „jetzt verkaufen, um den Gewinn sicher zu sichern" — beides genau gleich vom Diskontfaktor β beherrscht. Deshalb erklärt Verlustaversion allein nur die Hälfte dieses Zusammenbruchs — die andere Hälfte geschieht unabhängig von Verlust oder Gewinn, einfach weil sich genau dieser Moment überwältigend größer anfühlt als die Zukunft.</p>
<p class="fr">Ce qui rend ce schéma intéressant, c'est que les deux tentations ressemblent, en apparence, à des émotions opposées. Dans une baisse, la tentation de rompre un plan vient de la peur ; dans une hausse, elle vient de l'avidité. Mais du point de vue de l'actualisation hyperbolique, ce ne sont que deux visages du même mécanisme — dans les deux cas, « un résultat certain maintenant » écrase « une meilleure valeur attendue dans le futur ». Dans une baisse, « vendre maintenant pour arrêter à coup sûr la perte », et dans une hausse, « vendre maintenant pour sécuriser à coup sûr le gain », sont régis exactement de la même façon par le facteur d'actualisation β. C'est pourquoi l'aversion aux pertes seule n'explique que la moitié de cet effondrement — l'autre moitié se produit indépendamment de la perte ou du gain, simplement parce que ce moment précis se ressent comme écrasant face au futur.</p>
<p class="pt">O que torna esse padrão interessante é que as duas tentações parecem, na superfície, emoções opostas. Em uma queda, a tentação de quebrar um plano vem do medo; em uma alta, vem da ganância. Mas do ponto de vista do desconto hiperbólico, essas são apenas duas faces do mesmo mecanismo — em ambos os casos, "um resultado certo agora mesmo" domina "um valor esperado melhor no futuro". Em uma queda, "vender agora para parar com certeza a perda", e em uma alta, "vender agora para garantir com certeza o ganho", são regidos exatamente da mesma forma pelo fator de desconto β. É por isso que a aversão à perda sozinha explica apenas metade desse colapso — a outra metade acontece independentemente de perda ou ganho, simplesmente porque este exato momento parece esmagadoramente maior do que o futuro.</p>
<p class="tr">Bu deseni ilginç kılan şey, iki cazibenin de yüzeyde birbirine zıt duygular gibi görünmesidir. Düşüş piyasasında planı bozma cazibesi korkudan gelir, yükseliş piyasasında ise açgözlülükten. Ama hiperbolik iskonto açısından bakıldığında bu ikisi aynı mekanizmanın yalnızca iki farklı yüzüdür — her iki durumda da "tam şimdi kesin bir sonuç", "gelecekte daha iyi bir beklenen değeri" ezip geçer. Düşüşte "kaybı kesin olarak durdurmak için şimdi satmak", yükselişte ise "kazancı kesin olarak cebe atmak için şimdi satmak", tamamen aynı şekilde β iskonto katsayısı tarafından yönetilir. Bu yüzden kayıptan kaçınma tek başına bu çöküşün yalnızca yarısını açıklar — diğer yarısı kayıp ya da kazançtan bağımsız olarak, sadece tam da bu an geleceğe kıyasla ezici derecede büyük hissettirdiği için gerçekleşir.</p>
<p class="vi">Điều khiến khuôn mẫu này thú vị là hai cám dỗ trông bề ngoài giống như những cảm xúc đối lập. Trong một đợt giảm, cám dỗ phá vỡ kế hoạch đến từ nỗi sợ; trong một đợt tăng, nó đến từ lòng tham. Nhưng từ góc độ chiết khấu hyperbol, đây chỉ là hai bộ mặt của cùng một cơ chế — trong cả hai trường hợp, "một kết quả chắc chắn ngay bây giờ" áp đảo "một giá trị kỳ vọng tốt hơn trong tương lai". Trong đợt giảm, "bán ngay để chắc chắn dừng lỗ", và trong đợt tăng, "bán ngay để chắc chắn chốt lời", đều bị chi phối theo đúng cùng một cách bởi hệ số chiết khấu β. Đó là lý do tại sao chỉ riêng ác cảm mất mát chỉ giải thích được một nửa sự sụp đổ này — nửa còn lại xảy ra bất kể lãi hay lỗ, đơn giản vì chính khoảnh khắc này cảm thấy lớn áp đảo so với tương lai.</p>

<h2 class="ko">유일하게 검증된 해법: 오디세우스의 돛대</h2>
<h2 class="en">The One Solution That's Actually Been Tested: Odysseus's Mast</h2>
<h2 class="ja">唯一検証された解決策:オデュッセウスの帆柱</h2>
<h2 class="es">La Única Solución Realmente Probada: El Mástil de Ulises</h2>
<h2 class="de">Die einzige tatsächlich getestete Lösung: Odysseus' Mast</h2>
<h2 class="fr">La Seule Solution Réellement Testée : Le Mât d'Ulysse</h2>
<h2 class="pt">A Única Solução Realmente Testada: O Mastro de Ulisses</h2>
<h2 class="tr">Gerçekten Test Edilmiş Tek Çözüm: Odysseus'un Direği</h2>
<h2 class="vi">Giải Pháp Duy Nhất Thực Sự Được Kiểm Chứng: Cột Buồm Của Odysseus</h2>

<p class="ko">나바 애쉬라프(Nava Ashraf), 딘 카를란(Dean Karlan), 웨슬리 인(Wesley Yin)이 2006년 저널 오브 이코노믹스(Quarterly Journal of Economics)에 발표한 필리핀 현장 실험은 이 문제에 대한 가장 직접적인 실증 근거를 제공한다. 이들은 기존 은행 고객 710명을 대상으로 목표 금액이나 목표 날짜에 도달하기 전까지는 인출이 제한되는 "SEED" 저축 상품을 제안했고, 28.4%인 202명이 이를 받아들였다. 12개월 뒤, 이 상품에 가입한 집단의 평균 저축 잔액은 대조군보다 약 81%포인트 더 늘어난 것으로 나타났다. 그리고 이 상품을 가장 적극적으로 선택한 집단은 사전 설문에서 스스로 "쌍곡선형(현재 편향)" 성향으로 분류된 사람들, 그중에서도 여성이었다.</p>
<p class="en">A Philippine field experiment by Nava Ashraf, Dean Karlan, and Wesley Yin, published in the Quarterly Journal of Economics in 2006, provides the most direct empirical evidence on this problem. They offered 710 existing bank clients a "SEED" savings product whose withdrawals were locked until a target amount or target date was reached, and 202 people — 28.4% — accepted it. Twelve months later, the average savings balance of the group that signed up had risen by roughly 81 percentage points more than the control group. And the group that most actively chose this product was the one that a baseline survey had classified as "hyperbolic," or present-biased — specifically, women within that group.</p>
<p class="ja">ナバ・アシュラフ(Nava Ashraf)、ディーン・カーラン(Dean Karlan)、ウェズリー・イン(Wesley Yin)が2006年にクォータリー・ジャーナル・オブ・エコノミクス誌に発表したフィリピンでのフィールド実験は、この問題に対する最も直接的な実証根拠を提供する。彼らは既存の銀行顧客710人を対象に、目標金額または目標日付に達するまで引き出しが制限される「SEED」貯蓄商品を提案し、28.4%にあたる202人がこれを受け入れた。12か月後、この商品に加入した集団の平均貯蓄残高は対照群よりも約81パーセントポイント多く増加していたことが分かった。そしてこの商品を最も積極的に選んだ集団は、事前アンケートで自ら「双曲型(現在偏向)」傾向と分類された人々、その中でも女性だった。</p>
<p class="es">Un experimento de campo en Filipinas realizado por Nava Ashraf, Dean Karlan y Wesley Yin, publicado en el Quarterly Journal of Economics en 2006, ofrece la evidencia empírica más directa sobre este problema. Propusieron a 710 clientes existentes de un banco un producto de ahorro "SEED" cuyos retiros quedaban bloqueados hasta alcanzar un monto o una fecha objetivo, y 202 personas —el 28.4%— lo aceptaron. Doce meses después, el saldo promedio de ahorro del grupo que se inscribió había aumentado aproximadamente 81 puntos porcentuales más que el grupo de control. Y el grupo que eligió más activamente este producto fue el que una encuesta inicial había clasificado como de tendencia "hiperbólica" o sesgada hacia el presente —específicamente, las mujeres dentro de ese grupo.</p>
<p class="de">Ein philippinisches Feldexperiment von Nava Ashraf, Dean Karlan und Wesley Yin, veröffentlicht 2006 im Quarterly Journal of Economics, liefert die direkteste empirische Evidenz zu diesem Problem. Sie boten 710 bestehenden Bankkunden ein „SEED"-Sparprodukt an, dessen Abhebungen bis zum Erreichen eines Zielbetrags oder Zieldatums gesperrt waren, und 202 Personen — 28,4% — nahmen es an. Zwölf Monate später war das durchschnittliche Sparguthaben der Gruppe, die sich angemeldet hatte, um rund 81 Prozentpunkte stärker gestiegen als in der Kontrollgruppe. Und die Gruppe, die dieses Produkt am aktivsten wählte, war jene, die eine Vorabbefragung als „hyperbolisch", also gegenwartsverzerrt, eingestuft hatte — insbesondere die Frauen innerhalb dieser Gruppe.</p>
<p class="fr">Une expérience de terrain aux Philippines menée par Nava Ashraf, Dean Karlan et Wesley Yin, publiée dans le Quarterly Journal of Economics en 2006, fournit la preuve empirique la plus directe sur ce problème. Ils ont proposé à 710 clients existants d'une banque un produit d'épargne « SEED » dont les retraits étaient bloqués jusqu'à l'atteinte d'un montant ou d'une date cible, et 202 personnes — 28,4 % — l'ont accepté. Douze mois plus tard, le solde d'épargne moyen du groupe inscrit avait augmenté d'environ 81 points de pourcentage de plus que le groupe témoin. Et le groupe qui a le plus activement choisi ce produit était celui qu'une enquête initiale avait classé comme « hyperbolique », c'est-à-dire biaisé vers le présent — en particulier les femmes de ce groupe.</p>
<p class="pt">Um experimento de campo nas Filipinas conduzido por Nava Ashraf, Dean Karlan e Wesley Yin, publicado no Quarterly Journal of Economics em 2006, fornece a evidência empírica mais direta sobre esse problema. Eles ofereceram a 710 clientes bancários existentes um produto de poupança "SEED" cujos saques ficavam bloqueados até se atingir um valor-alvo ou data-alvo, e 202 pessoas — 28,4% — aceitaram. Doze meses depois, o saldo médio de poupança do grupo que aderiu havia aumentado cerca de 81 pontos percentuais a mais do que o grupo de controle. E o grupo que mais ativamente escolheu esse produto foi o que uma pesquisa inicial classificara como "hiperbólico", ou enviesado para o presente — especificamente, as mulheres dentro desse grupo.</p>
<p class="tr">Nava Ashraf, Dean Karlan ve Wesley Yin'in 2006'da Quarterly Journal of Economics'te yayımlanan Filipinler'deki saha deneyi, bu soruna dair en doğrudan ampirik kanıtı sunuyor. Mevcut 710 banka müşterisine, hedef tutara ya da hedef tarihe ulaşılana kadar para çekmenin kilitli kaldığı bir "SEED" tasarruf ürünü önerdiler ve %28,4'ü, yani 202 kişi, bunu kabul etti. On iki ay sonra, bu ürüne kaydolan grubun ortalama tasarruf bakiyesinin kontrol grubuna göre yaklaşık 81 yüzde puanı daha fazla arttığı görüldü. Ve bu ürünü en aktif şekilde seçen grup, ön ankette kendini "hiperbolik", yani şimdiki zaman yanlı olarak sınıflandıran kişiler, özellikle de bu grup içindeki kadınlardı.</p>
<p class="vi">Một thí nghiệm thực địa tại Philippines của Nava Ashraf, Dean Karlan và Wesley Yin, đăng trên Quarterly Journal of Economics năm 2006, cung cấp bằng chứng thực nghiệm trực tiếp nhất về vấn đề này. Họ đề nghị 710 khách hàng ngân hàng hiện có một sản phẩm tiết kiệm "SEED" mà việc rút tiền bị khóa cho đến khi đạt số tiền mục tiêu hoặc ngày mục tiêu, và 202 người — 28,4% — đã chấp nhận. Mười hai tháng sau, số dư tiết kiệm trung bình của nhóm đăng ký đã tăng thêm khoảng 81 điểm phần trăm so với nhóm đối chứng. Và nhóm chọn sản phẩm này tích cực nhất là nhóm mà một khảo sát ban đầu đã phân loại là "gần-hyperbol", tức thiên vị hiện tại — cụ thể là phụ nữ trong nhóm đó.</p>

<p class="ko">이 실험이 알려주는 교훈은 단순하다 — 자기통제 문제는 "더 굳게 마음먹기"로 해결되지 않는다. 해결책은 유혹이 도달하기 전에, 선택 자체를 구조적으로 차단하는 것이다. 비트코인 투자자에게 이는 구체적인 형태로 번역된다: <a href="/blog/dca-vs-lump-sum.php">자동화된 정기 매수·매도</a>로 그 순간의 판단을 아예 배제하거나, 일정 기간 인출이 잠기는 볼트·타임락 상품을 활용하거나, 매도 목표가를 미리 공개적으로 선언해 나중에 번복하는 데 사회적 비용을 부과하는 방식이다. 세 방법의 공통점은 모두 "실행하는 자아"가 그 순간에 마음을 바꿀 자유 자체를 빼앗는다는 데 있다 — 설득이 아니라 설계로 문제를 푸는 것이다.</p>
<p class="en">The lesson this experiment teaches is simple: a self-control problem doesn't get solved by "resolving to be stronger." The solution is to structurally block the choice itself before temptation arrives. For a Bitcoin investor, that translates into concrete forms: eliminating the in-the-moment decision entirely through <a href="/blog/dca-vs-lump-sum.php">automated recurring buys and sells</a>, using vault or time-lock products whose withdrawals stay locked for a set period, or publicly declaring a sell target in advance so that reversing it later carries a social cost. What all three share is that they strip the "doing self" of the very freedom to change its mind in the moment — solving the problem through design, not persuasion.</p>
<p class="ja">この実験が教える教訓はシンプルだ——自己統制の問題は「もっと固く心に決める」ことでは解決しない。解決策は、誘惑が到達する前に、選択そのものを構造的に遮断することだ。ビットコイン投資家にとってこれは具体的な形に翻訳される:<a href="/blog/dca-vs-lump-sum.php">自動化された定期的な売買</a>でその瞬間の判断をそもそも排除する、一定期間引き出しがロックされるボールト・タイムロック商品を活用する、売却目標価格をあらかじめ公に宣言して後で撤回することに社会的コストを課す、といった方法だ。三つの方法に共通するのは、いずれも「実行する自我」からその瞬間に心変わりする自由そのものを奪うという点にある——説得ではなく設計で問題を解くのだ。</p>
<p class="es">La lección que enseña este experimento es simple: un problema de autocontrol no se resuelve "decidiendo ser más fuerte". La solución es bloquear estructuralmente la elección misma antes de que llegue la tentación. Para un inversor de Bitcoin, esto se traduce en formas concretas: eliminar por completo la decisión del momento mediante <a href="/blog/dca-vs-lump-sum.php">compras y ventas periódicas automatizadas</a>, usar productos de bóveda o bloqueo temporal cuyos retiros permanecen cerrados durante un período fijo, o declarar públicamente de antemano un precio objetivo de venta para que revertirlo después tenga un costo social. Lo que comparten las tres es que despojan al "yo ejecutor" de la propia libertad de cambiar de opinión en el momento —resolviendo el problema mediante diseño, no persuasión.</p>
<p class="de">Die Lehre aus diesem Experiment ist einfach: Ein Selbstkontrollproblem wird nicht dadurch gelöst, dass man sich vornimmt, „stärker zu sein". Die Lösung besteht darin, die Wahl selbst strukturell zu blockieren, bevor die Versuchung eintrifft. Für einen Bitcoin-Anleger übersetzt sich das in konkrete Formen: die Entscheidung im Moment durch <a href="/blog/dca-vs-lump-sum.php">automatisierte, wiederkehrende Käufe und Verkäufe</a> ganz auszuschalten, Vault- oder Zeitsperr-Produkte zu nutzen, deren Abhebungen für einen festgelegten Zeitraum gesperrt bleiben, oder im Voraus öffentlich ein Verkaufsziel zu erklären, sodass eine spätere Rücknahme soziale Kosten verursacht. Allen drei Wegen gemeinsam ist, dass sie dem „handelnden Ich" genau die Freiheit nehmen, es sich im Moment anders zu überlegen — das Problem wird durch Design gelöst, nicht durch Überredung.</p>
<p class="fr">La leçon que cette expérience enseigne est simple : un problème de maîtrise de soi ne se résout pas en « décidant d'être plus fort ». La solution consiste à bloquer structurellement le choix lui-même avant que la tentation n'arrive. Pour un investisseur en Bitcoin, cela se traduit en formes concrètes : éliminer entièrement la décision du moment grâce à des <a href="/blog/dca-vs-lump-sum.php">achats et ventes récurrents automatisés</a>, utiliser des produits de coffre ou de blocage temporel dont les retraits restent verrouillés pendant une période fixée, ou déclarer publiquement à l'avance un objectif de vente afin qu'y renoncer plus tard entraîne un coût social. Ce que ces trois méthodes ont en commun, c'est qu'elles privent le « moi exécutant » de la liberté même de changer d'avis sur le moment — résoudre le problème par la conception, pas par la persuasion.</p>
<p class="pt">A lição que esse experimento ensina é simples: um problema de autocontrole não se resolve "decidindo ser mais forte". A solução é bloquear estruturalmente a própria escolha antes que a tentação chegue. Para um investidor de Bitcoin, isso se traduz em formas concretas: eliminar totalmente a decisão do momento por meio de <a href="/blog/dca-vs-lump-sum.php">compras e vendas recorrentes automatizadas</a>, usar produtos de cofre ou bloqueio temporal cujos saques ficam travados por um período fixo, ou declarar publicamente com antecedência uma meta de venda para que revertê-la depois carregue um custo social. O que essas três formas têm em comum é que todas retiram do "eu executor" a própria liberdade de mudar de ideia no momento — resolvendo o problema pelo design, não pela persuasão.</p>
<p class="tr">Bu deneyin öğrettiği ders basittir — bir öz-denetim sorunu "daha güçlü irade göstermeye karar vererek" çözülmez. Çözüm, cazibe gelmeden önce seçimin kendisini yapısal olarak engellemektir. Bir Bitcoin yatırımcısı için bu, somut biçimlere dönüşür: <a href="/blog/dca-vs-lump-sum.php">otomatikleştirilmiş düzenli alım-satımlarla</a> o anki kararı tamamen ortadan kaldırmak, belirli bir süre boyunca para çekmenin kilitli kaldığı kasa/zaman kilidi ürünlerini kullanmak ya da bir satış hedefini önceden herkese açık şekilde ilan ederek sonradan bundan dönmenin sosyal bir bedeli olmasını sağlamak. Bu üç yöntemin ortak noktası, hepsinin "uygulayan ben"in o anda fikrini değiştirme özgürlüğünün tam da kendisini elinden almasıdır — sorunu ikna yoluyla değil, tasarımla çözmek.</p>
<p class="vi">Bài học mà thí nghiệm này mang lại rất đơn giản — vấn đề tự kiểm soát không được giải quyết bằng cách "quyết tâm mạnh mẽ hơn". Giải pháp là chặn đứng về mặt cấu trúc chính sự lựa chọn đó trước khi cám dỗ ập đến. Đối với một nhà đầu tư Bitcoin, điều này chuyển thành những hình thức cụ thể: loại bỏ hoàn toàn quyết định tại thời điểm đó thông qua <a href="/blog/dca-vs-lump-sum.php">mua bán định kỳ tự động hóa</a>, sử dụng các sản phẩm hầm/khóa thời gian mà việc rút tiền bị khóa trong một khoảng thời gian cố định, hoặc công khai tuyên bố trước một mức giá bán mục tiêu để việc thay đổi sau này phải chịu một cái giá xã hội. Điểm chung của cả ba cách là chúng đều tước đi khỏi "cái tôi hành động" chính quyền tự do thay đổi ý định vào thời điểm đó — giải quyết vấn đề bằng thiết kế, không phải bằng thuyết phục.</p>

<h2 class="ko">결론: 문제는 의지가 아니라 설계다</h2>
<h2 class="en">Conclusion: The Problem Is Design, Not Willpower</h2>
<h2 class="ja">結論:問題は意志ではなく設計だ</h2>
<h2 class="es">Conclusión: El Problema Es el Diseño, No la Fuerza de Voluntad</h2>
<h2 class="de">Fazit: Das Problem ist Design, nicht Willenskraft</h2>
<h2 class="fr">Conclusion : Le Problème, C'est la Conception, Pas la Volonté</h2>
<h2 class="pt">Conclusão: O Problema É o Design, Não a Força de Vontade</h2>
<h2 class="tr">Sonuç: Sorun İrade Değil, Tasarımdır</h2>
<h2 class="vi">Kết Luận: Vấn Đề Là Thiết Kế, Không Phải Ý Chí</h2>

<p class="ko">"다음엔 더 강한 의지로 계획을 지키겠다"는 다짐은 통계적으로 거의 항상 실패한다 — 나이브한 투자자일수록 이 다짐을 더 자주, 더 진심으로 반복하기 때문이다. <a href="/blog/rebalancing-premium-discipline-gap.php">리밸런싱 규율이 가장 절실할 때 가장 쉽게 깨지는 이유</a>도, <a href="/blog/trade-journal-repeat-mistakes.php">매매일지를 쓰고도 같은 실수를 반복하는 이유</a>도 결국 같은 뿌리에서 나온다 — 계획을 세우는 자아와 그 계획을 실행할 자아가 애초에 같은 할인율로 세상을 보고 있지 않다는 사실이다. 이 글이 전하려는 단 하나의 주장은 이렇다: 그 간극을 인정하고, 유혹이 오기 전에 선택지 자체를 스스로에게서 빼앗아두는 사람만이, 실제로 계획한 대로 행동한다.</p>
<p class="en">The resolution to "keep the plan next time through sheer stronger willpower" fails almost every time, statistically — and the more naive an investor is, the more often, and the more sincerely, they repeat that same resolution. <a href="/blog/rebalancing-premium-discipline-gap.php">Why rebalancing discipline breaks down exactly when it matters most</a>, and <a href="/blog/trade-journal-repeat-mistakes.php">why keeping a trade journal still doesn't stop the same mistake from repeating</a>, both trace back to the same root: the self who makes the plan and the self who has to execute it were never looking at the world through the same discount rate to begin with. The single argument this piece wants to leave you with is this — only the person who acknowledges that gap, and strips the choice itself away from themselves before temptation arrives, actually ends up acting the way they planned to.</p>
<p class="ja">「次はもっと強い意志で計画を守る」という決意は、統計的にはほぼ毎回失敗する——ナイーブな投資家ほど、この決意をより頻繁に、より本気で繰り返すからだ。<a href="/blog/rebalancing-premium-discipline-gap.php">リバランスの規律が最も切実なときに最も簡単に崩れる理由</a>も、<a href="/blog/trade-journal-repeat-mistakes.php">売買日誌をつけても同じ過ちを繰り返す理由</a>も、結局は同じ根から生まれている——計画を立てる自我と、その計画を実行する自我が、そもそも同じ割引率で世界を見ていないという事実だ。本稿が伝えたいたった一つの主張はこうだ:その乖離を認め、誘惑が来る前に選択肢そのものを自分自身から奪っておく人だけが、実際に計画した通りに行動する。</p>
<p class="es">La resolución de "esta vez mantendré el plan con más fuerza de voluntad" falla casi siempre, estadísticamente hablando —y cuanto más ingenuo es un inversor, más frecuente y sinceramente repite esa misma resolución. <a href="/blog/rebalancing-premium-discipline-gap.php">Por qué la disciplina de reequilibrio se rompe justo cuando más importa</a>, y <a href="/blog/trade-journal-repeat-mistakes.php">por qué llevar un diario de operaciones tampoco impide repetir el mismo error</a>, ambos se remontan a la misma raíz: el yo que hace el plan y el yo que debe ejecutarlo nunca miraron el mundo con la misma tasa de descuento desde un principio. El único argumento que este artículo quiere dejarte es este: solo la persona que reconoce esa brecha, y se arrebata a sí misma la propia elección antes de que llegue la tentación, termina realmente actuando como había planeado.</p>
<p class="de">Der Vorsatz „nächstes Mal halte ich den Plan mit stärkerer Willenskraft ein" scheitert statistisch gesehen fast immer — und je naiver ein Anleger ist, desto häufiger und desto aufrichtiger wiederholt er genau diesen Vorsatz. <a href="/blog/rebalancing-premium-discipline-gap.php">Warum Rebalancing-Disziplin ausgerechnet dann zusammenbricht, wenn sie am wichtigsten ist</a>, und <a href="/blog/trade-journal-repeat-mistakes.php">warum ein Handelstagebuch trotzdem nicht verhindert, dass sich derselbe Fehler wiederholt</a>, gehen beide auf dieselbe Wurzel zurück: Das Ich, das den Plan macht, und das Ich, das ihn ausführen muss, haben die Welt von Anfang an nicht mit demselben Abzinsungssatz betrachtet. Die einzige Aussage, die dieser Beitrag vermitteln will, lautet: Nur wer diese Kluft anerkennt und sich die Wahl selbst entzieht, bevor die Versuchung eintrifft, handelt am Ende tatsächlich so, wie er es geplant hatte.</p>
<p class="fr">La résolution « la prochaine fois, je tiendrai le plan avec plus de volonté » échoue presque à chaque fois, statistiquement — et plus un investisseur est naïf, plus souvent, et plus sincèrement, il répète cette même résolution. <a href="/blog/rebalancing-premium-discipline-gap.php">Pourquoi la discipline de rééquilibrage cède exactement quand elle compte le plus</a>, et <a href="/blog/trade-journal-repeat-mistakes.php">pourquoi tenir un journal de trading n'empêche toujours pas de répéter la même erreur</a>, remontent tous deux à la même racine : le moi qui fait le plan et le moi qui doit l'exécuter n'ont jamais regardé le monde avec le même taux d'actualisation dès le départ. Le seul argument que cet article veut vous laisser est celui-ci : seule la personne qui reconnaît cet écart, et qui s'arrache à elle-même le choix avant que la tentation n'arrive, finit réellement par agir comme elle l'avait prévu.</p>
<p class="pt">A resolução de "da próxima vez vou manter o plano com mais força de vontade" falha quase sempre, estatisticamente — e quanto mais ingênuo é um investidor, mais frequente e sinceramente ele repete essa mesma resolução. <a href="/blog/rebalancing-premium-discipline-gap.php">Por que a disciplina de rebalanceamento se rompe justo quando mais importa</a>, e <a href="/blog/trade-journal-repeat-mistakes.php">por que manter um diário de operações ainda não impede que o mesmo erro se repita</a>, ambos remontam à mesma raiz: o eu que faz o plano e o eu que precisa executá-lo nunca enxergaram o mundo com a mesma taxa de desconto, desde o início. O único argumento que este artigo quer deixar é este: só a pessoa que reconhece essa lacuna, e retira de si mesma a própria escolha antes que a tentação chegue, de fato acaba agindo como havia planejado.</p>
<p class="tr">"Bir dahaki sefere daha güçlü bir irade ile plana bağlı kalacağım" kararı istatistiksel olarak neredeyse her zaman başarısız olur — çünkü bir yatırımcı ne kadar naifse, bu kararı o kadar sık ve o kadar içtenlikle tekrarlar. <a href="/blog/rebalancing-premium-discipline-gap.php">Yeniden dengeleme disiplininin tam da en çok gerekli olduğu anda neden en kolay bozulduğu</a> ve <a href="/blog/trade-journal-repeat-mistakes.php">bir işlem günlüğü tutmanın bile aynı hatanın tekrarlanmasını neden engellemediği</a>, ikisi de aynı köke dayanır — planı yapan ben ile onu uygulaması gereken ben, en baştan beri dünyaya aynı iskonto oranıyla bakmıyordur. Bu yazının aktarmak istediği tek iddia şudur: bu farkı kabul eden ve cazibe gelmeden önce seçimin kendisini kendi elinden alan kişi, gerçekte planladığı gibi davranan tek kişidir.</p>
<p class="vi">Quyết tâm "lần sau tôi sẽ giữ vững kế hoạch bằng ý chí mạnh mẽ hơn" hầu như luôn thất bại về mặt thống kê — và nhà đầu tư càng ngây thơ thì càng lặp lại quyết tâm đó thường xuyên hơn, chân thành hơn. <a href="/blog/rebalancing-premium-discipline-gap.php">Vì sao kỷ luật tái cân bằng lại sụp đổ đúng vào lúc nó quan trọng nhất</a>, và <a href="/blog/trade-journal-repeat-mistakes.php">vì sao viết nhật ký giao dịch vẫn không ngăn được việc lặp lại cùng một sai lầm</a>, cả hai đều bắt nguồn từ cùng một gốc rễ: cái tôi lập kế hoạch và cái tôi phải thực hiện kế hoạch đó ngay từ đầu đã không nhìn thế giới bằng cùng một tỷ lệ chiết khấu. Luận điểm duy nhất mà bài viết này muốn để lại là: chỉ người thừa nhận khoảng cách đó, và tước đi khỏi chính mình quyền lựa chọn trước khi cám dỗ ập đến, mới thực sự hành động đúng như những gì họ đã lên kế hoạch.</p>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: Thaler, R.H. (1981), "Some Empirical Evidence on Dynamic Inconsistency", Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), "An Economic Theory of Self-Control", Journal of Political Economy, 89(2). Laibson, D. (1997), "Golden Eggs and Hyperbolic Discounting", Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), "Doing It Now or Later", American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), "Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines", Quarterly Journal of Economics, 121(2).</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Thaler, R.H. (1981), "Some Empirical Evidence on Dynamic Inconsistency," Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), "An Economic Theory of Self-Control," Journal of Political Economy, 89(2). Laibson, D. (1997), "Golden Eggs and Hyperbolic Discounting," Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), "Doing It Now or Later," American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), "Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines," Quarterly Journal of Economics, 121(2).</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: Thaler, R.H. (1981), "Some Empirical Evidence on Dynamic Inconsistency", Economics Letters, 8(3)。Thaler, R.H. &amp; Shefrin, H.M. (1981), "An Economic Theory of Self-Control", Journal of Political Economy, 89(2)。Laibson, D. (1997), "Golden Eggs and Hyperbolic Discounting", Quarterly Journal of Economics, 112(2)。O'Donoghue, T. &amp; Rabin, M. (1999), "Doing It Now or Later", American Economic Review, 89(1)。Ashraf, N., Karlan, D. &amp; Yin, W. (2006), "Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines", Quarterly Journal of Economics, 121(2)。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: Thaler, R.H. (1981), "Some Empirical Evidence on Dynamic Inconsistency", Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), "An Economic Theory of Self-Control", Journal of Political Economy, 89(2). Laibson, D. (1997), "Golden Eggs and Hyperbolic Discounting", Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), "Doing It Now or Later", American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), "Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines", Quarterly Journal of Economics, 121(2).</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: Thaler, R.H. (1981), „Some Empirical Evidence on Dynamic Inconsistency", Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), „An Economic Theory of Self-Control", Journal of Political Economy, 89(2). Laibson, D. (1997), „Golden Eggs and Hyperbolic Discounting", Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), „Doing It Now or Later", American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), „Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines", Quarterly Journal of Economics, 121(2).</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : Thaler, R.H. (1981), « Some Empirical Evidence on Dynamic Inconsistency », Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), « An Economic Theory of Self-Control », Journal of Political Economy, 89(2). Laibson, D. (1997), « Golden Eggs and Hyperbolic Discounting », Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), « Doing It Now or Later », American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), « Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines », Quarterly Journal of Economics, 121(2).</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: Thaler, R.H. (1981), “Some Empirical Evidence on Dynamic Inconsistency”, Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), “An Economic Theory of Self-Control”, Journal of Political Economy, 89(2). Laibson, D. (1997), “Golden Eggs and Hyperbolic Discounting”, Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), “Doing It Now or Later”, American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), “Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines”, Quarterly Journal of Economics, 121(2).</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: Thaler, R.H. (1981), “Some Empirical Evidence on Dynamic Inconsistency”, Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), “An Economic Theory of Self-Control”, Journal of Political Economy, 89(2). Laibson, D. (1997), “Golden Eggs and Hyperbolic Discounting”, Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), “Doing It Now or Later”, American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), “Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines”, Quarterly Journal of Economics, 121(2).</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: Thaler, R.H. (1981), “Some Empirical Evidence on Dynamic Inconsistency”, Economics Letters, 8(3). Thaler, R.H. &amp; Shefrin, H.M. (1981), “An Economic Theory of Self-Control”, Journal of Political Economy, 89(2). Laibson, D. (1997), “Golden Eggs and Hyperbolic Discounting”, Quarterly Journal of Economics, 112(2). O'Donoghue, T. &amp; Rabin, M. (1999), “Doing It Now or Later”, American Economic Review, 89(1). Ashraf, N., Karlan, D. &amp; Yin, W. (2006), “Tying Odysseus to the Mast: Evidence from a Commitment Savings Product in the Philippines”, Quarterly Journal of Economics, 121(2).</p>
<?php require __DIR__.'/_footer.php'; ?>
