<?php $slug = 'project-eleven-quantum-wallet-proof-satoshi-coins-excluded'; require __DIR__.'/_header.php'; ?>

<p class="ko">프로젝트 일레븐(Project Eleven)이 양자컴퓨터가 등장해 비트코인 지갑의 전자서명을 위조할 수 있게 되더라도 소유권을 증명할 수 있는 영지식증명(ZK) 도구의 시제품을 공개했다. 19일(현지시간) 코인데스크 등에 따르면, 이 증명은 애플 M5 맥북 에어의 CPU 코어 4개만으로 243밀리초 만에 생성되고 40밀리초 만에 검증되며, 메모리 사용량은 약 2기가바이트에 그친다. 기존 방식보다 약 16배 빠른 수치다. 다만 사토시 나카모토가 보유한 것으로 추정되는 약 110만 BTC를 포함해 2012년 이전에 만들어진 초기 방식의 주소들은 이 도구의 보호 대상에서 원천적으로 제외된다.</p>
<p class="en">Project Eleven has unveiled a prototype zero-knowledge proof that lets a Bitcoin wallet owner establish control even after a quantum computer becomes capable of forging its signatures. According to CoinDesk and other outlets on July 19, the proof runs on just four CPU cores of an Apple M5 MacBook Air, generating in 243 milliseconds and verifying in 40 milliseconds while using roughly 2 gigabytes of memory — about 16 times faster than a prior approach. The tool, however, structurally cannot help the roughly 1.1 million BTC believed to belong to Satoshi Nakamoto, along with any other address created before 2012 using Bitcoin's original, pre-hierarchical wallet format.</p>
<p class="ja">プロジェクト・イレブン(Project Eleven)は、量子コンピューターがビットコインウォレットの電子署名を偽造できるようになった後でも、所有者が自らの管理権を証明できるゼロ知識証明(ZK)ツールの試作版を公開した。7月19日(現地時間)、コインデスクなどの報道によれば、この証明はApple M5 MacBook AirのCPUコア4基だけで243ミリ秒で生成され、40ミリ秒で検証され、メモリ使用量は約2ギガバイトにとどまる。これは従来方式より約16倍速い数値だ。ただし、サトシ・ナカモトが保有するとされる約110万BTCを含め、2012年以前に作られた旧方式のアドレスは、このツールの保護対象から構造的に除外される。</p>
<p class="es">Project Eleven presentó un prototipo de prueba de conocimiento cero (ZK) que permite a un propietario de una billetera de Bitcoin demostrar su control incluso después de que una computadora cuántica sea capaz de falsificar sus firmas. Según CoinDesk y otros medios, el 19 de julio, la prueba se ejecuta con solo cuatro núcleos de CPU de una MacBook Air M5 de Apple, generándose en 243 milisegundos y verificándose en 40 milisegundos, con un uso de memoria de apenas unos 2 gigabytes — cerca de 16 veces más rápido que un método anterior. Sin embargo, la herramienta no puede ayudar, por diseño, a los aproximadamente 1,1 millones de BTC que se cree pertenecen a Satoshi Nakamoto, ni a ninguna otra dirección creada antes de 2012 con el formato original de billetera de Bitcoin, previo a las carteras jerárquicas.</p>
<p class="de">Project Eleven hat einen Prototyp eines Zero-Knowledge-Beweises vorgestellt, mit dem Besitzer einer Bitcoin-Wallet ihre Kontrolle auch dann nachweisen können, wenn ein Quantencomputer in der Lage ist, ihre Signaturen zu fälschen. Laut CoinDesk und anderen Medien vom 19. Juli läuft der Beweis mit nur vier CPU-Kernen eines Apple M5 MacBook Air, wird in 243 Millisekunden erzeugt und in 40 Millisekunden verifiziert, bei einem Speicherverbrauch von rund 2 Gigabyte — etwa 16-mal schneller als ein früherer Ansatz. Das Werkzeug kann jedoch strukturell nicht den rund 1,1 Millionen BTC helfen, die vermutlich Satoshi Nakamoto gehören, ebenso wenig wie jeder anderen vor 2012 im ursprünglichen, nicht-hierarchischen Wallet-Format erzeugten Adresse.</p>
<p class="fr">Project Eleven a dévoilé un prototype de preuve à divulgation nulle de connaissance (ZK) permettant au propriétaire d'un portefeuille Bitcoin de prouver son contrôle même après qu'un ordinateur quantique devienne capable de falsifier ses signatures. Selon CoinDesk et d'autres médias, le 19 juillet, la preuve s'exécute avec seulement quatre cœurs CPU d'un MacBook Air M5 d'Apple, se génère en 243 millisecondes et se vérifie en 40 millisecondes, pour une consommation mémoire d'environ 2 gigaoctets — soit environ 16 fois plus rapide qu'une méthode antérieure. L'outil ne peut toutefois pas, par construction, venir en aide aux quelque 1,1 million de BTC que l'on croit appartenir à Satoshi Nakamoto, ni à aucune autre adresse créée avant 2012 selon le format de portefeuille original, antérieur aux portefeuilles hiérarchiques.</p>
<p class="pt">A Project Eleven revelou um protótipo de prova de conhecimento zero (ZK) que permite ao dono de uma carteira Bitcoin comprovar seu controle mesmo depois que um computador quântico se torne capaz de falsificar suas assinaturas. Segundo o CoinDesk e outros veículos, em 19 de julho, a prova roda com apenas quatro núcleos de CPU de um MacBook Air M5 da Apple, sendo gerada em 243 milissegundos e verificada em 40 milissegundos, com uso de memória de cerca de 2 gigabytes — quase 16 vezes mais rápido que uma abordagem anterior. A ferramenta, porém, não consegue ajudar, por construção, os cerca de 1,1 milhão de BTC que se acredita pertencerem a Satoshi Nakamoto, nem qualquer outro endereço criado antes de 2012 no formato original de carteira, anterior às carteiras hierárquicas.</p>
<p class="tr">Project Eleven, bir kuantum bilgisayar imzaları sahteleyebilecek hale geldikten sonra bile bir Bitcoin cüzdanı sahibinin kontrolünü kanıtlamasına olanak tanıyan bir sıfır bilgi kanıtı (ZK) prototipini tanıttı. CoinDesk ve diğer kaynaklara göre 19 Temmuz'da, kanıt bir Apple M5 MacBook Air'in yalnızca dört CPU çekirdeğiyle çalışıyor; 243 milisaniyede üretiliyor, 40 milisaniyede doğrulanıyor ve yaklaşık 2 gigabayt bellek kullanıyor — önceki bir yönteme göre yaklaşık 16 kat daha hızlı. Ancak araç, yapısı gereği, Satoshi Nakamoto'ya ait olduğu düşünülen yaklaşık 1,1 milyon BTC'ye ya da 2012 öncesinde, hiyerarşik cüzdanlardan önceki orijinal formatta oluşturulmuş herhangi bir adrese yardımcı olamıyor.</p>
<p class="vi">Project Eleven đã công bố một nguyên mẫu bằng chứng không tiết lộ thông tin (ZK) cho phép chủ sở hữu ví Bitcoin chứng minh quyền kiểm soát ngay cả sau khi máy tính lượng tử có khả năng giả mạo chữ ký của họ. Theo CoinDesk và các nguồn khác vào ngày 19 tháng 7, bằng chứng này chạy chỉ với bốn lõi CPU của MacBook Air M5 của Apple, được tạo ra trong 243 mili giây và xác minh trong 40 mili giây, sử dụng khoảng 2 gigabyte bộ nhớ — nhanh hơn khoảng 16 lần so với phương pháp trước đó. Tuy nhiên, về mặt cấu trúc, công cụ này không thể giúp khoảng 1,1 triệu BTC được cho là thuộc về Satoshi Nakamoto, cũng như bất kỳ địa chỉ nào khác được tạo trước năm 2012 theo định dạng ví gốc, trước khi có ví phân cấp.</p>
<p class="id">Project Eleven memperkenalkan prototipe bukti zero-knowledge (ZK) yang memungkinkan pemilik dompet Bitcoin membuktikan kontrolnya bahkan setelah komputer kuantum mampu memalsukan tanda tangannya. Menurut CoinDesk dan media lain pada 19 Juli, bukti ini berjalan hanya dengan empat inti CPU dari Apple MacBook Air M5, dihasilkan dalam 243 milidetik dan diverifikasi dalam 40 milidetik, dengan penggunaan memori sekitar 2 gigabyte — sekitar 16 kali lebih cepat dari pendekatan sebelumnya. Namun, alat ini secara struktural tidak dapat membantu sekitar 1,1 juta BTC yang diyakini milik Satoshi Nakamoto, maupun alamat lain yang dibuat sebelum 2012 dengan format dompet asli sebelum dompet hierarkis.</p>
<p class="pl">Project Eleven zaprezentował prototyp dowodu z wiedzą zerową (ZK), który pozwala właścicielowi portfela Bitcoin udowodnić kontrolę nad nim nawet po tym, jak komputer kwantowy będzie w stanie sfałszować jego podpisy. Według CoinDesk i innych mediów z 19 lipca, dowód działa na zaledwie czterech rdzeniach CPU Apple MacBook Air M5, generuje się w 243 milisekundy i weryfikuje w 40 milisekund, zużywając około 2 gigabajtów pamięci — czyli około 16 razy szybciej niż poprzednia metoda. Narzędzie to jednak strukturalnie nie może pomóc około 1,1 miliona BTC, które uważa się za należące do Satoshiego Nakamoto, ani żadnemu innemu adresowi utworzonemu przed 2012 rokiem w oryginalnym formacie portfela, sprzed portfeli hierarchicznych.</p>
<p class="it">Project Eleven ha presentato un prototipo di prova a conoscenza zero (ZK) che consente al proprietario di un wallet Bitcoin di dimostrare il proprio controllo anche dopo che un computer quantistico sarà in grado di falsificarne le firme. Secondo CoinDesk e altre testate, il 19 luglio, la prova viene eseguita con soli quattro core CPU di un MacBook Air M5 di Apple, generata in 243 millisecondi e verificata in 40 millisecondi, con un utilizzo di memoria di circa 2 gigabyte — circa 16 volte più veloce di un metodo precedente. Lo strumento, tuttavia, non può strutturalmente aiutare i circa 1,1 milioni di BTC che si ritiene appartengano a Satoshi Nakamoto, né alcun altro indirizzo creato prima del 2012 nel formato originale del wallet, precedente ai wallet gerarchici.</p>
<p class="ru">Project Eleven представила прототип доказательства с нулевым разглашением (ZK), позволяющее владельцу биткоин-кошелька подтвердить контроль над ним даже после того, как квантовый компьютер сможет подделывать его подписи. По данным CoinDesk и других изданий от 19 июля, доказательство выполняется всего на четырёх ядрах CPU Apple MacBook Air M5, генерируется за 243 миллисекунды и проверяется за 40 миллисекунд при использовании около 2 гигабайт памяти — примерно в 16 раз быстрее прежнего метода. Однако инструмент структурно не способен помочь примерно 1,1 миллиона BTC, предположительно принадлежащих Сатоши Накамото, а также любому другому адресу, созданному до 2012 года в изначальном, доиерархическом формате кошелька.</p>
<p class="zh">Project Eleven公布了一款零知識證明(ZK)工具的原型,即使量子電腦具備偽造比特幣錢包簽章的能力,錢包所有者仍可藉此證明自己的控制權。根據CoinDesk等媒體7月19日報導,該證明僅需Apple M5 MacBook Air的四個CPU核心即可運作,生成僅需243毫秒,驗證僅需40毫秒,記憶體使用量約2GB——比先前的方法快了約16倍。不過,這項工具在結構上無法幫助據信屬於中本聰的約110萬枚BTC,也無法幫助2012年以前、以階層式錢包出現前的原始格式建立的其他地址。</p>

<h2 class="ko">메커니즘: 파기된 서명 대신 '파생 경로'로 소유권을 증명한다</h2>
<h2 class="en">The Mechanism: Proving Ownership Through a Derivation Path, Not a Forgeable Signature</h2>
<h2 class="ja">仕組み:偽造された署名ではなく「派生パス」で所有権を証明する</h2>
<h2 class="es">El mecanismo: demostrar la propiedad mediante una ruta de derivación, no una firma falsificable</h2>
<h2 class="de">Der Mechanismus: Eigentum über einen Ableitungspfad statt über eine fälschbare Signatur nachweisen</h2>
<h2 class="fr">Le mécanisme : prouver la propriété via un chemin de dérivation, pas une signature falsifiable</h2>
<h2 class="pt">O mecanismo: provar a propriedade por um caminho de derivação, não por uma assinatura falsificável</h2>
<h2 class="tr">Mekanizma: Sahtelenebilir Bir İmza Değil, Bir Türetme Yolu ile Sahiplik Kanıtlama</h2>
<h2 class="vi">Cơ chế: Chứng minh quyền sở hữu qua đường dẫn phái sinh, không phải chữ ký có thể bị giả mạo</h2>
<h2 class="id">Mekanisme: Membuktikan Kepemilikan Lewat Jalur Derivasi, Bukan Tanda Tangan yang Bisa Dipalsukan</h2>
<h2 class="pl">Mechanizm: dowód własności poprzez ścieżkę derywacji, a nie fałszowalny podpis</h2>
<h2 class="it">Il meccanismo: dimostrare la proprietà tramite un percorso di derivazione, non una firma falsificabile</h2>
<h2 class="ru">Механизм: доказательство владения через путь деривации, а не через подделываемую подпись</h2>
<h2 class="zh">運作機制:透過「衍生路徑」而非可偽造的簽章證明所有權</h2>

<p class="ko">2012년 도입된 BIP-32 계층적결정형(HD) 지갑 구조에서는 하나의 마스터 키에서 부모 키, 다시 자식 키와 주소들이 단방향 해시 함수를 통해 파생된다. 쇼어 알고리즘을 실행하는 양자컴퓨터가 위협하는 지점은 이 파생 과정 자체가 아니라, 공개키로부터 개인키를 복원해 타원곡선 전자서명(ECDSA·슈노어)을 위조하는 마지막 단계다. 프로젝트 일레븐의 도구는 바로 이 틈새 — 서명은 위조될 수 있어도 해시 파생 관계 자체는 양자컴퓨터로도 뒤집을 수 없다는 사실 — 를 이용한다.</p>
<p class="en">In the BIP-32 hierarchical-deterministic (HD) wallet structure introduced in 2012, a single master key derives parent keys, and those in turn derive child keys and addresses, through one-way hash functions. What a quantum computer running Shor's algorithm threatens isn't that derivation chain itself, but the final step — recovering a private key from its public key to forge an elliptic-curve signature (ECDSA or Schnorr). Project Eleven's tool exploits exactly that gap: a signature can be forged, but the hash-based parent-to-child derivation relationship cannot be reversed even by a quantum computer.</p>
<p class="ja">2012年に導入されたBIP-32階層的決定性(HD)ウォレット構造では、単一のマスターキーから親キーが、さらに親キーから子キーとアドレスが、一方向ハッシュ関数を通じて派生する。ショアのアルゴリズムを実行する量子コンピューターが脅かすのは、この派生過程自体ではなく、公開鍵から秘密鍵を復元して楕円曲線電子署名(ECDSA・シュノア)を偽造する最後の段階だ。プロジェクト・イレブンのツールは、まさにこの隙間 — 署名は偽造できても、ハッシュに基づく親子間の派生関係そのものは量子コンピューターでも逆算できないという事実 — を利用する。</p>
<p class="es">En la estructura de billetera jerárquica determinista (HD) BIP-32, introducida en 2012, una única clave maestra deriva claves principales, y estas a su vez derivan claves hijas y direcciones mediante funciones hash unidireccionales. Lo que amenaza una computadora cuántica que ejecute el algoritmo de Shor no es esa cadena de derivación en sí, sino el paso final: recuperar una clave privada a partir de su clave pública para falsificar una firma de curva elíptica (ECDSA o Schnorr). La herramienta de Project Eleven explota exactamente esa brecha: una firma puede falsificarse, pero la relación de derivación padre-hijo basada en hash no puede revertirse ni siquiera con una computadora cuántica.</p>
<p class="de">In der 2012 eingeführten hierarchisch-deterministischen (HD) BIP-32-Wallet-Struktur leitet ein einzelner Master-Schlüssel übergeordnete Schlüssel ab, und diese wiederum leiten über Einwegs-Hashfunktionen untergeordnete Schlüssel und Adressen ab. Was ein Quantencomputer mit Shors Algorithmus bedroht, ist nicht diese Ableitungskette selbst, sondern der letzte Schritt — das Wiederherstellen eines privaten Schlüssels aus seinem öffentlichen Schlüssel, um eine Elliptische-Kurven-Signatur (ECDSA oder Schnorr) zu fälschen. Genau diese Lücke nutzt das Werkzeug von Project Eleven: Eine Signatur kann gefälscht werden, aber die hashbasierte Eltern-Kind-Ableitungsbeziehung lässt sich selbst mit einem Quantencomputer nicht umkehren.</p>
<p class="fr">Dans la structure de portefeuille hiérarchique déterministe (HD) BIP-32, introduite en 2012, une clé maîtresse unique dérive des clés parentes, qui à leur tour dérivent des clés enfants et des adresses via des fonctions de hachage à sens unique. Ce qu'un ordinateur quantique exécutant l'algorithme de Shor menace, ce n'est pas cette chaîne de dérivation elle-même, mais l'étape finale : récupérer une clé privée à partir de sa clé publique pour falsifier une signature à courbe elliptique (ECDSA ou Schnorr). L'outil de Project Eleven exploite précisément cette brèche : une signature peut être falsifiée, mais la relation de dérivation parent-enfant fondée sur le hachage ne peut être inversée, même par un ordinateur quantique.</p>
<p class="pt">Na estrutura de carteira hierárquica determinística (HD) BIP-32, introduzida em 2012, uma única chave mestra deriva chaves pai, que por sua vez derivam chaves filhas e endereços por meio de funções hash unidirecionais. O que um computador quântico executando o algoritmo de Shor ameaça não é essa cadeia de derivação em si, mas a etapa final — recuperar uma chave privada a partir de sua chave pública para falsificar uma assinatura de curva elíptica (ECDSA ou Schnorr). A ferramenta da Project Eleven explora exatamente essa brecha: uma assinatura pode ser falsificada, mas a relação de derivação pai-filho baseada em hash não pode ser revertida nem mesmo por um computador quântico.</p>
<p class="tr">2012'de tanıtılan BIP-32 hiyerarşik-deterministik (HD) cüzdan yapısında, tek bir ana anahtar üst anahtarları türetir; bunlar da tek yönlü hash fonksiyonları aracılığıyla alt anahtarları ve adresleri türetir. Shor algoritmasını çalıştıran bir kuantum bilgisayarın tehdit ettiği şey bu türetme zincirinin kendisi değil, son adımdır — açık anahtardan özel anahtarı geri kazanarak eliptik eğri imzasını (ECDSA veya Schnorr) sahtelemek. Project Eleven'ın aracı tam olarak bu açığı kullanıyor: bir imza sahtelenebilir, ancak hash tabanlı üst-alt türetme ilişkisi bir kuantum bilgisayar tarafından bile tersine çevrilemez.</p>
<p class="vi">Trong cấu trúc ví phân cấp tất định (HD) BIP-32 được giới thiệu năm 2012, một khóa chủ duy nhất phái sinh ra các khóa cha, và các khóa này lại phái sinh ra các khóa con và địa chỉ thông qua các hàm băm một chiều. Điều mà một máy tính lượng tử chạy thuật toán Shor đe dọa không phải là chuỗi phái sinh này, mà là bước cuối cùng — khôi phục khóa riêng từ khóa công khai để giả mạo chữ ký đường cong elliptic (ECDSA hoặc Schnorr). Công cụ của Project Eleven khai thác chính khe hở đó: chữ ký có thể bị giả mạo, nhưng mối quan hệ phái sinh cha-con dựa trên hàm băm thì không thể bị đảo ngược ngay cả bởi máy tính lượng tử.</p>
<p class="id">Dalam struktur dompet hierarkis deterministik (HD) BIP-32 yang diperkenalkan pada 2012, satu kunci induk menurunkan kunci induk lainnya, dan kunci-kunci ini pada gilirannya menurunkan kunci anak serta alamat melalui fungsi hash satu arah. Yang diancam oleh komputer kuantum yang menjalankan algoritma Shor bukanlah rantai derivasi itu sendiri, melainkan langkah terakhir — memulihkan kunci privat dari kunci publiknya untuk memalsukan tanda tangan kurva eliptik (ECDSA atau Schnorr). Alat dari Project Eleven memanfaatkan celah itu secara tepat: tanda tangan bisa dipalsukan, tetapi hubungan derivasi induk-ke-anak berbasis hash tidak bisa dibalik bahkan oleh komputer kuantum.</p>
<p class="pl">W strukturze hierarchiczno-deterministycznego (HD) portfela BIP-32, wprowadzonej w 2012 roku, jeden klucz główny wyprowadza klucze nadrzędne, a te z kolei wyprowadzają klucze podrzędne i adresy za pomocą jednokierunkowych funkcji skrótu. To, co zagraża komputer kwantowy uruchamiający algorytm Shora, to nie sam ten łańcuch derywacji, lecz ostatni krok — odzyskanie klucza prywatnego z klucza publicznego w celu sfałszowania podpisu krzywej eliptycznej (ECDSA lub Schnorr). Narzędzie Project Eleven wykorzystuje dokładnie tę lukę: podpis można sfałszować, ale relacji derywacji rodzic-dziecko opartej na skrócie nie da się odwrócić nawet za pomocą komputera kwantowego.</p>
<p class="it">Nella struttura di wallet gerarchico deterministico (HD) BIP-32, introdotta nel 2012, una singola chiave madre deriva chiavi genitore, che a loro volta derivano chiavi figlie e indirizzi tramite funzioni hash unidirezionali. Ciò che un computer quantistico che esegue l'algoritmo di Shor minaccia non è questa catena di derivazione in sé, ma l'ultimo passaggio: recuperare una chiave privata dalla sua chiave pubblica per falsificare una firma a curva ellittica (ECDSA o Schnorr). Lo strumento di Project Eleven sfrutta esattamente questa lacuna: una firma può essere falsificata, ma la relazione di derivazione genitore-figlio basata su hash non può essere invertita nemmeno da un computer quantistico.</p>
<p class="ru">В структуре иерархически-детерминированного (HD) кошелька BIP-32, введённой в 2012 году, единый мастер-ключ порождает родительские ключи, а те, в свою очередь, порождают дочерние ключи и адреса через однонаправленные хеш-функции. Квантовый компьютер, выполняющий алгоритм Шора, угрожает не самой этой цепочке деривации, а последнему шагу — восстановлению приватного ключа из публичного для подделки подписи на эллиптической кривой (ECDSA или Schnorr). Инструмент Project Eleven использует именно эту брешь: подпись можно подделать, но основанную на хешах связь деривации родитель-потомок не может обратить даже квантовый компьютер.</p>
<p class="zh">在2012年推出的BIP-32階層式確定性(HD)錢包結構中,單一主金鑰透過單向雜湊函數衍生出父金鑰,父金鑰再衍生出子金鑰與位址。執行秀爾演算法的量子電腦所威脅的並非這條衍生鏈本身,而是最後一步——從公鑰反推私鑰,以偽造橢圓曲線簽章(ECDSA或Schnorr)。Project Eleven的工具正是利用了這個縫隙:簽章可以被偽造,但基於雜湊的父子衍生關係,即使量子電腦也無法逆轉。</p>

<p class="ko">이 증명 체계는 지프(Jim Posen) — 효율적 영지식증명 시스템 '비니어스(Binius)'의 리드 메인테이너 — 가 프로젝트 일레븐의 자금 지원을 받아 구현했다. 사용자는 (1) 문제의 주소보다 파생 트리 상위에 있는 키 자료를 알고 있고, (2) 그 키가 실제로 해당 주소를 파생시키며, (3) 이 증명이 특정 메시지(예: 소유권 주장 트랜잭션)에 결속돼 있다는 세 가지를 증명하면서도, 키 자료 자체는 전혀 노출하지 않는다. 연구자 알론 사타스와 로버트 위보르스키가 처음 제안한 '서명 리프팅(signature lifting)' 개념을 구현으로 발전시킨 결과다. 라이트닝랩스 개발자 올라올루와 오순토쿤(로스비프)이 만든 기존 방식이 14.6초와 GPU 가속을 필요로 했던 것과 비교하면, CPU만으로 243밀리초에 증명을 생성하는 이번 결과는 실용성 면에서 질적인 도약이다.</p>
<p class="en">The proof system was implemented by Jim Posen — lead maintainer of Binius, an efficient zero-knowledge proof system — with funding from Project Eleven. A user proves three things at once: that they know key material sitting above the address in question in the derivation tree, that this key correctly derives the address, and that the proof is bound to a specific message (such as an ownership-claim transaction) — all without ever revealing the key material itself. The work builds on "signature lifting," a concept first proposed by researchers Alon Sattath and Robert Wyborski. Compared with a prior implementation by Lightning Labs developer Olaoluwa Osuntokun ("roasbeef"), which needed 14.6 seconds and GPU acceleration, generating a proof in 243 milliseconds on CPU alone marks a qualitative leap in practicality.</p>
<p class="ja">この証明システムは、効率的な零知識証明システム「Binius(ビニアス)」のリードメンテナーであるジム・ポーゼン(Jim Posen)が、プロジェクト・イレブンの資金提供を受けて実装した。ユーザーは、(1)問題のアドレスより上位の派生ツリーにある鍵素材を知っていること、(2)その鍵が実際に該当アドレスを派生させること、(3)この証明が特定のメッセージ(所有権主張トランザクションなど)に結び付けられていることの3点を証明しながら、鍵素材そのものは一切開示しない。研究者アロン・サタスとロバート・ヴィボルスキーが最初に提唱した「署名リフティング(signature lifting)」の概念を実装へと発展させた成果だ。ライトニング・ラブズの開発者オラオルワ・オスントクン(ロースビーフ)による従来方式が14.6秒とGPUアクセラレーションを必要としていたのに比べ、CPUのみで243ミリ秒で証明を生成する今回の結果は、実用性の面で質的な飛躍と言える。</p>
<p class="es">El sistema de prueba fue implementado por Jim Posen —mantenedor principal de Binius, un eficiente sistema de prueba de conocimiento cero— con financiamiento de Project Eleven. Un usuario prueba tres cosas a la vez: que conoce material de clave situado por encima de la dirección en cuestión en el árbol de derivación, que esa clave deriva correctamente la dirección, y que la prueba está vinculada a un mensaje específico (como una transacción de reclamación de propiedad), todo sin revelar jamás el material de clave. El trabajo se basa en el "signature lifting", un concepto propuesto originalmente por los investigadores Alon Sattath y Robert Wyborski. Comparado con una implementación anterior del desarrollador de Lightning Labs Olaoluwa Osuntokun ("roasbeef"), que requería 14,6 segundos y aceleración por GPU, generar una prueba en 243 milisegundos usando solo CPU representa un salto cualitativo en viabilidad práctica.</p>
<p class="de">Das Beweissystem wurde von Jim Posen — dem Lead-Maintainer von Binius, einem effizienten Zero-Knowledge-Beweissystem — mit Finanzierung durch Project Eleven implementiert. Ein Nutzer beweist drei Dinge gleichzeitig: dass er Schlüsselmaterial kennt, das im Ableitungsbaum über der betreffenden Adresse liegt, dass dieser Schlüssel die Adresse korrekt ableitet, und dass der Beweis an eine bestimmte Nachricht gebunden ist (etwa eine Eigentumsanspruch-Transaktion) — ohne das Schlüsselmaterial selbst je offenzulegen. Die Arbeit baut auf "Signature Lifting" auf, einem Konzept, das erstmals von den Forschern Alon Sattath und Robert Wyborski vorgeschlagen wurde. Im Vergleich zu einer früheren Implementierung des Lightning-Labs-Entwicklers Olaoluwa Osuntokun ("roasbeef"), die 14,6 Sekunden und GPU-Beschleunigung benötigte, markiert die Erzeugung eines Beweises in 243 Millisekunden allein auf der CPU einen qualitativen Sprung in der Praxistauglichkeit.</p>
<p class="fr">Le système de preuve a été mis en œuvre par Jim Posen — mainteneur principal de Binius, un système de preuve à divulgation nulle de connaissance efficace — grâce au financement de Project Eleven. Un utilisateur prouve trois choses à la fois : qu'il connaît du matériel de clé situé au-dessus de l'adresse en question dans l'arbre de dérivation, que cette clé dérive correctement l'adresse, et que la preuve est liée à un message spécifique (comme une transaction de revendication de propriété) — sans jamais révéler le matériel de clé lui-même. Ce travail s'appuie sur le « signature lifting », un concept proposé pour la première fois par les chercheurs Alon Sattath et Robert Wyborski. Comparé à une implémentation antérieure du développeur de Lightning Labs Olaoluwa Osuntokun (« roasbeef »), qui nécessitait 14,6 secondes et une accélération GPU, générer une preuve en 243 millisecondes sur CPU seul marque un bond qualitatif en termes de praticité.</p>
<p class="pt">O sistema de prova foi implementado por Jim Posen — mantenedor principal do Binius, um sistema eficiente de prova de conhecimento zero — com financiamento da Project Eleven. Um usuário prova três coisas ao mesmo tempo: que conhece material de chave situado acima do endereço em questão na árvore de derivação, que essa chave deriva corretamente o endereço, e que a prova está vinculada a uma mensagem específica (como uma transação de reivindicação de propriedade) — tudo sem jamais revelar o material de chave em si. O trabalho se baseia em "signature lifting", um conceito proposto originalmente pelos pesquisadores Alon Sattath e Robert Wyborski. Em comparação com uma implementação anterior do desenvolvedor da Lightning Labs Olaoluwa Osuntokun ("roasbeef"), que exigia 14,6 segundos e aceleração por GPU, gerar uma prova em 243 milissegundos usando apenas CPU marca um salto qualitativo em praticidade.</p>
<p class="tr">Kanıt sistemi, verimli bir sıfır bilgi kanıt sistemi olan Binius'un baş bakımcısı Jim Posen tarafından, Project Eleven'ın finansmanıyla hayata geçirildi. Bir kullanıcı aynı anda üç şeyi kanıtlar: söz konusu adresin türetme ağacında üzerinde yer alan anahtar materyalini bildiğini, bu anahtarın adresi doğru şekilde türettiğini ve kanıtın belirli bir mesaja (örneğin bir sahiplik iddiası işlemine) bağlı olduğunu — tüm bunları anahtar materyalinin kendisini hiç ifşa etmeden yapar. Çalışma, araştırmacılar Alon Sattath ve Robert Wyborski tarafından ilk kez önerilen "imza kaldırma (signature lifting)" kavramı üzerine inşa edildi. Lightning Labs geliştiricisi Olaoluwa Osuntokun'un ("roasbeef") 14,6 saniye ve GPU hızlandırması gerektiren önceki uygulamasıyla karşılaştırıldığında, yalnızca CPU ile 243 milisaniyede kanıt üretmek pratiklik açısından niteliksel bir sıçramaya işaret ediyor.</p>
<p class="vi">Hệ thống chứng minh này được Jim Posen — người bảo trì chính của Binius, một hệ thống chứng minh không tiết lộ thông tin hiệu quả — triển khai với nguồn tài trợ từ Project Eleven. Người dùng chứng minh đồng thời ba điều: họ biết vật liệu khóa nằm phía trên địa chỉ đang xét trong cây phái sinh, khóa đó phái sinh đúng ra địa chỉ này, và bằng chứng được ràng buộc với một thông điệp cụ thể (chẳng hạn giao dịch xác nhận quyền sở hữu) — tất cả mà không bao giờ tiết lộ vật liệu khóa. Công trình này được xây dựng dựa trên "nâng chữ ký" (signature lifting), khái niệm lần đầu được các nhà nghiên cứu Alon Sattath và Robert Wyborski đề xuất. So với cách triển khai trước đó của nhà phát triển Lightning Labs, Olaoluwa Osuntokun ("roasbeef"), vốn cần 14,6 giây và tăng tốc GPU, việc tạo ra bằng chứng trong 243 mili giây chỉ bằng CPU đánh dấu một bước nhảy vọt về chất trong tính thực tiễn.</p>
<p class="id">Sistem bukti ini diimplementasikan oleh Jim Posen — pemelihara utama Binius, sebuah sistem bukti zero-knowledge yang efisien — dengan pendanaan dari Project Eleven. Pengguna membuktikan tiga hal sekaligus: bahwa mereka mengetahui materi kunci yang berada di atas alamat yang dimaksud dalam pohon derivasi, bahwa kunci tersebut secara benar menurunkan alamat itu, dan bahwa bukti tersebut terikat pada pesan tertentu (seperti transaksi klaim kepemilikan) — semua tanpa pernah mengungkap materi kunci itu sendiri. Karya ini dibangun di atas "signature lifting", konsep yang pertama kali diusulkan oleh peneliti Alon Sattath dan Robert Wyborski. Dibandingkan dengan implementasi sebelumnya oleh pengembang Lightning Labs, Olaoluwa Osuntokun ("roasbeef"), yang membutuhkan 14,6 detik dan akselerasi GPU, menghasilkan bukti dalam 243 milidetik hanya dengan CPU menandai lompatan kualitatif dalam kepraktisan.</p>
<p class="pl">System dowodowy zaimplementował Jim Posen — główny opiekun Binius, wydajnego systemu dowodów z wiedzą zerową — dzięki finansowaniu Project Eleven. Użytkownik dowodzi jednocześnie trzech rzeczy: że zna materiał kluczowy znajdujący się powyżej danego adresu w drzewie derywacji, że ten klucz poprawnie wyprowadza dany adres, oraz że dowód jest powiązany z konkretną wiadomością (np. transakcją potwierdzającą własność) — a wszystko to bez ujawniania samego materiału kluczowego. Praca opiera się na koncepcji "signature lifting", zaproponowanej po raz pierwszy przez badaczy Alona Sattatha i Roberta Wyborskiego. W porównaniu z wcześniejszą implementacją dewelopera Lightning Labs, Olaoluwy Osuntokuna ("roasbeef"), która wymagała 14,6 sekundy i akceleracji GPU, wygenerowanie dowodu w 243 milisekundy wyłącznie na CPU oznacza jakościowy skok w praktyczności.</p>
<p class="it">Il sistema di prova è stato implementato da Jim Posen — lead maintainer di Binius, un efficiente sistema di prova a conoscenza zero — con il finanziamento di Project Eleven. Un utente dimostra contemporaneamente tre cose: di conoscere il materiale della chiave che si trova sopra l'indirizzo in questione nell'albero di derivazione, che questa chiave deriva correttamente l'indirizzo, e che la prova è vincolata a un messaggio specifico (come una transazione di rivendicazione di proprietà) — tutto senza mai rivelare il materiale della chiave stesso. Il lavoro si basa sul "signature lifting", un concetto proposto per la prima volta dai ricercatori Alon Sattath e Robert Wyborski. Rispetto a un'implementazione precedente dello sviluppatore di Lightning Labs Olaoluwa Osuntokun ("roasbeef"), che richiedeva 14,6 secondi e accelerazione GPU, generare una prova in 243 millisecondi con la sola CPU segna un salto qualitativo in termini di praticità.</p>
<p class="ru">Систему доказательства реализовал Джим Позен (Jim Posen) — ведущий сопровождающий Binius, эффективной системы доказательств с нулевым разглашением — при финансировании со стороны Project Eleven. Пользователь одновременно доказывает три вещи: что он знает ключевой материал, находящийся выше данного адреса в дереве деривации, что этот ключ действительно порождает данный адрес, и что доказательство привязано к конкретному сообщению (например, транзакции заявления о праве собственности) — всё это без раскрытия самого ключевого материала. Работа основана на концепции «подъёма подписи» (signature lifting), впервые предложенной исследователями Алоном Саттатом и Робертом Выборским. По сравнению с более ранней реализацией разработчика Lightning Labs Олаолувы Осунтокуна («roasbeef»), которая требовала 14,6 секунды и ускорения на GPU, генерация доказательства за 243 миллисекунды только на CPU знаменует качественный скачок в практичности.</p>
<p class="zh">此證明系統由吉姆·波森(Jim Posen)——高效零知識證明系統Binius的首席維護者——在Project Eleven的資助下實作完成。使用者可同時證明三件事:(1)自己掌握位於該位址衍生樹上層的金鑰資料;(2)該金鑰確實衍生出該位址;(3)此證明與特定訊息(例如一筆主張所有權的交易)相綁定——同時完全不洩露金鑰資料本身。這項成果建立在研究者阿隆·薩塔斯(Alon Sattath)與羅伯特·維博爾斯基(Robert Wyborski)最早提出的「簽章提升(signature lifting)」概念之上。相較於Lightning Labs開發者奧拉奧盧瓦·奧孫托昆(Olaoluwa Osuntokun,暱稱roasbeef)先前需要14.6秒並依賴GPU加速的實作方式,如今僅靠CPU即可在243毫秒內生成證明,在實用性上是一次質的飛躍。</p>

<h2 class="ko">사토시의 110만 BTC는 왜 대상이 아닌가</h2>
<h2 class="en">Why Satoshi's 1.1 Million BTC Are Left Out</h2>
<h2 class="ja">サトシの110万BTCはなぜ対象外なのか</h2>
<h2 class="es">Por qué se excluyen los 1,1 millones de BTC de Satoshi</h2>
<h2 class="de">Warum Satoshis 1,1 Millionen BTC außen vor bleiben</h2>
<h2 class="fr">Pourquoi les 1,1 million de BTC de Satoshi sont exclus</h2>
<h2 class="pt">Por que os 1,1 milhão de BTC de Satoshi ficam de fora</h2>
<h2 class="tr">Satoshi'nin 1,1 Milyon BTC'si Neden Dışarıda Kalıyor</h2>
<h2 class="vi">Vì sao 1,1 triệu BTC của Satoshi bị loại trừ</h2>
<h2 class="id">Mengapa 1,1 Juta BTC Milik Satoshi Tidak Termasuk</h2>
<h2 class="pl">Dlaczego 1,1 miliona BTC Satoshiego jest wykluczonych</h2>
<h2 class="it">Perché 1,1 milioni di BTC di Satoshi restano esclusi</h2>
<h2 class="ru">Почему 1,1 миллиона BTC Сатоши остаются за бортом</h2>
<h2 class="zh">為何中本聰的110萬枚BTC不在保護範圍內</h2>

<p class="ko">이 도구가 통하지 않는 이유는 구조적이다. 사토시가 채굴 초기에 사용한 것으로 추정되는 주소들은 페이투퍼블릭키(P2PK) 방식으로, 공개키 자체가 블록체인에 그대로 기록돼 있다. 이런 주소는 니모닉 시드도, 파생 경로도, 상위 부모 키도 없는 소프트웨어로 만들어졌다 — HD 지갑을 규정한 BIP-32가 등장한 것은 2012년 2월 11일로, 그보다 앞선 주소들에는 애초에 '트리 구조 위'라는 개념 자체가 존재하지 않는다. 증명할 상위 키가 없다면, 증명할 방법도 없다는 뜻이다.</p>
<p class="en">The reason the tool doesn't work here is structural. The addresses believed to have been used by Satoshi during Bitcoin's earliest mining were pay-to-pubkey (P2PK) outputs, where the public key itself sits directly on the blockchain. Those addresses were generated by software with no seed phrase, no derivation path, and no parent key — BIP-32, which defined HD wallets, didn't arrive until February 11, 2012, so for anything created earlier, the very concept of "something above it in a tree" simply didn't exist. With no parent key to prove knowledge of, there's no way to construct the proof.</p>
<p class="ja">このツールが通用しない理由は構造的なものだ。サトシが初期のマイニングで使用したとされるアドレスは、公開鍵そのものがブロックチェーンにそのまま記録されるペイ・トゥ・パブリックキー(P2PK)方式だった。これらのアドレスは、ニーモニックシードも派生パスも上位の親鍵も持たないソフトウェアによって生成された — HDウォレットを定めたBIP-32が登場したのは2012年2月11日であり、それ以前に作られたアドレスには「ツリー構造の上位」という概念自体がそもそも存在しない。証明すべき上位鍵がなければ、証明する方法もないということだ。</p>
<p class="es">La razón por la que la herramienta no funciona aquí es estructural. Se cree que las direcciones usadas por Satoshi durante la minería más temprana de Bitcoin fueron salidas "pay-to-pubkey" (P2PK), donde la propia clave pública queda registrada directamente en la blockchain. Esas direcciones fueron generadas por software sin frase semilla, sin ruta de derivación y sin clave madre — BIP-32, que definió las billeteras HD, no apareció hasta el 11 de febrero de 2012, así que para cualquier cosa creada antes, el propio concepto de "algo por encima en un árbol" simplemente no existía. Sin una clave madre de la que probar conocimiento, no hay forma de construir la prueba.</p>
<p class="de">Der Grund, warum das Werkzeug hier nicht greift, ist struktureller Natur. Die Adressen, die Satoshi vermutlich beim frühesten Mining von Bitcoin nutzte, waren Pay-to-Pubkey-Outputs (P2PK), bei denen der öffentliche Schlüssel selbst direkt auf der Blockchain liegt. Diese Adressen wurden von Software erzeugt, die weder eine Seed-Phrase noch einen Ableitungspfad noch einen übergeordneten Schlüssel kannte — BIP-32, das HD-Wallets definierte, kam erst am 11. Februar 2012, sodass für alles, was davor entstand, das Konzept von „etwas darüber in einem Baum" schlicht nicht existierte. Ohne übergeordneten Schlüssel, dessen Kenntnis man beweisen könnte, gibt es keine Möglichkeit, den Beweis zu konstruieren.</p>
<p class="fr">La raison pour laquelle l'outil ne fonctionne pas ici est structurelle. Les adresses que Satoshi aurait utilisées lors des tout premiers minages de Bitcoin étaient des sorties pay-to-pubkey (P2PK), où la clé publique elle-même figure directement sur la blockchain. Ces adresses ont été générées par un logiciel sans phrase de récupération, sans chemin de dérivation et sans clé parente — le BIP-32, qui a défini les portefeuilles HD, n'est apparu que le 11 février 2012, de sorte que pour tout ce qui a été créé avant, le concept même de « quelque chose au-dessus dans un arbre » n'existait tout simplement pas. Sans clé parente dont on puisse prouver la connaissance, il n'y a aucun moyen de construire la preuve.</p>
<p class="pt">O motivo pelo qual a ferramenta não funciona aqui é estrutural. Acredita-se que os endereços usados por Satoshi durante a mineração mais antiga do Bitcoin eram saídas pay-to-pubkey (P2PK), nas quais a própria chave pública fica registrada diretamente na blockchain. Esses endereços foram gerados por um software sem frase-semente, sem caminho de derivação e sem chave pai — o BIP-32, que definiu as carteiras HD, só surgiu em 11 de fevereiro de 2012, então, para tudo criado antes disso, o próprio conceito de "algo acima na árvore" simplesmente não existia. Sem uma chave pai da qual provar conhecimento, não há como construir a prova.</p>
<p class="tr">Aracın burada işe yaramamasının nedeni yapısaldır. Satoshi'nin Bitcoin'in en erken madencilik döneminde kullandığı düşünülen adresler, açık anahtarın kendisinin doğrudan blok zincirinde yer aldığı pay-to-pubkey (P2PK) çıktılarıydı. Bu adresler, ne tohum ifadesi (seed phrase), ne türetme yolu ne de üst anahtarı olan bir yazılımla oluşturuldu — HD cüzdanları tanımlayan BIP-32 ancak 11 Şubat 2012'de ortaya çıktı; dolayısıyla ondan önce oluşturulan her şey için "bir ağaçta üzerinde bir şey olması" kavramı zaten mevcut değildi. Bilgisini kanıtlayacak bir üst anahtar yoksa, kanıtı oluşturmanın da bir yolu yoktur.</p>
<p class="vi">Lý do công cụ này không hoạt động ở đây mang tính cấu trúc. Các địa chỉ được cho là Satoshi đã sử dụng trong giai đoạn đào Bitcoin sớm nhất là các đầu ra trả cho khóa công khai (P2PK), nơi chính khóa công khai được ghi trực tiếp trên blockchain. Những địa chỉ này được tạo bởi phần mềm không có cụm từ khôi phục, không có đường dẫn phái sinh và không có khóa cha — BIP-32, chuẩn định nghĩa ví HD, mãi đến ngày 11 tháng 2 năm 2012 mới xuất hiện, vì vậy với bất cứ thứ gì được tạo trước đó, khái niệm "có gì đó ở phía trên trong một cây" đơn giản là không tồn tại. Không có khóa cha để chứng minh sự hiểu biết, thì cũng không có cách nào xây dựng bằng chứng.</p>
<p class="id">Alasan alat ini tidak berfungsi di sini bersifat struktural. Alamat yang diyakini digunakan Satoshi selama penambangan Bitcoin paling awal adalah keluaran pay-to-pubkey (P2PK), di mana kunci publik itu sendiri tercatat langsung di blockchain. Alamat-alamat itu dihasilkan oleh perangkat lunak tanpa frasa seed, tanpa jalur derivasi, dan tanpa kunci induk — BIP-32, yang mendefinisikan dompet HD, baru muncul pada 11 Februari 2012, sehingga untuk apa pun yang dibuat sebelumnya, konsep "sesuatu di atasnya dalam sebuah pohon" sama sekali belum ada. Tanpa kunci induk yang bisa dibuktikan pengetahuannya, tidak ada cara untuk menyusun bukti tersebut.</p>
<p class="pl">Powód, dla którego narzędzie tu nie działa, ma charakter strukturalny. Adresy, których Satoshi prawdopodobnie używał podczas najwcześniejszego wydobycia Bitcoina, były wyjściami typu pay-to-pubkey (P2PK), gdzie sam klucz publiczny znajduje się bezpośrednio na blockchainie. Adresy te zostały wygenerowane przez oprogramowanie bez frazy seed, bez ścieżki derywacji i bez klucza nadrzędnego — BIP-32, definiujący portfele HD, pojawił się dopiero 11 lutego 2012 roku, więc dla wszystkiego, co powstało wcześniej, sama koncepcja "czegoś powyżej w drzewie" po prostu nie istniała. Bez klucza nadrzędnego, którego znajomość można by udowodnić, nie ma sposobu na skonstruowanie dowodu.</p>
<p class="it">Il motivo per cui lo strumento qui non funziona è strutturale. Gli indirizzi che si ritiene siano stati usati da Satoshi durante il mining più antico di Bitcoin erano output pay-to-pubkey (P2PK), in cui la chiave pubblica stessa risiede direttamente sulla blockchain. Questi indirizzi sono stati generati da software privo di seed phrase, percorso di derivazione e chiave genitore — il BIP-32, che ha definito i wallet HD, non è arrivato prima dell'11 febbraio 2012, quindi per tutto ciò che è stato creato in precedenza, il concetto stesso di "qualcosa sopra in un albero" semplicemente non esisteva. Senza una chiave genitore di cui dimostrare la conoscenza, non c'è modo di costruire la prova.</p>
<p class="ru">Причина, по которой инструмент здесь не работает, носит структурный характер. Адреса, которые, как считается, использовал Сатоши в период самого раннего майнинга биткоина, были выходами типа pay-to-pubkey (P2PK), где сам публичный ключ напрямую записан в блокчейне. Эти адреса были созданы программным обеспечением без seed-фразы, без пути деривации и без родительского ключа — BIP-32, определивший HD-кошельки, появился только 11 февраля 2012 года, поэтому для всего, что было создано раньше, самого понятия «нечто выше в дереве» попросту не существовало. Без родительского ключа, знание которого можно было бы доказать, построить доказательство невозможно.</p>
<p class="zh">這項工具在此失效的原因具有結構性。據信中本聰在比特幣最早期挖礦時使用的位址屬於「支付給公鑰」(P2PK)類型,公鑰本身就直接記錄在區塊鏈上。這些位址是由沒有助記詞、沒有衍生路徑、也沒有上層父金鑰的軟體所產生——定義HD錢包的BIP-32協議直到2012年2月11日才問世,因此在此之前建立的任何位址,根本不存在「衍生樹上層還有東西」這個概念。沒有可證明知悉的上層金鑰,自然也就無法建構這項證明。</p>

<p class="ko">역설적인 지점은 여기에 있다. 애초에 P2PK 방식으로 공개키가 그대로 노출된 주소들이야말로 양자컴퓨터의 1차 표적이 될 가능성이 가장 높다는 점이다 — 페이투퍼블릭키해시(P2PKH)로 만들어진 이후 세대 주소들은 자금이 한 번도 지출되지 않는 한 공개키가 체인에 드러나지 않지만, P2PK는 처음부터 공개키를 그대로 노출한다. <a href="/blog/bitcoin-quantum-migration-debate">이 사이트가 다룬 604만 BTC 동결 제안 논쟁</a>이 바로 이 지점—가장 취약한 초기 주소를 어떻게 처리할 것인가—을 둘러싸고 벌어지고 있다. 프로젝트 일레븐의 도구는 그 논쟁을 해결하지 못한다. 대신 전혀 다른, 더 좁은 사용자군—시드는 있지만 향후 양자내성 주소로의 마이그레이션을 놓치거나, 공격자가 먼저 서명을 위조하기 전에 소유권을 증명해야 하는 현대 HD 지갑 사용자—를 겨냥한다.</p>
<p class="en">There's an irony here. The very addresses left exposed by the P2PK format — with the public key sitting in the open — are arguably the most likely first targets for a quantum attacker in the first place. Later-generation pay-to-pubkey-hash (P2PKH) addresses never reveal their public key on-chain unless funds are spent, but P2PK exposes it from day one. <a href="/en/blog/bitcoin-quantum-migration-debate">This site's earlier coverage of the debate over freezing 6.04 million BTC</a> centers on exactly this question — what to do about the most exposed early addresses. Project Eleven's tool doesn't resolve that debate; it targets an entirely different, narrower population: modern HD-wallet users who miss a future migration to quantum-resistant addresses, or who need to prove ownership before an attacker forges their signature first.</p>
<p class="ja">ここには皮肉な点がある。そもそもP2PK方式によって公開鍵がそのまま露出しているアドレスこそ、量子コンピューターにとって最初の標的になる可能性が最も高いということだ — 後の世代であるペイ・トゥ・パブリックキーハッシュ(P2PKH)方式のアドレスは、資金が一度も使われない限り公開鍵がチェーン上に現れないが、P2PKは最初から公開鍵をそのまま露出させている。<a href="/ja/blog/bitcoin-quantum-migration-debate">本サイトが取り上げた604万BTC凍結提案をめぐる論争</a>は、まさにこの点 — 最も脆弱な初期アドレスをどう扱うか — をめぐって展開されている。プロジェクト・イレブンのツールはその論争を解決しない。代わりに、まったく異なる、より狭いユーザー層 — シードは持っているが将来の量子耐性アドレスへの移行を逃した、あるいは攻撃者が先に署名を偽造する前に所有権を証明する必要がある現代のHDウォレット利用者 — を対象としている。</p>
<p class="es">Aquí hay una ironía. Precisamente las direcciones que quedan expuestas por el formato P2PK —con la clave pública a la vista— son, posiblemente, el primer objetivo más probable para un atacante cuántico. Las direcciones de generación posterior pay-to-pubkey-hash (P2PKH) nunca revelan su clave pública en la cadena a menos que se gasten los fondos, pero P2PK la expone desde el primer día. <a href="/es/blog/bitcoin-quantum-migration-debate">La cobertura anterior de este sitio sobre el debate por congelar 6,04 millones de BTC</a> gira precisamente en torno a esta pregunta: qué hacer con las direcciones más antiguas y expuestas. La herramienta de Project Eleven no resuelve ese debate; apunta a una población completamente distinta y más reducida: usuarios de billeteras HD modernas que pierdan una futura migración a direcciones resistentes a la computación cuántica, o que necesiten probar la propiedad antes de que un atacante falsifique su firma primero.</p>
<p class="de">Hier liegt eine Ironie. Ausgerechnet die Adressen, deren öffentlicher Schlüssel durch das P2PK-Format offenliegt, sind wohl das wahrscheinlichste erste Ziel für einen Quantenangreifer. Spätere Pay-to-Pubkey-Hash-Adressen (P2PKH) legen ihren öffentlichen Schlüssel nie on-chain offen, solange die Gelder nicht ausgegeben wurden — P2PK jedoch von Anfang an. <a href="/de/blog/bitcoin-quantum-migration-debate">Die frühere Berichterstattung dieser Seite über die Debatte um das Einfrieren von 6,04 Millionen BTC</a> dreht sich genau um diese Frage — was mit den am stärksten exponierten frühen Adressen geschehen soll. Project Elevens Werkzeug löst diese Debatte nicht; es zielt auf eine völlig andere, engere Gruppe ab: Nutzer moderner HD-Wallets, die eine künftige Migration zu quantenresistenten Adressen verpassen oder ihr Eigentum nachweisen müssen, bevor ein Angreifer zuerst ihre Signatur fälscht.</p>
<p class="fr">Il y a ici une ironie. Ce sont précisément les adresses exposées par le format P2PK — avec la clé publique à découvert — qui constituent sans doute la cible la plus probable pour un attaquant quantique. Les adresses pay-to-pubkey-hash (P2PKH) de génération ultérieure ne révèlent jamais leur clé publique sur la chaîne tant que les fonds n'ont pas été dépensés, mais le P2PK l'expose dès le premier jour. <a href="/fr/blog/bitcoin-quantum-migration-debate">La couverture antérieure de ce site sur le débat autour du gel de 6,04 millions de BTC</a> porte précisément sur cette question — que faire des adresses anciennes les plus exposées. L'outil de Project Eleven ne résout pas ce débat ; il vise une population entièrement différente et plus restreinte : les utilisateurs de portefeuilles HD modernes qui manqueraient une future migration vers des adresses résistantes au quantique, ou qui doivent prouver leur propriété avant qu'un attaquant ne falsifie sa signature en premier.</p>
<p class="pt">Há uma ironia aqui. Justamente os endereços deixados expostos pelo formato P2PK — com a chave pública à mostra — são, possivelmente, o alvo inicial mais provável para um atacante quântico. Endereços pay-to-pubkey-hash (P2PKH) de geração posterior nunca revelam sua chave pública on-chain a menos que os fundos sejam gastos, mas o P2PK a expõe desde o primeiro dia. <a href="/pt/blog/bitcoin-quantum-migration-debate">A cobertura anterior deste site sobre o debate em torno de congelar 6,04 milhões de BTC</a> gira exatamente em torno dessa questão — o que fazer com os endereços antigos mais expostos. A ferramenta da Project Eleven não resolve esse debate; ela mira uma população totalmente diferente e mais restrita: usuários de carteiras HD modernas que percam uma futura migração para endereços resistentes a computadores quânticos, ou que precisem provar a propriedade antes que um atacante falsifique sua assinatura primeiro.</p>
<p class="tr">Burada bir ironi var. P2PK formatı tarafından açıkta bırakılan adresler — açık anahtarın ortada durduğu adresler — muhtemelen bir kuantum saldırganı için ilk hedef olma ihtimali en yüksek olanlardır. Daha sonraki nesil pay-to-pubkey-hash (P2PKH) adresleri, fonlar harcanmadığı sürece açık anahtarlarını zincir üzerinde asla ifşa etmez, ancak P2PK bunu ilk günden itibaren ifşa eder. <a href="/tr/blog/bitcoin-quantum-migration-debate">Bu sitenin daha önce ele aldığı 6,04 milyon BTC'yi dondurma önerisine ilişkin tartışma</a> tam olarak bu soru etrafında dönüyor — en savunmasız erken adreslere ne yapılacağı. Project Eleven'ın aracı bu tartışmayı çözmüyor; bunun yerine tamamen farklı, daha dar bir kitleyi hedefliyor: gelecekteki kuantuma dirençli adreslere geçişi kaçıran ya da bir saldırgan imzalarını sahtelemeden önce sahipliklerini kanıtlamaları gereken modern HD cüzdan kullanıcılarını.</p>
<p class="vi">Có một sự trớ trêu ở đây. Chính những địa chỉ bị để lộ bởi định dạng P2PK — với khóa công khai nằm sờ sờ ra đó — có lẽ lại là mục tiêu đầu tiên khả dĩ nhất cho một kẻ tấn công lượng tử. Các địa chỉ pay-to-pubkey-hash (P2PKH) thế hệ sau không bao giờ tiết lộ khóa công khai trên chuỗi trừ khi tiền đã được chi tiêu, nhưng P2PK lại phơi bày nó ngay từ đầu. <a href="/vi/blog/bitcoin-quantum-migration-debate">Bài viết trước đây của trang này về cuộc tranh luận đóng băng 6,04 triệu BTC</a> xoay quanh chính câu hỏi này — nên xử lý thế nào với những địa chỉ sớm dễ bị tổn thương nhất. Công cụ của Project Eleven không giải quyết cuộc tranh luận đó; nó nhắm đến một nhóm hoàn toàn khác, hẹp hơn: người dùng ví HD hiện đại bỏ lỡ một cuộc di chuyển trong tương lai sang địa chỉ kháng lượng tử, hoặc cần chứng minh quyền sở hữu trước khi kẻ tấn công giả mạo chữ ký của họ trước.</p>
<p class="id">Ada ironi di sini. Justru alamat-alamat yang terbuka karena format P2PK — dengan kunci publik yang tampak jelas — kemungkinan besar menjadi target pertama yang paling mungkin bagi penyerang kuantum. Alamat pay-to-pubkey-hash (P2PKH) generasi berikutnya tidak pernah mengungkap kunci publiknya di on-chain kecuali dana tersebut dibelanjakan, tetapi P2PK mengungkapkannya sejak awal. <a href="/id/blog/bitcoin-quantum-migration-debate">Liputan situs ini sebelumnya tentang perdebatan pembekuan 6,04 juta BTC</a> berpusat tepat pada pertanyaan ini — apa yang harus dilakukan terhadap alamat-alamat awal yang paling rentan. Alat dari Project Eleven tidak menyelesaikan perdebatan itu; alat ini menyasar populasi yang sama sekali berbeda dan lebih sempit: pengguna dompet HD modern yang melewatkan migrasi masa depan ke alamat tahan kuantum, atau yang perlu membuktikan kepemilikan sebelum penyerang lebih dulu memalsukan tanda tangan mereka.</p>
<p class="pl">Jest w tym pewna ironia. To właśnie adresy odsłonięte przez format P2PK — z kluczem publicznym widocznym jak na dłoni — są prawdopodobnie najbardziej narażone na to, by stać się pierwszym celem atakującego kwantowego. Adresy pay-to-pubkey-hash (P2PKH) nowszej generacji nigdy nie ujawniają swojego klucza publicznego on-chain, dopóki środki nie zostaną wydane, ale P2PK ujawnia go od pierwszego dnia. <a href="/pl/blog/bitcoin-quantum-migration-debate">Wcześniejszy materiał tej strony o debacie na temat zamrożenia 6,04 miliona BTC</a> krąży dokładnie wokół tego pytania — co zrobić z najbardziej narażonymi wczesnymi adresami. Narzędzie Project Eleven nie rozwiązuje tej debaty; celuje w zupełnie inną, węższą grupę: użytkowników nowoczesnych portfeli HD, którzy przegapią przyszłą migrację do adresów odpornych na kwant, lub którzy muszą udowodnić własność, zanim atakujący jako pierwszy sfałszuje ich podpis.</p>
<p class="it">C'è un'ironia in tutto questo. Sono proprio gli indirizzi lasciati esposti dal formato P2PK — con la chiave pubblica bene in vista — probabilmente il primo bersaglio più probabile per un attaccante quantistico. Gli indirizzi pay-to-pubkey-hash (P2PKH) di generazione successiva non rivelano mai la propria chiave pubblica on-chain a meno che i fondi non vengano spesi, ma il P2PK la espone fin dal primo giorno. <a href="/it/blog/bitcoin-quantum-migration-debate">La copertura precedente di questo sito sul dibattito riguardo al congelamento di 6,04 milioni di BTC</a> ruota esattamente attorno a questa domanda — cosa fare con gli indirizzi più antichi ed esposti. Lo strumento di Project Eleven non risolve quel dibattito; punta a una popolazione completamente diversa e più ristretta: utenti di wallet HD moderni che perdono una futura migrazione verso indirizzi resistenti al quantum, o che devono dimostrare la proprietà prima che un attaccante falsifichi la loro firma per primo.</p>
<p class="ru">Здесь есть ирония. Именно адреса, оставшиеся открытыми из-за формата P2PK — с публичным ключом на виду, — вероятно, являются наиболее вероятной первой целью для квантового злоумышленника. Адреса более позднего поколения pay-to-pubkey-hash (P2PKH) никогда не раскрывают свой публичный ключ в блокчейне, пока средства не потрачены, а P2PK раскрывает его с самого начала. <a href="/ru/blog/bitcoin-quantum-migration-debate">Более ранний материал этого сайта о споре вокруг заморозки 6,04 миллиона BTC</a> вращается именно вокруг этого вопроса — что делать с наиболее уязвимыми ранними адресами. Инструмент Project Eleven не решает этот спор; он нацелен на совершенно другую, более узкую группу: пользователей современных HD-кошельков, которые пропустят будущую миграцию на квантово-устойчивые адреса, или которым нужно доказать право собственности до того, как злоумышленник первым подделает их подпись.</p>
<p class="zh">這裡存在一個諷刺之處。恰恰是因P2PK格式而公鑰完全曝光的位址,最有可能成為量子攻擊者的首要目標。後來世代的「支付給公鑰雜湊」(P2PKH)位址,除非資金被花費過,否則公鑰永遠不會出現在鏈上,但P2PK從一開始就將公鑰完全暴露。<a href="/zh/blog/bitcoin-quantum-migration-debate">本站先前報導過關於凍結604萬枚BTC提案的爭論</a>,正是圍繞這個問題展開——該如何處理最脆弱的早期位址。Project Eleven的工具並未解決這場爭論;它瞄準的是完全不同、範圍更窄的族群:現代HD錢包使用者中,錯過未來遷移至抗量子位址時機的人,或是需要在攻擊者搶先偽造其簽章之前證明所有權的人。</p>

<h2 class="ko">왜 당장 쓸 수는 없나 — 감사·합의 변경이라는 장벽</h2>
<h2 class="en">Why It Can't Be Used Yet — The Audit and Consensus-Change Barrier</h2>
<h2 class="ja">なぜ今すぐ使えないのか — 監査と合意形成という壁</h2>
<h2 class="es">Por qué aún no se puede usar — la barrera de la auditoría y el cambio de consenso</h2>
<h2 class="de">Warum es noch nicht genutzt werden kann — die Hürde aus Audit und Konsensänderung</h2>
<h2 class="fr">Pourquoi cet outil n'est pas encore utilisable — l'obstacle de l'audit et du changement de consensus</h2>
<h2 class="pt">Por que ainda não pode ser usada — a barreira da auditoria e da mudança de consenso</h2>
<h2 class="tr">Neden Henüz Kullanılamıyor — Denetim ve Konsensüs Değişikliği Engeli</h2>
<h2 class="vi">Vì sao chưa thể sử dụng ngay — rào cản kiểm toán và thay đổi đồng thuận</h2>
<h2 class="id">Mengapa Belum Bisa Digunakan — Hambatan Audit dan Perubahan Konsensus</h2>
<h2 class="pl">Dlaczego jeszcze nie można go używać — bariera audytu i zmiany konsensusu</h2>
<h2 class="it">Perché non è ancora utilizzabile — la barriera dell'audit e del cambiamento di consenso</h2>
<h2 class="ru">Почему им пока нельзя пользоваться — барьер аудита и изменения консенсуса</h2>
<h2 class="zh">為何目前尚無法使用——稽核與共識變更的障礙</h2>

<p class="ko">프로젝트 일레븐도 이 시제품이 감사받지 않았고 아직 미완성 상태라는 점을 인정한다. 실제 자금을 보호하려면 비트코인의 합의 규칙 자체를 바꾸는, 논쟁적일 수밖에 없는 변경이 선행돼야 한다 — 즉 이 증명 방식을 체인이 인식하고 검증할 수 있는 새로운 트랜잭션 유형이나 복구 경로로 표준화하는 작업이다. 올해 2월 공식 검토 절차에 들어간 BIP-360은 향후 생성될 주소를 양자내성 방식으로 만드는 데 초점을 맞추고 있어, 이미 존재하는 주소의 소유권을 사후적으로 증명하는 이번 도구와는 역할이 다르다 — 두 제안 모두 별도의 합의가 필요하다는 점은 같다.</p>
<p class="en">Project Eleven itself acknowledges the prototype is unaudited and still incomplete. Protecting real funds would first require a contentious change to Bitcoin's consensus rules — standardizing this proof method into a new transaction type or recovery path the chain can recognize and verify. BIP-360, which entered formal review this February, focuses on making future addresses quantum-resistant from the start, a different role from this tool's after-the-fact ownership proof for addresses that already exist — though both proposals share the same requirement: a separate consensus change of their own.</p>
<p class="ja">プロジェクト・イレブン自身も、この試作版が監査を受けておらず、まだ未完成の状態であることを認めている。実際の資金を保護するには、まずビットコインの合意ルール自体を変える、論争を伴わざるを得ない変更が先行しなければならない — つまり、この証明方式をチェーンが認識・検証できる新しいトランザクションタイプや復旧経路として標準化する作業だ。今年2月に正式な検討手続きに入ったBIP-360は、今後生成されるアドレスを量子耐性のある方式にすることに焦点を当てており、既に存在するアドレスの所有権を事後的に証明する今回のツールとは役割が異なる — ただし両提案とも、それぞれ別個の合意形成が必要である点は同じだ。</p>
<p class="es">El propio Project Eleven reconoce que el prototipo no ha sido auditado y sigue incompleto. Proteger fondos reales requeriría antes un cambio, inevitablemente polémico, en las reglas de consenso de Bitcoin: estandarizar este método de prueba como un nuevo tipo de transacción o ruta de recuperación que la cadena pueda reconocer y verificar. El BIP-360, que entró en revisión formal en febrero, se centra en hacer que las direcciones futuras sean resistentes a la computación cuántica desde el principio, un papel distinto al de esta herramienta, que prueba a posteriori la propiedad de direcciones ya existentes — aunque ambas propuestas comparten el mismo requisito: un cambio de consenso propio y separado.</p>
<p class="de">Project Eleven selbst räumt ein, dass der Prototyp nicht auditiert und noch unvollständig ist. Um echte Gelder zu schützen, wäre zunächst eine zwangsläufig kontroverse Änderung der Bitcoin-Konsensregeln nötig — die Standardisierung dieser Beweismethode als neuer Transaktionstyp oder Wiederherstellungspfad, den die Chain erkennen und verifizieren kann. BIP-360, das im Februar in die formale Prüfung ging, konzentriert sich darauf, künftige Adressen von Anfang an quantenresistent zu machen — eine andere Rolle als der nachträgliche Eigentumsnachweis dieses Werkzeugs für bereits existierende Adressen. Beide Vorschläge teilen jedoch dieselbe Voraussetzung: eine eigene, separate Konsensänderung.</p>
<p class="fr">Project Eleven reconnaît lui-même que le prototype n'est pas audité et reste incomplet. Protéger de véritables fonds nécessiterait d'abord un changement, forcément controversé, des règles de consensus de Bitcoin — standardiser cette méthode de preuve en un nouveau type de transaction ou une voie de récupération que la chaîne puisse reconnaître et vérifier. Le BIP-360, entré en examen formel en février, vise à rendre les futures adresses résistantes au quantique dès le départ, un rôle différent de la preuve de propriété a posteriori que propose cet outil pour des adresses déjà existantes — bien que les deux propositions partagent la même exigence : un changement de consensus qui leur est propre.</p>
<p class="pt">A própria Project Eleven reconhece que o protótipo não foi auditado e ainda está incompleto. Proteger fundos reais exigiria antes uma mudança, inevitavelmente controversa, nas regras de consenso do Bitcoin — padronizar esse método de prova como um novo tipo de transação ou caminho de recuperação que a rede possa reconhecer e verificar. O BIP-360, que entrou em revisão formal em fevereiro, foca em tornar endereços futuros resistentes a computadores quânticos desde o início, um papel diferente da prova de propriedade a posteriori que esta ferramenta oferece para endereços já existentes — embora ambas as propostas compartilhem o mesmo requisito: uma mudança de consenso própria e separada.</p>
<p class="tr">Project Eleven'ın kendisi de bu prototipin denetlenmediğini ve hâlâ eksik olduğunu kabul ediyor. Gerçek fonları korumak için önce Bitcoin'in konsensüs kurallarında, kaçınılmaz olarak tartışmalı bir değişikliğin yapılması gerekir — yani bu kanıt yöntemini zincirin tanıyıp doğrulayabileceği yeni bir işlem türü veya kurtarma yolu olarak standartlaştırmak. Bu yılın Şubat ayında resmi inceleme sürecine giren BIP-360, gelecekte oluşturulacak adresleri baştan itibaren kuantuma dirençli hale getirmeye odaklanıyor; bu, halihazırda var olan adresler için sahiplik kanıtı sunan bu aracın rolünden farklıdır — ancak her iki öneri de kendi başına ayrı bir konsensüs değişikliği gerektiriyor.</p>
<p class="vi">Bản thân Project Eleven cũng thừa nhận nguyên mẫu này chưa được kiểm toán và vẫn chưa hoàn chỉnh. Để bảo vệ tiền thật, trước tiên cần một thay đổi tất yếu gây tranh cãi đối với các quy tắc đồng thuận của Bitcoin — chuẩn hóa phương pháp chứng minh này thành một loại giao dịch mới hoặc đường dẫn khôi phục mà chuỗi có thể nhận diện và xác minh. BIP-360, bước vào quy trình xem xét chính thức hồi tháng 2, tập trung vào việc làm cho các địa chỉ trong tương lai kháng lượng tử ngay từ đầu — một vai trò khác với việc chứng minh quyền sở hữu hậu kỳ cho các địa chỉ đã tồn tại của công cụ này — dù cả hai đề xuất đều có chung một yêu cầu: một thay đổi đồng thuận riêng của chính chúng.</p>
<p class="id">Project Eleven sendiri mengakui bahwa prototipe ini belum diaudit dan masih belum lengkap. Melindungi dana sungguhan terlebih dahulu memerlukan perubahan yang pasti kontroversial pada aturan konsensus Bitcoin — menstandarkan metode bukti ini menjadi jenis transaksi baru atau jalur pemulihan yang dapat dikenali dan diverifikasi oleh rantai. BIP-360, yang memasuki tinjauan resmi pada Februari lalu, berfokus pada membuat alamat masa depan tahan kuantum sejak awal, peran yang berbeda dari bukti kepemilikan pasca-fakta yang ditawarkan alat ini untuk alamat yang sudah ada — meski kedua proposal itu sama-sama membutuhkan perubahan konsensus tersendiri.</p>
<p class="pl">Sam Project Eleven przyznaje, że prototyp nie został poddany audytowi i wciąż jest niekompletny. Ochrona realnych środków wymagałaby najpierw nieuchronnie kontrowersyjnej zmiany zasad konsensusu Bitcoina — ustandaryzowania tej metody dowodowej jako nowego typu transakcji lub ścieżki odzyskiwania, którą łańcuch mógłby rozpoznać i zweryfikować. BIP-360, który w lutym wszedł w formalny proces przeglądu, koncentruje się na tym, by przyszłe adresy były odporne na kwant już od początku — inna rola niż dowód własności ex post, jaki oferuje to narzędzie dla adresów już istniejących — choć oba te wnioski łączy ten sam wymóg: własna, odrębna zmiana konsensusu.</p>
<p class="it">La stessa Project Eleven riconosce che il prototipo non è sottoposto ad audit ed è ancora incompleto. Proteggere fondi reali richiederebbe prima un cambiamento, inevitabilmente controverso, alle regole di consenso di Bitcoin — standardizzare questo metodo di prova in un nuovo tipo di transazione o percorso di recupero che la chain possa riconoscere e verificare. Il BIP-360, entrato in revisione formale a febbraio, si concentra sul rendere gli indirizzi futuri resistenti al quantum fin dall'inizio, un ruolo diverso dalla prova di proprietà a posteriori che questo strumento offre per indirizzi già esistenti — sebbene entrambe le proposte condividano lo stesso requisito: un proprio cambiamento di consenso separato.</p>
<p class="ru">Сама Project Eleven признаёт, что прототип не прошёл аудит и всё ещё незавершён. Для защиты реальных средств сначала потребуется неизбежно спорное изменение правил консенсуса биткоина — стандартизация этого метода доказательства в виде нового типа транзакции или пути восстановления, который сеть сможет распознавать и проверять. BIP-360, вступивший в формальный обзор в феврале, сосредоточен на том, чтобы будущие адреса изначально были устойчивы к квантовым атакам — это другая роль по сравнению с постфактум-доказательством владения этим инструментом для уже существующих адресов, хотя оба предложения объединяет одно требование: собственное отдельное изменение консенсуса.</p>
<p class="zh">Project Eleven自己也承認,這款原型尚未經過稽核,且仍不完整。要真正保護實際資金,首先需要對比特幣共識規則進行必然充滿爭議的變更——也就是將這種證明方式標準化為鏈上可辨識、可驗證的新交易類型或復原路徑。今年2月正式進入審查程序的BIP-360,著眼於讓未來新建立的位址從一開始就具備抗量子能力,這與本工具針對既有位址進行事後所有權證明的角色不同——但兩項提案都同樣需要各自獨立的共識變更。</p>

<p class="ko">이 대목에서 과거 사례를 참고할 만하다. 세그윗(SegWit)은 2015년 제안 이후 활성화까지 2년 넘게 걸렸고, 탭루트(Taproot)조차 비교적 순조로웠던 업그레이드임에도 1년가량이 소요됐다. 두 사례 모두 코드 자체보다 커뮤니티 합의를 모으는 과정이 병목이었다. '논쟁적일 수밖에 없는 변경'이라는 표현이 프로젝트 일레븐의 발표에 등장한 것도 같은 맥락이다. 문제는 이런 합의 형성에 걸리는 시간이 통상 수년 단위인 반면, 암호를 무력화할 수 있는 양자컴퓨터, 이른바 'Q-데이'가 언제 도래할지는 아무도 정확히 알지 못한다는 데 있다. 결국 이 도구가 보여주는 것은 암호학적 결과물 자체의 완성도가 아니라, 비트코인 특유의 보수적이고 느린 거버넌스 속도가 실제 배치 시점을 좌우하는 진짜 병목이라는 사실이다.</p>
<p class="en">History offers a useful benchmark here. SegWit took more than two years from proposal to activation starting in 2015, and even Taproot — a comparatively smooth upgrade — took roughly a year. In both cases, the bottleneck was building community consensus, not writing the code. The phrase "contentious changes to blockchain rules" in Project Eleven's own announcement points to the same dynamic. The problem is that this kind of consensus-building typically runs on a timeline of years, while nobody knows exactly when "Q-Day" — the arrival of a quantum computer capable of breaking today's cryptography — will actually happen. What this tool ultimately demonstrates isn't the polish of the cryptography itself, but that Bitcoin's characteristically conservative, slow-moving governance is the real bottleneck determining when — or whether — it ever gets deployed.</p>
<p class="ja">この点では過去の事例が参考になる。セグウィット(SegWit)は2015年の提案からアクティベーションまで2年以上を要し、比較的スムーズなアップグレードだったタップルート(Taproot)でさえ約1年を要した。どちらの事例でも、ボトルネックはコードそのものではなくコミュニティの合意形成だった。プロジェクト・イレブン自身の発表に「論争を伴わざるを得ない変更」という表現が登場するのも、同じ文脈だ。問題は、こうした合意形成に通常数年単位の時間がかかる一方で、今日の暗号を無力化しうる量子コンピューター、いわゆる「Qデー」がいつ到来するかは誰も正確には分からないという点にある。結局、このツールが示しているのは、暗号技術そのものの完成度ではなく、ビットコイン特有の保守的で緩慢なガバナンス速度こそが、実際の展開時期を左右する本当のボトルネックだという事実だ。</p>
<p class="es">La historia ofrece un punto de referencia útil aquí. SegWit tardó más de dos años desde su propuesta en 2015 hasta su activación, e incluso Taproot —una actualización comparativamente fluida— tardó aproximadamente un año. En ambos casos, el cuello de botella fue construir consenso en la comunidad, no escribir el código. La frase "cambios inevitablemente polémicos en las reglas de la cadena de bloques" en el propio anuncio de Project Eleven apunta a la misma dinámica. El problema es que este tipo de construcción de consenso suele tomar años, mientras que nadie sabe exactamente cuándo llegará el "Día Q" —la aparición de una computadora cuántica capaz de romper la criptografía actual—. Lo que esta herramienta demuestra en última instancia no es el pulido de la criptografía en sí, sino que la gobernanza característicamente conservadora y lenta de Bitcoin es el verdadero cuello de botella que determina cuándo, o si, llegará a implementarse.</p>
<p class="de">Die Geschichte liefert hier einen nützlichen Maßstab. SegWit brauchte von der Vorschlagsphase 2015 bis zur Aktivierung mehr als zwei Jahre, und selbst Taproot — ein vergleichsweise reibungsloses Upgrade — benötigte rund ein Jahr. In beiden Fällen war nicht das Schreiben des Codes der Engpass, sondern der Aufbau des Community-Konsenses. Die Formulierung „zwangsläufig kontroverse Änderungen der Blockchain-Regeln" in Project Elevens eigener Ankündigung verweist auf dieselbe Dynamik. Das Problem: Ein solcher Konsensbildungsprozess dauert üblicherweise Jahre, während niemand genau weiß, wann der sogenannte „Q-Day" — das Eintreffen eines Quantencomputers, der heutige Kryptografie brechen kann — tatsächlich kommt. Was dieses Werkzeug letztlich zeigt, ist nicht die Reife der Kryptografie selbst, sondern dass Bitcoins typisch konservatives, langsames Governance-Tempo der eigentliche Flaschenhals ist, der bestimmt, wann — oder ob überhaupt — es je zum Einsatz kommt.</p>
<p class="fr">L'histoire offre ici un point de référence utile. SegWit a pris plus de deux ans entre sa proposition en 2015 et son activation, et même Taproot — une mise à niveau relativement fluide — a nécessité environ un an. Dans les deux cas, le goulot d'étranglement était la construction d'un consensus communautaire, pas l'écriture du code. L'expression « changements inévitablement controversés aux règles de la blockchain », dans l'annonce même de Project Eleven, renvoie à la même dynamique. Le problème est que ce type de construction de consensus s'étend généralement sur plusieurs années, alors que personne ne sait exactement quand le « Q-Day » — l'arrivée d'un ordinateur quantique capable de briser la cryptographie actuelle — surviendra réellement. Ce que cet outil démontre finalement, ce n'est pas la finition de la cryptographie elle-même, mais que la gouvernance caractéristiquement conservatrice et lente de Bitcoin constitue le véritable goulot d'étranglement qui déterminera quand — ou si — il sera un jour déployé.</p>
<p class="pt">A história oferece uma referência útil aqui. O SegWit levou mais de dois anos, desde a proposta em 2015 até a ativação, e até mesmo o Taproot — uma atualização comparativamente tranquila — levou cerca de um ano. Em ambos os casos, o gargalo foi construir consenso na comunidade, não escrever o código. A expressão "mudanças inevitavelmente controversas nas regras da blockchain", no próprio anúncio da Project Eleven, aponta para a mesma dinâmica. O problema é que esse tipo de construção de consenso costuma levar anos, enquanto ninguém sabe exatamente quando chegará o "Dia Q" — a chegada de um computador quântico capaz de quebrar a criptografia atual. O que essa ferramenta demonstra, no fim das contas, não é o refinamento da criptografia em si, mas que a governança caracteristicamente conservadora e lenta do Bitcoin é o verdadeiro gargalo que determina quando — ou se — ela algum dia será implantada.</p>
<p class="tr">Tarih burada yararlı bir referans sunuyor. SegWit, 2015'teki öneriden aktivasyona kadar iki yıldan fazla sürdü ve nispeten sorunsuz bir yükseltme olan Taproot bile yaklaşık bir yıl aldı. Her iki durumda da darboğaz, kodu yazmak değil, topluluk konsensüsü oluşturmaktı. Project Eleven'ın kendi duyurusundaki "blok zinciri kurallarında kaçınılmaz olarak tartışmalı değişiklikler" ifadesi de aynı dinamiğe işaret ediyor. Sorun şu ki, bu tür bir konsensüs oluşturma süreci genellikle yıllar sürerken, günümüzün kriptografisini kırabilecek bir kuantum bilgisayarın, yani "Q-Günü"'nün ne zaman geleceğini kimse tam olarak bilmiyor. Bu aracın sonuçta gösterdiği şey, kriptografinin kendisinin cilası değil, Bitcoin'in tipik olarak muhafazakâr, yavaş yönetişim hızının, aracın ne zaman — ya da hiç — devreye alınacağını belirleyen gerçek darboğaz olduğudur.</p>
<p class="vi">Lịch sử cung cấp một mốc tham chiếu hữu ích ở đây. SegWit mất hơn hai năm từ khi được đề xuất năm 2015 đến khi kích hoạt, và ngay cả Taproot — một bản nâng cấp tương đối suôn sẻ — cũng mất khoảng một năm. Trong cả hai trường hợp, nút thắt cổ chai là việc xây dựng sự đồng thuận trong cộng đồng, chứ không phải viết mã. Cụm từ "những thay đổi tất yếu gây tranh cãi đối với quy tắc blockchain" trong chính thông báo của Project Eleven cũng phản ánh động lực tương tự. Vấn đề là loại xây dựng đồng thuận này thường kéo dài nhiều năm, trong khi không ai biết chính xác khi nào "Ngày Q" — thời điểm xuất hiện một máy tính lượng tử có khả năng phá vỡ mật mã hiện nay — sẽ thực sự đến. Điều mà công cụ này cuối cùng cho thấy không phải là độ hoàn thiện của bản thân công nghệ mật mã, mà là tốc độ quản trị đặc trưng bảo thủ, chậm chạp của Bitcoin mới chính là nút thắt thực sự quyết định khi nào — hay liệu có bao giờ — nó được triển khai.</p>
<p class="id">Sejarah menawarkan tolok ukur yang berguna di sini. SegWit membutuhkan lebih dari dua tahun sejak diusulkan pada 2015 hingga diaktifkan, dan bahkan Taproot — sebuah peningkatan yang relatif mulus — membutuhkan sekitar satu tahun. Dalam kedua kasus itu, hambatannya adalah membangun konsensus komunitas, bukan menulis kode. Frasa "perubahan yang pasti kontroversial pada aturan blockchain" dalam pengumuman Project Eleven sendiri menunjuk pada dinamika yang sama. Masalahnya, proses membangun konsensus semacam ini biasanya memakan waktu bertahun-tahun, sementara tidak ada yang tahu persis kapan "Q-Day" — kedatangan komputer kuantum yang mampu memecahkan kriptografi saat ini — akan benar-benar terjadi. Yang pada akhirnya ditunjukkan oleh alat ini bukanlah kematangan kriptografinya sendiri, melainkan bahwa kecepatan tata kelola Bitcoin yang khas konservatif dan lambat adalah hambatan nyata yang menentukan kapan — atau apakah — alat ini akan pernah diterapkan.</p>
<p class="pl">Historia daje tu przydatny punkt odniesienia. SegWit potrzebował ponad dwóch lat od propozycji w 2015 roku do aktywacji, a nawet Taproot — stosunkowo płynna aktualizacja — zajął około roku. W obu przypadkach wąskim gardłem było budowanie konsensusu społeczności, a nie pisanie kodu. Sformułowanie "nieuchronnie kontrowersyjne zmiany w zasadach blockchaina" w samym ogłoszeniu Project Eleven wskazuje na tę samą dynamikę. Problem w tym, że tego rodzaju budowanie konsensusu zwykle trwa lata, podczas gdy nikt dokładnie nie wie, kiedy nadejdzie tak zwany "Dzień Q" — moment pojawienia się komputera kwantowego zdolnego złamać dzisiejszą kryptografię. To, co ostatecznie pokazuje to narzędzie, to nie dopracowanie samej kryptografii, lecz fakt, że charakterystycznie konserwatywne, powolne tempo zarządzania Bitcoinem jest prawdziwym wąskim gardłem decydującym o tym, kiedy — a nawet czy w ogóle — zostanie ono wdrożone.</p>
<p class="it">La storia offre qui un utile punto di riferimento. SegWit ha impiegato più di due anni dalla proposta del 2015 fino all'attivazione, e persino Taproot — un aggiornamento relativamente fluido — ha richiesto circa un anno. In entrambi i casi, il collo di bottiglia è stato costruire il consenso della comunità, non scrivere il codice. L'espressione "cambiamenti inevitabilmente controversi alle regole della blockchain", usata dalla stessa Project Eleven nel suo annuncio, rimanda alla stessa dinamica. Il problema è che questo tipo di costruzione del consenso richiede tipicamente anni, mentre nessuno sa esattamente quando arriverà il cosiddetto "Q-Day" — il momento in cui un computer quantistico sarà in grado di violare la crittografia odierna. Ciò che questo strumento dimostra, in definitiva, non è la maturità della crittografia in sé, ma che la governance tipicamente conservatrice e lenta di Bitcoin è il vero collo di bottiglia che determina quando — o se — verrà mai distribuito.</p>
<p class="ru">История даёт здесь полезный ориентир. От предложения SegWit в 2015 году до его активации прошло более двух лет, а даже Taproot — сравнительно гладкое обновление — заняло около года. В обоих случаях узким местом было не написание кода, а достижение консенсуса сообщества. Формулировка «неизбежно спорные изменения правил блокчейна» в собственном заявлении Project Eleven указывает на ту же динамику. Проблема в том, что подобное построение консенсуса обычно занимает годы, тогда как никто точно не знает, когда наступит так называемый «Q-Day» — момент появления квантового компьютера, способного взломать современную криптографию. В конечном счёте этот инструмент демонстрирует не отточенность самой криптографии, а то, что характерно консервативный, медленный темп управления биткоином и есть настоящее узкое место, определяющее, когда — и будет ли вообще — он когда-либо развёрнут.</p>
<p class="zh">歷史在此提供了有用的參考。SegWit從2015年提案到啟用花了超過兩年時間,即便是相對順利的Taproot升級,也耗時約一年。這兩個案例的瓶頸都不在程式碼本身,而在於凝聚社群共識。Project Eleven自己在公告中使用「必然充滿爭議的變更」這樣的措辭,正指向同樣的動態。問題在於,這類共識形成過程通常需要數年時間,而沒有人能確切知道足以破解現今密碼學的量子電腦——所謂的「Q日」——何時真正降臨。這項工具最終展現的,並非密碼學技術本身的成熟度,而是比特幣一貫保守、緩慢的治理節奏,才是決定它何時——甚至能否——真正部署的真正瓶頸。</p>

<div class="ko en ja es de fr pt tr vi id pl it ru zh">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <g font-family="sans-serif">
    <rect x="16" y="40" width="205" height="130" rx="10" fill="#18181b" stroke="#06b6d4" stroke-width="1.4"/>
    <rect x="248" y="40" width="205" height="130" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
    <rect x="480" y="40" width="204" height="130" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
    <text x="34" y="100" fill="#f4f4f5" font-size="40" font-weight="800">243</text>
    <text x="34" y="128" fill="#06b6d4" font-size="16" font-weight="700">ms</text>
    <text x="34" y="155" fill="#71717a" font-size="12">CPU&#215;4</text>
    <text x="266" y="100" fill="#f4f4f5" font-size="40" font-weight="800">40</text>
    <text x="266" y="128" fill="#38bdf8" font-size="16" font-weight="700">ms</text>
    <text x="266" y="155" fill="#71717a" font-size="12">0 GPU</text>
    <text x="498" y="100" fill="#f4f4f5" font-size="40" font-weight="800">16&#215;</text>
    <text x="498" y="128" fill="#a1a1aa" font-size="16" font-weight="700">2GB</text>
    <text x="498" y="155" fill="#71717a" font-size="12">14,600&#8594;243ms</text>
    <line x1="16" y1="200" x2="684" y2="200" stroke="#27272a" stroke-width="1"/>
    <text x="16" y="230" fill="#71717a" font-size="13">2012.02.11 &#183; BIP-32</text>
    <text x="16" y="255" fill="#71717a" font-size="13">&#8776;1.1M BTC &#183; P2PK</text>
    <text x="16" y="290" fill="#52525b" font-size="12">Project Eleven &#183; Jim Posen &#183; Binius ZK</text>
  </g>
</svg>
</div>

<div class="box ko">💡 <strong>관전 포인트:</strong> (1) BIP-360이 올해 안에 공식 제안 번호를 넘어 실제 구현 단계로 나아가는지, (2) 이 증명 시스템이 제3자 감사를 통과해 오픈소스로 공개되는지, (3) 이더리움 등 다른 스마트컨트랙트 체인에서도 유사한 사후 소유권 복구 도구가 등장하는지.</div>
<div class="box en">💡 <strong>Watch for:</strong> (1) whether BIP-360 moves past the proposal stage into actual implementation within the year; (2) whether this proof system passes third-party audit and is released as open source; (3) whether similar after-the-fact ownership-recovery tools emerge on other smart-contract chains like Ethereum.</div>
<div class="box ja">💡 <strong>注目点:</strong>(1)BIP-360が今年中に提案段階を超えて実際の実装段階に進むか、(2)この証明システムが第三者監査を通過しオープンソースとして公開されるか、(3)イーサリアムなど他のスマートコントラクトチェーンでも同様の事後所有権復旧ツールが登場するか。</div>
<div class="box es">💡 <strong>A vigilar:</strong> (1) si el BIP-360 avanza este año más allá de la etapa de propuesta hacia una implementación real; (2) si este sistema de prueba pasa una auditoría de terceros y se publica como código abierto; (3) si surgen herramientas similares de recuperación de propiedad a posteriori en otras cadenas de contratos inteligentes como Ethereum.</div>
<div class="box de">💡 <strong>Zu beobachten:</strong> (1) ob BIP-360 noch in diesem Jahr über die Vorschlagsphase hinaus in die tatsächliche Umsetzung geht; (2) ob dieses Beweissystem ein Audit durch Dritte besteht und als Open Source veröffentlicht wird; (3) ob ähnliche nachträgliche Eigentums-Wiederherstellungswerkzeuge auf anderen Smart-Contract-Chains wie Ethereum entstehen.</div>
<div class="box fr">💡 <strong>À surveiller :</strong> (1) si le BIP-360 dépasse cette année le stade de proposition pour une mise en œuvre réelle ; (2) si ce système de preuve passe un audit tiers et est publié en open source ; (3) si des outils similaires de récupération de propriété a posteriori apparaissent sur d'autres chaînes de contrats intelligents comme Ethereum.</div>
<div class="box pt">💡 <strong>Fique de olho:</strong> (1) se o BIP-360 avança este ano da fase de proposta para a implementação real; (2) se esse sistema de prova passa por auditoria de terceiros e é lançado como código aberto; (3) se ferramentas semelhantes de recuperação de propriedade a posteriori surgem em outras cadeias de contratos inteligentes, como Ethereum.</div>
<div class="box tr">💡 <strong>İzlenecekler:</strong> (1) BIP-360'ın bu yıl içinde öneri aşamasını geçip gerçek uygulamaya geçip geçmeyeceği; (2) bu kanıt sisteminin üçüncü taraf denetiminden geçip açık kaynak olarak yayınlanıp yayınlanmayacağı; (3) Ethereum gibi diğer akıllı kontrat zincirlerinde de benzer, sonradan sahiplik kurtarma araçlarının ortaya çıkıp çıkmayacağı.</div>
<div class="box vi">💡 <strong>Cần theo dõi:</strong> (1) liệu BIP-360 có vượt qua giai đoạn đề xuất để tiến vào triển khai thực tế trong năm nay; (2) liệu hệ thống chứng minh này có vượt qua kiểm toán bên thứ ba và được phát hành dưới dạng mã nguồn mở; (3) liệu các công cụ khôi phục quyền sở hữu hậu kỳ tương tự có xuất hiện trên các chuỗi hợp đồng thông minh khác như Ethereum hay không.</div>
<div class="box id">💡 <strong>Yang perlu dipantau:</strong> (1) apakah BIP-360 akan melampaui tahap proposal menuju implementasi nyata tahun ini; (2) apakah sistem bukti ini lolos audit pihak ketiga dan dirilis sebagai open source; (3) apakah alat pemulihan kepemilikan pasca-fakta serupa muncul di rantai smart contract lain seperti Ethereum.</div>
<div class="box pl">💡 <strong>Warto obserwować:</strong> (1) czy BIP-360 wyjdzie w tym roku poza etap propozycji i trafi do realnej implementacji; (2) czy ten system dowodowy przejdzie audyt strony trzeciej i zostanie udostępniony jako open source; (3) czy podobne narzędzia do odzyskiwania własności ex post pojawią się na innych łańcuchach smart kontraktów, takich jak Ethereum.</div>
<div class="box it">💡 <strong>Da tenere d'occhio:</strong> (1) se il BIP-360 supererà quest'anno la fase di proposta per arrivare a un'implementazione reale; (2) se questo sistema di prova supererà un audit di terze parti e verrà rilasciato come open source; (3) se strumenti simili di recupero della proprietà a posteriori emergeranno su altre chain di smart contract come Ethereum.</div>
<div class="box ru">💡 <strong>Стоит отслеживать:</strong> (1) перейдёт ли BIP-360 в этом году от стадии предложения к реальной реализации; (2) пройдёт ли эта система доказательства сторонний аудит и будет ли она выпущена как open source; (3) появятся ли аналогичные постфактум-инструменты восстановления права собственности на других смарт-контрактных сетях, таких как Ethereum.</div>
<div class="box zh">💡 <strong>觀察重點:</strong>(1)BIP-360今年是否會從提案階段推進到實際實作;(2)這套證明系統能否通過第三方稽核並以開源形式發布;(3)以太坊等其他智能合約鏈是否也會出現類似的事後所有權復原工具。</div>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <text x="60" y="330" fill="#f4f4f5" font-size="150" font-weight="bold">243ms</text>
  <text x="60" y="400" fill="#06b6d4" font-size="42" font-weight="bold">ZK PROOF</text>
  <text x="60" y="460" fill="#a1a1aa" font-size="36" font-weight="bold">16&#215; &#183; BIP-32</text>
  <polygon fill="#22c55e" points="700,415 730,465 670,465"/>
  <image href="/oglogo/BTC.png" x="960" y="40" width="150" height="150"/>
</svg></div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 코인데스크(CoinDesk), 데일리코인(DailyCoin), 코인트리뷴(Cointribune), 크립토이코노미(Crypto Economy), 디크립트(Decrypt), 빗겟뉴스(Bitget News), 크립토노미스트(Cryptonomist), 코인터크(Coin-Turk), 크립토뉴스닷넷(Cryptonews.net)</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: コインデスク(CoinDesk)、デイリーコイン(DailyCoin)、コイントリビューン(Cointribune)、クリプトエコノミー(Crypto Economy)、ディークリプト(Decrypt)、ビットゲットニュース(Bitget News)、クリプトノミスト(Cryptonomist)、コインターク(Coin-Turk)、クリプトニュースネット(Cryptonews.net)</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="id" style="font-size:12px;color:#52525b;margin-top:24px">Sumber: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="pl" style="font-size:12px;color:#52525b;margin-top:24px">Źródła: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="it" style="font-size:12px;color:#52525b;margin-top:24px">Fonti: CoinDesk, DailyCoin, Cointribune, Crypto Economy, Decrypt, Bitget News, Cryptonomist, Coin-Turk, Cryptonews.net</p>
<p class="ru" style="font-size:12px;color:#52525b;margin-top:24px">Источники: КоинДеск (CoinDesk), ДейлиКоин (DailyCoin), Коинтрибьюн (Cointribune), Крипто Экономи (Crypto Economy), Дикрипт (Decrypt), Битгет Ньюс (Bitget News), Криптономист (Cryptonomist), Коин-Терк (Coin-Turk), Криптоньюс.нет (Cryptonews.net)</p>
<p class="zh" style="font-size:12px;color:#52525b;margin-top:24px">資料來源: CoinDesk、DailyCoin、Cointribune、Crypto Economy、Decrypt、Bitget News、Cryptonomist、Coin-Turk、Cryptonews.net</p>

<?php require __DIR__.'/_footer.php'; ?>
