<?php $slug = 'public-miners-record-btc-sale-q1-2026'; require __DIR__.'/_header.php'; ?>

<p class="ko">상장 비트코인 채굴사들이 2026년 1분기에만 <strong>3만 2천 BTC 이상을 매도</strong>해, 2025년 한 해 동안 판 물량 전체를 단일 분기에 넘어섰다고 채굴 전문 매체 TheMinerMag의 집계를 인용해 Cointelegraph와 BeInCrypto가 보도했다. 매도에 나선 곳은 MARA, 클린스파크(CleanSpark), 라이엇(Riot), 캉고(Cango), 코어 사이언티픽(Core Scientific), 비트디어(Bitdeer) 등이다. 이 규모는 2022년 2분기 테라·루나 붕괴 당시 채굴사들이 판 약 2만 BTC를 웃돌아, <strong>단일 분기 기준 사상 최대</strong>의 채굴사 매도 기록을 새로 썼다.</p>
  <p class="en">Listed bitcoin miners sold <strong>more than 32,000 BTC in the first quarter of 2026 alone</strong> — exceeding in a single quarter everything they sold across all of 2025 — Cointelegraph and BeInCrypto reported, citing a tally by the mining outlet TheMinerMag. The sellers include MARA, CleanSpark, Riot, Cango, Core Scientific and Bitdeer. The figure tops the roughly 20,000 BTC miners sold in the second quarter of 2022 during the Terra-Luna collapse, setting a new <strong>single-quarter record</strong> for miner selling.</p>
  <p class="ja">上場ビットコインマイニング企業が2026年第1四半期だけで<strong>3万2千BTC超を売却</strong>し、2025年通年で売った量を単一四半期で上回ったと、マイニング専門メディアTheMinerMagの集計を引用してCointelegraphとBeInCryptoが報じた。売却に動いたのはMARA、クリーンスパーク(CleanSpark)、ライオット(Riot)、カンゴ(Cango)、コア・サイエンティフィック(Core Scientific)、ビットディア(Bitdeer)などだ。この規模は2022年第2四半期のテラ・ルナ崩壊時にマイニング企業が売った約2万BTCを上回り、<strong>単一四半期で史上最大</strong>の採掘企業売却記録を新たに刻んだ。</p>

  <p class="es">Los mineros de bitcoin cotizados vendieron <strong>más de 32.000 BTC solo en el primer trimestre de 2026</strong> —superando en un solo trimestre todo lo que vendieron a lo largo de 2025—, informaron Cointelegraph y BeInCrypto, citando un recuento del medio minero TheMinerMag. Entre los vendedores figuran MARA, CleanSpark, Riot, Cango, Core Scientific y Bitdeer. La cifra supera los aproximadamente 20.000 BTC que los mineros vendieron en el segundo trimestre de 2022 durante el colapso de Terra-Luna, estableciendo un nuevo <strong>récord trimestral</strong> de venta minera.</p>
  <p class="de">Börsennotierte Bitcoin-Miner verkauften <strong>allein im ersten Quartal 2026 mehr als 32.000 BTC</strong> — und übertrafen damit in einem einzigen Quartal alles, was sie über das gesamte Jahr 2025 verkauft hatten, berichteten Cointelegraph und BeInCrypto unter Berufung auf eine Auswertung des Mining-Mediums TheMinerMag. Zu den Verkäufern zählen MARA, CleanSpark, Riot, Cango, Core Scientific und Bitdeer. Die Zahl übertrifft die rund 20.000 BTC, die Miner im zweiten Quartal 2022 während des Terra-Luna-Zusammenbruchs verkauften, und markiert einen neuen <strong>Quartalsrekord</strong> für Miner-Verkäufe.</p>
  <p class="fr">Des mineurs de bitcoin cotés en bourse ont vendu <strong>plus de 32 000 BTC au seul premier trimestre 2026</strong> — dépassant en un seul trimestre tout ce qu'ils avaient vendu au cours de l'année 2025 entière —, ont rapporté Cointelegraph et BeInCrypto, citant un décompte du média spécialisé TheMinerMag. Parmi les vendeurs figurent MARA, CleanSpark, Riot, Cango, Core Scientific et Bitdeer. Ce chiffre dépasse les quelque 20 000 BTC vendus par les mineurs au deuxième trimestre 2022 lors de l'effondrement de Terra-Luna, établissant un nouveau <strong>record trimestriel</strong> de ventes de mineurs.</p>
  <p class="pt">Mineradoras de bitcoin listadas em bolsa venderam <strong>mais de 32.000 BTC somente no primeiro trimestre de 2026</strong> — superando em um único trimestre tudo o que venderam ao longo de 2025 —, informaram Cointelegraph e BeInCrypto, citando um levantamento do veículo especializado em mineração TheMinerMag. Entre as vendedoras estão MARA, CleanSpark, Riot, Cango, Core Scientific e Bitdeer. O número supera os cerca de 20.000 BTC vendidos pelas mineradoras no segundo trimestre de 2022, durante o colapso da Terra-Luna, estabelecendo um novo <strong>recorde trimestral</strong> de vendas de mineradoras.</p>
  <p class="tr">Halka açık bitcoin madencileri, <strong>yalnızca 2026'nın ilk çeyreğinde 32.000 BTC'den fazlasını sattı</strong> — tek bir çeyrekte 2025'in tamamında sattıklarını geride bırakarak — Cointelegraph ve BeInCrypto, madencilik odaklı yayın TheMinerMag'in derlemesine dayanarak bildirdi. Satıcılar arasında MARA, CleanSpark, Riot, Cango, Core Scientific ve Bitdeer bulunuyor. Bu rakam, 2022'nin ikinci çeyreğinde Terra-Luna çöküşü sırasında madencilerin sattığı yaklaşık 20.000 BTC'yi geride bırakarak madenci satışlarında yeni bir <strong>tek çeyrek rekoru</strong> kırdı.</p>
  <p class="vi">Các công ty khai thác bitcoin niêm yết đã bán <strong>hơn 32.000 BTC chỉ riêng trong quý 1 năm 2026</strong> — vượt qua trong một quý duy nhất tổng lượng bán ra suốt cả năm 2025 — theo Cointelegraph và BeInCrypto đưa tin, dẫn số liệu thống kê của trang tin chuyên về khai thác TheMinerMag. Các bên bán bao gồm MARA, CleanSpark, Riot, Cango, Core Scientific và Bitdeer. Con số này vượt qua khoảng 20.000 BTC mà các công ty khai thác đã bán trong quý 2 năm 2022 trong giai đoạn sụp đổ của Terra-Luna, xác lập một <strong>kỷ lục theo quý</strong> mới về hoạt động bán của các công ty khai thác.</p>

  <h2 class="ko">무슨 일이 있었나</h2>
  <h2 class="en">What happened</h2>
  <h2 class="ja">何が起きたのか</h2>
  <h2 class="es">Qué ocurrió</h2>
  <h2 class="de">Was ist passiert</h2>
  <h2 class="fr">Ce qui s'est passé</h2>
  <h2 class="pt">O que aconteceu</h2>
  <h2 class="tr">Neler oldu</h2>
  <h2 class="vi">Chuyện gì đã xảy ra</h2>
  <p class="ko">비트코인 채굴사는 원래 채굴한 코인의 상당 부분을 팔지 않고 대차대조표에 쌓아 두는 '보유(HODL)' 전략을 즐겨 써 왔다. 코인을 팔지 않고 주식·전환사채로 자금을 조달해 채굴 규모를 키우고, 비트코인 가격 상승분을 고스란히 주주 가치로 전환하는 방식이다. 그런데 1분기의 대규모 매도는 이 전략이 <strong>더는 지탱되지 않는 구간</strong>에 진입했음을 뜻한다. TheMinerMag 집계에서 3만 2천 BTC라는 숫자가 충격적인 이유는, 그것이 단순히 많아서가 아니라 채굴사들이 스스로 '팔지 않겠다'던 원칙을 집단적으로 접었다는 신호이기 때문이다.</p>
  <p class="en">Bitcoin miners have long favored a "HODL" strategy of stacking much of what they mine onto their balance sheets rather than selling it. The model raises money through equity and convertible debt instead of selling coins, scales up mining capacity, and converts any rise in bitcoin's price directly into shareholder value. The heavy first-quarter selling means that strategy has entered a zone where it <strong>can no longer be sustained</strong>. The 32,000-BTC figure in the TheMinerMag tally is jarring not merely because it is large but because it signals that miners have collectively abandoned the very principle of "not selling" they had professed.</p>
  <p class="ja">ビットコインのマイニング企業は本来、採掘したコインの相当部分を売らずに貸借対照表へ積み上げる「保有(HODL)」戦略を好んできた。コインを売らずに株式・転換社債で資金を調達してマイニング規模を拡大し、ビットコイン価格の上昇分をそのまま株主価値へ転換する方式だ。ところが第1四半期の大規模売却は、この戦略が<strong>もはや支えきれない領域</strong>に入ったことを意味する。TheMinerMag集計で3万2千BTCという数字が衝撃的なのは、それが単に多いからではなく、マイニング企業が自ら「売らない」と掲げた原則を集団的に畳んだシグナルだからだ。</p>

  <p class="es">Los mineros de bitcoin han favorecido durante mucho tiempo una estrategia de "HODL", acumulando gran parte de lo que minan en sus balances en lugar de venderlo. El modelo capta dinero mediante acciones y deuda convertible en vez de vender monedas, amplía la capacidad de minado y convierte cualquier subida del precio de bitcoin directamente en valor para el accionista. La fuerte venta del primer trimestre significa que esa estrategia ha entrado en una zona donde <strong>ya no puede sostenerse</strong>. La cifra de 32.000 BTC del recuento de TheMinerMag resulta chocante no solo por ser grande, sino porque indica que los mineros han abandonado colectivamente el propio principio de "no vender" que proclamaban.</p>
  <p class="de">Bitcoin-Miner bevorzugten lange eine "HODL"-Strategie, bei der sie einen Großteil des Geförderten in ihre Bilanzen legen, statt es zu verkaufen. Das Modell beschafft Geld über Eigenkapital und Wandelanleihen statt über Münzverkäufe, baut die Mining-Kapazität aus und wandelt jeden Anstieg des Bitcoin-Preises direkt in Aktionärswert um. Der starke Verkauf im ersten Quartal bedeutet, dass diese Strategie in eine Zone geraten ist, in der sie <strong>nicht mehr tragfähig</strong> ist. Die 32.000-BTC-Zahl der TheMinerMag-Auswertung ist erschütternd, nicht weil sie groß ist, sondern weil sie signalisiert, dass Miner das Prinzip des "Nicht-Verkaufens", das sie propagierten, kollektiv aufgegeben haben.</p>
  <p class="fr">Les mineurs de bitcoin ont longtemps privilégié une stratégie de « HODL », empilant l'essentiel de ce qu'ils extraient dans leurs bilans plutôt que de le vendre. Ce modèle lève des fonds par actions et dette convertible plutôt que par la vente de pièces, augmente la capacité de minage et convertit toute hausse du prix du bitcoin directement en valeur pour les actionnaires. Les ventes massives du premier trimestre signifient que cette stratégie est entrée dans une zone où elle <strong>ne peut plus être soutenue</strong>. Le chiffre de 32 000 BTC du décompte de TheMinerMag est frappant non pas simplement parce qu'il est élevé, mais parce qu'il signale que les mineurs ont collectivement abandonné le principe même de « ne pas vendre » qu'ils affichaient.</p>
  <p class="pt">Os mineradores de bitcoin há muito preferem uma estratégia de “HODL”, acumulando grande parte do que minerem em seus balanços em vez de vendê-lo. O modelo capta recursos por meio de ações e dívida conversível em vez de vender moedas, amplia a capacidade de mineração e converte qualquer alta no preço do bitcoin diretamente em valor para os acionistas. A forte venda do primeiro trimestre significa que essa estratégia entrou em uma zona em que <strong>não pode mais ser sustentada</strong>. O número de 32.000 BTC no levantamento da TheMinerMag é impressionante não apenas por ser grande, mas porque sinaliza que as mineradoras abandonaram coletivamente o próprio princípio de “não vender” que professavam.</p>
  <p class="tr">Bitcoin madencileri uzun süredir, ürettiklerinin büyük bölümünü satmak yerine bilançolarında biriktiren bir “HODL” stratejisini tercih etti. Bu model, coin satmak yerine hisse senedi ve dönüştürülebilir borçla fon toplar, madencilik kapasitesini büyütür ve bitcoin fiyatındaki her artışı doğrudan hissedar değerine dönüştürür. İlk çeyrekteki yoğun satış, bu stratejinin artık <strong>sürdürülemeyeceği</strong> bir bölgeye girdiği anlamına geliyor. TheMinerMag derlemesindeki 32.000 BTC rakamı yalnızca büyük olduğu için değil, madencilerin savundukları “satmama” ilkesini topluca terk ettiklerinin bir işareti olduğu için çarpıcı.</p>
  <p class="vi">Các công ty khai thác bitcoin từ lâu đã ưa chuộng chiến lược “HODL” — tích lũy phần lớn lượng coin khai thác được vào bảng cân đối kế toán thay vì bán ra. Mô hình này huy động vốn thông qua cổ phiếu và nợ chuyển đổi thay vì bán coin, mở rộng công suất khai thác, và chuyển hóa trực tiếp bất kỳ mức tăng nào của giá bitcoin thành giá trị cho cổ đông. Đợt bán mạnh trong quý 1 cho thấy chiến lược này đã bước vào vùng <strong>không thể duy trì được nữa</strong>. Con số 32.000 BTC trong thống kê của TheMinerMag gây chấn động không chỉ vì lớn, mà vì nó cho thấy các công ty khai thác đã đồng loạt từ bỏ chính nguyên tắc “không bán” mà họ từng tuyên bố.</p>

  <h2 class="ko">왜 팔았나 — 해시프라이스와 손익분기의 역전</h2>
  <h2 class="en">Why they sold — hashprice and the breakeven inversion</h2>
  <h2 class="ja">なぜ売ったのか — ハッシュプライスと損益分岐の逆転</h2>
  <h2 class="es">Por qué vendieron — el hashprice y la inversión del umbral de rentabilidad</h2>
  <h2 class="de">Warum sie verkauften — Hashprice und die Umkehr der Gewinnschwelle</h2>
  <h2 class="fr">Pourquoi ils ont vendu — le hashprice et l'inversion du seuil de rentabilité</h2>
  <h2 class="pt">Por que venderam — o hashprice e a inversão do ponto de equilíbrio</h2>
  <h2 class="tr">Neden sattılar — hashprice ve başabaş noktasının tersine dönmesi</h2>
  <h2 class="vi">Vì sao họ bán ra — hashprice và sự đảo chiều của điểm hòa vốn</h2>
  <p class="ko">핵심은 '해시프라이스(hashprice)'라는 지표에 있다. 해시프라이스는 채굴 연산력 1페타해시(PH/s)가 하루에 벌어들이는 수익을 뜻하며, 채굴사의 수익성을 가장 직접적으로 보여준다. Cointelegraph에 따르면 현재 해시프라이스는 하루 PH/s당 <strong>약 33달러</strong>로, 다수 사업자의 손익분기점으로 통하는 <strong>약 35달러</strong>를 밑돈다. 그 결과 낡고 효율이 떨어지는 장비를 돌리는 업체를 중심으로 채굴 업계의 <strong>약 20%가 적자 상태</strong>에 놓였다. 전기요금이라는 고정비를 매달 현금으로 내야 하는 채굴사로서는, 팔지 않고 버티는 것 자체가 유동성 위기를 부른다.</p>
  <p class="en">The crux lies in a metric called "hashprice." Hashprice is the daily revenue earned by one petahash per second (PH/s) of mining power, and it is the most direct read on a miner's profitability. According to Cointelegraph, hashprice now sits at <strong>about $33 per PH/s a day</strong>, below the <strong>roughly $35</strong> that serves as a breakeven for many operators. As a result, about <strong>20% of the mining industry is running at a loss</strong>, concentrated among firms operating older, less efficient machines. For a miner that must pay its fixed electricity bill in cash every month, refusing to sell and holding on is itself what invites a liquidity crisis.</p>
  <p class="ja">核心は「ハッシュプライス(hashprice)」という指標にある。ハッシュプライスはマイニング演算力1ペタハッシュ(PH/s)が1日に稼ぐ収益を意味し、採掘企業の収益性を最も直接的に示す。Cointelegraphによれば、現在のハッシュプライスは1日PH/sあたり<strong>約33ドル</strong>で、多くの事業者の損益分岐点とされる<strong>約35ドル</strong>を下回る。その結果、古く効率の落ちる装置を回す業者を中心に、マイニング業界の<strong>約20%が赤字状態</strong>に置かれた。電気料金という固定費を毎月現金で払わねばならない採掘企業にとって、売らずに耐えること自体が流動性危機を招く。</p>

  <p class="es">El quid está en una métrica llamada "hashprice". El hashprice es el ingreso diario que genera un petahash por segundo (PH/s) de potencia de minado, y es la lectura más directa de la rentabilidad de un minero. Según Cointelegraph, el hashprice se sitúa ahora en <strong>unos 33 dólares por PH/s al día</strong>, por debajo de los <strong>aproximadamente 35 dólares</strong> que sirven de umbral de rentabilidad para muchos operadores. Como resultado, cerca del <strong>20% de la industria minera opera con pérdidas</strong>, concentrado en firmas con máquinas más antiguas y menos eficientes. Para un minero que debe pagar en efectivo su factura eléctrica fija cada mes, negarse a vender y aguantar es justo lo que provoca una crisis de liquidez.</p>
  <p class="de">Der Kern liegt in einer Kennzahl namens "Hashprice". Der Hashprice ist der Tagesertrag, den ein Petahash pro Sekunde (PH/s) an Mining-Leistung erzielt, und die direkteste Ablesung der Rentabilität eines Miners. Laut Cointelegraph liegt der Hashprice nun bei <strong>etwa 33 Dollar pro PH/s und Tag</strong>, unter den <strong>rund 35 Dollar</strong>, die für viele Betreiber als Gewinnschwelle gelten. Infolgedessen arbeitet etwa <strong>20% der Mining-Branche mit Verlust</strong>, konzentriert auf Firmen mit älteren, weniger effizienten Maschinen. Für einen Miner, der seine feste Stromrechnung jeden Monat bar zahlen muss, ist das Festhalten ohne Verkauf genau das, was eine Liquiditätskrise auslöst.</p>
  <p class="fr">Le nœud du problème réside dans un indicateur appelé « hashprice ». Le hashprice est le revenu quotidien généré par un pétahash par seconde (PH/s) de puissance de minage, et c'est la mesure la plus directe de la rentabilité d'un mineur. Selon Cointelegraph, le hashprice se situe désormais à <strong>environ 33 dollars par PH/s et par jour</strong>, en dessous des <strong>quelque 35 dollars</strong> qui servent de seuil de rentabilité pour de nombreux opérateurs. Résultat, environ <strong>20 % de l'industrie du minage fonctionne à perte</strong>, concentrée parmi les entreprises exploitant des machines plus anciennes et moins efficaces. Pour un mineur qui doit régler en liquide sa facture d'électricité fixe chaque mois, refuser de vendre et s'accrocher est en soi ce qui provoque une crise de liquidité.</p>
  <p class="pt">O cerne está em uma métrica chamada “hashprice”. O hashprice é a receita diária gerada por um petahash por segundo (PH/s) de poder de mineração, e é a leitura mais direta da rentabilidade de uma mineradora. Segundo a Cointelegraph, o hashprice está agora em <strong>cerca de US$ 33 por PH/s ao dia</strong>, abaixo dos <strong>aproximadamente US$ 35</strong> que servem de ponto de equilíbrio para muitos operadores. Como resultado, cerca de <strong>20% da indústria de mineração opera no prejuízo</strong>, concentrada em empresas que operam máquinas mais antigas e menos eficientes. Para uma mineradora que precisa pagar em dinheiro sua conta de energia fixa todo mês, recusar-se a vender e continuar segurando é, por si só, o que provoca uma crise de liquidez.</p>
  <p class="tr">İşin özü “hashprice” denen bir göstergede yatıyor. Hashprice, bir petahash/saniyelik (PH/s) madencilik gücünün günlük kazandırdığı gelirdir ve bir madencinin kârlılığına dair en doğrudan göstergedir. Cointelegraph'a göre hashprice şu anda <strong>günde PH/s başına yaklaşık 33 dolar</strong> seviyesinde ve birçok işletmeci için başabaş noktası sayılan <strong>yaklaşık 35 doların</strong> altında. Sonuç olarak, daha eski ve daha az verimli makineler işleten şirketlerde yoğunlaşan biçimde, madencilik sektörünün yaklaşık <strong>%20'si zararına çalışıyor</strong>. Her ay sabit elektrik faturasını nakit ödemek zorunda olan bir madenci için, satmayı reddederek dayanmak, likidite krizini davet eden şeyin ta kendisi.</p>
  <p class="vi">Cốt lõi nằm ở một chỉ số gọi là “hashprice”. Hashprice là doanh thu mỗi ngày mà một petahash trên giây (PH/s) công suất khai thác mang lại, và đây là thước đo trực tiếp nhất về khả năng sinh lời của một công ty khai thác. Theo Cointelegraph, hashprice hiện ở mức <strong>khoảng 33 đô la mỗi PH/s một ngày</strong>, thấp hơn mức <strong>khoảng 35 đô la</strong> vốn được xem là điểm hòa vốn đối với nhiều nhà vận hành. Kết quả là khoảng <strong>20% ngành khai thác đang hoạt động thua lỗ</strong>, tập trung ở các công ty vận hành máy móc cũ và kém hiệu quả hơn. Đối với một công ty khai thác phải trả hóa đơn tiền điện cố định bằng tiền mặt mỗi tháng, việc từ chối bán và cố gắng cầm cự chính là điều châm ngòi cho khủng hoảng thanh khoản.</p>

  <div class="ko">
  <svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">해시프라이스 vs 손익분기 — 그리고 분기별 채굴사 매도</text>
    <text x="20" y="46" fill="#a1a1aa" font-size="11" font-family="sans-serif">단위: 해시프라이스 $/PH/s/일 (막대) · 채굴사 매도량 천 BTC (점선)</text>
    <line x1="60" y1="70" x2="60" y2="210" stroke="#3f3f46" stroke-width="1"/>
    <line x1="60" y1="210" x2="670" y2="210" stroke="#3f3f46" stroke-width="1"/>
    <line x1="60" y1="118" x2="670" y2="118" stroke="#ef4444" stroke-width="1" stroke-dasharray="5,4"/>
    <text x="470" y="113" fill="#f87171" font-size="11" font-family="sans-serif">손익분기 ≈ $35</text>
    <g font-family="sans-serif" font-size="11">
      <rect x="110" y="90" width="46" height="120" fill="#22c55e"/><text x="112" y="228" fill="#a1a1aa">'25 3Q</text><text x="116" y="84" fill="#e4e4e7">$52</text>
      <rect x="230" y="104" width="46" height="106" fill="#4ade80"/><text x="232" y="228" fill="#a1a1aa">'25 4Q</text><text x="236" y="98" fill="#e4e4e7">$45</text>
      <rect x="350" y="126" width="46" height="84" fill="#fbbf24"/><text x="352" y="228" fill="#a1a1aa">'26 1Q초</text><text x="356" y="120" fill="#e4e4e7">$38</text>
      <rect x="470" y="132" width="46" height="78" fill="#f97316"/><text x="472" y="228" fill="#a1a1aa">'26 현재</text><text x="476" y="126" fill="#e4e4e7">$33</text>
    </g>
    <polyline points="133,190 253,182 373,150 493,96" fill="none" stroke="#60a5fa" stroke-width="2" stroke-dasharray="4,3"/>
    <circle cx="133" cy="190" r="3" fill="#60a5fa"/><circle cx="253" cy="182" r="3" fill="#60a5fa"/>
    <circle cx="373" cy="150" r="3" fill="#60a5fa"/><circle cx="493" cy="96" r="4" fill="#60a5fa"/>
    <text x="500" y="92" fill="#93c5fd" font-size="11" font-family="sans-serif">1Q 매도 ≈ 32K BTC</text>
    <text x="20" y="262" fill="#a1a1aa" font-size="11" font-family="sans-serif">해시프라이스가 손익분기($35) 아래로 내려앉자, 채굴사 매도량은 반대로 급증했다.</text>
    <text x="20" y="282" fill="#71717a" font-size="10" font-family="sans-serif">※ 해시프라이스 값은 보도된 대략치 기반 도식이며, 1Q 매도 32K BTC는 2022년 2Q(약 20K)를 넘어선 기록.</text>
  </svg>
  <p style="font-size:11px;color:#52525b;margin-top:-10px">출처: TheMinerMag(분기별 채굴사 매도 집계), Cointelegraph·BeInCrypto(해시프라이스·손익분기), CryptoQuant(채굴사 보유량).</p>
  </div>

  <h2 class="ko">과거와의 비교 — 2022년 붕괴기와 무엇이 다른가</h2>
  <h2 class="en">A comparison with the past — how this differs from the 2022 collapse</h2>
  <h2 class="ja">過去との比較 — 2022年崩壊期と何が違うのか</h2>
  <h2 class="es">Una comparación con el pasado — en qué difiere del colapso de 2022</h2>
  <h2 class="de">Ein Vergleich mit der Vergangenheit — worin es sich vom Kollaps 2022 unterscheidet</h2>
  <h2 class="fr">Comparaison avec le passé — en quoi cela diffère de l'effondrement de 2022</h2>
  <h2 class="pt">Uma comparação com o passado — em que isso difere do colapso de 2022</h2>
  <h2 class="tr">Geçmişle bir karşılaştırma — bu, 2022 çöküşünden nasıl farklı</h2>
  <h2 class="vi">So sánh với quá khứ — điều này khác gì so với sự sụp đổ năm 2022</h2>
  <p class="ko">2022년 2분기 채굴사 매도는 테라·루나 붕괴와 그에 이은 셀시우스·쓰리애로우캐피털(3AC) 연쇄 파산이라는 <strong>외생적 신용 충격</strong>이 방아쇠였다. 코인 가격이 급락하자 부채가 많던 채굴사들이 마진콜에 몰려 강제로 물량을 토해낸 것이다. 반면 2026년 1분기 매도는 성격이 다르다. 극적인 가격 붕괴 사건이 없는데도 채굴사들이 팔았다는 점에서, 이번은 사건형 위기가 아니라 <strong>구조적 수익성 압박</strong>의 결과에 가깝다.</p>
  <p class="en">The second-quarter 2022 miner selling was triggered by an <strong>exogenous credit shock</strong> — the Terra-Luna collapse and the chain of Celsius and Three Arrows Capital (3AC) failures that followed. As coin prices cratered, heavily indebted miners were caught in margin calls and forced to disgorge holdings. The first-quarter 2026 selling is different in character. Because miners sold even without a dramatic price-crash event, this looks less like an event-driven crisis and more like the product of a <strong>structural squeeze on profitability</strong>.</p>
  <p class="ja">2022年第2四半期のマイニング企業売却は、テラ・ルナ崩壊とそれに続くセルシウス・スリーアローズ・キャピタル(3AC)の連鎖破綻という<strong>外生的な信用ショック</strong>が引き金だった。コイン価格が急落すると、負債の多いマイニング企業がマージンコールに追い込まれ、強制的に保有分を吐き出した。一方、2026年第1四半期の売却は性格が異なる。劇的な価格崩壊イベントがないのにマイニング企業が売ったという点で、今回は事件型の危機ではなく<strong>構造的な収益性圧迫</strong>の結果に近い。</p>

  <p class="es">La venta minera del segundo trimestre de 2022 se desencadenó por un <strong>choque de crédito exógeno</strong>: el colapso de Terra-Luna y la cadena de quiebras de Celsius y Three Arrows Capital (3AC) que siguió. Cuando los precios se hundieron, los mineros muy endeudados quedaron atrapados en llamadas de margen y forzados a vaciar sus tenencias. La venta del primer trimestre de 2026 es de carácter distinto. Como los mineros vendieron incluso sin un evento dramático de desplome de precios, esto parece menos una crisis impulsada por un evento y más el producto de una <strong>presión estructural sobre la rentabilidad</strong>.</p>
  <p class="de">Der Miner-Verkauf im zweiten Quartal 2022 wurde durch einen <strong>exogenen Kreditschock</strong> ausgelöst — den Terra-Luna-Kollaps und die anschließende Kette von Celsius- und Three-Arrows-Capital-(3AC)-Pleiten. Als die Kurse einbrachen, gerieten hoch verschuldete Miner in Margin Calls und mussten Bestände abstoßen. Der Verkauf im ersten Quartal 2026 ist anderer Natur. Da Miner selbst ohne dramatisches Kurssturz-Ereignis verkauften, wirkt dies weniger wie eine ereignisgetriebene Krise und eher wie das Ergebnis eines <strong>strukturellen Drucks auf die Rentabilität</strong>.</p>
  <p class="fr">La vente des mineurs au deuxième trimestre 2022 avait été déclenchée par un <strong>choc de crédit exogène</strong> — l'effondrement de Terra-Luna et la chaîne de faillites de Celsius et de Three Arrows Capital (3AC) qui a suivi. Alors que les prix des pièces s'effondraient, des mineurs lourdement endettés se sont retrouvés pris dans des appels de marge et contraints de céder leurs avoirs. La vente du premier trimestre 2026 est de nature différente. Le fait que les mineurs aient vendu même sans événement spectaculaire d'effondrement des prix suggère que ceci ressemble moins à une crise déclenchée par un événement qu'au produit d'une <strong>pression structurelle sur la rentabilité</strong>.</p>
  <p class="pt">A venda de mineradoras no segundo trimestre de 2022 foi desencadeada por um <strong>choque de crédito exógeno</strong> — o colapso da Terra-Luna e a cadeia de falências da Celsius e da Three Arrows Capital (3AC) que se seguiu. Com os preços das moedas despencando, mineradoras fortemente endividadas foram pegas em chamadas de margem e forçadas a se desfazer de suas posições. A venda do primeiro trimestre de 2026 tem caráter diferente. Como as mineradoras venderam mesmo sem um evento dramático de colapso de preços, isso se assemelha menos a uma crise motivada por um evento e mais ao resultado de uma <strong>pressão estrutural sobre a rentabilidade</strong>.</p>
  <p class="tr">2022'nin ikinci çeyreğindeki madenci satışını tetikleyen, <strong>dışsal bir kredi şoku</strong> — Terra-Luna çöküşü ve ardından gelen Celsius ile Three Arrows Capital (3AC) iflasları zinciriydi. Coin fiyatları çökerken, ağır borçlu madenciler teminat çağrılarına yakalandı ve varlıklarını elden çıkarmak zorunda kaldı. 2026'nın ilk çeyreğindeki satış farklı bir nitelik taşıyor. Madenciler dramatik bir fiyat çöküşü olayı olmadan bile sattığı için, bu durum olay kaynaklı bir kriz olmaktan çok, <strong>kârlılık üzerindeki yapısal baskının</strong> bir sonucu gibi görünüyor.</p>
  <p class="vi">Đợt bán ra của các công ty khai thác trong quý 2 năm 2022 bị kích hoạt bởi một <strong>cú sốc tín dụng từ bên ngoài</strong> — sự sụp đổ của Terra-Luna và chuỗi phá sản tiếp theo của Celsius và Three Arrows Capital (3AC). Khi giá coin lao dốc, các công ty khai thác nợ nần chồng chất bị mắc kẹt trong các lệnh gọi ký quỹ và buộc phải bán tháo tài sản nắm giữ. Đợt bán trong quý 1 năm 2026 mang tính chất khác. Vì các công ty khai thác vẫn bán ra ngay cả khi không có một sự kiện sụp đổ giá kịch tính nào, điều này trông giống một kết quả của <strong>áp lực mang tính cấu trúc lên khả năng sinh lời</strong> hơn là một cuộc khủng hoảng do sự kiện gây ra.</p>

  <p class="ko">그 구조적 압박의 뿌리는 2024년 4월 반감기다. 반감기로 블록 보상이 절반으로 줄어든 뒤에도 네트워크 해시레이트는 계속 상승해, 같은 보상을 더 많은 채굴자가 나눠 갖는 상황이 심화됐다. Cointelegraph는 이를 두고 채굴 수익성이 "한 자릿수 배수만큼(order of magnitude)" 압축됐다고 표현했다. 즉 이번 매도는 단일 사건이 아니라 반감기 이후 누적된 마진 침식이 임계점에 도달한 결과로 읽는 편이 정확하다.</p>
  <p class="en">The root of that structural squeeze is the April 2024 halving. Even after the halving cut block rewards in half, network hashrate kept climbing, so the same reward is split among ever more miners. Cointelegraph described this as mining profitability compressing "by an order of magnitude." In other words, this selling is more accurately read not as a single event but as the point at which the margin erosion accumulating since the halving finally reached a threshold.</p>
  <p class="ja">その構造的圧迫の根は2024年4月の半減期だ。半減期でブロック報酬が半分に減った後もネットワークのハッシュレートは上昇を続け、同じ報酬をより多くの採掘者が分け合う状況が深まった。Cointelegraphはこれを、マイニング収益性が「一桁の倍率で(order of magnitude)」圧縮されたと表現した。つまり今回の売却は単一の事件ではなく、半減期以降に積み上がったマージン侵食が臨界点に達した結果と読むほうが正確だ。</p>

  <p class="es">La raíz de esa presión estructural es el halving de abril de 2024. Aun después de que el halving redujera a la mitad las recompensas por bloque, el hashrate de la red siguió subiendo, de modo que la misma recompensa se reparte entre cada vez más mineros. Cointelegraph describió esto como una compresión de la rentabilidad minera "en un orden de magnitud". En otras palabras, esta venta se lee con más precisión no como un evento único, sino como el punto en que la erosión de márgenes acumulada desde el halving alcanzó por fin un umbral.</p>
  <p class="de">Die Wurzel dieses strukturellen Drucks ist das Halving vom April 2024. Selbst nachdem das Halving die Blockbelohnungen halbierte, stieg die Netzwerk-Hashrate weiter, sodass sich dieselbe Belohnung auf immer mehr Miner verteilt. Cointelegraph beschrieb dies als eine Kompression der Mining-Rentabilität "um eine Größenordnung". Mit anderen Worten: Dieser Verkauf liest sich genauer nicht als Einzelereignis, sondern als der Punkt, an dem die seit dem Halving aufgelaufene Margenerosion endlich eine Schwelle erreichte.</p>
  <p class="fr">La racine de cette pression structurelle est le halving d'avril 2024. Même après que le halving a réduit de moitié les récompenses de bloc, le hashrate du réseau a continué de grimper, de sorte que la même récompense se répartit entre un nombre toujours croissant de mineurs. Cointelegraph a décrit cela comme une compression de la rentabilité du minage « d'un ordre de grandeur ». Autrement dit, il est plus juste de lire cette vente non pas comme un événement isolé, mais comme le moment où l'érosion des marges accumulée depuis le halving a finalement atteint un seuil critique.</p>
  <p class="pt">A raiz dessa pressão estrutural é o halving de abril de 2024. Mesmo depois que o halving cortou as recompensas por bloco pela metade, o hashrate da rede continuou subindo, de modo que a mesma recompensa passou a ser dividida entre um número cada vez maior de mineradores. A Cointelegraph descreveu isso como a rentabilidade da mineração se comprimindo “em uma ordem de grandeza”. Em outras palavras, é mais preciso ler essa venda não como um evento isolado, mas como o ponto em que a erosão de margem acumulada desde o halving finalmente atingiu um limiar.</p>
  <p class="tr">Bu yapısal baskının kökeni 2024 Nisan ayındaki yarılanmadır (halving). Yarılanma blok ödüllerini yarıya indirdikten sonra bile ağın hash oranı yükselmeye devam etti; böylece aynı ödül gitgide daha fazla madenci arasında paylaşılır oldu. Cointelegraph bunu, madencilik kârlılığının “bir büyüklük mertebesi kadar” sıkıştığı şeklinde tanımladı. Başka bir deyişle, bu satışı tek bir olay olarak değil, yarılanmadan bu yana biriken marj erozyonunun sonunda bir eşiğe ulaştığı nokta olarak okumak daha doğru.</p>
  <p class="vi">Gốc rễ của áp lực cấu trúc đó là sự kiện halving (giảm một nửa phần thưởng) tháng 4 năm 2024. Ngay cả sau khi halving cắt giảm một nửa phần thưởng khối, hashrate của mạng lưới vẫn tiếp tục tăng, khiến cùng một phần thưởng phải chia cho ngày càng nhiều công ty khai thác hơn. Cointelegraph mô tả điều này là khả năng sinh lời của hoạt động khai thác bị nén lại “theo cả một bậc độ lớn”. Nói cách khác, đợt bán này nên được hiểu chính xác hơn không phải như một sự kiện đơn lẻ, mà là thời điểm mà sự xói mòn biên lợi nhuận tích lũy kể từ sau halving cuối cùng đã chạm ngưỡng.</p>

  <h2 class="ko">자본은 어디로 가나 — AI로 옮겨가는 채굴 인프라</h2>
  <h2 class="en">Where the capital goes — mining infrastructure shifting to AI</h2>
  <h2 class="ja">資本はどこへ向かうのか — AIへ移るマイニング基盤</h2>
  <h2 class="es">Adónde va el capital — la infraestructura minera se desplaza hacia la IA</h2>
  <h2 class="de">Wohin das Kapital wandert — Mining-Infrastruktur verlagert sich zur KI</h2>
  <h2 class="fr">Où va le capital — l'infrastructure de minage bascule vers l'IA</h2>
  <h2 class="pt">Para onde vai o capital — a infraestrutura de mineração migra para a IA</h2>
  <h2 class="tr">Sermaye nereye gidiyor — madencilik altyapısı yapay zekâya kayıyor</h2>
  <h2 class="vi">Dòng vốn đang chảy về đâu — hạ tầng khai thác chuyển hướng sang AI</h2>
  <p class="ko">매도 대금의 상당 부분이 단순한 생존 자금이 아니라 <strong>사업 방향 전환</strong>에 쓰인다는 점이 이번 국면의 새로운 지점이다. KuCoin은 이번 매도를 다룬 속보에서 채굴사들이 확보한 현금을 <strong>AI·고성능 컴퓨팅(HPC) 인프라</strong>로 재배치하고 있다고 전했다. 대규모 전력 계약, 냉각 설비, 데이터센터 부지라는 채굴사의 핵심 자산은 AI 연산 수요에도 그대로 쓸 수 있어, 채굴로는 수지가 안 맞는 전력을 AI 임대로 돌리는 편이 훨씬 높은 수익을 낸다.</p>
  <p class="en">A new feature of this phase is that much of the sale proceeds fund not mere survival but a <strong>pivot in business direction</strong>. In a bulletin on the selling, KuCoin reported that miners are reallocating the cash they raise toward <strong>AI and high-performance computing (HPC) infrastructure</strong>. A miner's core assets — large power contracts, cooling systems and data-center sites — carry directly over to AI compute demand, so redirecting power that no longer pays through mining into AI leasing yields far higher returns.</p>
  <p class="ja">売却代金の相当部分が単なる生存資金ではなく<strong>事業方向の転換</strong>に使われている点が、今局面の新しい所だ。KuCoinは今回の売却を扱った速報で、マイニング企業が確保した現金を<strong>AI・高性能計算(HPC)基盤</strong>へ再配分していると伝えた。大規模な電力契約、冷却設備、データセンター用地というマイニング企業の中核資産はAI計算需要にもそのまま使え、マイニングでは採算が合わない電力をAI賃貸へ回すほうがはるかに高い収益を生む。</p>

  <p class="es">Un rasgo nuevo de esta fase es que gran parte de los ingresos por ventas financia no la mera supervivencia, sino un <strong>giro en la dirección del negocio</strong>. En un boletín sobre las ventas, KuCoin informó de que los mineros están reasignando el efectivo que captan hacia <strong>infraestructura de IA y computación de alto rendimiento (HPC)</strong>. Los activos centrales de un minero —grandes contratos de energía, sistemas de refrigeración y emplazamientos de centros de datos— se trasladan directamente a la demanda de cómputo de IA, de modo que redirigir hacia el alquiler de IA la energía que ya no rinde en minería genera rendimientos muy superiores.</p>
  <p class="de">Ein neues Merkmal dieser Phase ist, dass ein Großteil der Verkaufserlöse nicht bloßes Überleben, sondern einen <strong>Kurswechsel im Geschäft</strong> finanziert. In einer Meldung zu den Verkäufen berichtete KuCoin, dass Miner das aufgenommene Geld in <strong>KI- und Hochleistungsrechen-(HPC)-Infrastruktur</strong> umschichten. Die Kernvermögen eines Miners — große Stromverträge, Kühlsysteme und Rechenzentrumsflächen — lassen sich direkt auf KI-Rechenbedarf übertragen, sodass die Umleitung von Strom, der sich im Mining nicht mehr rechnet, in KI-Vermietung weit höhere Renditen bringt.</p>
  <p class="fr">Une caractéristique nouvelle de cette phase est qu'une grande partie du produit des ventes ne finance pas la simple survie, mais un <strong>changement de cap stratégique</strong>. Dans un bulletin consacré à ces ventes, KuCoin a rapporté que les mineurs réaffectent les liquidités levées vers des <strong>infrastructures d'IA et de calcul haute performance (HPC)</strong>. Les actifs essentiels d'un mineur — vastes contrats d'électricité, systèmes de refroidissement et sites de centres de données — se transposent directement à la demande de calcul pour l'IA, si bien que rediriger vers la location de capacité IA une électricité qui ne rentabilise plus le minage génère des rendements bien supérieurs.</p>
  <p class="pt">Uma característica nova dessa fase é que grande parte da receita das vendas não financia a mera sobrevivência, mas uma <strong>mudança de rumo nos negócios</strong>. Em um boletim sobre as vendas, a KuCoin informou que as mineradoras estão realocando o caixa captado para <strong>infraestrutura de IA e computação de alto desempenho (HPC)</strong>. Os ativos centrais de uma mineradora — grandes contratos de energia, sistemas de resfriamento e locais de data center — se aplicam diretamente à demanda de computação de IA, de modo que redirecionar para a locação de IA a energia que não compensa mais na mineração gera retornos muito maiores.</p>
  <p class="tr">Bu evrenin yeni bir özelliği, satış gelirlerinin büyük kısmının yalnızca hayatta kalmayı değil, <strong>iş yönünde bir dönüşü</strong> finanse etmesidir. Satışlarla ilgili bir bültende KuCoin, madencilerin topladıkları nakdi <strong>yapay zekâ ve yüksek performanslı bilgi işlem (HPC) altyapısına</strong> yeniden tahsis ettiğini bildirdi. Bir madencinin temel varlıkları — büyük elektrik sözleşmeleri, soğutma sistemleri ve veri merkezi arazileri — doğrudan yapay zekâ hesaplama talebine aktarılabiliyor; bu yüzden madencilikte artık karşılığını vermeyen elektriği yapay zekâ kiralamasına yönlendirmek çok daha yüksek getiri sağlıyor.</p>
  <p class="vi">Một đặc điểm mới của giai đoạn này là phần lớn số tiền thu được từ việc bán ra không chỉ tài trợ cho sự sống còn đơn thuần mà còn cho một <strong>bước chuyển hướng kinh doanh</strong>. Trong một bản tin về đợt bán ra này, KuCoin cho biết các công ty khai thác đang tái phân bổ nguồn tiền huy động được vào <strong>hạ tầng AI và điện toán hiệu năng cao (HPC)</strong>. Các tài sản cốt lõi của một công ty khai thác — hợp đồng điện năng quy mô lớn, hệ thống làm mát và mặt bằng trung tâm dữ liệu — có thể chuyển thẳng sang phục vụ nhu cầu tính toán AI, nên việc chuyển hướng phần điện năng không còn sinh lời qua khai thác sang cho thuê phục vụ AI mang lại lợi nhuận cao hơn nhiều.</p>

  <p class="ko">다만 이 전환을 마냥 긍정적으로만 볼 수는 없다. 채굴 인프라가 AI로 흘러갈수록 비트코인 네트워크의 해시레이트를 떠받치던 상장 채굴사의 유인은 약해질 수 있다. 반대 해석도 있다. 수익성 낮은 낡은 장비가 퇴출되고 저비용·고효율 사업자만 남으면, 채굴 산업 전체의 체질은 오히려 단단해진다는 것이다. 어느 쪽이든, '채굴사=비트코인 가격의 순수 레버리지'라는 오래된 등식은 AI라는 제2의 수익원이 끼어들면서 흔들리고 있다.</p>
  <p class="en">Yet the pivot should not be read as purely positive. The more mining infrastructure flows to AI, the weaker the incentive of listed miners that had propped up bitcoin's network hashrate may become. There is a counter-reading, too: if unprofitable old machines are pushed out and only low-cost, high-efficiency operators remain, the mining industry's underlying constitution actually hardens. Either way, the old equation of "miner equals pure leverage on the bitcoin price" is wobbling as a second revenue source — AI — muscles in.</p>
  <p class="ja">ただしこの転換を手放しで肯定的に見ることはできない。マイニング基盤がAIへ流れるほど、ビットコインのネットワークハッシュレートを支えてきた上場マイニング企業の誘因は弱まりうる。逆の解釈もある。収益性の低い古い装置が淘汰され、低コスト・高効率の事業者だけが残れば、マイニング産業全体の体質はむしろ強固になるというものだ。いずれにせよ、「マイニング企業=ビットコイン価格の純レバレッジ」という古い等式は、AIという第二の収益源が割り込むことで揺らいでいる。</p>

  <p class="es">Sin embargo, el giro no debe leerse como puramente positivo. Cuanta más infraestructura minera fluya hacia la IA, más débil puede volverse el incentivo de los mineros cotizados que habían sostenido el hashrate de la red de bitcoin. También hay una lectura contraria: si las viejas máquinas no rentables son expulsadas y solo quedan operadores de bajo coste y alta eficiencia, la constitución de fondo de la industria minera en realidad se endurece. En cualquier caso, la vieja ecuación de "minero igual a apalancamiento puro sobre el precio de bitcoin" se tambalea a medida que una segunda fuente de ingresos —la IA— se cuela.</p>
  <p class="de">Doch der Kurswechsel sollte nicht als rein positiv gelesen werden. Je mehr Mining-Infrastruktur zur KI fließt, desto schwächer könnte der Anreiz börsennotierter Miner werden, die Bitcoins Netzwerk-Hashrate gestützt hatten. Es gibt auch eine Gegenlesart: Werden unrentable alte Maschinen verdrängt und bleiben nur kostengünstige, hocheffiziente Betreiber, härtet sich die Grundverfassung der Mining-Branche sogar. So oder so gerät die alte Gleichung "Miner gleich reiner Hebel auf den Bitcoin-Preis" ins Wanken, während sich eine zweite Ertragsquelle — KI — hineindrängt.</p>
  <p class="fr">Pourtant, ce virage ne doit pas être lu comme purement positif. Plus l'infrastructure de minage bascule vers l'IA, plus l'incitation des mineurs cotés qui soutenaient le hashrate du réseau bitcoin pourrait s'affaiblir. Il existe aussi une lecture inverse : si les vieilles machines non rentables sont éliminées et qu'il ne reste que des opérateurs à faible coût et haute efficacité, la constitution sous-jacente de l'industrie du minage se renforce en réalité. Dans un cas comme dans l'autre, la vieille équation selon laquelle « le mineur équivaut à un pur levier sur le prix du bitcoin » vacille à mesure qu'une seconde source de revenus — l'IA — s'y invite.</p>
  <p class="pt">Ainda assim, essa guinada não deve ser lida como puramente positiva. Quanto mais infraestrutura de mineração migrar para a IA, mais fraco pode se tornar o incentivo das mineradoras listadas que sustentavam o hashrate da rede bitcoin. Há também uma leitura contrária: se as máquinas antigas e não lucrativas forem eliminadas e restarem apenas operadores de baixo custo e alta eficiência, a constituição de fundo da indústria de mineração na verdade se fortalece. De qualquer forma, a velha equação de que “mineradora equivale a alavancagem pura sobre o preço do bitcoin” está tremendo à medida que uma segunda fonte de receita — a IA — se impõe.</p>
  <p class="tr">Yine de bu dönüş yalnızca olumlu olarak okunmamalı. Madencilik altyapısı yapay zekâya ne kadar çok akarsa, bitcoin ağının hash oranını ayakta tutan halka açık madencilerin motivasyonu o kadar zayıflayabilir. Bunun tersi bir okuma da var: kârsız eski makineler devre dışı kalıp yalnızca düşük maliyetli, yüksek verimli işletmeciler kalırsa, madencilik sektörünün altta yatan yapısı aslında güçlenir. Her iki durumda da, “madenci bitcoin fiyatına saf bir kaldıraçtır” şeklindeki eski denklem, ikinci bir gelir kaynağı olan yapay zekânın araya girmesiyle sarsılıyor.</p>
  <p class="vi">Tuy nhiên, bước chuyển hướng này không nên được xem là hoàn toàn tích cực. Hạ tầng khai thác càng chảy nhiều về phía AI, động lực của các công ty khai thác niêm yết vốn từng nâng đỡ hashrate mạng lưới bitcoin có thể càng suy yếu. Cũng có một cách lý giải ngược lại: nếu các máy móc cũ kém sinh lời bị loại bỏ và chỉ còn lại những nhà vận hành chi phí thấp, hiệu suất cao, thì bản chất nền tảng của ngành khai thác thực ra lại trở nên vững chắc hơn. Dù theo hướng nào, phương trình cũ cho rằng “công ty khai thác đồng nghĩa với đòn bẩy thuần túy lên giá bitcoin” đang lung lay khi một nguồn doanh thu thứ hai — AI — chen chân vào.</p>

  <h2 class="ko">무엇을 지켜봐야 하나</h2>
  <h2 class="en">What to watch</h2>
  <h2 class="ja">何を注視すべきか</h2>
  <h2 class="es">Qué observar</h2>
  <h2 class="de">Worauf zu achten ist</h2>
  <h2 class="fr">Ce qu'il faut surveiller</h2>
  <h2 class="pt">O que observar</h2>
  <h2 class="tr">Nelere dikkat edilmeli</h2>
  <h2 class="vi">Những điều cần theo dõi</h2>
  <p class="ko">지켜볼 첫 번째 지표는 CryptoQuant가 집계하는 채굴사 보유량이다. 2023년 말 186만 BTC에서 약 180만 BTC로 줄어든 이 곡선이 계속 우하향한다면, 채굴사 매도가 일회성이 아니라 추세로 굳어지고 있다는 뜻이다. 두 번째는 해시레이트다. 적자 채굴자가 실제로 전원을 내리면 해시레이트가 꺾이고, 이는 난이도 하향 조정으로 이어져 살아남은 채굴자의 수익성을 회복시키는 자기교정 메커니즘이 작동한다. 이 조정이 언제, 얼마나 강하게 나타나는지가 채굴 산업 바닥의 신호가 될 수 있다.</p>
  <p class="en">The first gauge to watch is the miner-held balance tracked by CryptoQuant. If the curve that has slipped from 1.86 million BTC at the end of 2023 to about 1.8 million keeps sloping down, it means miner selling is hardening from a one-off into a trend. The second is hashrate. When loss-making miners actually power down, hashrate bends lower, which triggers a downward difficulty adjustment — a self-correcting mechanism that restores the profitability of the survivors. When and how strongly that adjustment appears can serve as a signal of a bottom in the mining industry.</p>
  <p class="ja">注視すべき第一の指標はCryptoQuantが集計する採掘企業保有量だ。2023年末の186万BTCから約180万BTCへ減ったこの曲線が右肩下がりを続けるなら、マイニング企業の売却が一過性ではなく趨勢として固まっていることを意味する。第二はハッシュレートだ。赤字の採掘者が実際に電源を落とせばハッシュレートが折れ、それが難易度の下方調整につながり、生き残った採掘者の収益性を回復させる自己修正メカニズムが働く。この調整がいつ、どれほど強く現れるかがマイニング産業の底のシグナルとなりうる。</p>

  <p class="es">El primer indicador a vigilar es el saldo en manos de los mineros que rastrea CryptoQuant. Si la curva que ha bajado de 1,86 millones de BTC a finales de 2023 a unos 1,8 millones sigue inclinándose a la baja, significa que la venta minera se endurece de un hecho puntual a una tendencia. El segundo es el hashrate. Cuando los mineros con pérdidas realmente apagan sus equipos, el hashrate se dobla a la baja, lo que dispara un ajuste de dificultad a la baja —un mecanismo autocorrector que restaura la rentabilidad de los supervivientes. Cuándo y con qué fuerza aparezca ese ajuste puede servir de señal de un suelo en la industria minera.</p>
  <p class="de">Der erste zu beobachtende Messwert ist der von CryptoQuant erfasste Miner-Bestand. Neigt sich die Kurve, die von 1,86 Millionen BTC Ende 2023 auf etwa 1,8 Millionen gerutscht ist, weiter abwärts, verfestigt sich der Miner-Verkauf von einem Einzelfall zu einem Trend. Der zweite ist die Hashrate. Fahren verlustbringende Miner tatsächlich herunter, knickt die Hashrate ein, was eine Abwärtsanpassung der Schwierigkeit auslöst — ein selbstkorrigierender Mechanismus, der die Rentabilität der Überlebenden wiederherstellt. Wann und wie stark diese Anpassung auftritt, kann als Signal für einen Boden in der Mining-Branche dienen.</p>
  <p class="fr">Le premier indicateur à surveiller est le solde détenu par les mineurs, suivi par CryptoQuant. Si la courbe, qui est passée de 1,86 million de BTC fin 2023 à environ 1,8 million, continue de s'incliner vers le bas, cela signifie que la vente des mineurs se durcit, passant d'un épisode isolé à une tendance. Le second est le hashrate. Lorsque des mineurs déficitaires cessent réellement leur activité, le hashrate fléchit, ce qui déclenche un ajustement à la baisse de la difficulté — un mécanisme autocorrecteur qui restaure la rentabilité des survivants. Le moment et la vigueur de cet ajustement peuvent servir de signal d'un point bas pour l'industrie du minage.</p>
  <p class="pt">O primeiro indicador a observar é o saldo em posse das mineradoras, acompanhado pela CryptoQuant. Se a curva, que recuou de 1,86 milhão de BTC no fim de 2023 para cerca de 1,8 milhão, continuar em queda, isso significa que a venda das mineradoras está se consolidando de um evento isolado para uma tendência. O segundo é o hashrate. Quando mineradoras deficitárias realmente desligam seus equipamentos, o hashrate recua, o que aciona um ajuste de dificuldade para baixo — um mecanismo autocorretivo que restaura a rentabilidade das sobreviventes. Quando e com que intensidade esse ajuste aparecer pode servir de sinal de um fundo na indústria de mineração.</p>
  <p class="tr">İzlenecek ilk gösterge, CryptoQuant tarafından takip edilen madenci elindeki bakiyedir. 2023 sonundaki 1,86 milyon BTC'den yaklaşık 1,8 milyona gerileyen bu eğri aşağı yönlü eğimini sürdürürse, bu, madenci satışlarının tek seferlik bir durumdan bir eğilime dönüştüğü anlamına gelir. İkincisi hash oranıdır. Zarar eden madenciler fiilen makinelerini kapattığında hash oranı aşağı bükülür, bu da zorluk seviyesinde aşağı yönlü bir ayarlamayı tetikler — hayatta kalanların kârlılığını geri kazandıran kendi kendini düzelten bir mekanizma. Bu ayarlamanın ne zaman ve ne kadar güçlü ortaya çıktığı, madencilik sektöründe bir dip sinyali olarak işlev görebilir.</p>
  <p class="vi">Chỉ báo đầu tiên cần theo dõi là số dư nắm giữ của các công ty khai thác mà CryptoQuant theo dõi. Nếu đường cong đã giảm từ 1,86 triệu BTC vào cuối năm 2023 xuống còn khoảng 1,8 triệu tiếp tục đi xuống, điều đó có nghĩa là hoạt động bán ra của các công ty khai thác đang trở nên cố định, chuyển từ một sự kiện đơn lẻ thành một xu hướng. Chỉ báo thứ hai là hashrate. Khi các công ty khai thác thua lỗ thực sự tắt máy, hashrate sẽ giảm xuống, kéo theo một đợt điều chỉnh độ khó theo hướng giảm — một cơ chế tự điều chỉnh giúp khôi phục khả năng sinh lời cho những bên còn trụ lại. Thời điểm và mức độ mạnh yếu của đợt điều chỉnh này có thể là tín hiệu cho một đáy của ngành khai thác.</p>

  <p class="ko">이번 매도 물결은 <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">해시레이트는 사상 최고, 채굴 수익은 최저로 갈라진 두 곡선</a>의 이면을 보여준다. 채굴자 스트레스를 읽는 전통 지표의 한계는 <a href="/blog/hash-ribbon-false-signals.html">해시 리본의 거짓 신호</a>에서, 채굴 수익성의 장기 천장 하락은 <a href="/blog/puell-multiple-ceiling-decay.html">퓨엘 멀티플 상단의 구조적 하락</a>에서 각각 이어서 확인할 수 있다. 개별 채굴사의 구조조정 사례로는 <a href="/blog/sbi-crypto-mining-pool-shutdown.html">SBI 크립토의 채굴풀 폐쇄</a>가 대표적이다.</p>
  <p class="en">This wave of selling exposes the flip side of <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">the two curves splitting apart — record-high hashrate and record-low miner revenue</a>. The limits of traditional gauges for reading miner stress can be followed in <a href="/blog/hash-ribbon-false-signals.html">the false signals of the Hash Ribbon</a>, and the long-run decline in the ceiling of mining profitability in <a href="/blog/puell-multiple-ceiling-decay.html">the structural decay of the Puell Multiple's upper bound</a>. A representative case of an individual miner's restructuring is <a href="/blog/sbi-crypto-mining-pool-shutdown.html">SBI Crypto's mining-pool shutdown</a>.</p>
  <p class="ja">今回の売却の波は、<a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">ハッシュレートは史上最高、採掘収益は最低へと分かれた二つの曲線</a>の裏面を示す。採掘者ストレスを読む伝統的指標の限界は<a href="/blog/hash-ribbon-false-signals.html">ハッシュリボンの偽シグナル</a>で、採掘収益性の長期的な天井低下は<a href="/blog/puell-multiple-ceiling-decay.html">ピュエル・マルチプル上限の構造的低下</a>で、それぞれ続けて確認できる。個別マイニング企業の再編事例としては<a href="/blog/sbi-crypto-mining-pool-shutdown.html">SBIクリプトのマイニングプール閉鎖</a>が代表的だ。</p>

  <p class="es">Esta ola de ventas expone la otra cara de <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">las dos curvas que se separan —hashrate en máximos y ingresos mineros en mínimos</a>. Los límites de los indicadores tradicionales para leer el estrés minero pueden seguirse en <a href="/blog/hash-ribbon-false-signals.html">las señales falsas del Hash Ribbon</a>, y el descenso a largo plazo del techo de la rentabilidad minera en <a href="/blog/puell-multiple-ceiling-decay.html">el deterioro estructural del límite superior del Múltiplo de Puell</a>. Un caso representativo de reestructuración de un minero individual es <a href="/blog/sbi-crypto-mining-pool-shutdown.html">el cierre del pool de minado de SBI Crypto</a>.</p>
  <p class="de">Diese Verkaufswelle offenbart die Kehrseite <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">der zwei auseinanderdriftenden Kurven — Rekord-Hashrate und Rekordtief bei den Miner-Erlösen</a>. Die Grenzen traditioneller Messgrößen zum Ablesen des Miner-Stresses lassen sich in <a href="/blog/hash-ribbon-false-signals.html">den Fehlsignalen des Hash Ribbon</a> weiterverfolgen und der langfristige Rückgang der Obergrenze der Mining-Rentabilität in <a href="/blog/puell-multiple-ceiling-decay.html">dem strukturellen Verfall der oberen Grenze des Puell-Multiples</a>. Ein repräsentativer Fall der Restrukturierung eines einzelnen Miners ist <a href="/blog/sbi-crypto-mining-pool-shutdown.html">die Schließung des Mining-Pools von SBI Crypto</a>.</p>
  <p class="fr">Cette vague de ventes révèle l'envers de <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">ces deux courbes qui divergent — hashrate au plus haut historique et revenus des mineurs au plus bas historique</a>. Les limites des indicateurs traditionnels pour lire le stress des mineurs peuvent être suivies dans <a href="/blog/hash-ribbon-false-signals.html">les faux signaux du Hash Ribbon</a>, et le déclin à long terme du plafond de la rentabilité du minage dans <a href="/blog/puell-multiple-ceiling-decay.html">la dégradation structurelle de la borne supérieure du Puell Multiple</a>. Un cas représentatif de restructuration d'un mineur pris individuellement est <a href="/blog/sbi-crypto-mining-pool-shutdown.html">la fermeture du pool de minage de SBI Crypto</a>.</p>
  <p class="pt">Essa onda de vendas expõe o outro lado de <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">duas curvas que se separam — hashrate em recorde histórico e receita das mineradoras em mínima histórica</a>. Os limites dos indicadores tradicionais para ler o estresse das mineradoras podem ser acompanhados em <a href="/blog/hash-ribbon-false-signals.html">os sinais falsos do Hash Ribbon</a>, e o declínio de longo prazo no teto da rentabilidade da mineração em <a href="/blog/puell-multiple-ceiling-decay.html">a deterioração estrutural do limite superior do Puell Multiple</a>. Um caso representativo de reestruturação de uma mineradora individual é <a href="/blog/sbi-crypto-mining-pool-shutdown.html">o fechamento do pool de mineração da SBI Crypto</a>.</p>
  <p class="tr">Bu satış dalgası, <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">rekor yüksek hash oranı ile rekor düşük madenci gelirinin ayrıştığı bu iki eğrinin</a> öteki yüzünü ortaya koyuyor. Madenci stresini okumak için kullanılan geleneksel göstergelerin sınırları <a href="/blog/hash-ribbon-false-signals.html">Hash Ribbon'ın yanlış sinyallerinde</a>, madencilik kârlılığının tavanındaki uzun vadeli düşüş ise <a href="/blog/puell-multiple-ceiling-decay.html">Puell Multiple'ın üst sınırındaki yapısal çözülmede</a> izlenebilir. Bireysel bir madencinin yeniden yapılanmasına örnek teşkil eden vaka ise <a href="/blog/sbi-crypto-mining-pool-shutdown.html">SBI Crypto'nun madencilik havuzunu kapatması</a>dır.</p>
  <p class="vi">Làn sóng bán ra này phơi bày mặt trái của <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.html">hai đường cong đang tách rời nhau — hashrate cao kỷ lục và doanh thu công ty khai thác thấp kỷ lục</a>. Giới hạn của các chỉ báo truyền thống trong việc đọc áp lực lên công ty khai thác có thể được theo dõi tiếp trong <a href="/blog/hash-ribbon-false-signals.html">những tín hiệu giả của Hash Ribbon</a>, còn sự suy giảm dài hạn của trần khả năng sinh lời khai thác có thể xem trong <a href="/blog/puell-multiple-ceiling-decay.html">sự suy thoái cấu trúc của biên trên chỉ số Puell Multiple</a>. Một trường hợp tiêu biểu về tái cơ cấu của một công ty khai thác đơn lẻ là <a href="/blog/sbi-crypto-mining-pool-shutdown.html">việc SBI Crypto đóng cửa pool khai thác</a>.</p>

  <p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: TheMinerMag(분기별 상장 채굴사 BTC 매도 집계), Cointelegraph("Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025"), BeInCrypto("Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025"), KuCoin(채굴사 AI·HPC 자본 재배치 속보), CryptoQuant(채굴사 보유량 데이터).</p>
  <p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: TheMinerMag (quarterly tally of listed-miner BTC sales), Cointelegraph ("Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025"), BeInCrypto ("Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025"), KuCoin (bulletin on miners reallocating capital to AI/HPC), and CryptoQuant (miner-reserve data).</p>
  <p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典:TheMinerMag(四半期別の上場マイニング企業BTC売却集計)、Cointelegraph(「Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025」)、BeInCrypto(「Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025」)、KuCoin(マイニング企業のAI・HPCへの資本再配分速報)、CryptoQuant(採掘企業保有量データ)。</p>
  <p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: TheMinerMag (recuento trimestral de ventas de BTC de mineros cotizados), Cointelegraph ("Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025"), BeInCrypto ("Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025"), KuCoin (boletín sobre mineros reasignando capital a IA/HPC) y CryptoQuant (datos de reservas de mineros).</p>
  <p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: TheMinerMag (Quartalsauswertung der BTC-Verkäufe börsennotierter Miner), Cointelegraph ("Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025"), BeInCrypto ("Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025"), KuCoin (Meldung zur Kapitalumschichtung der Miner in KI/HPC) und CryptoQuant (Miner-Reserve-Daten).</p>
  <p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : TheMinerMag (décompte trimestriel des ventes de BTC des mineurs cotés), Cointelegraph (« Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025 »), BeInCrypto (« Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025 »), KuCoin (bulletin sur la réaffectation de capital des mineurs vers l'IA/le HPC) et CryptoQuant (données sur les réserves des mineurs).</p>
  <p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: TheMinerMag (levantamento trimestral das vendas de BTC de mineradoras listadas), Cointelegraph (“Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025”), BeInCrypto (“Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025”), KuCoin (boletim sobre a realocação de capital das mineradoras para IA/HPC) e CryptoQuant (dados de reservas das mineradoras).</p>
  <p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: TheMinerMag (halka açık madencilerin çeyreklik BTC satış derlemesi), Cointelegraph (“Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025”), BeInCrypto (“Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025”), KuCoin (madencilerin sermayeyi AI/HPC'ye yeniden tahsis etmesine ilişkin bülten) ve CryptoQuant (madenci rezerv verileri).</p>
  <p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: TheMinerMag (thống kê theo quý về lượng BTC bán ra của các công ty khai thác niêm yết), Cointelegraph (“Major Bitcoin mining companies sold more BTC in Q1 2026 than all of 2025”), BeInCrypto (“Public Miners Liquidate More Bitcoin in Q1 2026 Than All of 2025”), KuCoin (bản tin về việc các công ty khai thác tái phân bổ vốn sang AI/HPC), và CryptoQuant (dữ liệu dự trữ của công ty khai thác).</p>
<?php require __DIR__.'/_footer.php'; ?>
