<?php $slug = 'rain-protocol-796m-unlock-fdv-tvl-gap'; require __DIR__.'/_header.php'; ?>

  <p class="ko">예측시장 프로토콜 레인(Rain Protocol)의 토큰 RAIN이 7월 11일, 전체 발행량의 4.51%에 해당하는 518억 4,000만 개를 한꺼번에 시장에 풀었다. 토큰언락 추적업체들의 집계에 따르면 이는 달러 가치로 약 7억 9,600만 달러 규모이며, 7월 6~12일 한 주간 예정된 전체 토큰 언락(약 11억 달러)의 72%를 차지하는 이번 주 최대 사건이다. 코인게코(CoinGecko) 기준 RAIN의 시가총액은 약 95억 달러로 전체 코인 중 13위에 올라 있는데, 정작 디파이라마(DefiLlama) 계열 집계가 잡아낸 프로토콜의 실제 예치자산(TVL)은 약 396만 달러에 불과하다. 시가총액이 TVL의 약 2,400배에 달하는 셈이다.</p>
  <p class="en">Rain Protocol's token RAIN unlocked 51.84 billion tokens — 4.51% of its total supply — in a single cliff release on July 11. Token-unlock trackers put the dollar value at roughly $796 million, making it the largest single event of the week's $1.1 billion in scheduled unlocks (July 6-12), accounting for 72% of that total on its own. By CoinGecko's count, RAIN's market cap sits at roughly $9.5 billion, good for #13 among all tracked coins — yet the protocol's actual on-chain deposits, tracked by DefiLlama-style aggregators, total only about $3.96 million. That puts the market cap at roughly 2,400 times the protocol's measured usage.</p>
  <p class="ja">予測市場プロトコル、レイン(Rain Protocol)のトークンRAINが7月11日、総発行量の4.51%に相当する518億4,000万枚を一括で市場に放出した。トークンアンロック追跡業者の集計によれば、これはドル換算で約7億9,600万ドル規模であり、7月6~12日の一週間に予定されていた全体のトークンアンロック(約11億ドル)の72%を占める今週最大の出来事だ。コインゲッコー(CoinGecko)基準でRAINの時価総額は約95億ドルで全コイン中13位に位置するが、ディーファイラマ(DefiLlama)系の集計が捉えたプロトコルの実際の預託資産(TVL)はわずか約396万ドルにすぎない。時価総額がTVLの約2,400倍に達する計算だ。</p>
  <p class="es">El token RAIN del protocolo de mercados de predicción Rain Protocol desbloqueó 51.840 millones de tokens —el 4,51% de su suministro total— en una única liberación tipo "cliff" el 11 de julio. Según los rastreadores de desbloqueos de tokens, el valor en dólares ronda los 796 millones, lo que lo convierte en el mayor evento individual de los 1.100 millones de dólares en desbloqueos programados para la semana (6-12 de julio), representando por sí solo el 72% de ese total. Según CoinGecko, la capitalización de mercado de RAIN ronda los 9.500 millones de dólares, el puesto #13 entre todas las monedas rastreadas; sin embargo, los depósitos reales en cadena del protocolo, según agregadores tipo DefiLlama, suman apenas unos 3,96 millones de dólares. Eso sitúa la capitalización de mercado en unas 2.400 veces el uso medido del protocolo.</p>
  <p class="de">Der Token RAIN des Prediction-Market-Protokolls Rain Protocol gab am 11. Juli 51,84 Milliarden Token — 4,51 % seines Gesamtangebots — in einer einzigen Cliff-Freigabe frei. Token-Unlock-Tracker beziffern den Dollarwert auf rund 796 Millionen Dollar, womit dies das größte Einzelereignis der für die Woche (6.-12. Juli) geplanten Freigaben im Umfang von 1,1 Milliarden Dollar ist — allein 72 % dieser Gesamtsumme. Laut CoinGecko liegt RAINs Marktkapitalisierung bei rund 9,5 Milliarden Dollar, Platz 13 unter allen erfassten Coins — doch die tatsächlichen On-Chain-Einlagen des Protokolls, erfasst von DefiLlama-ähnlichen Aggregatoren, belaufen sich auf lediglich rund 3,96 Millionen Dollar. Das setzt die Marktkapitalisierung auf etwa das 2.400-Fache der gemessenen Protokollnutzung.</p>
  <p class="fr">Le token RAIN du protocole de marchés de prédiction Rain Protocol a débloqué 51,84 milliards de jetons — 4,51 % de son offre totale — en une seule libération « cliff » le 11 juillet. Selon les traqueurs de déblocages de tokens, la valeur en dollars avoisine 796 millions, ce qui en fait le plus gros événement isolé des 1,1 milliard de dollars de déblocages prévus cette semaine (6-12 juillet), représentant à lui seul 72 % de ce total. Selon CoinGecko, la capitalisation boursière de RAIN avoisine 9,5 milliards de dollars, soit la 13e place parmi toutes les cryptomonnaies suivies — pourtant, les dépôts on-chain réels du protocole, mesurés par des agrégateurs de type DefiLlama, ne totalisent qu'environ 3,96 millions de dollars. Cela place la capitalisation boursière à environ 2 400 fois l'usage mesuré du protocole.</p>
  <p class="pt">O token RAIN, do protocolo de mercados de previsão Rain Protocol, destravou 51,84 bilhões de tokens — 4,51% de seu fornecimento total — em uma única liberação tipo "cliff" em 11 de julho. Segundo rastreadores de destravamento de tokens, o valor em dólares gira em torno de US$ 796 milhões, tornando-o o maior evento isolado dentro do US$ 1,1 bilhão em destravamentos programados para a semana (6-12 de julho), respondendo sozinho por 72% desse total. Segundo a CoinGecko, a capitalização de mercado da RAIN está em torno de US$ 9,5 bilhões, o 13º lugar entre todas as moedas rastreadas — mas os depósitos reais on-chain do protocolo, medidos por agregadores do tipo DefiLlama, somam apenas cerca de US$ 3,96 milhões. Isso coloca a capitalização de mercado em cerca de 2.400 vezes o uso medido do protocolo.</p>
  <p class="tr">Tahmin piyasası protokolü Rain Protocol'ün RAIN tokenı, 11 Temmuz'da toplam arzının %4,51'ine denk gelen 51,84 milyar tokenı tek seferde piyasaya sürdü. Token kilit açma takipçilerine göre bu, dolar bazında yaklaşık 796 milyon dolar değerinde ve haftanın (6-12 Temmuz) 1,1 milyar dolarlık toplam planlı kilit açmalarının %72'sini tek başına oluşturarak haftanın en büyük tekil olayı oldu. CoinGecko'ya göre RAIN'in piyasa değeri yaklaşık 9,5 milyar dolar ile takip edilen tüm coinler arasında 13. sırada — ama protokolün DefiLlama tarzı toplayıcılar tarafından ölçülen gerçek zincir üstü mevduatları yalnızca yaklaşık 3,96 milyon dolar. Bu da piyasa değerini protokolün ölçülen kullanımının yaklaşık 2.400 katına yerleştiriyor.</p>
  <p class="vi">Token RAIN của giao thức thị trường dự đoán Rain Protocol đã mở khóa 51,84 tỷ token — tương đương 4,51% tổng nguồn cung — trong một đợt phát hành "cliff" duy nhất vào ngày 11 tháng 7. Theo các bên theo dõi việc mở khóa token, giá trị quy đổi ra đô la vào khoảng 796 triệu đô la, khiến đây trở thành sự kiện đơn lẻ lớn nhất trong tổng số 1,1 tỷ đô la token dự kiến mở khóa trong tuần (6-12 tháng 7), chiếm tới 72% tổng số đó. Theo CoinGecko, vốn hóa thị trường của RAIN vào khoảng 9,5 tỷ đô la, xếp hạng 13 trong số các đồng coin được theo dõi — nhưng lượng tài sản thực sự gửi vào giao thức trên chuỗi, được các bên tổng hợp kiểu DefiLlama ghi nhận, chỉ khoảng 3,96 triệu đô la. Điều đó khiến vốn hóa thị trường cao gấp khoảng 2.400 lần mức sử dụng thực tế được đo lường của giao thức.</p>

  <div>
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="ko">RAIN: 밸류에이션 vs 실사용 (로그 스케일, 2026년 7월)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="en">RAIN: Valuation vs. Actual Usage (log scale, July 2026)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="ja">RAIN:バリュエーション vs 実使用(対数スケール、2026年7月)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="es">RAIN: Valoración vs. Uso Real (escala log, julio 2026)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="de">RAIN: Bewertung vs. Tatsächliche Nutzung (Logskala, Juli 2026)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="fr">RAIN : Valorisation vs Usage Réel (échelle log, juillet 2026)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="pt">RAIN: Avaliação vs. Uso Real (escala log, julho de 2026)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="tr">RAIN: Değerleme ve Gerçek Kullanım (log ölçek, Temmuz 2026)</text>
    <text x="20" y="30" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif" class="vi">RAIN: Định Giá so với Mức Sử Dụng Thực (thang log, tháng 7/2026)</text>
    <line x1="220" y1="55" x2="220" y2="330" stroke="#3f3f46" stroke-width="1"/>
    <line x1="360" y1="55" x2="360" y2="330" stroke="#3f3f46" stroke-width="1"/>
    <line x1="500" y1="55" x2="500" y2="330" stroke="#3f3f46" stroke-width="1"/>
    <line x1="640" y1="55" x2="640" y2="330" stroke="#3f3f46" stroke-width="1"/>
    <text x="220" y="348" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">$1M</text>
    <text x="360" y="348" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">$100M</text>
    <text x="500" y="348" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">$10B</text>
    <text x="640" y="348" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">$20B</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ko">프로토콜 예치자산 (TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="en">Protocol deposits (TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ja">プロトコル預託資産(TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="es">Depósitos del protocolo (TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="de">Protokoll-Einlagen (TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="fr">Dépôts du protocole (TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="pt">Depósitos do protocolo (TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="tr">Protokol mevduatları (TVL)</text>
    <text x="20" y="85" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="vi">Tài sản gửi vào giao thức (TVL)</text>
    <rect x="220" y="92" width="12" height="26" rx="3" fill="#60a5fa"/>
    <text x="242" y="110" fill="#60a5fa" font-size="13" font-weight="700" font-family="sans-serif">$3.96M</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ko">7/11 하루치 락업 해제분</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="en">July 11 unlock, this event alone</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ja">7/11 一日分のアンロック</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="es">Desbloqueo del 11 de julio, solo este evento</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="de">Freigabe am 11. Juli, allein dieses Ereignis</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="fr">Déblocage du 11 juillet, cet événement seul</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="pt">Destravamento de 11 de julho, só este evento</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="tr">11 Temmuz kilit açma, yalnızca bu olay</text>
    <text x="20" y="155" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="vi">Mở khóa ngày 11/7, chỉ riêng sự kiện này</text>
    <rect x="220" y="162" width="243" height="26" rx="3" fill="#fbbf24"/>
    <text x="473" y="180" fill="#fbbf24" font-size="13" font-weight="700" font-family="sans-serif">$796M</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ko">시가총액 (유통량 기준)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="en">Market cap (circulating supply)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ja">時価総額(流通量基準)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="es">Cap. de mercado (oferta circulante)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="de">Marktkapitalisierung (Umlaufmenge)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="fr">Cap. boursière (offre en circulation)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="pt">Cap. de mercado (oferta circulante)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="tr">Piyasa değeri (dolaşımdaki arz)</text>
    <text x="20" y="225" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="vi">Vốn hóa (nguồn cung lưu hành)</text>
    <rect x="220" y="232" width="280" height="26" rx="3" fill="#f97316"/>
    <text x="510" y="250" fill="#f97316" font-size="13" font-weight="700" font-family="sans-serif">$9.5B</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ko">완전희석가치 (FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="en">Fully diluted valuation (FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="ja">完全希薄化評価額(FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="es">Valoración totalmente diluida (FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="de">Voll verwässerte Bewertung (FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="fr">Valorisation entièrement diluée (FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="pt">Avaliação totalmente diluída (FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="tr">Tam seyreltilmiş değerleme (FDV)</text>
    <text x="20" y="295" fill="#e4e4e7" font-size="13" font-family="sans-serif" class="vi">Định giá pha loãng hoàn toàn (FDV)</text>
    <rect x="220" y="302" width="308" height="26" rx="3" fill="#ef4444"/>
    <text x="538" y="320" fill="#ef4444" font-size="13" font-weight="700" font-family="sans-serif">$16.5B</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="ko">가로축은 로그 스케일 — 막대 길이 차이가 실제 배수 차이보다 훨씬 작게 보임. 시총/TVL 배율 약 2,400배.</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="en">Horizontal axis is logarithmic — bar-length gaps look far smaller than the real multiples. Market cap/TVL ratio: ~2,400x.</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="ja">横軸は対数スケール — 棒の長さの差は実際の倍率差よりはるかに小さく見える。時総/TVL倍率は約2,400倍。</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="es">Eje horizontal logarítmico — las diferencias de longitud parecen mucho menores que los múltiplos reales. Ratio cap./TVL: ~2.400x.</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="de">Horizontale Achse ist logarithmisch — Balkenlängen wirken viel kleiner als die realen Multiplikatoren. Verhältnis Marktkap./TVL: ~2.400x.</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="fr">Axe horizontal logarithmique — les écarts de longueur paraissent bien plus petits que les multiples réels. Ratio cap./TVL : ~2 400x.</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="pt">Eixo horizontal logarítmico — as diferenças de comprimento parecem bem menores que os múltiplos reais. Razão cap./TVL: ~2.400x.</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="tr">Yatay eksen logaritmik — çubuk uzunluğu farkları gerçek katlardan çok daha küçük görünür. Piyasa değeri/TVL oranı: ~2.400x.</text>
    <text x="20" y="378" fill="#71717a" font-size="12" font-family="sans-serif" class="vi">Trục ngang theo thang log — chênh lệch độ dài cột trông nhỏ hơn nhiều so với bội số thực tế. Tỷ lệ vốn hóa/TVL: ~2.400 lần.</text>
    <text x="680" y="345" fill="#52525b" font-size="11" text-anchor="end" font-family="sans-serif">Source: CoinGecko, DefiLlama, Tokenomist.ai</text>
  </svg>
  </div>

  <h2 class="ko">레인 프로토콜이 무엇이고, 왜 오늘 7억 9,600만 달러가 풀렸나</h2>
  <h2 class="en">What Rain Protocol is, and why $796 million unlocked today</h2>
  <h2 class="ja">レインプロトコルとは何か、なぜ今日7億9,600万ドルが放出されたのか</h2>
  <h2 class="es">Qué es Rain Protocol y por qué se desbloquearon 796 millones de dólares hoy</h2>
  <h2 class="de">Was Rain Protocol ist und warum heute 796 Millionen Dollar freigegeben wurden</h2>
  <h2 class="fr">Qu'est-ce que Rain Protocol, et pourquoi 796 millions de dollars ont été débloqués aujourd'hui</h2>
  <h2 class="pt">O que é o Rain Protocol e por que US$ 796 milhões foram destravados hoje</h2>
  <h2 class="tr">Rain Protocol nedir ve bugün neden 796 milyon dolar kilidi açıldı</h2>
  <h2 class="vi">Rain Protocol là gì và vì sao 796 triệu đô la được mở khóa hôm nay</h2>
  <p class="ko">레인 프로토콜은 아비트럼(Arbitrum) 위에 구축된 탈중앙화 예측시장 인프라로, 개발자가 자체 예측시장 플랫폼을 만들 수 있도록 SDK와 API를 제공하는 '빌더 우선' 구조를 표방한다. 스스로를 "예측시장의 유니스왑"이라 부르며, 이더리움·베이스(Base)·BNB체인 등 다른 네트워크에서 자금을 예치할 수 있는 크로스체인 지원과, 올림푸스 AI(Olympus AI)가 시장 판정을 자동화하는 AI 기반 정산 프레임워크를 특징으로 내세운다. 토큰 이코노믹스의 핵심은 거래대금의 2.5%를 자동으로 RAIN 매입·소각에 배정하는 디플레이션 구조로, 누적 소각량은 6,900만 개를 넘어섰다.</p>
  <p class="en">Rain Protocol is decentralized prediction-market infrastructure built on Arbitrum, pitched as "builder-first" — it offers SDKs and APIs so developers can spin up their own forecasting platforms rather than building from scratch. It calls itself "the Uniswap of prediction markets," touts cross-chain deposits from Ethereum, Base, and BNB Chain, and features an AI-driven settlement framework, Olympus AI, that automates market resolution. The core of its tokenomics is a deflationary mechanism that routes 2.5% of trading volume into an automatic RAIN buyback-and-burn, which has removed more than 69 million tokens from supply cumulatively.</p>
  <p class="ja">レインプロトコルはアービトラム(Arbitrum)上に構築された分散型予測市場インフラで、開発者が独自の予測市場プラットフォームをゼロから作らずに済むようSDKとAPIを提供する「ビルダーファースト」構造を掲げる。自らを「予測市場のユニスワップ」と称し、イーサリアム・ベース(Base)・BNBチェーンなど他ネットワークからの資金預託を可能にするクロスチェーン対応と、オリンパスAI(Olympus AI)が市場判定を自動化するAI主導の決済フレームワークを特徴として打ち出す。トークノミクスの中核は、取引代金の2.5%を自動的にRAINの買い戻し・焼却に充てるデフレ構造で、累計焼却量は6,900万枚を超えた。</p>
  <p class="es">Rain Protocol es una infraestructura descentralizada de mercados de predicción construida sobre Arbitrum, presentada como "builder-first": ofrece SDKs y API para que los desarrolladores levanten sus propias plataformas de pronóstico sin construir desde cero. Se autodenomina "el Uniswap de los mercados de predicción", presume de depósitos cross-chain desde Ethereum, Base y BNB Chain, y cuenta con un marco de liquidación impulsado por IA, Olympus AI, que automatiza la resolución de mercados. El núcleo de su tokenómica es un mecanismo deflacionario que destina el 2,5% del volumen de trading a una recompra y quema automática de RAIN, que ha retirado acumuladamente más de 69 millones de tokens de la oferta.</p>
  <p class="de">Rain Protocol ist eine dezentrale Prediction-Market-Infrastruktur auf Arbitrum, die als „Builder-first" positioniert wird — sie bietet SDKs und APIs, damit Entwickler eigene Prognoseplattformen aufbauen können, statt bei null anzufangen. Das Protokoll bezeichnet sich als „das Uniswap der Prediction-Markets", wirbt mit Cross-Chain-Einzahlungen aus Ethereum, Base und BNB Chain und verfügt über ein KI-gestütztes Abwicklungsframework namens Olympus AI, das die Marktauflösung automatisiert. Kern der Tokenomics ist ein deflationärer Mechanismus, der 2,5 % des Handelsvolumens in einen automatischen RAIN-Rückkauf und -Burn leitet — dabei wurden kumuliert bereits über 69 Millionen Token aus dem Umlauf entfernt.</p>
  <p class="fr">Rain Protocol est une infrastructure décentralisée de marchés de prédiction construite sur Arbitrum, présentée comme « builder-first » : elle fournit des SDK et des API permettant aux développeurs de lancer leurs propres plateformes de prévision sans repartir de zéro. Le protocole se qualifie lui-même d'« Uniswap des marchés de prédiction », met en avant des dépôts cross-chain depuis Ethereum, Base et BNB Chain, et dispose d'un cadre de règlement piloté par IA, Olympus AI, qui automatise la résolution des marchés. Le cœur de sa tokenomics est un mécanisme déflationniste qui affecte 2,5 % du volume d'échange à un rachat-destruction automatique de RAIN, retirant ainsi cumulativement plus de 69 millions de jetons de la circulation.</p>
  <p class="pt">O Rain Protocol é uma infraestrutura descentralizada de mercados de previsão construída sobre a Arbitrum, apresentada como "builder-first" — oferece SDKs e APIs para que desenvolvedores criem suas próprias plataformas de previsão sem começar do zero. O protocolo se autodenomina "a Uniswap dos mercados de previsão", exibe depósitos cross-chain vindos de Ethereum, Base e BNB Chain, e conta com uma estrutura de liquidação orientada por IA, a Olympus AI, que automatiza a resolução dos mercados. O núcleo de sua tokenomics é um mecanismo deflacionário que destina 2,5% do volume de negociação a uma recompra e queima automática de RAIN, que já removeu cumulativamente mais de 69 milhões de tokens da oferta.</p>
  <p class="tr">Rain Protocol, Arbitrum üzerine kurulu, merkeziyetsiz bir tahmin piyasası altyapısıdır ve "önce geliştirici" yaklaşımıyla tanıtılır — geliştiricilerin sıfırdan başlamak yerine kendi tahmin platformlarını kurabilmesi için SDK'lar ve API'ler sunar. Kendisini "tahmin piyasalarının Uniswap'ı" olarak adlandırır, Ethereum, Base ve BNB Chain'den zincirler arası mevduatlarla övünür ve piyasa çözümünü otomatikleştiren yapay zeka destekli bir uzlaşma çerçevesi olan Olympus AI'a sahiptir. Tokenomisinin özü, işlem hacminin %2,5'ini otomatik bir RAIN geri alım ve yakım mekanizmasına yönlendiren deflasyonist bir yapıdır; bu mekanizma bugüne kadar arzdan kümülatif olarak 69 milyondan fazla tokenı çıkarmıştır.</p>
  <p class="vi">Rain Protocol là hạ tầng thị trường dự đoán phi tập trung xây dựng trên Arbitrum, được định vị theo hướng "ưu tiên nhà phát triển" — cung cấp SDK và API để nhà phát triển xây dựng nền tảng dự đoán riêng mà không phải làm lại từ đầu. Giao thức tự gọi mình là "Uniswap của thị trường dự đoán", quảng bá khả năng gửi tiền liên chuỗi từ Ethereum, Base và BNB Chain, và có khung giải quyết dựa trên AI mang tên Olympus AI để tự động hóa việc phân xử thị trường. Cốt lõi của tokenomics là cơ chế giảm phát dành 2,5% khối lượng giao dịch để tự động mua lại và đốt RAIN, đã loại bỏ tích lũy hơn 69 triệu token khỏi nguồn cung.</p>

  <p class="ko">토큰 언락은 이런 성장서사와 별개로 애초에 정해진 베스팅 일정에 따라 기계적으로 진행된다. 레인의 전체 발행량은 약 1조 1,498억 개이며, 이번 언락 이전까지 유통량은 약 6,600억 개(전체의 약 57%)였다. 7월 11일 한 번에 풀린 518억 4,000만 개는 팀·투자자·생태계 배정분 중 일부가 클리프(cliff, 벼랑형 일괄 해제) 방식으로 잠금 해제되는 사건으로, 매일 조금씩 풀리는 선형 베스팅과 달리 특정일에 대량 물량이 한꺼번에 유통 가능 상태로 전환된다는 점에서 시장의 매도 압력을 한 시점에 집중시키는 구조다. 이번 주(7월 6~12일) 전체 언락 규모는 약 11억 달러로 집계됐는데, RAIN 하나가 그 72%를 차지해 사실상 이번 주 알트코인 언락 캘린더를 지배했다.</p>
  <p class="en">Unlocks proceed on a fixed vesting schedule set independently of any growth narrative. Rain's total supply is about 1.1498 trillion tokens, and circulating supply stood at roughly 660 billion (about 57% of the total) before this event. The 51.84 billion tokens released at once on July 11 come from team, investor, and ecosystem allocations vesting under a cliff structure — rather than trickling out daily under linear vesting, a large block becomes tradable on a single date, concentrating potential sell pressure at one point in time. This week's (July 6-12) total unlock volume came to roughly $1.1 billion, and RAIN alone accounted for 72% of it, effectively dominating the altcoin unlock calendar for the week.</p>
  <p class="ja">トークンアンロックは、こうした成長ストーリーとは無関係に、あらかじめ定められたベスティングスケジュールに従って機械的に進む。レインの総発行量は約1兆1,498億枚で、今回のアンロック前の流通量は約6,600億枚(全体の約57%)だった。7月11日に一度に放出された518億4,000万枚は、チーム・投資家・エコシステム配分の一部が「クリフ」方式で一括解除される事象で、毎日少しずつ放出される線形ベスティングと異なり、特定の日に大量の数量が一度に流通可能な状態へ転換される点で、市場の売り圧力を一時点に集中させる構造だ。今週(7月6~12日)の全体アンロック規模は約11億ドルと集計され、RAIN一銘柄がその72%を占め、事実上今週のアルトコインアンロックカレンダーを支配した。</p>
  <p class="es">Los desbloqueos avanzan según un calendario de vesting fijo, establecido con independencia de cualquier narrativa de crecimiento. El suministro total de Rain es de unos 1,1498 billones de tokens, y la oferta circulante rondaba los 660.000 millones (cerca del 57% del total) antes de este evento. Los 51.840 millones de tokens liberados de golpe el 11 de julio proceden de asignaciones de equipo, inversores y ecosistema que vencen bajo una estructura tipo "cliff" —en lugar de salir goteando a diario bajo un vesting lineal, un bloque grande se vuelve negociable en una sola fecha, concentrando la potencial presión vendedora en un único momento. El volumen total de desbloqueos de esta semana (6-12 de julio) alcanzó unos 1.100 millones de dólares, y solo RAIN representó el 72%, dominando de hecho el calendario de desbloqueos de altcoins de la semana.</p>
  <p class="de">Die Freigaben folgen einem festen Vesting-Zeitplan, der unabhängig von jeder Wachstumsstory festgelegt wurde. Rains Gesamtangebot beträgt rund 1,1498 Billionen Token, und die Umlaufmenge lag vor diesem Ereignis bei etwa 660 Milliarden (rund 57 % des Gesamtangebots). Die am 11. Juli auf einen Schlag freigegebenen 51,84 Milliarden Token stammen aus Team-, Investoren- und Ökosystem-Zuteilungen, die nach einer Cliff-Struktur vesten — statt täglich in kleinen Portionen wie beim linearen Vesting freizuwerden, wird an einem einzigen Datum ein großer Block handelbar, was potenziellen Verkaufsdruck auf einen Zeitpunkt konzentriert. Das gesamte Freigabevolumen dieser Woche (6.-12. Juli) belief sich auf rund 1,1 Milliarden Dollar, wovon RAIN allein 72 % ausmachte — faktisch dominierte es den Altcoin-Unlock-Kalender der Woche.</p>
  <p class="fr">Les déblocages suivent un calendrier de vesting fixe, établi indépendamment de tout récit de croissance. L'offre totale de Rain est d'environ 1 149,8 milliards de jetons, et l'offre en circulation s'élevait à environ 660 milliards (environ 57 % du total) avant cet événement. Les 51,84 milliards de jetons libérés d'un coup le 11 juillet proviennent d'allocations équipe, investisseurs et écosystème vestant selon une structure « cliff » — plutôt que de sortir au compte-gouttes quotidiennement sous un vesting linéaire, un gros bloc devient négociable à une date unique, concentrant la pression vendeuse potentielle en un seul instant. Le volume total de déblocages de cette semaine (6-12 juillet) s'est élevé à environ 1,1 milliard de dollars, et RAIN à lui seul en représentait 72 %, dominant de fait le calendrier de déblocage des altcoins de la semaine.</p>
  <p class="pt">Os destravamentos avançam segundo um cronograma de vesting fixo, definido independentemente de qualquer narrativa de crescimento. O fornecimento total da Rain é de cerca de 1,1498 trilhão de tokens, e a oferta circulante estava em torno de 660 bilhões (cerca de 57% do total) antes deste evento. Os 51,84 bilhões de tokens liberados de uma vez em 11 de julho vêm de alocações de equipe, investidores e ecossistema que vestem sob uma estrutura "cliff" — em vez de saírem aos poucos diariamente sob vesting linear, um grande bloco se torna negociável em uma única data, concentrando a potencial pressão vendedora em um único momento. O volume total de destravamentos desta semana (6-12 de julho) somou cerca de US$ 1,1 bilhão, e somente a RAIN respondeu por 72% disso, dominando de fato o calendário de destravamento de altcoins da semana.</p>
  <p class="tr">Kilit açmalar, herhangi bir büyüme anlatısından bağımsız olarak belirlenmiş sabit bir vesting takvimine göre ilerler. Rain'in toplam arzı yaklaşık 1,1498 trilyon token'dır ve bu olaydan önce dolaşımdaki arz yaklaşık 660 milyar (toplamın yaklaşık %57'si) düzeyindeydi. 11 Temmuz'da tek seferde serbest bırakılan 51,84 milyar token, "cliff" yapısı altında vesting olan takım, yatırımcı ve ekosistem tahsislerinden geliyor — doğrusal vesting'de olduğu gibi günlük damla damla çıkmak yerine, büyük bir blok tek bir tarihte işlem görebilir hale geliyor ve potansiyel satış baskısını tek bir noktada yoğunlaştırıyor. Bu haftanın (6-12 Temmuz) toplam kilit açma hacmi yaklaşık 1,1 milyar dolara ulaştı ve RAIN tek başına bunun %72'sini oluşturarak haftanın altcoin kilit açma takvimine fiilen hükmetti.</p>
  <p class="vi">Việc mở khóa diễn ra theo lịch trình vesting cố định, được thiết lập độc lập với bất kỳ câu chuyện tăng trưởng nào. Tổng nguồn cung của Rain vào khoảng 1,1498 nghìn tỷ token, và nguồn cung lưu hành trước sự kiện này ở mức khoảng 660 tỷ (khoảng 57% tổng số). 51,84 tỷ token được giải phóng cùng lúc vào ngày 11 tháng 7 đến từ các phần phân bổ cho đội ngũ, nhà đầu tư và hệ sinh thái theo cấu trúc "cliff" — thay vì rò rỉ ra từng chút một hằng ngày theo kiểu vesting tuyến tính, một khối lượng lớn trở nên có thể giao dịch vào đúng một ngày, dồn áp lực bán tiềm tàng vào một thời điểm duy nhất. Tổng khối lượng mở khóa trong tuần này (6-12 tháng 7) đạt khoảng 1,1 tỷ đô la, và riêng RAIN đã chiếm 72% trong đó, gần như chi phối toàn bộ lịch mở khóa altcoin của tuần.</p>

  <h2 class="ko">엔리벡스의 2억 1,200만 달러 트레저리 베팅과 밸류에이션 간극</h2>
  <h2 class="en">Enlivex's $212 million treasury bet, and the valuation gap it inflated</h2>
  <h2 class="ja">エンリベックスの2億1,200万ドル・トレジャリー賭けと、それが膨らませたバリュエーションの乖離</h2>
  <h2 class="es">La apuesta de tesorería de 212 millones de dólares de Enlivex y la brecha de valoración que infló</h2>
  <h2 class="de">Enlivex' 212-Millionen-Dollar-Treasury-Wette und die dadurch aufgeblähte Bewertungslücke</h2>
  <h2 class="fr">Le pari de trésorerie de 212 millions de dollars d'Enlivex, et l'écart de valorisation qu'il a gonflé</h2>
  <h2 class="pt">A aposta de tesouraria de US$ 212 milhões da Enlivex e a lacuna de avaliação que ela inflou</h2>
  <h2 class="tr">Enlivex'in 212 milyon dolarlık hazine bahsi ve şişirdiği değerleme farkı</h2>
  <h2 class="vi">Canh bạc kho bạc 212 triệu đô la của Enlivex và khoảng cách định giá mà nó thổi phồng</h2>
  <p class="ko">RAIN의 시가총액이 실사용 규모와 이렇게 벌어진 배경에는 나스닥 상장 바이오텍 기업 엔리벡스(Enlivex Therapeutics)가 있다. 이 회사는 최근 2억 1,200만 달러 규모의 사모 유상증자를 발표하며 "RAIN 토큰을 중심으로 한 세계 최초의 트레저리 전략"을 표방했는데, 이는 스트래티지(옛 마이크로스트래티지)가 비트코인으로, 이후 여러 기업이 이더리움·솔라나로 벌여온 '기업 재무제표에 특정 코인을 대량 편입해 주가를 그 코인의 대리 투자수단으로 만드는' 전략을 소형 알트코인에 그대로 이식한 사례다. 이 발표 하나로 RAIN 가격은 약 100% 뛰었다. 바이오텍 회사가 항암 치료제 파이프라인과 무관한 예측시장 토큰을 재무제표의 핵심 자산으로 삼겠다고 선언하자 시장이 즉각 반응한 셈이다.</p>
  <p class="en">Behind that gap between RAIN's market cap and its actual usage sits Enlivex Therapeutics, a Nasdaq-listed biotech firm. The company recently announced a $212 million private placement to fund what it called "the world's first treasury strategy centered on the RAIN token" — transplanting onto a small-cap altcoin the same playbook Strategy (formerly MicroStrategy) built around bitcoin and that several firms have since copied with ether and solana: load a corporate balance sheet with a single coin and let the stock trade as a proxy for that coin. The announcement alone drove RAIN's price up roughly 100%. A biotech firm with an oncology pipeline declared a prediction-market token its core balance-sheet asset, and the market reacted instantly.</p>
  <p class="ja">RAINの時価総額と実際の使用規模がこれほど乖離した背景には、ナスダック上場のバイオテック企業エンリベックス(Enlivex Therapeutics)がある。同社は最近、2億1,200万ドル規模の私募増資を発表し、「RAINトークンを中心とした世界初のトレジャリー戦略」を掲げた。これはストラテジー(旧マイクロストラテジー)がビットコインで、その後複数の企業がイーサリアム・ソラナで展開してきた「企業の貸借対照表に特定コインを大量に組み込み、株価をそのコインの代理投資手段にする」戦略を、そのまま小型アルトコインに移植した事例だ。この発表一つでRAIN価格は約100%上昇した。抗がん治療薬パイプラインとは無関係の予測市場トークンを、バイオテック企業が貸借対照表の中核資産に据えると宣言したことに、市場が即座に反応した形だ。</p>
  <p class="es">Detrás de esa brecha entre la capitalización de mercado de RAIN y su uso real está Enlivex Therapeutics, una biotecnológica que cotiza en Nasdaq. La empresa anunció recientemente una colocación privada de 212 millones de dólares para financiar lo que llamó "la primera estrategia de tesorería del mundo centrada en el token RAIN" —trasplantando a una altcoin de pequeña capitalización el mismo manual que Strategy (antes MicroStrategy) construyó en torno al bitcoin y que varias empresas han copiado desde entonces con ether y solana: cargar el balance corporativo con una sola moneda y dejar que la acción cotice como sustituto de esa moneda. Solo el anuncio disparó el precio de RAIN cerca de un 100%. Una biotecnológica con una cartera oncológica declaró que un token de mercados de predicción era su activo central de balance, y el mercado reaccionó al instante.</p>
  <p class="de">Hinter dieser Lücke zwischen RAINs Marktkapitalisierung und seiner tatsächlichen Nutzung steht Enlivex Therapeutics, ein an der Nasdaq notiertes Biotech-Unternehmen. Das Unternehmen kündigte kürzlich eine Privatplatzierung über 212 Millionen Dollar an, um das zu finanzieren, was es „die weltweit erste, auf den RAIN-Token ausgerichtete Treasury-Strategie" nannte — und verpflanzte damit auf einen Small-Cap-Altcoin genau das Playbook, das Strategy (früher MicroStrategy) um Bitcoin herum aufgebaut hat und das seitdem mehrere Firmen mit Ether und Solana kopiert haben: die Unternehmensbilanz mit einem einzigen Coin aufladen und die Aktie als Stellvertreter für diesen Coin handeln lassen. Allein die Ankündigung trieb RAINs Kurs um rund 100 % nach oben. Ein Biotech-Unternehmen mit einer Onkologie-Pipeline erklärte einen Prediction-Market-Token zu seinem zentralen Bilanzaktivposten, und der Markt reagierte sofort.</p>
  <p class="fr">Derrière cet écart entre la capitalisation boursière de RAIN et son usage réel se trouve Enlivex Therapeutics, une société biotechnologique cotée au Nasdaq. L'entreprise a récemment annoncé un placement privé de 212 millions de dollars pour financer ce qu'elle a appelé « la première stratégie de trésorerie au monde centrée sur le token RAIN » — transplantant sur une altcoin à petite capitalisation le même schéma que Strategy (anciennement MicroStrategy) a bâti autour du bitcoin et que plusieurs entreprises ont depuis copié avec l'ether et le solana : charger le bilan d'une entreprise d'une seule cryptomonnaie et laisser l'action se négocier comme un proxy de cette monnaie. La seule annonce a fait grimper le prix de RAIN d'environ 100 %. Une société biotech dotée d'un pipeline en oncologie a déclaré qu'un token de marchés de prédiction était son actif de bilan central, et le marché a réagi instantanément.</p>
  <p class="pt">Por trás dessa lacuna entre a capitalização de mercado da RAIN e seu uso real está a Enlivex Therapeutics, uma empresa de biotecnologia listada na Nasdaq. A empresa anunciou recentemente uma colocação privada de US$ 212 milhões para financiar o que chamou de "a primeira estratégia de tesouraria do mundo centrada no token RAIN" — transplantando para uma altcoin de pequena capitalização o mesmo manual que a Strategy (antiga MicroStrategy) construiu em torno do bitcoin e que várias empresas já copiaram com ether e solana: carregar o balanço corporativo com uma única moeda e deixar a ação ser negociada como um proxy dessa moeda. Só o anúncio fez o preço da RAIN disparar cerca de 100%. Uma empresa de biotecnologia com um pipeline oncológico declarou que um token de mercados de previsão era seu ativo central de balanço, e o mercado reagiu instantaneamente.</p>
  <p class="tr">RAIN'in piyasa değeri ile gerçek kullanımı arasındaki bu farkın arkasında, Nasdaq'ta işlem gören bir biyoteknoloji şirketi olan Enlivex Therapeutics var. Şirket kısa süre önce, "RAIN tokenına odaklanan dünyanın ilk hazine stratejisi" olarak adlandırdığı şeyi finanse etmek için 212 milyon dolarlık özel bir sermaye artırımı duyurdu — bu, Strategy'nin (eski adıyla MicroStrategy) bitcoin etrafında kurduğu ve o zamandan beri birkaç şirketin ether ve solana ile kopyaladığı aynı oyun kitabını küçük ölçekli bir altcoine nakletmek anlamına geliyor: şirket bilançosunu tek bir coin ile doldurmak ve hissenin o coin için bir vekil gibi işlem görmesine izin vermek. Yalnızca bu duyuru RAIN fiyatını yaklaşık %100 yükseltti. Onkoloji ürün hattına sahip bir biyoteknoloji şirketi, bir tahmin piyasası tokenını bilançosunun temel varlığı ilan etti ve piyasa anında tepki verdi.</p>
  <p class="vi">Đằng sau khoảng cách giữa vốn hóa thị trường của RAIN và mức sử dụng thực tế là Enlivex Therapeutics, một công ty công nghệ sinh học niêm yết trên Nasdaq. Công ty này gần đây công bố đợt phát hành riêng lẻ trị giá 212 triệu đô la để tài trợ cho cái mà họ gọi là "chiến lược kho bạc đầu tiên trên thế giới xoay quanh token RAIN" — cấy ghép vào một altcoin vốn hóa nhỏ chính công thức mà Strategy (trước đây là MicroStrategy) đã xây dựng xung quanh bitcoin và sau đó nhiều công ty khác đã sao chép với ether và solana: nạp đầy bảng cân đối kế toán doanh nghiệp bằng một đồng coin duy nhất và để cổ phiếu giao dịch như một đại diện cho đồng coin đó. Chỉ riêng thông báo này đã đẩy giá RAIN tăng khoảng 100%. Một công ty công nghệ sinh học với danh mục sản phẩm ung thư tuyên bố một token thị trường dự đoán là tài sản cốt lõi trên bảng cân đối kế toán, và thị trường phản ứng ngay lập tức.</p>

  <p class="ko">이 패턴은 낯설지 않다. 이미 본지가 다뤄온 '기업 트레저리' 계열 기사들이 지적해온 것처럼, 코인을 재무제표에 편입하는 발표 자체가 단기 주가·토큰가 급등을 만들어내는 촉매로 작동하는 사례가 반복돼 왔다. 다만 비트코인·이더리움처럼 유동성이 깊고 오랜 시장 이력을 가진 자산과, 발행량 대부분이 아직 잠겨 있고 TVL이 400만 달러에도 못 미치는 신생 알트코인은 근본적으로 다른 리스크 프로필을 가진다. 프로토콜의 실질 사용량 대비 시가총액 배율이 수천 배에 달한다는 것은, 지금의 가격이 예측시장이라는 성장 서사에 대한 베팅이지 현재의 온체인 활동에 대한 평가가 아니라는 뜻이다. 7월 12일에는 펌프(PUMP)의 8억 2,500만 개(약 1억 3,500만 달러) 언락도 예정돼 있어, 이번 주는 클리프형 대량 언락이 잇달아 겹치는 한 주로 기록될 공산이 크다.</p>
  <p class="en">This pattern is familiar. As this outlet's own coverage of the "corporate treasury" trend has noted, the announcement of adding a coin to a balance sheet has repeatedly acted as its own short-term catalyst for both the stock and the token. But an asset like bitcoin or ether — deep liquidity, a long trading history — carries a fundamentally different risk profile from a young altcoin where most of the supply is still locked and TVL sits under $4 million. A market-cap-to-usage multiple in the thousands means today's price is a bet on the prediction-markets growth story, not a valuation of current on-chain activity. July 12 brings another cliff unlock — 82.5 billion PUMP tokens, worth roughly $135 million — meaning this week is shaping up as one where back-to-back cliff unlocks collide.</p>
  <p class="ja">このパターンは目新しいものではない。本紙がこれまで報じてきた「企業トレジャリー」系記事が指摘してきた通り、コインを貸借対照表に組み込む発表そのものが、短期的な株価・トークン価格急騰の触媒として繰り返し機能してきた。ただし、ビットコインやイーサリアムのように流動性が厚く長い市場実績を持つ資産と、発行量の大半がまだロックされておりTVLが400万ドルにも満たない新興アルトコインとでは、根本的にリスクプロファイルが異なる。プロトコルの実質使用量に対する時価総額の倍率が数千倍に達するということは、現在の価格が予測市場という成長ストーリーへの賭けであり、現時点のオンチェーン活動に対する評価ではないことを意味する。7月12日にはパンプ(PUMP)の825億枚(約1億3,500万ドル)のアンロックも予定されており、今週はクリフ型の大量アンロックが立て続けに重なる週として記録される公算が大きい。</p>
  <p class="es">Este patrón resulta familiar. Como ha señalado la propia cobertura de este medio sobre la tendencia de "tesorería corporativa", el mero anuncio de añadir una moneda al balance ha actuado repetidamente como catalizador a corto plazo tanto para la acción como para el token. Pero un activo como bitcoin o ether —liquidez profunda, un largo historial de negociación— tiene un perfil de riesgo fundamentalmente distinto al de una altcoin joven donde la mayor parte del suministro sigue bloqueado y el TVL está por debajo de los 4 millones de dólares. Un múltiplo de capitalización sobre uso de miles de veces significa que el precio actual es una apuesta por la narrativa de crecimiento de los mercados de predicción, no una valoración de la actividad on-chain actual. El 12 de julio llega otro desbloqueo tipo cliff —82.500 millones de tokens de PUMP, por unos 135 millones de dólares—, lo que sugiere que esta semana quedará marcada por desbloqueos cliff que colisionan uno tras otro.</p>
  <p class="de">Dieses Muster ist vertraut. Wie die eigene Berichterstattung dieses Blogs über den Trend der „Unternehmens-Treasury" bereits festgestellt hat, wirkt die bloße Ankündigung, einen Coin in eine Bilanz aufzunehmen, wiederholt als eigener kurzfristiger Katalysator für Aktie und Token gleichermaßen. Doch ein Asset wie Bitcoin oder Ether — mit tiefer Liquidität und langer Handelshistorie — trägt ein grundlegend anderes Risikoprofil als ein junger Altcoin, bei dem der Großteil des Angebots noch gesperrt ist und die TVL unter 4 Millionen Dollar liegt. Ein Verhältnis von Marktkapitalisierung zu Nutzung im vierstelligen Bereich bedeutet, dass der heutige Preis eine Wette auf die Wachstumsstory der Prediction-Markets ist, keine Bewertung der aktuellen On-Chain-Aktivität. Am 12. Juli folgt bereits die nächste Cliff-Freigabe — 82,5 Milliarden PUMP-Token im Wert von rund 135 Millionen Dollar —, sodass sich diese Woche als eine abzeichnet, in der Cliff-Freigaben unmittelbar aufeinanderprallen.</p>
  <p class="fr">Ce schéma est familier. Comme l'a souligné la couverture de ce média sur la tendance de la « trésorerie d'entreprise », la simple annonce d'ajouter une cryptomonnaie à un bilan a régulièrement agi comme son propre catalyseur à court terme, tant pour l'action que pour le token. Mais un actif comme le bitcoin ou l'ether — liquidité profonde, longue historique de cotation — présente un profil de risque fondamentalement différent d'une jeune altcoin dont la majeure partie de l'offre reste verrouillée et dont la TVL est inférieure à 4 millions de dollars. Un multiple capitalisation/usage de plusieurs milliers signifie que le prix actuel est un pari sur le récit de croissance des marchés de prédiction, non une valorisation de l'activité on-chain actuelle. Le 12 juillet apporte un autre déblocage cliff — 82,5 milliards de jetons PUMP, d'une valeur d'environ 135 millions de dollars —, ce qui indique que cette semaine s'annonce comme celle où les déblocages cliff s'enchaînent coup sur coup.</p>
  <p class="pt">Esse padrão é familiar. Como a própria cobertura deste site sobre a tendência de "tesouraria corporativa" já apontou, o simples anúncio de adicionar uma moeda a um balanço tem repetidamente atuado como catalisador de curto prazo tanto para a ação quanto para o token. Mas um ativo como bitcoin ou ether — liquidez profunda, longo histórico de negociação — carrega um perfil de risco fundamentalmente diferente de uma altcoin jovem em que a maior parte da oferta ainda está bloqueada e o TVL está abaixo de US$ 4 milhões. Um múltiplo de capitalização de mercado sobre uso na casa dos milhares significa que o preço de hoje é uma aposta na narrativa de crescimento dos mercados de previsão, não uma avaliação da atividade on-chain atual. Em 12 de julho vem outro destravamento tipo cliff — 82,5 bilhões de tokens PUMP, no valor de cerca de US$ 135 milhões —, o que sugere que esta semana está se tornando uma em que destravamentos cliff colidem um após o outro.</p>
  <p class="tr">Bu örüntü tanıdık. Bu yayının "kurumsal hazine" eğilimi üzerine yaptığı haberlerin de belirttiği gibi, bir coini bilançoya eklemek duyurusunun kendisi, hem hisse hem de token için tekrar tekrar kısa vadeli bir katalizör olarak işlev görmüştür. Ama bitcoin veya ether gibi derin likiditeye ve uzun bir işlem geçmişine sahip bir varlık, arzının çoğu hâlâ kilitli ve TVL'si 4 milyon doların altında olan genç bir altcoinden temelde farklı bir risk profiline sahiptir. Binlerle ifade edilen bir piyasa değeri/kullanım çarpanı, bugünkü fiyatın tahmin piyasalarının büyüme hikâyesine yapılan bir bahis olduğu, mevcut zincir üstü faaliyetin bir değerlemesi olmadığı anlamına gelir. 12 Temmuz'da bir başka cliff kilit açma daha geliyor — yaklaşık 135 milyon dolar değerinde 82,5 milyar PUMP tokenı — bu da bu haftanın art arda çarpışan cliff kilit açmalarıyla anılacağına işaret ediyor.</p>
  <p class="vi">Kiểu mẫu này không hề xa lạ. Như chính các bài viết của trang này về xu hướng "kho bạc doanh nghiệp" đã chỉ ra, riêng việc công bố thêm một đồng coin vào bảng cân đối kế toán đã nhiều lần đóng vai trò như một chất xúc tác ngắn hạn cho cả cổ phiếu lẫn token. Nhưng một tài sản như bitcoin hay ether — thanh khoản sâu, lịch sử giao dịch lâu đời — mang hồ sơ rủi ro khác về cơ bản so với một altcoin non trẻ mà phần lớn nguồn cung vẫn đang bị khóa và TVL dưới 4 triệu đô la. Một bội số vốn hóa trên mức sử dụng lên tới hàng nghìn lần có nghĩa là mức giá hôm nay là một canh bạc vào câu chuyện tăng trưởng của thị trường dự đoán, chứ không phải là định giá cho hoạt động on-chain hiện tại. Ngày 12 tháng 7 sẽ có thêm một đợt mở khóa cliff khác — 82,5 tỷ token PUMP, trị giá khoảng 135 triệu đô la — cho thấy tuần này đang trở thành tuần mà các đợt mở khóa cliff liên tiếp va chạm nhau.</p>

  <h2 class="ko">반박: 소각 메커니즘과 예측시장 성장세가 정당화할 수 있는가</h2>
  <h2 class="en">The counterargument: could the burn mechanism and the sector's growth justify it?</h2>
  <h2 class="ja">反論:焼却メカニズムと予測市場の成長がそれを正当化しうるか</h2>
  <h2 class="es">El contraargumento: ¿podrían el mecanismo de quema y el crecimiento del sector justificarlo?</h2>
  <h2 class="de">Das Gegenargument: Könnten der Burn-Mechanismus und das Sektorwachstum das rechtfertigen?</h2>
  <h2 class="fr">Le contre-argument : le mécanisme de destruction et la croissance du secteur peuvent-ils le justifier ?</h2>
  <h2 class="pt">O contra-argumento: o mecanismo de queima e o crescimento do setor poderiam justificar isso?</h2>
  <h2 class="tr">Karşı argüman: yakım mekanizması ve sektörün büyümesi bunu haklı çıkarabilir mi?</h2>
  <h2 class="vi">Lập luận phản biện: liệu cơ chế đốt token và tăng trưởng của ngành có thể biện minh cho điều này?</h2>
  <p class="ko">공정하게 보면, 레인의 소각 구조를 옹호할 여지도 있다. 거래대금의 2.5%가 자동으로 매입·소각되는 구조는 프로토콜 사용량이 늘어날수록 유통량 증가 속도를 상쇄하는 방향으로 작동한다. 게다가 예측시장 산업 자체가 실제로 급팽창하는 국면에 있다는 근거도 있다. 업계 리서치에 따르면 주요 예측시장 플랫폼들은 지난 분기에만 30억 달러의 거래대금을 기록해 전년 동기 대비 5배 넘게 늘었고, 누적 거래대금은 280억 달러를 넘어섰다. 시장조사기관들은 향후 10년 안에 이 시장이 955억 달러 규모로 성장할 것으로 내다본다. 칼시(Kalshi)와 폴리마켓(Polymarket)이 최근 월드컵 기간 거래량 기록을 새로 썼다는 점도 이 서사에 힘을 싣는다. 레인이 이 성장의 '인프라 레이어'로 자리잡는다면, 지금의 밸류에이션이 미래 수요를 선반영한 것이라는 주장도 완전히 터무니없지는 않다.</p>
  <p class="en">In fairness, there's a case for Rain's burn structure. Automatically buying and burning RAIN with 2.5% of trading volume works to offset supply growth as protocol usage rises — the more the platform is used, the faster tokens leave circulation. There's also evidence the prediction-market sector itself is genuinely expanding fast: industry research shows major platforms cleared $3 billion in trading volume last quarter alone, more than five times the year-ago figure, with cumulative volume topping $28 billion; forecasters project the sector could reach $95.5 billion within a decade. Kalshi and Polymarket recently set fresh volume records during the World Cup, which lends the narrative some weight. If Rain establishes itself as infrastructure for that growth, the argument that today's valuation is pricing in future demand isn't entirely far-fetched.</p>
  <p class="ja">公平に見れば、レインの焼却構造を擁護する余地もある。取引代金の2.5%が自動的に買い戻され焼却される仕組みは、プロトコルの利用が増えるほど流通量増加ペースを相殺する方向に働く。さらに、予測市場業界そのものが実際に急拡大局面にあるという根拠もある。業界リサーチによれば、主要予測市場プラットフォームは前四半期だけで30億ドルの取引代金を記録し前年同期比5倍超に増え、累積取引代金は280億ドルを超えた。市場調査機関は今後10年以内にこの市場が955億ドル規模に成長すると予測している。カルシ(Kalshi)とポリマーケット(Polymarket)が最近ワールドカップ期間中に取引量記録を更新したことも、この物語に説得力を与える。レインがこの成長の「インフラ層」として定着するなら、現在のバリュエーションが将来需要を先取りしているという主張も、まったく的外れとは言えない。</p>
  <p class="es">Para ser justos, hay argumentos a favor de la estructura de quema de Rain. Comprar y quemar RAIN automáticamente con el 2,5% del volumen de trading funciona para compensar el crecimiento de la oferta a medida que aumenta el uso del protocolo: cuanto más se usa la plataforma, más rápido salen los tokens de circulación. También hay indicios de que el propio sector de mercados de predicción está expandiéndose genuinamente rápido: la investigación del sector muestra que las principales plataformas registraron 3.000 millones de dólares en volumen de trading solo el trimestre pasado, más de cinco veces la cifra del año anterior, con un volumen acumulado que supera los 28.000 millones; los pronosticadores proyectan que el sector podría alcanzar los 95.500 millones de dólares en una década. Kalshi y Polymarket batieron recientemente récords de volumen durante el Mundial, lo que respalda algo esa narrativa. Si Rain se consolida como infraestructura de ese crecimiento, el argumento de que la valoración actual descuenta demanda futura no resulta del todo descabellado.</p>
  <p class="de">Fairerweise lässt sich auch etwas für Rains Burn-Struktur anführen. Der automatische Rückkauf und das Verbrennen von RAIN mit 2,5 % des Handelsvolumens wirkt dem Angebotswachstum entgegen, je stärker das Protokoll genutzt wird — je mehr die Plattform verwendet wird, desto schneller verlassen Token den Umlauf. Es gibt zudem Hinweise, dass der Prediction-Market-Sektor selbst tatsächlich schnell expandiert: Branchenresearch zeigt, dass große Plattformen allein im vergangenen Quartal 3 Milliarden Dollar Handelsvolumen erzielten, mehr als das Fünffache des Vorjahreswerts, bei einem kumulierten Volumen von über 28 Milliarden Dollar; Prognostiker erwarten, dass der Sektor innerhalb eines Jahrzehnts 95,5 Milliarden Dollar erreichen könnte. Kalshi und Polymarket stellten kürzlich während der Fußball-Weltmeisterschaft neue Volumenrekorde auf, was dieser Erzählung etwas Gewicht verleiht. Sollte sich Rain als Infrastruktur für dieses Wachstum etablieren, ist das Argument, die heutige Bewertung preise künftige Nachfrage ein, nicht völlig abwegig.</p>
  <p class="fr">En toute équité, il existe des arguments en faveur de la structure de destruction de Rain. Le rachat et la destruction automatiques de RAIN avec 2,5 % du volume d'échange contribuent à compenser la croissance de l'offre à mesure que l'usage du protocole augmente — plus la plateforme est utilisée, plus vite les jetons sortent de la circulation. Il existe aussi des indices que le secteur des marchés de prédiction lui-même connaît une expansion réellement rapide : les études sectorielles montrent que les principales plateformes ont réalisé 3 milliards de dollars de volume d'échange rien que le trimestre dernier, soit plus de cinq fois le chiffre de l'an dernier, avec un volume cumulé dépassant 28 milliards de dollars ; les prévisionnistes projettent que le secteur pourrait atteindre 95,5 milliards de dollars d'ici une décennie. Kalshi et Polymarket ont récemment établi de nouveaux records de volume pendant la Coupe du Monde, ce qui donne un certain poids à ce récit. Si Rain s'impose comme l'infrastructure de cette croissance, l'argument selon lequel la valorisation actuelle intègre déjà la demande future n'est pas totalement infondé.</p>
  <p class="pt">Para ser justo, há argumentos a favor da estrutura de queima da Rain. Recomprar e queimar automaticamente RAIN com 2,5% do volume de negociação funciona para compensar o crescimento da oferta à medida que o uso do protocolo aumenta — quanto mais a plataforma é usada, mais rápido os tokens saem de circulação. Também há indícios de que o próprio setor de mercados de previsão está de fato se expandindo rapidamente: pesquisas do setor mostram que as principais plataformas registraram US$ 3 bilhões em volume de negociação somente no trimestre passado, mais de cinco vezes o número do ano anterior, com volume acumulado ultrapassando US$ 28 bilhões; projeções apontam que o setor pode chegar a US$ 95,5 bilhões em uma década. Kalshi e Polymarket bateram recorde de volume recentemente durante a Copa do Mundo, o que dá algum peso a essa narrativa. Se a Rain se estabelecer como infraestrutura desse crescimento, o argumento de que a avaliação atual já precifica a demanda futura não é totalmente descabido.</p>
  <p class="tr">Adil olmak gerekirse, Rain'in yakım yapısını savunacak bir yön de var. İşlem hacminin %2,5'iyle RAIN'i otomatik olarak geri almak ve yakmak, protokol kullanımı arttıkça arz büyümesini dengelemeye çalışır — platform ne kadar çok kullanılırsa token'lar dolaşımdan o kadar hızlı çıkar. Ayrıca tahmin piyasası sektörünün kendisinin gerçekten hızla büyüdüğüne dair kanıtlar da var: sektör araştırmaları, büyük platformların yalnızca geçen çeyrekte 3 milyar dolar işlem hacmi kaydettiğini, bunun geçen yılın aynı dönemine göre beş kattan fazla olduğunu ve kümülatif hacmin 28 milyar doları aştığını gösteriyor; tahminciler sektörün on yıl içinde 95,5 milyar dolara ulaşabileceğini öngörüyor. Kalshi ve Polymarket, Dünya Kupası sırasında yakın zamanda yeni hacim rekorları kırdı; bu da bu anlatıya bir miktar ağırlık katıyor. Rain bu büyümenin altyapısı olarak kendini kanıtlarsa, bugünkü değerlemenin gelecekteki talebi fiyatladığı argümanı tamamen temelsiz sayılmaz.</p>
  <p class="vi">Công bằng mà nói, vẫn có lý lẽ ủng hộ cơ chế đốt token của Rain. Việc tự động mua lại và đốt RAIN bằng 2,5% khối lượng giao dịch giúp bù đắp cho tăng trưởng nguồn cung khi mức sử dụng giao thức tăng lên — nền tảng càng được sử dụng nhiều, token càng rời khỏi lưu thông nhanh hơn. Cũng có bằng chứng cho thấy chính ngành thị trường dự đoán đang thực sự mở rộng nhanh chóng: nghiên cứu ngành cho thấy các nền tảng lớn đã đạt 3 tỷ đô la khối lượng giao dịch chỉ riêng trong quý trước, hơn gấp năm lần con số cùng kỳ năm ngoái, với khối lượng lũy kế vượt 28 tỷ đô la; các nhà dự báo cho rằng ngành này có thể đạt 95,5 tỷ đô la trong một thập kỷ. Kalshi và Polymarket gần đây đã lập kỷ lục khối lượng mới trong kỳ World Cup, điều này phần nào củng cố câu chuyện đó. Nếu Rain khẳng định được vị thế là hạ tầng cho sự tăng trưởng đó, thì lập luận rằng định giá hiện tại đã phản ánh trước nhu cầu tương lai không hẳn là hoàn toàn vô căn cứ.</p>

  <p class="ko">그러나 이 반론에는 한계가 뚜렷하다. 첫째, 소각 규모(누적 6,900만 개)는 이번 하루 언락분(518억 4,000만 개)의 0.13%에 불과해, 지금까지의 소각 속도로는 언락 물량을 상쇄하기까지 수십 년이 걸린다. 둘째, "예측시장 산업 전체가 성장한다"는 사실이 "레인이라는 특정 인프라 프로토콜이 그 성장의 승자가 된다"는 결론을 자동으로 보장하지 않는다 — 칼시·폴리마켓처럼 이미 유동성과 브랜드를 확보한 소비자 대면 플랫폼과, 그 아래 깔리는 인프라 레이어 사업자는 가치 포착 구조가 전혀 다르다. 셋째, 펌프(PUMP)의 첫 클리프 언락 사례처럼, 락업 해제 직후 단기간 매도 압력이 집중되는 패턴은 과거에도 반복적으로 관찰됐다. 결국 지켜봐야 할 것은 하루짜리 가격 반응이 아니라, 언락 이후 몇 주간 TVL과 실거래량이 실제로 시가총액을 따라잡는 방향으로 움직이는지, 아니면 밸류에이션 간극이 그대로 유지되는지다.</p>
  <p class="en">Still, the counterargument has clear limits. First, cumulative burns (69 million tokens) equal just 0.13% of today's single unlock (51.84 billion tokens) — at that burn rate, it would take decades to offset the unlocked supply. Second, "the prediction-market sector is growing" doesn't automatically mean "Rain, specifically, captures that growth" — a consumer-facing platform with established liquidity and brand recognition, like Kalshi or Polymarket, captures value very differently than an infrastructure layer sitting beneath it. Third, the pattern of concentrated sell pressure right after a cliff unlock — as seen with PUMP's first cliff release — has repeated often enough to be a known risk, not a one-off. What's worth watching isn't today's price reaction but whether, over the weeks after this unlock, TVL and real trading activity actually catch up to the market cap, or whether the valuation gap simply persists.</p>
  <p class="ja">ただし、この反論には明確な限界がある。第一に、累積焼却量(6,900万枚)は今日一日分のアンロック(518億4,000万枚)のわずか0.13%にすぎず、この焼却速度ではアンロック分を相殺するのに数十年かかる。第二に、「予測市場業界全体が成長している」という事実は、「レインという特定のインフラプロトコルがその成長の勝者になる」という結論を自動的に保証しない――カルシ・ポリマーケットのように既に流動性とブランドを確保した消費者向けプラットフォームと、その下に敷かれるインフラ層事業者とでは、価値捕捉の構造がまったく異なる。第三に、パンプ(PUMP)の初回クリフアンロックの事例のように、ロック解除直後に短期的な売り圧力が集中するパターンは過去にも繰り返し観察されてきた。結局注視すべきは一日限りの価格反応ではなく、アンロック後の数週間でTVLと実取引量が実際に時価総額に追いつく方向へ動くのか、それともバリュエーションの乖離がそのまま維持されるのかだ。</p>
  <p class="es">Aun así, el contraargumento tiene límites claros. Primero, las quemas acumuladas (69 millones de tokens) equivalen a apenas el 0,13% del desbloqueo de un solo día de hoy (51.840 millones de tokens); a ese ritmo de quema, tardaría décadas en compensar el suministro desbloqueado. Segundo, que "el sector de mercados de predicción esté creciendo" no garantiza automáticamente que "Rain, en concreto, capture ese crecimiento" — una plataforma orientada al consumidor con liquidez y reconocimiento de marca ya establecidos, como Kalshi o Polymarket, captura valor de forma muy distinta a una capa de infraestructura subyacente. Tercero, el patrón de presión vendedora concentrada justo tras un desbloqueo tipo cliff —como se vio con la primera liberación cliff de PUMP— se ha repetido lo suficiente como para ser un riesgo conocido, no un hecho aislado. Lo que vale la pena vigilar no es la reacción del precio de hoy, sino si, en las semanas posteriores a este desbloqueo, el TVL y la actividad de trading real realmente alcanzan a la capitalización de mercado, o si la brecha de valoración simplemente persiste.</p>
  <p class="de">Dennoch hat das Gegenargument klare Grenzen. Erstens entsprechen die kumulierten Burns (69 Millionen Token) nur 0,13 % der heutigen Einzel-Freigabe (51,84 Milliarden Token) — bei dieser Burn-Rate würde es Jahrzehnte dauern, das freigegebene Angebot auszugleichen. Zweitens garantiert die Tatsache, dass „der Prediction-Market-Sektor wächst", nicht automatisch, dass „ausgerechnet Rain dieses Wachstum abschöpft" — eine verbraucherorientierte Plattform mit etablierter Liquidität und Markenbekanntheit wie Kalshi oder Polymarket erfasst Wert auf ganz andere Weise als eine darunterliegende Infrastrukturschicht. Drittens ist das Muster konzentrierten Verkaufsdrucks direkt nach einer Cliff-Freigabe — wie bei PUMPs erster Cliff-Freigabe zu sehen — schon oft genug aufgetreten, um ein bekanntes Risiko zu sein, kein Einzelfall. Beobachtenswert ist nicht die heutige Kursreaktion, sondern ob TVL und reale Handelsaktivität in den Wochen nach dieser Freigabe tatsächlich zur Marktkapitalisierung aufschließen — oder ob die Bewertungslücke einfach bestehen bleibt.</p>
  <p class="fr">Pourtant, le contre-argument a des limites claires. Premièrement, les destructions cumulées (69 millions de jetons) ne représentent que 0,13 % du seul déblocage d'aujourd'hui (51,84 milliards de jetons) — à ce rythme de destruction, il faudrait des décennies pour compenser l'offre débloquée. Deuxièmement, le fait que « le secteur des marchés de prédiction croît » ne garantit pas automatiquement que « Rain, en particulier, capte cette croissance » — une plateforme grand public dotée d'une liquidité et d'une notoriété déjà établies, comme Kalshi ou Polymarket, capte la valeur d'une manière très différente d'une couche d'infrastructure sous-jacente. Troisièmement, le schéma de pression vendeuse concentrée juste après un déblocage cliff — comme observé lors de la première libération cliff de PUMP — s'est répété assez souvent pour constituer un risque connu, pas un cas isolé. Ce qui mérite d'être surveillé n'est pas la réaction du prix aujourd'hui, mais si, dans les semaines suivant ce déblocage, la TVL et l'activité de trading réelle rattrapent effectivement la capitalisation boursière, ou si l'écart de valorisation persiste simplement.</p>
  <p class="pt">Ainda assim, o contra-argumento tem limites claros. Primeiro, as queimas acumuladas (69 milhões de tokens) equivalem a apenas 0,13% do destravamento de um único dia de hoje (51,84 bilhões de tokens) — nesse ritmo de queima, levaria décadas para compensar a oferta destravada. Segundo, o fato de "o setor de mercados de previsão estar crescendo" não garante automaticamente que "a Rain, especificamente, capture esse crescimento" — uma plataforma voltada ao consumidor com liquidez e reconhecimento de marca já estabelecidos, como Kalshi ou Polymarket, captura valor de forma muito diferente de uma camada de infraestrutura subjacente. Terceiro, o padrão de pressão vendedora concentrada logo após um destravamento tipo cliff — como visto na primeira liberação cliff da PUMP — já se repetiu vezes suficientes para ser um risco conhecido, não um caso isolado. O que vale a pena observar não é a reação do preço hoje, mas se, nas semanas após esse destravamento, o TVL e a atividade real de negociação realmente alcançam a capitalização de mercado, ou se a lacuna de avaliação simplesmente persiste.</p>
  <p class="tr">Yine de karşı argümanın açık sınırları var. Birincisi, kümülatif yakımlar (69 milyon token), bugünkü tek seferlik kilit açmanın (51,84 milyar token) yalnızca %0,13'üne eşit — bu yakım hızıyla, kilidi açılan arzı dengelemek on yıllar alır. İkincisi, "tahmin piyasası sektörü büyüyor" gerçeği, otomatik olarak "özellikle Rain bu büyümeyi yakalıyor" sonucunu garanti etmez — Kalshi veya Polymarket gibi zaten yerleşik likiditeye ve marka bilinirliğine sahip tüketiciye yönelik bir platform, altındaki bir altyapı katmanından çok farklı biçimde değer yakalar. Üçüncüsü, bir cliff kilit açmanın hemen ardından yoğunlaşan satış baskısı örüntüsü — PUMP'ın ilk cliff serbest bırakmasında görüldüğü gibi — bilinen bir risk sayılacak kadar sık tekrarlanmıştır, tek seferlik bir durum değildir. İzlenmesi gereken şey bugünkü fiyat tepkisi değil, bu kilit açmadan sonraki haftalarda TVL ve gerçek işlem faaliyetinin piyasa değerine gerçekten yetişip yetişmediği, yoksa değerleme farkının aynen sürüp sürmediğidir.</p>
  <p class="vi">Tuy vậy, lập luận phản biện này có những giới hạn rõ ràng. Thứ nhất, lượng đốt lũy kế (69 triệu token) chỉ bằng 0,13% lượng mở khóa của riêng ngày hôm nay (51,84 tỷ token) — với tốc độ đốt này, sẽ mất hàng chục năm để bù đắp lượng cung được mở khóa. Thứ hai, việc "ngành thị trường dự đoán đang tăng trưởng" không tự động đảm bảo rằng "riêng Rain sẽ nắm bắt được sự tăng trưởng đó" — một nền tảng hướng tới người dùng cuối với thanh khoản và độ nhận diện thương hiệu đã được thiết lập, như Kalshi hay Polymarket, nắm bắt giá trị theo cách rất khác so với một lớp hạ tầng nằm bên dưới. Thứ ba, kiểu áp lực bán tập trung ngay sau một đợt mở khóa cliff — như đã thấy với lần mở khóa cliff đầu tiên của PUMP — đã lặp lại đủ nhiều để trở thành một rủi ro đã biết, chứ không phải là trường hợp đơn lẻ. Điều đáng theo dõi không phải là phản ứng giá của hôm nay, mà là liệu trong những tuần sau đợt mở khóa này, TVL và hoạt động giao dịch thực tế có thực sự bắt kịp vốn hóa thị trường hay không, hay khoảng cách định giá đơn giản là vẫn tồn tại.</p>

  <div class="box ko">💡 <strong>시사점:</strong> RAIN의 시가총액(약 95억 달러)은 프로토콜의 실제 예치자산(약 396만 달러)의 약 2,400배에 달하며, 오늘 하루에만 발행량의 4.51%(약 7억 9,600만 달러)가 시장에 풀렸다. 이 간극은 상당 부분 나스닥 바이오텍 기업 엔리벡스의 2억 1,200만 달러 트레저리 베팅이 만들어낸 것으로, 코인 자체의 성장이 아니라 '기업이 재무제표에 특정 코인을 편입한다'는 발표가 가격을 밀어올린 익숙한 패턴이다. 소각 메커니즘과 예측시장 산업의 실질 성장세는 정당화 논리를 제공하지만, 현재의 소각 속도로는 이번 언락 물량조차 상쇄하지 못한다. 지켜볼 지표는 언락 이후 TVL과 실거래량이 시가총액을 따라잡는지 여부다.</div>
  <div class="box en">💡 <strong>Takeaway:</strong> RAIN's market cap (~$9.5B) runs roughly 2,400 times the protocol's actual on-chain deposits (~$3.96M), and 4.51% of supply (~$796M) unlocked in a single day. Much of that gap traces back to Enlivex's $212 million treasury bet — a familiar pattern where the announcement of adding a coin to a corporate balance sheet moves the price more than the coin's own usage does. The burn mechanism and the sector's real growth offer some justification, but at the current burn rate, it wouldn't even offset today's single unlock. What to watch: whether TVL and real trading activity catch up to the market cap in the weeks after this release.</div>
  <div class="box ja">💡 <strong>示唆:</strong> RAINの時価総額(約95億ドル)は、プロトコルの実際のオンチェーン預託資産(約396万ドル)の約2,400倍に達し、今日一日だけで発行量の4.51%(約7億9,600万ドル)が市場に放出された。この乖離の大部分は、ナスダック上場バイオテック企業エンリベックスの2億1,200万ドルのトレジャリー賭けが生み出したもので、コイン自体の成長ではなく「企業が貸借対照表に特定コインを組み込む」という発表が価格を押し上げるという、おなじみのパターンだ。焼却メカニズムと予測市場業界の実質的な成長は一定の正当化材料を提供するが、現在の焼却速度では今回のアンロック分すら相殺できない。注視すべき指標は、アンロック後にTVLと実取引量が時価総額に追いつくかどうかだ。</div>
  <div class="box es">💡 <strong>Conclusión:</strong> la capitalización de mercado de RAIN (~9.500 millones de dólares) es unas 2.400 veces los depósitos on-chain reales del protocolo (~3,96 millones de dólares), y el 4,51% del suministro (~796 millones de dólares) se desbloqueó en un solo día. Buena parte de esa brecha se remonta a la apuesta de tesorería de 212 millones de dólares de Enlivex —un patrón familiar en el que el anuncio de añadir una moneda a un balance corporativo mueve el precio más que el propio uso de la moneda—. El mecanismo de quema y el crecimiento real del sector ofrecen cierta justificación, pero al ritmo de quema actual ni siquiera compensaría el desbloqueo de hoy. Qué vigilar: si el TVL y la actividad de trading real alcanzan a la capitalización de mercado en las semanas posteriores a esta liberación.</div>
  <div class="box de">💡 <strong>Fazit:</strong> RAINs Marktkapitalisierung (~9,5 Mrd. Dollar) liegt beim rund 2.400-Fachen der tatsächlichen On-Chain-Einlagen des Protokolls (~3,96 Mio. Dollar), und 4,51 % des Angebots (~796 Mio. Dollar) wurden an einem einzigen Tag freigegeben. Ein Großteil dieser Lücke geht auf Enlivex' 212-Millionen-Dollar-Treasury-Wette zurück — ein vertrautes Muster, bei dem die Ankündigung, einen Coin in eine Unternehmensbilanz aufzunehmen, den Kurs stärker bewegt als die tatsächliche Nutzung des Coins. Der Burn-Mechanismus und das reale Wachstum des Sektors liefern eine gewisse Rechtfertigung, doch bei der aktuellen Burn-Rate würde nicht einmal die heutige Einzel-Freigabe ausgeglichen. Zu beobachten: ob TVL und reale Handelsaktivität in den Wochen nach dieser Freigabe zur Marktkapitalisierung aufschließen.</div>
  <div class="box fr">💡 <strong>À retenir :</strong> la capitalisation boursière de RAIN (~9,5 Md$) est environ 2 400 fois supérieure aux dépôts on-chain réels du protocole (~3,96 M$), et 4,51 % de l'offre (~796 M$) a été débloquée en une seule journée. Une grande partie de cet écart remonte au pari de trésorerie de 212 millions de dollars d'Enlivex — un schéma familier où l'annonce d'ajouter une cryptomonnaie à un bilan d'entreprise fait bouger le prix plus que l'usage réel de la monnaie. Le mécanisme de destruction et la croissance réelle du secteur offrent une certaine justification, mais au rythme de destruction actuel, cela ne compenserait même pas le déblocage d'aujourd'hui. À surveiller : si la TVL et l'activité de trading réelle rattrapent la capitalisation boursière dans les semaines suivant ce déblocage.</div>
  <div class="box pt">💡 <strong>Conclusão:</strong> a capitalização de mercado da RAIN (~US$ 9,5 bi) é cerca de 2.400 vezes os depósitos reais on-chain do protocolo (~US$ 3,96 mi), e 4,51% da oferta (~US$ 796 mi) foi destravada em um único dia. Boa parte dessa lacuna remonta à aposta de tesouraria de US$ 212 milhões da Enlivex — um padrão familiar em que o anúncio de adicionar uma moeda a um balanço corporativo move o preço mais do que o próprio uso da moeda. O mecanismo de queima e o crescimento real do setor oferecem alguma justificativa, mas no ritmo de queima atual, isso nem compensaria o destravamento de hoje. O que observar: se o TVL e a atividade real de negociação alcançam a capitalização de mercado nas semanas após essa liberação.</div>
  <div class="box tr">💡 <strong>Sonuç:</strong> RAIN'in piyasa değeri (~9,5 milyar dolar), protokolün gerçek zincir üstü mevduatlarının (~3,96 milyon dolar) yaklaşık 2.400 katı ve arzın %4,51'i (~796 milyon dolar) tek bir günde kilidi açıldı. Bu farkın büyük kısmı Enlivex'in 212 milyon dolarlık hazine bahsine dayanıyor — bir coini kurumsal bilançoya ekleme duyurusunun, coinin kendi kullanımından daha fazla fiyatı hareket ettirdiği tanıdık bir örüntü. Yakım mekanizması ve sektörün gerçek büyümesi bir miktar gerekçe sunuyor, ancak mevcut yakım hızında bugünkü tek seferlik kilit açma bile dengelenemez. İzlenmesi gereken: bu serbest bırakmadan sonraki haftalarda TVL ve gerçek işlem faaliyetinin piyasa değerine yetişip yetişmeyeceği.</div>
  <div class="box vi">💡 <strong>Rút ra:</strong> vốn hóa thị trường của RAIN (~9,5 tỷ đô la) cao gấp khoảng 2.400 lần tài sản thực gửi vào giao thức trên chuỗi (~3,96 triệu đô la), và 4,51% nguồn cung (~796 triệu đô la) đã được mở khóa chỉ trong một ngày. Phần lớn khoảng cách đó bắt nguồn từ canh bạc kho bạc 212 triệu đô la của Enlivex — một kiểu mẫu quen thuộc trong đó việc công bố thêm một đồng coin vào bảng cân đối kế toán doanh nghiệp tác động đến giá nhiều hơn chính mức sử dụng của đồng coin đó. Cơ chế đốt token và tăng trưởng thực của ngành mang lại một phần biện minh, nhưng với tốc độ đốt hiện tại, thậm chí không thể bù đắp cho đợt mở khóa hôm nay. Điều cần theo dõi: liệu TVL và hoạt động giao dịch thực tế có bắt kịp vốn hóa thị trường trong những tuần sau đợt phát hành này hay không.</div>

  <p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. 가격·시가총액·TVL 수치는 보도 시점 기준이며 이후 변동될 수 있다. 이 글은 투자 조언이 아니다.</p>
  <p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. Price, market-cap, and TVL figures are as of the time of reporting and may change later. This article is not investment advice.</p>
  <p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典:BeInCrypto、KuCoin News、MEXC News、Cryptobriefing、DL News、Tokenomist.ai、CoinGecko、CoinMarketCap、ChainBroker。価格・時価総額・TVLの数値は報道時点のものであり、今後変更される可能性がある。本記事は投資助言ではない。</p>
  <p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. Las cifras de precio, capitalización de mercado y TVL corresponden al momento de la publicación y pueden cambiar más adelante. Este artículo no es asesoría de inversión.</p>
  <p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. Angaben zu Preis, Marktkapitalisierung und TVL entsprechen dem Berichtszeitpunkt und können sich später ändern. Dieser Artikel ist keine Anlageberatung.</p>
  <p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. Les chiffres de prix, capitalisation boursière et TVL correspondent au moment de la publication et peuvent évoluer ultérieurement. Cet article ne constitue pas un conseil en investissement.</p>
  <p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. Os números de preço, capitalização de mercado e TVL são referentes ao momento da divulgação e podem mudar posteriormente. Este artigo não é aconselhamento de investimento.</p>
  <p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. Fiyat, piyasa değeri ve TVL rakamları haberin yapıldığı tarih itibarıyladır ve daha sonra değişebilir. Bu yazı yatırım tavsiyesi değildir.</p>
  <p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: BeInCrypto, KuCoin News, MEXC News, Cryptobriefing, DL News, Tokenomist.ai, CoinGecko, CoinMarketCap, ChainBroker. Các số liệu về giá, vốn hóa thị trường và TVL tính đến thời điểm đưa tin và có thể thay đổi sau đó. Bài viết này không phải là lời khuyên đầu tư.</p>

<?php require __DIR__.'/_footer.php'; ?>
