<?php $slug = 'robinhood-hood-sunrise-solana-tokenized-launch'; require __DIR__.'/_header.php'; ?>

<p class="ko">로빈후드마켓츠(Robinhood Markets)의 보통주 HOOD가 7월16일 솔라나 블록체인 위에서 토큰화된 형태로 거래를 시작했다. 발행은 백팩증권(Backpack Securities)이 맡았고, 유통은 웜홀랩스(Wormhole Labs)가 만든 솔라나의 외부자산 게이트웨이 '선라이즈(Sunrise)'를 통해 이뤄졌다. 코인게이버·트레이딩뷰뉴스·크립토브리핑 등의 7월16일 보도에 따르면, 토큰화된 주식 HOODx는 나스닥의 실제 HOOD 주식과 1대1로 상환 가능하며 주피터·레이디움·미티오라·오르카 등 솔라나의 주요 거래소에서 24시간 거래된다. 로빈후드 자신이 유럽에서 추진해온 자체 체인 '로빈후드체인'과는 무관하게, 경쟁 플랫폼인 솔라나 위에서 그 주식이 먼저 토큰화됐다는 점이 눈길을 끈다.</p>
<p class="en">Robinhood Markets' common stock, HOOD, began trading in tokenized form on the Solana blockchain on July 16. Issuance was handled by Backpack Securities, and distribution ran through Sunrise, the gateway Wormhole Labs built to bring outside assets onto Solana. Per July 16 reporting from CoinGabbar, TradingView News and CryptoBriefing, the tokenized stock, HOODx, is redeemable 1:1 for the actual Nasdaq-listed HOOD share and trades 24 hours a day across Solana venues including Jupiter, Raydium, Meteora and Orca. What stands out is that Robinhood's own stock was tokenized first on a rival platform — Solana — with no apparent involvement from Robinhood Chain, the company's own EU-focused tokenization effort.</p>
<p class="ja">ロビンフッド・マーケッツ(Robinhood Markets)の普通株HOODが、7月16日にソラナ・ブロックチェーン上でトークン化された形で取引を開始した。発行を担ったのはバックパック証券(Backpack Securities)で、流通はウォームホール・ラボ(Wormhole Labs)が構築したソラナの外部資産ゲートウェイ「サンライズ(Sunrise)」を通じて行われた。コインギャバー、トレーディングビュー・ニュース、クリプトブリーフィングなどの7月16日の報道によると、トークン化株式HOODxはナスダック上の実際のHOOD株と1対1で償還可能で、ジュピター・レイディウム・メテオラ・オルカなどソラナの主要取引所で24時間取引される。ロビンフッド自身が欧州向けに推進してきた自社チェーン「ロビンフッドチェーン」とは無関係に、競合プラットフォームであるソラナ上でその株式が先にトークン化された点が注目を集めている。</p>
<p class="es">La acción común de Robinhood Markets, HOOD, comenzó a operar en forma tokenizada en la blockchain de Solana el 16 de julio. La emisión estuvo a cargo de Backpack Securities, y la distribución se realizó a través de Sunrise, la puerta de enlace que Wormhole Labs construyó para traer activos externos a Solana. Según reportes del 16 de julio de CoinGabbar, TradingView News y CryptoBriefing, la acción tokenizada, HOODx, es redimible 1:1 por la acción real de HOOD listada en Nasdaq y opera 24 horas al día en plataformas de Solana como Jupiter, Raydium, Meteora y Orca. Lo llamativo es que la propia acción de Robinhood fue tokenizada primero en una plataforma rival — Solana — sin aparente participación de Robinhood Chain, el propio esfuerzo de tokenización de la empresa enfocado en la UE.</p>
<p class="de">Die Stammaktie von Robinhood Markets, HOOD, begann am 16. Juli in tokenisierter Form auf der Solana-Blockchain zu handeln. Die Emission übernahm Backpack Securities, die Distribution lief über Sunrise, das Gateway, das Wormhole Labs gebaut hat, um externe Assets auf Solana zu bringen. Laut Berichten vom 16. Juli von CoinGabbar, TradingView News und CryptoBriefing ist die tokenisierte Aktie HOODx 1:1 gegen die tatsächliche, an der Nasdaq notierte HOOD-Aktie einlösbar und wird rund um die Uhr auf Solana-Plattformen wie Jupiter, Raydium, Meteora und Orca gehandelt. Bemerkenswert: Robinhoods eigene Aktie wurde zuerst auf einer rivalisierenden Plattform — Solana — tokenisiert, offenbar ohne Beteiligung von Robinhood Chain, dem eigenen, auf die EU ausgerichteten Tokenisierungsprojekt des Unternehmens.</p>
<p class="fr">L'action ordinaire de Robinhood Markets, HOOD, a commencé à se négocier sous forme tokenisée sur la blockchain Solana le 16 juillet. L'émission a été assurée par Backpack Securities, et la distribution est passée par Sunrise, la passerelle construite par Wormhole Labs pour amener des actifs externes sur Solana. Selon des rapports du 16 juillet de CoinGabbar, TradingView News et CryptoBriefing, l'action tokenisée HOODx est rachetable 1:1 contre l'action HOOD réelle cotée au Nasdaq et se négocie 24 heures sur 24 sur les principales plateformes Solana comme Jupiter, Raydium, Meteora et Orca. Ce qui frappe, c'est que l'action de Robinhood elle-même a été tokenisée d'abord sur une plateforme rivale — Solana — sans implication apparente de Robinhood Chain, l'effort de tokenisation propre à l'entreprise axé sur l'UE.</p>
<p class="pt">A ação ordinária da Robinhood Markets, HOOD, começou a ser negociada em forma tokenizada na blockchain Solana em 16 de julho. A emissão ficou a cargo da Backpack Securities, e a distribuição passou pela Sunrise, o gateway que a Wormhole Labs construiu para trazer ativos externos para a Solana. Segundo reportagens de 16 de julho da CoinGabbar, TradingView News e CryptoBriefing, a ação tokenizada HOODx é resgatável 1:1 pela ação real HOOD listada na Nasdaq e é negociada 24 horas por dia em plataformas da Solana como Jupiter, Raydium, Meteora e Orca. O que chama atenção é que a própria ação da Robinhood foi tokenizada primeiro em uma plataforma rival — a Solana — sem envolvimento aparente da Robinhood Chain, o próprio esforço de tokenização da empresa voltado para a UE.</p>
<p class="tr">Robinhood Markets'in adi hissesi HOOD, 16 Temmuz'da Solana blok zinciri üzerinde tokenize edilmiş biçimde işlem görmeye başladı. İhracı Backpack Securities üstlendi, dağıtım ise Wormhole Labs'ın harici varlıkları Solana'ya taşımak için kurduğu ağ geçidi Sunrise üzerinden yapıldı. CoinGabbar, TradingView News ve CryptoBriefing'in 16 Temmuz tarihli haberlerine göre, tokenize edilmiş hisse HOODx, Nasdaq'ta işlem gören gerçek HOOD hissesine 1:1 oranında geri alınabiliyor ve Jupiter, Raydium, Meteora ve Orca gibi başlıca Solana platformlarında günün 24 saati işlem görüyor. Dikkat çeken nokta, Robinhood'un kendi hissesinin, şirketin AB'ye odaklı kendi tokenizasyon girişimi Robinhood Chain'in görünürde hiçbir katılımı olmadan, rakip bir platform olan Solana'da önce tokenize edilmiş olması.</p>
<p class="vi">Cổ phiếu phổ thông của Robinhood Markets, HOOD, bắt đầu giao dịch dưới dạng token hóa trên blockchain Solana vào ngày 16 tháng 7. Việc phát hành do Backpack Securities đảm nhiệm, còn việc phân phối được thực hiện qua Sunrise — cổng kết nối mà Wormhole Labs xây dựng để đưa tài sản bên ngoài lên Solana. Theo các báo cáo ngày 16 tháng 7 từ CoinGabbar, TradingView News và CryptoBriefing, cổ phiếu token hóa HOODx có thể được đổi lại theo tỷ lệ 1:1 với cổ phiếu HOOD thực niêm yết trên Nasdaq và được giao dịch 24 giờ mỗi ngày trên các nền tảng lớn của Solana như Jupiter, Raydium, Meteora và Orca. Điều đáng chú ý là chính cổ phiếu của Robinhood lại được token hóa trước tiên trên một nền tảng đối thủ — Solana — mà không có sự tham gia rõ ràng nào từ Robinhood Chain, dự án token hóa riêng của công ty hướng tới thị trường EU.</p>

<h2 class="ko">무엇이, 어떻게 상장됐나 — 선라이즈·웜홀 NTT 구조</h2>
<h2 class="en">What Was Listed, and How — Inside the Sunrise/Wormhole NTT Structure</h2>
<h2 class="ja">何が、どのように上場したか — サンライズ・ウォームホールNTT構造</h2>
<h2 class="es">Qué Se Listó y Cómo — Dentro de la Estructura Sunrise/Wormhole NTT</h2>
<h2 class="de">Was Gelistet Wurde und Wie — Die Sunrise/Wormhole-NTT-Struktur im Detail</h2>
<h2 class="fr">Ce Qui a Été Coté et Comment — À l'Intérieur de la Structure Sunrise/Wormhole NTT</h2>
<h2 class="pt">O Que Foi Listado e Como — Dentro da Estrutura Sunrise/Wormhole NTT</h2>
<h2 class="tr">Ne Listelendi ve Nasıl — Sunrise/Wormhole NTT Yapısının İçinde</h2>
<h2 class="vi">Điều Gì Đã Được Niêm Yết Và Bằng Cách Nào — Bên Trong Cấu Trúc Sunrise/Wormhole NTT</h2>

<p class="ko">선라이즈는 2025년 11월 웜홀랩스가 선보인 솔라나의 '자산 게이트웨이'다. 웜홀의 네이티브 토큰 트랜스퍼(NTT) 프레임워크를 이용해 외부 자산을 솔라나 위에서 마치 네이티브 토큰처럼 작동하도록 감싸고, 주피터·레이디움·미티오라·오르카 같은 솔라나의 주요 거래 플랫폼에 곧바로 연결한다. 이번에 상장된 HOODx도 이 구조를 그대로 따른다 — 실제 HOOD 주식은 블록체인 밖 규제된 수탁 체계 안에 남아 있고, 백팩증권이 그 보유분에 대응하는 토큰을 솔라나 위에서 발행하는 방식이다.</p>
<p class="ko">이 모델의 핵심은 '1대1 상환'이다. HOODx 보유자는 이론상 언제든 토큰을 실제 HOOD 주식으로 되돌릴 수 있고, 이 상환 경로가 나스닥 가격과 온체인 가격을 묶어주는 차익거래 고리 역할을 한다. 실제로 HOODx의 가격은 나스닥 HOOD 주가를 따라 대체로 102~115달러 구간에서 움직여 왔다. 이는 과거 미국 밖에서 애플·테슬라 같은 주식을 흉내 내며 실제 주식을 보유하지 않은 채 가격만 합성적으로 추종했던 초기 토큰화 주식들과는 결이 다르다 — 다만 그 상환이 실제로 얼마나 원활히 이뤄지는지는 아직 독립적으로 검증되지 않았다.</p>

<p class="en">Sunrise is the "asset gateway" Wormhole Labs introduced on Solana in November 2025. It uses Wormhole's Native Token Transfer (NTT) framework to wrap external assets so they behave like native tokens on Solana, plugging them directly into major Solana venues such as Jupiter, Raydium, Meteora and Orca. HOODx follows the same structure: the actual HOOD share stays outside the blockchain in a regulated custody chain, while Backpack Securities mints a corresponding token on Solana against that holding.</p>
<p class="en">The core of the model is 1:1 redemption. HOODx holders can, in theory, redeem their tokens back into real HOOD shares at any time, and that redemption path is what ties the on-chain price to the Nasdaq price through arbitrage. In practice, HOODx has largely tracked HOOD's Nasdaq price in a roughly $102–$115 range. That differs from earlier tokenized stocks issued outside the US that mimicked names like Apple and Tesla without holding the real shares, offering only synthetic price exposure — though how smoothly this redemption actually functions in practice has not yet been independently verified.</p>

<p class="ja">サンライズは2025年11月にウォームホール・ラボが発表した、ソラナの「資産ゲートウェイ」だ。ウォームホールのネイティブ・トークン・トランスファー(NTT)フレームワークを使い、外部資産をソラナ上でネイティブトークンのように機能するようラップし、ジュピター・レイディウム・メテオラ・オルカといったソラナの主要取引プラットフォームに直接接続する。今回上場したHOODxも同じ構造をそのまま踏襲している——実際のHOOD株はブロックチェーンの外、規制された保管体系の中にとどまり、バックパック証券がその保有分に対応するトークンをソラナ上で発行する仕組みだ。</p>
<p class="ja">このモデルの核心は「1対1償還」だ。HOODx保有者は理論上いつでもトークンを実際のHOOD株に戻すことができ、この償還経路がナスダック価格とオンチェーン価格を結び付ける裁定取引のループとして機能する。実際、HOODxの価格はナスダックのHOOD株価にほぼ連動し、おおむね102〜115ドルの範囲で推移してきた。これは、かつて米国外でアップルやテスラのような株式を模倣し、実株を保有せず価格だけを合成的に追随していた初期のトークン化株式とは一線を画す——ただし、この償還が実際にどれほど円滑に機能するかは、まだ独立して検証されていない。</p>

<p class="es">Sunrise es la "puerta de enlace de activos" que Wormhole Labs presentó en Solana en noviembre de 2025. Usa el marco Native Token Transfer (NTT) de Wormhole para envolver activos externos de modo que se comporten como tokens nativos en Solana, conectándolos directamente a las principales plataformas de Solana como Jupiter, Raydium, Meteora y Orca. HOODx sigue la misma estructura: la acción real de HOOD permanece fuera de la blockchain, en una cadena de custodia regulada, mientras Backpack Securities acuña un token correspondiente en Solana contra esa tenencia.</p>
<p class="es">El núcleo del modelo es la redención 1:1. Los tenedores de HOODx pueden, en teoría, canjear sus tokens por acciones reales de HOOD en cualquier momento, y esa vía de redención es lo que ata el precio on-chain al precio de Nasdaq mediante arbitraje. En la práctica, HOODx ha seguido de cerca el precio de HOOD en Nasdaq, en un rango de aproximadamente $102 a $115. Esto difiere de acciones tokenizadas anteriores, emitidas fuera de EE. UU., que imitaban nombres como Apple y Tesla sin poseer las acciones reales, ofreciendo solo exposición sintética al precio — aunque qué tan fluida es en la práctica esta redención aún no ha sido verificada de forma independiente.</p>

<p class="de">Sunrise ist das "Asset-Gateway", das Wormhole Labs im November 2025 auf Solana eingeführt hat. Es nutzt Wormholes Native-Token-Transfer-Framework (NTT), um externe Assets so zu verpacken, dass sie sich auf Solana wie native Token verhalten, und verbindet sie direkt mit wichtigen Solana-Plattformen wie Jupiter, Raydium, Meteora und Orca. HOODx folgt derselben Struktur: Die echte HOOD-Aktie bleibt außerhalb der Blockchain in einer regulierten Verwahrkette, während Backpack Securities einen entsprechenden Token auf Solana gegen diesen Bestand prägt.</p>
<p class="de">Der Kern des Modells ist die 1:1-Einlösung. HOODx-Inhaber können ihre Token theoretisch jederzeit gegen echte HOOD-Aktien einlösen, und dieser Einlösungspfad ist es, der den On-Chain-Preis über Arbitrage an den Nasdaq-Preis bindet. In der Praxis hat sich HOODx eng an den Nasdaq-Kurs von HOOD angelehnt und sich in einer Spanne von etwa 102 bis 115 US-Dollar bewegt. Das unterscheidet sich von früheren, außerhalb der USA ausgegebenen tokenisierten Aktien, die Namen wie Apple und Tesla nachahmten, ohne die echten Aktien zu halten, und nur synthetisches Preis-Exposure boten — wie reibungslos diese Einlösung in der Praxis tatsächlich funktioniert, ist allerdings noch nicht unabhängig verifiziert.</p>

<p class="fr">Sunrise est la « passerelle d'actifs » que Wormhole Labs a lancée sur Solana en novembre 2025. Elle utilise le cadre Native Token Transfer (NTT) de Wormhole pour envelopper des actifs externes afin qu'ils se comportent comme des tokens natifs sur Solana, les connectant directement à des plateformes Solana majeures comme Jupiter, Raydium, Meteora et Orca. HOODx suit la même structure : l'action HOOD réelle reste en dehors de la blockchain, dans une chaîne de conservation réglementée, tandis que Backpack Securities émet un token correspondant sur Solana en contrepartie de cette détention.</p>
<p class="fr">Le cœur du modèle est le rachat 1:1. Les détenteurs de HOODx peuvent, en théorie, racheter leurs tokens contre de véritables actions HOOD à tout moment, et cette voie de rachat est ce qui lie le prix on-chain au prix Nasdaq par arbitrage. En pratique, HOODx a globalement suivi le cours Nasdaq de HOOD dans une fourchette d'environ 102 à 115 dollars. Cela diffère des actions tokenisées antérieures, émises hors des États-Unis, qui imitaient des noms comme Apple et Tesla sans détenir les actions réelles, n'offrant qu'une exposition synthétique au prix — bien que la fluidité réelle de ce rachat en pratique n'ait pas encore été vérifiée de façon indépendante.</p>

<p class="pt">A Sunrise é o "gateway de ativos" que a Wormhole Labs lançou na Solana em novembro de 2025. Ela usa o framework Native Token Transfer (NTT) da Wormhole para envolver ativos externos de modo que se comportem como tokens nativos na Solana, conectando-os diretamente a grandes plataformas da Solana como Jupiter, Raydium, Meteora e Orca. A HOODx segue a mesma estrutura: a ação real da HOOD permanece fora da blockchain, em uma cadeia de custódia regulada, enquanto a Backpack Securities emite um token correspondente na Solana contra essa participação.</p>
<p class="pt">O núcleo do modelo é o resgate 1:1. Os detentores de HOODx podem, em teoria, resgatar seus tokens por ações reais da HOOD a qualquer momento, e essa via de resgate é o que amarra o preço on-chain ao preço da Nasdaq via arbitragem. Na prática, a HOODx tem acompanhado de perto o preço da HOOD na Nasdaq, numa faixa de aproximadamente US$ 102 a US$ 115. Isso difere de ações tokenizadas anteriores, emitidas fora dos EUA, que imitavam nomes como Apple e Tesla sem deter as ações reais, oferecendo apenas exposição sintética ao preço — embora quão suave esse resgate realmente funciona na prática ainda não tenha sido verificado de forma independente.</p>

<p class="tr">Sunrise, Wormhole Labs'ın Kasım 2025'te Solana'da tanıttığı "varlık ağ geçidi"dir. Harici varlıkları Solana üzerinde yerel token gibi davranacak şekilde sarmalamak için Wormhole'un Native Token Transfer (NTT) çerçevesini kullanır ve bunları doğrudan Jupiter, Raydium, Meteora ve Orca gibi büyük Solana platformlarına bağlar. HOODx da aynı yapıyı izliyor: gerçek HOOD hissesi blok zinciri dışında, düzenlenmiş bir saklama zincirinde kalırken, Backpack Securities bu varlığa karşılık Solana üzerinde eşdeğer bir token basıyor.</p>
<p class="tr">Modelin özü 1:1 geri alımdır. HOODx sahipleri teorik olarak tokenlerini istedikleri zaman gerçek HOOD hisselerine geri dönüştürebilir ve bu geri alım yolu, arbitraj yoluyla zincir üstü fiyatı Nasdaq fiyatına bağlayan mekanizmadır. Pratikte HOODx, HOOD'un Nasdaq fiyatını büyük ölçüde takip ederek yaklaşık 102-115 dolar aralığında hareket etti. Bu, ABD dışında ihraç edilen ve Apple, Tesla gibi isimleri gerçek hisseleri elinde bulundurmadan taklit ederek yalnızca sentetik fiyat maruziyeti sunan önceki tokenize hisselerden farklı — ancak bu geri alımın pratikte gerçekte ne kadar sorunsuz işlediği henüz bağımsız olarak doğrulanmadı.</p>

<p class="vi">Sunrise là "cổng tài sản" mà Wormhole Labs ra mắt trên Solana vào tháng 11 năm 2025. Nó sử dụng khung Native Token Transfer (NTT) của Wormhole để bọc các tài sản bên ngoài sao cho chúng hoạt động như token gốc trên Solana, kết nối trực tiếp với các nền tảng lớn của Solana như Jupiter, Raydium, Meteora và Orca. HOODx cũng theo cùng cấu trúc đó: cổ phiếu HOOD thực nằm ngoài blockchain, trong một chuỗi lưu ký được quản lý, trong khi Backpack Securities phát hành token tương ứng trên Solana dựa trên lượng nắm giữ đó.</p>
<p class="vi">Cốt lõi của mô hình này là khả năng đổi lại theo tỷ lệ 1:1. Về lý thuyết, người nắm giữ HOODx có thể đổi token của mình lấy cổ phiếu HOOD thực bất cứ lúc nào, và con đường đổi lại này chính là thứ ràng buộc giá on-chain với giá trên Nasdaq thông qua chênh lệch giá. Trên thực tế, HOODx phần lớn đã bám sát giá HOOD trên Nasdaq, dao động trong khoảng 102-115 đô la. Điều này khác với các cổ phiếu token hóa trước đây, phát hành bên ngoài nước Mỹ, vốn mô phỏng các cái tên như Apple và Tesla mà không nắm giữ cổ phiếu thực, chỉ mang lại mức độ tiếp cận giá tổng hợp — dù việc đổi lại này trên thực tế diễn ra suôn sẻ đến đâu vẫn chưa được xác minh độc lập.</p>

<div class="ko">
<svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">HOODx: 나스닥과 솔라나를 잇는 1:1 상환 구조</text>
  <g font-family="sans-serif">
    <rect x="30" y="60" width="190" height="90" rx="8" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
    <text x="125" y="90" fill="#e4e4e7" font-size="13" font-weight="700" text-anchor="middle">실제 HOOD 주식</text>
    <text x="125" y="112" fill="#a1a1aa" font-size="12" text-anchor="middle">나스닥 상장</text>
    <text x="125" y="132" fill="#71717a" font-size="11" text-anchor="middle">규제된 수탁 체인</text>

    <line x1="220" y1="105" x2="270" y2="105" stroke="#9945FF" stroke-width="2.5" marker-end="url(#arrow1)"/>
    <text x="245" y="95" fill="#9945FF" font-size="11" text-anchor="middle">발행/상환</text>

    <rect x="270" y="60" width="200" height="90" rx="8" fill="#1c1c1f" stroke="#9945FF" stroke-width="1.5"/>
    <text x="370" y="90" fill="#e4e4e7" font-size="13" font-weight="700" text-anchor="middle">HOODx 토큰</text>
    <text x="370" y="112" fill="#a1a1aa" font-size="12" text-anchor="middle">솔라나 · 웜홀 NTT 래핑</text>
    <text x="370" y="132" fill="#71717a" font-size="11" text-anchor="middle">백팩증권 발행</text>

    <line x1="470" y1="105" x2="520" y2="105" stroke="#22c55e" stroke-width="2.5"/>
    <text x="495" y="95" fill="#22c55e" font-size="11" text-anchor="middle">유통</text>

    <rect x="520" y="60" width="150" height="90" rx="8" fill="#1c1c1f" stroke="#22c55e" stroke-width="1.5"/>
    <text x="595" y="86" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Jupiter</text>
    <text x="595" y="106" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Raydium</text>
    <text x="595" y="126" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Meteora · Orca</text>

    <rect x="30" y="185" width="640" height="80" rx="8" fill="#1c1c1f" stroke="rgba(255,255,255,.1)" stroke-width="1"/>
    <text x="350" y="215" fill="#f4f4f5" font-size="20" font-weight="700" text-anchor="middle">1:1 상환 · $102~115 구간에서 나스닥 가격 추적</text>
    <text x="350" y="242" fill="#a1a1aa" font-size="13" text-anchor="middle">나스닥 폐장 시간대(야간·주말)에는 상환 차익거래가 즉시 작동하지 않아 가격 괴리 위험이 남는다</text>
  </g>
  <text x="350" y="288" fill="#71717a" font-size="10" text-anchor="middle" font-family="sans-serif">출처: CoinGabbar, CryptoBriefing, Solana Compass (2026.7.16)</text>
</svg>
</div>
<div class="en es de fr pt tr vi">
<svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">HOODx: the 1:1 Redemption Bridge Between Nasdaq and Solana</text>
  <g font-family="sans-serif">
    <rect x="30" y="60" width="190" height="90" rx="8" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
    <text x="125" y="90" fill="#e4e4e7" font-size="13" font-weight="700" text-anchor="middle">Real HOOD Share</text>
    <text x="125" y="112" fill="#a1a1aa" font-size="12" text-anchor="middle">Nasdaq-listed</text>
    <text x="125" y="132" fill="#71717a" font-size="11" text-anchor="middle">Regulated custody chain</text>

    <line x1="220" y1="105" x2="270" y2="105" stroke="#9945FF" stroke-width="2.5"/>
    <text x="245" y="95" fill="#9945FF" font-size="11" text-anchor="middle">mint/redeem</text>

    <rect x="270" y="60" width="200" height="90" rx="8" fill="#1c1c1f" stroke="#9945FF" stroke-width="1.5"/>
    <text x="370" y="90" fill="#e4e4e7" font-size="13" font-weight="700" text-anchor="middle">HOODx Token</text>
    <text x="370" y="112" fill="#a1a1aa" font-size="12" text-anchor="middle">Solana · Wormhole NTT-wrapped</text>
    <text x="370" y="132" fill="#71717a" font-size="11" text-anchor="middle">Issued by Backpack Securities</text>

    <line x1="470" y1="105" x2="520" y2="105" stroke="#22c55e" stroke-width="2.5"/>
    <text x="495" y="95" fill="#22c55e" font-size="11" text-anchor="middle">trade</text>

    <rect x="520" y="60" width="150" height="90" rx="8" fill="#1c1c1f" stroke="#22c55e" stroke-width="1.5"/>
    <text x="595" y="86" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Jupiter</text>
    <text x="595" y="106" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Raydium</text>
    <text x="595" y="126" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Meteora · Orca</text>

    <rect x="30" y="185" width="640" height="80" rx="8" fill="#1c1c1f" stroke="rgba(255,255,255,.1)" stroke-width="1"/>
    <text x="350" y="215" fill="#f4f4f5" font-size="20" font-weight="700" text-anchor="middle">1:1 redemption · tracks Nasdaq around $102–$115</text>
    <text x="350" y="242" fill="#a1a1aa" font-size="13" text-anchor="middle">When Nasdaq is closed (nights/weekends), redemption arbitrage can't fire instantly — leaving room to diverge</text>
  </g>
  <text x="350" y="288" fill="#71717a" font-size="10" text-anchor="middle" font-family="sans-serif">Source: CoinGabbar, CryptoBriefing, Solana Compass (July 16, 2026)</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">HOODx: ナスダックとソラナを結ぶ1対1償還構造</text>
  <g font-family="sans-serif">
    <rect x="30" y="60" width="190" height="90" rx="8" fill="#1c1c1f" stroke="#38bdf8" stroke-width="1.5"/>
    <text x="125" y="90" fill="#e4e4e7" font-size="13" font-weight="700" text-anchor="middle">実際のHOOD株</text>
    <text x="125" y="112" fill="#a1a1aa" font-size="12" text-anchor="middle">ナスダック上場</text>
    <text x="125" y="132" fill="#71717a" font-size="11" text-anchor="middle">規制された保管チェーン</text>

    <line x1="220" y1="105" x2="270" y2="105" stroke="#9945FF" stroke-width="2.5"/>
    <text x="245" y="95" fill="#9945FF" font-size="11" text-anchor="middle">発行/償還</text>

    <rect x="270" y="60" width="200" height="90" rx="8" fill="#1c1c1f" stroke="#9945FF" stroke-width="1.5"/>
    <text x="370" y="90" fill="#e4e4e7" font-size="13" font-weight="700" text-anchor="middle">HOODxトークン</text>
    <text x="370" y="112" fill="#a1a1aa" font-size="12" text-anchor="middle">ソラナ・ウォームホールNTTラップ</text>
    <text x="370" y="132" fill="#71717a" font-size="11" text-anchor="middle">バックパック証券が発行</text>

    <line x1="470" y1="105" x2="520" y2="105" stroke="#22c55e" stroke-width="2.5"/>
    <text x="495" y="95" fill="#22c55e" font-size="11" text-anchor="middle">流通</text>

    <rect x="520" y="60" width="150" height="90" rx="8" fill="#1c1c1f" stroke="#22c55e" stroke-width="1.5"/>
    <text x="595" y="86" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Jupiter</text>
    <text x="595" y="106" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Raydium</text>
    <text x="595" y="126" fill="#e4e4e7" font-size="12" font-weight="700" text-anchor="middle">Meteora・Orca</text>

    <rect x="30" y="185" width="640" height="80" rx="8" fill="#1c1c1f" stroke="rgba(255,255,255,.1)" stroke-width="1"/>
    <text x="350" y="215" fill="#f4f4f5" font-size="20" font-weight="700" text-anchor="middle">1対1償還・ナスダック価格を102〜115ドルで追跡</text>
    <text x="350" y="242" fill="#a1a1aa" font-size="13" text-anchor="middle">ナスダック休場時間帯(夜間・週末)は償還裁定がすぐ働かず、価格乖離のリスクが残る</text>
  </g>
  <text x="350" y="288" fill="#71717a" font-size="10" text-anchor="middle" font-family="sans-serif">出典: CoinGabbar, CryptoBriefing, Solana Compass (2026年7月16日)</text>
</svg>
</div>

<h2 class="ko">선라이즈의 전례 — 스페이스X·마이크론에 이은 세 번째 대형 상장</h2>
<h2 class="en">Sunrise's Track Record — A Third Major Listing After SpaceX and Micron</h2>
<h2 class="ja">サンライズの実績 — スペースX・マイクロンに続く3件目の大型上場</h2>
<h2 class="es">El Historial de Sunrise — Un Tercer Gran Listado Tras SpaceX y Micron</h2>
<h2 class="de">Sunrises Erfolgsbilanz — Das Dritte Große Listing Nach SpaceX und Micron</h2>
<h2 class="fr">Le Palmarès de Sunrise — Une Troisième Cotation Majeure Après SpaceX et Micron</h2>
<h2 class="pt">O Histórico da Sunrise — Uma Terceira Grande Listagem Após SpaceX e Micron</h2>
<h2 class="tr">Sunrise'ın Geçmişi — SpaceX ve Micron'un Ardından Üçüncü Büyük Listeleme</h2>
<h2 class="vi">Thành Tích Của Sunrise — Lần Niêm Yết Lớn Thứ Ba Sau SpaceX Và Micron</h2>

<p class="ko">선라이즈와 백팩증권이 유명 기업 주식을 솔라나에 올린 건 이번이 처음이 아니다. 지난 6월12일에는 스페이스X(SPCX)가 나스닥 상장 당일 같은 날 솔라나에도 토큰화 형태로 동시 상장된 바 있고, 이 사이트가 앞서 짚은 것처럼 <a href="/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">마이크론·샌디스크 등도 같은 24시간 토큰화 증권 라인업</a>에 합류했다. HOOD는 이 흐름에서 가장 널리 알려진 소비자 브랜드라는 점에서 상징성이 크다.</p>
<p class="ko">같은 '실물 연동 토큰화'라도 진영은 갈린다. 이더리움 쪽에서는 <a href="/blog/ondo-tokenized-ivv-blackrock-etf">Ondo파이낸스가 SEC 등록 이전대리인을 통해 블랙록 ETF·마이크론 주식을 발행</a>하는, 미국 증권법 체계 안에 완전히 편입된 수탁형 모델을 밀고 있다. 반면 선라이즈·웜홀 방식은 기존 브로커리지(백팩증권)의 상환 약속과 웜홀의 크로스체인 메시징에 의존하는 구조로, 온체인에서의 유동성 확장 속도는 더 빠르지만 미국 증권거래위원회(SEC) 차원의 명시적 인가를 거친 것은 아니다. 두 모델 중 어느 쪽이 결국 표준이 될지는 아직 정해지지 않았다.</p>

<p class="en">This isn't the first time Sunrise and Backpack Securities have brought a well-known company's stock onto Solana. On June 12, SpaceX stock (SPCX) was simultaneously tokenized on Solana the same day it listed on Nasdaq, and as this site has covered, <a href="/en/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">Micron and SanDisk joined the same 24-hour tokenized-securities lineup</a>. HOOD carries outsized symbolic weight in this trend as the most widely recognized consumer brand among them.</p>
<p class="en">Even within "real-asset-backed tokenization," the field is splitting into camps. On Ethereum, <a href="/en/blog/ondo-tokenized-ivv-blackrock-etf">Ondo Finance issues BlackRock's ETF and Micron stock through an SEC-registered transfer agent</a>, a custodial model built fully inside US securities law. Sunrise and Wormhole's approach instead relies on a traditional brokerage's (Backpack Securities') redemption promise plus Wormhole's cross-chain messaging — faster to scale on-chain liquidity, but without explicit SEC authorization. Which model ultimately becomes the standard is still an open question.</p>

<p class="ja">サンライズとバックパック証券が著名企業の株式をソラナに載せたのは今回が初めてではない。6月12日にはスペースX(SPCX)がナスダック上場と同じ日にソラナでもトークン化形式で同時上場されており、当サイトが以前取り上げたように<a href="/ja/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">マイクロン・サンディスクなども同じ24時間トークン化証券のラインナップに加わった</a>。HOODはこの流れの中で最も広く知られた消費者ブランドという点で、象徴的な意味合いが大きい。</p>
<p class="ja">同じ「実物資産連動型トークン化」でも陣営は分かれる。イーサリアム陣営では<a href="/ja/blog/ondo-tokenized-ivv-blackrock-etf">Ondoファイナンスが、SEC登録の移転代理人を通じてブラックロックETFとマイクロン株を発行</a>する、米国証券法の枠組みに完全に組み込まれた保管型モデルを推進している。一方、サンライズ・ウォームホール方式は、既存の証券会社(バックパック証券)の償還保証とウォームホールのクロスチェーン・メッセージングに依存する構造で、オンチェーンでの流動性拡大は速いものの、米証券取引委員会(SEC)による明示的な認可を経たものではない。どちらのモデルが最終的に標準になるかは、まだ決まっていない。</p>

<p class="es">No es la primera vez que Sunrise y Backpack Securities llevan la acción de una empresa reconocida a Solana. El 12 de junio, la acción de SpaceX (SPCX) fue tokenizada simultáneamente en Solana el mismo día de su debut en Nasdaq, y como este sitio ha cubierto, <a href="/es/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">Micron y SanDisk se unieron a la misma alineación de valores tokenizados 24 horas</a>. HOOD tiene un peso simbólico desproporcionado en esta tendencia por ser la marca de consumo más reconocida entre ellas.</p>
<p class="es">Incluso dentro de la "tokenización respaldada por activos reales", el campo se divide en bandos. En Ethereum, <a href="/es/blog/ondo-tokenized-ivv-blackrock-etf">Ondo Finance emite el ETF de BlackRock y la acción de Micron a través de un agente de transferencia registrado ante la SEC</a>, un modelo custodial construido enteramente dentro de la ley de valores de EE. UU. El enfoque de Sunrise y Wormhole, en cambio, depende de la promesa de redención de una correduría tradicional (Backpack Securities) más la mensajería entre cadenas de Wormhole — más rápido para escalar liquidez on-chain, pero sin autorización explícita de la SEC. Cuál modelo termine siendo el estándar sigue siendo una pregunta abierta.</p>

<p class="de">Es ist nicht das erste Mal, dass Sunrise und Backpack Securities die Aktie eines bekannten Unternehmens auf Solana bringen. Am 12. Juni wurde die SpaceX-Aktie (SPCX) am selben Tag wie ihr Nasdaq-Debüt gleichzeitig auf Solana tokenisiert, und wie diese Seite bereits berichtet hat, <a href="/de/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">stießen Micron und SanDisk zur selben 24-Stunden-Reihe tokenisierter Wertpapiere</a>. HOOD trägt in diesem Trend überdurchschnittliches symbolisches Gewicht, da es die bekannteste Verbrauchermarke unter ihnen ist.</p>
<p class="de">Selbst innerhalb der "durch reale Assets gedeckten Tokenisierung" spaltet sich das Feld in Lager. Auf Ethereum <a href="/de/blog/ondo-tokenized-ivv-blackrock-etf">gibt Ondo Finance BlackRocks ETF und die Micron-Aktie über einen bei der SEC registrierten Transfer Agent aus</a> — ein Verwahrmodell, das vollständig innerhalb des US-Wertpapierrechts aufgebaut ist. Sunrises und Wormholes Ansatz stützt sich dagegen auf das Einlösungsversprechen eines traditionellen Brokers (Backpack Securities) plus Wormholes Cross-Chain-Messaging — schneller skalierbar bei der On-Chain-Liquidität, aber ohne explizite SEC-Genehmigung. Welches Modell sich letztlich durchsetzt, ist noch offen.</p>

<p class="fr">Ce n'est pas la première fois que Sunrise et Backpack Securities apportent l'action d'une entreprise reconnue sur Solana. Le 12 juin, l'action SpaceX (SPCX) a été tokenisée simultanément sur Solana le jour même de ses débuts au Nasdaq, et comme ce site l'a couvert, <a href="/fr/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">Micron et SanDisk ont rejoint la même gamme de titres tokenisés 24 heures sur 24</a>. HOOD porte un poids symbolique disproportionné dans cette tendance en tant que marque grand public la plus reconnue parmi elles.</p>
<p class="fr">Même au sein de la « tokenisation adossée à des actifs réels », le camp se divise. Sur Ethereum, <a href="/fr/blog/ondo-tokenized-ivv-blackrock-etf">Ondo Finance émet l'ETF de BlackRock et l'action Micron via un agent de transfert enregistré auprès de la SEC</a>, un modèle custodial construit entièrement dans le cadre du droit des valeurs mobilières américain. L'approche de Sunrise et Wormhole repose en revanche sur la promesse de rachat d'un courtier traditionnel (Backpack Securities) plus la messagerie inter-chaînes de Wormhole — plus rapide à faire évoluer en liquidité on-chain, mais sans autorisation explicite de la SEC. Quel modèle deviendra finalement la norme reste une question ouverte.</p>

<p class="pt">Não é a primeira vez que a Sunrise e a Backpack Securities trazem a ação de uma empresa conhecida para a Solana. Em 12 de junho, a ação da SpaceX (SPCX) foi tokenizada simultaneamente na Solana no mesmo dia de sua estreia na Nasdaq, e como este site já cobriu, <a href="/pt/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">Micron e SanDisk se juntaram à mesma linha de valores tokenizados 24 horas</a>. A HOOD carrega peso simbólico desproporcional nessa tendência por ser a marca de consumo mais reconhecida entre elas.</p>
<p class="pt">Mesmo dentro da "tokenização lastreada em ativos reais", o campo se divide em times. Na Ethereum, <a href="/pt/blog/ondo-tokenized-ivv-blackrock-etf">a Ondo Finance emite o ETF da BlackRock e a ação da Micron por meio de um agente de transferência registrado na SEC</a>, um modelo de custódia construído inteiramente dentro da legislação de valores mobiliários dos EUA. Já a abordagem da Sunrise e da Wormhole depende da promessa de resgate de uma corretora tradicional (Backpack Securities) somada à mensageria entre chains da Wormhole — mais rápida para escalar liquidez on-chain, mas sem autorização explícita da SEC. Qual modelo acabará se tornando o padrão ainda é uma questão em aberto.</p>

<p class="tr">Sunrise ve Backpack Securities'in tanınmış bir şirketin hissesini Solana'ya getirmesi bu ilk sefer değil. 12 Haziran'da SpaceX hissesi (SPCX), Nasdaq'taki listeleme günüyle aynı gün Solana'da da tokenize edilerek eşzamanlı listelendi ve bu sitenin daha önce ele aldığı gibi <a href="/tr/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">Micron ve SanDisk de aynı 24 saatlik tokenize menkul kıymet dizisine katıldı</a>. HOOD, bu trend içinde aralarında en yaygın tanınan tüketici markası olması nedeniyle orantısız bir sembolik ağırlık taşıyor.</p>
<p class="tr">"Gerçek varlık destekli tokenizasyon" içinde bile alan kamplara ayrılıyor. Ethereum tarafında <a href="/tr/blog/ondo-tokenized-ivv-blackrock-etf">Ondo Finance, SEC'e kayıtlı bir transfer acentesi aracılığıyla BlackRock'un ETF'ini ve Micron hissesini ihraç ediyor</a> — bu, tamamen ABD menkul kıymetler hukuku içinde inşa edilmiş bir saklama modeli. Sunrise ve Wormhole'un yaklaşımı ise geleneksel bir aracı kurumun (Backpack Securities) geri alım vaadine artı Wormhole'un zincirler arası mesajlaşmasına dayanıyor — zincir üstü likiditeyi ölçeklendirmede daha hızlı ama açık bir SEC yetkilendirmesi olmadan. Hangi modelin nihayetinde standart haline geleceği hâlâ açık bir soru.</p>

<p class="vi">Đây không phải lần đầu tiên Sunrise và Backpack Securities đưa cổ phiếu của một công ty nổi tiếng lên Solana. Vào ngày 12 tháng 6, cổ phiếu SpaceX (SPCX) đã được token hóa đồng thời trên Solana cùng ngày niêm yết trên Nasdaq, và như trang này đã đưa tin, <a href="/vi/blog/backpack-247-tokenized-equities-spacex-micron-sandisk">Micron và SanDisk cũng đã gia nhập cùng danh sách chứng khoán token hóa giao dịch 24 giờ đó</a>. HOOD mang trọng lượng biểu tượng lớn trong xu hướng này vì là thương hiệu tiêu dùng được biết đến rộng rãi nhất trong số đó.</p>
<p class="vi">Ngay cả trong nhóm "token hóa được bảo đảm bằng tài sản thực", lĩnh vực này cũng đang chia thành các phe khác nhau. Trên Ethereum, <a href="/vi/blog/ondo-tokenized-ivv-blackrock-etf">Ondo Finance phát hành ETF của BlackRock và cổ phiếu Micron thông qua một đại lý chuyển nhượng đã đăng ký với SEC</a>, một mô hình có lưu ký được xây dựng hoàn toàn trong khuôn khổ luật chứng khoán Mỹ. Trong khi đó, cách tiếp cận của Sunrise và Wormhole lại dựa vào cam kết đổi lại của một công ty môi giới truyền thống (Backpack Securities) cộng với hệ thống nhắn tin liên chuỗi của Wormhole — mở rộng thanh khoản on-chain nhanh hơn, nhưng không có sự cho phép rõ ràng từ SEC. Mô hình nào cuối cùng sẽ trở thành chuẩn mực vẫn còn là câu hỏi bỏ ngỏ.</p>

<h2 class="ko">아이러니와 리스크 — 로빈후드 체인, 그리고 24시간 거래의 괴리</h2>
<h2 class="en">The Irony and the Risk — Robinhood Chain, and the 24-Hour Trading Gap</h2>
<h2 class="ja">皮肉とリスク — ロビンフッドチェーン、そして24時間取引のズレ</h2>
<h2 class="es">La Ironía y el Riesgo — Robinhood Chain y la Brecha del Trading 24 Horas</h2>
<h2 class="de">Die Ironie und das Risiko — Robinhood Chain und die Lücke im 24-Stunden-Handel</h2>
<h2 class="fr">L'Ironie et le Risque — Robinhood Chain, et l'Écart du Trading 24h/24</h2>
<h2 class="pt">A Ironia e o Risco — Robinhood Chain, e o Descompasso da Negociação 24 Horas</h2>
<h2 class="tr">İroni ve Risk — Robinhood Chain ve 24 Saatlik İşlem Açığı</h2>
<h2 class="vi">Sự Trớ Trêu Và Rủi Ro — Robinhood Chain, Và Khoảng Cách Của Giao Dịch 24 Giờ</h2>

<p class="ko">아이러니는 로빈후드 자신이 유럽 고객을 대상으로 '로빈후드체인'이라는 자체 토큰화 인프라를 구축해 온 회사라는 데 있다. 그런데 정작 미국 나스닥에 상장된 HOOD 본주는, 로빈후드의 관여 없이 경쟁 생태계인 솔라나 위에서 먼저 24시간 거래되는 토큰으로 다시 태어났다. 공교롭게도 이 시점 HOOD 주가 자체는 신용 확장과 자금조달 계획을 둘러싼 투자자들의 우려로 100달러 선을 향해 밀리고 있었다는 FX리더스의 7월16일 보도도 함께 나왔다 — 토큰화 상장과 실물 주가 흐름이 같은 주에 겹친 셈이다.</p>
<p class="ko">24시간 거래는 양날의 검이다. 지지자들은 싱가포르의 투자자가 나스닥 개장을 기다리지 않고 로빈후드 관련 뉴스에 즉시 반응할 수 있다는 점을 장점으로 든다. 그러나 나스닥이 닫혀 있는 야간·주말 시간대에는 상환 차익거래가 즉시 작동하지 않을 수 있어, HOODx 가격이 일시적으로 실제 주가와 괴리될 위험이 남는다. 유동성이 얇은 시간대일수록 이 괴리가 커질 수 있다는 점은 토큰화 증권 전반이 안고 있는 구조적 약점이다.</p>

<p class="en">There's an irony here: Robinhood itself has built its own tokenization infrastructure, Robinhood Chain, for European customers. Yet the actual Nasdaq-listed HOOD stock was reborn as a 24-hour-traded token first on a rival ecosystem, Solana, with no apparent Robinhood involvement. Coincidentally, July 16 reporting from FXLeaders showed HOOD's own share price sliding toward the $100 level on investor concern over credit expansion and fundraising plans — the tokenized listing and the underlying stock's price action landed in the same week.</p>
<p class="en">Round-the-clock trading cuts both ways. Proponents point out that a trader in Singapore can react to Robinhood-related news instantly instead of waiting for the Nasdaq opening bell. But during nights and weekends when Nasdaq is closed, the redemption arbitrage that keeps HOODx tied to the real share can't fire immediately, leaving room for the token price to temporarily diverge from the underlying stock. That gap can widen in thinly traded hours — a structural weakness shared across tokenized securities generally.</p>

<p class="ja">皮肉なのは、ロビンフッド自身が欧州の顧客向けに「ロビンフッドチェーン」という自社のトークン化インフラを構築してきた会社だという点だ。それにもかかわらず、実際に米ナスダックに上場するHOOD本株は、ロビンフッドの関与なしに競合エコシステムであるソラナ上で先に24時間取引されるトークンとして生まれ変わった。奇しくも同じ時期、信用拡大と資金調達計画を巡る投資家の懸念からHOOD株価自体が100ドル台へと押し下げられていたというFXリーダーズの7月16日の報道も出ている——トークン化上場と実株の値動きが同じ週に重なった格好だ。</p>
<p class="ja">24時間取引は諸刃の剣だ。支持派は、シンガポールの投資家がナスダックの寄り付きを待たずにロビンフッド関連のニュースに即座に反応できる点を利点として挙げる。しかしナスダックが閉まっている夜間・週末には償還裁定がすぐには機能しない可能性があり、HOODxの価格が実株価から一時的に乖離するリスクが残る。流動性が薄い時間帯ほどこの乖離が広がりうる点は、トークン化証券全般が抱える構造的な弱点だ。</p>

<p class="es">Hay una ironía aquí: la propia Robinhood ha construido su propia infraestructura de tokenización, Robinhood Chain, para clientes europeos. Sin embargo, la acción real de HOOD listada en Nasdaq renació como un token negociado 24 horas primero en un ecosistema rival, Solana, sin aparente participación de Robinhood. Casualmente, reportes del 16 de julio de FXLeaders mostraron que el propio precio de la acción de HOOD se deslizaba hacia el nivel de $100 por preocupación de los inversores sobre la expansión de crédito y los planes de financiamiento — el listado tokenizado y el movimiento de precio de la acción subyacente coincidieron en la misma semana.</p>
<p class="es">El trading las 24 horas tiene dos caras. Los defensores señalan que un trader en Singapur puede reaccionar instantáneamente a noticias relacionadas con Robinhood en lugar de esperar la campana de apertura de Nasdaq. Pero durante las noches y fines de semana cuando Nasdaq está cerrado, el arbitraje de redención que ata a HOODx con la acción real no puede activarse de inmediato, dejando espacio para que el precio del token se desvíe temporalmente de la acción subyacente. Esa brecha puede ampliarse en horas de poca liquidez — una debilidad estructural compartida por los valores tokenizados en general.</p>

<p class="de">Es liegt eine Ironie darin: Robinhood selbst hat mit Robinhood Chain eine eigene Tokenisierungsinfrastruktur für europäische Kunden aufgebaut. Doch die tatsächliche, an der Nasdaq notierte HOOD-Aktie wurde zuerst auf einem rivalisierenden Ökosystem, Solana, als rund um die Uhr gehandelter Token wiedergeboren — offenbar ohne Beteiligung von Robinhood. Zufällig zeigten Berichte von FXLeaders vom 16. Juli, dass der Kurs der HOOD-Aktie selbst wegen Anlegersorgen über Kreditausweitung und Finanzierungspläne in Richtung der 100-Dollar-Marke abrutschte — das tokenisierte Listing und die Kursbewegung der zugrunde liegenden Aktie fielen in dieselbe Woche.</p>
<p class="de">Der Rund-um-die-Uhr-Handel ist zweischneidig. Befürworter weisen darauf hin, dass ein Trader in Singapur sofort auf Robinhood-bezogene Nachrichten reagieren kann, statt auf die Nasdaq-Eröffnungsglocke zu warten. Doch nachts und am Wochenende, wenn die Nasdaq geschlossen ist, kann die Einlösungsarbitrage, die HOODx an die echte Aktie bindet, nicht sofort greifen — der Token-Preis kann sich vorübergehend vom zugrunde liegenden Aktienkurs entkoppeln. Diese Lücke kann sich in liquiditätsschwachen Stunden vergrößern — eine strukturelle Schwäche, die tokenisierte Wertpapiere generell teilen.</p>

<p class="fr">Il y a une ironie ici : Robinhood elle-même a construit sa propre infrastructure de tokenisation, Robinhood Chain, pour ses clients européens. Pourtant, l'action HOOD réelle, cotée au Nasdaq, est réapparue comme un token négocié 24h/24 d'abord sur un écosystème rival, Solana, sans implication apparente de Robinhood. Par coïncidence, des rapports du 16 juillet de FXLeaders montraient que le cours de l'action HOOD elle-même glissait vers le niveau de 100 dollars en raison des inquiétudes des investisseurs sur l'expansion du crédit et les plans de financement — la cotation tokenisée et le mouvement de prix de l'action sous-jacente sont tombés la même semaine.</p>
<p class="fr">Le trading 24h/24 a un double tranchant. Les partisans soulignent qu'un trader à Singapour peut réagir instantanément aux nouvelles liées à Robinhood au lieu d'attendre la cloche d'ouverture du Nasdaq. Mais pendant les nuits et les week-ends où le Nasdaq est fermé, l'arbitrage de rachat qui lie HOODx à l'action réelle ne peut pas s'activer immédiatement, laissant une marge pour que le prix du token diverge temporairement de l'action sous-jacente. Cet écart peut s'élargir aux heures de faible liquidité — une faiblesse structurelle partagée par les valeurs tokenisées en général.</p>

<p class="pt">Há uma ironia aqui: a própria Robinhood construiu sua própria infraestrutura de tokenização, a Robinhood Chain, para clientes europeus. No entanto, a ação real da HOOD, listada na Nasdaq, renasceu como um token negociado 24 horas primeiro em um ecossistema rival, a Solana, sem envolvimento aparente da Robinhood. Coincidentemente, reportagens de 16 de julho da FXLeaders mostraram que o próprio preço da ação da HOOD deslizava rumo ao patamar de US$ 100 em meio à preocupação dos investidores com expansão de crédito e planos de captação — a listagem tokenizada e o movimento de preço da ação subjacente caíram na mesma semana.</p>
<p class="pt">A negociação 24 horas tem dois gumes. Defensores apontam que um trader em Singapura pode reagir instantaneamente a notícias relacionadas à Robinhood em vez de esperar o sino de abertura da Nasdaq. Mas durante noites e fins de semana em que a Nasdaq está fechada, a arbitragem de resgate que amarra a HOODx à ação real não consegue disparar imediatamente, deixando espaço para o preço do token divergir temporariamente da ação subjacente. Essa lacuna pode se ampliar em horários de baixa liquidez — uma fragilidade estrutural compartilhada pelos valores tokenizados de modo geral.</p>

<p class="tr">Burada bir ironi var: Robinhood'un kendisi, Avrupalı müşteriler için kendi tokenizasyon altyapısı olan Robinhood Chain'i inşa etti. Yine de Nasdaq'ta listelenen gerçek HOOD hissesi, görünürde Robinhood'un hiçbir katılımı olmadan, rakip bir ekosistem olan Solana'da önce 24 saat işlem gören bir token olarak yeniden doğdu. Tesadüfen, FXLeaders'ın 16 Temmuz tarihli haberleri, HOOD'un kendi hisse fiyatının kredi genişlemesi ve fon sağlama planlarına ilişkin yatırımcı endişeleri nedeniyle 100 dolar seviyesine doğru gerilediğini gösterdi — tokenize listeleme ile dayanak hissenin fiyat hareketi aynı haftaya denk geldi.</p>
<p class="tr">Kesintisiz işlem iki ucu keskin bir kılıç. Savunucular, Singapur'daki bir yatırımcının Nasdaq'ın açılış zilini beklemeden Robinhood ile ilgili haberlere anında tepki verebildiğini vurguluyor. Ancak Nasdaq'ın kapalı olduğu gece ve hafta sonlarında, HOODx'i gerçek hisseye bağlayan geri alım arbitrajı hemen devreye giremiyor ve bu da token fiyatının geçici olarak dayanak hisseden sapmasına alan bırakıyor. Bu açık, likiditenin ince olduğu saatlerde büyüyebilir — genel olarak tokenize menkul kıymetlerin paylaştığı yapısal bir zayıflık.</p>

<p class="vi">Có một sự trớ trêu ở đây: chính Robinhood đã xây dựng hạ tầng token hóa riêng của mình, Robinhood Chain, dành cho khách hàng châu Âu. Thế nhưng, cổ phiếu HOOD thực, niêm yết trên Nasdaq, lại được "tái sinh" thành một token giao dịch 24 giờ trước tiên trên một hệ sinh thái đối thủ, Solana, mà không có sự tham gia rõ ràng nào từ Robinhood. Trùng hợp thay, các báo cáo ngày 16 tháng 7 từ FXLeaders cho thấy chính giá cổ phiếu HOOD đang trượt về ngưỡng 100 đô la do lo ngại của nhà đầu tư về việc mở rộng tín dụng và các kế hoạch huy động vốn — việc niêm yết token hóa và diễn biến giá của cổ phiếu cơ sở rơi vào cùng một tuần.</p>
<p class="vi">Giao dịch suốt ngày đêm là con dao hai lưỡi. Những người ủng hộ chỉ ra rằng một nhà giao dịch ở Singapore có thể phản ứng ngay lập tức với tin tức liên quan đến Robinhood thay vì phải chờ tiếng chuông mở cửa Nasdaq. Nhưng vào ban đêm và cuối tuần khi Nasdaq đóng cửa, cơ chế chênh lệch giá đổi lại vốn ràng buộc HOODx với cổ phiếu thực không thể kích hoạt ngay lập tức, để lại khoảng trống cho giá token tạm thời lệch khỏi cổ phiếu cơ sở. Khoảng cách này có thể nới rộng hơn vào những giờ thanh khoản mỏng — một điểm yếu mang tính cấu trúc mà các chứng khoán token hóa nói chung đều có.</p>

<h2 class="ko">무엇을 지켜봐야 하나</h2>
<h2 class="en">What to Watch From Here</h2>
<h2 class="ja">今後注視すべき点</h2>
<h2 class="es">Qué Observar a Partir de Ahora</h2>
<h2 class="de">Worauf von Hier an zu Achten Ist</h2>
<h2 class="fr">Ce Qu'il Faut Surveiller à Partir de Maintenant</h2>
<h2 class="pt">O Que Observar a Partir de Agora</h2>
<h2 class="tr">Buradan İtibaren Nelere Dikkat Edilmeli</h2>
<h2 class="vi">Những Điều Cần Theo Dõi Từ Đây</h2>

<p class="ko">규제 측면에서 흥미로운 대목은, 로빈후드가 자체적으로 내놓은 토큰화 주식 상품은 미국이 아닌 유럽연합(EU) 고객만을 대상으로 설계돼 있다는 점이다. 이는 미국 규제당국이 자국 상장 증권의 토큰화에 대해 아직 신중한 태도를 유지하고 있음을 보여주는 간접 지표다. 선라이즈·백팩증권의 이번 상장이 미국 거주자에게 어느 범위까지 열려 있는지, 그리고 SEC가 이런 '브로커리지 상환형' 모델에 대해 어떤 입장을 낼지는 앞으로 지켜봐야 할 변수다.</p>
<p class="ko">더 큰 그림에서 이번 사례는 실물자산 토큰화 경쟁이 이더리움의 수탁형 모델과 솔라나의 유동성 우선 모델로 갈라져 동시에 진행되고 있음을 보여준다. 어느 체인이 더 많은 기업 주식을 유치하느냐가 아니라, 상환 메커니즘의 신뢰성과 규제 명확성이 결국 승부를 가를 가능성이 크다. 다음 지표로 볼 것은 로빈후드가 이 상장에 공식 반응을 내놓는지, 그리고 다른 대형 핀테크 기업의 주식이 뒤따라 토큰화되는지 여부다.</p>

<p class="en">One regulatory wrinkle worth noting: Robinhood's own tokenized stock products are built for EU customers, not US ones — an indirect signal that US regulators remain cautious about tokenizing domestically listed securities. Whether Sunrise and Backpack Securities' listing is open to US residents, and how the SEC eventually treats this "brokerage-redemption" model, are variables worth tracking.</p>
<p class="en">Zooming out, this case shows the real-world-asset tokenization race splitting into Ethereum's custodial model and Solana's liquidity-first model, running in parallel. Which chain attracts more corporate stock listings may matter less than which redemption mechanism proves more trustworthy and which gets clearer regulatory footing. The next signals to watch: whether Robinhood issues an official response to this listing, and whether other major fintech stocks follow HOOD onto tokenized rails.</p>

<p class="ja">規制面で興味深いのは、ロビンフッド自身が出しているトークン化株式商品が、米国ではなく欧州連合(EU)の顧客のみを対象に設計されている点だ。これは、米国の規制当局が自国上場証券のトークン化について依然として慎重な姿勢を維持していることを示す間接的な指標といえる。サンライズ・バックパック証券による今回の上場が米国居住者にどこまで開かれているのか、そしてSECがこうした「証券会社償還型」モデルにどのような立場を取るのかは、今後の注視点だ。</p>
<p class="ja">大きな構図で見れば、今回の事例は実物資産トークン化競争が、イーサリアムの保管型モデルとソラナの流動性優先モデルへと分かれ、同時並行で進んでいることを示している。どのチェーンがより多くの企業株を誘致するかよりも、償還メカニズムの信頼性と規制の明確さが最終的に勝敗を分ける可能性が高い。次に見るべき指標は、ロビンフッドがこの上場に公式な反応を示すかどうか、そして他の大手フィンテック企業の株式が続いてトークン化されるかどうかだ。</p>

<p class="es">Un matiz regulatorio que vale la pena notar: los propios productos de acciones tokenizadas de Robinhood están construidos para clientes de la UE, no de EE. UU. — una señal indirecta de que los reguladores estadounidenses siguen siendo cautelosos respecto a tokenizar valores listados domésticamente. Si el listado de Sunrise y Backpack Securities está abierto a residentes de EE. UU., y cómo eventualmente trate la SEC este modelo de "redención por correduría", son variables que vale la pena seguir.</p>
<p class="es">En perspectiva amplia, este caso muestra que la carrera de tokenización de activos del mundo real se está dividiendo entre el modelo custodial de Ethereum y el modelo centrado en liquidez de Solana, corriendo en paralelo. Qué cadena atraiga más listados de acciones corporativas puede importar menos que qué mecanismo de redención resulte más confiable y cuál obtenga una base regulatoria más clara. Las próximas señales a observar: si Robinhood emite una respuesta oficial a este listado, y si otras acciones importantes de fintech siguen a HOOD hacia los rieles tokenizados.</p>

<p class="de">Eine regulatorische Feinheit ist bemerkenswert: Robinhoods eigene tokenisierte Aktienprodukte sind für EU-Kunden gebaut, nicht für US-Kunden — ein indirektes Signal dafür, dass US-Regulierer bei der Tokenisierung inländisch notierter Wertpapiere weiterhin vorsichtig bleiben. Ob das Listing von Sunrise und Backpack Securities für US-Bürger offensteht und wie die SEC dieses "Broker-Einlösungs"-Modell letztlich behandelt, sind Variablen, die es zu beobachten gilt.</p>
<p class="de">Im größeren Bild zeigt dieser Fall, dass sich das Rennen um die Tokenisierung realer Assets in Ethereums Verwahrmodell und Solanas liquiditätsorientiertes Modell aufspaltet, die parallel laufen. Welche Chain mehr Unternehmensaktien-Listings anzieht, dürfte weniger entscheidend sein als welcher Einlösungsmechanismus sich als vertrauenswürdiger erweist und welcher klarere regulatorische Grundlagen erhält. Die nächsten Signale, auf die es zu achten gilt: ob Robinhood offiziell auf dieses Listing reagiert und ob weitere große Fintech-Aktien HOOD auf die tokenisierten Schienen folgen.</p>

<p class="fr">Une nuance réglementaire à noter : les propres produits d'actions tokenisées de Robinhood sont conçus pour les clients de l'UE, pas ceux des États-Unis — un signal indirect que les régulateurs américains restent prudents quant à la tokenisation de titres cotés domestiquement. Savoir si la cotation de Sunrise et Backpack Securities est ouverte aux résidents américains, et comment la SEC traitera finalement ce modèle de « rachat par courtier », sont des variables à surveiller.</p>
<p class="fr">Plus largement, ce cas montre que la course à la tokenisation d'actifs du monde réel se divise entre le modèle custodial d'Ethereum et le modèle axé sur la liquidité de Solana, qui progressent en parallèle. Quelle chaîne attire le plus de cotations d'actions d'entreprises pourrait compter moins que quel mécanisme de rachat s'avère le plus fiable et lequel obtient une base réglementaire plus claire. Les prochains signaux à surveiller : si Robinhood publie une réponse officielle à cette cotation, et si d'autres grandes actions fintech suivent HOOD sur les rails tokenisés.</p>

<p class="pt">Um detalhe regulatório digno de nota: os próprios produtos de ações tokenizadas da Robinhood são construídos para clientes da UE, não dos EUA — um sinal indireto de que os reguladores americanos permanecem cautelosos quanto à tokenização de valores mobiliários listados domesticamente. Se a listagem da Sunrise e da Backpack Securities está aberta a residentes dos EUA, e como a SEC eventualmente tratará esse modelo de "resgate via corretora", são variáveis que vale a pena acompanhar.</p>
<p class="pt">Em uma visão mais ampla, este caso mostra a corrida de tokenização de ativos do mundo real se dividindo entre o modelo de custódia da Ethereum e o modelo focado em liquidez da Solana, correndo em paralelo. Qual chain atrai mais listagens de ações corporativas pode importar menos do que qual mecanismo de resgate se mostra mais confiável e qual obtém base regulatória mais clara. Os próximos sinais a observar: se a Robinhood emite uma resposta oficial a essa listagem, e se outras grandes ações de fintech seguem a HOOD para os trilhos tokenizados.</p>

<p class="tr">Dikkat çekici bir düzenleyici ayrıntı: Robinhood'un kendi tokenize hisse ürünleri ABD değil AB müşterileri için tasarlandı — bu, ABD düzenleyicilerinin yurt içinde listelenmiş menkul kıymetleri tokenize etme konusunda hâlâ temkinli kaldığının dolaylı bir işareti. Sunrise ve Backpack Securities'in bu listelemesinin ABD sakinlerine ne ölçüde açık olduğu ve SEC'in bu "aracı kurum geri alımı" modeline nihayetinde nasıl yaklaşacağı, takip edilmeye değer değişkenler.</p>
<p class="tr">Daha geniş açıdan bakıldığında, bu vaka gerçek dünya varlık tokenizasyon yarışının Ethereum'un saklama modeli ile Solana'nın likidite öncelikli modeli arasında paralel şekilde ikiye bölündüğünü gösteriyor. Hangi zincirin daha fazla kurumsal hisse listelemesi çektiğinden çok, hangi geri alım mekanizmasının daha güvenilir çıktığı ve hangisinin daha net bir düzenleyici zemin kazandığı belirleyici olabilir. İzlenecek bir sonraki sinyaller: Robinhood'un bu listelemeye resmi bir yanıt verip vermeyeceği ve diğer büyük fintek hisselerinin HOOD'u tokenize raylara takip edip etmeyeceği.</p>

<p class="vi">Một điểm đáng chú ý về mặt quản lý: chính các sản phẩm cổ phiếu token hóa của Robinhood được thiết kế cho khách hàng EU, không phải khách hàng Mỹ — một tín hiệu gián tiếp cho thấy các cơ quan quản lý Mỹ vẫn còn thận trọng với việc token hóa chứng khoán niêm yết trong nước. Việc niêm yết của Sunrise và Backpack Securities có mở cho cư dân Mỹ hay không, và cuối cùng SEC sẽ ứng xử thế nào với mô hình "đổi lại qua công ty môi giới" này, là những biến số đáng theo dõi.</p>
<p class="vi">Nhìn rộng hơn, trường hợp này cho thấy cuộc đua token hóa tài sản thực đang phân tách thành mô hình có lưu ký của Ethereum và mô hình ưu tiên thanh khoản của Solana, chạy song song với nhau. Chuỗi nào thu hút được nhiều cổ phiếu doanh nghiệp niêm yết hơn có thể không quan trọng bằng việc cơ chế đổi lại nào chứng minh được độ tin cậy cao hơn và chuỗi nào có nền tảng quản lý rõ ràng hơn. Những tín hiệu tiếp theo cần theo dõi: liệu Robinhood có đưa ra phản hồi chính thức về việc niêm yết này hay không, và liệu các cổ phiếu fintech lớn khác có theo chân HOOD lên đường ray token hóa hay không.</p>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <polyline fill="none" stroke="#9945FF" stroke-width="6" stroke-linejoin="round" points="60,470 220,440 380,455 540,410 700,420 860,360 1020,300 1140,260"/>
  <circle cx="1140" cy="260" r="12" fill="#9945FF"/>
  <text x="60" y="180" fill="#f4f4f5" font-size="130" font-weight="bold">1:1</text>
  <text x="60" y="232" fill="#06b6d4" font-size="42" font-weight="bold">HOODX REDEEM</text>
  <text x="60" y="580" fill="#f4f4f5" font-size="46" font-weight="bold">$102–115</text>
  <text x="420" y="580" fill="#71717a" font-size="32" font-weight="bold">24/7 · HOOD/SOL</text>
  <image href="/oglogo/SOL.png" x="960" y="40" width="150" height="150"/>
</svg></div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: CoinGabbar('Solana News: Robinhood Expands Tokenized Stock Access with $HOOD', 2026.7.16), TradingView News/CoinMarketCal('Solana: gains tokenized HOOD shares', 2026.7.16), CryptoBriefing('Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana'), Coinfomania·HokaNews·Pluang 관련 보도(2026.7.16), Solana Compass(HOODx 가격 추적 데이터), FX리더스('Robinhood HOOD Stock Slides Toward $100', 2026.7.16). 일부 수치는 근사치이며 실시간 시세와 다를 수 있다. 본 글은 투자 조언이 아니다.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinGabbar ("Solana News: Robinhood Expands Tokenized Stock Access with $HOOD," July 16, 2026), TradingView News/CoinMarketCal ("Solana: gains tokenized HOOD shares," July 16, 2026), CryptoBriefing ("Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana"), Coinfomania, HokaNews and Pluang reporting (July 16, 2026), Solana Compass (HOODx price-tracking data), FXLeaders ("Robinhood HOOD Stock Slides Toward $100," July 16, 2026). Some figures are approximate and may differ from real-time quotes. This is not investment advice.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: コインギャバー(「Solana News: Robinhood Expands Tokenized Stock Access with $HOOD」、2026年7月16日)、トレーディングビュー・ニュース/コインマーケットカル(「Solana: gains tokenized HOOD shares」、2026年7月16日)、クリプトブリーフィング(「Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana」)、コインフォマニア・ホカニュース・プルアンの関連報道(2026年7月16日)、ソラナ・コンパス(HOODx価格追跡データ)、FXリーダーズ(「Robinhood HOOD Stock Slides Toward $100」、2026年7月16日)。一部数値は近似値であり、リアルタイム相場と異なる場合がある。本記事は投資助言ではない。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinGabbar ("Solana News: Robinhood Expands Tokenized Stock Access with $HOOD", 16 de julio de 2026), TradingView News/CoinMarketCal ("Solana: gains tokenized HOOD shares", 16 de julio de 2026), CryptoBriefing ("Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana"), reportes de Coinfomania, HokaNews y Pluang (16 de julio de 2026), Solana Compass (datos de seguimiento de precio de HOODx), FXLeaders ("Robinhood HOOD Stock Slides Toward $100", 16 de julio de 2026). Algunas cifras son aproximadas y pueden diferir de las cotizaciones en tiempo real. Esto no es asesoría de inversión.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinGabbar ("Solana News: Robinhood Expands Tokenized Stock Access with $HOOD", 16. Juli 2026), TradingView News/CoinMarketCal ("Solana: gains tokenized HOOD shares", 16. Juli 2026), CryptoBriefing ("Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana"), Berichte von Coinfomania, HokaNews und Pluang (16. Juli 2026), Solana Compass (HOODx-Preisverfolgungsdaten), FXLeaders ("Robinhood HOOD Stock Slides Toward $100", 16. Juli 2026). Einige Zahlen sind Näherungswerte und können von Echtzeitkursen abweichen. Dies ist keine Anlageberatung.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinGabbar (« Solana News: Robinhood Expands Tokenized Stock Access with $HOOD », 16 juillet 2026), TradingView News/CoinMarketCal (« Solana: gains tokenized HOOD shares », 16 juillet 2026), CryptoBriefing (« Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana »), reportages de Coinfomania, HokaNews et Pluang (16 juillet 2026), Solana Compass (données de suivi du prix de HOODx), FXLeaders (« Robinhood HOOD Stock Slides Toward $100 », 16 juillet 2026). Certains chiffres sont approximatifs et peuvent différer des cotations en temps réel. Ceci n'est pas un conseil en investissement.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinGabbar ("Solana News: Robinhood Expands Tokenized Stock Access with $HOOD", 16 de julho de 2026), TradingView News/CoinMarketCal ("Solana: gains tokenized HOOD shares", 16 de julho de 2026), CryptoBriefing ("Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana"), reportagens da Coinfomania, HokaNews e Pluang (16 de julho de 2026), Solana Compass (dados de rastreamento de preço da HOODx), FXLeaders ("Robinhood HOOD Stock Slides Toward $100", 16 de julho de 2026). Alguns números são aproximados e podem diferir das cotações em tempo real. Isto não é aconselhamento de investimento.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinGabbar ("Solana News: Robinhood Expands Tokenized Stock Access with $HOOD", 16 Temmuz 2026), TradingView News/CoinMarketCal ("Solana: gains tokenized HOOD shares", 16 Temmuz 2026), CryptoBriefing ("Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana"), Coinfomania, HokaNews ve Pluang haberleri (16 Temmuz 2026), Solana Compass (HOODx fiyat takip verileri), FXLeaders ("Robinhood HOOD Stock Slides Toward $100", 16 Temmuz 2026). Bazı rakamlar yaklaşık değerlerdir ve gerçek zamanlı fiyatlardan farklı olabilir. Bu, yatırım tavsiyesi değildir.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinGabbar ("Solana News: Robinhood Expands Tokenized Stock Access with $HOOD", 16/7/2026), TradingView News/CoinMarketCal ("Solana: gains tokenized HOOD shares", 16/7/2026), CryptoBriefing ("Sunrise lists tokenized Robinhood stock $HOOD for trading on Solana"), các báo cáo từ Coinfomania, HokaNews và Pluang (16/7/2026), Solana Compass (dữ liệu theo dõi giá HOODx), FXLeaders ("Robinhood HOOD Stock Slides Toward $100", 16/7/2026). Một số số liệu là gần đúng và có thể khác với giá thời gian thực. Đây không phải là lời khuyên đầu tư.</p>

<?php require __DIR__.'/_footer.php'; ?>
