<?php $slug = 'rsi-threshold-vs-divergence'; require __DIR__.'/_header.php'; ?>

<p class="ko">2018년 12월, 비트코인 주간 RSI가 25.6까지 떨어졌다. 이 정도로 깊은 과매도 구간은 비트코인 역사에서 단 두 차례밖에 없었다 — 2015년 초 가격이 200달러대였을 때와, 이때 3,500달러대로 주저앉았을 때다. 시장 데이터를 분석한 스포티드크립토(Spoted Crypto)에 따르면, 이 두 바닥 모두 신호가 뜬 직후 곧바로 반등하지는 않았지만 3~6개월의 횡보를 거친 뒤 결국 추세가 뒤집혔다. 반대로 2020년 말부터 2021년 11월까지 이어진 상승장에서는 완전히 다른 그림이 펼쳐졌다. RSI가 70을 넘어설 때마다 "과매수니 매도"라는 신호를 곧이곧대로 따른 투자자는, 약 1만 달러에서 6만 9천 달러까지 이어진 거의 10배 상승의 대부분을 반납하고 시장 밖에서 지켜봐야 했다.</p>
<p class="en">In December 2018, Bitcoin's weekly RSI dropped to 25.6. That depth of oversold territory had occurred only twice before in Bitcoin's history — once in early 2015 when the price sat in the $200s, and this time, when it collapsed into the $3,500 range. According to an analysis of historical data by Spoted Crypto, neither bottom rebounded immediately; both needed three to six months of sideways consolidation before the trend actually reversed. Contrast that with the bull run that ran from late 2020 through November 2021. Anyone who took "RSI above 70 means overbought, sell" literally every time it crossed that line gave up most of a nearly tenfold rally — from roughly $10,000 to $69,000 — and watched it from the sidelines.</p>
<p class="ja">2018年12月、ビットコインの週足RSIは25.6まで下落した。これほど深い売られすぎ水準は、ビットコインの歴史上これまで2度しかなかった——2015年初め、価格が200ドル台だった時と、このとき3,500ドル台まで沈み込んだ時だ。Spoted Cryptoの過去データ分析によれば、どちらの底も直後に即座に反発したわけではなく、実際にトレンドが転換するまでには3〜6ヶ月の横ばいが必要だった。対照的に、2020年末から2021年11月まで続いた上昇相場ではまったく違う光景が広がった。「RSIが70を超えたら買われすぎ、売り」という教科書通りの解釈をそのまま守った投資家は、約1万ドルから6万9千ドルまで続いたほぼ10倍の上昇のほとんどを逃し、市場の外から眺めるしかなかった。</p>
<p class="es">En diciembre de 2018, el RSI semanal de Bitcoin cayó hasta 25.6. Una sobreventa de esa profundidad solo se había dado dos veces antes en la historia de Bitcoin — una a comienzos de 2015, cuando el precio rondaba los $200, y esta vez, cuando se derrumbó a la zona de los $3,500. Según un análisis de datos históricos de Spoted Crypto, ninguno de los dos fondos rebotó de inmediato; ambos necesitaron entre tres y seis meses de consolidación lateral antes de que la tendencia realmente se revirtiera. Compárese eso con el mercado alcista que corrió desde finales de 2020 hasta noviembre de 2021. Quien tomó al pie de la letra que "RSI por encima de 70 significa sobrecompra, hay que vender" cada vez que cruzaba esa línea, renunció a la mayor parte de una subida de casi diez veces — de unos $10,000 a $69,000 — y la vio pasar desde la banca.</p>
<p class="de">Im Dezember 2018 fiel der wöchentliche RSI von Bitcoin auf 25,6. Eine derart tiefe Überverkauft-Zone hatte es in der Geschichte von Bitcoin bis dahin nur zweimal gegeben — einmal Anfang 2015, als der Preis in den 200-Dollar-Bereich fiel, und diesmal, als er auf rund 3.500 Dollar abstürzte. Laut einer Analyse historischer Daten von Spoted Crypto erholte sich keiner der beiden Böden sofort; beide brauchten drei bis sechs Monate Seitwärtskonsolidierung, bevor sich der Trend tatsächlich umkehrte. Man vergleiche das mit dem Bullenmarkt, der von Ende 2020 bis November 2021 lief. Wer "RSI über 70 bedeutet überkauft, verkaufen" wörtlich nahm und bei jeder Überschreitung dieser Linie verkaufte, verpasste den Großteil einer fast zehnfachen Rallye — von rund 10.000 auf 69.000 Dollar — und sah nur von der Seitenlinie zu.</p>

<p class="ko">같은 지표, 같은 30·70이라는 숫자인데 왜 한쪽에서는 몇 달의 시차를 두고라도 결국 맞았고, 다른 쪽에서는 반복적으로 완전히 틀렸는가. 답은 RSI가 실제로는 하나의 신호가 아니라 서로 다른 두 개의 신호를 한 숫자 안에 욱여넣은 지표라는 데 있다. 하나는 30·70이라는 고정된 레벨을 근거로 삼는 임계값 신호이고, 다른 하나는 가격의 고점·저점과 모멘텀의 고점·저점이 서로 어떤 '모양'을 그리는지를 비교하는 다이버전스 신호다. 이 둘은 시장이 추세를 그리고 있는지, 방향 없이 맴돌고 있는지에 따라 전혀 다른 승률을 낸다. 이 구분 없이 RSI를 하나의 지표처럼 취급하는 트레이더는, 지표가 가장 필요한 순간에 정확히 배신당한다.</p>
<p class="en">Same indicator, same 30-and-70 thresholds — so why did one eventually turn out right, if only after a lag of months, while the other was repeatedly and completely wrong? The answer is that RSI isn't really one signal. It's two signals crammed into a single number. One is a threshold signal that relies on fixed levels — 30 and 70. The other is a divergence signal that compares the relative "shape" formed by price's highs and lows against the shape formed by momentum's highs and lows. Depending on whether the market is trending or going nowhere, these two produce very different win rates. A trader who treats RSI as a single indicator, without making that distinction, gets betrayed exactly when the indicator matters most.</p>
<p class="ja">同じ指標、同じ30・70という数字なのに、なぜ一方は数ヶ月の時差を経てでも結局正しく、もう一方は繰り返し完全に間違っていたのか。答えは、RSIが実際には一つのシグナルではなく、二つの異なるシグナルを一つの数字に押し込めた指標だという点にある。一つは30・70という固定レベルを根拠とする閾値シグナルであり、もう一つは価格の高値・安値とモメンタムの高値・安値がどのような「形」を描くかを比較するダイバージェンスシグナルだ。この二つは、市場がトレンドを描いているか方向性なく漂っているかによって、まったく異なる勝率を出す。この区別を知らずにRSIを一つの指標として扱うトレーダーは、指標が最も必要な瞬間に正確に裏切られる。</p>
<p class="es">El mismo indicador, los mismos umbrales de 30 y 70 — entonces, ¿por qué uno terminó acertando, aunque con meses de retraso, mientras el otro estuvo repetida y completamente equivocado? La respuesta es que el RSI en realidad no es una sola señal. Son dos señales comprimidas en un único número. Una es una señal de umbral que depende de niveles fijos — 30 y 70. La otra es una señal de divergencia que compara la "forma" relativa que forman los máximos y mínimos del precio frente a la forma que forman los máximos y mínimos del momentum. Según si el mercado está en tendencia o sin rumbo, estas dos producen tasas de acierto muy distintas. Un trader que trata al RSI como un solo indicador, sin hacer esa distinción, es traicionado justo cuando más lo necesita.</p>
<p class="de">Derselbe Indikator, dieselben Schwellenwerte 30 und 70 — warum lag der eine am Ende richtig, wenn auch mit einer Verzögerung von Monaten, während der andere wiederholt und vollständig falsch lag? Die Antwort ist, dass der RSI eigentlich kein einziges Signal ist. Es sind zwei Signale, die in eine einzige Zahl gepresst wurden. Das eine ist ein Schwellenwertsignal, das sich auf feste Niveaus stützt — 30 und 70. Das andere ist ein Divergenzsignal, das die relative "Form" vergleicht, die die Hochs und Tiefs des Preises gegenüber der Form bilden, die die Hochs und Tiefs des Momentums bilden. Je nachdem, ob der Markt trendet oder richtungslos ist, liefern diese beiden sehr unterschiedliche Trefferquoten. Ein Trader, der den RSI ohne diese Unterscheidung als einen einzigen Indikator behandelt, wird genau dann im Stich gelassen, wenn er den Indikator am meisten braucht.</p>

<h2 class="ko">계산 구조 — 하나의 공식 안에 있는 서로 다른 두 신호</h2>
<h2 class="en">The Math Behind It — Why One Formula Hides Two Different Signals</h2>
<h2 class="ja">計算の仕組み——一つの数式が隠す二つの異なるシグナル</h2>
<h2 class="es">La Matemática Detrás — Por Qué Una Fórmula Esconde Dos Señales Distintas</h2>
<h2 class="de">Die Mathematik Dahinter — Warum Eine Formel Zwei Verschiedene Signale Verbirgt</h2>

<p class="ko">RSI(상대강도지수)는 1978년 J. 웰레스 와일더(J. Welles Wilder Jr.)가 저서 『New Concepts in Technical Trading Systems』에서 처음 제시한 지표다. 계산식은 RSI = 100 − 100/(1+RS)이며, 여기서 RS는 일정 기간 동안의 평균 상승폭을 평균 하락폭으로 나눈 값이다. 표준 기간값 14는 정교한 최적화의 산물이 아니다. 와일더가 다른 지표들에서 함께 쓰던 28일 주기의 절반을 그대로 가져온 값이라는 게 여러 기술적 분석 자료의 설명이다 — MACD의 12·26·9가 1970년대 미국 증시의 6일 거래 주기에서 나온 것과 마찬가지로, RSI의 14 역시 물리 법칙이 아니라 그 시절 와일더의 작업 방식에 맞춘 경험적 선택이었다.</p>
<p class="en">The Relative Strength Index was introduced by J. Welles Wilder Jr. in his 1978 book, New Concepts in Technical Trading Systems. The formula is RSI = 100 − 100/(1+RS), where RS is the average gain over a given period divided by the average loss over that same period. The standard 14-period setting wasn't the product of rigorous optimization. Several technical-analysis sources note that Wilder simply carried over half of the 28-day cycle he was already using across his other indicators — much like MACD's 12-26-9 settings trace back to the six-day trading week of 1970s U.S. stock markets. RSI's 14 wasn't a law of nature either; it was an empirical choice fit to how Wilder worked at the time.</p>
<p class="ja">RSI(相対力指数)は1978年、J・ウェルズ・ワイルダーJr.(J. Welles Wilder Jr.)が著書『New Concepts in Technical Trading Systems』で初めて提示した指標だ。計算式はRSI = 100 − 100/(1+RS)であり、RSは一定期間の平均上昇幅を平均下落幅で割った値だ。標準期間値の14は、精緻な最適化の産物ではない。ワイルダーが他の指標でも併用していた28日周期の半分をそのまま持ってきた数字だという説明が、複数のテクニカル分析資料に見られる——MACDの12・26・9が1970年代の米国株式市場の6日取引週から来ているのと同じように、RSIの14もまた自然法則ではなく、当時のワイルダーの作業方式に合わせた経験的な選択だった。</p>
<p class="es">El Índice de Fuerza Relativa fue presentado por J. Welles Wilder Jr. en su libro de 1978, New Concepts in Technical Trading Systems. La fórmula es RSI = 100 − 100/(1+RS), donde RS es la ganancia promedio en un periodo dado dividida entre la pérdida promedio de ese mismo periodo. El ajuste estándar de 14 periodos no fue producto de una optimización rigurosa. Varias fuentes de análisis técnico señalan que Wilder simplemente tomó la mitad del ciclo de 28 días que ya usaba en sus otros indicadores — de forma parecida a como los ajustes 12-26-9 del MACD provienen de la semana laboral de seis días de los mercados bursátiles estadounidenses de los años setenta. El 14 del RSI tampoco fue una ley natural; fue una elección empírica ajustada a la forma de trabajar de Wilder en esa época.</p>
<p class="de">Der Relative-Stärke-Index wurde 1978 von J. Welles Wilder Jr. in seinem Buch New Concepts in Technical Trading Systems eingeführt. Die Formel lautet RSI = 100 − 100/(1+RS), wobei RS der durchschnittliche Gewinn über einen bestimmten Zeitraum geteilt durch den durchschnittlichen Verlust im selben Zeitraum ist. Die Standardeinstellung von 14 Perioden war nicht das Ergebnis rigoroser Optimierung. Mehrere Quellen der technischen Analyse weisen darauf hin, dass Wilder schlicht die Hälfte des 28-Tage-Zyklus übernahm, den er bereits bei seinen anderen Indikatoren verwendete — ähnlich wie die 12-26-9-Einstellungen des MACD auf die Sechs-Tage-Handelswoche der US-Aktienmärkte der 1970er-Jahre zurückgehen. Auch die 14 des RSI war kein Naturgesetz; sie war eine empirische Wahl, die zu Wilders damaliger Arbeitsweise passte.</p>

<p class="ko">문제는 이 하나의 숫자에서 두 가지 완전히 다른 방식으로 신호를 읽어낼 수 있다는 데 있다. 첫 번째는 절대 레벨 읽기다 — RSI가 30 밑으로 내려가면 과매도, 70을 넘으면 과매수로 보고 반전을 기대하는 방식으로, 이는 가격이 결국 평균으로 회귀한다는 전제를 깔고 있다. 두 번째는 모양 읽기다 — 다이버전스는 절대 레벨이 아니라, 가격이 만든 두 고점(혹은 저점)과 RSI가 만든 두 고점(혹은 저점)의 상대적인 방향이 서로 어긋나는지를 비교한다. 절대 레벨에 기대지 않기 때문에 다이버전스는 이론적으로 어떤 국면에서도 관측될 수 있지만, 임계값 신호는 가격이 실제로 평균으로 회귀하는 국면에서만 의미를 가진다. 이 전제 조건의 차이가 이후 두 신호의 승률을 완전히 갈라놓는다.</p>
<p class="en">The trouble is that this single number can be read two completely different ways. The first is a level read: when RSI drops below 30 it's oversold, when it rises above 70 it's overbought, and a reversal is expected — a read that assumes price eventually reverts to its mean. The second is a shape read: divergence doesn't rely on absolute levels at all. It compares whether the direction of two peaks (or troughs) in price and the direction of the corresponding two peaks (or troughs) in RSI disagree with each other. Because it doesn't depend on an absolute level, divergence can in principle be observed in any market regime. A threshold signal, by contrast, only means something in a regime where price actually does revert to its mean. That difference in underlying assumptions is what splits the two signals' win rates apart.</p>
<p class="ja">問題は、この一つの数字が二つのまったく異なる方法で読み取れるという点にある。一つ目は絶対レベル読みだ——RSIが30を下回れば売られすぎ、70を超えれば買われすぎとみなし反転を期待する読み方で、これは価格が最終的に平均へ回帰するという前提を敷いている。二つ目は形読みだ——ダイバージェンスは絶対レベルに依存せず、価格が作る2つの高値(または安値)とRSIが作る2つの高値(または安値)の相対的な方向が食い違っているかどうかを比較する。絶対レベルに頼らないため、ダイバージェンスは理論上どんな局面でも観測できるが、閾値シグナルは価格が実際に平均へ回帰する局面でのみ意味を持つ。この前提条件の違いが、その後の二つのシグナルの勝率を完全に分けている。</p>
<p class="es">El problema es que este único número puede leerse de dos maneras completamente distintas. La primera es una lectura de nivel: cuando el RSI cae por debajo de 30 está sobrevendido, cuando sube por encima de 70 está sobrecomprado, y se espera una reversión — una lectura que asume que el precio termina revirtiendo a su media. La segunda es una lectura de forma: la divergencia no depende de niveles absolutos en absoluto. Compara si la dirección de dos picos (o valles) del precio y la dirección de los dos picos (o valles) correspondientes del RSI se contradicen entre sí. Como no depende de un nivel absoluto, la divergencia en principio puede observarse en cualquier régimen de mercado. Una señal de umbral, en cambio, solo significa algo en un régimen donde el precio realmente revierte a su media. Esa diferencia en los supuestos subyacentes es lo que separa por completo las tasas de acierto de ambas señales.</p>
<p class="de">Das Problem ist, dass sich diese eine Zahl auf zwei völlig unterschiedliche Arten lesen lässt. Die erste ist eine Niveau-Lesart: Fällt der RSI unter 30, gilt er als überverkauft, steigt er über 70, als überkauft, und eine Umkehr wird erwartet — eine Lesart, die voraussetzt, dass der Preis letztlich zu seinem Mittelwert zurückkehrt. Die zweite ist eine Form-Lesart: Die Divergenz stützt sich überhaupt nicht auf absolute Niveaus. Sie vergleicht, ob die Richtung zweier Hochs (oder Tiefs) des Preises der Richtung der entsprechenden zwei Hochs (oder Tiefs) des RSI widerspricht. Weil sie nicht von einem absoluten Niveau abhängt, lässt sich Divergenz prinzipiell in jedem Marktregime beobachten. Ein Schwellenwertsignal dagegen bedeutet nur in einem Regime etwas, in dem der Preis tatsächlich zu seinem Mittelwert zurückkehrt. Dieser Unterschied in den zugrunde liegenden Annahmen ist es, der die Trefferquoten der beiden Signale vollständig auseinanderreißt.</p>

<h2 class="ko">다이버전스가 실제로 맞았던 순간들 — 2017년 고점에서 2018년 바닥까지</h2>
<h2 class="en">When Divergence Actually Got It Right — From the 2017 Top to the 2018 Bottom</h2>
<h2 class="ja">ダイバージェンスが実際に的中した瞬間——2017年の高値から2018年の底値まで</h2>
<h2 class="es">Cuando la Divergencia Acertó de Verdad — Del Techo de 2017 al Fondo de 2018</h2>
<h2 class="de">Als Divergenz Wirklich Richtig Lag — Vom Hoch 2017 bis zum Tief 2018</h2>

<p class="ko">2017년 11월부터 12월 사이, 비트코인이 2만 달러 문턱까지 치솟는 동안 주간 RSI는 정반대의 그림을 그렸다. 가격은 그 이전 고점보다 훨씬 높은 신고점을 세웠지만, RSI가 그리는 모멘텀의 고점은 오히려 이전보다 낮아지는 전형적인 약세 다이버전스가 나타났다. 이후 벌어진 일은 익히 알려진 대로다 — 비트코인은 12개월 동안 80% 넘게 폭락해 2018년 말 3천 달러대까지 주저앉았다. 그리고 바로 그 바닥에서, 이번에는 반대 방향의 신호가 떴다. 주간 RSI가 25.6까지 떨어지는 극단적 과매도와 함께, 가격의 저점 대비 모멘텀 저점이 완만해지는 강세 다이버전스가 함께 관측된 것이다.</p>
<p class="en">Between November and December 2017, as Bitcoin surged toward the $20,000 threshold, the weekly RSI told the opposite story. Price set a new high well above its previous peak, but the peak traced by RSI's momentum was actually lower than the one before it — a textbook bearish divergence. What followed is well documented: Bitcoin fell more than 80% over the next twelve months, bottoming in the $3,000s by late 2018. And right at that bottom, a signal in the opposite direction appeared. Alongside the extreme oversold reading of 25.6 on the weekly RSI, price's low compared with the previous low showed a bullish divergence in momentum's shape.</p>
<p class="ja">2017年11月から12月にかけて、ビットコインが2万ドルの大台に迫る中、週足RSIはまったく逆の絵を描いていた。価格は以前の高値をはるかに上回る新高値をつけたが、RSIが描くモメンタムの高値はむしろ以前より低くなる、教科書通りの弱気ダイバージェンスが現れた。その後起きたことはよく知られている通りだ——ビットコインはその後12ヶ月で80%以上暴落し、2018年末には3,000ドル台まで沈んだ。そして、まさにその底値で、今度は逆方向のシグナルが現れた。週足RSIが25.6まで下がる極端な売られすぎとともに、価格の安値に対してモメンタムの安値が緩やかになる強気ダイバージェンスが同時に観測されたのだ。</p>
<p class="es">Entre noviembre y diciembre de 2017, mientras Bitcoin subía hacia el umbral de los $20,000, el RSI semanal contaba la historia contraria. El precio marcó un nuevo máximo muy por encima del anterior, pero el pico que trazó el momentum del RSI fue en realidad más bajo que el anterior — una divergencia bajista de libro de texto. Lo que ocurrió después es bien conocido: Bitcoin cayó más de un 80% en los siguientes doce meses, tocando fondo en la zona de los $3,000 hacia fines de 2018. Y justo en ese fondo apareció una señal en la dirección contraria. Junto con la lectura extrema de sobreventa de 25.6 en el RSI semanal, el mínimo del precio frente al mínimo anterior mostró una divergencia alcista en la forma del momentum.</p>
<p class="de">Zwischen November und Dezember 2017, während Bitcoin auf die Schwelle von 20.000 Dollar zusteuerte, erzählte der wöchentliche RSI die gegenteilige Geschichte. Der Preis markierte ein neues Hoch weit über dem vorherigen, doch das Hoch, das der RSI beim Momentum zeichnete, war tatsächlich niedriger als das vorherige — eine lehrbuchmäßige bärische Divergenz. Was danach geschah, ist gut dokumentiert: Bitcoin fiel in den folgenden zwölf Monaten um mehr als 80% und erreichte Ende 2018 einen Boden im Bereich von 3.000 Dollar. Und genau an diesem Boden erschien ein Signal in die entgegengesetzte Richtung. Zusammen mit dem extremen Überverkauft-Wert von 25,6 im wöchentlichen RSI zeigte das Tief des Preises im Vergleich zum vorherigen Tief eine bullische Divergenz in der Form des Momentums.</p>

<div class="ko">
<svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">2021년 이중 고점의 다이버전스 — 가격은 올랐지만 모멘텀은 내려왔다</text>
  <line x1="200" y1="55" x2="200" y2="260" stroke="#3f3f46" stroke-dasharray="4 4"/>
  <line x1="550" y1="55" x2="550" y2="260" stroke="#3f3f46" stroke-dasharray="4 4"/>
  <text x="200" y="285" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">2021년 4월</text>
  <text x="550" y="285" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">2021년 11월</text>
  <text x="30" y="105" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">가격</text>
  <line x1="200" y1="140" x2="550" y2="95" stroke="#4ade80" stroke-width="3"/>
  <circle cx="200" cy="140" r="6" fill="#4ade80"/>
  <circle cx="550" cy="95" r="6" fill="#4ade80"/>
  <text x="200" y="165" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">약 $64,800</text>
  <text x="550" y="80" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">$69,000 (신고점)</text>
  <text x="30" y="205" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">RSI</text>
  <text x="30" y="222" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">모멘텀</text>
  <line x1="200" y1="195" x2="550" y2="235" stroke="#f87171" stroke-width="3"/>
  <circle cx="200" cy="195" r="6" fill="#f87171"/>
  <circle cx="550" cy="235" r="6" fill="#f87171"/>
  <text x="200" y="180" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">더 높은 고점</text>
  <text x="550" y="258" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">더 낮은 고점 (다이버전스)</text>
</svg>
</div>
<div class="en es de">
<svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">2021's Double-Top Divergence — Price Rose While Momentum Fell</text>
  <line x1="200" y1="55" x2="200" y2="260" stroke="#3f3f46" stroke-dasharray="4 4"/>
  <line x1="550" y1="55" x2="550" y2="260" stroke="#3f3f46" stroke-dasharray="4 4"/>
  <text x="200" y="285" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">April 2021</text>
  <text x="550" y="285" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">November 2021</text>
  <text x="30" y="105" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Price</text>
  <line x1="200" y1="140" x2="550" y2="95" stroke="#4ade80" stroke-width="3"/>
  <circle cx="200" cy="140" r="6" fill="#4ade80"/>
  <circle cx="550" cy="95" r="6" fill="#4ade80"/>
  <text x="200" y="165" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">~$64,800</text>
  <text x="550" y="80" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">$69,000 (ATH)</text>
  <text x="30" y="205" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">RSI</text>
  <text x="30" y="222" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">Momentum</text>
  <line x1="200" y1="195" x2="550" y2="235" stroke="#f87171" stroke-width="3"/>
  <circle cx="200" cy="195" r="6" fill="#f87171"/>
  <circle cx="550" cy="235" r="6" fill="#f87171"/>
  <text x="200" y="180" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">Higher Peak</text>
  <text x="550" y="258" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">Lower Peak (Divergence)</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">2021年の二重高値ダイバージェンス——価格は上昇、モメンタムは下降</text>
  <line x1="200" y1="55" x2="200" y2="260" stroke="#3f3f46" stroke-dasharray="4 4"/>
  <line x1="550" y1="55" x2="550" y2="260" stroke="#3f3f46" stroke-dasharray="4 4"/>
  <text x="200" y="285" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">2021年4月</text>
  <text x="550" y="285" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">2021年11月</text>
  <text x="30" y="105" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">価格</text>
  <line x1="200" y1="140" x2="550" y2="95" stroke="#4ade80" stroke-width="3"/>
  <circle cx="200" cy="140" r="6" fill="#4ade80"/>
  <circle cx="550" cy="95" r="6" fill="#4ade80"/>
  <text x="200" y="165" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">約$64,800</text>
  <text x="550" y="80" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">$69,000(史上最高値)</text>
  <text x="30" y="205" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">RSI</text>
  <text x="30" y="222" fill="#e4e4e7" font-size="13" font-weight="700" font-family="sans-serif">モメンタム</text>
  <line x1="200" y1="195" x2="550" y2="235" stroke="#f87171" stroke-width="3"/>
  <circle cx="200" cy="195" r="6" fill="#f87171"/>
  <circle cx="550" cy="235" r="6" fill="#f87171"/>
  <text x="200" y="180" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">より高い高値</text>
  <text x="550" y="258" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle" font-family="sans-serif">より低い高値(ダイバージェンス)</text>
</svg>
</div>

<p class="ko">4년 뒤인 2021년, 같은 패턴이 한 해 안에서 두 번 반복됐다. 4월에 비트코인은 약 6만 4,800~6만 5,000달러의 신고점을 세웠고, 이후 조정을 거쳐 11월 6만 9천 달러의 새로운 사상 최고가를 기록했다. 가격만 보면 4월보다 11월이 명백히 높았지만, 이번에도 RSI가 그리는 모멘텀의 고점은 4월보다 11월이 더 낮았다 — 가격과 모멘텀이 서로 다른 말을 하는 이중 다이버전스였다. 이 신호는 4월 고점 이후 곧바로 벌어진 50%대 조정을 예고했을 뿐 아니라, 11월 고점 이후 2022년 말까지 이어진 하락장의 전조이기도 했다. 세 번의 사례 모두에서 다이버전스는 신호가 뜬 시점과 실제 전환 사이에 몇 주에서 몇 달의 시차를 남겼지만, 방향 자체는 세 번 다 맞았다.</p>
<p class="en">Four years later, in 2021, the same pattern repeated twice within a single year. In April, Bitcoin set a new high around $64,800–$65,000; after a correction, it went on to a fresh all-time high of $69,000 that November. Looking at price alone, November was clearly higher than April. But once again, the peak RSI traced in November was lower than the one in April — a double divergence in which price and momentum told different stories. That signal not only foreshadowed the roughly 50% correction that followed the April top, but also served as an early warning for the bear market that ran from the November top through the end of 2022. In all three cases, divergence left a gap of weeks to months between the signal and the actual turn — but the direction itself was right all three times.</p>
<p class="ja">4年後の2021年、同じパターンが1年の中で2度繰り返された。4月にビットコインは約6万4,800〜6万5,000ドルの新高値をつけ、その後調整を経て、11月には6万9千ドルの新たな史上最高値を記録した。価格だけを見れば11月は4月より明らかに高かったが、今回もRSIが描くモメンタムの高値は4月より11月の方が低かった——価格とモメンタムが異なることを語る二重のダイバージェンスだった。このシグナルは4月の高値後にすぐ起きた50%台の調整を予告しただけでなく、11月の高値後2022年末まで続いた下落相場の前兆でもあった。3つの事例すべてで、ダイバージェンスはシグナルが出た時点と実際の転換の間に数週間から数ヶ月の時差を残したが、方向自体は3度とも正しかった。</p>
<p class="es">Cuatro años después, en 2021, el mismo patrón se repitió dos veces dentro de un mismo año. En abril, Bitcoin marcó un nuevo máximo de alrededor de $64,800–$65,000; tras una corrección, llegó a un nuevo máximo histórico de $69,000 en noviembre. Mirando solo el precio, noviembre fue claramente más alto que abril. Pero, de nuevo, el pico que trazó el RSI en noviembre fue más bajo que el de abril — una doble divergencia en la que precio y momentum contaban historias distintas. Esa señal no solo anticipó la corrección de alrededor del 50% que siguió al techo de abril, sino que también sirvió de advertencia temprana para el mercado bajista que corrió desde el techo de noviembre hasta fines de 2022. En los tres casos, la divergencia dejó un desfase de semanas a meses entre la señal y el giro real — pero la dirección en sí acertó las tres veces.</p>
<p class="de">Vier Jahre später, 2021, wiederholte sich dasselbe Muster zweimal innerhalb eines Jahres. Im April markierte Bitcoin ein neues Hoch von rund 64.800 bis 65.000 Dollar; nach einer Korrektur erreichte es im November ein neues Allzeithoch von 69.000 Dollar. Betrachtet man nur den Preis, war November eindeutig höher als April. Doch auch diesmal war das Hoch, das der RSI im November zeichnete, niedriger als das im April — eine doppelte Divergenz, bei der Preis und Momentum unterschiedliche Geschichten erzählten. Dieses Signal kündigte nicht nur die rund 50-prozentige Korrektur an, die dem April-Hoch folgte, sondern diente auch als frühe Warnung für den Bärenmarkt, der vom November-Hoch bis Ende 2022 andauerte. In allen drei Fällen ließ die Divergenz eine Lücke von Wochen bis Monaten zwischen Signal und tatsächlicher Wende — doch die Richtung selbst stimmte alle drei Male.</p>

<h2 class="ko">임계값이 완전히 무너진 순간 — 추세장에서는 과매수가 정상이다</h2>
<h2 class="en">Where the Threshold Broke Down Completely — Overbought Is Normal in a Trend</h2>
<h2 class="ja">閾値が完全に崩れた瞬間——トレンド相場では買われすぎが正常になる</h2>
<h2 class="es">Donde el Umbral Se Derrumbó por Completo — la Sobrecompra Es Normal en una Tendencia</h2>
<h2 class="de">Wo der Schwellenwert Vollständig Versagte — Überkauft Ist Normal in Einem Trend</h2>

<p class="ko">반면 같은 RSI의 임계값 신호는 정반대의 성적표를 받았다. 2020년 말부터 2021년 11월까지 이어진 상승장에서, 비트코인은 1만 달러 안팎에서 시작해 6만 9천 달러까지 거의 열 배 가까이 상승했다. 그 과정에서 주간 RSI는 70을 훌쩍 넘는 수준에서 몇 달씩 머물렀다. "70을 넘으면 과매수, 곧 조정"이라는 교과서적 해석을 그대로 따라 매도한 투자자는, 이 상승장의 대부분 구간에서 시장 밖에 있었어야 했다. 2017년 11~12월의 랠리에서도 마찬가지였다 — RSI는 이미 과매수 구간에 진입한 뒤에도 가격이 2만 달러에 근접할 때까지 계속 그 상태를 유지했다.</p>
<p class="en">The same RSI's threshold signal, meanwhile, earned the opposite report card. During the bull run that ran from late 2020 through November 2021, Bitcoin climbed nearly tenfold, from around $10,000 to $69,000. Along the way, the weekly RSI sat well above 70 for months at a stretch. Anyone who followed the textbook interpretation — "above 70 means overbought, expect a pullback" — literally, and sold, would have had to sit out most of that rally. The same thing happened during the November-December 2017 run: RSI had already entered overbought territory and simply stayed there as price kept climbing toward $20,000.</p>
<p class="ja">一方、同じRSIの閾値シグナルはまったく逆の成績を残した。2020年末から2021年11月まで続いた上昇相場で、ビットコインは1万ドル前後から6万9千ドルまでほぼ10倍近く上昇した。その過程で、週足RSIは70をはるかに超える水準に何ヶ月も留まった。「70を超えたら買われすぎ、まもなく調整」という教科書的な解釈をそのまま守って売却した投資家は、この上昇相場のほとんどの区間で市場の外にいなければならなかった。2017年11〜12月のラリーでも同様だった——RSIはすでに買われすぎ圏に入った後も、価格が2万ドルに近づくまでその状態を維持し続けた。</p>
<p class="es">La señal de umbral del mismo RSI, en cambio, recibió una calificación opuesta. Durante el mercado alcista que corrió desde fines de 2020 hasta noviembre de 2021, Bitcoin subió casi diez veces, de unos $10,000 a $69,000. En el camino, el RSI semanal se mantuvo muy por encima de 70 durante meses seguidos. Quien siguió al pie de la letra la interpretación de manual — "por encima de 70 es sobrecompra, se espera una corrección" — y vendió, tuvo que quedarse fuera de la mayor parte de esa subida. Lo mismo ocurrió durante el rally de noviembre-diciembre de 2017: el RSI ya había entrado en territorio de sobrecompra y simplemente se mantuvo ahí mientras el precio seguía subiendo hacia los $20,000.</p>
<p class="de">Das Schwellenwertsignal desselben RSI erhielt hingegen ein gegenteiliges Zeugnis. Während des Bullenmarkts, der von Ende 2020 bis November 2021 lief, stieg Bitcoin um fast das Zehnfache, von rund 10.000 auf 69.000 Dollar. Dabei verharrte der wöchentliche RSI monatelang deutlich über 70. Wer die Lehrbuch-Interpretation — "über 70 bedeutet überkauft, eine Korrektur steht bevor" — wörtlich befolgte und verkaufte, musste den Großteil dieser Rallye von der Seitenlinie aus verpassen. Dasselbe geschah während der Rallye im November/Dezember 2017: Der RSI war bereits in überkauftes Terrain eingetreten und blieb dort einfach, während der Preis weiter auf 20.000 Dollar zusteuerte.</p>

<div class="ko">
<svg viewBox="0 0 700 260" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">RSI 70 임계값 신호 — 국면에 따라 정반대의 결과</text>
  <line x1="50" y1="220" x2="660" y2="220" stroke="#3f3f46"/>
  <rect x="120" y="90" width="180" height="130" rx="4" fill="#f87171"/>
  <text x="210" y="80" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle">추세장</text>
  <text x="210" y="238" fill="#a1a1aa" font-size="13" text-anchor="middle">2017년 11~12월 / 2020~2021년</text>
  <text x="210" y="145" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">매도 시</text>
  <text x="210" y="163" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">상승분 대부분 상실</text>
  <rect x="400" y="140" width="180" height="80" rx="4" fill="#4ade80"/>
  <text x="490" y="130" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle">평균회귀 국면</text>
  <text x="490" y="238" fill="#a1a1aa" font-size="13" text-anchor="middle">2018년 12월 저점 부근</text>
  <text x="490" y="175" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">3~6개월 후</text>
  <text x="490" y="193" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">신호 결국 적중</text>
</svg>
</div>
<div class="en es de">
<svg viewBox="0 0 700 260" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">The RSI-70 Threshold Signal — Opposite Outcomes by Regime</text>
  <line x1="50" y1="220" x2="660" y2="220" stroke="#3f3f46"/>
  <rect x="120" y="90" width="180" height="130" rx="4" fill="#f87171"/>
  <text x="210" y="80" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle">Trending Regime</text>
  <text x="210" y="238" fill="#a1a1aa" font-size="13" text-anchor="middle">Nov-Dec 2017 / 2020-2021</text>
  <text x="210" y="145" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">Selling Here</text>
  <text x="210" y="163" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">Forfeits Most of the Rally</text>
  <rect x="400" y="140" width="180" height="80" rx="4" fill="#4ade80"/>
  <text x="490" y="130" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle">Mean-Reverting Regime</text>
  <text x="490" y="238" fill="#a1a1aa" font-size="13" text-anchor="middle">Near the Dec 2018 Bottom</text>
  <text x="490" y="175" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">3-6 Months Later</text>
  <text x="490" y="193" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">Signal Eventually Right</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 260" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="14" font-weight="700" font-family="sans-serif">RSI70閾値シグナル——局面によって正反対の結果</text>
  <line x1="50" y1="220" x2="660" y2="220" stroke="#3f3f46"/>
  <rect x="120" y="90" width="180" height="130" rx="4" fill="#f87171"/>
  <text x="210" y="80" fill="#f87171" font-size="13" font-weight="700" text-anchor="middle">トレンド相場</text>
  <text x="210" y="238" fill="#a1a1aa" font-size="13" text-anchor="middle">2017年11〜12月 / 2020〜2021年</text>
  <text x="210" y="145" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">売却した場合</text>
  <text x="210" y="163" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">上昇分の大半を喪失</text>
  <rect x="400" y="140" width="180" height="80" rx="4" fill="#4ade80"/>
  <text x="490" y="130" fill="#4ade80" font-size="13" font-weight="700" text-anchor="middle">平均回帰局面</text>
  <text x="490" y="238" fill="#a1a1aa" font-size="13" text-anchor="middle">2018年12月安値付近</text>
  <text x="490" y="175" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">3〜6ヶ月後</text>
  <text x="490" y="193" fill="#111113" font-size="13" font-weight="700" text-anchor="middle">シグナルは結局的中</text>
</svg>
</div>

<p class="ko">이 실패는 우연이 아니라 임계값 신호가 전제로 삼는 조건 자체가 깨졌기 때문이다. 임계값 신호는 가격이 결국 평균으로 되돌아온다는 것을 전제로 하는데, 강한 추세장은 정의상 그 평균 회귀가 당분간 일어나지 않는 국면이다. 추세가 강할수록 RSI는 과매수·과매도 구간에 진입한 채로 오래 머무는 것이 오히려 정상적인 현상이 되며, 이 국면에서 임계값을 따르는 매매는 추세의 방향과 반대로 베팅하는 셈이 된다. 더 곤란한 점은, RSI 숫자 자체만 보고는 지금이 추세장인지 횡보장인지 구분할 방법이 없다는 것이다 — 그 구분을 이미 알고 있어야 임계값 신호를 신뢰할지 말지를 정할 수 있다는 점에서, 이 신호는 순환 논리에 가깝다.</p>
<p class="en">This wasn't bad luck — it happened because the very condition the threshold signal assumes had broken down. A threshold signal presumes price eventually reverts to its mean; a strong trend is, by definition, a regime where that mean reversion simply isn't happening yet. The stronger the trend, the more normal it becomes for RSI to sit in overbought or oversold territory for extended stretches, which means following the threshold in that regime amounts to betting against the direction of the trend itself. What makes this worse is that the RSI reading alone gives you no way to tell whether you're in a trending or a range-bound regime — you'd already need to know that distinction to decide whether to trust the threshold signal in the first place, which makes the whole thing close to circular.</p>
<p class="ja">この失敗は偶然ではなく、閾値シグナルが前提とする条件そのものが崩れていたからだ。閾値シグナルは価格が最終的に平均へ回帰することを前提とするが、強いトレンド相場とは、定義上その平均回帰が当面起きない局面だ。トレンドが強いほど、RSIが買われすぎ・売られすぎ圏に長く留まることの方がむしろ正常な現象になり、この局面で閾値に従う売買は、トレンドの方向に逆らって賭けることになる。さらに厄介なのは、RSIの数字だけを見ても、今がトレンド相場なのかレンジ相場なのかを区別する方法がないという点だ——その区別をすでに知っていて初めて閾値シグナルを信頼すべきかどうかを決められるという意味で、このシグナルは循環論法に近い。</p>
<p class="es">Esto no fue mala suerte — ocurrió porque la propia condición que asume la señal de umbral se había roto. Una señal de umbral presupone que el precio eventualmente revierte a su media; una tendencia fuerte es, por definición, un régimen en el que esa reversión a la media simplemente no está ocurriendo todavía. Cuanto más fuerte la tendencia, más normal se vuelve que el RSI permanezca en territorio de sobrecompra o sobreventa durante tramos prolongados, lo que significa que seguir el umbral en ese régimen equivale a apostar en contra de la dirección de la propia tendencia. Lo que empeora las cosas es que la lectura del RSI por sí sola no da ninguna manera de saber si se está en un régimen de tendencia o de rango — habría que conocer ya esa distinción para decidir si confiar en la señal de umbral, lo cual la vuelve casi circular.</p>
<p class="de">Das war kein Pech — es geschah, weil genau die Voraussetzung, die das Schwellenwertsignal annimmt, nicht mehr galt. Ein Schwellenwertsignal setzt voraus, dass der Preis letztlich zu seinem Mittelwert zurückkehrt; ein starker Trend ist per Definition ein Regime, in dem diese Rückkehr zum Mittelwert vorerst schlicht nicht stattfindet. Je stärker der Trend, desto normaler wird es, dass der RSI über längere Strecken in überkauftem oder überverkauftem Terrain verharrt — was bedeutet, dass das Befolgen des Schwellenwerts in diesem Regime einer Wette gegen die Richtung des Trends selbst gleichkommt. Erschwerend kommt hinzu, dass der RSI-Wert allein keine Möglichkeit bietet, zu erkennen, ob man sich in einem trendenden oder einem Seitwärtsregime befindet — man müsste diese Unterscheidung bereits kennen, um zu entscheiden, ob man dem Schwellenwertsignal überhaupt vertrauen sollte, was das Ganze fast zirkulär macht.</p>

<h2 class="ko">다이버전스도 완벽하지 않다 — 실전에서 두 신호를 나눠 쓰는 법</h2>
<h2 class="en">Why Divergence Isn't Foolproof Either — Splitting the Two Signals in Practice</h2>
<h2 class="ja">ダイバージェンスも万能ではない——実践で二つのシグナルを使い分ける方法</h2>
<h2 class="es">Por Qué la Divergencia Tampoco Es Infalible — Separando las Dos Señales en la Práctica</h2>
<h2 class="de">Warum Auch Divergenz Nicht Unfehlbar Ist — Die Zwei Signale in der Praxis Trennen</h2>

<p class="ko">그렇다고 다이버전스가 만능인 것도 아니다. 다이버전스는 어느 두 고점(혹은 저점)을 비교 대상으로 삼을지가 사람마다 다르게 그려질 수 있다는 점에서 임계값보다 훨씬 더 주관적이다. 실제로 2022년 하락장 내내 일간·4시간봉 등 짧은 시간대에서는 여러 차례의 강세 다이버전스가 나타났다가, 가격이 다시 신저가를 갱신하며 무산되기를 반복했다. 11월 FTX 붕괴와 함께 찾아온 최종 바닥에서야 그중 하나가 실제 반전으로 이어졌을 뿐, 그 전까지의 다이버전스들은 모두 이른 경보로 그쳤다. 다이버전스가 방향을 맞힌다고 해서 타이밍까지 정확하다는 뜻은 아니라는 걸 이 반복된 실패가 보여준다.</p>
<p class="en">None of this makes divergence a silver bullet. It's considerably more subjective than a threshold, since which two peaks (or troughs) to compare is a judgment call that different people can draw differently. In practice, throughout the 2022 bear market, several bullish divergences appeared on shorter timeframes — daily, four-hour — only to be invalidated as price kept printing new lows. Only one of them, arriving with the final capitulation around the November FTX collapse, actually turned into a real reversal; every divergence before it was just an early false alarm. That repeated failure shows that divergence getting the direction right doesn't mean it gets the timing right too.</p>
<p class="ja">だからといってダイバージェンスが万能というわけでもない。ダイバージェンスは、どの2つの高値(または安値)を比較対象にするかが人によって異なりうるという点で、閾値よりもはるかに主観的だ。実際、2022年の下落相場を通じて、日足・4時間足など短い時間軸では複数回の強気ダイバージェンスが現れては、価格が再び新安値を更新して無効化されることを繰り返した。11月のFTX破綻とともに訪れた最終的な底値でようやくその一つが実際の反転につながっただけで、それ以前のダイバージェンスはすべて早すぎる警報に終わった。ダイバージェンスが方向を的中させることは、タイミングまで正確だということを意味しないと、この繰り返された失敗が示している。</p>
<p class="es">Nada de esto convierte a la divergencia en una solución mágica. Es considerablemente más subjetiva que un umbral, ya que decidir qué dos picos (o valles) comparar es un juicio que distintas personas pueden trazar de forma distinta. En la práctica, a lo largo del mercado bajista de 2022, aparecieron varias divergencias alcistas en marcos temporales más cortos — diario, de cuatro horas — solo para ser invalidadas cuando el precio seguía marcando nuevos mínimos. Solo una de ellas, la que llegó con la capitulación final en torno al colapso de FTX en noviembre, se convirtió realmente en una reversión; todas las anteriores fueron solo falsas alarmas tempranas. Ese fracaso repetido muestra que acertar la dirección con la divergencia no significa acertar también el momento.</p>
<p class="de">All das macht Divergenz nicht zu einem Allheilmittel. Sie ist deutlich subjektiver als ein Schwellenwert, da die Entscheidung, welche zwei Hochs (oder Tiefs) man vergleicht, eine Ermessensfrage ist, die unterschiedliche Menschen unterschiedlich treffen können. In der Praxis traten während des gesamten Bärenmarkts 2022 auf kürzeren Zeitrahmen — Tages-, Vier-Stunden-Charts — mehrfach bullische Divergenzen auf, nur um wieder entkräftet zu werden, als der Preis erneut neue Tiefs markierte. Erst eine davon, die mit der finalen Kapitulation rund um den FTX-Zusammenbruch im November eintraf, führte tatsächlich zu einer echten Umkehr; alle vorherigen waren nur verfrühte Fehlalarme. Dieses wiederholte Scheitern zeigt: Dass Divergenz die Richtung richtig erfasst, heißt nicht, dass sie auch das Timing richtig trifft.</p>

<p class="ko">그래서 실전에서 중요한 건 RSI 숫자 자체가 아니라, 그 숫자를 읽기 전에 먼저 지금이 어떤 국면인지를 판단하는 순서다. 추세가 뚜렷하다면 임계값 교차는 무시하고 다이버전스만 참고하되, 그 다이버전스조차 <a href="/blog/golden-cross-death-cross-lag.php">추세선 붕괴나 저점 갱신 같은 가격 구조의 확인</a>과 함께 봐야 한다. 반대로 방향성 없는 횡보 구간이라면 임계값도 여전히 쓸모가 있다. <a href="/blog/macd-signal-already-late.php">MACD의 크로스오버와 다이버전스가 서로 다른 속도로 신호를 낸다</a>는 것과 마찬가지로, RSI 역시 하나의 숫자 뒤에 서로 다른 두 개의 규칙이 숨어 있다는 걸 아는 사람에게만 계속 쓸모가 있다. <a href="/blog/conflicting-indicators.php">여러 지표가 서로 다른 말을 할 때</a>도 결국 같은 원칙이 적용된다 — 문제는 지표 사이의 충돌만이 아니라, 지표 하나 안에서도 서로 다른 전제를 가진 신호들이 충돌할 수 있다는 사실이다.</p>
<p class="en">What matters in practice, then, isn't the RSI number itself, but the sequencing — deciding what regime you're in before you read the number. If the trend is clear, ignore threshold crossovers and lean on divergence instead, but even divergence should be checked against <a href="/blog/golden-cross-death-cross-lag.php">confirmation from price structure, like a broken trendline or a fresh low</a>. If the market is range-bound with no clear direction, the threshold still has something to offer. Much like <a href="/blog/macd-signal-already-late.php">MACD's crossover and divergence signals fire on different timelines</a>, RSI stays useful only to someone who knows that two rules with different assumptions are hiding behind that one number. The same principle applies <a href="/blog/conflicting-indicators.php">when multiple indicators send conflicting signals</a> — the real problem isn't just conflict between indicators, it's that signals with different underlying assumptions can conflict within a single indicator too.</p>
<p class="ja">したがって実践で重要なのは、RSIの数字そのものではなく、その数字を読む前にまず今がどの局面かを判断する順序だ。トレンドが明確なら閾値の交差は無視し、ダイバージェンスだけを参考にすべきだが、そのダイバージェンスでさえ<a href="/blog/golden-cross-death-cross-lag.php">トレンドラインの崩壊や安値更新といった価格構造の確認</a>と併せて見る必要がある。逆に方向性のないレンジ局面なら、閾値もまだ役に立つ。<a href="/blog/macd-signal-already-late.php">MACDのクロスオーバーとダイバージェンスがそれぞれ異なる速度でシグナルを出す</a>のと同様に、RSIもまた、一つの数字の裏に前提の異なる二つのルールが隠れていることを知る人にだけ使い続けられる。<a href="/blog/conflicting-indicators.php">複数の指標が食い違うシグナルを出す時</a>にも結局同じ原則が当てはまる——問題は指標同士の衝突だけでなく、一つの指標の中でも前提の異なるシグナル同士が衝突しうるということだ。</p>
<p class="es">Lo que importa en la práctica, entonces, no es el número del RSI en sí, sino el orden — decidir en qué régimen se está antes de leer el número. Si la tendencia es clara, hay que ignorar los cruces de umbral y apoyarse en la divergencia, pero incluso la divergencia debe contrastarse con <a href="/blog/golden-cross-death-cross-lag.php">una confirmación de la estructura del precio, como una línea de tendencia rota o un nuevo mínimo</a>. Si el mercado está lateral, sin dirección clara, el umbral todavía tiene algo que ofrecer. De forma parecida a como <a href="/blog/macd-signal-already-late.php">el cruce y la divergencia del MACD se disparan en calendarios distintos</a>, el RSI solo sigue siendo útil para quien sabe que detrás de ese único número se esconden dos reglas con supuestos distintos. El mismo principio aplica <a href="/blog/conflicting-indicators.php">cuando varios indicadores envían señales contradictorias</a> — el problema real no es solo el conflicto entre indicadores, sino que señales con supuestos distintos pueden entrar en conflicto incluso dentro de un mismo indicador.</p>
<p class="de">Was in der Praxis zählt, ist daher nicht die RSI-Zahl selbst, sondern die Reihenfolge — zuerst zu entscheiden, in welchem Regime man sich befindet, bevor man die Zahl liest. Ist der Trend eindeutig, sollte man Schwellenwert-Kreuzungen ignorieren und sich stattdessen auf Divergenz stützen, doch selbst diese Divergenz sollte gegen <a href="/blog/golden-cross-death-cross-lag.php">eine Bestätigung durch die Preisstruktur, etwa eine gebrochene Trendlinie oder ein neues Tief</a>, abgeglichen werden. Befindet sich der Markt dagegen richtungslos in einer Seitwärtsphase, hat der Schwellenwert immer noch etwas zu bieten. Ganz ähnlich wie <a href="/blog/macd-signal-already-late.php">Crossover und Divergenz des MACD auf unterschiedlichen Zeitplänen auslösen</a>, bleibt auch der RSI nur für jene nützlich, die wissen, dass sich hinter dieser einen Zahl zwei Regeln mit unterschiedlichen Annahmen verbergen. Dasselbe Prinzip gilt, <a href="/blog/conflicting-indicators.php">wenn mehrere Indikatoren widersprüchliche Signale senden</a> — das eigentliche Problem ist nicht nur der Konflikt zwischen Indikatoren, sondern dass Signale mit unterschiedlichen zugrunde liegenden Annahmen auch innerhalb eines einzigen Indikators kollidieren können.</p>

<div class="box ko">💡 <strong>제 생각:</strong> RSI가 "틀렸다"는 불평은 대개 임계값 신호를 다이버전스 신호처럼 쓴 실수에서 나온다. 이 지표를 볼 때 먼저 던져야 할 질문은 "지금 몇인가"가 아니라 "지금 이 시장은 추세장인가, 횡보장인가" — 그 답에 따라 같은 숫자가 완전히 다른 것을 의미한다.</div>
<div class="box en">💡 <strong>My take:</strong> The complaint that RSI "got it wrong" usually comes from using a threshold signal as if it were a divergence signal. The first question to ask when looking at this indicator isn't "what's the number right now," but "is this market trending or range-bound right now" — the same number means something completely different depending on the answer.</div>
<div class="box ja">💡 <strong>私の考え:</strong> RSIが「間違っていた」という不満は、たいてい閾値シグナルをダイバージェンスシグナルのように使ってしまった結果だ。この指標を見るときにまず投げかけるべき問いは「今いくつか」ではなく、「今この市場はトレンド相場かレンジ相場か」——その答えによって、同じ数字がまったく違う意味を持つ。</div>
<div class="box es">💡 <strong>Mi opinión:</strong> La queja de que el RSI "se equivocó" suele venir de usar una señal de umbral como si fuera una señal de divergencia. La primera pregunta que hay que hacerse al mirar este indicador no es "cuál es el número ahora", sino "¿este mercado está en tendencia o en rango ahora?" — según la respuesta, el mismo número significa algo completamente distinto.</div>
<div class="box de">💡 <strong>Meine Meinung:</strong> Die Klage, der RSI habe "sich geirrt", entsteht meist daraus, ein Schwellenwertsignal so zu benutzen, als wäre es ein Divergenzsignal. Die erste Frage, die man sich bei diesem Indikator stellen sollte, lautet nicht "wie hoch ist die Zahl gerade", sondern "trendet dieser Markt gerade, oder bewegt er sich seitwärts" — je nach Antwort bedeutet dieselbe Zahl etwas völlig anderes.</div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: J. 웰레스 와일더 Jr., 『New Concepts in Technical Trading Systems』(1978); 2018년 12월 비트코인 주간 RSI 25.6 및 과거 유사 사례 분석(Spoted Crypto); 2017년 11~12월 및 2021년 4월·11월 비트코인 RSI 약세 다이버전스 분석(Cryptopotato, Stopsaving); 2020~2021년 상승장 RSI 임계값 신호 관련 분석(Newhedge 외 다수 트레이딩 리서치).</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: J. Welles Wilder Jr., New Concepts in Technical Trading Systems (1978); analysis of Bitcoin's December 2018 weekly RSI of 25.6 and prior comparable cases (Spoted Crypto); analyses of Bitcoin's bearish RSI divergences in November-December 2017 and April/November 2021 (Cryptopotato, Stopsaving); analyses of RSI threshold signals during the 2020-2021 bull run (Newhedge and other trading research).</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: J・ウェルズ・ワイルダーJr.、『New Concepts in Technical Trading Systems』(1978年);2018年12月のビットコイン週足RSI25.6および過去の類似事例分析(Spoted Crypto);2017年11〜12月、2021年4月・11月のビットコインRSI弱気ダイバージェンス分析(Cryptopotato、Stopsaving);2020〜2021年の上昇相場におけるRSI閾値シグナルに関する分析(Newhedgeほか複数のトレーディングリサーチ)。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: J. Welles Wilder Jr., New Concepts in Technical Trading Systems (1978); análisis del RSI semanal de Bitcoin de 25.6 en diciembre de 2018 y casos comparables anteriores (Spoted Crypto); análisis de las divergencias bajistas del RSI de Bitcoin en noviembre-diciembre de 2017 y abril/noviembre de 2021 (Cryptopotato, Stopsaving); análisis de las señales de umbral del RSI durante el mercado alcista de 2020-2021 (Newhedge y otras investigaciones de trading).</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: J. Welles Wilder Jr., New Concepts in Technical Trading Systems (1978); Analyse des wöchentlichen Bitcoin-RSI von 25,6 im Dezember 2018 und früherer vergleichbarer Fälle (Spoted Crypto); Analysen der bärischen Bitcoin-RSI-Divergenzen im November/Dezember 2017 sowie April/November 2021 (Cryptopotato, Stopsaving); Analysen der RSI-Schwellenwertsignale während des Bullenmarkts 2020-2021 (Newhedge und weitere Trading-Recherchen).</p>
<?php require __DIR__.'/_footer.php'; ?>
