<?php $slug = 'russia-crypto-mining-ban-moscow-regions'; require __DIR__.'/_header.php'; ?>

  <p class="ko">러시아 에너지부가 수도 모스크바와 모스크바주(州), 쿠르스크주 일부 지역에서 암호화폐 채굴을 2026년 7월 1일부터 2032년 12월 31일까지 전면 금지하는 정부 결의안 초안을 마련했다고 러시아 국영통신 타스(TASS)와 인테르팍스(Interfax)가 보도했다. 채굴풀 참여까지 포함하는 이 금지안은 전력망 부담을 줄이기 위한 조치로, 에너지부는 해당 지역에 65개 데이터센터가 총 734메가와트(MW)를 소비하며 이 가운데 모스크바주에만 19개 센터가 233MW를 쓰고 있다고 밝혔다. 러시아는 2024년 채굴을 합법화한 지 채 2년도 되지 않아, 전력이 부족한 지역부터 다시 빗장을 걸고 있다.</p>
  <p class="en">Russia's Energy Ministry has drafted a government resolution to ban cryptocurrency mining outright in the capital Moscow, the Moscow Region and parts of the Kursk Region from July 1, 2026 through December 31, 2032, the state news agencies TASS and Interfax reported. The ban, which extends even to participation in mining pools, is a measure to relieve strain on the power grid; the ministry said 65 data centers in the affected areas consume a combined 734 megawatts (MW), with 19 centers in the Moscow Region alone drawing 233 MW. Less than two years after legalizing mining in 2024, Russia is bolting the door again, starting with its power-short regions.</p>
  <p class="ja">ロシア・エネルギー省が、首都モスクワとモスクワ州、クルスク州の一部地域で暗号資産のマイニングを2026年7月1日から2032年12月31日まで全面禁止する政府決議案の草案をまとめたと、国営通信タス(TASS)とインテルファクス(Interfax)が報じた。マイニングプールへの参加まで含むこの禁止案は電力網の負担を軽減するための措置で、エネルギー省は当該地域に65のデータセンターが計734メガワット(MW)を消費し、うちモスクワ州だけで19センターが233MWを使っていると明らかにした。ロシアは2024年にマイニングを合法化してから2年も経たないうちに、電力の足りない地域から再び門を閉ざしつつある。</p>
  <p class="es">El Ministerio de Energía de Rusia ha redactado una resolución gubernamental para prohibir por completo la minería de criptomonedas en la capital, Moscú, la Región de Moscú y partes de la Región de Kursk desde el 1 de julio de 2026 hasta el 31 de diciembre de 2032, informaron las agencias estatales TASS e Interfax. La prohibición, que se extiende incluso a la participación en pools de minería, es una medida para aliviar la presión sobre la red eléctrica; el ministerio dijo que 65 centros de datos en las zonas afectadas consumen en conjunto 734 megavatios (MW), con 19 centros solo en la Región de Moscú que absorben 233 MW. Menos de dos años después de legalizar la minería en 2024, Rusia vuelve a echar el cerrojo, empezando por sus regiones con escasez de energía.</p>
  <p class="de">Russlands Energieministerium hat einen Regierungsbeschluss entworfen, der das Krypto-Mining in der Hauptstadt Moskau, der Region Moskau und Teilen der Region Kursk vom 1. Juli 2026 bis zum 31. Dezember 2032 vollständig verbietet, wie die staatlichen Nachrichtenagenturen TASS und Interfax berichteten. Das Verbot, das sich sogar auf die Teilnahme an Mining-Pools erstreckt, ist eine Maßnahme zur Entlastung des Stromnetzes; das Ministerium erklärte, 65 Rechenzentren in den betroffenen Gebieten verbrauchten zusammen 734 Megawatt (MW), wobei allein 19 Zentren in der Region Moskau 233 MW beziehen. Weniger als zwei Jahre nach der Legalisierung des Minings 2024 verriegelt Russland die Tür wieder — beginnend bei seinen strommangelnden Regionen.</p>
  <p class="fr">Le ministère russe de l'Énergie a rédigé un projet de résolution gouvernementale visant à interdire purement et simplement le minage de cryptomonnaies dans la capitale Moscou, la région de Moscou et certaines parties de la région de Koursk, du 1er juillet 2026 au 31 décembre 2032, ont rapporté les agences de presse d'État TASS et Interfax. L'interdiction, qui s'étend même à la participation à des pools de minage, est une mesure destinée à soulager le réseau électrique ; le ministère a indiqué que 65 centres de données dans les zones concernées consomment au total 734 mégawatts (MW), dont 19 centres dans la seule région de Moscou qui absorbent 233 MW. Moins de deux ans après avoir légalisé le minage en 2024, la Russie reverrouille la porte, en commençant par ses régions en déficit d'électricité.</p>
  <p class="pt">O Ministério da Energia da Rússia elaborou um projeto de resolução governamental para proibir totalmente a mineração de criptomoedas na capital Moscou, na Região de Moscou e em partes da Região de Kursk, de 1º de julho de 2026 a 31 de dezembro de 2032, informaram as agências estatais TASS e Interfax. A proibição, que se estende até à participação em pools de mineração, é uma medida para aliviar a pressão sobre a rede elétrica; o ministério disse que 65 centros de dados nas áreas afetadas consomem, em conjunto, 734 megawatts (MW), com 19 centros somente na Região de Moscou a consumir 233 MW. Menos de dois anos depois de legalizar a mineração em 2024, a Rússia volta a fechar a porta, começando pelas suas regiões com escassez de energia.</p>
  <p class="tr">Rusya Enerji Bakanlığı, başkent Moskova, Moskova Bölgesi ve Kursk Bölgesi'nin bazı kısımlarında kripto para madenciliğini 1 Temmuz 2026'dan 31 Aralık 2032'ye kadar tamamen yasaklayan bir hükümet kararı taslağı hazırladı; bunu devlet haber ajansları TASS ve Interfax bildirdi. Madencilik havuzlarına katılımı bile kapsayan yasak, elektrik şebekesi üzerindeki yükü hafifletmeye yönelik bir önlem; bakanlık, etkilenen bölgelerdeki 65 veri merkezinin toplam 734 megavat (MW) tükettiğini, bunların 19'unun yalnızca Moskova Bölgesi'nde bulunup 233 MW çektiğini açıkladı. Madenciliğin 2024'te yasallaştırılmasının üzerinden iki yıl bile geçmeden Rusya, elektrik açığı çeken bölgelerden başlayarak kapıyı yeniden kilitliyor.</p>
  <p class="vi">Bộ Năng lượng Nga đã soạn thảo một nghị quyết của chính phủ nhằm cấm hoàn toàn việc khai thác tiền điện tử tại thủ đô Moskva, Vùng Moskva và một phần Vùng Kursk, từ ngày 1 tháng 7 năm 2026 đến ngày 31 tháng 12 năm 2032, theo hãng thông tấn nhà nước TASS và Interfax. Lệnh cấm, vốn mở rộng cả sang việc tham gia các nhóm khai thác (mining pool), là biện pháp nhằm giảm áp lực lên lưới điện; bộ này cho biết 65 trung tâm dữ liệu tại các khu vực bị ảnh hưởng tiêu thụ tổng cộng 734 megawatt (MW), trong đó riêng 19 trung tâm tại Vùng Moskva đã tiêu thụ 233 MW. Chưa đầy hai năm sau khi hợp pháp hóa hoạt động khai thác vào năm 2024, Nga lại đóng cửa, bắt đầu từ những khu vực thiếu điện.</p>

  <h2 class="ko">전력망을 지키기 위한 6년 반의 금지</h2>
  <h2 class="en">A six-and-a-half-year ban to protect the grid</h2>
  <h2 class="ja">電力網を守るための6年半の禁止</h2>
  <h2 class="es">Una prohibición de seis años y medio para proteger la red</h2>
  <h2 class="de">Ein sechseinhalbjähriges Verbot zum Schutz des Netzes</h2>
  <h2 class="fr">Une interdiction de six ans et demi pour protéger le réseau</h2>
  <h2 class="pt">Uma proibição de seis anos e meio para proteger a rede</h2>
  <h2 class="tr">Şebekeyi korumak için altı buçuk yıllık yasak</h2>
  <h2 class="vi">Lệnh cấm sáu năm rưỡi để bảo vệ lưới điện</h2>
  <p class="ko">이번 초안이 겨냥하는 대상은 명확하다. 금지 구역에는 모스크바시와 모스크바주 전역, 그리고 쿠르스크주의 벨로프스키·볼셰솔다트스키·글루시콥스키·코레넵스키·리곱스키·릴스키·수잔스키·호무톱스키 지구와 리곱시 등이 포함된다. 에너지부는 연중 상시 금지가 없으면 전력 소모가 큰 채굴 설비가 계속 전력망에 연결돼 에너지 부족 위험을 키운다고 설명했다. 채굴이 문제가 되는 이유는 그 부하의 성격에 있다. 비트코인 채굴기는 하루 24시간, 계절과 무관하게 거의 일정한 최대 출력으로 전기를 끌어다 쓴다. 냉난방처럼 수요가 시간대에 따라 오르내리는 것이 아니라, 전력망 입장에서는 '내려가지 않는 바닥 부하'가 통째로 추가되는 셈이다.</p>
  <p class="en">The draft's targets are clear. The banned zone includes the city of Moscow, the entire Moscow Region and, in the Kursk Region, the Belovsky, Bolshesoldatsky, Glushkovsky, Korenevsky, Lgovsky, Rylsky, Sudzhansky and Khomutovsky districts as well as the city of Lgov. The ministry explained that without a year-round ban, power-hungry mining facilities remain connected to the grid and heighten the risk of energy shortfalls. The reason mining is a problem lies in the nature of its load. Bitcoin miners draw electricity at a nearly constant peak, 24 hours a day, regardless of season. Unlike heating or cooling, whose demand rises and falls with the hour, from the grid's standpoint an entire block of "base load that never comes down" is added at once.</p>
  <p class="ja">今回の草案が狙う対象は明確だ。禁止区域にはモスクワ市とモスクワ州全域、そしてクルスク州のベロフスキー・ボリシェソルダツキー・グルシコフスキー・コレネフスキー・リゴフスキー・ルィリスキー・スジャンスキー・ホムトフスキー地区およびリゴフ市などが含まれる。エネルギー省は、通年の常時禁止がなければ電力消費の大きいマイニング設備が電力網に接続され続け、エネルギー不足のリスクを高めると説明した。マイニングが問題になる理由はその負荷の性質にある。ビットコインのマイニング機は一日24時間、季節に関係なくほぼ一定の最大出力で電気を引く。冷暖房のように需要が時間帯で上下するのではなく、電力網から見れば「下がらないベース負荷」がまるごと追加されるのに等しい。</p>
  <p class="es">Los objetivos del borrador son claros. La zona prohibida incluye la ciudad de Moscú, toda la Región de Moscú y, en la Región de Kursk, los distritos de Belovsky, Bolshesoldatsky, Glushkovsky, Korenevsky, Lgovsky, Rylsky, Sudzhansky y Khomutovsky, así como la ciudad de Lgov. El ministerio explicó que sin una prohibición durante todo el año, las instalaciones de minería, ávidas de energía, permanecen conectadas a la red y elevan el riesgo de déficits energéticos. La razón por la que la minería es un problema reside en la naturaleza de su carga. Los mineros de bitcoin consumen electricidad a un pico casi constante, 24 horas al día, sin importar la estación. A diferencia de la calefacción o el aire acondicionado, cuya demanda sube y baja con la hora, desde el punto de vista de la red se añade de golpe todo un bloque de "carga base que nunca baja".</p>
  <p class="de">Die Ziele des Entwurfs sind klar. Die Verbotszone umfasst die Stadt Moskau, die gesamte Region Moskau und in der Region Kursk die Bezirke Belowski, Bolschesoldatski, Gluschkowski, Korenewski, Lgowski, Rylski, Sudschanski und Chomutowski sowie die Stadt Lgow. Das Ministerium erklärte, ohne ein ganzjähriges Verbot blieben energiehungrige Mining-Anlagen am Netz und erhöhten das Risiko von Energieengpässen. Der Grund, warum Mining ein Problem ist, liegt in der Natur seiner Last. Bitcoin-Miner beziehen Strom rund um die Uhr mit nahezu konstanter Spitzenleistung, unabhängig von der Jahreszeit. Anders als Heizung oder Klimaanlage, deren Nachfrage mit der Tageszeit steigt und fällt, wird aus Sicht des Netzes ein ganzer Block „Grundlast, die nie sinkt" auf einmal hinzugefügt.</p>
  <p class="fr">Les cibles du projet sont claires. La zone interdite comprend la ville de Moscou, l'ensemble de la région de Moscou et, dans la région de Koursk, les districts de Belovski, Bolchesoldatski, Glouchkovski, Korenevski, Lgovski, Rylski, Soudjanski et Khomoutovski, ainsi que la ville de Lgov. Le ministère a expliqué que, sans interdiction valable toute l'année, les installations de minage gourmandes en énergie restent connectées au réseau et accroissent le risque de pénuries énergétiques. La raison pour laquelle le minage pose problème tient à la nature de sa charge. Les mineurs de bitcoin consomment de l'électricité à un pic quasi constant, 24 heures sur 24, quelle que soit la saison. Contrairement au chauffage ou à la climatisation, dont la demande varie selon l'heure, du point de vue du réseau, c'est tout un bloc de « charge de base qui ne redescend jamais » qui s'ajoute d'un coup.</p>
  <p class="pt">Os alvos do projeto são claros. A zona proibida inclui a cidade de Moscou, toda a Região de Moscou e, na Região de Kursk, os distritos de Belovsky, Bolshesoldatsky, Glushkovsky, Korenevsky, Lgovsky, Rylsky, Sudzhansky e Khomutovsky, bem como a cidade de Lgov. O ministério explicou que, sem uma proibição válida durante todo o ano, as instalações de mineração, ávidas de energia, permanecem ligadas à rede e aumentam o risco de escassez energética. A razão pela qual a mineração é um problema está na natureza da sua carga. Os mineradores de bitcoin consomem eletricidade num pico quase constante, 24 horas por dia, independentemente da estação. Ao contrário do aquecimento ou do ar condicionado, cuja procura sobe e desce conforme a hora, do ponto de vista da rede é como se todo um bloco de “carga de base que nunca desce” fosse adicionado de uma só vez.</p>
  <p class="tr">Taslağın hedefleri açık. Yasaklı bölge; Moskova şehrini, Moskova Bölgesi'nin tamamını ve Kursk Bölgesi'nde Belovski, Bolşesoldatski, Gluşkovski, Korenevski, Lgovski, Rılski, Sudjanski ve Homutovski ilçeleri ile Lgov şehrini kapsıyor. Bakanlık, yıl boyu geçerli bir yasak olmadan, elektrik açlığı çeken madencilik tesislerinin şebekeye bağlı kalmaya devam edip enerji açığı riskini artırdığını açıkladı. Madenciliğin sorun olmasının nedeni yükünün doğasında yatıyor. Bitcoin madencileri, mevsimden bağımsız olarak günün 24 saati neredeyse sabit bir tepe değerde elektrik çekiyor. Talebi saate göre inip çıkan ısıtma veya soğutmanın aksine, şebeke açısından bakıldığında bir kerede eklenen "hiç düşmeyen taban yük" bloğu söz konusu.</p>
  <p class="vi">Mục tiêu của dự thảo rất rõ ràng. Khu vực bị cấm bao gồm thành phố Moskva, toàn bộ Vùng Moskva và tại Vùng Kursk là các huyện Belovsky, Bolshesoldatsky, Glushkovsky, Korenevsky, Lgovsky, Rylsky, Sudzhansky, Khomutovsky cùng thành phố Lgov. Bộ này giải thích rằng nếu không có lệnh cấm quanh năm, các cơ sở khai thác tiêu tốn nhiều điện sẽ vẫn kết nối với lưới điện và làm tăng nguy cơ thiếu hụt năng lượng. Lý do khiến khai thác trở thành vấn đề nằm ở bản chất tải điện của nó. Máy đào bitcoin tiêu thụ điện ở mức đỉnh gần như không đổi, 24 giờ một ngày, bất kể mùa nào. Khác với sưởi ấm hay làm mát vốn có nhu cầu tăng giảm theo giờ, xét từ góc độ lưới điện thì cả một khối "tải nền không bao giờ giảm" bị cộng thêm cùng một lúc.</p>
  <p class="ko">이번 조치는 갑작스러운 것이 아니라 러시아가 지난 1년간 넓혀온 규제의 연장선에 있다. 정부는 이미 2026년 4월부터 부랴티야공화국과 자바이칼스키 변경주에서 연중 채굴 금지를 시행했고, 다게스탄·체첸·잉구셰티야·북오세티야 등 북캅카스 지역과 러시아 통제하 우크라이나 일부 지역에서는 2031년까지 채굴을 금지해 왔다. 여기에 모스크바권이 더해지면서, 계절 제한까지 포함해 채굴이 제약되는 러시아 지역은 10곳을 훌쩍 넘게 됐다. 겨울철 난방 수요가 폭증하는 시베리아 일부 지역에서 시작된 규제가, 이제 수도권이라는 정치·경제 중심부로까지 확대된 것이다.</p>
  <p class="en">This is not a sudden move but an extension of restrictions Russia has been widening over the past year. The government already imposed year-round mining bans in the Republic of Buryatia and Zabaykalsky Krai from April 2026, and has banned mining through 2031 in North Caucasus regions such as Dagestan, Chechnya, Ingushetia and North Ossetia, as well as in parts of Russian-controlled Ukraine. With the Moscow area now added, the number of Russian regions where mining is constrained — counting seasonal limits — comfortably exceeds ten. Restrictions that began in parts of Siberia, where winter heating demand spikes, have now reached the political and economic heart of the country: the capital region.</p>
  <p class="ja">今回の措置は突然のものではなく、ロシアがこの1年で広げてきた規制の延長線上にある。政府はすでに2026年4月からブリヤート共和国とザバイカリスキー地方で通年のマイニング禁止を施行し、ダゲスタン・チェチェン・イングーシ・北オセチアなど北カフカス地域とロシア統制下ウクライナの一部地域では2031年までマイニングを禁止してきた。ここにモスクワ圏が加わることで、季節制限まで含めてマイニングが制約されるロシアの地域は10か所を優に超えることになる。冬季の暖房需要が急増するシベリアの一部地域で始まった規制が、いまや首都圏という政治・経済の中枢にまで拡大したのだ。</p>
  <p class="es">No es un movimiento repentino, sino una extensión de las restricciones que Rusia ha venido ampliando durante el último año. El gobierno ya impuso prohibiciones de minería durante todo el año en la República de Buriatia y el Krai de Zabaikalie desde abril de 2026, y ha prohibido la minería hasta 2031 en regiones del Cáucaso Norte como Daguestán, Chechenia, Ingusetia y Osetia del Norte, así como en partes de la Ucrania controlada por Rusia. Con la incorporación ahora del área de Moscú, el número de regiones rusas donde la minería está restringida —contando los límites estacionales— supera con holgura las diez. Las restricciones que comenzaron en partes de Siberia, donde la demanda de calefacción invernal se dispara, han alcanzado ya el corazón político y económico del país: la región de la capital.</p>
  <p class="de">Dies ist kein plötzlicher Schritt, sondern eine Fortführung der Beschränkungen, die Russland im vergangenen Jahr ausgeweitet hat. Die Regierung verhängte bereits ab April 2026 ganzjährige Mining-Verbote in der Republik Burjatien und der Region Transbaikalien und hat das Mining bis 2031 in nordkaukasischen Regionen wie Dagestan, Tschetschenien, Inguschetien und Nordossetien sowie in Teilen der von Russland kontrollierten Ukraine verboten. Mit dem nun hinzugekommenen Moskauer Raum übersteigt die Zahl der russischen Regionen, in denen Mining eingeschränkt ist — die saisonalen Grenzen mitgezählt — deutlich zehn. Beschränkungen, die in Teilen Sibiriens begannen, wo die winterliche Heiznachfrage in die Höhe schießt, haben nun das politische und wirtschaftliche Herz des Landes erreicht: die Hauptstadtregion.</p>
  <p class="fr">Il ne s'agit pas d'une décision soudaine, mais du prolongement de restrictions que la Russie a élargies au cours de l'année écoulée. Le gouvernement avait déjà imposé des interdictions de minage valables toute l'année dans la République de Bouriatie et le kraï de Transbaïkalie à partir d'avril 2026, et interdit le minage jusqu'en 2031 dans des régions du Caucase du Nord telles que le Daghestan, la Tchétchénie, l'Ingouchie et l'Ossétie du Nord, ainsi que dans des parties de l'Ukraine sous contrôle russe. Avec l'ajout désormais de la région moscovite, le nombre de régions russes où le minage est restreint — limites saisonnières comprises — dépasse largement la dizaine. Des restrictions qui avaient commencé dans certaines parties de la Sibérie, où la demande de chauffage explose en hiver, atteignent désormais le cœur politique et économique du pays : la région capitale.</p>
  <p class="pt">Não se trata de uma decisão repentina, mas do prolongamento de restrições que a Rússia vem alargando ao longo do último ano. O governo já havia imposto proibições de mineração válidas o ano todo na República da Buriácia e na Região de Transbaikália a partir de abril de 2026, e proibiu a mineração até 2031 em regiões do Cáucaso do Norte, como Daguestão, Chechênia, Inguchétia e Ossétia do Norte, bem como em partes da Ucrânia sob controlo russo. Com a área de Moscou agora somada, o número de regiões russas onde a mineração está restrita — contando os limites sazonais — ultrapassa folgadamente a dezena. As restrições que começaram em partes da Sibéria, onde a procura de aquecimento dispara no inverno, chegaram agora ao coração político e económico do país: a região da capital.</p>
  <p class="tr">Bu ani bir hamle değil, Rusya'nın geçen yıl boyunca genişlettiği kısıtlamaların bir devamı. Hükümet, Nisan 2026'dan itibaren Buryatya Cumhuriyeti ve Zabaykalski Krayı'nda yıl boyu madencilik yasakları uygulamıştı ve Dağıstan, Çeçenya, İnguşetya ve Kuzey Osetya gibi Kuzey Kafkasya bölgelerinde ile Rusya kontrolündeki Ukrayna'nın bazı kısımlarında madenciliği 2031'e kadar yasaklamıştı. Şimdi Moskova bölgesinin de eklenmesiyle, madenciliğin kısıtlandığı Rusya bölgelerinin sayısı — mevsimsel sınırlamalar dahil — rahatlıkla ona ulaşıyor. Kışın ısıtma talebinin fırladığı Sibirya'nın bazı bölgelerinde başlayan kısıtlamalar, artık ülkenin siyasi ve ekonomik merkezi olan başkent bölgesine ulaştı.</p>
  <p class="vi">Đây không phải là một động thái đột ngột mà là sự nối dài của các hạn chế mà Nga đã mở rộng trong năm qua. Chính phủ đã áp đặt lệnh cấm khai thác quanh năm tại Cộng hòa Buryatia và Vùng Zabaykalsky từ tháng 4 năm 2026, đồng thời cấm khai thác đến năm 2031 tại các vùng Bắc Kavkaz như Dagestan, Chechnya, Ingushetia và Bắc Ossetia, cũng như tại một số khu vực của Ukraine do Nga kiểm soát. Với việc khu vực Moskva nay được bổ sung, số vùng của Nga nơi hoạt động khai thác bị hạn chế — tính cả các giới hạn theo mùa — đã vượt xa con số mười. Các hạn chế bắt đầu từ một số vùng của Siberia, nơi nhu cầu sưởi ấm mùa đông tăng vọt, giờ đây đã lan tới trung tâm chính trị và kinh tế của đất nước: vùng thủ đô.</p>

  <div class="ko">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">러시아 채굴 규제의 확산 — 시베리아에서 수도권까지</text>
    <g font-family="sans-serif">
      <line x1="60" y1="70" x2="60" y2="330" stroke="#3f3f46" stroke-width="2"/>
      <circle cx="60" cy="100" r="6" fill="#f97316"/>
      <text x="82" y="96" fill="#fafafa" font-size="14" font-weight="700">2024년 11월</text>
      <text x="82" y="118" fill="#a1a1aa" font-size="13">채굴 합법화 — 과세·등록 대상으로 편입</text>
      <circle cx="60" cy="160" r="6" fill="#f97316"/>
      <text x="82" y="156" fill="#fafafa" font-size="14" font-weight="700">2025년~</text>
      <text x="82" y="178" fill="#a1a1aa" font-size="13">북캅카스·우크라이나 통제지역 등 2031년까지 금지</text>
      <circle cx="60" cy="220" r="6" fill="#f97316"/>
      <text x="82" y="216" fill="#fafafa" font-size="14" font-weight="700">2026년 4월</text>
      <text x="82" y="238" fill="#a1a1aa" font-size="13">부랴티야·자바이칼스키 연중 금지</text>
      <circle cx="60" cy="290" r="7" fill="#ef4444"/>
      <text x="82" y="284" fill="#fca5a5" font-size="14" font-weight="700">2026년 7월 1일 (초안)</text>
      <text x="82" y="306" fill="#e4e4e7" font-size="13">모스크바·모스크바주·쿠르스크 일부 → 2032년까지</text>
      <rect x="430" y="330" width="250" height="52" rx="8" fill="#1f2937" stroke="#f97316" stroke-width="1"/>
      <text x="445" y="352" fill="#fdba74" font-size="13" font-weight="700">금지 구역 채굴 전력 부하</text>
      <text x="445" y="372" fill="#e4e4e7" font-size="13">65개 데이터센터 · 총 734 MW</text>
    </g>
  </svg>
  </div>
  <div class="en fr pt tr vi">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Russia's spreading mining curbs — from Siberia to the capital</text>
    <g font-family="sans-serif">
      <line x1="60" y1="70" x2="60" y2="330" stroke="#3f3f46" stroke-width="2"/>
      <circle cx="60" cy="100" r="6" fill="#f97316"/>
      <text x="82" y="96" fill="#fafafa" font-size="14" font-weight="700">Nov 2024</text>
      <text x="82" y="118" fill="#a1a1aa" font-size="13">Mining legalized — brought under tax and registration</text>
      <circle cx="60" cy="160" r="6" fill="#f97316"/>
      <text x="82" y="156" fill="#fafafa" font-size="14" font-weight="700">From 2025</text>
      <text x="82" y="178" fill="#a1a1aa" font-size="13">North Caucasus, controlled Ukraine areas: banned to 2031</text>
      <circle cx="60" cy="220" r="6" fill="#f97316"/>
      <text x="82" y="216" fill="#fafafa" font-size="14" font-weight="700">Apr 2026</text>
      <text x="82" y="238" fill="#a1a1aa" font-size="13">Buryatia, Zabaykalsky Krai: year-round ban</text>
      <circle cx="60" cy="290" r="7" fill="#ef4444"/>
      <text x="82" y="284" fill="#fca5a5" font-size="14" font-weight="700">July 1, 2026 (draft)</text>
      <text x="82" y="306" fill="#e4e4e7" font-size="13">Moscow, Moscow Region, parts of Kursk → through 2032</text>
      <rect x="430" y="330" width="250" height="52" rx="8" fill="#1f2937" stroke="#f97316" stroke-width="1"/>
      <text x="445" y="352" fill="#fdba74" font-size="13" font-weight="700">Mining load in banned zone</text>
      <text x="445" y="372" fill="#e4e4e7" font-size="13">65 data centers · 734 MW total</text>
    </g>
  </svg>
  </div>
  <div class="ja">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">ロシアのマイニング規制の拡大 — シベリアから首都圏へ</text>
    <g font-family="sans-serif">
      <line x1="60" y1="70" x2="60" y2="330" stroke="#3f3f46" stroke-width="2"/>
      <circle cx="60" cy="100" r="6" fill="#f97316"/>
      <text x="82" y="96" fill="#fafafa" font-size="14" font-weight="700">2024年11月</text>
      <text x="82" y="118" fill="#a1a1aa" font-size="13">マイニング合法化 — 課税・登録の対象に</text>
      <circle cx="60" cy="160" r="6" fill="#f97316"/>
      <text x="82" y="156" fill="#fafafa" font-size="14" font-weight="700">2025年~</text>
      <text x="82" y="178" fill="#a1a1aa" font-size="13">北カフカス・ウクライナ統制地域など2031年まで禁止</text>
      <circle cx="60" cy="220" r="6" fill="#f97316"/>
      <text x="82" y="216" fill="#fafafa" font-size="14" font-weight="700">2026年4月</text>
      <text x="82" y="238" fill="#a1a1aa" font-size="13">ブリヤート・ザバイカリスキー通年禁止</text>
      <circle cx="60" cy="290" r="7" fill="#ef4444"/>
      <text x="82" y="284" fill="#fca5a5" font-size="14" font-weight="700">2026年7月1日(草案)</text>
      <text x="82" y="306" fill="#e4e4e7" font-size="13">モスクワ・モスクワ州・クルスク一部 → 2032年まで</text>
      <rect x="430" y="330" width="250" height="52" rx="8" fill="#1f2937" stroke="#f97316" stroke-width="1"/>
      <text x="445" y="352" fill="#fdba74" font-size="13" font-weight="700">禁止区域のマイニング電力負荷</text>
      <text x="445" y="372" fill="#e4e4e7" font-size="13">65データセンター · 計734 MW</text>
    </g>
  </svg>
  </div>
  <div class="es">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">La expansión de los límites de minería en Rusia — de Siberia a la capital</text>
    <g font-family="sans-serif">
      <line x1="60" y1="70" x2="60" y2="330" stroke="#3f3f46" stroke-width="2"/>
      <circle cx="60" cy="100" r="6" fill="#f97316"/>
      <text x="82" y="96" fill="#fafafa" font-size="14" font-weight="700">Nov 2024</text>
      <text x="82" y="118" fill="#a1a1aa" font-size="13">Minería legalizada — sujeta a impuestos y registro</text>
      <circle cx="60" cy="160" r="6" fill="#f97316"/>
      <text x="82" y="156" fill="#fafafa" font-size="14" font-weight="700">Desde 2025</text>
      <text x="82" y="178" fill="#a1a1aa" font-size="13">Cáucaso Norte, zonas de Ucrania: prohibida hasta 2031</text>
      <circle cx="60" cy="220" r="6" fill="#f97316"/>
      <text x="82" y="216" fill="#fafafa" font-size="14" font-weight="700">Abr 2026</text>
      <text x="82" y="238" fill="#a1a1aa" font-size="13">Buriatia, Zabaikalie: prohibición todo el año</text>
      <circle cx="60" cy="290" r="7" fill="#ef4444"/>
      <text x="82" y="284" fill="#fca5a5" font-size="14" font-weight="700">1 jul 2026 (borrador)</text>
      <text x="82" y="306" fill="#e4e4e7" font-size="13">Moscú, Región de Moscú, parte de Kursk → hasta 2032</text>
      <rect x="430" y="330" width="250" height="52" rx="8" fill="#1f2937" stroke="#f97316" stroke-width="1"/>
      <text x="445" y="352" fill="#fdba74" font-size="13" font-weight="700">Carga de minería en zona prohibida</text>
      <text x="445" y="372" fill="#e4e4e7" font-size="13">65 centros de datos · 734 MW total</text>
    </g>
  </svg>
  </div>
  <div class="de">
  <svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Russlands sich ausbreitende Mining-Beschränkungen — von Sibirien zur Hauptstadt</text>
    <g font-family="sans-serif">
      <line x1="60" y1="70" x2="60" y2="330" stroke="#3f3f46" stroke-width="2"/>
      <circle cx="60" cy="100" r="6" fill="#f97316"/>
      <text x="82" y="96" fill="#fafafa" font-size="14" font-weight="700">Nov 2024</text>
      <text x="82" y="118" fill="#a1a1aa" font-size="13">Mining legalisiert — Steuer- und Registrierungspflicht</text>
      <circle cx="60" cy="160" r="6" fill="#f97316"/>
      <text x="82" y="156" fill="#fafafa" font-size="14" font-weight="700">Ab 2025</text>
      <text x="82" y="178" fill="#a1a1aa" font-size="13">Nordkaukasus, Ukraine-Gebiete: verboten bis 2031</text>
      <circle cx="60" cy="220" r="6" fill="#f97316"/>
      <text x="82" y="216" fill="#fafafa" font-size="14" font-weight="700">Apr 2026</text>
      <text x="82" y="238" fill="#a1a1aa" font-size="13">Burjatien, Transbaikalien: Ganzjahresverbot</text>
      <circle cx="60" cy="290" r="7" fill="#ef4444"/>
      <text x="82" y="284" fill="#fca5a5" font-size="14" font-weight="700">1. Juli 2026 (Entwurf)</text>
      <text x="82" y="306" fill="#e4e4e7" font-size="13">Moskau, Region Moskau, Teile von Kursk → bis 2032</text>
      <rect x="430" y="330" width="250" height="52" rx="8" fill="#1f2937" stroke="#f97316" stroke-width="1"/>
      <text x="445" y="352" fill="#fdba74" font-size="13" font-weight="700">Mining-Last in Verbotszone</text>
      <text x="445" y="372" fill="#e4e4e7" font-size="13">65 Rechenzentren · 734 MW gesamt</text>
    </g>
  </svg>
  </div>

  <h2 class="ko">합법화와 금지 사이 — 러시아의 이중 노선</h2>
  <h2 class="en">Between legalization and prohibition — Russia's double track</h2>
  <h2 class="ja">合法化と禁止の間 — ロシアの二重路線</h2>
  <h2 class="es">Entre la legalización y la prohibición — la doble vía de Rusia</h2>
  <h2 class="de">Zwischen Legalisierung und Verbot — Russlands doppeltes Gleis</h2>
  <h2 class="fr">Entre légalisation et interdiction — la double voie de la Russie</h2>
  <h2 class="pt">Entre legalização e proibição — a dupla via da Rússia</h2>
  <h2 class="tr">Yasallaştırma ile yasak arasında — Rusya'nın çifte yolu</h2>
  <h2 class="vi">Giữa hợp pháp hóa và cấm đoán — hướng đi song song của Nga</h2>
  <p class="ko">러시아의 접근은 언뜻 모순처럼 보인다. 정부는 2024년 채굴을 정식 산업으로 합법화해 등록·과세 대상으로 삼았다. 서방 제재로 좁아진 재정 여건에서 채굴은 잉여 에너지를 외화 획득 수단으로 바꾸는 통로였고, 러시아는 미국에 이어 세계 2위권의 채굴 강국으로 꼽혀 왔다. 그러나 같은 정부가 특정 지역에서는 채굴을 6년 넘게 금지한다. 이 둘은 실은 하나의 논리로 이어진다. 채굴을 합법화해 '어디서 얼마나 이뤄지는지'를 파악할 수 있게 된 뒤에야, 전력이 부족한 지역만 골라 정밀하게 잘라내는 선별적 금지가 가능해졌기 때문이다.</p>
  <p class="en">Russia's approach looks contradictory at first glance. In 2024 the government legalized mining as a formal industry, making it subject to registration and taxation. Under fiscal conditions squeezed by Western sanctions, mining was a conduit for turning surplus energy into a means of earning foreign currency, and Russia has ranked as a mining power second only to the United States. Yet the same government bans mining for more than six years in certain regions. The two in fact join into a single logic: only after legalizing mining — and thereby being able to see where and how much of it takes place — did a selective ban, surgically excising only the power-short regions, become possible.</p>
  <p class="ja">ロシアのアプローチは一見矛盾しているように見える。政府は2024年、マイニングを正式な産業として合法化し、登録・課税の対象とした。西側の制裁で狭まった財政状況の中で、マイニングは余剰エネルギーを外貨獲得の手段に変える通路であり、ロシアは米国に次ぐ世界第2位級のマイニング大国とされてきた。しかし同じ政府が特定地域では6年以上マイニングを禁止する。この二つは実は一つの論理でつながる。マイニングを合法化し「どこでどれだけ行われているか」を把握できるようになって初めて、電力の足りない地域だけを選んで精密に切り取る選別的な禁止が可能になったからだ。</p>
  <p class="es">El enfoque de Rusia parece contradictorio a primera vista. En 2024 el gobierno legalizó la minería como industria formal, sometiéndola a registro y tributación. Bajo condiciones fiscales estranguladas por las sanciones occidentales, la minería era un conducto para convertir el excedente de energía en un medio de obtener divisas, y Rusia se ha situado como una potencia minera solo por detrás de Estados Unidos. Sin embargo, el mismo gobierno prohíbe la minería durante más de seis años en ciertas regiones. Ambas cosas se unen de hecho en una sola lógica: solo tras legalizar la minería —y poder así ver dónde y cuánto se realiza— resultó posible una prohibición selectiva que extirpa quirúrgicamente solo las regiones con escasez de energía.</p>
  <p class="de">Russlands Ansatz wirkt auf den ersten Blick widersprüchlich. 2024 legalisierte die Regierung das Mining als formelle Industrie und unterwarf es Registrierung und Besteuerung. Unter den durch westliche Sanktionen verengten Finanzbedingungen war Mining ein Kanal, um überschüssige Energie in ein Mittel zum Devisenerwerb zu verwandeln, und Russland galt als Mining-Macht, die nur hinter den USA rangiert. Doch dieselbe Regierung verbietet das Mining in bestimmten Regionen für mehr als sechs Jahre. Beide fügen sich tatsächlich zu einer einzigen Logik: Erst nachdem das Mining legalisiert war — und man dadurch sehen konnte, wo und wie viel davon stattfindet —, wurde ein selektives Verbot möglich, das chirurgisch nur die strommangelnden Regionen herausschneidet.</p>
  <p class="fr">L'approche russe paraît contradictoire à première vue. En 2024, le gouvernement a légalisé le minage comme industrie à part entière, le soumettant à l'enregistrement et à l'imposition. Dans des conditions budgétaires resserrées par les sanctions occidentales, le minage était un moyen de transformer l'énergie excédentaire en devises étrangères, et la Russie s'est classée comme puissance minière juste derrière les États-Unis. Pourtant, ce même gouvernement interdit le minage pendant plus de six ans dans certaines régions. Les deux s'inscrivent en réalité dans une seule et même logique : ce n'est qu'après avoir légalisé le minage — et donc pu observer où et dans quelle mesure il a lieu — qu'une interdiction sélective, retranchant chirurgicalement les seules régions en déficit d'électricité, est devenue possible.</p>
  <p class="pt">A abordagem da Rússia parece contraditória à primeira vista. Em 2024, o governo legalizou a mineração como indústria formal, sujeitando-a a registo e tributação. Em condições fiscais espremidas pelas sanções ocidentais, a mineração era um canal para transformar energia excedente em divisas, e a Rússia posicionou-se como potência mineradora atrás apenas dos Estados Unidos. No entanto, o mesmo governo proíbe a mineração por mais de seis anos em certas regiões. As duas coisas ligam-se, na verdade, numa única lógica: só depois de legalizar a mineração — e assim poder ver onde e quanto dela ocorre — se tornou possível uma proibição seletiva que corta cirurgicamente apenas as regiões com escassez de energia.</p>
  <p class="tr">Rusya'nın yaklaşımı ilk bakışta çelişkili görünüyor. Hükümet 2024'te madenciliği resmi bir sektör olarak yasallaştırarak kayıt ve vergilendirmeye tabi tuttu. Batı yaptırımlarıyla daralan mali koşullar altında madencilik, fazla enerjiyi döviz kazanma aracına dönüştüren bir kanal oldu ve Rusya, ABD'nin ardından ikinci sıradaki madencilik gücü olarak sıralandı. Yine de aynı hükümet, belirli bölgelerde madenciliği altı yıldan fazla yasaklıyor. Bu ikisi aslında tek bir mantıkta birleşiyor: Madenciliği yasallaştırıp — böylece nerede ve ne kadar yapıldığını görebilir hale geldikten — sonra ancak, yalnızca elektrik açığı çeken bölgeleri cerrahi biçimde ayıklayan seçici bir yasak mümkün oldu.</p>
  <p class="vi">Cách tiếp cận của Nga thoạt nhìn có vẻ mâu thuẫn. Năm 2024, chính phủ đã hợp pháp hóa khai thác như một ngành công nghiệp chính thức, buộc phải đăng ký và chịu thuế. Trong bối cảnh tài chính bị siết chặt bởi các lệnh trừng phạt phương Tây, khai thác là kênh biến năng lượng dư thừa thành phương tiện kiếm ngoại tệ, và Nga được xếp hạng là cường quốc khai thác chỉ đứng sau Hoa Kỳ. Thế nhưng cũng chính chính phủ đó lại cấm khai thác hơn sáu năm tại một số vùng. Hai điều này thực ra gắn với cùng một logic: chỉ sau khi hợp pháp hóa khai thác — và nhờ đó có thể thấy được nơi nào và mức độ khai thác ra sao — thì một lệnh cấm chọn lọc, cắt bỏ chính xác chỉ những vùng thiếu điện, mới trở nên khả thi.</p>
  <p class="ko">그럼에도 이 조치가 순수하게 에너지 문제만은 아니라는 반론도 가능하다. 러시아 당국은 이번 초안의 근거로 금융범죄 우려도 함께 들었다. 등록되지 않은 '회색 채굴'은 보조금이 붙은 값싼 산업·주거용 전기를 몰래 끌어다 쓰며 전력망을 왜곡하고, 그 수익은 과세 밖에 놓인다. 즉 금지의 이면에는 통제 밖에서 자라는 지하 채굴을 솎아내려는 의도가 함께 있다. 그러나 바로 여기서 딜레마가 생긴다. 합법 채굴을 금지하면 남는 것은 더 은밀해진 불법 채굴일 수 있고, 단속 인력과 계량 인프라가 뒷받침되지 않으면 금지 조항은 종이 위에만 존재하게 된다. 결국 이번 조치의 성패는 법 조문이 아니라 집행 역량에서 갈릴 것이다.</p>
  <p class="en">Even so, one can counter that the measure is not purely about energy. Russian authorities also cited concerns about financial crime as a basis for the draft. Unregistered "gray mining" quietly siphons subsidized, cheap industrial and residential electricity, distorting the grid, while its revenue sits outside taxation. Behind the ban, in other words, lies an intent to weed out the underground mining that grows beyond control. But this is exactly where the dilemma arises. Banning legal mining may leave only illegal mining that has grown more clandestine, and without enforcement manpower and metering infrastructure the prohibition exists only on paper. In the end, the measure's success or failure will be decided not by the letter of the law but by enforcement capacity.</p>
  <p class="ja">それでも、この措置が純粋にエネルギー問題だけではないという反論も可能だ。ロシア当局は今回の草案の根拠として金融犯罪への懸念も併せて挙げた。登録されていない「グレーマイニング」は補助金のついた安価な産業・住宅用電気をこっそり引いて電力網を歪め、その収益は課税の外に置かれる。つまり禁止の裏には、統制の外で育つ地下マイニングを間引こうとする意図も併存する。しかしまさにここでジレンマが生じる。合法マイニングを禁止すれば残るのはより密やかになった違法マイニングかもしれず、取締人員と計量インフラが伴わなければ禁止条項は紙の上にのみ存在することになる。結局この措置の成否は、法の条文ではなく執行能力で分かれるだろう。</p>
  <p class="es">Aun así, cabe replicar que la medida no trata puramente de energía. Las autoridades rusas también citaron preocupaciones por delitos financieros como base del borrador. La "minería gris" no registrada desvía en silencio electricidad industrial y residencial barata y subvencionada, distorsionando la red, mientras sus ingresos quedan fuera de la tributación. Detrás de la prohibición, en otras palabras, subyace la intención de erradicar la minería subterránea que crece fuera de control. Pero aquí surge precisamente el dilema. Prohibir la minería legal puede dejar solo una minería ilegal aún más clandestina, y sin personal de control ni infraestructura de medición la prohibición existe solo sobre el papel. Al final, el éxito o el fracaso de la medida se decidirá no por la letra de la ley, sino por la capacidad de ejecución.</p>
  <p class="de">Dennoch lässt sich einwenden, dass es bei der Maßnahme nicht rein um Energie geht. Die russischen Behörden führten als Grundlage des Entwurfs auch Bedenken über Finanzkriminalität an. Nicht registriertes „Graues Mining" zapft stillschweigend subventionierten, billigen Industrie- und Wohnstrom ab, verzerrt das Netz, während seine Erträge außerhalb der Besteuerung liegen. Hinter dem Verbot steht mit anderen Worten die Absicht, das unkontrolliert wachsende Untergrund-Mining auszujäten. Doch genau hier entsteht das Dilemma. Ein Verbot legalen Minings mag nur noch heimlicheres illegales Mining übriglassen, und ohne Kontrollpersonal und Messinfrastruktur existiert das Verbot nur auf dem Papier. Am Ende entscheidet sich Erfolg oder Misserfolg der Maßnahme nicht am Gesetzestext, sondern an der Durchsetzungskapazität.</p>
  <p class="fr">Malgré tout, on peut objecter que la mesure ne relève pas purement de l'énergie. Les autorités russes ont également invoqué des préoccupations liées à la criminalité financière comme fondement du projet. Le « minage gris » non enregistré détourne discrètement de l'électricité industrielle et résidentielle subventionnée et bon marché, faussant le réseau, tandis que ses revenus échappent à l'impôt. Derrière l'interdiction se cache, en d'autres termes, une volonté d'éliminer le minage souterrain qui prospère hors de tout contrôle. Mais c'est précisément là que surgit le dilemme. Interdire le minage légal risque de ne laisser subsister qu'un minage illégal devenu plus clandestin encore, et sans effectifs de contrôle ni infrastructure de mesure, l'interdiction n'existe que sur le papier. En fin de compte, le succès ou l'échec de la mesure se jouera non pas dans la lettre de la loi, mais dans la capacité d'application.</p>
  <p class="pt">Ainda assim, pode-se contra-argumentar que a medida não é puramente energética. As autoridades russas também citaram preocupações com crimes financeiros como base do projeto. A “mineração cinzenta” não registada desvia silenciosamente eletricidade industrial e residencial barata e subsidiada, distorcendo a rede, enquanto as suas receitas ficam fora da tributação. Por trás da proibição está, em outras palavras, a intenção de eliminar a mineração clandestina que cresce fora de controlo. Mas é precisamente aí que surge o dilema. Proibir a mineração legal pode deixar apenas mineração ilegal ainda mais clandestina, e sem efetivos de fiscalização e infraestrutura de medição, a proibição existe apenas no papel. No final, o sucesso ou fracasso da medida será decidido não pela letra da lei, mas pela capacidade de fiscalização.</p>
  <p class="tr">Yine de bu önlemin salt enerjiyle ilgili olmadığı öne sürülebilir. Rus yetkilileri taslağın gerekçesi olarak mali suç endişelerini de gösterdi. Kayıt dışı "gri madencilik", sübvansiyonlu ucuz sanayi ve konut elektriğini sessizce çekerek şebekeyi bozuyor, gelirleri ise vergilendirme dışında kalıyor. Yasağın arkasında, başka bir deyişle, kontrol dışında büyüyen yeraltı madenciliğini ayıklama niyeti de yatıyor. Ama tam da burada ikilem ortaya çıkıyor. Yasal madenciliği yasaklamak, geriye yalnızca daha da gizlenmiş yasa dışı madenciliği bırakabilir ve denetim personeli ile ölçüm altyapısı olmadan yasak yalnızca kağıt üzerinde kalır. Sonuçta bu önlemin başarısı ya da başarısızlığı, kanun metniyle değil uygulama kapasitesiyle belirlenecek.</p>
  <p class="vi">Dù vậy, cũng có thể phản biện rằng biện pháp này không hoàn toàn chỉ vì năng lượng. Giới chức Nga cũng viện dẫn lo ngại về tội phạm tài chính làm cơ sở cho dự thảo. "Khai thác xám" không đăng ký âm thầm rút điện công nghiệp và dân dụng giá rẻ được trợ cấp, làm méo mó lưới điện, trong khi doanh thu của nó nằm ngoài phạm vi thuế. Nói cách khác, đằng sau lệnh cấm là ý định loại bỏ hoạt động khai thác ngầm phát triển ngoài tầm kiểm soát. Nhưng chính đây là nơi nảy sinh nghịch lý. Cấm khai thác hợp pháp có thể chỉ để lại hoạt động khai thác bất hợp pháp trở nên kín đáo hơn, và nếu không có nhân lực thực thi cùng hạ tầng đo lường thì lệnh cấm chỉ tồn tại trên giấy. Rốt cuộc, thành hay bại của biện pháp này sẽ được quyết định không phải bởi câu chữ của luật mà bởi năng lực thực thi.</p>

  <h2 class="ko">채굴은 값싼 전기를 따라 이동한다</h2>
  <h2 class="en">Mining migrates toward cheap power</h2>
  <h2 class="ja">マイニングは安い電気を追って移動する</h2>
  <h2 class="es">La minería migra hacia la energía barata</h2>
  <h2 class="de">Mining wandert zur billigen Energie</h2>
  <h2 class="fr">Le minage migre vers l'électricité bon marché</h2>
  <h2 class="pt">A mineração migra para a energia barata</h2>
  <h2 class="tr">Madencilik ucuz enerjinin peşinden göç ediyor</h2>
  <h2 class="vi">Khai thác di chuyển theo nguồn điện giá rẻ</h2>
  <p class="ko">채굴 산업의 역사는 곧 전기를 따라 흐른 이동의 역사다. 2021년 중국이 채굴을 전면 금지했을 때, 당시 전 세계 해시레이트의 절반 이상을 차지하던 중국의 채굴기들은 몇 달 만에 미국·카자흐스탄·러시아로 흩어졌다. 네트워크 해시레이트는 일시적으로 급락했다가 이내 회복했고, 미국은 오늘날 최대 채굴 거점으로 올라섰다. 러시아의 이번 조치는 그때와 규모는 다르지만 방향은 같다. 다만 국경을 넘는 이동이 아니라, 러시아 내부에서 전력이 부족한 서부·수도권으로부터 전력이 남는 시베리아·극동으로 채굴 설비가 재배치될 가능성이 크다. 값싼 수력·잉여 전력이 있는 곳으로 채굴이 몰리는 '스트랜디드 에너지(stranded energy)' 논리가 국내 지도 위에서 다시 작동하는 셈이다.</p>
  <p class="en">The history of the mining industry is a history of migration that follows electricity. When China banned mining outright in 2021, the Chinese rigs that then made up more than half of global hashrate scattered to the United States, Kazakhstan and Russia within months. Network hashrate plunged temporarily before recovering, and the United States has since risen to become the largest mining hub. Russia's move differs in scale from that episode but points the same way. Only this is not a cross-border migration: mining equipment is likely to be redeployed within Russia, from the power-short west and capital region toward Siberia and the Far East, where power is in surplus. The "stranded energy" logic — mining clustering wherever cheap hydro or surplus power exists — is at work again, this time on a domestic map.</p>
  <p class="ja">マイニング産業の歴史は、すなわち電気を追って流れた移動の歴史だ。2021年に中国がマイニングを全面禁止したとき、当時世界のハッシュレートの半分以上を占めていた中国のマイニング機は数か月で米国・カザフスタン・ロシアへ散らばった。ネットワークハッシュレートは一時的に急落したのちすぐ回復し、米国は今日最大のマイニング拠点へと上り詰めた。ロシアの今回の措置はその時と規模は異なるが方向は同じだ。ただし国境を越える移動ではなく、ロシア国内で電力の足りない西部・首都圏から電力の余るシベリア・極東へマイニング設備が再配置される可能性が高い。安価な水力・余剰電力のある場所へマイニングが集まる「ストランデッド・エネルギー(stranded energy)」の論理が、国内の地図の上で再び作動するわけだ。</p>
  <p class="es">La historia de la industria minera es una historia de migración que sigue a la electricidad. Cuando China prohibió por completo la minería en 2021, los equipos chinos que entonces representaban más de la mitad del hashrate mundial se dispersaron hacia Estados Unidos, Kazajistán y Rusia en cuestión de meses. El hashrate de la red se desplomó temporalmente antes de recuperarse, y Estados Unidos ha ascendido desde entonces hasta convertirse en el mayor centro minero. El movimiento de Rusia difiere en escala de aquel episodio, pero apunta en la misma dirección. Solo que esto no es una migración transfronteriza: es probable que el equipo minero se redistribuya dentro de Rusia, desde el oeste y la región de la capital, con escasez de energía, hacia Siberia y el Lejano Oriente, donde la energía es excedentaria. La lógica de la "energía varada" (stranded energy) —la minería agrupándose allí donde existe hidroeléctrica barata o energía sobrante— vuelve a operar, esta vez sobre un mapa nacional.</p>
  <p class="de">Die Geschichte der Mining-Industrie ist eine Geschichte der Wanderung, die dem Strom folgt. Als China 2021 das Mining vollständig verbot, verstreuten sich die chinesischen Anlagen, die damals mehr als die Hälfte der globalen Hashrate ausmachten, innerhalb von Monaten in die USA, nach Kasachstan und Russland. Die Netzwerk-Hashrate stürzte vorübergehend ab, bevor sie sich erholte, und die USA sind seither zum größten Mining-Zentrum aufgestiegen. Russlands Schritt unterscheidet sich im Ausmaß von jener Episode, weist aber in dieselbe Richtung. Nur ist dies keine grenzüberschreitende Wanderung: Mining-Ausrüstung wird wahrscheinlich innerhalb Russlands verlagert — vom strommangelnden Westen und der Hauptstadtregion nach Sibirien und in den Fernen Osten, wo Strom im Überschuss vorhanden ist. Die „Stranded-Energy"-Logik — Mining ballt sich, wo billige Wasserkraft oder Überschussstrom existiert — wirkt erneut, diesmal auf einer inländischen Karte.</p>
  <p class="fr">L'histoire de l'industrie du minage est une histoire de migration qui suit l'électricité. Lorsque la Chine a interdit purement et simplement le minage en 2021, les machines chinoises, qui représentaient alors plus de la moitié du hashrate mondial, se sont dispersées vers les États-Unis, le Kazakhstan et la Russie en quelques mois. Le hashrate du réseau a chuté temporairement avant de se redresser, et les États-Unis sont depuis devenus le plus grand pôle minier. Le mouvement de la Russie diffère de cet épisode par son ampleur, mais va dans la même direction. Seulement, il ne s'agit pas ici d'une migration transfrontalière : l'équipement minier sera probablement redéployé à l'intérieur de la Russie, de l'ouest et de la région capitale en déficit d'électricité vers la Sibérie et l'Extrême-Orient, où l'électricité est excédentaire. La logique de l'« énergie échouée » (stranded energy) — le minage se regroupant partout où existent une hydroélectricité bon marché ou un surplus d'électricité — est de nouveau à l'œuvre, cette fois sur une carte intérieure.</p>
  <p class="pt">A história da indústria de mineração é uma história de migração que segue a eletricidade. Quando a China proibiu totalmente a mineração em 2021, as máquinas chinesas, que então representavam mais de metade do hashrate global, dispersaram-se para os Estados Unidos, o Cazaquistão e a Rússia em poucos meses. O hashrate da rede caiu temporariamente antes de recuperar, e os Estados Unidos desde então ascenderam ao maior polo de mineração. O movimento da Rússia difere em escala desse episódio, mas aponta na mesma direção. Só que isto não é uma migração transfronteiriça: é provável que o equipamento de mineração seja redistribuído dentro da Rússia, do oeste e da região da capital, com escassez de energia, para a Sibéria e o Extremo Oriente, onde a energia está em excedente. A lógica da “energia presa” (stranded energy) — a mineração agrupando-se onde quer que exista hidroeletricidade barata ou energia excedente — volta a operar, desta vez num mapa doméstico.</p>
  <p class="tr">Madencilik sektörünün tarihi, elektriği izleyen bir göç tarihidir. Çin 2021'de madenciliği tamamen yasakladığında, o dönem küresel hashrate'in yarısından fazlasını oluşturan Çinli cihazlar aylar içinde ABD, Kazakistan ve Rusya'ya dağıldı. Ağ hashrate'i geçici olarak sert düştükten sonra toparlandı ve ABD o zamandan beri en büyük madencilik merkezi haline geldi. Rusya'nın bu hamlesi ölçek olarak o dönemden farklı ama aynı yöne işaret ediyor. Ancak bu, sınır ötesi bir göç değil: madencilik ekipmanının, elektrik açığı çeken batı ve başkent bölgesinden elektrik fazlası bulunan Sibirya ve Uzak Doğu'ya doğru Rusya içinde yeniden konumlandırılması muhtemel. Ucuz hidroelektrik veya fazla elektriğin bulunduğu her yerde madenciliğin kümelendiği "atıl enerji" (stranded energy) mantığı, bu kez bir iç harita üzerinde yeniden işliyor.</p>
  <p class="vi">Lịch sử của ngành khai thác chính là lịch sử di cư theo dòng điện. Khi Trung Quốc cấm hoàn toàn hoạt động khai thác vào năm 2021, các dàn máy đào của Trung Quốc, khi đó chiếm hơn một nửa hashrate toàn cầu, đã phân tán sang Hoa Kỳ, Kazakhstan và Nga chỉ trong vài tháng. Hashrate mạng lưới sụt giảm tạm thời trước khi phục hồi, và Hoa Kỳ từ đó đã vươn lên thành trung tâm khai thác lớn nhất. Động thái của Nga khác về quy mô so với sự kiện đó nhưng cùng hướng đi. Chỉ có điều đây không phải là cuộc di cư xuyên biên giới: thiết bị khai thác nhiều khả năng sẽ được tái bố trí ngay trong nước Nga, từ khu vực phía tây và vùng thủ đô thiếu điện sang Siberia và Viễn Đông, nơi điện năng dư thừa. Logic "năng lượng mắc kẹt" (stranded energy) — hoạt động khai thác tụ tập ở bất cứ đâu có thủy điện giá rẻ hoặc điện dư thừa — lại vận hành, lần này trên bản đồ trong nước.</p>
  <p class="ko">이 재배치가 글로벌 네트워크에 미치는 영향은 제한적일 것으로 보인다. 러시아 내부에서 채굴이 이동하는 것이라면 전체 해시레이트에는 큰 공백이 생기지 않는다. 다만 최근 비트코인 가격 하락으로 채산성이 압박받는 상황과 겹치면 이야기가 달라진다. 최근 <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">해시레이트는 사상 최고인데 채굴 수익은 쥐어짜이는</a> 국면처럼, 마진이 얇아진 채굴자들은 이전 비용이 큰 대규모 이전을 감내하기 어렵다. 값싼 전기를 찾아 시베리아로 옮길 여력이 있는 대형 사업자와, 그 비용을 감당 못해 아예 가동을 멈추는 소형 사업자 사이의 격차가 벌어질 수 있다. 즉 이번 금지는 러시아 채굴 산업 내부의 옥석을 가르는 압력으로도 작용할 것이다.</p>
  <p class="en">The impact of this redeployment on the global network looks limited. If mining is moving within Russia, no large gap opens in total hashrate. The story changes, however, when it overlaps with the recent squeeze on profitability from falling bitcoin prices. As in the recent phase in which <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">hashrate hit record highs even as mining revenue was squeezed</a>, miners with thinned margins can ill afford a large, costly relocation. A gap may widen between big operators with the means to move to Siberia in search of cheap power and small operators who, unable to bear that cost, simply shut down. The ban, in other words, will also act as a pressure that separates the wheat from the chaff within Russia's mining industry.</p>
  <p class="ja">この再配置がグローバルネットワークに及ぼす影響は限定的とみられる。ロシア国内でマイニングが移動するのであれば、全体のハッシュレートに大きな空白は生じない。ただし最近のビットコイン価格下落で採算が圧迫される状況と重なると話は変わる。最近<a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">ハッシュレートは過去最高なのにマイニング収益は圧迫された</a>局面のように、マージンが薄くなったマイナーは移転費用の大きい大規模移転に耐えにくい。安い電気を求めてシベリアへ移す余力のある大手事業者と、その費用を賄えず稼働そのものを止める小規模事業者との格差が広がりうる。つまり今回の禁止は、ロシアのマイニング産業内部の淘汰を促す圧力としても作用するだろう。</p>
  <p class="es">El impacto de esta redistribución sobre la red global parece limitado. Si la minería se mueve dentro de Rusia, no se abre un gran vacío en el hashrate total. La historia cambia, sin embargo, cuando se superpone con la reciente presión sobre la rentabilidad por la caída de los precios de bitcoin. Como en la reciente fase en la que <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">el hashrate alcanzó máximos históricos mientras los ingresos de la minería se estrujaban</a>, los mineros con márgenes adelgazados difícilmente pueden permitirse una reubicación grande y costosa. Puede ampliarse la brecha entre grandes operadores con medios para trasladarse a Siberia en busca de energía barata y pequeños operadores que, incapaces de soportar ese coste, simplemente cierran. La prohibición, en otras palabras, actuará también como una presión que separa el grano de la paja dentro de la industria minera rusa.</p>
  <p class="de">Die Auswirkung dieser Verlagerung auf das globale Netzwerk erscheint begrenzt. Wenn Mining sich innerhalb Russlands bewegt, öffnet sich keine große Lücke in der Gesamt-Hashrate. Die Geschichte ändert sich jedoch, wenn sie sich mit dem jüngsten Druck auf die Profitabilität durch fallende Bitcoin-Preise überlagert. Wie in der jüngsten Phase, in der die <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">Hashrate Rekordhöhen erreichte, während die Mining-Erträge gequetscht wurden</a>, können sich Miner mit geschrumpften Margen eine große, kostspielige Verlagerung kaum leisten. Eine Kluft könnte sich auftun zwischen Großbetreibern mit den Mitteln, für billigen Strom nach Sibirien zu ziehen, und Kleinbetreibern, die diese Kosten nicht tragen können und einfach abschalten. Das Verbot wirkt mit anderen Worten auch als Druck, der innerhalb der russischen Mining-Industrie die Spreu vom Weizen trennt.</p>
  <p class="fr">L'impact de cette redistribution sur le réseau mondial paraît limité. Si le minage se déplace à l'intérieur de la Russie, aucun grand vide ne s'ouvre dans le hashrate total. L'histoire change toutefois lorsqu'elle se superpose à la récente pression sur la rentabilité due à la baisse des prix du bitcoin. Comme lors de la récente phase où <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">le hashrate a atteint des sommets records alors même que les revenus du minage étaient comprimés</a>, les mineurs aux marges amincies peuvent difficilement se permettre une relocalisation coûteuse et de grande ampleur. Un écart pourrait se creuser entre les grands opérateurs ayant les moyens de s'installer en Sibérie en quête d'électricité bon marché et les petits opérateurs qui, incapables d'en supporter le coût, cessent simplement leur activité. L'interdiction agira donc aussi, en d'autres termes, comme une pression qui sépare le bon grain de l'ivraie au sein de l'industrie minière russe.</p>
  <p class="pt">O impacto desta redistribuição na rede global parece limitado. Se a mineração se move dentro da Rússia, não se abre um grande vazio no hashrate total. A história muda, no entanto, quando se sobrepõe à recente pressão sobre a rentabilidade causada pela queda dos preços do bitcoin. Como na fase recente em que <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">o hashrate atingiu máximos históricos mesmo com a receita de mineração espremida</a>, mineradores com margens reduzidas dificilmente conseguem custear uma realocação grande e dispendiosa. Pode alargar-se o fosso entre grandes operadores com meios para se mudarem para a Sibéria em busca de energia barata e pequenos operadores que, incapazes de suportar esse custo, simplesmente encerram. A proibição, por outras palavras, também atuará como uma pressão que separa o trigo do joio dentro da indústria mineradora russa.</p>
  <p class="tr">Bu yeniden konumlandırmanın küresel ağ üzerindeki etkisi sınırlı görünüyor. Madencilik Rusya içinde hareket ediyorsa, toplam hashrate'te büyük bir boşluk açılmaz. Ancak bu durum, düşen bitcoin fiyatlarının kârlılık üzerindeki son baskısıyla çakıştığında hikaye değişir. <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">Hashrate rekor seviyelere ulaşırken madencilik gelirinin sıkıştığı</a> yakın dönemdeki gibi, marjları incelen madenciler büyük ve maliyetli bir taşınmayı pek karşılayamaz. Ucuz elektrik arayışıyla Sibirya'ya taşınacak imkâna sahip büyük işletmeciler ile bu maliyeti karşılayamayıp faaliyetini tamamen durduran küçük işletmeciler arasındaki uçurum genişleyebilir. Başka bir deyişle bu yasak, Rusya'nın madencilik sektöründe iyiyi kötüden ayıklayan bir baskı unsuru olarak da işlev görecek.</p>
  <p class="vi">Tác động của việc tái bố trí này lên mạng lưới toàn cầu có vẻ hạn chế. Nếu hoạt động khai thác chỉ di chuyển trong nội bộ nước Nga, tổng hashrate sẽ không xuất hiện khoảng trống lớn. Tuy nhiên câu chuyện sẽ khác khi nó trùng với áp lực gần đây lên lợi nhuận do giá bitcoin giảm. Giống như giai đoạn gần đây khi <a href="/blog/bitcoin-hashrate-record-miner-revenue-squeeze.php">hashrate đạt mức cao kỷ lục ngay cả khi doanh thu khai thác bị siết chặt</a>, những thợ đào có biên lợi nhuận mỏng khó có thể kham nổi một cuộc di dời lớn và tốn kém. Khoảng cách có thể nới rộng giữa các nhà vận hành lớn có đủ nguồn lực để chuyển tới Siberia tìm điện giá rẻ và các nhà vận hành nhỏ, do không chịu nổi chi phí đó, đơn giản là ngừng hoạt động. Nói cách khác, lệnh cấm cũng sẽ đóng vai trò như một áp lực sàng lọc, tách hạt lúa khỏi vỏ trấu trong ngành khai thác của Nga.</p>

  <h2 class="ko">무엇을 지켜봐야 하나</h2>
  <h2 class="en">What to watch</h2>
  <h2 class="ja">注視すべき点</h2>
  <h2 class="es">Qué vigilar</h2>
  <h2 class="de">Worauf zu achten ist</h2>
  <h2 class="fr">Ce qu'il faut surveiller</h2>
  <h2 class="pt">O que observar</h2>
  <h2 class="tr">Nelere dikkat edilmeli</h2>
  <h2 class="vi">Những điều cần theo dõi</h2>
  <p class="ko">세 가지를 지켜볼 만하다. 첫째, 집행의 실효성이다. 이 초안은 아직 정부 결의로 확정되지 않은 단계이며, 확정되더라도 실제 효과는 미등록 채굴을 얼마나 적발하느냐에 달려 있다. 전기 사용량 급증 패턴을 추적하는 계량 기반 단속이 뒷받침되지 않으면, 금지는 대형 합법 사업자만 몰아내고 지하 채굴은 오히려 음지로 더 깊이 숨는 역효과를 낳을 수 있다.</p>
  <p class="en">Three things are worth watching. First, the effectiveness of enforcement. This draft has not yet been finalized as a government resolution, and even once it is, its actual effect will depend on how much unregistered mining can be detected. Without metering-based enforcement that tracks spikes in electricity use, the ban may drive out only large legal operators while pushing underground mining deeper into the shadows — a perverse outcome.</p>
  <p class="ja">三つの点が注視に値する。第一に、執行の実効性だ。この草案はまだ政府決議として確定していない段階であり、確定しても実際の効果は未登録マイニングをどれだけ摘発できるかにかかっている。電気使用量の急増パターンを追う計量ベースの取締りが伴わなければ、禁止は大手の合法事業者だけを追い出し、地下マイニングはかえって陰に深く隠れるという逆効果を生みうる。</p>
  <p class="es">Tres cosas merecen atención. Primero, la eficacia de la ejecución. Este borrador aún no se ha formalizado como resolución gubernamental, y aun cuando lo haga, su efecto real dependerá de cuánta minería no registrada pueda detectarse. Sin una ejecución basada en la medición que rastree los picos de consumo eléctrico, la prohibición puede expulsar solo a los grandes operadores legales mientras empuja la minería subterránea más hacia las sombras: un resultado perverso.</p>
  <p class="de">Drei Dinge sind beobachtenswert. Erstens die Wirksamkeit der Durchsetzung. Dieser Entwurf ist noch nicht als Regierungsbeschluss verabschiedet, und selbst dann wird seine tatsächliche Wirkung davon abhängen, wie viel nicht registriertes Mining aufgedeckt werden kann. Ohne messungsbasierte Durchsetzung, die Spitzen im Stromverbrauch verfolgt, mag das Verbot nur große legale Betreiber vertreiben, während es das Untergrund-Mining tiefer in den Schatten drängt — ein perverses Ergebnis.</p>
  <p class="fr">Trois éléments méritent d'être suivis. Premièrement, l'efficacité de l'application. Ce projet n'a pas encore été finalisé sous forme de résolution gouvernementale, et même une fois cela fait, son effet réel dépendra de la capacité à détecter le minage non enregistré. Sans une application fondée sur la mesure, capable de repérer les pics de consommation électrique, l'interdiction risque de ne chasser que les grands opérateurs légaux tout en enfonçant le minage souterrain plus profondément dans l'ombre — un résultat pervers.</p>
  <p class="pt">Três aspetos merecem atenção. Primeiro, a eficácia da fiscalização. Este projeto ainda não foi finalizado como resolução governamental e, mesmo depois de o ser, o seu efeito real dependerá de quanta mineração não registada puder ser detetada. Sem uma fiscalização baseada na medição que rastreie picos no consumo de eletricidade, a proibição pode expulsar apenas os grandes operadores legais, ao mesmo tempo que empurra a mineração clandestina ainda mais para as sombras — um resultado perverso.</p>
  <p class="tr">Üç şey izlenmeye değer. Birincisi, uygulamanın etkinliği. Bu taslak henüz hükümet kararı olarak kesinleşmedi ve kesinleştiğinde bile gerçek etkisi, kayıt dışı madenciliğin ne kadarının tespit edilebileceğine bağlı olacak. Elektrik tüketimindeki ani artışları izleyen ölçüm tabanlı bir uygulama olmadan, yasak yalnızca büyük yasal işletmecileri kovup yeraltı madenciliğini gölgelere daha da gömebilir — ters bir sonuç.</p>
  <p class="vi">Có ba điều đáng theo dõi. Thứ nhất là hiệu quả thực thi. Dự thảo này chưa được hoàn tất thành nghị quyết chính thức của chính phủ, và ngay cả khi được thông qua, tác động thực tế của nó sẽ phụ thuộc vào việc phát hiện được bao nhiêu hoạt động khai thác không đăng ký. Nếu không có biện pháp thực thi dựa trên đo lường để theo dõi các đợt tăng đột biến trong tiêu thụ điện, lệnh cấm có thể chỉ đuổi được các nhà vận hành hợp pháp lớn trong khi đẩy hoạt động khai thác ngầm lún sâu hơn vào bóng tối — một kết quả trớ trêu.</p>
  <p class="ko">둘째, 러시아의 글로벌 해시레이트 점유율이다. 채굴이 국내에서 재배치되는 데 그친다면 세계 네트워크는 흔들리지 않지만, 규제 불확실성이 커지면 일부 자본은 아예 카자흐스탄이나 중동 등 국외로 빠져나갈 수도 있다. 러시아가 미국에 이은 채굴 강국 지위를 유지할지, 아니면 규제 리스크로 그 비중이 점진적으로 깎일지가 향후 수년의 관전 포인트다. 셋째, 다른 에너지 부족 국가로의 파급이다. 채굴을 산업으로 받아들이면서도 전력망 부담이 커지는 딜레마는 러시아만의 것이 아니다. 값싼 전기를 무기로 채굴을 유치했던 여러 신흥국이 겨울철 전력난이나 보조금 남용 문제에 부딪히면, '합법화 후 선별적 금지'라는 러시아식 이중 노선을 참고 모델로 삼을 가능성이 있다. 이번 조치는 그 실험의 가장 큰 사례로 기록될 것이다.</p>
  <p class="en">Second, Russia's share of global hashrate. If mining is merely redeployed domestically, the world network is not shaken, but as regulatory uncertainty grows, some capital may leave the country entirely for Kazakhstan, the Middle East and elsewhere. Whether Russia keeps its standing as a mining power behind the United States, or sees that weight gradually pared down by regulatory risk, is a viewing point for the coming years. Third, the ripple effect on other energy-short nations. The dilemma of embracing mining as an industry while grid strain mounts is not Russia's alone. If various emerging economies that lured mining with cheap electricity run into winter power crunches or subsidy abuse, they may take Russia's double track — "legalize, then selectively ban" — as a reference model. This measure will be recorded as the largest case of that experiment.</p>
  <p class="ja">第二に、ロシアのグローバルハッシュレート占有率だ。マイニングが国内で再配置されるにとどまれば世界のネットワークは揺らがないが、規制の不確実性が高まれば一部の資本はカザフスタンや中東など国外へ抜け出す可能性もある。ロシアが米国に次ぐマイニング大国の地位を保つのか、それとも規制リスクでその比重が徐々に削られるのかが、今後数年の観戦ポイントだ。第三に、他の電力不足国への波及だ。マイニングを産業として受け入れつつ電力網の負担が増すというジレンマはロシアだけのものではない。安い電気を武器にマイニングを誘致した複数の新興国が冬季の電力難や補助金の乱用問題に直面すれば、「合法化後の選別的禁止」というロシア式の二重路線を参考モデルとする可能性がある。今回の措置はその実験の最大の事例として記録されるだろう。</p>
  <p class="es">Segundo, la cuota de Rusia en el hashrate global. Si la minería solo se redistribuye a nivel nacional, la red mundial no se tambalea, pero a medida que crece la incertidumbre regulatoria, parte del capital puede abandonar el país por completo rumbo a Kazajistán, Oriente Medio y otros lugares. Que Rusia mantenga su posición como potencia minera por detrás de Estados Unidos, o que vea ese peso recortado gradualmente por el riesgo regulatorio, es un punto a observar en los próximos años. Tercero, el efecto dominó sobre otras naciones con escasez de energía. El dilema de abrazar la minería como industria mientras aumenta la presión sobre la red no es exclusivo de Rusia. Si diversas economías emergentes que atrajeron la minería con electricidad barata chocan con crisis eléctricas invernales o abusos de subsidios, podrían tomar la doble vía rusa —"legalizar y luego prohibir selectivamente"— como modelo de referencia. Esta medida quedará registrada como el mayor caso de ese experimento.</p>
  <p class="de">Zweitens Russlands Anteil an der globalen Hashrate. Wird Mining nur inländisch verlagert, gerät das Weltnetzwerk nicht ins Wanken, doch mit wachsender regulatorischer Unsicherheit könnte etwas Kapital das Land ganz verlassen — nach Kasachstan, in den Nahen Osten und anderswohin. Ob Russland seinen Rang als Mining-Macht hinter den USA behält oder dieses Gewicht durch Regulierungsrisiko allmählich beschnitten sieht, ist ein Beobachtungspunkt für die kommenden Jahre. Drittens der Dominoeffekt auf andere strommangelnde Nationen. Das Dilemma, Mining als Industrie anzunehmen, während der Netzdruck steigt, ist nicht Russlands allein. Wenn diverse Schwellenländer, die Mining mit billigem Strom anlockten, in winterliche Stromengpässe oder Subventionsmissbrauch geraten, könnten sie Russlands doppeltes Gleis — „legalisieren, dann selektiv verbieten" — als Referenzmodell nehmen. Diese Maßnahme wird als der größte Fall dieses Experiments verzeichnet werden.</p>
  <p class="fr">Deuxièmement, la part de la Russie dans le hashrate mondial. Si le minage n'est que redéployé au niveau national, le réseau mondial n'en est pas ébranlé, mais à mesure que l'incertitude réglementaire grandit, une partie des capitaux pourrait quitter entièrement le pays pour le Kazakhstan, le Moyen-Orient ou ailleurs. Que la Russie conserve son rang de puissance minière juste derrière les États-Unis, ou que ce poids soit progressivement rogné par le risque réglementaire, sera un point à observer dans les années à venir. Troisièmement, l'effet d'entraînement sur d'autres nations en déficit d'énergie. Le dilemme consistant à adopter le minage comme industrie tout en voyant la pression sur le réseau s'accroître n'est pas propre à la Russie. Si diverses économies émergentes, qui avaient attiré le minage grâce à une électricité bon marché, se heurtent à des pénuries d'électricité hivernales ou à des abus de subventions, elles pourraient prendre la double voie russe — « légaliser, puis interdire sélectivement » — comme modèle de référence. Cette mesure sera consignée comme le plus grand cas de cette expérience.</p>
  <p class="pt">Segundo, a quota da Rússia no hashrate global. Se a mineração é apenas redistribuída internamente, a rede mundial não é abalada, mas à medida que a incerteza regulatória cresce, parte do capital pode deixar totalmente o país rumo ao Cazaquistão, ao Médio Oriente e a outros lugares. Se a Rússia mantém a sua posição como potência mineradora atrás dos Estados Unidos, ou se vê esse peso gradualmente reduzido pelo risco regulatório, é um ponto a observar nos próximos anos. Terceiro, o efeito de contágio sobre outras nações com escassez de energia. O dilema de adotar a mineração como indústria enquanto a pressão sobre a rede aumenta não é exclusivo da Rússia. Se várias economias emergentes que atraíram a mineração com eletricidade barata se depararem com apertos de energia no inverno ou abusos de subsídios, poderão adotar a dupla via russa — “legalizar e depois proibir seletivamente” — como modelo de referência. Esta medida ficará registada como o maior caso dessa experiência.</p>
  <p class="tr">İkincisi, Rusya'nın küresel hashrate'teki payı. Madencilik yalnızca yurt içinde yeniden konumlandırılıyorsa dünya ağı sarsılmaz, ancak düzenleyici belirsizlik arttıkça bir miktar sermaye tamamen ülkeyi terk edip Kazakistan, Orta Doğu ve başka yerlere gidebilir. Rusya'nın ABD'nin ardından ikinci sıradaki madencilik gücü konumunu koruyup korumayacağı, yoksa bu ağırlığın düzenleyici risk yüzünden giderek azalıp azalmayacağı, önümüzdeki yıllar için izlenecek bir nokta. Üçüncüsü, diğer elektrik açığı çeken ülkelere yayılma etkisi. Madenciliği bir sektör olarak benimserken şebeke baskısının artması ikilemi yalnızca Rusya'ya özgü değil. Ucuz elektrikle madenciliği cezbeden çeşitli gelişmekte olan ekonomiler kışın elektrik sıkıntısı veya sübvansiyon istismarıyla karşılaşırsa, Rusya'nın çifte yolunu — "önce yasallaştır, sonra seçici biçimde yasakla" — referans model olarak alabilirler. Bu önlem, o deneyin en büyük örneği olarak kayda geçecek.</p>
  <p class="vi">Thứ hai là thị phần hashrate toàn cầu của Nga. Nếu hoạt động khai thác chỉ đơn thuần được tái bố trí trong nước, mạng lưới thế giới sẽ không bị lung lay, nhưng khi tính bất định về pháp lý gia tăng, một phần vốn có thể rời khỏi đất nước hoàn toàn để tới Kazakhstan, Trung Đông và các nơi khác. Việc Nga có giữ được vị thế cường quốc khai thác đứng sau Hoa Kỳ hay để trọng số đó dần bị bào mòn bởi rủi ro pháp lý là điểm cần theo dõi trong những năm tới. Thứ ba là hiệu ứng lan tỏa tới các quốc gia thiếu điện khác. Nghịch lý giữa việc đón nhận khai thác như một ngành công nghiệp trong khi áp lực lên lưới điện gia tăng không phải chỉ riêng Nga gặp phải. Nếu nhiều nền kinh tế mới nổi từng thu hút hoạt động khai thác bằng điện giá rẻ gặp phải tình trạng thiếu điện mùa đông hoặc lạm dụng trợ cấp, họ có thể lấy hướng đi song song của Nga — "hợp pháp hóa rồi cấm chọn lọc" — làm mô hình tham chiếu. Biện pháp này sẽ được ghi nhận là trường hợp lớn nhất của thử nghiệm đó.</p>

  <div class="box ko">💡 <strong>시사점:</strong> 러시아의 모스크바권 채굴 금지는 '합법화 후 선별적 금지'라는 이중 노선의 확장판이다. 채굴을 산업으로 인정해 파악 가능하게 만든 뒤, 전력이 부족한 지역만 골라 잘라내는 방식이다. 글로벌 해시레이트에 미칠 충격은 제한적이겠지만, 값싼 전기를 따라 채굴이 이동한다는 오래된 법칙과, 에너지-산업 딜레마에 부딪힌 국가들의 참고 모델이라는 점에서 지켜볼 사건이다.</div>
  <div class="box en">💡 <strong>Takeaway:</strong> Russia's ban on mining in the Moscow area is an expanded version of a double track — "legalize, then selectively ban." First recognize mining as an industry to make it visible, then surgically cut only the power-short regions. The shock to global hashrate will be limited, but it is worth watching for the old law that mining migrates toward cheap power, and as a reference model for nations caught in the energy-versus-industry dilemma.</div>
  <div class="box ja">💡 <strong>示唆:</strong> ロシアのモスクワ圏マイニング禁止は「合法化後の選別的禁止」という二重路線の拡張版だ。マイニングを産業として認めて把握可能にした後、電力の足りない地域だけを選んで切り取る方式である。グローバルハッシュレートへの衝撃は限定的だろうが、安い電気を追ってマイニングが移動するという古い法則と、エネルギー・産業のジレンマに直面する国々の参考モデルという点で注視すべき事件だ。</div>
  <div class="box es">💡 <strong>Conclusión:</strong> La prohibición de la minería en el área de Moscú por parte de Rusia es una versión ampliada de una doble vía: "legalizar y luego prohibir selectivamente". Primero reconocer la minería como industria para hacerla visible, luego cortar quirúrgicamente solo las regiones con escasez de energía. El impacto sobre el hashrate global será limitado, pero merece atención por la vieja ley de que la minería migra hacia la energía barata y como modelo de referencia para las naciones atrapadas en el dilema energía-industria.</div>
  <div class="box de">💡 <strong>Fazit:</strong> Russlands Mining-Verbot im Moskauer Raum ist eine erweiterte Version eines doppelten Gleises — „legalisieren, dann selektiv verbieten". Zuerst Mining als Industrie anerkennen, um es sichtbar zu machen, dann chirurgisch nur die strommangelnden Regionen herausschneiden. Der Schock für die globale Hashrate wird begrenzt sein, doch die Maßnahme ist beobachtenswert wegen des alten Gesetzes, dass Mining zur billigen Energie wandert, und als Referenzmodell für Nationen im Dilemma zwischen Energie und Industrie.</div>
  <div class="box fr">💡 <strong>À retenir :</strong> L'interdiction du minage dans la région de Moscou par la Russie est une version élargie d'une double voie — « légaliser, puis interdire sélectivement ». D'abord reconnaître le minage comme une industrie pour le rendre visible, puis découper chirurgicalement les seules régions en déficit d'électricité. Le choc sur le hashrate mondial sera limité, mais l'événement mérite d'être suivi en raison de la vieille loi selon laquelle le minage migre vers l'électricité bon marché, et comme modèle de référence pour les nations prises dans le dilemme entre énergie et industrie.</div>
  <div class="box pt">💡 <strong>Conclusão:</strong> A proibição da mineração na área de Moscou pela Rússia é uma versão ampliada de uma dupla via — “legalizar e depois proibir seletivamente”. Primeiro reconhecer a mineração como indústria para a tornar visível, depois cortar cirurgicamente apenas as regiões com escassez de energia. O choque no hashrate global será limitado, mas o episódio merece atenção pela velha lei de que a mineração migra para a energia barata, e como modelo de referência para nações presas no dilema entre energia e indústria.</div>
  <div class="box tr">💡 <strong>Çıkarım:</strong> Rusya'nın Moskova bölgesindeki madencilik yasağı, "önce yasallaştır, sonra seçici biçimde yasakla" çifte yolunun genişletilmiş bir versiyonudur. Önce madenciliği bir sektör olarak tanıyıp görünür kılmak, ardından yalnızca elektrik açığı çeken bölgeleri cerrahi biçimde kesip atmak. Küresel hashrate üzerindeki şok sınırlı olacak, ancak madenciliğin ucuz enerjinin peşinden gittiğine dair eski kural ve enerji-sektör ikilemine yakalanan ülkeler için bir referans model olması bakımından izlenmeye değer bir olay.</div>
  <div class="box vi">💡 <strong>Điểm rút ra:</strong> Lệnh cấm khai thác của Nga tại khu vực Moskva là phiên bản mở rộng của hướng đi song song — "hợp pháp hóa rồi cấm chọn lọc." Trước tiên công nhận khai thác là một ngành công nghiệp để có thể giám sát, sau đó cắt bỏ chính xác chỉ những vùng thiếu điện. Cú sốc đối với hashrate toàn cầu sẽ hạn chế, nhưng đây là sự kiện đáng theo dõi vì quy luật xưa nay rằng hoạt động khai thác di chuyển theo nguồn điện giá rẻ, và vì đây là mô hình tham chiếu cho các quốc gia mắc kẹt trong nghịch lý năng lượng và công nghiệp.</div>

  <p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 러시아 국영통신 타스(TASS), 인테르팍스(Interfax), 러시아 에너지부 결의안 초안, CryptoRank, DL News, crypto.news, KuCoin 뉴스. 데이터센터 수·전력 소비량과 금지 지역 목록은 에너지부 초안 및 각 매체 보도에 따른 것이며, 초안은 아직 정부 결의로 최종 확정되지 않았다.</p>
  <p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Russian state agencies TASS and Interfax, the Energy Ministry's draft resolution, CryptoRank, DL News, crypto.news, KuCoin news. Data-center counts, power consumption and the list of banned regions follow the ministry's draft and the respective outlets; the draft has not yet been finalized as a government resolution.</p>
  <p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: ロシア国営通信タス(TASS)、インテルファクス(Interfax)、ロシア・エネルギー省の決議案草案、CryptoRank、DL News、crypto.news、KuCoinニュース。データセンター数・電力消費量および禁止地域の一覧はエネルギー省の草案および各媒体の報道に基づくもので、草案はまだ政府決議として最終確定していない。</p>
  <p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: agencias estatales rusas TASS e Interfax, el borrador de resolución del Ministerio de Energía, CryptoRank, DL News, crypto.news, noticias de KuCoin. El número de centros de datos, el consumo de energía y la lista de regiones prohibidas siguen el borrador del ministerio y los respectivos medios; el borrador aún no se ha formalizado como resolución gubernamental.</p>
  <p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: die russischen Staatsagenturen TASS und Interfax, der Beschlussentwurf des Energieministeriums, CryptoRank, DL News, crypto.news, KuCoin-Nachrichten. Rechenzentrumszahlen, Stromverbrauch und die Liste der Verbotsregionen folgen dem Entwurf des Ministeriums und den jeweiligen Medien; der Entwurf ist noch nicht als Regierungsbeschluss verabschiedet.</p>
  <p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : les agences d'État russes TASS et Interfax, le projet de résolution du ministère de l'Énergie, CryptoRank, DL News, crypto.news, KuCoin News. Le nombre de centres de données, la consommation d'électricité et la liste des régions interdites suivent le projet du ministère et les médias respectifs ; le projet n'a pas encore été finalisé sous forme de résolution gouvernementale.</p>
  <p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: as agências estatais russas TASS e Interfax, o projeto de resolução do Ministério da Energia, CryptoRank, DL News, crypto.news, KuCoin News. O número de centros de dados, o consumo de energia e a lista de regiões proibidas seguem o projeto do ministério e os respetivos meios de comunicação; o projeto ainda não foi finalizado como resolução governamental.</p>
  <p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: Rus devlet ajansları TASS ve Interfax, Enerji Bakanlığı'nın karar taslağı, CryptoRank, DL News, crypto.news, KuCoin News. Veri merkezi sayıları, elektrik tüketimi ve yasaklı bölgeler listesi, bakanlığın taslağına ve ilgili haber kaynaklarına dayanmaktadır; taslak henüz hükümet kararı olarak kesinleşmemiştir.</p>
  <p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: các hãng thông tấn nhà nước Nga TASS và Interfax, dự thảo nghị quyết của Bộ Năng lượng, CryptoRank, DL News, crypto.news, tin tức KuCoin. Số lượng trung tâm dữ liệu, mức tiêu thụ điện và danh sách các vùng bị cấm được lấy theo dự thảo của bộ và các nguồn tin tương ứng; dự thảo này chưa được hoàn tất thành nghị quyết chính thức của chính phủ.</p>

<?php require __DIR__.'/_footer.php'; ?>
