<?php $slug = 'terawulf-anthropic-ai-datacenter-lease'; require __DIR__.'/_header.php'; ?>

<p class="ko">비트코인 채굴기업 테라울프(TeraWulf·나스닥 WULF)가 켄터키주 호크스빌의 '저스티파이드 데이터(Justified Data)' 캠퍼스를 인공지능(AI) 기업 앤트로픽(Anthropic)에 20년간 임대하는 계약을 체결했다고 7월 6일 밝혔다. 회사는 이 임대가 초기 계약 기간에 약 190억 달러의 계약 매출을 창출할 것으로 예상한다고 발표했다. 같은 날 테라울프는 애버내시(Abernathy) 합작법인의 과반 지분을 플루이드스택(Fluidstack) 주도 컨소시엄에 약 5억3,000만 달러에 매각했으며, 발표 직후 주가는 17% 넘게 급등했다고 로이터·CNBC가 전했다. 비트코인을 채굴하던 회사가 그 전력 인프라를 AI 연산에 내주는, 업계 전반의 전환을 상징하는 거래다.</p>
  <p class="en">Bitcoin miner TeraWulf (Nasdaq: WULF) said on July 6 that it had signed a 20-year lease to rent its "Justified Data" campus in Hawesville, Kentucky, to the artificial-intelligence firm Anthropic. The company said the lease is expected to generate roughly $19 billion of contracted revenue over its initial term. On the same day, TeraWulf sold the majority stake in its Abernathy joint venture to a Fluidstack-led consortium for about $530 million, and its shares jumped more than 17% after the announcement, Reuters and CNBC reported. It is a deal that symbolizes an industry-wide shift, as a company that mined bitcoin hands its power infrastructure over to AI computation.</p>
  <p class="ja">ビットコイン採掘企業テラウルフ(TeraWulf、ナスダック:WULF)は7月6日、ケンタッキー州ホークスビルの「ジャスティファイド・データ(Justified Data)」キャンパスを人工知能(AI)企業アンスロピック(Anthropic)に20年間リースする契約を締結したと発表した。会社はこのリースが初期契約期間に約190億ドルの契約売上を生むと見込むとした。同日、テラウルフはアバナシー(Abernathy)合弁法人の過半数持分をフルイドスタック(Fluidstack)主導の陣営に約5億3,000万ドルで売却し、発表直後に株価は17%超急騰したとロイター・CNBCが伝えた。ビットコインを採掘していた企業がその電力インフラをAI計算に明け渡す、業界全体の転換を象徴する取引だ。</p>
  <p class="es">El minero de Bitcoin TeraWulf (Nasdaq: WULF) dijo el 6 de julio que había firmado un arrendamiento a 20 años para alquilar su campus "Justified Data" en Hawesville, Kentucky, a la firma de inteligencia artificial (IA) Anthropic. La empresa señaló que se espera que el contrato genere unos 19.000 millones de dólares en ingresos contratados durante su plazo inicial. El mismo día, TeraWulf vendió la participación mayoritaria en su empresa conjunta Abernathy a un consorcio liderado por Fluidstack por unos 530 millones de dólares, y sus acciones subieron más del 17% tras el anuncio, informaron Reuters y CNBC. Es un acuerdo que simboliza un giro en toda la industria, cuando una empresa que minaba bitcoin cede su infraestructura eléctrica al cómputo de IA.</p>
  <p class="de">Der Bitcoin-Miner TeraWulf (Nasdaq: WULF) teilte am 6. Juli mit, einen 20-Jahres-Mietvertrag unterzeichnet zu haben, um seinen Campus „Justified Data" in Hawesville, Kentucky, an das Unternehmen für künstliche Intelligenz (KI) Anthropic zu vermieten. Das Unternehmen erklärte, der Vertrag werde über seine anfängliche Laufzeit voraussichtlich rund 19 Milliarden Dollar an vertraglich gesicherten Einnahmen erbringen. Am selben Tag verkaufte TeraWulf die Mehrheitsbeteiligung an seinem Abernathy-Joint-Venture an ein von Fluidstack geführtes Konsortium für rund 530 Millionen Dollar, und die Aktie sprang nach der Ankündigung um mehr als 17%, wie Reuters und CNBC berichteten. Es ist ein Deal, der einen branchenweiten Wandel symbolisiert: Ein Unternehmen, das Bitcoin schürfte, überlässt seine Strominfrastruktur der KI-Berechnung.</p>
  <p class="fr">Le mineur de bitcoin TeraWulf (Nasdaq : WULF) a annoncé le 6 juillet avoir signé un bail de 20 ans pour louer son campus « Justified Data » à Hawesville, dans le Kentucky, à la société d'intelligence artificielle (IA) Anthropic. L'entreprise a indiqué que ce bail devrait générer environ 19 milliards de dollars de revenus contractuels sur sa durée initiale. Le même jour, TeraWulf a vendu la participation majoritaire de sa coentreprise Abernathy à un consortium mené par Fluidstack pour environ 530 millions de dollars, et son action a bondi de plus de 17 % après l'annonce, ont rapporté Reuters et CNBC. Il s'agit d'un accord qui symbolise un basculement à l'échelle du secteur, une entreprise qui minait du bitcoin cédant désormais son infrastructure électrique au calcul d'IA.</p>
  <p class="pt">A mineradora de bitcoin TeraWulf (Nasdaq: WULF) informou em 6 de julho ter assinado um contrato de arrendamento de 20 anos para alugar seu campus "Justified Data" em Hawesville, Kentucky, à empresa de inteligência artificial (IA) Anthropic. A empresa disse que o contrato deve gerar cerca de 19 bilhões de dólares em receita contratada ao longo de seu prazo inicial. No mesmo dia, a TeraWulf vendeu a participação majoritária em sua joint venture Abernathy a um consórcio liderado pela Fluidstack por cerca de 530 milhões de dólares, e suas ações saltaram mais de 17% após o anúncio, segundo a Reuters e a CNBC. É um negócio que simboliza uma mudança em todo o setor, com uma empresa que minerava bitcoin repassando sua infraestrutura elétrica para a computação de IA.</p>
  <p class="tr">Bitcoin madencisi TeraWulf (Nasdaq: WULF), 6 Temmuz'da Kentucky eyaletindeki Hawesville'de bulunan "Justified Data" kampüsünü yapay zeka (AI) şirketi Anthropic'e 20 yıllığına kiraladığına dair bir sözleşme imzaladığını açıkladı. Şirket, bu kira sözleşmesinin ilk dönem boyunca yaklaşık 19 milyar dolarlık sözleşmeye bağlı gelir yaratmasının beklendiğini belirtti. Aynı gün TeraWulf, Abernathy ortak girişimindeki çoğunluk hissesini Fluidstack liderliğindeki bir konsorsiyuma yaklaşık 530 milyon dolara sattı ve Reuters ile CNBC'nin haberine göre açıklamanın ardından hisseleri yüzde 17'den fazla yükseldi. Bu, bitcoin madenciliği yapan bir şirketin güç altyapısını yapay zeka hesaplamasına devretmesiyle sektör genelindeki bir dönüşümü simgeleyen bir anlaşma.</p>
  <p class="vi">Công ty khai thác bitcoin TeraWulf (Nasdaq: WULF) cho biết vào ngày 6 tháng 7 rằng họ đã ký hợp đồng thuê 20 năm để cho công ty trí tuệ nhân tạo (AI) Anthropic thuê khuôn viên "Justified Data" tại Hawesville, bang Kentucky. Công ty cho biết hợp đồng thuê này dự kiến sẽ tạo ra khoảng 19 tỷ đô la doanh thu theo hợp đồng trong thời hạn ban đầu. Cùng ngày, TeraWulf đã bán cổ phần đa số trong liên doanh Abernathy cho một tập đoàn do Fluidstack dẫn đầu với giá khoảng 530 triệu đô la, và cổ phiếu của công ty đã tăng vọt hơn 17% sau thông báo này, theo Reuters và CNBC. Đây là một thỏa thuận tượng trưng cho sự chuyển dịch trên toàn ngành, khi một công ty từng khai thác bitcoin nay giao cơ sở hạ tầng điện năng của mình cho việc tính toán AI.</p>

  <h2 class="ko">무엇이 발표됐나</h2>
  <h2 class="en">What was announced</h2>
  <h2 class="ja">何が発表されたのか</h2>
  <h2 class="es">Qué se anunció</h2>
  <h2 class="de">Was wurde angekündigt</h2>
  <h2 class="fr">Ce qui a été annoncé</h2>
  <h2 class="pt">O que foi anunciado</h2>
  <h2 class="tr">Ne açıklandı</h2>
  <h2 class="vi">Điều gì đã được công bố</h2>
  <p class="ko">테라울프가 공개한 자료에 따르면 임대 대상인 저스티파이드 데이터 캠퍼스는 최대 약 401메가와트(MW)의 핵심 IT 부하를 수용하도록 여러 단계로 개발된다. 초기 용량은 2027년 하반기에 가동에 들어가고, 2028년 초까지 401MW 전체로 확장될 예정이다. 회사는 이 임대가 투자등급 신용 구조로 뒷받침된다고 밝혀, 20년이라는 장기 계약의 안정성을 강조했다. 폴 프레이거(Paul Prager) 회장 겸 최고경영자는 "2월 저스티파이드 데이터 캠퍼스 인수를 발표하며 2분기 말께 주요 고객 계약을 확보할 것으로 기대한다고 투자자에게 밝혔다"고 말해, 이번 계약이 예고된 로드맵의 실현임을 부각했다.</p>
  <p class="ko">거래는 단일 임대에 그치지 않았다. 테라울프는 같은 날 168MW 규모 애버내시 합작법인의 지분 50.1%를 플루이드스택이 이끄는 컨소시엄에 약 5억3,000만 달러에 매각했다. 회사가 이 합작에 투입한 자본은 약 4억5,000만 달러로 알려져, 투입 대비 프리미엄을 얹어 회수하며 100% 소유의 AI 인프라 확장에 쓸 실탄을 확보한 셈이다. 여기에 뉴욕주 레이크 마리너(Lake Mariner) 캠퍼스는 가동 이후 구글이 보증인으로 나서기로 하면서 구글의 총 보증 규모가 약 32억 달러로, 지분율은 약 14%로 늘었다. 앤트로픽·플루이드스택·구글이라는 세 갈래의 대형 파트너가 한 채굴기업의 재무 구조에 동시에 얽힌 것이다.</p>
  <p class="en">According to TeraWulf's disclosure, the leased Justified Data campus will be built out in multiple phases to house up to about 401 megawatts (MW) of critical IT load. Initial capacity is due to enter service in the second half of 2027 and to ramp to the full 401 MW by early 2028. The company said the lease is backed by an investment-grade credit structure, underscoring the stability of a 20-year commitment. Chairman and CEO Paul Prager said, "When we announced the Justified Data campus acquisition in February, we told investors that we expected to secure a major customer commitment by around the end of the second quarter of 2026," framing the deal as the delivery of a promised roadmap.</p>
  <p class="en">The transaction did not stop at a single lease. On the same day, TeraWulf sold a 50.1% stake in its 168 MW Abernathy joint venture to a Fluidstack-led consortium for about $530 million. The company had reportedly invested roughly $450 million in that venture, so it recouped its capital at a premium and freed up dry powder to expand wholly owned AI infrastructure. On top of that, its Lake Mariner campus in New York will be backed by Google as guarantor once operational, lifting Google's total backstop to about $3.2 billion and its pro forma equity stake to roughly 14%. Three large partners — Anthropic, Fluidstack and Google — are now simultaneously entangled in a single miner's financial structure.</p>
  <p class="ja">テラウルフの開示によれば、リース対象のジャスティファイド・データ・キャンパスは最大約401メガワット(MW)の重要IT負荷を収容できるよう複数段階で開発される。初期容量は2027年下半期に稼働し、2028年初めまでに401MW全体へ拡張される予定だ。会社はこのリースが投資適格の信用構造で裏付けられていると述べ、20年という長期契約の安定性を強調した。ポール・プレーガー会長兼最高経営責任者は「2月にジャスティファイド・データ・キャンパスの取得を発表した際、第2四半期末ごろに主要顧客の契約を確保すると投資家に伝えていた」と述べ、今回の契約が予告済みのロードマップの実現であることを際立たせた。</p>
  <p class="ja">取引は単一のリースにとどまらなかった。テラウルフは同日、168MW規模のアバナシー合弁法人の持分50.1%をフルイドスタック主導の陣営に約5億3,000万ドルで売却した。会社がこの合弁に投じた資本は約4億5,000万ドルとされ、投入分にプレミアムを乗せて回収し、100%所有のAIインフラ拡張に充てる資金を確保した格好だ。さらにニューヨーク州のレイク・マリナー・キャンパスは稼働後にグーグルが保証人となることで、グーグルの総保証規模は約32億ドル、持分は約14%へと増えた。アンスロピック・フルイドスタック・グーグルという三つの大手パートナーが、一つの採掘企業の財務構造に同時に絡んだのである。</p>
  <p class="es">Según la divulgación de TeraWulf, el campus arrendado Justified Data se construirá en varias fases para albergar hasta unos 401 megavatios (MW) de carga informática crítica. La capacidad inicial entrará en servicio en la segunda mitad de 2027 y alcanzará los 401 MW completos a principios de 2028. La empresa dijo que el arrendamiento está respaldado por una estructura crediticia de grado de inversión, subrayando la estabilidad de un compromiso a 20 años. El presidente y consejero delegado Paul Prager afirmó: "Cuando anunciamos la adquisición del campus Justified Data en febrero, dijimos a los inversores que esperábamos asegurar el compromiso de un gran cliente hacia finales del segundo trimestre de 2026", presentando el acuerdo como la entrega de una hoja de ruta prometida.</p>
  <p class="es">La operación no se limitó a un solo arrendamiento. El mismo día, TeraWulf vendió una participación del 50,1% en su empresa conjunta Abernathy de 168 MW a un consorcio liderado por Fluidstack por unos 530 millones de dólares. La empresa habría invertido cerca de 450 millones en esa sociedad, de modo que recuperó su capital con una prima y liberó munición para expandir infraestructura de IA de propiedad total. Además, su campus Lake Mariner en Nueva York contará con Google como garante una vez operativo, elevando el respaldo total de Google a unos 3.200 millones de dólares y su participación proforma a cerca del 14%. Tres grandes socios —Anthropic, Fluidstack y Google— están ahora entrelazados simultáneamente en la estructura financiera de un solo minero.</p>
  <p class="de">Laut der Offenlegung von TeraWulf wird der gemietete Justified-Data-Campus in mehreren Phasen ausgebaut, um bis zu rund 401 Megawatt (MW) kritischer IT-Last aufzunehmen. Die anfängliche Kapazität soll in der zweiten Hälfte 2027 in Betrieb gehen und bis Anfang 2028 auf die vollen 401 MW hochgefahren werden. Das Unternehmen erklärte, der Mietvertrag werde durch eine Kreditstruktur mit Investment-Grade gestützt, was die Stabilität einer 20-Jahres-Verpflichtung unterstreiche. Vorstandsvorsitzender und CEO Paul Prager sagte: „Als wir im Februar den Erwerb des Justified-Data-Campus ankündigten, teilten wir den Investoren mit, dass wir bis etwa Ende des zweiten Quartals 2026 die Zusage eines großen Kunden erwarteten", und stellte den Deal so als Einlösung eines versprochenen Fahrplans dar.</p>
  <p class="fr">Selon les informations communiquées par TeraWulf, le campus Justified Data loué sera aménagé en plusieurs phases pour accueillir jusqu'à environ 401 mégawatts (MW) de charge informatique critique. La capacité initiale doit entrer en service au second semestre 2027 et monter en puissance jusqu'aux 401 MW complets d'ici début 2028. L'entreprise a précisé que ce bail est adossé à une structure de crédit de qualité « investment grade », soulignant la solidité d'un engagement sur 20 ans. Le président-directeur général Paul Prager a déclaré : « Lorsque nous avons annoncé l'acquisition du campus Justified Data en février, nous avions indiqué aux investisseurs que nous espérions obtenir l'engagement d'un client majeur vers la fin du deuxième trimestre 2026 », présentant l'accord comme la concrétisation d'une feuille de route promise.</p>
  <p class="pt">Segundo a divulgação da TeraWulf, o campus arrendado Justified Data será construído em várias fases para abrigar até cerca de 401 megawatts (MW) de carga de TI crítica. A capacidade inicial deve entrar em operação no segundo semestre de 2027 e chegar aos 401 MW completos até o início de 2028. A empresa disse que o contrato é respaldado por uma estrutura de crédito de grau de investimento, reforçando a estabilidade de um compromisso de 20 anos. O presidente e CEO Paul Prager afirmou: "Quando anunciamos a aquisição do campus Justified Data em fevereiro, dissemos aos investidores que esperávamos garantir o compromisso de um grande cliente por volta do fim do segundo trimestre de 2026", apresentando o acordo como a concretização de um roteiro prometido.</p>
  <p class="tr">TeraWulf'un açıklamasına göre, kiralanan Justified Data kampüsü, yaklaşık 401 megavata (MW) kadar kritik BT yükünü barındıracak şekilde çok aşamalı olarak inşa edilecek. İlk kapasitenin 2027'nin ikinci yarısında hizmete girmesi ve 2028'in başına kadar tam 401 MW'a çıkması bekleniyor. Şirket, bu kira sözleşmesinin yatırım yapılabilir düzeyde bir kredi yapısıyla desteklendiğini, bunun da 20 yıllık taahhüdün istikrarını güçlendirdiğini belirtti. Yönetim Kurulu Başkanı ve CEO Paul Prager, "Şubat ayında Justified Data kampüsünün satın alınmasını duyurduğumuzda, yatırımcılara 2026'nın ikinci çeyreğinin sonuna doğru büyük bir müşteri taahhüdü güvence altına almayı beklediğimizi söylemiştik" diyerek anlaşmayı vadedilmiş bir yol haritasının gerçekleşmesi olarak sundu.</p>
  <p class="vi">Theo thông tin công bố của TeraWulf, khuôn viên Justified Data được cho thuê sẽ được xây dựng theo nhiều giai đoạn để chứa tải trọng CNTT quan trọng lên tới khoảng 401 megawatt (MW). Công suất ban đầu dự kiến đi vào hoạt động trong nửa cuối năm 2027 và nâng lên toàn bộ 401 MW vào đầu năm 2028. Công ty cho biết hợp đồng thuê được hậu thuẫn bởi một cấu trúc tín dụng ở mức đầu tư (investment-grade), nhấn mạnh sự ổn định của cam kết kéo dài 20 năm. Chủ tịch kiêm Giám đốc điều hành Paul Prager cho biết: "Khi chúng tôi công bố việc mua lại khuôn viên Justified Data vào tháng 2, chúng tôi đã nói với các nhà đầu tư rằng chúng tôi kỳ vọng sẽ đảm bảo được cam kết từ một khách hàng lớn vào khoảng cuối quý hai năm 2026", qua đó định hình thỏa thuận này như việc hiện thực hóa một lộ trình đã hứa hẹn.</p>
  <p class="de">Die Transaktion blieb nicht bei einem einzigen Mietvertrag. Am selben Tag verkaufte TeraWulf einen Anteil von 50,1% an seinem 168-MW-Abernathy-Joint-Venture an ein von Fluidstack geführtes Konsortium für rund 530 Millionen Dollar. Das Unternehmen hatte Berichten zufolge etwa 450 Millionen Dollar in dieses Vorhaben investiert, holte sein Kapital also mit einem Aufschlag zurück und schuf sich Spielraum, um vollständig eigene KI-Infrastruktur auszubauen. Hinzu kommt, dass sein Campus Lake Mariner in New York nach der Inbetriebnahme von Google als Garant abgesichert wird, wodurch Googles Gesamtabsicherung auf rund 3,2 Milliarden Dollar und sein Pro-forma-Anteil auf etwa 14% steigt. Drei große Partner — Anthropic, Fluidstack und Google — sind nun gleichzeitig in die Finanzstruktur eines einzigen Miners verflochten.</p>
  <p class="fr">L'opération ne s'est pas arrêtée à un seul bail. Le même jour, TeraWulf a cédé une participation de 50,1 % dans sa coentreprise Abernathy, d'une capacité de 168 MW, à un consortium mené par Fluidstack, pour environ 530 millions de dollars. L'entreprise aurait investi environ 450 millions de dollars dans cette coentreprise ; elle a donc récupéré son capital avec une prime et dégagé des liquidités pour développer une infrastructure d'IA détenue à 100 %. À cela s'ajoute le fait que son campus Lake Mariner, dans l'État de New York, sera garanti par Google une fois opérationnel, portant le soutien total de Google à environ 3,2 milliards de dollars et sa participation pro forma à environ 14 %. Trois grands partenaires — Anthropic, Fluidstack et Google — se retrouvent désormais simultanément imbriqués dans la structure financière d'un seul mineur.</p>
  <p class="pt">A transação não parou em um único arrendamento. No mesmo dia, a TeraWulf vendeu uma participação de 50,1% em sua joint venture Abernathy, de 168 MW, a um consórcio liderado pela Fluidstack por cerca de 530 milhões de dólares. Segundo relatos, a empresa havia investido cerca de 450 milhões de dólares nesse empreendimento, de modo que recuperou seu capital com um prêmio e liberou recursos para expandir uma infraestrutura de IA de propriedade integral. Além disso, seu campus Lake Mariner, em Nova York, contará com o aval do Google como garantidor assim que entrar em operação, elevando o respaldo total do Google para cerca de 3,2 bilhões de dólares e sua participação acionária pro forma para cerca de 14%. Três grandes parceiros — Anthropic, Fluidstack e Google — estão agora simultaneamente entrelaçados na estrutura financeira de uma única mineradora.</p>
  <p class="tr">İşlem tek bir kira sözleşmesiyle sınırlı kalmadı. Aynı gün TeraWulf, 168 MW'lık Abernathy ortak girişimindeki yüzde 50,1'lik hissesini Fluidstack liderliğindeki bir konsorsiyuma yaklaşık 530 milyon dolara sattı. Şirketin bu girişime yaklaşık 450 milyon dolar yatırdığı bildiriliyor; dolayısıyla sermayesini bir prim ile geri kazandı ve tamamen kendisine ait yapay zeka altyapısını genişletmek için kaynak serbest bıraktı. Bunun yanında, New York eyaletindeki Lake Mariner kampüsü faaliyete geçtiğinde Google'ın garantörlüğünde olacak; bu da Google'ın toplam teminatını yaklaşık 3,2 milyar dolara, pro forma hisse payını ise yaklaşık yüzde 14'e çıkarıyor. Anthropic, Fluidstack ve Google olmak üzere üç büyük ortak, artık tek bir madencilik şirketinin mali yapısında aynı anda iç içe geçmiş durumda.</p>
  <p class="vi">Giao dịch không dừng lại ở một hợp đồng thuê duy nhất. Cùng ngày, TeraWulf đã bán 50,1% cổ phần trong liên doanh Abernathy công suất 168 MW cho một tập đoàn do Fluidstack dẫn đầu với giá khoảng 530 triệu đô la. Theo thông tin, công ty đã đầu tư khoảng 450 triệu đô la vào liên doanh này, do đó đã thu hồi vốn kèm khoản chênh lệch và giải phóng nguồn lực để mở rộng cơ sở hạ tầng AI thuộc sở hữu hoàn toàn. Thêm vào đó, khuôn viên Lake Mariner tại New York sẽ được Google bảo lãnh một khi đi vào hoạt động, nâng tổng mức bảo lãnh của Google lên khoảng 3,2 tỷ đô la và tỷ lệ sở hữu cổ phần pro forma của họ lên khoảng 14%. Ba đối tác lớn — Anthropic, Fluidstack và Google — giờ đây cùng lúc đan xen trong cấu trúc tài chính của một công ty khai thác duy nhất.</p>

  <h2 class="ko">채굴기업이 왜 AI의 집주인이 되나 — 작동 원리</h2>
  <h2 class="en">Why a miner becomes AI's landlord — how it works</h2>
  <h2 class="ja">採掘企業がなぜAIの大家になるのか — 作動原理</h2>
  <h2 class="es">Por qué un minero se vuelve el casero de la IA — cómo funciona</h2>
  <h2 class="de">Warum ein Miner zum Vermieter der KI wird — wie es funktioniert</h2>
  <h2 class="fr">Pourquoi un mineur devient le bailleur de l'IA — le mécanisme</h2>
  <h2 class="pt">Por que uma mineradora se torna a senhoria da IA — como funciona</h2>
  <h2 class="tr">Bir madenci neden yapay zekanın ev sahibi oluyor — nasıl işliyor</h2>
  <h2 class="vi">Vì sao một công ty khai thác trở thành chủ nhà của AI — cơ chế hoạt động</h2>
  <p class="ko">한 단계 더 들어가면 이 거래의 핵심은 GPU도, 비트코인도 아닌 '전력'이다. 대규모 AI 학습·추론에서 가장 희소한 자원은 반도체가 아니라, 즉시 끌어 쓸 수 있는 대용량 전력과 그 전력을 받을 수 있는 계통 연결(grid interconnection)이다. 미국에서 신규 대형 부하의 계통 연결 승인은 수년이 걸리는데, 비트코인 채굴기업들은 지난 사이클 동안 값싼 전력을 찾아 이미 수백 MW급 전력 계약과 변전 설비, 냉각 인프라를 확보해 두었다. 즉 채굴장은 이미 '전기가 들어와 있는 빈 창고'였고, 그 안을 채굴용 ASIC 대신 AI용 GPU로 바꿔 끼우면 곧바로 AI 데이터센터가 된다. 앤트로픽이 스스로 부지를 사고 인허가를 받아 3년을 기다리는 대신 테라울프의 캠퍼스를 20년 빌리는 이유가 여기에 있다.</p>
  <p class="ko">이 논리는 이번이 처음이 아니다. 올해 들어 AI 인프라 기업으로 변신한 아이렌(IREN)은 마이크로소프트와 약 97억 달러 규모 계약을 맺고 텍사스 칠드러스 캠퍼스 200MW에 엔비디아 GB300 GPU 7만6,000장을 배치하기로 했고, 코어사이언티픽(Core Scientific)은 33억 달러 규모 하이일드 채권으로, 사이퍼 마이닝(Cipher Mining)은 17억 달러 규모 담보부 채권으로 같은 전환에 자금을 댔다. 테라울프의 앤트로픽 계약은 이 흐름의 최신·최대 사례일 뿐이다. 다만 마이크로소프트가 아이렌과 맺은 것이 GPU 배치를 포함한 호스팅 계약이었다면, 앤트로픽 건은 건물과 전력을 통째로 빌리는 순수 임대에 가깝다는 점에서 계약 구조가 조금 다르다.</p>
  <p class="en">Go one level deeper, and the crux of this deal is neither the GPUs nor the bitcoin — it is power. In large-scale AI training and inference, the scarcest resource is not the chips but ready, high-capacity electricity and the grid interconnection to receive it. In the United States, approval to connect a large new load to the grid can take years, yet bitcoin miners spent the last cycle chasing cheap power and already locked in hundreds of megawatts of supply contracts, substation gear and cooling infrastructure. A mining site, in other words, was already an "empty warehouse with the electricity switched on"; swap the mining ASICs inside for AI GPUs and it becomes an AI data center almost overnight. That is why Anthropic would rather lease TeraWulf's campus for 20 years than buy land, win permits and wait three years itself.</p>
  <p class="en">This logic is not new. Earlier this year IREN, which reinvented itself as an AI-infrastructure firm, struck a roughly $9.7 billion deal with Microsoft to deploy 76,000 Nvidia GB300 GPUs across 200 MW at its Childress, Texas campus; Core Scientific funded the same pivot with a $3.3 billion high-yield bond and Cipher Mining with $1.7 billion of secured notes. TeraWulf's Anthropic deal is merely the latest and largest example of the trend. One distinction: where Microsoft's arrangement with IREN was a hosting contract that included the GPUs, the Anthropic deal is closer to a pure lease of the building and its power — a slightly different contractual shape.</p>
  <p class="ja">もう一段掘り下げると、この取引の核心はGPUでもビットコインでもなく「電力」だ。大規模なAI学習・推論で最も希少な資源は半導体ではなく、すぐに引き出せる大容量の電力と、その電力を受けられる系統連系(グリッド接続)である。米国では新規の大型負荷の系統連系承認に数年かかるが、ビットコイン採掘企業は前サイクルで安い電力を求め、すでに数百MW級の電力契約や変電設備、冷却インフラを確保していた。つまり採掘場は既に「電気が来ている空の倉庫」であり、その中身を採掘用ASICからAI用GPUに差し替えれば、ほぼ即座にAIデータセンターになる。アンスロピックが自ら用地を買い、許認可を取り、3年待つ代わりにテラウルフのキャンパスを20年借りる理由はここにある。</p>
  <p class="ja">この論理は今回が初めてではない。今年に入りAIインフラ企業へ転身したアイレン(IREN)はマイクロソフトと約97億ドル規模の契約を結び、テキサス州チルドレス・キャンパスの200MWにエヌビディアのGB300 GPUを7万6,000枚配置することにし、コアサイエンティフィック(Core Scientific)は33億ドル規模のハイイールド債で、サイファー・マイニング(Cipher Mining)は17億ドル規模の担保付き債券で同じ転換に資金を充てた。テラウルフのアンスロピック契約は、この流れの最新かつ最大の事例にすぎない。ただしマイクロソフトがアイレンと結んだのがGPU配置を含むホスティング契約だったのに対し、アンスロピック案件は建物と電力をまるごと借りる純粋なリースに近い点で、契約構造がやや異なる。</p>
  <p class="es">Si se profundiza un nivel más, el meollo de este acuerdo no son las GPU ni el bitcoin: es la energía. En el entrenamiento y la inferencia de IA a gran escala, el recurso más escaso no son los chips, sino la electricidad de alta capacidad lista para usar y la conexión a la red para recibirla. En Estados Unidos, la aprobación para conectar una gran carga nueva a la red puede tardar años, pero los mineros de bitcoin pasaron el último ciclo buscando energía barata y ya aseguraron cientos de megavatios de contratos de suministro, equipos de subestación e infraestructura de refrigeración. Un sitio de minería, en otras palabras, ya era una "nave vacía con la electricidad encendida"; se cambian los ASIC de minería por GPU de IA y se convierte en un centro de datos de IA casi de la noche a la mañana. Por eso Anthropic prefiere arrendar el campus de TeraWulf durante 20 años en lugar de comprar terreno, obtener permisos y esperar tres años por su cuenta.</p>
  <p class="es">Esta lógica no es nueva. A principios de este año IREN, que se reinventó como firma de infraestructura de IA, cerró un acuerdo de unos 9.700 millones de dólares con Microsoft para desplegar 76.000 GPU Nvidia GB300 en 200 MW de su campus de Childress, Texas; Core Scientific financió el mismo giro con un bono de alto rendimiento de 3.300 millones y Cipher Mining con 1.700 millones en pagarés garantizados. El acuerdo de TeraWulf con Anthropic es simplemente el ejemplo más reciente y mayor de la tendencia. Una distinción: mientras el arreglo de Microsoft con IREN era un contrato de hosting que incluía las GPU, el de Anthropic se acerca más a un arrendamiento puro del edificio y su energía, una forma contractual algo diferente.</p>
  <p class="de">Eine Ebene tiefer betrachtet ist der Kern dieses Deals weder die GPUs noch das Bitcoin — es ist der Strom. Beim groß angelegten KI-Training und -Inferenz ist die knappste Ressource nicht der Chip, sondern sofort verfügbarer Hochkapazitätsstrom und der Netzanschluss, um ihn zu empfangen. In den USA kann die Genehmigung zum Anschluss einer großen neuen Last ans Netz Jahre dauern, doch Bitcoin-Miner verbrachten den letzten Zyklus auf der Suche nach billigem Strom und sicherten sich bereits Hunderte Megawatt an Lieferverträgen, Umspannanlagen und Kühlinfrastruktur. Eine Mining-Anlage war mit anderen Worten bereits eine „leere Halle mit eingeschaltetem Strom"; man tauscht die Mining-ASICs im Inneren gegen KI-GPUs und sie wird fast über Nacht zu einem KI-Rechenzentrum. Deshalb mietet Anthropic lieber TeraWulfs Campus für 20 Jahre, als selbst Land zu kaufen, Genehmigungen zu erlangen und drei Jahre zu warten.</p>
  <p class="fr">En creusant un niveau plus loin, le cœur de cet accord n'est ni les GPU ni le bitcoin : c'est l'électricité. Dans l'entraînement et l'inférence de l'IA à grande échelle, la ressource la plus rare n'est pas la puce, mais l'électricité disponible en grande capacité et le raccordement au réseau permettant de la recevoir. Aux États-Unis, l'autorisation de raccorder une nouvelle charge importante au réseau peut prendre des années, mais les mineurs de bitcoin ont passé le dernier cycle à courir après l'électricité bon marché et ont déjà verrouillé des centaines de mégawatts de contrats d'approvisionnement, d'équipements de sous-station et d'infrastructures de refroidissement. Un site de minage était donc déjà, en somme, un « entrepôt vide dont l'électricité est déjà branchée » ; il suffit de remplacer les ASIC de minage par des GPU d'IA pour qu'il devienne un centre de données d'IA en un temps record. C'est pourquoi Anthropic préfère louer le campus de TeraWulf pendant 20 ans plutôt que d'acheter un terrain, d'obtenir des permis et d'attendre elle-même trois ans.</p>
  <p class="pt">Aprofundando um nível, o cerne desse acordo não são as GPUs nem o bitcoin — é a energia. No treinamento e na inferência de IA em grande escala, o recurso mais escasso não são os chips, mas a eletricidade de alta capacidade pronta para uso e a conexão à rede elétrica capaz de recebê-la. Nos Estados Unidos, a aprovação para conectar uma nova carga de grande porte à rede pode levar anos, mas os mineradores de bitcoin passaram o último ciclo em busca de energia barata e já garantiram centenas de megawatts em contratos de fornecimento, equipamentos de subestação e infraestrutura de refrigeração. Um site de mineração, em outras palavras, já era um "galpão vazio com a eletricidade ligada"; basta trocar os ASICs de mineração por GPUs de IA para que ele se torne um data center de IA quase da noite para o dia. É por isso que a Anthropic prefere arrendar o campus da TeraWulf por 20 anos a comprar terreno, obter licenças e esperar três anos por conta própria.</p>
  <p class="tr">Bir adım daha derine inildiğinde, bu anlaşmanın özü ne GPU'lar ne de bitcoin — enerjidir. Büyük ölçekli yapay zeka eğitiminde ve çıkarımında en kıt kaynak çipler değil, hazır, yüksek kapasiteli elektrik ve onu alacak şebeke bağlantısıdır. Amerika Birleşik Devletleri'nde büyük bir yeni yükün şebekeye bağlanma onayı yıllar alabilir; oysa bitcoin madencileri son döngüde ucuz elektrik peşinde koşarak yüzlerce megavatlık tedarik sözleşmesini, trafo merkezi ekipmanını ve soğutma altyapısını çoktan güvence altına almıştı. Başka bir deyişle, bir madencilik tesisi zaten "elektriği açık boş bir depo" idi; içindeki madencilik ASIC'lerini yapay zeka GPU'larıyla değiştirmek, onu neredeyse bir gecede yapay zeka veri merkezine dönüştürür. Anthropic'in arazi satın alıp izin almak ve kendisi üç yıl beklemek yerine TeraWulf'un kampüsünü 20 yıllığına kiralamayı tercih etmesinin sebebi budur.</p>
  <p class="vi">Đi sâu thêm một mức, cốt lõi của thỏa thuận này không phải là GPU cũng không phải bitcoin — mà là điện năng. Trong huấn luyện và suy luận AI quy mô lớn, tài nguyên khan hiếm nhất không phải là chip mà là nguồn điện công suất lớn sẵn sàng sử dụng và kết nối lưới điện để tiếp nhận nguồn điện đó. Tại Hoa Kỳ, việc phê duyệt kết nối một tải trọng lớn mới vào lưới điện có thể mất nhiều năm, nhưng các công ty khai thác bitcoin đã dành cả chu kỳ trước để săn tìm nguồn điện giá rẻ và đã sớm khóa được hàng trăm megawatt hợp đồng cung cấp điện, thiết bị trạm biến áp và hạ tầng làm mát. Nói cách khác, một địa điểm khai thác vốn đã là "một nhà kho trống với điện đã được bật sẵn"; chỉ cần thay các ASIC khai thác bên trong bằng GPU AI là nó gần như ngay lập tức trở thành một trung tâm dữ liệu AI. Đó là lý do Anthropic thà thuê khuôn viên của TeraWulf trong 20 năm còn hơn tự mình mua đất, xin giấy phép và chờ đợi ba năm.</p>
  <p class="de">Diese Logik ist nicht neu. Anfang dieses Jahres schloss IREN, das sich als KI-Infrastrukturfirma neu erfand, einen rund 9,7-Milliarden-Dollar-Deal mit Microsoft, um 76.000 Nvidia-GB300-GPUs über 200 MW auf seinem Campus in Childress, Texas, einzusetzen; Core Scientific finanzierte denselben Schwenk mit einer Hochzinsanleihe über 3,3 Milliarden Dollar und Cipher Mining mit 1,7 Milliarden Dollar besicherter Schuldverschreibungen. TeraWulfs Anthropic-Deal ist lediglich das jüngste und größte Beispiel des Trends. Ein Unterschied: Während Microsofts Vereinbarung mit IREN ein Hosting-Vertrag war, der die GPUs einschloss, kommt der Anthropic-Deal eher einer reinen Vermietung des Gebäudes und seines Stroms gleich — eine etwas andere Vertragsform.</p>
  <p class="fr">Cette logique n'est pas nouvelle. Plus tôt cette année, IREN, qui s'est réinventée en entreprise d'infrastructure d'IA, a conclu avec Microsoft un accord d'environ 9,7 milliards de dollars pour déployer 76 000 GPU Nvidia GB300 sur 200 MW dans son campus de Childress, au Texas ; Core Scientific a financé le même virage grâce à une obligation à haut rendement de 3,3 milliards de dollars, et Cipher Mining avec 1,7 milliard de dollars de billets garantis. L'accord de TeraWulf avec Anthropic n'est que l'exemple le plus récent et le plus important de cette tendance. Une distinction : là où l'arrangement de Microsoft avec IREN était un contrat d'hébergement incluant les GPU, l'accord avec Anthropic s'apparente davantage à une location pure du bâtiment et de son électricité — une forme contractuelle légèrement différente.</p>
  <p class="pt">Essa lógica não é nova. No início deste ano, a IREN, que se reinventou como empresa de infraestrutura de IA, fechou um acordo de cerca de 9,7 bilhões de dólares com a Microsoft para implantar 76.000 GPUs Nvidia GB300 em 200 MW em seu campus de Childress, no Texas; a Core Scientific financiou a mesma guinada com um título de alto rendimento de 3,3 bilhões de dólares, e a Cipher Mining, com 1,7 bilhão de dólares em notas garantidas. O acordo da TeraWulf com a Anthropic é apenas o exemplo mais recente e maior dessa tendência. Uma distinção: enquanto o arranjo da Microsoft com a IREN era um contrato de hospedagem que incluía as GPUs, o acordo com a Anthropic se aproxima mais de um arrendamento puro do prédio e de sua energia — uma configuração contratual um pouco diferente.</p>
  <p class="tr">Bu mantık yeni değil. Bu yılın başlarında kendini bir yapay zeka altyapı şirketine dönüştüren IREN, Texas'taki Childress kampüsünde 200 MW üzerinde 76.000 Nvidia GB300 GPU dağıtmak için Microsoft ile yaklaşık 9,7 milyar dolarlık bir anlaşma yaptı; Core Scientific aynı dönüşümü 3,3 milyar dolarlık yüksek getirili bir tahvil ile, Cipher Mining ise 1,7 milyar dolarlık teminatlı senetlerle finanse etti. TeraWulf'un Anthropic anlaşması, bu eğilimin yalnızca en yeni ve en büyük örneği. Bir fark şu: Microsoft'un IREN ile yaptığı düzenleme GPU'ları da içeren bir barındırma sözleşmesiyken, Anthropic anlaşması binanın ve gücünün saf bir kiralanmasına daha yakın — biraz farklı bir sözleşme yapısı.</p>
  <p class="vi">Logic này không mới. Đầu năm nay, IREN — công ty đã tự tái định vị mình thành một hãng hạ tầng AI — đã đạt được thỏa thuận trị giá khoảng 9,7 tỷ đô la với Microsoft để triển khai 76.000 GPU Nvidia GB300 trên 200 MW tại khuôn viên Childress, bang Texas; Core Scientific tài trợ cho bước chuyển đổi tương tự bằng trái phiếu lợi suất cao trị giá 3,3 tỷ đô la, còn Cipher Mining bằng 1,7 tỷ đô la trái phiếu có bảo đảm. Thỏa thuận của TeraWulf với Anthropic chỉ là ví dụ mới nhất và lớn nhất của xu hướng này. Một điểm khác biệt: trong khi thỏa thuận của Microsoft với IREN là hợp đồng lưu trữ (hosting) bao gồm cả GPU, thỏa thuận với Anthropic lại gần với một hợp đồng thuê thuần túy tòa nhà và nguồn điện của nó — một hình thức hợp đồng có phần khác biệt.</p>

  <div class="ko">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">테라울프–앤트로픽 거래와 채굴업계의 AI 전환</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="26" font-weight="800">190억$</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">계약 매출 (20년)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">임대 용량</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">5.3억$</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">애버내시 지분 매각</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">발표 후 주가 (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="14" font-weight="700">상장 채굴기업의 AI 매출 비중 (추정·전망)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">2026년 현재 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">2026년 말 전망 ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="13.5" font-weight="700">업계 AI·HPC 누적 계약 700억 달러+ · 비트코인 해시레이트 6년 만에 첫 분기 감소</text>
      <text x="20" y="420" fill="#52525b" font-size="12">출처: 테라울프 보도자료, 로이터, CNBC, 코인데스크, S&amp;P 글로벌 (전망은 업계 추정치)</text>
    </g>
  </svg>
  </div>
  <div class="en">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">The TeraWulf–Anthropic deal and mining's AI pivot</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="26" font-weight="800">$19B</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">contracted revenue (20y)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">leased capacity</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">$530M</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">Abernathy stake sold</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">stock after news (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="14" font-weight="700">Listed miners' AI revenue share (estimate / outlook)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">now, 2026 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">end-2026 outlook ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="13.5" font-weight="700">$70B+ cumulative AI/HPC contracts across public miners · first Q1 hashrate drop in 6 years</text>
      <text x="20" y="420" fill="#52525b" font-size="12">Sources: TeraWulf release, Reuters, CNBC, CoinDesk, S&amp;P Global (outlook is an industry estimate)</text>
    </g>
  </svg>
  </div>
  <div class="ja">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">テラウルフ・アンスロピック取引と採掘業界のAI転換</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="26" font-weight="800">190億$</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">契約売上 (20年)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">リース容量</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">5.3億$</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">アバナシー持分売却</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">発表後の株価 (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="14" font-weight="700">上場採掘企業のAI売上比率 (推計・見通し)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">2026年現在 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">2026年末見通し ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="13.5" font-weight="700">業界AI・HPC累計契約700億ドル+ · ビットコイン・ハッシュレート6年ぶり初の四半期減</text>
      <text x="20" y="420" fill="#52525b" font-size="12">出典: テラウルフ発表、ロイター、CNBC、コインデスク、S&amp;Pグローバル (見通しは業界推計)</text>
    </g>
  </svg>
  </div>
  <div class="es">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15.5" font-weight="700" font-family="sans-serif">El acuerdo TeraWulf–Anthropic y el giro a la IA de la minería</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="24" font-weight="800">19.000M$</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">ingresos contratados (20a)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">capacidad arrendada</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="25" font-weight="800">530M$</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">venta stake Abernathy</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">acción tras anuncio (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="14" font-weight="700">Peso de ingresos de IA en mineros cotizados (estim./previsión)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">hoy, 2026 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">previsión fin 2026 ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="12.5" font-weight="700">+70.000M$ en contratos IA/HPC del sector · primera caída trimestral del hashrate en 6 años</text>
      <text x="20" y="420" fill="#52525b" font-size="12">Fuentes: comunicado de TeraWulf, Reuters, CNBC, CoinDesk, S&amp;P Global (la previsión es una estimación del sector)</text>
    </g>
  </svg>
  </div>
  <div class="de">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15.5" font-weight="700" font-family="sans-serif">Der TeraWulf–Anthropic-Deal und der KI-Schwenk des Minings</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="23" font-weight="800">19 Mrd.$</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">Vertragsumsatz (20 J.)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">vermietete Kapazität</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="24" font-weight="800">530 Mio.$</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">Abernathy-Anteil verkauft</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">Aktie nach Meldung (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="14" font-weight="700">KI-Umsatzanteil börsennotierter Miner (Schätzung/Ausblick)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">heute, 2026 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">Ausblick Ende 2026 ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="12.5" font-weight="700">70 Mrd.$+ kumulierte KI/HPC-Verträge im Sektor · erster Q1-Hashrate-Rückgang seit 6 Jahren</text>
      <text x="20" y="420" fill="#52525b" font-size="12">Quellen: TeraWulf-Mitteilung, Reuters, CNBC, CoinDesk, S&amp;P Global (Ausblick ist eine Branchenschätzung)</text>
    </g>
  </svg>
  </div>
  <div class="fr">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15.5" font-weight="700" font-family="sans-serif">L'accord TeraWulf–Anthropic et le virage IA du minage</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="24" font-weight="800">19 Md$</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="12.5">revenus contractuels (20 ans)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">capacité louée</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="25" font-weight="800">530 M$</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">part Abernathy cédée</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">action après l'annonce (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="13.5" font-weight="700">Part de l'IA dans les revenus des mineurs cotés (estimation / prévision)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">actuellement, 2026 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">prévision fin 2026 ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="12.5" font-weight="700">70 Md$+ de contrats IA/HPC cumulés chez les mineurs cotés · première baisse trimestrielle du hashrate en 6 ans</text>
      <text x="20" y="420" fill="#52525b" font-size="12">Sources : communiqué de TeraWulf, Reuters, CNBC, CoinDesk, S&amp;P Global (la prévision est une estimation du secteur)</text>
    </g>
  </svg>
  </div>
  <div class="pt">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">O acordo TeraWulf–Anthropic e a guinada da mineração para IA</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="24" font-weight="800">US$19bi</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="12.5">receita contratada (20 anos)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">capacidade arrendada</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="24" font-weight="800">US$530mi</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">participação Abernathy vendida</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">ação após o anúncio (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="13.5" font-weight="700">Participação da IA na receita das mineradoras listadas (estimativa/previsão)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">atual, 2026 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">previsão fim de 2026 ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="12.5" font-weight="700">US$70bi+ em contratos de IA/HPC acumulados entre mineradoras listadas · primeira queda trimestral do hashrate em 6 anos</text>
      <text x="20" y="420" fill="#52525b" font-size="12">Fontes: comunicado da TeraWulf, Reuters, CNBC, CoinDesk, S&amp;P Global (a previsão é uma estimativa do setor)</text>
    </g>
  </svg>
  </div>
  <div class="tr">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="14.5" font-weight="700" font-family="sans-serif">TeraWulf–Anthropic anlaşması ve madenciliğin yapay zekaya dönüşü</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="23" font-weight="800">19B $</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="12.5">sözleşmeli gelir (20 yıl)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">kiralanan kapasite</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="24" font-weight="800">530M $</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">satılan Abernathy hissesi</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">haber sonrası hisse (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="13" font-weight="700">Halka açık madencilerin gelirinde yapay zeka payı (tahmin / öngörü)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">şu an, 2026 ~%30</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈%30</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">2026 sonu öngörüsü ~%70</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈%70</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="12.5" font-weight="700">Halka açık madencilerde 70B$+ birikimli AI/HPC sözleşmesi · 6 yılın ilk çeyreklik hashrate düşüşü</text>
      <text x="20" y="420" fill="#52525b" font-size="12">Kaynaklar: TeraWulf açıklaması, Reuters, CNBC, CoinDesk, S&amp;P Global (öngörü sektör tahminidir)</text>
    </g>
  </svg>
  </div>
  <div class="vi">
  <svg viewBox="0 0 700 430" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
    <text x="20" y="32" fill="#fafafa" font-size="14.5" font-weight="700" font-family="sans-serif">Thỏa thuận TeraWulf–Anthropic và bước chuyển sang AI của ngành khai thác</text>
    <g font-family="sans-serif">
      <rect x="20" y="52" width="158" height="96" rx="10" fill="#0e2a30" stroke="#06b6d4" stroke-width="1.6"/>
      <text x="99" y="92" fill="#22d3ee" text-anchor="middle" font-size="24" font-weight="800">19 tỷ$</text>
      <text x="99" y="120" fill="#a1a1aa" text-anchor="middle" font-size="12.5">doanh thu theo hợp đồng (20 năm)</text>
      <rect x="186" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="265" y="92" fill="#fafafa" text-anchor="middle" font-size="26" font-weight="800">401 MW</text>
      <text x="265" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">công suất cho thuê</text>
      <rect x="352" y="52" width="158" height="96" rx="10" fill="#18181b" stroke="#3f3f46" stroke-width="1.3"/>
      <text x="431" y="92" fill="#fafafa" text-anchor="middle" font-size="22" font-weight="800">530 triệu$</text>
      <text x="431" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">cổ phần Abernathy đã bán</text>
      <rect x="518" y="52" width="162" height="96" rx="10" fill="#14311f" stroke="#22c55e" stroke-width="1.6"/>
      <text x="599" y="92" fill="#4ade80" text-anchor="middle" font-size="26" font-weight="800">+17%</text>
      <text x="599" y="120" fill="#a1a1aa" text-anchor="middle" font-size="13">cổ phiếu sau tin tức (WULF)</text>
      <line x1="20" y1="176" x2="680" y2="176" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="206" fill="#e4e4e7" font-size="13" font-weight="700">Tỷ trọng doanh thu AI của các công ty khai thác niêm yết (ước tính/dự báo)</text>
      <text x="20" y="238" fill="#a1a1aa" font-size="13">hiện tại, 2026 ~30%</text>
      <rect x="20" y="248" width="186" height="30" rx="6" fill="#3f3f46"/>
      <text x="214" y="269" fill="#e4e4e7" font-size="13" font-weight="700">≈30%</text>
      <text x="20" y="308" fill="#a1a1aa" font-size="13">dự báo cuối 2026 ~70%</text>
      <rect x="20" y="318" width="434" height="30" rx="6" fill="#06b6d4"/>
      <text x="462" y="339" fill="#22d3ee" font-size="13" font-weight="700">≈70%</text>
      <line x1="20" y1="372" x2="680" y2="372" stroke="#27272a" stroke-width="1"/>
      <text x="20" y="400" fill="#f7931a" font-size="12" font-weight="700">70 tỷ$+ hợp đồng AI/HPC lũy kế tại các công ty khai thác niêm yết · lần sụt giảm hashrate theo quý đầu tiên sau 6 năm</text>
      <text x="20" y="420" fill="#52525b" font-size="12">Nguồn: thông cáo của TeraWulf, Reuters, CNBC, CoinDesk, S&amp;P Global (dự báo là ước tính của ngành)</text>
    </g>
  </svg>
  </div>

  <h2 class="ko">채굴에서 AI로 — 업계의 대이동</h2>
  <h2 class="en">From mining to AI — an industry-wide migration</h2>
  <h2 class="ja">採掘からAIへ — 業界の大移動</h2>
  <h2 class="es">De la minería a la IA — una migración de toda la industria</h2>
  <h2 class="de">Vom Mining zur KI — eine branchenweite Wanderung</h2>
  <h2 class="fr">Du minage à l'IA — une migration à l'échelle du secteur</h2>
  <h2 class="pt">Da mineração para a IA — uma migração em todo o setor</h2>
  <h2 class="tr">Madencilikten yapay zekaya — sektör genelinde bir göç</h2>
  <h2 class="vi">Từ khai thác sang AI — cuộc di cư trên toàn ngành</h2>
  <p class="ko">이번 계약은 개별 기업의 호재를 넘어, 비트코인 채굴 산업 전체가 지나는 구조적 변곡점을 보여준다. S&amp;P 글로벌과 코인데스크 집계에 따르면 상장 채굴기업들이 발표한 AI·고성능컴퓨팅(HPC) 누적 계약 규모는 이미 700억 달러를 넘어섰고, 일부 분석가는 상장 채굴기업의 매출에서 AI가 차지하는 비중이 현재 약 30%에서 2026년 말 70% 안팎까지 커질 수 있다고 본다. 채굴이 본업이던 기업들이 사실상 데이터센터 임대업으로 정체성을 바꾸고 있는 것이다. 이 변화의 배경에는 반감기 이후 채굴 보상 감소와 낮은 해시프라이스(채굴 단위 수익)로 채굴 경제가 장기간 압박받아 온 현실이 있다.</p>
  <p class="ko">그 결과는 비트코인 네트워크 자체에도 흔적을 남기고 있다. 코인데스크 보도에 따르면 올해 1분기 비트코인 네트워크 해시레이트는 6년 만에 처음으로 분기 기준 하락을 기록했는데, 이는 일부 채굴기업이 연산 자원을 채굴에서 AI로 돌리며 채굴기를 꺼버린 결과로 해석된다. 과거 채굴기업의 성장 스토리가 '더 많은 해시레이트'였다면, 지금의 성장 스토리는 '더 많은 계약된 전력 임대 매출'로 바뀌었다. 이 대목에서 짚어야 할 것은, 테라울프 같은 기업의 주가 급등이 반드시 비트코인 채굴 사업의 호조를 뜻하지는 않는다는 점이다. 오히려 채굴이라는 원래 사업에서 발을 빼는 속도가 빠를수록 시장이 더 환호하는, 역설적 국면에 가깝다.</p>
  <p class="en">The deal is more than a single company's good news; it illustrates a structural inflection point for the entire bitcoin-mining industry. By tallies from S&amp;P Global and CoinDesk, cumulative AI and high-performance-computing (HPC) contracts announced by listed miners have already passed $70 billion, and some analysts think the share of AI in listed miners' revenue could grow from about 30% today to around 70% by the end of 2026. Firms whose core business was mining are effectively rebranding as data-center landlords. Behind the shift lies a reality in which mining economics have been squeezed for a long stretch by post-halving reward cuts and low hashprice, the per-unit measure of mining revenue.</p>
  <p class="en">The consequences are leaving marks on the Bitcoin network itself. Per CoinDesk, the network's hashrate posted its first quarterly decline in six years in the first quarter of this year — read as the result of some miners redirecting compute from mining to AI and switching machines off. Where a miner's growth story used to be "more hashrate," today it is "more contracted power-lease revenue." Worth noting here is that a surge in the stock of a firm like TeraWulf does not necessarily signal a healthy bitcoin-mining business. If anything, it is closer to a paradox in which the faster a company retreats from its original mining business, the more the market cheers.</p>
  <p class="ja">今回の契約は個別企業の好材料にとどまらず、ビットコイン採掘産業全体が通過する構造的な変曲点を示している。S&amp;Pグローバルやコインデスクの集計によれば、上場採掘企業が発表したAI・高性能計算(HPC)の累計契約規模はすでに700億ドルを超え、一部のアナリストは上場採掘企業の売上に占めるAIの比率が現在の約30%から2026年末には70%前後まで拡大しうるとみる。採掘が本業だった企業が事実上、データセンター賃貸業へと正体を変えつつあるのだ。この変化の背景には、半減期後の採掘報酬の減少と低いハッシュプライス(採掘単位あたり収益)により採掘経済が長期間圧迫されてきた現実がある。</p>
  <p class="ja">その結果はビットコイン・ネットワーク自体にも痕跡を残している。コインデスクの報道によれば、今年第1四半期のビットコイン・ネットワークのハッシュレートは6年ぶりに四半期ベースで下落を記録した。これは一部の採掘企業が計算資源を採掘からAIへ振り向け、採掘機を停止させた結果と解釈される。かつて採掘企業の成長ストーリーが「より多くのハッシュレート」だったとすれば、今の成長ストーリーは「より多くの契約された電力賃貸売上」へと変わった。ここで押さえるべきは、テラウルフのような企業の株価急騰が必ずしもビットコイン採掘事業の好調を意味しない点だ。むしろ採掘という本来の事業から手を引く速度が速いほど市場がより歓迎する、逆説的な局面に近い。</p>
  <p class="es">El acuerdo es más que la buena noticia de una sola empresa; ilustra un punto de inflexión estructural para toda la industria minera de bitcoin. Según los recuentos de S&amp;P Global y CoinDesk, los contratos acumulados de IA y computación de alto rendimiento (HPC) anunciados por mineros cotizados ya superan los 70.000 millones de dólares, y algunos analistas creen que la proporción de IA en los ingresos de los mineros cotizados podría crecer de cerca del 30% actual a alrededor del 70% para finales de 2026. Empresas cuyo negocio principal era la minería se están reconvirtiendo, de hecho, en caseros de centros de datos. Detrás del giro hay una realidad en la que la economía minera lleva mucho tiempo presionada por los recortes de recompensa tras el halving y un hashprice bajo, la medida de ingresos por unidad de minería.</p>
  <p class="es">Las consecuencias están dejando huella en la propia red Bitcoin. Según CoinDesk, el hashrate de la red registró su primera caída trimestral en seis años en el primer trimestre de este año, interpretada como resultado de que algunos mineros redirigen cómputo de la minería a la IA y apagan máquinas. Donde la historia de crecimiento de un minero solía ser "más hashrate", hoy es "más ingresos contratados por arrendamiento de energía". Cabe señalar que un repunte en la acción de una firma como TeraWulf no señala necesariamente un negocio minero saludable. Más bien se acerca a una paradoja en la que cuanto más rápido se retira una empresa de su negocio minero original, más la aplaude el mercado.</p>
  <p class="de">Der Deal ist mehr als die gute Nachricht eines einzelnen Unternehmens; er veranschaulicht einen strukturellen Wendepunkt für die gesamte Bitcoin-Mining-Branche. Nach Aufstellungen von S&amp;P Global und CoinDesk haben die von börsennotierten Minern angekündigten kumulierten KI- und Hochleistungsrechen-(HPC)-Verträge bereits 70 Milliarden Dollar überschritten, und einige Analysten meinen, der Anteil der KI an den Einnahmen börsennotierter Miner könne von heute rund 30% bis Ende 2026 auf etwa 70% wachsen. Firmen, deren Kerngeschäft das Mining war, benennen sich faktisch in Rechenzentrums-Vermieter um. Hinter dem Wandel steht eine Realität, in der die Mining-Ökonomie lange durch die nach dem Halving gesunkenen Belohnungen und einen niedrigen Hashprice, das Maß des Umsatzes je Mining-Einheit, unter Druck stand.</p>
  <p class="fr">Cet accord dépasse la simple bonne nouvelle pour une entreprise ; il illustre un point d'inflexion structurel pour l'ensemble de l'industrie du minage de bitcoin. Selon les décomptes de S&amp;P Global et de CoinDesk, les contrats cumulés d'IA et de calcul haute performance (HPC) annoncés par les mineurs cotés ont déjà dépassé 70 milliards de dollars, et certains analystes estiment que la part de l'IA dans les revenus des mineurs cotés pourrait passer d'environ 30 % aujourd'hui à près de 70 % d'ici la fin de 2026. Des entreprises dont le cœur de métier était le minage se transforment de fait en bailleurs de centres de données. Derrière ce virage se cache une réalité où l'économie du minage est sous pression depuis longtemps, du fait des réductions de récompense consécutives au halving et d'un hashprice — la mesure du revenu par unité de minage — resté bas.</p>
  <p class="pt">O acordo é mais do que a boa notícia de uma única empresa; ele ilustra um ponto de inflexão estrutural para toda a indústria de mineração de bitcoin. Segundo levantamentos da S&amp;P Global e da CoinDesk, os contratos acumulados de IA e computação de alto desempenho (HPC) anunciados por mineradoras listadas já ultrapassam 70 bilhões de dólares, e alguns analistas acreditam que a participação da IA na receita das mineradoras listadas pode crescer dos atuais cerca de 30% para perto de 70% até o fim de 2026. Empresas cujo negócio principal era a mineração estão, na prática, se reposicionando como senhorias de data centers. Por trás dessa mudança há uma realidade em que a economia da mineração vem sendo pressionada há muito tempo pelos cortes de recompensa pós-halving e pelo baixo hashprice, a medida de receita por unidade de mineração.</p>
  <p class="tr">Bu anlaşma tek bir şirketin iyi haberinden fazlasıdır; tüm bitcoin madenciliği sektörü için yapısal bir dönüm noktasını gözler önüne seriyor. S&amp;P Global ve CoinDesk'in derlemelerine göre, halka açık madenciler tarafından açıklanan birikimli yapay zeka ve yüksek performanslı bilgi işlem (HPC) sözleşmeleri şimdiden 70 milyar doları aştı ve bazı analistler, halka açık madencilerin gelirinde yapay zekanın payının bugün yaklaşık yüzde 30'dan 2026 sonuna kadar yüzde 70 civarına yükselebileceğini düşünüyor. Temel işi madencilik olan şirketler, fiilen veri merkezi ev sahipliğine dönüşüyor. Bu dönüşümün arkasında, halving sonrası ödül kesintileri ve madencilik gelirinin birim başına ölçütü olan düşük hashprice nedeniyle madencilik ekonomisinin uzun süredir baskı altında olduğu bir gerçeklik yatıyor.</p>
  <p class="vi">Thỏa thuận này không chỉ là tin tốt của riêng một công ty; nó minh họa cho một bước ngoặt mang tính cấu trúc của toàn bộ ngành khai thác bitcoin. Theo thống kê của S&amp;P Global và CoinDesk, tổng giá trị các hợp đồng AI và điện toán hiệu năng cao (HPC) mà các công ty khai thác niêm yết công bố đã vượt 70 tỷ đô la, và một số nhà phân tích cho rằng tỷ trọng AI trong doanh thu của các công ty khai thác niêm yết có thể tăng từ khoảng 30% hiện nay lên khoảng 70% vào cuối năm 2026. Các công ty vốn có hoạt động cốt lõi là khai thác đang thực chất tái định vị mình thành chủ cho thuê trung tâm dữ liệu. Đằng sau sự chuyển dịch này là một thực tế rằng kinh tế học của việc khai thác đã bị siết chặt trong thời gian dài bởi việc cắt giảm phần thưởng sau halving và hashprice thấp — thước đo doanh thu trên mỗi đơn vị khai thác.</p>
  <p class="de">Die Folgen hinterlassen Spuren im Bitcoin-Netzwerk selbst. Laut CoinDesk verzeichnete die Netzwerk-Hashrate im ersten Quartal dieses Jahres ihren ersten Quartalsrückgang seit sechs Jahren — gelesen als Ergebnis dessen, dass einige Miner Rechenleistung vom Mining zur KI umleiten und Maschinen abschalten. Wo die Wachstumsgeschichte eines Miners früher „mehr Hashrate" war, ist sie heute „mehr vertraglich gesicherter Strommietumsatz". Festzuhalten ist hier, dass ein Kurssprung bei einer Firma wie TeraWulf nicht zwangsläufig ein gesundes Bitcoin-Mining-Geschäft signalisiert. Eher kommt es einem Paradox nahe, bei dem der Markt umso mehr jubelt, je schneller sich ein Unternehmen aus seinem ursprünglichen Mining-Geschäft zurückzieht.</p>
  <p class="fr">Les conséquences se font sentir jusque sur le réseau Bitcoin lui-même. Selon CoinDesk, le hashrate du réseau a enregistré sa première baisse trimestrielle en six ans au premier trimestre de cette année — un phénomène lu comme le résultat de mineurs redirigeant leur puissance de calcul du minage vers l'IA et éteignant leurs machines. Là où le récit de croissance d'un mineur reposait autrefois sur « plus de hashrate », il repose aujourd'hui sur « plus de revenus contractuels issus de la location d'électricité ». Il convient de noter qu'une envolée boursière d'une entreprise comme TeraWulf ne signale pas nécessairement un secteur du minage en bonne santé. Il s'agit plutôt d'un paradoxe : plus une entreprise se retire rapidement de son activité minière d'origine, plus le marché l'applaudit.</p>
  <p class="pt">As consequências estão deixando marcas na própria rede Bitcoin. Segundo a CoinDesk, o hashrate da rede registrou sua primeira queda trimestral em seis anos no primeiro trimestre deste ano — interpretada como resultado de alguns mineradores redirecionando poder computacional da mineração para a IA e desligando máquinas. Onde a narrativa de crescimento de uma mineradora costumava ser "mais hashrate", hoje é "mais receita contratada de arrendamento de energia". Vale notar que uma disparada nas ações de uma empresa como a TeraWulf não sinaliza necessariamente um negócio de mineração de bitcoin saudável. Na verdade, é mais próximo de um paradoxo em que, quanto mais rápido uma empresa se retira de seu negócio original de mineração, mais o mercado a aplaude.</p>
  <p class="tr">Bu sonuçlar Bitcoin ağının kendisinde de izler bırakıyor. CoinDesk'e göre, ağın hashrate'i bu yılın ilk çeyreğinde altı yılın ilk çeyreklik düşüşünü kaydetti — bu durum, bazı madencilerin hesaplama gücünü madencilikten yapay zekaya yönlendirip makineleri kapatmasının sonucu olarak yorumlanıyor. Bir madencinin büyüme hikayesi eskiden "daha fazla hashrate" iken, bugün "daha fazla sözleşmeli güç kiralama geliri" haline geldi. Burada dikkat çekilmesi gereken nokta, TeraWulf gibi bir şirketin hisse senedindeki sıçramanın mutlaka sağlıklı bir bitcoin madenciliği işini işaret etmediğidir. Aksine, bir şirket özgün madencilik işinden ne kadar hızlı çekilirse piyasanın onu o kadar çok alkışladığı bir paradoksa daha yakındır.</p>
  <p class="vi">Những hệ quả này đang để lại dấu ấn ngay trên chính mạng lưới Bitcoin. Theo CoinDesk, hashrate của mạng lưới đã ghi nhận mức sụt giảm theo quý đầu tiên sau sáu năm trong quý một năm nay — được diễn giải là kết quả của việc một số công ty khai thác chuyển hướng năng lực tính toán từ khai thác sang AI và tắt máy. Trước đây câu chuyện tăng trưởng của một công ty khai thác thường là "nhiều hashrate hơn", thì nay đó là "nhiều doanh thu cho thuê điện theo hợp đồng hơn". Điều đáng lưu ý ở đây là việc cổ phiếu của một công ty như TeraWulf tăng vọt không nhất thiết báo hiệu một hoạt động khai thác bitcoin lành mạnh. Nếu có, nó gần với một nghịch lý hơn: công ty càng nhanh chóng rút lui khỏi hoạt động khai thác nguyên bản của mình thì thị trường càng hoan nghênh.</p>

  <h2 class="ko">리스크와 반론</h2>
  <h2 class="en">Risks and counterarguments</h2>
  <h2 class="ja">リスクと反論</h2>
  <h2 class="es">Riesgos y contraargumentos</h2>
  <h2 class="de">Risiken und Gegenargumente</h2>
  <h2 class="fr">Risques et contre-arguments</h2>
  <h2 class="pt">Riscos e contra-argumentos</h2>
  <h2 class="tr">Riskler ve karşı argümanlar</h2>
  <h2 class="vi">Rủi ro và các lập luận phản biện</h2>
  <p class="ko">낙관 일변도로 보기 어려운 이유도 분명하다. 첫째는 계약 상대방(카운터파티) 위험이다. 190억 달러라는 숫자는 20년에 걸친 미래 매출의 합계일 뿐, 실제 현금흐름은 앤트로픽이 20년간 임대료를 성실히 지급한다는 전제 위에 서 있다. 앤트로픽은 상장사가 아니며 AI 산업 자체가 대규모 자본지출 경쟁 속에 있어, 일각에서는 'AI 캐펙스 버블' 우려가 제기된다. 초기 전력 공급이 2027년 하반기로 예정돼 있어 실제 매출 인식까지 시간이 걸린다는 점, 그 사이 건설·전력 인프라 비용이 선행 투입된다는 점도 리스크다. 회사가 '투자등급 신용 구조'를 강조한 것도 바로 이 카운터파티 위험을 완화하기 위한 장치로 읽힌다.</p>
  <p class="ko">둘째는 비트코인 진영에서 제기되는 탈중앙화·보안 관련 반론이다. 채굴기업들이 앞다퉈 연산을 AI로 돌리면 네트워크 해시레이트 성장세가 둔화하고, 남은 채굴 능력이 소수 대형 사업자에게 더 집중될 수 있다. 여기에 구글이 테라울프의 보증인 겸 약 14% 지분 보유자가 되고, 마이크로소프트·앤트로픽 같은 빅테크가 채굴 인프라의 실질적 고객이자 자금줄이 되는 구조는, 비트코인의 물리적 기반이 소수 대기업의 손에 얽혀 들어간다는 우려를 낳는다. 물론 반대 해석도 가능하다. 절대적 해시레이트의 크기보다 채굴 주체의 분산이 더 중요하며, 남은 채굴기업들이 더 저렴하고 유연한 전력 계약으로 경쟁력을 유지한다면 네트워크 보안이 실질적으로 약화되지 않을 수 있다는 것이다. 지켜봐야 할 것은 2027년 첫 전력 공급이 예정대로 이뤄지는지, 그리고 남은 채굴 능력의 집중도가 실제로 어떻게 변하는지다.</p>
  <p class="en">There are clear reasons not to read this as pure optimism. The first is counterparty risk. The $19 billion figure is merely the sum of future revenue across 20 years; the actual cash flow rests on the premise that Anthropic pays rent faithfully for two decades. Anthropic is not a public company, and the AI industry itself is locked in a race of massive capital spending, prompting some to warn of an "AI capex bubble." Initial power delivery is slated for the second half of 2027, so it will take time before revenue is recognized, while construction and power-infrastructure costs are incurred up front — another risk. The company's emphasis on an "investment-grade credit structure" reads precisely as a device to mitigate that counterparty risk.</p>
  <p class="en">The second is a decentralization-and-security counterargument raised within the Bitcoin camp. If miners rush to redirect compute to AI, growth in network hashrate slows and the remaining mining capacity may concentrate further among a few large operators. Add that Google becomes TeraWulf's guarantor and an owner of roughly 14%, and that Big Tech names like Microsoft and Anthropic become the real customers and funders of mining infrastructure, and you get worries that Bitcoin's physical base is being entangled in the hands of a few large corporations. The opposite reading is also possible: the distribution of mining operators matters more than the absolute size of hashrate, and if the remaining miners keep their edge with cheaper, more flexible power contracts, network security need not weaken in practice. What to watch is whether the first power delivery in 2027 happens on schedule, and how the concentration of remaining mining capacity actually evolves.</p>
  <p class="ja">楽観一辺倒で見られない理由も明確だ。第一に契約相手(カウンターパーティ)リスクである。190億ドルという数字は20年にわたる将来売上の合計にすぎず、実際のキャッシュフローはアンスロピックが20年間賃料を誠実に支払うという前提の上に立つ。アンスロピックは上場企業ではなく、AI産業自体が大規模な設備投資競争の中にあるため、一部では「AIキャペックス・バブル」への懸念が示される。初期の電力供給が2027年下半期に予定され、実際の売上認識まで時間がかかる点、その間に建設・電力インフラ費用が先行投入される点もリスクだ。会社が「投資適格の信用構造」を強調したのも、まさにこのカウンターパーティ・リスクを緩和する仕組みと読める。</p>
  <p class="ja">第二にビットコイン陣営から提起される分散化・セキュリティに関する反論だ。採掘企業が競って計算をAIへ振り向ければ、ネットワークのハッシュレート成長は鈍化し、残る採掘能力が少数の大手事業者にさらに集中しうる。加えてグーグルがテラウルフの保証人かつ約14%の持分保有者となり、マイクロソフトやアンスロピックといった巨大テックが採掘インフラの実質的な顧客かつ資金源となる構造は、ビットコインの物理的基盤が少数の大企業の手に絡めとられるという懸念を生む。もちろん反対の解釈も可能だ。絶対的なハッシュレートの大きさより採掘主体の分散のほうが重要であり、残る採掘企業がより安く柔軟な電力契約で競争力を保つなら、ネットワークのセキュリティは実質的に弱まらないかもしれない。注視すべきは、2027年の初回電力供給が予定通り行われるか、そして残る採掘能力の集中度が実際にどう変わるかだ。</p>
  <p class="es">Hay razones claras para no leer esto como puro optimismo. La primera es el riesgo de contraparte. La cifra de 19.000 millones es solo la suma de ingresos futuros a lo largo de 20 años; el flujo de caja real descansa en la premisa de que Anthropic pague el alquiler fielmente durante dos décadas. Anthropic no es una empresa cotizada, y la propia industria de la IA está inmersa en una carrera de gasto de capital masivo, lo que lleva a algunos a advertir de una "burbuja de capex de IA". La entrega inicial de energía está prevista para la segunda mitad de 2027, de modo que pasará tiempo antes de reconocer ingresos, mientras los costes de construcción e infraestructura eléctrica se asumen por adelantado, otro riesgo. El énfasis de la empresa en una "estructura crediticia de grado de inversión" se lee precisamente como un mecanismo para mitigar ese riesgo de contraparte.</p>
  <p class="es">El segundo es un contraargumento de descentralización y seguridad que se plantea dentro del campo de Bitcoin. Si los mineros se apresuran a redirigir cómputo a la IA, el crecimiento del hashrate de la red se ralentiza y la capacidad minera restante puede concentrarse aún más en unos pocos grandes operadores. Súmese que Google se convierte en garante de TeraWulf y propietario de cerca del 14%, y que nombres de Big Tech como Microsoft y Anthropic pasan a ser los clientes y financiadores reales de la infraestructura minera, y surgen temores de que la base física de Bitcoin quede enredada en manos de unas pocas grandes corporaciones. También cabe la lectura opuesta: la distribución de los operadores mineros importa más que el tamaño absoluto del hashrate, y si los mineros restantes mantienen su ventaja con contratos de energía más baratos y flexibles, la seguridad de la red no tiene por qué debilitarse en la práctica. Lo que hay que vigilar es si la primera entrega de energía en 2027 ocurre según lo previsto y cómo evoluciona realmente la concentración de la capacidad minera restante.</p>
  <p class="de">Es gibt klare Gründe, dies nicht als reinen Optimismus zu lesen. Der erste ist das Kontrahentenrisiko. Die Zahl von 19 Milliarden Dollar ist lediglich die Summe künftiger Einnahmen über 20 Jahre; der tatsächliche Cashflow beruht auf der Prämisse, dass Anthropic zwei Jahrzehnte lang zuverlässig Miete zahlt. Anthropic ist kein börsennotiertes Unternehmen, und die KI-Branche selbst steckt in einem Wettlauf massiver Investitionen, weshalb einige vor einer „KI-Capex-Blase" warnen. Die erste Stromlieferung ist für die zweite Hälfte 2027 vorgesehen, sodass es dauert, bis Umsatz verbucht wird, während Bau- und Strominfrastrukturkosten im Voraus anfallen — ein weiteres Risiko. Die Betonung einer „Kreditstruktur mit Investment-Grade" durch das Unternehmen liest sich genau als Instrument, um dieses Kontrahentenrisiko zu mildern.</p>
  <p class="fr">Il existe des raisons claires de ne pas y voir un optimisme sans nuance. La première est le risque de contrepartie. Le chiffre de 19 milliards de dollars n'est que la somme des revenus futurs sur 20 ans ; le flux de trésorerie réel repose sur l'hypothèse qu'Anthropic paiera fidèlement son loyer pendant deux décennies. Anthropic n'est pas une société cotée en bourse, et l'industrie de l'IA elle-même est engagée dans une course aux dépenses d'investissement massives, ce qui pousse certains à mettre en garde contre une « bulle du capex de l'IA ». La livraison initiale d'électricité est prévue pour le second semestre 2027, de sorte qu'il faudra du temps avant que les revenus ne soient comptabilisés, tandis que les coûts de construction et d'infrastructure électrique sont engagés en amont — un risque supplémentaire. L'insistance de l'entreprise sur une « structure de crédit de qualité investment grade » se lit précisément comme un dispositif destiné à atténuer ce risque de contrepartie.</p>
  <p class="pt">Há razões claras para não interpretar isso como puro otimismo. A primeira é o risco de contraparte. O número de 19 bilhões de dólares é apenas a soma da receita futura ao longo de 20 anos; o fluxo de caixa real depende da premissa de que a Anthropic pagará o aluguel fielmente por duas décadas. A Anthropic não é uma empresa de capital aberto, e a própria indústria de IA está presa em uma corrida de gastos de capital massivos, o que leva alguns a alertar sobre uma "bolha de capex de IA". A entrega inicial de energia está prevista para o segundo semestre de 2027, de modo que levará tempo até que a receita seja reconhecida, enquanto os custos de construção e infraestrutura elétrica são incorridos antecipadamente — outro risco. A ênfase da empresa em uma "estrutura de crédito de grau de investimento" soa precisamente como um mecanismo para mitigar esse risco de contraparte.</p>
  <p class="tr">Bunu saf bir iyimserlik olarak görmemek için açık nedenler var. Birincisi karşı taraf riski. 19 milyar dolarlık rakam, yalnızca 20 yıla yayılan gelecekteki gelirin toplamıdır; gerçek nakit akışı, Anthropic'in iki on yıl boyunca kirasını sadakatle ödemesi varsayımına dayanır. Anthropic halka açık bir şirket değildir ve yapay zeka sektörünün kendisi devasa sermaye harcaması yarışına kilitlenmiş durumda; bu da bazılarının bir "yapay zeka capex balonu" konusunda uyarıda bulunmasına yol açıyor. İlk enerji tesliminin 2027'nin ikinci yarısı için planlanmış olması, gelirin muhasebeleştirilmesinden önce zaman geçeceği anlamına geliyor; bu arada inşaat ve güç altyapısı maliyetleri önceden üstlenilmiş oluyor — bu da başka bir risk. Şirketin "yatırım yapılabilir düzeyde kredi yapısı" vurgusu, tam olarak bu karşı taraf riskini azaltmaya yönelik bir araç olarak okunuyor.</p>
  <p class="vi">Có những lý do rõ ràng để không nhìn nhận điều này thuần túy bằng sự lạc quan. Thứ nhất là rủi ro đối tác. Con số 19 tỷ đô la chỉ đơn thuần là tổng doanh thu tương lai trải dài trong 20 năm; dòng tiền thực tế phụ thuộc vào tiền đề rằng Anthropic sẽ trả tiền thuê đầy đủ trong suốt hai thập kỷ. Anthropic không phải là công ty đại chúng, và bản thân ngành AI đang bị cuốn vào một cuộc đua chi tiêu vốn khổng lồ, khiến một số người cảnh báo về "bong bóng capex AI". Việc cung cấp điện ban đầu dự kiến vào nửa cuối năm 2027, nên sẽ mất thời gian trước khi doanh thu được ghi nhận, trong khi chi phí xây dựng và hạ tầng điện lại phát sinh trước — đây là một rủi ro khác. Việc công ty nhấn mạnh vào một "cấu trúc tín dụng ở mức đầu tư" được hiểu chính xác như một công cụ nhằm giảm thiểu rủi ro đối tác đó.</p>
  <p class="de">Der zweite ist ein Dezentralisierungs- und Sicherheitseinwand aus dem Bitcoin-Lager. Wenn Miner in Eile Rechenleistung zur KI umleiten, verlangsamt sich das Wachstum der Netzwerk-Hashrate, und die verbleibende Mining-Kapazität könnte sich weiter bei wenigen großen Betreibern konzentrieren. Hinzu kommt, dass Google zum Garanten von TeraWulf und Eigentümer von rund 14% wird und Big-Tech-Namen wie Microsoft und Anthropic zu den realen Kunden und Geldgebern der Mining-Infrastruktur werden — daraus erwächst die Sorge, dass Bitcoins physische Basis in die Hände weniger Großkonzerne gerät. Auch die gegenteilige Lesart ist möglich: Die Verteilung der Mining-Betreiber zählt mehr als die absolute Größe der Hashrate, und wenn die verbleibenden Miner ihren Vorteil mit billigeren, flexibleren Stromverträgen wahren, muss die Netzwerksicherheit praktisch nicht schwächer werden. Zu beobachten ist, ob die erste Stromlieferung 2027 planmäßig erfolgt und wie sich die Konzentration der verbleibenden Mining-Kapazität tatsächlich entwickelt.</p>
  <p class="fr">La deuxième est un contre-argument lié à la décentralisation et à la sécurité, soulevé au sein du camp Bitcoin. Si les mineurs se précipitent pour rediriger leur puissance de calcul vers l'IA, la croissance du hashrate du réseau ralentit et la capacité de minage restante pourrait se concentrer davantage entre les mains de quelques grands opérateurs. Ajoutez à cela que Google devient le garant de TeraWulf et détient environ 14 % de son capital, et que des géants technologiques comme Microsoft et Anthropic deviennent les véritables clients et bailleurs de fonds de l'infrastructure minière, et l'on obtient des craintes selon lesquelles la base physique de Bitcoin se retrouve prise dans les mains de quelques grandes entreprises. La lecture inverse est également possible : la répartition des opérateurs de minage compte davantage que la taille absolue du hashrate, et si les mineurs restants conservent leur avantage grâce à des contrats d'électricité moins chers et plus flexibles, la sécurité du réseau n'a pas nécessairement à s'affaiblir dans les faits. Ce qu'il faut surveiller, c'est si la première livraison d'électricité de 2027 aura lieu comme prévu, et comment évoluera réellement la concentration de la capacité de minage restante.</p>
  <p class="pt">A segunda é um contra-argumento sobre descentralização e segurança levantado dentro do próprio universo Bitcoin. Se os mineradores se apressarem a redirecionar poder computacional para a IA, o crescimento do hashrate da rede desacelera e a capacidade de mineração remanescente pode se concentrar ainda mais em poucos grandes operadores. Some-se a isso o fato de o Google se tornar garantidor da TeraWulf e proprietário de cerca de 14%, e de nomes de Big Tech como Microsoft e Anthropic se tornarem os verdadeiros clientes e financiadores da infraestrutura de mineração, e surgem preocupações de que a base física do Bitcoin esteja se enredando nas mãos de poucas grandes corporações. A leitura oposta também é possível: a distribuição dos operadores de mineração importa mais do que o tamanho absoluto do hashrate, e se os mineradores remanescentes mantiverem sua vantagem com contratos de energia mais baratos e flexíveis, a segurança da rede não precisa necessariamente enfraquecer na prática. O que observar é se a primeira entrega de energia em 2027 ocorrerá conforme o previsto, e como a concentração da capacidade de mineração remanescente realmente evoluirá.</p>
  <p class="tr">İkincisi, Bitcoin kampı içinde dile getirilen bir merkeziyetsizlik ve güvenlik karşı argümanı. Madenciler hesaplama gücünü yapay zekaya yönlendirmek için aceleyle davranırsa, ağ hashrate'indeki büyüme yavaşlar ve kalan madencilik kapasitesi birkaç büyük operatörde daha da yoğunlaşabilir. Buna Google'ın TeraWulf'un garantörü ve yaklaşık yüzde 14'lük sahibi haline gelmesini ve Microsoft ile Anthropic gibi büyük teknoloji şirketlerinin madencilik altyapısının gerçek müşterileri ve finansörleri olmasını eklerseniz, Bitcoin'in fiziksel tabanının birkaç büyük şirketin elinde birbirine dolanması yönünde endişeler ortaya çıkıyor. Tersi bir okuma da mümkündür: madencilik operatörlerinin dağılımı, hashrate'in mutlak büyüklüğünden daha önemlidir ve kalan madenciler daha ucuz, daha esnek güç sözleşmeleriyle avantajlarını korursa, ağ güvenliğinin pratikte zayıflaması gerekmez. İzlenmesi gereken, 2027'deki ilk enerji tesliminin planlandığı gibi gerçekleşip gerçekleşmeyeceği ve kalan madencilik kapasitesinin yoğunlaşmasının gerçekte nasıl evrileceğidir.</p>
  <p class="vi">Thứ hai là lập luận phản biện về phi tập trung hóa và bảo mật được nêu ra trong chính cộng đồng Bitcoin. Nếu các công ty khai thác đổ xô chuyển hướng năng lực tính toán sang AI, tốc độ tăng trưởng hashrate của mạng lưới sẽ chậm lại và năng lực khai thác còn lại có thể tập trung hơn nữa vào tay một số ít nhà vận hành lớn. Thêm vào đó, việc Google trở thành bên bảo lãnh của TeraWulf và sở hữu khoảng 14% cổ phần, cùng việc các tên tuổi công nghệ lớn như Microsoft và Anthropic trở thành khách hàng và nhà tài trợ thực sự cho hạ tầng khai thác, khiến người ta lo ngại rằng nền tảng vật lý của Bitcoin đang bị ràng buộc trong tay một số ít tập đoàn lớn. Cách diễn giải ngược lại cũng khả dĩ: sự phân bổ của các nhà vận hành khai thác quan trọng hơn quy mô tuyệt đối của hashrate, và nếu các công ty khai thác còn lại vẫn giữ được lợi thế nhờ các hợp đồng điện rẻ hơn, linh hoạt hơn, thì bảo mật mạng lưới trên thực tế không nhất thiết suy yếu. Điều cần theo dõi là liệu việc cung cấp điện đầu tiên vào năm 2027 có diễn ra đúng kế hoạch hay không, và mức độ tập trung của năng lực khai thác còn lại sẽ thực sự biến chuyển ra sao.</p>

  <div class="box ko">💡 <strong>시사점:</strong> 테라울프–앤트로픽 계약은 비트코인 채굴기업의 최대 자산이 채굴기가 아니라 '이미 확보된 대용량 전력'임을 확인시켜 준다. 190억 달러는 20년치 미래 매출의 합계일 뿐이므로 앤트로픽의 지급 능력과 2027년 가동 일정이 관건이며, 채굴 자원의 AI 이동이 비트코인 해시레이트와 채굴 집중도에 미칠 영향도 함께 지켜봐야 한다. 주가 급등이 곧 채굴업 호황을 뜻하지는 않는다.</div>
  <div class="box en">💡 <strong>Takeaway:</strong> The TeraWulf–Anthropic lease confirms that a bitcoin miner's biggest asset is not its machines but its "already-secured, high-capacity power." The $19 billion is only the sum of 20 years of future revenue, so Anthropic's ability to pay and the 2027 start date are what matter — and the migration of mining resources to AI, and its effect on bitcoin's hashrate and mining concentration, deserve watching too. A stock surge does not equal a mining boom.</div>
  <div class="box ja">💡 <strong>示唆:</strong> テラウルフ・アンスロピック契約は、ビットコイン採掘企業の最大の資産が採掘機ではなく「すでに確保された大容量電力」であることを確認させる。190億ドルは20年分の将来売上の合計にすぎず、アンスロピックの支払い能力と2027年の稼働日程が鍵であり、採掘資源のAIへの移動がビットコインのハッシュレートと採掘集中度に及ぼす影響も併せて注視すべきだ。株価急騰が採掘業の好況を意味するわけではない。</div>
  <div class="box es">💡 <strong>Conclusión:</strong> El arrendamiento TeraWulf–Anthropic confirma que el mayor activo de un minero de bitcoin no son sus máquinas, sino su "energía de alta capacidad ya asegurada". Los 19.000 millones son solo la suma de 20 años de ingresos futuros, así que lo que importa es la capacidad de pago de Anthropic y el arranque en 2027; y la migración de recursos mineros a la IA, y su efecto sobre el hashrate y la concentración minera de bitcoin, también merecen atención. Un repunte de la acción no equivale a un auge minero.</div>
  <div class="box de">💡 <strong>Fazit:</strong> Der TeraWulf–Anthropic-Mietvertrag bestätigt, dass das größte Kapital eines Bitcoin-Miners nicht seine Maschinen sind, sondern sein „bereits gesicherter Hochkapazitätsstrom". Die 19 Milliarden Dollar sind nur die Summe von 20 Jahren künftiger Einnahmen, daher zählen Anthropics Zahlungsfähigkeit und der Start 2027 — und auch die Abwanderung von Mining-Ressourcen zur KI sowie ihre Wirkung auf Bitcoins Hashrate und Mining-Konzentration verdienen Beobachtung. Ein Kurssprung ist kein Mining-Boom.</div>
  <div class="box fr">💡 <strong>À retenir :</strong> Le bail TeraWulf–Anthropic confirme que le principal actif d'un mineur de bitcoin n'est pas ses machines mais son « électricité de forte capacité déjà sécurisée ». Les 19 milliards de dollars ne sont que la somme de 20 années de revenus futurs, ce qui fait que la capacité de paiement d'Anthropic et le démarrage en 2027 sont ce qui compte vraiment — tout comme la migration des ressources minières vers l'IA, et son effet sur le hashrate et la concentration du minage de bitcoin, méritent d'être surveillés. Une envolée boursière n'équivaut pas à un boom du minage.</div>
  <div class="box pt">💡 <strong>Conclusão:</strong> O arrendamento TeraWulf–Anthropic confirma que o maior ativo de uma mineradora de bitcoin não são suas máquinas, mas sua "energia de alta capacidade já garantida". Os 19 bilhões de dólares são apenas a soma de 20 anos de receita futura, então a capacidade de pagamento da Anthropic e a data de início em 2027 são o que realmente importa — e a migração de recursos de mineração para a IA, e seu efeito sobre o hashrate e a concentração da mineração de bitcoin, também merecem atenção. Uma disparada nas ações não equivale a um boom da mineração.</div>
  <div class="box tr">💡 <strong>Sonuç:</strong> TeraWulf–Anthropic kira sözleşmesi, bir bitcoin madencisinin en büyük varlığının makineleri değil, "zaten güvence altına alınmış, yüksek kapasiteli gücü" olduğunu doğruluyor. 19 milyar dolar yalnızca 20 yıllık gelecekteki gelirin toplamıdır; dolayısıyla önemli olan Anthropic'in ödeme kapasitesi ve 2027 başlangıç tarihidir — ayrıca madencilik kaynaklarının yapay zekaya göçü ve bunun bitcoin'in hashrate'i ile madencilik yoğunlaşması üzerindeki etkisi de izlenmeyi hak ediyor. Hisse senedindeki sıçrama, madencilik patlaması anlamına gelmiyor.</div>
  <div class="box vi">💡 <strong>Điểm mấu chốt:</strong> Hợp đồng thuê TeraWulf–Anthropic khẳng định rằng tài sản lớn nhất của một công ty khai thác bitcoin không phải là máy móc mà là "nguồn điện công suất lớn đã được đảm bảo sẵn". Con số 19 tỷ đô la chỉ là tổng doanh thu tương lai trong 20 năm, nên khả năng chi trả của Anthropic và mốc khởi động năm 2027 mới là điều quan trọng — và việc di chuyển các nguồn lực khai thác sang AI, cùng tác động của nó lên hashrate và mức độ tập trung khai thác của bitcoin, cũng đáng được theo dõi. Cổ phiếu tăng vọt không đồng nghĩa với một cơn bùng nổ khai thác.</div>

  <p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 테라울프(WULF) 보도자료 '앤트로픽 임대 및 애버내시 합작 지분 매각', 로이터, CNBC, 코인데스크, The Block, 데이터센터다이내믹스, 블록스페이스. 업계 AI·HPC 계약 및 해시레이트 통계는 S&amp;P 글로벌·코인데스크 집계, 아이렌·마이크로소프트, 코어사이언티픽, 사이퍼 마이닝 사례 참고. AI 매출 비중 전망은 업계 추정치.</p>
  <p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: TeraWulf (WULF) press release "Anthropic Lease and Sale of Abernathy JV Interest," Reuters, CNBC, CoinDesk, The Block, DataCenterDynamics, Blockspace. Sector AI/HPC contract and hashrate figures per S&amp;P Global and CoinDesk tallies, with IREN–Microsoft, Core Scientific and Cipher Mining as comparisons. AI revenue-share outlook is an industry estimate.</p>
  <p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: テラウルフ(WULF)発表「アンスロピック・リースおよびアバナシー合弁持分の売却」、ロイター、CNBC、コインデスク、The Block、データセンターダイナミクス、ブロックスペース。業界のAI・HPC契約およびハッシュレート統計はS&amp;Pグローバル・コインデスク集計、アイレン・マイクロソフト、コアサイエンティフィック、サイファー・マイニングの事例を参照。AI売上比率の見通しは業界推計。</p>
  <p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: comunicado de TeraWulf (WULF) "Arrendamiento con Anthropic y venta de la participación en la JV Abernathy", Reuters, CNBC, CoinDesk, The Block, DataCenterDynamics, Blockspace. Cifras de contratos de IA/HPC del sector y hashrate según recuentos de S&amp;P Global y CoinDesk, con IREN–Microsoft, Core Scientific y Cipher Mining como comparaciones. La previsión de la proporción de ingresos de IA es una estimación del sector.</p>
  <p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: TeraWulf-(WULF)-Mitteilung „Anthropic-Mietvertrag und Verkauf des Abernathy-JV-Anteils", Reuters, CNBC, CoinDesk, The Block, DataCenterDynamics, Blockspace. Branchenzahlen zu KI/HPC-Verträgen und Hashrate nach Aufstellungen von S&amp;P Global und CoinDesk, mit IREN–Microsoft, Core Scientific und Cipher Mining als Vergleich. Der Ausblick zum KI-Umsatzanteil ist eine Branchenschätzung.</p>
  <p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : communiqué de presse de TeraWulf (WULF), « Bail avec Anthropic et cession de la participation dans la coentreprise Abernathy », Reuters, CNBC, CoinDesk, The Block, DataCenterDynamics, Blockspace. Les chiffres sectoriels sur les contrats IA/HPC et le hashrate proviennent des décomptes de S&amp;P Global et de CoinDesk, avec IREN–Microsoft, Core Scientific et Cipher Mining à titre de comparaison. La prévision de part des revenus IA est une estimation du secteur.</p>
  <p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: comunicado de imprensa da TeraWulf (WULF), "Arrendamento com a Anthropic e venda da participação na JV Abernathy", Reuters, CNBC, CoinDesk, The Block, DataCenterDynamics, Blockspace. Os números setoriais de contratos de IA/HPC e hashrate seguem os levantamentos da S&amp;P Global e da CoinDesk, com IREN–Microsoft, Core Scientific e Cipher Mining como comparação. A previsão de participação da receita de IA é uma estimativa do setor.</p>
  <p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: TeraWulf (WULF) basın bülteni "Anthropic Kira Sözleşmesi ve Abernathy Ortak Girişim Payının Satışı", Reuters, CNBC, CoinDesk, The Block, DataCenterDynamics, Blockspace. Sektördeki AI/HPC sözleşme ve hashrate rakamları S&amp;P Global ile CoinDesk derlemelerine dayanmaktadır; karşılaştırma için IREN–Microsoft, Core Scientific ve Cipher Mining örnek alınmıştır. Yapay zeka gelir payı öngörüsü sektör tahminidir.</p>
  <p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: thông cáo báo chí của TeraWulf (WULF) "Hợp đồng thuê với Anthropic và việc bán cổ phần liên doanh Abernathy", Reuters, CNBC, CoinDesk, The Block, DataCenterDynamics, Blockspace. Số liệu về hợp đồng AI/HPC và hashrate của ngành theo thống kê của S&amp;P Global và CoinDesk, với IREN–Microsoft, Core Scientific và Cipher Mining làm ví dụ so sánh. Dự báo tỷ trọng doanh thu AI là ước tính của ngành.</p>
<?php require __DIR__.'/_footer.php'; ?>
