<?php $slug = 'tweet-volume-12month-low-institutional-gap'; require __DIR__.'/_header.php'; ?>

<p class="ko">비트코인은 7월14일 오전(한국시간) 6만2,600~6만2,900달러 사이에서 움직이며 최근 며칠째 이어진 좁은 박스권을 벗어나지 못하고 있다. 그런데 몇 시간 전 더블록이 공개한 전혀 다른 차트는 더 날카로운 이야기를 담고 있었다. '비트코인'과 '이더리움' 키워드가 포함된 주간 트윗(X 게시물) 수가 최근 12개월 내 최저치로 떨어졌다는 것이다. 비트코인 관련 언급은 약 13만건, 이더리움은 약 4만건까지 줄었는데, 이는 기관 자금이 아직 크립토 시장에 본격적으로 들어오기 전인 2020년 수준의 관심도다(더블록).</p>
<p class="en">Bitcoin traded between $62,600 and $62,900 on the morning of July 14 (KST), still boxed inside the same narrow range it has held for days. But a very different chart, published just hours earlier by The Block, told a sharper story: weekly Twitter/X mentions containing the keywords "Bitcoin" and "Ethereum" have fallen to their lowest level in 12 months. Bitcoin mentions are down to roughly 130,000 and Ethereum to around 40,000 — a level of retail chatter last seen in 2020, before institutional money had meaningfully entered the crypto market (The Block).</p>
<p class="ja">ビットコインは7月14日午前(韓国時間)時点で6万2,600~6万2,900ドルの間で推移し、ここ数日続く狭いレンジから抜け出せずにいる。だが数時間前にザ・ブロックが公開したまったく別のチャートは、より鋭い物語を伝えていた。「ビットコイン」「イーサリアム」というキーワードを含む週間ツイート(X投稿)数が、直近12カ月で最低水準まで落ち込んだというのだ。ビットコイン関連の言及は約13万件、イーサリアムは約4万件まで減少し、これは機関資金が本格的にクリプト市場へ流入する前、2020年当時の水準に相当する(ザ・ブロック)。</p>
<p class="es">Bitcoin cotizó entre $62,600 y $62,900 en la mañana del 14 de julio (hora de Corea), todavía encajonado en el mismo rango estrecho que ha mantenido durante días. Pero un gráfico muy distinto, publicado apenas horas antes por The Block, contaba una historia más aguda: las menciones semanales en Twitter/X que contienen las palabras clave "Bitcoin" y "Ethereum" cayeron a su nivel más bajo en 12 meses. Las menciones de Bitcoin bajaron a unas 130,000 y las de Ethereum a cerca de 40,000 — un nivel de conversación minorista que no se veía desde 2020, antes de que el dinero institucional hubiera entrado de forma significativa al mercado cripto (The Block).</p>
<p class="de">Bitcoin notierte am Morgen des 14. Juli (KST) zwischen 62.600 und 62.900 Dollar und steckt weiterhin in derselben engen Spanne fest, die er seit Tagen hält. Doch ein ganz anderes Diagramm, das The Block nur Stunden zuvor veröffentlichte, erzählte eine schärfere Geschichte: Die wöchentlichen Twitter/X-Erwähnungen mit den Schlagworten "Bitcoin" und "Ethereum" sind auf ihr niedrigstes Niveau seit 12 Monaten gefallen. Bitcoin-Erwähnungen sanken auf etwa 130.000, Ethereum auf rund 40.000 — ein Niveau an Privatanleger-Gerede, das zuletzt 2020 zu beobachten war, bevor institutionelles Geld nennenswert in den Kryptomarkt geflossen war (The Block).</p>
<p class="fr">Le bitcoin s'est échangé entre 62 600 et 62 900 dollars au matin du 14 juillet (heure de Corée), toujours enfermé dans la même fourchette étroite qu'il maintient depuis des jours. Mais un graphique très différent, publié quelques heures plus tôt par The Block, racontait une histoire plus tranchante : les mentions hebdomadaires sur Twitter/X contenant les mots-clés « Bitcoin » et « Ethereum » sont tombées à leur plus bas niveau en 12 mois. Les mentions de Bitcoin sont descendues à environ 130 000 et celles d'Ethereum à environ 40 000 — un niveau de bavardage grand public qu'on n'avait plus vu depuis 2020, avant que l'argent institutionnel n'entre significativement sur le marché crypto (The Block).</p>
<p class="pt">O bitcoin foi negociado entre US$ 62.600 e US$ 62.900 na manhã de 14 de julho (horário da Coreia), ainda preso na mesma faixa estreita que vem mantendo há dias. Mas um gráfico bem diferente, publicado poucas horas antes pela The Block, contava uma história mais afiada: as menções semanais no Twitter/X contendo as palavras-chave "Bitcoin" e "Ethereum" caíram para o nível mais baixo em 12 meses. As menções ao bitcoin caíram para cerca de 130.000 e as ao ethereum para cerca de 40.000 — um nível de conversa do varejo não visto desde 2020, antes de o dinheiro institucional ter entrado de forma significativa no mercado cripto (The Block).</p>
<p class="tr">Bitcoin, 14 Temmuz (KST) sabahı itibarıyla 62.600 ile 62.900 dolar arasında işlem gördü ve günlerdir sürdürdüğü aynı dar aralığın dışına çıkamadı. Ancak The Block'un birkaç saat önce yayımladığı çok farklı bir grafik daha keskin bir hikâye anlatıyordu: "Bitcoin" ve "Ethereum" anahtar kelimelerini içeren haftalık Twitter/X bahisleri 12 ayın en düşük seviyesine geriledi. Bitcoin bahisleri yaklaşık 130.000'e, Ethereum ise yaklaşık 40.000'e geriledi — bu, kurumsal paranın kripto piyasasına henüz ciddi biçimde girmediği 2020 seviyelerinde bir perakende ilgisi anlamına geliyor (The Block).</p>
<p class="vi">Bitcoin giao dịch trong khoảng 62.600-62.900 đô la vào sáng ngày 14 tháng 7 (giờ Hàn Quốc), vẫn bị kẹt trong cùng biên độ hẹp đã duy trì suốt nhiều ngày qua. Nhưng một biểu đồ hoàn toàn khác, được The Block công bố chỉ vài giờ trước đó, kể một câu chuyện sắc bén hơn: số lượt nhắc đến từ khóa "Bitcoin" và "Ethereum" trên Twitter/X hàng tuần đã giảm xuống mức thấp nhất trong 12 tháng. Lượt nhắc đến Bitcoin giảm còn khoảng 130.000 và Ethereum còn khoảng 40.000 — mức độ bàn tán của nhà đầu tư nhỏ lẻ chưa từng thấy kể từ năm 2020, thời điểm dòng tiền tổ chức chưa thực sự đổ vào thị trường crypto (The Block).</p>

<p class="ko">이 대비 자체가 핵심이다. 2020년의 낮은 소셜 관심도는 기관도 함께 부재했던 시장에서 나타난 현상이었다. 그런데 지금은 정확히 같은 침묵이, 비트코인 현물 ETF가 2주 연속 순유입을 기록하고 토큰화된 실물자산(RWA)이 온체인 기준 330억달러를 넘어선 국면에서 벌어지고 있다. 이번 점검은 대중이 조용해진 바로 그 시점에 자금은 계속 들어오고 있다는 것이 무엇을 의미하는지, 그리고 '트윗 볼륨 저하 = 가격 정체'라는 과거의 경험칙이 발언권을 쥔 매수 주체 자체가 바뀐 지금도 여전히 유효한지를 짚는다.</p>
<p class="en">That comparison is the whole point. In 2020, thin retail chatter accompanied a market where institutions were largely absent too. Today, the same social-media silence is unfolding while spot Bitcoin ETFs have just logged back-to-back weekly inflows and tokenized real-world assets have crossed $33 billion on-chain. This check examines what it means when the crowd goes quiet at the exact moment the money keeps arriving — and whether the historical link between low tweet volume and price stagnation still holds now that the buyers doing the talking have changed.</p>
<p class="ja">この対比こそが本質だ。2020年の低い関心度は、機関投資家も同時に不在だった市場で起きた現象だった。だが今は、まさに同じ沈黙が、ビットコイン現物ETFが2週連続で純流入を記録し、トークン化された実物資産(RWA)がオンチェーン基準で330億ドルを超えた局面で起きている。今回の点検では、大衆が静かになったまさにその瞬間に資金が流入し続けているとはどういうことか、そして「トゥイート量の低下=価格停滞」という過去の経験則が、発言力を持つ買い手そのものが入れ替わった今も通用するのかを検証する。</p>
<p class="es">Esa comparación es todo el punto. En 2020, la escasa conversación minorista acompañaba a un mercado donde las instituciones también estaban mayormente ausentes. Hoy, ese mismo silencio en redes sociales se desarrolla mientras los ETF spot de Bitcoin acaban de registrar entradas netas semanales consecutivas y los activos del mundo real tokenizados (RWA) han superado los $33,000 millones on-chain. Este análisis examina qué significa que la multitud guarde silencio justo en el momento en que el dinero sigue llegando — y si el vínculo histórico entre el bajo volumen de tuits y el estancamiento de precios todavía se sostiene ahora que los compradores que tienen la palabra han cambiado.</p>
<p class="de">Genau dieser Vergleich ist der Kern. 2020 ging das geringe Privatanleger-Gerede mit einem Markt einher, in dem auch Institutionen weitgehend abwesend waren. Heute entfaltet sich dieselbe Stille in den sozialen Medien, während Spot-Bitcoin-ETFs gerade zwei aufeinanderfolgende Wochen mit Nettozuflüssen verzeichnet haben und tokenisierte reale Vermögenswerte (RWA) on-chain die 33-Milliarden-Dollar-Marke überschritten haben. Diese Analyse untersucht, was es bedeutet, wenn die Menge genau in dem Moment verstummt, in dem das Geld weiter hereinströmt — und ob die historische Verbindung zwischen niedrigem Tweet-Volumen und Kursstagnation noch gilt, nachdem sich die Käufer, die eigentlich das Wort führen, verändert haben.</p>
<p class="fr">Cette comparaison est tout l'enjeu. En 2020, le faible bavardage des particuliers accompagnait un marché où les institutions étaient elles aussi largement absentes. Aujourd'hui, ce même silence sur les réseaux sociaux se déroule alors que les ETF bitcoin au comptant viennent d'enregistrer des entrées nettes hebdomadaires consécutives et que les actifs du monde réel tokenisés (RWA) ont dépassé les 33 milliards de dollars on-chain. Cette analyse examine ce que signifie le silence de la foule au moment précis où l'argent continue d'arriver — et si le lien historique entre faible volume de tweets et stagnation des prix tient toujours maintenant que les acheteurs qui ont la parole ont changé.</p>
<p class="pt">Essa comparação é todo o cerne da questão. Em 2020, a escassa conversa do varejo acompanhava um mercado em que as instituições também estavam majoritariamente ausentes. Hoje, esse mesmo silêncio nas redes sociais se desenrola enquanto os ETFs à vista de bitcoin acabam de registrar entradas líquidas semanais consecutivas e os ativos do mundo real tokenizados (RWA) ultrapassaram US$ 33 bilhões on-chain. Esta análise examina o que significa a multidão ficar quieta exatamente no momento em que o dinheiro continua chegando — e se o vínculo histórico entre baixo volume de tweets e estagnação de preços ainda se sustenta agora que os compradores com voz ativa mudaram.</p>
<p class="tr">Bu karşılaştırma meselenin tam özü. 2020'de zayıf perakende sohbeti, kurumların da büyük ölçüde yok olduğu bir piyasada görülmüştü. Bugün ise aynı sosyal medya sessizliği, spot Bitcoin ETF'lerinin art arda haftalık net giriş kaydettiği ve tokenize edilmiş gerçek dünya varlıklarının (RWA) zincir üstünde 33 milyar doları aştığı bir dönemde yaşanıyor. Bu inceleme, kitlenin tam olarak paranın gelmeye devam ettiği anda sessizleşmesinin ne anlama geldiğini ve düşük tweet hacmi ile fiyat durgunluğu arasındaki tarihsel bağın, konuşma hakkını elinde tutan alıcılar değiştikten sonra hâlâ geçerli olup olmadığını ele alıyor.</p>
<p class="vi">Sự so sánh đó chính là trọng tâm. Vào năm 2020, lượng bàn tán ít ỏi của nhà đầu tư nhỏ lẻ đi kèm với một thị trường mà các tổ chức cũng phần lớn vắng mặt. Ngày nay, sự im lặng tương tự trên mạng xã hội đang diễn ra trong khi các ETF Bitcoin giao ngay vừa ghi nhận dòng vốn ròng vào hai tuần liên tiếp và tài sản thực được token hóa (RWA) đã vượt mốc 33 tỷ đô la trên chuỗi. Bài kiểm tra này xem xét ý nghĩa của việc đám đông im lặng đúng vào thời điểm dòng tiền vẫn tiếp tục đổ vào — và liệu mối liên hệ lịch sử giữa khối lượng tweet thấp và sự trì trệ giá cả có còn đúng hay không, khi mà nhóm người mua đang lên tiếng đã thay đổi.</p>

<h2 class="ko">왜 대중의 관심도가 2020년 수준으로 되돌아갔나</h2>
<h2 class="en">Why Retail Chatter Round-Tripped Back to 2020 Levels</h2>
<h2 class="ja">なぜ大衆の関心度は2020年水準まで逆戻りしたのか</h2>
<h2 class="es">Por Qué la Conversación Minorista Volvió a los Niveles de 2020</h2>
<h2 class="de">Warum das Privatanleger-Gerede Auf das Niveau von 2020 Zurückfiel</h2>
<h2 class="fr">Pourquoi le Bavardage des Particuliers Est Revenu aux Niveaux de 2020</h2>
<h2 class="pt">Por Que a Conversa do Varejo Voltou aos Níveis de 2020</h2>
<h2 class="tr">Perakende Sohbeti Neden 2020 Seviyelerine Geri Döndü</h2>
<h2 class="vi">Tại Sao Sự Bàn Tán Của Nhà Đầu Tư Nhỏ Lẻ Quay Lại Mức Của Năm 2020</h2>

<p class="ko">더블록의 '트윗 볼륨' 지표는 X(옛 트위터)에 올라온 게시물 중 '비트코인'·'이더리움' 키워드가 포함된 주간 건수를 집계하는 지표로, 실제 자금 흐름이 아니라 일반 대중이 이 자산들에 대해 얼마나 이야기하고 있는지를 보여주는 대략적인 대리지표(proxy)다. 소셜 데이터 집계업체의 자료를 기반으로 하며, 코인 가격이나 온체인 거래량과는 별개로 움직인다. 현재 수치(비트코인 약 13만건, 이더리움 약 4만건)는 2021~2024년의 반복된 강세장·밈코인 열풍기에 형성됐던 언급량 기준선을 뚜렷이 밑돌며, 기관 자금 유입이 본격화되기 전이었던 2020년 수준까지 되돌아간 것이다.</p>
<p class="en">The Block's Tweet Volume metric counts weekly posts on X (formerly Twitter) that contain the keywords "Bitcoin" and "Ethereum" — a rough proxy for how much the general public is talking about these assets, not a measure of actual capital flow. It's built on social-data aggregator feeds and moves independently of price or on-chain transaction volume. The current reading (roughly 130,000 for Bitcoin, 40,000 for Ethereum) sits clearly below the baseline mention levels that built up during the repeated bull runs and meme-coin frenzies of 2021-2024, and has round-tripped back to where it stood in 2020, before institutional inflows had meaningfully picked up.</p>
<p class="ja">ザ・ブロックの「トゥイート量」指標は、X(旧Twitter)上で「ビットコイン」「イーサリアム」というキーワードを含む投稿の週間件数を集計するもので、実際の資金の流れではなく、一般大衆がこれらの資産についてどれだけ話題にしているかを示すおおまかな代理指標(プロキシ)だ。ソーシャルデータ集計業者のフィードを基にしており、価格やオンチェーンの取引量とは独立して動く。現在の数値(ビットコイン約13万件、イーサリアム約4万件)は、2021~2024年に繰り返された強気相場やミームコイン熱狂期に積み上がった言及量の基準を明らかに下回っており、機関資金の流入が本格化する前だった2020年当時の水準まで逆戻りしている。</p>
<p class="es">La métrica de Volumen de Tuits de The Block cuenta las publicaciones semanales en X (antes Twitter) que contienen las palabras clave "Bitcoin" y "Ethereum" — un indicador aproximado de cuánto habla el público general sobre estos activos, no una medida del flujo real de capital. Se construye a partir de feeds de agregadores de datos sociales y se mueve de forma independiente del precio o del volumen de transacciones on-chain. La lectura actual (unas 130,000 para Bitcoin, 40,000 para Ethereum) está claramente por debajo de los niveles base de menciones que se acumularon durante los repetidos mercados alcistas y la locura de las meme-coins de 2021-2024, y ha vuelto exactamente a donde estaba en 2020, antes de que las entradas institucionales hubieran repuntado de forma significativa.</p>
<p class="de">Die "Tweet-Volumen"-Kennzahl von The Block zählt wöchentliche Beiträge auf X (ehemals Twitter), die die Schlagworte "Bitcoin" und "Ethereum" enthalten — ein grober Näherungswert dafür, wie viel die breite Öffentlichkeit über diese Assets spricht, keine Messung des tatsächlichen Kapitalflusses. Sie basiert auf Feeds von Social-Data-Aggregatoren und bewegt sich unabhängig von Kurs oder On-Chain-Transaktionsvolumen. Der aktuelle Wert (rund 130.000 für Bitcoin, 40.000 für Ethereum) liegt deutlich unter dem Erwähnungsniveau, das sich während der wiederholten Bullenmärkte und Meme-Coin-Manien von 2021-2024 aufgebaut hatte, und ist genau dorthin zurückgekehrt, wo er 2020 stand, bevor institutionelle Zuflüsse nennenswert zunahmen.</p>
<p class="fr">L'indicateur « Volume de Tweets » de The Block comptabilise les publications hebdomadaires sur X (anciennement Twitter) contenant les mots-clés « Bitcoin » et « Ethereum » — un indicateur approximatif de l'ampleur avec laquelle le grand public parle de ces actifs, et non une mesure du flux de capitaux réel. Il repose sur des flux d'agrégateurs de données sociales et évolue indépendamment du prix ou du volume de transactions on-chain. Le niveau actuel (environ 130 000 pour le bitcoin, 40 000 pour l'ethereum) se situe nettement en dessous des niveaux de mentions accumulés pendant les marchés haussiers répétés et les frénésies de meme-coins de 2021-2024, et est revenu exactement là où il se trouvait en 2020, avant que les entrées institutionnelles n'aient véritablement décollé.</p>
<p class="pt">A métrica de Volume de Tweets da The Block conta as postagens semanais no X (antigo Twitter) que contêm as palavras-chave "Bitcoin" e "Ethereum" — um proxy aproximado de quanto o público em geral está falando sobre esses ativos, não uma medida do fluxo real de capital. Ela é construída a partir de feeds de agregadores de dados sociais e se move de forma independente do preço ou do volume de transações on-chain. A leitura atual (cerca de 130.000 para bitcoin, 40.000 para ethereum) está claramente abaixo dos níveis básicos de menções acumulados durante os repetidos mercados em alta e frenesis de meme-coins de 2021-2024, e voltou exatamente para onde estava em 2020, antes que as entradas institucionais tivessem decolado de forma significativa.</p>
<p class="tr">The Block'un "Tweet Hacmi" göstergesi, X'te (eski adıyla Twitter) "Bitcoin" ve "Ethereum" anahtar kelimelerini içeren haftalık gönderileri sayıyor — bu, gerçek sermaye akışının değil, genel halkın bu varlıklar hakkında ne kadar konuştuğunun kabaca bir vekil göstergesi. Sosyal veri toplayıcı akışlarına dayanıyor ve fiyattan veya zincir üstü işlem hacminden bağımsız hareket ediyor. Mevcut okuma (Bitcoin için yaklaşık 130.000, Ethereum için 40.000) 2021-2024'ün tekrarlanan boğa piyasaları ve meme-coin çılgınlıkları sırasında oluşan bahis seviyelerinin belirgin biçimde altında ve kurumsal girişlerin henüz ciddi biçimde ivme kazanmadığı 2020'de bulunduğu seviyeye tam olarak geri döndü.</p>
<p class="vi">Chỉ số "Khối Lượng Tweet" của The Block đếm số bài đăng hàng tuần trên X (trước đây là Twitter) có chứa từ khóa "Bitcoin" và "Ethereum" — một chỉ số đại diện gần đúng cho mức độ công chúng bàn luận về các tài sản này, chứ không phải thước đo dòng vốn thực tế. Chỉ số này được xây dựng từ nguồn dữ liệu của các đơn vị tổng hợp dữ liệu mạng xã hội và di chuyển độc lập với giá hoặc khối lượng giao dịch trên chuỗi. Mức đọc hiện tại (khoảng 130.000 cho Bitcoin, 40.000 cho Ethereum) nằm rõ ràng dưới mức nền của lượt nhắc đến đã tích lũy trong các đợt tăng giá lặp lại và cơn sốt meme-coin giai đoạn 2021-2024, và đã quay trở lại đúng mức của năm 2020, trước khi dòng vốn tổ chức thực sự tăng tốc.</p>

<p class="ko">이런 침묵은 결과이지 원인이 아니다. 2026년 상반기 내내 이어진 가격 정체와 조정장(비트코인 전체 유통량의 절반 이상이 미실현 손실 구간에 놓였다는 <a href="/blog/btc-supply-in-loss-crossover-2026.php">이 사이트의 이전 점검</a>이 짚었던 대목이다), 그리고 반복된 돌파 실패는 한때 밈코인 열풍이나 ETF 출시 같은 이벤트가 만들어냈던 언급량 급등 유인을 사실상 소진시켰다. 과거에도 트윗 볼륨 저하는 가격 정체나 하락 국면과 함께 나타나는 경향이 있었지만, 이는 트윗 볼륨이 가격을 예측한다기보다는 가격 움직임을 뒤따라가는 거울에 가깝다는 뜻이기도 하다. 즉 지금의 침묵은 시장이 조용해서라기보다, 시장이 오랫동안 대중을 흥분시킬 만한 재료를 주지 못했기 때문에 나타난 결과로 읽을 수 있다.</p>
<p class="en">This silence is more a symptom than a cause. Months of price stagnation and drawdown through the first half of 2026 — <a href="/blog/btc-supply-in-loss-crossover-2026.php">a period this site previously flagged</a> as one where more than half of Bitcoin's circulating supply sat at an unrealized loss — combined with repeated failed breakouts have largely drained the kind of catalysts that once drove mention spikes, like meme-coin frenzies or ETF-launch euphoria. Historically, low tweet volume has tended to coincide with periods of price stagnation or decline, which also means the metric behaves more like a mirror trailing price action than a leading predictor of it. In other words, today's quiet is less a cause of market calm than a byproduct of a market that has gone a long time without giving the public a reason to get excited.</p>
<p class="ja">この沈黙は原因というより結果に近い。2026年上半期を通じて続いた価格の停滞と調整局面——<a href="/blog/btc-supply-in-loss-crossover-2026.php">当サイトの以前の点検</a>では、ビットコインの流通供給量の半分以上が未実現損失圏にあると指摘した——に加え、繰り返された突破の失敗が、かつてミームコイン熱狂やETF上場の高揚感が生み出していたような言及急増の誘因をほぼ枯渇させた。過去にもトゥイート量の低下は価格の停滞や下落局面と重なる傾向があったが、これはトゥイート量が価格を予測するというより、価格の動きを後追いする鏡に近いことを意味してもいる。つまり今の静けさは、市場が静かだから生じたというより、市場が長い間、大衆を興奮させる材料を提供できずにいた結果として読み解ける。</p>
<p class="es">Este silencio es más un síntoma que una causa. Meses de estancamiento de precios y caídas durante la primera mitad de 2026 — <a href="/blog/btc-supply-in-loss-crossover-2026.php">un período que este sitio ya señaló</a> como aquel en que más de la mitad del suministro circulante de Bitcoin estaba en pérdida no realizada — combinados con repetidos intentos fallidos de ruptura han agotado en gran medida el tipo de catalizadores que antes generaban picos de menciones, como las frenesis de meme-coins o la euforia por el lanzamiento de ETF. Históricamente, el bajo volumen de tuits ha tendido a coincidir con períodos de estancamiento o caída de precios, lo que también significa que el indicador se comporta más como un espejo que sigue a la acción del precio que como un predictor adelantado de esta. En otras palabras, el silencio de hoy es menos una causa de la calma del mercado que un subproducto de un mercado que lleva mucho tiempo sin dar al público un motivo para entusiasmarse.</p>
<p class="de">Diese Stille ist eher ein Symptom als eine Ursache. Monate der Kursstagnation und des Rückgangs in der ersten Hälfte des Jahres 2026 — <a href="/blog/btc-supply-in-loss-crossover-2026.php">ein Zeitraum, den diese Seite bereits als Phase kennzeichnete</a>, in der mehr als die Hälfte des zirkulierenden Bitcoin-Angebots einen nicht realisierten Verlust auswies — haben zusammen mit wiederholt gescheiterten Ausbrüchen weitgehend jene Katalysatoren erschöpft, die früher Erwähnungsspitzen auslösten, etwa Meme-Coin-Manien oder ETF-Launch-Euphorie. Historisch fiel ein niedriges Tweet-Volumen tendenziell mit Phasen der Kursstagnation oder des Rückgangs zusammen, was auch bedeutet, dass sich die Kennzahl eher wie ein der Kursbewegung nachlaufender Spiegel verhält als wie ein vorlaufender Indikator dafür. Mit anderen Worten: Die heutige Stille ist weniger Ursache der Marktruhe als Nebenprodukt eines Marktes, der der Öffentlichkeit lange keinen Grund zur Begeisterung geliefert hat.</p>
<p class="fr">Ce silence est davantage un symptôme qu'une cause. Des mois de stagnation des prix et de repli au cours du premier semestre 2026 — <a href="/blog/btc-supply-in-loss-crossover-2026.php">une période que ce site avait déjà signalée</a> comme celle où plus de la moitié de l'offre en circulation du bitcoin se trouvait en perte latente — combinés à des tentatives de cassure répétées et infructueuses ont largement épuisé le type de catalyseurs qui généraient autrefois des pics de mentions, comme les frénésies de meme-coins ou l'euphorie liée au lancement d'ETF. Historiquement, un faible volume de tweets a eu tendance à coïncider avec des périodes de stagnation ou de baisse des prix, ce qui signifie aussi que l'indicateur se comporte davantage comme un miroir suivant l'évolution des prix que comme un prédicteur avancé de celle-ci. Autrement dit, le silence d'aujourd'hui est moins une cause du calme du marché qu'un sous-produit d'un marché qui, depuis longtemps, ne donne plus au public de raison de s'enthousiasmer.</p>
<p class="pt">Esse silêncio é mais um sintoma do que uma causa. Meses de estagnação de preços e retração ao longo do primeiro semestre de 2026 — <a href="/blog/btc-supply-in-loss-crossover-2026.php">período que este site já apontou</a> como aquele em que mais da metade da oferta em circulação de bitcoin estava em perda não realizada — combinados com repetidas tentativas fracassadas de rompimento esgotaram em grande parte o tipo de catalisador que antes gerava picos de menções, como frenesis de meme-coins ou euforia de lançamento de ETF. Historicamente, o baixo volume de tweets tendeu a coincidir com períodos de estagnação ou queda de preços, o que também significa que o indicador se comporta mais como um espelho que segue a ação do preço do que como um preditor antecipado dela. Em outras palavras, o silêncio de hoje é menos uma causa da calmaria do mercado do que um subproduto de um mercado que há muito tempo não dá ao público um motivo para se empolgar.</p>
<p class="tr">Bu sessizlik bir nedenden çok bir belirti. 2026'nın ilk yarısı boyunca süren fiyat durgunluğu ve gerileme — <a href="/blog/btc-supply-in-loss-crossover-2026.php">bu sitenin daha önce belirttiği</a>, Bitcoin'in dolaşımdaki arzının yarısından fazlasının gerçekleşmemiş zarar bölgesinde olduğu bir dönem — tekrarlanan başarısız kırılım denemeleriyle birleşince, meme-coin çılgınlıkları veya ETF lansmanı coşkusu gibi geçmişte bahis patlamalarına yol açan katalizörleri büyük ölçüde tüketti. Tarihsel olarak, düşük tweet hacmi fiyat durgunluğu veya düşüş dönemleriyle örtüşme eğilimindeydi; bu da göstergenin fiyatı öngören bir gösterge olmaktan çok, fiyat hareketini takip eden bir ayna gibi davrandığı anlamına geliyor. Başka bir deyişle, bugünkü sessizlik piyasanın sakinliğinin bir nedeni olmaktan çok, halka uzun süredir heyecanlanacak bir sebep vermeyen bir piyasanın yan ürünü olarak okunabilir.</p>
<p class="vi">Sự im lặng này là triệu chứng nhiều hơn là nguyên nhân. Nhiều tháng giá trì trệ và điều chỉnh xuyên suốt nửa đầu năm 2026 — <a href="/blog/btc-supply-in-loss-crossover-2026.php">giai đoạn mà trang này từng chỉ ra</a> là thời điểm hơn một nửa nguồn cung lưu hành của Bitcoin nằm trong vùng lỗ chưa thực hiện — kết hợp với các lần phá vỡ thất bại lặp đi lặp lại đã làm cạn kiệt phần lớn loại chất xúc tác từng tạo ra các đợt tăng vọt lượt nhắc đến, như cơn sốt meme-coin hay sự phấn khích khi ra mắt ETF. Về mặt lịch sử, khối lượng tweet thấp có xu hướng trùng với các giai đoạn giá trì trệ hoặc suy giảm, điều này cũng có nghĩa là chỉ số này hoạt động giống một tấm gương theo sau biến động giá hơn là một chỉ báo dẫn dắt giá. Nói cách khác, sự im lặng hôm nay ít mang tính nguyên nhân của sự bình lặng thị trường hơn là hệ quả của một thị trường đã lâu không cho công chúng lý do để hào hứng.</p>

<h2 class="ko">그 사이 기관 자금의 장부는 정반대 방향을 가리키고 있다</h2>
<h2 class="en">Meanwhile, the Institutional Ledger Points the Other Way</h2>
<h2 class="ja">その間、機関資金の帳簿は正反対の方向を示している</h2>
<h2 class="es">Mientras Tanto, el Libro Contable Institucional Apunta en Dirección Contraria</h2>
<h2 class="de">Unterdessen Zeigt das Institutionelle Kontobuch in die Entgegengesetzte Richtung</h2>
<h2 class="fr">Pendant ce Temps, le Registre Institutionnel Pointe dans la Direction Opposée</h2>
<h2 class="pt">Enquanto Isso, o Livro-Razão Institucional Aponta na Direção Oposta</h2>
<h2 class="tr">Bu Arada Kurumsal Defter Tam Tersi Yönü İşaret Ediyor</h2>
<h2 class="vi">Trong Khi Đó, Sổ Sách Của Các Tổ Chức Lại Chỉ Về Hướng Ngược Lại</h2>

<p class="ko">미국 현물 비트코인 ETF는 6월 45억달러 순유출이라는 최악의 달을 보낸 뒤, 7월2일과 7월11일 마감 주간 연속 순유입(각각 2억2,172만달러, 1억9,740만달러)으로 돌아섰다. 같은 달 중앙화거래소(CEX)의 현물 거래량은 5개월 만에 처음으로 반등해 6월 한 달 15.3% 늘어난 1조1,100억달러를 기록했고, 실물자산(RWA) 연계 무기한선물 거래량은 사상 최고치인 3,110억달러까지 치솟았다(코인데스크). 이 수치들은 '거래'라는 행위 자체가 늘고 있다는 뜻이며, 소셜미디어에서의 언급량과는 전혀 다른 방향을 그리고 있다.</p>
<p class="en">U.S. spot Bitcoin ETFs, after enduring their worst month on record in June with $4.5 billion in net outflows, swung to back-to-back weekly net inflows for the weeks ending July 2 and July 11 ($221.72 million and $197.4 million, respectively). That same June, centralized-exchange (CEX) spot trading volumes rebounded for the first time in five months, rising 15.3% to $1.11 trillion, while real-world-asset (RWA) perpetual futures volume surged to a record $311 billion (CoinDesk). Those numbers describe an increase in the sheer act of trading and capital movement — tracing a completely different line than the mention count on social media.</p>
<p class="ja">米国の現物ビットコインETFは、6月に45億ドルの純流出という過去最悪の月を経験した後、7月2日と7月11日締め週に連続で純流入(それぞれ2億2,172万ドル、1億9,740万ドル)へと転じた。同じ6月、中央集権型取引所(CEX)の現物取引量は5カ月ぶりに反発し、月間15.3%増の1兆1,100億ドルを記録、実物資産(RWA)連動の無期限先物取引量は過去最高の3,110億ドルまで急増した(コインデスク)。これらの数字は「取引」という行為そのものが増えていることを示しており、ソーシャルメディア上の言及量とはまったく異なる方向を描いている。</p>
<p class="es">Los ETF spot de Bitcoin en EE.UU., tras soportar su peor mes registrado en junio con $4,500 millones en salidas netas, se revirtieron hacia entradas netas semanales consecutivas en las semanas que terminaron el 2 y el 11 de julio ($221.72 millones y $197.4 millones, respectivamente). Ese mismo junio, el volumen de trading spot de los exchanges centralizados (CEX) repuntó por primera vez en cinco meses, subiendo 15.3% hasta $1.11 billones, mientras que el volumen de futuros perpetuos ligados a activos del mundo real (RWA) se disparó hasta un récord de $311,000 millones (CoinDesk). Esas cifras describen un aumento en el propio acto de operar y mover capital — trazando una línea completamente distinta a la del recuento de menciones en redes sociales.</p>
<p class="de">Die US-Spot-Bitcoin-ETFs, die im Juni mit 4,5 Milliarden Dollar an Nettoabflüssen ihren bislang schlechtesten Monat erlebt hatten, schwenkten in den Wochen bis zum 2. und 11. Juli zu aufeinanderfolgenden wöchentlichen Nettozuflüssen um (221,72 Millionen bzw. 197,4 Millionen Dollar). Im selben Juni erholte sich das Spot-Handelsvolumen an zentralisierten Börsen (CEX) erstmals seit fünf Monaten und stieg um 15,3 Prozent auf 1,11 Billionen Dollar, während das Volumen unbefristeter Futures auf reale Vermögenswerte (RWA) auf ein Rekordhoch von 311 Milliarden Dollar sprang (CoinDesk). Diese Zahlen beschreiben eine Zunahme des reinen Handels- und Kapitalbewegungsvolumens — eine völlig andere Linie als die Erwähnungszahlen in den sozialen Medien.</p>
<p class="fr">Les ETF bitcoin au comptant américains, après avoir traversé en juin leur pire mois jamais enregistré avec 4,5 milliards de dollars de sorties nettes, sont repassés à des entrées nettes hebdomadaires consécutives pour les semaines se terminant les 2 et 11 juillet (221,72 millions et 197,4 millions de dollars respectivement). Ce même mois de juin, les volumes d'échange au comptant sur les bourses centralisées (CEX) ont rebondi pour la première fois en cinq mois, en hausse de 15,3 % à 1 110 milliards de dollars, tandis que le volume des futures perpétuels adossés à des actifs du monde réel (RWA) a bondi à un record de 311 milliards de dollars (CoinDesk). Ces chiffres décrivent une augmentation de l'acte même de négocier et de déplacer des capitaux — traçant une trajectoire totalement différente de celle du décompte des mentions sur les réseaux sociaux.</p>
<p class="pt">Os ETFs à vista de bitcoin dos EUA, após enfrentarem seu pior mês já registrado em junho, com US$ 4,5 bilhões em saídas líquidas, viraram para entradas líquidas semanais consecutivas nas semanas encerradas em 2 e 11 de julho (US$ 221,72 milhões e US$ 197,4 milhões, respectivamente). Nesse mesmo mês de junho, os volumes de negociação à vista das exchanges centralizadas (CEX) se recuperaram pela primeira vez em cinco meses, subindo 15,3% para US$ 1,11 trilhão, enquanto o volume de futuros perpétuos ligados a ativos do mundo real (RWA) disparou para um recorde de US$ 311 bilhões (CoinDesk). Esses números descrevem um aumento no próprio ato de negociar e movimentar capital — traçando uma linha completamente diferente daquela do número de menções nas redes sociais.</p>
<p class="tr">ABD spot Bitcoin ETF'leri, Haziran'da 4,5 milyar dolarlık net çıkışla rekor kötü bir ay yaşadıktan sonra, 2 ve 11 Temmuz'da biten haftalarda art arda haftalık net girişe döndü (sırasıyla 221,72 milyon ve 197,4 milyon dolar). Aynı Haziran ayında, merkezi borsaların (CEX) spot işlem hacimleri beş ayda ilk kez toparlanarak %15,3 artışla 1,11 trilyon dolara yükseldi; gerçek dünya varlıklarına (RWA) bağlı sürekli vadeli işlem hacmi ise rekor 311 milyar dolara fırladı (CoinDesk). Bu rakamlar, işlem yapma ve sermaye hareketinin arttığını gösteriyor — sosyal medyadaki bahis sayısından tamamen farklı bir çizgi izliyor.</p>
<p class="vi">Các ETF Bitcoin giao ngay của Mỹ, sau khi trải qua tháng tồi tệ nhất từng ghi nhận vào tháng 6 với 4,5 tỷ đô la rút ròng, đã chuyển sang dòng vốn ròng vào hàng tuần liên tiếp trong các tuần kết thúc ngày 2 và 11 tháng 7 (lần lượt là 221,72 triệu và 197,4 triệu đô la). Cũng trong tháng 6 đó, khối lượng giao dịch giao ngay trên các sàn tập trung (CEX) phục hồi lần đầu tiên sau năm tháng, tăng 15,3% lên 1,11 nghìn tỷ đô la, trong khi khối lượng hợp đồng tương lai vĩnh viễn gắn với tài sản thực (RWA) tăng vọt lên mức kỷ lục 311 tỷ đô la (CoinDesk). Những con số này mô tả sự gia tăng trong chính hành vi giao dịch và di chuyển vốn — vẽ nên một đường hoàn toàn khác so với số lượt nhắc đến trên mạng xã hội.</p>

<div class="ko">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">대중은 조용해졌는데, 기관 장부는 계속 채워지고 있다</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">주간 트윗 언급량(좌) vs 기관·거래 지표(우), 7월14일 기준</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">소셜 관심도 (더블록 트윗 볼륨)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">비트코인 언급</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130,000건 (12개월 최저)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">이더리움 언급</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40,000건 (2020년 수준)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">기관·거래 지표</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">ETF 순유입(7/11 마감주)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+$197.4M</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">CEX 현물거래량(6월)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$1.11T (+15.3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">RWA 무기한선물 거래량(6월)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$311B (사상 최고)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020년: 낮은 언급량 + 낮은 기관 참여가 동시에 나타났다.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">2026년 7월: 낮은 언급량 속에서도 기관 자금·거래량은 늘고 있다 — 과거와 다른 조합.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">※ 트윗 볼륨은 소셜 관심도의 대리지표일 뿐, 자금 흐름을 직접 나타내지 않는다.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">출처: 더블록(트윗 볼륨), 코인데스크(ETF·CEX·RWA 지표)</text>
</svg>
</div>
<div class="en">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">The Crowd Went Quiet, But the Institutional Ledger Keeps Filling In</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">Weekly Tweet Mentions (left) vs. Institutional/Trading Metrics (right), as of Jul 14</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Social Attention (The Block Tweet Volume)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Bitcoin mentions</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130,000 (12-mo low)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Ethereum mentions</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40,000 (2020 level)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Institutional / Trading Metrics</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">ETF net inflow (wk end Jul 11)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+$197.4M</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">CEX spot volume (June)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$1.11T (+15.3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">RWA perp futures volume (June)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$311B (record)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020: low mentions and low institutional participation happened together.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">July 2026: mentions are low, yet institutional capital and volume keep rising — a new combination.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">* Tweet volume is only a proxy for social attention, not a direct measure of capital flow.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">Sources: The Block (tweet volume), CoinDesk (ETF, CEX, RWA metrics)</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">大衆は沈黙したが、機関の帳簿は積み上がり続けている</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">週間トゥイート言及量(左) vs 機関・取引指標(右)、7月14日時点</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">ソーシャル関心度(ザ・ブロック トゥイート量)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">ビットコイン言及</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈13万件(12カ月最低)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">イーサリアム言及</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈4万件(2020年水準)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">機関・取引指標</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">ETF純流入(7/11締め週)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+$197.4M</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">CEX現物取引量(6月)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$1.11T (+15.3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">RWA無期限先物取引量(6月)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$311B(過去最高)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020年: 低い言及量と低い機関参加が同時に起きていた。</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">2026年7月: 言及量は低いが機関資金・取引量は増加中——過去とは異なる組み合わせ。</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">※トゥイート量はソーシャル関心度の代理指標にすぎず、資金の流れを直接示すものではない。</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">出典: ザ・ブロック(トゥイート量)、コインデスク(ETF・CEX・RWA指標)</text>
</svg>
</div>
<div class="es">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">La Multitud Guardó Silencio, Pero el Libro Institucional Sigue Llenándose</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">Menciones Semanales en Tuits (izq.) vs. Métricas Institucionales/Trading (der.), al 14 jul</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Atención Social (Volumen de Tuits, The Block)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Menciones de Bitcoin</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130,000 (mín. 12 meses)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Menciones de Ethereum</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40,000 (nivel de 2020)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Métricas Institucionales / Trading</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Entrada neta ETF (sem. 11 jul)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+$197.4M</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Volumen spot CEX (junio)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$1.11T (+15.3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">Volumen futuros perp. RWA (junio)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$311B (récord)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020: bajas menciones y baja participación institucional coincidieron.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">Julio 2026: las menciones son bajas, pero el capital y volumen institucional siguen subiendo — una combinación nueva.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">* El volumen de tuits es solo un proxy de atención social, no una medida directa del flujo de capital.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">Fuentes: The Block (volumen de tuits), CoinDesk (métricas de ETF, CEX, RWA)</text>
</svg>
</div>
<div class="de">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Die Menge Verstummte, Doch das Institutionelle Kontobuch Füllt Sich Weiter</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">Wöchentliche Tweet-Erwähnungen (links) vs. Institutionelle/Handelskennzahlen (rechts), Stand 14. Jul</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Soziale Aufmerksamkeit (The Block Tweet-Volumen)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Bitcoin-Erwähnungen</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130.000 (12-Mon.-Tief)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Ethereum-Erwähnungen</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40.000 (Niveau 2020)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Institutionelle / Handelskennzahlen</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">ETF-Nettozufluss (Wo. bis 11. Jul)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+$197,4M</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">CEX-Spotvolumen (Juni)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$1,11T (+15,3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">RWA-Perp-Futures-Volumen (Juni)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">$311Mrd (Rekord)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020: niedrige Erwähnungen und niedrige institutionelle Beteiligung traten gemeinsam auf.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">Juli 2026: Erwähnungen niedrig, doch institutionelles Kapital und Volumen steigen weiter — eine neue Kombination.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">* Tweet-Volumen ist nur ein Näherungswert für soziale Aufmerksamkeit, kein direktes Maß für Kapitalfluss.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">Quellen: The Block (Tweet-Volumen), CoinDesk (ETF-, CEX-, RWA-Kennzahlen)</text>
</svg>
</div>
<div class="fr">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">La Foule S'est Tue, Mais le Registre Institutionnel Continue de Se Remplir</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">Mentions Hebdomadaires sur Twitter (g.) vs. Indicateurs Institutionnels/Trading (dr.), au 14 juil</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Attention Sociale (Volume de Tweets, The Block)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Mentions Bitcoin</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130 000 (plus bas en 12 mois)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Mentions Ethereum</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40 000 (niveau de 2020)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Indicateurs Institutionnels / Trading</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Entrée nette ETF (sem. 11 juil)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+197,4 M$</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Volume spot CEX (juin)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">1,11 T$ (+15,3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">Volume futures perp. RWA (juin)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">311 Md$ (record)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020 : faibles mentions et faible participation institutionnelle allaient de pair.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">Juillet 2026 : mentions faibles, mais capital et volume institutionnels continuent de grimper — une combinaison nouvelle.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">* Le volume de tweets n'est qu'un indicateur approximatif de l'attention sociale, pas une mesure directe du flux de capitaux.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">Sources : The Block (volume de tweets), CoinDesk (indicateurs ETF, CEX, RWA)</text>
</svg>
</div>
<div class="pt">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">A Multidão Ficou Quieta, Mas o Livro-Razão Institucional Continua Enchendo</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">Menções Semanais no Twitter (esq.) vs. Métricas Institucionais/Trading (dir.), em 14 jul</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Atenção Social (Volume de Tweets, The Block)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Menções ao Bitcoin</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130.000 (mín. 12 meses)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Menções ao Ethereum</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40.000 (nível de 2020)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Métricas Institucionais / Trading</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Entrada líquida ETF (sem. 11 jul)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+US$ 197,4M</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Volume à vista CEX (junho)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">US$ 1,11T (+15,3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">Volume futuros perp. RWA (junho)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">US$ 311B (recorde)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020: baixas menções e baixa participação institucional ocorreram juntas.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">Julho 2026: menções baixas, mas capital e volume institucional seguem subindo — uma combinação nova.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">* O volume de tweets é apenas um proxy de atenção social, não uma medida direta do fluxo de capital.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">Fontes: The Block (volume de tweets), CoinDesk (métricas de ETF, CEX, RWA)</text>
</svg>
</div>
<div class="tr">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Kitle Sessizleşti, Ama Kurumsal Defter Dolmaya Devam Ediyor</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">Haftalık Tweet Bahisleri (sol) vs. Kurumsal/İşlem Göstergeleri (sağ), 14 Tem itibarıyla</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Sosyal İlgi (The Block Tweet Hacmi)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Bitcoin bahisleri</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130.000 (12 aylık dip)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Ethereum bahisleri</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40.000 (2020 seviyesi)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Kurumsal / İşlem Göstergeleri</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">ETF net girişi (11 Tem haftası)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+197,4M$</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">CEX spot hacmi (Haziran)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">1,11T$ (+%15,3)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">RWA sürekli vadeli hacmi (Haziran)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">311Mr$ (rekor)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020: düşük bahis ve düşük kurumsal katılım birlikte görüldü.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">Temmuz 2026: bahisler düşük, ama kurumsal sermaye ve hacim artmaya devam ediyor — yeni bir kombinasyon.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">* Tweet hacmi yalnızca sosyal ilginin bir vekil göstergesidir, sermaye akışının doğrudan ölçüsü değildir.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">Kaynaklar: The Block (tweet hacmi), CoinDesk (ETF, CEX, RWA göstergeleri)</text>
</svg>
</div>
<div class="vi">
<svg viewBox="0 0 700 460" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="28" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Đám Đông Im Lặng, Nhưng Sổ Sách Tổ Chức Vẫn Tiếp Tục Đầy Lên</text>
  <text x="20" y="48" fill="#a1a1aa" font-family="sans-serif" font-size="13">Lượt Nhắc Đến Trên Tweet Hàng Tuần (trái) vs. Chỉ Số Tổ Chức/Giao Dịch (phải), tính đến 14/7</text>
  <text x="20" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Sự Chú Ý Xã Hội (Khối Lượng Tweet, The Block)</text>
  <rect x="20" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">Lượt nhắc Bitcoin</text>
  <text x="36" y="136" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈130.000 (thấp nhất 12 tháng)</text>
  <rect x="20" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Lượt nhắc Ethereum</text>
  <text x="36" y="191" fill="#f87171" font-family="sans-serif" font-size="19" font-weight="800">≈40.000 (mức năm 2020)</text>
  <text x="390" y="80" fill="#e4e4e7" font-family="sans-serif" font-size="14" font-weight="700">Chỉ Số Tổ Chức / Giao Dịch</text>
  <rect x="390" y="95" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="118" fill="#a1a1aa" font-family="sans-serif" font-size="13">ETF dòng vào ròng (tuần 11/7)</text>
  <text x="406" y="136" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">+197,4 Tr$</text>
  <rect x="390" y="150" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="173" fill="#a1a1aa" font-family="sans-serif" font-size="13">Khối lượng giao ngay CEX (tháng 6)</text>
  <text x="406" y="191" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">1,11 Ngàn Tỷ$ (+15,3%)</text>
  <rect x="390" y="205" width="290" height="46" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="406" y="228" fill="#a1a1aa" font-family="sans-serif" font-size="13">Khối lượng hợp đồng vĩnh viễn RWA (tháng 6)</text>
  <text x="406" y="246" fill="#34d399" font-family="sans-serif" font-size="19" font-weight="800">311 Tỷ$ (kỷ lục)</text>
  <line x1="350" y1="70" x2="350" y2="270" stroke="#3f3f46" stroke-width="1" stroke-dasharray="4 4"/>
  <text x="350" y="300" text-anchor="middle" fill="#71717a" font-family="sans-serif" font-size="22" font-weight="700">↔</text>
  <text x="20" y="335" fill="#71717a" font-family="sans-serif" font-size="13">2020: lượt nhắc thấp và sự tham gia tổ chức thấp xảy ra cùng lúc.</text>
  <text x="20" y="358" fill="#71717a" font-family="sans-serif" font-size="13">Tháng 7/2026: lượt nhắc thấp, nhưng vốn và khối lượng tổ chức vẫn tăng — một sự kết hợp mới.</text>
  <text x="20" y="410" fill="#71717a" font-family="sans-serif" font-size="13">* Khối lượng tweet chỉ là chỉ số đại diện cho sự chú ý xã hội, không đo trực tiếp dòng vốn.</text>
  <text x="20" y="433" fill="#71717a" font-family="sans-serif" font-size="13">Nguồn: The Block (khối lượng tweet), CoinDesk (chỉ số ETF, CEX, RWA)</text>
</svg>
</div>

<h2 class="ko">과거 패턴이 반복될까, 아니면 이번엔 다를까</h2>
<h2 class="en">Does the Old Pattern Repeat, or Is This Time Different?</h2>
<h2 class="ja">過去のパターンは繰り返すのか、それとも今回は違うのか</h2>
<h2 class="es">¿Se Repite el Viejo Patrón, o Esta Vez Es Diferente?</h2>
<h2 class="de">Wiederholt Sich das Alte Muster, Oder Ist Es Diesmal Anders?</h2>
<h2 class="fr">L'Ancien Schéma Se Répète-t-il, ou Est-ce Différent Cette Fois?</h2>
<h2 class="pt">O Antigo Padrão Se Repete, ou Desta Vez É Diferente?</h2>
<h2 class="tr">Eski Örüntü Tekrar mı Ediyor, Yoksa Bu Sefer Farklı mı?</h2>
<h2 class="vi">Mô Hình Cũ Có Lặp Lại, Hay Lần Này Sẽ Khác?</h2>

<p class="ko">2020년의 트윗 볼륨 저점은 결국 2020~2021년 슈퍼사이클의 전조로 판명됐다. 대중의 무관심은 투기적 과열이 빠진 상태를 뜻했고, 사후적으로는 저점 매집의 신호로 읽혔다. 이 사이트가 7월8일 짚었던 <a href="/blog/quiet-rebound-sentiment-attention-gap.php">공포탐욕지수·구글트렌드 관심도 격차 점검</a>은 구글트렌드 검색 관심도가 몇 주째 26~30 수준에 정체돼 있고 공포탐욕지수는 오히려 하락했다는, 이번과 유사한 관심도 격차를 지적한 바 있다. <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">크립토퀀트의 불 스코어 지수 점검</a> 역시 여전히 20에 머물러 있어 '베어마켓 회복' 단계로 분류된다고 짚었다 — 대중의 침묵이 하루이틀이 아니라 몇 주째 이어지고 있다는 뜻이다.</p>
<p class="en">The 2020 tweet-volume trough eventually proved to be a precursor to the 2020-2021 supercycle. Public apathy back then reflected the absence of speculative froth, and in hindsight was read as a sign of quiet accumulation. This site's July 8 check on <a href="/blog/quiet-rebound-sentiment-attention-gap.php">the Fear & Greed/Google Trends attention gap</a> found a similar pattern: Google Trends search interest for "bitcoin" stuck at 26-30 for weeks while the Fear & Greed Index actually fell further. A separate check on <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">CryptoQuant's Bull Score index</a> found it still stuck at 20, still classified as "bear-market recovery" — meaning the public's silence has now stretched on for weeks, not days.</p>
<p class="ja">2020年のトゥイート量の底値は、結局2020~2021年のスーパーサイクルの前兆であったことが判明した。当時の大衆の無関心は投機的な過熱がない状態を意味し、事後的には静かな買い集めのサインと読み解かれた。当サイトが7月8日に取り上げた<a href="/blog/quiet-rebound-sentiment-attention-gap.php">恐怖強欲指数・グーグルトレンド関心度格差の点検</a>では、グーグルトレンドの検索関心度が数週間26~30水準で停滞し、恐怖強欲指数はむしろ下落したという、今回と似た関心度の乖離を指摘していた。<a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">クリプトクアントのブルスコア指数の点検</a>も依然20にとどまり「ベアマーケット回復」段階に分類されると指摘した——大衆の沈黙が一日二日ではなく、数週間続いているということだ。</p>
<p class="es">El mínimo del volumen de tuits de 2020 resultó ser, con el tiempo, un precursor del supraciclo de 2020-2021. La apatía pública de entonces reflejaba la ausencia de espuma especulativa, y en retrospectiva se leyó como una señal de acumulación silenciosa. El análisis de este sitio del 8 de julio sobre <a href="/blog/quiet-rebound-sentiment-attention-gap.php">la brecha de atención entre el Índice de Miedo y Codicia y Google Trends</a> encontró un patrón similar: el interés de búsqueda en Google Trends para "bitcoin" estancado en 26-30 durante semanas mientras el Índice de Miedo y Codicia caía aún más. Otro análisis sobre <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">el índice Bull Score de CryptoQuant</a> encontró que permanece atascado en 20, aún clasificado como "recuperación de mercado bajista" — lo que significa que el silencio del público ya se ha extendido durante semanas, no días.</p>
<p class="de">Das Tweet-Volumen-Tief von 2020 erwies sich letztlich als Vorbote des Superzyklus 2020-2021. Die öffentliche Gleichgültigkeit spiegelte damals das Fehlen spekulativer Übertreibung wider und wurde im Rückblick als Zeichen stiller Akkumulation gedeutet. Die Analyse dieser Seite vom 8. Juli zur <a href="/blog/quiet-rebound-sentiment-attention-gap.php">Aufmerksamkeitslücke zwischen Fear & Greed Index und Google Trends</a> fand ein ähnliches Muster: Das Google-Trends-Suchinteresse für "bitcoin" verharrte wochenlang bei 26-30, während der Fear & Greed Index sogar weiter fiel. Eine weitere Analyse zu <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">CryptoQuants Bull-Score-Index</a> merkte an, dass er weiterhin bei 20 feststeckt und noch immer als "Bärenmarkt-Erholung" eingestuft wird — was bedeutet, dass das Schweigen der Öffentlichkeit inzwischen Wochen andauert, nicht nur Tage.</p>
<p class="fr">Le creux du volume de tweets de 2020 s'est finalement révélé être un précurseur du supercycle 2020-2021. L'apathie publique de l'époque reflétait l'absence d'écume spéculative et a été, rétrospectivement, interprétée comme un signe d'accumulation silencieuse. L'analyse de ce site du 8 juillet sur <a href="/blog/quiet-rebound-sentiment-attention-gap.php">l'écart d'attention entre l'indice Fear & Greed et Google Trends</a> a relevé un schéma similaire : l'intérêt de recherche Google Trends pour « bitcoin » bloqué entre 26 et 30 pendant des semaines, alors que l'indice Fear & Greed a même encore baissé. Une autre analyse sur <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">l'indice Bull Score de CryptoQuant</a> a souligné qu'il reste bloqué à 20, toujours classé comme « reprise de marché baissier » — ce qui signifie que le silence du public dure désormais depuis des semaines, pas des jours.</p>
<p class="pt">O fundo do volume de tweets de 2020 acabou se revelando um precursor do superciclo de 2020-2021. A apatia pública da época refletia a ausência de espuma especulativa e, em retrospectiva, foi lida como um sinal de acumulação silenciosa. A análise deste site de 8 de julho sobre <a href="/blog/quiet-rebound-sentiment-attention-gap.php">a lacuna de atenção entre o Índice de Medo e Ganância e o Google Trends</a> encontrou um padrão semelhante: o interesse de busca no Google Trends por "bitcoin" travado em 26-30 por semanas, enquanto o Índice de Medo e Ganância na verdade caiu ainda mais. Outra análise sobre <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">o índice Bull Score da CryptoQuant</a> apontou que ele permanece travado em 20, ainda classificado como "recuperação de mercado em baixa" — o que significa que o silêncio do público já se estende por semanas, não dias.</p>
<p class="tr">2020'deki tweet hacmi dibi, sonunda 2020-2021 süper döngüsünün habercisi olduğu ortaya çıktı. O dönemki kamu ilgisizliği spekülatif köpüğün yokluğunu yansıtıyordu ve geriye dönük olarak sessiz birikimin bir işareti olarak okundu. Bu sitenin 8 Temmuz'da ele aldığı <a href="/blog/quiet-rebound-sentiment-attention-gap.php">Korku-Açgözlülük Endeksi/Google Trends ilgi farkı incelemesi</a> benzer bir örüntü buldu: "bitcoin" için Google Trends arama ilgisi haftalarca 26-30 aralığında takılı kalırken, Korku ve Açgözlülük Endeksi aslında daha da düştü. <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">CryptoQuant'ın Bull Score endeksi incelemesi</a> de hâlâ 20'de takılı kaldığını ve hâlâ "ayı piyasası toparlanması" olarak sınıflandırıldığını belirtti — bu da halkın sessizliğinin artık günler değil haftalardır sürdüğü anlamına geliyor.</p>
<p class="vi">Đáy khối lượng tweet năm 2020 cuối cùng đã chứng minh là điềm báo trước cho siêu chu kỳ 2020-2021. Sự thờ ơ của công chúng khi đó phản ánh sự vắng bóng của bọt đầu cơ, và nhìn lại được hiểu là dấu hiệu của việc âm thầm tích lũy. Bài kiểm tra ngày 8 tháng 7 của trang này về <a href="/blog/quiet-rebound-sentiment-attention-gap.php">khoảng cách chú ý giữa Chỉ số Sợ Hãi & Tham Lam và Google Trends</a> từng phát hiện một mô hình tương tự: mức độ quan tâm tìm kiếm trên Google Trends cho "bitcoin" mắc kẹt ở mức 26-30 trong nhiều tuần trong khi Chỉ số Sợ Hãi & Tham Lam thực tế còn giảm sâu hơn. Một bài kiểm tra khác về <a href="/blog/cryptoquant-bull-score-bear-market-recovery.php">chỉ số Bull Score của CryptoQuant</a> chỉ ra rằng chỉ số này vẫn mắc kẹt ở mức 20, vẫn được xếp loại là "phục hồi thị trường gấu" — nghĩa là sự im lặng của công chúng giờ đây đã kéo dài hàng tuần, chứ không phải chỉ vài ngày.</p>

<p class="ko">하지만 '조용할수록 오히려 매수 기회'라는 낙관적 해석에는 전제가 있다. 대중이 언젠가 다시 돌아와 다음 상승 국면에 다시 불을 붙인다는 전제, 즉 과거 모든 사이클이 그랬듯 결국 소셜 관심도와 가격이 다시 함께 움직인다는 가정이다. 그런데 2026년의 시장 구조는 다르다. ETF, 기업 재무제표상의 비트코인 보유, 토큰화라는 통로를 통해 유입되는 수요 비중이 점점 커지면서, 가격을 움직이는 데 더 이상 대중의 소셜 버즈가 필요하지 않은 구조가 만들어지고 있을 수 있다. 이는 트윗 볼륨과 가격의 상관관계 자체가 지연되고 있다기보다, 구조적으로 약화되고 있다는 뜻일 수도 있다는 반박이다. 어느 해석이 맞는지는 트윗 수 하나만으로는 판가름 나지 않는다.</p>
<p class="en">But the bullish reading — that quiet means opportunity — rests on an assumption: that the public eventually returns and reignites the next leg up, the way social attention and price have realigned in every past cycle. The market structure of 2026 may be different, though. As a growing share of demand flows in through ETFs, corporate balance-sheet bitcoin holdings, and tokenization rails, it's plausible that moving the price no longer requires public social buzz the way it once did. That's a counter-argument worth taking seriously: the relationship between tweet volume and price may not just be lagging this time — it could be structurally weakening. Which reading is correct won't be settled by the tweet count alone.</p>
<p class="ja">しかし「静かなほど買い場である」という強気の解釈には前提がある。大衆がいつか再び戻ってきて、次の上昇局面に再び火をつけるという前提、つまり過去のすべてのサイクルがそうであったように、結局はソーシャル関心度と価格が再び連動するという仮定だ。だが2026年の市場構造は異なる可能性がある。ETF、企業のバランスシート上のビットコイン保有、トークン化という経路を通じて流入する需要の比重が大きくなるにつれ、価格を動かすのにもはや大衆のソーシャルバズが必要でない構造が生まれつつあるかもしれない。これは、トゥイート量と価格の相関関係そのものが遅延しているというより、構造的に弱まっている可能性があるという反論だ。どちらの解釈が正しいかは、トゥイート数だけでは判断できない。</p>
<p class="es">Pero la lectura alcista — que la calma significa oportunidad — se apoya en un supuesto: que el público eventualmente regresa y reenciende el próximo tramo alcista, tal como la atención social y el precio se han realineado en todos los ciclos pasados. Sin embargo, la estructura de mercado de 2026 podría ser diferente. A medida que una porción creciente de la demanda entra a través de ETF, tenencias de bitcoin en balances corporativos y vías de tokenización, es plausible que mover el precio ya no requiera el zumbido social del público como antes. Ese es un contraargumento que vale la pena tomar en serio: la relación entre el volumen de tuits y el precio podría no estar solo retrasada esta vez — podría estar debilitándose estructuralmente. Cuál lectura es correcta no se resolverá solo con el conteo de tuits.</p>
<p class="de">Doch die optimistische Lesart — Stille bedeutet Gelegenheit — beruht auf einer Annahme: dass die Öffentlichkeit irgendwann zurückkehrt und die nächste Aufwärtsbewegung erneut entfacht, so wie sich soziale Aufmerksamkeit und Kurs in jedem vergangenen Zyklus wieder angeglichen haben. Die Marktstruktur von 2026 könnte jedoch anders sein. Da ein wachsender Anteil der Nachfrage über ETFs, Bitcoin-Bestände in Unternehmensbilanzen und Tokenisierungsschienen einfließt, ist es plausibel, dass die Kursbewegung nicht mehr das öffentliche Social-Media-Rauschen von einst benötigt. Das ist ein Gegenargument, das man ernst nehmen sollte: Die Beziehung zwischen Tweet-Volumen und Kurs hinkt diesmal vielleicht nicht nur hinterher — sie könnte sich strukturell abschwächen. Welche Lesart zutrifft, lässt sich allein an der Tweet-Zahl nicht entscheiden.</p>
<p class="fr">Mais la lecture haussière — le calme signifie une opportunité — repose sur une hypothèse : que le public finit par revenir et rallumer la prochaine jambe haussière, comme l'attention sociale et le prix se sont réalignés à chaque cycle passé. La structure du marché de 2026 pourrait toutefois être différente. Alors qu'une part croissante de la demande entre via les ETF, les avoirs en bitcoin des bilans d'entreprises et les rails de tokenisation, il est plausible que faire bouger le prix ne nécessite plus le bourdonnement social du public comme autrefois. C'est un contre-argument à prendre au sérieux : la relation entre le volume de tweets et le prix n'est peut-être pas simplement retardée cette fois — elle pourrait s'affaiblir structurellement. Laquelle des deux lectures est correcte ne sera pas tranchée par le seul décompte de tweets.</p>
<p class="pt">Mas a leitura otimista — de que a calmaria significa oportunidade — se apoia em uma premissa: a de que o público eventualmente retorna e reacende a próxima perna de alta, assim como a atenção social e o preço se realinharam em todos os ciclos passados. A estrutura de mercado de 2026, porém, pode ser diferente. À medida que uma fatia crescente da demanda entra via ETFs, participações de bitcoin em balanços corporativos e trilhos de tokenização, é plausível que mover o preço já não exija o burburinho social do público como antes. Esse é um contra-argumento que vale a pena levar a sério: a relação entre volume de tweets e preço pode não estar apenas atrasada desta vez — ela pode estar enfraquecendo estruturalmente. Qual leitura está correta não será resolvido apenas pela contagem de tweets.</p>
<p class="tr">Ancak "sessizlik fırsat demektir" şeklindeki iyimser okuma bir varsayıma dayanıyor: halkın er ya da geç geri döneceği ve bir sonraki yükseliş bacağını yeniden ateşleyeceği, yani geçmişteki her döngüde olduğu gibi sosyal ilgi ile fiyatın yeniden hizalanacağı varsayımı. Ancak 2026'nın piyasa yapısı farklı olabilir. Talebin giderek artan bir kısmı ETF'ler, kurumsal bilançolardaki bitcoin varlıkları ve tokenizasyon rayları üzerinden geldikçe, fiyatı hareket ettirmenin artık eskisi gibi halkın sosyal medya gürültüsüne ihtiyaç duymaması akla yatkın. Bu, ciddiye alınmaya değer bir karşı argüman: tweet hacmi ile fiyat arasındaki ilişki bu sefer sadece gecikmiyor olabilir — yapısal olarak zayıflıyor da olabilir. Hangi okumanın doğru olduğu yalnızca tweet sayısıyla belirlenemez.</p>
<p class="vi">Nhưng cách hiểu lạc quan — rằng sự im lặng đồng nghĩa với cơ hội — dựa trên một giả định: rằng công chúng cuối cùng sẽ quay lại và thắp lại đợt tăng tiếp theo, giống như sự chú ý xã hội và giá đã tái đồng bộ trong mọi chu kỳ trước đây. Tuy nhiên, cấu trúc thị trường năm 2026 có thể khác. Khi một phần ngày càng lớn của nhu cầu đổ vào qua ETF, lượng nắm giữ bitcoin trên bảng cân đối kế toán doanh nghiệp và các kênh token hóa, rất có thể việc đẩy giá không còn cần đến sự ồn ào trên mạng xã hội của công chúng như trước nữa. Đây là một lập luận phản biện đáng được xem xét nghiêm túc: mối quan hệ giữa khối lượng tweet và giá lần này có thể không chỉ đơn thuần bị trễ — mà có thể đang suy yếu về mặt cấu trúc. Cách hiểu nào đúng sẽ không được quyết định chỉ bằng số lượng tweet.</p>

<h2 class="ko">지금부터 지켜볼 지점</h2>
<h2 class="en">What to Watch From Here</h2>
<h2 class="ja">これから注視すべき点</h2>
<h2 class="es">Qué Observar a Partir de Ahora</h2>
<h2 class="de">Worauf Von Hier An zu Achten Ist</h2>
<h2 class="fr">Ce Qu'il Faut Surveiller à Partir de Maintenant</h2>
<h2 class="pt">O Que Observar a Partir de Agora</h2>
<h2 class="tr">Buradan İtibaren Nelere Dikkat Edilmeli</h2>
<h2 class="vi">Những Điều Cần Theo Dõi Từ Đây</h2>

<p class="ko">첫째, ETF 순유입 행진이 3주째로 이어지는지다. <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">이 사이트가 같은 날 다룬 별도 점검</a>에서 이미 짚었듯, 2주 연속 유입만으로는 추세 전환을 단정하기 이르다. 만약 3주째 유입이 이어지는 가운데 트윗 볼륨도 함께 반등한다면, 이는 대중과 기관이 동시에 돌아오는 전형적인 회복 패턴으로 볼 수 있다. 반대로 자금 유입 규모가 더 커지는데도 트윗 볼륨이 계속 가라앉는다면, 이는 '가격을 움직이는 데 대중의 목소리가 더는 필요 없다'는 구조적 탈동조화 해석에 힘을 싣게 된다.</p>
<p class="en">First, whether the ETF inflow streak extends to a third straight week. As <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">a separate check on this site</a> flagged the same day, two weeks of inflows alone are too early to call a trend reversal. If inflows continue into a third week alongside any rebound in tweet volume, that would look like the classic recovery pattern where retail and institutions return together. Conversely, if inflow size keeps growing while tweet volume keeps sinking, that would lend weight to the structural-decoupling reading — that moving the price no longer requires the public's voice.</p>
<p class="ja">第一に、ETF純流入の行進が3週目に入るかどうかだ。<a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">当サイトが同日扱った別の点検</a>で既に指摘した通り、2週連続の流入だけではトレンド転換と断定するには早い。もし3週目も流入が続き、同時にトゥイート量も反発するなら、これは大衆と機関が同時に戻ってくる典型的な回復パターンと見ることができる。逆に、資金流入の規模がさらに拡大しているのにトゥイート量が沈み続けるなら、これは「価格を動かすのにもはや大衆の声が必要ない」という構造的な非連動化の解釈を後押しすることになる。</p>
<p class="es">Primero, si la racha de entradas de ETF se extiende a una tercera semana consecutiva. Como señaló <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">otro análisis de este sitio</a> el mismo día, dos semanas de entradas por sí solas son demasiado pronto para declarar una reversión de tendencia. Si las entradas continúan en una tercera semana junto con algún repunte en el volumen de tuits, eso se parecería al patrón de recuperación clásico donde el retail y las instituciones regresan juntos. Por el contrario, si el tamaño de las entradas sigue creciendo mientras el volumen de tuits sigue hundiéndose, eso reforzaría la lectura del desacoplamiento estructural — que mover el precio ya no requiere la voz del público.</p>
<p class="de">Erstens, ob sich die ETF-Zuflussserie auf eine dritte Woche in Folge ausdehnt. Wie <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">eine andere Analyse dieser Seite</a> am selben Tag anmerkte, reichen zwei Wochen an Zuflüssen allein noch nicht aus, um von einer Trendwende zu sprechen. Setzen sich die Zuflüsse in eine dritte Woche fort und erholt sich gleichzeitig das Tweet-Volumen, würde das wie das klassische Erholungsmuster aussehen, bei dem Privatanleger und Institutionen gemeinsam zurückkehren. Steigt hingegen das Zuflussvolumen weiter, während das Tweet-Volumen weiter sinkt, würde das der Lesart der strukturellen Entkopplung Gewicht verleihen — dass die Kursbewegung nicht mehr die Stimme der Öffentlichkeit braucht.</p>
<p class="fr">Premièrement, si la série d'entrées nettes des ETF se prolonge une troisième semaine consécutive. Comme l'a signalé <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">une autre analyse de ce site</a> le même jour, deux semaines d'entrées seules sont trop tôt pour déclarer un renversement de tendance. Si les entrées se poursuivent une troisième semaine, accompagnées d'un rebond du volume de tweets, cela ressemblerait au schéma de reprise classique où particuliers et institutions reviennent ensemble. À l'inverse, si le volume des entrées continue de croître alors que le volume de tweets continue de s'effondrer, cela renforcerait la lecture d'un découplage structurel — selon laquelle faire bouger le prix ne nécessite plus la voix du public.</p>
<p class="pt">Primeiro, se a sequência de entradas de ETF se estende por uma terceira semana consecutiva. Como <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">outra análise deste site</a> apontou no mesmo dia, duas semanas de entradas sozinhas são cedo demais para declarar uma reversão de tendência. Se as entradas continuarem em uma terceira semana junto com alguma recuperação no volume de tweets, isso se pareceria com o padrão de recuperação clássico em que varejo e instituições retornam juntos. Por outro lado, se o tamanho das entradas continuar crescendo enquanto o volume de tweets continua afundando, isso reforçaria a leitura de desacoplamento estrutural — de que mover o preço já não requer a voz do público.</p>
<p class="tr">Birincisi, ETF girişi serisinin üçüncü haftaya uzayıp uzamayacağı. <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">Bu sitenin aynı gün ele aldığı ayrı bir inceleme</a>nin belirttiği gibi, yalnızca iki haftalık giriş bir trend tersine dönüşü ilan etmek için henüz erken. Eğer girişler üçüncü haftaya da devam eder ve tweet hacminde de bir toparlanma görülürse, bu, perakende ve kurumların birlikte geri döndüğü klasik toparlanma örüntüsüne benzer. Tersine, giriş büyüklüğü artmaya devam ederken tweet hacmi batmaya devam ederse, bu, fiyatı hareket ettirmenin artık halkın sesine ihtiyaç duymadığı şeklindeki yapısal ayrışma okumasına ağırlık katar.</p>
<p class="vi">Thứ nhất, liệu chuỗi dòng vốn ETF vào có kéo dài sang tuần thứ ba liên tiếp hay không. Như <a href="/blog/feargreed-whipsaw-options-skew-unwind-gap.php">một bài kiểm tra khác của trang này</a> đã chỉ ra cùng ngày, chỉ hai tuần có dòng vốn vào là quá sớm để tuyên bố một sự đảo chiều xu hướng. Nếu dòng vốn tiếp tục sang tuần thứ ba cùng với bất kỳ sự phục hồi nào trong khối lượng tweet, điều đó sẽ giống với mô hình phục hồi cổ điển khi nhà đầu tư nhỏ lẻ và tổ chức cùng quay trở lại. Ngược lại, nếu quy mô dòng vốn tiếp tục tăng trong khi khối lượng tweet tiếp tục chìm xuống, điều đó sẽ củng cố thêm cho cách hiểu về sự tách rời cấu trúc — rằng việc đẩy giá không còn cần đến tiếng nói của công chúng nữa.</p>

<p class="ko">둘째, 트윗 볼륨이 실제로 가격 움직임에 선행하는지 아니면 계속 후행하는지를 몇 주 더 지켜볼 필요가 있다. 이 지표는 원래 자금 흐름을 직접 반영하지 않는 대리지표이므로, 단독으로 매매 신호를 만들기보다는 구글트렌드 검색 관심도, 공포탐욕지수, ETF 자금 흐름 같은 다른 지표와 함께 놓고 봐야 그림이 분명해진다. 그 조합에서 대중의 관심도만 계속 뒤처지는 패턴이 이어진다면, 이번 사이클에서 '조용함'이 갖는 의미 자체가 과거 사이클과는 다르게 재정의될 가능성이 있다.</p>
<p class="en">Second, whether tweet volume actually leads price action or keeps trailing it deserves a few more weeks of observation. Since the metric is a proxy rather than a direct read of capital flow, it makes more sense placed alongside other gauges — Google Trends search interest, the Fear & Greed Index, ETF flows — than treated as a standalone trading signal. If that combination keeps showing public attention lagging while the other gauges move, the meaning of "quiet" in this cycle may end up being redefined from what it meant in past ones.</p>
<p class="ja">第二に、トゥイート量が実際に価格の動きに先行するのか、それとも引き続き遅行し続けるのかを、あと数週間見極める必要がある。この指標はもともと資金の流れを直接反映しない代理指標であるため、単独で売買シグナルにするより、グーグルトレンドの検索関心度、恐怖強欲指数、ETF資金の流れといった他の指標と併せて見た方が、より明確な絵が見えてくる。その組み合わせで大衆の関心度だけが遅行し続けるパターンが続くなら、今回のサイクルにおける「静けさ」の意味そのものが、過去のサイクルとは異なる形で再定義される可能性がある。</p>
<p class="es">Segundo, si el volumen de tuits realmente antecede a la acción del precio o sigue rezagándose merece unas semanas más de observación. Dado que el indicador es un proxy más que una lectura directa del flujo de capital, tiene más sentido colocarlo junto a otros indicadores — el interés de búsqueda en Google Trends, el Índice de Miedo y Codicia, los flujos de ETF — que tratarlo como una señal de trading aislada. Si esa combinación sigue mostrando que la atención pública se rezaga mientras los demás indicadores se mueven, el significado de "silencio" en este ciclo podría terminar redefiniéndose respecto a lo que significó en ciclos pasados.</p>
<p class="de">Zweitens verdient es noch einige Wochen Beobachtung, ob das Tweet-Volumen der Kursentwicklung tatsächlich vorausläuft oder ihr weiterhin hinterherhinkt. Da die Kennzahl eher ein Näherungswert als eine direkte Ablesung des Kapitalflusses ist, ergibt es mehr Sinn, sie zusammen mit anderen Messgrößen zu betrachten — Google-Trends-Suchinteresse, Fear & Greed Index, ETF-Flüsse — als sie als eigenständiges Handelssignal zu behandeln. Zeigt diese Kombination weiterhin, dass die öffentliche Aufmerksamkeit hinterherhinkt, während sich die anderen Messgrößen bewegen, könnte die Bedeutung von "Stille" in diesem Zyklus letztlich anders definiert werden als in vergangenen Zyklen.</p>
<p class="fr">Deuxièmement, savoir si le volume de tweets précède réellement l'évolution des prix ou continue de la suivre mérite encore quelques semaines d'observation. Puisque l'indicateur est un indicateur approximatif plutôt qu'une lecture directe du flux de capitaux, il est plus judicieux de le placer aux côtés d'autres jauges — intérêt de recherche Google Trends, indice Fear & Greed, flux des ETF — que de le traiter comme un signal de trading autonome. Si cette combinaison continue de montrer que l'attention du public accuse un retard pendant que les autres jauges bougent, la signification du « calme » dans ce cycle pourrait finir par être redéfinie par rapport à ce qu'elle signifiait dans les cycles passés.</p>
<p class="pt">Segundo, se o volume de tweets realmente antecede a ação do preço ou continua atrasado merece mais algumas semanas de observação. Como o indicador é um proxy, e não uma leitura direta do fluxo de capital, faz mais sentido colocá-lo ao lado de outros indicadores — interesse de busca no Google Trends, Índice de Medo e Ganância, fluxos de ETF — do que tratá-lo como um sinal de negociação isolado. Se essa combinação continuar mostrando a atenção pública atrasada enquanto os outros indicadores se movem, o significado de "silêncio" neste ciclo pode acabar sendo redefinido em relação ao que significou em ciclos passados.</p>
<p class="tr">İkincisi, tweet hacminin fiyat hareketine gerçekten öncülük mü ettiği yoksa onu takip etmeye mi devam ettiği birkaç hafta daha gözlemlenmeyi hak ediyor. Bu gösterge sermaye akışının doğrudan bir okuması değil, bir vekil gösterge olduğundan, tek başına bir işlem sinyali olarak ele almaktan çok, Google Trends arama ilgisi, Korku ve Açgözlülük Endeksi, ETF akışları gibi diğer göstergelerle birlikte değerlendirmek daha mantıklı. Bu kombinasyon, diğer göstergeler hareket ederken kamu ilgisinin gecikmeye devam ettiğini göstermeye devam ederse, bu döngüdeki "sessizliğin" anlamı geçmiş döngülerden farklı biçimde yeniden tanımlanabilir.</p>
<p class="vi">Thứ hai, việc khối lượng tweet có thực sự dẫn dắt biến động giá hay tiếp tục đi sau vẫn cần thêm vài tuần quan sát. Vì chỉ số này là một chỉ số đại diện chứ không phải là thước đo trực tiếp của dòng vốn, nên việc đặt nó cạnh các chỉ số khác — mức độ quan tâm tìm kiếm trên Google Trends, Chỉ số Sợ Hãi & Tham Lam, dòng vốn ETF — sẽ hợp lý hơn là coi nó như một tín hiệu giao dịch độc lập. Nếu sự kết hợp đó tiếp tục cho thấy sự chú ý của công chúng đi sau trong khi các chỉ số khác đang chuyển động, ý nghĩa của "sự im lặng" trong chu kỳ này có thể cuối cùng sẽ được định nghĩa lại khác với những gì nó từng mang trong các chu kỳ trước.</p>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 더블록(트윗 볼륨 지표), 코인데스크(ETF 자금 흐름·CEX 거래량·RWA 무기한선물 거래량), rwatimes·RWA.xyz(토큰화 실물자산 규모). 수치는 각 데이터 제공처 기준 근사치이며 소스·집계 시점에 따라 편차가 있을 수 있다.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: The Block (tweet volume metric), CoinDesk (ETF flows, CEX volume, RWA perpetual futures volume), rwatimes.substack, RWA.xyz (tokenized real-world asset value). Figures are approximate per each data provider and may vary by source and timing.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: ザ・ブロック(トゥイート量指標)、コインデスク(ETF資金の流れ・CEX取引量・RWA無期限先物取引量)、rwatimes・RWA.xyz(トークン化された実物資産規模)。数値は各データ提供元に基づく近似値であり、情報源や集計時点により差異がある場合がある。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: The Block (indicador de volumen de tuits), CoinDesk (flujos de ETF, volumen CEX, volumen de futuros perpetuos RWA), rwatimes.substack, RWA.xyz (valor de activos del mundo real tokenizados). Las cifras son aproximadas según cada proveedor de datos y pueden variar según la fuente y el momento.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: The Block (Tweet-Volumen-Kennzahl), CoinDesk (ETF-Flüsse, CEX-Volumen, RWA-Perp-Futures-Volumen), rwatimes.substack, RWA.xyz (Wert tokenisierter realer Vermögenswerte). Zahlen sind Näherungswerte je nach Datenanbieter und können je nach Quelle und Zeitpunkt variieren.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : The Block (indicateur de volume de tweets), CoinDesk (flux ETF, volume CEX, volume de futures perpétuels RWA), rwatimes.substack, RWA.xyz (valeur des actifs du monde réel tokenisés). Les chiffres sont approximatifs selon chaque fournisseur de données et peuvent varier selon la source et le moment.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: The Block (métrica de volume de tweets), CoinDesk (fluxos de ETF, volume CEX, volume de futuros perpétuos RWA), rwatimes.substack, RWA.xyz (valor de ativos do mundo real tokenizados). Os números são aproximados conforme cada provedor de dados e podem variar conforme a fonte e o momento.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: The Block (tweet hacmi göstergesi), CoinDesk (ETF akışları, CEX hacmi, RWA sürekli vadeli işlem hacmi), rwatimes.substack, RWA.xyz (tokenize edilmiş gerçek dünya varlık değeri). Rakamlar her veri sağlayıcısına göre yaklaşık değerlerdir ve kaynağa ve zamana göre değişebilir.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: The Block (chỉ số khối lượng tweet), CoinDesk (dòng vốn ETF, khối lượng CEX, khối lượng hợp đồng tương lai vĩnh viễn RWA), rwatimes.substack, RWA.xyz (giá trị tài sản thực được token hóa). Các số liệu là giá trị gần đúng theo từng nhà cung cấp dữ liệu và có thể thay đổi tùy theo nguồn và thời điểm.</p>
<?php require __DIR__.'/_footer.php'; ?>
