<?php $slug = 'visa-stablecoin-platform-open-usd-circle-competition'; require __DIR__.'/_header.php'; ?>

<p class="ko">비자(Visa)가 7월 16일 은행과 핀테크 기업이 스테이블코인을 발행·보관·전송·상환할 수 있도록 지원하는 기업용 플랫폼 '비자 스테이블코인 플랫폼(Visa Stablecoin Platform, VSP)'을 공개했다. 코인데스크·블룸버그·포천 등에 따르면 VSP는 비자가 결제망을 통해 접근하는 약 1만5000개 금융기관과 2억 개 이상의 가맹점을 대상으로 하며, 초기에는 마스터카드·스트라이프·블랙록 등 140여 개 기업이 참여한 컨소시엄 오픈스탠더드(Open Standard)가 발행하는 스테이블코인 '오픈USD(Open USD, 티커 OUSD)'를 지원한다. 서비스는 일부 고객을 대상으로 한 베타 단계로 시작해 단계적으로 확대될 예정이다.</p>
<p class="en">Visa unveiled the Visa Stablecoin Platform (VSP) on July 16, an enterprise service letting banks and fintechs issue, hold, transfer and redeem stablecoins through a single Visa-managed system. According to CoinDesk, Bloomberg and Fortune, VSP is aimed at the roughly 15,000 financial institutions and more than 200 million merchants that touch Visa's payment network, and will initially support Open USD (ticker OUSD), a stablecoin issued by Open Standard, a consortium of more than 140 companies including Mastercard, Stripe and BlackRock. The service is launching in beta with select customers before a wider rollout.</p>
<p class="ja">ビザ(Visa)は7月16日、銀行やフィンテック企業がステーブルコインを発行・保管・送金・償還できるようにする企業向けプラットフォーム「ビザ・ステーブルコイン・プラットフォーム(Visa Stablecoin Platform, VSP)」を発表した。コインデスク、ブルームバーグ、フォーチュンによれば、VSPはビザの決済網が接続する約1万5000の金融機関と2億以上の加盟店を対象とし、初期段階ではマスターカード、ストライプ、ブラックロックなど140社超が参加するコンソーシアム、オープンスタンダード(Open Standard)が発行するステーブルコイン「オープンUSD(Open USD、ティッカーOUSD)」を支援する。サービスは一部顧客向けのベータ版として開始し、段階的に拡大する予定だ。</p>
<p class="es">Visa presentó el 16 de julio la Visa Stablecoin Platform (VSP), un servicio empresarial que permite a bancos y fintechs emitir, custodiar, transferir y canjear stablecoins a través de un único sistema gestionado por Visa. Según CoinDesk, Bloomberg y Fortune, VSP está dirigida a las aproximadamente 15.000 instituciones financieras y más de 200 millones de comercios conectados a la red de pagos de Visa, y en un inicio dará soporte a Open USD (ticker OUSD), una stablecoin emitida por Open Standard, un consorcio de más de 140 empresas entre las que están Mastercard, Stripe y BlackRock. El servicio arranca en beta con clientes seleccionados antes de una expansión más amplia.</p>
<p class="de">Visa stellte am 16. Juli die Visa Stablecoin Platform (VSP) vor, einen Unternehmensdienst, mit dem Banken und Fintechs Stablecoins über ein einziges, von Visa verwaltetes System ausgeben, verwahren, übertragen und einlösen können. Laut CoinDesk, Bloomberg und Fortune richtet sich VSP an die rund 15.000 Finanzinstitute und mehr als 200 Millionen Händler, die über Visas Zahlungsnetzwerk erreichbar sind, und unterstützt zunächst Open USD (Ticker OUSD), eine Stablecoin, die vom Konsortium Open Standard mit über 140 Mitgliedsunternehmen wie Mastercard, Stripe und BlackRock ausgegeben wird. Der Dienst startet als Beta mit ausgewählten Kunden vor einem breiteren Rollout.</p>
<p class="fr">Visa a dévoilé le 16 juillet la Visa Stablecoin Platform (VSP), un service d'entreprise permettant aux banques et fintechs d'émettre, conserver, transférer et racheter des stablecoins via un système unique géré par Visa. Selon CoinDesk, Bloomberg et Fortune, VSP cible les quelque 15 000 institutions financières et plus de 200 millions de commerçants connectés au réseau de paiement de Visa, et prendra d'abord en charge Open USD (symbole OUSD), un stablecoin émis par Open Standard, un consortium de plus de 140 entreprises dont Mastercard, Stripe et BlackRock. Le service démarre en bêta avec des clients sélectionnés avant un déploiement plus large.</p>
<p class="pt">A Visa revelou em 16 de julho a Visa Stablecoin Platform (VSP), um serviço corporativo que permite a bancos e fintechs emitir, custodiar, transferir e resgatar stablecoins por meio de um único sistema gerenciado pela Visa. Segundo CoinDesk, Bloomberg e Fortune, a VSP tem como alvo cerca de 15 mil instituições financeiras e mais de 200 milhões de comerciantes conectados à rede de pagamentos da Visa, e inicialmente dará suporte à Open USD (ticker OUSD), uma stablecoin emitida pela Open Standard, um consórcio com mais de 140 empresas, incluindo Mastercard, Stripe e BlackRock. O serviço começa em beta com clientes selecionados antes de uma expansão mais ampla.</p>
<p class="tr">Visa, 16 Temmuz'da bankaların ve fintek şirketlerinin tek bir Visa yönetimli sistem üzerinden stabilcoin ihraç etmesine, saklamasına, transfer etmesine ve itfa etmesine olanak tanıyan kurumsal hizmeti Visa Stablecoin Platform'u (VSP) tanıttı. CoinDesk, Bloomberg ve Fortune'a göre VSP, Visa'nın ödeme ağının ulaştığı yaklaşık 15.000 finans kuruluşunu ve 200 milyondan fazla satıcıyı hedefliyor ve başlangıçta Mastercard, Stripe ve BlackRock dahil 140'tan fazla şirketin oluşturduğu Open Standard konsorsiyumunun ihraç ettiği Open USD (OUSD) stabilcoinini destekleyecek. Hizmet, geniş çaplı kullanıma geçmeden önce seçili müşterilerle beta olarak başlıyor.</p>
<p class="vi">Visa đã công bố Nền tảng Stablecoin Visa (Visa Stablecoin Platform, VSP) vào ngày 16/7, một dịch vụ dành cho doanh nghiệp cho phép ngân hàng và công ty fintech phát hành, lưu giữ, chuyển và đổi lại stablecoin thông qua một hệ thống duy nhất do Visa quản lý. Theo CoinDesk, Bloomberg và Fortune, VSP nhắm đến khoảng 15.000 tổ chức tài chính và hơn 200 triệu điểm chấp nhận thanh toán kết nối với mạng lưới của Visa, và ban đầu sẽ hỗ trợ Open USD (mã OUSD), một stablecoin do liên minh Open Standard với hơn 140 công ty thành viên gồm Mastercard, Stripe và BlackRock phát hành. Dịch vụ khởi động ở giai đoạn beta với một số khách hàng chọn lọc trước khi mở rộng.</p>

<h2 class="ko">단일 발행사 모델과 무엇이 다른가</h2>
<h2 class="en">How This Differs From the Single-Issuer Model</h2>
<h2 class="ja">単一発行体モデルと何が違うのか</h2>
<h2 class="es">En qué se diferencia del modelo de emisor único</h2>
<h2 class="de">Was sich vom Modell des einzelnen Emittenten unterscheidet</h2>
<h2 class="fr">En quoi cela diffère du modèle à émetteur unique</h2>
<h2 class="pt">Em que isso difere do modelo de emissor único</h2>
<h2 class="tr">Bu, Tekli İhraççı Modelinden Nasıl Farklı</h2>
<h2 class="vi">Điểm Khác Biệt So Với Mô Hình Nhà Phát Hành Đơn Lẻ</h2>

<p class="ko">오픈USD는 지난 6월 30일 출범한 컨소시엄 오픈스탠더드가 발행하는데, 서클(USDC)이나 테더(USDT)처럼 하나의 회사가 발행 이익을 독점하는 구조가 아니다. 참여 기업 이사회가 지배구조를 구성하고, 준비자산에서 발생하는 이자수익 대부분을 관리 수수료를 제외한 뒤 참여사들에게 배분한다. 발행·상환에는 수량 제한이나 수수료가 없다는 점도 특징이다. 비자의 VSP는 이 오픈USD를 은행·핀테크가 자체 브랜드로 발행·유통할 수 있도록 지갑 인프라, 발행·상환 엔진, 트레저리 관리 기능을 하나의 시스템으로 묶어 제공하는 역할을 한다. 즉 VSP 자체가 새로운 스테이블코인이 아니라, 결제 인프라 대기업이 스테이블코인을 '배포'하는 파이프라인이라는 점이 핵심이다.</p>
<p class="en">Open USD is issued by Open Standard, the consortium that launched on June 30 — structurally different from single-company issuers like Circle (USDC) or Tether (USDT) that keep issuance profits for themselves. Open Standard is governed by a board drawn from member companies, and most of the interest income earned on reserve assets is distributed back to partners after a management fee, with no caps or fees on minting and redemption. Visa's VSP, in turn, packages wallet infrastructure, an issuance-and-redemption engine, and treasury management into one system so banks and fintechs can distribute Open USD under their own brand. The key point is that VSP itself isn't a new stablecoin — it's the distribution pipeline a payments giant is building around one.</p>
<p class="ja">オープンUSDは6月30日に発足したコンソーシアム、オープンスタンダードが発行するもので、サークル(USDC)やテザー(USDT)のように一社が発行益を独占する構造ではない。参加企業の取締役会が統治構造を構成し、準備資産から生じる利息収益の大部分は管理手数料を除いた上で参加各社に分配される。発行・償還に数量制限や手数料がない点も特徴だ。ビザのVSPはこのオープンUSDを銀行やフィンテックが自社ブランドで発行・流通できるよう、ウォレット基盤、発行・償還エンジン、トレジャリー管理機能を一つのシステムにまとめて提供する役割を担う。つまりVSP自体が新しいステーブルコインなのではなく、決済インフラ大手がステーブルコインを「配布」するパイプラインである点が要点だ。</p>
<p class="es">Open USD es emitida por Open Standard, el consorcio lanzado el 30 de junio, estructuralmente distinto de emisores de una sola empresa como Circle (USDC) o Tether (USDT), que se quedan con las ganancias de emisión. Open Standard está gobernada por una junta formada por empresas miembro, y la mayor parte del interés generado por los activos de reserva se distribuye a los socios tras descontar una comisión de gestión, sin límites ni comisiones en la emisión y el canje. La VSP de Visa, por su parte, empaqueta infraestructura de wallets, un motor de emisión y canje, y gestión de tesorería en un solo sistema para que bancos y fintechs distribuyan Open USD bajo su propia marca. El punto clave es que la VSP en sí no es una nueva stablecoin, sino la tubería de distribución que un gigante de pagos está construyendo alrededor de una.</p>
<p class="de">Open USD wird von Open Standard ausgegeben, dem am 30. Juni gestarteten Konsortium — strukturell anders als Einzelemittenten wie Circle (USDC) oder Tether (USDT), die die Emissionsgewinne selbst behalten. Open Standard wird von einem aus Mitgliedsunternehmen gebildeten Board gesteuert, und der Großteil der Zinserträge aus den Reserveanlagen wird nach Abzug einer Verwaltungsgebühr an die Partner ausgeschüttet, ohne Obergrenzen oder Gebühren bei Ausgabe und Rücknahme. Visas VSP wiederum bündelt Wallet-Infrastruktur, eine Ausgabe- und Rücknahme-Engine sowie Treasury-Management in einem System, damit Banken und Fintechs Open USD unter eigener Marke vertreiben können. Entscheidend ist: VSP selbst ist keine neue Stablecoin, sondern die Vertriebspipeline, die ein Zahlungsriese um eine solche herum baut.</p>
<p class="fr">Open USD est émis par Open Standard, le consortium lancé le 30 juin — structurellement différent des émetteurs uniques comme Circle (USDC) ou Tether (USDT), qui conservent les profits d'émission pour eux-mêmes. Open Standard est régi par un conseil issu des entreprises membres, et l'essentiel des revenus d'intérêts générés par les actifs de réserve est redistribué aux partenaires après déduction de frais de gestion, sans plafond ni frais sur l'émission et le rachat. La VSP de Visa, elle, regroupe une infrastructure de portefeuilles, un moteur d'émission-rachat et une gestion de trésorerie en un seul système pour que banques et fintechs distribuent Open USD sous leur propre marque. Le point clé est que la VSP n'est pas elle-même un nouveau stablecoin, mais le pipeline de distribution qu'un géant des paiements construit autour de celui-ci.</p>
<p class="pt">A Open USD é emitida pela Open Standard, o consórcio lançado em 30 de junho — estruturalmente diferente de emissores únicos como a Circle (USDC) ou a Tether (USDT), que retêm os lucros da emissão para si. A Open Standard é governada por um conselho formado por empresas membros, e a maior parte da receita de juros gerada pelos ativos de reserva é distribuída aos parceiros após uma taxa de gestão, sem limites ou taxas sobre emissão e resgate. Já a VSP da Visa reúne infraestrutura de carteiras, um mecanismo de emissão e resgate e gestão de tesouraria em um único sistema para que bancos e fintechs distribuam a Open USD sob sua própria marca. O ponto central é que a VSP em si não é uma nova stablecoin, mas o pipeline de distribuição que uma gigante de pagamentos está construindo em torno de uma.</p>
<p class="tr">Open USD, 30 Haziran'da kurulan konsorsiyum Open Standard tarafından ihraç ediliyor — ihraç kârlarını kendine saklayan Circle (USDC) veya Tether (USDT) gibi tekli ihraççılardan yapısal olarak farklı. Open Standard, üye şirketlerden oluşan bir kurul tarafından yönetiliyor ve rezerv varlıklardan elde edilen faiz gelirinin büyük kısmı, bir yönetim ücreti düşüldükten sonra ortaklara dağıtılıyor; basım ve itfada üst sınır veya ücret yok. Visa'nın VSP'si ise cüzdan altyapısını, ihraç-itfa motorunu ve hazine yönetimini tek bir sistemde birleştirerek bankaların ve finteklerin Open USD'yi kendi markaları altında dağıtmasını sağlıyor. Kritik nokta, VSP'nin kendisinin yeni bir stabilcoin olmaması; bir ödeme devinin bir stabilcoin etrafında kurduğu dağıtım hattı olmasıdır.</p>
<p class="vi">Open USD do Open Standard phát hành, liên minh ra mắt ngày 30/6 — khác biệt về cấu trúc so với các nhà phát hành đơn lẻ như Circle (USDC) hay Tether (USDT), vốn giữ lại lợi nhuận phát hành cho riêng mình. Open Standard được quản trị bởi một hội đồng gồm các công ty thành viên, và phần lớn thu nhập lãi từ tài sản dự trữ được phân phối lại cho các đối tác sau khi trừ phí quản lý, không giới hạn số lượng hay phí khi phát hành và đổi lại. Còn VSP của Visa đóng gói hạ tầng ví, cơ chế phát hành-đổi lại và quản lý ngân khố thành một hệ thống duy nhất để ngân hàng và fintech phân phối Open USD dưới thương hiệu riêng của họ. Điểm mấu chốt là bản thân VSP không phải một stablecoin mới, mà là đường ống phân phối mà một gã khổng lồ thanh toán đang xây dựng xung quanh nó.</p>

<div class="ko en ja es de fr pt tr vi"><svg viewBox="0 0 700 400" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="34" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Single-Issuer vs Open USD Consortium Model</text>
  <g font-family="sans-serif">
    <rect x="30" y="60" width="300" height="180" rx="10" fill="#1c1c1e" stroke="#71717a" stroke-width="1.2"/>
    <text x="180" y="88" fill="#e4e4e7" font-size="14" font-weight="700" text-anchor="middle">USDC / USDT</text>
    <circle cx="180" cy="150" r="45" fill="#06b6d4" opacity="0.25" stroke="#06b6d4" stroke-width="2"/>
    <text x="180" y="156" fill="#67e8f9" font-size="13" font-weight="700" text-anchor="middle">1 issuer</text>
    <text x="180" y="215" fill="#a1a1aa" font-size="12" text-anchor="middle">Reserve yield kept</text>
    <text x="180" y="232" fill="#a1a1aa" font-size="12" text-anchor="middle">by the issuer</text>
  </g>
  <g font-family="sans-serif">
    <rect x="370" y="60" width="300" height="180" rx="10" fill="#1c1c1e" stroke="#71717a" stroke-width="1.2"/>
    <text x="520" y="88" fill="#e4e4e7" font-size="14" font-weight="700" text-anchor="middle">Open USD (OUSD)</text>
    <circle cx="460" cy="150" r="18" fill="#38bdf8" opacity="0.5"/>
    <circle cx="500" cy="130" r="18" fill="#38bdf8" opacity="0.5"/>
    <circle cx="540" cy="155" r="18" fill="#38bdf8" opacity="0.5"/>
    <circle cx="580" cy="130" r="18" fill="#38bdf8" opacity="0.5"/>
    <circle cx="500" cy="175" r="18" fill="#38bdf8" opacity="0.5"/>
    <text x="520" y="205" fill="#7dd3fc" font-size="13" font-weight="700" text-anchor="middle">140+ partners</text>
    <text x="520" y="225" fill="#a1a1aa" font-size="12" text-anchor="middle">Yield shared, no mint/redeem fee</text>
  </g>
  <text x="30" y="270" fill="#fbbf24" font-size="14" font-weight="700" font-family="sans-serif">VSP scale (Visa network)</text>
  <rect x="30" y="285" width="640" height="90" rx="10" fill="#1c1c1e" stroke="#71717a" stroke-width="1.2"/>
  <text x="60" y="320" fill="#f4f4f5" font-size="24" font-weight="700" font-family="sans-serif">15,000</text>
  <text x="60" y="340" fill="#a1a1aa" font-size="11" font-family="sans-serif">institutions</text>
  <text x="270" y="320" fill="#f4f4f5" font-size="24" font-weight="700" font-family="sans-serif">200M+</text>
  <text x="270" y="340" fill="#a1a1aa" font-size="11" font-family="sans-serif">merchants</text>
  <text x="470" y="320" fill="#f4f4f5" font-size="24" font-weight="700" font-family="sans-serif">$15T/yr</text>
  <text x="470" y="340" fill="#a1a1aa" font-size="11" font-family="sans-serif">Visa settlement volume</text>
</svg></div>

<h2 class="ko">서클에게는 두 번째 충격 — 경쟁 구도와 남은 질문들</h2>
<h2 class="en">A Second Blow to Circle — the Competitive Landscape and Open Questions</h2>
<h2 class="ja">サークルへの二度目の打撃 — 競争構図と残された疑問</h2>
<h2 class="es">Un segundo golpe para Circle: el panorama competitivo y las preguntas abiertas</h2>
<h2 class="de">Ein zweiter Schlag für Circle — die Wettbewerbslage und offene Fragen</h2>
<h2 class="fr">Un second coup dur pour Circle — paysage concurrentiel et questions en suspens</h2>
<h2 class="pt">Um segundo golpe para a Circle — o cenário competitivo e questões em aberto</h2>
<h2 class="tr">Circle İçin İkinci Darbe — Rekabet Ortamı ve Açık Sorular</h2>
<h2 class="vi">Đòn Giáng Thứ Hai Vào Circle — Bối Cảnh Cạnh Tranh Và Những Câu Hỏi Còn Bỏ Ngỏ</h2>

<p class="ko">오픈USD 컨소시엄 결성 소식이 처음 전해졌을 때 서클 주가가 급락한 바 있다. VSP는 그 컨소시엄의 발행 상품을 비자의 실제 결제망에 얹는 유통 채널이라는 점에서, 서클과 테더가 10년 가까이 지배해 온 스테이블코인 시장 구도에 결제 대기업들이 직접 뛰어들었다는 신호로 읽힌다. 과거에도 JP모건의 JPM코인이나 페이팔의 PYUSD처럼 대형 금융·결제사가 자체 스테이블코인을 시도한 사례는 있었지만, 대부분 폐쇄형 네트워크나 자사 생태계 안에 머물렀다. 이번 VSP-오픈USD 조합이 다른 점은 처음부터 경쟁 관계였던 비자·마스터카드·스트라이프 등이 한 발행체 아래 뭉쳐 이해관계를 일치시켰다는 데 있다.</p>
<p class="en">Circle's stock dropped sharply when news of the Open USD consortium first broke. VSP is essentially the distribution channel that puts that consortium's issued product onto Visa's live payment rails, which reads as a signal that payments giants are moving directly into a stablecoin market Circle and Tether have dominated for nearly a decade. Big financial and payments firms have tried proprietary stablecoins before — JPMorgan's JPM Coin, PayPal's PYUSD — but most stayed confined to closed networks or a single company's own ecosystem. What's different about the VSP-Open USD combination is that historically competing firms — Visa, Mastercard, Stripe and others — aligned their interests under one shared issuer from the start.</p>
<p class="ja">オープンUSDコンソーシアム結成のニュースが最初に伝わったとき、サークルの株価は急落した。VSPはそのコンソーシアムの発行商品をビザの実際の決済網に乗せる流通チャネルであるという点で、サークルとテザーが10年近く支配してきたステーブルコイン市場の構図に決済大手が直接踏み込んできたシグナルと読める。過去にもJPモルガンのJPMコインやペイパルのPYUSDのように大手金融・決済会社が自社ステーブルコインを試みた例はあったが、大半は閉鎖型ネットワークや自社エコシステム内にとどまった。今回のVSP・オープンUSDの組み合わせが異なるのは、もともと競合関係にあったビザ、マスターカード、ストライプなどが一つの発行体の下で利害を一致させた点だ。</p>
<p class="es">Las acciones de Circle cayeron con fuerza cuando se conoció por primera vez la noticia del consorcio Open USD. VSP es, en esencia, el canal de distribución que lleva el producto emitido por ese consorcio a los rieles de pago reales de Visa, lo cual se lee como una señal de que los gigantes de pagos están entrando directamente en un mercado de stablecoins que Circle y Tether han dominado durante casi una década. Grandes firmas financieras y de pagos ya habían intentado stablecoins propias antes —el JPM Coin de JPMorgan, el PYUSD de PayPal—, pero la mayoría se quedó confinada a redes cerradas o al ecosistema propio de una sola empresa. Lo distinto de la combinación VSP-Open USD es que firmas históricamente competidoras —Visa, Mastercard, Stripe y otras— alinearon sus intereses bajo un emisor compartido desde el inicio.</p>
<p class="de">Die Circle-Aktie brach stark ein, als die Nachricht vom Open-USD-Konsortium erstmals bekannt wurde. VSP ist im Grunde der Vertriebskanal, der das vom Konsortium ausgegebene Produkt auf Visas reale Zahlungsschienen bringt — was als Signal zu lesen ist, dass Zahlungsriesen direkt in einen Stablecoin-Markt vordringen, den Circle und Tether fast ein Jahrzehnt lang dominiert haben. Große Finanz- und Zahlungsunternehmen haben schon zuvor eigene Stablecoins versucht — JPMorgans JPM Coin, PayPals PYUSD —, doch die meisten blieben auf geschlossene Netzwerke oder das eigene Ökosystem beschränkt. Das Besondere an der Kombination VSP-Open USD ist, dass historisch konkurrierende Firmen — Visa, Mastercard, Stripe und andere — ihre Interessen von Anfang an unter einem gemeinsamen Emittenten gebündelt haben.</p>
<p class="fr">L'action Circle avait fortement chuté quand la nouvelle du consortium Open USD avait éclaté. VSP est essentiellement le canal de distribution qui met le produit émis par ce consortium sur les rails de paiement réels de Visa, ce qui se lit comme un signal que les géants des paiements s'engagent directement sur un marché des stablecoins que Circle et Tether dominent depuis près d'une décennie. De grandes entreprises financières et de paiement avaient déjà tenté des stablecoins propriétaires — le JPM Coin de JPMorgan, le PYUSD de PayPal — mais la plupart sont restées confinées à des réseaux fermés ou à l'écosystème d'une seule entreprise. Ce qui distingue la combinaison VSP-Open USD, c'est que des entreprises historiquement concurrentes — Visa, Mastercard, Stripe et d'autres — ont aligné leurs intérêts sous un émetteur commun dès le départ.</p>
<p class="pt">As ações da Circle caíram forte quando a notícia do consórcio Open USD veio à tona pela primeira vez. A VSP é, essencialmente, o canal de distribuição que leva o produto emitido por esse consórcio para os trilhos de pagamento reais da Visa, o que se lê como um sinal de que gigantes de pagamentos estão entrando diretamente em um mercado de stablecoins que Circle e Tether dominaram por quase uma década. Grandes empresas financeiras e de pagamentos já haviam tentado stablecoins próprias antes — o JPM Coin do JPMorgan, o PYUSD do PayPal —, mas a maioria ficou confinada a redes fechadas ou ao próprio ecossistema de uma empresa. O que diferencia a combinação VSP-Open USD é que empresas historicamente concorrentes — Visa, Mastercard, Stripe e outras — alinharam seus interesses sob um emissor compartilhado desde o início.</p>
<p class="tr">Open USD konsorsiyumu haberi ilk yayıldığında Circle hisseleri sert düştü. VSP, esasen o konsorsiyumun ihraç ettiği ürünü Visa'nın gerçek ödeme raylarına taşıyan dağıtım kanalıdır; bu da ödeme devlerinin, Circle ve Tether'in neredeyse on yıldır domine ettiği bir stabilcoin piyasasına doğrudan girdiğinin bir işareti olarak okunuyor. Büyük finans ve ödeme şirketleri daha önce de kendi stabilcoinlerini denemişti — JPMorgan'ın JPM Coin'i, PayPal'ın PYUSD'si — ancak çoğu kapalı ağlarla veya tek bir şirketin kendi ekosistemiyle sınırlı kaldı. VSP-Open USD kombinasyonunu farklı kılan, tarihsel olarak rakip olan Visa, Mastercard, Stripe gibi şirketlerin çıkarlarını en baştan ortak bir ihraççı altında hizalamış olmasıdır.</p>
<p class="vi">Cổ phiếu Circle đã giảm mạnh khi tin tức về liên minh Open USD lần đầu được công bố. VSP về cơ bản là kênh phân phối đưa sản phẩm do liên minh đó phát hành lên hệ thống thanh toán thực tế của Visa, điều này được hiểu như một tín hiệu cho thấy các ông lớn thanh toán đang tiến thẳng vào thị trường stablecoin mà Circle và Tether đã thống trị gần một thập kỷ. Các công ty tài chính và thanh toán lớn từng thử stablecoin riêng trước đây — JPM Coin của JPMorgan, PYUSD của PayPal — nhưng phần lớn chỉ giới hạn trong mạng lưới khép kín hoặc hệ sinh thái riêng của một công ty. Điều khác biệt ở sự kết hợp VSP-Open USD là các công ty vốn là đối thủ cạnh tranh trong lịch sử — Visa, Mastercard, Stripe và những công ty khác — đã đồng nhất lợi ích của họ dưới một nhà phát hành chung ngay từ đầu.</p>

<p class="ko">다만 규모를 과대평가하지 않도록 주의할 필요는 있다. 비자가 내세운 '1만5000개 기관·2억 가맹점·연 15조 달러 결제'라는 숫자는 VSP가 이론적으로 접근 가능한 네트워크 전체 규모이지, 오픈USD의 실제 채택 규모가 아니다. 서비스는 아직 베타 단계이며, 미국에서는 스테이블코인 발행사의 준비자산·자본 규제를 규정하는 지니어스법(GENIUS Act) 후속 규칙 제정이 7월 18일 마감 시한을 앞두고도 6개 관계 기관 중 어느 곳도 최종 규칙을 발표하지 못한 상태다. 즉 대형 결제망을 등에 업은 유통력은 확보했지만, 실제 발행 잔액이 서클의 USDC나 테더의 USDT 규모를 단기간에 잠식할지는 아직 검증되지 않았다는 반박도 가능하다. 지켜볼 지점은 ①VSP 베타 참여 은행·핀테크의 실제 명단과 규모, ②오픈USD 유통량이 출범 이후 몇 주 안에 얼마나 빠르게 늘어나는지, ③지니어스법 세부 규칙이 오픈USD 같은 컨소시엄형 발행 구조에 어떤 자본·준비자산 요건을 적용할지다.</p>
<p class="en">That scale figure deserves a caveat, though. Visa's touted "15,000 institutions, 200 million merchants, $15 trillion in annual payment volume" describes the network VSP can theoretically reach, not Open USD's actual adoption. The service remains in beta, and in the U.S., the GENIUS Act's follow-on rulemaking — which will set reserve and capital requirements for stablecoin issuers — has missed its own July 18 deadline, with none of the six responsible agencies having finalized rules yet. So there's a fair counter-read: Visa has secured distribution muscle by riding its existing payment rails, but whether Open USD's actual circulating balance can erode Circle's USDC or Tether's USDT in the near term remains unproven. Worth watching: (1) the actual roster and size of banks and fintechs joining the VSP beta; (2) how fast Open USD's circulating supply grows in the weeks after launch; (3) what capital and reserve requirements the GENIUS Act's final rules impose on consortium-issued stablecoins like this one.</p>
<p class="ja">ただし、この規模を過大評価しないよう注意が必要だ。ビザが掲げる「1万5000機関・2億加盟店・年間15兆ドルの決済」という数字は、VSPが理論上到達可能なネットワーク全体の規模であって、オープンUSDの実際の採用規模ではない。サービスはまだベータ段階であり、米国ではステーブルコイン発行体の準備資産・資本規制を定めるジーニアス法(GENIUS Act)の後続規則制定が7月18日の期限を控えながらも、6つの関係機関のいずれも最終規則を発表できていない。つまり大手決済網を背にした流通力は確保したものの、実際の発行残高がサークルのUSDCやテザーのUSDTの規模を短期間で侵食するかはまだ検証されていない、という反論も可能だ。注視すべき点は、①VSPベータに参加する銀行・フィンテックの実際の顔ぶれと規模、②オープンUSDの流通量が発足後数週間でどれだけ急速に増えるか、③ジーニアス法の細則がオープンUSDのようなコンソーシアム型発行構造にどのような資本・準備資産要件を課すかだ。</p>
<p class="es">Sin embargo, conviene matizar esa cifra de escala. Los "15.000 instituciones, 200 millones de comercios, 15 billones de dólares en volumen anual de pagos" que promociona Visa describen la red que VSP puede alcanzar teóricamente, no la adopción real de Open USD. El servicio sigue en fase beta, y en EE. UU. la reglamentación derivada de la Ley GENIUS —que fijará los requisitos de reservas y capital para emisores de stablecoins— ha incumplido su propio plazo del 18 de julio, sin que ninguna de las seis agencias responsables haya finalizado las normas todavía. Cabe entonces una lectura contraria razonable: Visa se ha asegurado músculo de distribución apoyándose en sus rieles de pago existentes, pero si el saldo circulante real de Open USD puede erosionar el USDC de Circle o el USDT de Tether a corto plazo sigue sin comprobarse. Vale la pena vigilar: (1) la nómina y el tamaño reales de bancos y fintechs que se sumen a la beta de VSP; (2) qué tan rápido crece la oferta circulante de Open USD en las semanas posteriores al lanzamiento; (3) qué requisitos de capital y reservas impondrán las normas finales de la Ley GENIUS a stablecoins emitidas por consorcios como esta.</p>
<p class="de">Diese Größenangabe verdient jedoch einen Vorbehalt. Visas vielzitierte „15.000 Institute, 200 Millionen Händler, 15 Billionen Dollar jährliches Zahlungsvolumen" beschreiben das Netzwerk, das VSP theoretisch erreichen kann, nicht die tatsächliche Verbreitung von Open USD. Der Dienst befindet sich noch in der Beta-Phase, und in den USA hat die Folgeregulierung des GENIUS Act — die Reserve- und Kapitalanforderungen für Stablecoin-Emittenten festlegen soll — ihre eigene Frist vom 18. Juli verpasst, ohne dass eine der sechs zuständigen Behörden bislang endgültige Regeln erlassen hat. Es gibt also eine faire Gegenlesart: Visa hat sich Vertriebsstärke gesichert, indem es auf seinen bestehenden Zahlungsschienen aufsetzt, aber ob der tatsächliche Umlaufbestand von Open USD Circles USDC oder Tethers USDT kurzfristig verdrängen kann, bleibt unbewiesen. Beobachtenswert: (1) die tatsächliche Liste und Größe der Banken und Fintechs, die der VSP-Beta beitreten; (2) wie schnell der Umlaufbestand von Open USD in den Wochen nach dem Start wächst; (3) welche Kapital- und Reserveanforderungen die endgültigen GENIUS-Act-Regeln für konsortial ausgegebene Stablecoins wie diesen vorschreiben.</p>
<p class="fr">Ce chiffre d'échelle mérite toutefois une réserve. Les « 15 000 institutions, 200 millions de commerçants, 15 000 milliards de dollars de volume de paiement annuel » avancés par Visa décrivent le réseau que VSP peut théoriquement atteindre, pas l'adoption réelle d'Open USD. Le service reste en bêta, et aux États-Unis, la réglementation d'application du GENIUS Act — qui fixera les exigences de réserves et de capital pour les émetteurs de stablecoins — a manqué sa propre échéance du 18 juillet, aucune des six agences responsables n'ayant encore finalisé de règles. Une lecture inverse est donc défendable : Visa s'est assuré une force de distribution en s'appuyant sur ses rails de paiement existants, mais que l'encours réel d'Open USD puisse éroder à court terme l'USDC de Circle ou l'USDT de Tether reste à prouver. À surveiller : (1) la liste et la taille réelles des banques et fintechs rejoignant la bêta de VSP ; (2) la vitesse de croissance de l'offre en circulation d'Open USD dans les semaines suivant le lancement ; (3) les exigences de capital et de réserves que les règles finales du GENIUS Act imposeront aux stablecoins émis par des consortiums comme celui-ci.</p>
<p class="pt">Esse número de escala merece, porém, uma ressalva. Os "15 mil instituições, 200 milhões de comerciantes, US$ 15 trilhões em volume anual de pagamentos" divulgados pela Visa descrevem a rede que a VSP pode teoricamente alcançar, não a adoção real da Open USD. O serviço ainda está em beta, e nos EUA a regulamentação subsequente da Lei GENIUS — que definirá exigências de reserva e capital para emissores de stablecoins — perdeu seu próprio prazo de 18 de julho, sem que nenhuma das seis agências responsáveis tenha finalizado as regras até agora. Cabe, portanto, uma leitura contrária razoável: a Visa garantiu força de distribuição ao se apoiar em seus trilhos de pagamento já existentes, mas se o saldo circulante real da Open USD conseguirá corroer o USDC da Circle ou o USDT da Tether no curto prazo ainda não está comprovado. Vale observar: (1) a lista e o tamanho reais de bancos e fintechs que aderirem à beta da VSP; (2) a velocidade de crescimento da oferta circulante da Open USD nas semanas após o lançamento; (3) quais exigências de capital e reserva as regras finais da Lei GENIUS imporão a stablecoins emitidas por consórcios como este.</p>
<p class="tr">Ancak bu ölçek rakamı bir çekince hak ediyor. Visa'nın öne çıkardığı "15.000 kurum, 200 milyon satıcı, yıllık 15 trilyon dolarlık ödeme hacmi" ifadesi, VSP'nin teorik olarak ulaşabileceği ağı tanımlıyor, Open USD'nin gerçek benimsenme düzeyini değil. Hizmet hâlâ beta aşamasında ve ABD'de, stabilcoin ihraççıları için rezerv ve sermaye gerekliliklerini belirleyecek olan GENIUS Yasası'nın devam kurallarının kendi 18 Temmuz son teslim tarihi kaçırılmış durumda; sorumlu altı kurumdan hiçbiri henüz nihai kuralları yayımlamadı. Dolayısıyla makul bir karşı okuma da mümkün: Visa mevcut ödeme raylarına dayanarak dağıtım gücünü garantiledi, ancak Open USD'nin gerçek dolaşımdaki bakiyesinin kısa vadede Circle'ın USDC'sini veya Tether'in USDT'sini aşındırıp aşındıramayacağı henüz kanıtlanmadı. İzlenmesi gerekenler: (1) VSP betasına katılan banka ve finteklerin gerçek listesi ve büyüklüğü; (2) Open USD'nin dolaşımdaki arzının lansmandan sonraki haftalarda ne kadar hızlı büyüdüğü; (3) GENIUS Yasası'nın nihai kurallarının bu tür konsorsiyum tarafından ihraç edilen stabilcoinlere ne tür sermaye ve rezerv gereklilikleri getireceği.</p>
<p class="vi">Tuy nhiên, con số quy mô này cần một lưu ý. Con số "15.000 tổ chức, 200 triệu điểm chấp nhận thanh toán, 15 nghìn tỷ USD khối lượng thanh toán hàng năm" mà Visa nêu ra mô tả mạng lưới mà VSP có thể tiếp cận về mặt lý thuyết, không phải mức độ áp dụng thực tế của Open USD. Dịch vụ vẫn đang trong giai đoạn beta, và tại Mỹ, việc ban hành quy tắc tiếp theo của Đạo luật GENIUS — vốn sẽ đặt ra yêu cầu về dự trữ và vốn cho các nhà phát hành stablecoin — đã lỡ hạn chót ngày 18/7 do chính mình đặt ra, khi chưa cơ quan nào trong số sáu cơ quan phụ trách hoàn tất quy tắc cuối cùng. Vì vậy có một cách đọc ngược lại hợp lý: Visa đã đảm bảo được sức mạnh phân phối nhờ dựa vào hệ thống thanh toán sẵn có, nhưng liệu số dư lưu hành thực tế của Open USD có thể xói mòn USDC của Circle hay USDT của Tether trong ngắn hạn hay không vẫn chưa được kiểm chứng. Đáng theo dõi: (1) danh sách và quy mô thực tế của các ngân hàng, fintech tham gia beta VSP; (2) tốc độ tăng trưởng nguồn cung lưu hành của Open USD trong những tuần sau khi ra mắt; (3) các yêu cầu về vốn và dự trữ mà quy tắc cuối cùng của Đạo luật GENIUS sẽ áp dụng cho các stablecoin do liên minh phát hành như thế này.</p>

<p class="ko">서클의 주가가 오픈USD 컨소시엄 결성 소식만으로 급락했던 배경은 <a href="/blog/circle-stock-crash-open-usd">관련 기사</a>에서 더 자세히 다뤘다.</p>
<p class="en">The earlier stock-price shock Circle took purely from the Open USD consortium announcement is covered in more detail in <a href="/en/blog/circle-stock-crash-open-usd">this related article</a>.</p>
<p class="ja">オープンUSDコンソーシアム結成の発表だけでサークル株が急落した経緯は<a href="/ja/blog/circle-stock-crash-open-usd">こちらの関連記事</a>で詳しく取り上げている。</p>
<p class="es">El desplome anterior de la acción de Circle únicamente por el anuncio del consorcio Open USD se analiza con más detalle en <a href="/es/blog/circle-stock-crash-open-usd">este artículo relacionado</a>.</p>
<p class="de">Der frühere Kurssturz von Circle allein aufgrund der Ankündigung des Open-USD-Konsortiums wird ausführlicher in <a href="/de/blog/circle-stock-crash-open-usd">diesem verwandten Artikel</a> behandelt.</p>
<p class="fr">Le choc boursier subi plus tôt par Circle après la seule annonce du consortium Open USD est détaillé dans <a href="/fr/blog/circle-stock-crash-open-usd">cet article associé</a>.</p>
<p class="pt">O choque anterior no preço das ações da Circle apenas com o anúncio do consórcio Open USD é detalhado em <a href="/pt/blog/circle-stock-crash-open-usd">neste artigo relacionado</a>.</p>
<p class="tr">Circle hisselerinin yalnızca Open USD konsorsiyumu duyurusuyla yaşadığı önceki şok, <a href="/tr/blog/circle-stock-crash-open-usd">bu ilgili yazıda</a> daha ayrıntılı ele alınıyor.</p>
<p class="vi">Cú sốc giá cổ phiếu trước đó mà Circle gánh chịu chỉ vì thông báo thành lập liên minh Open USD được phân tích chi tiết hơn trong <a href="/vi/blog/circle-stock-crash-open-usd">bài viết liên quan này</a>.</p>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <circle cx="900" cy="315" r="240" fill="none" stroke="#06b6d4" stroke-width="2" opacity="0.25"/>
  <circle cx="820" cy="240" r="16" fill="#06b6d4" opacity="0.55"/>
  <circle cx="880" cy="200" r="16" fill="#06b6d4" opacity="0.55"/>
  <circle cx="940" cy="245" r="16" fill="#06b6d4" opacity="0.55"/>
  <circle cx="1000" cy="200" r="16" fill="#06b6d4" opacity="0.55"/>
  <circle cx="880" cy="290" r="16" fill="#06b6d4" opacity="0.55"/>
  <text x="60" y="290" fill="#f4f4f5" font-size="120" font-weight="bold">140+</text>
  <text x="60" y="345" fill="#06b6d4" font-size="40" font-weight="bold">OPEN USD PARTNERS</text>
  <text x="60" y="420" fill="#8a8a94" font-size="34" font-weight="600">VSP ÷ $15T/YR</text>
</svg></div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 코인데스크(CoinDesk), 블룸버그(Bloomberg), 포천(Fortune), 디크립트(Decrypt), 핀테크매거진(FinTech Magazine), 테크부키(TechBooky), 넥스트웹(The Next Web), 더블록(The Block), 아메리칸뱅커(American Banker).</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CoinDesk, Bloomberg, Fortune, Decrypt, FinTech Magazine, TechBooky, The Next Web, The Block, American Banker.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: コインデスク(CoinDesk)、ブルームバーグ(Bloomberg)、フォーチュン(Fortune)、デクリプト(Decrypt)、フィンテックマガジン(FinTech Magazine)、テックブーキー(TechBooky)、ザ・ネクストウェブ(The Next Web)、ザ・ブロック(The Block)、アメリカンバンカー(American Banker)。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CoinDesk, Bloomberg, Fortune, Decrypt, FinTech Magazine, TechBooky, The Next Web, The Block, American Banker.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CoinDesk, Bloomberg, Fortune, Decrypt, FinTech Magazine, TechBooky, The Next Web, The Block, American Banker.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CoinDesk, Bloomberg, Fortune, Decrypt, FinTech Magazine, TechBooky, The Next Web, The Block, American Banker.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CoinDesk, Bloomberg, Fortune, Decrypt, FinTech Magazine, TechBooky, The Next Web, The Block, American Banker.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CoinDesk, Bloomberg, Fortune, Decrypt, FinTech Magazine, TechBooky, The Next Web, The Block, American Banker.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CoinDesk, Bloomberg, Fortune, Decrypt, FinTech Magazine, TechBooky, The Next Web, The Block, American Banker.</p>
<?php require __DIR__.'/_footer.php'; ?>
