<?php $slug = 'volatility-decay-leverage-tokens'; require __DIR__.'/_header.php'; ?>

<p class="ko">'포지션 방향을 맞히는 것'과 '그 포지션에서 살아남는 것'은 다른 문제다. 트레이더 대부분은 후자를 전자의 부산물로 여긴다 — 방향만 맞으면 나머지는 저절로 따라온다고. 그러나 2배·3배 레버리지 토큰이나 일일 리밸런싱형 레버리지 ETF에서는 이 가정 자체가 틀렸다. 비트코인 가격이 열흘 전과 정확히 같은 자리로 돌아와도, 그 사이 가격이 오르내린 경로가 충분히 거칠었다면 3배 토큰은 원금의 4분의 1가량을 잃을 수 있다. 방향 예측은 완벽했다. 그런데도 계좌는 줄어든다.</p>
<p class="en">"Getting the direction of a position right" and "surviving that position" are different problems. Most traders treat the second as a byproduct of the first — get the direction right, and the rest follows automatically. But for 2x and 3x leveraged tokens, or daily-rebalanced leveraged ETFs, that assumption is simply wrong. Even if Bitcoin's price returns to exactly where it stood ten days earlier, a 3x token can lose roughly a quarter of its principal if the path in between was rough enough. The directional call was perfect. The account still shrank.</p>
<p class="ja">「ポジションの方向を当てること」と「そのポジションで生き残ること」は別の問題だ。多くのトレーダーは後者を前者のおまけだと考えている——方向さえ当たれば、残りは自動的についてくると。しかし2倍・3倍レバレッジトークンや、毎日リバランスされるレバレッジETFでは、この前提そのものが間違っている。ビットコインの価格が10日前とちょうど同じ水準に戻っていたとしても、その間の値動きが十分に荒かったなら、3倍トークンは元本のおよそ4分の1を失うことがある。方向の予測は完璧だった。それでも口座残高は減っている。</p>
<p class="es">"Acertar la dirección de una posición" y "sobrevivir en esa posición" son problemas distintos. La mayoría de los traders trata el segundo como una consecuencia automática del primero: si aciertas la dirección, el resto viene solo. Pero en los tokens apalancados 2x y 3x, o en los ETF apalancados con reequilibrio diario, esa suposición es simplemente falsa. Aunque el precio de Bitcoin regrese exactamente al mismo nivel de diez días antes, un token 3x puede perder alrededor de una cuarta parte de su capital si el camino intermedio fue lo bastante accidentado. La predicción de dirección fue perfecta. La cuenta se redujo igual.</p>
<p class="de">"Die Richtung einer Position richtig einzuschätzen" und "diese Position zu überleben" sind zwei verschiedene Probleme. Die meisten Trader behandeln Zweiteres als automatisches Nebenprodukt des Ersteren — stimmt die Richtung, folgt der Rest von selbst. Bei 2x- und 3x-gehebelten Token oder täglich neu ausbalancierten gehebelten ETFs ist diese Annahme jedoch schlicht falsch. Selbst wenn der Bitcoin-Preis genau zu dem Niveau zurückkehrt, auf dem er zehn Tage zuvor stand, kann ein 3x-Token rund ein Viertel seines Kapitals verlieren, sofern der Weg dazwischen ausreichend ruppig war. Die Richtungseinschätzung war perfekt. Das Konto schrumpfte trotzdem.</p>

<p class="ko">이 현상에 붙는 이름이 변동성 감가(volatility decay), 혹은 리밸런싱 감가(rebalancing decay)다. 학계에서는 이미 오래전에 정리가 끝난 주제다 — Cheng과 Madhavan(2009)은 저널 오브 인베스트먼트 매니지먼트에 실린 논문에서, Avellaneda와 Zhang(2010)은 SIAM 저널 온 파이낸셜 매스매틱스에서 각각 레버리지 ETF 수익률의 경로의존성을 수학적으로 증명했다. 결론은 한 문장으로 요약된다: 레버리지 상품의 장기 수익률을 결정하는 건 시작가와 끝가의 차이가 아니라, 그 사이의 실현 변동성이다.</p>
<p class="en">The name for this is volatility decay, or rebalancing decay. Academia settled the matter long ago — Cheng and Madhavan (2009), in a paper published in the Journal of Investment Management, and Avellaneda and Zhang (2010), in the SIAM Journal on Financial Mathematics, each mathematically demonstrated the path dependence of leveraged ETF returns. The conclusion fits in one sentence: what determines a leveraged product's long-run return isn't the gap between the starting and ending price, but the realized volatility along the way.</p>
<p class="ja">この現象に付けられた名前がボラティリティ減価(volatility decay)、あるいはリバランス減価だ。学術界ではすでに久しく決着がついているテーマである——チェンとマダヴァン(2009)はジャーナル・オブ・インベストメント・マネジメント誌に掲載された論文で、アベジャネダとジャン(2010)はSIAMジャーナル・オン・ファイナンシャル・マスマティクス誌で、それぞれレバレッジETFのリターンの経路依存性を数学的に証明した。結論は一文で要約できる——レバレッジ商品の長期リターンを決めるのは、開始価格と終了価格の差ではなく、その間の実現ボラティリティである。</p>
<p class="es">El nombre de este fenómeno es decaimiento de volatilidad, o decaimiento por reequilibrio. El mundo académico zanjó el asunto hace tiempo: Cheng y Madhavan (2009), en un artículo publicado en el Journal of Investment Management, y Avellaneda y Zhang (2010), en el SIAM Journal on Financial Mathematics, demostraron matemáticamente, cada uno por su lado, la dependencia de la trayectoria en los rendimientos de los ETF apalancados. La conclusión cabe en una frase: lo que determina el rendimiento a largo plazo de un producto apalancado no es la diferencia entre el precio inicial y el final, sino la volatilidad realizada en el camino.</p>
<p class="de">Der Name für dieses Phänomen ist Volatilitätszerfall oder Rebalancing-Zerfall. Die Wissenschaft hat die Frage längst geklärt — Cheng und Madhavan (2009) wiesen in einem im Journal of Investment Management veröffentlichten Aufsatz und Avellaneda und Zhang (2010) im SIAM Journal on Financial Mathematics jeweils mathematisch die Pfadabhängigkeit der Renditen gehebelter ETFs nach. Das Fazit passt in einen Satz: Was die langfristige Rendite eines gehebelten Produkts bestimmt, ist nicht die Differenz zwischen Start- und Endpreis, sondern die realisierte Volatilität auf dem Weg dorthin.</p>

<p class="ko">문제는 이 결론이 학술지 안에서만 머물지 않는다는 데 있다. 2021년 5월 비트코인이 하루 만에 30% 넘게 빠졌던 폭락장에서 바이낸스 레버리지 토큰 보유자들이 대거 항의했던 사건, 2024년 프로셰어스(현재 볼래틸리티 셰어스) BITX가 비트코인 현물 수익률 5.28%를 훌쩍 뛰어넘었다가도 구조적으로는 콘탱고에 잠식당하는 현상 — 이 모두가 같은 수식에서 나온다. 이 글은 그 수식이 무엇인지, 그리고 왜 트레이더들이 방향을 맞히고도 이 원칙을 지키지 못하는지를 다룬다.</p>
<p class="en">The problem is that this conclusion doesn't stay confined to academic journals. The May 2021 crash, when Bitcoin fell more than 30% in a single day and holders of Binance's leveraged tokens filed a wave of complaints; the 2024 case in which ProShares' (now Volatility Shares') BITX comfortably beat Bitcoin spot's 5.28% annual return, even as the same structure was quietly eaten away by futures contango — both trace back to the same formula. This piece is about what that formula actually is, and why traders keep failing to honor this discipline even when they get the direction exactly right.</p>
<p class="ja">問題は、この結論が学術誌の中だけにとどまらないという点だ。2021年5月、ビットコインが一日で30%超下落した暴落局面でバイナンスのレバレッジトークン保有者から大量の抗議が上がった件。2024年、プロシェアーズ(現ボラティリティ・シェアーズ)のBITXがビットコイン現物の年間5.28%上昇を大きく上回りながらも、同じ構造が先物のコンタンゴによって静かに蝕まれていた件——どちらも同じ数式に行き着く。本稿はその数式が何であるか、そしてなぜトレーダーが方向を正確に当てても、この原則を守れないのかを扱う。</p>
<p class="es">El problema es que esta conclusión no se queda encerrada en las revistas académicas. La caída de mayo de 2021, cuando Bitcoin cayó más del 30% en un solo día y los poseedores de los tokens apalancados de Binance protagonizaron una ola de quejas; el caso de 2024, en que el BITX de ProShares (hoy Volatility Shares) superó cómodamente el 5,28% de rentabilidad anual del Bitcoin al contado, mientras la misma estructura era erosionada silenciosamente por el contango de los futuros — ambos casos remiten a la misma fórmula. Este artículo trata sobre qué es exactamente esa fórmula, y por qué los traders siguen sin poder respetar esta disciplina incluso cuando aciertan la dirección exacta.</p>
<p class="de">Das Problem ist, dass dieses Fazit nicht in den Fachzeitschriften eingesperrt bleibt. Der Crash im Mai 2021, als Bitcoin an einem einzigen Tag um mehr als 30% einbrach und Halter von Binances gehebelten Token in Scharen Beschwerden einreichten; der Fall von 2024, in dem BITX von ProShares (heute Volatility Shares) die 5,28-prozentige Jahresrendite des Bitcoin-Spotmarkts deutlich übertraf, während dieselbe Struktur gleichzeitig still von der Futures-Contango aufgezehrt wurde — beide führen auf dieselbe Formel zurück. Dieser Beitrag behandelt, was diese Formel tatsächlich ist, und warum Trader diese Disziplin immer wieder nicht einhalten, selbst wenn sie die Richtung exakt richtig einschätzen.</p>

<h2 class="ko">레버리지 상품이 실제로 하는 일: 매일 리셋되는 배율</h2>
<h2 class="en">What Leveraged Products Actually Do: A Multiplier Reset Every Day</h2>
<h2 class="ja">レバレッジ商品が実際にしていること:毎日リセットされる倍率</h2>
<h2 class="es">Lo Que Realmente Hacen los Productos Apalancados: Un Multiplicador que se Reinicia Cada Día</h2>
<h2 class="de">Was gehebelte Produkte tatsächlich tun: Ein täglich zurückgesetzter Multiplikator</h2>

<p class="ko">2배 레버리지 토큰이 파는 약속은 단순하다 — '기초자산이 하루에 10% 오르면 토큰은 20% 오른다.' 이 약속은 정확히 지켜진다, 다만 '하루짜리' 약속이라는 단서가 붙는다. 배율은 매일 자정(또는 거래소가 정한 기준 시각)마다 리셋된다. 리셋 과정에서 발행사는 가격이 올랐으면 추가로 매수해 레버리지를 다시 목표치로 맞추고, 가격이 내렸으면 매도해 레버리지를 낮춘다 — '오르면 사고, 내리면 판다'는 리밸런싱이다. 문제는 이 리밸런싱이 매일 반복되면서 경로의존성을 만들어낸다는 데 있다.</p>
<p class="en">What a 2x leveraged token promises is simple: "if the underlying rises 10% in a day, the token rises 20%." That promise is kept exactly — with the caveat that it's a one-day promise. The multiplier resets every day, at midnight or whatever reference time the exchange sets. During that reset, the issuer buys more to push leverage back up to target if the price rose, and sells to bring leverage down if the price fell — a "buy high, sell low" rebalancing. The trouble is that this rebalancing, repeated daily, is exactly what creates path dependence.</p>
<p class="ja">2倍レバレッジトークンが約束することは単純だ——「原資産が1日に10%上がれば、トークンは20%上がる」。この約束は正確に守られる、ただし「1日限定」という条件付きだ。倍率は毎日、深夜0時(または取引所が定める基準時刻)にリセットされる。リセットの過程で発行体は、価格が上がっていればさらに買い増してレバレッジを目標値に戻し、価格が下がっていれば売却してレバレッジを下げる——「上がれば買い、下がれば売る」リバランスだ。問題は、このリバランスが毎日繰り返されることで経路依存性が生まれる点にある。</p>
<p class="es">Lo que promete un token apalancado 2x es simple: "si el subyacente sube un 10% en un día, el token sube un 20%". Esa promesa se cumple exactamente, con la salvedad de que es una promesa de un solo día. El multiplicador se reinicia cada día, a medianoche o en la hora de referencia que fije el exchange. Durante ese reinicio, el emisor compra más para devolver el apalancamiento al objetivo si el precio subió, y vende para reducirlo si el precio bajó: un reequilibrio de "comprar caro, vender barato". El problema es que este reequilibrio, repetido a diario, es precisamente lo que genera dependencia de la trayectoria.</p>
<p class="de">Was ein 2x-gehebeltes Token verspricht, ist einfach: "Steigt der Basiswert an einem Tag um 10%, steigt das Token um 20%." Dieses Versprechen wird exakt eingehalten — mit dem Vorbehalt, dass es sich um ein Ein-Tages-Versprechen handelt. Der Multiplikator wird jeden Tag zurückgesetzt, um Mitternacht oder zu dem vom Börsenplatz festgelegten Referenzzeitpunkt. Beim Reset kauft der Emittent bei gestiegenem Preis nach, um den Hebel wieder auf das Ziel zu bringen, und verkauft bei gefallenem Preis, um den Hebel zu senken — ein Rebalancing nach dem Prinzip "teuer kaufen, billig verkaufen". Das Problem ist, dass genau dieses täglich wiederholte Rebalancing die Pfadabhängigkeit erzeugt.</p>

<p class="ko">이 효과를 확인하는 가장 널리 인용되는 예시는 이렇다. 기초자산이 첫날 10% 오르고 다음날 10% 내리면, 이틀 뒤 기초자산은 100→110→99로 정확히 -1%가 된다. 그런데 2배 토큰은 같은 이틀 동안 100→120→96으로 움직여 -4%가 된다 — 산술적으로 기대할 법한 -2%(기초자산 -1%의 두 배)가 아니라 그 두 배인 -4%다. 3배 토큰이라면 100→130→91로 -9%가 되어, 기대치인 -3%의 세 배에 이른다. 기초자산은 겨우 1% 빠졌을 뿐인데, 레버리지 배율이 커질수록 손실은 훨씬 더 크게 벌어진다. 이것이 Cheng과 Madhavan이 수식으로 증명한, 변동성의 제곱에 비례해 커지는 감가다.</p>
<p class="en">The most widely cited illustration of the effect goes like this. If the underlying rises 10% on day one and falls 10% on day two, it ends up at 100 → 110 → 99 two days later — exactly -1%. A 2x token over the same two days moves 100 → 120 → 96, a -4% loss — not the -2% you'd arithmetically expect (twice the underlying's -1%), but double that, at -4%. A 3x token goes 100 → 130 → 91, a -9% loss, three times the -3% you'd expect. The underlying dropped only 1%, yet the loss widens far more sharply as the leverage multiple grows. This is the decay proportional to the square of volatility that Cheng and Madhavan proved mathematically.</p>
<p class="ja">この効果を確認する最も広く引用される例はこうだ。原資産が初日に10%上がり、翌日に10%下がると、2日後には原資産は100→110→99となり、ちょうど-1%になる。ところが2倍トークンは同じ2日間で100→120→96と動き、-4%になる——算術的に期待されるはずの-2%(原資産の-1%の2倍)ではなく、その倍の-4%だ。3倍トークンなら100→130→91で-9%となり、期待値である-3%の3倍に達する。原資産はわずか1%しか下がっていないのに、レバレッジ倍率が大きくなるほど損失ははるかに大きく開いていく。これがチェンとマダヴァンが数式で証明した、ボラティリティの2乗に比例して拡大する減価だ。</p>
<p class="es">El ejemplo más citado para verificar este efecto es el siguiente. Si el subyacente sube un 10% el primer día y baja un 10% el segundo, dos días después queda en 100 → 110 → 99, exactamente -1%. Un token 2x en esos mismos dos días se mueve 100 → 120 → 96, una pérdida del -4% — no el -2% que cabría esperar aritméticamente (el doble del -1% del subyacente), sino el doble de eso, -4%. Un token 3x llega a 100 → 130 → 91, una pérdida del -9%, tres veces el -3% esperado. El subyacente cayó solo un 1%, y aun así la pérdida se amplía mucho más cuanto mayor es el múltiplo de apalancamiento. Este es el decaimiento proporcional al cuadrado de la volatilidad que Cheng y Madhavan demostraron matemáticamente.</p>
<p class="de">Das am häufigsten zitierte Beispiel für diesen Effekt lautet so: Steigt der Basiswert am ersten Tag um 10% und fällt am zweiten Tag um 10%, landet er zwei Tage später bei 100 → 110 → 99 — genau -1%. Ein 2x-Token bewegt sich in denselben zwei Tagen von 100 → 120 → 96, ein Verlust von -4% — nicht die arithmetisch erwarteten -2% (das Doppelte der -1% des Basiswerts), sondern das Doppelte davon, -4%. Ein 3x-Token kommt auf 100 → 130 → 91, ein Verlust von -9%, das Dreifache der erwarteten -3%. Der Basiswert fiel nur um 1%, doch der Verlust weitet sich mit steigendem Hebel-Multiplikator weit stärker aus. Das ist der zum Quadrat der Volatilität proportionale Zerfall, den Cheng und Madhavan mathematisch nachgewiesen haben.</p>

<h2 class="ko">변동성 자체가 세금이다 — 방향이 맞아도 사라지는 돈</h2>
<h2 class="en">Volatility Itself Is a Tax — Money That Vanishes Even When the Direction Is Right</h2>
<h2 class="ja">ボラティリティそのものが税金だ——方向が当たっても消えるお金</h2>
<h2 class="es">La Volatilidad Misma Es un Impuesto — Dinero Que Desaparece Aunque la Dirección Sea Correcta</h2>
<h2 class="de">Volatilität selbst ist eine Steuer — Geld, das verschwindet, obwohl die Richtung stimmt</h2>

<p class="ko">위의 이틀짜리 예시를 열흘로 늘리면 감가의 크기가 훨씬 선명해진다. 비트코인이 하루는 10% 오르고 다음 날은 9.09% 내리는 패턴을 다섯 번 반복한다고 가정하자(10%와 9.09%를 짝지은 이유는 단순하다 — 1.10 × 0.9091 = 1.0000이어서, 이 두 날을 거치면 가격이 정확히 원래 자리로 돌아오기 때문이다). 열흘이 지나면 비트코인 가격은 처음과 정확히 같다. 그런데 같은 열흘 동안 3배 토큰은 1.30 × 0.7273 = 0.9455를 다섯 번 반복해 0.9455⁵ ≈ 0.7555가 된다 — 원금의 24.5%가 사라진다. 방향 예측은 완벽했다(비트코인이 결국 어디로도 가지 않을 것이라는 예측이 정확히 맞았다). 그런데도 계좌는 4분의 1가량 줄어 있다.</p>
<p class="en">Stretch the two-day example above to ten days and the scale of the decay becomes far clearer. Suppose Bitcoin rises 10% one day and falls 9.09% the next, repeating that pattern five times (10% and 9.09% are paired for a simple reason: 1.10 × 0.9091 = 1.0000, so after those two days the price lands back exactly where it started). Ten days later, Bitcoin's price is exactly what it was at the start. Yet over those same ten days, a 3x token repeats 1.30 × 0.7273 = 0.9455 five times, landing at 0.9455⁵ ≈ 0.7555 — 24.5% of the principal has vanished. The directional call was perfect (the prediction that Bitcoin would end up going nowhere was exactly right). The account is still down by roughly a quarter.</p>
<p class="ja">上の2日間の例を10日間に広げると、減価の大きさがはるかにはっきりする。ビットコインがある日10%上がり、翌日9.09%下がるパターンを5回繰り返すとしよう(10%と9.09%を組み合わせたのは単純な理由からだ——1.10×0.9091=1.0000となるため、この2日間を経ると価格はちょうど元の水準に戻る)。10日後、ビットコインの価格は最初とまったく同じになる。ところが同じ10日間で、3倍トークンは1.30×0.7273=0.9455を5回繰り返し、0.9455⁵≒0.7555になる——元本の24.5%が消える。方向の予測は完璧だった(ビットコインが結局どこにも行かないという予測がまさに的中していた)。それでも口座残高は4分の1ほど減っている。</p>
<p class="es">Si estiramos el ejemplo de dos días anterior a diez días, la magnitud del decaimiento se vuelve mucho más clara. Supongamos que Bitcoin sube un 10% un día y baja un 9,09% al siguiente, repitiendo ese patrón cinco veces (10% y 9,09% se emparejan por una razón simple: 1,10 × 0,9091 = 1,0000, así que tras esos dos días el precio regresa exactamente a donde empezó). Diez días después, el precio de Bitcoin es exactamente el mismo que al principio. Sin embargo, durante esos mismos diez días, un token 3x repite 1,30 × 0,7273 = 0,9455 cinco veces, quedando en 0,9455⁵ ≈ 0,7555 — ha desaparecido el 24,5% del capital. La predicción de dirección fue perfecta (acertar que Bitcoin terminaría sin ir a ninguna parte fue exactamente correcto). Y aun así la cuenta ha caído en torno a una cuarta parte.</p>
<p class="de">Streckt man das obige Zwei-Tage-Beispiel auf zehn Tage, wird das Ausmaß des Zerfalls weit deutlicher. Angenommen, Bitcoin steigt an einem Tag um 10% und fällt am nächsten um 9,09%, und dieses Muster wiederholt sich fünfmal (10% und 9,09% sind aus einem einfachen Grund gepaart: 1,10 × 0,9091 = 1,0000, sodass der Preis nach diesen zwei Tagen exakt zu seinem Ausgangspunkt zurückkehrt). Nach zehn Tagen steht der Bitcoin-Preis exakt dort, wo er begonnen hat. Doch im selben Zeitraum wiederholt ein 3x-Token 1,30 × 0,7273 = 0,9455 fünfmal und landet bei 0,9455⁵ ≈ 0,7555 — 24,5% des Kapitals sind verschwunden. Die Richtungseinschätzung war perfekt (die Vorhersage, dass Bitcoin am Ende nirgendwohin gehen würde, traf exakt zu). Das Konto ist trotzdem um rund ein Viertel geschrumpft.</p>

<div class="ko">
<svg viewBox="0 0 700 360" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">10일 시뮬레이션: 비트코인은 제자리, 3배 토큰은 −24.5%</text>
  <text x="20" y="42" fill="#71717a" font-size="10" font-family="sans-serif">가정: 매일 +10%/−9.09% 반복(비트코인 매 사이클 원점 복귀) · 3배 레버리지 토큰의 개념적 감가 곡선</text>
  <line x1="60" y1="162.7" x2="655" y2="162.7" stroke="#71717a" stroke-dasharray="4,4"/>
  <text x="76" y="156" fill="#a1a1aa" font-size="10" text-anchor="start" font-family="sans-serif">100(시작가)</text>
  <polyline points="70,162.7 128,133.3 186,162.7 244,133.3 302,162.7 360,133.3 418,162.7 476,133.3 534,162.7 592,133.3 650,162.7" fill="none" stroke="#60a5fa" stroke-width="2.5"/>
  <polyline points="70,162.7 128,74.7 186,178.7 244,95.5 302,193.8 360,115.2 418,208.1 476,133.7 534,221.6 592,151.3 650,234.4" fill="none" stroke="#f87171" stroke-width="2.5"/>
  <circle cx="650" cy="162.7" r="4.5" fill="#60a5fa"/>
  <text x="650" y="148" fill="#93c5fd" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">비트코인 100 (0%)</text>
  <circle cx="650" cy="234.4" r="4.5" fill="#f87171"/>
  <text x="650" y="252" fill="#f87171" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">3배 토큰 75.5 (−24.5%)</text>
  <text x="70" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 0</text>
  <text x="186" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 2</text>
  <text x="302" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 4</text>
  <text x="418" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 6</text>
  <text x="534" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 8</text>
  <text x="650" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 10</text>
  <circle cx="30" cy="305" r="5" fill="#60a5fa"/><text x="42" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">비트코인(현물)</text>
  <circle cx="180" cy="305" r="5" fill="#f87171"/><text x="192" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">3배 레버리지 토큰</text>
</svg>
<p class="ko" style="font-size:12px;color:#71717a;margin-top:-10px">※ 하루 +10%/−9.09% 반복(비트코인은 매 사이클 원점 복귀)을 가정한 3배 레버리지 토큰의 개념적 시뮬레이션이며, 수수료·펀딩비는 반영하지 않았습니다.</p>
</div>
<div class="en">
<svg viewBox="0 0 700 360" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">10-Day Simulation: Bitcoin Flat, 3x Token Down 24.5%</text>
  <text x="20" y="42" fill="#71717a" font-size="10" font-family="sans-serif">Assumes a repeating +10%/-9.09% daily cycle (Bitcoin returns to its starting point every cycle) · conceptual decay curve for a 3x leveraged token</text>
  <line x1="60" y1="162.7" x2="655" y2="162.7" stroke="#71717a" stroke-dasharray="4,4"/>
  <text x="76" y="156" fill="#a1a1aa" font-size="10" text-anchor="start" font-family="sans-serif">100 (start)</text>
  <polyline points="70,162.7 128,133.3 186,162.7 244,133.3 302,162.7 360,133.3 418,162.7 476,133.3 534,162.7 592,133.3 650,162.7" fill="none" stroke="#60a5fa" stroke-width="2.5"/>
  <polyline points="70,162.7 128,74.7 186,178.7 244,95.5 302,193.8 360,115.2 418,208.1 476,133.7 534,221.6 592,151.3 650,234.4" fill="none" stroke="#f87171" stroke-width="2.5"/>
  <circle cx="650" cy="162.7" r="4.5" fill="#60a5fa"/>
  <text x="650" y="148" fill="#93c5fd" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">Bitcoin 100 (0%)</text>
  <circle cx="650" cy="234.4" r="4.5" fill="#f87171"/>
  <text x="650" y="252" fill="#f87171" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">3x token 75.5 (−24.5%)</text>
  <text x="70" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 0</text>
  <text x="186" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 2</text>
  <text x="302" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 4</text>
  <text x="418" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 6</text>
  <text x="534" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 8</text>
  <text x="650" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 10</text>
  <circle cx="30" cy="305" r="5" fill="#60a5fa"/><text x="42" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">Bitcoin (spot)</text>
  <circle cx="180" cy="305" r="5" fill="#f87171"/><text x="192" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">3x leveraged token</text>
</svg>
<p class="en" style="font-size:12px;color:#71717a;margin-top:-10px">※ A conceptual simulation of a 3x leveraged token assuming a repeating +10%/-9.09% daily cycle (Bitcoin returns to its starting point every cycle); fees and funding costs are not included.</p>
</div>
<div class="ja">
<svg viewBox="0 0 700 360" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">10日間シミュレーション:ビットコインは横ばい、3倍トークンは−24.5%</text>
  <text x="20" y="42" fill="#71717a" font-size="10" font-family="sans-serif">前提:1日+10%/−9.09%の反復(ビットコインは各サイクルで元の水準に復帰)・3倍レバレッジトークンの概念的な減価曲線</text>
  <line x1="60" y1="162.7" x2="655" y2="162.7" stroke="#71717a" stroke-dasharray="4,4"/>
  <text x="76" y="156" fill="#a1a1aa" font-size="10" text-anchor="start" font-family="sans-serif">100(開始値)</text>
  <polyline points="70,162.7 128,133.3 186,162.7 244,133.3 302,162.7 360,133.3 418,162.7 476,133.3 534,162.7 592,133.3 650,162.7" fill="none" stroke="#60a5fa" stroke-width="2.5"/>
  <polyline points="70,162.7 128,74.7 186,178.7 244,95.5 302,193.8 360,115.2 418,208.1 476,133.7 534,221.6 592,151.3 650,234.4" fill="none" stroke="#f87171" stroke-width="2.5"/>
  <circle cx="650" cy="162.7" r="4.5" fill="#60a5fa"/>
  <text x="650" y="148" fill="#93c5fd" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">ビットコイン 100(0%)</text>
  <circle cx="650" cy="234.4" r="4.5" fill="#f87171"/>
  <text x="650" y="252" fill="#f87171" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">3倍トークン 75.5(−24.5%)</text>
  <text x="70" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 0</text>
  <text x="186" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 2</text>
  <text x="302" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 4</text>
  <text x="418" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 6</text>
  <text x="534" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 8</text>
  <text x="650" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Day 10</text>
  <circle cx="30" cy="305" r="5" fill="#60a5fa"/><text x="42" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">ビットコイン(現物)</text>
  <circle cx="180" cy="305" r="5" fill="#f87171"/><text x="192" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">3倍レバレッジトークン</text>
</svg>
<p class="ja" style="font-size:12px;color:#71717a;margin-top:-10px">※ 1日+10%/−9.09%の反復(ビットコインは各サイクルで元の水準に復帰)を仮定した3倍レバレッジトークンの概念的シミュレーションであり、手数料・ファンディング費用は反映していません。</p>
</div>
<div class="es">
<svg viewBox="0 0 700 360" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">Simulación de 10 Días: Bitcoin Plano, Token 3x Cae un 24,5%</text>
  <text x="20" y="42" fill="#71717a" font-size="10" font-family="sans-serif">Supone un ciclo diario repetido de +10%/-9,09% (Bitcoin vuelve a su punto de partida en cada ciclo) · curva conceptual de decaimiento de un token apalancado 3x</text>
  <line x1="60" y1="162.7" x2="655" y2="162.7" stroke="#71717a" stroke-dasharray="4,4"/>
  <text x="76" y="156" fill="#a1a1aa" font-size="10" text-anchor="start" font-family="sans-serif">100 (inicio)</text>
  <polyline points="70,162.7 128,133.3 186,162.7 244,133.3 302,162.7 360,133.3 418,162.7 476,133.3 534,162.7 592,133.3 650,162.7" fill="none" stroke="#60a5fa" stroke-width="2.5"/>
  <polyline points="70,162.7 128,74.7 186,178.7 244,95.5 302,193.8 360,115.2 418,208.1 476,133.7 534,221.6 592,151.3 650,234.4" fill="none" stroke="#f87171" stroke-width="2.5"/>
  <circle cx="650" cy="162.7" r="4.5" fill="#60a5fa"/>
  <text x="650" y="148" fill="#93c5fd" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">Bitcoin 100 (0%)</text>
  <circle cx="650" cy="234.4" r="4.5" fill="#f87171"/>
  <text x="650" y="252" fill="#f87171" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">Token 3x 75,5 (−24,5%)</text>
  <text x="70" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Día 0</text>
  <text x="186" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Día 2</text>
  <text x="302" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Día 4</text>
  <text x="418" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Día 6</text>
  <text x="534" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Día 8</text>
  <text x="650" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Día 10</text>
  <circle cx="30" cy="305" r="5" fill="#60a5fa"/><text x="42" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">Bitcoin (spot)</text>
  <circle cx="180" cy="305" r="5" fill="#f87171"/><text x="192" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">Token apalancado 3x</text>
</svg>
<p class="es" style="font-size:12px;color:#71717a;margin-top:-10px">※ Simulación conceptual de un token apalancado 3x asumiendo un ciclo diario repetido de +10%/-9,09% (Bitcoin vuelve a su punto de partida en cada ciclo); no se incluyen comisiones ni costes de financiación.</p>
</div>
<div class="de">
<svg viewBox="0 0 700 360" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="26" fill="#fafafa" font-size="13" font-weight="700" font-family="sans-serif">10-Tage-Simulation: Bitcoin unverändert, 3x-Token −24,5%</text>
  <text x="20" y="42" fill="#71717a" font-size="10" font-family="sans-serif">Annahme: sich wiederholender Tageszyklus von +10%/-9,09% (Bitcoin kehrt bei jedem Zyklus zum Ausgangspunkt zurück) · konzeptionelle Zerfallskurve eines 3x gehebelten Tokens</text>
  <line x1="60" y1="162.7" x2="655" y2="162.7" stroke="#71717a" stroke-dasharray="4,4"/>
  <text x="76" y="156" fill="#a1a1aa" font-size="10" text-anchor="start" font-family="sans-serif">100 (Start)</text>
  <polyline points="70,162.7 128,133.3 186,162.7 244,133.3 302,162.7 360,133.3 418,162.7 476,133.3 534,162.7 592,133.3 650,162.7" fill="none" stroke="#60a5fa" stroke-width="2.5"/>
  <polyline points="70,162.7 128,74.7 186,178.7 244,95.5 302,193.8 360,115.2 418,208.1 476,133.7 534,221.6 592,151.3 650,234.4" fill="none" stroke="#f87171" stroke-width="2.5"/>
  <circle cx="650" cy="162.7" r="4.5" fill="#60a5fa"/>
  <text x="650" y="148" fill="#93c5fd" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">Bitcoin 100 (0%)</text>
  <circle cx="650" cy="234.4" r="4.5" fill="#f87171"/>
  <text x="650" y="252" fill="#f87171" font-size="11" text-anchor="end" font-family="sans-serif" font-weight="700">3x-Token 75,5 (−24,5%)</text>
  <text x="70" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Tag 0</text>
  <text x="186" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Tag 2</text>
  <text x="302" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Tag 4</text>
  <text x="418" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Tag 6</text>
  <text x="534" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Tag 8</text>
  <text x="650" y="280" fill="#d4d4d8" font-size="10" text-anchor="middle" font-family="sans-serif">Tag 10</text>
  <circle cx="30" cy="305" r="5" fill="#60a5fa"/><text x="42" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">Bitcoin (Spot)</text>
  <circle cx="180" cy="305" r="5" fill="#f87171"/><text x="192" y="309" fill="#d4d4d8" font-size="12" font-family="sans-serif">3x gehebeltes Token</text>
</svg>
<p class="de" style="font-size:12px;color:#71717a;margin-top:-10px">※ Eine konzeptionelle Simulation eines 3x gehebelten Tokens unter der Annahme eines sich wiederholenden Tageszyklus von +10%/-9,09% (Bitcoin kehrt bei jedem Zyklus zu seinem Ausgangspunkt zurück); Gebühren und Finanzierungskosten sind nicht berücksichtigt.</p>
</div>

<p class="ko">비트코인은 역사상 실현 변동성이 연 50% 미만이었던 기간이 전체의 5%에 불과할 만큼 변동성이 큰 자산이다(Fidelity Digital Assets 분석). 연 변동성 50~100%대를 하루 단위로 환산하면(연율을 √365로 나누면) 일일 변동폭이 통상 2.5~5%대이고, 급락·급등 국면에서는 두 자릿수로 뛴다 — 위 시뮬레이션에 쓰인 10%/9.09% 오르내림은 비트코인에서 결코 극단적인 가정이 아니다. 이 차트에서 확인해야 할 건 방향이 아니라 궤적이다 — 같은 최종 지점에 도달하더라도 경로가 거칠수록 레버리지 상품의 감가는 커진다.</p>
<p class="en">Bitcoin is volatile enough that realized volatility below 50% annualized has occurred in only about 5% of its history (per Fidelity Digital Assets research). Converting an annualized volatility of 50–100% into a daily figure (dividing the annualized rate by √365) works out to a typical daily swing of roughly 2.5–5%, jumping into double digits during sharp crashes or rallies — meaning the 10%/9.09% swings used in the simulation above are hardly an extreme assumption for Bitcoin. What matters in this chart isn't the direction — it's the path. Even when two assets reach the same final point, the rougher the path, the larger a leveraged product's decay.</p>
<p class="ja">ビットコインは、実現ボラティリティが年率50%未満だった期間が全歴史のわずか5%に過ぎないほど変動の激しい資産だ(フィデリティ・デジタル・アセッツの分析による)。年率50~100%台のボラティリティを日次に換算すると(年率を√365で割ると)、通常の日次変動幅はおよそ2.5~5%台になり、急落・急騰局面では二桁に跳ね上がる——上のシミュレーションで用いた10%/9.09%の上下動は、ビットコインにおいて決して極端な仮定ではない。このチャートで確認すべきは方向ではなく軌跡だ——同じ最終地点にたどり着くとしても、経路が荒いほどレバレッジ商品の減価は大きくなる。</p>
<p class="es">Bitcoin es lo bastante volátil como para que una volatilidad realizada anualizada inferior al 50% se haya dado solo en cerca del 5% de su historia (según la investigación de Fidelity Digital Assets). Convertir una volatilidad anualizada del 50–100% a una cifra diaria (dividiendo la tasa anualizada entre √365) arroja una oscilación diaria típica de aproximadamente 2,5–5%, que salta a dos dígitos durante caídas o subidas bruscas — lo que significa que las oscilaciones del 10%/9,09% usadas en la simulación anterior no son en absoluto un supuesto extremo para Bitcoin. Lo que importa en este gráfico no es la dirección, sino la trayectoria. Aunque dos activos lleguen al mismo punto final, cuanto más accidentado sea el camino, mayor será el decaimiento de un producto apalancado.</p>
<p class="de">Bitcoin ist volatil genug, dass eine annualisierte realisierte Volatilität von unter 50% nur in etwa 5% seiner Geschichte vorkam (laut einer Analyse von Fidelity Digital Assets). Rechnet man eine annualisierte Volatilität von 50–100% auf einen Tageswert um (Division der Jahresrate durch √365), ergibt sich eine typische Tagesschwankung von etwa 2,5–5%, die bei scharfen Einbrüchen oder Rallyes in den zweistelligen Bereich springt — die in der obigen Simulation verwendeten Schwankungen von 10%/9,09% sind für Bitcoin also keineswegs eine extreme Annahme. Was in diesem Diagramm zählt, ist nicht die Richtung — sondern der Pfad. Selbst wenn zwei Werte denselben Endpunkt erreichen, gilt: Je ruppiger der Weg, desto größer der Zerfall eines gehebelten Produkts.</p>

<h2 class="ko">실제 사례: 2024년 BITX, 그리고 2021년 5월의 대혼란</h2>
<h2 class="en">Real Cases: BITX in 2024, and the Chaos of May 2021</h2>
<h2 class="ja">実際の事例:2024年のBITX、そして2021年5月の大混乱</h2>
<h2 class="es">Casos Reales: BITX en 2024, y el Caos de Mayo de 2021</h2>
<h2 class="de">Reale Fälle: BITX 2024 und das Chaos vom Mai 2021</h2>

<p class="ko">이 수식은 이론에서 끝나지 않는다. 2024년 비트코인 현물은 연간 5.28% 상승에 그쳤지만, 선물 기반 2배 상품인 볼래틸리티 셰어스의 BITX는 이 소폭 상승을 레버리지로 크게 웃도는 수익을 냈다 — 방향이 맞았고 상대적으로 변동성이 관리된 구간에서는 레버리지가 유리하게 작동한다는 걸 보여준 사례다. 그런데 바로 이 사례의 이면에 함정이 있다. BITX는 매일 목표 배율을 재설정하는 구조인 데다, 선물 콘탱고(만기가 먼 선물이 더 비싸게 거래되는 현상)로 인한 롤 비용까지 얹힌다. 즉 같은 상품이 방향이 맞고 변동성이 낮을 땐 기대 이상으로 뛰지만, 가격이 오르내리길 반복하거나 변동성이 커지는 순간 정확히 같은 메커니즘이 반대로 작동해 손실을 부풀린다.</p>
<p class="en">This formula doesn't stay theoretical. In 2024, Bitcoin spot rose only 5.28% for the year, yet Volatility Shares' BITX, a futures-based 2x product, delivered a leveraged return that comfortably outpaced that modest gain — a case showing that leverage works in your favor when the direction is right and volatility is relatively contained. But the trap is hiding behind that very case. BITX resets its target multiple daily, and on top of that carries roll costs from futures contango (where longer-dated futures trade at a premium). The same structure that jumps beyond expectations when direction is right and volatility is low works in exact reverse — inflating losses — the moment prices swing back and forth or volatility rises.</p>
<p class="ja">この数式は理論だけにとどまらない。2024年、ビットコイン現物は年間5.28%の上昇にとどまったが、先物ベースの2倍商品であるボラティリティ・シェアーズのBITXは、この小幅な上昇をレバレッジで大きく上回るリターンを出した——方向が当たり、ボラティリティが比較的抑えられた局面ではレバレッジが有利に働くことを示した事例だ。ところが、まさにこの事例の裏に罠がある。BITXは毎日目標倍率を再設定する構造であるうえ、先物のコンタンゴ(期先の先物がより高く取引される現象)によるロールコストも上乗せされる。つまり、方向が当たりボラティリティが低いときには期待以上に跳ねる同じ商品が、価格が上下動を繰り返したりボラティリティが高まったりした瞬間、まったく同じメカニズムが逆方向に作用して損失を膨らませる。</p>
<p class="es">Esta fórmula no se queda en la teoría. En 2024, el Bitcoin al contado subió solo un 5,28% en el año, pero el BITX de Volatility Shares, un producto 2x basado en futuros, entregó un rendimiento apalancado que superó cómodamente esa modesta subida — un caso que muestra que el apalancamiento funciona a favor cuando la dirección es correcta y la volatilidad está relativamente contenida. Pero la trampa se esconde justo detrás de ese mismo caso. BITX reinicia su múltiplo objetivo cada día y, además, arrastra costes de rollover por el contango de los futuros (cuando los futuros de vencimiento más lejano cotizan más caros). Es decir, la misma estructura que salta por encima de lo esperado cuando la dirección es correcta y la volatilidad es baja funciona exactamente al revés —inflando las pérdidas— en el momento en que el precio oscila de un lado a otro o la volatilidad aumenta.</p>
<p class="de">Diese Formel bleibt nicht in der Theorie stecken. 2024 stieg Bitcoin am Spotmarkt im Jahresverlauf nur um 5,28%, doch BITX von Volatility Shares, ein futuresbasiertes 2x-Produkt, lieferte eine gehebelte Rendite, die diesen bescheidenen Zuwachs deutlich übertraf — ein Fall, der zeigt, dass Hebel zugunsten des Anlegers wirkt, wenn die Richtung stimmt und die Volatilität relativ gebändigt ist. Doch genau hinter diesem Fall lauert die Falle. BITX setzt sein Zielmultiplikat täglich zurück und trägt obendrein Rollkosten durch Futures-Contango (bei dem länger laufende Futures teurer gehandelt werden). Dieselbe Struktur, die über die Erwartungen hinausschießt, wenn die Richtung stimmt und die Volatilität niedrig ist, wirkt in exakt umgekehrter Richtung — Verluste aufblähend —, sobald die Preise hin- und herpendeln oder die Volatilität steigt.</p>

<p class="ko">2021년 5월 19일 비트코인이 하루 만에 30% 넘게 급락했던 날, 바이낸스 레버리지 토큰(BTCUP/BTCDOWN 등) 보유자들 사이에서 대혼란이 벌어졌다. 당시 코인데스크 보도에 따르면 다수 트레이더가 극단적 변동성 구간에서 리밸런싱이 지연되거나 예상과 다르게 체결되며 손실이 눈덩이처럼 불어났다고 항의했다. 바이낸스 레버리지 토큰은 평소엔 1.5~3배(BTCDOWN의 경우 1.25~4배) 목표 범위 안에서 정기적으로 리밸런싱하지 않고 '필요할 때만'(주로 극단적 변동성 구간에) 리밸런싱하도록 설계돼 있는데, 이 구조 자체가 급락장에서는 감가를 지연시켰다가 한 번에 몰아서 반영하는 결과를 낳는다. 여기에 연 3.65%(하루 약 0.01%)의 운용보수까지 방향과 무관하게 매일 꾸준히 깎여나간다.</p>
<p class="en">On May 19, 2021, when Bitcoin dropped more than 30% in a single day, chaos broke out among holders of Binance's leveraged tokens (BTCUP/BTCDOWN and others). According to CoinDesk's coverage at the time, many traders complained that rebalancing was delayed or executed differently than expected during the extreme volatility, snowballing their losses. Binance's leveraged tokens are designed to rebalance not on a regular schedule within their normal 1.5x–3x target range (1.25x–4x for BTCDOWN), but only "as needed" — mainly during periods of extreme volatility — and that very structure tends to delay decay during a crash and then dump it all at once. On top of that, a 3.65% annual management fee (roughly 0.01% per day) is steadily deducted every day, regardless of direction.</p>
<p class="ja">2021年5月19日、ビットコインが一日で30%超急落した日、バイナンスのレバレッジトークン(BTCUP/BTCDOWNなど)保有者の間で大混乱が起きた。当時のコインデスクの報道によれば、多くのトレーダーが、極端なボラティリティ局面でリバランスが遅れたり想定と異なる形で執行されたりして損失が雪だるま式に膨らんだと訴えた。バイナンスのレバレッジトークンは通常、1.5~3倍(BTCDOWNの場合は1.25~4倍)の目標範囲内で定期的にリバランスするのではなく、「必要なときだけ」(主に極端なボラティリティ局面で)リバランスするよう設計されており、この構造自体が急落局面では減価を先送りしたうえで一気に反映させる結果を生む。これに加えて、年3.65%(1日あたり約0.01%)の運用報酬が、方向とは無関係に毎日着実に差し引かれていく。</p>
<p class="es">El 19 de mayo de 2021, cuando Bitcoin cayó más de un 30% en un solo día, se desató el caos entre los poseedores de los tokens apalancados de Binance (BTCUP/BTCDOWN y otros). Según la cobertura de CoinDesk en su momento, muchos traders se quejaron de que el reequilibrio se retrasaba o se ejecutaba de forma distinta a la esperada durante la volatilidad extrema, haciendo que las pérdidas crecieran como una bola de nieve. Los tokens apalancados de Binance están diseñados para reequilibrarse no de forma periódica dentro de su rango objetivo habitual de 1,5x–3x (1,25x–4x para BTCDOWN), sino solo "cuando es necesario" —principalmente durante períodos de volatilidad extrema—, y esa misma estructura tiende a retrasar el decaimiento durante una caída para después reflejarlo todo de golpe. A esto se suma una comisión de gestión anual del 3,65% (aproximadamente un 0,01% diario) que se descuenta constantemente cada día, sin importar la dirección.</p>
<p class="de">Am 19. Mai 2021, als Bitcoin an einem einzigen Tag um mehr als 30% einbrach, brach unter den Haltern von Binances gehebelten Token (BTCUP/BTCDOWN und andere) Chaos aus. Laut damaliger Berichterstattung von CoinDesk beschwerten sich viele Trader, dass sich das Rebalancing während der extremen Volatilität verzögerte oder anders als erwartet ausgeführt wurde, wodurch sich ihre Verluste lawinenartig auftürmten. Binances gehebelte Token sind so konzipiert, dass sie innerhalb ihrer üblichen Zielspanne von 1,5x–3x (1,25x–4x bei BTCDOWN) nicht routinemäßig, sondern nur "bei Bedarf" rebalancen — vor allem in Phasen extremer Volatilität —, und genau diese Struktur neigt dazu, den Zerfall während eines Crashs zu verzögern und ihn dann auf einen Schlag nachzuholen. Hinzu kommt eine jährliche Verwaltungsgebühr von 3,65% (etwa 0,01% pro Tag), die unabhängig von der Richtung Tag für Tag stetig abgezogen wird.</p>

<p class="ko">두 사례를 나란히 놓으면 패턴이 보인다. 방향이 맞고 변동성이 관리된 국면에서 레버리지 상품은 보유자에게 보상을 주지만, 그 보상은 '이 상품을 오래 들고 있어도 안전하다'는 착각을 함께 심어준다. 그리고 바로 다음 국면 — 방향은 여전히 맞을 수 있지만 변동성이 커지거나 가격이 잠시 반대로 튀는 국면 — 에서 같은 상품이 정확히 같은 메커니즘으로 원금을 갉아먹는다.</p>
<p class="en">Line the two cases up side by side and a pattern emerges. When direction is right and volatility is contained, a leveraged product rewards its holder — but that reward also plants the illusion that holding the product for a long time is safe. And in the very next regime — direction still possibly right, but volatility rising or price briefly whipsawing — the same product, through the exact same mechanism, eats into the principal.</p>
<p class="ja">この2つの事例を並べてみるとパターンが見えてくる。方向が当たり、ボラティリティが抑えられている局面では、レバレッジ商品は保有者に報酬を与える。しかしその報酬は同時に「この商品は長く持っていても安全だ」という錯覚を植え付ける。そして次の局面——方向は依然として当たっているかもしれないが、ボラティリティが高まったり価格が一時的に逆に振れたりする局面——で、まったく同じメカニズムによって同じ商品が元本を蝕んでいく。</p>
<p class="es">Al poner ambos casos uno al lado del otro, aparece un patrón. Cuando la dirección es correcta y la volatilidad está contenida, un producto apalancado recompensa a quien lo mantiene — pero esa recompensa también siembra la ilusión de que mantener el producto durante mucho tiempo es seguro. Y en el régimen siguiente —la dirección puede seguir siendo correcta, pero la volatilidad aumenta o el precio da un latigazo momentáneo en sentido contrario— el mismo producto, mediante exactamente el mismo mecanismo, corroe el capital.</p>
<p class="de">Stellt man beide Fälle nebeneinander, zeigt sich ein Muster. Stimmt die Richtung und ist die Volatilität gebändigt, belohnt ein gehebeltes Produkt seinen Halter — doch diese Belohnung sät zugleich die Illusion, das Produkt lange zu halten sei sicher. Und im nächsten Regime — die Richtung mag weiterhin stimmen, doch die Volatilität steigt oder der Preis schlägt kurzzeitig in die Gegenrichtung aus — frisst dasselbe Produkt über exakt denselben Mechanismus das Kapital auf.</p>

<h2 class="ko">왜 이 원칙은 실전에서 지키기 어려운가</h2>
<h2 class="en">Why This Principle Is Hard to Follow in Practice</h2>
<h2 class="ja">なぜこの原則は実践で守りにくいのか</h2>
<h2 class="es">Por Qué Este Principio Es Difícil de Seguir en la Práctica</h2>
<h2 class="de">Warum dieses Prinzip in der Praxis schwer einzuhalten ist</h2>

<p class="ko">'레버리지 상품은 장기 보유하지 마라'는 조언은 이미 업계 표준 문구에 가깝다. 바이낸스를 비롯한 대부분의 거래소가 레버리지 토큰 상품 설명 페이지에 이 경고를 명시한다. 그런데도 실제로 이 원칙이 무너지는 지점은 트레이더가 방향을 틀렸을 때가 아니라, 방향을 맞혔을 때다. 3배 롱 토큰을 매수한 뒤 비트코인이 실제로 올랐다면, 트레이더는 자신의 판단이 옳았다는 확인을 받는다. 이 확인은 '그러니 계속 들고 있어도 된다'는 결론으로 자연스럽게 이어진다 — 그러나 실제로 검증된 것은 방향에 대한 판단이지, 그 판단을 레버리지 상품으로 오래 표현해도 되는지에 대한 판단이 아니다. 두 질문은 겉보기엔 하나처럼 보이지만 수학적으로는 완전히 다른 질문이다.</p>
<p class="en">"Don't hold leveraged products long-term" is close to a standard industry warning by now. Binance and most other exchanges spell it out right on their leveraged token product pages. And yet the point where this principle actually breaks down in practice isn't when a trader gets the direction wrong — it's when they get it right. Buy a 3x long token and watch Bitcoin actually rise, and the trader receives confirmation that their call was correct. That confirmation flows naturally into the conclusion, "so it's fine to keep holding" — but what was actually validated was the directional call, not the separate question of whether it's fine to express that call through a leveraged product for a long time. The two questions look like one on the surface, but they are mathematically entirely different.</p>
<p class="ja">「レバレッジ商品は長期保有するな」という助言は、すでに業界標準の文言に近い。バイナンスをはじめとするほとんどの取引所が、レバレッジトークンの商品説明ページにこの警告を明記している。それでも実際にこの原則が崩れるのは、トレーダーが方向を外したときではなく、方向を当てたときだ。3倍ロングトークンを買った後、実際にビットコインが上がれば、トレーダーは自分の判断が正しかったという確認を得る。この確認は「だから持ち続けてもいい」という結論へと自然につながる——しかし実際に検証されたのは方向についての判断であって、その判断をレバレッジ商品で長く表現し続けてよいかという判断ではない。2つの問いは見た目には1つに見えるが、数学的にはまったく別の問いだ。</p>
<p class="es">"No mantengas productos apalancados a largo plazo" está ya cerca de ser una advertencia estándar de la industria. Binance y la mayoría de los exchanges lo dejan claro en las propias páginas de descripción de sus tokens apalancados. Y sin embargo, el punto donde este principio realmente se rompe en la práctica no es cuando un trader se equivoca de dirección, sino cuando acierta. Compra un token largo 3x y observa que Bitcoin realmente sube, y el trader recibe la confirmación de que su llamada fue correcta. Esa confirmación fluye de forma natural hacia la conclusión "entonces está bien seguir manteniéndolo" — pero lo que realmente se validó fue el acierto direccional, no la pregunta separada de si está bien expresar ese acierto mediante un producto apalancado durante mucho tiempo. Las dos preguntas parecen una sola en la superficie, pero matemáticamente son completamente distintas.</p>
<p class="de">"Gehebelte Produkte nicht langfristig halten" ist inzwischen fast eine Standardwarnung der Branche. Binance und die meisten anderen Börsen führen sie explizit auf den Produktseiten ihrer gehebelten Token auf. Und doch bricht dieses Prinzip in der Praxis genau dort zusammen, wo der Trader nicht die falsche, sondern die richtige Richtung erwischt hat. Kauft man ein 3x-Long-Token und Bitcoin steigt tatsächlich, erhält der Trader die Bestätigung, dass seine Einschätzung richtig war. Diese Bestätigung mündet ganz natürlich in die Schlussfolgerung "also kann ich es weiter halten" — validiert wurde aber tatsächlich nur die Richtungseinschätzung, nicht die davon getrennte Frage, ob es in Ordnung ist, diese Einschätzung über einen längeren Zeitraum mit einem gehebelten Produkt auszudrücken. Die beiden Fragen wirken an der Oberfläche wie eine einzige, sind mathematisch aber vollkommen verschieden.</p>

<p class="ko">여기서 작동하는 심리적 메커니즘은 확신과 상품 적합성을 혼동하는 것이다. 트레이더는 '내가 맞았다'는 사실이 '이 도구를 계속 써도 좋다'는 근거가 된다고 느낀다. 그러나 레버리지 토큰의 감가는 방향이 맞고 틀리고와 무관하게, 오직 경로의 거칠기에서만 발생한다. 방향이 맞은 상태에서 발생하는 손실은 특히 더 받아들이기 어렵다 — 손실이 나면 원인을 외부(변동성)가 아니라 '조금만 더 버텼어야 했는데'라는 자기 서사로 돌리게 되고, 이는 다음번에도 같은 상품을 같은 방식으로 오래 들고 있게 만드는 고리를 만든다. 결국 이 원칙이 실전에서 지켜지지 않는 이유는 정보 부족이 아니라, 방향이 맞았을 때 느끼는 확신이 정확히 감가가 누적되는 그 구간에서 보유 기간을 늘리도록 유혹하기 때문이다.</p>
<p class="en">The psychological mechanism at work here is confusing conviction with product suitability. A trader feels that the fact "I was right" becomes evidence that "it's fine to keep using this tool." But a leveraged token's decay has nothing to do with whether the direction was right or wrong — it comes purely from how rough the path was. Losses that occur even when direction was right are especially hard to accept — instead of attributing them to an external factor (volatility), traders default to a self-narrative of "I just should have held on a little longer," which forms a loop that leads to holding the same product the same way for a long time the next round too. In the end, this principle fails not for lack of information, but because the very conviction a trader feels after getting the direction right is exactly what tempts them to extend the holding period right into the zone where decay accumulates.</p>
<p class="ja">ここで働く心理的メカニズムは、確信と商品の適合性を混同することだ。トレーダーは「自分が正しかった」という事実が「この道具を使い続けていい」という根拠になると感じる。しかしレバレッジトークンの減価は、方向が合っていたか外れていたかとは無関係に、経路の荒さだけから生じる。方向が合っていた状態で発生する損失は、特に受け入れがたい——損失が出ると、原因を外部要因(ボラティリティ)ではなく「もう少し持ちこたえるべきだった」という自己物語に帰属させてしまい、これが次回も同じ商品を同じように長く持ち続けさせるループを作る。結局、この原則が実践で守られない理由は情報不足ではなく、方向が当たったときに感じる確信こそが、まさに減価が蓄積するその局面で保有期間を延ばすよう誘惑するからだ。</p>
<p class="es">El mecanismo psicológico que opera aquí es confundir la convicción con la idoneidad del producto. El trader siente que el hecho de "haber acertado" se convierte en evidencia de que "está bien seguir usando esta herramienta". Pero el decaimiento de un token apalancado no tiene nada que ver con si la dirección fue correcta o no — proviene puramente de lo accidentado que fue el camino. Las pérdidas que ocurren incluso cuando la dirección fue correcta son especialmente difíciles de aceptar: en lugar de atribuirlas a un factor externo (la volatilidad), los traders recurren por defecto a una autonarrativa de "debería haber aguantado un poco más", lo que forma un bucle que lleva a mantener el mismo producto de la misma manera durante mucho tiempo también la próxima vez. Al final, este principio falla no por falta de información, sino porque la propia convicción que siente un trader tras acertar la dirección es exactamente lo que lo tienta a extender el período de tenencia justo hacia la zona donde el decaimiento se acumula.</p>
<p class="de">Der psychologische Mechanismus dahinter ist die Verwechslung von Überzeugung mit Produkteignung. Der Trader empfindet die Tatsache, "ich lag richtig", als Beleg dafür, dass "es in Ordnung ist, dieses Instrument weiter zu nutzen". Doch der Zerfall eines gehebelten Tokens hat nichts damit zu tun, ob die Richtung stimmte oder nicht — er entsteht ausschließlich aus der Rauheit des Pfads. Verluste, die trotz richtiger Richtung entstehen, sind besonders schwer zu akzeptieren — statt sie einem externen Faktor (der Volatilität) zuzuschreiben, greifen Trader standardmäßig zur Selbsterzählung "ich hätte nur noch etwas länger durchhalten müssen", was eine Schleife bildet, die dazu führt, dasselbe Produkt beim nächsten Mal wieder auf dieselbe Weise lange zu halten. Am Ende scheitert dieses Prinzip in der Praxis nicht an fehlender Information, sondern daran, dass genau die Überzeugung, die man nach einer richtigen Richtungseinschätzung verspürt, dazu verführt, die Haltedauer exakt in die Zone hinein zu verlängern, in der sich der Zerfall aufsummiert.</p>

<h2 class="ko">그래서 실전에서 어떻게 다르게 해야 하는가</h2>
<h2 class="en">So What Should You Actually Do Differently</h2>
<h2 class="ja">では実践で何を変えるべきか</h2>
<h2 class="es">Entonces Qué Deberías Hacer Realmente Distinto</h2>
<h2 class="de">Was man also tatsächlich anders machen sollte</h2>

<p class="ko">결론은 단순하지만 실행은 별개의 문제다. 첫째, 레버리지 토큰·레버리지 ETF는 보유 기간을 사전에 정해두고 진입해야 한다 — 하루 안에 청산하는 데이트레이딩 도구로 취급하거나, 길어도 실현 변동성이 낮게 유지되는 짧은 구간으로 한정해야 한다. '방향에 대한 확신이 강해졌다'는 이유로 보유 기간을 늘리는 건 정확히 이 글이 설명한 함정에 스스로 걸어 들어가는 것이다. 둘째, 방향에 대한 베팅과 레버리지 구조에 대한 베팅을 분리해야 한다 — 방향에 확신이 있다면 무기한 보유가 가능한 현물이나 무기한 선물 포지션(다만 펀딩비는 별도로 계산)으로 표현하고, 레버리지 토큰은 짧은 구간의 변동성이 낮을 것이라는 별도의 확신이 있을 때만 얹는 도구로 써야 한다.</p>
<p class="en">The conclusion is simple, but executing it is a separate matter. First, enter leveraged tokens and leveraged ETFs with a holding period decided in advance — treat them as day-trading tools to be closed within a single day, or at most confine them to short windows where realized volatility stays low. Extending the holding period because "conviction about the direction has gotten stronger" is walking straight into the exact trap this piece describes. Second, separate the directional bet from the bet on the leveraged structure itself — if you have conviction on direction, express it through spot or a perpetual futures position that can be held indefinitely (accounting separately for funding costs), and use leveraged tokens only as an add-on for the times you have a distinct conviction that near-term volatility will stay low.</p>
<p class="ja">結論は単純だが、実行はまた別の問題だ。第一に、レバレッジトークン・レバレッジETFは保有期間をあらかじめ決めてから建てるべきだ——1日以内に手仕舞うデイトレード用の道具として扱うか、長くても実現ボラティリティが低く保たれる短い区間に限定する。「方向への確信が強まった」という理由で保有期間を延ばすのは、まさに本稿が説明した罠に自ら足を踏み入れることに等しい。第二に、方向に対する賭けとレバレッジ構造に対する賭けを切り分けるべきだ——方向に確信があるなら、無期限に保有できる現物か無期限先物ポジション(ただしファンディング費用は別途計算)で表現し、レバレッジトークンは短期のボラティリティが低いという別個の確信があるときだけ上乗せする道具として使う。</p>
<p class="es">La conclusión es simple, pero ejecutarla es otro asunto. Primero, entra en tokens apalancados y ETF apalancados con un período de tenencia decidido de antemano — trátalos como herramientas de day trading para cerrar en un solo día, o como mucho confínalos a ventanas cortas donde la volatilidad realizada se mantenga baja. Extender el período de tenencia porque "la convicción sobre la dirección se ha reforzado" es caminar directamente hacia la trampa que describe este artículo. Segundo, separa la apuesta sobre la dirección de la apuesta sobre la estructura apalancada en sí — si tienes convicción sobre la dirección, exprésala mediante spot o una posición de futuros perpetuos que puedas mantener indefinidamente (contabilizando por separado los costes de financiación), y usa los tokens apalancados solo como un añadido para los momentos en que tengas una convicción distinta de que la volatilidad a corto plazo se mantendrá baja.</p>
<p class="de">Das Fazit ist einfach, die Umsetzung eine andere Sache. Erstens sollte man in gehebelte Token und gehebelte ETFs mit einer im Voraus festgelegten Haltedauer einsteigen — sie als Daytrading-Instrumente behandeln, die noch am selben Tag glattgestellt werden, oder sie höchstens auf kurze Zeitfenster beschränken, in denen die realisierte Volatilität niedrig bleibt. Die Haltedauer zu verlängern, weil "die Überzeugung zur Richtung stärker geworden ist", bedeutet, genau in die in diesem Beitrag beschriebene Falle zu laufen. Zweitens sollte man die Wette auf die Richtung von der Wette auf die gehebelte Struktur selbst trennen — bei Überzeugung zur Richtung sollte man diese über Spot oder eine unbefristet haltbare Perpetual-Futures-Position ausdrücken (Finanzierungskosten separat berücksichtigt), und gehebelte Token nur dann als Ergänzung einsetzen, wenn eine eigenständige Überzeugung besteht, dass die kurzfristige Volatilität niedrig bleiben wird.</p>

<p class="ko">셋째, 실현 변동성 자체를 하나의 신호로 취급해야 한다. 최근 며칠간의 일일 변동폭이 커지고 있다면, 방향에 대한 판단이 아무리 확고해도 레버리지 상품의 감가 속도는 그 변동성의 제곱에 비례해 빨라진다는 사실을 <a href="/blog/position-sizing-bet-conviction-not-money.php">포지션 크기</a>와 연결지어야 한다. 이는 <a href="/blog/kelly-criterion-trap.php">켈리 공식이 계산해 준 숫자를 그대로 걸면 안 되는 이유</a>와도 같은 논리를 공유한다 — 포지션 크기를 확신의 크기가 아니라 감당 가능한 손실로 정해야 한다는 원칙은, 레버리지 상품에서는 감당 가능한 '변동성 노출'로 다시 번역돼야 한다. 방향을 맞히는 재능과 레버리지 구조에서 살아남는 규율은 서로 다른 근육이며, 전자가 뛰어나다고 후자가 저절로 따라오지는 않는다.</p>
<p class="en">Third, treat realized volatility itself as a signal. If the daily swing over the past few days is widening, connect that fact — that a leveraged product's decay accelerates in proportion to the square of that volatility, no matter how solid your directional call is — to your actual <a href="/blog/position-sizing-bet-conviction-not-money.php">position size</a>. This shares the same logic as <a href="/blog/kelly-criterion-trap.php">why you shouldn't bet what the Kelly criterion tells you to</a> — the principle that position size should be set by tolerable loss rather than the strength of conviction has to be re-translated, for leveraged products, into tolerable "volatility exposure." The talent for calling direction and the discipline for surviving a leveraged structure are different muscles, and being good at the former doesn't automatically bring the latter along with it.</p>
<p class="ja">第三に、実現ボラティリティそのものを一つのシグナルとして扱うべきだ。直近数日の日次変動幅が拡大しているなら、方向についての判断がどれほど確固たるものであっても、レバレッジ商品の減価速度はそのボラティリティの2乗に比例して速まるという事実を、実際の<a href="/blog/position-sizing-bet-conviction-not-money.php">ポジションサイズ</a>と結びつけるべきだ。これは<a href="/blog/kelly-criterion-trap.php">ケリー基準が計算した数字をそのまま賭けてはいけない理由</a>とも同じ論理を共有している——ポジションサイズは確信の大きさではなく耐えられる損失で決めるべきという原則は、レバレッジ商品においては耐えられる「ボラティリティ・エクスポージャー」へと翻訳し直す必要がある。方向を当てる才能とレバレッジ構造の中で生き残る規律は別の筋肉であり、前者に優れているからといって後者が自動的についてくるわけではない。</p>
<p class="es">Tercero, trata la volatilidad realizada misma como una señal. Si la oscilación diaria de los últimos días se está ampliando, conecta ese hecho —que el decaimiento de un producto apalancado se acelera en proporción al cuadrado de esa volatilidad, sin importar cuán sólida sea tu llamada direccional— con tu <a href="/blog/position-sizing-bet-conviction-not-money.php">tamaño de posición</a> real. Esto comparte la misma lógica que <a href="/blog/kelly-criterion-trap.php">por qué no deberías apostar lo que te dice el criterio de Kelly</a> — el principio de que el tamaño de la posición debe fijarse según la pérdida tolerable y no según la fuerza de la convicción tiene que traducirse, en los productos apalancados, en una "exposición a la volatilidad" tolerable. El talento para acertar la dirección y la disciplina para sobrevivir a una estructura apalancada son músculos distintos, y ser bueno en el primero no trae automáticamente consigo el segundo.</p>
<p class="de">Drittens sollte man die realisierte Volatilität selbst als Signal behandeln. Weitet sich die Tagesschwankung der letzten Tage aus, muss man die Tatsache — dass sich der Zerfall eines gehebelten Produkts proportional zum Quadrat dieser Volatilität beschleunigt, ganz gleich wie solide die Richtungseinschätzung ist — mit der tatsächlichen <a href="/blog/position-sizing-bet-conviction-not-money.php">Positionsgröße</a> verknüpfen. Das folgt derselben Logik wie die Frage, <a href="/blog/kelly-criterion-trap.php">warum man nicht setzen sollte, was das Kelly-Kriterium vorschlägt</a> — das Prinzip, dass die Positionsgröße durch den tragbaren Verlust und nicht durch die Stärke der Überzeugung bestimmt werden sollte, muss bei gehebelten Produkten in eine tragbare "Volatilitätsexposition" übersetzt werden. Das Talent, die Richtung richtig einzuschätzen, und die Disziplin, eine gehebelte Struktur zu überleben, sind unterschiedliche Muskeln — in Ersterem gut zu sein, bringt Letzteres nicht automatisch mit sich.</p>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: Cheng, M. &amp; Madhavan, A. (2009), "The Dynamics of Leveraged and Inverse Exchange-Traded Funds", Journal of Investment Management, 7(4). Avellaneda, M. &amp; Zhang, S. (2010), "Path-Dependence of Leveraged ETF Returns", SIAM Journal on Financial Mathematics, 1, 586-603. CoinDesk (2021.5.27), "Mayhem in Binance Leveraged Tokens During Crypto Crash Leaves Traders Fuming". Fidelity Digital Assets, "A Closer Look at Bitcoin's Volatility". Binance Support, "Binance Leveraged Tokens Trading Rules".</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Cheng, M. &amp; Madhavan, A. (2009), "The Dynamics of Leveraged and Inverse Exchange-Traded Funds", Journal of Investment Management, 7(4). Avellaneda, M. &amp; Zhang, S. (2010), "Path-Dependence of Leveraged ETF Returns", SIAM Journal on Financial Mathematics, 1, 586-603. CoinDesk (May 27, 2021), "Mayhem in Binance Leveraged Tokens During Crypto Crash Leaves Traders Fuming". Fidelity Digital Assets, "A Closer Look at Bitcoin's Volatility". Binance Support, "Binance Leveraged Tokens Trading Rules".</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: Cheng, M. &amp; Madhavan, A. (2009), "The Dynamics of Leveraged and Inverse Exchange-Traded Funds", Journal of Investment Management, 7(4)。Avellaneda, M. &amp; Zhang, S. (2010), "Path-Dependence of Leveraged ETF Returns", SIAM Journal on Financial Mathematics, 1, 586-603。CoinDesk(2021年5月27日), "Mayhem in Binance Leveraged Tokens During Crypto Crash Leaves Traders Fuming"。Fidelity Digital Assets, "A Closer Look at Bitcoin's Volatility"。Binance Support, "Binance Leveraged Tokens Trading Rules"。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: Cheng, M. &amp; Madhavan, A. (2009), "The Dynamics of Leveraged and Inverse Exchange-Traded Funds", Journal of Investment Management, 7(4). Avellaneda, M. &amp; Zhang, S. (2010), "Path-Dependence of Leveraged ETF Returns", SIAM Journal on Financial Mathematics, 1, 586-603. CoinDesk (27 de mayo de 2021), "Mayhem in Binance Leveraged Tokens During Crypto Crash Leaves Traders Fuming". Fidelity Digital Assets, "A Closer Look at Bitcoin's Volatility". Binance Support, "Binance Leveraged Tokens Trading Rules".</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: Cheng, M. &amp; Madhavan, A. (2009), „The Dynamics of Leveraged and Inverse Exchange-Traded Funds", Journal of Investment Management, 7(4). Avellaneda, M. &amp; Zhang, S. (2010), „Path-Dependence of Leveraged ETF Returns", SIAM Journal on Financial Mathematics, 1, 586-603. CoinDesk (27. Mai 2021), „Mayhem in Binance Leveraged Tokens During Crypto Crash Leaves Traders Fuming". Fidelity Digital Assets, „A Closer Look at Bitcoin's Volatility". Binance Support, „Binance Leveraged Tokens Trading Rules".</p>
<?php require __DIR__.'/_footer.php'; ?>
