<?php $slug = 'wall-street-banks-tokenized-deposit-stablecoin-yield-fight'; require __DIR__.'/_header.php'; ?>

<p class="ko">블룸버그(Bloomberg)의 7월13일 보도에 따르면, 미국은행협회(ABA)를 필두로 한 40여개 은행권 단체가 스테이블코인 거래소·유통 제휴사가 '리워드'나 '플랫폼 인센티브'라는 이름으로 사실상 이자를 지급하는 관행을 GENIUS법상 금지 대상에 포함시켜 달라고 요구하고 나섰다. GENIUS법은 스테이블코인 발행사가 직접 이자·수익을 지급하는 것은 금지했지만, 거래소나 제휴 플랫폼이 우회적으로 3.5~5.2%대 수익을 제공하는 길은 그대로 열려 있었다. 은행권은 이 우회로가 저원가 예금이라는 은행의 핵심 자금조달 기반을 잠식한다고 보고 있다.</p>
<p class="en">According to a July 13 Bloomberg report, more than 40 banking associations led by the American Bankers Association are pushing to extend the GENIUS Act's ban on stablecoin yield to cover exchanges and distribution partners that pay de facto interest under the label of "rewards" or "platform incentives." While the GENIUS Act bars stablecoin issuers themselves from paying interest or yield directly, it left open a path for exchanges and affiliated platforms to route returns of roughly 3.5% to 5.2% to holders indirectly. Banks argue this workaround is eroding the cheap-deposit funding base that underpins their core lending business.</p>
<p class="ja">ブルームバーグ(Bloomberg)の7月13日の報道によれば、米国銀行協会(ABA)を筆頭とする40超の銀行団体が、ステーブルコイン取引所や流通提携先が「リワード」や「プラットフォーム特典」の名目で事実上の利息を支払う慣行を、GENIUS法の禁止対象に含めるよう求めている。GENIUS法はステーブルコイン発行体自身が直接利息・収益を支払うことを禁じたが、取引所や提携プラットフォームが迂回的に3.5~5.2%程度の利回りを提供する道はそのまま開かれていた。銀行界はこの抜け道が、銀行の中核的な資金調達基盤である低コスト預金を侵食していると見ている。</p>
<p class="es">Según un informe de Bloomberg del 13 de julio, más de 40 asociaciones bancarias lideradas por la Asociación de Banqueros Americanos presionan para extender la prohibición de rendimiento de la GENIUS Act y así cubrir a los exchanges y socios distribuidores que pagan interés de facto bajo la etiqueta de "recompensas" o "incentivos de plataforma". Si bien la GENIUS Act prohíbe a los propios emisores de stablecoins pagar interés o rendimiento directamente, dejó abierta una vía para que exchanges y plataformas afiliadas canalizaran indirectamente retornos de entre 3,5% y 5,2% a los tenedores. Los bancos sostienen que esta vía alternativa está erosionando la base de depósitos baratos que sustenta su negocio principal de préstamos.</p>
<p class="de">Laut einem Bloomberg-Bericht vom 13. Juli drängen mehr als 40 von der American Bankers Association angeführte Bankenverbände darauf, das Zinsverbot des GENIUS Act so auszuweiten, dass es auch Börsen und Vertriebspartner erfasst, die unter dem Label „Rewards“ oder „Plattform-Anreize“ faktisch Zinsen zahlen. Zwar untersagt der GENIUS Act Stablecoin-Emittenten selbst, direkt Zinsen oder Rendite zu zahlen, doch er ließ einen Weg offen, über den Börsen und angeschlossene Plattformen Renditen von etwa 3,5 bis 5,2% indirekt an Inhaber weiterleiten können. Banken argumentieren, dieser Umweg untergrabe die günstige Einlagenbasis, auf der ihr Kerngeschäft mit der Kreditvergabe beruht.</p>
<p class="fr">Selon un rapport de Bloomberg du 13 juillet, plus de 40 associations bancaires menées par l'American Bankers Association font pression pour étendre l'interdiction de rendement du GENIUS Act aux plateformes d'échange et partenaires de distribution qui versent des intérêts de facto sous l'appellation de « récompenses » ou d'« incitations de plateforme ». Si le GENIUS Act interdit aux émetteurs de stablecoins eux-mêmes de verser directement des intérêts ou un rendement, il a laissé une voie ouverte permettant aux plateformes d'échange et à leurs partenaires affiliés de reverser indirectement des rendements de l'ordre de 3,5% à 5,2% aux détenteurs. Les banques estiment que ce contournement érode la base de dépôts bon marché sur laquelle repose leur activité principale de prêt.</p>
<p class="pt">Segundo reportagem da Bloomberg de 13 de julho, mais de 40 associações bancárias lideradas pela American Bankers Association pressionam para estender a proibição de rendimento da GENIUS Act, cobrindo exchanges e parceiros de distribuição que pagam juros de fato sob o rótulo de "recompensas" ou "incentivos de plataforma". Embora a GENIUS Act proíba os próprios emissores de stablecoins de pagar juros ou rendimento diretamente, ela deixou aberto um caminho para que exchanges e plataformas afiliadas repassassem indiretamente retornos de cerca de 3,5% a 5,2% aos detentores. Os bancos argumentam que essa alternativa está corroendo a base de depósitos baratos que sustenta seu negócio principal de crédito.</p>
<p class="tr">Bloomberg'in 13 Temmuz tarihli haberine göre, Amerikan Bankacılar Birliği önderliğindeki 40'tan fazla bankacılık derneği, GENIUS Yasası'nın getiri yasağının, "ödül" ya da "platform teşviki" adı altında fiilen faiz ödeyen borsaları ve dağıtım ortaklarını da kapsayacak şekilde genişletilmesi için baskı yapıyor. GENIUS Yasası, stablecoin ihraççılarının doğrudan faiz veya getiri ödemesini yasaklasa da, borsaların ve iştirak platformlarının sahiplere dolaylı yoldan yaklaşık %3,5 ila %5,2 arasında getiri aktarmasına açık bir yol bıraktı. Bankalar, bu dolambaçlı yolun, temel kredi işlerinin dayandığı ucuz mevduat tabanını aşındırdığını savunuyor.</p>
<p class="vi">Theo báo cáo ngày 13 tháng 7 của Bloomberg, hơn 40 hiệp hội ngân hàng do Hiệp hội Ngân hàng Hoa Kỳ dẫn đầu đang thúc đẩy mở rộng lệnh cấm lợi suất theo Đạo luật GENIUS để bao trùm cả các sàn giao dịch và đối tác phân phối trả lãi trên thực tế dưới danh nghĩa "phần thưởng" hoặc "ưu đãi nền tảng". Mặc dù Đạo luật GENIUS cấm chính các tổ chức phát hành stablecoin trả lãi hoặc lợi suất trực tiếp, nó vẫn để ngỏ một con đường cho các sàn giao dịch và nền tảng liên kết chuyển gián tiếp lợi suất khoảng 3,5% đến 5,2% cho người nắm giữ. Các ngân hàng lập luận rằng cách lách luật này đang bào mòn nền tảng tiền gửi chi phí thấp vốn là trụ cột cho hoạt động cho vay cốt lõi của họ.</p>

<p class="ko">동시에 대형은행들은 방어에만 그치지 않고 별도의 인프라 구축으로 맞불을 놓고 있다. JP모건체이스·씨티그룹·뱅크오브아메리카·웰스파고를 비롯해 BNY·BMO·시티즌스파이낸셜·피프스서드·HSBC·헌팅턴·키뱅크·PNC·리전스·산탄데르·TD뱅크·트루이스트·US뱅크 등이 참여해, 청산결제기구 더클리어링하우스(The Clearing House)를 통한 토큰화 예금망을 2027년 상반기 가동을 목표로 준비 중이다. 이와 별개로 지역은행들도 소매용 토큰화 예금을 겨냥한 '카리 네트워크(Cari Network)' 컨소시엄을 결성해 2026년 3분기 파일럿, 4분기 고객 출시를 계획하고 있어, 대형은행과 지역은행이 각자 다른 속도로 같은 방향의 대응에 나선 모습이다.</p>
<p class="en">At the same time, big banks are not limiting themselves to defense — they are countering with infrastructure of their own. JPMorgan Chase, Citigroup, Bank of America and Wells Fargo, joined by BNY, BMO, Citizens Financial, Fifth Third, HSBC, Huntington, KeyBank, PNC, Regions, Santander, TD Bank, Truist and U.S. Bank, are building a tokenized deposit network through the clearing utility The Clearing House, targeting launch in the first half of 2027. Separately, regional banks have formed their own consortium, the Cari Network, aimed at retail tokenized deposits, with a pilot planned for the third quarter of 2026 and a customer launch in the fourth quarter — so large and regional banks are moving at different speeds toward the same broad response.</p>
<p class="ja">同時に大手銀行は防御に留まらず、独自のインフラ構築で対抗している。JPモルガン・チェース、シティグループ、バンクオブアメリカ、ウェルズファーゴに加え、BNY、BMO、シチズンズ・ファイナンシャル、フィフス・サード、HSBC、ハンティントン、キーバンク、PNC、リージョンズ、サンタンデール、TDバンク、トゥルーイスト、USバンクなどが参加し、清算機関ザ・クリアリングハウス(The Clearing House)を通じたトークン化預金網を2027年上半期の稼働を目標に準備している。これとは別に、地方銀行も小口向けトークン化預金を狙った「カリ・ネットワーク(Cari Network)」コンソーシアムを結成し、2026年第3四半期のパイロット、第4四半期の顧客向け開始を計画しており、大手銀行と地方銀行がそれぞれ異なる速度で同じ方向の対応に動いている。</p>
<p class="es">Al mismo tiempo, los grandes bancos no se limitan a defenderse: están contraatacando con su propia infraestructura. JPMorgan Chase, Citigroup, Bank of America y Wells Fargo, junto con BNY, BMO, Citizens Financial, Fifth Third, HSBC, Huntington, KeyBank, PNC, Regions, Santander, TD Bank, Truist y U.S. Bank, están construyendo una red de depósitos tokenizados a través de la cámara de compensación The Clearing House, con lanzamiento previsto para el primer semestre de 2027. Por separado, los bancos regionales han formado su propio consorcio, la Cari Network, orientado a depósitos tokenizados minoristas, con un piloto planificado para el tercer trimestre de 2026 y un lanzamiento al público en el cuarto trimestre, de modo que grandes bancos y bancos regionales avanzan a velocidades distintas hacia una misma respuesta general.</p>
<p class="de">Gleichzeitig beschränken sich die Großbanken nicht auf Verteidigung — sie kontern mit eigener Infrastruktur. JPMorgan Chase, Citigroup, Bank of America und Wells Fargo bauen zusammen mit BNY, BMO, Citizens Financial, Fifth Third, HSBC, Huntington, KeyBank, PNC, Regions, Santander, TD Bank, Truist und U.S. Bank über die Clearingstelle The Clearing House ein tokenisiertes Einlagennetzwerk auf, dessen Start für die erste Hälfte 2027 angepeilt wird. Unabhängig davon haben Regionalbanken ihr eigenes Konsortium namens Cari Network gegründet, das auf tokenisierte Privatkundeneinlagen abzielt, mit einem Pilotprojekt im dritten Quartal 2026 und einem Kundenstart im vierten Quartal — Groß- und Regionalbanken bewegen sich also mit unterschiedlichem Tempo in dieselbe Richtung.</p>
<p class="fr">Dans le même temps, les grandes banques ne se contentent pas de se défendre : elles ripostent avec leur propre infrastructure. JPMorgan Chase, Citigroup, Bank of America et Wells Fargo, rejointes par BNY, BMO, Citizens Financial, Fifth Third, HSBC, Huntington, KeyBank, PNC, Regions, Santander, TD Bank, Truist et U.S. Bank, construisent un réseau de dépôts tokenisés via la chambre de compensation The Clearing House, visant un lancement au premier semestre 2027. Par ailleurs, les banques régionales ont formé leur propre consortium, le Cari Network, destiné aux dépôts tokenisés de détail, avec un pilote prévu pour le troisième trimestre 2026 et un lancement client au quatrième trimestre — grandes banques et banques régionales avancent ainsi à des vitesses différentes vers une même réponse d'ensemble.</p>
<p class="pt">Ao mesmo tempo, os grandes bancos não se limitam à defesa — estão revidando com sua própria infraestrutura. JPMorgan Chase, Citigroup, Bank of America e Wells Fargo, junto com BNY, BMO, Citizens Financial, Fifth Third, HSBC, Huntington, KeyBank, PNC, Regions, Santander, TD Bank, Truist e U.S. Bank, estão construindo uma rede de depósitos tokenizados por meio da câmara de compensação The Clearing House, com lançamento previsto para o primeiro semestre de 2027. Separadamente, bancos regionais formaram seu próprio consórcio, a Cari Network, voltado a depósitos tokenizados de varejo, com piloto planejado para o terceiro trimestre de 2026 e lançamento para clientes no quarto trimestre — assim, grandes bancos e bancos regionais avançam em velocidades diferentes rumo à mesma resposta geral.</p>
<p class="tr">Aynı zamanda büyük bankalar yalnızca savunmayla yetinmiyor — kendi altyapılarıyla karşı hamle yapıyorlar. JPMorgan Chase, Citigroup, Bank of America ve Wells Fargo'ya BNY, BMO, Citizens Financial, Fifth Third, HSBC, Huntington, KeyBank, PNC, Regions, Santander, TD Bank, Truist ve U.S. Bank da katılarak, takas kuruluşu The Clearing House aracılığıyla, 2027'nin ilk yarısında devreye alınması hedeflenen bir tokenleştirilmiş mevduat ağı inşa ediyor. Ayrı olarak, bölgesel bankalar da perakende tokenleştirilmiş mevduatları hedefleyen kendi konsorsiyumları olan Cari Network'ü kurdu; 2026'nın üçüncü çeyreğinde pilot, dördüncü çeyreğinde müşteri lansmanı planlanıyor — yani büyük bankalar ve bölgesel bankalar farklı hızlarda ama aynı genel yanıta doğru ilerliyor.</p>
<p class="vi">Đồng thời, các ngân hàng lớn không chỉ dừng lại ở phòng thủ — họ đang phản công bằng chính hạ tầng của mình. JPMorgan Chase, Citigroup, Bank of America và Wells Fargo, cùng với BNY, BMO, Citizens Financial, Fifth Third, HSBC, Huntington, KeyBank, PNC, Regions, Santander, TD Bank, Truist và U.S. Bank, đang xây dựng một mạng lưới tiền gửi token hóa thông qua tổ chức thanh toán bù trừ The Clearing House, dự kiến ra mắt vào nửa đầu năm 2027. Riêng biệt, các ngân hàng khu vực đã thành lập liên minh riêng của mình, Cari Network, nhắm đến tiền gửi token hóa bán lẻ, với thí điểm dự kiến vào quý 3 năm 2026 và ra mắt khách hàng vào quý 4 — cho thấy ngân hàng lớn và ngân hàng khu vực đang di chuyển với tốc độ khác nhau nhưng hướng tới cùng một phản ứng chung.</p>

<h2 class="ko">왜 이렇게까지 반발하나 — 토큰화 예금과 스테이블코인의 근본적 차이</h2>
<h2 class="en">Why the Alarm — the Fundamental Difference Between Tokenized Deposits and Stablecoins</h2>
<h2 class="ja">なぜここまで反発するのか — トークン化預金とステーブルコインの根本的な違い</h2>
<h2 class="es">Por Qué Tanta Alarma — la Diferencia Fundamental Entre Depósitos Tokenizados y Stablecoins</h2>
<h2 class="de">Warum der Alarm — der Grundlegende Unterschied Zwischen Tokenisierten Einlagen und Stablecoins</h2>
<h2 class="fr">Pourquoi Une Telle Alarme — la Différence Fondamentale Entre Dépôts Tokenisés et Stablecoins</h2>
<h2 class="pt">Por Que Tanto Alarme — a Diferença Fundamental Entre Depósitos Tokenizados e Stablecoins</h2>
<h2 class="tr">Neden Bu Kadar Alarm — Tokenleştirilmiş Mevduatlar ile Stablecoinler Arasındaki Temel Fark</h2>
<h2 class="vi">Tại Sao Báo Động Đến Vậy — Khác Biệt Căn Bản Giữa Tiền Gửi Token Hóa Và Stablecoin</h2>

<p class="ko">은행업의 근간은 부분지급준비제도다. 예금자가 맡긴 돈은 은행 대차대조표에 남아 대출 재원으로 쓰이고, 은행은 그 예금에 낮은 이자만 지급하면서 대출로 더 높은 수익을 낸다. 만약 예금자들이 대거 수익률 높은 스테이블코인으로 자금을 옮기면, 은행은 이 저비용 자금조달원을 잃고 도매금융 등 더 비싼 자금을 조달해야 하며, 이는 결국 대출금리 상승으로 이어질 수 있다. 반면 토큰화 예금은 블록체인 상에서 표현될 뿐 여전히 은행의 실제 요구불예금 계좌이며, 연방예금보험공사(FDIC) 한도 내에서 예금보험 대상이 된다. GENIUS법을 준수하는 스테이블코인은 이와 다르다 — 발행사가 보유한 현금·단기국채 등 준비자산으로 뒷받침되지만, 이는 은행이 재대출하는 예금이 아니며 예금보험 대상도 아니다.</p>
<p class="en">Banking's foundation is fractional-reserve lending: money deposited by savers stays on a bank's balance sheet and funds loans, with the bank paying depositors only a low rate of interest while earning a higher return on those loans. If depositors move funds en masse into higher-yielding stablecoins, banks lose that cheap funding source and must turn to costlier wholesale funding instead, which can eventually push up loan rates. A tokenized deposit, by contrast, is simply a blockchain-native representation of an actual demand deposit account still sitting on a bank's balance sheet, eligible for deposit insurance up to FDIC limits. A GENIUS Act-compliant stablecoin is structurally different — it's backed by reserve assets such as cash and short-term Treasuries held by the issuer, but those are not deposits a bank re-lends, and they carry no deposit insurance at all.</p>
<p class="ja">銀行業の根幹は部分準備制度にある。預金者が預けた資金は銀行の貸借対照表に残り貸出の原資となり、銀行はその預金に低い利息だけを支払いながら貸出でより高い収益を得る。もし預金者が大挙して利回りの高いステーブルコインへ資金を移せば、銀行はこの低コストの資金調達源を失い、より高コストのホールセール資金調達などに頼らざるを得なくなり、これは結局貸出金利の上昇につながりかねない。これに対しトークン化預金は、ブロックチェーン上で表現されているに過ぎず、依然として銀行の実際の要求払預金口座であり、連邦預金保険公社(FDIC)の限度内で預金保険の対象となる。GENIUS法に準拠したステーブルコインはこれとは異なる — 発行体が保有する現金や短期国債などの準備資産に裏付けられているが、これは銀行が再貸出する預金ではなく、預金保険の対象にもならない。</p>
<p class="es">Los fundamentos de la banca son la reserva fraccionaria: el dinero depositado por los ahorradores permanece en el balance del banco y financia préstamos, mientras el banco paga a los depositantes solo una tasa baja de interés y obtiene un rendimiento mayor de esos préstamos. Si los depositantes trasladan sus fondos en masa hacia stablecoins de mayor rendimiento, los bancos pierden esa fuente de financiación barata y deben recurrir a financiación mayorista más costosa, lo que eventualmente puede elevar las tasas de los préstamos. Un depósito tokenizado, en cambio, es simplemente una representación nativa en blockchain de una cuenta de depósito a la vista real que sigue en el balance de un banco, elegible para el seguro de depósitos hasta los límites de la FDIC. Una stablecoin conforme a la GENIUS Act es estructuralmente distinta: está respaldada por activos de reserva como efectivo y letras del Tesoro a corto plazo en poder del emisor, pero eso no son depósitos que un banco vuelva a prestar, y no llevan ningún seguro de depósitos.</p>
<p class="de">Die Grundlage des Bankwesens ist das Teilreserve-System: Von Sparern eingezahltes Geld bleibt in der Bankbilanz und finanziert Kredite, wobei die Bank den Einlegern nur einen niedrigen Zinssatz zahlt, während sie mit diesen Krediten eine höhere Rendite erzielt. Verlagern Einleger ihr Geld massenhaft in höher verzinste Stablecoins, verlieren Banken diese günstige Finanzierungsquelle und müssen stattdessen auf teurere Großhandelsfinanzierung zurückgreifen, was letztlich die Kreditzinsen nach oben treiben kann. Eine tokenisierte Einlage ist dagegen lediglich eine blockchain-native Abbildung eines echten Sichteinlagenkontos, das weiterhin in der Bankbilanz steht und bis zu den FDIC-Grenzen einlagenversichert ist. Eine GENIUS-Act-konforme Stablecoin ist strukturell anders — sie wird durch Reserveassets wie Bargeld und kurzfristige Staatsanleihen gedeckt, die der Emittent hält, doch das sind keine Einlagen, die eine Bank weiterverleiht, und sie sind überhaupt nicht einlagenversichert.</p>
<p class="fr">Le fondement de la banque, c'est la réserve fractionnaire : l'argent déposé par les épargnants reste au bilan de la banque et finance des prêts, la banque ne versant aux déposants qu'un faible taux d'intérêt tout en tirant un rendement supérieur de ces prêts. Si les déposants transfèrent massivement leurs fonds vers des stablecoins à rendement plus élevé, les banques perdent cette source de financement bon marché et doivent se tourner vers un financement de gros plus coûteux, ce qui peut à terme faire grimper les taux de prêt. Un dépôt tokenisé, en revanche, n'est qu'une représentation native sur blockchain d'un véritable compte de dépôt à vue toujours inscrit au bilan d'une banque, éligible à l'assurance des dépôts dans la limite des plafonds de la FDIC. Un stablecoin conforme au GENIUS Act est structurellement différent — il est adossé à des actifs de réserve tels que des liquidités et des bons du Trésor à court terme détenus par l'émetteur, mais il ne s'agit pas de dépôts qu'une banque reprête, et ils ne bénéficient d'aucune assurance des dépôts.</p>
<p class="pt">O alicerce do setor bancário é a reserva fracionária: o dinheiro depositado pelos poupadores permanece no balanço do banco e financia empréstimos, com o banco pagando aos depositantes apenas uma taxa baixa de juros enquanto obtém um retorno maior com esses empréstimos. Se os depositantes transferirem seus recursos em massa para stablecoins de maior rendimento, os bancos perdem essa fonte de financiamento barata e precisam recorrer a financiamento atacadista mais caro, o que pode eventualmente elevar as taxas de empréstimo. Um depósito tokenizado, por outro lado, é simplesmente uma representação nativa em blockchain de uma conta de depósito à vista real que continua no balanço de um banco, elegível ao seguro de depósitos até os limites do FDIC. Uma stablecoin em conformidade com a GENIUS Act é estruturalmente diferente — ela é lastreada por ativos de reserva, como caixa e títulos do Tesouro de curto prazo mantidos pelo emissor, mas isso não são depósitos que um banco reempresta, e não contam com nenhum seguro de depósitos.</p>
<p class="tr">Bankacılığın temeli kısmi rezerv sistemidir: mevduat sahiplerinin yatırdığı para bankanın bilançosunda kalır ve kredileri finanse eder; banka mevduat sahiplerine yalnızca düşük bir faiz öderken bu kredilerden daha yüksek bir getiri elde eder. Mevduat sahipleri toplu halde daha yüksek getirili stablecoinlere geçerse, bankalar bu ucuz fonlama kaynağını kaybeder ve bunun yerine daha maliyetli toptan fonlamaya yönelmek zorunda kalır; bu da nihayetinde kredi faizlerini yükseltebilir. Buna karşılık tokenleştirilmiş bir mevduat, hâlâ bir bankanın bilançosunda duran gerçek bir vadesiz mevduat hesabının blok zinciri üzerindeki bir temsilinden ibarettir ve FDIC limitlerine kadar mevduat sigortası kapsamındadır. GENIUS Yasası'na uyumlu bir stablecoin ise yapısal olarak farklıdır — ihraççının elinde tuttuğu nakit ve kısa vadeli hazine bonoları gibi rezerv varlıklarla desteklenir, ancak bunlar bir bankanın yeniden kredi olarak verdiği mevduatlar değildir ve hiçbir mevduat sigortası taşımazlar.</p>
<p class="vi">Nền tảng của ngành ngân hàng là chế độ dự trữ một phần: tiền do người gửi tiết kiệm ký gửi vẫn nằm trên bảng cân đối kế toán của ngân hàng và tài trợ cho các khoản vay, trong khi ngân hàng chỉ trả cho người gửi tiền một mức lãi suất thấp nhưng thu được lợi suất cao hơn từ các khoản vay đó. Nếu người gửi tiền chuyển vốn hàng loạt sang các stablecoin có lợi suất cao hơn, ngân hàng sẽ mất đi nguồn vốn giá rẻ đó và phải chuyển sang nguồn vốn bán buôn đắt đỏ hơn, điều này cuối cùng có thể đẩy lãi suất cho vay lên cao. Ngược lại, tiền gửi token hóa chỉ đơn thuần là một đại diện gốc blockchain của một tài khoản tiền gửi không kỳ hạn thực sự vẫn nằm trên bảng cân đối kế toán của ngân hàng, đủ điều kiện được bảo hiểm tiền gửi trong giới hạn của FDIC. Một stablecoin tuân thủ Đạo luật GENIUS thì khác về cấu trúc — nó được bảo đảm bằng các tài sản dự trữ như tiền mặt và trái phiếu kho bạc ngắn hạn do tổ chức phát hành nắm giữ, nhưng đó không phải là tiền gửi mà ngân hàng cho vay lại, và chúng hoàn toàn không có bảo hiểm tiền gửi.</p>

<p class="ko">문제가 되는 '우회 수익 지급' 구조도 정확히 짚을 필요가 있다. GENIUS법은 발행사가 직접 이자를 지급하는 것만 금지했을 뿐, 그 하위 유통 단계까지는 명시적으로 막지 않았다. 거래소나 제휴 플랫폼은 준비자산에서 나오는 수익(예: 국채 이자)의 일부를 '리워드'나 '인센티브'라는 명목으로 보유자에게 되돌려주는 방식으로, 사실상 저축계좌형 수익률을 법 문언을 위반하지 않으면서 복제해낸다. 미국 통화감독청(OCC)은 2월25일 이런 간접적 수익 지급 구조에 '반증 가능한 위법 추정'을 적용하는 내용의 규칙 초안을 내놓았는데, 이는 은행권이 요구하는 '발행사뿐 아니라 제휴사까지 규제 대상에 포함'이라는 방향과 궤를 같이한다.</p>
<p class="en">It's worth pinning down exactly how the disputed "indirect yield" structure works. The GENIUS Act bans only issuers from paying interest directly — it does not explicitly reach further down the distribution chain. Exchanges and affiliated platforms pass a portion of the returns generated by reserve assets (Treasury interest, for instance) back to holders under labels like "rewards" or "incentives," effectively replicating a savings-account-style yield without technically violating the statute's wording. The Office of the Comptroller of the Currency issued a proposed rule on February 25 that would apply a "rebuttable presumption" against such indirect yield-generating arrangements — a move that lines up with what banks are now demanding: extending regulation beyond issuers to cover affiliates as well.</p>
<p class="ja">問題となっている「間接的な収益還元」の仕組みも正確に押さえておく必要がある。GENIUS法が禁じているのは発行体が直接利息を支払うことのみで、その先の流通段階までは明示的に対象としていない。取引所や提携プラットフォームは、準備資産から生じる収益(例えば国債の利息)の一部を「リワード」や「インセンティブ」の名目で保有者に還元することで、法の文言に違反することなく事実上、貯蓄口座型の利回りを再現している。米国通貨監督庁(OCC)は2月25日、こうした間接的な収益還元の仕組みに「反証可能な違法推定」を適用する規則案を提示しており、これは銀行界が求める「発行体だけでなく提携先も規制対象に含める」という方向性と軌を一にする。</p>
<p class="es">Vale la pena precisar exactamente cómo funciona la controvertida estructura de "rendimiento indirecto". La GENIUS Act prohíbe únicamente que los emisores paguen interés de forma directa; no alcanza explícitamente a los eslabones posteriores de la cadena de distribución. Los exchanges y las plataformas afiliadas devuelven a los tenedores una parte de los rendimientos generados por los activos de reserva (los intereses del Tesoro, por ejemplo) bajo etiquetas como "recompensas" o "incentivos", replicando en la práctica un rendimiento tipo cuenta de ahorro sin violar técnicamente la letra de la ley. La Oficina del Contralor de la Moneda (OCC) emitió el 25 de febrero una propuesta de norma que aplicaría una "presunción refutable" contra este tipo de mecanismos indirectos de generación de rendimiento, una medida que coincide con lo que ahora exigen los bancos: extender la regulación más allá de los emisores para cubrir también a los afiliados.</p>
<p class="de">Es lohnt sich, genau zu klären, wie die umstrittene Struktur der „indirekten Rendite" funktioniert. Der GENIUS Act verbietet nur Emittenten, direkt Zinsen zu zahlen — er reicht ausdrücklich nicht weiter die Vertriebskette hinunter. Börsen und angeschlossene Plattformen geben einen Teil der aus Reserveassets erzielten Erträge (etwa Zinsen aus Staatsanleihen) unter Bezeichnungen wie „Rewards" oder „Anreize" an Inhaber zurück und bilden damit faktisch eine Sparkonto-ähnliche Rendite nach, ohne den Wortlaut des Gesetzes formal zu verletzen. Die Bankenaufsichtsbehörde OCC legte am 25. Februar einen Regelentwurf vor, der eine „widerlegbare Vermutung" gegen solche indirekten renditegenerierenden Vereinbarungen einführen würde — ein Schritt, der mit der Forderung der Banken übereinstimmt, die Regulierung über die Emittenten hinaus auch auf Partnerunternehmen auszuweiten.</p>
<p class="fr">Il convient de préciser exactement comment fonctionne la structure contestée de « rendement indirect ». Le GENIUS Act interdit uniquement aux émetteurs de verser des intérêts directement — il ne s'étend pas explicitement plus bas dans la chaîne de distribution. Les plateformes d'échange et les partenaires affiliés reversent une partie des rendements générés par les actifs de réserve (les intérêts des bons du Trésor, par exemple) aux détenteurs sous des étiquettes telles que « récompenses » ou « incitations », reproduisant ainsi de fait un rendement de type compte d'épargne sans techniquement enfreindre la lettre de la loi. Le Bureau du contrôleur de la monnaie (OCC) a publié le 25 février un projet de règle qui appliquerait une « présomption réfutable » contre ce type de dispositifs générateurs de rendement indirect — une mesure qui rejoint ce que les banques exigent désormais : étendre la réglementation au-delà des émetteurs pour couvrir aussi les affiliés.</p>
<p class="pt">Vale a pena precisar exatamente como funciona a contestada estrutura de "rendimento indireto". A GENIUS Act proíbe apenas que os emissores paguem juros diretamente — ela não alcança explicitamente elos mais adiante na cadeia de distribuição. Exchanges e plataformas afiliadas repassam parte dos rendimentos gerados pelos ativos de reserva (juros de títulos do Tesouro, por exemplo) aos detentores sob rótulos como "recompensas" ou "incentivos", replicando na prática um rendimento estilo conta poupança sem, tecnicamente, violar a letra da lei. O Office of the Comptroller of the Currency (OCC) emitiu, em 25 de fevereiro, uma proposta de regra que aplicaria uma "presunção refutável" contra esses arranjos indiretos geradores de rendimento — uma medida alinhada com o que os bancos agora exigem: estender a regulação para além dos emissores, cobrindo também os afiliados.</p>
<p class="tr">Tartışmalı "dolaylı getiri" yapısının tam olarak nasıl işlediğini netleştirmekte fayda var. GENIUS Yasası yalnızca ihraççıların doğrudan faiz ödemesini yasaklıyor — dağıtım zincirinin daha aşağısına açıkça uzanmıyor. Borsalar ve iştirak platformları, rezerv varlıklardan elde edilen getirilerin (örneğin hazine bonosu faizinin) bir kısmını "ödül" veya "teşvik" adı altında sahiplere geri aktararak, yasanın lafzını teknik olarak ihlal etmeden fiilen bir tasarruf hesabı tarzı getiri yaratıyor. ABD Para Denetleme Ofisi (OCC), 25 Şubat'ta, bu tür dolaylı getiri yaratan düzenlemelere karşı "çürütülebilir bir karine" uygulayacak bir taslak kural yayımladı — bu adım, bankaların şimdi talep ettiği yönle, yani düzenlemenin yalnızca ihraççıları değil iştirakleri de kapsayacak şekilde genişletilmesiyle örtüşüyor.</p>
<p class="vi">Cũng đáng để làm rõ chính xác cách thức hoạt động của cơ cấu "lợi suất gián tiếp" đang gây tranh cãi này. Đạo luật GENIUS chỉ cấm các tổ chức phát hành trả lãi trực tiếp — nó không vươn tới một cách rõ ràng các mắt xích xa hơn trong chuỗi phân phối. Các sàn giao dịch và nền tảng liên kết chuyển lại một phần lợi suất tạo ra từ tài sản dự trữ (ví dụ lãi trái phiếu kho bạc) cho người nắm giữ dưới các nhãn như "phần thưởng" hay "ưu đãi", trên thực tế tái tạo một mức lợi suất kiểu tài khoản tiết kiệm mà không vi phạm câu chữ của luật về mặt kỹ thuật. Văn phòng Kiểm soát Tiền tệ (OCC) đã ban hành một dự thảo quy định vào ngày 25 tháng 2 sẽ áp dụng "giả định có thể bác bỏ" đối với các thỏa thuận tạo lợi suất gián tiếp như vậy — một động thái phù hợp với điều mà các ngân hàng hiện đang yêu cầu: mở rộng quy định vượt ra ngoài các tổ chức phát hành để bao trùm cả các đơn vị liên kết.</p>

<h2 class="ko">과거와의 대조 — 2023년 예금 이탈 사태, 그리고 유로달러 시장의 선례</h2>
<h2 class="en">Historical Parallels — the 2023 Deposit Flight, and the Eurodollar Precedent</h2>
<h2 class="ja">過去との対照 — 2023年の預金流出、そしてユーロダラー市場の先例</h2>
<h2 class="es">Paralelismos Históricos — la Fuga de Depósitos de 2023 y el Precedente del Eurodólar</h2>
<h2 class="de">Historische Parallelen — die Einlagenflucht von 2023 und der Eurodollar-Präzedenzfall</h2>
<h2 class="fr">Parallèles Historiques — la Fuite des Dépôts de 2023 et le Précédent de l'Eurodollar</h2>
<h2 class="pt">Paralelos Históricos — a Fuga de Depósitos de 2023 e o Precedente do Eurodólar</h2>
<h2 class="tr">Tarihsel Paralellikler — 2023 Mevduat Kaçışı ve Eurodolar Emsali</h2>
<h2 class="vi">Những Điểm Tương Đồng Lịch Sử — Làn Sóng Rút Tiền Gửi Năm 2023 Và Tiền Lệ Thị Trường Eurodollar</h2>

<p class="ko">은행권이 이 문제를 사소한 상품 경쟁이 아니라 존립을 건 문제로 다루는 이유는 2023년 미국 지역은행 위기 당시의 학습효과 때문으로 보인다. 실리콘밸리은행(SVB) 사태 당시, 예금자들은 스마트폰 앱 몇 번의 터치만으로 며칠 만에 수십억달러를 더 높은 수익률을 주는 머니마켓펀드(MMF)로 옮겼고, 이는 은행의 유동성을 순식간에 고갈시켰다. 스테이블코인의 '리워드'형 우회 수익은 바로 이 '핫머니 이탈'의 크립토 버전이라 할 수 있다 — 차이가 있다면 지금은 그 이탈 경로가 규제된 MMF가 아니라 온체인 지갑이라는 점뿐이다.</p>
<p class="en">Banks appear to be treating this as an existential issue rather than a minor product-competition dispute, likely because of lessons learned from the 2023 US regional banking crisis. During the Silicon Valley Bank collapse, depositors moved billions of dollars into higher-yielding money market funds within days, with just a few taps on a smartphone app, draining bank liquidity almost overnight. Stablecoins' rewards-based indirect yield is arguably the crypto-native version of that same hot-money flight risk — the only real difference now is that the exit ramp is an on-chain wallet rather than a regulated money market fund.</p>
<p class="ja">銀行界がこの問題を些細な商品競争ではなく、存続をかけた問題として扱っているのは、2023年の米地方銀行危機で得た教訓によるものと見られる。シリコンバレー銀行(SVB)破綻の際、預金者はスマートフォンアプリの数回のタップだけで、数日のうちに数十億ドルをより高利回りのマネー・マーケット・ファンド(MMF)へ移し、これが銀行の流動性をほぼ一夜にして枯渇させた。ステーブルコインの「リワード」型間接収益は、まさにこの「ホットマネー流出」の暗号資産版と言える — 唯一の違いは、その流出経路が規制されたMMFではなく、オンチェーンのウォレットになったという点だけだ。</p>
<p class="es">Los bancos parecen tratar esto como una cuestión existencial y no como una disputa menor de competencia de productos, probablemente por las lecciones aprendidas de la crisis bancaria regional estadounidense de 2023. Durante el colapso de Silicon Valley Bank, los depositantes trasladaron miles de millones de dólares hacia fondos del mercado monetario de mayor rendimiento en cuestión de días, con solo unos toques en una app del teléfono, drenando la liquidez bancaria casi de un día para otro. El rendimiento indirecto de las stablecoins basado en "recompensas" es, podría decirse, la versión cripto de ese mismo riesgo de fuga de dinero caliente — la única diferencia real ahora es que la vía de salida es una billetera on-chain en lugar de un fondo del mercado monetario regulado.</p>
<p class="de">Banken behandeln dies offenbar als existenzielle Frage und nicht als kleineren Produktwettbewerbsstreit — wahrscheinlich aufgrund der Lehren aus der US-Regionalbankenkrise von 2023. Beim Zusammenbruch der Silicon Valley Bank verschoben Einleger innerhalb weniger Tage Milliarden Dollar in höher verzinste Geldmarktfonds, mit nur wenigen Taps in einer Smartphone-App, und entzogen den Banken so nahezu über Nacht Liquidität. Die auf „Rewards" basierende indirekte Rendite der Stablecoins ist wohl die krypto-native Version genau dieses Hot-Money-Fluchtrisikos — der einzige wirkliche Unterschied besteht heute darin, dass die Fluchtroute eine On-Chain-Wallet statt eines regulierten Geldmarktfonds ist.</p>
<p class="fr">Les banques semblent traiter cette question comme existentielle plutôt que comme un simple différend concurrentiel entre produits, probablement en raison des leçons tirées de la crise bancaire régionale américaine de 2023. Lors de l'effondrement de la Silicon Valley Bank, les déposants ont transféré des milliards de dollars vers des fonds du marché monétaire à rendement plus élevé en quelques jours, en quelques clics sur une application de smartphone, asséchant la liquidité bancaire presque du jour au lendemain. Le rendement indirect des stablecoins fondé sur les « récompenses » constitue sans doute la version native de la crypto de ce même risque de fuite d'argent chaud — la seule vraie différence aujourd'hui est que la voie de sortie est un portefeuille on-chain plutôt qu'un fonds du marché monétaire réglementé.</p>
<p class="pt">Os bancos parecem tratar isso como uma questão existencial, e não como uma disputa menor de concorrência entre produtos, provavelmente por causa das lições aprendidas com a crise bancária regional americana de 2023. Durante o colapso do Silicon Valley Bank, os depositantes transferiram bilhões de dólares para fundos do mercado monetário de maior rendimento em questão de dias, com apenas alguns toques em um aplicativo de smartphone, drenando a liquidez bancária quase da noite para o dia. O rendimento indireto das stablecoins baseado em "recompensas" é, sem dúvida, a versão nativa cripto desse mesmo risco de fuga de dinheiro especulativo — a única diferença real agora é que a rota de saída é uma carteira on-chain, em vez de um fundo do mercado monetário regulado.</p>
<p class="tr">Bankalar bunu küçük bir ürün rekabeti anlaşmazlığı değil, varoluşsal bir mesele olarak ele alıyor gibi görünüyor; bunun nedeni büyük olasılıkla 2023 ABD bölgesel bankacılık krizinden çıkarılan derslerdir. Silicon Valley Bank'ın çöküşü sırasında, mevduat sahipleri bir akıllı telefon uygulamasında sadece birkaç dokunuşla, günler içinde milyarlarca doları daha yüksek getirili para piyasası fonlarına taşıdı ve bu da banka likiditesini neredeyse bir gecede kuruttu. Stablecoinlerin ödül temelli dolaylı getirisi, muhtemelen aynı "sıcak para" kaçış riskinin kripto yerlisi versiyonudur — buradaki tek gerçek fark, çıkış yolunun düzenlenmiş bir para piyasası fonu değil, zincir üstü bir cüzdan olmasıdır.</p>
<p class="vi">Các ngân hàng dường như coi đây là một vấn đề sống còn chứ không phải một tranh chấp cạnh tranh sản phẩm nhỏ nhặt, có lẽ do những bài học rút ra từ cuộc khủng hoảng ngân hàng khu vực Mỹ năm 2023. Trong vụ sụp đổ của Silicon Valley Bank, người gửi tiền đã chuyển hàng tỷ đô la sang các quỹ thị trường tiền tệ có lợi suất cao hơn chỉ trong vài ngày, chỉ bằng vài cú chạm trên ứng dụng điện thoại thông minh, khiến thanh khoản ngân hàng cạn kiệt gần như chỉ sau một đêm. Lợi suất gián tiếp dựa trên "phần thưởng" của stablecoin có thể coi là phiên bản gốc tiền mã hóa của chính rủi ro tháo chạy dòng tiền nóng đó — khác biệt thực sự duy nhất bây giờ là lối thoát là một chiếc ví on-chain thay vì một quỹ thị trường tiền tệ được quản lý.</p>

<p class="ko">더 오래된 선례를 찾자면 1950~60년대 유로달러 시장의 등장이 있다. 당시 미국의 레귤레이션Q(Regulation Q)가 국내 예금금리에 상한을 두자, 자본은 그 규제망 밖인 역외 시장으로 빠져나가 더 높은 수익을 좇았다. 이는 규제가 특정 수익률에 상한을 두면, 자금은 규제의 문언이 닿지 않는 인접 영역을 찾아 흘러간다는 반복되는 패턴을 보여준다. 스테이블코인의 '리워드' 우회 역시 GENIUS법의 정확한 문구, 즉 '발행사'에만 국한된 금지 조항이 낳은 사실상 예견된 규제차익 현상이라는 해석이 가능하다.</p>
<p class="en">An even older precedent is the emergence of the Eurodollar market in the 1950s and 1960s. When US Regulation Q capped domestic deposit interest rates, capital fled offshore, beyond the reach of that regulatory perimeter, chasing higher returns. That episode illustrates a recurring pattern: whenever regulation caps a particular yield, money finds an adjacent space the rule's wording doesn't reach. Stablecoins' rewards-based workaround can arguably be read the same way — a largely predictable instance of regulatory arbitrage born from the GENIUS Act's precise wording, which restricts only "issuers."</p>
<p class="ja">さらに古い先例としては、1950~60年代のユーロダラー市場の誕生がある。当時、米国のレギュレーションQ(Regulation Q)が国内預金金利に上限を設けると、資本はその規制網の外側であるオフショア市場へと逃避し、より高い収益を追い求めた。この出来事は、規制が特定の利回りに上限を設けると、資金は規制の文言が及ばない隣接領域を見つけて流れ込む、という繰り返されるパターンを示している。ステーブルコインの「リワード」型迂回もまた、GENIUS法の正確な文言 ── すなわち「発行体」のみを対象とした禁止条項 ── が生んだ、ほぼ予見可能な規制裁定の一例だと解釈できる。</p>
<p class="es">Un precedente aún más antiguo es la aparición del mercado del eurodólar en las décadas de 1950 y 1960. Cuando la Regulación Q de EE. UU. impuso un tope a las tasas de interés de los depósitos domésticos, el capital huyó al extranjero, más allá del alcance de ese perímetro regulatorio, en busca de mayores rendimientos. Ese episodio ilustra un patrón recurrente: cada vez que una regulación pone un tope a un determinado rendimiento, el dinero encuentra un espacio adyacente que la letra de la norma no alcanza. El rodeo basado en "recompensas" de las stablecoins puede interpretarse de la misma manera: un caso de arbitraje regulatorio en gran medida previsible, nacido de la redacción precisa de la GENIUS Act, que restringe únicamente a los "emisores".</p>
<p class="de">Ein noch älterer Präzedenzfall ist die Entstehung des Eurodollar-Marktes in den 1950er- und 1960er-Jahren. Als die US-Regulation Q die inländischen Einlagenzinsen deckelte, floh Kapital offshore, außerhalb der Reichweite dieses Regulierungsperimeters, auf der Suche nach höheren Renditen. Diese Episode veranschaulicht ein wiederkehrendes Muster: Sobald eine Regulierung eine bestimmte Rendite deckelt, findet Geld einen benachbarten Raum, den der Wortlaut der Regel nicht erreicht. Der auf „Rewards" basierende Umweg der Stablecoins lässt sich ebenso deuten — als weitgehend vorhersehbarer Fall regulatorischer Arbitrage, entstanden aus dem präzisen Wortlaut des GENIUS Act, der nur „Emittenten" einschränkt.</p>
<p class="fr">Un précédent encore plus ancien est l'apparition du marché de l'eurodollar dans les années 1950 et 1960. Lorsque la Regulation Q américaine a plafonné les taux d'intérêt des dépôts domestiques, les capitaux ont fui vers l'offshore, hors de portée de ce périmètre réglementaire, à la recherche de rendements plus élevés. Cet épisode illustre un schéma récurrent : dès qu'une réglementation plafonne un rendement donné, l'argent trouve un espace adjacent que la lettre de la règle n'atteint pas. Le contournement des stablecoins fondé sur les « récompenses » peut être lu de la même façon — un cas d'arbitrage réglementaire largement prévisible, né de la formulation précise du GENIUS Act, qui ne restreint que les « émetteurs ».</p>
<p class="pt">Um precedente ainda mais antigo é o surgimento do mercado do eurodólar nas décadas de 1950 e 1960. Quando a Regulation Q dos EUA limitou as taxas de juros de depósitos domésticos, o capital fugiu para o exterior, além do alcance daquele perímetro regulatório, em busca de retornos mais altos. Esse episódio ilustra um padrão recorrente: sempre que uma regulação limita determinado rendimento, o dinheiro encontra um espaço adjacente que a letra da norma não alcança. O contorno das stablecoins baseado em "recompensas" pode ser lido da mesma forma — um caso, em grande parte previsível, de arbitragem regulatória nascido da redação precisa da GENIUS Act, que restringe apenas os "emissores".</p>
<p class="tr">Daha da eski bir emsal, 1950'ler ve 1960'larda Eurodolar piyasasının ortaya çıkışıdır. ABD'nin Regulation Q düzenlemesi yurt içi mevduat faiz oranlarına tavan koyduğunda, sermaye bu düzenleyici çerçevenin ulaşamayacağı offshore piyasalara kaçarak daha yüksek getiri peşinde koştu. Bu olay, tekrar eden bir örüntüyü gösteriyor: bir düzenleme belirli bir getiriye tavan koyduğunda, para, kuralın lafzının ulaşamadığı bitişik bir alan buluyor. Stablecoinlerin ödül temelli dolambaçlı yolu da aynı şekilde okunabilir — yalnızca "ihraççıları" kısıtlayan GENIUS Yasası'nın kesin lafzından doğan, büyük ölçüde öngörülebilir bir düzenleyici arbitraj örneği.</p>
<p class="vi">Một tiền lệ thậm chí còn xa xưa hơn là sự ra đời của thị trường Eurodollar vào những năm 1950 và 1960. Khi Quy định Q của Hoa Kỳ áp trần lãi suất tiền gửi trong nước, dòng vốn đã chạy ra nước ngoài, vượt ra ngoài phạm vi quản lý đó, để tìm kiếm lợi suất cao hơn. Sự việc đó minh họa một khuôn mẫu lặp lại: bất cứ khi nào quy định áp trần một mức lợi suất nhất định, dòng tiền sẽ tìm ra một khoảng không gian liền kề mà câu chữ của quy định không vươn tới. Cách lách luật dựa trên "phần thưởng" của stablecoin cũng có thể được hiểu theo cách tương tự — một trường hợp phần lớn có thể dự đoán trước của hoạt động chênh lệch quy định, sinh ra từ câu chữ chính xác của Đạo luật GENIUS, vốn chỉ giới hạn ở "các tổ chức phát hành".</p>

<div class="ko">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">규모로 본 스테이블코인 시장 — 현재 vs. 시나리오</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">단위: 1조달러</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">현재 실제 시가총액 (2026년7월): 약 0.26조달러</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">베선트 재무장관 2030년 전망: 3조달러</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">재무부 최악 시나리오 예금이탈: 6.6조달러</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">막대 길이는 서로 다른 기준(시총·성장전망·잠재손실)의 수치이며 직접 비교용이 아님</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">은행권 반격의 두 축</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① 규제 로비: 40여개 은행단체 → 리워드형 우회 이자 금지 확대 요구</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② 인프라 구축: JP모건·씨티·BoA·웰스파고 등 <tspan fill="#34d399" font-weight="700">2027년 상반기</tspan> 토큰화 예금망 목표</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ 지역은행: 카리 네트워크, <tspan fill="#34d399" font-weight="700">2026년 3분기</tspan> 파일럿 · <tspan fill="#34d399" font-weight="700">4분기</tspan> 고객 출시</text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">OCC는 2월25일 간접 수익 지급에 '반증 가능한 위법 추정' 규칙 초안 발표</text>
</svg>
</div>
<div class="en">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Stablecoin Market Scale — Actual vs. Scenarios</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Units: $ trillion</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">Actual market cap today (Jul 2026): ~$0.26T</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">Bessent's 2030 growth projection: $3T</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">Treasury's worst-case deposit outflow: $6.6T</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">Bar lengths reflect different metrics (market cap, growth forecast, potential loss) — not directly comparable</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">The Banks' Two-Pronged Counteroffensive</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① Regulatory lobbying: 40+ banking groups push to extend the rewards-yield ban</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② Infrastructure: JPMorgan, Citi, BofA, Wells Fargo target <tspan fill="#34d399" font-weight="700">1H 2027</tspan> for a tokenized deposit network</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ Regional banks: Cari Network, <tspan fill="#34d399" font-weight="700">Q3 2026</tspan> pilot · <tspan fill="#34d399" font-weight="700">Q4</tspan> customer launch</text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">OCC proposed a rule on Feb 25 applying a "rebuttable presumption" against indirect yield</text>
</svg>
</div>
<div class="ja">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">ステーブルコイン市場の規模 — 実際の数値とシナリオ</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">単位:兆ドル</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">現在の実際の時価総額(2026年7月):約0.26兆ドル</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">ベサント財務長官の2030年成長予測:3兆ドル</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">財務省の最悪シナリオ預金流出:6.6兆ドル</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">バーの長さは異なる指標(時価総額・成長予測・潜在的損失)であり、直接比較はできない</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">銀行の反撃、二つの軸</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① 規制ロビー活動:40超の銀行団体がリワード型迂回利息の禁止拡大を要求</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② インフラ構築:JPモルガン・シティ・BoA・ウェルズファーゴなど<tspan fill="#34d399" font-weight="700">2027年上半期</tspan>目標のトークン化預金網</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ 地方銀行:カリ・ネットワーク、<tspan fill="#34d399" font-weight="700">2026年第3四半期</tspan>パイロット・<tspan fill="#34d399" font-weight="700">第4四半期</tspan>顧客向け開始</text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">OCCは2月25日、間接的な収益還元に「反証可能な違法推定」を適用する規則案を発表</text>
</svg>
</div>
<div class="es">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Escala del Mercado de Stablecoins — Real vs. Escenarios</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Unidades: billones de USD</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">Capitalización real actual (jul. 2026): ~0,26 billones de USD</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">Proyección de Bessent para 2030: 3 billones de USD</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">Peor escenario de fuga de depósitos del Tesoro: 6,6 billones de USD</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">Las longitudes de las barras reflejan métricas distintas (capitalización, previsión, pérdida potencial), no comparables directamente</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">Los Dos Frentes del Contraataque Bancario</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① Presión regulatoria: 40+ grupos bancarios buscan ampliar la prohibición de rendimiento por recompensas</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② Infraestructura: JPMorgan, Citi, BofA, Wells Fargo apuntan al <tspan fill="#34d399" font-weight="700">1S 2027</tspan> para una red de depósitos tokenizados</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ Bancos regionales: Cari Network, piloto en el <tspan fill="#34d399" font-weight="700">T3 2026</tspan> · lanzamiento en el <tspan fill="#34d399" font-weight="700">T4</tspan></text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">La OCC propuso el 25 de febrero una regla con "presunción refutable" contra el rendimiento indirecto</text>
</svg>
</div>
<div class="de">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Stablecoin-Marktgröße — Ist-Wert vs. Szenarien</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Einheit: Billionen USD</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">Tatsächliche Marktkapitalisierung heute (Jul. 2026): ~0,26 Bio. USD</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">Bessents Wachstumsprognose für 2030: 3 Bio. USD</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">Schlimmster Einlagenabfluss laut Finanzministerium: 6,6 Bio. USD</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">Balkenlängen zeigen unterschiedliche Kennzahlen (Marktkap., Prognose, Verlustpotenzial) — nicht direkt vergleichbar</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">Die Zwei Stoßrichtungen der Bankengegenoffensive</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① Regulierungslobbying: 40+ Bankenverbände drängen auf Ausweitung des Rewards-Renditeverbots</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② Infrastruktur: JPMorgan, Citi, BofA, Wells Fargo peilen <tspan fill="#34d399" font-weight="700">1. Hälfte 2027</tspan> für tokenisiertes Einlagennetzwerk an</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ Regionalbanken: Cari Network, Pilot <tspan fill="#34d399" font-weight="700">Q3 2026</tspan> · Kundenstart <tspan fill="#34d399" font-weight="700">Q4</tspan></text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">OCC schlug am 25. Februar eine Regel mit „widerlegbarer Vermutung" gegen indirekte Rendite vor</text>
</svg>
</div>
<div class="fr">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Taille du Marché des Stablecoins — Réel vs. Scénarios</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Unités : billions de USD</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">Capitalisation réelle actuelle (juil. 2026) : ~0,26 billion USD</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">Prévision de croissance de Bessent pour 2030 : 3 billions USD</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">Pire scénario de fuite des dépôts du Trésor : 6 600 milliards USD</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">Les longueurs de barres reflètent des indicateurs différents (capitalisation, prévision, perte potentielle) — non comparables directement</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">Les Deux Volets de la Contre-Offensive Bancaire</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① Lobbying réglementaire : 40+ groupes bancaires cherchent à étendre l'interdiction sur le rendement via récompenses</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② Infrastructure : JPMorgan, Citi, BofA, Wells Fargo visent le <tspan fill="#34d399" font-weight="700">1er semestre 2027</tspan> pour un réseau de dépôts tokenisés</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ Banques régionales : Cari Network, pilote au <tspan fill="#34d399" font-weight="700">T3 2026</tspan> · lancement client au <tspan fill="#34d399" font-weight="700">T4</tspan></text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">L'OCC a proposé le 25 février une règle de « présomption réfutable » contre le rendement indirect</text>
</svg>
</div>
<div class="pt">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Escala do Mercado de Stablecoins — Real vs. Cenários</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Unidades: trilhões de USD</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">Capitalização real atual (jul. 2026): ~US$ 0,26 tri</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">Projeção de Bessent para 2030: US$ 3 tri</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">Pior cenário de fuga de depósitos do Tesouro: US$ 6,6 tri</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">Os comprimentos das barras refletem métricas diferentes (capitalização, projeção, perda potencial) — não comparáveis diretamente</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">As Duas Frentes da Contraofensiva dos Bancos</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① Pressão regulatória: 40+ grupos bancários buscam ampliar a proibição de rendimento via recompensas</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② Infraestrutura: JPMorgan, Citi, BofA, Wells Fargo miram o <tspan fill="#34d399" font-weight="700">1º semestre de 2027</tspan> para uma rede de depósitos tokenizados</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ Bancos regionais: Cari Network, piloto no <tspan fill="#34d399" font-weight="700">3º tri de 2026</tspan> · lançamento no <tspan fill="#34d399" font-weight="700">4º tri</tspan></text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">Em 25 de fevereiro, o OCC propôs uma regra de "presunção refutável" contra o rendimento indireto</text>
</svg>
</div>
<div class="tr">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Stablecoin Piyasası Büyüklüğü — Gerçek vs. Senaryolar</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Birim: trilyon USD</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">Bugünkü gerçek piyasa değeri (Tem. 2026): ~0,26 trilyon USD</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">Bessent'in 2030 büyüme öngörüsü: 3 trilyon USD</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">Hazine'nin en kötü senaryo mevduat çıkışı: 6,6 trilyon USD</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">Çubuk uzunlukları farklı ölçütleri (piyasa değeri, büyüme tahmini, potansiyel kayıp) yansıtır — doğrudan karşılaştırılamaz</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">Bankaların Karşı Saldırısının İki Cephesi</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① Düzenleyici lobicilik: 40+ bankacılık grubu ödül temelli getiri yasağının genişletilmesini istiyor</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② Altyapı: JPMorgan, Citi, BofA, Wells Fargo tokenleştirilmiş mevduat ağı için <tspan fill="#34d399" font-weight="700">2027 1. yarı</tspan>yı hedefliyor</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ Bölgesel bankalar: Cari Network, <tspan fill="#34d399" font-weight="700">2026 3Ç</tspan> pilot · <tspan fill="#34d399" font-weight="700">4Ç</tspan> müşteri lansmanı</text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">OCC, 25 Şubat'ta dolaylı getiriye karşı "çürütülebilir karine" öneren bir kural yayımladı</text>
</svg>
</div>
<div class="vi">
<svg viewBox="0 0 700 440" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="30" fill="#fafafa" font-size="16" font-weight="700" font-family="sans-serif">Quy Mô Thị Trường Stablecoin — Thực Tế So Với Kịch Bản</text>
  <text x="20" y="50" fill="#71717a" font-size="13" font-family="sans-serif">Đơn vị: nghìn tỷ USD</text>
  <rect x="40" y="90" width="30" height="20" fill="#38bdf8"/>
  <text x="80" y="105" fill="#e4e4e7" font-size="14" font-family="sans-serif">Vốn hóa thực tế hiện nay (7/2026): ~0,26 nghìn tỷ USD</text>
  <rect x="40" y="130" width="90" height="20" fill="#fbbf24"/>
  <text x="140" y="145" fill="#e4e4e7" font-size="14" font-family="sans-serif">Dự báo tăng trưởng đến 2030 của Bessent: 3 nghìn tỷ USD</text>
  <rect x="40" y="170" width="200" height="20" fill="#f87171"/>
  <text x="250" y="185" fill="#e4e4e7" font-size="14" font-family="sans-serif">Kịch bản xấu nhất về rút tiền gửi của Bộ Tài chính: 6,6 nghìn tỷ USD</text>
  <line x1="40" y1="220" x2="660" y2="220" stroke="#3f3f46" stroke-width="1"/>
  <text x="40" y="245" fill="#a1a1aa" font-size="13" font-family="sans-serif">Độ dài các thanh phản ánh các chỉ số khác nhau (vốn hóa, dự báo tăng trưởng, tổn thất tiềm tàng) — không so sánh trực tiếp được</text>
  <rect x="20" y="270" width="660" height="140" rx="8" fill="#18181b" stroke="#3f3f46"/>
  <text x="36" y="296" fill="#f2f2f5" font-size="14" font-weight="700" font-family="sans-serif">Hai Mũi Nhọn Phản Công Của Ngân Hàng</text>
  <text x="36" y="322" fill="#a1a1aa" font-size="13" font-family="sans-serif">① Vận động hành lang: 40+ nhóm ngân hàng thúc đẩy mở rộng lệnh cấm lợi suất kiểu phần thưởng</text>
  <text x="36" y="346" fill="#a1a1aa" font-size="13" font-family="sans-serif">② Hạ tầng: JPMorgan, Citi, BofA, Wells Fargo nhắm đến <tspan fill="#34d399" font-weight="700">nửa đầu 2027</tspan> cho mạng lưới tiền gửi token hóa</text>
  <text x="36" y="370" fill="#a1a1aa" font-size="13" font-family="sans-serif">③ Ngân hàng khu vực: Cari Network, thí điểm <tspan fill="#34d399" font-weight="700">Q3/2026</tspan> · ra mắt khách hàng <tspan fill="#34d399" font-weight="700">Q4</tspan></text>
  <text x="36" y="394" fill="#71717a" font-size="12" font-family="sans-serif">OCC đề xuất quy định ngày 25/2 áp dụng "giả định có thể bác bỏ" với lợi suất gián tiếp</text>
</svg>
</div>

<h2 class="ko">지켜봐야 할 것과 반론 — '3천억달러 붐'은 아직 증명되지 않았다</h2>
<h2 class="en">What to Watch and a Counter-Argument — the "Boom" Hasn't Actually Been Proven Yet</h2>
<h2 class="ja">注視すべき点と反論 — 「ブーム」はまだ証明されていない</h2>
<h2 class="es">Qué Vigilar y un Contraargumento — el "Boom" Aún No Está Demostrado</h2>
<h2 class="de">Worauf zu Achten Ist, und ein Gegenargument — der „Boom" Ist Noch Nicht Belegt</h2>
<h2 class="fr">Points à Surveiller et Contre-Argument — le « Boom » n'est Pas Encore Prouvé</h2>
<h2 class="pt">O Que Observar e um Contra-Argumento — o "Boom" Ainda Não Foi Comprovado</h2>
<h2 class="tr">İzlenmesi Gerekenler ve Bir Karşı Argüman — "Patlama" Henüz Kanıtlanmadı</h2>
<h2 class="vi">Điều Cần Theo Dõi Và Một Lập Luận Phản Biện — "Sự Bùng Nổ" Vẫn Chưa Được Chứng Minh</h2>

<p class="ko">앞으로 지켜봐야 할 지점은 세 가지다. 첫째, 의회나 OCC가 실제로 리워드형 우회 수익 지급의 허점을 완전히 봉쇄할 것인지, 아니면 포브스가 'GENIUS법의 코인베이스 모양 구멍'이라 부른 것처럼 거래소 측이 법정에서 이의를 제기해 무산될 것인지다. 둘째, 2027년 상반기로 예정된 토큰화 예금망이 실제로 정산 마찰을 의미 있게 줄일지, 아니면 어차피 은행 허가제 네트워크라는 폐쇄성 때문에 공개형 스테이블코인만큼의 유연성을 갖지 못할지다. 셋째, 재무부가 제시한 6조6,000억달러라는 최악 시나리오가 실제로는 지나치게 경고성이었던 것으로 판명될지, 아니면 베선트 재무장관이 언급한 3조달러(2030년)라는 상대적으로 온건한 성장 전망이 더 현실에 가까운 것으로 드러날지다.</p>
<p class="en">Three things are worth watching from here. First, whether Congress or the OCC actually manages to close the rewards-based yield loophole completely, or whether it gets unwound by exchanges challenging it in court — what Forbes has called the "Coinbase-shaped hole" in the GENIUS Act. Second, whether the tokenized deposit network targeted for the first half of 2027 actually reduces settlement friction in a meaningful way, or whether its bank-permissioned, closed-network nature keeps it less flexible than public stablecoins regardless. Third, whether the Treasury's worst-case $6.6 trillion deposit-outflow estimate turns out to have been alarmist, or whether Treasury Secretary Bessent's comparatively modest $3 trillion growth projection for 2030 proves closer to reality.</p>
<p class="ja">今後注視すべき点は三つある。第一に、議会やOCCが実際にリワード型迂回収益の抜け穴を完全に封じ込められるのか、それともフォーブスが「GENIUS法のコインベース型の穴」と呼んだように、取引所側が法廷で異議を申し立てて骨抜きにされるのかだ。第二に、2027年上半期を目標とするトークン化預金網が実際に決済摩擦を意味あるレベルで削減できるのか、それとも銀行許可制で閉じたネットワークであるがゆえに、公開型ステーブルコインほどの柔軟性を持てないままなのかだ。第三に、財務省が示した6兆6,000億ドルという最悪シナリオが実際には過度に警鐘的なものだったと判明するのか、それともベサント財務長官が言及した3兆ドル(2030年)という比較的穏やかな成長予測の方が現実に近いことが明らかになるのかだ。</p>
<p class="es">De cara al futuro, hay tres cosas que vale la pena vigilar. Primero, si el Congreso o la OCC logran realmente cerrar por completo el vacío legal del rendimiento basado en recompensas, o si termina siendo desmontado por exchanges que lo impugnen en los tribunales —lo que Forbes ha llamado el "agujero con forma de Coinbase" en la GENIUS Act—. Segundo, si la red de depósitos tokenizados prevista para el primer semestre de 2027 realmente reduce la fricción de liquidación de forma significativa, o si su naturaleza de red cerrada y con permiso bancario la mantiene, en cualquier caso, menos flexible que las stablecoins públicas. Tercero, si la estimación del peor escenario del Tesoro, 6,6 billones de dólares en fuga de depósitos, termina resultando alarmista, o si la proyección de crecimiento comparativamente moderada de 3 billones de dólares para 2030, mencionada por el secretario Bessent, resulta más cercana a la realidad.</p>
<p class="de">Drei Dinge lohnt es sich von hier an zu beobachten. Erstens, ob Kongress oder OCC das auf Rewards basierende Renditeschlupfloch tatsächlich vollständig schließen können, oder ob es durch Börsen, die es vor Gericht anfechten, wieder aufgeweicht wird — das, was Forbes das „Coinbase-förmige Loch" im GENIUS Act genannt hat. Zweitens, ob das für die erste Hälfte 2027 angepeilte tokenisierte Einlagennetzwerk tatsächlich die Abwicklungsreibung spürbar verringert, oder ob es aufgrund seiner bankgenehmigten, geschlossenen Netzwerkstruktur ohnehin weniger flexibel bleibt als öffentliche Stablecoins. Drittens, ob sich die Worst-Case-Schätzung des Finanzministeriums von 6,6 Billionen Dollar Einlagenabfluss als alarmistisch herausstellt, oder ob sich Finanzminister Bessents vergleichsweise moderate Wachstumsprognose von 3 Billionen Dollar bis 2030 als näher an der Realität erweist.</p>
<p class="fr">Trois éléments méritent d'être surveillés à partir de maintenant. Premièrement, si le Congrès ou l'OCC parviennent réellement à combler entièrement la faille du rendement fondé sur les récompenses, ou si elle est démantelée par des plateformes d'échange la contestant devant les tribunaux — ce que Forbes a appelé le « trou en forme de Coinbase » du GENIUS Act. Deuxièmement, si le réseau de dépôts tokenisés visé pour le premier semestre 2027 réduit réellement la friction de règlement de façon significative, ou si sa nature de réseau fermé et autorisé par les banques le maintient de toute façon moins flexible que les stablecoins publics. Troisièmement, si l'estimation du pire scénario du Trésor, 6 600 milliards de dollars de fuite de dépôts, se révèle avoir été alarmiste, ou si la prévision de croissance relativement modeste de 3 000 milliards de dollars d'ici 2030 évoquée par le secrétaire Bessent se révèle plus proche de la réalité.</p>
<p class="pt">Três coisas merecem atenção daqui para frente. Primeiro, se o Congresso ou o OCC conseguem realmente fechar por completo a brecha do rendimento baseado em recompensas, ou se ela acaba sendo desfeita por exchanges que a contestam na justiça — o que a Forbes chamou de "buraco em formato Coinbase" na GENIUS Act. Segundo, se a rede de depósitos tokenizados prevista para o primeiro semestre de 2027 realmente reduz o atrito de liquidação de forma significativa, ou se sua natureza de rede fechada e autorizada por bancos a mantém, de todo modo, menos flexível do que as stablecoins públicas. Terceiro, se a estimativa de pior cenário do Tesouro, de US$ 6,6 trilhões em fuga de depósitos, acaba se revelando alarmista, ou se a projeção de crescimento comparativamente modesta de US$ 3 trilhões até 2030, mencionada pelo secretário Bessent, se mostra mais próxima da realidade.</p>
<p class="tr">Buradan itibaren izlenmesi gereken üç şey var. Birincisi, Kongre'nin ya da OCC'nin ödül temelli getiri boşluğunu gerçekten tamamen kapatıp kapatamayacağı, yoksa Forbes'un GENIUS Yasası'ndaki "Coinbase şeklinde delik" dediği şekilde borsaların bunu mahkemede itiraz ederek boşa çıkarıp çıkarmayacağı. İkincisi, 2027'nin ilk yarısı için hedeflenen tokenleştirilmiş mevduat ağının takas sürtünmesini gerçekten anlamlı ölçüde azaltıp azaltmayacağı, yoksa banka izinli, kapalı ağ yapısı nedeniyle her hâlükârda kamuya açık stablecoinler kadar esnek kalamayacağı. Üçüncüsü, Hazine'nin en kötü senaryo tahmini olan 6,6 trilyon dolarlık mevduat çıkışının aşırı alarmcı çıkıp çıkmayacağı, yoksa Bakan Bessent'in belirttiği görece mütevazı 3 trilyon dolarlık (2030) büyüme öngörüsünün gerçeğe daha yakın olduğunun ortaya çıkıp çıkmayacağı.</p>
<p class="vi">Có ba điều đáng theo dõi từ đây. Thứ nhất, liệu Quốc hội hay OCC có thực sự bịt kín hoàn toàn lỗ hổng lợi suất kiểu phần thưởng hay không, hay nó sẽ bị các sàn giao dịch phá vỡ bằng cách khởi kiện — điều mà Forbes gọi là "lỗ hổng hình Coinbase" trong Đạo luật GENIUS. Thứ hai, liệu mạng lưới tiền gửi token hóa dự kiến cho nửa đầu năm 2027 có thực sự giảm ma sát quyết toán một cách đáng kể hay không, hay bản chất mạng lưới đóng, được ngân hàng cấp phép của nó vẫn khiến nó kém linh hoạt hơn stablecoin công khai dù thế nào đi nữa. Thứ ba, liệu ước tính kịch bản xấu nhất của Bộ Tài chính, 6,6 nghìn tỷ đô la dòng tiền gửi rút ra, có thực sự chỉ mang tính báo động thái quá, hay dự báo tăng trưởng tương đối khiêm tốn 3 nghìn tỷ đô la vào năm 2030 mà Bộ trưởng Bessent đề cập lại gần với thực tế hơn.</p>

<p class="ko">반론도 짚고 넘어갈 필요가 있다. 은행권이 위기감을 과장하고 있다고 볼 여지도 충분하다 — <a href="/blog/stablecoin-market-cap-10b-shrink-tether-usdc">스테이블코인 시가총액은 오히려 지난 5월 이후 100억달러 줄어들었다는 보도가 이미 나온 상황</a>이라, 일부 매체가 쓰는 '3천억달러 붐'이라는 표현 자체가 시기상조일 수 있다. 게다가 대형은행들의 토큰화 예금망은 2027년 상반기에야 가동될 예정인데, 이는 스테이블코인 업계의 상품 반복 속도에 비하면 상당히 느린 편이다. 결국 로비를 통한 규제 승리를 거두더라도, 소매 결제 속도 경쟁에서는 이미 뒤처진 채로 시작하게 될 수 있다는 점에서, 이번 반격이 실제로 예금 이탈을 막아낼 수 있을지는 아직 열린 질문으로 남아 있다는 것이 필자의 판단이다.</p>
<p class="en">A counter-argument is worth raising here too. There's a reasonable case that banks are overstating the sense of crisis — <a href="/en/blog/stablecoin-market-cap-10b-shrink-tether-usdc">reporting has already shown the stablecoin market cap actually shrank by $10 billion since May</a>, which makes the "trillion-dollar boom" framing used by some coverage look premature. On top of that, the big banks' tokenized deposit network isn't due to launch until the first half of 2027, which is fairly slow compared to the pace at which stablecoin products iterate. Even if the lobbying effort wins on the regulatory front, banks could still start the retail-payment speed race already behind — which is why, in my assessment, whether this counteroffensive actually stops deposit flight remains an open question.</p>
<p class="ja">反論についても触れておく必要がある。銀行界が危機感を過大に演出しているという見方にも十分な根拠がある — <a href="/ja/blog/stablecoin-market-cap-10b-shrink-tether-usdc">ステーブルコインの時価総額はむしろ5月以降100億ドル減少したとの報道がすでに出ている</a>状況であり、一部メディアが使う「3,000億ドルのブーム」という表現自体が時期尚早である可能性がある。さらに、大手銀行のトークン化預金網は2027年上半期にようやく稼働する予定であり、これはステーブルコイン業界の商品反復速度に比べればかなり遅い。結局、ロビー活動によって規制面での勝利を収めたとしても、小売決済の速度競争では既に出遅れた状態でスタートすることになりかねない、という点で、今回の反撃が実際に預金流出を食い止められるかどうかはまだ開かれた問いのままだ、というのが筆者の判断だ。</p>
<p class="es">También conviene plantear un contraargumento. Hay razones para pensar que los bancos están exagerando la sensación de crisis — <a href="/es/blog/stablecoin-market-cap-10b-shrink-tether-usdc">informes ya han mostrado que la capitalización de mercado de las stablecoins en realidad se contrajo en 10.000 millones de dólares desde mayo</a>, lo que hace que el marco del "boom de un billón de dólares" usado por algunos medios parezca prematuro. Además, la red de depósitos tokenizados de los grandes bancos no está prevista para lanzarse hasta el primer semestre de 2027, un ritmo bastante lento comparado con la velocidad de iteración de los productos de stablecoins. Incluso si el esfuerzo de cabildeo logra una victoria regulatoria, los bancos podrían de todos modos empezar ya rezagados en la carrera de velocidad de pagos minoristas — por lo que, en mi valoración, si este contraataque logrará realmente detener la fuga de depósitos sigue siendo una pregunta abierta.</p>
<p class="de">Auch ein Gegenargument verdient hier Erwähnung. Es gibt durchaus Gründe anzunehmen, dass Banken das Krisengefühl übertreiben — <a href="/de/blog/stablecoin-market-cap-10b-shrink-tether-usdc">Berichte haben bereits gezeigt, dass die Marktkapitalisierung von Stablecoins seit Mai tatsächlich um 10 Milliarden Dollar geschrumpft ist</a>, was den von manchen Medien verwendeten Rahmen des „Billionen-Dollar-Booms" verfrüht erscheinen lässt. Hinzu kommt, dass das tokenisierte Einlagennetzwerk der Großbanken erst in der ersten Hälfte 2027 starten soll — recht langsam im Vergleich zu dem Tempo, in dem sich Stablecoin-Produkte weiterentwickeln. Selbst wenn die Lobbyarbeit auf regulatorischer Ebene einen Sieg erringt, könnten Banken im Wettlauf um Geschwindigkeit bei Privatkundenzahlungen bereits im Rückstand starten — weshalb meiner Einschätzung nach offen bleibt, ob diese Gegenoffensive die Einlagenflucht tatsächlich stoppen kann.</p>
<p class="fr">Un contre-argument mérite également d'être soulevé ici. Il existe des raisons valables de penser que les banques exagèrent le sentiment de crise — <a href="/fr/blog/stablecoin-market-cap-10b-shrink-tether-usdc">des articles ont déjà montré que la capitalisation du marché des stablecoins a en réalité diminué de 10 milliards de dollars depuis mai</a>, ce qui rend le cadrage du « boom à mille milliards de dollars » utilisé par certains médias prématuré. De plus, le réseau de dépôts tokenisés des grandes banques ne doit être lancé qu'au premier semestre 2027, un rythme assez lent comparé à la vitesse d'itération des produits stablecoins. Même si l'effort de lobbying l'emporte sur le plan réglementaire, les banques pourraient malgré tout démarrer déjà en retard dans la course à la vitesse des paiements de détail — c'est pourquoi, à mon avis, la question de savoir si cette contre-offensive parviendra réellement à arrêter la fuite des dépôts reste ouverte.</p>
<p class="pt">Também vale a pena levantar um contra-argumento aqui. Há razão para achar que os bancos estão exagerando a sensação de crise — <a href="/pt/blog/stablecoin-market-cap-10b-shrink-tether-usdc">reportagens já mostraram que a capitalização de mercado das stablecoins na verdade encolheu US$ 10 bilhões desde maio</a>, o que torna o enquadramento de "boom de um trilhão de dólares" usado por parte da cobertura algo prematuro. Além disso, a rede de depósitos tokenizados dos grandes bancos só deve entrar em operação no primeiro semestre de 2027, um ritmo bastante lento em comparação à velocidade de iteração dos produtos de stablecoin. Mesmo que o esforço de lobby vença no front regulatório, os bancos ainda podem começar já atrás na corrida por velocidade nos pagamentos de varejo — motivo pelo qual, em minha avaliação, se essa contraofensiva realmente conterá a fuga de depósitos continua sendo uma questão em aberto.</p>
<p class="tr">Burada bir karşı argümanı da dile getirmekte fayda var. Bankaların kriz hissini abarttığını düşünmek için makul bir gerekçe var — <a href="/tr/blog/stablecoin-market-cap-10b-shrink-tether-usdc">haberler stablecoin piyasa değerinin Mayıs'tan bu yana aslında 10 milyar dolar küçüldüğünü zaten göstermişti</a>, bu da bazı haberlerde kullanılan "trilyon dolarlık patlama" çerçevesini erken göstermiş olabilir. Bunun üzerine, büyük bankaların tokenleştirilmiş mevduat ağı ancak 2027'nin ilk yarısında devreye girecek; bu da stablecoin ürünlerinin yinelenme hızına kıyasla oldukça yavaş. Lobi faaliyeti düzenleyici cephede zafer kazansa bile, bankalar perakende ödeme hız yarışına zaten geride başlamış olabilir — bu yüzden benim değerlendirmeme göre, bu karşı saldırının mevduat kaçışını gerçekten durdurup durduramayacağı açık bir soru olarak kalıyor.</p>
<p class="vi">Cũng cần nêu ra một lập luận phản biện ở đây. Có cơ sở hợp lý để cho rằng các ngân hàng đang phóng đại cảm giác khủng hoảng — <a href="/vi/blog/stablecoin-market-cap-10b-shrink-tether-usdc">các báo cáo đã cho thấy vốn hóa thị trường stablecoin thực ra đã co lại 10 tỷ đô la kể từ tháng 5</a>, khiến cách đóng khung "sự bùng nổ nghìn tỷ đô la" mà một số nguồn tin sử dụng có vẻ còn quá sớm. Thêm vào đó, mạng lưới tiền gửi token hóa của các ngân hàng lớn phải đến nửa đầu năm 2027 mới ra mắt, khá chậm so với tốc độ lặp lại sản phẩm của ngành stablecoin. Ngay cả khi nỗ lực vận động hành lang giành chiến thắng trên mặt trận quản lý, các ngân hàng vẫn có thể đã bắt đầu cuộc đua tốc độ thanh toán bán lẻ trong thế tụt hậu — đó là lý do tại sao, theo đánh giá của tôi, việc liệu cuộc phản công này có thực sự ngăn được dòng tiền gửi tháo chạy hay không vẫn là một câu hỏi còn bỏ ngỏ.</p>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 블룸버그(Bloomberg, "Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom"), 언체인드(Unchained, "JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins"), 코인데스크(CoinDesk, "JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network"), 더디파이언트(The Defiant, "Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network"), 핌츠(PYMNTS, "Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat"), 코인게이프(CoinGape, "Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate"), 포브스(Forbes, "The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole"), 코인데스크(CoinDesk, "Stablecoin market cap has shrunk by $10 billion since May"). 수치·일정은 각 매체 보도 시점 기준이다.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Bloomberg ("Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom"), Unchained ("JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins"), CoinDesk ("JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network"), The Defiant ("Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network"), PYMNTS ("Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat"), CoinGape ("Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate"), Forbes ("The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole"), CoinDesk ("Stablecoin market cap has shrunk by $10 billion since May"). Figures and timelines are as reported by each outlet at time of publication.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: ブルームバーグ(Bloomberg、「Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom」)、アンチェインド(Unchained、「JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins」)、コインデスク(CoinDesk、「JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network」)、ザ・ディファイアント(The Defiant、「Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network」)、ピムンツ(PYMNTS、「Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat」)、コインゲープ(CoinGape、「Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate」)、フォーブス(Forbes、「The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole」)、コインデスク(CoinDesk、「Stablecoin market cap has shrunk by $10 billion since May」)。数値・日程は各媒体の報道時点のものである。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: Bloomberg ("Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom"), Unchained ("JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins"), CoinDesk ("JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network"), The Defiant ("Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network"), PYMNTS ("Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat"), CoinGape ("Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate"), Forbes ("The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole"), CoinDesk ("Stablecoin market cap has shrunk by $10 billion since May"). Las cifras y los plazos corresponden al momento de publicación de cada medio.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: Bloomberg („Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom"), Unchained („JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins"), CoinDesk („JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network"), The Defiant („Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network"), PYMNTS („Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat"), CoinGape („Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate"), Forbes („The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole"), CoinDesk („Stablecoin market cap has shrunk by $10 billion since May"). Zahlen und Zeitpläne entsprechen dem jeweiligen Berichtszeitpunkt.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : Bloomberg (« Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom »), Unchained (« JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins »), CoinDesk (« JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network »), The Defiant (« Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network »), PYMNTS (« Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat »), CoinGape (« Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate »), Forbes (« The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole »), CoinDesk (« Stablecoin market cap has shrunk by $10 billion since May »). Les chiffres et les calendriers correspondent au moment de la publication de chaque média.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: Bloomberg ("Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom"), Unchained ("JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins"), CoinDesk ("JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network"), The Defiant ("Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network"), PYMNTS ("Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat"), CoinGape ("Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate"), Forbes ("The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole"), CoinDesk ("Stablecoin market cap has shrunk by $10 billion since May"). Números e prazos conforme reportados por cada veículo no momento da publicação.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: Bloomberg ("Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom"), Unchained ("JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins"), CoinDesk ("JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network"), The Defiant ("Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network"), PYMNTS ("Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat"), CoinGape ("Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate"), Forbes ("The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole"), CoinDesk ("Stablecoin market cap has shrunk by $10 billion since May"). Rakamlar ve takvimler her kaynağın yayın anına göredir.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: Bloomberg ("Wall Street Mounts Pushback on Trillion-Dollar Stablecoin Boom"), Unchained ("JPMorgan, Citi, BofA, and Wells Fargo Plan 2027 Tokenized Deposit Network as Banks Move to Counter Stablecoins"), CoinDesk ("JPMorgan, Bank of America and Citi are going on the blockchain offensive with a shared tokenized network"), The Defiant ("Major US Banks Including JPMorgan, Citi and BofA Plan Shared Tokenized Deposit Network"), PYMNTS ("Big Banks Launch Tokenized Deposit Network to Fight Off Stablecoin Threat"), CoinGape ("Genius Act: Stablecoin Yields Face Regulatory Crackdown as Banks' Lobby Pressures Senate"), Forbes ("The GENIUS Act Stablecoin Yield Ban Has A Coinbase-Shaped Hole"), CoinDesk ("Stablecoin market cap has shrunk by $10 billion since May"). Số liệu và mốc thời gian theo thời điểm đưa tin của từng nguồn.</p>
<?php require __DIR__.'/_footer.php'; ?>
