<?php $slug = 'xaut-whale-accumulation-gold-etf-outflow-divergence'; require __DIR__.'/_header.php'; ?>

<p class="ko">크립토 자산운용사 아브락사스 캐피털(Abraxas Capital)이 지난 7월 8일 8분이라는 짧은 시간 동안 바이낸스·비트파이넥스·OKX·바이비트 등 주요 거래소에서 테더골드(XAUT) 3,931개, 약 1,596만 달러어치를 인출했다고 온체인 분석 플랫폼 룩온체인(Lookonchain)이 포착해 비트코인월드·크립토뉴스·블록체인닷뉴스 등이 보도했다. 같은 시기 또 다른 고래 지갑도 XAUT 953개(약 393만 달러)를 인출한 것으로 나타나 금 연동 토큰을 향한 대형 투자자들의 매집이 다시 두드러지고 있다.</p>
<p class="en">Crypto asset manager Abraxas Capital withdrew 3,931 XAUT — worth roughly $15.96 million — from major exchanges including Binance, Bitfinex, OKX, and Bybit within an eight-minute window on July 8, according to on-chain analytics platform Lookonchain, as reported by Bitcoin World, CryptoNews, and Blockchain.News. Around the same time, another whale wallet withdrew 953 XAUT (about $3.93 million), signaling a renewed pickup in large-investor accumulation of gold-backed tokens.</p>
<p class="ja">暗号資産運用会社アブラクサス・キャピタル(Abraxas Capital)は7月8日、わずか8分の間にバイナンス、ビットフィネックス、OKX、バイビットなど主要取引所からテザーゴールド(XAUT)3,931枚、約1,596万ドル相当を引き出したと、オンチェーン分析プラットフォームのルックオンチェーン(Lookonchain)が捕捉し、ビットコインワールド、クリプトニュース、ブロックチェーン・ニュースなどが報じた。同時期に別のクジラウォレットもXAUT953枚(約393万ドル)を引き出しており、金連動トークンへの大口投資家の買い集めが再び目立ち始めている。</p>
<p class="es">La gestora de criptoactivos Abraxas Capital retiró 3.931 XAUT —por un valor aproximado de 15,96 millones de dólares— de exchanges importantes como Binance, Bitfinex, OKX y Bybit en una ventana de ocho minutos el 8 de julio, según la plataforma de análisis on-chain Lookonchain, tal como informaron Bitcoin World, CryptoNews y Blockchain.News. Casi al mismo tiempo, otra billetera ballena retiró 953 XAUT (unos 3,93 millones de dólares), lo que indica un repunte renovado en la acumulación de tokens respaldados por oro por parte de grandes inversores.</p>
<p class="de">Der Krypto-Vermögensverwalter Abraxas Capital zog am 8. Juli innerhalb eines Achtminutenfensters 3.931 XAUT — im Wert von rund 15,96 Millionen US-Dollar — von großen Börsen wie Binance, Bitfinex, OKX und Bybit ab, wie die On-Chain-Analyseplattform Lookonchain aufdeckte und Bitcoin World, CryptoNews und Blockchain.News berichteten. Etwa zur gleichen Zeit zog eine weitere Großanleger-Wallet 953 XAUT (rund 3,93 Millionen US-Dollar) ab, was auf eine erneute Zunahme der Akkumulation goldgedeckter Token durch Großinvestoren hindeutet.</p>
<p class="fr">Le gestionnaire d'actifs crypto Abraxas Capital a retiré 3 931 XAUT — d'une valeur d'environ 15,96 millions de dollars — de grandes bourses telles que Binance, Bitfinex, OKX et Bybit en l'espace de huit minutes le 8 juillet, selon la plateforme d'analyse on-chain Lookonchain, comme l'ont rapporté Bitcoin World, CryptoNews et Blockchain.News. À peu près au même moment, un autre portefeuille baleine a retiré 953 XAUT (environ 3,93 millions de dollars), signalant une reprise de l'accumulation de jetons adossés à l'or par de grands investisseurs.</p>
<p class="pt">A gestora de ativos cripto Abraxas Capital retirou 3.931 XAUT — no valor aproximado de US$ 15,96 milhões — de grandes exchanges como Binance, Bitfinex, OKX e Bybit em uma janela de oito minutos no dia 8 de julho, segundo a plataforma de análise on-chain Lookonchain, conforme reportado por Bitcoin World, CryptoNews e Blockchain.News. Por volta da mesma época, outra carteira baleia retirou 953 XAUT (cerca de US$ 3,93 milhões), sinalizando uma retomada no acúmulo de tokens lastreados em ouro por grandes investidores.</p>
<p class="tr">Kripto varlık yöneticisi Abraxas Capital, 8 Temmuz'da sekiz dakikalık bir pencerede Binance, Bitfinex, OKX ve Bybit gibi büyük borsalardan yaklaşık 15,96 milyon dolar değerinde 3.931 XAUT çekti; bunu zincir üstü analiz platformu Lookonchain tespit etti ve Bitcoin World, CryptoNews ve Blockchain.News haberleştirdi. Yaklaşık aynı dönemde başka bir balina cüzdanı da 953 XAUT (yaklaşık 3,93 milyon dolar) çekerek altına dayalı tokenlerde büyük yatırımcı birikiminin yeniden hız kazandığına işaret etti.</p>
<p class="vi">Công ty quản lý tài sản crypto Abraxas Capital đã rút 3.931 XAUT — trị giá khoảng 15,96 triệu USD — khỏi các sàn giao dịch lớn gồm Binance, Bitfinex, OKX và Bybit chỉ trong vòng tám phút vào ngày 8 tháng 7, theo nền tảng phân tích on-chain Lookonchain, được Bitcoin World, CryptoNews và Blockchain.News đưa tin. Gần như cùng thời điểm, một ví cá voi khác cũng rút 953 XAUT (khoảng 3,93 triệu USD), cho thấy hoạt động gom hàng token được bảo chứng bằng vàng của các nhà đầu tư lớn đang tăng trở lại.</p>

<h2 class="ko">탈중앙 금고행과 ETF 엑소더스 — 두 갈래로 갈린 금 수요</h2>
<h2 class="en">Onchain vaults vs. the ETF exodus — gold demand splits in two</h2>
<h2 class="ja">オンチェーン金庫行きとETFエクソダス — 二極化する金需要</h2>
<h2 class="es">Bóvedas on-chain frente al éxodo de los ETF — la demanda de oro se bifurca</h2>
<h2 class="de">Onchain-Tresore versus ETF-Exodus — Goldnachfrage spaltet sich</h2>
<h2 class="fr">Coffres on-chain contre exode des ETF — la demande d'or se scinde en deux</h2>
<h2 class="pt">Cofres on-chain versus êxodo dos ETFs — a demanda por ouro se divide em duas</h2>
<h2 class="tr">Zincir üstü kasalar mı, ETF çıkışı mı — altın talebi ikiye ayrılıyor</h2>
<h2 class="vi">Kho lưu trữ on-chain và làn sóng rút khỏi ETF — nhu cầu vàng phân hóa hai hướng</h2>

<p class="ko">테더골드(XAUT)는 스위스 금고에 보관된 실물 금에 1대1로 연동되는 토큰으로, 1 XAUT는 순금 1트로이온스에 대한 청구권을 나타낸다. 발행사 테더의 자회사 TG 커모디티스가 관리하며, 분기별로 독립 회계법인 BDO 이탈리아의 감사보고서를 통해 보유 금 물량을 공개한다. 이번 아브락사스의 인출은 전체 XAUT 시가총액(약 25억 달러 안팎)에 비하면 1%도 안 되는 규모지만, 8분이라는 짧은 시간에 여러 거래소에서 동시다발적으로 이뤄졌다는 점에서 단순 개인 이체가 아니라 사전에 조율된 자금 이동으로 해석된다.</p>
<p class="en">Tether Gold (XAUT) is a token pegged one-to-one to physical gold held in Swiss vaults, with each XAUT representing a claim on one troy ounce of pure gold. It's managed by TG Commodities, a Tether subsidiary, which discloses its gold holdings quarterly through audit reports from independent accounting firm BDO Italia. Abraxas's withdrawal amounts to less than 1% of XAUT's total market cap (roughly $2.5 billion), but the fact that it happened across multiple exchanges within an eight-minute window suggests a pre-coordinated capital move rather than a simple individual transfer.</p>
<p class="ja">テザーゴールド(XAUT)はスイスの金庫に保管された実物金に1対1で連動するトークンで、1XAUTは純金1トロイオンスに対する請求権を表す。発行会社テザーの子会社TGコモディティーズが管理し、四半期ごとに独立会計事務所BDOイタリアの監査報告書を通じて保有金量を公開している。今回のアブラクサスの引き出しはXAUT全体の時価総額(約25億ドル前後)に比べれば1%にも満たない規模だが、8分という短時間に複数の取引所で同時多発的に行われた点から、単純な個人の送金ではなく事前に調整された資金移動と解釈される。</p>
<p class="es">Tether Gold (XAUT) es un token vinculado uno a uno con oro físico custodiado en bóvedas suizas, donde cada XAUT representa un derecho sobre una onza troy de oro puro. Lo gestiona TG Commodities, una filial de Tether, que divulga trimestralmente sus reservas de oro mediante informes de auditoría de la firma contable independiente BDO Italia. El retiro de Abraxas representa menos del 1% de la capitalización total de mercado de XAUT (unos 2.500 millones de dólares), pero el hecho de que ocurriera en múltiples exchanges dentro de una ventana de ocho minutos sugiere un movimiento de capital coordinado de antemano, más que una simple transferencia individual.</p>
<p class="de">Tether Gold (XAUT) ist ein Token, der eins zu eins an physisches Gold gekoppelt ist, das in Schweizer Tresoren gelagert wird, wobei jedes XAUT einen Anspruch auf eine Feinunze reines Gold darstellt. Es wird von TG Commodities verwaltet, einer Tether-Tochtergesellschaft, die ihre Goldbestände vierteljährlich durch Prüfberichte der unabhängigen Wirtschaftsprüfungsgesellschaft BDO Italia offenlegt. Der Abzug von Abraxas macht weniger als 1 % der gesamten Marktkapitalisierung von XAUT (rund 2,5 Milliarden US-Dollar) aus, doch die Tatsache, dass er innerhalb eines Achtminutenfensters über mehrere Börsen hinweg erfolgte, deutet eher auf eine im Voraus koordinierte Kapitalbewegung als auf eine einfache Einzelüberweisung hin.</p>
<p class="fr">Tether Gold (XAUT) est un jeton adossé un pour un à de l'or physique conservé dans des coffres suisses, chaque XAUT représentant une créance sur une once troy d'or pur. Il est géré par TG Commodities, une filiale de Tether, qui divulgue trimestriellement ses réserves d'or via des rapports d'audit du cabinet comptable indépendant BDO Italia. Le retrait d'Abraxas représente moins de 1 % de la capitalisation boursière totale de XAUT (environ 2,5 milliards de dollars), mais le fait qu'il se soit produit sur plusieurs bourses en l'espace de huit minutes suggère un mouvement de capitaux coordonné à l'avance plutôt qu'un simple transfert individuel.</p>
<p class="pt">A Tether Gold (XAUT) é um token vinculado um a um a ouro físico mantido em cofres suíços, em que cada XAUT representa um direito sobre uma onça troy de ouro puro. É administrada pela TG Commodities, subsidiária da Tether, que divulga trimestralmente suas reservas de ouro por meio de relatórios de auditoria da firma contábil independente BDO Italia. A retirada da Abraxas representa menos de 1% da capitalização de mercado total da XAUT (cerca de US$ 2,5 bilhões), mas o fato de ter ocorrido em várias exchanges dentro de uma janela de oito minutos sugere um movimento de capital coordenado previamente, em vez de uma simples transferência individual.</p>
<p class="tr">Tether Gold (XAUT), İsviçre kasalarında saklanan fiziksel altına bire bir bağlı bir tokendir; her XAUT, bir troy ons saf altın üzerinde bir hak talebini temsil eder. Tether'in bir yan kuruluşu olan TG Commodities tarafından yönetilir ve bağımsız denetim firması BDO Italia'nın denetim raporları aracılığıyla altın rezervlerini üç ayda bir kamuoyuna açıklar. Abraxas'ın çekimi, XAUT'un toplam piyasa değerinin (yaklaşık 2,5 milyar dolar) yüzde 1'inden azına denk geliyor, ancak sekiz dakikalık bir pencerede birden fazla borsada gerçekleşmesi, basit bir bireysel transferden çok önceden koordine edilmiş bir sermaye hareketine işaret ediyor.</p>
<p class="vi">Tether Gold (XAUT) là token được neo 1:1 với vàng vật chất lưu giữ trong các hầm chứa tại Thụy Sĩ, mỗi XAUT đại diện cho quyền yêu cầu đối với một troy ounce vàng nguyên chất. Token này do TG Commodities, công ty con của Tether, quản lý và công bố lượng vàng nắm giữ theo quý thông qua báo cáo kiểm toán của công ty kiểm toán độc lập BDO Italia. Đợt rút của Abraxas chiếm chưa tới 1% tổng vốn hóa thị trường của XAUT (khoảng 2,5 tỷ USD), nhưng việc diễn ra trên nhiều sàn giao dịch chỉ trong vòng tám phút cho thấy đây là một động thái chuyển vốn được phối hợp từ trước, chứ không phải một giao dịch chuyển tiền cá nhân đơn thuần.</p>

<p class="ko">이런 '실물 선호' 흐름은 낯설지 않다. 2022~2023년에도 금 ETF에서는 자금이 빠져나가는 동안 실물 골드바·주화 수요는 오히려 늘어나는 탈동조화가 관측된 바 있는데, 이번 XAUT 매집은 그 흐름이 크립토 네이티브 영역으로 확장된 형태로 읽을 수 있다. 다만 반박 여지도 분명하다 — 이번에 포착된 인출 총액은 2,000만 달러가 채 안 되는 반면, 같은 기간 금 ETF에서는 89억 달러가 빠져나갔다. 규모 차이가 워낙 커서, 이를 '자금 이동의 증거'로 단정하기보다는 초기 신호(leading indicator) 정도로 보수적으로 해석하는 편이 안전하다 — 고래 한두 곳의 리밸런싱일 가능성을 배제할 수 없기 때문이다.</p>
<p class="en">This kind of "preference for the physical" isn't unfamiliar. In 2022-2023, a similar decoupling was observed where capital left gold ETFs even as demand for physical gold bars and coins rose — and this XAUT accumulation can be read as that same pattern extending into crypto-native territory. There's a clear rebuttable point, though: the withdrawals captured here total under $20 million, while gold ETFs saw $8.9 billion in outflows over the same period. Given that scale gap, it's safer to treat this as a leading indicator rather than conclusive proof of a capital shift — the possibility that this is simply one or two whales rebalancing can't be ruled out.</p>
<p class="ja">こうした「実物選好」の流れは目新しいものではない。2022〜2023年にも金ETFから資金が流出する一方で実物ゴールドバー・コインの需要はむしろ増加するという脱同調化が観測されており、今回のXAUT買い集めはその流れが暗号資産ネイティブな領域へと拡張した形と読み取れる。ただし明確な反論の余地もある — 今回捕捉された引き出し総額は2,000万ドルに満たない一方、同期間に金ETFからは89億ドルが流出している。規模の差があまりに大きいため、これを「資金移動の証拠」と断定するよりも、初期シグナル(先行指標)程度に控えめに解釈する方が安全だ — 一つか二つのクジラのリバランシングである可能性を排除できないからだ。</p>
<p class="es">Esta preferencia por lo "físico" no es desconocida. En 2022-2023 se observó una desconexión similar en la que el capital abandonaba los ETF de oro mientras la demanda de barras y monedas de oro físico aumentaba, y esta acumulación de XAUT puede leerse como esa misma pauta extendiéndose al territorio nativo de las criptomonedas. Sin embargo, hay un punto contrario claro: los retiros registrados aquí suman menos de 20 millones de dólares, mientras que los ETF de oro registraron salidas de 8.900 millones de dólares en el mismo período. Dada esa diferencia de escala, es más prudente tratar esto como un indicador adelantado y no como prueba concluyente de un desplazamiento de capital — no se puede descartar que se trate simplemente de una o dos ballenas reequilibrando posiciones.</p>
<p class="de">Diese Art von „Präferenz für das Physische" ist nicht unbekannt. Auch 2022–2023 wurde eine ähnliche Entkopplung beobachtet, bei der Kapital aus Gold-ETFs abfloss, während die Nachfrage nach physischen Goldbarren und -münzen stieg — und diese XAUT-Akkumulation lässt sich als Ausweitung dieses Musters auf krypto-natives Terrain lesen. Es gibt jedoch einen klaren widerlegbaren Punkt: Die hier erfassten Abhebungen summieren sich auf unter 20 Millionen US-Dollar, während Gold-ETFs im selben Zeitraum Abflüsse von 8,9 Milliarden US-Dollar verzeichneten. Angesichts dieser Größenordnungslücke ist es sicherer, dies als Frühindikator statt als endgültigen Beweis für eine Kapitalverschiebung zu betrachten — die Möglichkeit, dass es sich schlicht um die Neugewichtung ein oder zweier Großanleger handelt, lässt sich nicht ausschließen.</p>
<p class="fr">Cette préférence pour le « physique » n'est pas inconnue. En 2022-2023, un découplage similaire avait été observé, où les capitaux quittaient les ETF sur l'or tandis que la demande de lingots et de pièces d'or physiques augmentait — et cette accumulation de XAUT peut se lire comme ce même schéma s'étendant au territoire natif de la crypto. Il existe toutefois un point contraire clair : les retraits recensés ici totalisent moins de 20 millions de dollars, tandis que les ETF sur l'or ont enregistré 8,9 milliards de dollars de sorties sur la même période. Vu cet écart d'échelle, il est plus prudent de considérer cela comme un indicateur avancé plutôt que comme une preuve concluante d'un déplacement de capitaux — la possibilité qu'il s'agisse simplement du rééquilibrage d'une ou deux baleines ne peut être écartée.</p>
<p class="pt">Esse tipo de "preferência pelo físico" não é desconhecido. Em 2022-2023, observou-se uma dissociação semelhante, em que o capital saía dos ETFs de ouro enquanto a demanda por barras e moedas de ouro físico aumentava — e esse acúmulo de XAUT pode ser lido como esse mesmo padrão se estendendo ao território nativo cripto. Há, porém, um ponto contrário claro: as retiradas registradas aqui somam menos de US$ 20 milhões, enquanto os ETFs de ouro tiveram saídas de US$ 8,9 bilhões no mesmo período. Dada essa diferença de escala, é mais seguro tratar isso como um indicador antecedente, e não como prova conclusiva de uma mudança de capital — não se pode descartar que seja simplesmente o rebalanceamento de uma ou duas baleias.</p>
<p class="tr">Bu tür bir "fiziksele yönelme" eğilimi yabancı değil. 2022-2023'te de altın ETF'lerinden sermaye çıkarken fiziksel altın külçe ve sikke talebinin arttığı benzer bir ayrışma gözlemlenmişti — ve bu XAUT birikimi, aynı eğilimin kripto-yerli alana genişlemesi olarak okunabilir. Ancak açık bir karşı nokta da var: burada tespit edilen çekimler toplamda 20 milyon doların altında kalırken, aynı dönemde altın ETF'lerinden 8,9 milyar dolar çıkış oldu. Bu ölçek farkı göz önüne alındığında, bunu kesin bir sermaye kayması kanıtı olarak değil, öncü bir gösterge olarak temkinli biçimde yorumlamak daha güvenli — bunun yalnızca bir veya iki balinanın pozisyon dengelemesi olma ihtimali de göz ardı edilemez.</p>
<p class="vi">Kiểu "ưu tiên vật chất" này không xa lạ. Trong giai đoạn 2022-2023, một sự phân tách tương tự từng được ghi nhận khi dòng vốn rút khỏi các ETF vàng trong lúc nhu cầu vàng miếng và tiền xu vật chất lại tăng lên — và đợt gom XAUT lần này có thể được hiểu là cùng một mô hình đó đang mở rộng sang lĩnh vực gốc crypto. Tuy nhiên, cũng đáng lưu ý một điểm phản bác rõ ràng: tổng số tiền rút được ghi nhận ở đây chưa tới 20 triệu USD, trong khi cùng kỳ các ETF vàng chứng kiến 8,9 tỷ USD bị rút ra. Với khoảng cách quy mô lớn như vậy, nên thận trọng xem đây là một chỉ báo sớm thay vì bằng chứng kết luận về sự dịch chuyển dòng vốn — không thể loại trừ khả năng đây chỉ là hoạt động tái cân bằng của một hoặc hai cá voi.</p>

<h2 class="ko">왜 지금 금인가 — 지정학적 리스크와 커스터디 트레이드오프</h2>
<h2 class="en">Why gold, why now — geopolitical risk and the custody trade-off</h2>
<h2 class="ja">なぜ今、金なのか — 地政学リスクとカストディのトレードオフ</h2>
<h2 class="es">Por qué el oro, por qué ahora — riesgo geopolítico y el dilema de la custodia</h2>
<h2 class="de">Warum Gold, warum jetzt — geopolitisches Risiko und der Verwahrungs-Trade-off</h2>
<h2 class="fr">Pourquoi l'or, pourquoi maintenant — risque géopolitique et arbitrage de garde</h2>
<h2 class="pt">Por que ouro, por que agora — risco geopolítico e o trade-off da custódia</h2>
<h2 class="tr">Neden altın, neden şimdi — jeopolitik risk ve saklama ödünleşimi</h2>
<h2 class="vi">Vì sao là vàng, vì sao là lúc này — rủi ro địa chính trị và sự đánh đổi trong lưu ký</h2>

<p class="ko">이번 매집은 중동 정세가 다시 악화된 시점과 맞물려 있다. 7월 12일 도널드 트럼프 미국 대통령이 이란과의 취약한 휴전이 사실상 끝났다고 밝히면서 유가가 급등했고, 비트코인은 장중 6만1000달러대까지 밀렸다. 안전자산 회전(safe-haven rotation) 국면에서 대형 투자자들이 금 관련 자산으로 눈을 돌리는 것은 특별한 일이 아니지만, 이번엔 전통적 금 ETF가 아니라 온체인 토큰 형태의 금을 택했다는 점이 눈에 띈다. 이는 지정학적 긴장이 고조될 때 유동성이 반드시 전통 금융 상품으로만 흘러가지 않는다는 것을 보여준다.</p>
<p class="en">This accumulation coincides with a fresh deterioration in Middle East tensions. On July 12, U.S. President Donald Trump said a fragile ceasefire with Iran had effectively ended, sending oil prices surging and pulling Bitcoin down to the $61,000 range intraday. It's nothing unusual for large investors to rotate into gold-related assets during a safe-haven phase — but what stands out here is that they chose an onchain token form of gold rather than a traditional gold ETF. That shows liquidity doesn't necessarily flow only into traditional financial products when geopolitical tension rises.</p>
<p class="ja">今回の買い集めは、中東情勢が再び悪化した時期と重なっている。7月12日、ドナルド・トランプ米大統領はイランとの脆弱な停戦が事実上終了したと表明し、原油価格が急騰、ビットコインは取引時間中に6万1000ドル台まで下落した。セーフヘイブン局面で大口投資家が金関連資産に目を向けること自体は珍しくないが、今回は伝統的な金ETFではなくオンチェーントークン形式の金を選んだ点が目を引く。これは地政学的緊張が高まる際、流動性が必ずしも伝統的金融商品にだけ流れるわけではないことを示している。</p>
<p class="es">Esta acumulación coincide con un nuevo deterioro de las tensiones en Oriente Medio. El 12 de julio, el presidente estadounidense Donald Trump declaró que un frágil alto el fuego con Irán había terminado de hecho, lo que disparó los precios del petróleo y llevó a Bitcoin a la franja de los 61.000 dólares intradía. No es nada inusual que los grandes inversores roten hacia activos relacionados con el oro en una fase de refugio seguro, pero lo llamativo aquí es que eligieron una forma de oro en token on-chain en lugar de un ETF de oro tradicional. Eso demuestra que la liquidez no necesariamente fluye solo hacia productos financieros tradicionales cuando aumenta la tensión geopolítica.</p>
<p class="de">Diese Akkumulation fällt mit einer erneuten Verschlechterung der Spannungen im Nahen Osten zusammen. Am 12. Juli erklärte US-Präsident Donald Trump, ein fragiler Waffenstillstand mit dem Iran sei faktisch beendet, was die Ölpreise in die Höhe schnellen ließ und Bitcoin im Intraday-Handel auf die 61.000-Dollar-Marke drückte. Es ist nichts Ungewöhnliches, dass Großinvestoren in einer Safe-Haven-Phase in goldbezogene Vermögenswerte umschichten — auffällig ist hier jedoch, dass sie eine On-Chain-Token-Form von Gold statt eines traditionellen Gold-ETFs wählten. Das zeigt, dass Liquidität bei steigender geopolitischer Spannung nicht zwangsläufig nur in traditionelle Finanzprodukte fließt.</p>
<p class="fr">Cette accumulation coïncide avec une nouvelle détérioration des tensions au Moyen-Orient. Le 12 juillet, le président américain Donald Trump a déclaré qu'un cessez-le-feu fragile avec l'Iran avait pris fin dans les faits, faisant flamber les prix du pétrole et faisant chuter le Bitcoin vers la fourchette des 61 000 dollars en intraday. Il n'est pas inhabituel que de grands investisseurs se tournent vers des actifs liés à l'or en phase de valeur refuge — mais ce qui frappe ici, c'est qu'ils ont choisi une forme d'or en jeton on-chain plutôt qu'un ETF sur l'or traditionnel. Cela montre que la liquidité ne s'oriente pas nécessairement uniquement vers les produits financiers traditionnels lorsque les tensions géopolitiques montent.</p>
<p class="pt">Esse acúmulo coincide com uma nova deterioração das tensões no Oriente Médio. Em 12 de julho, o presidente dos EUA, Donald Trump, disse que um frágil cessar-fogo com o Irã havia efetivamente terminado, disparando os preços do petróleo e derrubando o Bitcoin para a faixa de US$ 61.000 durante o pregão. Não é incomum que grandes investidores migrem para ativos relacionados a ouro em uma fase de refúgio seguro — mas o que chama atenção aqui é que eles escolheram uma forma de ouro em token on-chain, em vez de um ETF de ouro tradicional. Isso mostra que a liquidez não flui necessariamente apenas para produtos financeiros tradicionais quando a tensão geopolítica aumenta.</p>
<p class="tr">Bu birikim, Orta Doğu'daki gerilimlerin yeniden tırmandığı bir döneme denk geliyor. 12 Temmuz'da ABD Başkanı Donald Trump, İran ile kırılgan ateşkesin fiilen sona erdiğini açıklayınca petrol fiyatları fırladı ve Bitcoin gün içinde 61.000 dolar bandına kadar geriledi. Büyük yatırımcıların güvenli liman evresinde altınla ilişkili varlıklara yönelmesi alışılmadık bir şey değil — ancak burada dikkat çeken, geleneksel bir altın ETF'i yerine zincir üstü token biçiminde altını tercih etmiş olmaları. Bu da jeopolitik gerilim yükseldiğinde likiditenin mutlaka yalnızca geleneksel finansal ürünlere akmadığını gösteriyor.</p>
<p class="vi">Đợt gom hàng này trùng với thời điểm căng thẳng Trung Đông leo thang trở lại. Vào ngày 12 tháng 7, Tổng thống Mỹ Donald Trump tuyên bố lệnh ngừng bắn mong manh với Iran đã thực sự kết thúc, khiến giá dầu tăng vọt và kéo Bitcoin xuống vùng 61.000 USD trong phiên giao dịch. Việc các nhà đầu tư lớn xoay trục sang tài sản liên quan đến vàng trong giai đoạn trú ẩn an toàn không có gì bất thường — nhưng điều đáng chú ý ở đây là họ chọn hình thức vàng trên chuỗi thay vì một ETF vàng truyền thống. Điều này cho thấy thanh khoản không nhất thiết chỉ chảy vào các sản phẩm tài chính truyền thống khi căng thẳng địa chính trị gia tăng.</p>

<p class="ko">XAUT를 보유한다는 것은 실물 금괴나 금 ETF와는 다른 상충관계를 수반한다. 실물 금은 발행사 리스크가 없지만 보관·운송·검증 비용이 들고, 금 ETF는 규제된 상장 구조 아래 있지만 어디까지나 '금에 대한 청구권'이라는 서류상 자산이다. XAUT는 이 둘 사이에서 '테더와 커스터디 기관에 대한 신뢰'라는 별도의 상대방 리스크(counterparty risk)를 지는 대신, 주식 시장이 닫혀 있어도 24시간 이체·담보 활용이 가능하다는 유동성 이점을 얻는다. 테더가 최근 XAUT를 소액 단위로 쪼개 결제에 쓸 수 있게 한 스쿠도(Scudo) 프로젝트(관련 기사: <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">테더 스쿠도 금 소액결제</a>)를 선보인 것도, 이 토큰이 단순 가치저장 수단을 넘어 디파이 담보·결제 자산으로 쓰이길 원하는 발행사의 의도를 보여준다 — 대형 투자자들이 위기 국면에 XAUT를 택하는 구조적 이유도 바로 이 '24시간 온체인 활용성'에 있다고 볼 수 있다.</p>
<p class="en">Holding XAUT carries a different trade-off than holding physical gold bars or a gold ETF. Physical gold carries no issuer risk but comes with storage, transport, and verification costs; a gold ETF sits within a regulated, listed structure but is, at bottom, a paper claim on gold. XAUT sits between the two: it takes on a separate counterparty risk — trust in Tether and its custodians — but in exchange gains the liquidity advantage of being transferable and usable as collateral 24/7, even when stock markets are closed. Tether's recent Scudo project, which lets XAUT be split into small units for payments (related coverage: <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">Tether's Scudo gold micro-payments</a>), reflects the issuer's intent for the token to be used as DeFi collateral and a payment asset, not just a store of value — and that same 24/7 onchain utility is arguably the structural reason large investors reach for XAUT during a crisis window.</p>
<p class="ja">XAUTを保有することは、実物金塊や金ETFとは異なるトレードオフを伴う。実物金は発行体リスクがないが保管・輸送・検証コストがかかり、金ETFは規制された上場構造下にあるが、あくまで「金に対する請求権」という紙の資産である。XAUTはこの両者の中間に位置し、「テザーとカストディ機関への信頼」という別個のカウンターパーティリスクを負う代わりに、株式市場が閉まっていても24時間送金・担保活用が可能という流動性上の利点を得る。テザーが最近、XAUTを少額単位に分割して決済に使えるようにしたスクード(Scudo)プロジェクト(関連記事:<a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">テザー・スクード金小口決済</a>)を打ち出したのも、このトークンを単なる価値保存手段にとどめず、DeFi担保・決済資産として使わせたいという発行体の意図を示している――大口投資家が危機局面でXAUTを選ぶ構造的な理由も、まさにこの「24時間オンチェーン活用性」にあると言える。</p>
<p class="es">Poseer XAUT implica un compromiso diferente al de poseer lingotes de oro físico o un ETF de oro. El oro físico no conlleva riesgo del emisor, pero implica costos de almacenamiento, transporte y verificación; un ETF de oro se sitúa dentro de una estructura regulada y cotizada, pero es, en esencia, un derecho documental sobre el oro. XAUT se sitúa entre ambos: asume un riesgo de contraparte distinto —la confianza en Tether y sus custodios— pero a cambio obtiene la ventaja de liquidez de ser transferible y utilizable como garantía las 24 horas, incluso cuando los mercados bursátiles están cerrados. El reciente proyecto Scudo de Tether, que permite dividir XAUT en pequeñas unidades para pagos (cobertura relacionada: <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">micropagos en oro Scudo de Tether</a>), refleja la intención del emisor de que el token se use como garantía en DeFi y como activo de pago, no solo como reserva de valor — y esa misma utilidad on-chain 24/7 es, podría decirse, la razón estructural por la que los grandes inversores recurren a XAUT en una ventana de crisis.</p>
<p class="de">Das Halten von XAUT bringt einen anderen Kompromiss mit sich als das Halten physischer Goldbarren oder eines Gold-ETFs. Physisches Gold trägt kein Emittentenrisiko, verursacht aber Lagerungs-, Transport- und Prüfkosten; ein Gold-ETF befindet sich innerhalb einer regulierten, börsennotierten Struktur, ist im Kern jedoch ein papierener Anspruch auf Gold. XAUT liegt dazwischen: Es geht ein separates Kontrahentenrisiko ein — Vertrauen in Tether und seine Verwahrer — erhält im Gegenzug aber den Liquiditätsvorteil, rund um die Uhr übertragbar und als Sicherheit nutzbar zu sein, selbst wenn die Aktienmärkte geschlossen sind. Tethers jüngstes Scudo-Projekt, das es erlaubt, XAUT für Zahlungen in kleine Einheiten aufzuteilen (verwandte Berichterstattung: <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">Tethers Scudo-Goldmikrozahlungen</a>), spiegelt die Absicht des Emittenten wider, den Token als DeFi-Sicherheit und Zahlungsmittel zu nutzen, nicht nur als Wertspeicher — und genau diese 24/7-On-Chain-Nutzbarkeit ist wohl der strukturelle Grund, warum Großinvestoren in einem Krisenfenster zu XAUT greifen.</p>
<p class="fr">Détenir des XAUT implique un compromis différent de la détention de lingots d'or physiques ou d'un ETF sur l'or. L'or physique ne comporte aucun risque émetteur, mais entraîne des coûts de stockage, de transport et de vérification ; un ETF sur l'or s'inscrit dans une structure réglementée et cotée, mais reste, au fond, une créance papier sur l'or. Le XAUT se situe entre les deux : il assume un risque de contrepartie distinct — la confiance envers Tether et ses dépositaires — mais obtient en retour l'avantage de liquidité d'être transférable et utilisable comme garantie 24 heures sur 24, même lorsque les marchés boursiers sont fermés. Le récent projet Scudo de Tether, qui permet de diviser le XAUT en petites unités pour les paiements (couverture associée : <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">micropaiements en or Scudo de Tether</a>), reflète la volonté de l'émetteur de faire de ce jeton une garantie DeFi et un actif de paiement, pas seulement une réserve de valeur — et cette même utilité on-chain 24 h/24 est sans doute la raison structurelle pour laquelle les grands investisseurs se tournent vers le XAUT en période de crise.</p>
<p class="pt">Manter XAUT envolve um trade-off diferente de manter barras de ouro físico ou um ETF de ouro. O ouro físico não traz risco de emissor, mas implica custos de armazenamento, transporte e verificação; um ETF de ouro está dentro de uma estrutura regulada e listada, mas é, no fundo, um direito em papel sobre o ouro. O XAUT fica entre os dois: assume um risco de contraparte separado — confiança na Tether e em seus custodiantes — mas em troca ganha a vantagem de liquidez de ser transferível e utilizável como garantia 24 horas por dia, mesmo quando os mercados de ações estão fechados. O recente projeto Scudo da Tether, que permite dividir o XAUT em unidades pequenas para pagamentos (cobertura relacionada: <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">micropagamentos em ouro Scudo da Tether</a>), reflete a intenção da emissora de que o token seja usado como garantia em DeFi e ativo de pagamento, não apenas como reserva de valor — e essa mesma utilidade on-chain 24 horas é, pode-se dizer, a razão estrutural pela qual grandes investidores recorrem ao XAUT em uma janela de crise.</p>
<p class="tr">XAUT bulundurmak, fiziksel altın külçesi veya altın ETF'i bulundurmaktan farklı bir ödünleşim taşır. Fiziksel altın ihraççı riski taşımaz ama saklama, taşıma ve doğrulama maliyetleri getirir; bir altın ETF'i düzenlenmiş, borsada işlem gören bir yapı içindedir ama temelde altın üzerinde kağıt üzerinde bir hak talebidir. XAUT ikisinin arasında yer alır: Tether ve saklama kuruluşlarına duyulan güven şeklinde ayrı bir karşı taraf riski üstlenir, ancak karşılığında hisse senedi piyasaları kapalıyken bile 7/24 devredilebilir ve teminat olarak kullanılabilir olma likidite avantajını kazanır. Tether'in XAUT'u ödemeler için küçük birimlere bölmeye olanak tanıyan yakın tarihli Scudo projesi (ilgili haber: <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">Tether'in Scudo altın mikro ödemeleri</a>), ihraççının bu tokeni yalnızca bir değer saklama aracı değil, DeFi teminatı ve ödeme varlığı olarak kullandırma niyetini yansıtıyor — büyük yatırımcıların kriz döneminde XAUT'a yönelmesinin yapısal nedeni de tam olarak bu 7/24 zincir üstü kullanılabilirlik olabilir.</p>
<p class="vi">Nắm giữ XAUT đi kèm một sự đánh đổi khác so với nắm giữ vàng miếng vật chất hay một ETF vàng. Vàng vật chất không có rủi ro từ tổ chức phát hành nhưng đi kèm chi phí lưu trữ, vận chuyển và xác minh; một ETF vàng nằm trong một cấu trúc được quản lý, niêm yết, nhưng về bản chất vẫn là một quyền yêu cầu trên giấy đối với vàng. XAUT nằm giữa hai hình thức đó: nó gánh một rủi ro đối tác riêng — niềm tin vào Tether và các đơn vị lưu ký của họ — nhưng đổi lại có được lợi thế thanh khoản là có thể chuyển nhượng và dùng làm tài sản thế chấp 24/7, ngay cả khi thị trường chứng khoán đóng cửa. Dự án Scudo gần đây của Tether, cho phép chia nhỏ XAUT thành các đơn vị nhỏ để thanh toán (bài liên quan: <a href="/tether-scudo-gold-fractional-unit-payments" style="color:#fbbf24">thanh toán vi mô bằng vàng Scudo của Tether</a>), phản ánh ý định của tổ chức phát hành muốn token này được dùng làm tài sản thế chấp DeFi và tài sản thanh toán, chứ không chỉ là công cụ lưu trữ giá trị — và chính khả năng sử dụng on-chain 24/7 đó có thể là lý do mang tính cấu trúc khiến các nhà đầu tư lớn tìm đến XAUT trong giai đoạn khủng hoảng.</p>

<h2 class="ko">비트코인-금 디커플링 국면에서 읽는 신호</h2>
<h2 class="en">Reading the signal amid the Bitcoin-gold decoupling</h2>
<h2 class="ja">ビットコイン・金デカップリング局面で読み解くシグナル</h2>
<h2 class="es">Interpretando la señal en medio del desacoplamiento bitcoin-oro</h2>
<h2 class="de">Das Signal inmitten der Bitcoin-Gold-Entkopplung deuten</h2>
<h2 class="fr">Décrypter le signal au cœur du découplage bitcoin-or</h2>
<h2 class="pt">Interpretando o sinal em meio ao desacoplamento bitcoin-ouro</h2>
<h2 class="tr">Bitcoin-altın ayrışması ortasında sinyali okumak</h2>
<h2 class="vi">Đọc tín hiệu giữa giai đoạn phân tách Bitcoin-vàng</h2>

<p class="ko">이번 XAUT 매집은 본지가 앞서 짚은 비트코인-금 관계 변화의 맥락에서도 눈여겨볼 만하다. 본지는 이미 <a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">비트코인-금 상관관계 붕괴</a> 및 <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">비트코인-금 디커플링과 공포·탐욕 지수 간극</a> 기사에서, 두 자산이 과거처럼 함께 움직이지 않는 국면이 이어지고 있다고 짚은 바 있다. 이런 흐름 속에서 대형 투자자가 '비트코인'이 아니라 '토큰화된 금'을 안전자산으로 택했다는 사실은, 위기 국면에서 크립토 자금이 반드시 비트코인으로 흘러가는 것은 아니라는 점을 보여주는 사례로 읽힌다.</p>
<p class="en">This XAUT accumulation is also worth reading against the backdrop of the shifting Bitcoin-gold relationship this outlet has covered before. Earlier coverage — <a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">the breakdown in Bitcoin-gold correlation</a> and <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">the gap between the Bitcoin-gold decoupling and the fear-greed index</a> — has noted that the two assets have stopped moving together the way they historically did. Against that backdrop, the fact that a large investor chose "tokenized gold" rather than Bitcoin as a safe haven reads as a case study showing that crypto-adjacent capital doesn't necessarily flow into Bitcoin during a crisis window.</p>
<p class="ja">今回のXAUT買い集めは、本紙が以前取り上げたビットコイン・金関係の変化という文脈でも注目に値する。本紙はすでに<a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">ビットコイン・金の相関崩壊</a>および<a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">ビットコイン・金デカップリングと恐怖・強欲指数の間隙</a>の記事で、両資産がかつてのように連動しなくなった局面が続いていると指摘している。こうした流れの中で、大口投資家が「ビットコイン」ではなく「トークン化された金」を安全資産として選んだという事実は、危機局面において暗号資産隣接の資金が必ずしもビットコインに流れるわけではないことを示す事例として読み取れる。</p>
<p class="es">Esta acumulación de XAUT también merece leerse en el contexto del cambio en la relación bitcoin-oro que este medio ha cubierto anteriormente. Coberturas previas —<a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">la ruptura de la correlación bitcoin-oro</a> y <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">la brecha entre el desacoplamiento bitcoin-oro y el índice de miedo y codicia</a>— han señalado que ambos activos han dejado de moverse juntos como lo hacían históricamente. En ese contexto, el hecho de que un gran inversor eligiera "oro tokenizado" en lugar de bitcoin como refugio seguro se lee como un caso que demuestra que el capital adyacente a las criptomonedas no fluye necesariamente hacia bitcoin en una ventana de crisis.</p>
<p class="de">Diese XAUT-Akkumulation lohnt sich auch vor dem Hintergrund der sich wandelnden Bitcoin-Gold-Beziehung zu lesen, über die dieses Medium bereits berichtet hat. Frühere Berichte — <a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">der Zusammenbruch der Bitcoin-Gold-Korrelation</a> und <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">die Kluft zwischen der Bitcoin-Gold-Entkopplung und dem Angst-Gier-Index</a> — haben festgestellt, dass sich die beiden Anlageklassen nicht mehr wie historisch üblich gemeinsam bewegen. Vor diesem Hintergrund liest sich die Tatsache, dass ein Großinvestor „tokenisiertes Gold" statt Bitcoin als sicheren Hafen wählte, als Fallbeispiel dafür, dass krypto-nahes Kapital in einem Krisenfenster nicht zwangsläufig in Bitcoin fließt.</p>
<p class="fr">Cette accumulation de XAUT mérite également d'être lue dans le contexte de l'évolution de la relation bitcoin-or déjà couverte par ce média. Une couverture antérieure — <a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">la rupture de la corrélation bitcoin-or</a> et <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">l'écart entre le découplage bitcoin-or et l'indice de peur et de cupidité</a> — a noté que les deux actifs ont cessé de se déplacer ensemble comme ils le faisaient historiquement. Dans ce contexte, le fait qu'un grand investisseur ait choisi l'« or tokenisé » plutôt que le bitcoin comme valeur refuge se lit comme un cas d'école montrant que les capitaux proches de la crypto ne se dirigent pas nécessairement vers le bitcoin en période de crise.</p>
<p class="pt">Esse acúmulo de XAUT também merece ser lido no contexto da mudança na relação bitcoin-ouro já coberta por este veículo. Coberturas anteriores — <a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">o colapso da correlação bitcoin-ouro</a> e <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">a lacuna entre o desacoplamento bitcoin-ouro e o índice de medo e ganância</a> — apontaram que os dois ativos deixaram de se mover juntos como faziam historicamente. Nesse contexto, o fato de um grande investidor ter escolhido "ouro tokenizado" em vez de bitcoin como refúgio seguro se lê como um caso que mostra que o capital adjacente às criptomoedas não flui necessariamente para o bitcoin em uma janela de crise.</p>
<p class="tr">Bu XAUT birikimi, bu yayının daha önce ele aldığı değişen Bitcoin-altın ilişkisi bağlamında da dikkat çekicidir. Önceki haberler — <a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">Bitcoin-altın korelasyonunun çöküşü</a> ve <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">Bitcoin-altın ayrışması ile korku-açgözlülük endeksi arasındaki açık</a> — iki varlığın artık tarihsel olarak olduğu gibi birlikte hareket etmediğini belirtmişti. Bu bağlamda, büyük bir yatırımcının güvenli liman olarak Bitcoin yerine "tokenleştirilmiş altını" seçmesi, kripto ile bağlantılı sermayenin kriz döneminde mutlaka Bitcoin'e akmadığını gösteren bir örnek olarak okunabilir.</p>
<p class="vi">Đợt gom XAUT này cũng đáng được nhìn nhận trong bối cảnh mối quan hệ Bitcoin-vàng đang thay đổi mà trang này từng đề cập trước đây. Các bài viết trước — <a href="/correlation-breakdown-gold-bitcoin" style="color:#fbbf24">sự sụp đổ của tương quan Bitcoin-vàng</a> và <a href="/btc-gold-decoupling-fear-greed-gap" style="color:#fbbf24">khoảng cách giữa sự phân tách Bitcoin-vàng và chỉ số sợ hãi-tham lam</a> — đã chỉ ra rằng hai tài sản này không còn di chuyển cùng nhau như trước đây. Trong bối cảnh đó, việc một nhà đầu tư lớn chọn "vàng token hóa" thay vì Bitcoin làm nơi trú ẩn an toàn được xem như một minh chứng cho thấy dòng vốn liên quan đến crypto không nhất thiết chảy vào Bitcoin trong giai đoạn khủng hoảng.</p>

<p class="ko">결국 이 흐름이 일회성 리밸런싱인지 구조적 전환인지를 가르는 기준은 명확하다. 앞으로 XAUT와 경쟁 토큰인 팍소스골드(PAXG)를 합친 시가총액이 단발성 인출이 아니라 지속적인 순유입 추세로 이어지는지, 그리고 테더의 다음 분기 감사보고서에서 실제 보유 물리적 금이 늘어나는지를 확인해야 한다. 감사보고서 상 금 보유량이 함께 늘지 않는다면 이번 인출은 거래소 간 단순 재배치에 그칠 가능성이 크고, 반대로 물리적 금 보유가 함께 늘어난다면 이는 신규 자금 유입을 뒷받침하는 더 강한 증거가 된다.</p>
<p class="en">Ultimately, the line between a one-off rebalancing and a structural shift is clear enough. What needs confirming going forward is whether the combined market cap of XAUT and its rival token PAXG shows a sustained net-inflow trend rather than a one-time withdrawal, and whether Tether's next quarterly audit report shows an actual increase in physical gold holdings. If the audited gold reserves don't grow in step, this withdrawal is more likely just a simple inter-exchange reshuffling; if physical gold holdings do rise together with it, that would be stronger evidence of genuine new capital inflow.</p>
<p class="ja">結局のところ、この流れが一時的なリバランシングなのか構造的な転換なのかを分ける基準は明確だ。今後、XAUTと競合トークンのパクソスゴールド(PAXG)を合わせた時価総額が単発的な引き出しではなく持続的な純流入トレンドにつながるか、そしてテザーの次期四半期監査報告書で実際の物理的金保有量が増加するかを確認する必要がある。監査報告書上の金保有量が並行して増えなければ、今回の引き出しは取引所間の単純な再配置にとどまる可能性が高く、逆に物理的金保有が同時に増えれば、新規資金流入を裏付けるより強い証拠となる。</p>
<p class="es">En última instancia, la línea entre un reequilibrio puntual y un cambio estructural es bastante clara. Lo que hay que confirmar de ahora en adelante es si la capitalización de mercado combinada de XAUT y su token rival PAXG muestra una tendencia sostenida de entrada neta en lugar de un retiro puntual, y si el próximo informe de auditoría trimestral de Tether muestra un aumento real en las reservas de oro físico. Si las reservas de oro auditadas no crecen a la par, este retiro será probablemente solo una simple reubicación entre exchanges; si las tenencias de oro físico sí aumentan junto con él, eso sería evidencia más sólida de una entrada genuina de capital nuevo.</p>
<p class="de">Letztlich ist die Grenze zwischen einer einmaligen Neugewichtung und einer strukturellen Verschiebung klar genug. Zu bestätigen ist künftig, ob die kombinierte Marktkapitalisierung von XAUT und dem Konkurrenz-Token PAXG einen anhaltenden Nettozufluss-Trend statt einer einmaligen Abhebung zeigt, und ob der nächste Quartalsprüfbericht von Tether einen tatsächlichen Anstieg der physischen Goldbestände ausweist. Wachsen die geprüften Goldreserven nicht im Gleichschritt, handelt es sich bei dieser Abhebung wahrscheinlich nur um eine einfache Umschichtung zwischen Börsen; steigen die physischen Goldbestände hingegen mit, wäre das ein stärkerer Beleg für einen echten Zufluss neuen Kapitals.</p>
<p class="fr">En définitive, la ligne entre un simple rééquilibrage ponctuel et un basculement structurel est assez claire. Ce qu'il faudra confirmer à l'avenir, c'est si la capitalisation boursière combinée du XAUT et de son jeton rival PAXG affiche une tendance d'afflux net soutenu plutôt qu'un retrait ponctuel, et si le prochain rapport d'audit trimestriel de Tether montre une augmentation réelle des réserves d'or physique. Si les réserves d'or auditées ne croissent pas en parallèle, ce retrait ne sera probablement qu'une simple réallocation entre bourses ; si les avoirs en or physique augmentent bel et bien avec lui, ce serait une preuve plus solide d'un véritable afflux de nouveaux capitaux.</p>
<p class="pt">No fim das contas, a linha entre um rebalanceamento pontual e uma mudança estrutural é bastante clara. O que precisa ser confirmado daqui para frente é se a capitalização de mercado combinada de XAUT e de seu token rival PAXG mostra uma tendência sustentada de entrada líquida, e não uma retirada pontual, e se o próximo relatório de auditoria trimestral da Tether mostra um aumento real nas reservas de ouro físico. Se as reservas de ouro auditadas não crescerem junto, essa retirada provavelmente será apenas uma simples realocação entre exchanges; se as reservas de ouro físico aumentarem junto, isso seria uma evidência mais forte de uma entrada genuína de capital novo.</p>
<p class="tr">Sonuçta, tek seferlik bir yeniden dengeleme ile yapısal bir değişim arasındaki çizgi yeterince açık. Bundan sonra doğrulanması gereken şey, XAUT ile rakip tokeni PAXG'nin birleşik piyasa değerinin tek seferlik bir çekim yerine sürekli bir net giriş eğilimi gösterip göstermediği ve Tether'in bir sonraki üç aylık denetim raporunun fiziksel altın rezervlerinde gerçek bir artış gösterip göstermediği. Denetlenen altın rezervleri buna paralel büyümezse, bu çekimin yalnızca borsalar arası basit bir yeniden dağıtım olması muhtemel; fiziksel altın varlıkları da birlikte artarsa, bu gerçek bir yeni sermaye girişinin daha güçlü kanıtı olur.</p>
<p class="vi">Cuối cùng, ranh giới giữa một đợt tái cân bằng đơn lẻ và một sự dịch chuyển mang tính cấu trúc khá rõ ràng. Điều cần xác nhận trong thời gian tới là liệu tổng vốn hóa thị trường của XAUT và token đối thủ PAXG có cho thấy xu hướng dòng vốn ròng chảy vào bền vững thay vì chỉ là một đợt rút vốn đơn lẻ hay không, và liệu báo cáo kiểm toán quý tới của Tether có cho thấy lượng vàng vật chất nắm giữ thực sự tăng lên hay không. Nếu lượng vàng được kiểm toán không tăng song song, đợt rút này nhiều khả năng chỉ là một sự sắp xếp lại đơn giản giữa các sàn giao dịch; ngược lại, nếu lượng vàng vật chất nắm giữ cũng tăng theo, đó sẽ là bằng chứng mạnh hơn cho một dòng vốn mới thực sự.</p>

<div class="ko">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">금 ETF 유출 vs 온체인 금(XAUT) 고래 유입 규모</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">금 ETF 6월 순유출</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-89억 달러</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">아브락사스+고래 XAUT 인출(7.8, 8분간)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">약 1,990만 달러 (ETF 유출의 0.2% 규모)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">두 수치의 스케일 차이가 최대 450배에 달해, 아직은 선행 신호 정도로 봐야 한다.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">야후파이낸스·룩온체인·테케디아 보도 수치 기준.</p>
</div>
<div class="en">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Gold ETF outflow vs. onchain gold (XAUT) whale inflow</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">Gold ETFs, June net outflow</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-$8.9 billion</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">Abraxas + whale XAUT withdrawals (Jul 8, 8 min)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">~$19.9 million (0.2% of the ETF outflow)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">The scale gap runs up to ~450x, so for now this reads as a leading indicator at most.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Figures per Yahoo Finance, Lookonchain, and Tekedia reporting.</p>
</div>
<div class="ja">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">金ETF流出 vs オンチェーン金(XAUT)クジラ流入</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">金ETF 6月純流出</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-89億ドル</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">アブラクサス+クジラ XAUT引き出し(7/8、8分間)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">約1,990万ドル(ETF流出の0.2%規模)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">両者のスケール差は最大450倍に達し、現時点では先行シグナル程度と見るべきだ。</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">ヤフーファイナンス、ルックオンチェーン、テケディアの報道数値に基づく。</p>
</div>
<div class="es">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Salida de ETF de oro vs. entrada de ballenas en oro on-chain (XAUT)</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">ETF de oro, salida neta de junio</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-$8.900 millones</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">Retiros de XAUT de Abraxas + ballena (8 jul, 8 min)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">~$19,9 millones (0,2% de la salida de ETF)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">La brecha de escala llega hasta ~450x, así que por ahora es, a lo sumo, un indicador adelantado.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Cifras según Yahoo Finance, Lookonchain y Tekedia.</p>
</div>
<div class="de">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Gold-ETF-Abfluss vs. Onchain-Gold(XAUT)-Wal-Zufluss</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">Gold-ETFs, Nettoabfluss Juni</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-8,9 Mrd. USD</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">Abraxas + Wal-XAUT-Abhebungen (8. Juli, 8 Min.)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">~19,9 Mio. USD (0,2 % des ETF-Abflusses)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">Die Größenordnungslücke beträgt bis zu ~450x — vorerst also bestenfalls ein Frühindikator.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Zahlen laut Yahoo Finance, Lookonchain und Tekedia.</p>
</div>
<div class="fr">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Sortie des ETF sur l'or vs. entrée de baleines dans l'or on-chain (XAUT)</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">ETF sur l'or, sortie nette de juin</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-8,9 Md$</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">Retraits XAUT d'Abraxas + baleine (8 juil., 8 min)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">~19,9 M$ (0,2 % de la sortie des ETF)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">L'écart d'échelle atteint ~450x — pour l'instant, tout au plus un indicateur avancé.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Chiffres selon Yahoo Finance, Lookonchain et Tekedia.</p>
</div>
<div class="pt">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Saída de ETFs de ouro vs. entrada de baleias em ouro on-chain (XAUT)</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">ETFs de ouro, saída líquida em junho</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-US$ 8,9 bi</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">Retiradas de XAUT da Abraxas + baleia (8/7, 8 min)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">~US$ 19,9 mi (0,2% da saída dos ETFs)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">A diferença de escala chega a ~450x — por ora, no máximo um indicador antecedente.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Números conforme Yahoo Finance, Lookonchain e Tekedia.</p>
</div>
<div class="tr">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Altın ETF çıkışı ve zincir üstü altın (XAUT) balina girişi</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">Altın ETF'leri, Haziran net çıkışı</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-8,9 milyar $</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">Abraxas + balina XAUT çekimleri (8 Tem, 8 dk)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">~19,9 milyon $ (ETF çıkışının %0,2'si)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">Ölçek farkı ~450 kata kadar çıkıyor — şimdilik en fazla öncü bir gösterge.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Rakamlar Yahoo Finance, Lookonchain ve Tekedia haberlerine göredir.</p>
</div>
<div class="vi">
<svg viewBox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <text x="20" y="32" fill="#fafafa" font-size="15" font-weight="700" font-family="sans-serif">Dòng rút ETF vàng so với dòng vào của cá voi vàng on-chain (XAUT)</text>
  <g font-family="sans-serif">
    <text x="40" y="90" fill="#d4d4d8" font-size="14">ETF vàng, dòng rút ròng tháng 6</text>
    <rect x="40" y="105" width="600" height="42" rx="6" fill="#f87171" opacity="0.85"/>
    <text x="360" y="132" fill="#111113" font-size="15" font-weight="700" text-anchor="middle">-8,9 tỷ USD</text>
    <text x="40" y="200" fill="#d4d4d8" font-size="14">Abraxas + cá voi rút XAUT (8/7, trong 8 phút)</text>
    <rect x="40" y="215" width="14" height="42" rx="6" fill="#fbbf24" opacity="0.9"/>
    <text x="90" y="242" fill="#d4d4d8" font-size="14" font-weight="700">~19,9 triệu USD (0,2% dòng rút ETF)</text>
  </g>
  <text x="40" y="300" fill="#71717a" font-size="12">Khoảng cách quy mô lên tới ~450 lần — hiện tại nhiều nhất chỉ nên xem là chỉ báo sớm.</text>
</svg>
<p style="font-size:11px;color:#52525b;margin-top:-10px">Số liệu theo Yahoo Finance, Lookonchain và Tekedia.</p>
</div>

<div class="box ko">💡 <strong>지금 지켜봐야 할 것:</strong> (1) XAUT·PAXG를 합친 토큰화 금 시가총액이 이번 인출 이후에도 지속적인 순유입 추세를 보이는지, (2) 테더의 다음 분기 감사보고서에서 물리적 금 보유량이 실제로 늘어나는지, (3) 중동發 지정학적 긴장이 추가로 고조될 경우 비트코인과 토큰화 금 중 어느 쪽으로 안전자산 수요가 더 쏠리는지.</div>
<div class="box en">💡 <strong>What to watch now:</strong> (1) whether the combined market cap of XAUT and PAXG keeps showing a sustained net-inflow trend after this withdrawal; (2) whether Tether's next quarterly audit report shows an actual rise in physical gold holdings; and (3) if Middle East tensions escalate further, whether safe-haven demand tilts more toward Bitcoin or toward tokenized gold.</div>
<div class="box ja">💡 <strong>今後注視すべきこと:</strong> (1) XAUTとPAXGを合わせたトークン化金の時価総額が、今回の引き出し後も持続的な純流入トレンドを示すか、(2) テザーの次期四半期監査報告書で物理的金保有量が実際に増加するか、(3) 中東発の地政学的緊張がさらに高まった場合、ビットコインとトークン化金のどちらに安全資産需要がより偏るか。</div>
<div class="box es">💡 <strong>Qué vigilar ahora:</strong> (1) si la capitalización de mercado combinada de XAUT y PAXG sigue mostrando una tendencia sostenida de entrada neta tras este retiro; (2) si el próximo informe de auditoría trimestral de Tether muestra un aumento real en las tenencias de oro físico; y (3) si las tensiones en Oriente Medio se agravan aún más, hacia qué lado se inclina más la demanda de refugio seguro: bitcoin o el oro tokenizado.</div>
<div class="box de">💡 <strong>Worauf jetzt zu achten ist:</strong> (1) ob die kombinierte Marktkapitalisierung von XAUT und PAXG auch nach dieser Abhebung einen anhaltenden Nettozufluss-Trend zeigt; (2) ob der nächste Quartalsprüfbericht von Tether einen tatsächlichen Anstieg der physischen Goldbestände ausweist; und (3) sollten sich die Spannungen im Nahen Osten weiter verschärfen, ob sich die Nachfrage nach sicheren Häfen stärker in Richtung Bitcoin oder tokenisiertes Gold verschiebt.</div>
<div class="box fr">💡 <strong>À surveiller maintenant :</strong> (1) si la capitalisation boursière combinée du XAUT et du PAXG continue d'afficher une tendance d'afflux net soutenu après ce retrait ; (2) si le prochain rapport d'audit trimestriel de Tether montre une augmentation réelle des avoirs en or physique ; et (3) si les tensions au Moyen-Orient s'aggravent encore, si la demande de valeur refuge penche davantage vers le bitcoin ou vers l'or tokenisé.</div>
<div class="box pt">💡 <strong>O que observar agora:</strong> (1) se a capitalização de mercado combinada de XAUT e PAXG continua mostrando uma tendência sustentada de entrada líquida após essa retirada; (2) se o próximo relatório de auditoria trimestral da Tether mostra um aumento real nas reservas de ouro físico; e (3) se as tensões no Oriente Médio se agravarem ainda mais, para qual lado a demanda por refúgio seguro pende mais — bitcoin ou ouro tokenizado.</div>
<div class="box tr">💡 <strong>Şimdi izlenmesi gerekenler:</strong> (1) XAUT ve PAXG'nin birleşik piyasa değerinin bu çekimden sonra da sürekli bir net giriş eğilimi göstermeye devam edip etmeyeceği; (2) Tether'in bir sonraki üç aylık denetim raporunun fiziksel altın varlıklarında gerçek bir artış gösterip göstermeyeceği; ve (3) Orta Doğu'daki gerilimler daha da tırmanırsa güvenli liman talebinin Bitcoin'e mi yoksa tokenleştirilmiş altına mı daha çok kayacağı.</div>
<div class="box vi">💡 <strong>Điều cần theo dõi lúc này:</strong> (1) liệu tổng vốn hóa thị trường của XAUT và PAXG có tiếp tục cho thấy xu hướng dòng vốn ròng chảy vào bền vững sau đợt rút này hay không; (2) liệu báo cáo kiểm toán quý tới của Tether có cho thấy lượng vàng vật chất nắm giữ thực sự tăng lên hay không; và (3) nếu căng thẳng Trung Đông leo thang hơn nữa, nhu cầu trú ẩn an toàn sẽ nghiêng nhiều hơn về Bitcoin hay vàng token hóa.</div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 룩온체인(Lookonchain) 온체인 분석, 비트코인월드(Bitcoin World), 크립토뉴스(CryptoNews.net), 블록체인닷뉴스(Blockchain.News), 테케디아(Tekedia)의 금 ETF 유출 관련 보도, 옐로(Yellow.com)의 골드실버(GoldSilver.com) 인용 보도, 야후파이낸스의 금 ETF 유출 집계, 테더 공식 XAUT 감사보고서 페이지.</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: Lookonchain on-chain analytics, Bitcoin World, CryptoNews.net, Blockchain.News, Tekedia's reporting on gold ETF outflows, Yellow.com (citing GoldSilver.com), Yahoo Finance's gold ETF outflow tally, and Tether's official XAUT audit report page.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: ルックオンチェーン(Lookonchain)のオンチェーン分析、ビットコインワールド(Bitcoin World)、クリプトニュース(CryptoNews.net)、ブロックチェーン・ニュース(Blockchain.News)、テケディア(Tekedia)の金ETF流出関連報道、イエロー(Yellow.com、ゴールドシルバー(GoldSilver.com)引用)、ヤフーファイナンスの金ETF流出集計、テザー公式XAUT監査報告書ページ。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: análisis on-chain de Lookonchain, Bitcoin World, CryptoNews.net, Blockchain.News, la cobertura de Tekedia sobre las salidas de los ETF de oro, Yellow.com (citando a GoldSilver.com), el recuento de salidas de ETF de oro de Yahoo Finance, y la página oficial de informes de auditoría de XAUT de Tether.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: On-Chain-Analyse von Lookonchain, Bitcoin World, CryptoNews.net, Blockchain.News, Tekedias Berichterstattung über Gold-ETF-Abflüsse, Yellow.com (unter Berufung auf GoldSilver.com), Yahoo Finances Zusammenstellung der Gold-ETF-Abflüsse und die offizielle XAUT-Prüfbericht-Seite von Tether.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : analyse on-chain de Lookonchain, Bitcoin World, CryptoNews.net, Blockchain.News, la couverture de Tekedia sur les sorties des ETF sur l'or, Yellow.com (citant GoldSilver.com), le décompte des sorties d'ETF sur l'or de Yahoo Finance, et la page officielle des rapports d'audit XAUT de Tether.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: análise on-chain da Lookonchain, Bitcoin World, CryptoNews.net, Blockchain.News, a cobertura da Tekedia sobre as saídas dos ETFs de ouro, Yellow.com (citando GoldSilver.com), o levantamento de saídas de ETF de ouro da Yahoo Finance, e a página oficial de relatórios de auditoria da XAUT da Tether.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: Lookonchain zincir üstü analiz, Bitcoin World, CryptoNews.net, Blockchain.News, Tekedia'nın altın ETF çıkışlarına ilişkin haberleri, Yellow.com (GoldSilver.com'dan alıntıyla), Yahoo Finance'in altın ETF çıkış toplamı ve Tether'in resmi XAUT denetim raporu sayfası.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: phân tích on-chain của Lookonchain, Bitcoin World, CryptoNews.net, Blockchain.News, bài đưa tin của Tekedia về dòng rút khỏi ETF vàng, Yellow.com (trích dẫn GoldSilver.com), thống kê dòng rút ETF vàng của Yahoo Finance, và trang báo cáo kiểm toán XAUT chính thức của Tether.</p>
<?php require __DIR__.'/_footer.php'; ?>
