<?php $slug = 'xrp-etf-july-high-inflow-rebound'; require __DIR__.'/_header.php'; ?>

<p class="ko">미국에 상장된 현물 XRP ETF 7종이 7월16일 하루 동안 678만달러의 순유입을 기록했다고 크립토타임스(CryptoTimes)가 전했다. 이는 7월 들어 하루 기준 최대 유입액이다. 비트와이즈(Bitwise) XRP ETF가 441만달러로 유입을 주도했고, 프랭클린(Franklin) XRP ETF(XRPZ)가 238만달러를 더했다. 반면 캐너리(Canary)의 XRPC, 21셰어스(21Shares)의 TOXR, 그레이스케일(Grayscale)의 GXRP는 이날 순유입이 없었다. 이번 유입으로 누적 순유입액은 14억9,000만달러로 늘었고, 전체 순자산은 약 9억9,700만달러로 집계됐다.</p>
<p class="en">Seven U.S.-listed spot XRP ETFs recorded a combined $6.78 million in net inflows on July 16, according to CryptoTimes — the largest single-day figure of July so far. The Bitwise XRP ETF led with $4.41 million, and the Franklin XRP ETF (XRPZ) added $2.38 million. Canary's XRPC, 21Shares' TOXR and Grayscale's GXRP saw no net flow that day. The inflow pushed cumulative net inflows across U.S. spot XRP ETFs to $1.49 billion, with total net assets at roughly $997.18 million.</p>
<p class="ja">米国上場の現物XRP ETF7銘柄が7月16日、合計678万ドルの純流入を記録したとクリプトタイムズ(CryptoTimes)が伝えた。これは7月に入って以降、一日あたりの流入額としては最大だ。ビットワイズ(Bitwise)のXRP ETFが441万ドルで流入を主導し、フランクリン(Franklin)のXRP ETF(XRPZ)が238万ドルを追加した。一方、キャナリー(Canary)のXRPC、21シェアーズ(21Shares)のTOXR、グレースケール(Grayscale)のGXRPはこの日、純流入がなかった。この流入により累積純流入額は14億9,000万ドルに達し、純資産総額は約9億9,700万ドルとなった。</p>
<p class="es">Siete ETF al contado de XRP que cotizan en EE.UU. registraron en conjunto $6.78 millones en entradas netas el 16 de julio, según CryptoTimes, la cifra diaria más alta de julio hasta ahora. El ETF Bitwise XRP lideró con $4.41 millones, y el ETF Franklin XRP (XRPZ) añadió $2.38 millones. El XRPC de Canary, el TOXR de 21Shares y el GXRP de Grayscale no registraron flujo neto ese día. La entrada elevó las entradas netas acumuladas de los ETF al contado de XRP en EE.UU. a $1,490 millones, con activos netos totales de aproximadamente $997.18 millones.</p>
<p class="de">Sieben in den USA gelistete Spot-XRP-ETFs verzeichneten am 16. Juli zusammen Nettozuflüsse von 6,78 Millionen Dollar, so CryptoTimes — der bisher höchste Tageswert im Juli. Der Bitwise-XRP-ETF führte mit 4,41 Millionen Dollar, und der Franklin-XRP-ETF (XRPZ) fügte 2,38 Millionen Dollar hinzu. Canarys XRPC, 21Shares' TOXR und Grayscales GXRP verzeichneten an diesem Tag keinen Nettofluss. Der Zufluss trieb die kumulierten Nettozuflüsse der US-Spot-XRP-ETFs auf 1,49 Milliarden Dollar, bei einem Gesamtnettovermögen von rund 997,18 Millionen Dollar.</p>
<p class="fr">Sept ETF au comptant XRP cotés aux États-Unis ont enregistré ensemble 6,78 millions de dollars d'entrées nettes le 16 juillet, selon CryptoTimes — le chiffre journalier le plus élevé de juillet à ce jour. L'ETF Bitwise XRP a mené avec 4,41 millions de dollars, et l'ETF Franklin XRP (XRPZ) a ajouté 2,38 millions de dollars. Le XRPC de Canary, le TOXR de 21Shares et le GXRP de Grayscale n'ont enregistré aucun flux net ce jour-là. Cette entrée a porté les entrées nettes cumulées des ETF au comptant XRP américains à 1,49 milliard de dollars, pour un actif net total d'environ 997,18 millions de dollars.</p>
<p class="pt">Sete ETFs à vista de XRP listados nos EUA registraram, em conjunto, US$ 6,78 milhões em entradas líquidas em 16 de julho, segundo a CryptoTimes — o maior número diário de julho até agora. O ETF Bitwise XRP liderou com US$ 4,41 milhões, e o ETF Franklin XRP (XRPZ) acrescentou US$ 2,38 milhões. O XRPC da Canary, o TOXR da 21Shares e o GXRP da Grayscale não registraram fluxo líquido naquele dia. A entrada elevou as entradas líquidas acumuladas dos ETFs à vista de XRP nos EUA para US$ 1,49 bilhão, com ativos líquidos totais de aproximadamente US$ 997,18 milhões.</p>
<p class="tr">ABD'de işlem gören yedi spot XRP ETF'i, CryptoTimes'a göre 16 Temmuz'da toplam 6,78 milyon dolarlık net girişle Temmuz ayının şimdiye kadarki en yüksek günlük rakamını kaydetti. Bitwise XRP ETF'i 4,41 milyon dolarla öncülük ederken, Franklin XRP ETF'i (XRPZ) 2,38 milyon dolar ekledi. Canary'nin XRPC'si, 21Shares'in TOXR'ı ve Grayscale'in GXRP'si o gün net akış görmedi. Bu giriş, ABD spot XRP ETF'lerindeki kümülatif net girişleri 1,49 milyar dolara çıkardı ve toplam net varlıklar yaklaşık 997,18 milyon dolar oldu.</p>
<p class="vi">Bảy ETF giao ngay XRP niêm yết tại Mỹ ghi nhận tổng cộng 6,78 triệu đô la dòng vốn ròng vào ngày 16/7, theo CryptoTimes — con số cao nhất trong ngày của tháng 7 tính đến nay. ETF Bitwise XRP dẫn đầu với 4,41 triệu đô la, và ETF Franklin XRP (XRPZ) đóng góp thêm 2,38 triệu đô la. XRPC của Canary, TOXR của 21Shares và GXRP của Grayscale không ghi nhận dòng vốn ròng nào trong ngày đó. Dòng vốn này đã đẩy tổng dòng vốn ròng lũy kế của các ETF giao ngay XRP tại Mỹ lên 1,49 tỷ đô la, với tổng tài sản ròng khoảng 997,18 triệu đô la.</p>
<p class="id">Tujuh ETF spot XRP yang terdaftar di AS mencatat gabungan arus masuk bersih $6,78 juta pada 16 Juli, menurut CryptoTimes — angka harian tertinggi bulan Juli sejauh ini. ETF Bitwise XRP memimpin dengan $4,41 juta, dan ETF Franklin XRP (XRPZ) menambahkan $2,38 juta. XRPC milik Canary, TOXR milik 21Shares, dan GXRP milik Grayscale tidak mencatat arus bersih pada hari itu. Arus masuk ini mendorong arus masuk bersih kumulatif ETF spot XRP AS menjadi $1,49 miliar, dengan total aset bersih sekitar $997,18 juta.</p>
<p class="pl">Siedem notowanych w USA ETF-ów spot na XRP odnotowało łącznie 6,78 mln USD napływów netto 16 lipca, według CryptoTimes — najwyższy dzienny wynik lipca jak dotąd. ETF Bitwise XRP przewodził z 4,41 mln USD, a ETF Franklin XRP (XRPZ) dodał 2,38 mln USD. XRPC od Canary, TOXR od 21Shares i GXRP od Grayscale nie odnotowały tego dnia żadnego przepływu netto. Napływ ten podniósł skumulowane napływy netto amerykańskich ETF-ów spot na XRP do 1,49 mld USD, przy łącznych aktywach netto wynoszących około 997,18 mln USD.</p>
<p class="it">Sette ETF spot su XRP quotati negli Stati Uniti hanno registrato complessivamente 6,78 milioni di dollari di afflussi netti il 16 luglio, secondo CryptoTimes — il dato giornaliero più alto di luglio finora. L'ETF Bitwise XRP ha guidato con 4,41 milioni di dollari, e l'ETF Franklin XRP (XRPZ) ha aggiunto 2,38 milioni di dollari. XRPC di Canary, TOXR di 21Shares e GXRP di Grayscale non hanno registrato flussi netti quel giorno. L'afflusso ha portato gli afflussi netti cumulativi degli ETF spot su XRP statunitensi a 1,49 miliardi di dollari, con un patrimonio netto totale di circa 997,18 milioni di dollari.</p>
<p class="ru">Семь спотовых XRP ETF, торгующихся в США, зафиксировали в сумме 6,78 млн долларов чистого притока 16 июля, по данным CryptoTimes — крупнейший дневной показатель июля на данный момент. ETF Bitwise XRP лидировал с 4,41 млн долларов, а ETF Franklin XRP (XRPZ) добавил 2,38 млн долларов. У XRPC от Canary, TOXR от 21Shares и GXRP от Grayscale в этот день не было чистого потока. Приток поднял совокупный чистый приток по спотовым XRP ETF в США до 1,49 млрд долларов, при общих чистых активах около 997,18 млн долларов.</p>
<p class="zh">據CryptoTimes報導,美國上市的七檔XRP現貨ETF於7月16日合計錄得678萬美元淨流入——這是截至目前7月單日最高紀錄。比特懷斯(Bitwise)XRP ETF以441萬美元領先流入,富蘭克林(Franklin)XRP ETF(XRPZ)則新增238萬美元。相較之下,Canary的XRPC、21Shares的TOXR與Grayscale的GXRP當日並無淨流入。這波流入使美國XRP現貨ETF的累計淨流入達到14.9億美元,總淨資產約為9.9718億美元。</p>

<h2 class="ko">유출에서 유입으로 — 일주일 만의 반전</h2>
<h2 class="en">From Outflow to Inflow — A Reversal in a Week</h2>
<h2 class="ja">流出から流入へ — わずか1週間での反転</h2>
<h2 class="es">De la Salida a la Entrada — Un Giro en Una Semana</h2>
<h2 class="de">Vom Abfluss zum Zufluss — Eine Kehrtwende Innerhalb Einer Woche</h2>
<h2 class="fr">De la Sortie à l'Entrée — Un Revirement en Une Semaine</h2>
<h2 class="pt">Da Saída para a Entrada — Uma Reviravolta em Uma Semana</h2>
<h2 class="tr">Çıkıştan Girişe — Bir Haftada Yaşanan Tersine Dönüş</h2>
<h2 class="vi">Từ Dòng Vốn Ra Đến Dòng Vốn Vào — Sự Đảo Chiều Trong Một Tuần</h2>
<h2 class="id">Dari Arus Keluar ke Arus Masuk — Pembalikan dalam Seminggu</h2>
<h2 class="pl">Od Odpływu do Napływu — Zwrot w Ciągu Tygodnia</h2>
<h2 class="it">Dal Deflusso all'Afflusso — Un'Inversione in Una Settimana</h2>
<h2 class="ru">От Оттока к Притоку — Разворот за Неделю</h2>
<h2 class="zh">從流出到流入——一週內的逆轉</h2>

<p class="ko">이번 반등은 불과 일주일 전 상황과 뚜렷이 대비된다. <a href="/blog/xrp-whale-tx-collapse-etf-streak-reversal">7월9일 마감 주간</a>, 미국 현물 XRP ETF는 9주 연속·누적 14억8,000만달러 순유입 기록을 깨고 729만달러 순유출을 기록한 바 있으며, 당시 이 유출 전량을 비트와이즈 ETF 한 곳이 흡수했다. 같은 주 XRP 원장에서 100만달러가 넘는 대형 거래 건수도 70건에서 2건으로 97% 급감해, 온체인 활동과 ETF 자금 모두 동시에 위축되는 모습을 보였다. 그런데 불과 며칠 뒤인 7월16일, 바로 그 비트와이즈 ETF가 이번에는 441만달러 순유입으로 반등을 주도하며 흐름을 뒤집었다.</p>
<p class="en">The rebound stands in sharp contrast to the picture just a week earlier. In <a href="/en/blog/xrp-whale-tx-collapse-etf-streak-reversal">the week ending July 9</a>, U.S. spot XRP ETFs broke a nine-week, cumulative $1.48 billion inflow streak and posted a $7.29 million net outflow, all of it absorbed by the Bitwise ETF alone. That same week, XRP Ledger transactions above $1 million collapsed 97%, from around 70 to just 2, so both on-chain activity and ETF flows contracted at the same time. Only days later, on July 16, that same Bitwise fund flipped the script, leading the rebound with $4.41 million in net inflows.</p>
<p class="ja">今回の反発は、わずか1週間前の状況とは対照的だ。<a href="/ja/blog/xrp-whale-tx-collapse-etf-streak-reversal">7月9日終了週</a>、米国の現物XRP ETFは9週連続・累計14億8,000万ドルの純流入記録を破り、729万ドルの純流出を記録した。当時、この流出はすべてビットワイズのETF一社が吸収した。同じ週にはXRP台帳上の100万ドル超の大口取引件数も70件から2件へと97%急減し、オンチェーン活動とETF資金の両方が同時に縮小する様相を見せた。ところが、わずか数日後の7月16日、まさにそのビットワイズETFが今度は441万ドルの純流入で反発を主導し、流れを覆した。</p>
<p class="es">El repunte contrasta claramente con la situación de apenas una semana antes. En <a href="/es/blog/xrp-whale-tx-collapse-etf-streak-reversal">la semana que terminó el 9 de julio</a>, los ETF al contado de XRP en EE.UU. rompieron una racha de nueve semanas y $1,480 millones acumulados en entradas, registrando una salida neta de $7.29 millones, absorbida en su totalidad por el ETF de Bitwise. Esa misma semana, las transacciones de más de $1 millón en el libro mayor de XRP se desplomaron un 97%, de unas 70 a solo 2, por lo que tanto la actividad on-chain como los flujos de ETF se contrajeron al mismo tiempo. Apenas días después, el 16 de julio, ese mismo fondo de Bitwise invirtió el guion, liderando el repunte con $4.41 millones en entradas netas.</p>
<p class="de">Die Erholung steht in scharfem Kontrast zum Bild nur eine Woche zuvor. In der <a href="/de/blog/xrp-whale-tx-collapse-etf-streak-reversal">Woche bis zum 9. Juli</a> durchbrachen US-Spot-XRP-ETFs eine neunwöchige, kumuliert 1,48 Milliarden Dollar schwere Zuflussserie und verzeichneten einen Nettoabfluss von 7,29 Millionen Dollar, den allein der Bitwise-ETF auffing. In derselben Woche brachen die XRP-Ledger-Transaktionen über 1 Million Dollar um 97 Prozent ein, von rund 70 auf nur 2 — sodass sich sowohl On-Chain-Aktivität als auch ETF-Flüsse gleichzeitig zusammenzogen. Nur Tage später, am 16. Juli, drehte genau dieser Bitwise-Fonds das Blatt und führte die Erholung mit Nettozuflüssen von 4,41 Millionen Dollar an.</p>
<p class="fr">Ce rebond contraste nettement avec la situation observée une semaine plus tôt seulement. Lors de <a href="/fr/blog/xrp-whale-tx-collapse-etf-streak-reversal">la semaine se terminant le 9 juillet</a>, les ETF au comptant XRP américains ont rompu une série de neuf semaines et 1,48 milliard de dollars cumulés d'entrées, enregistrant une sortie nette de 7,29 millions de dollars, entièrement absorbée par le seul ETF Bitwise. La même semaine, les transactions de plus d'1 million de dollars sur le grand livre XRP ont chuté de 97 %, passant d'environ 70 à seulement 2, si bien que l'activité on-chain et les flux ETF se sont contractés simultanément. Quelques jours plus tard seulement, le 16 juillet, ce même fonds Bitwise a inversé la tendance, menant le rebond avec 4,41 millions de dollars d'entrées nettes.</p>
<p class="pt">A recuperação contrasta fortemente com o quadro de apenas uma semana antes. Na <a href="/pt/blog/xrp-whale-tx-collapse-etf-streak-reversal">semana encerrada em 9 de julho</a>, os ETFs à vista de XRP nos EUA romperam uma sequência de nove semanas e US$ 1,48 bilhão acumulado em entradas, registrando uma saída líquida de US$ 7,29 milhões, toda ela absorvida apenas pelo ETF da Bitwise. Na mesma semana, as transações acima de US$ 1 milhão no livro-razão do XRP despencaram 97%, de cerca de 70 para apenas 2, de modo que tanto a atividade on-chain quanto os fluxos de ETF se contraíram ao mesmo tempo. Apenas dias depois, em 16 de julho, esse mesmo fundo da Bitwise virou o jogo, liderando a recuperação com US$ 4,41 milhões em entradas líquidas.</p>
<p class="tr">Bu toparlanma, yalnızca bir hafta önceki tabloyla keskin bir tezat oluşturuyor. <a href="/tr/blog/xrp-whale-tx-collapse-etf-streak-reversal">9 Temmuz'da biten hafta</a>, ABD spot XRP ETF'leri dokuz haftalık, kümülatif 1,48 milyar dolarlık giriş serisini kırarak 7,29 milyon dolarlık net çıkış kaydetti ve bunun tamamını yalnızca Bitwise ETF'i karşıladı. Aynı hafta, XRP defterinde 1 milyon doları aşan işlemler yaklaşık 70'ten yalnızca 2'ye, yani %97 çöktü; böylece hem zincir üstü faaliyet hem de ETF akışları aynı anda daraldı. Yalnızca birkaç gün sonra, 16 Temmuz'da, tam da o Bitwise fonu senaryoyu tersine çevirerek 4,41 milyon dolarlık net girişle toparlanmaya öncülük etti.</p>
<p class="vi">Sự phục hồi này tương phản rõ rệt với bức tranh chỉ một tuần trước đó. Trong <a href="/vi/blog/xrp-whale-tx-collapse-etf-streak-reversal">tuần kết thúc vào ngày 9/7</a>, các ETF giao ngay XRP tại Mỹ đã chấm dứt chuỗi 9 tuần với tổng cộng 1,48 tỷ đô la dòng vốn vào, ghi nhận dòng vốn ròng ra 7,29 triệu đô la, toàn bộ được hấp thụ bởi một mình ETF Bitwise. Cùng tuần đó, các giao dịch trên 1 triệu đô la trên sổ cái XRP sụt giảm 97%, từ khoảng 70 xuống chỉ còn 2, khiến cả hoạt động on-chain lẫn dòng vốn ETF đều co lại cùng lúc. Chỉ vài ngày sau, vào ngày 16/7, chính quỹ Bitwise đó đã đảo ngược tình thế, dẫn đầu đà phục hồi với 4,41 triệu đô la dòng vốn ròng vào.</p>
<p class="id">Kebangkitan ini sangat kontras dengan gambaran hanya seminggu sebelumnya. Pada <a href="/id/blog/xrp-whale-tx-collapse-etf-streak-reversal">minggu yang berakhir 9 Juli</a>, ETF spot XRP AS memutus rentetan sembilan minggu dengan total kumulatif $1,48 miliar arus masuk dan mencatat arus keluar bersih $7,29 juta, yang seluruhnya diserap oleh ETF Bitwise sendirian. Pada minggu yang sama, transaksi di atas $1 juta di buku besar XRP anjlok 97%, dari sekitar 70 menjadi hanya 2, sehingga aktivitas on-chain dan aliran ETF sama-sama menyusut bersamaan. Hanya beberapa hari kemudian, pada 16 Juli, dana Bitwise yang sama itu membalikkan keadaan, memimpin kebangkitan dengan arus masuk bersih $4,41 juta.</p>
<p class="pl">Odbicie ostro kontrastuje z obrazem sprzed zaledwie tygodnia. W <a href="/pl/blog/xrp-whale-tx-collapse-etf-streak-reversal">tygodniu kończącym się 9 lipca</a> amerykańskie ETF-y spot na XRP przerwały dziewięciotygodniową, skumulowaną serię napływów o wartości 1,48 mld USD i odnotowały odpływ netto w wysokości 7,29 mln USD, w całości pochłonięty przez sam ETF Bitwise. W tym samym tygodniu transakcje powyżej 1 mln USD w rejestrze XRP załamały się o 97%, z około 70 do zaledwie 2, więc zarówno aktywność on-chain, jak i przepływy ETF skurczyły się jednocześnie. Zaledwie kilka dni później, 16 lipca, ten sam fundusz Bitwise odwrócił scenariusz, prowadząc odbicie z napływami netto w wysokości 4,41 mln USD.</p>
<p class="it">Il rimbalzo contrasta nettamente con il quadro di appena una settimana prima. Nella <a href="/it/blog/xrp-whale-tx-collapse-etf-streak-reversal">settimana conclusasi il 9 luglio</a>, gli ETF spot su XRP statunitensi hanno interrotto una serie di nove settimane e 1,48 miliardi di dollari cumulativi di afflussi, registrando un deflusso netto di 7,29 milioni di dollari, interamente assorbito dal solo ETF Bitwise. Nella stessa settimana, le transazioni superiori a 1 milione di dollari sul registro XRP sono crollate del 97%, da circa 70 a sole 2, per cui sia l'attività on-chain sia i flussi ETF si sono contratti contemporaneamente. Solo pochi giorni dopo, il 16 luglio, proprio quel fondo Bitwise ha ribaltato la situazione, guidando il rimbalzo con 4,41 milioni di dollari di afflussi netti.</p>
<p class="ru">Восстановление резко контрастирует с картиной всего неделей ранее. На <a href="/ru/blog/xrp-whale-tx-collapse-etf-streak-reversal">неделе, завершившейся 9 июля</a>, спотовые XRP ETF в США прервали девятинедельную серию с совокупным притоком в 1,48 млрд долларов, показав чистый отток в 7,29 млн долларов, который полностью поглотил один лишь ETF Bitwise. На той же неделе транзакции свыше 1 млн долларов в реестре XRP обрушились на 97%, примерно с 70 до всего 2, так что и ончейн-активность, и потоки ETF сократились одновременно. Всего через несколько дней, 16 июля, тот же фонд Bitwise перевернул сценарий, возглавив восстановление с чистым притоком в 4,41 млн долларов.</p>
<p class="zh">這波反彈與僅僅一週前的局面形成鮮明對比。在<a href="/zh/blog/xrp-whale-tx-collapse-etf-streak-reversal">截至7月9日的那一週</a>,美國XRP現貨ETF終結了連續9週、累計14.8億美元的淨流入紀錄,錄得729萬美元淨流出,而這筆流出全數由比特懷斯一家ETF吸收。同一週,XRP帳本上超過100萬美元的大額交易也從約70筆驟減97%至僅2筆,鏈上活動與ETF資金同時萎縮。然而僅僅數天後的7月16日,正是同一檔比特懷斯基金扭轉局面,以441萬美元淨流入領軍這波反彈。</p>

<p class="ko">이 반전의 메커니즘을 이해하려면 ETF의 설정·환매(creation/redemption) 구조를 볼 필요가 있다. 현물 ETF의 일일 순유입·유출은 지정참가회사(AP)가 실제 수요에 맞춰 신규 좌수를 설정하거나 기존 좌수를 환매하는 과정에서 발생하며, 이 단위는 대개 개인 소액 투자자가 아니라 소수의 기관·마켓메이커가 움직인다. 그래서 유출입 액수가 특정 발행사 한 곳에 쏠려 있다는 것은 시장 전반의 방향 전환이라기보다, 소수 참여자의 포지션 조정일 가능성을 시사한다. 실제로 이번에도 유입액 678만달러 중 441만달러(65%)가 비트와이즈 한 곳에서 나왔다.</p>
<p class="en">Understanding the mechanism behind this reversal requires looking at how spot ETFs actually create and redeem shares. Daily net inflows or outflows happen when authorized participants (APs) create new shares or redeem existing ones to match real demand — and that activity is typically driven by a handful of institutions and market makers, not retail investors trading in small size. When flows are concentrated in a single issuer, that's a signal it may reflect a few participants adjusting positions rather than a broad shift in market direction. Indeed, $4.41 million of the day's $6.78 million inflow — about 65% — came from Bitwise alone.</p>
<p class="ja">この反転のメカニズムを理解するには、現物ETFの設定・償還(creation/redemption)の仕組みを見る必要がある。現物ETFの日次純流入・流出は、指定参加者(AP)が実需に合わせて新規口数を設定したり、既存口数を償還したりする過程で発生し、この単位は通常、個人の少額投資家ではなく、少数の機関やマーケットメーカーが動かしている。そのため、流出入額が特定の一発行会社に集中しているということは、市場全体の方向転換というより、少数の参加者によるポジション調整である可能性を示唆する。実際、今回も流入額678万ドルのうち441万ドル(65%)がビットワイズ一社から出たものだった。</p>
<p class="es">Entender el mecanismo detrás de esta reversión requiere ver cómo los ETF al contado crean y canjean realmente sus participaciones. Las entradas o salidas netas diarias ocurren cuando los participantes autorizados (AP) crean nuevas participaciones o canjean las existentes para ajustarse a la demanda real, y esa actividad suele estar impulsada por un puñado de instituciones y creadores de mercado, no por inversores minoristas que operan en pequeña escala. Cuando los flujos se concentran en un solo emisor, es una señal de que podría reflejar el ajuste de posiciones de unos pocos participantes más que un giro amplio en la dirección del mercado. De hecho, $4.41 millones de los $6.78 millones de entrada del día —cerca del 65%— provinieron solo de Bitwise.</p>
<p class="de">Um den Mechanismus hinter dieser Umkehr zu verstehen, muss man betrachten, wie Spot-ETFs tatsächlich Anteile schaffen und zurücknehmen. Tägliche Nettozu- oder -abflüsse entstehen, wenn autorisierte Teilnehmer (APs) neue Anteile schaffen oder bestehende zurückgeben, um die tatsächliche Nachfrage abzubilden — und dieses Geschehen wird typischerweise von einer Handvoll Institutionen und Market-Makern getrieben, nicht von Kleinanlegern mit geringem Volumen. Wenn sich Flüsse bei einem einzelnen Emittenten konzentrieren, ist das ein Signal, dass dies eher die Positionsanpassung weniger Teilnehmer widerspiegeln könnte als eine breite Richtungsänderung des Marktes. Tatsächlich stammten 4,41 Millionen Dollar des Tageszuflusses von 6,78 Millionen Dollar — rund 65 Prozent — allein von Bitwise.</p>
<p class="fr">Comprendre le mécanisme derrière ce renversement nécessite d'examiner comment les ETF au comptant créent et rachètent réellement des parts. Les entrées ou sorties nettes quotidiennes se produisent lorsque des participants autorisés (AP) créent de nouvelles parts ou rachètent des parts existantes pour répondre à la demande réelle — une activité généralement menée par une poignée d'institutions et de teneurs de marché, pas par des investisseurs particuliers négociant de petites quantités. Lorsque les flux se concentrent chez un seul émetteur, c'est le signe qu'il s'agit peut-être de l'ajustement de position de quelques participants plutôt que d'un large virage de la direction du marché. En effet, 4,41 millions de dollars des 6,78 millions d'entrées du jour — environ 65 % — provenaient de Bitwise seul.</p>
<p class="pt">Entender o mecanismo por trás dessa reversão exige observar como os ETFs à vista realmente criam e resgatam cotas. As entradas ou saídas líquidas diárias ocorrem quando participantes autorizados (APs) criam novas cotas ou resgatam cotas existentes para corresponder à demanda real — e essa atividade costuma ser impulsionada por um punhado de instituições e formadores de mercado, não por investidores de varejo negociando em pequena escala. Quando os fluxos se concentram em um único emissor, é um sinal de que pode refletir o ajuste de posição de poucos participantes, e não uma ampla mudança na direção do mercado. De fato, US$ 4,41 milhões dos US$ 6,78 milhões de entrada do dia — cerca de 65% — vieram apenas da Bitwise.</p>
<p class="tr">Bu tersine dönüşün arkasındaki mekanizmayı anlamak, spot ETF'lerin pay yaratma ve geri alma sürecine bakmayı gerektirir. Günlük net giriş veya çıkışlar, yetkili katılımcıların (AP) gerçek talebe uyacak şekilde yeni pay yaratması veya mevcut payları geri alması sonucunda gerçekleşir ve bu faaliyet genellikle küçük ölçekte işlem yapan bireysel yatırımcılar değil, bir avuç kurum ve piyasa yapıcısı tarafından yönlendirilir. Akışlar tek bir ihraççıda yoğunlaştığında, bu durum piyasa yönünde geniş bir değişimden çok, birkaç katılımcının pozisyon ayarlamasını yansıtabileceğinin bir işaretidir. Nitekim, günün 6,78 milyon dolarlık girişinin 4,41 milyon doları — yaklaşık %65'i — yalnızca Bitwise'tan geldi.</p>
<p class="vi">Để hiểu cơ chế đằng sau sự đảo chiều này, cần xem xét cách các ETF giao ngay thực sự tạo lập và mua lại chứng chỉ quỹ. Dòng vốn ròng vào hoặc ra hằng ngày xảy ra khi các bên tham gia được ủy quyền (AP) tạo lập chứng chỉ mới hoặc mua lại chứng chỉ hiện có để khớp với nhu cầu thực tế — và hoạt động này thường do một số ít tổ chức và nhà tạo lập thị trường thúc đẩy, chứ không phải nhà đầu tư nhỏ lẻ giao dịch quy mô nhỏ. Khi dòng vốn tập trung vào một tổ chức phát hành duy nhất, đó là tín hiệu cho thấy có thể phản ánh việc điều chỉnh vị thế của một vài bên tham gia, hơn là một sự thay đổi hướng rộng rãi của thị trường. Thật vậy, 4,41 triệu đô la trong tổng số 6,78 triệu đô la dòng vốn vào ngày hôm đó — khoảng 65% — chỉ đến từ một mình Bitwise.</p>
<p class="id">Memahami mekanisme di balik pembalikan ini memerlukan pemahaman tentang bagaimana ETF spot sebenarnya menciptakan dan menebus unit penyertaan. Arus masuk atau keluar bersih harian terjadi ketika peserta resmi (AP) menciptakan unit baru atau menebus unit yang ada untuk menyesuaikan dengan permintaan riil — dan aktivitas ini biasanya digerakkan oleh segelintir institusi dan pembuat pasar, bukan investor ritel yang bertransaksi dalam skala kecil. Ketika aliran dana terkonsentrasi pada satu penerbit, itu adalah sinyal bahwa hal itu mungkin mencerminkan penyesuaian posisi oleh sedikit peserta, bukan pergeseran arah pasar yang luas. Memang, $4,41 juta dari $6,78 juta arus masuk hari itu — sekitar 65% — berasal dari Bitwise saja.</p>
<p class="pl">Zrozumienie mechanizmu stojącego za tym odwróceniem wymaga przyjrzenia się temu, jak ETF-y spot faktycznie tworzą i umarzają jednostki. Dzienne napływy lub odpływy netto zachodzą, gdy autoryzowani uczestnicy (AP) tworzą nowe jednostki lub umarzają istniejące, aby dopasować się do rzeczywistego popytu — a ta aktywność jest zazwyczaj napędzana przez garstkę instytucji i animatorów rynku, a nie inwestorów detalicznych handlujących w małej skali. Gdy przepływy koncentrują się u jednego emitenta, to sygnał, że może to odzwierciedlać dostosowanie pozycji przez kilku uczestników, a nie szeroką zmianę kierunku rynku. Rzeczywiście, 4,41 mln USD z dziennego napływu 6,78 mln USD — około 65% — pochodziło wyłącznie od Bitwise.</p>
<p class="it">Per capire il meccanismo alla base di questa inversione bisogna guardare a come gli ETF spot creano e rimborsano effettivamente le quote. Gli afflussi o deflussi netti giornalieri si verificano quando i partecipanti autorizzati (AP) creano nuove quote o rimborsano quelle esistenti per adeguarsi alla domanda reale — e questa attività è tipicamente guidata da una manciata di istituzioni e market maker, non da investitori retail che negoziano in piccola scala. Quando i flussi si concentrano in un singolo emittente, è un segnale che potrebbe riflettere l'aggiustamento di posizione di pochi partecipanti piuttosto che un ampio cambiamento di direzione del mercato. Infatti, 4,41 milioni di dollari dei 6,78 milioni di afflusso giornaliero — circa il 65% — sono arrivati solo da Bitwise.</p>
<p class="ru">Чтобы понять механизм этого разворота, нужно посмотреть, как спотовые ETF на самом деле создают и погашают паи. Дневные чистые притоки или оттоки происходят, когда уполномоченные участники (AP) создают новые паи или погашают существующие в соответствии с реальным спросом — и эта активность обычно обеспечивается горсткой институтов и маркет-мейкеров, а не розничными инвесторами, торгующими небольшими объёмами. Когда потоки концентрируются у одного эмитента, это сигнал, что это может отражать корректировку позиций несколькими участниками, а не широкий разворот направления рынка. Действительно, 4,41 млн долларов из 6,78 млн долларов дневного притока — около 65% — пришлось только на Bitwise.</p>
<p class="zh">要理解這次逆轉背後的機制,需要了解現貨ETF實際上如何進行申購與贖回。每日淨流入或流出,是授權參與者(AP)為配合實際需求而創設新單位或贖回既有單位所產生的,而這類操作通常由少數機構與造市商主導,而非小額散戶交易。當資金流向集中在單一發行商時,這便是一個訊號,顯示這可能只是少數參與者調整部位,而非市場方向的廣泛轉變。事實上,當日678萬美元流入中有441萬美元(約65%)僅來自比特懷斯一家。</p>

<div class="ko en ja es de fr pt tr vi id pl it ru zh">
<svg viewBox="0 0 700 340" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;background:#111113;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:20px 0">
  <line x1="60" y1="170" x2="640" y2="170" stroke="#3f3f46" stroke-width="2"/>
  <rect x="140" y="170" width="90" height="86" fill="#ef4444" rx="4"/><text x="185" y="278" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">7/9</text><text x="185" y="160" fill="#ef4444" font-size="16" font-weight="700" text-anchor="middle" font-family="sans-serif">-$7.29M</text>
  <rect x="470" y="84" width="90" height="86" fill="#22c55e" rx="4"/><text x="515" y="278" fill="#a1a1aa" font-size="13" text-anchor="middle" font-family="sans-serif">7/16</text><text x="515" y="74" fill="#22c55e" font-size="16" font-weight="700" text-anchor="middle" font-family="sans-serif">+$6.78M</text>
  <rect x="470" y="300" width="66" height="14" fill="#22c55e" rx="2"/><text x="545" y="311" fill="#e4e4e7" font-size="12" font-family="sans-serif">$4.41M (65%)</text>
  <rect x="470" y="318" width="36" height="14" fill="#38bdf8" rx="2"/><text x="515" y="329" fill="#e4e4e7" font-size="12" font-family="sans-serif">$2.38M (35%)</text>
</svg>
</div>

<h2 class="ko">숫자 이면 — 누적 유입 순위와 실제 보유자산 순위가 다른 이유</h2>
<h2 class="en">Behind the Numbers — Why Cumulative Inflow Rank Differs from AUM Rank</h2>
<h2 class="ja">数字の裏側 — 累積流入順位と現在の運用資産順位が異なる理由</h2>
<h2 class="es">Detrás de las Cifras — Por Qué el Ranking de Entradas Acumuladas Difiere del Ranking de AUM</h2>
<h2 class="de">Hinter den Zahlen — Warum der Rang bei den Kumulierten Zuflüssen vom AUM-Rang Abweicht</h2>
<h2 class="fr">Derrière les Chiffres — Pourquoi le Classement des Entrées Cumulées Diffère de Celui des Actifs Sous Gestion</h2>
<h2 class="pt">Por Trás dos Números — Por Que o Ranking de Entradas Acumuladas Difere do Ranking de Patrimônio Sob Gestão</h2>
<h2 class="tr">Rakamların Ardında — Kümülatif Giriş Sıralaması Neden Yönetilen Varlık Sıralamasından Farklı</h2>
<h2 class="vi">Đằng Sau Những Con Số — Vì Sao Thứ Hạng Dòng Vốn Lũy Kế Khác Với Thứ Hạng Tài Sản Quản Lý</h2>
<h2 class="id">Di Balik Angka — Mengapa Peringkat Arus Masuk Kumulatif Berbeda dari Peringkat AUM</h2>
<h2 class="pl">Za Liczbami — Dlaczego Ranking Skumulowanych Napływów Różni się od Rankingu Aktywów pod Zarządzaniem</h2>
<h2 class="it">Dietro i Numeri — Perché la Classifica degli Afflussi Cumulativi Differisce da Quella del Patrimonio Gestito</h2>
<h2 class="ru">За Цифрами — Почему Рейтинг по Совокупному Притоку Отличается от Рейтинга по Активам под Управлением</h2>
<h2 class="zh">數字背後——為何累計流入排名與實際資產管理規模排名不同</h2>

<p class="ko">발행사별 누적 순유입은 비트와이즈가 4억9,827만달러로 1위, 캐너리가 4억6,697만달러로 2위, 프랭클린이 4억1,561만달러로 3위다. 그런데 현재 보유자산(AUM) 기준으로는 비트와이즈가 3억1,282만달러로 여전히 1위이지만, 캐너리의 XRPC(2억5,320만달러)와 프랭클린의 XRPZ(2억5,215만달러)가 그 뒤를 바짝 좇고 있다. 누적 유입액과 현재 AUM 사이의 이 격차는, 초기에 많이 유입됐던 자금 중 일부가 이후 가격 하락이나 부분 환매로 빠져나갔다는 뜻이다. 즉 '역대 가장 많이 벌어들인 ETF'와 '지금 가장 많은 돈을 담고 있는 ETF'가 반드시 같지 않다는 것이다.</p>
<p class="en">By cumulative net inflows since launch, Bitwise leads at $498.27 million, followed by Canary at $466.97 million and Franklin at $415.61 million. But by current assets under management, Bitwise still leads at $312.82 million — while Canary's XRPC ($253.20 million) and Franklin's XRPZ ($252.15 million) trail closely behind. The gap between cumulative inflows and current AUM means some of the money that flowed in earlier has since left, whether through price depreciation or partial redemptions. In other words, the fund that has taken in the most money over its lifetime isn't necessarily the fund holding the most money right now.</p>
<p class="ja">発行会社別の累積純流入額は、ビットワイズが4億9,827万ドルで1位、キャナリーが4億6,697万ドルで2位、フランクリンが4億1,561万ドルで3位だ。しかし現在の運用資産(AUM)ベースでは、ビットワイズが3億1,282万ドルで依然として1位だが、キャナリーのXRPC(2億5,320万ドル)とフランクリンのXRPZ(2億5,215万ドル)がすぐ後ろに迫っている。累積流入額と現在のAUMとのこの差は、初期に多く流入した資金の一部がその後、価格下落や部分的な償還によって流出したことを意味する。つまり、「これまでで最も多くを稼いだETF」と「現在最も多くの資金を保有するETF」は必ずしも同じではないということだ。</p>
<p class="es">Por entradas netas acumuladas desde el lanzamiento, Bitwise lidera con $498.27 millones, seguido de Canary con $466.97 millones y Franklin con $415.61 millones. Pero por activos bajo gestión (AUM) actuales, Bitwise sigue liderando con $312.82 millones, mientras que el XRPC de Canary ($253.20 millones) y el XRPZ de Franklin ($252.15 millones) le siguen de cerca. La brecha entre las entradas acumuladas y el AUM actual significa que parte del dinero que entró antes ha salido desde entonces, ya sea por depreciación de precio o por canjes parciales. En otras palabras, el fondo que más dinero ha captado a lo largo de su vida no es necesariamente el fondo que más dinero tiene ahora mismo.</p>
<p class="de">Nach kumulierten Nettozuflüssen seit Auflegung führt Bitwise mit 498,27 Millionen Dollar, gefolgt von Canary mit 466,97 Millionen Dollar und Franklin mit 415,61 Millionen Dollar. Nach aktuell verwaltetem Vermögen (AUM) führt jedoch weiterhin Bitwise mit 312,82 Millionen Dollar — während Canarys XRPC (253,20 Millionen Dollar) und Franklins XRPZ (252,15 Millionen Dollar) dicht dahinter liegen. Die Lücke zwischen kumulierten Zuflüssen und aktuellem AUM bedeutet, dass ein Teil des zuvor eingeflossenen Geldes seither abgeflossen ist, sei es durch Preisrückgang oder teilweise Rücknahmen. Mit anderen Worten: Der Fonds, der über seine Lebensdauer das meiste Geld eingesammelt hat, ist nicht zwangsläufig der Fonds, der gerade jetzt das meiste Geld hält.</p>
<p class="fr">En entrées nettes cumulées depuis le lancement, Bitwise mène avec 498,27 millions de dollars, suivi de Canary avec 466,97 millions et de Franklin avec 415,61 millions. Mais en actifs sous gestion (AUM) actuels, Bitwise mène toujours avec 312,82 millions de dollars — tandis que le XRPC de Canary (253,20 millions) et le XRPZ de Franklin (252,15 millions) suivent de près. L'écart entre les entrées cumulées et l'AUM actuel signifie qu'une partie de l'argent entré plus tôt en est ressortie depuis, que ce soit par dépréciation du prix ou par rachats partiels. Autrement dit, le fonds qui a collecté le plus d'argent au cours de sa vie n'est pas forcément celui qui détient le plus d'argent à l'heure actuelle.</p>
<p class="pt">Por entradas líquidas acumuladas desde o lançamento, a Bitwise lidera com US$ 498,27 milhões, seguida pela Canary com US$ 466,97 milhões e pela Franklin com US$ 415,61 milhões. Mas por patrimônio sob gestão (AUM) atual, a Bitwise ainda lidera com US$ 312,82 milhões — enquanto o XRPC da Canary (US$ 253,20 milhões) e o XRPZ da Franklin (US$ 252,15 milhões) seguem logo atrás. A diferença entre as entradas acumuladas e o AUM atual significa que parte do dinheiro que entrou antes já saiu, seja por depreciação de preço ou resgates parciais. Em outras palavras, o fundo que mais captou dinheiro ao longo de sua existência não é necessariamente o fundo que detém mais dinheiro agora.</p>
<p class="tr">Lansmandan bu yana kümülatif net girişlere göre Bitwise 498,27 milyon dolarla önde, onu 466,97 milyon dolarla Canary ve 415,61 milyon dolarla Franklin izliyor. Ancak mevcut yönetilen varlıklara (AUM) göre Bitwise 312,82 milyon dolarla hâlâ önde — Canary'nin XRPC'si (253,20 milyon dolar) ve Franklin'in XRPZ'si (252,15 milyon dolar) hemen arkasından geliyor. Kümülatif girişler ile mevcut AUM arasındaki bu fark, daha önce giren paranın bir kısmının, fiyat düşüşü veya kısmi geri alımlar yoluyla o zamandan bu yana çıktığı anlamına geliyor. Başka bir deyişle, ömrü boyunca en çok para toplayan fon, şu anda en çok parayı elinde tutan fon olmak zorunda değil.</p>
<p class="vi">Xét theo dòng vốn ròng lũy kế kể từ khi ra mắt, Bitwise dẫn đầu với 498,27 triệu đô la, tiếp theo là Canary với 466,97 triệu đô la và Franklin với 415,61 triệu đô la. Nhưng xét theo tài sản đang quản lý (AUM) hiện tại, Bitwise vẫn dẫn đầu với 312,82 triệu đô la — trong khi XRPC của Canary (253,20 triệu đô la) và XRPZ của Franklin (252,15 triệu đô la) bám sát phía sau. Khoảng cách giữa dòng vốn lũy kế và AUM hiện tại có nghĩa là một phần tiền đã chảy vào trước đó nay đã rút ra, dù là do giá giảm hay do các đợt mua lại một phần. Nói cách khác, quỹ đã thu hút được nhiều tiền nhất trong suốt vòng đời của nó không nhất thiết là quỹ đang nắm giữ nhiều tiền nhất ngay bây giờ.</p>
<p class="id">Berdasarkan arus masuk bersih kumulatif sejak diluncurkan, Bitwise memimpin dengan $498,27 juta, diikuti Canary dengan $466,97 juta dan Franklin dengan $415,61 juta. Namun berdasarkan aset yang dikelola (AUM) saat ini, Bitwise masih memimpin dengan $312,82 juta — sementara XRPC milik Canary ($253,20 juta) dan XRPZ milik Franklin ($252,15 juta) mengikuti dengan ketat di belakangnya. Kesenjangan antara arus masuk kumulatif dan AUM saat ini berarti sebagian uang yang mengalir masuk sebelumnya telah keluar sejak itu, baik karena penurunan harga maupun penebusan sebagian. Dengan kata lain, dana yang telah mengumpulkan uang paling banyak sepanjang masa hidupnya belum tentu menjadi dana yang memegang uang paling banyak saat ini.</p>
<p class="pl">Pod względem skumulowanych napływów netto od momentu uruchomienia, Bitwise przoduje z 498,27 mln USD, za nim plasuje się Canary z 466,97 mln USD i Franklin z 415,61 mln USD. Jednak pod względem obecnych aktywów pod zarządzaniem (AUM) Bitwise wciąż przoduje z 312,82 mln USD — podczas gdy XRPC od Canary (253,20 mln USD) i XRPZ od Franklin (252,15 mln USD) podążają tuż za nim. Różnica między skumulowanymi napływami a obecnym AUM oznacza, że część pieniędzy, które napłynęły wcześniej, od tego czasu odpłynęła, czy to przez spadek ceny, czy częściowe umorzenia. Innymi słowy, fundusz, który zebrał najwięcej pieniędzy w ciągu swojego istnienia, niekoniecznie jest funduszem trzymającym obecnie najwięcej pieniędzy.</p>
<p class="it">In termini di afflussi netti cumulativi dal lancio, Bitwise guida con 498,27 milioni di dollari, seguito da Canary con 466,97 milioni e Franklin con 415,61 milioni. Ma in termini di patrimonio in gestione (AUM) attuale, Bitwise guida ancora con 312,82 milioni di dollari — mentre XRPC di Canary (253,20 milioni) e XRPZ di Franklin (252,15 milioni) seguono da vicino. Il divario tra afflussi cumulativi e AUM attuale significa che parte del denaro entrato in precedenza è successivamente uscito, sia per deprezzamento del prezzo sia per rimborsi parziali. In altre parole, il fondo che ha raccolto più denaro nel corso della sua esistenza non è necessariamente il fondo che detiene più denaro in questo momento.</p>
<p class="ru">По совокупному чистому притоку с момента запуска лидирует Bitwise с 498,27 млн долларов, за ним следуют Canary с 466,97 млн долларов и Franklin с 415,61 млн долларов. Но по текущим активам под управлением (AUM) по-прежнему лидирует Bitwise с 312,82 млн долларов — при этом XRPC от Canary (253,20 млн долларов) и XRPZ от Franklin (252,15 млн долларов) следуют вплотную позади. Разрыв между совокупным притоком и текущим AUM означает, что часть денег, поступивших ранее, с тех пор ушла — либо из-за снижения цены, либо из-за частичных погашений. Другими словами, фонд, привлёкший больше всего денег за всё время существования, не обязательно является фондом, держащим больше всего денег прямо сейчас.</p>
<p class="zh">按自推出以來的累計淨流入計算,比特懷斯以4.9827億美元領先,其次是Canary的4.6697億美元與富蘭克林的4.1561億美元。但按目前的資產管理規模(AUM)計算,比特懷斯仍以3.1282億美元領先——而Canary的XRPC(2.532億美元)與富蘭克林的XRPZ(2.5215億美元)則緊隨其後。累計流入與目前AUM之間的落差意味著,早期流入的部分資金後來已經流出,原因可能是價格下跌或部分贖回。換句話說,「史上募集資金最多的ETF」未必就是「目前持有資金最多的ETF」。</p>

<p class="ko">이 시점의 가격 배경도 함께 봐야 한다. 이번 유입이 나온 7월16일 전후로 비트코인과 이더리움은 미국의 대이란 공습과 반도체주 급락 여파로 압박을 받으며 하락세를 보이고 있었다. 이런 배경에서 XRP ETF로만 자금이 순유입됐다는 사실은 낙관론자들에게는 '약세장 속 저가 매수'로 읽힐 수 있다. 그러나 반대로 볼 수도 있다 — 678만달러는 비트코인 현물 ETF의 같은 시기 하루 순유입액(약 7,900만달러)의 10분의 1에도 못 미치는 소액이며, 암호화폐 시장 전체의 하루 거래대금(수백억달러)에 비하면 통계적으로 유의미하다고 보기 어려운 규모다. 방향성 베팅이라기보다 소수 기관의 정기적 리밸런싱일 가능성을 배제할 수 없다.</p>
<p class="en">The price backdrop around this inflow matters too. Around July 16, bitcoin and ether were both under pressure from fresh U.S. strikes on Iran and a global chip-stock selloff. Against that backdrop, bulls could read net inflows into XRP ETFs specifically as "buying the dip" during broader weakness. But the opposite reading is just as available: $6.78 million is less than a tenth of the roughly $79 million spot bitcoin ETFs took in on a comparable day around the same period, and it's a rounding error against the tens of billions of dollars that trade across crypto markets daily. It's hard to rule out that this was routine rebalancing by a small number of institutions rather than a directional bet.</p>
<p class="ja">この流入の時期の価格背景も併せて見る必要がある。7月16日前後、ビットコインとイーサリアムはともに米国のイラン新規空爆と半導体株急落の余波で圧迫を受け、下落基調にあった。こうした背景の中でXRP ETFにのみ資金が純流入したという事実は、強気派には「弱気相場の中での押し目買い」と読める。しかし逆の見方も十分成り立つ — 678万ドルは同時期のビットコイン現物ETFの一日純流入額(約7,900万ドル)の10分の1にも満たない小額であり、暗号資産市場全体の一日取引代金(数百億ドル)と比べれば統計的に有意とは言い難い規模だ。方向性のある賭けというより、少数の機関による定期的なリバランスである可能性を排除できない。</p>
<p class="es">El contexto de precios en torno a esta entrada también importa. Alrededor del 16 de julio, tanto el bitcoin como el ether estaban bajo presión por nuevos ataques de EE.UU. contra Irán y una venta masiva global de acciones de semiconductores. En ese contexto, los optimistas podrían leer las entradas netas específicamente en los ETF de XRP como "comprar la caída" durante una debilidad más amplia. Pero la lectura contraria es igual de plausible: $6.78 millones es menos de una décima parte de los aproximadamente $79 millones que captaron los ETF al contado de bitcoin en un día comparable del mismo período, y es un error de redondeo frente a las decenas de miles de millones de dólares que se negocian a diario en los mercados cripto. No se puede descartar que esto fuera un reequilibrio rutinario de un pequeño número de instituciones en lugar de una apuesta direccional.</p>
<p class="de">Auch der Preishintergrund rund um diesen Zufluss ist relevant. Um den 16. Juli standen Bitcoin und Ether beide unter Druck durch neue US-Angriffe auf den Iran und einen globalen Ausverkauf bei Chip-Aktien. Vor diesem Hintergrund könnten Bullen Nettozuflüsse speziell in XRP-ETFs als "Kauf des Rücksetzers" inmitten breiterer Schwäche lesen. Doch die gegenteilige Lesart ist ebenso plausibel: 6,78 Millionen Dollar sind weniger als ein Zehntel der rund 79 Millionen Dollar, die Spot-Bitcoin-ETFs an einem vergleichbaren Tag im selben Zeitraum einnahmen, und ein Rundungsfehler im Vergleich zu den zig Milliarden Dollar, die täglich an den Kryptomärkten gehandelt werden. Es lässt sich nicht ausschließen, dass dies eine routinemäßige Neugewichtung durch eine kleine Zahl von Institutionen war und keine gerichtete Wette.</p>
<p class="fr">Le contexte des prix autour de cette entrée compte aussi. Vers le 16 juillet, le bitcoin et l'ether étaient tous deux sous pression en raison de nouvelles frappes américaines sur l'Iran et d'une déroute mondiale des valeurs des semi-conducteurs. Dans ce contexte, les haussiers pourraient interpréter les entrées nettes spécifiquement dans les ETF XRP comme un « achat sur repli » pendant une faiblesse plus large. Mais la lecture inverse est tout aussi plausible : 6,78 millions de dollars représentent moins d'un dixième des quelque 79 millions de dollars collectés par les ETF au comptant bitcoin lors d'un jour comparable sur la même période, et c'est une erreur d'arrondi face aux dizaines de milliards de dollars échangés quotidiennement sur les marchés crypto. On ne peut exclure qu'il s'agisse d'un rééquilibrage de routine par un petit nombre d'institutions plutôt que d'un pari directionnel.</p>
<p class="pt">O pano de fundo de preços em torno dessa entrada também importa. Por volta de 16 de julho, tanto o bitcoin quanto o ether estavam sob pressão devido a novos ataques dos EUA ao Irã e a uma liquidação global de ações de semicondutores. Nesse contexto, os otimistas poderiam interpretar as entradas líquidas especificamente nos ETFs de XRP como "comprar na baixa" durante uma fraqueza mais ampla. Mas a leitura oposta é igualmente plausível: US$ 6,78 milhões é menos de um décimo dos cerca de US$ 79 milhões que os ETFs à vista de bitcoin captaram em um dia comparável no mesmo período, e é um erro de arredondamento diante das dezenas de bilhões de dólares negociados diariamente nos mercados cripto. Não se pode descartar que isso tenha sido um rebalanceamento rotineiro por um pequeno número de instituições, em vez de uma aposta direcional.</p>
<p class="tr">Bu girişin çevresindeki fiyat arka planı da önemli. 16 Temmuz civarında, hem bitcoin hem de ether, ABD'nin İran'a yönelik yeni saldırıları ve küresel çip hisseleri satışı nedeniyle baskı altındaydı. Bu arka plana karşı, boğalar özellikle XRP ETF'lerine yönelik net girişleri daha geniş bir zayıflık sırasında 'düşüşü satın almak' olarak okuyabilir. Ancak tam tersi bir okuma da aynı derecede mümkün: 6,78 milyon dolar, spot bitcoin ETF'lerinin aynı dönemde karşılaştırılabilir bir günde topladığı yaklaşık 79 milyon dolarlık rakamın onda birinden az ve kripto piyasalarında günlük işlem gören onlarca milyar dolara kıyasla yuvarlama hatası mertebesinde. Bunun yönlü bir bahis değil, az sayıda kurum tarafından yapılan rutin bir yeniden dengeleme olma olasılığı göz ardı edilemez.</p>
<p class="vi">Bối cảnh giá xung quanh dòng vốn này cũng quan trọng. Khoảng ngày 16/7, cả bitcoin và ether đều chịu áp lực từ các cuộc không kích mới của Mỹ nhằm vào Iran và đợt bán tháo cổ phiếu chip toàn cầu. Trong bối cảnh đó, phe tăng giá có thể diễn giải dòng vốn ròng vào cụ thể là ETF XRP như 'mua vào khi giá giảm' trong bối cảnh yếu đi trên diện rộng. Nhưng cách diễn giải ngược lại cũng hoàn toàn khả dĩ: 6,78 triệu đô la ít hơn một phần mười so với khoảng 79 triệu đô la mà các ETF giao ngay bitcoin thu được trong một ngày tương đương cùng kỳ, và đó chỉ là sai số làm tròn so với hàng chục tỷ đô la giao dịch mỗi ngày trên toàn thị trường tiền mã hóa. Không thể loại trừ khả năng đây chỉ là hoạt động tái cân bằng thường lệ của một số ít tổ chức, chứ không phải một cược có định hướng.</p>
<p class="id">Latar belakang harga di sekitar arus masuk ini juga penting. Sekitar 16 Juli, bitcoin dan ether sama-sama tertekan oleh serangan baru AS terhadap Iran dan aksi jual saham chip global. Dengan latar belakang itu, kalangan bullish bisa membaca arus masuk bersih khusus ke ETF XRP sebagai 'membeli saat harga turun' di tengah pelemahan yang lebih luas. Namun tafsiran sebaliknya juga sama mungkinnya: $6,78 juta kurang dari sepersepuluh dari sekitar $79 juta yang diraih ETF spot bitcoin pada hari yang sebanding di periode yang sama, dan itu adalah kesalahan pembulatan dibandingkan puluhan miliar dolar yang diperdagangkan di pasar kripto setiap hari. Sulit untuk menyingkirkan kemungkinan bahwa ini adalah penyeimbangan ulang rutin oleh sejumlah kecil institusi, bukan taruhan terarah.</p>
<p class="pl">Kontekst cenowy wokół tego napływu również ma znaczenie. Około 16 lipca zarówno bitcoin, jak i ether znajdowały się pod presją nowych amerykańskich uderzeń na Iran oraz globalnej wyprzedaży akcji spółek chipowych. Na tym tle byki mogłyby odczytać napływy netto konkretnie do ETF-ów XRP jako „kupowanie spadku" w czasie szerszej słabości. Ale odwrotna interpretacja jest równie dostępna: 6,78 mln USD to mniej niż jedna dziesiąta z około 79 mln USD, jakie ETF-y spot na bitcoina zebrały w porównywalnym dniu tego samego okresu, i to błąd zaokrąglenia w porównaniu z dziesiątkami miliardów dolarów, którymi handluje się codziennie na rynkach kryptowalut. Nie można wykluczyć, że było to rutynowe rebalansowanie przez niewielką liczbę instytucji, a nie zakład kierunkowy.</p>
<p class="it">Anche il contesto dei prezzi attorno a questo afflusso è importante. Intorno al 16 luglio, sia bitcoin sia ether erano sotto pressione a causa dei nuovi attacchi statunitensi contro l'Iran e di una svendita globale dei titoli dei semiconduttori. In questo contesto, i rialzisti potrebbero leggere gli afflussi netti specificamente negli ETF su XRP come un "comprare sul ribasso" durante una debolezza più ampia. Ma la lettura opposta è altrettanto plausibile: 6,78 milioni di dollari sono meno di un decimo dei circa 79 milioni di dollari raccolti dagli ETF spot su bitcoin in un giorno comparabile nello stesso periodo, ed è un errore di arrotondamento rispetto alle decine di miliardi di dollari scambiati quotidianamente sui mercati cripto. Non si può escludere che si sia trattato di un ribilanciamento di routine da parte di un piccolo numero di istituzioni piuttosto che di una scommessa direzionale.</p>
<p class="ru">Ценовой фон вокруг этого притока также важен. Примерно 16 июля и биткоин, и эфир были под давлением из-за новых ударов США по Ирану и глобальной распродажи акций производителей чипов. На этом фоне быки могли бы прочитать чистые притоки именно в XRP ETF как «покупку на просадке» на фоне общей слабости. Но противоположная трактовка столь же правдоподобна: 6,78 млн долларов — это меньше десятой части примерно 79 млн долларов, которые спотовые биткоин-ETF привлекли в сопоставимый день того же периода, и это статистическая погрешность на фоне десятков миллиардов долларов, торгуемых ежедневно на криптовалютных рынках. Нельзя исключить, что это было рутинное перебалансирование небольшого числа институтов, а не направленная ставка.</p>
<p class="zh">這波流入前後的價格背景同樣值得關注。7月16日前後,比特幣與以太幣雙雙受到美國新一輪對伊朗空襲及全球晶片股拋售的衝擊而承壓下跌。在這樣的背景下,多頭可能將資金唯獨淨流入XRP ETF解讀為「逢低買進」。但反向解讀同樣站得住腳——678萬美元不到同期比特幣現貨ETF單日淨流入(約7900萬美元)的十分之一,相對於加密貨幣市場每日數百億美元的交易額而言,更是統計上難稱顯著的零頭。很難排除這只是少數機構例行性的部位再平衡,而非方向性押注的可能性。</p>

<h2 class="ko">지켜볼 점</h2>
<h2 class="en">What to Watch</h2>
<h2 class="ja">見ておくべき点</h2>
<h2 class="es">Qué Vigilar</h2>
<h2 class="de">Worauf zu Achten Ist</h2>
<h2 class="fr">Ce qu'il Faut Surveiller</h2>
<h2 class="pt">O Que Observar</h2>
<h2 class="tr">İzlenmesi Gerekenler</h2>
<h2 class="vi">Những Điều Cần Theo Dõi</h2>
<h2 class="id">Yang Perlu Diperhatikan</h2>
<h2 class="pl">Na Co Zwrócić Uwagę</h2>
<h2 class="it">Cosa Osservare</h2>
<h2 class="ru">На Что Обратить Внимание</h2>
<h2 class="zh">值得關注之處</h2>

<p class="ko">첫째는 이 반등이 새로운 연속 유입 흐름의 시작인지, 아니면 하루짜리 반등에 그치는지다. 앞서 9주 연속 유입 기록도 결국 단 하루의 유출로 깨졌던 것처럼, ETF 자금 흐름은 하루 단위로 방향이 쉽게 뒤집힐 수 있다. 다음 주 누적 데이터가 다시 유입 쪽으로 이어지는지, 아니면 곧바로 유출로 돌아서는지를 봐야 진짜 추세인지 판단할 수 있다.</p>
<p class="en">The first thing to watch is whether this rebound marks the start of a new inflow streak or is just a one-day bounce. The nine-week streak that preceded it, after all, was broken by a single day of outflows — a reminder that ETF flow direction can flip on a daily basis. Whether next week's cumulative data keeps tilting toward inflows, or swings straight back to outflows, will tell us whether this is a real trend or noise.</p>
<p class="ja">まず注目すべきは、この反発が新たな連続流入の始まりなのか、それとも一日限りの反発にとどまるのかだ。先立つ9週連続の流入記録も、結局はたった一日の流出で破られたように、ETFの資金フローは日単位で方向が容易に反転しうる。来週の累積データが再び流入方向に傾き続けるのか、それとも即座に流出に転じるのかを見て初めて、これが本物のトレンドなのかノイズなのかを判断できる。</p>
<p class="es">Lo primero a vigilar es si este repunte marca el inicio de una nueva racha de entradas o es solo un rebote de un día. Al fin y al cabo, la racha de nueve semanas que lo precedió se rompió por un solo día de salidas, un recordatorio de que la dirección del flujo de los ETF puede invertirse a diario. Si los datos acumulados de la próxima semana siguen inclinándose hacia las entradas, o vuelven directamente a las salidas, nos dirá si esto es una tendencia real o solo ruido.</p>
<p class="de">Das Erste, worauf zu achten ist, ist, ob diese Erholung den Beginn einer neuen Zuflussserie markiert oder nur ein eintägiger Ausschlag ist. Die vorangegangene neunwöchige Serie wurde schließlich durch einen einzigen Tag mit Abflüssen gebrochen — eine Erinnerung daran, dass sich die Richtung der ETF-Flüsse täglich umkehren kann. Ob sich die kumulierten Daten der kommenden Woche weiter Richtung Zuflüsse neigen oder direkt wieder zu Abflüssen zurückkehren, wird zeigen, ob dies ein echter Trend oder nur Rauschen ist.</p>
<p class="fr">La première chose à surveiller est de savoir si ce rebond marque le début d'une nouvelle série d'entrées ou n'est qu'un sursaut d'un jour. La série de neuf semaines qui l'a précédé a, après tout, été brisée par une seule journée de sorties — un rappel que la direction des flux ETF peut basculer d'un jour à l'autre. Que les données cumulées de la semaine prochaine continuent de pencher vers les entrées, ou reviennent directement aux sorties, nous dira s'il s'agit d'une tendance réelle ou d'un simple bruit.</p>
<p class="pt">A primeira coisa a observar é se essa recuperação marca o início de uma nova sequência de entradas ou é apenas um salto de um dia. Afinal, a sequência de nove semanas que a precedeu foi rompida por um único dia de saídas — um lembrete de que a direção do fluxo de ETFs pode se inverter diariamente. Se os dados acumulados da próxima semana continuarem inclinando para entradas, ou voltarem direto para saídas, isso nos dirá se isso é uma tendência real ou apenas ruído.</p>
<p class="tr">İlk dikkat edilmesi gereken şey, bu toparlanmanın yeni bir giriş serisinin başlangıcı mı yoksa yalnızca tek günlük bir sıçrama mı olduğu. Sonuçta ondan önceki dokuz haftalık seri de tek bir günlük çıkışla kırılmıştı — bu da ETF akış yönünün günlük bazda tersine dönebileceğinin bir hatırlatıcısı. Gelecek haftanın kümülatif verilerinin girişlere doğru eğilmeye devam edip etmeyeceği, yoksa doğrudan çıkışlara mı döneceği, bunun gerçek bir eğilim mi yoksa gürültü mü olduğunu bize söyleyecek.</p>
<p class="vi">Điều đầu tiên cần theo dõi là liệu đà phục hồi này đánh dấu sự khởi đầu của một chuỗi dòng vốn vào mới hay chỉ là một cú bật một ngày. Xét cho cùng, chuỗi 9 tuần trước đó cũng đã bị phá vỡ bởi chỉ một ngày dòng vốn ra — một lời nhắc nhở rằng hướng dòng vốn ETF có thể đảo chiều theo từng ngày. Việc dữ liệu lũy kế của tuần tới tiếp tục nghiêng về dòng vốn vào, hay quay ngoắt trở lại dòng vốn ra, sẽ cho biết đây là một xu hướng thực sự hay chỉ là nhiễu.</p>
<p class="id">Hal pertama yang perlu diperhatikan adalah apakah kebangkitan ini menandai awal dari rentetan arus masuk baru atau hanya lonjakan satu hari. Bagaimanapun, rentetan sembilan minggu sebelumnya akhirnya terputus oleh arus keluar hanya dalam satu hari — pengingat bahwa arah aliran ETF bisa berbalik setiap hari. Apakah data kumulatif minggu depan terus condong ke arus masuk, atau langsung berbalik ke arus keluar, akan memberi tahu kita apakah ini tren nyata atau sekadar noise.</p>
<p class="pl">Pierwszą rzeczą, na którą warto zwrócić uwagę, jest to, czy to odbicie oznacza początek nowej serii napływów, czy jest tylko jednodniowym odbiciem. W końcu poprzedzająca je dziewięciotygodniowa seria została przerwana przez zaledwie jeden dzień odpływów — przypomnienie, że kierunek przepływów ETF może odwrócić się z dnia na dzień. To, czy skumulowane dane z przyszłego tygodnia będą nadal skłaniać się ku napływom, czy od razu wrócą do odpływów, pokaże nam, czy jest to prawdziwy trend, czy tylko szum.</p>
<p class="it">La prima cosa da osservare è se questo rimbalzo segni l'inizio di una nuova serie di afflussi o sia solo un rimbalzo di un giorno. Dopotutto, la serie di nove settimane che l'ha preceduto è stata interrotta da un solo giorno di deflussi — un promemoria che la direzione dei flussi ETF può ribaltarsi su base giornaliera. Se i dati cumulativi della prossima settimana continueranno a pendere verso gli afflussi, o torneranno subito ai deflussi, ci dirà se si tratta di una tendenza reale o solo di rumore.</p>
<p class="ru">Первое, на что стоит обратить внимание, — знаменует ли это восстановление начало новой серии притоков или это лишь однодневный отскок. В конце концов, предшествовавшая девятинедельная серия была прервана всего одним днём оттоков — напоминание о том, что направление потоков ETF может разворачиваться ежедневно. Будут ли совокупные данные следующей недели по-прежнему склоняться к притокам или сразу же вернутся к оттокам, покажет, реальный ли это тренд или просто шум.</p>
<p class="zh">首先要關注的是,這波反彈究竟是新一輪連續流入的開端,還是僅僅曇花一現的單日反彈。畢竟先前那連續9週的紀錄,最終也是被單單一天的流出所打破——這提醒我們ETF資金流向可以逐日翻轉。下週的累計數據是繼續傾向流入,還是立刻轉回流出,將能告訴我們這究竟是真實趨勢還是雜訊。</p>

<p class="ko">둘째는 자산군 간 비교다. 같은 기간 비트코인 현물 ETF는 약 7,900만달러의 완만한 순유입을 기록했는데, 규모 면에서는 XRP ETF의 678만달러보다 훨씬 크지만, 두 자산의 시가총액 대비 비중으로 보면 이야기가 달라질 수 있다. 만약 앞으로 몇 주간 비트코인·이더리움 ETF는 유출입이 둔화되는 반면 XRP ETF만 꾸준한 유입을 이어간다면, 이는 개별 자산으로의 자금 로테이션 신호로 해석할 근거가 쌓이는 셈이다. 반대로 XRP ETF 유입도 함께 잦아든다면, 이번 반등은 앞서 지적한 대로 소수 기관의 일시적 포지션 조정이었을 가능성에 무게가 실린다.</p>
<p class="en">The second is how this compares across asset classes. Spot bitcoin ETFs took in a milder roughly $79 million over the same period — larger in absolute terms than XRP ETFs' $6.78 million, but the picture could look different measured against each asset's market capitalization. If bitcoin and ether ETF flows keep cooling over the coming weeks while XRP ETFs keep drawing steady inflows, that would build a case for genuine rotation into the individual asset. If XRP ETF inflows fade just as quickly instead, it would support the read that this rebound was, as noted above, a temporary position adjustment by a small number of institutions.</p>
<p class="ja">第二は、資産クラス間での比較だ。同時期にビットコイン現物ETFは約7,900万ドルの緩やかな純流入を記録した。金額の絶対値ではXRP ETFの678万ドルよりはるかに大きいが、それぞれの資産の時価総額に対する比率で見ると話は変わってくる可能性がある。もし今後数週間、ビットコイン・イーサリアムETFの流出入が鈍化する一方でXRP ETFだけが着実な流入を続けるなら、これは個別資産への資金ローテーションのシグナルと解釈する根拠が積み上がることになる。逆にXRP ETFの流入も同様に急速に萎めば、今回の反発は前述の通り、少数機関による一時的なポジション調整だった可能性に重みが置かれる。</p>
<p class="es">El segundo punto es cómo se compara esto entre clases de activos. Los ETF al contado de bitcoin captaron unos moderados $79 millones en el mismo período —mayor en términos absolutos que los $6.78 millones de los ETF de XRP—, pero el panorama podría verse diferente medido frente a la capitalización de mercado de cada activo. Si los flujos de los ETF de bitcoin y ether siguen enfriándose en las próximas semanas mientras los ETF de XRP siguen atrayendo entradas constantes, eso reforzaría la tesis de una rotación genuina hacia ese activo individual. Si, por el contrario, las entradas de los ETF de XRP se desvanecen igual de rápido, respaldaría la lectura de que este repunte fue, como se señaló antes, un ajuste temporal de posiciones por parte de un pequeño número de instituciones.</p>
<p class="de">Zweitens ist der Vergleich über Anlageklassen hinweg zu beobachten. Spot-Bitcoin-ETFs nahmen im gleichen Zeitraum moderate rund 79 Millionen Dollar ein — in absoluten Zahlen größer als die 6,78 Millionen Dollar der XRP-ETFs, doch das Bild könnte sich anders darstellen, gemessen an der Marktkapitalisierung jedes Assets. Wenn sich die Flüsse bei Bitcoin- und Ether-ETFs in den kommenden Wochen weiter abkühlen, während XRP-ETFs weiterhin stetige Zuflüsse verzeichnen, würde das die These einer echten Rotation in dieses einzelne Asset stärken. Verpuffen die XRP-ETF-Zuflüsse stattdessen ebenso schnell, würde das die oben genannte Lesart stützen, dass diese Erholung eine vorübergehende Positionsanpassung durch eine kleine Zahl von Institutionen war.</p>
<p class="fr">Le deuxième point est la comparaison entre classes d'actifs. Les ETF au comptant bitcoin ont collecté environ 79 millions de dollars, plus modestes, sur la même période — plus important en termes absolus que les 6,78 millions de dollars des ETF XRP, mais le tableau pourrait sembler différent rapporté à la capitalisation boursière de chaque actif. Si les flux des ETF bitcoin et ether continuent de refroidir dans les semaines à venir tandis que les ETF XRP continuent d'attirer des entrées régulières, cela renforcerait la thèse d'une véritable rotation vers cet actif particulier. Si au contraire les entrées des ETF XRP s'estompent tout aussi vite, cela conforterait la lecture selon laquelle ce rebond était, comme indiqué plus haut, un ajustement de position temporaire par un petit nombre d'institutions.</p>
<p class="pt">O segundo ponto é como isso se compara entre classes de ativos. Os ETFs à vista de bitcoin captaram cerca de US$ 79 milhões, mais modestos, no mesmo período — maior em termos absolutos que os US$ 6,78 milhões dos ETFs de XRP, mas o quadro poderia parecer diferente medido em relação à capitalização de mercado de cada ativo. Se os fluxos dos ETFs de bitcoin e ether continuarem esfriando nas próximas semanas enquanto os ETFs de XRP continuarem atraindo entradas constantes, isso reforçaria a tese de uma rotação genuína para esse ativo individual. Se, ao contrário, as entradas do ETF de XRP diminuírem igualmente rápido, isso apoiaria a leitura de que essa recuperação foi, como observado acima, um ajuste temporário de posição por um pequeno número de instituições.</p>
<p class="tr">İkincisi, bunun varlık sınıfları arasında nasıl karşılaştırıldığı. Spot bitcoin ETF'leri aynı dönemde daha ılımlı, yaklaşık 79 milyon dolar topladı — mutlak rakamlarla XRP ETF'lerinin 6,78 milyon dolarından daha büyük, ancak her varlığın piyasa değerine göre ölçüldüğünde tablo farklı görünebilir. Önümüzdeki haftalarda bitcoin ve ether ETF akışları soğumaya devam ederken XRP ETF'leri istikrarlı girişler çekmeye devam ederse, bu bireysel varlığa gerçek bir rotasyon tezini güçlendirir. Bunun yerine XRP ETF girişleri de aynı hızla sönerse, bu toparlanmanın yukarıda belirtildiği gibi az sayıda kurum tarafından yapılan geçici bir pozisyon ayarlaması olduğu okumasını destekler.</p>
<p class="vi">Điều thứ hai là so sánh giữa các loại tài sản. Các ETF giao ngay bitcoin thu hút khoảng 79 triệu đô la khiêm tốn hơn trong cùng kỳ — lớn hơn về giá trị tuyệt đối so với 6,78 triệu đô la của ETF XRP, nhưng bức tranh có thể trông khác đi nếu đo theo vốn hóa thị trường của từng tài sản. Nếu dòng vốn ETF bitcoin và ether tiếp tục nguội đi trong những tuần tới trong khi ETF XRP tiếp tục thu hút dòng vốn ổn định, điều đó sẽ củng cố luận điểm về sự luân chuyển thực sự sang tài sản riêng lẻ này. Ngược lại, nếu dòng vốn ETF XRP cũng nhanh chóng phai nhạt, điều đó sẽ ủng hộ cách diễn giải rằng đà phục hồi này, như đã lưu ý ở trên, chỉ là sự điều chỉnh vị thế tạm thời của một số ít tổ chức.</p>
<p class="id">Kedua adalah bagaimana ini dibandingkan antar kelas aset. ETF spot bitcoin meraih sekitar $79 juta yang lebih moderat dalam periode yang sama — lebih besar secara absolut dibandingkan $6,78 juta milik ETF XRP, tetapi gambarannya bisa terlihat berbeda jika diukur terhadap kapitalisasi pasar masing-masing aset. Jika aliran ETF bitcoin dan ether terus mendingin dalam beberapa minggu mendatang sementara ETF XRP terus menarik arus masuk yang stabil, itu akan membangun argumen untuk rotasi sejati ke aset individu tersebut. Jika sebaliknya arus masuk ETF XRP memudar dengan cepat, itu akan mendukung tafsiran bahwa kebangkitan ini, seperti disebutkan di atas, adalah penyesuaian posisi sementara oleh sejumlah kecil institusi.</p>
<p class="pl">Drugą kwestią jest to, jak wypada to porównanie między klasami aktywów. ETF-y spot na bitcoina zebrały w tym samym okresie łagodniejsze, około 79 mln USD — więcej w wartościach bezwzględnych niż 6,78 mln USD ETF-ów XRP, ale obraz mógłby wyglądać inaczej mierzony w stosunku do kapitalizacji rynkowej każdego aktywa. Jeśli przepływy ETF-ów na bitcoina i ethera będą nadal słabnąć w nadchodzących tygodniach, podczas gdy ETF-y XRP będą nadal przyciągać stabilne napływy, wzmocniłoby to tezę o prawdziwej rotacji w kierunku tego pojedynczego aktywa. Jeśli natomiast napływy do ETF XRP osłabną równie szybko, potwierdziłoby to odczyt, że to odbicie było, jak zaznaczono powyżej, tymczasowym dostosowaniem pozycji przez niewielką liczbę instytucji.</p>
<p class="it">Il secondo punto è il confronto tra le classi di asset. Gli ETF spot su bitcoin hanno raccolto circa 79 milioni di dollari, più modesti, nello stesso periodo — maggiore in termini assoluti dei 6,78 milioni di dollari degli ETF XRP, ma il quadro potrebbe apparire diverso se misurato rispetto alla capitalizzazione di mercato di ciascun asset. Se i flussi degli ETF su bitcoin ed ether continueranno a raffreddarsi nelle prossime settimane mentre gli ETF XRP continueranno ad attirare afflussi costanti, ciò rafforzerebbe la tesi di una rotazione genuina verso quel singolo asset. Se invece gli afflussi degli ETF XRP svaniranno altrettanto rapidamente, ciò sosterrebbe la lettura secondo cui questo rimbalzo è stato, come notato sopra, un aggiustamento temporaneo di posizione da parte di un piccolo numero di istituzioni.</p>
<p class="ru">Второе — как это сравнение выглядит между классами активов. Спотовые биткоин-ETF привлекли за тот же период более скромные примерно 79 млн долларов — больше в абсолютном выражении, чем 6,78 млн долларов XRP ETF, но картина может выглядеть иначе, если измерять её относительно рыночной капитализации каждого актива. Если потоки биткоин- и эфир-ETF продолжат охлаждаться в ближайшие недели, а XRP ETF продолжат привлекать стабильные притоки, это укрепит аргумент в пользу подлинной ротации в отдельный актив. Если же притоки в XRP ETF угаснут так же быстро, это подтвердит трактовку о том, что данное восстановление было, как отмечено выше, временной корректировкой позиций небольшим числом институтов.</p>
<p class="zh">第二個看點是跨資產類別的比較。同期比特幣現貨ETF錄得約7900萬美元較為溫和的淨流入,絕對金額遠高於XRP ETF的678萬美元,但若按各自資產的市值比例衡量,情況可能大不相同。若未來幾週比特幣、以太幣ETF的資金流動持續降溫,而XRP ETF卻持續穩定流入,這將為個別資產的資金輪動說法累積更多論據。反之,若XRP ETF的流入同樣迅速消退,則更支持前述觀點:這波反彈只是少數機構的暫時性部位調整。</p>

<div class="box ko">💡 <strong>정리:</strong> 미국 현물 XRP ETF가 7월16일 678만달러 순유입을 기록해 7월 최대 하루 유입액을 새로 썼다. 비트와이즈가 441만달러, 프랭클린이 238만달러를 담당했고 캐너리·21셰어스·그레이스케일은 유입이 없었다. 누적 순유입은 14억9,000만달러, 순자산은 약 9억9,700만달러다. 이는 불과 일주일 전 9주 연속 유입 기록이 깨지며 729만달러 순유출을 기록했던 것과 대비되는 반전이다. 다만 유입액이 소수 발행사에 쏠려 있고 규모 자체도 작아, 방향성 신호로 단정하기보다 다음 주 데이터로 추세 여부를 확인할 필요가 있다.</div>
<div class="box en">💡 <strong>Bottom line:</strong> U.S. spot XRP ETFs posted $6.78 million in net inflows on July 16, the largest single-day figure of July. Bitwise contributed $4.41 million and Franklin $2.38 million, while Canary, 21Shares and Grayscale saw no inflows. Cumulative net inflows stand at $1.49 billion, with net assets around $997.18 million — a sharp reversal from just a week earlier, when a nine-week inflow streak broke with a $7.29 million net outflow. But the inflow is concentrated in a couple of issuers and small in absolute size, so next week's data will matter more than this one day for judging whether it's a real trend.</div>
<div class="box ja">💡 <strong>まとめ:</strong> 米国の現物XRP ETFは7月16日に678万ドルの純流入を記録し、7月の一日流入額として最大となった。ビットワイズが441万ドル、フランクリンが238万ドルを担い、キャナリー・21シェアーズ・グレースケールは流入がなかった。累積純流入は14億9,000万ドル、純資産は約9億9,700万ドルだ。これはわずか1週間前、9週連続の流入記録が途切れ729万ドルの純流出を記録したのとは対照的な反転である。ただし流入額は少数の発行会社に集中しており、規模自体も小さいため、方向性のシグナルと断定するより、来週のデータでトレンドかどうかを確認する必要がある。</div>
<div class="box es">💡 <strong>En resumen:</strong> Los ETF al contado de XRP en EE.UU. registraron $6.78 millones en entradas netas el 16 de julio, la cifra diaria más alta de julio. Bitwise aportó $4.41 millones y Franklin $2.38 millones, mientras que Canary, 21Shares y Grayscale no registraron entradas. Las entradas netas acumuladas se sitúan en $1,490 millones, con activos netos de unos $997.18 millones, un giro brusco respecto a solo una semana antes, cuando una racha de nueve semanas de entradas se rompió con una salida neta de $7.29 millones. Pero la entrada está concentrada en un par de emisores y es pequeña en tamaño absoluto, por lo que los datos de la próxima semana importarán más que este único día para juzgar si es una tendencia real.</div>
<div class="box de">💡 <strong>Fazit:</strong> US-Spot-XRP-ETFs verzeichneten am 16. Juli Nettozuflüsse von 6,78 Millionen Dollar, den höchsten Tageswert im Juli. Bitwise steuerte 4,41 Millionen Dollar bei, Franklin 2,38 Millionen Dollar, während Canary, 21Shares und Grayscale keine Zuflüsse verzeichneten. Die kumulierten Nettozuflüsse liegen bei 1,49 Milliarden Dollar, bei Nettovermögen von rund 997,18 Millionen Dollar — eine scharfe Kehrtwende gegenüber nur einer Woche zuvor, als eine neunwöchige Zuflussserie mit einem Nettoabfluss von 7,29 Millionen Dollar riss. Doch der Zufluss konzentriert sich auf wenige Emittenten und ist absolut klein, sodass die Daten der kommenden Woche wichtiger sein werden als dieser eine Tag, um zu beurteilen, ob es sich um einen echten Trend handelt.</div>
<div class="box fr">💡 <strong>En résumé :</strong> les ETF au comptant XRP américains ont enregistré 6,78 millions de dollars d'entrées nettes le 16 juillet, le chiffre journalier le plus élevé de juillet. Bitwise a contribué à hauteur de 4,41 millions de dollars et Franklin de 2,38 millions, tandis que Canary, 21Shares et Grayscale n'ont enregistré aucune entrée. Les entrées nettes cumulées s'élèvent à 1,49 milliard de dollars, avec des actifs nets d'environ 997,18 millions de dollars — un net revirement par rapport à une semaine plus tôt seulement, lorsqu'une série de neuf semaines d'entrées s'est brisée avec une sortie nette de 7,29 millions de dollars. Mais l'entrée est concentrée chez quelques émetteurs et de petite taille en valeur absolue, donc les données de la semaine prochaine compteront plus que cette seule journée pour juger s'il s'agit d'une tendance réelle.</div>
<div class="box pt">💡 <strong>Resumo:</strong> os ETFs à vista de XRP nos EUA registraram US$ 6,78 milhões em entradas líquidas em 16 de julho, o maior número diário de julho. A Bitwise contribuiu com US$ 4,41 milhões e a Franklin com US$ 2,38 milhões, enquanto Canary, 21Shares e Grayscale não tiveram entradas. As entradas líquidas acumuladas somam US$ 1,49 bilhão, com ativos líquidos de cerca de US$ 997,18 milhões — uma reviravolta acentuada em relação a apenas uma semana antes, quando uma sequência de nove semanas de entradas se rompeu com uma saída líquida de US$ 7,29 milhões. Mas a entrada está concentrada em poucos emissores e é pequena em tamanho absoluto, então os dados da próxima semana importarão mais do que esse único dia para julgar se é uma tendência real.</div>
<div class="box tr">💡 <strong>Özet:</strong> ABD spot XRP ETF'leri 16 Temmuz'da 6,78 milyon dolarlık net girişle Temmuz'un en yüksek günlük rakamını kaydetti. Bitwise 4,41 milyon dolar, Franklin 2,38 milyon dolar katkı sağladı; Canary, 21Shares ve Grayscale'de ise giriş görülmedi. Kümülatif net girişler 1,49 milyar dolara, net varlıklar ise yaklaşık 997,18 milyon dolara ulaştı — bu, yalnızca bir hafta önce dokuz haftalık giriş serisinin 7,29 milyon dolarlık net çıkışla kırılmasının tam tersi keskin bir dönüş. Ancak giriş birkaç ihraççıda yoğunlaşmış ve mutlak büyüklük olarak küçük, bu yüzden gerçek bir eğilim olup olmadığını değerlendirmek için gelecek haftanın verileri bu tek günden daha önemli olacak.</div>
<div class="box vi">💡 <strong>Tóm lại:</strong> Các ETF giao ngay XRP tại Mỹ ghi nhận 6,78 triệu đô la dòng vốn ròng vào ngày 16/7, con số cao nhất trong tháng 7. Bitwise đóng góp 4,41 triệu đô la và Franklin 2,38 triệu đô la, trong khi Canary, 21Shares và Grayscale không có dòng vốn vào. Dòng vốn ròng lũy kế đạt 1,49 tỷ đô la, với tài sản ròng khoảng 997,18 triệu đô la — một sự đảo chiều mạnh so với chỉ một tuần trước đó, khi chuỗi 9 tuần dòng vốn vào bị đứt gãy với dòng vốn ròng ra 7,29 triệu đô la. Nhưng dòng vốn vào tập trung ở một vài tổ chức phát hành và có quy mô tuyệt đối nhỏ, nên dữ liệu tuần tới sẽ quan trọng hơn một ngày này để đánh giá liệu đây có phải là xu hướng thực sự hay không.</div>
<div class="box id">💡 <strong>Ringkasan:</strong> ETF spot XRP AS mencatat arus masuk bersih $6,78 juta pada 16 Juli, angka harian tertinggi bulan Juli. Bitwise menyumbang $4,41 juta dan Franklin $2,38 juta, sementara Canary, 21Shares, dan Grayscale tidak mencatat arus masuk. Arus masuk bersih kumulatif mencapai $1,49 miliar, dengan aset bersih sekitar $997,18 juta — pembalikan tajam dari hanya seminggu sebelumnya, ketika rentetan arus masuk sembilan minggu terputus dengan arus keluar bersih $7,29 juta. Namun arus masuk ini terkonsentrasi pada beberapa penerbit dan kecil dalam ukuran absolut, sehingga data minggu depan akan lebih penting daripada satu hari ini untuk menilai apakah ini tren nyata.</div>
<div class="box pl">💡 <strong>Podsumowanie:</strong> amerykańskie ETF-y spot na XRP odnotowały 16 lipca napływy netto w wysokości 6,78 mln USD, najwyższy dzienny wynik lipca. Bitwise wniósł 4,41 mln USD, a Franklin 2,38 mln USD, podczas gdy Canary, 21Shares i Grayscale nie odnotowały napływów. Skumulowane napływy netto wynoszą 1,49 mld USD, przy aktywach netto na poziomie około 997,18 mln USD — gwałtowny zwrot w porównaniu z zaledwie tygodniem wcześniej, gdy dziewięciotygodniowa seria napływów została przerwana odpływem netto w wysokości 7,29 mln USD. Napływ jest jednak skoncentrowany u kilku emitentów i niewielki w wartościach bezwzględnych, więc dane z przyszłego tygodnia będą ważniejsze niż ten jeden dzień dla oceny, czy to prawdziwy trend.</div>
<div class="box it">💡 <strong>In sintesi:</strong> gli ETF spot su XRP statunitensi hanno registrato 6,78 milioni di dollari di afflussi netti il 16 luglio, il dato giornaliero più alto di luglio. Bitwise ha contribuito con 4,41 milioni di dollari e Franklin con 2,38 milioni, mentre Canary, 21Shares e Grayscale non hanno registrato afflussi. Gli afflussi netti cumulativi si attestano a 1,49 miliardi di dollari, con un patrimonio netto di circa 997,18 milioni di dollari — un'inversione netta rispetto a solo una settimana prima, quando una serie di nove settimane di afflussi si è interrotta con un deflusso netto di 7,29 milioni di dollari. Ma l'afflusso è concentrato in un paio di emittenti ed è di dimensioni assolute contenute, quindi i dati della prossima settimana conteranno più di questo singolo giorno per giudicare se si tratta di una tendenza reale.</div>
<div class="box ru">💡 <strong>Итог:</strong> спотовые XRP ETF в США показали чистый приток в размере 6,78 млн долларов 16 июля — крупнейший дневной показатель июля. Bitwise внёс 4,41 млн долларов, Franklin — 2,38 млн долларов, а у Canary, 21Shares и Grayscale притока не было. Совокупный чистый приток составляет 1,49 млрд долларов при чистых активах около 997,18 млн долларов — резкий разворот по сравнению с ситуацией всего неделей ранее, когда девятинедельная серия притоков прервалась чистым оттоком в 7,29 млн долларов. Но приток сконцентрирован у пары эмитентов и мал в абсолютном выражении, поэтому данные следующей недели будут значить больше, чем этот один день, для оценки того, реальный ли это тренд.</div>
<div class="box zh">💡 <strong>總結:</strong>美國XRP現貨ETF於7月16日錄得678萬美元淨流入,創下7月單日新高。比特懷斯貢獻441萬美元,富蘭克林貢獻238萬美元,Canary、21Shares與Grayscale則無流入。累計淨流入達14.9億美元,淨資產約9.9718億美元——這與僅僅一週前連續9週流入紀錄中斷、單週淨流出729萬美元形成鮮明對比的逆轉。但這筆流入集中在少數幾家發行商身上,絕對規模也小,因此判斷這是否為真實趨勢,下週的數據會比這單一天更具參考價值。</div>

<div class="og-cover" style="display:none"><svg viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <text x="60" y="270" fill="#f4f4f5" font-size="130" font-weight="bold">$6.78M</text>
  <text x="60" y="330" fill="#06b6d4" font-size="42" font-weight="bold">XRP ETF</text>
  <polygon fill="#22c55e" points="640,225 672,270 608,270"/>
  <polyline fill="none" stroke="#ef4444" stroke-width="6" points="60,440 220,510 400,460"/>
  <polyline fill="none" stroke="#22c55e" stroke-width="6" points="400,460 620,340"/>
  <circle cx="620" cy="340" r="12" fill="#22c55e"/>
  <text x="60" y="560" fill="#ef4444" font-size="34" font-weight="bold">-$7.29M</text>
  <polygon fill="#71717a" points="270,535 300,548 270,561"/>
  <text x="320" y="560" fill="#22c55e" font-size="34" font-weight="bold">+$6.78M</text>
  <text x="900" y="230" fill="#f4f4f5" font-size="52" font-weight="bold" text-anchor="middle">$1.49B</text>
  <text x="900" y="270" fill="#71717a" font-size="28" text-anchor="middle">TOTAL</text>
</svg></div>

<p class="ko" style="font-size:12px;color:#52525b;margin-top:24px">출처: 크립토타임스(CryptoTimes), 코인가바르(CoinGabbar), 크립토뉴스닷넷(Cryptonews.net), 호카뉴스(HokaNews), 벤징가(Benzinga), 코인글래스(CoinGlass).</p>
<p class="en" style="font-size:12px;color:#52525b;margin-top:24px">Sources: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="ja" style="font-size:12px;color:#52525b;margin-top:24px">出典: クリプトタイムズ(CryptoTimes)、コインガバー(CoinGabbar)、クリプトニュース・ネット(Cryptonews.net)、ホカニュース(HokaNews)、ベンジンガ(Benzinga)、コイングラス(CoinGlass)。</p>
<p class="es" style="font-size:12px;color:#52525b;margin-top:24px">Fuentes: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="de" style="font-size:12px;color:#52525b;margin-top:24px">Quellen: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="fr" style="font-size:12px;color:#52525b;margin-top:24px">Sources : CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="pt" style="font-size:12px;color:#52525b;margin-top:24px">Fontes: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="tr" style="font-size:12px;color:#52525b;margin-top:24px">Kaynaklar: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="vi" style="font-size:12px;color:#52525b;margin-top:24px">Nguồn: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="id" style="font-size:12px;color:#52525b;margin-top:24px">Sumber: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="pl" style="font-size:12px;color:#52525b;margin-top:24px">Źródła: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="it" style="font-size:12px;color:#52525b;margin-top:24px">Fonti: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="ru" style="font-size:12px;color:#52525b;margin-top:24px">Источники: CryptoTimes, CoinGabbar, Cryptonews.net, HokaNews, Benzinga, CoinGlass.</p>
<p class="zh" style="font-size:12px;color:#52525b;margin-top:24px">資料來源:CryptoTimes、CoinGabbar、Cryptonews.net、HokaNews、Benzinga、CoinGlass。</p>

<?php require __DIR__.'/_footer.php'; ?>
